### ISSUE TITLE
 平台自定义角色文案错误

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1000]
* [x] 平台是应用管理，但自定义角色是应用模版
![Screen Shot 2019-10-15 at 3 00 14 PM](https://user-images.githubusercontent.com/28859385/66807835-88a42800-ef5c-11e9-88cb-fa0ecc2370fb.png)

**Comment by leoendless** [comment]
fixed

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191015
