### ISSUE TITLE
阿里云centos7.6安装all-in-one报错

### ISSUE THREAD

**Issue by cugbzc** [kubesphere/kubesphere#1002]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**：

安装all-in-one报错，按照常见错误问题，我执行了pip install --upgrade setuptools==30.1.0 仍然报相同的错误。
**安装环境的硬件配置**
阿里云Centos7.6.1810，8核32GB，500GB云盘。

**错误信息或截图**
![image](https://user-images.githubusercontent.com/56579138/66808752-76c38480-ef5e-11e9-8b45-8fdfcb9ffd42.png)

**Installer版本**
kubesphere-all-advanced-2.0.2

**Comment by jazzmr** [comment]
![image](https://user-images.githubusercontent.com/5153501/66811465-b8a2f980-ef63-11e9-9a2f-cb22a4665736.png)
我是一直卡住不动啦

**Comment by cugbzc** [comment]
> ![image](https://user-images.githubusercontent.com/5153501/66811465-b8a2f980-ef63-11e9-9a2f-cb22a4665736.png)
> 我是一直卡住不动啦

卡住不动，可能是网速太慢，在下载容器，耐心等吧

**Comment by rayzhou2017** [comment]
如果是网速慢的话就把带宽加大一些，下载完了再改小带宽，带宽影响对安装速度影响很大。

**Comment by 2young2simple** [comment]
> 如果是网速慢的话就把带宽加大一些，下载完了再改小带宽，带宽对安装速度影响很大。

我也是这个问题，100m的网，一晚上下不好，感觉不是这个问题

**Comment by 2young2simple** [comment]
> 如果是网速慢的话就把带宽加大一些，下载完了再改小带宽，带宽对安装速度影响很大。

是否脚本中能够展示正在下载什么镜像，目前是什么速度比较好。

**Comment by 2young2simple** [comment]
> 如果是网速慢的话就把带宽加大一些，下载完了再改小带宽，带宽对安装速度影响很大。

现在无任何提示信息，我不知道是否能够下通，也不知道正在下哪一个镜像，无法确定问题去解决。

**Comment by rayzhou2017** [comment]
100m带宽应该需要一个多小时，你可以看看存储空间是不是在减少。

**Comment by pixiake** [comment]
下载镜像慢的话可以先把镜像包下载到本地导入到机器中，下个版本会展示正在下载的镜像名称。

1. `wget  https://kubesphere-installer.pek3b.qingstor.com/ks-only/kubesphere-images-advanced-2.0.2.tar.gz`
2. `tar -zxvf kubesphere-images-advanced-2.0.2.tar.gz`
3. `docker load < kubesphere-images-advanced-2.0.2.tar`

**Comment by pixiake** [comment]
阿里云遇到的pip问题参考下边连接解决：
https://github.com/kubesphere/ks-installer/issues/23#issuecomment-530720509

**Comment by 2young2simple** [comment]
@pixiake @rayzhou2017   感谢解答！ 我试试。
