### ISSUE TITLE
创建存储卷时，存储卷大小不支持输入

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#1007]
**Describe the bug(描述下问题)**
创建存储卷时，存储卷大小不支持输入

![image](https://user-images.githubusercontent.com/53003665/66813648-b773cb80-ef67-11e9-9620-b77c083252a4.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere:2.1.1

/area console
/kind bug
/milestone 2.1.0

**Comment by leoendless** [comment]
fixed

**Comment by wanjunlei** [comment]
16号的版本，还有这个问题

**Comment by wanjunlei** [comment]
![image](https://user-images.githubusercontent.com/53003665/67935189-49383580-fc04-11e9-9ce5-e9dbcde20804.png)
存储卷的最小值10无法删除，只能在后面追加
