### ISSUE TITLE
企业空间下容器组均运行失败，此企业空间也参与了企业空间资源排行

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1009]
如下图所示，企业空间s2i-test下有1个项目，且项目下有一个容器组，只是运行失败了：
![image](https://user-images.githubusercontent.com/7677050/66818054-4df7bb00-ef6f-11e9-9bfd-c2b99426baee.png)

但该企业空间参与了资源排行，而且容器组数量显示为0：
![image](https://user-images.githubusercontent.com/7677050/66817982-2f91bf80-ef6f-11e9-97b5-fb6c37421fb8.png)

**Comment by mayuhope** [comment]
/area  monitoring
@huanggze

**Comment by huanggze** [comment]
确实几处 “容器组数量” 的含义是不一致的。Non-terminated Pod Count、Running Pod Count, Abnormal Pod Count。需要统一文案和指标使用。牵涉面较大，看 2.1 是否有时间
