### ISSUE TITLE
应用计数出错

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1012]
* [ ] 出现了NaN
![Screen Shot 2019-10-15 at 5 58 49 PM](https://user-images.githubusercontent.com/28859385/66821697-6f5ba580-ef75-11e9-91e5-01d51acbc9ff.png)

**Comment by leoendless** [comment]
再check下

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191018
