### ISSUE TITLE
应用部署name长度文案或校验有错

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1013]
* [ ] 一个说最长15，一个说要小于15
![Screen Shot 2019-10-15 at 6 08 19 PM](https://user-images.githubusercontent.com/28859385/66822445-d4fc6180-ef76-11e9-8ceb-d12d5394d5b9.png)

**Comment by whDongRui** [comment]
好的，我把这个表单下面的提示文字修改一下吧，和后端验证的逻辑保持一致。就改成“小于15个字符，......"

**Comment by leoendless** [comment]
验证规则也得改成14

**Comment by leoendless** [comment]
Fixed

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191018
