### ISSUE TITLE
kubesphere中需要发送邮件的pod有哪些

### ISSUE THREAD

**Issue by Forget-C** [kubesphere/kubesphere#1014]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
集群中只有一个node有发送邮件的权限，我们对这个node打了标签，需要将kubesphere中发送邮件的pod分配到这个node上。 请问kubesphere中需要发送邮件的pod有哪些呢？ 为kubesphere的pod添加node选择器是通过kubectl edit 还是其他更方便的方法呢 
**安装环境的硬件配置**
物理机，已正常运行

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
无
**Installer版本**
2.0.2

**Comment by zryfish** [comment]
可以将 kubesphere-alerting-system 下 notification 开头的 deployment 固定到你说的节点。固定节点的话，建议先给节点加label，通过 labelSelector 来选择节点

**Comment by Forget-C** [comment]
现在有了一个新的问题， 我们使用的告警邮箱为公司其他部门提供的。 
因邮箱服务设计的原因，在授权的服务器上发送邮件是不需要密码的，而kubesphere在登记邮箱时是必须输入密码的，请问一下，这个问题该怎么解决呢？

**Comment by rayzhou2017** [comment]
随便输入一个密码不行？

**Comment by Forget-C** [comment]
> 随便输入一个密码不行？

不行的 有密码就是验证失败。 我也不知道为什么这么设计～～

**Comment by rayzhou2017** [comment]
那没有密码岂不是很不安全？就输入地址就可以了？

**Comment by huojiao2006** [comment]
好的

**Comment by huojiao2006** [comment]
already verified in the Environment of user, it is passed.

**Comment by mayuhope** [comment]
Close the issue
