### ISSUE TITLE
gitlab单独安装bug

### ISSUE THREAD

**Issue by cnicy** [kubesphere/kubesphere#1015]
在按照：https://kubesphere.io/docs/v2.0/zh-CN/installation/gitlab-installation/
进行单独安装gitlab时，我选择：2 他安装的是harbor，我选择：1 安装的才是gitlab 
################################################
         gitlab-harbor Installer Menu
################################################
*   1) Harbor
*   2) Gitlab
*   3) Harbor-Gitlab
################################################
https://kubesphere.io/               2019-10-15
################################################
Please input an option: 2

**Comment by rayzhou2017** [comment]
这个fix了吗？

**Comment by Forest-L** [comment]
Fixed at https://github.com/kubesphere/tutorial/pull/6

**Comment by pengcong06** [comment]
area/testing
the way to enable gitlab is not supported in latest installer
