### ISSUE TITLE
All-in-one在线安装，安装过程等了很久，下载了很多镜像。现在提示这种错误：IPVS rr tcp 10.233.0.1:443 no destination available

### ISSUE THREAD

**Issue by wujay77** [kubesphere/kubesphere#1016]
**问题描述**
kubesphere-all-advanced-2.0.2
物理机Ubuntu18.04.3，All-in-one在线安装，安装过程等了很久，下载了很多镜像。现在提示这种错误：IPVS rr tcp 10.233.0.1:443 no destination available，请问怎么解决？谢谢！

**Comment by wujay77** [comment]
在确保防火墙已经关闭的情况下ufw disable
我又关闭了SELINUX：
apt install selinux-utils
setenforce 0
$ vim /etc/selinux/config
写入如下内容，
SELINUX=disabled
再确保安装了ipvsadm和ipset之后，又重新./install.sh安装了一遍，成功了。但控制台依然不断打印IPVS rr tcp 10.233.0.1:443 no destination available这种错误，不过控制台界面30880访问没有问题。

**Comment by rayzhou2017** [comment]
可以到https://github.com/kubesphere/ks-installer/issues 查查答案

**Comment by pixiake** [comment]
`IPVS rr tcp 10.233.0.1:443 no destination available`
这是内核打印的ipvs日志，这种信息一般是由于有些service的endpoint还没有启动，pod完全启动后应该就没有这种信息打印了。

如果不想看到这种信息，可以用`dmesg -n 1`屏蔽
