### ISSUE TITLE
文档需更新

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1019]
* [x] 2.1 菜单变更为高级设置了
![Screen Shot 2019-10-16 at 11 32 30 AM](https://user-images.githubusercontent.com/28859385/66886037-b47ce780-f008-11e9-831b-b5710bb4118b.png)

**Comment by FeynmanZhou** [comment]
@rayzhou2017  Updated, see this [guide](https://kubesphere.com.cn/docs/v2.1/zh-CN/project-setting/project-gateway/)

**Comment by rayzhou2017** [comment]
verified
