### ISSUE TITLE
项目资源用量没有曲线

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1020]
* [x] 没看见曲线
![Screen Shot 2019-10-16 at 11 36 13 AM](https://user-images.githubusercontent.com/28859385/66886190-281ef480-f009-11e9-9fe2-d54985351d88.png)

**Comment by leoendless** [comment]
@justahole 应该是 chart 库的问题

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191017
