### ISSUE TITLE
s2i 项目角色说明

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1023]
* [x] 最好有一个中英文的说明
![Screen Shot 2019-10-16 at 12 06 41 PM](https://user-images.githubusercontent.com/28859385/66887397-6dddbc00-f00d-11e9-9033-6ea812088a3d.png)

**Comment by rayzhou2017** [comment]
这个用户权限列表是空的，是正常的吧？就是什么权限都没有

**Comment by runzexia** [comment]
@wansir 正常来说应该没这个角色吧

**Comment by wansir** [comment]
这是一个手动创建的角色

**Comment by rayzhou2017** [comment]
这个是怎么回事呢？我看也没有改变，也没有说明。这个角色是在run s2i/b2i时候自动生成的

**Comment by wansir** [comment]
这个角色是 s2i operator 创建出来的， 应该被过滤掉
@leoendless  获取项目角色列表的时候可以加上额外的参数，过滤出面向用户的角色
https://github.com/kubesphere/kubesphere/pull/1111

**Comment by rayzhou2017** [comment]
verified
