### ISSUE TITLE
配额设置需要清除空数据

### ISSUE THREAD

**Issue by Carlosfengv** [kubesphere/kubesphere#1025]
RT；

- [ ] 默认不显示空数据的item,且只能有一个item处于空数据状态；

![image](https://user-images.githubusercontent.com/23092051/66889185-0e36df00-f014-11e9-8beb-5aa57b326e55.png)

**Comment by leoendless** [comment]
fixed

**Comment by Carlosfengv** [comment]
更新Dev Console 镜像后问题依然存在
