### ISSUE TITLE
项目设置菜单问题

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1026]
* [ ] 鼠标放上去或者点击箭头收不回去，其它的都可以，在FF下测试的
![Screen Shot 2019-10-16 at 1 14 06 PM](https://user-images.githubusercontent.com/28859385/66889977-e2692880-f016-11e9-8732-de1dd34fdfa1.png)

**Comment by leoendless** [comment]
这里的展示策略是鼠标悬浮时自动展开子菜单

**Comment by rayzhou2017** [comment]
哦，我理解错了，如果选择这个菜单下的子项是不会收起来的
