### ISSUE TITLE
应用组件不能为空 提示一直驻留在界面上

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1029]
第一次未添加任何组件点确定的情况下，提示“应用组件不能为空”。但该信息一直驻留在界面上

![image](https://user-images.githubusercontent.com/22350668/66894170-4f35f000-f022-11e9-81c7-44268bf747b1.png)

**Comment by leoendless** [comment]
fixed

**Comment by huanggze** [comment]
verified
