### ISSUE TITLE
部署示例应用点击确定没反应

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1030]
![image](https://user-images.githubusercontent.com/22350668/66894533-3da11800-f023-11e9-8871-5cec29a30389.png)

**Comment by huanggze** [comment]
是提示信息放在了底部？

![image](https://user-images.githubusercontent.com/22350668/66894563-55789c00-f023-11e9-9213-3131cd8c0542.png)

/assign @leoendless

**Comment by leoendless** [comment]
是的，之后会改善提示
