### ISSUE TITLE
输入镜像的页面link错误

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1031]
* [x] “创建镜像仓库密钥” link是错误的
![Screen Shot 2019-10-16 at 2 43 41 PM](https://user-images.githubusercontent.com/28859385/66894597-6f19e380-f023-11e9-851c-f51495d014a5.png)

**Comment by minghaoye** [comment]
fixed

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191017
