### ISSUE TITLE
应用列表翻页数字 NaN

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1033]
![image](https://user-images.githubusercontent.com/22350668/66895035-7097db80-f024-11e9-85a6-b75b6b2bc607.png)

**Comment by huanggze** [comment]
在搜索栏，搜索过应用。而且好像搜索功能没生效？？

**Comment by leoendless** [comment]
这个需要调整下接口

**Comment by rayzhou2017** [comment]
devops 下也有这个问题
![Screen Shot 2019-10-16 at 5 09 38 PM](https://user-images.githubusercontent.com/28859385/66905064-b8742e00-f037-11e9-8903-930502e56ab7.png)

**Comment by leoendless** [comment]
fixed

**Comment by leoendless** [comment]
devops @minghaoye 看下吧

**Comment by rayzhou2017** [comment]
企业空间也是这个问题
![Screen Shot 2019-10-16 at 5 37 51 PM](https://user-images.githubusercontent.com/28859385/66907236-9ed4e580-f03b-11e9-98b3-b43fc536e5e5.png)

**Comment by huanggze** [comment]
verified
