### ISSUE TITLE
应用仓库部署一直等待中

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1037]
第一次部署 fluentd，一直等到中

![image](https://user-images.githubusercontent.com/22350668/66897958-b8216600-f02a-11e9-9881-0d26fa508f3d.png)

到节点检查 helm，尝试手动 `helm install stable/fluentd --name my-release`，报错：
![image](https://user-images.githubusercontent.com/22350668/66898018-dd15d900-f02a-11e9-8d5f-f1fb737a20c5.png)

需要手动执行 `helm update`。之后，后台可以 `helm install` 了
![image](https://user-images.githubusercontent.com/22350668/66898097-03d40f80-f02b-11e9-81a2-c086d63c7450.png)

同时，UI 上也能部署 fluentd 了
![image](https://user-images.githubusercontent.com/22350668/66898150-1e0ded80-f02b-11e9-8683-3e100c341a9e.png)

**Comment by huanggze** [comment]
又有一个处于等待中的应用

![image](https://user-images.githubusercontent.com/22350668/66975009-a5ad3800-f0cf-11e9-9055-efaeb9eeff58.png)


![image](https://user-images.githubusercontent.com/22350668/66975005-9cbc6680-f0cf-11e9-85d9-52f17e8c25e4.png)

**Comment by wansir** [comment]
#887

**Comment by pengcong06** [comment]
#887 
这里的问题跟这个issue #1037还是有点区别;
这里找不到负载的问题的复现过程:
1.从ks部署应用emq
2.在allinone环境通过helm list查看emq,是在hello这个namespace下面
3.kubectl -n hello里边没有emq这个deployment
3.kubectl -n default里边找到了这个deployment
查看emq chart里边的namespace 是default

**Comment by zheng1** [comment]
已修复. 将openpitrix-system下的两个deployment `openpitrix-rp-kubernetes-deployment` 和 `openpitrix-hyperpitrix-deployment` 副本数从1调整到0再调整回1. 稳定后重新部署几次app看看能否复现.

**Comment by huanggze** [comment]
verified
