### ISSUE TITLE
创建告警规则报错

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1039]
* [ ] 普通用户创建告警规则的时候报错如下
![Screen Shot 2019-10-16 at 4 53 14 PM](https://user-images.githubusercontent.com/28859385/66903655-72b66600-f035-11e9-80ec-2388660c1a50.png)

**Comment by wansir** [comment]
fixed

**Comment by rayzhou2017** [comment]
这个是后端还是前端fix的？如果是后端的话是哪个PR？

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191017
