### ISSUE TITLE
语言设置

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1040]
* [ ] 中文环境下 label其实应该是 “Language”，英文环境下label是“语言”
![Screen Shot 2019-10-16 at 5 13 51 PM](https://user-images.githubusercontent.com/28859385/66905480-83b4a680-f038-11e9-99a4-ca094412aba8.png)

**Comment by leoendless** [comment]
感觉不是很有必要，不认识的根本都找不到这个地方

**Comment by rayzhou2017** [comment]
这应该是正确的做法，比如对于English speaker，他点开这个弹框也不知道这个是语言设置，一般人会点一级，再往下一级点开的概率就非常低。

**Comment by leoendless** [comment]
最合适还是用图标引导吧
