### ISSUE TITLE
删除应用仓库会白屏

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1041]
![image](https://user-images.githubusercontent.com/22350668/66905685-e8700100-f038-11e9-9d7d-1e12e1e38b06.png)

**Comment by whDongRui** [comment]
我测试的环境暂时没复现这个问题，需要在你测试的这个环境上再测一下。

**Comment by whDongRui** [comment]
这个问题刚复现了，是先勾选列表的多选框，再去列表中操作删除会有这个问题，刚给修复了。

**Comment by huanggze** [comment]
verified
