### ISSUE TITLE
上传应用，点击部署测试，出现大量同名重复部署

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1042]
部署按钮响应非常慢，可能是我一次点急了，点了四次。弹出多个部署成功的对话框

![image](https://user-images.githubusercontent.com/22350668/66906526-76002080-f03a-11e9-9ec0-f029214ce0e5.png)

![image](https://user-images.githubusercontent.com/22350668/66906571-86180000-f03a-11e9-92c3-ec255fa042a6.png)

![image](https://user-images.githubusercontent.com/22350668/66906486-6385e700-f03a-11e9-835f-06a8c6b653bd.png)

![image](https://user-images.githubusercontent.com/22350668/66908349-7c43cc00-f03d-11e9-8d5a-4b687e1b8ea5.png)

**Comment by huanggze** [comment]
@whDongRui 点击第一次后，按钮需要禁止响应

**Comment by whDongRui** [comment]
好的，从版本部署应用这个地方是没有加，其它几个入口的部署应用都加上了。这个我刚在本地修复了。

**Comment by huanggze** [comment]
verified
