### ISSUE TITLE
等待中的应用无法在二级页面删除，且一级页面删除时显示的应用名和列表中的应用名不同

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1044]
等待中的应用

![image](https://user-images.githubusercontent.com/22350668/66908681-14da4c00-f03e-11e9-92b1-8105c6f1b938.png)

无法在二级页面删除（启动成功的应用可以）
![image](https://user-images.githubusercontent.com/22350668/66908772-3dfadc80-f03e-11e9-9beb-162d6f5bb195.png)

在一级页面删除操作，显示的应用名和列表的应用名不一致
![image](https://user-images.githubusercontent.com/22350668/66908825-55d26080-f03e-11e9-88b5-29234bfb2f75.png)

![image](https://user-images.githubusercontent.com/22350668/66908860-6387e600-f03e-11e9-9912-d8011da63421.png)

**Comment by whDongRui** [comment]
这个删除提示框我已经改成都显示name了，在二级页面(详情页面)删除后会跳转到列表页面，由于删除的过程比较慢，目前这块没有websocket，所以还会在列表中看到数据，其实是删除成功了的。

**Comment by whDongRui** [comment]
目前暂时的解决办法是根据transition_status 加了“创建中”，“删除中”这两种状态。

![image](https://user-images.githubusercontent.com/38676269/67178593-e970ac00-f405-11e9-8739-c01efa979a47.png)


![image](https://user-images.githubusercontent.com/38676269/67178564-ce9e3780-f405-11e9-9213-58f018bc2576.png)
