### ISSUE TITLE
应用管理文案

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1045]
* [x] 上面的menu是不是应该是“应用管理”？因为是从平台管理下的“应用管理”点击过来的，不然两边不一致
![Screen Shot 2019-10-16 at 6 02 30 PM](https://user-images.githubusercontent.com/28859385/66909352-312ab880-f03f-11e9-8d26-ae73e31fc2be.png)

**Comment by whDongRui** [comment]
好的，把“应用商店管理”改成“应用管理”。

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-10191017
