### ISSUE TITLE
从应用仓库部署应用偶尔会失败，而且删除操作在界面上回显不友好

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1046]
前一次部署成功了，这一次没有部署成功

![image](https://user-images.githubusercontent.com/22350668/66910010-5bc94100-f040-11e9-85d8-d98530cf07ce.png)

删除后，刷新按钮不会更新页面。需要 F5 更新整个页面才能知道应用部署确实被删除成功了

![image](https://user-images.githubusercontent.com/22350668/66910115-887d5880-f040-11e9-8986-98cc51cced55.png)

**Comment by whDongRui** [comment]
这个页面部署应用或应用删除，其实就是对cluster的操作。但这次的版本这块后端接口没有websocket,列表中数据的状态前端不好更新。

这块部署完应用或删除后，要不前端加一下setInterval来请求列表数据？

/assign @wansir

**Comment by wansir** [comment]
@whDongRui   状态展示用 `transition_status`

**Comment by whDongRui** [comment]
目前接口返回的信息中还没有transition_status
