### ISSUE TITLE
偶发应用模板和应用仓库菜单没了

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1047]
偶发三次

![image](https://user-images.githubusercontent.com/22350668/66911150-8c11df00-f042-11e9-939d-694e378c2a26.png)

**Comment by huanggze** [comment]
一会又有了

![image](https://user-images.githubusercontent.com/22350668/66911214-a5b32680-f042-11e9-8952-c44a5e7ccef1.png)

**Comment by whDongRui** [comment]
这个已经修复了

**Comment by huanggze** [comment]
现在又多出 DevOps 菜单

![image](https://user-images.githubusercontent.com/22350668/67256001-74f64580-f4b7-11e9-9db3-1309c62b7a7d.png)


![image](https://user-images.githubusercontent.com/22350668/67255992-690a8380-f4b7-11e9-8a57-a1b43e8eba5c.png)

**Comment by whDongRui** [comment]
@leoendless 我看导航的配置里最近是加了DevOps工程，帮忙确认一下加了这个是不是bug?

**Comment by leoendless** [comment]
不是bug, 升级最新的installer验证

**Comment by huanggze** [comment]
问题仍然存在，需要移除浏览器缓存

**Comment by leoendless** [comment]
Fixed

**Comment by huanggze** [comment]
verified
