### ISSUE TITLE
没启用 devops 时，无须请求 devops 监控数据

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1048]
![image](https://user-images.githubusercontent.com/22350668/66922370-82e03c80-f059-11e9-9a54-efb11a0d4f65.png)

![image](https://user-images.githubusercontent.com/22350668/66922480-bb801600-f059-11e9-822d-809ebd30f52a.png)

ks-apiserver 频繁报错

![image](https://user-images.githubusercontent.com/22350668/66922325-69d78b80-f059-11e9-9e03-302f3b395b66.png)

**Comment by leoendless** [comment]
最好在api server catch 下，否则前端调整太繁琐
