### ISSUE TITLE
应用名称已存在，无法上传应用

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1049]
![image](https://user-images.githubusercontent.com/22350668/66923773-07cc5580-f05c-11e9-834d-3a5d59deaba8.png)

不仅限于 fluentd，还包括 mysql、fluent-bit 等

![image](https://user-images.githubusercontent.com/22350668/66923712-e8cdc380-f05b-11e9-8433-a7c53c2f46e4.png)

**Comment by huanggze** [comment]
是和应用仓库的命名冲突了吗？

![image](https://user-images.githubusercontent.com/22350668/66924494-50d0d980-f05d-11e9-8664-560ed55cd2fc.png)

**Comment by huanggze** [comment]
删了应用仓库也不行

**Comment by whDongRui** [comment]
这个是和应用仓库中应用名称有冲突的，有可能其它企业空间下的仓库还有一样的应用名称。

**Comment by pengcong06** [comment]
第三方仓库跟内置仓库里边的package文件都会调用RepoIndex将应用元信息存入到app表里边,这个流程里边会检测app Name是否已经存在,就导致了你看到的错误!
现在,我们会去掉检测app Name是否存在这个逻辑!
/assign @huanggze

**Comment by zheng1** [comment]
@huanggze  验证一下最新版本是否还有这个问题

**Comment by huanggze** [comment]
verified
