### ISSUE TITLE
企业空间角色权限问题

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1050]
- [ ] workspace-viewer 有创建 bookinfo、工作负载 的权限
- [ ] workspace-viewer 创建 bookinfo 会提示已存在（wk-admin创建过），但实际界面上并没有bookinfo

![image](https://user-images.githubusercontent.com/22350668/66974530-eb690100-f0cd-11e9-9fbe-0f5ed5b98ed0.png)

![image](https://user-images.githubusercontent.com/22350668/66974537-f2900f00-f0cd-11e9-9ec4-3d5d61f5b41a.png)

- [ ] workspace-regular 看不到企业监控（但 viewer 能看到）

![image](https://user-images.githubusercontent.com/22350668/66973086-7398d780-f0c9-11e9-84dc-c23ba3cbbd04.png)

![image](https://user-images.githubusercontent.com/22350668/66973151-a6db6680-f0c9-11e9-88c9-ed81ec1f4457.png)

- [ ] workspace-regular 无部署应用入口

![image](https://user-images.githubusercontent.com/22350668/66974715-94aff700-f0ce-11e9-95ce-53d71e09a79c.png)

![image](https://user-images.githubusercontent.com/22350668/66974676-734f0b00-f0ce-11e9-8436-0ad7e529d242.png)

**Comment by huanggze** [comment]
两个 workspace role 在 namespace  下都是 admin 权限

**Comment by wansir** [comment]
1. @leoendless  入口禁用一下
2. workspace-viewer 无法创建资源
3. workspace-regular 是无法看到workspace 层面的监控数据
4. workspace-regular只定义了workspace层面的权限，还需要检查该用户在namespace 层级的角色

**Comment by leoendless** [comment]
bookinfo 入口已修复

**Comment by huanggze** [comment]
verified
