### ISSUE TITLE
English locales bug list

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1052]
* [x] TOTAL_CATE_COUNT not replaced @whDongRui 
![Screen Shot 2019-10-17 at 10 11 59 AM](https://user-images.githubusercontent.com/28859385/66972274-b1483100-f0c6-11e9-955e-114e2c17ce1a.png)
* [x]  should remove the word management from the menu, i.e., change Projects Management to Projects, Accounts Management to Accounts, also change App manage to Applications @leoendless 
![Screen Shot 2019-10-17 at 11 54 03 AM](https://user-images.githubusercontent.com/28859385/66976545-da6fbe00-f0d4-11e9-9d58-07f86be6aae2.png)

* [x] change Visited Address to Service Address
![Screen Shot 2019-10-17 at 12 27 22 PM](https://user-images.githubusercontent.com/28859385/66977692-7e5b6880-f0d9-11e9-906f-81ef9c108333.png)

![Screen Shot 2019-10-17 at 12 29 11 PM](https://user-images.githubusercontent.com/28859385/66977752-b82c6f00-f0d9-11e9-828d-f155ecd5a662.png)
![Screen Shot 2019-10-17 at 12 29 33 PM](https://user-images.githubusercontent.com/28859385/66977757-be225000-f0d9-11e9-90bc-56e8e6b04398.png)

**Comment by whDongRui** [comment]
好的，应用商店首页的翻译已经加上了。

**Comment by rayzhou2017** [comment]
第二个和第三个没有fix

**Comment by leoendless** [comment]
Fixed

**Comment by rayzhou2017** [comment]
第二个即使要留管理也应该是Apps Management，不是App Manage，另外Accounts Management这个地方最好去掉Management，不然下面role为什么没有management？

**Comment by rayzhou2017** [comment]
第三个还是visited

**Comment by leoendless** [comment]
![image](https://user-images.githubusercontent.com/8739949/67352011-65dbca00-f581-11e9-94cb-df810979dcec.png)

visited 应该改过来了

**Comment by leoendless** [comment]
App Manage 也更新过来了，kubespheredev/ks-console:latest

**Comment by rayzhou2017** [comment]
verified
