### ISSUE TITLE
企业空间搜索 结果排序优化

### ISSUE THREAD

**Issue by Carlosfengv** [kubesphere/kubesphere#1053]
RT；

- [x] 最相关的结果应在搜索结果的最前面

![image](https://user-images.githubusercontent.com/23092051/66972832-692a0e00-f0c8-11e9-922a-fe90ed53244d.png)

**Comment by wansir** [comment]
@leoendless query param:` orderBy=name`

**Comment by wanjunlei** [comment]
Verified，need to be closed
