### ISSUE TITLE
在 namespace 下，从应用商店部署应用，需要手动指定部署到哪个 workspace、namespace

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1055]
在一个 workspace、namespace 下部署应用

![image](https://user-images.githubusercontent.com/22350668/66974780-db055600-f0ce-11e9-8fd1-ab40fe44e92c.png)

应用商店部署仍每次需要手动修改

![image](https://user-images.githubusercontent.com/22350668/66974878-2a4b8680-f0cf-11e9-9c30-2983d839dfd2.png)

**Comment by whDongRui** [comment]
这个是直接跳转到应用商店的首页，但从首页跳转到详情页面部署的，url中没有把workspace、namespace 传过去，所以导致部署时还要选择企业空间和项目。

之前没有考虑这一点，这个我和设计确认一下有需要的就在详情页面的url中把workspace、namespace加上，这样部署时就可以默认选中企业空间和项目了。

**Comment by whDongRui** [comment]
刚把这块的逻辑给加了上，这个等明天前端更新了你再测试一下吧。

**Comment by huanggze** [comment]
verified
