### ISSUE TITLE
搜索应用失效、不能翻页

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1056]
![image](https://user-images.githubusercontent.com/22350668/66975108-f4f36880-f0cf-11e9-932f-01eb44853647.png)

![image](https://user-images.githubusercontent.com/22350668/66975207-616e6780-f0d0-11e9-8e64-dafb87e4b82d.png)

**Comment by whDongRui** [comment]
这个页面的搜索，刷新等有问题。这个是之前有人为了修复bug在这个页面加了一个componentDidMount方法，但这个方法把基类中对搜索，刷新的逻辑给覆盖了。刚给修复了。

**Comment by huanggze** [comment]
verified
