### ISSUE TITLE
从仓库部署了应用gcp-night-king后，列表中缺少图标

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1059]
1、对企业空间添加应用仓库；

2、新建项目，在项目下通过仓库新建应用，部署了应用gcp-night-king后，列表中缺少图标：
![image](https://user-images.githubusercontent.com/7677050/66982966-f9c51600-f0e9-11e9-9f31-0d85f40bfab0.png)

**Comment by whDongRui** [comment]
这个已经修复了，上次他们重构这个组件用了之前的组件导致的。这个你明天再确认一下吧。

![image](https://user-images.githubusercontent.com/38676269/66990553-04d37280-f0f9-11e9-89d1-74e142220602.png)
