### ISSUE TITLE
添加平台级别的告警策略时，集群节点缺少IP

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1062]
1、进入平台管理-监控中心，添加告警策略，输入名称，点击下一步，结果没有显示节点IP（节点已经被分配了IP）：

![image](https://user-images.githubusercontent.com/7677050/66984952-562a3480-f0ee-11e9-9ee1-df4e9f3c9d86.png)

**Comment by leoendless** [comment]
Fixed

**Comment by mayuhope** [comment]
已修复
