### ISSUE TITLE
应用提交审核时，点击《开发者测试指南》后没有跳转到正确的网页

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1066]
1、上传应用模板后，对应用提交审核；

2、在提交审核页面，点击《开发者测试指南》后没有跳转到正确的网页，该链接地址目前为http://139.198.5.33:30880/workspaces/space1/apps/app-lOPg15lZqPo8/version-manage#

![image](https://user-images.githubusercontent.com/7677050/66991167-1c5f2b00-f0fa-11e9-8eb0-a367cb85170e.png)

**Comment by FeynmanZhou** [comment]
链接已经提交给了 @whDongRui  ， @whDongRui console 上的两处链接更新后请在 issue 后面回复吧

**Comment by whDongRui** [comment]
@mayuhope 这两处的链接昨天已经修复了，有时间可以再测试一下看还有没有问题。

**Comment by mayuhope** [comment]
已验证
