### ISSUE TITLE
高可用集群，关闭一个master节点后，kubesphere界面无法访问

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#1070]
**Describe the bug(描述下问题)**
高可用集群，关闭一个master节点后，kubesphere界面无法访问

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere:2.1.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
3 masters:  8cpu/16g
3 nodes: 8cpu/16g

/kind bug
/milestone 2.1.0

**Comment by rayzhou2017** [comment]
这是因为还有很多单点，需要先解决这些问题才能测HA。
![Screen Shot 2019-10-17 at 6 12 55 PM](https://user-images.githubusercontent.com/28859385/67000085-bda1ad80-f109-11e9-9f5f-7d8db12c24ad.png)
