### ISSUE TITLE
创建s2i java 服务报错

### ISSUE THREAD

**Issue by bmingithub** [kubesphere/kubesphere#1071]
**Describe the bug(描述下问题)**
按照kubesphere/s2i-java-container创建服务，Pod运行报错， 前端接口也有404

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/35321102/66995091-0012bc80-f101-11e9-8738-6562a1ec31b8.png)

**Expected behavior(预期行为)**
pod能正常运行

**Comment by bmingithub** [comment]
夏润泽说有两个问题：
1.  404是url拼接有问题
2.  相对路径参数没有带

![image](https://user-images.githubusercontent.com/35321102/66995527-bf677300-f101-11e9-894c-02c2d9aba938.png)

**Comment by runzexia** [comment]
/assign @minghaoye 

![image](https://user-images.githubusercontent.com/31230341/66995771-1ec58300-f102-11e9-8c8a-9cdfd575d450.png)
上面这个漏了

**Comment by minghaoye** [comment]
fixed in new image at 17th oct 20:30
