### ISSUE TITLE
应用的状态显示错误，实际为“等待审核”时，列表中显示为“待提交”

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1072]
1、在企业空间下上传应用模板nginx；

2、对nginx提交审核，状态为“等待审核”，结果左侧详情中显示的状态为“待提交”，显示错误：

![image](https://user-images.githubusercontent.com/7677050/66995470-a6f75880-f101-11e9-8cfa-e14aea0f26a9.png)

![image](https://user-images.githubusercontent.com/7677050/66995507-b4144780-f101-11e9-9aaf-0fa045040670.png)

**Comment by whDongRui** [comment]
@mayuhope 

状态为“等待审核”是根据version的状态来的，左侧详情中显示的状态为“待提交”，这个是app的状态。version和app这两个状态是不同的，

目前app支持'draft|active|suspended|deleted',后面审核通过加了一个'passed',这个后端接口可能还没更新。
version的状态有：draft|submitted|rejected|in-review|passed|active|suspended|deleted

**Comment by whDongRui** [comment]
@mayuhope 一个是app的状态，一个是版本的状态。右侧版本列表可能有多个版本，他们之前的状态可以不同，但在应用详情页面多个版本只能对应一个应用的状态。
应用的状态和版本的状态不一定要和版本的状态保持一致的。

![image](https://user-images.githubusercontent.com/38676269/66996239-f5f1bd80-f102-11e9-889c-e8b14f82d8af.png)

**Comment by mayuhope** [comment]
close
