### ISSUE TITLE
could select and upload war file with jar mode b2i

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1078]
**Describe the bug(描述下问题)**
could select and upload war file with jar mode b2i

For UI issues please also add a screenshot that shows the issue.

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0 dev

**To Reproduce(复现步骤)**
1. Create a b2i service with jar mode
2. select upload file and you could see both jar and war files are all listed for selection

**Expected behavior(预期行为)**
Only jar files could be selected.
Similar problem happens for war b2i, which should only allow to select war file

**Comment by minghaoye** [comment]
fixed. 

chrome can't distinguish jar and war, added tips for this case.
