### ISSUE TITLE
b2i could set empty image server, is it as design? 

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1079]
**Describe the bug(描述下问题)**
when creating b2i svc, I don't need to input image reg server parm and just leave it empty, is it as design? 

For UI issues please also add a screenshot that shows the issue.

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0 dev

**Comment by runzexia** [comment]
this should be required 
/cc @minghaoye

**Comment by calvinyv** [comment]
verified
