### ISSUE TITLE
delete b2i svc but its job data still left

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1080]
**Describe the bug(描述下问题)**
delete b2i svc but its job data still left

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0 dev

**To Reproduce(复现步骤)**
1. Create a b2i svc
2. Delete above b2i svc
3. Go to Job page, you could see that b2j job is still there

**Expected behavior(预期行为)**
all data related to this b2i svc should be clear at same time

**Comment by calvinyv** [comment]
another issue I also found is: the b2i job are always there even if I delete it manually, another new job will be created automatically later. @soulseen

**Comment by soulseen** [comment]
> another issue I also found is: the b2i job are always there even if I delete it manually, another new job will be created automatically later. @soulseen

s2i/b2i job created by Image Builder. You should delete Image Builder, and s2i/b2i job will delete automatic.

all data related to this b2i svc should be clear at same time, this will be fix.

**Comment by minghaoye** [comment]
fixed

**Comment by calvinyv** [comment]
verified
