### ISSUE TITLE
no description info for s2i regular role

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1082]
**Describe the bug(描述下问题)**
no description info for s2i regular role

For UI issues please also add a screenshot that shows the issue.
![Jietu20191018-101441](https://user-images.githubusercontent.com/28883416/67060638-4bc07700-f190-11e9-8a5b-7769e9f907f2.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0 dev

**Comment by minghaoye** [comment]
dirt data, could create a new project,

**Comment by calvinyv** [comment]
@minghaoye I tried the latest build today, and didn't see this role, so 'dirty data' means that role should not shown on kubesphere?

**Comment by minghaoye** [comment]
yes, it shouldn't appear
