### ISSUE TITLE
alert only supports deployment

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1083]
* [x] It should support deployment, statefulset and daemonset
![Screen Shot 2019-10-18 at 10 15 24 AM](https://user-images.githubusercontent.com/28859385/67060634-419e7880-f190-11e9-89a7-52925abd7616.png)

**Comment by justahole** [comment]
右边的选择器没有  deployment, statefulset ，daemonset 的选项吗

**Comment by rayzhou2017** [comment]
下拉框点不动

**Comment by justahole** [comment]
告警目标一次只能选择deployment, statefulset and daemonset中的其中一个。为了产生误会，选择了一个资源后，阻止了用户切换类型

**Comment by rayzhou2017** [comment]
那应该提示一下，加一下文案

**Comment by rayzhou2017** [comment]
verified
