### ISSUE TITLE
The role operator of a project shouldn't have access to advanced settings

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1084]
* [ ] The role operator of a project shouldn't have access to advanced settings of the project
![Screen Shot 2019-10-18 at 10 07 38 AM](https://user-images.githubusercontent.com/28859385/67060821-f173e600-f190-11e9-821e-b4adeb5b8814.png)

**Comment by rayzhou2017** [comment]
should have read access, not edit access

**Comment by wansir** [comment]
@leoendless  operator/viewer can view advanced settings, do not show edit button

**Comment by rayzhou2017** [comment]
verified
