### ISSUE TITLE
用户信息保存体验不一致

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1085]
**Describe the bug(描述下问题)**
修改用户信息，按钮提示的是“Save”这样文字风格的，但资源保存的提示是✅❌这种

For UI issues please also add a screenshot that shows the issue.

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0 dev

**Comment by calvinyv** [comment]
/assign @leoendless 
@kind enhancement

**Comment by leoendless** [comment]
Fixed

**Comment by calvinyv** [comment]
verified
