### ISSUE TITLE
已删除版本的应用，能再次上传一个其他应用名tar.gz

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1087]
一个已删除版本的应用（couchdb）

![image](https://user-images.githubusercontent.com/22350668/67061255-5da31980-f192-11e9-9088-7326711898a5.png)

![image](https://user-images.githubusercontent.com/22350668/67061276-68f64500-f192-11e9-8b49-2844a2af1c14.png)

能上传一个其他应用的 tar.gz (比如fluentd)

![image](https://user-images.githubusercontent.com/22350668/67061348-a1961e80-f192-11e9-96a0-4b464c83a9b2.png)

![image](https://user-images.githubusercontent.com/22350668/67061364-ad81e080-f192-11e9-9547-49449405c68f.png)

成功后名字却显示的是 couchdb，而实际内容是 fluentd

![image](https://user-images.githubusercontent.com/22350668/67061396-c68a9180-f192-11e9-83b5-478105bc986e.png)

**Comment by Carlosfengv** [comment]
暂时应该没有办法确保上传helm 包 的内容与应用是一致的，所以对于应用商店上线的版本只能是通过部署测试实例和审核来干预。

**Comment by pengcong06** [comment]
这个逻辑不是预期,现在也没办法做到通过程序来辨别!
App可以认为是一个app_version的一个label,app_version才是一个具体的package,在load这个pkg的时候会将名字同package里边的内容进行简单的验证,但是这种验证也不能保证所见即所得,只能通过部审核人员部署测试来判断 /assign @huanggze
