### ISSUE TITLE
安装完成其中一个pod报错

### ISSUE THREAD

**Issue by lijinbang** [kubesphere/kubesphere#1088]
日志如下
![image](https://user-images.githubusercontent.com/18083299/67063431-64815a80-f199-11e9-9efb-5f62e871ed75.png)；请问如何解决！

**Comment by zheng1** [comment]
你好，请贴一下 `kubectl get pod -n openpitrix-system` 的结果

**Comment by lijinbang** [comment]
![image](https://user-images.githubusercontent.com/18083299/67066565-b29c5b00-f1a5-11e9-878b-76235a69d356.png)

**Comment by lijinbang** [comment]
这是没有启动完成还是没有安装完成呢？

**Comment by rayzhou2017** [comment]
应该是出错了

**Comment by lijinbang** [comment]
这种应该如何恢复呢

**Comment by zheng1** [comment]
可以执行 `/etc/kubesphere/openpitrix/kubernetes/scripts && ./deploy-k8s.sh -n openpitrix-system -d -v v0.3.5` 尝试修复

然后检查 `kubectl get pod -n openpitrix-system | grep iam-db-ctrl-job` 的结果

**Comment by lijinbang** [comment]
我先试试

**Comment by lijinbang** [comment]
![image](https://user-images.githubusercontent.com/18083299/67078112-3a449280-f1c3-11e9-8bdc-e572fe9cd16d.png)
这是执行结果

**Comment by zheng1** [comment]
可以将登录环境发到 kubesphere@yunify.com 下吗，我们看下
