### ISSUE TITLE
应用仓库创建模态框被重复填充

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1093]
![image](https://user-images.githubusercontent.com/22350668/67083269-7250d300-f1cd-11e9-9980-558423bde0de.png)

再次创建时，有上一次的内容

![image](https://user-images.githubusercontent.com/22350668/67083295-7e3c9500-f1cd-11e9-984b-9efba8500b39.png)

**Comment by whDongRui** [comment]
Fixed

**Comment by huanggze** [comment]
verified
