### ISSUE TITLE
最小安装之后，无法创建应用，页面一直转圈等待，接口 404。

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#1096]
安装类型：在线最小安装

版本： kubesphere 2.1 20191018 

截图：

![image](https://user-images.githubusercontent.com/43693241/67087872-69b0ca80-f1d6-11e9-9e37-770a71c08d5b.png)

/area microservice
/assign @zryfish

**Comment by huanggze** [comment]
提了相同问题...已经修复了 latest tag

**Comment by ZPJeck** [comment]
最小安装，为什么 没有部署service  ，没有对外访问的接口？？？

**Comment by shaowenchen** [comment]
部署之后，有没有提示成功？有其他问题，可以在 https://kubesphere.com.cn/forum/ 提下，这个 issues 已经关闭了。
