### ISSUE TITLE
跑起来的应用显示等待中

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1097]
多次刷新确认，仍是等待中

![image](https://user-images.githubusercontent.com/22350668/67092350-928a8d00-f1e1-11e9-8bd7-497f700f3c1a.png)

![image](https://user-images.githubusercontent.com/22350668/67092359-961e1400-f1e1-11e9-98b3-21f43fe8db6f.png)

**Comment by whDongRui** [comment]
列表显示的状态是根据后端返回的数据显示的，如果刷新数据后状态没有变这个要后端看一下应用的状态为什么没有及时更新。

**Comment by zheng1** [comment]
same with #1037

/kind need-to-verify

**Comment by huanggze** [comment]
verified
