### ISSUE TITLE
应用列表刷新无动画效果，其他地方都有交互

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1098]
UI 其他地方的刷新动画效果

![image](https://user-images.githubusercontent.com/22350668/67092611-455aeb00-f1e2-11e9-984e-a392e3b4101d.png)

应用列表这里刷新虽然可以生效，但无交互效果

![image](https://user-images.githubusercontent.com/22350668/67092718-87842c80-f1e2-11e9-9d56-6a7c8ff08cbf.png)

**Comment by whDongRui** [comment]
Fixed

**Comment by huanggze** [comment]
verified
