### ISSUE TITLE
应用列表排序

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1099]
名字、更新时间排序有问题

![image](https://user-images.githubusercontent.com/22350668/67093625-ae436280-f1e4-11e9-900a-da0a727f4786.png)

**Comment by whDongRui** [comment]
我看前端有传参，应该是后端接口支持的问题

![image](https://user-images.githubusercontent.com/38676269/67171726-e6b48d80-f3ea-11e9-9b80-40e862fbe63d.png)

/assign @wansir @pengcong06

**Comment by huanggze** [comment]
可以排序，但结果升降逻辑有问题

/remove-kind need-to-verify

**Comment by whDongRui** [comment]
结果升降逻辑好像反了的问题后端会修复的

**Comment by huanggze** [comment]
10月25日 早上9点半 安装的环境，仍有问题 @pengcong06 

/remove-kind need-to-verify

**Comment by zheng1** [comment]
@huanggze  我这里没能复现, 这个能录个视频吗?
![Kapture 2019-11-01 at 8 15 24](https://user-images.githubusercontent.com/4156721/67994384-f8662280-fc7f-11e9-8d09-5ce2881bfe4d.gif)

**Comment by huanggze** [comment]
verified
