### ISSUE TITLE
部分应用没有应用名

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1100]
![image](https://user-images.githubusercontent.com/22350668/67094118-b354e180-f1e5-11e9-956a-214cfa7db2d2.png)

**Comment by wansir** [comment]
这个名称取自 pod 的label，如果helm chart 没有按约定俗成的方式写的话这里就无法展示应用名称，不算咱们的bug

**Comment by huanggze** [comment]
是看哪个 label?
