### ISSUE TITLE
示例应用没有在应用列表显示

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1101]
* [x] 我部署了示例应用，但没有显示在应用表里
<img width="990" alt="Screen Shot 2019-10-18 at 8 27 51 PM" src="https://user-images.githubusercontent.com/28859385/67094714-eb105900-f1e6-11e9-9239-077ae13f3c58.png">
<img width="1009" alt="Screen Shot 2019-10-18 at 8 27 59 PM" src="https://user-images.githubusercontent.com/28859385/67094728-f2cffd80-f1e6-11e9-8758-e800602655fe.png">

**Comment by huanggze** [comment]
在自制应用这个 tab 下。比较奇怪为什么分成两个 tab

![image](https://user-images.githubusercontent.com/22350668/67095388-61618b00-f1e8-11e9-82e0-66114488f38f.png)
