### ISSUE TITLE
CICD的deploy过程中所调用的yaml文件能否解析环境变量？

### ISSUE THREAD

**Issue by l3950809** [kubesphere/kubesphere#1105]
例如我在流水线中，有一步目的是构建一个镜像:docker build -t abc_images/${BUILD_NUMBER} .
docker push  abc_images/${BUILD_NUMBER}  .
接着问题是我在流水线的最后一步，需要调用代码仓库中的yaml文件进行部署的时候，yaml文件里面是否也能识别到${BUILD_NUMBER}这个环境变量呢？

**Comment by runzexia** [comment]
https://github.com/kubesphere/devops-java-sample/blob/master/deploy/dev-ol/devops-sample.yaml#L31

https://kubesphere.io/docs/v2.0/zh-CN/quick-start/jenkinsfile-out-of-scm/

参考devops-java-sample，是可以识别到的
