### ISSUE TITLE
ws viewer should not have the access to edit/delete repo

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1106]
* [ ] the logged in user is the ws viewer, but can edit/delete the configured repo as shown below
![Screen Shot 2019-10-21 at 1 08 16 PM](https://user-images.githubusercontent.com/28859385/67178125-2d62b180-f404-11e9-9273-95185051ce44.png)

**Comment by rayzhou2017** [comment]
only frontend needs to change? How about the backend?

**Comment by wansir** [comment]
> only frontend needs to change? How about the backend?

only frontend

**Comment by leoendless** [comment]
Fixed

**Comment by rayzhou2017** [comment]
verified
