### ISSUE TITLE
蓝绿部署时，流量已经切换，但是组件状态没有更新

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#1108]
![image](https://user-images.githubusercontent.com/43693241/67184466-699f0d80-f416-11e9-98d6-b94af78e7c85.png)

/assign @leoendless 
/milestone 2.1
/area console

**Comment by shaowenchen** [comment]
其他灰度策略时，存在同样的问题，只刷新了 metrics 接口，没有刷新组件状态

**Comment by leoendless** [comment]
这里的 pod 列表没有加上实时更新，消耗比较大

**Comment by shaowenchen** [comment]
那就转到下一个 milestone 吧

/remove-milestone 2.1.0
/milestone 2.1.1

**Comment by leoendless** [comment]
这个应该修复了，可以验证看看

**Comment by shaowenchen** [comment]
20191030 的版本还没有。可以将灰度发布的版本设置，大一点复现。

![image](https://user-images.githubusercontent.com/43693241/67845908-47ef0600-fb3b-11e9-8159-665110baf1e4.png)

就绪的副本数和副本状态，没有实时刷新。在负载里面，可以看到部分副本已经就绪。

**Comment by leoendless** [comment]
修复了 websocket 连接的问题，可以更新下环境看看

**Comment by shaowenchen** [comment]
轮询，更新状态，OK。

/close
