### ISSUE TITLE
蓝绿部署时，编辑组件 -> 灰度策略，状态显示错误，同时无法编辑保存

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#1110]
![image](https://user-images.githubusercontent.com/43693241/67185369-3d848c00-f418-11e9-945c-0b7e5a0e1c70.png)

1，状态显示错误。

实际上，v3 已经上线接管全部流量，但是依然高亮显示【接管所有流量】

2，接管流量后，无法保存生效。

/milestone 2.1.0
/area console
/assign @leoendless

**Comment by leoendless** [comment]
Fixed

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/67843793-a3b79000-fb37-11e9-8d09-becb49fbb6f3.png)

OK
/close
