### ISSUE TITLE
示例应用，不显示 Tracing 应用和事件数据

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#1114]
![image](https://user-images.githubusercontent.com/43693241/67187855-be925200-f41d-11e9-8751-31d2e8b92226.png)

**Comment by rayzhou2017** [comment]
你发请求了吗？这个需要发请求才有数据

**Comment by shaowenchen** [comment]
@rayzhou2017 
已经发过请求了，使用 watch 命令，刷新页面

**Comment by xumengqingyuan** [comment]
2.0.2版本同样无数据
![image](https://user-images.githubusercontent.com/11515270/67268630-83f4ec00-f4e7-11e9-875b-ad6a5d10ea2b.png)

![image](https://user-images.githubusercontent.com/11515270/67268584-64f65a00-f4e7-11e9-93fd-54a4ace0419d.png)

**Comment by zryfish** [comment]
最新的installer修复了，需要打开网关的应用治理功能

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/67842886-fa23cf00-fb35-11e9-9003-c0be119450a2.png)

事件被去掉了吗？
