### ISSUE TITLE
项目容器资源默认请求编辑框和列表展示数据不一致

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1115]
1、项目-基本信息，项目管理-编辑默认资源请求，内容如下，提交成功：
![image](https://user-images.githubusercontent.com/7677050/67189794-74ab6b00-f421-11e9-9d50-0bd89cfc2dac.png)

2、但是提交成功后列表展示的数据不正确：
![image](https://user-images.githubusercontent.com/7677050/67189801-77a65b80-f421-11e9-9fa7-864613a7272a.png)

**Comment by leoendless** [comment]
Fixed

**Comment by mayuhope** [comment]
latest 已修复
