### ISSUE TITLE
部署中，事件数量达到 10 之后，不会继续滚动更新。

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#1117]
![image](https://user-images.githubusercontent.com/43693241/67190300-4f6b2c80-f422-11e9-8231-6ee4aabd9c7f.png)

事件数量达到 10 条之后，后续的事件不会显示出来。

/milestone 2.1.0
/area console
/assign @leoendless

**Comment by zryfish** [comment]
apiserver会对一些相似的事件做合并，也不是只是10条，会很多条，不过event没有做持久化，仅会保留最近两小时的event
