### ISSUE TITLE
部署中，版本控制 Tab 页面没有分页（每10个版本），另外建议倒序排列

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#1118]
![image](https://user-images.githubusercontent.com/43693241/67191281-f2707600-f423-11e9-9063-a5dfe29e9e45.png)

**Comment by leoendless** [comment]
倒序排列已修正，分页需要下一版才能处理

**Comment by shaowenchen** [comment]
验证 OK。
/close
