### ISSUE TITLE
访问devops凭证后点击返回，页面报错提示不存在

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1119]
1、新建一个deops项目；
2、新建一个凭证，如sonar-token，进入凭证详情页，点击返回：
![image](https://user-images.githubusercontent.com/7677050/67191760-cc97a100-f424-11e9-82aa-ee9bbe6cc93d.png)

3、结果：提示页面不存在：
![image](https://user-images.githubusercontent.com/7677050/67191829-ef29ba00-f424-11e9-9c94-35774f320335.png)

**Comment by minghaoye** [comment]
fixed, verify in new image at 8:30 pm oct 21th

**Comment by mayuhope** [comment]
已修复
