### ISSUE TITLE
构建镜像，镜像描述需要优化

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#1120]
![image](https://user-images.githubusercontent.com/43693241/67192042-63fcf400-f425-11e9-9e15-cf344ad0cfed.png)

1，需要考虑国际化
2，描述太长，前端 hover 时，能不能给出完整提示

/milestone 2.1.0
/area devops 
/assign @leoendless @runzexia

**Comment by minghaoye** [comment]
已添加，10/21 晚上的镜像可以验证一下

**Comment by shaowenchen** [comment]
验证 OK。
/close
