### ISSUE TITLE
应用仓库是否可以支持用户验证和企业空间绑定

### ISSUE THREAD

**Issue by Forget-C** [kubesphere/kubesphere#1121]
1. 登记的应用仓库现在是所有企业空间可见，而有些用户可能并不希望共享自己的helm，所以是否可以将helm仓库与企业空间关联绑定，设置权限。
2. helm仓库的登记不支持用户密码验证
3. 还有一个其他的问题，现在的项目支持资源配额，是否可以增加企业空间的资源配额？ 否则无法对整体资源做限制

**Comment by wansir** [comment]
1. 2.1.0 中应用仓库在每个企业空间中可以添加私有的应用仓库，也提供集群层级的公共仓库方便提交自制应用。
2. 暂时还不支持需要认证的helm仓库
3. 企业空间配额已在开发计划中

**Comment by Forget-C** [comment]
@wansir 
企业空间配额支持为 企业空间指定服务器吗？ 就是这个企业空间的容器只会调度到指定的节点上

**Comment by calvinyv** [comment]
@Forget-C pls join the discussion here #1152

**Comment by zryfish** [comment]
/close 

Workspace resource quota is included in our master branch and will be released in v3.1.0 soon
