### ISSUE TITLE
2.0.2 容器终端的日志不能打印出dotnet core的控制台打印

### ISSUE THREAD

**Issue by xwb2535** [kubesphere/kubesphere#1122]
部署出来的应用是dotnet core的程序，里面的控制台打印的内容，不能在 容器组的日志里面看到。docker和其他的k8s里面是可以查看的。

**Comment by huanggze** [comment]
请参考 https://kubesphere.io/forum/d/23-kubesphere-kubectl-logs 截图下

**Comment by xwb2535** [comment]
重新安装了一次，显示出来了....

**Comment by huanggze** [comment]
之前是刚安装完，组件还没起来就查日志了么？

**Comment by xwb2535** [comment]
组件应该起来了，等了一段时间了。不过可能是机器配置，部署到4核8G的节点机器去了，导致性能较慢吧。现在都升级到1个16核32G ，2个8核16G的之后，就一直没出现卡顿的问题了。
