### ISSUE TITLE
流水线运行到sonarqube analysis这一步失败，installer安装失败但没有提示错误

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1123]
1、执行kubectl edit cm -n kubesphere-system ks-installer，启用devops和sonarqube；

2、按照 https://kubesphere.io/docs/v2.0/zh-CN/quick-start/devops-online/ 创建好凭证，运行流水线；

3、结果流水线运行到sonarqube analysis这一步失败，
![image](https://user-images.githubusercontent.com/7677050/67256490-e46d3480-f4b9-11e9-833e-cb539fbea012.png)

4、查看ks-installer这个 pod下的容器日志，没有提示出问题；

5、重新编辑ks-installer的cm后，等installer重新执行后，再次运行流水线此问题恢复正常；

**Comment by runzexia** [comment]
现在模块安装失败stdout不会有错误，要进容器里才能看到出现问题的原因。
要在stout/stderr打印错误日志
