### ISSUE TITLE
容器组页面刷新之后翻页按钮计算页码错误

### ISSUE THREAD

**Issue by zheng1** [kubesphere/kubesphere#1125]
![截屏2019-10-2214 35 50](https://user-images.githubusercontent.com/4156721/67263051-805a6880-f4d9-11e9-8ec5-6f4fd12f2021.png)

先点击刷新，地址栏变成图上所示之后再翻到下一页就会进入第11页，预期是第2页。

**Comment by leoendless** [comment]
Fixed
