### ISSUE TITLE
项目 viewer 角色前段相关问题

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1126]
UI 有编辑按钮或菜单

![image](https://user-images.githubusercontent.com/22350668/67264415-98cc8200-f4dd-11e9-930c-ec9cd305d765.png)

![image](https://user-images.githubusercontent.com/22350668/67264463-b26dc980-f4dd-11e9-95df-588866654d52.png)

**Comment by leoendless** [comment]
更新到最新的installer测试看看
