### ISSUE TITLE
grpc服务端的连接使用问题

### ISSUE THREAD

**Issue by xwb2535** [kubesphere/kubesphere#1127]
客户端一直提示，Status(StatusCode=Unavailable, Detail="Trying to connect an http1.x server")  。
dns不支持 http2 的grpc服务。
应用路由的配置，注解已经加上了。
```
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: grpc-key
  namespace: mybztst
  resourceVersion: '327046'
  labels:
    app: grpc-key
  annotations:
    desc: grpc-key
    displayName: grpc-key
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/grpc-backend: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  rules:
    - host: grpc-key.mybztst.10.0.0.219.nip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: grpc-key
              servicePort: 6010
```

**Comment by zryfish** [comment]
https://github.com/kubernetes/ingress-nginx/issues/2497 和这个issue有些类似，可以看下

**Comment by dingyaguang117** [comment]
我在ingress-nginx 里面看到这样的配置：

`server {
                server_name _ ;

                listen 80 default_server reuseport backlog=511 ;
                listen 443 default_server reuseport backlog=511 ssl http2 ;
.....
`

80 端口应该是不支持 http2 的
