### ISSUE TITLE
2.0.2多节点使用过程卡死

### ISSUE THREAD

**Issue by xwb2535** [kubesphere/kubesphere#1128]
发生这种卡死的时候，要怎么排查，是哪一个地方卡？几个节点的资源使用情况都还OK

**Comment by xwb2535** [comment]
![image](https://user-images.githubusercontent.com/20022334/67270806-f36cda80-f4eb-11e9-99a9-403e043f29fc.png)

**Comment by xwb2535** [comment]
发生好几次了。卡死之后，就只能重启节点，但是重启一个，似乎不行，而是必须重启出问题的哪个

**Comment by xwb2535** [comment]
发生好几次了。卡死之后，就只能重启节点，但是重启一个，似乎不行，而是必须重启出问题的哪个

。问题是，我怎么找出有问题的哪个呢

**Comment by wansir** [comment]
需要通过访问日志确认一下请求是在哪里hang住了，通过web console看看请求是超时还是报错了，可以检查一下代理服务器的日志，[外部负载均衡器] -> ks-console -> ks-apigateway
