### ISSUE TITLE
创建 ConfinMap 模态框被重复填充

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1129]
![image](https://user-images.githubusercontent.com/22350668/67271203-a9d0bf80-f4ec-11e9-8534-ec4a5a0fe4f3.png)

![image](https://user-images.githubusercontent.com/22350668/67271225-b35a2780-f4ec-11e9-935f-ba480404c530.png)

**Comment by leoendless** [comment]
可以描述详细些吗

**Comment by huanggze** [comment]
和之前提的模态框重复填充问题一样。这里也有。创建 ConfigMap 时输入的内容，会被缓存。然后我打算新开一个 ConfigMap 时，发现创建新 ConfigMap 对话框里有上一次的内容

**Comment by leoendless** [comment]
表单在未完成提交时是会把数据缓存起来，避免误操作

**Comment by huanggze** [comment]
哦，确实
