### ISSUE TITLE
应用仓库app“最新版”不是最新的

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1130]
这个最新版的应用版本号为啥比其他的小，也不是最小，但不是最大

![image](https://user-images.githubusercontent.com/22350668/67271708-a8ec5d80-f4ed-11e9-8899-cf18c9c069b9.png)

**Comment by whDongRui** [comment]
这里是根据查询versions的返回数据来显示的，一般是把第一条数据设置为最新版本。
返回的数据一般是按更新时间倒序的，但这个我了一个所有数据的update_time全部是一样的。
查询数据的排序规则还得后端帮忙确认一下。

![image](https://user-images.githubusercontent.com/38676269/67273120-6aa46d80-f4f0-11e9-908f-1bbfda72a207.png)

/assign @pengcong06 @wansir

**Comment by whDongRui** [comment]
这个查询我单独加了传参，让查询结果按name来排序，这样显示应该就没问题了。（对于最新版本如果版本号不是最大的除外）

![image](https://user-images.githubusercontent.com/38676269/67274262-a809fa80-f4f2-11e9-983e-58370ed1e274.png)

**Comment by pengcong06** [comment]
在IndexRepo的时候是"一瞬间"完成的,表现出来就像是在同一时刻创建的,所以看到的create_time都是一样的,这边后端在IndexRepo中创建app_version的的时候漏写了一个sequence字段,app_version的排序应该是根据这个字段来的

**Comment by huanggze** [comment]
没完全 fix，还有点小问题

![image](https://user-images.githubusercontent.com/22350668/67539386-8ee09400-f714-11e9-8607-0b8478b515e0.png)

**Comment by huanggze** [comment]
/remove-kind need-to-verify

@whDongRui

**Comment by whDongRui** [comment]
@pengcong06  后端让我把按name排序的逻辑给去掉了，这个bug还得后端看一下，应该没有修复好。

**Comment by huanggze** [comment]
还是有问题

![image](https://user-images.githubusercontent.com/22350668/68460122-ff71cf80-0241-11ea-9b2a-896e2e96d802.png)
