### ISSUE TITLE
部署构建镜像名过长显示问题

### ISSUE THREAD

**Issue by knowwinter** [kubesphere/kubesphere#1131]
部署里的构建镜像名称如果较长会有显示问题，如图
![微信图片_20191022210408](https://user-images.githubusercontent.com/25719964/67288406-82d7b500-f50f-11e9-9d5b-972d8b0a06f2.png)
![微信图片_20191022210708](https://user-images.githubusercontent.com/25719964/67288648-ef52b400-f50f-11e9-871c-b05695e4c149.png)

**Comment by minghaoye** [comment]
will fix in 2.1.0

**Comment by mayuhope** [comment]
经验证已修复
