### ISSUE TITLE
进入应用仓库部署，默认版本为空

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1132]
默认版本为空，需要手动下拉菜单
![image](https://user-images.githubusercontent.com/22350668/67347934-1cd24880-f576-11e9-9072-8bcf913768e2.png)

但是下一步骤中，默认版本被填充“最新版”

![image](https://user-images.githubusercontent.com/22350668/67348022-44291580-f576-11e9-9cb8-7405866f7cda.png)

**Comment by whDongRui** [comment]
这个刚才已经修复了，这个页面是详情页面默认显示的是查询app信息中的latest_app_version,但有的latest_app_version并不在查询versions前10条数据中导致的。

另外部署页面选择版本也有问题，只能选择前10条数据，如果版本数据大于10条后面的就选择不了，刚才也给修复了。

**Comment by huanggze** [comment]
verified
