### ISSUE TITLE
deployment replicas 英文环境scale箭头错位

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1134]
* [ ] 上下箭头有点靠上
![Screen Shot 2019-10-23 at 10 27 06 AM](https://user-images.githubusercontent.com/28859385/67351309-c7029e00-f57f-11e9-9424-a607b4c44514.png)

**Comment by leoendless** [comment]
Fixed

**Comment by rayzhou2017** [comment]
verified
