### ISSUE TITLE
安装路径问题

### ISSUE THREAD

**Issue by dpp814** [kubesphere/kubesphere#1135]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
如何指定安装路径？在哪里可以配置？
**安装环境的硬件配置**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**

**Installer版本**

**Comment by pixiake** [comment]
要改哪个组建的安装路径呢？基本都是容器启动的

**Comment by dpp814** [comment]
> 要改哪个组建的安装路径呢？基本都是容器启动的

我装的是allinone模式。执行得install.sh，默认安装到系统盘中，安装完就花了十几个g，系统盘总共就20g，我挂载了100g的硬盘，如何默认安装到挂载盘中

**Comment by pixiake** [comment]
这个主要是镜像比较大，docker的数据存储路径为/var/lib/docker，可以在安装前将盘挂到这个路径下

**Comment by dpp814** [comment]
> 这个主要是镜像比较大，docker的数据存储路径为/var/lib/docker，可以在安装前将盘挂到这个路径下

你好，请问在哪里配置呢

**Comment by pixiake** [comment]
执行安装前把100G的盘挂载到这个路径并格式化就可以了 ，不用修改配置

**Comment by dpp814** [comment]
> 执行安装前把100G的盘挂载到这个路径并格式化就可以了 ，不用修改配置

好的
