### ISSUE TITLE
邮件服务器页面无法访问，日志报错

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1136]
1、进入平台设置-邮件服务器页面，报错，502 bad  gateway；

2、查看日志，报错：

[root@ks-allinone ~]# kubectl logs notification-deployment-6784869b9b-8ksk4  -n kubesphere-alerting-system
2019-10-23 11:12:38.33202 -CRITICAL- Init database pool failure... (global.go:72)
Error 1049: Unknown database 'notification'

（github上传图片有点问题，这会我上传不上来）

**Comment by rayzhou2017** [comment]
重复  #1133

**Comment by mayuhope** [comment]
已修复
