### ISSUE TITLE
ws viewer can not view the app template

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1137]
* [x] ws viewer should be able to view (no edit/delete rights) app template page.
![Screen Shot 2019-10-23 at 11 21 01 AM](https://user-images.githubusercontent.com/28859385/67354207-1bf5e280-f587-11e9-82e3-6c822ad30fe3.png)

**Comment by wansir** [comment]
@whDongRui @leoendless 帮忙检查一下
![image](https://user-images.githubusercontent.com/8263040/67354899-6166df80-f588-11e9-83c9-ad00c8d8e5b0.png)
![image](https://user-images.githubusercontent.com/8263040/67354924-78a5cd00-f588-11e9-8270-3e7936b24d1b.png)

**Comment by leoendless** [comment]
Fixed

**Comment by rayzhou2017** [comment]
verified
