### ISSUE TITLE
采用默认配置新建一个项目后，在此项目部署示例应用bookinfo时，部署无法运行

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1138]
1、单节点，按照默认配置新建一个项目；
2、在此项目下部署示例应用bookinfo，部署无法运行，提示最小副本不可用：
状态分析(Conditions)
可用性(Available)
状态: False

原因: 最小副本不可用(MinimumReplicasUnavailable)

消息: Deployment does not have minimum availability.

创建进度(Progressing)
状态: True

原因: 副本已更新(ReplicaSetUpdated)

消息: ReplicaSet "reviews-v1-6b58587dbc" is progressing.

3、建议考虑下项目默认配置提供的资源是否要提高一下。

**Comment by leoendless** [comment]
感觉这个是在创建中吧

**Comment by rayzhou2017** [comment]
是不是理解有误？

**Comment by ekkoun** [comment]
这个解决了吗？？我这边也出现了

**Comment by leoendless** [comment]
请进入到具体资源详情里的查看事件或 pod 信息
Deployment does not have minimum availability. 这个 condition 表示 pod 还在启动中，需要等待，是创建过程中的一个正常的 condition.

**Comment by leoendless** [comment]
> 这个解决了吗？？我这边也出现了

请进入到具体资源详情里的查看事件或 pod 信息.
MinimumReplicasUnavailable 这个 condition 表示 pod 还在启动中，需要等待，是创建过程中的一个 condition.

**Comment by ekkoun** [comment]
![image](https://user-images.githubusercontent.com/28840419/102705268-a12a7380-42c0-11eb-8988-d06b2656ffbd.png)   
![image](https://user-images.githubusercontent.com/28840419/102705279-bbfce800-42c0-11eb-944d-b2b8e5bd927b.png)

![image](https://user-images.githubusercontent.com/28840419/102705284-c323f600-42c0-11eb-9ea6-3c8c19cea655.png)
![image](https://user-images.githubusercontent.com/28840419/102705354-d84d5480-42c1-11eb-9e8f-b365b17ca6aa.png)

**Comment by ekkoun** [comment]
还在试用中，结果新手教程都过不了好无奈

**Comment by rayzhou2017** [comment]
我看提示quota不够，你提高一下项目下的quota

**Comment by ekkoun** [comment]
![image](https://user-images.githubusercontent.com/28840419/102705728-a1793d80-42c5-11eb-9394-320b408769ff.png)
现在是最小可用副本不可用~
![image](https://user-images.githubusercontent.com/28840419/102705719-80185180-42c5-11eb-8de7-d6887791ec70.png)

**Comment by ekkoun** [comment]
![Uploading image.png…]()

**Comment by ekkoun** [comment]
![image](https://user-images.githubusercontent.com/28840419/102705846-d9cd4b80-42c6-11eb-9f16-b0ba4f1df12b.png)

**Comment by leoendless** [comment]
查看下项目下的资源配额吧

项目设置->基本信息->资源配额

![image](https://user-images.githubusercontent.com/8739949/102705925-ca023700-42c7-11eb-8c81-e984769505d0.png)

**Comment by ekkoun** [comment]
![image](https://user-images.githubusercontent.com/28840419/102705986-9a076380-42c8-11eb-85bc-325d590794ff.png)

**Comment by ekkoun** [comment]
配置有问题么

**Comment by leoendless** [comment]
`kubectl get resourcequota -n project-demo` 什么结果呢

**Comment by ekkoun** [comment]
![image](https://user-images.githubusercontent.com/28840419/102707913-0e96ce00-42da-11eb-8432-e251bf1820db.png)

**Comment by leoendless** [comment]
重新创建一个项目再部署试试看，或者删除这个 resourcequota 
看你图里的错误说明是项目配额超出了

**Comment by ekkoun** [comment]
可以了，谢谢

**Comment by bear-dubai** [comment]
大佬！后面这个问题怎么解决的呀？我这也遇到这个问题了！菜鸟路过。。。。
