### ISSUE TITLE
Fail to save bookinfo application data

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1139]
**Describe the bug(描述下问题)**
Fail to save bookinfo application data

![Jietu20191023-113712](https://user-images.githubusercontent.com/28883416/67355347-a6d7dc80-f589-11e9-86f0-7851abc8f875.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0 dev
Kubernetes: 

**Environment(环境的硬件配置)**
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

**To Reproduce(复现步骤)**
1. Create sample bookinfo application
2. Go to application list page
3. Edit bookinfo and add a description, then click 'Save"

**Expected behavior(预期行为)**
Save successfully.

**Comment by leoendless** [comment]
Fixed

**Comment by calvinyv** [comment]
verified
