### ISSUE TITLE
no tracing data even if I create some traffic request to bookinfo/product page

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1140]
**Describe the bug(描述下问题)**
no tracing data even if I create some traffic request to bookinfo/product page

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0 dev
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
For example:
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

**To Reproduce(复现步骤)**
1. Deploy bookinfo sample page
2. Create some network traffic to product page
3. Wait for a while and could see data in "流量治理", but no data is show in tracing

**Comment by leoendless** [comment]
@zryfish 看下什么原因吧

**Comment by zryfish** [comment]
最新的installer修复了，需要打开网关的应用治理功能

**Comment by calvinyv** [comment]
verified
