### ISSUE TITLE
how could I see event data in application page

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1141]
**Describe the bug(描述下问题)**
how could I see event data in application page

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0 dev
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**
1. Deploy bookinfo application
2. there's no event data shown in application event page and sub-modules event pages
3. Edit application and sub-modules, and also no event data

**Comment by zryfish** [comment]
there is no event right now because controller didn't write any, @leoendless this tab can be removed

**Comment by leoendless** [comment]
Fixed

**Comment by calvinyv** [comment]
verified
