### ISSUE TITLE
查看磁盘监控页后，点击左上返回上级菜单404

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1142]
**Describe the bug(描述下问题)**
查看磁盘监控页后，点击左上返回上级菜单404
![Jietu20191023-120955](https://user-images.githubusercontent.com/28883416/67356845-32536c80-f58e-11e9-87c8-cd2a683ffbb5.png)
![Jietu20191023-121011](https://user-images.githubusercontent.com/28883416/67356852-37b0b700-f58e-11e9-8874-e2103236cf4b.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0 dev
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**
基础设施 - 存储插件 -qingcloud-csi，点击打开某个pvc详情页，再点击左上返回箭头，404

**Expected behavior(预期行为)**

**Comment by justahole** [comment]
Fixed

**Comment by calvinyv** [comment]
verified
