### ISSUE TITLE
应用商店app部署状态错误

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1143]
* [ ] 部署成功后应用的状态不对
![Screen Shot 2019-10-23 at 12 21 51 PM](https://user-images.githubusercontent.com/28859385/67357423-c1ad4f80-f58f-11e9-9f98-87b7c2e3c4ef.png)
![Screen Shot 2019-10-23 at 12 22 00 PM](https://user-images.githubusercontent.com/28859385/67357445-d4278900-f58f-11e9-883c-fe37ca848e50.png)

**Comment by whDongRui** [comment]
列表中的状态为什么没有显示正确这个需要后端帮忙看一下。

**Comment by zheng1** [comment]
same with #1037

/kind need-to-verify

**Comment by rayzhou2017** [comment]
verified
