### ISSUE TITLE
Missing  Health Checker when create a service by s2i/b2i.

### ISSUE THREAD

**Issue by soulseen** [kubesphere/kubesphere#1144]
**Describe the bug(描述下问题)**

Missing  Health Checker when create a service by s2i/b2i.

![image](https://user-images.githubusercontent.com/16031013/67357237-37fd8200-f58f-11e9-9b7c-0514d865d320.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1 dev
Kubernetes: v1.15.5

**To Reproduce(复现步骤)**
1. Build a new service by b2i/s2i . 
2. in step Container Settings, Missing  Health Checker

**Comment by minghaoye** [comment]
fixed, can verify in next nightly build image
