### ISSUE TITLE
应用商店app部署成功后服务信息缺失

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1145]
* [ ] app部署成功后应用page缺失service信息，比如IP等
![Screen Shot 2019-10-23 at 12 22 00 PM](https://user-images.githubusercontent.com/28859385/67357587-3c766a80-f590-11e9-96db-50e006ee0a87.png)
![Screen Shot 2019-10-23 at 12 25 04 PM](https://user-images.githubusercontent.com/28859385/67357598-4ac48680-f590-11e9-9b9d-1d43a49492d0.png)

**Comment by whDongRui** [comment]
之前详情页面服务信息中只有显示类型的逻辑，没有类型具体值的逻辑，现在已经给加上了。

![image](https://user-images.githubusercontent.com/38676269/67377602-83785600-f5b8-11e9-9919-1a371489f541.png)

**Comment by rayzhou2017** [comment]
verified
