### ISSUE TITLE
App Store issues

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1146]
* [x] The font of introduction and screenshot looks different. Check the word None.
* [x] The tab App Detail --> App Details
* [ ] Categories --> Category since it is for the app only not for all apps categories. Note, do not change other Categories, only change here.
* [ ] Join Time --> Published Date is better
* [ ] The basic info style needs to reformat. It is screwed.
* [ ] Install and Deploy --> Just "Install" or "Deploy" is better.
![Screen Shot 2019-10-23 at 1 37 19 PM](https://user-images.githubusercontent.com/28859385/67361115-51f09200-f59a-11e9-9f62-fd6691082d66.png)

**Comment by whDongRui** [comment]
Fixed, please see in the screenshot.

![image](https://user-images.githubusercontent.com/38676269/67368067-3ccf2f80-f5a9-11e9-9219-f09633a29323.png)

**Comment by rayzhou2017** [comment]
verified
