### ISSUE TITLE
system-workspace 企业空间有部署应用入口

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1147]
system-workspace 不支持部署的话，部署按钮需要屏蔽吗？

![image](https://user-images.githubusercontent.com/22350668/67364423-16f25c80-f5a2-11e9-885d-30cc91f48f95.png)

**Comment by leoendless** [comment]
需要的，我处理下

**Comment by huanggze** [comment]
verified

**Comment by leoendless** [comment]
Fixed
