### ISSUE TITLE
应用模版

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1148]
* [ ] 部署集群要改成部署实例，英文Deploy Cluster改成Deployed Instances
* [ ] 部署实例个数错误，不是0个，我已经部署了一个
* [ ] 更新时间英文改成Updated Time
![Screen Shot 2019-10-23 at 3 23 59 PM](https://user-images.githubusercontent.com/28859385/67368327-b6671d80-f5a9-11e9-91c4-45056760bdbf.png)

**Comment by rayzhou2017** [comment]
我好像明白了，这个地方的计数只是统计测试集群实例个数，不包括应用商店用户部署的个数，那第二个应该不是bug。

**Comment by whDongRui** [comment]
第二个也是bug,后端只统计了active状态的集群应用，其实应该要统计非deleted的集群应用个数。

**Comment by whDongRui** [comment]
两个翻译的问题已经修改了，统计 部署实例个数错误的需要后端帮忙修改。

**Comment by rayzhou2017** [comment]
verified
