### ISSUE TITLE
创建应用模版规范url错误

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1149]
* [ ] 点击url会跳转到ks docs主页
* [x] Start Upload改成Upload
![Screen Shot 2019-10-23 at 3 36 29 PM](https://user-images.githubusercontent.com/28859385/67369028-e2cf6980-f5aa-11e9-8de1-7ee52cd2e88f.png)

**Comment by whDongRui** [comment]
这个应该只有中文文档没有对应的英文文档，这块目前前端是统一处理的。英文下跟的路径是/en，中文下路径是/zh。
