### ISSUE TITLE
权限设计

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#1152]
@calvinyv @wansir @zheng1 @Carlosfengv 
OP 之前的应用上传定位是 OP 内置的开发者角色，ks 2.1 应用上传实际应该是什么角色？ 
目前只能是 ws-admin 角色才有权限上传应用，但开发者或者 ISV 给他 ws-admin 权限是不是太高了？
ws viewer/project operator 应该也不能上传应用

![image](https://user-images.githubusercontent.com/40452856/67378912-955af880-f5ba-11e9-9ccd-6f99c5888cb9.png)

**Comment by wansir** [comment]
worksoace-regular可以上传应用的话会违背现有设计， worksoace-regular 是不能直接管理workspace 层面的资源的，创建应用的功能也不能滥用，因为还有集群层面的公共repo。  @Carlosfengv

**Comment by rayzhou2017** [comment]
理解错了吧，ws regular不能操作ws管理层面的东西，但是资源、应用层面还是有创建能力的，比如创建ns，devops工程，那相应的也应该能创建应用模版吧

**Comment by rayzhou2017** [comment]
配置repo是ws管理功能，regular确实只有读的权限

**Comment by Carlosfengv** [comment]
**问题根源**
目前整个功能流程还不完整，NameSpace中Helm应用编排的功能还没有开发,OP中没有实际的开发者的功能，仅实现了Helm上传。

**功能预期**
完整的操作路径应该是在 NameSace 中创建组成应用（应用编排），测试通过后提交至WorkSpace的企业空间中，企业空间管理员审核通过后即可留在Ws中，甚至可以提交至公共的应用商店中。

**解决办法**
worksoace-regular  允许去上传应用模板的话会早成资源的滥用，应该为只读权限。
允许worksoace-regular 使用应用模板的话可以在应用模板的repo中增加来自企业空间的模板解决。

至于 @FeynmanZhou  说的应用开发者，其实应该下沉至NameSpace中，WorkSpace 对应op的ISV。
当前版本为了适配功能，所以仅允许ISV的管理员上传Helm chart。通过审核可以上应用商店。

**Comment by FeynmanZhou** [comment]
@Carlosfengv @rayzhou2017 @wansir  仅允许 ISV 的管理员上传 Helm chart，也就是只能允许 ws-admin 上传应用吗？ 这个逻辑好奇怪，跟实际的应用场景结合不起来

**Comment by Forget-C** [comment]
作为使用者来说，在不了解内部细节的情况下，我的理解是这样的：
1. workspace的作用是 “隔离” ，所以不论权限还是资源都不要有默认的跨workspace能力。
2. 多租户模式下，有的用户可能并不希望helm应用公开，而有的用户会希望公开自己的应用，所以我认为我区分helm仓库，分为集群级的公共仓库和企业空间级的私有仓库，私有仓库应用提交到公共仓库需要有审批操作。
3. 个人理解企业空间中主要工作角色应该还是 regular ，所以要放权下去，可以考虑是否增加审批，或者将 regular 权限、helm应用与项目关联。

**Comment by Forget-C** [comment]
另外我觉得支持用户密码验证得helm仓库很重要。

**Comment by Carlosfengv** [comment]
首先我认为大家说的都没错，可是忽略了一个很重要的问题，这里整个流程并**没有做完**；
OP 只是单纯的移植到了ks，并没有做一些定制化的开发来配合ks的整个功能逻辑，因此会有些地方有不完美的地方；
3.0 中会在NameSpace级别中增加应用开发的功能，开发者可以上传（审核）给企业空间管理员（ISV管理员）。企业空间管理员再上传给应用商店，这样形成一个完整个的功能闭环。

**Comment by FeynmanZhou** [comment]
@Carlosfengv @wansir  所以目前还是把应用上传的权限 仅开放给 ws-admin 是么？

**Comment by rayzhou2017** [comment]
Please check if this issue is still in 3.0

**Comment by zheng1** [comment]
In 3.0:
1. workspace-self-provisioner can view repo and app template
2. supported HTTP basic auth based repo
