### ISSUE TITLE
应用商店部署应用无创建者

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1153]
* 创建者是空的
![Screen Shot 2019-10-23 at 5 41 23 PM](https://user-images.githubusercontent.com/28859385/67380153-7eb5a100-f5bc-11e9-9d41-1cb840681159.png)

**Comment by whDongRui** [comment]
之前改这个页面接口进像你反馈过的，这个详情返回信息分为cluster,app，version这三类信息了，但这个里面没有创建者的信息

**Comment by wansir** [comment]
@pengcong06  确认一下createCluster 接口 context 的sender 会不会写入 owner 字段
https://github.com/kubesphere/kubesphere/blob/master/pkg/models/openpitrix/applications.go#L360-L365

**Comment by rayzhou2017** [comment]
这个fix是错误的，创建者应该是登录用户
<img width="1226" alt="Screen Shot 2019-11-06 at 12 38 05 PM" src="https://user-images.githubusercontent.com/28859385/68268717-4b7e1200-0092-11ea-9e5a-34411fff2c0e.png">
