### ISSUE TITLE
创建有状态副本集后，无法修改Volume挂载配置

### ISSUE THREAD

**Issue by soulseen** [kubesphere/kubesphere#1154]
**Describe the bug(描述下问题)**

按照[文档](https://kubesphere.io/docs/v2.1/zh-CN/quick-start/mysql-deployment/)步骤创建 mysql StatefulSet，创建完成后无法在`编辑配置模版`下修改 `存储卷` 配置。

**Versions used(KubeSphere/Kubernetes的版本)**

KubeSphere: 2.1.0 dev
Kubernetes: v1.15.5

**Environment(环境的硬件配置)**

1 masters:  4cpu/8g
2 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**
1. 按照[文档](https://kubesphere.io/docs/v2.1/zh-CN/quick-start/mysql-deployment/)步骤创建 mysql StatefulSet
2. 创建完成后，点击 `更多操作`
3. 点击 `编辑配置模版`
4. 点击 `存储卷`，修改存储卷模版
![image](https://user-images.githubusercontent.com/16031013/67380489-000d3380-f5bd-11e9-83ef-39946dd5c4b1.png)
5. 修改挂载配置，比如修改只读权限，然后点击`保存`。
6. 无法点击`确认`保存修改的配置。
![image](https://user-images.githubusercontent.com/16031013/67380424-e2d86500-f5bc-11e9-8903-1f92e1c51d7f.png)

**Expected behavior(预期行为)**
可以正常保存修改的存储卷配置。

**Comment by soulseen** [comment]
/kind bug
/milestone 2.1.0
/area/console
/assign @leoendless

**Comment by leoendless** [comment]
Fixed
