### ISSUE TITLE
sonarqube安装不上

### ISSUE THREAD

**Issue by dpp814** [kubesphere/kubesphere#1155]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
你好，默认安装allinone模式，安装最后失败，报错如下：
fatal: [ks-allinone]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm upgrade --install ks-sonarqube /etc/kubesphere/sonarqube/sonarqube-0.13.5.tgz -f /etc/kubesphere/sonarqube/custom-values-sonarqube.yaml --namespace kubesphere-devops-system", "delta": "0:00:01.430238", "end": "2019-10-23 18:42:44.490158", "msg": "non-zero return code", "rc": 1, "start": "2019-10-23 18:42:43.059920", "stderr": "Error: release ks-sonarqube failed: persistentvolumeclaims \"ks-sonarqube-postgresql\" is forbidden: Internal error occurred: 2 default StorageClasses were found", "stderr_lines": ["Error: release ks-sonarqube failed: persistentvolumeclaims \"ks-sonarqube-postgresql\" is forbidden: Internal error occurred: 2 default StorageClasses were found"], "stdout": "Release \"ks-sonarqube\" does not exist. Installing it now.", "stdout_lines": ["Release \"ks-sonarqube\" does not exist. Installing it now."]}
这个该如何解决
**安装环境的硬件配置**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**

**Installer版本**

**Comment by runzexia** [comment]
这个提示看起来是有两个默认的存储卷类型。
需要调整为一个
https://kubernetes.io/zh/docs/tasks/administer-cluster/change-default-storage-class/

**Comment by dpp814** [comment]
> 这个提示看起来是有两个默认的存储卷类型。
> 需要调整为一个
> https://kubernetes.io/zh/docs/tasks/administer-cluster/change-default-storage-class/

fatal: [ks-allinone]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm upgrade --install ks-sonarqube /etc/kubesphere/sonarqube/sonarqube-0.13.5.tgz -f /etc/kubesphere/sonarqube/custom-values-sonarqube.yaml --namespace kubesphere-devops-system", "delta": "0:00:00.224315", "end": "2019-10-24 09:14:23.144059", "msg": "non-zero return code", "rc": 1, "start": "2019-10-24 09:14:22.919744", "stderr": "Error: UPGRADE FAILED: \"ks-sonarqube\" has no deployed releases", "stderr_lines": ["Error: UPGRADE FAILED: \"ks-sonarqube\" has no deployed releases"], "stdout": "", "stdout_lines": []}

已经设置了一个默认存储卷类型，还是报错

**Comment by dpp814** [comment]
> 这个提示看起来是有两个默认的存储卷类型。
> 需要调整为一个
> https://kubernetes.io/zh/docs/tasks/administer-cluster/change-default-storage-class/

可以了，需要卸载再重新安装
