### ISSUE TITLE
ws regular进不去ws

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1161]
* [ ] 看不到进去ws的入口
![Screen Shot 2019-10-24 at 10 09 01 AM](https://user-images.githubusercontent.com/28859385/67447399-507ca380-f646-11e9-902b-3972d4a21cc7.png)
![Screen Shot 2019-10-24 at 10 08 49 AM](https://user-images.githubusercontent.com/28859385/67447427-65593700-f646-11e9-88ef-b5d2e5ae9fef.png)

**Comment by leoendless** [comment]
by design

**Comment by rayzhou2017** [comment]
这是什么原因？ws viewer能进去，regular反而进不去？

**Comment by wansir** [comment]
workspace-viewer 可以看到wokrspace 层级更多的资源，现在还没有把应用模板、应用仓库相关的操作权限开放给 workspace-regular， workspace-regualr 只能看到自己在当前workspace下的namespace 和 devops project，所以这里看到的是一个独立的列表以示区分

**Comment by rayzhou2017** [comment]
现在是regular都没有入口进ws

**Comment by wansir** [comment]
这里应该是从设计上就是为了减少层级，进到ws 里看能到的也只是自己的项目和工程列表。

**Comment by wansir** [comment]
因为 workspace-regular 看不到 workspace 层级的概览/监控

**Comment by leoendless** [comment]
ws regular 在 workspace层级里 没有什么信息要展示的

**Comment by rayzhou2017** [comment]
app template不是在ws级别吗？

**Comment by wansir** [comment]
不希望ws-regular可以创建/管理 app template，现在app template 是属于 ws 这个层级的公共资源（而不是跟用户关联）， 需要通过权限来控制。 计划在2.1.1  修复这个问题

**Comment by rayzhou2017** [comment]
verified
