### ISSUE TITLE
ws viewer看不到ws下的devops工程

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1162]
* [ ] 按照设计ws viewer是应该有ws下所有资源的读权限，但devops看不到
![Screen Shot 2019-10-24 at 10 15 40 AM](https://user-images.githubusercontent.com/28859385/67447699-44ddac80-f647-11e9-8d4d-db86bb1925b6.png)

![Screen Shot 2019-10-24 at 10 15 36 AM](https://user-images.githubusercontent.com/28859385/67447717-53c45f00-f647-11e9-849c-9b8c21b05f53.png)
![Screen Shot 2019-10-24 at 10 15 09 AM](https://user-images.githubusercontent.com/28859385/67447723-58891300-f647-11e9-89bc-fcdca80d5906.png)

**Comment by runzexia** [comment]
要 3.0.0 解决了
与 https://github.com/kubesphere/kubesphere/issues/704 是同一原因造成

**Comment by rayzhou2017** [comment]
verified
