### ISSUE TITLE
安装前增加配置文件检测

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#1163]
建议安装前，增加配置文件检测。包括但不限于以下内容：
1.主机是否可用，包括网络是否可用以及密码是否正确。
2.区域配置是否正确。当使用qingcloud存储时，错误的区域配置不会影响安装过程，但是安装完成后无法创建磁盘。
3.qingcloud csi参数配置。当使用qingcloud存储时，错误的配置不会影响安装过程，但是安装完成后无法创建磁盘。例如qingcloud_minSize的值必须大于0，但是配置为0安装依然可以成功，但是安装完成后无法创建磁盘，且此参数在安装完成后不易修改。

/area installation

**Comment by pixiake** [comment]
@wnxn qingcloud csi如何预先检测上述情况，qingcloud-cli吗？可以提供下检查步骤

**Comment by wnxn** [comment]
> @wnxn qingcloud csi如何预先检测上述情况，qingcloud-cli吗？可以提供下检查步骤

# 预先检查方法
1. 从 vars.yaml 配置文件提取出 qingcloud cli 所需要的 config 文件

1. 用 qingcloud cli 创建硬盘并挂载到主机上, 必须能够成功挂载，测完后需要卸载和删除测试硬盘https://docs.qingcloud.com/product/cli/#%E5%91%BD%E4%BB%A4%E5%88%97%E8%A1%A8
  ```
  qingcloud iaas create-volumes
  qingcloud iaas attach-volumes
  ```

3. maxSize, minSize, stepSize 可以按照 type 值来检查这三个值，不正确告警即可 https://github.com/yunify/qingcloud-csi/blob/master/docs/user-guide-zh.md#type-maxsize-minsize-stepsize 。qingcloud csi v1.1.0-rc.4 支持用户不填写 maxSize, minSize, stepSize ，插件会补上默认值。
# 其他注意
- volumeBindingMode 应在 vars.yaml 中暴露出来，默认 Immediate。支持 Immediate 和 WaitForFirstConsumer
- storageclass tags 参数应在 vars.yaml 中暴露出来，允许用户不填写。
