### ISSUE TITLE
编辑项目配额

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1165]
* [x] cpu,memory右边的那个拖拽按钮(设置limit)非常不好使
![Screen Shot 2019-10-24 at 10 59 11 AM](https://user-images.githubusercontent.com/28859385/67449608-4f9b4000-f64d-11e9-8bff-68a37595dadd.png)

**Comment by leoendless** [comment]
能具体描述下吗

**Comment by rayzhou2017** [comment]
鼠标点中圆点，往左边拖，拖不动

**Comment by leoendless** [comment]
Fixed

**Comment by rayzhou2017** [comment]
还是有点不流畅，尤其是在最右边开始拖的时候，算了，这个问题不大

**Comment by leoendless** [comment]
右侧有一段距离都是不限制，相当于一个磁吸效果
