### ISSUE TITLE
应用部署按钮没了

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1166]
![image](https://user-images.githubusercontent.com/22350668/67450151-0f3cc180-f64f-11e9-98a7-afeb00e4316d.png)

![image](https://user-images.githubusercontent.com/22350668/67450162-1663cf80-f64f-11e9-875c-335f888bfd05.png)

**Comment by leoendless** [comment]
@wansir 需要将项目里的applications create 权限整理出来

**Comment by wansir** [comment]
https://github.com/kubesphere/ks-installer/pull/328

**Comment by huanggze** [comment]
verified
