### ISSUE TITLE
服务组件列表的文案缺失

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#1167]
有些组件独立出来后，多处需要补充文案，否则看起来不整齐
![image](https://user-images.githubusercontent.com/40452856/67450980-ad318b80-f651-11e9-9513-c76f8ef192ee.png)

**Comment by leoendless** [comment]
@zryfish @FeynmanZhou 提供下中英文文案吧

**Comment by soulseen** [comment]
文案勘误建议修改：
1. `s2i` 可改为大写 `S2I`
2. `全声明周期管理` 改为 `全生命周期管理`
3. `jenkins` `Jenkins` 大小写统一

![image](https://user-images.githubusercontent.com/16031013/67651636-f0a33700-f97c-11e9-9fd1-0142929ae573.png)

**Comment by rayzhou2017** [comment]
Please verify in 3.0

**Comment by FeynmanZhou** [comment]
Verified: https://github.com/kubesphere/console/pull/1193
