### ISSUE TITLE
关于Devops工程流水线问题

### ISSUE THREAD

**Issue by dpp814** [kubesphere/kubesphere#1173]
你好，我在流水线配置git仓库和svn仓库得时候，工程目录下都有jenkinsfile文件，而且名字都是对应上的，但是扫描远程分支得时候就报"未找到 Pipeline 配置文件"，这个该如何解决

**Comment by dpp814** [comment]
> 大小写注意了吗？有截图吗？
![image](https://user-images.githubusercontent.com/22487387/67470097-cf420280-f67f-11e9-9b68-c362af0e4993.png)
![image](https://user-images.githubusercontent.com/22487387/67470126-db2dc480-f67f-11e9-8359-b11c45706d1e.png)

**Comment by dpp814** [comment]
> 大小写注意了吗？有截图吗？

![image](https://user-images.githubusercontent.com/22487387/67470205-f567a280-f67f-11e9-8dc6-b167f099c4ca.png)
![image](https://user-images.githubusercontent.com/22487387/67470219-f8fb2980-f67f-11e9-93ef-ca7145662042.png)

**Comment by dpp814** [comment]
> 向日葵、tv12等远程桌面的方式也可以

发你邮箱了，不过快要下班了，要不明天吧

**Comment by runzexia** [comment]
好的👌🏻

**Comment by dpp814** [comment]
> 好的👌🏻

啥时候有时间，帮我看下？

**Comment by runzexia** [comment]
这个地方是single_svn被处理成svn导致的，需要前端fix下
/cc @minghaoye

**Comment by minghaoye** [comment]
single_svn的问题2.1已修复，git仓库测试是没问题的

**Comment by runzexia** [comment]
fix in 2.1.0-2019-10-27
/close
