### ISSUE TITLE
企业空间的异常容器组数显示变化较慢

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1174]
1、新建一个部署，配置错误，使得它的pod无法运行；

2、删除该部署；

3、使用该项目admin登录系统，查看异常容器组，发现仍然显示了1个，应该是0个；
![image](https://user-images.githubusercontent.com/7677050/67469632-124fa600-f67f-11e9-8c83-e790d9340d60.png)
![image](https://user-images.githubusercontent.com/7677050/67469647-14b20000-f67f-11e9-8980-a9cfc787b989.png)

**Comment by huanggze** [comment]
后端采集间隔设的 1min，再加上前端周期性调 api。极端情况可能有1分多钟。当时体验的迟延有多大？

**Comment by mayuhope** [comment]
差不多2分钟左右

**Comment by mayuhope** [comment]
经过沟通延迟可以接受，关闭此issue
