### ISSUE TITLE
用户已经不在企业空间成员里了，但还是显示他为企业空间管理员

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1175]
1、使用admin用户将用户user1移除出企业空间space-user1；
![image](https://user-images.githubusercontent.com/7677050/67474757-973ebd80-f687-11e9-8ce6-246528bc14c9.png)

2、列表中该企业空间的管理员仍显示为user1，建议修改此处的文案，改为创建者更合适：
![image](https://user-images.githubusercontent.com/7677050/67474732-8ee68280-f687-11e9-88c5-69755889ba6c.png)

**Comment by wansir** [comment]
@leoendless  @Carlosfengv  这里的文案改成创建者更合适

**Comment by leoendless** [comment]
不太好吧，正常使用情况下创建者都会是超级管理员或者企业空间管理员

**Comment by leoendless** [comment]
这里建议 admin 用户将其它用户指定为该企业空间管理员

**Comment by wansir** [comment]
这里建议不做改动， role/rolebinding/user ， 目前都是松耦合，应该延续k8s 这种资源管理的方式

**Comment by Carlosfengv** [comment]
不太好，可能会被认为是个bug；
建议修改
上级管理员移除企业空间或者ns 管理员，在移除的过程中指定一个新的管理员（不指定的话默认为当前的上级管理员）；

**Comment by leoendless** [comment]
建议移除这个manager 信息吧，目前的权限规则里没有一个这样的存在，需要查看相关人员信息的话可以在 企业空间的 members 里查看

并且如果有多个 workspace-admin 时，逻辑也不好处理

**Comment by leoendless** [comment]
Fixed

**Comment by mayuhope** [comment]
已验证
