### ISSUE TITLE
需求完善

### ISSUE THREAD

**Issue by fairychild1** [kubesphere/kubesphere#1176]
1.监控里面，node允许的request值和limit值看不出来，这样一个node满了，pod调度不上去也不知道为什么，node当前跑了的pod消耗的资源总量，占node的limit总量的多少，无法得知；

    2.挂掉的pod，上一次在哪个node上面，日志里没法区分，也无法知道。正常的pod产生的日志，在通过日志跳转到pod后，能看到pod是在哪个node上，但是挂掉的pod就不行了，是否可以通过annotation或者label，把node上的pod产生的日志都自动带上一个标签，这样既是挂掉的pod产生的日志，也能知道这个pod之前在哪个node上。这个需求方便用户排查node的问题；

    3.日志增加导出功能，这个需求记得其他行里碰到过，不知道咱们后面的版本计划里，是否会支持这个；

    4.harbor的clair漏洞库是否支持离线，怎么导入?

**Comment by rayzhou2017** [comment]
日志导出2.1.0有命令行，UI需要到3.0提供，1和2都在3.0提供。4要看看habor的情况了

**Comment by huanggze** [comment]
日志导出在 2.1 有一键操作。但默认限制 10w 条日志（通常不超过 100M）。大体量的日志导出或备份建议跑一个 elasticdump Job 或其他办法

![image](https://user-images.githubusercontent.com/22350668/67486956-9a45a800-f69f-11e9-8871-ae496160b5f1.png)

![image](https://user-images.githubusercontent.com/22350668/67486986-ac274b00-f69f-11e9-82a2-f2355b25d578.png)

**Comment by rayzhou2017** [comment]
Please check if they are fixed in 3.0

**Comment by zryfish** [comment]
Can import vulnerability data to offline harbor now, check it out https://goharbor.io/docs/1.10/administration/vulnerability-scanning/import-vulnerability-data/

**Comment by zryfish** [comment]
/close
The first, second and third issue already supported in v3.0
