### ISSUE TITLE
容器终端数据一行没显示全

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1178]
这一行后面应该还有很多内容，没显示全

![image](https://user-images.githubusercontent.com/22350668/67491760-f9a7b600-f6a7-11e9-8848-1175908bb61a.png)

![image](https://user-images.githubusercontent.com/22350668/67491809-075d3b80-f6a8-11e9-80a1-c539439e696c.png)

**Comment by huanggze** [comment]
而且显示的内容多少，受浏览器缩放比例影响

![image](https://user-images.githubusercontent.com/22350668/67492016-628f2e00-f6a8-11e9-80a5-38da0369a92b.png)

**Comment by leoendless** [comment]
这个暂不支持吧，需要看下 xterm.js 是否支持浏览器的缩放

**Comment by rayzhou2017** [comment]
Is this problem still existing in 3.0?

**Comment by huanggze** [comment]
not fixed

**Comment by zryfish** [comment]
It's not a bug, content returned from server based on the client window size, see the example below
![截屏2020-08-18 16 27 07](https://user-images.githubusercontent.com/3326354/90489422-d9357480-e16f-11ea-9d7f-170ce849e747.png)
![截屏2020-08-18 16 28 02](https://user-images.githubusercontent.com/3326354/90489470-ea7e8100-e16f-11ea-8e61-59966818f68e.png)
