### ISSUE TITLE
私有harbor仓库滚动升级的时候证书失败，自定义证书

### ISSUE THREAD

**Issue by xwb2535** [kubesphere/kubesphere#1183]
![image](https://user-images.githubusercontent.com/20022334/67537102-913ef000-f70c-11e9-87b9-331b6cb0ae1c.png)

自己搭建的harbor服务器，没有用收费的证书，自己弄了一个。然后按照上面的文档，配置了一个属性。第一次pull镜像OK，应用成功创建，第二次修改标签版本号之后滚动升级，就提示
Failed to pull image "harbor.ivinbo.com/mybztst/api-open:xwb.01.02": rpc error: code = Unknown desc = Error response from daemon: Get https://harbor.ivinbo.com/v2/: x509: certificate signed by unknown authority。 
也就是第一次更新的时候已经不会有证书错误了，第二次就有。

**Comment by pixiake** [comment]
@hlwanghl

**Comment by hlwanghl** [comment]
--insecure-registry 需要在所有 KubeSphere 节点主机配置。
