### ISSUE TITLE
应用商店页面表格错位

### ISSUE THREAD

**Issue by zheng1** [kubesphere/kubesphere#1184]
![截屏2019-10-2510 04 34](https://user-images.githubusercontent.com/4156721/67537679-feec1b80-f70e-11e9-9bb9-211fa886915d.png)

/area app-management
/kind bug
/milestone 2.1.0
/assign @whDongRui

**Comment by whDongRui** [comment]
你这个环境不是最新前端代码，我这边看显示是好的，你更新一下前端代码再验证一下。

![image](https://user-images.githubusercontent.com/38676269/67537807-93ef1480-f70f-11e9-9e98-055d614784bc.png)

**Comment by zheng1** [comment]
Verified
