### ISSUE TITLE
应用商店翻译问题

### ISSUE THREAD

**Issue by zheng1** [kubesphere/kubesphere#1186]
目前我们有几个概念搞混淆了. 需要在这里讨论一下:

我认为在KS中有以下的概念和解释:
1. App Template, 应用模板, 对应OP中的App(应用)
2. Application, 应用, 对应OP中的Cluster(集群)
3. App Store, 应用商店, 对应OP中的App Store(应用商店), 解释是"一个应用分发平台, 一个允许用户浏览和部署应用的商店"

@Carlosfengv @wansir   请帮看下这样的理解是否与你们之前的设计有冲突

基于这种理解, 下面有些地方是有歧义的. 

![截屏2019-10-2510 23 10](https://user-images.githubusercontent.com/4156721/67539150-d31f6480-f713-11e9-9e97-8d7bfa5dfc24.png)
![截屏2019-10-2510 32 20](https://user-images.githubusercontent.com/4156721/67539152-d4e92800-f713-11e9-9091-7a582d39d994.png)
![截屏2019-10-2510 28 38](https://user-images.githubusercontent.com/4156721/67539154-d4e92800-f713-11e9-95a7-acaf96e61f3d.png)
![截屏2019-10-2510 24 00](https://user-images.githubusercontent.com/4156721/67539156-d581be80-f713-11e9-9514-1d20064638e0.png)

/area app-management
/kind bug
/milestone 2.1.0
/assign @whDongRui

**Comment by zheng1** [comment]
- [ ] "Upload Helm Config File" 应当是 "Upload Helm Chart Package"

**Comment by Carlosfengv** [comment]
赞👍

**Comment by whDongRui** [comment]
有些翻译在之前的issue已经改过了, 刚按截图中标注的翻译都改过了。
配置包支持的格式tgz,tar.gz应该是都支持的吧，这两个是一样的。
有时间的话可以帮忙看一下应用管理那块的页面翻译还有没有什么问题，谢谢了。

**Comment by zheng1** [comment]
Verified.
