### ISSUE TITLE
项目，基本信息中，资源配额信息不准确

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#1188]
版本：2.1-dev

1，创建示例应用之后，查看项目基本信息，cpu 和 mem 使用量都为 0

![image](https://user-images.githubusercontent.com/43693241/67539409-9ef87380-f714-11e9-95e5-af6cb3a005ae.png)

2，点击【项目管理】，限制项目配额之后，实际使用量不准确，数值过大（仅部署示例应用）

![image](https://user-images.githubusercontent.com/43693241/67539521-06162800-f715-11e9-8dbc-47e475d5ad55.png)

/area monitoring
/area console

/kind bug

/assign @leoendless 
/assign @huanggze

**Comment by leoendless** [comment]
@wansir @zryfish 看下这个问题吧，

一个是未设置配额时，limits.cpu，requests.cpu 值为空

二可能是 bookinfo 的 limits 设置太大 ？

**Comment by shaowenchen** [comment]
从监控中心，可以看到监控数据。

![image](https://user-images.githubusercontent.com/43693241/67540136-e67fff00-f716-11e9-8339-e6543b2a019d.png)

**Comment by leoendless** [comment]
@shaowenchen 这是两种不同的概念，一个是 cpu 最大允许使用的配额统计，一个是 当前所有资源cpu使用量的统计

**Comment by shaowenchen** [comment]
那就是这里显示的是 limit 值？并不是实际使用值。

这里按照文案理解，很容易想到的是监控实时数据。同时，cpu、mem 下面同列数据，显示的 pod svc  等都是显示的实际使用额度。

**Comment by leoendless** [comment]
所以这里写的是配额

**Comment by shaowenchen** [comment]
属于产品设计与用户理解的偏差

/close
