### ISSUE TITLE
应用仓库同步多余的报错

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1189]
刚添加 repo，应该在自动同步中。这里报错是多余的把？即使同步中，点击同步应该不会报错才对

![image](https://user-images.githubusercontent.com/22350668/67539950-5641ba00-f716-11e9-8eb5-314ff2f716a9.png)

**Comment by zheng1** [comment]
@Carlosfengv  @whDongRui  这里其实缺一个repo event的list页面, 让用户能方便看到历史执行记录和当前状态

**Comment by rayzhou2017** [comment]
这个现在能加上吗？如果需要两天以上的时间就挪到下一给版本。

**Comment by pengcong06** [comment]
kind/need-to-verify

**Comment by huanggze** [comment]
仍然存在。

复现方法是：添加 repo 好后，立刻去点同步

![image](https://user-images.githubusercontent.com/22350668/74134500-a5f4b480-4c25-11ea-8676-dd1b19bfa404.png)

**Comment by huanggze** [comment]
verified
