### ISSUE TITLE
缺少版本号填写规范文案

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1190]
![image](https://user-images.githubusercontent.com/22350668/67540160-ff88b000-f716-11e9-821c-7e660c741899.png)

**Comment by whDongRui** [comment]
/assign @whDongRui 

这个是前端进行的版本号格式验证，我来改一下验证的提示文字吧

**Comment by whDongRui** [comment]
这个我已经给加上了

![image](https://user-images.githubusercontent.com/38676269/67566311-097fd280-f75a-11e9-82d4-48fb4bb6828a.png)

![image](https://user-images.githubusercontent.com/38676269/67566320-113f7700-f75a-11e9-855e-a09d38bd93d4.png)

**Comment by whDongRui** [comment]
/kind need-to-verify
@huanggze
