### ISSUE TITLE
异常pod计数 UI 绘图间隔太大，导致间隔内的数据漏了

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1191]
目前 UI 展示是 10 分钟一个段。如果这 10分钟内有 pod 异常的变化，在 UI 上会看不出来。比如下图，其中有个 10分钟段内应该有一个 异常pod 计数

![image](https://user-images.githubusercontent.com/22350668/67540437-f3e9b900-f717-11e9-8d7f-bceacfe370cf.png)

**Comment by Carlosfengv** [comment]
目前后端支持的最小时间间隔多少？

**Comment by huanggze** [comment]
30s

**Comment by Carlosfengv** [comment]
建议修改时间间隔为 30s  
/assign @justahole

**Comment by justahole** [comment]
现在是10个小时，10分钟间隔。这样不香吗 @huanggze
