### ISSUE TITLE
应用部署报 data too long 错误，

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1192]
虽然报错，但前端有创建显示（等待中）

![image](https://user-images.githubusercontent.com/22350668/67540745-1a5c2400-f719-11e9-8052-8255a6cdf182.png)

![image](https://user-images.githubusercontent.com/22350668/67540759-3069e480-f719-11e9-8826-17e5e0c96a74.png)

**Comment by huanggze** [comment]
@whDongRui 另外，报错后，应用仍显示在 UI 上（图中框起来的地方，以等待中的状态展示）。这是前段要 fix 吗？

**Comment by zheng1** [comment]
已修复, 等这个build https://travis-ci.org/openpitrix/openpitrix/builds/603773967 结束后可以通过
```
cd /etc/kubesphere/openpitrix/hyperpitrix-kubernetes/scripts && ./deploy-k8s.sh -c
```
来重新执行dbctrl更新数据库, 更新后问题会被修复.

/kind need-to-verify

**Comment by huanggze** [comment]
好的，可能前端也要同步改下？我 @whDongRui 和你们问下

**Comment by huanggze** [comment]
verified
