### ISSUE TITLE
邮箱配置，SSL 开启报错、邮件中图片无法显示

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#1193]
版本：2.1-dev

1，配置 QQ 邮箱，可以发送邮件，但邮件中的图片无法正常显示。

查看邮件原文发现，图片地址 404 ，kubesphere.io/static/logo.58fe8884.svg

![image](https://user-images.githubusercontent.com/43693241/67541065-2eecec00-f71a-11e9-9a52-927b14a863b1.png)

2，邮件开启 SSL ，发送测试邮件失败

![image](https://user-images.githubusercontent.com/43693241/67541090-4c21ba80-f71a-11e9-97c7-43a55d8023cb.png)

3，测试邮件内容没有国际化

4，建议在缺省配置中，让 smtp 用户与发件人邮件，保持一致。以他人的名义，发送邮件不合理，同时，公有邮箱不允许这么做。

![image](https://user-images.githubusercontent.com/43693241/67541307-116c5200-f71b-11e9-8b8d-9c04b2864e28.png)

/area notification
/kind bug
/assign @huojiao2006

**Comment by runzexia** [comment]
![image](https://user-images.githubusercontent.com/31230341/67552621-fb23bd80-f73d-11e9-8c52-95cfa41065ba.png)
yunify邮箱也不可以

**Comment by rayzhou2017** [comment]
测试email如果国际化比较麻烦就先用英文

**Comment by justahole** [comment]
发件人邮箱是为了考虑 发件人邮箱 与 SMTP 用户不同值的情况而考虑的。如果想要保持两个值一致则不填发件人邮箱即可。

**Comment by huojiao2006** [comment]
建议在缺省配置中，让 smtp 用户与发件人邮件，保持一致.
如果发件人邮件不填的话，就是用的smtp用户。
这里单独给一个发件人邮件，是因为有些邮件服务器的SMTP用户和发件人邮件 不是同一个值。

**Comment by huojiao2006** [comment]
邮件开启 SSL ，发送测试邮件失败
已经fixed

**Comment by huojiao2006** [comment]
配置 QQ 邮箱，可以发送邮件，但邮件中的图片无法正常显示。
前端应该已经fix了 @justahole

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/67843464-fd6b8a80-fb36-11e9-9db0-d3c9eb952efe.png)

SSL 发送测试邮件成功。

/close
