### ISSUE TITLE
没有删除 PVC 的入口了，之前还有

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1194]
一周前的版本还有

![image](https://user-images.githubusercontent.com/22350668/67541654-5f358a00-f71c-11e9-97a5-bae1cceb7996.png)

10月25日早上的 installer 没了

![image](https://user-images.githubusercontent.com/22350668/67541836-ff8bae80-f71c-11e9-9d14-6cd608d1d008.png)

**Comment by huanggze** [comment]
还没有再复现，先放一放

**Comment by rayzhou2017** [comment]
我没复现，看是不是角色的问题
