### ISSUE TITLE
appstore url

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1196]
* [ ] path是apps，这个容易混淆，最好改成appstore
![Screen Shot 2019-10-25 at 12 32 34 PM](https://user-images.githubusercontent.com/28859385/67543391-bdb23680-f723-11e9-9f61-e32e3b1253d7.png)

* [ ] 最新上架url param 不是latest，改成new比较好
![Screen Shot 2019-10-25 at 12 39 11 PM](https://user-images.githubusercontent.com/28859385/67543555-927c1700-f724-11e9-9f6f-106fbc72a494.png)

**Comment by whDongRui** [comment]
应用商店的url都按上面说的已经改了。

**Comment by leoendless** [comment]
url 这个如果是 appstore, 那详情就会是 appstore/app-xxx , 看起来不符合 rest 规范

apps 的话与 appcenter 里方式一致，应该是很容易理解的吧

**Comment by rayzhou2017** [comment]
也是，path可能是应该是apps，如果需要改的话应该是类似于appstore.xxxx.com/apps

**Comment by rayzhou2017** [comment]
我需要更新哪个pod才能看到这个更新？ 好像不是ks-console

**Comment by rayzhou2017** [comment]
第二个还没有fix

**Comment by leoendless** [comment]
@whDongRui 看下第二个问题吧

**Comment by whDongRui** [comment]
@rayzhou2017 我后来又提了一个mr来修复第二个问题的，再去验证一下吧，应该已经解决了。

**Comment by rayzhou2017** [comment]
verified
