### ISSUE TITLE
登录url错误

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1200]
* [ ] "登录遇到问题?" url不对
* [ ] 选择“记住我”好像也不起作用
![Screen Shot 2019-10-25 at 1 29 28 PM](https://user-images.githubusercontent.com/28859385/67545450-af681880-f72b-11e9-939e-2fe7985ac93e.png)

**Comment by leoendless** [comment]
建议这里的登录与 login 页面统一为一个 @Carlosfengv

**Comment by Carlosfengv** [comment]
去掉Modal 的登录方式吧

**Comment by leoendless** [comment]
Fixed

**Comment by rayzhou2017** [comment]
verified
