### ISSUE TITLE
dashboard页项目加link

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1201]
* [x] 既然现在已经提供了全局项目功能，dashboard页面的项目最好加一个link过去
![Screen Shot 2019-10-25 at 1 49 36 PM](https://user-images.githubusercontent.com/28859385/67546243-77160980-f72e-11e9-885c-19cbce686380.png)

**Comment by leoendless** [comment]
Fixed

**Comment by rayzhou2017** [comment]
verified
