### ISSUE TITLE
应用管理文案

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1202]
* [ ] uncategorized这个地方没有翻译
![Screen Shot 2019-10-25 at 2 02 40 PM](https://user-images.githubusercontent.com/28859385/67546957-3d460280-f730-11e9-8726-40ca9e098ed7.png)

**Comment by whDongRui** [comment]
未分类是后端查询app返回的数据，这个地方忘记加转换了，刚给经修复了。

![image](https://user-images.githubusercontent.com/38676269/67549498-fad3f400-f736-11e9-864c-621e0fc8f1e4.png)

**Comment by rayzhou2017** [comment]
verified
