### ISSUE TITLE
helm sample

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1203]
* [ ] 提供一个完整的sample，这样我能看到介绍、截图怎么在这个地方展现出来
![Screen Shot 2019-10-25 at 2 10 10 PM](https://user-images.githubusercontent.com/28859385/67547312-5b603280-f731-11e9-9c57-507cdab8e441.png)

**Comment by zheng1** [comment]
可以使用 https://kubernetes-charts.storage.googleapis.com/mysql-1.3.3.tgz 作为sample.

这里有两个问题:

- [ ] 介绍没有正确的显示出来, @wansir ks后端没有返回, @pengcong06 这个在op数据库里是空的.
- [ ] 截图不应该展示出来, helm包里没有截图这个信息 @whDongRui

**Comment by whDongRui** [comment]
介绍，截图没有信息是时前端给默认显示的"无”
介绍和截图可在以企业空间->应用模板->应用详情,去点编辑按钮，编辑页面有上传截图和填写介绍的地方。编辑完保存后在应用商店就可以看到相应的信息了。

![image](https://user-images.githubusercontent.com/38676269/67549661-5d2cf480-f737-11e9-8ec4-bde08d7705c1.png)

**Comment by zheng1** [comment]
![截屏2019-10-2811 40 48](https://user-images.githubusercontent.com/4156721/67650490-137f1c80-f978-11e9-99c6-2394d816d846.png)

## 介绍和截图的编辑功能测试正常

![截屏2019-10-2811 40 55](https://user-images.githubusercontent.com/4156721/67650492-1548e000-f978-11e9-8b88-217a2cd3d278.png)

## 应用介绍建议去掉, 直接从version的readme中读取即可

![截屏2019-10-2811 41 56](https://user-images.githubusercontent.com/4156721/67650494-167a0d00-f978-11e9-8ab5-e7581aa28913.png)

@whDongRui

**Comment by whDongRui** [comment]
应用介绍这块内容当时OP这块是为了统一不同类型(比如说helm，vmbased)的应用介绍弄出来的。
这个可以去掉,不过去掉这后这个页面的的元素布局可能要调整一下。

@Carlosfengv

**Comment by rayzhou2017** [comment]
这个是解决了吗？

**Comment by whDongRui** [comment]
这个跟设计讨论下，改动比较大，差不多把应用商店和应用仓库的显示页面重构了下(把之前有些用op的组件换也ks自己的)。刚改完了，还没合到master分支上。

**Comment by rayzhou2017** [comment]
verified
