### ISSUE TITLE
服务组件回退404了

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1206]
* [x] 在服务组件里进入一个服务，点击上面的返回箭头404了
![Screen Shot 2019-10-25 at 4 26 47 PM](https://user-images.githubusercontent.com/28859385/67555720-6f615f80-f744-11e9-9cc1-3d113f62f6aa.png)

**Comment by leoendless** [comment]
Fixed

**Comment by rayzhou2017** [comment]
verified
