### ISSUE TITLE
安装主节点上 /dev/loop2 设备没了，iso目录下的文件全没了

### ISSUE THREAD

**Issue by Carriezhangyan** [kubesphere/kubesphere#1208]
一般安装完后 /dev/loop2 会挂载一个iso目录，，今天查看5080端口下的iso目录的时候发现，iso目录下的所有文件都没有了，但是不知道是做了什么导致/dev/loop*设备全部不见了。。如果没有/dev/loop*设备挂载到iso目录的话，，以后做节点扩容会找不到镜像下载。请大神们看一下为什么会出现这种问题？

**Comment by pixiake** [comment]
应该是重启过机器吧    执行下install.sh就会重新挂那些iso

**Comment by Carriezhangyan** [comment]
我已经测试过重新执行 install.sh 可以重新挂载那些iso，，但是会对已经部署的应用有一些影响。。

能不能找到代码，可以手动执行命令获取那些iso文件呢？

**Comment by pixiake** [comment]
install.sh 最开始就是挂载这些iso，所以不用执行完，看到更新软件源就可以停掉了。相关的挂载命令在scripts/os/centos.sh or ubuntu.sh

**Comment by Carriezhangyan** [comment]
非常谢谢。已经解决。

执行一下scripts/os/centos7.sh 就可以解决重启后iso文件消失的问题

**Comment by Carriezhangyan** [comment]
发现新的问题：
执行一下scripts/os/centos7.sh 就可以解决重启后iso文件消失的问题，，
但是http://localhost:5080/yum_repo/iso/  浏览器上的5080端口下的iso目录下还是没有文件，，节点扩容的时候使用的是5080端口对应的目录，使用什么命令使5080端口可以连到终端下的/kubeinstaller/k8s_repo/iso/ 呢？

**Comment by pixiake** [comment]
要重启下5080对应的那个容器，可以试下·`docker  restart  pkg-download-center`

**Comment by Carriezhangyan** [comment]
我执行了一下命令“  bash scripts/os/tag.sh  ” ，，然后发现5080端口iso文件出现，，

是因为tag.sh中包含了重启容器的命令吗？

**Comment by pixiake** [comment]
是的

**Comment by Carriezhangyan** [comment]
非常感谢！。。这个问题终于彻底解决。
