### ISSUE TITLE
告警策略无法删除，报错 404

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#1209]
版本：2.1-dev

![image](https://user-images.githubusercontent.com/43693241/67558292-48f1f300-f749-11e9-95e0-fcbb36743ab0.png)

/area alerting
/kind bug
/milestone 2.1.0

**Comment by runzexia** [comment]
版本太老了？
我这里是可以work的

**Comment by shaowenchen** [comment]
我使用的是今天凌晨的版本

**Comment by leoendless** [comment]
Fixed

**Comment by shaowenchen** [comment]
OK。
/close
