### ISSUE TITLE
app store 英文文案

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1210]
* [x] 点击suspend后，跳出的窗口文案需要改成：The version 0.1.0 [1.0] will not be displayed in the store when it is suspended. Are you sure to suspend it now?
![Screen Shot 2019-10-25 at 5 33 46 PM](https://user-images.githubusercontent.com/28859385/67560557-b56ef100-f74d-11e9-8c9d-30e1da93244d.png)

* [x] Recover Version改成 Activate Version比较好，跳出的窗口文案改成：The version 0.1.0 [1.0] will be displayed again in the store. Are you sure to activate it now?
![Screen Shot 2019-10-25 at 5 37 15 PM](https://user-images.githubusercontent.com/28859385/67560769-21e9f000-f74e-11e9-8495-f9ef506e5c76.png)

* [x] 文案改为： The following information must be true and accurate. Key instructions must be given in details. Terms and Conditions are required to state clearly.

![Screen Shot 2019-10-25 at 5 55 10 PM](https://user-images.githubusercontent.com/28859385/67562083-a3db1880-f750-11e9-833b-aa10a85d945c.png)

**Comment by whDongRui** [comment]
版本和应用相关操作提示的英文翻译已经修复了。

![image](https://user-images.githubusercontent.com/38676269/67566390-3c29cb00-f75a-11e9-8800-1cc99045213c.png)

![image](https://user-images.githubusercontent.com/38676269/67566409-49df5080-f75a-11e9-98e0-6851948481c9.png)

![image](https://user-images.githubusercontent.com/38676269/67566435-5c598a00-f75a-11e9-959c-b86832e43b75.png)

**Comment by rayzhou2017** [comment]
verified
