### ISSUE TITLE
监控网络流量的单位转换

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1211]
这两个点的单位转化是不是有点问题？UI 上显示的怎么这么大，实际值单位是 bytes/s

![webwxgetmsgimg](https://user-images.githubusercontent.com/22350668/67563051-8444ef80-f752-11e9-9649-9a52ecfeac09.jpeg)

![webwxgetmsgimg (1)](https://user-images.githubusercontent.com/22350668/67563056-84dd8600-f752-11e9-8fdd-e7bb96d4e071.jpeg)

![image](https://user-images.githubusercontent.com/22350668/67563094-96269280-f752-11e9-9475-aa9d107e5bfc.png)

**Comment by huanggze** [comment]
流入、流出需要检查下

**Comment by justahole** [comment]
👍
