### ISSUE TITLE
system-workspace权限问题

### ISSUE THREAD

**Issue by knowwinter** [kubesphere/kubesphere#1212]
这个默认的企业空间里的所有的创建的权限（比如创建存储卷、创建部署、创建服务等，还有容器的终端登陆）这些按钮有时会有有时就消失了，用的同一个帐号admin，都是最大权限的，很莫名奇妙，但是其他的企业空间里的这些按钮都是有的。
![微信图片_20191025183824](https://user-images.githubusercontent.com/25719964/67564960-c96b2080-f756-11e9-846b-1382fb00d26c.png)
![微信图片_20191025183838](https://user-images.githubusercontent.com/25719964/67564965-cbcd7a80-f756-11e9-8014-dd266d2972dd.png)
![微信图片_20191025183845](https://user-images.githubusercontent.com/25719964/67564968-ce2fd480-f756-11e9-8ebe-b973e81b18bb.png)
![微信图片_20191025183851](https://user-images.githubusercontent.com/25719964/67564973-cff99800-f756-11e9-972b-f8f4a1ac9e33.png)

**Comment by wansir** [comment]
system-workspace里主要是一些控制平面的ns，在前端对编辑做了限制，防止误操作。

**Comment by FeynmanZhou** [comment]
@knowwinter system-workspace 里面运行的都是 kubesphere 系统组件，默认不允许创建和删除。可以新建 workspace 然后创建资源

**Comment by knowwinter** [comment]
问题是system-workspace这些按钮有时有有时没有，这个才是重点啊，如果他就是应该没有的为什么有时会有这些按钮呢，我都在这里创建过存储卷和终端登陆过容器，然后突然之间这些按钮又凭空消失了，怀疑人生

**Comment by rayzhou2017** [comment]
2.1.0版本应该没这个问题

**Comment by calvinyv** [comment]
fixed in 2.1.0
