### ISSUE TITLE
告警，发送邮件次数与显示不相符

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#1215]
版本：2.1-dev

配置的【危险告警】，每30分钟告警一次。17：37—19：19  ，仅收到两次邮件提醒，但是页面上显示4次消息通知。

![image](https://user-images.githubusercontent.com/43693241/67567469-88760a80-f75c-11e9-99eb-13b378fd7400.png)

![image](https://user-images.githubusercontent.com/43693241/67567568-b65b4f00-f75c-11e9-83b4-0b39795f2bd4.png)

![image](https://user-images.githubusercontent.com/43693241/67567609-c4a96b00-f75c-11e9-8b4d-5f3a7e568f08.png)

时间间隔在 一个小时。

下面是，副本可用率，监控数据：

![image](https://user-images.githubusercontent.com/43693241/67567645-e60a5700-f75c-11e9-919d-bc40ae8c9c50.png)

/kind bug
/area alerting

**Comment by rayzhou2017** [comment]
这个在解决吗？

**Comment by shaowenchen** [comment]
OK
/close
