### ISSUE TITLE
告警，cpu和memory 配置不生效

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#1216]
版本：2.1-dev

以内存为例，部署了一个 Jenkins ，内存肯定超过 100M

![image](https://user-images.githubusercontent.com/43693241/67567866-51ecbf80-f75d-11e9-9e00-00a269d532c3.png)

但是没有收到，告警消息。

![image](https://user-images.githubusercontent.com/43693241/67567906-692bad00-f75d-11e9-9f12-0ac6f8ce098e.png)

/area alerting
/milestone 2.1.0
/help

**Comment by runzexia** [comment]
节点级别以下指标没有上报状态
![image](https://user-images.githubusercontent.com/31230341/67665259-5951da00-f9a4-11e9-8b67-031dbc102e26.png)

`inode利用率`
`本地磁盘可用空间 `
`可用内存`
`CPU 1分钟平均负载`
`CPU利用率`
`容器组异常率`

**Comment by Ma-Dan** [comment]
内存监控指标的问题，读取 workload_pod_memory_usage 时，监控系统返回的实际上是 workload_pod_memory_usage_wo_cache 指标的值，因为请求和返回的指标不一致，导致作为没有读取到数据处理，无法进行后面的比较和通知流程。

**Comment by Ma-Dan** [comment]
一个Alert包含多个Rule时，有些Rule会在读取到监控指标后，没有处理。具体问题如下：
https://github.com/Ma-Dan/alert/blob/master/pkg/services/executor/runner.go#L459
该处的写法
for resourceMetrics := range ch {
		logger.Debug(nil, "resourceMetrics %v", resourceMetrics)

		needUpdate = needUpdate || ar.checkOneMetric(resourceMetrics)
	}
编译器优化之后，在needUpdate为true之后，将停止对后续监控值的循环处理。
修改为必须处理解决。

**Comment by rayzhou2017** [comment]
这个是什么结论呢？

**Comment by Ma-Dan** [comment]
问题和解决：

**Comment by shaowenchen** [comment]
/assign @huanggze 
/assign @leoendless 

上面的 （3）已经更新，（1）、（2）需要前端和监控修复。

**Comment by huanggze** [comment]
前后端已提

**Comment by shaowenchen** [comment]
1. cpu 的监控单位需要更新，有两个地方

填写告警规则

![image](https://user-images.githubusercontent.com/43693241/67929819-3835f700-fbf9-11e9-8f61-e18974815524.png)

告警详情

![image](https://user-images.githubusercontent.com/43693241/67929831-42f08c00-fbf9-11e9-989b-e872648e94ba.png)

**Comment by huanggze** [comment]
界面操作问题汇总 #1298

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/67997127-ac21df00-fc8d-11e9-8ccf-7a4cc238651a.png)

/close

**Comment by magicsong** [comment]
http://139.198.188.19:30880/test-workspace/projects/test/alert-policy/gaojing---2/alert-rules
