### ISSUE TITLE
告警通知人信息，修改之后，通知邮件没有更新

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#1218]
版本：2.1-dev

首先配置告警策略，然后修改通知人的基本信息，可以复现

![image](https://user-images.githubusercontent.com/43693241/67613717-3af0b080-f7e3-11e9-97f8-0129840da826.png)

![image](https://user-images.githubusercontent.com/43693241/67613722-4c39bd00-f7e3-11e9-9dab-19751cc3b211.png)

![image](https://user-images.githubusercontent.com/43693241/67613726-5b206f80-f7e3-11e9-9627-7f4cb3087371.png)

/area alerting 
/kind bug
/milestone 2.1.0

**Comment by shaowenchen** [comment]
待测试：

- 配置告警时，添加的通知人被删除之后，会不会继续通知
- 不同权限的通知人，会不会对通知有影响
- 由于设置通知人时，可以拉取到人员信息，会不会有越权
- 不同告警级别，通知时间间隔，是否准确
- 通知时间间隔在漂移，需要进一步确认

![image](https://user-images.githubusercontent.com/43693241/67614070-b43ed200-f7e8-11e9-814f-edbe0025c7c1.png)

**Comment by Ma-Dan** [comment]
时间漂移问题为通知允许发送时间在00:00~23:59之间，最后实际时间运行到23:59，会禁止一次发送，并设置下次可发送时间为00:00导致。已改正，发送时间严格按照告警周期进行，不再被通知允许发送时间影响，在通知允许时间范围之外的，仅禁止发送，并将告警信息累积。

**Comment by huojiao2006** [comment]
告警通知人信息，修改之后，通知邮件没有更新
需要前端修改一下，在修改用户的邮箱的时候，需要更新对应的通知列表里面的地址的信息，前端需要修改一下。

**Comment by Ma-Dan** [comment]
![image](https://user-images.githubusercontent.com/38337958/67821723-f02fab00-faf8-11e9-9c52-5a3324cb6440.png)
时间漂移问题在昨天版本已解决，验证如上图，发送时间和累积次数均正确。

**Comment by justahole** [comment]
如果在账户改密码的时候改变通知列表中的信息，会出现权限的问题。@huojiao2006

**Comment by justahole** [comment]
目前告警策略的通知人原本设计只是添加邮箱，没用指定到用户。可能需要后端改下逻辑@huojiao2006

**Comment by shaowenchen** [comment]
下个版本解决

/milestone 2.1.1
/remove-milestone 2.1.0

**Comment by shaowenchen** [comment]
修复有一定工作量

/remove-kind need-to-verify

**Comment by rayzhou2017** [comment]
How is this bug going?

**Comment by shaowenchen** [comment]
This bug has not been fixed in 2.1.1

**Comment by benjaminhuo** [comment]
This is a corner case, we'll not fix it in 2.1.1 per discussion in wechat group.
The design might be changed in 3.0 to avoid issue like this

**Comment by shaowenchen** [comment]
outdated
/close
