### ISSUE TITLE
最新版在centos7.5安装不起来问题

### ISSUE THREAD

**Issue by xiawanyingtest** [kubesphere/kubesphere#1219]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
安装不起来，好像是你们自动化【选择的是单机模式，离线包】包给我搭建的yum私库有问题,我对yum私服不是太了解
**安装环境的硬件配置**
centos7.5 迷你版  ram=8.5g 内核版本3.10
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)
vbox虚拟机 6.14最新版
**错误信息或截图**
docker: Error response from daemon: driver failed programming external connectivity on endpoint registry (3d4a656774f9ff82be0e71d7723744ae4366bf187513d43d7fca454a90b688bc):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 5000 -j DNAT --to-destination 172.17.0.2:5000 ! -i docker0: iptables: No chain/target/match by that name.
 (exit status 1)).
192.168.1.160:5000/kubesphere/ks-console:advanced-2.0.2
The push refers to repository [192.168.1.160:5000/kubesphere/ks-console]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: dockerhub.qingcloud.com/kubesphere/ks-console:advanced-2.0.2
192.168.1.160:5000/kubesphere/notification:flyway_advanced-2.0.2
The push refers to repository [192.168.1.160:5000/kubesphere/notification]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: kubesphere/notification:flyway_advanced-2.0.2
192.168.1.160:5000/kubesphere/notification:advanced-2.0.2
The push refers to repository [192.168.1.160:5000/kubesphere/notification]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: kubesphere/notification:advanced-2.0.2
192.168.1.160:5000/kubesphere/ks-devops:flyway-advanced-2.0.2
The push refers to repository [192.168.1.160:5000/kubesphere/ks-devops]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: kubesphere/ks-devops:flyway-advanced-2.0.2
192.168.1.160:5000/kubesphere/ks-controller-manager:advanced-2.0.2
The push refers to repository [192.168.1.160:5000/kubesphere/ks-controller-manager]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: kubesphere/ks-controller-manager:advanced-2.0.2
192.168.1.160:5000/kubesphere/ks-account:advanced-2.0.2
The push refers to repository [192.168.1.160:5000/kubesphere/ks-account]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: kubesphere/ks-account:advanced-2.0.2
192.168.1.160:5000/kubesphere/ks-apiserver:advanced-2.0.2
The push refers to repository [192.168.1.160:5000/kubesphere/ks-apiserver]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: kubesphere/ks-apiserver:advanced-2.0.2
192.168.1.160:5000/kubesphere/ks-apigateway:advanced-2.0.2
The push refers to repository [192.168.1.160:5000/kubesphere/ks-apigateway]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: kubesphere/ks-apigateway:advanced-2.0.2
192.168.1.160:5000/kubesphere/alerting:advanced-2.0.2
The push refers to repository [192.168.1.160:5000/kubesphere/alerting]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: kubesphere/alerting:advanced-2.0.2
192.168.1.160:5000/library/redis:4.0
The push refers to repository [192.168.1.160:5000/library/redis]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: redis:4.0
192.168.1.160:5000/kubesphere/alert_adapter:advanced-2.0.2
The push refers to repository [192.168.1.160:5000/kubesphere/alert_adapter]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: kubesphere/alert_adapter:advanced-2.0.2
192.168.1.160:5000/library/perl:latest
The push refers to repository [192.168.1.160:5000/library/perl]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: perl:latest
192.168.1.160:5000/library/mysql:5.6
The push refers to repository [192.168.1.160:5000/library/mysql]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: mysql:5.6
192.168.1.160:5000/kubesphere/fluentbit-operator:advanced-2.0.0
The push refers to repository [192.168.1.160:5000/kubesphere/fluentbit-operator]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: kubesphere/fluentbit-operator:advanced-2.0.0
192.168.1.160:5000/kubesphere/docs.kubesphere.io:advanced-2.0.0
The push refers to repository [192.168.1.160:5000/kubesphere/docs.kubesphere.io]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: kubesphere/docs.kubesphere.io:advanced-2.0.0
192.168.1.160:5000/kubesphere/cloud-controller-manager:v1.3.4
The push refers to repository [192.168.1.160:5000/kubesphere/cloud-controller-manager]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: kubesphere/cloud-controller-manager:v1.3.4
192.168.1.160:5000/kubesphere/alerting-dbinit:advanced-2.0.2
The push refers to repository [192.168.1.160:5000/kubesphere/alerting-dbinit]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: kubesphere/alerting-dbinit:advanced-2.0.2
192.168.1.160:5000/kubesphere/ks-upgrade:advanced-2.0.0
The push refers to repository [192.168.1.160:5000/kubesphere/ks-upgrade]
Get http://192.168.1.160:5000/v2/: dial tcp 192.168.1.160:5000: connect: connection refused
Untagged: kubesphere/ks-upgrade:advanced-2.0.0

Friday 25 October 2019  23:52:40 -0400 (0:00:00.083)       0:00:05.784 ******** 
fatal: [ks-allinone]: FAILED! => {"changed": false, "msg": "http://192.168.1.160:5080/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/libxml2-python-2.9.1-6.el7_2.3.x86_64.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-chardet-2.2.1-1.el7_1.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-kitchen-1.1.1-5.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/yum-utils-1.1.31-50.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/libxml2-python-2.9.1-6.el7_2.3.x86_64.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-chardet-2.2.1-1.el7_1.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-kitchen-1.1.1-5.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/yum-utils-1.1.31-50.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/libxml2-python-2.9.1-6.el7_2.3.x86_64.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-chardet-2.2.1-1.el7_1.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-kitchen-1.1.1-5.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/yum-utils-1.1.31-50.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/libxml2-python-2.9.1-6.el7_2.3.x86_64.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-chardet-2.2.1-1.el7_1.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-kitchen-1.1.1-5.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/yum-utils-1.1.31-50.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/libxml2-python-2.9.1-6.el7_2.3.x86_64.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-chardet-2.2.1-1.el7_1.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-kitchen-1.1.1-5.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/yum-utils-1.1.31-50.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/libxml2-python-2.9.1-6.el7_2.3.x86_64.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-chardet-2.2.1-1.el7_1.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-kitchen-1.1.1-5.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/yum-utils-1.1.31-50.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/libxml2-python-2.9.1-6.el7_2.3.x86_64.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-chardet-2.2.1-1.el7_1.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-kitchen-1.1.1-5.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/yum-utils-1.1.31-50.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/libxml2-python-2.9.1-6.el7_2.3.x86_64.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-chardet-2.2.1-1.el7_1.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-kitchen-1.1.1-5.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/yum-utils-1.1.31-50.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/libxml2-python-2.9.1-6.el7_2.3.x86_64.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-chardet-2.2.1-1.el7_1.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-kitchen-1.1.1-5.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/yum-utils-1.1.31-50.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/libxml2-python-2.9.1-6.el7_2.3.x86_64.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-chardet-2.2.1-1.el7_1.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/python-kitchen-1.1.1-5.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\nhttp://192.168.1.160:5080/yum_repo/iso/yum-utils-1.1.31-50.el7.noarch.rpm: [Errno 14] curl#7 - \"Failed connect to 192.168.1.160:5080; Connection refused\"\nTrying other mirror.\n\n\nError downloading packages:\n  python-chardet-2.2.1-1.el7_1.noarch: [Errno 256] No more mirrors to try.\n  yum-utils-1.1.31-50.el7.noarch: [Errno 256] No more mirrors to try.\n  python-kitchen-1.1.1-5.el7.noarch: [Errno 256] No more mirrors to try.\n  libxml2-python-2.9.1-6.el7_2.3.x86_64: [Errno 256] No more mirrors to try.\n\n", "rc": 1, "results": ["libselinux-python-2.5-14.1.el7.x86_64 providing libselinux-python is already installed", "Resolving Dependencies\n--> Running transaction check\n---> Package yum-utils.noarch 0:1.1.31-50.el7 will be installed\n--> Processing Dependency: python-kitchen for package: yum-utils-1.1.31-50.el7.noarch\n--> Processing Dependency: libxml2-python for package: yum-utils-1.1.31-50.el7.noarch\n--> Running transaction check\n---> Package libxml2-python.x86_64 0:2.9.1-6.el7_2.3 will be installed\n---> Package python-kitchen.noarch 0:1.1.1-5.el7 will be installed\n--> Processing Dependency: python-chardet for package: python-kitchen-1.1.1-5.el7.noarch\n--> Running transaction check\n---> Package python-chardet.noarch 0:2.2.1-1.el7_1 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package               Arch          Version                  Repository   Size\n================================================================================\nInstalling:\n yum-utils             noarch        1.1.31-50.el7            bash        121 k\nInstalling for dependencies:\n libxml2-python        x86_64        2.9.1-6.el7_2.3          bash        247 k\n python-chardet        noarch        2.2.1-1.el7_1            bash        227 k\n python-kitchen        noarch        1.1.1-5.el7              bash        267 k\n\nTransaction Summary\n================================================================================\nInstall  1 Package (+3 Dependent packages)\n\nTotal download size: 861 k\nInstalled size: 4.3 M\nDownloading packages:\nDelta RPMs disabled because /usr/bin/applydeltarpm not installed.\n"]}

**Installer版本**
2.0.2

**Comment by pixiake** [comment]
https://github.com/kubesphere/ks-installer/issues/73
