### ISSUE TITLE
centos7.4 安装多节点 版本2.0.2 ，安装多次报这个错，问一下是什么原因

### ISSUE THREAD

**Issue by gongjx11** [kubesphere/kubesphere#1220]
![image](https://user-images.githubusercontent.com/21954004/67615729-4c958080-f802-11e9-9e3d-18748f40a875.png)

这个装了好几次，每次到这里就报错，请问一下这个怎么解决？谢谢

**Comment by xiawanyingtest** [comment]
我安装在线版的在centos7.5上也安装不了，虚拟机甲骨文vbox


TASK [ks-alerting : ks-alerting | Waiting for alerting-db-init] **************************************************************************************************************************************************************************************************************
Saturday 26 October 2019  23:05:05 -0400 (0:00:01.273)       0:14:04.821 ****** 
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (30 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (29 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (28 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (27 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (26 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (25 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (24 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (23 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (22 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (21 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (20 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (19 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (18 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (17 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (16 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (15 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (14 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (13 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (12 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (11 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (10 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (9 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (8 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (7 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (6 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (5 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (4 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (3 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (2 retries left).
FAILED - RETRYING: ks-alerting | Waiting for alerting-db-init (1 retries left).
fatal: [ks-allinone]: FAILED! => {"attempts": 30, "changed": true, "cmd": "/usr/local/bin/kubectl -n kubesphere-alerting-system get pod | grep alerting-db-init | awk '{print $3}'", "delta": "0:00:00.288563", "end": "2019-10-26 23:06:21.165784", "rc": 0, "start": "2019-10-26 23:06:20.877221", "stderr": "", "stderr_lines": [], "stdout": "Init:0/1", "stdout_lines": ["Init:0/1"]}

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
ks-allinone                : ok=282  changed=117  unreachable=0    failed=1

**Comment by pixiake** [comment]
https://github.com/kubesphere/ks-installer/issues/48
