### ISSUE TITLE
【2.1】workspace-manager 登录后，删除admin创建的workspace，返回 404

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#1221]
workspace-manager 登录后，删除admin创建的workspace，返回 404，这个返回感觉不合理。
![image](https://user-images.githubusercontent.com/40452856/67630986-c5600f80-f8ca-11e9-8dc1-71de54d82e7a.png)

**Comment by leoendless** [comment]
最新 installer 没有复现这个错误，提供下环境看看吧
