### ISSUE TITLE
【2.1】”关于“页面的 URL 需要更新

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#1222]
这里有3个链接全都是指向同一个 URL（ github kubesphere repo），建议把 ”项目地址“ 替换为 ”论坛交流“，”问题反馈“ 文案改成 ”Bug 反馈“。 可以让技术问题的支持都引导到论坛，Bug 引导至 github issue 提交。
![image](https://user-images.githubusercontent.com/40452856/67631258-d3179400-f8ce-11e9-847a-1feae98460ea.png)

**Comment by Carlosfengv** [comment]
别，反馈可以提给github issue，项目地址也是必须的。Github 比论坛可靠稳定的多。

**Comment by Carlosfengv** [comment]
另外，论只是中文的，国际用户看不懂

**Comment by leoendless** [comment]
@FeynmanZhou

**Comment by FeynmanZhou** [comment]
@leoendless 那就只在中文界面加上论坛的 icon 和 URL 吧
