### ISSUE TITLE
【2.1】应用创建成功后，状态仍显示更新中。

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#1223]
在 ”应用“ 下手动创建了一个 wordpress 应用，确认其 deployment  和 statefulset 都显示运行中，wordpress 也可以正常访问，但该应用的状态还是 ”更新中“。
![image](https://user-images.githubusercontent.com/40452856/67632846-e7b25700-f8e3-11e9-99fd-3ad6f52adf4d.png)

**Comment by leoendless** [comment]
过一段时间后恢复正常了吗，还是一直是更新中

**Comment by xianyuwu** [comment]
我也遇到这个问题，确定所有的Workload都是正常的状态，但应用状态一直显示“更新中”。还有一种状态不正常的情况发生在，通过S2I构建镜像的时候，第一次的构建失败了，然后找到问题修改之后重新进行构建，成功之后Workload的 状态还是显示“构建镜像失败”，查看构建日志实际上已经成功了，这个状态会一直显示“构建镜像失败”，不会更新为“运行中”。
![image](https://user-images.githubusercontent.com/22258895/68994311-8ebf5880-08bc-11ea-9fd3-e943ce299f97.png)
![image](https://user-images.githubusercontent.com/22258895/68994315-95e66680-08bc-11ea-9c16-1113635fb57d.png)

**Comment by leoendless** [comment]
@minghaoye 看下这个 s2i workload 状态问题吧

**Comment by minghaoye** [comment]
@runzexia  这里怎么优化一下

**Comment by runzexia** [comment]
@minghaoye 这个地方要取s2ib的lastRunState

**Comment by minghaoye** [comment]
> @minghaoye 这个地方要取s2ib的.status.lastRunState

需要再发次请求么，那之前在label里取得状态就没必要了

**Comment by runzexia** [comment]
需要再次发请求，之前的不用再取了
@minghaoye

**Comment by minghaoye** [comment]
@runzexia 一个页面如果有10个 s2i 资源就得发10次查询请求。2.1.1这里前端先加个聚合api，这里后面后端还是得做处理。

**Comment by leoendless** [comment]
1. s2i 状态发生变化时，没有触发对应 workload 的 watch 接口。
2. s2i 状态发生变化时，有触发对应 workload 的 watch 接口。前端监听到变化，获取新的列表数据。但 workload 里的 s2i 状态没有更新。

@runzexia @minghaoye 是哪一种情况呢

**Comment by minghaoye** [comment]
添加的耦合代码太多，这个修复移到 3.0，在意这个显示的可以先自行合并这个 PR（https://github.com/kubesphere/console/pull/105）并编译。

/milestore 3.0

**Comment by rayzhou2017** [comment]
should be fixed in 3.0

**Comment by rayzhou2017** [comment]
wordpress status is not fixed.
