### ISSUE TITLE
推送镜像到harbor失败

### ISSUE THREAD

**Issue by tzghost** [kubesphere/kubesphere#1224]
allinone 模式部署的2.0.2版本，Harbor平台访问正常，push 镜像到仓库时失败。

[root@ks-allinone scripts]# docker login -u admin  http://harbor.devops.kubesphere.local:30280
Password: 
Error response from daemon: Get https://harbor.devops.kubesphere.local:30280/v2/: http: server gave HTTP response to HTTPS client

**Comment by pixiake** [comment]
http的仓库要在docker的配置文件中加`--insecure-registry`
https://kubesphere.io/docs/v2.0/zh-CN/configuration/image-registry/#http

**Comment by tzghost** [comment]
添加配置参数后，仍然失败
![image](https://user-images.githubusercontent.com/17000535/67653581-f7ce4300-f984-11e9-91a5-34171ea28f92.png)

**Comment by pixiake** [comment]
修改完配置要重载配置，重启服务
`systemctl daemon-reload`
`systemctl restart docker`

**Comment by tzghost** [comment]
在/etc/docker/daemon.json添加如下配置后正常

[root@ks-allinone docker]# cat /etc/docker/daemon.json 
{
	"insecure-registries": ["harbor.devops.kubesphere.local:30280"]
}
