### ISSUE TITLE
应用仓库部署 mysql 卡住

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1225]
卡住。卡完后，界面没有任何变化（图二）手动退出这个菜单，倒是可以看到有把 mysql 创建出来（图三）

![image](https://user-images.githubusercontent.com/22350668/67647600-de6dcc80-f96d-11e9-9759-83fbcb76d31e.png)

![image](https://user-images.githubusercontent.com/22350668/67647632-f2193300-f96d-11e9-9341-447ae5e5b758.png)

![image](https://user-images.githubusercontent.com/22350668/67647740-47eddb00-f96e-11e9-9c82-fe3e5d48e3e0.png)

**Comment by whDongRui** [comment]
这个是之前把应用模板和自制应用拆分成两个页面，导致提交后再查询列表页面的数据有问题，刚已经修复了。

**Comment by huanggze** [comment]
好像没有变化 /remove-kind need-to-verify
