### ISSUE TITLE
查看pvc报错

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1226]
* [ ] 我是这个ns的admin，创建了一个pvc，然后想查看一下，报错，用默认的集群admin查看没有问题
![Screen Shot 2019-10-28 at 10 44 14 AM](https://user-images.githubusercontent.com/28859385/67648226-1544e200-f970-11e9-9575-f27b705df333.png)

**Comment by wansir** [comment]
@leoendless  这里应该不需要请求 `/apis/storage.k8s.io/v1/storageclasses/{storageclass}`

**Comment by justahole** [comment]
@wansir 不好意思，我需要这个请求来判断当前volume是否支持扩容。

**Comment by rayzhou2017** [comment]
verified
