### ISSUE TITLE
webhook Tag Push Hook 无法触发pipline

### ISSUE THREAD

**Issue by Forget-C** [kubesphere/kubesphere#1228]
常规的代码提交是可以出发webhook的，并可以成功执行pipline。
当创建新tag时，即 “Tag Push Hook”， git已经向webhook发送信息，但是并没有触发jenkins构建。jenkins甚至没有创建对应的 builder pod。
![image](https://user-images.githubusercontent.com/25631506/67650102-8c7d7480-f976-11e9-95e2-13c3ca083f77.png)

另外，即使成功的处罚也会有一个这样看起来是错误的返回：
![image](https://user-images.githubusercontent.com/25631506/67650150-c0589a00-f976-11e9-8d72-9161a97ec70c.png)

**Comment by runzexia** [comment]
目前还没有支持针对tag进行构建

**Comment by soulseen** [comment]
麻烦补充提供下kubesphere版本信息以及复现步骤。

**Comment by Forget-C** [comment]
有什么临时的解决方法吗？

**Comment by Forget-C** [comment]
另外 需要证书的https git 地址需要怎么做？ 文档中的这一段没有看懂
![image](https://user-images.githubusercontent.com/25631506/67652018-21d03700-f97e-11e9-887a-4a55375a2fa7.png)

**Comment by runzexia** [comment]
https git 可以使用账户凭证的凭证类型。
git tag构建可以在网上查找jenkins git tag相关的问题。
https://stackoverflow.com/questions/10195900/jenkins-git-plugin-how-to-build-specific-tag
