### ISSUE TITLE
应用仓库编辑 values.yml 没有生效

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1229]
比如部署 mysql-exporter，修改 service.type 为 NodePort。但创建后发现，并没有生效，仍是 ClusterIP。其他字段也是一样没有生效

![image](https://user-images.githubusercontent.com/22350668/67651047-49bd9b80-f97a-11e9-9e21-6d683a26167c.png)

**Comment by whDongRui** [comment]
你修改后，看一下前端的传参，我刚才测试是namespace修改后，传参是跟着变化的。

![image](https://user-images.githubusercontent.com/38676269/67655422-8219a580-f98b-11e9-9c87-da4be2902634.png)

**Comment by whDongRui** [comment]
还有应用详情页面查询配置文件页面中，配置文件可以输入这个也修复了。是之前把组件属性readOnly传成了readonly导致的。

**Comment by huanggze** [comment]
verified
