### ISSUE TITLE
被要求登录之后没有跳转到最初点击的链接

### ISSUE THREAD

**Issue by magicsong** [kubesphere/kubesphere#1230]
**General remarks**

> Please delete this section including header before submitting
> 也可以使用中文
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug(描述下问题)**
用户点击其他用户复制的资源链接比如http://x.x.x.x/system-workspace/projects/kube-system/deployments/cloud-controller-manager/pods/cloud-controller-manager-7dc596ff8d-2np8r/resource-status   
如果没登录，会被要求登录。但是登录之后就跳转到dashboard。并不会跳转到相应的链接
For UI issues please also add a screenshot that shows the issue.
/kind enhancement
**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)
/area console

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**

**Expected behavior(预期行为)**

**Comment by leoendless** [comment]
最新版本应该修复了吧

**Comment by leoendless** [comment]
Fixed
