### ISSUE TITLE
创建任务及定时任务时参数文案问题

### ISSUE THREAD

**Issue by soulseen** [kubesphere/kubesphere#1232]
**Describe the bug(描述下问题)**
如图，创建任务及定时任务时设置参数显示为英文。
![image](https://user-images.githubusercontent.com/16031013/67654313-12ee8200-f988-11e9-8618-57e722b12409.png)

![image](https://user-images.githubusercontent.com/16031013/67653831-2862ac80-f986-11e9-867d-6d42cd7c8068.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1 dev

**Comment by rayzhou2017** [comment]
这个是不是不用翻译？上面表示的是专业术语，类似于参数，下面是中文解释

**Comment by Carlosfengv** [comment]
有翻译更容易理解参数的作用。

**Comment by rayzhou2017** [comment]
那提交吧
