### ISSUE TITLE
jenkins 登录 Invalid username or password

### ISSUE THREAD

**Issue by Forget-C** [kubesphere/kubesphere#1233]
**General remarks**

> Please delete this section including header before submitting
> 也可以使用中文
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug(描述下问题)**
用户密码是正确的，jenkins 登录 有时会多次登录失败，显示 Invalid username or password。
![image](https://user-images.githubusercontent.com/25631506/67657552-0b33db00-f992-11e9-9c6a-13fc9c65f770.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.0.2

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**
1. 登录jenkins是就会有几率连续出现

**Comment by runzexia** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-5303

jenkins 所使用的底层库问题

**Comment by runzexia** [comment]
这个问题不会影响 ks devops的功能，在登陆 jenkins 时可能会提示错误，修复应该在上游 jenkins 社区进行
