### ISSUE TITLE
按照应用管理文档操作，验证helm repo错误

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#1234]
![image](https://user-images.githubusercontent.com/31230341/67662764-045f9500-f99f-11e9-9f9e-d6dfed70437a.png)
验证op pod到仓库地址网络可达
/kind bug
/area app-management
/milestone 2.1.0

**Comment by runzexia** [comment]
https://kubesphere.io/docs/v2.1/zh-CN/quick-start/one-click-deploy/

**Comment by zheng1** [comment]
/kind need-to-verify

Fixed in https://travis-ci.org/openpitrix/openpitrix/builds/603932695

Please wait for travis build and push the image to DockerHub

**Comment by runzexia** [comment]
verfied in latest
/close
