### ISSUE TITLE
HA安装问题

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1238]
* [x] 这个image需要换镜像库
<img width="991" alt="Screen Shot 2019-10-28 at 11 05 39 PM" src="https://user-images.githubusercontent.com/28859385/67690298-9daa9d80-f9d7-11e9-9eca-62c860050461.png">

* [x] 下面两个镜像有问题
<img width="990" alt="Screen Shot 2019-10-28 at 11 08 29 PM" src="https://user-images.githubusercontent.com/28859385/67690484-ee21fb00-f9d7-11e9-81f8-bc7713b296e4.png">
<img width="986" alt="Screen Shot 2019-10-28 at 11 09 35 PM" src="https://user-images.githubusercontent.com/28859385/67690546-0abe3300-f9d8-11e9-94ab-6c5ad56ba888.png">

* [ ] nameserver也有告警
![Screen Shot 2019-10-29 at 11 01 18 AM](https://user-images.githubusercontent.com/28859385/67734273-8d2c0e80-fa3b-11e9-9861-2ed74f5a6e53.png)

* [ ] 7个服务有单点
![Screen Shot 2019-10-29 at 11 38 20 AM](https://user-images.githubusercontent.com/28859385/67735977-bef3a400-fa40-11e9-9b0e-4310cc0f0db6.png)
![Screen Shot 2019-10-29 at 11 41 17 AM](https://user-images.githubusercontent.com/28859385/67736053-109c2e80-fa41-11e9-8899-14350b67c298.png)
![Screen Shot 2019-10-29 at 11 47 33 AM](https://user-images.githubusercontent.com/28859385/67736264-f9117580-fa41-11e9-9050-2661f110759e.png)
![Screen Shot 2019-10-29 at 11 57 03 AM](https://user-images.githubusercontent.com/28859385/67736629-43dfbd00-fa43-11e9-82a3-cceb45365637.png)

**Comment by rayzhou2017** [comment]
jaeger的两个镜像又好了，是系统没有装好的原因？

**Comment by zryfish** [comment]
jaeger依赖于es，es没起来的话，jaeger状态会异常

镜像会改成 mirrorgooglecontainers/defaultbackend-amd64:v1.4

**Comment by rayzhou2017** [comment]
下面两个问题尽快fix

**Comment by rayzhou2017** [comment]
前面两个verified，后面两个我重新看issue，降低priority
