### ISSUE TITLE
centos7.4 多节点安装，Sonarqube 启动不起来

### ISSUE THREAD

**Issue by gongjx11** [kubesphere/kubesphere#1239]
![image](https://user-images.githubusercontent.com/21954004/67731067-e98a3080-fa31-11e9-9480-8187ab91db88.png)

根据前面解答说，需要关掉防火墙 我这边都以经关了。但是装了几次一直都是这个错。

**Comment by Forest-L** [comment]
@gongjx11
1、检查下helm是否正常，helm list;
2、可以先卸载再安装，先执行uninstall脚本，再执行install

**Comment by gongjx11** [comment]
好的 我试一下
