### ISSUE TITLE
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db 

### ISSUE THREAD

**Issue by huazai007** [kubesphere/kubesphere#1240]
Multi-Node 模式

**安装环境的硬件配置**
3台物理机DellR710

**错误信息或截图**
TASK [ks-devops/ks-devops : OpenPitrix | Waiting for openpitrix-db] *************************************************************************************************************************************
Monday 28 October 2019  21:34:43 -0400 (0:00:00.951)       0:08:22.641 ******** 
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (15 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (14 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (13 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (12 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (11 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (10 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (9 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (8 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (7 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (6 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (5 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (4 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (3 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (2 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (1 retries left).
fatal: [master]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/usr/local/bin/kubectl -n openpitrix-system get pod | grep openpitrix-db-deployment | awk '{print $3}'", "delta": "0:00:00.220585", "end": "2019-10-28 21:37:20.261077", "rc": 0, "start": "2019-10-28 21:37:20.040492", "stderr": "", "stderr_lines": [], "stdout": "CrashLoopBackOff", "stdout_lines": ["CrashLoopBackOff"]}

PLAY RECAP **********************************************************************************************************************************************************************************************
master                     : ok=271  changed=73   unreachable=0    failed=1   
node1                      : ok=174  changed=8    unreachable=0    failed=0   
node2                      : ok=174  changed=8    unreachable=0    failed=0   

**Installer版本**
v2.0.2

**Comment by rayzhou2017** [comment]
可能是存储的问题，到 https://github.com/kubesphere/ks-installer/issues 找找答案

**Comment by pixiake** [comment]
查下pod的events和日志，用的什么存储？如果是用的nfs的话，nfs服务器里把no_root_squash这个配置加上。

`kubectl -n openpitrix-system describe pods $(kubectl -n openpitrix-system get po --selector=tier=db -o jsonpath='{.items[0].metadata.name}')`

`kubectl -n openpitrix-system logs $(kubectl -n openpitrix-system get po --selector=tier=db -o jsonpath='{.items[0].metadata.name}')`

**Comment by pixiake** [comment]
https://github.com/kubesphere/ks-installer/issues/94
