### ISSUE TITLE
监控指标和单位问题

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/kubesphere#1241]
版本：2.1-dev

![image](https://user-images.githubusercontent.com/38337958/67733705-15111900-fa3a-11e9-82eb-c351bce9d094.png)

监控指标 workload_pod_memory_usage 读取出 workload_pod_memory_usage_wo_cache 值。

![image](https://user-images.githubusercontent.com/38337958/67733842-66b9a380-fa3a-11e9-86a5-0eb63fcc0694.png)

![image](https://user-images.githubusercontent.com/38337958/67733872-7df89100-fa3a-11e9-8393-b1fc9b411469.png)

![image](https://user-images.githubusercontent.com/38337958/67733889-85b83580-fa3a-11e9-88c9-5fa682b8fb84.png)

![image](https://user-images.githubusercontent.com/38337958/67733898-8bae1680-fa3a-11e9-93ff-3f26c2803c69.png)

CPU 指标 workload_pod_cpu_usage 在告警创建时单位为m，倍率为1.0，读取出来的单位为core，造成按照m指定的告警无法被正确判断，需要修改单位一致，或者换算倍率。

/area monitoring
/milestone 2.1.0
/help

**Comment by huanggze** [comment]
1. 我补上 workload_pod_memory_usage
2. 可以统一改成 core

**Comment by Ma-Dan** [comment]
改成Core不知道前端输入和换算是否方便，目前告警中cpu的usage指标是否都是以Core为单位的，或者统一改换算倍率，现在都是1.0

**Comment by huanggze** [comment]
@justahole @Ma-Dan 

单位调整为 Core，不是 m 

![image](https://user-images.githubusercontent.com/22350668/67743194-e9515b80-fa58-11e9-93cf-a78d02d628a9.png)
