### ISSUE TITLE
ks-gitlab-shared-secrets Error

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1244]
![image](https://user-images.githubusercontent.com/22350668/67734765-e5afdb80-fa3c-11e9-85e7-e9ecb0aeadbc.png)

日志：

![image](https://user-images.githubusercontent.com/22350668/67734800-0c6e1200-fa3d-11e9-85a0-842418f05e72.png)

**Comment by hlwanghl** [comment]
Which OS version did you use? Not reproduced on CentOS 7.5.

**Comment by huanggze** [comment]
ubuntu 18 也没有再复现 先 /close
