### ISSUE TITLE
构建Spring Boot流水线报错

### ISSUE THREAD

**Issue by tzghost** [kubesphere/kubesphere#1248]
构建Spring Boot流水线报错，报错信息如下，这个问题如何解决？

+ echo ****
+ docker login docker.io -u **** --password-stdin
Error response from daemon: Get https://registry-1.docker.io/v2/: Get https://auth.docker.io/token?account=****&client_id=docker&offline_token=true&service=registry.docker.io: net/http: TLS handshake timeout

![image](https://user-images.githubusercontent.com/17000535/67743324-3f260380-fa59-11e9-92bf-6b5fe072350e.png)

**Comment by runzexia** [comment]
网络问题，尝试用国内镜像仓库吧

**Comment by tzghost** [comment]
有推荐吗？

**Comment by runzexia** [comment]
https://appcenter.qingcloud.com/apps/app-2mhyb1ui
可以尝试下使用青云公有云的harbor服务
![image](https://user-images.githubusercontent.com/31230341/67745731-f4f45080-fa5f-11e9-8ec7-99480c5f2cc5.png)
