### ISSUE TITLE
centos7.4 多节点安装，一直提示报FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (15 retries left).

### ISSUE THREAD

**Issue by gongjx11** [kubesphere/kubesphere#1249]
![image](https://user-images.githubusercontent.com/21954004/67750985-35a59700-fa6b-11e9-8e58-067af836a648.png)
问一下这是什么原因：

**Comment by runzexia** [comment]
https://github.com/kubesphere/ks-installer/issues/94
存储配置问题
