### ISSUE TITLE
system suspend when input illegal password

### ISSUE THREAD

**Issue by jerryjedi** [kubesphere/kubesphere#125]
If input illegal password when create user, at first I will got a warning message,it's fine. Then I change password and try to create again, but the system seems suspend and can't click the "OK" button. Pls check the screen copy. 
![1](https://user-images.githubusercontent.com/7875026/41955879-741c24a0-7a14-11e8-9d8a-793f7d42c378.png)

**Comment by jerryjedi** [comment]
I logout and login again. Then the button restore to normal status.

**Comment by leoendless** [comment]
@jerryjedi If password is illegal, the confirm button should not response. Could you tell me your running enviroment
