### ISSUE TITLE
useless dropdown arrow is shown when mounting vol

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1251]
**Describe the bug(描述下问题)**

For UI issues please also add a screenshot that shows the issue.

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0 dev 

![Jietu20191029-143457](https://user-images.githubusercontent.com/28883416/67752327-c54c4500-fa6d-11e9-84d7-cba7c5ee1595.png)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**
create a vol and then create a workload which need to mount vol, and you could see there's dropdown arrow, but nothing happen when clicking it.

**Expected behavior(预期行为)**

**Comment by leoendless** [comment]
是这样的，多建几个volume再看
