### ISSUE TITLE
【加急】CentOS Linux release 7.5.1804 安装失败kubesphere2.0.2离线版，已经尝试5台统一错误

### ISSUE THREAD

**Issue by arraycto** [kubesphere/kubesphere#1253]
[备注]: 明天领导需要演示，跪求大神支持。小白已经哭了，拜托

**问题描述**

**安装环境的硬件配置**
8vCPU  32GB内存
CentOS Linux release 7.5.1804 
离线安装kubesphere2.0.2
安装方式all-in-one离线
 
[备注]: 公司自己的内网云，不能连接公网

**错误信息或截图**

TASK [kubernetes/node : Ensure nodePort range is reserved] ************************************************
Tuesday 29 October 2019  17:02:16 +0800 (0:00:01.152)       0:03:47.516 ******* 
fatal: [ks-allinone]: FAILED! => {"changed": false, "msg": "Failed to reload sysctl: kernel.randomize_va_space = 1\nnet.ipv4.tcp_syncookies = 1\nnet.ipv4.ip_forward = 1\nnet.ipv4.conf.all.send_redirects = 0\nnet.ipv4.conf.all.accept_source_route = 0\nnet.ipv4.conf.default.accept_source_route = 0\nnet.ipv4.conf.all.log_martians = 0\nnet.ipv4.conf.all.accept_redirects = 0\nnet.ipv4.conf.all.secure_redirects = 0\nnet.ipv4.conf.default.accept_redirects = 0\nnet.ipv4.conf.default.log_martians = 0\nnet.ipv4.conf.all.rp_filter = 0\nnet.ipv4.ip_local_reserved_ports = 30000-32767\nsysctl: cannot stat /proc/sys/kernel/exec-shield: No such file or directory\n"}

NO MORE HOSTS LEFT ****************************************************************************************

PLAY RECAP ************************************************************************************************
ks-allinone                : ok=283  changed=49   unreachable=0    failed=1   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

Tuesday 29 October 2019  17:02:16 +0800 (0:00:00.323)       0:03:47.840 ******* 
=============================================================================== 

**Installer版本**
kubesphere2.0.2

**Comment by pixiake** [comment]
sysctl 修改内核参数失败，手动执行sysctl 命令设置下返回信息中的那些值

**Comment by arraycto** [comment]
修正后，继续报如下错误：
TASK [ks-devops/ks-devops : OpenPitrix | Waiting for openpitrix-db] *****************************************************************************************************************************************************************************
Tuesday 29 October 2019  21:06:32 +0800 (0:00:00.776)       0:06:25.399 ******* 
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (15 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (14 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (13 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (12 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (11 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (10 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (9 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (8 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (7 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (6 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (5 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (4 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (3 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (2 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (1 retries left).
fatal: [ks-allinone]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/usr/local/bin/kubectl -n openpitrix-system get pod | grep openpitrix-db-deployment | awk '{print $3}'", "delta": "0:00:00.277817", "end": "2019-10-29 21:11:40.450306", "rc": 0, "start": "2019-10-29 21:11:40.172489", "stderr": "", "stderr_lines": [], "stdout": "Pending", "stdout_lines": ["Pending"]}

PLAY RECAP **************************************************************************************************************************************************************************************************************************************
ks-allinone                : ok=244  changed=90   unreachable=0    failed=1   

Tuesday 29 October 2019  21:11:40 +0800 (0:05:07.919)       0:11:33.318 ******* 
===============================================================================

**Comment by pixiake** [comment]
检查下存储配置和存储服务器
https://github.com/kubesphere/kubesphere/issues/1240
