### ISSUE TITLE
用户上架nginx这个应用后无法调整分类，报错

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1254]
1、上传nginx这个应用模板，依次提交审核、审核通过、上架；
2、新建一个分类；
3、将步骤1中的nginx调整分类到新分类，报错：
![image](https://user-images.githubusercontent.com/7677050/67756013-2f67e880-fa74-11e9-8412-1335207d67e8.png)

**Comment by rayzhou2017** [comment]
verified
