### ISSUE TITLE
namespace operator 可以移除其他 admin

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1257]
namespace operator 可以移除 admin 吗？（这个用户是该 workspace 的 admin）

![image](https://user-images.githubusercontent.com/22350668/67770339-276a7180-fa91-11e9-9329-85d666feb040.png)

**Comment by rayzhou2017** [comment]
这是一个很严重的权限bug

**Comment by wansir** [comment]
符合预期， 因为cluster层面的权限 > workspace 层级的权限 > 项目层级的权限，因为hgz 这个账号 是workspace-admin ，权限是三级叠加的， 所以 hgz 还是可以管理项目下的成员和角色

**Comment by wansir** [comment]
就类似于 cluster-admin 即使被添加为一个项目的viewer，他依旧可以管理该项目

**Comment by rayzhou2017** [comment]
那要测试一下非cluster admin的operator是否有这个问题

**Comment by huanggze** [comment]
verified
