### ISSUE TITLE
【加急】CentOS Linux release 7.5.1804 安装失败kubesphere2.0.2离线版 

### ISSUE THREAD

**Issue by arraycto** [kubesphere/kubesphere#1258]
[备注]:  大哥哥，安装的过程出现了一个新问题，加班24点都可能解决不了，明天汇报，跪求

**问题描述**
```
TASK [ks-devops/ks-devops : OpenPitrix | Waiting for openpitrix-db] *****************************************************************************************************************************************************************************
Tuesday 29 October 2019  21:06:32 +0800 (0:00:00.776)       0:06:25.399 ******* 
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (15 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (14 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (13 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (12 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (11 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (10 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (9 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (8 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (7 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (6 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (5 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (4 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (3 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (2 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (1 retries left).
fatal: [ks-allinone]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/usr/local/bin/kubectl -n openpitrix-system get pod | grep openpitrix-db-deployment | awk '{print $3}'", "delta": "0:00:00.277817", "end": "2019-10-29 21:11:40.450306", "rc": 0, "start": "2019-10-29 21:11:40.172489", "stderr": "", "stderr_lines": [], "stdout": "Pending", "stdout_lines": ["Pending"]}

PLAY RECAP **************************************************************************************************************************************************************************************************************************************
ks-allinone                : ok=244  changed=90   unreachable=0    failed=1   

Tuesday 29 October 2019  21:11:40 +0800 (0:05:07.919)       0:11:33.318 ******* 
=============================================================================== 
```
**安装环境的硬件配置**
8vCPU 32GB内存
CentOS Linux release 7.5.1804
离线安装kubesphere2.0.2
安装方式all-in-one离线

[备注]:  公司的服务器，内网，不能上网的服务器

**错误信息或截图**

```
TASK [ks-devops/ks-devops : OpenPitrix | Waiting for openpitrix-db] *****************************************************************************************************************************************************************************
Tuesday 29 October 2019  21:06:32 +0800 (0:00:00.776)       0:06:25.399 ******* 
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (15 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (14 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (13 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (12 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (11 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (10 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (9 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (8 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (7 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (6 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (5 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (4 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (3 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (2 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (1 retries left).
fatal: [ks-allinone]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/usr/local/bin/kubectl -n openpitrix-system get pod | grep openpitrix-db-deployment | awk '{print $3}'", "delta": "0:00:00.277817", "end": "2019-10-29 21:11:40.450306", "rc": 0, "start": "2019-10-29 21:11:40.172489", "stderr": "", "stderr_lines": [], "stdout": "Pending", "stdout_lines": ["Pending"]}

PLAY RECAP **************************************************************************************************************************************************************************************************************************************
ks-allinone                : ok=244  changed=90   unreachable=0    failed=1   

Tuesday 29 October 2019  21:11:40 +0800 (0:05:07.919)       0:11:33.318 ******* 
=============================================================================== 
ks-devops/ks-devops : OpenPitrix | Waiting for openpitrix-db --------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 307.92s
openpitrix : OpenPitrix | Installing OpenPitrix(2) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 139.90s
ks-monitor : ks-monitor | Getting monitor installation files ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 20.57s
openpitrix : OpenPitrix | Getting OpenPitrix installation files ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 18.29s
prepare/nodes : Ceph RBD | Installing ceph-common (YUM) --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 14.92s
prepare/nodes : KubeSphere| Installing JQ (YUM) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 8.59s
metrics-server : Metrics-Server | Getting metrics-server installation files -------------------------------------------------------------------------------------------------------------------------------------------------------------- 7.80s
prepare/base : KubeSphere | Labeling system-workspace ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 6.91s
ks-monitor : ks-monitor | Creating manifests --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 5.35s
ks-logging : ks-logging | Creating manifests --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 4.61s
prepare/base : KubeSphere | Getting installation init files ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 4.03s
download : Download items ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 3.85s
prepare/base : KubeSphere | Init KubeSphere ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 3.70s
prepare/nodes : GlusterFS | Installing glusterfs-client (YUM) ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 3.38s
prepare/base : KubeSphere | Create kubesphere namespace ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 3.32s
prepare/base : KubeSphere | Creating manifests ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 3.03s
ks-console : ks-console | Creating manifests --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 2.95s
openpitrix : OpenPitrix | Getting OpenPitrix installation files -------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 2.82s
ks-devops/s2i : S2I | Creating manifests ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 2.76s
ks-monitor : ks-monitor | Installing prometheus-operator --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 2.73s
failed!
[root@JTGC-APP190599 scripts]# kubectl -n openpitrix-system get pod
NAME                                                      READY   STATUS     RESTARTS   AGE
openpitrix-api-gateway-deployment-6bc9747f6c-xxdl2        0/1     Init:0/2   0          8m43s
openpitrix-app-manager-deployment-7df95d8848-hv8cj        0/1     Init:0/2   0          8m42s
openpitrix-category-manager-deployment-694bd85647-6pdwm   0/1     Init:0/2   0          8m42s
openpitrix-cluster-manager-deployment-5c8c797d59-265wf    0/1     Init:0/2   0          8m42s
openpitrix-db-deployment-79f9db9dd9-fcp5s                 0/1     Pending    0          8m45s
openpitrix-etcd-deployment-84d677449b-mt6r5               0/1     Pending    0          8m44s
openpitrix-iam-service-deployment-6bc657d9c6-khgtk        0/1     Init:0/2   0          8m41s
openpitrix-job-manager-deployment-d9d966976-7q7dv         0/1     Init:0/2   0          8m41s
openpitrix-minio-deployment-594df9bb5-wssbw               0/1     Pending    0          8m44s
openpitrix-repo-indexer-deployment-5856985997-fvh76       0/1     Init:0/2   0          8m40s
openpitrix-repo-manager-deployment-b9888bf58-87zrs        0/1     Init:0/2   0          8m40s
openpitrix-runtime-manager-deployment-54c6bb64f4-zmfnd    0/1     Init:0/2   0          8m40s
openpitrix-task-manager-deployment-5479966bfc-lj6xl       0/1     Init:0/2   0          8m39s
[root@JTGC-APP190599 scripts]# cat /etc/resolv.conf
```
**Installer版本**
8vCPU 32GB内存
CentOS Linux release 7.5.1804
离线安装kubesphere2.0.2
安装方式all-in-one离线

**Comment by arraycto** [comment]
明天向领导汇报，现在还没安装成功！跪求大佬指点，在线ing

**Comment by rayzhou2017** [comment]
如果只是演示的话，要么用allinone，要么用2.1 Dev 版，这个版本可以不用配置存储

**Comment by rayzhou2017** [comment]
哦，你已经是allinone, 到https://github.com/kubesphere/ks-installer/commits/master找找答案

**Comment by pixiake** [comment]
kubectl get sc 看下

**Comment by zryfish** [comment]
你的环境能登录么，登录方式可以发到 kubesphere@yunify.com ，我们帮你看下

**Comment by pixiake** [comment]
单节点可以使用local，如果要用nfs的话把local的is_default_class设置成false

helm list看下nfs-client的状态是不是FAILED，如果是的话helm del --purge  xxx，然后手动执行下上边那条命令看看
`/usr/local/bin/helm upgrade --install nfs-client /etc/kubernetes/addons/nfs-client-provisioner --set nfs.server=11.11.147.76 --set nfs.path=/opt/kubesphere --set storageClass.defaultClass=True --namespace kube-system`

**Comment by pixiake** [comment]
1.  确认要使用nfs的话，vars.yaml里修改配置 local_volume_is_default_class: false
2.  nfs的服务端配置建议   *(rw,insecure,sync,no_subtree_check,no_root_squash)
3.  先执行`helm del --purge nfs-client`  ， 然后执行`/usr/local/bin/helm upgrade --install nfs-client /etc/kubernetes/addons/nfs-client-provisioner --set nfs.server=11.11.147.76 --set nfs.path=/opt/kubesphere --set storageClass.defaultClass=True --namespace kube-system`

**Comment by arraycto** [comment]
改成这样？
# Local volume provisioner deployment(Only all-in-one)
local_volume_provisioner_enabled: false
local_volume_provisioner_storage_class: disabled
local_volume_is_default_class: false

正在执行中

**Comment by pixiake** [comment]
可以  执行`helm del --purge nfs-client`了么？

**Comment by arraycto** [comment]
[sysadm@ks-allinone ~]$ clear
[sysadm@ks-allinone ~]$ helm del --purge nfs-client
Error: Get http://localhost:8080/api/v1/namespaces/kube-system/pods?labelSelector=app%3Dhelm%2Cname%3Dtiller: dial tcp 127.0.0.1:8080: connect: connection refused
[sysadm@ks-allinone ~]$ 
是上面的结果，哥哥。all in one是不是以后不支持生产环境（未来，今天只考虑明天 演示搭建好的开发环境）

**Comment by pixiake** [comment]
你的环境能登录么，登录方式可以发到 kubesphere@yunify.com ，我们帮你看下  ssh / tv 12 / 向日葵

**Comment by pixiake** [comment]
卸载了的话  就不用执行上边命令  直接安装即可

**Comment by pixiake** [comment]
allinone的目的是快速体验用的，所以一般都是用local volume，生产环境建议搞多节点，做高可用

**Comment by arraycto** [comment]
1.公司的电脑，没有您说的哪些东西哈，不然早发邮件了哈。
2.说的对，现在改成了local 官方的文档all in one的，但是还是报错。之前就是如下错才改成nfs的，如下：，现在有改成原版的官网离线，还是报下面的错误：
TASK [ks-devops/ks-devops : OpenPitrix | Waiting for openpitrix-db] *****************************************************************************************************************************************************************************
Wednesday 30 October 2019  00:29:33 +0800 (0:00:00.914)       0:07:56.385 ***** 
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (15 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (14 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (13 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (12 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (11 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (10 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (9 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (8 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (7 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (6 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (5 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (4 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (3 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (2 retries left).
FAILED - RETRYING: OpenPitrix | Waiting for openpitrix-db (1 retries left).
fatal: [ks-allinone]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/usr/local/bin/kubectl -n openpitrix-system get pod | grep openpitrix-db-deployment | awk '{print $3}'", "delta": "0:00:00.212271", "end": "2019-10-30 00:34:41.566946", "rc": 0, "start": "2019-10-30 00:34:41.354675", "stderr": "", "stderr_lines": [], "stdout": "Pending", "stdout_lines": ["Pending"]}

PLAY RECAP **************************************************************************************************************************************************************************************************************************************
ks-allinone                : ok=248  changed=68   unreachable=0    failed=1   

Wednesday 30 October 2019  00:34:41 +0800 (0:05:07.647)       0:13:04.033 ***** 
=============================================================================== 
ks-devops/ks-devops : OpenPitrix | Waiting for openpitrix-db --------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 307.65s
openpitrix : OpenPitrix | Installing OpenPitrix(2) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 132.33s
ks-monitor : ks-monitor | Getting monitor installation files ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 19.91s
openpitrix : OpenPitrix | Getting OpenPitrix installation files ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 19.02s
storages/LocalVolume : local_volume | Creating manifests -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 12.05s
download : Download items ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 8.37s
ks-monitor : ks-monitor | Creating manifests --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 7.92s
metrics-server : Metrics-Server | Getting metrics-server installation files ----

**Comment by arraycto** [comment]
[root@ks-allinone scripts]# kubectl get sc
NAME                   PROVISIONER                                       AGE
local (default)        kubernetes.io/no-provisioner                      111m
nfs-client (default)   cluster.local/nfs-client-nfs-client-provisioner   3h5m
[root@ks-allinone scripts]#

**Comment by pixiake** [comment]
vars.yaml里只能设置一个is_default_class，如果用local volume的话设置nfs_client_is_default_class: false

**Comment by arraycto** [comment]
没错，已经是false啊，改成local后nfs的就改成了false，现在的配置如下
# NFS-Client provisioner deployment
nfs_client_enable: false
nfs_client_is_default_class: false
# Hostname of the NFS server(ip or hostname)
#nfs_server: 192.168.xx.xx
# Basepath of the mount point to be used
nfs_path: /opt/kubesphere

**Comment by pixiake** [comment]
卸载重装下，环境里一直有两个default的storageclass，所以pvc不知道找哪个

**Comment by arraycto** [comment]
@pixiake@zryfish两位哥哥，非常感谢您们的不辞辛苦的解答，麻烦把您们回答中带有后缀为76的ip变成xxx（例如10.xx.xx.xx）,公司管的比较严格，感谢理解我一个小白的痛楚·

**Comment by arraycto** [comment]
@pixiake@zryfish 问题已经解决，成功进入登录页面。接下来上生产。kubesphere很棒。接下来，行业内也帮您们推广推广。良心产品，继续关注。

**Comment by calvinyv** [comment]
@arraycto 觉得好给个star 呗 ~

**Comment by arraycto** [comment]
已经star哈。刚才有推荐了几个合作伙伴用这个，今天客户很满意，现在正在搭建集群版本的。
@calvinyv@管理员。我没有编辑权限啊。
麻烦管理员@管理员把：上面回答中带有后缀为76的ip变成xxx（例如10.xx.xx.xx）,公司管的比较严格，比较敏感；感谢理解我一个小白的难处~拜托

**Comment by hg-developer** [comment]
怎么解决得啊，我也遇到了
