### ISSUE TITLE
带 CRD 的应用都不能部署

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1259]
不局限于自带 CRD 的 operator 应用，还包括依赖了 CRD 的应用，比如 mysql-exporter

![image](https://user-images.githubusercontent.com/22350668/67771795-efb0f900-fa93-11e9-8c40-0a580258bcd1.png)

![image](https://user-images.githubusercontent.com/22350668/67771852-06efe680-fa94-11e9-9862-5c14f74b16b4.png)

**Comment by zheng1** [comment]
Same with https://github.com/kubesphere/kubesphere/issues/1245

**Comment by rayzhou2017** [comment]
两天之内能fix吗？

**Comment by zheng1** [comment]
@rayzhou2017  升级client-go影响比较大, 最好放到2.1.1里面

**Comment by rayzhou2017** [comment]
这个是新feature吧，放到3.0吧

**Comment by pengcong06** [comment]
kind/need-to-verify

**Comment by huanggze** [comment]
未解决。使用的 google stable repo

# 无法安装 jaeger operator

![image](https://user-images.githubusercontent.com/22350668/74144747-4358e400-4c38-11ea-8cf3-2c999e263853.png)

# 无法安装 prometheus operator

![image](https://user-images.githubusercontent.com/22350668/74144849-74d1af80-4c38-11ea-88ce-bcedf8608469.png)

**Comment by huanggze** [comment]
verified
