### ISSUE TITLE
"regular" user can't access  "Application Management“ function.

### ISSUE THREAD

**Issue by jerryjedi** [kubesphere/kubesphere#126]
One user has "regular" role, but don't have authorization to access "application management", no ”application template" or “application depot". I think "application template” or "application depot" both are basic component to all users. So pls check what's the wrong.

**Comment by jerryjedi** [comment]
I use "admin" role to change the authorization configuration of "regular" role, add "application management" to role "regular" . Then the normal user who has "regular" role can access "application management" function. Then I have two new question:
1. Is "regular" role is the base role of kubesphere, Can change it by admin？
2. Does KubeSphere has clear definition of initial role ?

**Comment by wansir** [comment]
## User rights management depends on k8s RBAC mode.
Base role is only allowed to be modified by the admin in kubectl, we will fix it.
## User facing initial role.

### Cluster scope initial role
|Role|Explain|
|------|----------|
|`cluster-admin`|Allows management of all resources at the cluster scope.|
|`admin`|Allows management of all resources except users and cluster roles at the cluster scope.|
|`edit`|Allows management of workloads,services and routes  for all projects at the cluster scope.|
|`view`|Allows viewing of workloads,services and routes  for all projects at the cluster scope.|
|`regular`|Default cluster role, only allowed to create projects in cluster scope. Regular users are allowed to manage their own or invited  projects.|


### Project scope initial role
|Role|Explain|
|------|------|
|`admin`|Allows management of all resources  at the project scope.|
|`editor`|Allows management of workloads,services and routes  at the project scope, cannot invite project members. |
|`viewer`|Allows viewing of workloads,services and routes  at the project scope.|
