### ISSUE TITLE
版本支持：k8s v1.16.2啥时候支持哈？

### ISSUE THREAD

**Issue by arraycto** [kubesphere/kubesphere#1261]
[备注]: 版本支持：k8s v1.16.2啥时候支持哈？

**问题描述**
版本支持，服务器已经有k8s v1.16.2
**安装环境的硬件配置**
centos7

[备注]:  私有云

**错误信息或截图**

**Installer版本**
kubesphere2.0.2

**Comment by rayzhou2017** [comment]
要到下一个大版本了了，3.0，预计3个月以后
