### ISSUE TITLE
devops英文文案

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1264]
* [ ] 没有翻译成英文
![Screen Shot 2019-10-30 at 12 32 07 PM](https://user-images.githubusercontent.com/28859385/67829238-71933780-fb11-11e9-91cf-233821c97fb2.png)

**Comment by minghaoye** [comment]
这个周一已经已经修改了，可以更新下环境

**Comment by rayzhou2017** [comment]
verified
