### ISSUE TITLE
websocket英文环境下失效

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1265]
* [x] 我已经发现好几起了，换成中文就有效果
![Screen Shot 2019-10-30 at 12 36 50 PM](https://user-images.githubusercontent.com/28859385/67829429-1746a680-fb12-11e9-92df-9eb2b4fea504.png)

**Comment by rayzhou2017** [comment]
创建PVC也有这个问题

**Comment by rayzhou2017** [comment]
切回来又有效果了
![Screen Shot 2019-10-30 at 12 39 43 PM](https://user-images.githubusercontent.com/28859385/67829491-5f65c900-fb12-11e9-90cc-9196a5c16c64.png)

**Comment by rayzhou2017** [comment]
又测试了一下创建pvc，确实没有动画效果，但会在创建好之后状态有更新

**Comment by leoendless** [comment]
@justahole @minghaoye 看下你们对应的列表页 warning 状态有启用闪烁效果吗，以及websocket 是否有监听

**Comment by minghaoye** [comment]
fixed, next daily build can be verified.

**Comment by rayzhou2017** [comment]
verified
