### ISSUE TITLE
centos7.4 多节点安装,openpitrix-db-deployment 还是报错，以经配置好了存储，空间也创建，但是还是报错

### ISSUE THREAD

**Issue by gongjx11** [kubesphere/kubesphere#1270]
1 服务安装还是报这个错，
![image](https://user-images.githubusercontent.com/21954004/67836032-79a9a200-fb26-11e9-8938-76c71fbd78a4.png)
2 存储使用CEPH 以经配置；
![image](https://user-images.githubusercontent.com/21954004/67836091-a1990580-fb26-11e9-912a-7acd85f9cb28.png)
3 openpitrix-db-deployment 配置也看了是创建PVC一样的
![image](https://user-images.githubusercontent.com/21954004/67836146-cb522c80-fb26-11e9-8692-7a984b6cb62d.png)

搞了好久了，麻烦帮忙看一下，谢谢！

**Comment by Forest-L** [comment]
请再检查下ceph，通过截图来看，pvc都没有bound，还在pending，说明存储还没有好。

**Comment by gongjx11** [comment]
好的 我在看一下，谢谢

**Comment by gongjx11** [comment]
我看了一下这几个配置 都没有说到配PV，创建PVC 的时候需要PV
![image](https://user-images.githubusercontent.com/21954004/67841389-ef1b6f80-fb32-11e9-95bb-8017105da63a.png)

而我这边几次配都没有看到PV，是不是我重新需要增加，而且vars.yaml 也没有看到要配PV。我现在错还是和上面一样的结果；

**Comment by wnxn** [comment]
这个是 ks-only 安装的还是 ks installer ? 用 describe 命令看看 pvc 的 event 有什么报错。

**Comment by gongjx11** [comment]
我是多节点安装的， 不是单节点的
