### ISSUE TITLE
Installing prometheus-operator Failed

### ISSUE THREAD

**Issue by zhyawshhz** [kubesphere/kubesphere#1271]
在现有K8S集群上部署Kubesphere，但是在执行到ks-monitor任务的Installing prometheus-operator一直报错，显示是执行apply -f /etc/kubesphere/prometheus/sources出错，各位大神帮我看下。

![image](https://user-images.githubusercontent.com/4849512/67837553-4cf78980-fb2a-11e9-97f9-b61017b6b366.png)

![image](https://user-images.githubusercontent.com/4849512/67837574-5c76d280-fb2a-11e9-9c14-725b35c3790c.png)

![image](https://user-images.githubusercontent.com/4849512/67837605-6d274880-fb2a-11e9-8b23-1844e69f1d50.png)

**Comment by huanggze** [comment]
请问是否有重复执行安装过？还是首次安装？

**Comment by zhyawshhz** [comment]
> 请问是否有重复执行安装过？还是首次安装？

重复执行过，但是我每次都是把K8S集群重置重新安装的

**Comment by huanggze** [comment]
看报错应该是残留了 CRD 没有删除干净。`kubectl get crd | grep 'monitoring'` 是重置节点系统吗还是怎样重置的？

**Comment by zhyawshhz** [comment]
> 看报错应该是残留了 CRD 没有删除干净。`kubectl get crd | grep 'monitoring'` 是重置节点系统吗还是怎样重置的？

我用的是kubeadm搭建的4节点集群，都是kubeadm reset重置集群再重新搭建的。
