### ISSUE TITLE
500并发压测下， /kapis/logging.kubesphere.io/v1alpha2/cluster接口报错

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1272]
**API：**
/kapis/logging.kubesphere.io/v1alpha2/cluster

**Request  Body**：GET  http://192.168.0.2:31656/kapis/logging.kubesphere.io/v1alpha2/cluster?operation=query&workspaces=space2&namespaces=pp1&workloads=dp1&pods=dp1-5cf847465f-qcxgp&containers=busybox-yg8ov3&log_query=loops&start_time=1572376550883&end_time=1572419750883

**测试结果**：
在500并发/秒的压测下，错误率为49.2%，错误结果为：
HTTP/1.1 500 Internal Server Error
Content-Length: 66
Content-Type: application/json
Date: Wed, 30 Oct 2019 07:31:41 GMT
Server: Caddy

{
 "message": "type: search_phase_execution_exception, reason: "
}

**apiserver日志：**
![image](https://user-images.githubusercontent.com/7677050/67838462-4ec24c80-fb2c-11e9-9cfd-34b763d7a11a.png)

**Comment by huanggze** [comment]
100并发/秒测过吗？2.1 查询做过优化，看起来比 2.0 的压测好些。外接 QingCloud 企业型 ES 的，有时间也测测比较看看

**Comment by mayuhope** [comment]
100并发测过了，100并发/秒没有报错，这是结果：
![image](https://user-images.githubusercontent.com/7677050/67912511-191d7200-fbc5-11e9-9721-eca256f10012.png)

**Comment by huanggze** [comment]
In ks v2.1.1, we will only use elasticsearch for archived log query https://github.com/kubesphere/kubesphere/issues/1650. This helps to further decrease performance pressure. 100 qps test shows the current performance is acceptable.

/kine need-to-verify
