### ISSUE TITLE
应用管理导入helm 包，版本时间不正确

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#1273]
![image](https://user-images.githubusercontent.com/31230341/67839243-263b5200-fb2e-11e9-8ecf-5a186728c36f.png)
https://hub.helm.sh/charts/stable/mysql
/kind bug
/area app-management
/cc @zheng1 @pengcong06

**Comment by zheng1** [comment]
在之前的设计中, 这里定义的是导入时间, 而不是helm包中的创建时间

**Comment by runzexia** [comment]
这里感觉显示创建时间会更合适一点。
3.0有考虑改这个吗？
