### ISSUE TITLE
无法搜索私有仓库中的镜像

### ISSUE THREAD

**Issue by soulseen** [kubesphere/kubesphere#1274]
**Describe the bug(描述下问题)**
根据[文档](https://kubesphere.io/docs/v2.0/zh-CN/system-settings/push-img-harbor/#%E5%A6%82%E4%BD%95%E4%B8%8A%E4%BC%A0%E5%9F%BA%E7%A1%80%E9%95%9C%E5%83%8F%E5%88%B0-harbor)将镜像上传至harbor后，无法在ks中搜到到该镜像

![image](https://user-images.githubusercontent.com/16031013/67838693-d4de9300-fb2c-11e9-8fbe-cb2e31ec03c3.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1 dev

**To Reproduce(复现步骤)**
1. 根据[文档](https://kubesphere.io/docs/v2.0/zh-CN/system-settings/push-img-harbor/#%E5%A6%82%E4%BD%95%E4%B8%8A%E4%BC%A0%E5%9F%BA%E7%A1%80%E9%95%9C%E5%83%8F%E5%88%B0-harbor)将镜像上传至harbor
2. 按照[文档](https://kubesphere.io/docs/v2.0/zh-CN/installation/harbor-installation/#kubesphere-%E4%B8%AD%E4%BD%BF%E7%94%A8-harbor)使用harbor中的镜像，但是无法搜索到该镜像。
3. 调试发现传入参数有误
![image](https://user-images.githubusercontent.com/16031013/67838693-d4de9300-fb2c-11e9-8fbe-cb2e31ec03c3.png)

4. 创建dockerhub密钥，
5. 使用dockerhub密钥搜索私有仓库镜像,镜像仓库中只有tag v1, 无法搜索到该镜像。
![image](https://user-images.githubusercontent.com/16031013/67839647-140de380-fb2f-11e9-9117-f56f6b525ebb.png)

6. 推送tag latest至dockerhub私有仓库，可以搜索到。
![image](https://user-images.githubusercontent.com/16031013/67839594-f6d91500-fb2e-11e9-988c-e0cd173798e5.png)

**Expected behavior(预期行为)**
正常搜索到镜私有仓库的镜像。

**Comment by minghaoye** [comment]
前端传参错误已修复
