### ISSUE TITLE
应用管理版本号展示不全

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#1275]
以 stable/mysql 为例
* [x] 简介页面版本不全，且排序混乱
![image](https://user-images.githubusercontent.com/31230341/67839659-196b2e00-fb2f-11e9-8937-e85a637f8ba5.png)
* [ ] 部署完成后版本号展示不全且排序混乱
![image](https://user-images.githubusercontent.com/31230341/67839773-651dd780-fb2f-11e9-89d1-9cfbe3ce7efc.png)
/kind bug
* [x] 版本号排序不太对
![image](https://user-images.githubusercontent.com/31230341/67840074-04db6580-fb30-11e9-80f7-7d4184a31b28.png)

/area app-management
/cc @zheng1 @pengcong06

**Comment by zheng1** [comment]
/assign @whDongRui 

这里的排序条件是 sequence, 需要改一下

**Comment by whDongRui** [comment]
好的，已经把查询versions的默认排序设置成了sequence。

**Comment by runzexia** [comment]
@whDongRui 我试了一下十条后的版本部署页面也可以选择版本呀。
现在还有第二个版本信息展示不太全

**Comment by whDongRui** [comment]
哦，应用详情页面版本的展示我问一下设计，看要不要加分页。

**Comment by whDongRui** [comment]
@runzexia @Carlosfengv 这个跟设计沟通过了，这个页面版本信息暂时只显示10条最新的版本就可以了，加分页的话得换另外的显示风格。
