### ISSUE TITLE
centos7.4 多节点，还是之前哪个问题npitrix-db-deployment

### ISSUE THREAD

**Issue by gongjx11** [kubesphere/kubesphere#1277]
https://github.com/kubesphere/kubesphere/issues/1270
我看了一下这几个配置 都没有说到配PV，创建PVC 的时候需要PV
image

而我这边几次配都没有看到PV，是不是我重新需要增加，而且vars.yaml 也没有看到要配PV。我现在错还是和上面一样的结果；

**Comment by gongjx11** [comment]
https://user-images.githubusercontent.com/21954004/67841389-ef1b6f80-fb32-11e9-95bb-8017105da63a.png

**Comment by rayzhou2017** [comment]
这肯定是存储的问题

**Comment by gongjx11** [comment]
我知道是存储的问题，具体想问一下这个是不会是会创建PV ，还有就是一个问题 我发现我每次配置好的ceph的secret值，装的时候都会变。
![image](https://user-images.githubusercontent.com/21954004/67842731-b29d4300-fb35-11e9-8ab0-26be929b5855.png)

我想问一下，kubesphere  存储ceph需不需要配pv

**Comment by rayzhou2017** [comment]
不需要，kubesphere用的是动态存储分配

**Comment by gongjx11** [comment]
好的 哪我在看一下吧，谢谢了！

**Comment by gongjx11** [comment]
我就是参考这个去配的。

**Comment by wnxn** [comment]
describe 看看 pvc 有什么报错

**Comment by gongjx11** [comment]
以经解决了，谢谢
