### ISSUE TITLE
应用图标上传应过滤文件类型，另外页面上应加上一些帮助信息

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1279]
**Describe the bug(描述下问题)**
应用图标上传应过滤文件类型，另外页面上应加上一些帮助信息

现在文件上传可以选择任意文件类型，另外没有任何帮助信息，我们应该告诉应用开发者推荐图标的格式、大小等信息

![Jietu20191030-175238](https://user-images.githubusercontent.com/28883416/67847719-470ba380-fb3e-11e9-8527-d1e96d9794fd.png)

**Comment by Carlosfengv** [comment]
zpl://screen?pid=5cbe7fbc2f55d8b73f56811b&sid=5d26dfd36ed932130ced215f

**Comment by whDongRui** [comment]
已经按设计图加了应用图标上传的提示文字

![image](https://user-images.githubusercontent.com/38676269/67850865-352cff00-fb44-11e9-9672-fb9b7cefc695.png)

**Comment by calvinyv** [comment]
@whDongRui 文件类型过滤呢？ks上已经有现成的实现了，在b2i那里，具体可以咨询 @minghaoye

**Comment by whDongRui** [comment]
file有一个accept属性可以限制上传的文件类型，op中涉及到文件上传的位置都加了类型过滤。

**Comment by calvinyv** [comment]
verified
