### ISSUE TITLE
从应用实例页面左上快捷跳转到应用 404

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1280]
问题见录屏：
https://yunify.anybox.qingcloud.com/s/R4mC8Iv6k1QBmqRGA1mJMIuEq22pUiiQ

**Comment by whDongRui** [comment]
这个是什么环境？你更新一下最新代码或换一个环境测试一下。我测试没有复现这个问题。

**Comment by calvinyv** [comment]
verified
