### ISSUE TITLE
导入第三方repo后，部署部分应用没有工作负载

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#1285]
导入第三方repo后，部署其中一部分应用没有工作负载，我已经在 Values.yml 中定义了 namespace: "My namespace"，复现可通过仓库： "https://openchart.choerodon.com.cn/choerodon/c7n/"。

![image](https://user-images.githubusercontent.com/40452856/67914410-fb530b80-fbca-11e9-8e60-c9a093307c3f.png)

![image](https://user-images.githubusercontent.com/40452856/67914420-04dc7380-fbcb-11e9-8a41-ff35a223b114.png)

**Comment by zheng1** [comment]
tidb 和 oauth-server 这两个手动通过helm安装也是失败的, 估计是还没开发完.

**Comment by zheng1** [comment]
skywalk这个应用查不出来工作负载这个问题看上去是开发的helm包不太规范. op需要兼容这种情况. 等2.1发布之后考虑研究如何兼容. @pengcong06

**Comment by zheng1** [comment]
修复了. 原因是这个chart里面的template扩展名是`.yml`, 这不是helm推荐的做法, 不过op还是兼容了. 

@FeynmanZhou  在ks的 /system-workspace/projects/openpitrix-system/deployments/openpitrix-rp-kubernetes-deployment/resource-status 页面减一加一之后, 删掉老的应用重新部署试试
