### ISSUE TITLE
HA安装nameserver有告警

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1286]
* [ ] nameserver也有告警
![Screen Shot 2019-10-29 at 11 01 18 AM](https://user-images.githubusercontent.com/28859385/67734273-8d2c0e80-fa3b-11e9-9861-2ed74f5a6e53.png)

**Comment by zryfish** [comment]
这和机器的dns设置有关，glibc只能识别最多三个nameserver，设置多了会告警，一般来说没有什么大问题，某些情况会导致问题
