### ISSUE TITLE
HA有单点

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1287]
* [ ] 7个服务有单点，无状态服务需不需要考虑HA？
![Screen Shot 2019-10-29 at 11 38 20 AM](https://user-images.githubusercontent.com/28859385/67735977-bef3a400-fa40-11e9-9b0e-4310cc0f0db6.png)
![Screen Shot 2019-10-29 at 11 41 17 AM](https://user-images.githubusercontent.com/28859385/67736053-109c2e80-fa41-11e9-8899-14350b67c298.png)
![Screen Shot 2019-10-29 at 11 47 33 AM](https://user-images.githubusercontent.com/28859385/67736264-f9117580-fa41-11e9-9050-2661f110759e.png)
![Screen Shot 2019-10-29 at 11 57 03 AM](https://user-images.githubusercontent.com/28859385/67736629-43dfbd00-fa43-11e9-82a3-cceb45365637.png)

**Comment by calvinyv** [comment]
fixed in 2.1.0
