### ISSUE TITLE
kubesphere

### ISSUE THREAD

**Issue by liuflylove666** [kubesphere/kubesphere#1289]
kubesphere 能否提供基于docker run的 安装方式呢？一步一步的安装步骤，一建安装出错后排出困难

**Comment by pixiake** [comment]
目前的安装方式主要有两种：

1. 裸机整体部署（docker + k8s + kubesphere）
       这种方式后续应该可以提供docker run的方式，不过需要单独找一台装了docker的机器做taskbox了。
2. Install KubeSphere on existing kubernetes cluster 
       这种方式是纯容器化部署，如果已有k8s集群，可以选择这种部署方式。
