### ISSUE TITLE
All-in-One 模式 安装失败

### ISSUE THREAD

**Issue by zhangjun050754** [kubesphere/kubesphere#1293]
![image](https://user-images.githubusercontent.com/22231085/67934155-3de40a80-fc02-11e9-99a6-17a303f6a6ae.png)

**Comment by pixiake** [comment]
tiller 异常，`kubectl get pod -n kube-system`看看pod状态

机器什么配置？

**Comment by zhangjun050754** [comment]
![image](https://user-images.githubusercontent.com/22231085/67936173-41799080-fc06-11e9-820b-d262f9725ed3.png)

**Comment by zhangjun050754** [comment]
![image](https://user-images.githubusercontent.com/22231085/67936702-36733000-fc07-11e9-8c92-e32e2a19fef3.png)
这个helm有问题

**Comment by pixiake** [comment]
describe  那些pod看看为啥pending

**Comment by zhangjun050754** [comment]
> describe 那些pod看看为啥pending

![image](https://user-images.githubusercontent.com/22231085/67997042-2c941000-fc8d-11e9-976e-48c3b3097a6d.png)

**Comment by pixiake** [comment]
`kubectl  get pod -n kubesphere-devops-system`看下里边有没有pod

**Comment by zhangjun050754** [comment]
> kubectl get pod -n kubesphere-devops-system

![image](https://user-images.githubusercontent.com/22231085/67997304-8c3eeb00-fc8e-11e9-85a4-6856a49fd7aa.png)

**Comment by zhangjun050754** [comment]
journalctl -xefu kubelet 报这个错
![image](https://user-images.githubusercontent.com/22231085/67997318-a082e800-fc8e-11e9-9855-ca8a66ce1d46.png)

**Comment by pixiake** [comment]
这个是说kube-scheduler起不来，应该还有别的报错

**Comment by zhangjun050754** [comment]
> 这个是说kube-scheduler起不来，应该还有别的报错

![image](https://user-images.githubusercontent.com/22231085/67997541-741b9b80-fc8f-11e9-8d7f-f2dab850e29f.png)
![image](https://user-images.githubusercontent.com/22231085/67997545-7d0c6d00-fc8f-11e9-94cf-ce169534dc20.png)

**Comment by zhangjun050754** [comment]
> 这个是说kube-scheduler起不来，应该还有别的报错

![image](https://user-images.githubusercontent.com/22231085/67998816-bdbab500-fc94-11e9-8efd-23fba3bc2d2b.png)

**Comment by pixiake** [comment]
机器可以远程嘛(ssh  tv12   向日葵)?  可以的话把信息发到 kubesphere@yunify.com，我们上去看看

**Comment by zhangjun050754** [comment]
> 机器可以远程嘛(ssh tv12 向日葵)? 可以的话把信息发到 [kubesphere@yunify.com](mailto:kubesphere@yunify.com)，我们上去看看

已经好了 感谢支持 估计之前没卸载干净 kube-scheduler端口被占用了 起不来
