### ISSUE TITLE
应用通过审核后，在列表看到状态还是“开发中”

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#1295]
应用通过审核后，在列表看到状态还是“开发中”，感觉比较奇怪。

![image](https://user-images.githubusercontent.com/40452856/67934588-248f8e00-fc03-11e9-882f-2670cacdf39b.png)

![image](https://user-images.githubusercontent.com/40452856/67934602-2d805f80-fc03-11e9-8d68-206ecc01265a.png)

**Comment by zheng1** [comment]
在op的设计中就是这样的, 开发者上架应用之后状态才会改变.

**Comment by whDongRui** [comment]
这个是由于app，version设计的状态不同导致的，可以看一下这个issue https://github.com/kubesphere/kubesphere/issues/975。
