### ISSUE TITLE
centos7.4 多节点集群多次安装harbor 报错，请问一下是什么原因

### ISSUE THREAD

**Issue by gongjx11** [kubesphere/kubesphere#1296]
![image](https://user-images.githubusercontent.com/21954004/67934853-9ff13f80-fc03-11e9-81d4-ae0a0479bb70.png)

**Comment by gongjx11** [comment]
我用的是单节点部署方式在多节点集群去部署的harbor，麻烦帮忙看一下，哪里的问题，谢谢！

**Comment by Forest-L** [comment]
1、单节点部署方式在多节点集群，没太明白你这样做的目的？
2、通过报错信息来看，qingcloud_ib_enable参数没有定义。

**Comment by gongjx11** [comment]
我以经解决了，把哪行注掉了，就可以了
