### ISSUE TITLE
告警界面操作问题汇总

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1298]
- [ ] 单位显示有误，共七处

此处应为 Core

![image](https://user-images.githubusercontent.com/22350668/67936196-4b02f880-fc06-11e9-886e-2ba081164e10.png)

红线的绘图不对，对应的值应该也是以 Core 为单位的住（fix 的时候考虑一下，不是简单改单位，如果前端做了单位换算，要正确换算出来）

![image](https://user-images.githubusercontent.com/22350668/67936371-a2a16400-fc06-11e9-803a-47916b8e651c.png)

红线下面的这个总结栏的单位

![image](https://user-images.githubusercontent.com/22350668/67937756-18a6ca80-fc09-11e9-8090-b52cd7dc1862.png)

红线旁边告警详情的单位

![image](https://user-images.githubusercontent.com/22350668/67938134-dcc03500-fc09-11e9-8573-f747d5dd005a.png)

项目首页告警概览里的单位

![image](https://user-images.githubusercontent.com/22350668/67937893-5dcafc80-fc09-11e9-8518-4628083cafc9.png)

告警规则页的单位

![image](https://user-images.githubusercontent.com/22350668/67938025-a97da600-fc09-11e9-893c-84963e7ccec6.png)

告警历史页的单位

![image](https://user-images.githubusercontent.com/22350668/67938078-c3b78400-fc09-11e9-865f-3d43cc2730da.png)

- [ ] 针对有状态副本集类型，创建告警规则中，中途回退到第一步后无法再修改工作负载类型，只能选 “部署” 了

![image](https://user-images.githubusercontent.com/22350668/67938965-86ec8c80-fc0b-11e9-8316-11fb24af9738.png)

- [ ] 监控图尾部是 0？为啥绘制了未来 10 分钟的图，是设计上这样吗？需要检查下设计图

![image](https://user-images.githubusercontent.com/22350668/67939199-011d1100-fc0c-11e9-9105-b746dbcda3e7.png)

- [ ] 只选了一个监控目标用于告警，但显示了两个。（是 API 用了正则筛选，应该完全匹配）

![image](https://user-images.githubusercontent.com/22350668/68000176-f7da8580-fc99-11e9-968a-959d0152c06f.png)

![image](https://user-images.githubusercontent.com/22350668/68000166-ef824a80-fc99-11e9-9830-8879e03f0c39.png)

**Comment by justahole** [comment]
kind/need-to-verify

**Comment by huanggze** [comment]
这里不对 /remove-kind need-to-verify
![image](https://user-images.githubusercontent.com/22350668/68458285-5fb24280-023d-11ea-82b8-1fb31ba1b0af.png)

![image](https://user-images.githubusercontent.com/22350668/68458290-63de6000-023d-11ea-9428-47dde39cb697.png)
