### ISSUE TITLE
NodePort方式暴露的服务（比如mysql,redis）这些，客户端工具连接到一定的时间不操作就会被中断

### ISSUE THREAD

**Issue by xwb2535** [kubesphere/kubesphere#1302]
端口暴露的公网访问的服务，在一定的时间后就会出现连接中断的问题。这个问题，应该是检查服务器是否有设置关闭连接还是看kubesphere的设置？或者你们知道哪里的设置么？

**Comment by wansir** [comment]
检查一下公网lb 有没有超时设置

**Comment by xwb2535** [comment]
> 检查一下公网lb 有没有超时设置

没有设置LB，纯粹端口暴露模式。请问，怎么检查，应该检查kubesphere 设置还是检查 云服务器的设置。比如我的是阿里云 centos 7.5.如果应该检查 服务器那边的设置，我就去问阿里云。

**Comment by xwb2535** [comment]
以前用docker模式都不会出现端口被终端。就比如mysql工作，打开的窗口，2分钟不动之后，再去执行一条语句，mysql工具就会卡死，好像连接被关闭，他要重新打开连接，等待1分钟之后重连，然后才会执行成功语句，redis工具也是一样。换了好几个网络都这样，以前用docker单机直接暴露主机端口是不存在这种情况。现在用这个k8s集群就经常这样。我也不知道应该要询问阿里云是因为全部端口暴露了他固定时间关闭我的连接，还是这边dns管理出现问题导致这样的现象。跟之前的putty 的远程很像。

**Comment by wansir** [comment]
公网ip 是直接绑定在主机上的吗？ NodePort相较于docker 网络只是多了几次nat转发，不会有超时机制，你可以检查一下网络链路，看看是在哪个环节发生了中断。实际使用中NodePort不应该出现这样的问题

**Comment by xwb2535** [comment]
恩。阿里云，直接绑定到主机，用Ip+端口访问。

**Comment by xwb2535** [comment]
[client]
port = 3306
socket = /var/run/mysqld/mysqld.sock
[mysql]
no-auto-rehash

[mysqld]
port = 3306
datadir = /var/lib/mysql
lower_case_table_names = 1
max_connections = 3000
max_user_connections=2980 
max_connect_errors=1000000
max_allowed_packet = 1073741824
event_scheduler = 1
sql_mode = "STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER"
interactive_timeout = 1800
wait_timeout = 1800
connect_timeout=10
net_read_timeout=30
net_write_timeout=60
net_retry_count=10
lower_case_table_names = 1
table_open_cache = 8192
table_definition_cache = 8192
table_open_cache_instances = 16

**Comment by xwb2535** [comment]
[client]
port = 3306
socket = /var/run/mysqld/mysqld.sock
[mysql]
no-auto-rehash

[mysqld]
port = 3306
datadir = /var/lib/mysql
lower_case_table_names = 1
max_connections = 3000
max_user_connections=2980 
max_connect_errors=1000000
max_allowed_packet = 1073741824
event_scheduler = 1
sql_mode = "STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER"
interactive_timeout = 1800
wait_timeout = 1800
connect_timeout=10
net_read_timeout=30
net_write_timeout=60
net_retry_count=10
lower_case_table_names = 1
table_open_cache = 8192
table_definition_cache = 8192
table_open_cache_instances = 16

**Comment by wansir** [comment]
检查一下阿里云安全组的配置,可以搜索到相关的问题
