### ISSUE TITLE
all in one 离线 安装失败

### ISSUE THREAD

**Issue by ethan12871** [kubesphere/kubesphere#1303]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**

**安装环境的硬件配置**
VMware虚拟机  8核16G
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**

TASK [ks-devops/sonarqube : Sonarqube | Deploy Sonarqube] ********************************************************************************************************************************************************************************************************************
Thursday 31 October 2019  10:05:10 -0400 (0:00:00.337)       0:00:48.674 ****** 
fatal: [ks-allinone]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm upgrade --install ks-sonarqube /etc/kubesphere/sonarqube/sonarqube-0.13.5.tgz -f /etc/kubesphere/sonarqube/custom-values-sonarqube.yaml --namespace kubesphere-devops-system", "delta": "0:00:02.114211", "end": "2019-10-31 10:05:12.893834", "msg": "non-zero return code", "rc": 1, "start": "2019-10-31 10:05:10.779623", "stderr": "Error: UPGRADE FAILED: Get https://10.233.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%!D(MISSING)ks-sonarqube%!C(MISSING)OWNER%!D(MISSING)TILLER%!C(MISSING)STATUS%!D(MISSING)DEPLOYED: dial tcp 10.233.0.1:443: connect: no route to host", "stderr_lines": ["Error: UPGRADE FAILED: Get https://10.233.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%!D(MISSING)ks-sonarqube%!C(MISSING)OWNER%!D(MISSING)TILLER%!C(MISSING)STATUS%!D(MISSING)DEPLOYED: dial tcp 10.233.0.1:443: connect: no route to host"], "stdout": "", "stdout_lines": []}

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
ks-allinone                : ok=163  changed=18   unreachable=0    failed=1   

Thursday 31 October 2019  10:05:12 -0400 (0:00:02.232)       0:00:50.907 ****** 
=============================================================================== 
prepare/nodes : Ceph RBD | Installing ceph-common (YUM) --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 5.78s
storages/LocalVolume : local_volume | Creating manifests -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 5.44s
prepare/nodes : NFS-Client | Installing nfs-utils (YUM) --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 2.70s
storages/LocalVolume : local_volume | Creating directories for local_volume ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 2.33s
ks-devops/sonarqube : Sonarqube | Deploy Sonarqube -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 2.23s
prepare/nodes : GlusterFS | Installing glusterfs-client (YUM) --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 2.10s
download : Download items --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.31s
prepare/nodes : KubeSphere| Installing JQ (YUM) ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 1.17s
storages/LocalVolume : local_volume | Creating PV --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.53s
download : Sync container --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.52s
download : Sync container --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.48s
download : Download items --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.45s
download : Download items --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.41s
download : Sync container --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.40s
download : Sync container --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.39s
download : Download items --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.39s
download : Register docker images info -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.36s
ks-devops/sonarqube : Sonarqube | Creating manifests ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 0.34s
download : Register docker images info -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.33s
download : Register docker images info -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.32s
failed!

**Installer版本**
2.0.2

**Comment by Forest-L** [comment]
检查下防火墙是否关闭了，
https://kubesphere.io/docs/v2.0/zh-CN/faq/faq-install/  可以先在这里找下答案。
