### ISSUE TITLE
Feature: provide an option to switch logging by time in ascending or descending order

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1306]
**Describe the bug(描述下问题)**
Feature: provide an option to switch logging by time in ascending or descending order

Currently，container logging page and log query page only support logging by time in descending order, hope to provide ascending option for more better logging experience. 

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0 dev
Kubernetes: (If KubeSphere installer used, you can skip this)

**Comment by zryfish** [comment]
We are now following the order just as like K8s does, I think we can close this issue now.
