### ISSUE TITLE
openpitrix-db-deployment安装出问题

### ISSUE THREAD

**Issue by zhyawshhz** [kubesphere/kubesphere#1307]
hi all，
       在解决ceph存储的问题后，部署顺利执行到ks-devops/ks-devops任务，然后报下面的错误：
![image](https://user-images.githubusercontent.com/4849512/68008598-70e9d500-fcba-11e9-9485-f4e3986a41b4.png)

describe pod后发现安装mysql报错：
![image](https://user-images.githubusercontent.com/4849512/68008699-b60e0700-fcba-11e9-8407-db4efdc488b4.png)

一直在这个问题上走不过去，有哪位大神遇到过吗？求指导！！！

**Comment by zheng1** [comment]
你好, 请贴一下对应的 OS version 和 Kernel version

**Comment by zhyawshhz** [comment]
> 你好, 请贴一下对应的 OS version 和 Kernel version

![image](https://user-images.githubusercontent.com/4849512/68010261-1acb6080-fcbf-11e9-97f0-8043a4237897.png)

**Comment by zhyawshhz** [comment]
> 你好, 请贴一下对应的 OS version 和 Kernel version

centos 7.6的

**Comment by zheng1** [comment]
请贴一下docker的版本

**Comment by zhyawshhz** [comment]
> 请贴一下docker的版本

![image](https://user-images.githubusercontent.com/4849512/68017725-4e63b600-fcd2-11e9-9e57-4758ac0c5a30.png)
我咋感觉还是存储这块的问题呀
非常感谢您能看到我这问题，非常感谢！

**Comment by zheng1** [comment]
这个docker的版本太老, 建议使用 19.03.3 

参考 https://github.com/moby/moby/issues/37009#issuecomment-495297050 至少需要使用 18.09.1 才能避免这种问题

**Comment by zhyawshhz** [comment]
> 这个docker的版本太老, 建议使用 19.03.3
> 
> 参考 [moby/moby#37009 (comment)](https://github.com/moby/moby/issues/37009#issuecomment-495297050) 至少需要使用 18.09.1 才能避免这种问题

![image](https://user-images.githubusercontent.com/4849512/68183156-815dc080-ffd6-11e9-8da3-2b1eea3aa9ec.png)
![image](https://user-images.githubusercontent.com/4849512/68183169-8884ce80-ffd6-11e9-9956-6122f11238bd.png)
按照您说的升级到18.09.7，还是解决不了呀

**Comment by zhyawshhz** [comment]
> 这个docker的版本太老, 建议使用 19.03.3
> 
> 参考 [moby/moby#37009 (comment)](https://github.com/moby/moby/issues/37009#issuecomment-495297050) 至少需要使用 18.09.1 才能避免这种问题

我尝试把所有的docker镜像全部删除了，重新部署重新下载了一次，然后就好了。
