### ISSUE TITLE
【建议】UI改进

### ISSUE THREAD

**Issue by magicsong** [kubesphere/kubesphere#1308]
**General remarks**
界面上有很多如下的弹窗，
![image](https://user-images.githubusercontent.com/4010679/68009357-bd361480-fcbc-11e9-9e8d-d155eed81ec1.png)
右上角已经有显式的关闭按钮了，但是一旦用户不小心点了一下弹窗外面的区域，弹窗消失。消失之后刚刚创建的yaml就没了，稍微有点影响体验（界面微微有点挤，容易点到外面）。

**Comment by liuyp2018** [comment]
fixed and verfied in v3.1.1-rc.1
