### ISSUE TITLE
移除项目全部成员后，项目基本信息中仍显示 admin 为管理员

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1312]
![image](https://user-images.githubusercontent.com/22350668/68013239-5d913680-fcc7-11e9-8d7a-cd26b81ab5fc.png)

![image](https://user-images.githubusercontent.com/22350668/68013252-63871780-fcc7-11e9-8ec8-8636e35db574.png)

**Comment by leoendless** [comment]
Fixed

**Comment by huanggze** [comment]
![image](https://user-images.githubusercontent.com/22350668/68373788-8c535500-017e-11ea-883f-4cac4c615cfe.png)

/remove-kind need-to-verify

**Comment by leoendless** [comment]
Fixed

**Comment by huanggze** [comment]
verified
