### ISSUE TITLE
替换项目管理员后，项目基本信息中仍显示 admin 为管理员

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1313]
![image](https://user-images.githubusercontent.com/22350668/68013386-bbbe1980-fcc7-11e9-908f-00783c0909e7.png)

![image](https://user-images.githubusercontent.com/22350668/68013395-c2e52780-fcc7-11e9-9e8a-4345b65d9da8.png)

**Comment by wansir** [comment]
#1312 这里的管理员展示的是 annotation 中 creator 这个字段 @leoendless  这里文案改成创建者吧，这个字段不用做权限关系的维护

**Comment by leoendless** [comment]
Fixed

**Comment by wansir** [comment]
这个字段 目前版本不做维护，只是在创建项目的时候绑定了管理员的角色，但实际管理员可以有多个

**Comment by huanggze** [comment]
别忘了概览这里还有一处 @leoendless 

![image](https://user-images.githubusercontent.com/22350668/68017083-dd6fce80-fcd0-11e9-82fc-ac4f4025321d.png)

**Comment by leoendless** [comment]
更新下再看看

**Comment by leoendless** [comment]
Same with #1312
