### ISSUE TITLE
某些情况的角色只能部署自制应用

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1316]
某些角色只能创建自制应用。比如，这是一个 cluster-regular + workspace-admin + namespace-admin 的用户。还有其他情况也会。但 cluster-admin 无这个问题

![image](https://user-images.githubusercontent.com/22350668/68015103-56205c00-fccc-11e9-859f-9b40378e76ba.png)

![image](https://user-images.githubusercontent.com/22350668/68015401-1148f500-fccd-11e9-9907-87b2c60d4c20.png)

![image](https://user-images.githubusercontent.com/22350668/68015444-245bc500-fccd-11e9-8baf-fd7fafd903e6.png)

**Comment by wansir** [comment]
是不是没装op模块?

**Comment by huanggze** [comment]
哦是的
