### ISSUE TITLE
日志系统没有记录纯Pod日志

### ISSUE THREAD

**Issue by magicsong** [kubesphere/kubesphere#1318]
从网上copy了一个sidecar的pod(原生pod，非高级workload)测试日志，但是这个pod的日志并没有被日志系统搜索到
/kind bug
/area logging

**Comment by huanggze** [comment]
单独部署的 Pod 没算作工作负载，得按 pod name 来查询。目前支持的按工作负载查询的类型有：Deployment、StatefulSet、DaemonSet、Job
