### ISSUE TITLE
projects 点不进去

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1319]
* [x] 在platform下打开projects，但点不进去具体的project
<img width="840" alt="Screen Shot 2019-11-01 at 9 17 40 PM" src="https://user-images.githubusercontent.com/28859385/68027392-32b9d900-fced-11e9-9ab6-5f895f103f8b.png">

**Comment by leoendless** [comment]
Fixed

**Comment by rayzhou2017** [comment]
verified
