### ISSUE TITLE
project role with manage access problems

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1321]
* [x] 用admin创建了一个manage projects角色，然后创建一个有此角色的账号，切换账号登录，显示是regular ueser

* [x] 打开projects，报403错误

* [x] 切换回admin登录，查看此自定义role，白屏

**Comment by leoendless** [comment]
@wansir 第二个问题需要 给 projects manage 带上 ``kapis/resources.kubesphere.io/v1alpha2/workspaces`` 的 GET 权限

**Comment by wansir** [comment]
fixed

**Comment by rayzhou2017** [comment]
verified
