### ISSUE TITLE
Strange alert rule names shown when creating alert policy

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1323]
**Describe the bug(描述下问题)**
Strange alert rule names shown when creating alert policy

For UI issues please also add a screenshot that shows the issue.
<img width="1680" alt="Jietu20191102-205114" src="https://user-images.githubusercontent.com/28883416/68071166-bb4e7d00-fdb2-11e9-9f8d-c056884008f1.png">

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0 dev 20191102
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**
1. Go to some workplace dashbaord 
2. Try to create a new alert policy 

**Expected behavior(预期行为)**

**Comment by Ma-Dan** [comment]
这3个指标
CPU load average 1 minute
CPU load average 5 minutes
CPU load average 15 minutes
这里的长度是足够的，或者显示简写
CPU load avg 1 min
CPU load avg 5 min
CPU load avg 15 min

**Comment by calvinyv** [comment]
@justahole could see this issue on 20191105

<img width="720" alt="Jietu20191105-204350" src="https://user-images.githubusercontent.com/28883416/68208844-111e6180-000d-11ea-918d-83cb41b46cf4.png">

**Comment by calvinyv** [comment]
verified
