### ISSUE TITLE
Regression: No link to volume detail page in volumes page

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1324]
**Describe the bug(描述下问题)**
Regression: No link to volume detail page in volumes page

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0 dev 20191102
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**
1. Go to 'Infrastucture - storageclass'
2. Click on 'csi-qingcloud.', you could a list of mounted volumes
3. I can't click any of volume to see detail page

**Expected behavior(预期行为)**
it should be linked to detail page when clicking each volume name

**Comment by leoendless** [comment]
这里因为权限问题，不推荐从这里跳转查看

**Comment by calvinyv** [comment]
@leoendless 那是以后都可以跳转到详情页了么？

**Comment by leoendless** [comment]
最好不要从这里跳转了，感觉直接跳转过去不太合理

**Comment by calvinyv** [comment]
如果不能跳转，那我认为此处应该在加上一列展示磁盘使用率
放到下个版本改善吧

**Comment by calvinyv** [comment]
closed
