### ISSUE TITLE
Globalization: Environment or Envionmental? 

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1325]
**Describe the bug(描述下问题)**
It should be 'Environment Variables' or 'Environmental Variables'?

For UI issues please also add a screenshot that shows the issue.
<img width="541" alt="Jietu20191102-210359" src="https://user-images.githubusercontent.com/28883416/68071329-80e5df80-fdb4-11e9-8a61-3b8d8f7e72b4.png">

**Comment by calvinyv** [comment]
@rayzhou2017 @FeynmanZhou

**Comment by rayzhou2017** [comment]
Environment

**Comment by leoendless** [comment]
Fixed
