### ISSUE TITLE
HA console不工作

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1326]
* [ ] 关机一个master，pod都正常，但console登录不进去，报internal error

**Comment by rayzhou2017** [comment]
原因应该是这样的，node 宕掉，系统需要几分钟检测，其实pod是死了，等检测周期到了会重新调度，系统转为工作正常。这应该是预期的，不过需要文档写清楚多长时间恢复正常。

**Comment by rayzhou2017** [comment]
这个internal error最好改一下错误提示

**Comment by calvinyv** [comment]
duplicate as https://github.com/kubesphere/console/issues/43
/close
