### ISSUE TITLE
未安装 istio，ks-controller-manager 一直报错

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1328]
![image](https://user-images.githubusercontent.com/22350668/68083498-04123e80-fe64-11e9-99c4-9f9d7f37fc94.png)

**Comment by rayzhou2017** [comment]
这个要fix，不然没有装istio的用户日志系统会跟塞了炸弹似的

**Comment by zryfish** [comment]
修复了

**Comment by huanggze** [comment]
verified
