### ISSUE TITLE
openldap 开启了 debug 模式，日志产生特别多

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1329]
![image](https://user-images.githubusercontent.com/22350668/68083566-0cb74480-fe65-11e9-98fa-0609a975ee5d.png)

![image](https://user-images.githubusercontent.com/22350668/68083569-193b9d00-fe65-11e9-9c3e-81042e4d3d00.png)

**Comment by wansir** [comment]
开发过程中，release 会关掉
