### ISSUE TITLE
切换浏览存储系统时，“自定义” 选项里面的内容被错误填充

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1332]
首次进入“自定义”选项时，是待填写状态，显示正常的
![image](https://user-images.githubusercontent.com/22350668/68085670-65470b80-fe7e-11e9-8e6f-4cc0967e9c68.png)

![image](https://user-images.githubusercontent.com/22350668/68085671-6aa45600-fe7e-11e9-9efd-f8d02e836102.png)

此时回退到上一步，查看其他 “存储系统” ，比如 Ceph RBD 后再切换回来，发现被填充

![image](https://user-images.githubusercontent.com/22350668/68085682-83ad0700-fe7e-11e9-8889-3fd81182d5d1.png)

![image](https://user-images.githubusercontent.com/22350668/68085695-af2ff180-fe7e-11e9-8df0-86e3e31d90fe.png)

**Comment by justahole** [comment]
kind need-to-verify
