### ISSUE TITLE
公司自己的镜像仓库如何对接到KubeSphere？

### ISSUE THREAD

**Issue by PYIsOk** [kubesphere/kubesphere#1335]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
公司自己的镜像仓库如何对接到kubesphere？
**安装环境的硬件配置**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**

**Installer版本**
2.02离线版

**Comment by zheng1** [comment]
你好, 可以参考 https://kubesphere.io/docs/v2.0/zh-CN/configuration/image-registry/

**Comment by PYIsOk** [comment]
> 你好，可以参考https://kubesphere.io/docs/v2.0/zh-CN/configuration/image-registry/

谢谢您，不过我们是自己搭建的nexus

**Comment by PYIsOk** [comment]
> 你好，可以参考https://kubesphere.io/docs/v2.0/zh-CN/configuration/image-registry/

谢谢您，不过我们是自己搭建的nexus。想要对接KubeSphere
