### ISSUE TITLE
【Google Cloud centos 7 安装 2.1 失败】

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#1336]
第一次报错：

![image](https://user-images.githubusercontent.com/40452856/68096150-d079f780-fee9-11e9-8da9-33c8304fc5f4.png)

发现 `kubesphere/roles/ks-installer/tasks/main.yaml` 目录缺少 kubectl 的环境变量，修改了该文件，installer 也应当调整。

第二次报错：
![image](https://user-images.githubusercontent.com/40452856/68096089-7ed16d00-fee9-11e9-8ffa-eee93fafcbe5.png)
原因不确定。

**Comment by Forest-L** [comment]
1、请检查下本地源是否正常，执行如下指令：yum clean all;yum makecache

**Comment by Forest-L** [comment]
1、重新安装报错插件container-selinux，yum install container-selinux -y
2、如果重安装插件报错，卸载该插件，更新yum源，yum remove container-selinux -y && yum update;
3、重新安装插件container-selinux，yum install container-selinux -y

**Comment by FeynmanZhou** [comment]
@Forest-L 好，我再试试

**Comment by FeynmanZhou** [comment]
GCP 的 ubuntu 18.04 LTS 最小化安装成功，centos 我再尝试上述方法
