### ISSUE TITLE
修改configmap配置不生效

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#1337]
/milestone 2.1.0
/kind bug
/area console
/cc @leoendless 
![image](https://user-images.githubusercontent.com/31230341/68097513-6285fe00-fef2-11e9-9eba-5b5051ebee76.png)

**Comment by leoendless** [comment]
这个问题是编辑 data 时直接提交了，但逻辑上应该是先完成data的编辑，ui上现在加上了限制

**Comment by runzexia** [comment]
verified in latest
/close
