### ISSUE TITLE
【建议】在权限管理这块建议增加对密钥类型显示明文的控制

### ISSUE THREAD

**Issue by knowwinter** [kubesphere/kubesphere#1342]
目前密钥类型的数据虽然默认是密文的，但是可以通过那个眼睛的按钮查看到明文，建议可以增加权限控制，让没权限的人在那个地方只能看密文，不能看明文，因为有些人员可能需要查看到底有哪些密钥可用，但是他们只要用就可以，不需要知道实际对应的值

**Comment by rayzhou2017** [comment]
要求再次输入密码，类似于mac装软件或者查看keychain一样，这样应该可以

**Comment by Carlosfengv** [comment]
这里有两种方式可以做
1.  仅允许密钥创建者查看修改密钥的内容；
2.  增加以个人维度的密钥类型，比如 Github 等秘钥信息，存在公开的ns下不太合适

**Comment by knowwinter** [comment]
嗯，我觉得可以增加公共和个人的维度，公共的密钥可以是创建者查看和有一定管理权限的人查看，比如项目管理员或企业空间管理员，或者索性公共密钥只有管理员可以创建，在管理上这些密钥可能需要于管理者之间共享，个人密钥只能创建者查看
