### ISSUE TITLE
cluster regular 中文文案

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#1344]
/kind bug
/area console
/assign @leoendless 
![image](https://user-images.githubusercontent.com/31230341/68104744-3d57b680-ff17-11e9-9acf-fa561a13f7a3.png)

**Comment by wansir** [comment]
fixed https://github.com/kubesphere/ks-installer/pull/374/files#diff-dcd9a051e9e10aa874e279e2ed57704aL58

/kind need-to-verify

**Comment by runzexia** [comment]
verified in 2019-11-04
/close
