### ISSUE TITLE
workspaces-manager 登陆后应该进入 ws 列表页

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#1346]
现在 workspaces-manager 登陆后进入工作台，会选中某个ws，这里是不是应该进入 ws 列表页？
/label question
/cc @Carlosfengv @wansir @leoendless 
/area console
/area iam

**Comment by Carlosfengv** [comment]
workspaces-manager 看到的应该企业空间功能的那个页面。他的工作台即企业空间列表页面。

**Comment by leoendless** [comment]
Fixed
