### ISSUE TITLE
应用商店访问路径后有 / 会导致页面404

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#1347]
例如使用`http://ks.xx/apps/`访问，查看应用详情，会导致网页404错误
进入详情 url 拼接的不太对
![image](https://user-images.githubusercontent.com/31230341/68107024-77788680-ff1e-11e9-8903-cb31738aaeba.png)
/milestone 2.1.0
/kind bug
/area console
/assign @whDongRui

**Comment by leoendless** [comment]
Fixed

**Comment by runzexia** [comment]
verified in latest
/close
