### ISSUE TITLE
应用部署打开选择框并使用滚轮，选择框会飘

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#1348]
/milestone 2.1.0
/kind bug
/area console
/assign @whDongRui
![image](https://user-images.githubusercontent.com/31230341/68107839-02f31700-ff21-11e9-8fe3-8b3dc7f9b61c.png)

**Comment by whDongRui** [comment]
这个应该是我们引用qui组件库中select组件有bug导致的样式上显示有问题。下面截图是创建企业空间弹层，如果把浏览器的高度调小，使用滚轮有时选择框也会飘

![image](https://user-images.githubusercontent.com/38676269/68186297-c554c380-ffde-11e9-81e3-6582b5a7d3da.png)

**Comment by runzexia** [comment]
这个问题优先级比较低，可以下个bug fix 版本修复。
我看 devops 里的选择框的处理是正确的，后面可以找 @mayuhope 参考下。

**Comment by whDongRui** [comment]
devopsv那边也会出现这种情况，不过一般那边的弹层内容比较少，没有出现滚动条。如果把浏览器的控制台打开，窗口高度变小了，也会有这种情况，如下截图所示。

![image](https://user-images.githubusercontent.com/38676269/68267609-f5a76b00-008d-11ea-833e-6b2bf01e6b41.png)

**Comment by calvinyv** [comment]
@leoendless  pls assign this issue to right person to fix, thx.

**Comment by leoendless** [comment]
UI已重构，当前问题不存在了。
