### ISSUE TITLE
100线程并发创建告警操作后，查看alerting-executor日志中监控获取不到数据

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#1349]
100个线程并发进行创建告警压测，一共创建5W条告警策略，且每条告警策略都会触发告警；：
压测接口：
/kapis/alerting.kubesphere.io/v1/nodes/alert

压测后，利用命令kubectl logs -n kubesphere-alerting-system alerting-executor-59c8768c5b-8tdwk alerting-adapter查看日志信息，很多监控读不到数据，导致alert无法正常工作
![alert](https://user-images.githubusercontent.com/36271543/68108693-7c8c0480-ff23-11e9-9e1c-cea92236c9f9.png)

**Comment by rayzhou2017** [comment]
这个是发送告警还是创建告警规则？

**Comment by Ma-Dan** [comment]
是50000条告警运行起来之后，周期性向监控系统读取监控指标。

**Comment by huanggze** [comment]
@liuyp2018 可以单独压测监控

**Comment by liuyp2018** [comment]
The problem no longer exists in later 2.1.0 performance test
/colse
