### ISSUE TITLE
Edit workspace roles?

### ISSUE THREAD

**Issue by shinebayar-g** [kubesphere/kubesphere#1352]
**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: Advanced 2.0.2

**Environment(环境的硬件配置)**
All in one node.

Is there a way to edit workspace roles? Currently project level roles works great, however in order to invite someone to this single project, first we must invite this member to project's parent workspace and workspace roles cannot be edited. So I have to either give this member **workspace-regular** role which can create it's own projects which defeats the purpose of having project based role, or have to give **workspace-viewer** which can see every project in that workspace, again defeats the very purpose of having project based permission.

So do we really need to have this "workspace" thing? I guess **project** on its own could be sufficient enough to handle multi tenancy management. Please enlighten me on why do you need such design and what I am missing here. Thank you.

**Comment by FeynmanZhou** [comment]
@shinebayar-g  KubeSphere provides 3 level of multi tenancy including cluster-> workspace -> project & devops project, each level has default role, **also it allows admin to customize roles and permissions as well.**  

For your question, for instance, workspace is used for different groups who has different namespaces and cicd pipelines in a same cluster (organization), this hierarchy can help admin to isolate and manage users with different roles, which you can get familiar from this [hands-on guide](https://kubesphere.io/docs/v2.0/en/quick-start/admin-quick-start/). The default hierarchy of KubeSphere you can see from the following graph.
![image](https://user-images.githubusercontent.com/40452856/68171205-ce796c80-ffad-11e9-8195-c99e7288e39e.png)

**Comment by FeynmanZhou** [comment]
@shinebayar-g  #1334   BTW, have you installed KubeSphere successfully on your machine?  In GCP ubuntu 18.04 LTS or your virtual box?

**Comment by rayzhou2017** [comment]
ws role customization will be provided in the next version (3.0) which is released around 3 months later.

**Comment by rayzhou2017** [comment]
BTW, workspace is useful. For example, we have several departments in a corporation sharing one k8s cluster. Each dept could be a tenant who wants a k8s environment with full functionalities ready for them. That means a tenant wants to create many projects/namespaces within the workspace. Actually the feature is required by some large enterprises.

**Comment by shinebayar-g** [comment]
@FeynmanZhou I see thank you, as I said earlier, workspace roles cannot be edited right now. So I've 2 roles to choose when inviting members into that workspace. Unfortunately both roles are weird and exposes underlying project information.

I've tried to install it on my local machine using virtualbox, unfortunately my home connection was too slow to finish downloads. Now I'm trying to install on DigitalOcean vps.

@rayzhou2017 Thanks for the information. Looking forward to that.

You guys made awesome project, now this user roles & permissions could be even better.

For example, what if I want to limit of project number per workspace?
What if I want to limit someone to only single project in workspace? and that user must not be able to create it's own project. Basically read only user to only single project.
Workspace and project level quota? etc more broader use cases can be difficult to achieve.
For this reason I cannot share my cluster to someone stranger as it exposes some information here and there.

**Comment by rayzhou2017** [comment]
KubeSphere 2.1 (will release in one week) has project level quota for k8s resource such deployment.... The workspace quota including the limit of project number as you said will provide in 3.0. 

"What if I want to limit someone to only single project in workspace? and that user must not be able to create it's own project. " I think this one is already supported. Invite the user to the workspace as viewer, then invite this user as editor or viewer or customized role in the specific project.

**Comment by shinebayar-g** [comment]
@rayzhou2017 **workspace-viewer** role currently sees all project inside workspace, not only one.

**Comment by rayzhou2017** [comment]
You may want share a project to a stranger without exposing workspace info. That case is not supported by workspace viewer since the user can view info. It need customized workspace role to limit the user only have access project menu, then utilize project role to limit the user permission in the project.

**Comment by shinebayar-g** [comment]
Yes exactly. I guess this is coming in v3.0 then

**Comment by rayzhou2017** [comment]
I see. That is the default behavior of workspace viewer. We need the custom role of workspace to achieve the goal you said.

**Comment by rayzhou2017** [comment]
It is supported in 3.0.0 now
