### ISSUE TITLE
组件健康检查 UI 阻塞

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1354]
11.5 日 早上8点20安装的 2.1-dev

![image](https://user-images.githubusercontent.com/22350668/68172631-32eafa80-ffb3-11e9-9164-6f4d98eb881b.png)

![image](https://user-images.githubusercontent.com/22350668/68172866-0daabc00-ffb4-11e9-8aa5-3ffa1188bfa5.png)

**Comment by zryfish** [comment]
重新拉下ks-apiserver的镜像

**Comment by huanggze** [comment]
verified
