### ISSUE TITLE
多节点环境安装gitlab 服务启动正常， gitlab.devops.kubesphere.local 不能访问

### ISSUE THREAD

**Issue by gongjx11** [kubesphere/kubesphere#1357]
IE 里面使用添加域名访问不能访问，以经添加解析，coredns也添加了。问一下是什么原因？

**Comment by gongjx11** [comment]
![image](https://user-images.githubusercontent.com/21954004/68183910-a6533300-ffd8-11e9-85c7-b6faad22bff5.png)

无法访问

**Comment by gongjx11** [comment]
以经解决了。

**Comment by oliver-csu** [comment]
举例说明：如果在yaml中配置的域名是baidu-int.com，那么gitlab的域名是gitlab.baidu-int.com，所以如果配置的是gitlab.baidu-int.com，那么域名应该是gitlab.gitlab.baidu-int.com

**Comment by oliver-csu** [comment]
有空close一下

**Comment by FeynmanZhou** [comment]
@oliver-csu @gongjx11  Close 了。已经解决的问题，欢迎在 [KubeSphere 论坛](https://kubesphere.com.cn/forum/) 写个详细的攻略，帮助其他用户避坑~
