### ISSUE TITLE
gitlab登录密码按照文档上 admin / P@88w0rd 不正确啊

### ISSUE THREAD

**Issue by gongjx11** [kubesphere/kubesphere#1360]
环境多环境安装部署，使用域名访问，提示密码一直错误
![image](https://user-images.githubusercontent.com/21954004/68187892-def80a00-ffe2-11e9-9ef5-4dd7cd3cdfd3.png)

**Comment by wansir** [comment]
可以检查一下kubesphere-system下pod是否都正常，kubesphere 可以正常登录吗？

**Comment by gongjx11** [comment]
![image](https://user-images.githubusercontent.com/21954004/68188069-50d05380-ffe3-11e9-8c74-02c2443a222c.png)
这里都是正常的

**Comment by gongjx11** [comment]
![image](https://user-images.githubusercontent.com/21954004/68188183-912fd180-ffe3-11e9-8567-6a4e69d04556.png)

**Comment by gongjx11** [comment]
可以登录了，因为我把Kubesphere 登录平台密码改了，我用改的密码去登gitlab可以了
