### ISSUE TITLE
日志关键字搜索不能键入空格

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1362]
不能输入空格

![image](https://user-images.githubusercontent.com/22350668/68189672-d0abed00-ffe6-11e9-8913-82646e6885d1.png)

**Comment by rayzhou2017** [comment]
不能输入空格是什么意思？是不能输入类似于 hello world这样的短语吗？

**Comment by justahole** [comment]
不能输入hello空格来匹配

**Comment by rayzhou2017** [comment]
为什么我觉得这是正确的做法？google对keyword会做很多处理，比如大小写，非语义词等。如果需要空格是不是应该当成词组对待？比如要求用户输入"elastic "

**Comment by huanggze** [comment]
是不能输入 hello world，输入到hello后面，不能再键入空格了

**Comment by rayzhou2017** [comment]
哦，那是bug

**Comment by huanggze** [comment]
verified
