### ISSUE TITLE
helm 部署的应用不支持流量治理吗？

### ISSUE THREAD

**Issue by Forget-C** [kubesphere/kubesphere#1365]
helm 部署的应用不支持流量治理吗？
我在自制的helm应用中打入了istio的组件，但是发现web上并没有流量治理的选项。
请问是只用使用 "通过服务构建应用" 部署的支持流量治理吗？  如果自制应用也支持的话，需要在helm模板中加入什么选项吗？

**Comment by tianbocheng** [comment]
我也发现了，有好的处理方法吗
