### ISSUE TITLE
Plans for 2.1.1 and 3.0.0

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1368]
We will release 2.1.0 in a few days. Next we will work on the first fixpack for 2.1.0 and the next major version 3.0.0. 

**Plan for 2.1.1**
1. Most of the work will be bugfix.
2. Refactor RBAC in order to support future versions regarding third-party plugins with custom access control.
3. Refactor installer. We will not provide full package installer (with K8s) as we do right now since we encountered so many problems from the community users. The reason is too many environments required to test but we didn't. We are short of hands to support these problems. So we might change it to deliver the package in docker format which we need to discuss later. Besides that, we continue to deliver the install method that allows users to install KubeSphere on existing K8s. That means users need to install K8s by themselves first. The install instruction is [here](https://github.com/kubesphere/ks-installer)

**Plan for 3.0.0**
In this major version, the big component will be multi-cluster management which brings huge design change for the current features such as monitoring, logging, app management etc. So most likely supporting multi-cluster management will be the only big one for 3.0.0. Besides that, we will add a few more functions such that
1. Porter UI support in BM environment which includes EIP management and LB management.
2. Metering support
3. Org for accounts support
4. DevOps project management, for example, integrate Jira etc.
5. Continue to improve App Store/template supported by OpenPitrix.

**Comment by DevYukine** [comment]
Hey,

i actuall just found out about this an it looks very promising.

But i do have something for the 3.0.0 Release, currently Kubesphere only supports Kubernetes up to version 1.15, since the latest is 1.17 and my cluster already uses that i sadly can't try this out. Also i saw in the readme that Helm 3 is planned for 3.0.0 but its also not written down in here :).

**Comment by rayzhou2017** [comment]
> Hey,
> 
> i actuall just found out about this an it looks very promising.
> 
> But i do have something for the 3.0.0 Release, currently Kubesphere only supports Kubernetes up to version 1.15, since the latest is 1.17 and my cluster already uses that i sadly can't try this out. Also i saw in the readme that Helm 3 is planned for 3.0.0 but its also not written down in here :).

KubeSphere supports K8s 1.16 in the upcoming 2.1.1 release which is under intensively testing now. It might support K8s 1.17 too but we are short of hands to test it thoroughly. This note of plans is just general ideas about next steps, which means we only put big things here. The roadmap is the details tasks to do for next releases. BTW, Helm 3 will be supported in KubeSphere 3.0.

**Comment by randaliang** [comment]
when will 3.0.0 Release?

**Comment by rayzhou2017** [comment]
> when will 3.0.0 Release?

the middle of May.

**Comment by yufan022** [comment]
does 2.1.1 support kubernetes 1.14.x？
this link https://kubesphere.io/docs/v2.1/zh-CN/release/release-v211 shows support v1.14.x。
this link https://kubesphere.io/docs/v2.1/zh-CN/installation/install-complete-ks-on-k8s shows 1.15.x ≤ K8s version ≤ 1.17.x。

**Comment by rayzhou2017** [comment]
> does 2.1.1 support kubernetes 1.14.x？
> this link https://kubesphere.io/docs/v2.1/zh-CN/release/release-v211 shows support v1.14.x。
> this link https://kubesphere.io/docs/v2.1/zh-CN/installation/install-complete-ks-on-k8s shows 1.15.x ≤ K8s version ≤ 1.17.x。

Actually it supports. Officially the roadmap of KubeSphere is to support the latest three versions of K8s for each release. That is why you see such document.

**Comment by yufan022** [comment]
> > does 2.1.1 support kubernetes 1.14.x？
> > this link https://kubesphere.io/docs/v2.1/zh-CN/release/release-v211 shows support v1.14.x。
> > this link https://kubesphere.io/docs/v2.1/zh-CN/installation/install-complete-ks-on-k8s shows 1.15.x ≤ K8s version ≤ 1.17.x。
> 
> Actually it supports. Officially the roadmap of KubeSphere is to support the latest three versions of K8s for each release. That is why you see such document.

Will you consider extending this version list?
When we use EKS or ACK We have to consider this. 
Because they highest version only 1.14.X.

**Comment by rayzhou2017** [comment]
> > > does 2.1.1 support kubernetes 1.14.x？
> > > this link https://kubesphere.io/docs/v2.1/zh-CN/release/release-v211 shows support v1.14.x。
> > > this link https://kubesphere.io/docs/v2.1/zh-CN/installation/install-complete-ks-on-k8s shows 1.15.x ≤ K8s version ≤ 1.17.x。
> > 
> > 
> > Actually it supports. Officially the roadmap of KubeSphere is to support the latest three versions of K8s for each release. That is why you see such document.
> 
> Will you consider extending this version list?
> When we use EKS or ACK We have to consider this.
> Because they highest version only 1.14.X.

We tested on EKS as you can from the screenshot below. It does support 1.14.
![WechatIMG37934](https://user-images.githubusercontent.com/28859385/76084683-64201980-5feb-11ea-94e0-0b85ebfeb58b.jpeg)

**Comment by yufan022** [comment]
> > > > does 2.1.1 support kubernetes 1.14.x？
> > > > this link https://kubesphere.io/docs/v2.1/zh-CN/release/release-v211 shows support v1.14.x。
> > > > this link https://kubesphere.io/docs/v2.1/zh-CN/installation/install-complete-ks-on-k8s shows 1.15.x ≤ K8s version ≤ 1.17.x。
> > > 
> > > 
> > > Actually it supports. Officially the roadmap of KubeSphere is to support the latest three versions of K8s for each release. That is why you see such document.
> > 
> > 
> > Will you consider extending this version list?
> > When we use EKS or ACK We have to consider this.
> > Because they highest version only 1.14.X.
> 
> We tested on EKS as you can from the screenshot below. It does support 1.14.
> ![WechatIMG37934](https://user-images.githubusercontent.com/28859385/76084683-64201980-5feb-11ea-94e0-0b85ebfeb58b.jpeg)

Okay! will you keep support 1.14 in the feature 3.0.0 version ？

**Comment by rayzhou2017** [comment]
> > > > > does 2.1.1 support kubernetes 1.14.x？
> > > > > this link https://kubesphere.io/docs/v2.1/zh-CN/release/release-v211 shows support v1.14.x。
> > > > > this link https://kubesphere.io/docs/v2.1/zh-CN/installation/install-complete-ks-on-k8s shows 1.15.x ≤ K8s version ≤ 1.17.x。
> > > > 
> > > > 
> > > > Actually it supports. Officially the roadmap of KubeSphere is to support the latest three versions of K8s for each release. That is why you see such document.
> > > 
> > > 
> > > Will you consider extending this version list?
> > > When we use EKS or ACK We have to consider this.
> > > Because they highest version only 1.14.X.
> > 
> > 
> > We tested on EKS as you can from the screenshot below. It does support 1.14.
> 
> Okay! will you keep support 1.14 in the feature 3.0.0 version ？

If most of cloud provider's k8s services upgrade to new version (> 1.14) about a month before we release 3.0, we may not support the older version. Otherwise, we will support it.

**Comment by wartih** [comment]
3.0.0能否按预计时间五月中旬发布？十分期待！

**Comment by rayzhou2017** [comment]
> 3.0.0能否按预计时间五月中旬发布？十分期待！

There are 2-4 weeks delay because of the COVID-19.

**Comment by calvinyv** [comment]
We're close to the GA of 3.0.0, here are the main features and enhancements list for this major release:

- multiple clusters management
- open UI for 3rd party monitoring metrics
- network policy management
- compatible with Prometheus Alert Mgr
- Event management
- Audit management
- compatible with AWS EKS

**Comment by wartih** [comment]
Is there any improvments in auth management?
https://kubesphere.com.cn/forum/d/847-2-1-1/5

**Comment by calvinyv** [comment]
> Is there any improvments in auth management?
> https://kubesphere.com.cn/forum/d/847-2-1-1/5

sure, we do, which is upgrade and enhancement from backend perspective but not function perspective, including: 
 - migrate and support OPA
 - upgrade to CRD constructor
For the link you posted, we already fix related problems in 3.0.0.
