### ISSUE TITLE
istioctl doesn't upgrade after upgrading ks from 2.0.2 to 2.1.0

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1369]
istioctl doesn't upgrade after upgrading ks from 2.0.2 to 2.1.0

**Comment by pixiake** [comment]
https://github.com/kubesphere/kubespray/commit/8fec56dca3f694a106c676cac573d2a84d97d048

**Comment by calvinyv** [comment]
@pixiake how about this issue now?
