### ISSUE TITLE
latest installer exits during the final phase with no information

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1370]
![image](https://user-images.githubusercontent.com/22350668/68267579-dc9eba00-008d-11ea-9a80-472ebbc2fbb8.png)

**Comment by huanggze** [comment]
logs from ks-installer:

![image](https://user-images.githubusercontent.com/22350668/68267847-c5ac9780-008e-11ea-8cb2-303250f9d18a.png)

**Comment by pixiake** [comment]
检查下存储能不能用    这个应该是minio存储挂不上盘  导致超时。
nfs的存储配置有问题，检查下吧

**Comment by huanggze** [comment]
建议文档这里把网段改成，192.168.0.0/16，顺手 copy 容易忽视出错，仅作为新手 tutorial 可以把范围调大

![image](https://user-images.githubusercontent.com/22350668/68276830-d964f780-00a8-11ea-83a3-442f10d84762.png)
