### ISSUE TITLE
app info screenshot needs size tip

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1371]
* [x] 需要提示上传的截图大小要求
<img width="1112" alt="Screen Shot 2019-11-06 at 12 12 58 PM" src="https://user-images.githubusercontent.com/28859385/68267879-ec6ace00-008e-11ea-9b9c-5f43cf5a2494.png">

**Comment by Carlosfengv** [comment]
设计稿在  zpl://screen?pid=5cbe7fbc2f55d8b73f56811b&sid=5d5a72376754d79b309a5acd

**Comment by whDongRui** [comment]
这个刚按设计图给加上，并支持单个截图的删除。

![image](https://user-images.githubusercontent.com/38676269/68280529-af173800-00b0-11ea-8134-90aa6a79451a.png)

**Comment by rayzhou2017** [comment]
verified
