### ISSUE TITLE
修改app info 清空信息

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1372]
* [x] 我填入了app abstract，然后上传icon，screenshots，发现abstract被清空了，另外fix这个bug的时候需要测试一下其它信息是不是也有这个问题
<img width="1226" alt="Screen Shot 2019-11-06 at 12 14 58 PM" src="https://user-images.githubusercontent.com/28859385/68267945-305dd300-008f-11ea-8ede-54fbd2bc5114.png">

**Comment by whDongRui** [comment]
上传icon应该不会清空应用的其它信息，删除或上传screenshots会清空，这个问题刚修复了。

**Comment by rayzhou2017** [comment]
verified
