### ISSUE TITLE
b2i 英文翻译

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1373]
* [ ] 这个是regression问题吧，没有翻译
<img width="1039" alt="Screen Shot 2019-11-06 at 12 22 23 PM" src="https://user-images.githubusercontent.com/28859385/68268183-27213600-0090-11ea-87c0-9a7438f9b06d.png">

**Comment by soulseen** [comment]
这个是什么时候的版本。今天早上的版本没有复现。

**Comment by rayzhou2017** [comment]
verified
