### ISSUE TITLE
key and value of app meta data is shown after upgrading from 2.0.2 to 2.1.0

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1375]
**Describe the bug(描述下问题)**
key and value of app meta data is shown after upgrading from 2.0.2 to 2.1.0

For UI issues please also add a screenshot that shows the issue.
<img width="1147" alt="Jietu20191106-135724" src="https://user-images.githubusercontent.com/28883416/68272052-83d71d80-009d-11ea-861a-19c0675733a1.png">
<img width="946" alt="Jietu20191106-135742" src="https://user-images.githubusercontent.com/28883416/68272056-889bd180-009d-11ea-9f91-761509a50b2d.png">

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0 dev 20191105
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

**To Reproduce(复现步骤)**
1. deploy sample app on 2.0.2: https://yunify.anybox.qingcloud.com/s/BRgdySosqf8jKcENmvTB0O1Lxd4dPpI6
2. Upgrade to 2.1.0
3. See above meta key/value on app list page 

**Expected behavior(预期行为)**

**Comment by leoendless** [comment]
建议写脚本进行字段替换，应该是要修改 mysql 里的记录

**Comment by calvinyv** [comment]
@rayzhou2017 @zheng1 is it an acceptable solution?

**Comment by rayzhou2017** [comment]
I am not sure. It is OK to fix it in whatever way right now.

**Comment by zheng1** [comment]
@pengcong06  need a script that can clear all clusters `description` column when upgrading from 2.0.2 to 2.1.0

**Comment by benjaminhuo** [comment]
This is an app management issue, should be assigned to @zheng1 team?
