### ISSUE TITLE
ldap error when opening a devops project after upgrading to 2.1.0

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1376]
**Describe the bug(描述下问题)**
ldap error when opening a devops project after upgrading to 2.1.0

For UI issues please also add a screenshot that shows the issue.
<img width="1675" alt="Jietu20191106-140543" src="https://user-images.githubusercontent.com/28883416/68272462-c2210c80-009e-11ea-8315-7d9cf463ee9c.png">

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0 dev 20191105
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**
1. Upgrade to 2.1.0
2. create a new devops project as admin
3. open this devops project and see this ldap error

**Expected behavior(预期行为)**

**Comment by wansir** [comment]
fixed 
/kind need-to-verify
