### ISSUE TITLE
gitlab 无法删除项目，报错

### ISSUE THREAD

**Issue by gongjx11** [kubesphere/kubesphere#1377]
![image](https://user-images.githubusercontent.com/21954004/68274020-f7c7f480-00a2-11ea-9b7d-3e26abdf4ecc.png)

这是日志错误：
![image](https://user-images.githubusercontent.com/21954004/68274049-09110100-00a3-11ea-9972-76a198867a25.png)

这里显示没有权限但是我以经删除提了，日志这里会显示这个，而且界面也会显示被删除的项目

**Comment by gongjx11** [comment]
gitlab 使用管理员创建的project 项目，用管理员无法删除，请问一下是什么原因

**Comment by hlwanghl** [comment]
提供一下环境信息，操作系统和 kubesphere 版本？

**Comment by gongjx11** [comment]
centos7.4 系统，多节点环境，2.0.2 版本，存储有的是ceph  现在任何项目都没有办法删除。
![image](https://user-images.githubusercontent.com/21954004/68282244-4c27a000-00b4-11ea-96cd-ba755ffb8507.png)

只要删除就会报下面日志错误：
![image](https://user-images.githubusercontent.com/21954004/68282301-65c8e780-00b4-11ea-9f95-e27385668e33.png)

**Comment by hlwanghl** [comment]
这里报的 `Permission Denied` 一般都是存储层面的，可能跟 Ceph 有关。

从 GitLab 官方 Issue 里只找到一个类似的：https://gitlab.com/gitlab-org/charts/gitlab/issues/1386，里面建议进到 gitaly 的 pod 里检查一下相关目录的权限和用户的权限是不是有问题。

如果解决不了的话，可能需要在上面开个 Issue ：https://gitlab.com/gitlab-org/charts/gitlab/issues

**Comment by gongjx11** [comment]
我先看一下你给的文档，谢谢

**Comment by hlwanghl** [comment]
没事，他贴的日志是 sidekiq 的，也可以一起排查一下。

**Comment by gongjx11** [comment]
我测了几次 普通账号通过注册进去，然后使用管理员付权，然后用注册账号去添加项目，可以删除，如果是管理员账号登录进去，创建的项目，删除不了项目，就会报上面哪个错误

**Comment by gongjx11** [comment]
我问一下 多节点gitlab 安装是不是和搭单节点安装一样的，我是集群的环境在安装时，有一步是需要青云的存储  我跳过了这一步。问一下这个和我报的这个错有没有原因

**Comment by hlwanghl** [comment]
多节点和单节点一样，都会用默认的 storage class，只要配好默认的就可以。

如果有问题，这些 pod 分配不到 PVC ，压根就起不来。

**Comment by gongjx11** [comment]
我这里的GITLAB 分配到了PVC,因为安装时会选择存储，我用的是CEPH，所以在安装时选择不到青云的存储，被我注释掉了，另外我想问一下，如果不用集群的GITLAB。而单独部署一台GITLAB对集群有没有影响。

**Comment by hlwanghl** [comment]
没影响，可以用单独的，跑 DevOps 流水线的时候，网络相互是通的就可以。

**Comment by gongjx11** [comment]
好的 谢谢
