### ISSUE TITLE
监控自定义时间范围不生效

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#1378]
/kind bug
/area console
/assign @justahole 
/milestone 2.1.0
自定义时间范围之后，通过编辑修改自定义时间范围，无法生效
![image](https://user-images.githubusercontent.com/31230341/68274749-e5e75100-00a4-11ea-8b1c-edfce62f95fe.png)

**Comment by justahole** [comment]
无法生效指的是？

**Comment by runzexia** [comment]
@justahole 
编辑时间的，修改后还是编辑之前的时间

**Comment by justahole** [comment]
哦，明白，我看下。

**Comment by justahole** [comment]
已经合入，明天可以验证
