### ISSUE TITLE
alert msg 图不正确

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1381]
* [ ] 正确告警，但msg显示的图数值应该不对
<img width="916" alt="Screen Shot 2019-11-06 at 4 53 39 PM" src="https://user-images.githubusercontent.com/28859385/68283221-1f748800-00b6-11ea-9371-fc376abb5fd5.png">
<img width="981" alt="Screen Shot 2019-11-06 at 4 53 52 PM" src="https://user-images.githubusercontent.com/28859385/68283233-24393c00-00b6-11ea-9aa0-7d719a0f7520.png">

**Comment by leoendless** [comment]
监控数值这块的正确性 @Ma-Dan @huanggze 帮看下吧

**Comment by rayzhou2017** [comment]
现在好像又好了

**Comment by calvinyv** [comment]
@rayzhou2017 pls verify it in 2.1.1
