### ISSUE TITLE
web端的kubectl链接报错

### ISSUE THREAD

**Issue by jinmin527** [kubesphere/kubesphere#1382]
web端链接kubectl 报如下错：

Connecting...Could not connect to the container. Do you have sufficient privileges?

**Comment by wansir** [comment]
需要你的代理服务器支持 websocket，nginx 可以参看下面的配置

```
location /wsapp/ {
    proxy_pass http://wsbackend;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
}
```

https://www.nginx.com/blog/websocket-nginx/

**Comment by izerui** [comment]
如果用的是 nginx ingress controller的话，可以在自己的ingress中增加注解： nginx.org/websocket-services: "ks-console"
就可以了
