### ISSUE TITLE
命令行docker不能登录harbor

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1385]
测试版本：v2.1-dev

![image](https://user-images.githubusercontent.com/57089340/68287176-41bdd400-00bd-11ea-9084-bb85bac0872e.png)
/assign @hlwanghl

**Comment by hlwanghl** [comment]
Caused by a bug of the Harbor chart 1.1.3. Will upgrade to 1.2.1.

**Comment by hlwanghl** [comment]
A bug in Harbor Chart 1.1.3. Will upgrade to 1.2.1.

**Comment by hlwanghl** [comment]
https://github.com/kubesphere/ks-installer/pull/402

**Comment by hlwanghl** [comment]
The fix above was merged into latest installer and it works on my CentOS 7.5 all in one. Give a try.

**Comment by gongjx11** [comment]
以经可以了 谢谢！

**Comment by ellaye** [comment]
verify ok
