### ISSUE TITLE
Alert policy support for volume usage

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1386]
**Describe the bug(描述下问题)**
Alert policy support for volume usage

**Comment by benjaminhuo** [comment]
This can be solved by using  Prometheus alert rule + Alertmanager, 3 default volume alertrule exists already。

**Comment by benjaminhuo** [comment]
We've already add volume usage alerts in prometheus alert rules in 3.0 https://github.com/kubesphere/kube-prometheus/blob/ks-v3.0/manifests/prometheus-rules.yaml#L1281

**Comment by calvinyv** [comment]
closed
