### ISSUE TITLE
Alerting Localization

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1387]
* [ ] I am in English, but the alert is Chinese.
<img width="616" alt="Screen Shot 2019-11-06 at 5 51 59 PM" src="https://user-images.githubusercontent.com/28859385/68287719-256e6700-00be-11ea-840d-9a0b4ee24c51.png">

**Comment by huojiao2006** [comment]
会在调用端也是告警这段实现 @Ma-Dan

**Comment by rayzhou2017** [comment]
Do we localize this alerting?

**Comment by Ma-Dan** [comment]
Alerting email templates contains Chinese and English, and language is specified by ks console language on alert creation  language, and api for modifying language is also provided.
https://github.com/kubesphere/alert/commit/a733b20bb37a072fe8cedc6eff6c8ea0df2ac378
Current version only specify alert language once on creation, that means if we switch console language and create alerts on different language selection(or with different console logins), we will have alerts in different languages.

**Comment by rayzhou2017** [comment]
We are going to support Traditional Chinese, Simple Chinese, English, Spanish, Turkish in v3.0.0 console. How about alerting?

**Comment by Ma-Dan** [comment]
Alerting could add language support by updating [alert adaptor email template](https://github.com/kubesphere/alert-adapter/blob/master/pkg/constants/email.go) with more language templates. KS console just create alert with its language selected as parameter(eg. en zh ...), alert will be created with the language parameter and notification email will be formated with that language.

**Comment by Sherlock113** [comment]
I see....so other language providers need to provide localization for two templates in this file: EmailKubeSphereNotifyResumeTemplate and EmailKubeSphereNotifyActiveTemplate, with the language code following the name (e.g. for Spanish it can be "EmailKubeSphereNotifyResumeTemplateSp =" and "EmailKubeSphereNotifyActiveTemplateSp =").

Honestly, this is not a localization-friendly way. We cannot require them to find each loc keys among all the code, which is time-consuming (there are 900 lines or so for each template....). And they need to make sure they do not mess up with the code when they do the translation. I am wondering if there is a way to extract all the keys that need to be localized and put them in the locales folder? In this way, our partners can do the translation directly.

**Comment by rayzhou2017** [comment]
ok, before finding a nice way to do that, I think it is ok for now to provide English and Chinese.
