### ISSUE TITLE
app store部署的app自带的pvc没有创建者

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1388]
* [ ] 如下图，应该是创建此app的当前登录用户
<img width="777" alt="Screen Shot 2019-11-06 at 6 03 37 PM" src="https://user-images.githubusercontent.com/28859385/68288703-df1a0780-00bf-11ea-814b-3e54d3a4510b.png">

**Comment by zheng1** [comment]
After version 3.1 use --post-renderer to add creator annotations to the necessary resources
