### ISSUE TITLE
pvc expand数值问题

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1389]
* [ ] pvc原来大小是100G，准备扩容，打开默认是8G
<img width="974" alt="Screen Shot 2019-11-06 at 6 08 58 PM" src="https://user-images.githubusercontent.com/28859385/68289338-e4c41d00-00c0-11ea-8204-940c408cf9ba.png">

**Comment by wnxn** [comment]
前端应该优先从 pvc status 里读取存储卷大小。
```
# kubectl get pvc -n demo-project test -oyaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubesphere.io/creator: xszhou
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: csi-qingcloud
  creationTimestamp: "2019-11-06T04:28:52Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: test
  name: test
  namespace: demo-project
  resourceVersion: "26213"
  selfLink: /api/v1/namespaces/demo-project/persistentvolumeclaims/test
  uid: 3781d073-b500-48f8-bb2f-a381b9776257
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-qingcloud
  volumeMode: Filesystem
  volumeName: pvc-3781d073-b500-48f8-bb2f-a381b9776257
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  phase: Bound
```

**Comment by justahole** [comment]
@wnxn 当前并不能拿status中的参数作为扩容的原始值，否者会报错。
PersistentVolumeClaim "mysql-volume-mysql-jvitof-0" is invalid: spec.resources.requests.storage: Forbidden: field can not be less than previous value

**Comment by rayzhou2017** [comment]
当前pvc的yaml文件里大小也是8G，是错的

**Comment by wnxn** [comment]
spec 里大小是存储卷请求值，status 里大小是存储卷实际值。实际值是大于等于请求值的
@justahole 你试验的时候扩容前存储卷 实际值和请求值是多少，扩容存储卷请求的容量多少？

**Comment by justahole** [comment]
这个报错的情况是 request 30， status 20。我发了一个新的扩容请求。request 为25。
PersistentVolumeClaim "mysql-volume-mysql-jvitof-0" is invalid: spec.resources.requests.storage: Forbidden: field can not be less than previous value
所以并不能拿status 值作为UI的最小扩容值。

**Comment by wnxn** [comment]
request 30， status 20 这个状态的存储卷已经在扩容状态了，再触发一次扩容需要 容量大于 30。
这里前端先用 spec 里的容量吧。

**Comment by justahole** [comment]
现在就是这个逻辑。而这个issue出现8G。也就是说 spec 的值也并不一定可靠。

**Comment by wnxn** [comment]
扩容用 spec 值，显示存储卷容量优先用 status 值，比较合适。

**Comment by rayzhou2017** [comment]
verified
