### ISSUE TITLE
编辑有状态副本集对应的服务时，不显示所指定的具体工作负载

### ISSUE THREAD

**Issue by junotx** [kubesphere/kubesphere#1390]
以下是编辑有状态副本集对应的服务时的截图，只显示工作负载个数，不显示具体负载类型和名称
![image](https://user-images.githubusercontent.com/49136171/68290655-44bbc300-00c3-11ea-9edc-3705a07cf6ea.png)
/area console
/kind bug

**Comment by leoendless** [comment]
Fixed

**Comment by junotx** [comment]
verified
