### ISSUE TITLE
job rerun websocket

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1391]
* [x] rerun job的时候这个running没有动画效果
<img width="1009" alt="Screen Shot 2019-11-06 at 6 32 16 PM" src="https://user-images.githubusercontent.com/28859385/68290969-d75c6200-00c3-11ea-84da-b925a87d8fe9.png">

**Comment by leoendless** [comment]
@wansir 目前 job rerun 的机制应该不支持吧

**Comment by wansir** [comment]
watch  job  应该可以看到变化，有删除和创建的过程

**Comment by leoendless** [comment]
@rayzhou2017 是指 job 的 running 同 workload 的warning 一样闪烁吗

**Comment by rayzhou2017** [comment]
是的，这个running一直没动，然后最后转成complete，这个是预期的？

**Comment by leoendless** [comment]
现在 job 的 running 也是闪烁的

**Comment by rayzhou2017** [comment]
verified
