### ISSUE TITLE
QingCloud-CSI currently only supports access mode RWO, but the console defaults to enable all alternatives

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1394]
![image](https://user-images.githubusercontent.com/22350668/68352932-f221eb80-0142-11ea-856d-dfc5fa4cb7a8.png)

**Comment by wnxn** [comment]
qingcloud-csi, qingstor-csi, local: RWO
ceph rbd: RWO ROX
nfs, glusterfs: RWO ROX RWM

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

**Comment by huanggze** [comment]
verified
