### ISSUE TITLE
qincloud lb设置错误

### ISSUE THREAD

**Issue by minghaoye** [kubesphere/kubesphere#1395]
1.第一次安装，按照文档设置 auto，qingcloud已自动创建 eip, 但是ks返回为空
2.重新安装，设置为固定eIP, ks lb 返回为空
3.删除 service.beta.kubernetes.io/qingcloud-load-balancer-eip-ids这条注解，新增 service.beta.kubernetes.io/qingcloud-load-balancer-eip-source，并没有删除，被合并

<img width="1000" alt="Screen Shot 2019-11-07 at 10 05 03 AM" src="https://user-images.githubusercontent.com/22934997/68354099-6611c300-0146-11ea-8200-6fe868fa9c83.png">

环境：http://139.198.17.39:30770/projects/test/advanced

**Comment by magicsong** [comment]
lb 配置有两个问题：
1. 是ks返回有延迟
2. iaas 返回[QingCloud Error: Code (1400), Message (PermissionDenied, public IP [eip-265r2sjl] is not available, can not be associated to loadbalancer)]，可能是eip无法使用。另外，手动指定eip，应该删除配置项service.beta.kubernetes.io/qingcloud-load-balancer-eip-source： auto。如果不删除，插件会自动获取一个新的。从后台看，后台无法获取是因为eip 额度不够了。

第三个错误应该是UI出错了，我也稳定复现了。
@leoendless

**Comment by leoendless** [comment]
后端接口没有正确处理请求传参

**Comment by minghaoye** [comment]
review ok

/close
