### ISSUE TITLE
告警View不好用

### ISSUE THREAD

**Issue by magicsong** [kubesphere/kubesphere#1397]
1. 每个告警通知是按照时间正序，但是用户习惯去解决最新的告警，查看最新的告警的状态
2. 告警通知条目没有跳转，如下图，我要看最新的告警，非常难受。
![image](https://user-images.githubusercontent.com/4010679/68355990-fbfc1c80-014b-11ea-9e97-f0e578a173f5.png)
/area console

**Comment by rayzhou2017** [comment]
这个是需要设计一下
