### ISSUE TITLE
重建workload之后，告警似乎不工作了。

### ISSUE THREAD

**Issue by magicsong** [kubesphere/kubesphere#1398]
参考下面这个环境，这个target已经恢复了。但是告警没有显示已恢复。
http://139.198.188.19:30880/projects/test/alert-policy/gaojing---2/monitoring-target

/assign @Ma-Dan

**Comment by Ma-Dan** [comment]
告警因为无法预知会有多少target(通过label selector支持了动态target)，所以删除后，该target的状态从监控系统未返回的那一个周期，该target的状态就被删除了，不会再有alert或者是resume信息，再次创建后，会当作新加入的target重新建立状态。
比如监控系统中节点的状态，可以在不知道有多少node情况下，一个selector就指定了，一开始读取node信息为1个，那么就建立了这个node的状态，开始alert/resume过程，后面node会动态加入和删除，删除的信息就会清除掉。
