### ISSUE TITLE
容器组无异常pod时，创建告警策略为 容器组异常率<100%，不会触发告警

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#1409]
当平台容器组中无异常pod时，创建告警策略为 容器组异常率<100%

预期：
应可以触发告警

实际结果：
查看该条告警一直未触发告警动作
另：当平台中存在有异常pod时，创建相同的告警策略，可以成功触发告警。

**Comment by huanggze** [comment]
异常 pod 的算法可以改进下。让无异常 pod 时结果返回 0，而不是空。这个问题可以先标记为 medium，不会影响正常的异常pod告警

**Comment by benjaminhuo** [comment]
/assign @junotx 
@junotx pls take a look at this issue

**Comment by huanggze** [comment]
I don't think this is a big issue. Basically, no body will set the threshold to <100%.

**Comment by benjaminhuo** [comment]
agree , usually it should be > xxx% .
We can fix this if there is no other work items to do
