### ISSUE TITLE
403 errors after namespace admin removes himself from the namespace

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1410]
`devops-wk-regular` is the namespace admin

![image](https://user-images.githubusercontent.com/22350668/68372936-c02d7b00-017c-11ea-9eaf-fc6d5a36847b.png)

![image](https://user-images.githubusercontent.com/22350668/68372953-c885b600-017c-11ea-9cc1-4176d9607977.png)

**Comment by leoendless** [comment]
Fixed, now disabled member modify self's role

**Comment by huanggze** [comment]
verified
