### ISSUE TITLE
通过状态搜索主机不生效

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1414]
1、进入平台管理-基础设施-主机；
2、3台主机状态均为运行中，通过状态进行搜索，搜索条件为运行中，结果没有任何返回结果
![image](https://user-images.githubusercontent.com/7677050/68383133-06d8a080-0190-11ea-9590-4e55033ad5f0.png)
![image](https://user-images.githubusercontent.com/7677050/68383138-093afa80-0190-11ea-931d-67a6efdf73fe.png)

**Comment by mayuhope** [comment]
补充:通过系统版本搜索也不生效

**Comment by leoendless** [comment]
Fixed

**Comment by mayuhope** [comment]
经验证已修复
