### ISSUE TITLE
自定义角色为日志查看和主机编辑时，权限错误

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1416]
1、新建一个平台自定义角色test，权限为日志查看、主机编辑，使用该角色绑定一个账户user1；
![image](https://user-images.githubusercontent.com/7677050/68385435-b152c280-0194-11ea-938b-108757220821.png)

2、使用账户user1登录，发现权限错误：

![image](https://user-images.githubusercontent.com/7677050/68385574-0db5e200-0195-11ea-81c3-22c5e1344505.png)

**Comment by wansir** [comment]
前端根据规则作出限制就可以了

**Comment by leoendless** [comment]
Fixed

**Comment by mayuhope** [comment]
经验证已修复
