### ISSUE TITLE
regression: pod terminal打不开

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1421]
* [x] 试过多个权限，都打不开
<img width="1139" alt="Screen Shot 2019-11-08 at 10 15 08 AM" src="https://user-images.githubusercontent.com/28859385/68444073-bd7c6580-0210-11ea-95aa-313bee0172ff.png">

**Comment by wansir** [comment]
kubectl -n kubesphere-system set image deployment/ks-console ks-console=kubespheredev/ks-console:latest

需要更新一下ks-console 的镜像

**Comment by rayzhou2017** [comment]
verified
