### ISSUE TITLE
自定义角色登录后查看监控返回 403

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#1422]
昨天装的环境，自定义的 role，该角色对监控仅开放查看权限，该角色登录后提示 403

![image](https://user-images.githubusercontent.com/40452856/68444525-0ed92480-0212-11ea-89b8-619be9045cce.png)

![image](https://user-images.githubusercontent.com/40452856/68444492-f36e1980-0211-11ea-9ef3-e9641334c127.png)

**Comment by wansir** [comment]
这里是因为新增了API
