### ISSUE TITLE
如何查询工作负载的历史日志

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#1424]
/help
/cc @Carlosfengv @huanggze @justahole 
在实际使用过程当中，我们进行排错的时候，需要对工作负载的历史日志进行查询（例如pod挂了，我在界面上看不到，想要查看历史日志）。
但是通过日志查询页面，不容易通过上下文找到我出错的信息。
![image](https://user-images.githubusercontent.com/31230341/68445857-0edb2380-0216-11ea-9782-80b035ff806f.png)
因此我点击某个日志详情进入日志查询页面，发现查询结果只有几条，也不太容易找到我出错时候的日志。
![image](https://user-images.githubusercontent.com/31230341/68445916-3b8f3b00-0216-11ea-83ce-3db7cd18bf37.png)

**Comment by huanggze** [comment]
定位日志后，点选查看上下文应该是有一处小bug 挪到3.0， @justahole 看看影不影响历史日志查询

**Comment by justahole** [comment]
@huanggze  只能根据定位的日志，通过可能的时间来寻找日志。
