### ISSUE TITLE
优化流水线邮件通知邮件服务器配置，支持在kubesphere界面中统一配置

### ISSUE THREAD

**Issue by soulseen** [kubesphere/kubesphere#1426]
1. v2.1.0版本中流水线邮件通知功能，配置邮件服务器需要Jenkins中单独配置。  
2. 在v2.1.1中进行优化，在kubesphere界面中统一配置邮件服务器即可。  

/kind improved
/assign @runzexia @soulseen

**Comment by Carlosfengv** [comment]
#1411
