### ISSUE TITLE
kubesphere 平台添加 nfs 存储

### ISSUE THREAD

**Issue by Carriezhangyan** [kubesphere/kubesphere#1427]
问题:
1. kubesphere 平台想要增加一个存储，，存储类型是nfs ，，请问应该怎样设置？ 我选择了一个自定义设置，，后面的参数不知道应该怎样设置了。。有没有文档说明应该怎样新加一个nfs存储呢？

![image](https://user-images.githubusercontent.com/46554638/68457992-a8b5c700-023c-11ea-9333-499acf52467d.png)

![image](https://user-images.githubusercontent.com/46554638/68457879-5bd1f080-023c-11ea-9dd0-87bd3e618154.png)

**Comment by wnxn** [comment]
选择自定义，填写 parameters 里的 key 和 value，就可以新增存储类型了。
NFS 动态分配需要安装动态分配器，可以参考：https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner

**Comment by Carriezhangyan** [comment]
parameters 里的 key 和 value，填写什么？ 是新增nfs的ip和指定的存储路径吗？

**Comment by Carriezhangyan** [comment]
我想要安装多个nfs服务器，以便于一台nfs服务器挂掉后，另一台及时启动，，不影响业务。
一定要安装nfs动态分配器吗？ 安装后会冲掉我以前的nfs服务器上的存储数据吗？ 还有，这个nfs动态分配器是需要安装到master节点上吗？还是安装到nfs服务器上？安装后会对我原来的存储数据有影响吗？会冲掉我以前存储好的数据吗？如果删掉其中一台存储了数据的nfs服务器，以前的存储数据会丢失吗？

**Comment by wnxn** [comment]
1个nfs动态分配器对接1个 nfs 服务端。
nfs动态分配器通过 k8s 工作负载安装在 k8s 里，安装后对nfs 服务端数据没有影响。
使用nfs动态分配器当创建 pvc 时自动创建nfs pv，并且在 nfs 指定目录下创建对应pv的子目录。

**Comment by Carriezhangyan** [comment]
kubesphere支持添加多个nfs服务端吗？

**Comment by wnxn** [comment]
支持，你弄多个 nfs 动态分配器就可以了，1个nfs动态分配器对应 1个存储类型对应1个nfs服务端和路径二元组。

**Comment by Carriezhangyan** [comment]
可是我参照 https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner  中执行命令，，一直报错。。
错误如下：
```
[root@master0 nfs]# helm install --set nfs.server=192.168.37.114 --set nfs.path=/data/kubevolume/ stable/nfs-client-provisioner
Error: release lazy-stingray failed: storageclasses.storage.k8s.io "nfs-client" already exists
```

应该不需要先停掉原来的nfs服务器吧

**Comment by wnxn** [comment]
看起来是存储类型名冲突，创建动态分配器时指定 name 参数，生成不同的存储类型名就可以了。NFS 服务端不需要停，支持 k8s 对接多个 nfs 服务端。
https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner#installing-the-chart
