### ISSUE TITLE
Devops任务界面，未解析Jenkins任务状态: UNSTABLE

### ISSUE THREAD

**Issue by geniussheep** [kubesphere/kubesphere#1428]
Bug描述：
发起devops任务后 以确定任务成功完成，但是在devops上任务状态依然是 [未运行] 状态
![image](https://user-images.githubusercontent.com/7587017/68460130-04368380-0242-11ea-8485-262f4703ddc7.png)
![image](https://user-images.githubusercontent.com/7587017/68460152-13b5cc80-0242-11ea-8559-7d33fca045d4.png)
![image](https://user-images.githubusercontent.com/7587017/68460174-20d2bb80-0242-11ea-9d0d-ad6b4527bd93.png)

**Comment by runzexia** [comment]
fixed
