### ISSUE TITLE
Source-to-image 构建镜像加载不了jar，麻烦帮忙看一下

### ISSUE THREAD

**Issue by gongjx11** [kubesphere/kubesphere#1430]
带码包，用的是官网推建的 https://github.com/kubesphere/devops-java-sample  这个demo.
因为我的GITHUB git不下来，所以把它下载下来，推到了gitlab本地仓库。

下面是我的配置：
![image](https://user-images.githubusercontent.com/21954004/68460931-00a3fc00-0244-11ea-8d2d-46c5824d3dbc.png)
![image](https://user-images.githubusercontent.com/21954004/68460976-1e716100-0244-11ea-85f8-e469eee7088f.png)

卷没有添加
![image](https://user-images.githubusercontent.com/21954004/68461028-406ae380-0244-11ea-9399-be96094969bc.png)

构建过程：
![image](https://user-images.githubusercontent.com/21954004/68461075-5c6e8500-0244-11ea-88ac-5e9ad0590b10.png)
构建日志：没有加载到Java
![image](https://user-images.githubusercontent.com/21954004/68461145-82942500-0244-11ea-8479-83a9a4e9f7fd.png)

容器启动报错：
![image](https://user-images.githubusercontent.com/21954004/68461288-d141bf00-0244-11ea-9e7a-9b4512de8403.png)

容器日志：
![image](https://user-images.githubusercontent.com/21954004/68461329-e9b1d980-0244-11ea-98bc-99ddceb733b3.png)

**Comment by runzexia** [comment]
看下代码仓库的截图

**Comment by gongjx11** [comment]
![image](https://user-images.githubusercontent.com/21954004/68461647-a86df980-0245-11ea-85e8-0e41482e1498.png)
这个就是代码仓库

**Comment by gongjx11** [comment]
我看一下

**Comment by gongjx11** [comment]
现在可以了，谢谢了
