### ISSUE TITLE
笔记本上创建用户时密码被挡住

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1432]
复现步骤：
1、使用admin登录kubesphere
2、平台管理-账户管理-创建用户
3、输入用户名、邮箱、选择角色，拉动滚动条到最下端，输入密码

期望结果：密码不被挡住
实际结果：密码被挡住
![image](https://user-images.githubusercontent.com/57089340/68923630-b679c800-07b9-11ea-9e43-97bfccbbdd7e.png)

**Comment by zryfish** [comment]
/close
issue has been fixed already
