### ISSUE TITLE
请教一下ks的sso是怎么做的

### ISSUE THREAD

**Issue by chenpfeisoo** [kubesphere/kubesphere#1433]
我看到ks里面集成了 监控日志相关的产品，咨询一下 sso这块的实现

**Comment by LinuxSuRen** [comment]
Hi @chenpfeisoo , sorry about no response here.  You're welcome to join Kubesphere community and communicate with us.

But GitHub issues is not a good place to ask questions. Please visit [the community forum](https://kubesphere.com.cn/forum/) instead. Usually,  people creating an issue on GitHub only to propose a feature, report a bug.
