### ISSUE TITLE
前端应用商店的权限控制

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#1437]
没有部署 OP，但是admin登录后，前端显示了应用商店入口，进入会报错。
![image](https://user-images.githubusercontent.com/40452856/68468261-a65e6780-0252-11ea-8365-0a1492f4da61.png)

**Comment by leoendless** [comment]
应该是部署op了，但op没有正常启动起来

**Comment by zheng1** [comment]
看看installer安装日志
