### ISSUE TITLE
default-http-backend-xxxx 这个镜像文件imagepullbackoff

### ISSUE THREAD

**Issue by johnlu655** [kubesphere/kubesphere#1439]
**问题描述**
kubesphere-controls-system     default-http-backend-xxxx 这个镜像文件处于imagepullbackoff，其它都是就绪，为什么这个镜像老下不来？
**安装环境的硬件配置**
ubuntu18.04
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)
all-in-one安装方式
**错误信息或截图**

**Installer版本**
kubesphere2.0.2在线版本安装

**Comment by rayzhou2017** [comment]
2.1.0已经fix了

**Comment by johnlu655** [comment]
非常感谢！------------------ 原始邮件 ------------------
发件人: "rayzhou2017"<notifications@github.com>
发送时间: 2019年11月9日(星期六) 中午11:46
收件人: "kubesphere/kubesphere"<kubesphere@noreply.github.com>;
抄送: "johnlu655"<553826005@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [kubesphere/kubesphere] default-http-backend-xxxx 这个镜像文件imagepullbackoff (#1439)



2.1.0已经fix了
 
&mdash;
