### ISSUE TITLE
添加应用仓库时，先创建再单击验证会提示错误

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1440]
1、进入一个企业空间，企业空间设置-应用仓库，点击创建仓库；
2、创建仓库时正确填写各项内容，先点击创建，在创建过程中点击验证，此时前端会报错
![image](https://user-images.githubusercontent.com/7677050/68524157-53da8500-02fe-11ea-9970-b1e5f5405bed.png)

**Comment by whDongRui** [comment]
这个是提交之后会重置表单中输入的信息，导致再去验证时传参为空，刚给修复了。

**Comment by mayuhope** [comment]
@whDongRui  这个问题开发环境仍然存在，麻烦看一下

**Comment by mayuhope** [comment]
在dev环境经验证已修复

**Comment by mayuhope** [comment]
使用2.1.1的安装包验证，已修复
