### ISSUE TITLE
搜索容器日志时无法根据下划线后的参数取值进行搜索

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1444]
1、查询容器日志，例如查询
ks-console这个容器的日志，该日志包含类似metrics_filter=node_cpu_usage这样的语句，如下图所示：
![image](https://user-images.githubusercontent.com/7677050/68525608-6fe62280-030e-11ea-81e0-f5e650d8bae0.png)

2、输入关键字cpu，结果无匹配结果：
![image](https://user-images.githubusercontent.com/7677050/68525618-7eccd500-030e-11ea-8377-ba6422d6b672.png)

**Comment by huanggze** [comment]
这是 es 分词的缘故，node_cpu_usage 是一个完整的单词，一般下划线算在单词里面。可以通过 nod、node_cpu、node_cpu_usa 这样搜索到。

要再精细化可能影响 es 查询性能，需要评估，看用户有没有方面的需求

**Comment by calvinyv** [comment]
/area documentation 
@huanggze 转成文档吧，作为功能限制

**Comment by huanggze** [comment]
测试多次，确实有一次发现出现空白节点。原因是指标 label 返回 node=“”，正常情况不应该出现。新的 pr 排序代码里过滤掉了这样的资源、不参与排序

**Comment by huanggze** [comment]
更新文档 https://github.com/kubesphere/docs.kubesphere.io/pull/559
