### ISSUE TITLE
存储卷扩容输入小数时，提交成功，但是配置文件没更新

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1445]
1、对已有存储卷进行扩容，输入小数位，例如输入100.1，提交

2、结果：前端提示更新成功，查看配置文件，发现仍然是之前的数据，实际上扩容失败了
![image](https://user-images.githubusercontent.com/7677050/68526447-0dddeb00-0317-11ea-83a6-d051d70354a8.png)

3、修改建议：建议检查是否支持小数位，若不支持小数位的扩容，建议在前端做下限制

**Comment by justahole** [comment]
目前还没开放小数点的容量

**Comment by calvinyv** [comment]
@mayuhope pls evaluate if this is a accepted answer, if yes, pls close issue.

**Comment by wnxn** [comment]
我觉得目前开放小数意义不大，数值部分按照整数处理即可。

**Comment by justahole** [comment]
同意，请求关闭这个issue

**Comment by mayuhope** [comment]
经沟通，跟前端UI库有关，输入的时候是小数，但是当光标移开的时候就会转为整数了，这是内部UI库的实现， 关闭此issue
