### ISSUE TITLE
The svc list needs to show ip address

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1446]
* [ ] 包括svc ip和lb ip，如果有的话
<img width="1001" alt="Screen Shot 2019-11-09 at 9 59 14 PM" src="https://user-images.githubusercontent.com/28859385/68529719-4e9c2b00-033c-11ea-98ca-a6b5aa19222c.png">

**Comment by Carlosfengv** [comment]
这里会以DNS信息代替Virtual IP ，
如果开启外网访问会根据 NodePort 和 Loadblance 显示对应的端口信息和IP信息。

**Comment by daniel-hutao** [comment]
/retitle The svc list needs to show ip address

**Comment by zryfish** [comment]
Already fixed 
/close
