### ISSUE TITLE
最新建的应用分类无法编辑和删除

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1450]
1、进入平台管理-应用管理-应用分类，新建一个应用分类；
2、该分类无法编辑和删除，鼠标移上去无编辑和删除图标，而其他所有分类（包括未分类）均可编辑和删除；

**Comment by whDongRui** [comment]
这个是后端默认查询结果没按时间倒序排序导致的，之前的查询结果是倒序的。目前OP相关的结果查询都没按时间倒序排序。

/assign @pengcong06 @wansir  帮忙看一下

**Comment by whDongRui** [comment]
这个前端单独加逻辑处理了。

**Comment by mayuhope** [comment]
经验证已修复，关闭issue
