### ISSUE TITLE
安装时等待sonarqube启动超时，导致流水线运行失败

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1452]
流水线运行到sonarqube analysis这一步骤时失败：
![image](https://user-images.githubusercontent.com/7677050/68540406-b9954280-03cc-11ea-8211-ede3471e20c0.png)
![image](https://user-images.githubusercontent.com/7677050/68540422-e2b5d300-03cc-11ea-8b4d-70617a627220.png)

建议：可以考虑延长超时时间，或其他规避方法

**Comment by pixiake** [comment]
sonarqube启动这个现在是等待10分钟，起不来自动跳过，不会影响安装流程，installer可以增加等待时间，但无法估计具体时间，跟集群网络环境有关系，下载镜像快的话，启动也比较快。 @runzexia

**Comment by runzexia** [comment]
@pixiake 可以预下载下镜像吧

**Comment by pixiake** [comment]
如果用installer 安装之前就开启devops 会预先下载相关镜像，但之后修改配置文件开启devops 就不会预先下载镜像了
