### ISSUE TITLE
关于2.0.2 升级至2.1.0问题

### ISSUE THREAD

**Issue by Forget-C** [kubesphere/kubesphere#1455]
首先 很高兴看到2.1版本发布了。
我看了一下2.1文档中的 “升级”升级，发现升级步骤是针对 “All-in-One”和“Multi-Node”的，而我的2.0.2安装方式是“在现有集群安装"的， 请问我该怎么升级？
我已经将升级包下载到了本地，看到里面有很多集群相关的“版本”，比如ks和etcd 。 如何在不更改我现有集群版本的情况下升级呢？

**Comment by Forget-C** [comment]
@zryfish

**Comment by rayzhou2017** [comment]
再等等

**Comment by Forget-C** [comment]
@rayzhou2017  是当前没有升级方法，需要等待吗？ 请问需要多久呢， 对新功能需求很迫切

**Comment by rayzhou2017** [comment]
是有一些细节需要调整，比如安装体验之类的

**Comment by Forget-C** [comment]
@rayzhou2017 那大概什么时候可以呢？

**Comment by rayzhou2017** [comment]
就这几天

**Comment by pixiake** [comment]
可以直接部署这个进行升级，注意存储一定要跟原来一致哦
https://github.com/kubesphere/ks-installer/tree/master/deploy
https://github.com/kubesphere/ks-installer/blob/master/README_zh.md

**Comment by Forget-C** [comment]
@pixiake  只要 storageClass 保证一致数据就不会丢失是吧
