### ISSUE TITLE
添加应用路由时可选择的服务数与实际服务数不符

### ISSUE THREAD

**Issue by ethanxzw** [kubesphere/kubesphere#1456]
添加应用路由时可选择的服务数远远小于实际服务数。

**Comment by ethanxzw** [comment]
![55d14bbfa9d9c6b7835429dc9842a0a](https://user-images.githubusercontent.com/41108414/68557409-ad62c100-0470-11ea-8e29-8d1eb910b3d5.png)

![d9e359417810317b678a70fdce34e31](https://user-images.githubusercontent.com/41108414/68557400-a50a8600-0470-11ea-94a2-5b2fb9c37032.png)

**Comment by zryfish** [comment]
升级到2.1.0试下，修复了

**Comment by ethanxzw** [comment]
已升级到2.1.0，但添加路由时，服务数仍然不对，比实际少很多
![image](https://user-images.githubusercontent.com/41108414/69337996-2ea22b00-0c9d-11ea-9993-62f39f496f23.png)
