### ISSUE TITLE
2.0.2升级到2.1页面显示还是2.0.2

### ISSUE THREAD

**Issue by tzghost** [kubesphere/kubesphere#1459]
从2.0.2升级到2.1，但页面上还是看到2.0.2

![image](https://user-images.githubusercontent.com/17000535/68562981-f32a8400-0486-11ea-89cc-e51138fecdab.png)

![image](https://user-images.githubusercontent.com/17000535/68562986-f7ef3800-0486-11ea-955b-c06dcb07e58e.png)

**Comment by pixiake** [comment]
`kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l app=ks-install -o jsonpath='{.items[0].metadata.name}') -f`

执行这个查看下升级日志

**Comment by tzghost** [comment]
[root@master1 kubesphere-all-v2.1.0]# kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l app=ks-install -o jsonpath='{.items[0].metadata.name}') -f
2019-11-11T04:04:04Z INFO     : shell-operator v1.0.0-beta.5
2019-11-11T04:04:04Z INFO     : HTTP SERVER Listening on 0.0.0.0:9115
2019-11-11T04:04:04Z INFO     : Use temporary dir: /tmp/shell-operator
2019-11-11T04:04:04Z INFO     : Initialize hooks manager ...
2019-11-11T04:04:04Z INFO     : Search and load hooks ...
2019-11-11T04:04:04Z INFO     : Load hook config from '/hooks/kubesphere/installRunner.py'
2019-11-11T04:04:05Z INFO     : Initializing schedule manager ...
2019-11-11T04:04:05Z INFO     : KUBE Init Kubernetes client
2019-11-11T04:04:05Z INFO     : KUBE-INIT Kubernetes client is configured successfully
2019-11-11T04:04:05Z INFO     : MAIN: run main loop
2019-11-11T04:04:05Z INFO     : MAIN: add onStartup tasks
2019-11-11T04:04:05Z INFO     : Running schedule manager ...
2019-11-11T04:04:05Z INFO     : QUEUE add all HookRun@OnStartup
2019-11-11T04:04:05Z INFO     : MSTOR Create new metric shell_operator_live_ticks
2019-11-11T04:04:05Z INFO     : MSTOR Create new metric shell_operator_tasks_queue_length
2019-11-11T04:04:05Z INFO     : GVR for kind 'ConfigMap' is /v1, Resource=configmaps
2019-11-11T04:04:05Z INFO     : EVENT Kube event 'cb2f699d-1a76-4130-8b0b-f8470b9e129b'
2019-11-11T04:04:05Z INFO     : QUEUE add TASK_HOOK_RUN@KUBE_EVENTS kubesphere/installRunner.py
2019-11-11T04:04:08Z INFO     : TASK_RUN HookRun@KUBE_EVENTS kubesphere/installRunner.py
2019-11-11T04:04:08Z INFO     : Running hook 'kubesphere/installRunner.py' binding 'KUBE_EVENTS' ...
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [localhost] ***************************************************************

TASK [download : include_tasks] ************************************************
skipping: [localhost]

TASK [download : Download items] ***********************************************
skipping: [localhost]

TASK [download : Sync container] ***********************************************
skipping: [localhost]

TASK [kubesphere-defaults : Configure defaults] ********************************
ok: [localhost] => {
    "msg": "Check roles/kubesphere-defaults/defaults/main.yml"
}

TASK [preinstall : check k8s version] ******************************************
changed: [localhost]

TASK [preinstall : init k8s version] *******************************************
ok: [localhost]

TASK [preinstall : Stop if kuernetes version is nonsupport] ********************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [preinstall : check helm status] ******************************************
changed: [localhost]

TASK [preinstall : Stop if Helm is not available] ******************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [preinstall : check storage class] ****************************************
changed: [localhost]

TASK [preinstall : Stop if StorageClass was not found] *************************
fatal: [localhost]: FAILED! => {
    "assertion": "persistence.storageClass in storage_class_check.stdout_lines", 
    "changed": false, 
    "evaluated_to": false, 
    "msg": "StorageClass local  was not found !"
}

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=3    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0

**Comment by pixiake** [comment]
"assertion": "persistence.storageClass in storage_class_check.stdout_lines",
"changed": false,
"evaluated_to": false,
"msg": "StorageClass local was not found !"


之前存储不是用的local吧   要跟之前一样哦

**Comment by tzghost** [comment]
之前用的是NFS，2.1配置了NFS和local都有true了
# LOCAL VOLUME
# KubeSphere will use local volume as storage by default.
# This is just for demostration and testing purpose, and highly not
# recommended in production environment.
# For production environment, please change to other storage type.
local_volume_enabled: true
local_volume_is_default_class: true
local_volume_storage_class: local


# NFS CONFIGURATION
# KubeSphere can use existing nfs service as backend storage service.
# change to true to use nfs.
nfs_client_enabled: true
nfs_client_is_default_class: true

# Hostname of the NFS server(ip or hostname)
nfs_server: 192.168.0.62

# Basepath of the mount point
nfs_path: /export
nfs_vers3_enabled: true
nfs_archiveOnDelete: true

**Comment by pixiake** [comment]
把local的改成false    为啥nfs_vers3_enabled也设置成 true了   之前用的nfs v3嘛？

**Comment by tzghost** [comment]
把local 和nfs_vers3_enabled 设置成的false后重新升级

[root@master1 scripts]# kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l app=ks-install -o jsonpath='{.items[0].metadata.name}') -f
2019-11-11T04:04:04Z INFO     : shell-operator v1.0.0-beta.5
2019-11-11T04:04:04Z INFO     : HTTP SERVER Listening on 0.0.0.0:9115
2019-11-11T04:04:04Z INFO     : Use temporary dir: /tmp/shell-operator
2019-11-11T04:04:04Z INFO     : Initialize hooks manager ...
2019-11-11T04:04:04Z INFO     : Search and load hooks ...
2019-11-11T04:04:04Z INFO     : Load hook config from '/hooks/kubesphere/installRunner.py'
2019-11-11T04:04:05Z INFO     : Initializing schedule manager ...
2019-11-11T04:04:05Z INFO     : KUBE Init Kubernetes client
2019-11-11T04:04:05Z INFO     : KUBE-INIT Kubernetes client is configured successfully
2019-11-11T04:04:05Z INFO     : MAIN: run main loop
2019-11-11T04:04:05Z INFO     : MAIN: add onStartup tasks
2019-11-11T04:04:05Z INFO     : Running schedule manager ...
2019-11-11T04:04:05Z INFO     : QUEUE add all HookRun@OnStartup
2019-11-11T04:04:05Z INFO     : MSTOR Create new metric shell_operator_live_ticks
2019-11-11T04:04:05Z INFO     : MSTOR Create new metric shell_operator_tasks_queue_length
2019-11-11T04:04:05Z INFO     : GVR for kind 'ConfigMap' is /v1, Resource=configmaps
2019-11-11T04:04:05Z INFO     : EVENT Kube event 'cb2f699d-1a76-4130-8b0b-f8470b9e129b'
2019-11-11T04:04:05Z INFO     : QUEUE add TASK_HOOK_RUN@KUBE_EVENTS kubesphere/installRunner.py
2019-11-11T04:04:08Z INFO     : TASK_RUN HookRun@KUBE_EVENTS kubesphere/installRunner.py
2019-11-11T04:04:08Z INFO     : Running hook 'kubesphere/installRunner.py' binding 'KUBE_EVENTS' ...
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [localhost] ***************************************************************

TASK [download : include_tasks] ************************************************
skipping: [localhost]

TASK [download : Download items] ***********************************************
skipping: [localhost]

TASK [download : Sync container] ***********************************************
skipping: [localhost]

TASK [kubesphere-defaults : Configure defaults] ********************************
ok: [localhost] => {
    "msg": "Check roles/kubesphere-defaults/defaults/main.yml"
}

TASK [preinstall : check k8s version] ******************************************
changed: [localhost]

TASK [preinstall : init k8s version] *******************************************
ok: [localhost]

TASK [preinstall : Stop if kuernetes version is nonsupport] ********************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [preinstall : check helm status] ******************************************
changed: [localhost]

TASK [preinstall : Stop if Helm is not available] ******************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [preinstall : check storage class] ****************************************
changed: [localhost]

TASK [preinstall : Stop if StorageClass was not found] *************************
fatal: [localhost]: FAILED! => {
    "assertion": "persistence.storageClass in storage_class_check.stdout_lines", 
    "changed": false, 
    "evaluated_to": false, 
    "msg": "StorageClass local  was not found !"
}

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=3    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0   

2019-11-11T05:58:51Z INFO     : EVENT Kube event 'cb2f699d-1a76-4130-8b0b-f8470b9e129b'
2019-11-11T05:58:51Z INFO     : QUEUE add TASK_HOOK_RUN@KUBE_EVENTS kubesphere/installRunner.py
2019-11-11T05:58:53Z INFO     : TASK_RUN HookRun@KUBE_EVENTS kubesphere/installRunner.py
2019-11-11T05:58:53Z INFO     : Running hook 'kubesphere/installRunner.py' binding 'KUBE_EVENTS' ...
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [localhost] ***************************************************************

TASK [download : include_tasks] ************************************************
skipping: [localhost]

TASK [download : Download items] ***********************************************
skipping: [localhost]

TASK [download : Sync container] ***********************************************
skipping: [localhost]

TASK [kubesphere-defaults : Configure defaults] ********************************
ok: [localhost] => {
    "msg": "Check roles/kubesphere-defaults/defaults/main.yml"
}

TASK [preinstall : check k8s version] ******************************************
changed: [localhost]

TASK [preinstall : init k8s version] *******************************************
ok: [localhost]

TASK [preinstall : Stop if kuernetes version is nonsupport] ********************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [preinstall : check helm status] ******************************************
changed: [localhost]

TASK [preinstall : Stop if Helm is not available] ******************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [preinstall : check storage class] ****************************************
changed: [localhost]

TASK [preinstall : Stop if StorageClass was not found] *************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [preinstall : check default storage class] ********************************
changed: [localhost]

TASK [preinstall : Stop if defaultStorageClass was not found] ******************
skipping: [localhost]

TASK [preinstall : check kubesphere ca secret] *********************************
changed: [localhost]

TASK [preinstall : Stop if kubesphere ca secret was not found] *****************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=5    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0   

[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [localhost] ***************************************************************

TASK [download : include_tasks] ************************************************
skipping: [localhost]

TASK [download : Download items] ***********************************************
skipping: [localhost]

TASK [download : Sync container] ***********************************************
skipping: [localhost]

TASK [kubesphere-defaults : Configure defaults] ********************************
ok: [localhost] => {
    "msg": "Check roles/kubesphere-defaults/defaults/main.yml"
}

TASK [common : Kubesphere | Check kube-node-lease namespace] *******************
changed: [localhost]

TASK [common : KubeSphere | Get system namespaces] *****************************
ok: [localhost]

TASK [common : set_fact] *******************************************************
ok: [localhost]

TASK [common : debug] **********************************************************
ok: [localhost] => {
    "msg": [
        "kubesphere-system", 
        "kubesphere-controls-system", 
        "kubesphere-monitoring-system", 
        "kube-node-lease", 
        "kubesphere-logging-system", 
        "openpitrix-system", 
        "kubesphere-devops-system", 
        "kubesphere-devops-system", 
        "kubesphere-devops-system", 
        "istio-system", 
        "kubesphere-alerting-system", 
        "istio-system"
    ]
}

TASK [common : KubeSphere | Create kubesphere namespace] ***********************
changed: [localhost] => (item=kubesphere-system)
changed: [localhost] => (item=kubesphere-controls-system)
changed: [localhost] => (item=kubesphere-monitoring-system)
changed: [localhost] => (item=kube-node-lease)
changed: [localhost] => (item=kubesphere-logging-system)
changed: [localhost] => (item=openpitrix-system)
changed: [localhost] => (item=kubesphere-devops-system)
changed: [localhost] => (item=kubesphere-devops-system)
changed: [localhost] => (item=kubesphere-devops-system)
changed: [localhost] => (item=istio-system)
changed: [localhost] => (item=kubesphere-alerting-system)
changed: [localhost] => (item=istio-system)

TASK [common : KubeSphere | Labeling system-workspace] *************************
changed: [localhost] => (item=default)
changed: [localhost] => (item=kube-public)
changed: [localhost] => (item=kube-system)
changed: [localhost] => (item=kubesphere-system)
changed: [localhost] => (item=kubesphere-controls-system)
changed: [localhost] => (item=kubesphere-monitoring-system)
changed: [localhost] => (item=kube-node-lease)
changed: [localhost] => (item=kubesphere-logging-system)
changed: [localhost] => (item=openpitrix-system)
changed: [localhost] => (item=kubesphere-devops-system)
changed: [localhost] => (item=kubesphere-devops-system)
changed: [localhost] => (item=kubesphere-devops-system)
changed: [localhost] => (item=istio-system)
changed: [localhost] => (item=kubesphere-alerting-system)
changed: [localhost] => (item=istio-system)

TASK [common : KubeSphere | Create ImagePullSecrets] ***************************
changed: [localhost] => (item=default)
changed: [localhost] => (item=kube-public)
changed: [localhost] => (item=kube-system)
changed: [localhost] => (item=kubesphere-system)
changed: [localhost] => (item=kubesphere-controls-system)
changed: [localhost] => (item=kubesphere-monitoring-system)
changed: [localhost] => (item=kube-node-lease)
changed: [localhost] => (item=kubesphere-logging-system)
changed: [localhost] => (item=openpitrix-system)
changed: [localhost] => (item=kubesphere-devops-system)
changed: [localhost] => (item=kubesphere-devops-system)
changed: [localhost] => (item=kubesphere-devops-system)
changed: [localhost] => (item=istio-system)
changed: [localhost] => (item=kubesphere-alerting-system)
changed: [localhost] => (item=istio-system)

TASK [common : KubeSphere | Getting kubernetes master num] *********************
changed: [localhost]

TASK [common : KubeSphere | Setting master num] ********************************
ok: [localhost]

TASK [common : Kubesphere | Getting common component installation files] *******
changed: [localhost] => (item=common)
changed: [localhost] => (item=ks-crds)

TASK [common : KubeSphere | Create KubeSphere crds] ****************************
changed: [localhost]

TASK [common : Kubesphere | Checking openpitrix common component] **************
changed: [localhost]

TASK [common : include_tasks] **************************************************
included: /kubesphere/installer/roles/common/tasks/pv-migration.yaml for localhost
included: /kubesphere/installer/roles/common/tasks/pv-migration.yaml for localhost

TASK [common : Kubesphere | Disabled openpitrix] *******************************
changed: [localhost]

TASK [common : Kubesphere | Checking openpitrix common component] **************
changed: [localhost]

TASK [common : Kubesphere | Get PersistentVolume Name] *************************
changed: [localhost]

TASK [common : Kubesphere | Patch PersistentVolume (persistentVolumeReclaimPolicy)] ***
changed: [localhost]

TASK [common : Kubesphere | Delete PersistentVolumeClaim] **********************
changed: [localhost]

TASK [common : Kubesphere | Patch PersistentVolume] ****************************
changed: [localhost]

TASK [common : Kubesphere | Disabled openpitrix] *******************************
changed: [localhost]

TASK [common : Kubesphere | Checking openpitrix common component] **************
changed: [localhost]

TASK [common : Kubesphere | Get PersistentVolume Name] *************************
changed: [localhost]

TASK [common : Kubesphere | Patch PersistentVolume (persistentVolumeReclaimPolicy)] ***
changed: [localhost]

TASK [common : Kubesphere | Delete PersistentVolumeClaim] **********************
changed: [localhost]

TASK [common : Kubesphere | Patch PersistentVolume] ****************************
changed: [localhost]

TASK [common : Getting PersistentVolumeName (mysql)] ***************************
changed: [localhost]

TASK [common : Getting PersistentVolumeSize (mysql)] ***************************
changed: [localhost]

TASK [common : Setting PersistentVolumeName (mysql)] ***************************
ok: [localhost]

TASK [common : Setting PersistentVolumeSize (mysql)] ***************************
ok: [localhost]

TASK [common : Getting PersistentVolumeName (etcd)] ****************************
changed: [localhost]

TASK [common : Getting PersistentVolumeSize (etcd)] ****************************
changed: [localhost]

TASK [common : Setting PersistentVolumeName (etcd)] ****************************
ok: [localhost]

TASK [common : Setting PersistentVolumeSize (etcd)] ****************************
ok: [localhost]

TASK [common : Kubesphere | Creating common component manifests] ***************
changed: [localhost] => (item={u'path': u'etcd', u'file': u'etcd.yaml'})
changed: [localhost] => (item={u'name': u'mysql', u'file': u'mysql.yaml'})
changed: [localhost] => (item={u'path': u'redis', u'file': u'redis.yaml'})

TASK [common : Kubesphere | Creating mysql sercet] *****************************
changed: [localhost]

TASK [common : Kubesphere | Deploying etcd and mysql] **************************
changed: [localhost] => (item=etcd.yaml)
changed: [localhost] => (item=mysql.yaml)

TASK [common : Kubesphere | Getting minio installation files] ******************
changed: [localhost] => (item=minio-ha)

TASK [common : Kubesphere | Creating manifests] ********************************
changed: [localhost] => (item={u'name': u'custom-values-minio', u'file': u'custom-values-minio.yaml'})

TASK [common : Kubesphere | Deploy minio] **************************************
error: unexpected EOF

**Comment by tzghost** [comment]
![image](https://user-images.githubusercontent.com/17000535/68564866-c1b4b700-048c-11ea-8ed2-6b12f35cf8e8.png)

**Comment by pixiake** [comment]
可以检查下存储的配置，或者开个teamviewer（tv 12）或者向日葵，把信息发到 kubesphere@yunify.com，我们上去看看吧

**Comment by tzghost** [comment]
发现很多pod 的状态是PodInitializing和ContainerCreating，等running就正常了
