### ISSUE TITLE
KS-Only安装好之后，admin登录，创建1个企业空间和1个项目之后，从应用商店部署应用，无法选择到该企业空间下的项目

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/kubesphere#1461]
![image](https://user-images.githubusercontent.com/38337958/68568799-8bc90000-0497-11ea-9aef-d11174f607c3.png)

**Comment by wansir** [comment]
fixed
/kind need-to-verify

**Comment by Ma-Dan** [comment]
![image](https://user-images.githubusercontent.com/38337958/68681919-3d068d80-059f-11ea-900a-2ba9bf3c8d67.png)
Verified, close issue.
