### ISSUE TITLE
2.1 应用商店

### ISSUE THREAD

**Issue by tzghost** [kubesphere/kubesphere#1462]
2.1版本应用商店怎么添加仓库和上传应用？admin没有看到相关权限

**Comment by wansir** [comment]
在企业空间管理概览页左侧可以看到应用模版的入口，应用仓库的配置在企业空间设置中。

这些的前提是需要启用 openpitrix 组件，通过修改kubesphere-system 下 ks-installer 这个 configmap

**Comment by FeynmanZhou** [comment]
@tzghost 请查阅文档，快速入门下有相关的教程

**Comment by tzghost** [comment]
好的
