### ISSUE TITLE
修改node节点的CPU和内存后，集群会临时多出一个节点

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1464]
测试环境：1个master和2个node节点；
测试步骤:
1、修改其中一个node节点的内存和CPU配置后，在ks的节点监控中会临时多出一个节点，该节点名称是空白的，监控数据为空，后来才恢复正常，稍后补图

**Comment by calvinyv** [comment]
@huanggze please double confirm if this is issue or as expected? my guess this may be caused by dirty data from prometheus or some status updating from k8s api.

**Comment by huanggze** [comment]
测试多次，确实有一次发现出现空白节点。原因是指标 label 返回 node=“”，正常情况不应该出现。新的 pr 排序代码里过滤掉了这样的资源、不参与排序

**Comment by mayuhope** [comment]
采用最新的installer测试验证，已无问题，因此关闭issue
