### ISSUE TITLE
2.1.0 kibana镜像拉取失败

### ISSUE THREAD

**Issue by Forget-C** [kubesphere/kubesphere#1466]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
2.1.0 kibana镜像拉取失败
**安装环境的硬件配置**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
![image](https://user-images.githubusercontent.com/25631506/68637300-27f71380-0539-11ea-958b-0137fa55b53e.png)

**Installer版本**
2.1.0

**Comment by FeynmanZhou** [comment]
kibana 属于第三方组件，如果从 qingcloud dockerhub 拉取有问题，可以尝试从国内的 mirror 或 dockerhub 拉取。
