### ISSUE TITLE
2.1.0邮件服务器设置 502

### ISSUE THREAD

**Issue by Forget-C** [kubesphere/kubesphere#1468]
2.1.0 邮件服务器设置页面 502 
api-gateway log 
![image](https://user-images.githubusercontent.com/25631506/68639380-57108380-053f-11ea-92de-ab0bb21f71f7.png)
除了loging中的kibana ， 其他服务都是正常
![image](https://user-images.githubusercontent.com/25631506/68639449-8f17c680-053f-11ea-95a7-36efb9a92588.png)

**Comment by wansir** [comment]
是不是刚刚启用通知告警模块呢，组件启动需要些时间，可以看看`kubesphere-alerting-system`下的pod是否正常

**Comment by Forget-C** [comment]
是 notification-deployment 这个pod的问题 ， 已经解决了
