### ISSUE TITLE
2.1在线安装失败，etcdcert失败

### ISSUE THREAD

**Issue by kalivenis** [kubesphere/kubesphere#1473]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
```
TASK [etcd : Check_certs | Set 'sync_certs' to true] ***********************************************
Tuesday 12 November 2019  14:59:01 +0800 (0:00:00.323)       0:12:49.181 ****** 
fatal: [master]: FAILED! => {}

MSG:

The conditional check 'gen_node_certs[inventory_hostname] or (not etcdcert_node.results[0].stat.exists|default(false)) or (not etcdcert_node.results[1].stat.exists|default(false)) or (etcdcert_node.results[1].stat.checksum|default('') != etcdcert_master.files|selectattr("path", "equalto", etcdcert_node.results[1].stat.path)|map(attribute="checksum")|first|default(''))' failed. The error was: no test named 'equalto'

The error appears to be in '/opt/kubesphere-all-v2.1.0/k8s/roles/etcd/tasks/check_certs.yml': line 57, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: "Check_certs | Set 'sync_certs' to true"
```
**安装环境的硬件配置**
多节点安装，三台centos7.6 x86-64 4核8g，VMware虚拟机
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
```
TASK [etcd : Check_certs | Set 'sync_certs' to true] ***********************************************
Tuesday 12 November 2019  14:59:01 +0800 (0:00:00.323)       0:12:49.181 ****** 
fatal: [master]: FAILED! => {}

MSG:

The conditional check 'gen_node_certs[inventory_hostname] or (not etcdcert_node.results[0].stat.exists|default(false)) or (not etcdcert_node.results[1].stat.exists|default(false)) or (etcdcert_node.results[1].stat.checksum|default('') != etcdcert_master.files|selectattr("path", "equalto", etcdcert_node.results[1].stat.path)|map(attribute="checksum")|first|default(''))' failed. The error was: no test named 'equalto'

The error appears to be in '/opt/kubesphere-all-v2.1.0/k8s/roles/etcd/tasks/check_certs.yml': line 57, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: "Check_certs | Set 'sync_certs' to true"
```
**Installer版本**
ks-install v2.1

**Comment by pixiake** [comment]
1.  执行`ansible --version`看下ansible的版本
2.  hosts.ini是怎么配的呢？

**Comment by kalivenis** [comment]
> 1. 执行`ansible --version`看下ansible的版本
> 2. hosts.ini是怎么配的呢？
ansible 2.8.5
  config file = /opt/kubesphere-all-v2.1.0/scripts/ansible.cfg
  configured module search path = [u'/opt/kubesphere-all-v2.1.0/scripts/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

[all]
master ansible_connection=local  ip=192.168.x.x
node1  ansible_host=192.168.x.x  ip=192.168.x.x ansible_ssh_pass=xxxxx
node2  ansible_host=192.168.x.x  ip=192.168.x.x ansible_ssh_pass=xxxxx

[kube-master]
master

[kube-node]
master
node1
node2

[etcd]
master

[k8s-cluster:children]
kube-node
kube-master

**Comment by pixiake** [comment]
ansible用2.7+  ,大版本还是有区别的 

`pip  install  ansible=2.7.12`

**Comment by kalivenis** [comment]
> ansible用2.7+ ,大版本还是有区别的
> 
> `pip install ansible=2.7.12`

[root@master scripts]# pip install 2.7.12
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement 2.7.12 (from versions: none)
ERROR: No matching distribution found for 2.7.12

**Comment by kalivenis** [comment]
> @kalivenis
> `pip install ansible==2.7.12`

[root@master scripts]# ansible --version
ansible 2.7.12
  config file = /opt/kubesphere-all-v2.1.0/scripts/ansible.cfg
  configured module search path = [u'/opt/kubesphere-all-v2.1.0/scripts/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

还是一样的错误

**Comment by kalivenis** [comment]
> @kalivenis
> `pip install ansible==2.7.12`

Please ensure that your environment has met the above requirements  (yes/no) yes
Traceback (most recent call last):
  File "os/precheck.py", line 71, in <module>
    defaultStorageClassCheck(getVars(getVarsFiles()), getVarsFiles())
  File "os/precheck.py", line 22, in getVars
    configs = yaml.load(f.read(), Loader=yaml.FullLoader)
AttributeError: 'module' object has no attribute 'FullLoader'
安装开始有这个提示，2.0.2没有

**Comment by pixiake** [comment]
`pip install -U --ignore-installed PyYAML`

**Comment by kalivenis** [comment]
> `pip install -U --ignore-installed PyYAML`

这个提示没有了，但是还是一样的错

**Comment by pixiake** [comment]
开个teamviewer（tv 12）或者向日葵，把信息发到 kubesphere@yunify.com

**Comment by kalivenis** [comment]
> 开个teamviewer（tv 12）或者向日葵，把信息发到 [kubesphere@yunify.com](mailto:kubesphere@yunify.com)

已发

**Comment by pixiake** [comment]
`pip install -U Jinja2`

可按照scripts/os/requirement.txt中版本修改pip依赖包版本

**Comment by kalivenis** [comment]
按上述方法已解决此问题
