### ISSUE TITLE
All-in-one 升级ks 2.1版本后; 相关组件依然是老的 

### ISSUE THREAD

**Issue by geniussheep** [kubesphere/kubesphere#1474]
1.升级完成后 jenkins版本 依然是 2.138.4
2.ks页面版本 依然是 2.0.2
3.openpitrix的相关组件几乎都被停止
4.在ks界面查看系统组件时，报错
报错信息如下：
Request to http://openpitrix-api-gateway.openpitrix-system:9100/v1/clusters?limit=10&offset=0&status=active&status=stopped&status=pending&status=ceased&runtime_id=runtime-2lGjZkxNAxYJ failed, method: GET,token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzeXN0ZW0iLCJyb2xlIjoiZ2xvYmFsX2FkbWluIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE4MTYyMzkwMjJ9.MViwGjfLLntiJ8IGeSGjNidYFJh-NYR589LakrXmXrc, reason: Get http://openpitrix-api-gateway.openpitrix-system:9100/v1/clusters?limit=10&offset=0&status=active&status=stopped&status=pending&status=ceased&runtime_id=runtime-2lGjZkxNAxYJ: dial tcp 10.233.18.13:9100: connect: connection refused

![image](https://user-images.githubusercontent.com/7587017/68651874-46720480-0563-11ea-831d-396d7e34f44b.png)

-------------------------------------------
common.yaml配置：
如下图
![image](https://user-images.githubusercontent.com/7587017/68651739-f3984d00-0562-11ea-953b-058ae823cee1.png)

**Comment by pixiake** [comment]
执行下边命令查看日志 ：
`kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l app=ks-install -o jsonpath='{.items[0].metadata.name}') -f`
