### ISSUE TITLE
日志收集的原理是什么？ 仅有个别的pod日志可以被收集

### ISSUE THREAD

**Issue by Forget-C** [kubesphere/kubesphere#1476]
不是通过kubesphere部署的应用可以被收集日志吗？  我们现在有的pod日志可以被收集，有的不可以，还有一些是断断续续的收集

**Comment by huanggze** [comment]
Fluent Bit + ElasticSearch

kubectl logs 看看 kubesphere-logging-system 下的 fluent-bit pod 有什么日志

**Comment by Forget-C** [comment]
@huanggze 
这是所有的 fluent-bit pod  日志 
![image](https://user-images.githubusercontent.com/25631506/68662010-ebe2a380-0576-11ea-92ab-bf46cca008d0.png)

**Comment by Forget-C** [comment]
因为今天升级过， 所以之前的日志都没了。 现在不收集日志

**Comment by huanggze** [comment]
之前的日志没了吗？是 index 空了？

```
curl elasticsearch-logging-data.kubesphere-logging-system.svc:9200/_cat/indices
```

请问怎么升级的呢？ks 2.1 的 fluent-bit 升级到 1.3.2 了，我看环境还是 1.0.5

**Comment by Forget-C** [comment]
之前的日志收集也有问题，只有少部分被收集，而且断断续续的。 
升级是用的的这个
![image](https://user-images.githubusercontent.com/25631506/68662570-0bc69700-0578-11ea-8db0-3288d4f661af.png)
[issues](https://github.com/kubesphere/kubesphere/issues/1455)

**Comment by huanggze** [comment]
我更新了我前面的 comment，你再试试

**Comment by Forget-C** [comment]
首先 fluent-bit的版本对了
![image](https://user-images.githubusercontent.com/25631506/68663123-17ff2400-0579-11ea-9973-2015f69fa029.png)
现在日志里有很多这样的 warn 
![image](https://user-images.githubusercontent.com/25631506/68663183-306f3e80-0579-11ea-83d9-9ac48ef35415.png)

**Comment by Forget-C** [comment]
web端查看只有 kube-system 和 kubesphere 的日志 。 其他项目的日志都没有收集。

**Comment by Forget-C** [comment]
@huanggze 日质量没有统计过，pod数量大概在400左右

**Comment by huanggze** [comment]
方便 tv 的话，可以预约一个时间段，发到我们的 support 邮箱 kubesphere@yunify.com 远程看看

**Comment by Forget-C** [comment]
hi  @huanggze  中午时候发的邮件没有收到回复。 
我修改了configmap 现在fluent-bit 无法启动了。 如何只将日志组件重新安装，恢复到初始状态？

**Comment by huanggze** [comment]
Hi 你截图的问题是 fluent-bit 新版本引入的 bug。具体可以看 fluent-bit 的issue 1707。我们会关注新版本的发布，并及时更新 fluent-bit

只需要重新安装 fluent-bit 即可。不需要重新安装 es。重启 flunet-bit 按论坛里这个问题的最佳回复操作即可 https://kubesphere.io/forum/d/142/5

**Comment by Forget-C** [comment]
@huanggze  按照你说的方法，pod已经恢复了 ， 但是现在仍然无法收集日志， 报错如下：
![图片](https://user-images.githubusercontent.com/25631506/68845206-05662580-0706-11ea-8861-da0e0f9d8739.png)

**Comment by huanggze** [comment]
听起来有几个问题呢。。一个个来，先说报错

我看 es 相关的 error 有 read-only 的提示信息。应该是日志太多， es 磁盘写满了。进入 elasticsearch-logging-data 的 pod 终端看看，是不是接近阈值了，导致触发 read-only：

```
curl localhost:9200/_cat/allocation?v
```

解决办法是要么扩容、要么删除一些index。下面假设删除 index：
```
# 查看有哪些 index
curl localhost:9200/_cat/indices

# 删除 index
curl -X DELETE "localhost:9200/ks-logstash-log-xxx"
```

然后解除 read-only
```
curl -X PUT "localhost:9200/ks-logstash-log-*/_settings" -H 'Content-Type: application/json' -d'
{
  "index.blocks.read_only_allow_delete": null
}
'
```

后面，你说增加过 Parser 导致起不来，应该是配置错了。可以先单独在自己的 namespace 部署 fluent-bit 试试，调好后再修改（不建议自己修改 kubesphere-logging-system 组件，以免影响后续升级。如果有需求可以提到社区，我们会考虑新增功能）

**Comment by huanggze** [comment]
也可以回退老版本的 fluent-bit，修改 ConfigMap，按之前的操作重建 fluent-bit。这是这个版本不支持中文日志

image = "kubesphere/fluent-bit:advanced-2.0.0"

![image](https://user-images.githubusercontent.com/22350668/68858300-b331fe00-071f-11ea-99fa-5d9d3ea55975.png)

**Comment by Forget-C** [comment]
@huanggze hi  确实是因为es的容量不够了导致的readonly。 
现在基本上是正常运行了， 但是仍然只收集 kubesphere 和 k8s 自己的日志， 用户容器日志仍然不收集。

**Comment by huanggze** [comment]
@Forget-C 这个是刚开始拉取日志的时候排队吧。等拉取完了就好了，等一会。现在再看应该没有新的 bulk queue 相关的error了
