### ISSUE TITLE
应用商店访问异常：Internal Server Error rpc error: code = Internal desc = describe resources failed: Error 1054: Unknown column 'owner_path' in 'field list'

### ISSUE THREAD

**Issue by zhangpfly** [kubesphere/kubesphere#1479]
系统环境：CentOS Linux release 7.7.1908 (Core)
主机：4核12G

使用在线安装脚本已经安装完毕，所有pod运行状态显示正常。

现在jenkins，gitlab，harbor这些组件都正常，但是应用商店无法正常使用。
![QQ截图20191113093458](https://user-images.githubusercontent.com/17722518/68725389-445a8500-05f9-11ea-88b0-8892aea407e9.png)

麻烦帮忙看一下是什么问题？还是需要设置？

**Comment by zhangpfly** [comment]
![QQ截图20191113093818](https://user-images.githubusercontent.com/17722518/68725436-69e78e80-05f9-11ea-9379-e4ef724e9ac7.png)

**Comment by calvinyv** [comment]
kubectl get pods -n openpitrix-system 看下

**Comment by zhangpfly** [comment]
![QQ截图20191113140736](https://user-images.githubusercontent.com/17722518/68737633-f8223b80-061e-11ea-9622-39e4a6cf462f.png)

**Comment by pengcong06** [comment]
可能是数据库初始化失败了,重新执行一下这个任务看看!
kubectl -n openpitrix-system get job openpitrix-db-init-job -o json | jq 'del(.spec.selector)' | jq 'del(.spec.template.metadata.labels)' | kubectl replace --force -f -

**Comment by zhangpfly** [comment]
已重装，已解决

**Comment by noprom** [comment]
我也遇到了这个问题：
![image](https://user-images.githubusercontent.com/8455444/70305621-d55efd80-183f-11ea-8692-3901af299898.png)
@pengcong06 重新执行这个任务成功了也不能访问。
![image](https://user-images.githubusercontent.com/8455444/70305661-ea3b9100-183f-11ea-8847-f7d7deefb503.png)
麻烦帮忙看看谢谢。

**Comment by zheng1** [comment]
@noprom 可以尝试禁用后再启用openpitrix
