### ISSUE TITLE
Support more alert policy

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#1480]
**Describe the feature(描述下问题)**
More requirement about alert and notification components for metrics and events:

1. Alert me when some node not ready
2. Alert me if some pod restart too many times: 5/10/20
3. Alert me if some pod crash
4. Alert me if the count of pod replicas fail to reach the target

**Comment by calvinyv** [comment]
@benjaminhuo @junotx pls double confirm, the scenarios mentioned above are supported or not?

**Comment by benjaminhuo** [comment]
They are supported by prometheus alert rules + event alert , user need to enable event component and setup notification manager receiver & configs to receive these alerts. No UI support to setup notification manager receiver yet though.

**Comment by calvinyv** [comment]
okay, so I plan to keep this issue open before we introduce UI in KS 3.1 or later, that should be called the total solution or perfect feature, thanks.

**Comment by zryfish** [comment]
@benjaminhuo Can we close this issue now? I assume the features requested above are all supported right now?

**Comment by benjaminhuo** [comment]
Yes, all supported in v3.1 now
