### ISSUE TITLE
前端优化

### ISSUE THREAD

**Issue by lenawu43** [kubesphere/kubesphere#1485]
我们希望能够实现前端开源，使得：
1：可以修改前端的配色
2：修改前端的字体等按键、组件
3：可以更改图片
etc...

**Comment by kuaiwenwu** [comment]
> 我们希望能够实现前端开源，使得：
> 1：可以修改前端的配色
> 2：修改前端的字体等按键、组件
> 3：可以更改图片
> etc...

默认的ui很好看，这也是kubesphere吸引人的一方面

**Comment by FeynmanZhou** [comment]
前端开源在这两周内，我们在论坛上有这样的帖子
