### ISSUE TITLE
ks-installer卡在Fetch op-minio data

### ISSUE THREAD

**Issue by 53537** [kubesphere/kubesphere#1486]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
common : Kubesphere | Fetch op-minio data
ks-installer在这里卡了几个小时了，请问是正常情况吗
**安装环境的硬件配置**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
![image](https://user-images.githubusercontent.com/37730538/68738333-040efd00-0621-11ea-86f5-238100ddbbf0.png)

**Installer版本**

**Comment by pixiake** [comment]
可以退出重看下日志是否还在这一步，如果是的话执行
`kubectl get pod, svc -n openpitrix-system`看下

**Comment by 53537** [comment]
![image](https://user-images.githubusercontent.com/37730538/68739725-73d2b700-0624-11ea-932d-4cb5aa6285eb.png)

**Comment by pixiake** [comment]
开个teamviewer（tv 12）或者向日葵，把信息发到 kubesphere@yunify.com看下

**Comment by 53537** [comment]
已发送

**Comment by pixiake** [comment]
由于openpitrix-system下的minio hang住，导致无法获取op-minio数据，重启op-minio恢复

**Comment by 53537** [comment]
升级完成后很多我们自建的pod状态异常，升级过程中有个错误task servicemesh status is failed
