### ISSUE TITLE
集群v2.0.2升级v2.1.0报错kubernetes/master : kubeadm | Upgrade other masters

### ISSUE THREAD

**Issue by zhangjun050754** [kubesphere/kubesphere#1489]
节点 3master 7node
![image](https://user-images.githubusercontent.com/22231085/68749015-7dfeb080-0638-11ea-87e3-d8c25cbf9544.png)

**Comment by pixiake** [comment]
应该是loadblancer的超时间隔超过了kubeadm的检测时间，重新执行一遍升级试下

**Comment by zhangjun050754** [comment]
> 应该是loadblancer的超时间隔超过了kubeadm的检测时间，重新执行一遍升级试下

执行了3次成功了 谢谢
