### ISSUE TITLE
Helm 应用模板填写中文乱码

### ISSUE THREAD

**Issue by leoendless** [kubesphere/kubesphere#1490]
see: https://kubesphere.io/forum/d/155-helm

**Comment by whDongRui** [comment]
已经引用base64-js解决了中文显示乱码的问题，目前就只有应用版本配置包中的文件回显作了处理。
不太清楚其它地方有没有base64解码显示的地方，有的话可以测试一下。

**Comment by rayzhou2017** [comment]
Please help verify this one @zheng1

**Comment by zheng1** [comment]
Verified
