### ISSUE TITLE
kubesphere 的2.0.2 版本中用多master方式安装完之后，应用仓库不能添加，在ns openpitrix-system 中的deployment 中逐个编辑添加后OPENPITRIX_ID_RANDOM_SEED后，不能添加青云默认的仓库，且验证不通过，

### ISSUE THREAD

**Issue by xugirl** [kubesphere/kubesphere#1491]
kubesphere 的2.0.2 版本中用多master方式安装完之后，应用仓库不能添加，在ns openpitrix-system 中的deployment 中逐个编辑添加后OPENPITRIX_ID_RANDOM_SEED后，不能添加青云默认的仓库，且验证不通过
![image](https://user-images.githubusercontent.com/35447641/68750816-77256d00-063b-11ea-9435-f4cb38453c4e.png)

**Comment by xugirl** [comment]
添加了别的仓库能成功添加，但是通过仓库部署pod时会报  
![image](https://user-images.githubusercontent.com/35447641/68751667-f10a2600-063c-11ea-97fc-e10e79b1f544.png)

**Comment by FeynmanZhou** [comment]
@xugirl 建议升级到 2.1，这是已知的 Bug 并在 2.1 进行了修复，可参考2.1的升级文档进行升级

**Comment by xugirl** [comment]
ok ,thks
