### ISSUE TITLE
cronjob定时任务时间默认是UTC

### ISSUE THREAD

**Issue by errorcode7** [kubesphere/kubesphere#1492]
[v2.02][cronjob][UTC]
今天设置了一个定时任务，发现到了时间没有执行，后来排查发现，时间默认是utc时间。
希望有个根据本地时间添加任务的办法？

**Comment by calvinyv** [comment]
Besides this problem, we also need to adjust the timestamps of ks core workloads, and sync with host boxes's timezone configuration.

**Comment by calvinyv** [comment]
also refer to another issue: https://github.com/kubesphere/ks-installer/issues/86

**Comment by calvinyv** [comment]
more reference could be found here:
https://kubesphere.com.cn/forum/d/191-pod
https://kubesphere.com.cn/forum/d/846-glusterfs
https://kubesphere.com.cn/forum/d/806-kubesphere2-1-0-bug

**Comment by pixiake** [comment]
The host‘s `/etc/localtime` can be mounted to the pod，when the workload‘s  manifests are generated.

https://github.com/kubesphere/ks-installer/blob/e552bfbe5e45c29c256e6315110426ced8ad0f9b/deploy/kubesphere-installer.yaml#L233

**Comment by rayzhou2017** [comment]
Does that require root?

**Comment by pixiake** [comment]
I tested it in ks-apiserver, It shouldn't be required.
![图片](https://user-images.githubusercontent.com/22290449/88018224-dbe57f80-cb59-11ea-85d3-79b72d210076.png)

**Comment by wanjunlei** [comment]
The cronjob is created by console, it needed console to add host‘s /etc/localtime to the cronjob pod.

**Comment by wanjunlei** [comment]
To fix this bug, it need to add host‘s /etc/localtime to the podtemplate of cronjob, not podtemplate of ks-consloe deployment, the latest version does not fix this.

**Comment by rayzhou2017** [comment]
not fixed yet. /cc @wanjunlei Can you show an example of the solution here?

**Comment by leoendless** [comment]
Did you select the `sync host timezone` in the container form?
![image](https://user-images.githubusercontent.com/8739949/88764345-60ae4a00-d1a7-11ea-81a0-e69fdf300b16.png)

**Comment by rayzhou2017** [comment]
The solution is not correct. It is still using the UTC. /cc @zryfish @pixiake please take a look this one. It might need to configure K8s controller to use local time

**Comment by rayzhou2017** [comment]
The solution is not correct. It is using the UTC. /cc @zryfish @pixiake please take a look this one. It might need to configure K8s controller to use local time

**Comment by zryfish** [comment]
https://github.com/kubernetes/kubernetes/issues/47202 Cronjob timezone is not supported by Kubernetes, it's too complicated, they want to focus on the core functionality and leave issue like this to the community. Currently, I can think of two approaches to solve this:
1. Mount `/etc/timezone` to kube-controller-manager, cause it's kube-controller-manager's job to calculate when to run cronjob. The limitation is involving change control plane configuration which might lead to unexpected behavior.
2. Convert user's input to the timezone that kube-controller-manager uses, which is UTC, to desired timezone, such as GMT+8. For example, when user type `0 14 * * *`, assuming user timezone is GMT+8, convert to `0 6 * * *` UTC. The limitation is what you see is not what you get, may lead confusion.

I think the best option for us now is to tell users we are using UTC timezone as default now, leave the timezone converting job to the user. Timezone converting is not an easy job.

**Comment by rayzhou2017** [comment]
Yes, It is better to just put a notice under the schedule time edit box right now, also remove the sync local time because it is useless. /cc @leoendless

**Comment by zryfish** [comment]
<img width="977" alt="截屏2020-07-31 10 21 56" src="https://user-images.githubusercontent.com/3326354/88993154-b7d32c80-d317-11ea-956a-1fc734237620.png">

A tooltip added to advise user to adjust schedule plan based on their timezone. I think we can close this issue now.
