### ISSUE TITLE
升级2.1完成后很多我们自建的pod状态异常

### ISSUE THREAD

**Issue by 53537** [kubesphere/kubesphere#1493]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
升级2.1完成后很多我们自建的pod状态异常;deployment正常，删除pod后不会重建
**安装环境的硬件配置**
3主多节点物理机
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**

**Installer版本**

**Comment by 53537** [comment]
W1112 12:54:55.886405       1 authentication.go:249] No authentication-kubeconfig provided in order to lookup client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication won't work.
W1112 12:54:55.886420       1 authentication.go:252] No authentication-kubeconfig provided in order to lookup requestheader-client-ca-file in configmap/extension-apiserver-authentication in kube-system, so request-header client certificate authentication won't work.
W1112 12:54:55.886444       1 authorization.go:177] failed to read in-cluster kubeconfig for delegated authorization: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
W1112 12:54:55.886467       1 authorization.go:146] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won't work.
I1112 12:54:55.890206       1 server.go:142] Version: v1.15.5
I1112 12:54:55.890306       1 defaults.go:87] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
W1112 12:54:55.892037       1 authorization.go:47] Authorization is disabled
W1112 12:54:55.892053       1 authentication.go:55] Authentication is disabled
I1112 12:54:55.892077       1 deprecated_insecure_serving.go:51] Serving healthz insecurely on [::]:10251
I1112 12:54:55.892635       1 secure_serving.go:116] Serving securely on [::]:10259
I1112 12:54:56.793764       1 leaderelection.go:235] attempting to acquire leader lease  kube-system/kube-scheduler...
I1112 12:56:07.078420       1 leaderelection.go:245] successfully acquired lease kube-system/kube-scheduler
E1113 04:01:02.841521       1 factory.go:678] Error scheduling kubesphere-system/etcd-778b9848d7-f249j: pod has unbound immediate PersistentVolumeClaims (repeated 3 times); retrying
E1113 04:01:02.845674       1 scheduler.go:485] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
E1113 04:01:04.138318       1 factory.go:678] Error scheduling kubesphere-system/etcd-778b9848d7-f249j: pod has unbound immediate PersistentVolumeClaims (repeated 3 times); retrying
E1113 04:01:04.138380       1 scheduler.go:485] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
E1113 04:01:06.264583       1 factory.go:678] Error scheduling kubesphere-system/etcd-778b9848d7-f249j: pod has unbound immediate PersistentVolumeClaims (repeated 3 times); retrying
E1113 04:01:06.264639       1 scheduler.go:485] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
E1113 04:01:12.848857       1 factory.go:678] Error scheduling kubesphere-system/minio-8cd46c8d9-jf4wq: pod has unbound immediate PersistentVolumeClaims (repeated 3 times); retrying
E1113 04:01:12.852318       1 factory.go:702] pod is already present in the activeQ
E1113 04:01:12.853043       1 scheduler.go:485] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
E1113 04:01:12.853712       1 factory.go:678] Error scheduling kubesphere-system/minio-8cd46c8d9-jf4wq: pod has unbound immediate PersistentVolumeClaims (repeated 3 times); retrying
E1113 04:01:12.853740       1 scheduler.go:485] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
E1113 05:31:57.117638       1 factory.go:678] Error scheduling kubesphere-system/redis-ha-server-0: pod has unbound immediate PersistentVolumeClaims (repeated 8 times); retrying
E1113 05:31:57.125767       1 scheduler.go:485] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 8 times)
E1113 05:31:57.125785       1 factory.go:702] pod is already present in the activeQ
E1113 05:31:57.127706       1 factory.go:678] Error scheduling kubesphere-system/redis-ha-server-0: pod has unbound immediate PersistentVolumeClaims (repeated 8 times); retrying
E1113 05:31:57.127739       1 scheduler.go:485] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 8 times)
E1113 05:32:20.827040       1 factory.go:678] Error scheduling kubesphere-system/redis-ha-server-1: pod has unbound immediate PersistentVolumeClaims (repeated 8 times); retrying
E1113 05:32:20.833274       1 scheduler.go:485] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 8 times)
E1113 05:32:20.833495       1 factory.go:702] pod is already present in the activeQ
E1113 05:32:20.835292       1 factory.go:678] Error scheduling kubesphere-system/redis-ha-server-1: pod has unbound immediate PersistentVolumeClaims (repeated 8 times); retrying
E1113 05:32:20.835330       1 scheduler.go:485] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 8 times)
E1113 05:32:33.545255       1 factory.go:678] Error scheduling kubesphere-system/redis-ha-server-2: pod has unbound immediate PersistentVolumeClaims (repeated 8 times); retrying
E1113 05:32:33.556097       1 scheduler.go:485] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 8 times)
E1113 05:35:19.366965       1 factory.go:678] Error scheduling kubesphere-system/openldap-0: pod has unbound immediate PersistentVolumeClaims (repeated 9 times); retrying
E1113 05:35:19.374353       1 scheduler.go:485] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 9 times)
E1113 05:36:05.808793       1 factory.go:678] Error scheduling kubesphere-system/openldap-1: pod has unbound immediate PersistentVolumeClaims (repeated 8 times); retrying
E1113 05:36:05.815807       1 scheduler.go:485] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 8 times)
E1113 05:36:05.818419       1 factory.go:678] Error scheduling kubesphere-system/openldap-1: pod has unbound immediate PersistentVolumeClaims (repeated 8 times); retrying
E1113 05:36:05.818461       1 scheduler.go:485] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 8 times)
E1113 05:36:05.822652       1 factory.go:702] pod is already present in the backoffQ
E1113 08:17:25.461211       1 factory.go:678] Error scheduling kubesphere-logging-system/elasticsearch-logging-discovery-1: pod has unbound immediate PersistentVolumeClaims (repeated 3 times); retrying
E1113 08:17:25.465403       1 scheduler.go:485] error selecting node for pod: pod has unbound immediate PersistentVolumeClaims (repeated 3 times)

**Comment by zryfish** [comment]
你升级的时候是保持StorageClass设置和之前是一样的么， 你执行 kubectl get sc 看下

**Comment by 53537** [comment]
配置和之前一样

**Comment by zryfish** [comment]
你执行下 `kubectl get sc` 看下输出，找到这些 pod 对应的 pvc `kubectl get pvc --all-namespaces`，使用 `kubectl describe [pvc]` 看下pvc的信息

**Comment by 53537** [comment]
kubectl get sc
NAME            PROVISIONER         AGE
rbd (default)   kubernetes.io/rbd   77d

kubectl get pvc -A
NAMESPACE                      NAME                                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
kubesphere-devops-system       data-ks-harbor-harbor-redis-0                      Bound    pvc-e98d4cda-c975-11e9-98a6-74867ad416e0   1Gi        RWO            rbd            77d
kubesphere-devops-system       database-data-ks-harbor-harbor-database-0          Bound    pvc-e987f710-c975-11e9-98a6-74867ad416e0   1Gi        RWO            rbd            77d
kubesphere-devops-system       ks-gitlab-minio                                    Bound    pvc-fdb4b69d-c975-11e9-b865-74867add05bc   10Gi       RWO            rbd            77d
kubesphere-devops-system       ks-gitlab-postgresql                               Bound    pvc-fdb51f54-c975-11e9-b865-74867add05bc   8Gi        RWO            rbd            77d
kubesphere-devops-system       ks-gitlab-redis                                    Bound    pvc-fdb57dd0-c975-11e9-b865-74867add05bc   5Gi        RWO            rbd            77d
kubesphere-devops-system       ks-harbor-harbor-chartmuseum                       Bound    pvc-e96f8779-c975-11e9-b865-74867add05bc   5Gi        RWO            rbd            77d
kubesphere-devops-system       ks-harbor-harbor-jobservice                        Bound    pvc-e96fed98-c975-11e9-b865-74867add05bc   1Gi        RWO            rbd            77d
kubesphere-devops-system       ks-harbor-harbor-registry                          Bound    pvc-e970568c-c975-11e9-b865-74867add05bc   5Gi        RWO            rbd            77d
kubesphere-devops-system       ks-jenkins                                         Bound    pvc-2d372270-c976-11e9-b865-74867add05bc   8Gi        RWO            rbd            77d
kubesphere-devops-system       ks-sonarqube-postgresql                            Bound    pvc-bb864322-c975-11e9-b865-74867add05bc   8Gi        RWO            rbd            77d
kubesphere-devops-system       repo-data-ks-gitlab-gitaly-0                       Bound    pvc-fdcd0b43-c975-11e9-98a6-74867ad416e0   10Gi       RWO            rbd            77d
kubesphere-logging-system      data-elasticsearch-logging-data-0                  Bound    pvc-066b2a3a-c976-11e9-98a6-74867ad416e0   20Gi       RWO            rbd            77d
kubesphere-logging-system      data-elasticsearch-logging-data-1                  Bound    pvc-22b42824-c976-11e9-98a6-74867ad416e0   20Gi       RWO            rbd            77d
kubesphere-logging-system      data-elasticsearch-logging-discovery-0             Bound    pvc-066eaba9-c976-11e9-98a6-74867ad416e0   4Gi        RWO            rbd            77d
kubesphere-logging-system      data-elasticsearch-logging-discovery-1             Bound    pvc-e255dfcd-afe3-433b-b172-27d9c679c9b9   4Gi        RWO            rbd            3h20m
kubesphere-monitoring-system   prometheus-k8s-db-prometheus-k8s-0                 Bound    pvc-07c48587-c976-11e9-98a6-74867ad416e0   20Gi       RWO            rbd            77d
kubesphere-monitoring-system   prometheus-k8s-db-prometheus-k8s-1                 Bound    pvc-07c643db-c976-11e9-98a6-74867ad416e0   20Gi       RWO            rbd            77d
kubesphere-monitoring-system   prometheus-k8s-system-db-prometheus-k8s-system-0   Bound    pvc-07e4ce9f-c976-11e9-98a6-74867ad416e0   20Gi       RWO            rbd            77d
kubesphere-monitoring-system   prometheus-k8s-system-db-prometheus-k8s-system-1   Bound    pvc-07e6710d-c976-11e9-98a6-74867ad416e0   20Gi       RWO            rbd            77d
kubesphere-system              data-redis-ha-server-0                             Bound    pvc-b00f988a-730c-47df-bb01-4b6905c2509d   2Gi        RWO            rbd            6h6m
kubesphere-system              data-redis-ha-server-1                             Bound    pvc-0db97933-de15-419b-914a-26919d5cc75d   2Gi        RWO            rbd            6h5m
kubesphere-system              data-redis-ha-server-2                             Bound    pvc-63590e9a-e6fa-4b19-a14b-6aadded885b4   2Gi        RWO            rbd            6h5m
kubesphere-system              etcd-pvc                                           Bound    pvc-c41c3562-c975-11e9-9554-74867adcf16c   20Gi       RWO            rbd            7h36m
kubesphere-system              minio                                              Bound    pvc-a3d9ac4f-0554-4034-8f7c-0309b108f171   20Gi       RWO            rbd            7h36m
kubesphere-system              mysql-pvc                                          Bound    pvc-c3f11a67-c975-11e9-98a6-74867ad416e0   20Gi       RWO            rbd            7h36m
kubesphere-system              openldap-pvc                                       Bound    pvc-cd06c5f1-c975-11e9-98a6-74867ad416e0   2Gi        RWO            rbd            77d
kubesphere-system              openldap-pvc-openldap-0                            Bound    pvc-17837173-a596-40a4-ad83-315abe134732   2Gi        RWO            rbd            6h2m
kubesphere-system              openldap-pvc-openldap-1                            Bound    pvc-4ab179c3-917c-4bcb-8622-b5d833746578   2Gi        RWO            rbd            6h1m
kubesphere-system              redis-pvc                                          Bound    pvc-cd08a6d4-c975-11e9-98a6-74867ad416e0   2Gi        RWO            rbd            77d
openpitrix-system              openpitrix-minio-pvc                               Bound    pvc-c4456ffa-c975-11e9-b865-74867add05bc   20Gi       RWO            rbd            77d
p2c-api                        wiki-yapi-mongo-storage-wiki-yapi-mongo-0          Bound    pvc-0148f1f0-d04c-11e9-a790-74867adcf16c   10Gi       RWO            rbd            68d
p2c-api                        wiki-yapi-web-storage-log                          Bound    pvc-60bc4b42-d04e-11e9-8efc-74867add05bc   10Gi       RWO            rbd            68d
p2c-arch-branch                cat-bucket-cat-1-0                                 Bound    pvc-b35eef71-daa3-11e9-a790-74867adcf16c   1Gi        RWO            rbd            55d
p2c-arch-branch                cat-bucket-cat-2-0                                 Bound    pvc-def4a77e-daa6-11e9-a790-74867adcf16c   1Gi        RWO            rbd            55d
p2c-fe-branch                  redis-data-redis-qnvugs-master-0                   Bound    pvc-1104d531-f564-11e9-a790-74867adcf16c   8Gi        RWO            rbd            21d
p2c-fe-branch                  redis-data-redis-qnvugs-slave-0                    Bound    pvc-11087751-f564-11e9-a790-74867adcf16c   8Gi        RWO            rbd            21d
p2c-fe-branch                  redis-data-redis-qnvugs-slave-1                    Bound    pvc-a0f19f21-f564-11e9-a790-74867adcf16c   8Gi        RWO            rbd            21d
p2c-fe-trunk                   redis-data-redis-1t9a3z-master-0                   Bound    pvc-1fdf522a-f564-11e9-a790-74867adcf16c   8Gi        RWO            rbd            21d
p2c-fe-trunk                   redis-data-redis-1t9a3z-slave-0                    Bound    pvc-1fe34bc3-f564-11e9-a790-74867adcf16c   8Gi        RWO            rbd            21d
p2c-fe-trunk                   redis-data-redis-1t9a3z-slave-1                    Bound    pvc-5e419f4c-f564-11e9-a790-74867adcf16c   8Gi        RWO            rbd            21d


kubectl -n kubesphere-system describe pvc openldap-1
Error from server (NotFound): persistentvolumeclaims "openldap-1" not found
[root@master3 ~]# kubectl -n kubesphere-system describe pvc openldap-pvc-openldap-1 
Name:          openldap-pvc-openldap-1
Namespace:     kubesphere-system
StorageClass:  rbd
Status:        Bound
Volume:        pvc-4ab179c3-917c-4bcb-8622-b5d833746578
Labels:        app.kubernetes.io/instance=ks-openldap
               app.kubernetes.io/name=openldap-ha
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/rbd
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      2Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    openldap-1
Events:        <none>


kubectl -n kubesphere-system describe pods openldap-1 
Name:           openldap-1
Namespace:      kubesphere-system
Priority:       0
Node:           master2/192.168.60.30
Start Time:     Wed, 13 Nov 2019 13:47:01 +0800
Labels:         app.kubernetes.io/instance=ks-openldap
                app.kubernetes.io/name=openldap-ha
                controller-revision-hash=openldap-656bd649d7
                statefulset.kubernetes.io/pod-name=openldap-1
Annotations:    <none>
Status:         Running
IP:             10.233.116.51
Controlled By:  StatefulSet/openldap
Containers:
  openldap-ha:
    Container ID:  docker://dc1cf0f9bd929a2ace279d6f16802fd466de197dc428505f7f480e5406887484
    Image:         osixia/openldap:1.3.0
    Image ID:      docker-pullable://osixia/openldap@sha256:cb3f5fea3c3203acddc3e6b8a70642a0f994d89be3ec5f0e50621b2a9ea17a83
    Port:          389/TCP
    Host Port:     0/TCP
    Args:
      --copy-service
      --loglevel=warning
    State:          Running
      Started:      Wed, 13 Nov 2019 19:37:24 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Wed, 13 Nov 2019 13:47:10 +0800
      Finished:     Wed, 13 Nov 2019 19:35:47 +0800
    Ready:          True
    Restart Count:  1
    Liveness:       tcp-socket :389 delay=30s timeout=1s period=15s #success=1 #failure=3
    Readiness:      tcp-socket :389 delay=30s timeout=1s period=15s #success=1 #failure=3
    Environment:
      LDAP_ORGANISATION:                 kubesphere
      LDAP_DOMAIN:                       kubesphere.io
      LDAP_CONFIG_PASSWORD:              admin
      LDAP_ADMIN_PASSWORD:               admin
      LDAP_REPLICATION:                  true
      LDAP_TLS:                          false
      LDAP_REMOVE_CONFIG_AFTER_SETUP:    true
      MY_POD_NAME:                       openldap-1 (v1:metadata.name)
      HOSTNAME:                          $(MY_POD_NAME).openldap
      LDAP_REPLICATION_CONFIG_SYNCPROV:  binddn="cn=admin,cn=config" bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config" type=refreshAndPersist retry="60 +" timeout=1
      LDAP_REPLICATION_DB_SYNCPROV:      binddn="cn=admin,$LDAP_BASE_DN" bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN" type=refreshAndPersist interval=01:00:00:10 retry="60 +" timeout=1
      LDAP_REPLICATION_HOSTS:            #PYTHON2BASH:['ldap://openldap-0.openldap', 'ldap://openldap-1.openldap']
    Mounts:
      /etc/ldap/slapd.d from openldap-pvc (rw,path="ldap-config")
      /var/lib/ldap from openldap-pvc (rw,path="ldap-data")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-b8dwx (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  openldap-pvc:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  openldap-pvc-openldap-1
    ReadOnly:   false
  default-token-b8dwx:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-b8dwx
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason          Age    From              Message
  ----    ------          ----   ----              -------
  Normal  SandboxChanged  4m19s  kubelet, master2  Pod sandbox changed, it will be killed and re-created.
  Normal  Pulled          4m18s  kubelet, master2  Container image "osixia/openldap:1.3.0" already present on machine
  Normal  Created         4m18s  kubelet, master2  Created container openldap-ha
  Normal  Started         4m18s  kubelet, master2  Started container openldap-ha

**Comment by zryfish** [comment]
这些pvc看着是正常的，异常的POD是哪些呢，可以尝试把对应的 deployment / statefulset scale 到 0，再scale 回去试下

**Comment by 53537** [comment]
尝试了删除pod，未重建出新pod

**Comment by 53537** [comment]
异常pod多数为我们自建业务pod

**Comment by zryfish** [comment]
有环境么，可以发到 kubesphere@yunify.com ，我看下

**Comment by 53537** [comment]
已发邮件
