### ISSUE TITLE
为什么grafana开启nodeport后很多栏目是没有数据？

### ISSUE THREAD

**Issue by kuaiwenwu** [kubesphere/kubesphere#1496]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
1. 把grafana 服务暴露出来后，发现很多指标是没有数据的，这个是什么情况
2，还有个疑问 kubesphere的网络流量的监控室通过什么技术实现抓取的。
**安装环境的硬件配置**
vmware虚拟机
 k8s 1.5.2集群

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
1. 把grafana 服务暴露出来后，发现很多指标是没有数据的，这个是什么情况
2，还有个疑问 kubesphere的网络流量的监控室通过什么技术实现抓取的。
**Installer版本**
kubesphere v2.1

**Comment by huanggze** [comment]
应该是没选择数据源

![image](https://user-images.githubusercontent.com/22350668/68817208-ee024a80-06bb-11ea-97ad-9a7d4afe2fa9.png)

容器流量监控来自 cAdvisor，节点监控数据来自 node-exporter
