### ISSUE TITLE
应用审核中列表名称有两个审核对象

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1498]
![image](https://user-images.githubusercontent.com/57089340/68923531-7dd9ee80-07b9-11ea-83f6-932c7ecbf673.png)

**Comment by whDongRui** [comment]
这个是翻译导致的，第二个应该是操作者。

**Comment by calvinyv** [comment]
@ellaye pls verify it.

**Comment by ellaye** [comment]
fix
/close
