### ISSUE TITLE
安装KS 2.1版本 

### ISSUE THREAD

**Issue by long0419** [kubesphere/kubesphere#1502]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**

**安装环境的硬件配置**
本地主机3台 ：
![image](https://user-images.githubusercontent.com/1064859/68829640-4f3e1400-06e4-11ea-8684-aa99be29a01b.png)

都属于cento 7 ，但是版本不一样 分别是 7.5  7.7  7.6

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
![image](https://user-images.githubusercontent.com/1064859/68829691-798fd180-06e4-11ea-9f70-125f09c32186.png)

![image](https://user-images.githubusercontent.com/1064859/68829706-86142a00-06e4-11ea-8c9b-ea74718e8bd6.png)

![image](https://user-images.githubusercontent.com/1064859/68829715-8f9d9200-06e4-11ea-8c24-874747dc99cb.png)

**Installer版本**
2.1

**Comment by pixiake** [comment]
检查下你的yum源 ，  master的yum源里没得有chrony这个包，对比一下三台机器的yum源

**Comment by long0419** [comment]
安装快结束的时候 提示这个错误 试错了很多遍

![2761573732330_ pic_hd](https://user-images.githubusercontent.com/1064859/68855630-9a264e80-0719-11ea-8e20-106fb9f5564f.jpg)

![2771573732563_ pic_hd](https://user-images.githubusercontent.com/1064859/68855634-9c88a880-0719-11ea-82ee-2fc4dbaac126.jpg)

![2781573732615_ pic_hd](https://user-images.githubusercontent.com/1064859/68855644-a27e8980-0719-11ea-84f4-5cb7b570028d.jpg)

**Comment by long0419** [comment]
> 检查下你的yum源 ， master的yum源里没得有chrony这个包，对比一下三台机器的yum源

已经解决了! 下面这个问题是快安装完报错的

**Comment by pixiake** [comment]
可以看下kube-system下的pod是否都正常，看样子像是kube-schedule不正常
`kubectl get pod -n kube-system`
`kubectl get pod -n kubesphere-system`

**Comment by pixiake** [comment]
如果kube-system下有不正常的pod    describe一下看看events

**Comment by long0419** [comment]
执行kubectl get pod -n kube-system 报如下错误

![image](https://user-images.githubusercontent.com/1064859/68859232-c9d95480-0721-11ea-9cee-d55e88db85b0.png)

执行kubectl get pod -n kubesphere-system 报如下错误
![image](https://user-images.githubusercontent.com/1064859/68859267-d9f13400-0721-11ea-9749-a2a3d0cadce0.png)

执行 kubectl describe pod ks-installer-7987c659d6-ht89k -n kubesphere-system 报如下错误
![image](https://user-images.githubusercontent.com/1064859/68859398-1e7ccf80-0722-11ea-8052-40724e4e6eda.png)

![image](https://user-images.githubusercontent.com/1064859/68859398-1e7ccf80-0722-11ea-8052-40724e4e6eda.png)

**Comment by pixiake** [comment]
用logs 看下

**Comment by long0419** [comment]
查询日志报如下错误
kubectl logs -f ks-installer-7987c659d6-ht89k -n kubesphere-system

![image](https://user-images.githubusercontent.com/1064859/68909518-84507200-0789-11ea-810d-20756e1aebaf.png)

**Comment by long0419** [comment]
我关了防火墙

**Comment by long0419** [comment]
![image](https://user-images.githubusercontent.com/1064859/68910073-77cd1900-078b-11ea-8eee-3c7413cc32c8.png)

安装成功了

**Comment by long0419** [comment]
安装完之后 ，现在报错如下 

![image](https://user-images.githubusercontent.com/1064859/68910754-dc897300-078d-11ea-8b35-dd93c30d42eb.png)

**Comment by long0419** [comment]
在现在监控镜像

**Comment by long0419** [comment]
![image](https://user-images.githubusercontent.com/1064859/68918718-62b3b280-07aa-11ea-8a24-1a65f9fc02a4.png)

开启这个服务之后 服务报错

**Comment by long0419** [comment]
> 这是minio容器因为cpu资源不够调度失败，是不是机器cpu性能不够了

确实是cpu 的问题 ，现在基本问题都解决了

**Comment by chinazj** [comment]
FAILED - RETRYING: kubesphere-installer is ok (30 retries left).

**Comment by chinazj** [comment]
FAILED - RETRYING: kubesphere-installer is ok (30 retries left).
