### ISSUE TITLE
kubesphere后台创建pv 和pvc失败

### ISSUE THREAD

**Issue by Carriezhangyan** [kubesphere/kubesphere#1503]
在kubesphere平台上手动创建一个存储卷名字为test，，然后在后台通过命令“kubectl get pv pvc-e7c31872-06a5-11ea-a6d6-000c29fd9fde -o yaml”获取这个存储卷的yaml文件，，将yaml文件内容保存到test.yaml，，在kubesphere平台上手动删除这个test存储卷。

终端执行命令“kubectl apply -f ./test.yaml” ，显示“persistentvolume/pvc-e7c31872-06a5-11ea-a6d6-000c29fd9fde created”。。。但是kubesphere平台web界面，找不到后台创建的存储卷，而且“kubectl get sv” 命令也找不到创建的存储卷。。这是为什么呢？还需要添加什么代码吗？

test.yaml文件内容如下
`apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: cluster.local/nfs-client-nfs-client-provisioner
  #creationTimestamp: "2019-11-14T06:13:44Z"
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-e7c31872-06a5-11ea-a6d6-000c29fd9fde
  resourceVersion: "17356718"
  selfLink: /api/v1/persistentvolumes/pvc-e7c31872-06a5-11ea-a6d6-000c29fd9fde
  uid: e97461dd-06a5-11ea-adfa-000c290849d5
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: test
    namespace: crm-dev
    resourceVersion: "17356710"
    uid: e7c31872-06a5-11ea-a6d6-000c29fd9fde
  nfs:
    path: /data/kubevolume/crm-dev-test-pvc-e7c31872-06a5-11ea-a6d6-000c29fd9fde
    server: 192.168.3.65
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-client
  volumeMode: Filesystem
status:
  phase: Bound
`

**Comment by wnxn** [comment]
kubesphere ui 里使用动态分配存储卷，ks 里存储卷对应 k8s 的 pvc，所以没有显示 pv。
kubesphere 里通过界面看不到 pv 的，可以通过界面的 kubectl 命令行工具查询 pv。

**Comment by Carriezhangyan** [comment]
修改后的代码如下，，出现的问题是：在kubesphere平台的前端可以看到创建的存储卷test，，但是状态显示“丢失”，，后端使用命令“kubectl get pv” ，也没有查到创建的那个pv和pvc


apiVersion: v1
kind: PersistentVolume
metadata:
&nbsp; annotations:
&nbsp; &nbsp; pv.kubernetes.io/provisioned-by: cluster.local/nfs-client-nfs-client-provisioner
&nbsp; finalizers:
&nbsp; - kubernetes.io/pv-protection
&nbsp; name: pvc-c7b51348-05eb-11ea-adfa-000c290849d5
&nbsp; selfLink: /api/v1/persistentvolumes/pvc-c7b51348-05eb-11ea-adfa-000c290849d5
&nbsp; uid: cde83921-05eb-11ea-adfa-000c290849d5
spec:
&nbsp; accessModes:
&nbsp; - ReadWriteMany
&nbsp; capacity:
&nbsp; &nbsp; storage: 20Gi
&nbsp; claimRef:
&nbsp; &nbsp; apiVersion: v1
&nbsp; &nbsp; kind: PersistentVolumeClaim
&nbsp; &nbsp; name: test
&nbsp; &nbsp; namespace: crm-dev
&nbsp; &nbsp; uid: c7b51348-05eb-11ea-adfa-000c290849d5
&nbsp; nfs:
&nbsp; &nbsp; path: /data/kubevolume/crm-dev-test-pvc-c7b51348-05eb-11ea-adfa-000c290849d5
&nbsp; &nbsp; server: 192.168.3.65
&nbsp; persistentVolumeReclaimPolicy: Delete
&nbsp; storageClassName: nfs-client
&nbsp; volumeMode: Filesystem
#status:
#&nbsp; phase: Bound
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
&nbsp; name: test
&nbsp; namespace: crm-dev
&nbsp; labels:
&nbsp; &nbsp; app: test
&nbsp; annotations:
&nbsp; &nbsp; pv.kubernetes.io/bind-completed: 'yes'
&nbsp; &nbsp; pv.kubernetes.io/bound-by-controller: 'yes'
&nbsp; &nbsp; volume.beta.kubernetes.io/storage-provisioner: cluster.local/nfs-client-nfs-client-provisioner
&nbsp; finalizers:
&nbsp; &nbsp; - kubernetes.io/pvc-protection
spec:
&nbsp; accessModes:
&nbsp; &nbsp; - ReadWriteMany
&nbsp; resources:
&nbsp; &nbsp; requests:
&nbsp; &nbsp; &nbsp; storage: 20Gi
&nbsp; volumeName: pvc-c7b51348-05eb-11ea-adfa-000c290849d5
&nbsp; storageClassName: nfs-client

**Comment by wnxn** [comment]
> 后端使用命令“kubectl get pv” ，也没有查到创建的那个pv和pvc

方便把完整的输入输出内容贴出来吗？

**Comment by Carriezhangyan** [comment]
确实在后端没有找到那个名字的pv和pvc。。。而且前端可以看到那个创建的pvc，，只是状态显示的不对，，状态为“丢失”。
我发给你的那段代码就是整个文件的代码..&nbsp;
前端的显示如下：



查看pvc





后端查询pv和pvc的命令如下：
[root@master0]# kubectl get pv
NAME&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;CAPACITY&nbsp; &nbsp;ACCESS MODES&nbsp; &nbsp;RECLAIM POLICY&nbsp; &nbsp;STATUS&nbsp; &nbsp;CLAIM&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;STORAGECLASS&nbsp; &nbsp;REASON&nbsp; &nbsp;AGE
pvc-0138273d-ddd3-11e9-a6d6-000c29fd9fde&nbsp; &nbsp;100Gi&nbsp; &nbsp; &nbsp; RWX&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Delete&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Bound&nbsp; &nbsp; sit/test-sh&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;nfs-client&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 52d









------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"pixiake-kubesphere"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 下午5:18
收件人:&nbsp;"kubesphere/kubesphere"<kubesphere@noreply.github.com&gt;;
抄送:&nbsp;"zhangyan"<625495630@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kubesphere/kubesphere] kubesphere后台创建pv 和pvc失败 (#1503)



 
后端使用命令“kubectl get pv” ，也没有查到创建的那个pv和pvc
  
方便把完整的输入输出内容贴出来吗？

**Comment by wnxn** [comment]
> 确实在后端没有找到那个名字的pv和pvc。。。而且前端可以看到那个创建的pvc，，只是状态显示的不对，，状态为“丢失”。 我发给你的那段代码就是整个文件的代码..&nbsp; 前端的显示如下： 查看pvc 后端查询pv和pvc的命令如下： [root@master0]# kubectl get pv NAME&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;CAPACITY&nbsp; &nbsp;ACCESS MODES&nbsp; &nbsp;RECLAIM POLICY&nbsp; &nbsp;STATUS&nbsp; &nbsp;CLAIM&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;STORAGECLASS&nbsp; &nbsp;REASON&nbsp; &nbsp;AGE pvc-0138273d-ddd3-11e9-a6d6-000c29fd9fde&nbsp; &nbsp;100Gi&nbsp; &nbsp; &nbsp; RWX&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Delete&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Bound&nbsp; &nbsp; sit/test-sh&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;nfs-client&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 52d
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"pixiake-kubesphere"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月14日(星期四) 下午5:18 收件人:&nbsp;"kubesphere/kubesphere"<kubesphere@noreply.github.com&gt;; 抄送:&nbsp;"zhangyan"<625495630@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [kubesphere/kubesphere] kubesphere后台创建pv 和pvc失败 (#1503) 后端使用命令“kubectl get pv” ，也没有查到创建的那个pv和pvc 方便把完整的输入输出内容贴出来吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

创建 PV 后有什么提示么？可能是 PV 没创建成功

**Comment by Carriezhangyan** [comment]
创建命令如下：
[root@master0]# kubectl apply -f ./pv.yaml
persistentvolume/pvc-c7b51348-05eb-11ea-adfa-000c290849d5 created
persistentvolumeclaim/test created



查询pv命令“kubectl get pv” 查询不到pv


查询pvc命令及结果如下：
[root@master0 angel-crm]# kubectl get pvc -n crm-dev
NAME&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;STATUS&nbsp; &nbsp; &nbsp; &nbsp; VOLUME&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;CAPACITY&nbsp; &nbsp;ACCESS MODES&nbsp; &nbsp;STORAGECLASS&nbsp; &nbsp;AGE
test&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Lost&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; pvc-c7b51348-05eb-11ea-adfa-000c290849d5&nbsp; &nbsp;0&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;nfs-client&nbsp; &nbsp; &nbsp;2m


前端的pvc状态显示为“丢失”




删除创建的pv和pvc命令及结果如下：
[root@master0 angel-crm]# kubectl delete -f ./pv.yaml
persistentvolumeclaim "test" deleted
Error from server (NotFound): error when deleting "./pv.yaml": persistentvolumes "pvc-c7b51348-05eb-11ea-adfa-000c290849d5" not found













------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"pixiake-kubesphere"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 下午5:41
收件人:&nbsp;"kubesphere/kubesphere"<kubesphere@noreply.github.com&gt;;
抄送:&nbsp;"zhangyan"<625495630@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kubesphere/kubesphere] kubesphere后台创建pv 和pvc失败 (#1503)



 
确实在后端没有找到那个名字的pv和pvc。。。而且前端可以看到那个创建的pvc，，只是状态显示的不对，，状态为“丢失”。 我发给你的那段代码就是整个文件的代码..&nbsp; 前端的显示如下： 查看pvc 后端查询pv和pvc的命令如下： [root@master0]# kubectl get pv NAME&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;CAPACITY&nbsp; &nbsp;ACCESS MODES&nbsp; &nbsp;RECLAIM POLICY&nbsp; &nbsp;STATUS&nbsp; &nbsp;CLAIM&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;STORAGECLASS&nbsp; &nbsp;REASON&nbsp; &nbsp;AGE pvc-0138273d-ddd3-11e9-a6d6-000c29fd9fde&nbsp; &nbsp;100Gi&nbsp; &nbsp; &nbsp; RWX&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Delete&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Bound&nbsp; &nbsp; sit/test-sh&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;nfs-client&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 52d
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"pixiake-kubesphere"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月14日(星期四) 下午5:18 收件人:&nbsp;"kubesphere/kubesphere"<kubesphere@noreply.github.com&gt;; 抄送:&nbsp;"zhangyan"<625495630@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [kubesphere/kubesphere] kubesphere后台创建pv 和pvc失败 (#1503) 后端使用命令“kubectl get pv” ，也没有查到创建的那个pv和pvc 方便把完整的输入输出内容贴出来吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
创建 PV 后有什么提示么？可能是 PV 没创建成功

**Comment by Carriezhangyan** [comment]
已经解决。。
