### ISSUE TITLE
集群环境istio 怎么没有安装istio-grafana?

### ISSUE THREAD

**Issue by gongjx11** [kubesphere/kubesphere#1504]
我想通过grafana来查看istio流量，我查了一上官方配置，需要启动一个POD istio-grafana应用，我看了一下我的POD没有这个应用，但是我看到了有这个目录和配置文件，但是为什么没有安装，请问一下是什么原？
安装的POD：
![image](https://user-images.githubusercontent.com/21954004/68838190-08a6e480-06f9-11ea-9a1d-986bd3341dd9.png)

配置文件：
![image](https://user-images.githubusercontent.com/21954004/68838240-1d837800-06f9-11ea-9846-4f1237dbcdc9.png)

**Comment by zryfish** [comment]
grafana默认没有安装，如果需要可以自己装下

**Comment by gongjx11** [comment]
好的，谢谢
