### ISSUE TITLE
同一个daemonset中部分容器无日志输出，日志数据中 "kubernetes": null

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1505]
1、创建一个daemonset，该daemonset中有3个pod，其中2个pod有日志输出，另一个pod （本次测试为logabc-fbx9m）在ks中无日志输出；

2、在后台使用kubectl查询无日志输出的那个容器日志，有日志：
root@master1 log]# kubectl logs logabc-fbx9m  -n  wahaha |wc -l
10003

3、flunt-bit容器日志有报错：
![image](https://user-images.githubusercontent.com/7677050/68840788-5d009300-06fe-11ea-9a2a-dcd6b81e955a.png)

4、在kibana中查询日志，结果如下,kubernetes为null，导致不会进行查询
![image](https://user-images.githubusercontent.com/7677050/68840840-71449000-06fe-11ea-87ff-5fcaae29704f.png)

**Comment by huanggze** [comment]
需要等 fluent-bit release bugfix。1.3.2 的bug，具体可以看 fluent bit issue 1707

**Comment by mayuhope** [comment]
在最新的instaler中已验证
