### ISSUE TITLE
2.02 离线版反复安装，导致产生很多备份文件夹

### ISSUE THREAD

**Issue by errorcode7** [kubesphere/kubesphere#1506]
安装出错，必然会反复重新安装，会导致以下问题：
1.master上会多出很多/etc/yum.repos.d备份文件夹
2.node 上/etc/yum.repos.d/里的client.repo 会反复追加内容
建议增加md5相关的校验脚步，检查到内容相同则不再备份以及添加文件内容

**Comment by pixiake** [comment]
很好的建议
