### ISSUE TITLE
Jenkins Pipeline的语法检查：正确的代码 被告知语法错误，导致无法修改

### ISSUE THREAD

**Issue by geniussheep** [kubesphere/kubesphere#1508]
本人使用 jenkins shared libraries  时 编辑JenkinsPipeline 脚本式提示错误，导致无法继续修改
但是通过 Jenkins 去修改对应项目的pipeline后，可以成功运行。

![image](https://user-images.githubusercontent.com/7587017/68845718-cd131700-0706-11ea-9e30-cdee380162ea.png)
![image](https://user-images.githubusercontent.com/7587017/68845876-15323980-0707-11ea-94cb-1a827c2d8c7b.png)

**Comment by soulseen** [comment]
可以把jenkinsfile贴出来看一下吗
