### ISSUE TITLE
2.0.2升级2.1后，ldap运行正常，登录时校验失败

### ISSUE THREAD

**Issue by 53537** [kubesphere/kubesphere#1509]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
2.0.2升级2.1后，ldap pod运行正常，登录时校验失败,用户名或密码错误
openldap pod日志如下：
5dcd2f2a conn=12063 fd=33 ACCEPT from IP=192.168.xx.xx:51354 (IP=0.0.0.0:389)
5dcd2f2a conn=12063 fd=33 closed (connection lost)
**安装环境的硬件配置**
3主多节点物理机
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**

**Installer版本**

**Comment by 53537** [comment]
升级前同步信息和用户校验正常；升级后无法校验

**Comment by 53537** [comment]
这是ldap pod另外一段日志
5dcd3003 conn=1011 op=22 SRCH base="ou=Users,dc=kubesphere,dc=io" scope=2 deref=0 filter="(&(objectClass=inetOrgPerson))"
5dcd3003 conn=1011 op=22 SRCH attr=uid mail description preferredLanguage createTimestamp

**Comment by wansir** [comment]
可以看看 ks-account 的日志， ldap 日志正常没有错误。无法登录请注意前端提示，确认一下密码是否正确，确认一下是否因为登录失败次数太多被封禁。

**Comment by 53537** [comment]
ks-account日志：

E1113 11:41:39.462884       1 routers.go:183] open /etc/kubesphere/ingress-controller: no such file or directory
E1113 11:41:39.464131       1 routers.go:61] open /etc/kubesphere/ingress-controller: no such file or directory
W1113 11:41:39.494111       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1113 11:41:40.839623       1 server.go:113] Server listening on 0.0.0.0:9090 
I1114 07:14:05.222544       1 im.go:448] auth failed chenjie1 LDAP Result Code 49 "Invalid Credentials": 
I1115 03:48:33.930080       1 im.go:448] auth failed chenjie1 LDAP Result Code 49 "Invalid Credentials":

**Comment by wansir** [comment]
看错误提示是密码输入错了，可以登录管理员账号重置密码

**Comment by 53537** [comment]
这个是域控的认证，没有设置

**Comment by 53537** [comment]
密码没有输错，尝试多个账号都是认证失败

**Comment by wansir** [comment]
升级之后把 ad-sidecar 给移除掉了， 需要重新配置一下 https://kubesphere.io/forum/d/159-kubesphere-ad
