### ISSUE TITLE
k8s v1.15.0 minimal安装，找不到workspace.yaml

### ISSUE THREAD

**Issue by errorcode7** [kubesphere/kubesphere#1511]
k8s v1.15.0 
fatal: [localhost]: FAILED! => {"attempts": 5, "changed": true, "cmd": "/usr/local/bin/kubectl apply -f /etc/kubesphere/workspace.yaml", "delta": "0:00:00.452092", "end": "2019-11-15 01:14:10.619730", "msg": "non-zero return code", "rc": 1, "start": "2019-11-15 01:14:10.167638", "stderr": "error: unable to recognize \"/etc/kubesphere/workspace.yaml\": no matches for kind \"Workspace\" in version \"tenant.kubesphere.io/v1alpha1\"", "stderr_lines": ["error: unable to recognize \"/etc/kubesphere/workspace.yaml\": no matches for kind \"Workspace\" in version \"tenant.kubesphere.io/v1alpha1\""], "stdout": "", "stdout_lines": []}

**Comment by errorcode7** [comment]
同时不建议把kubectl路径固定为/usr/local/bin/kubectl，因为我用yum安装的kubectl，默认路径在/usr/bin/下面，建议先用which kubectl找一下。

**Comment by pixiake** [comment]
上边的操作都在容器里，看日志像是crd没有创建成功  @wansir

**Comment by errorcode7** [comment]
@pixiake delete 掉，重新apply可以了。。。
