### ISSUE TITLE
在有状态副本集中更新服务报错

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1513]
![image](https://user-images.githubusercontent.com/57089340/68923438-48cd9c00-07b9-11ea-8266-83ec98ab317b.png)

**Comment by liangyuanpeng** [comment]
也许是 metadata.resourcesVersion字段没有填或填错了？
 
从提示框看来是这样的

**Comment by leoendless** [comment]
将在2.1.1 修复

**Comment by leoendless** [comment]
Fixed

**Comment by ellaye** [comment]
fixed
/close
