### ISSUE TITLE
请问下，如果想更改一下前端代码然后再安装，应该如何找到前端代码？

### ISSUE THREAD

**Issue by yurokn** [kubesphere/kubesphere#1514]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**

**安装环境的硬件配置**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**

**Installer版本**

**Comment by FeynmanZhou** [comment]
前端会在近2周内开源
