### ISSUE TITLE
worker节点资源调度限制，Node Allocatable特性

### ISSUE THREAD

**Issue by zhangpfly** [kubesphere/kubesphere#1515]
系统环境：3节点，4核12G，1master 2worker，centos7

今天上午我遇到一个问题就是，节点2还有2G内存，节点1是5G内存，在安装harbor的时候，调度到了节点2上，直接把节点2 OOM了，显示状态NotReady。系统无法正常运行。

能否在安装之前，配置文件中设置可配置项，定义每个节点预留给系统多少资源。
或者是安装完成之后，有界面能设置每台主机可以调度的资源也行。这样不用安装完成后，再手动设置这些参数了。

**Comment by FeynmanZhou** [comment]
好建议，对于 Harbor 和 Gitlab 这种资源消耗较大的第三方应用  通过 selector 指定在某个资源充足节点创建更合适，我们会参考调整
