### ISSUE TITLE
您好，前端什么时候支持开源呢？

### ISSUE THREAD

**Issue by yabigal** [kubesphere/kubesphere#1516]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**

**安装环境的硬件配置**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**

**Installer版本**

**Comment by AaronPei** [comment]
听说再过两个星期
