### ISSUE TITLE
平台设置中，找不到应用仓库设置

### ISSUE THREAD

**Issue by zhangpfly** [kubesphere/kubesphere#1519]
系统环境：CentOS Linux release 7.7.1908 (Core)
主机：4核12G
KubeSphere 版本 : v2.1.0

使用在线安装脚本已经安装完毕，所有pod运行状态显示正常。

应用商店显示正常。但是在平台设置里面看不到应用仓库的设置。

![image](https://user-images.githubusercontent.com/17722518/68926738-2d668f00-07c1-11ea-89e8-d2ff96047d48.png)
![image](https://user-images.githubusercontent.com/17722518/68926821-54bd5c00-07c1-11ea-8524-aba504569141.png)

**Comment by FeynmanZhou** [comment]
2.1 把应用仓库放到了 企业空间 下，参考：https://kubesphere.io/docs/v2.1/zh-CN/quick-start/one-click-deploy/#%E5%AF%BC%E5%85%A5%E5%BA%94%E7%94%A8%E4%BB%93%E5%BA%93
