### ISSUE TITLE
定时任务编辑配置文件后不能更新

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1520]
![image](https://user-images.githubusercontent.com/57089340/68930278-f7c5a400-07c8-11ea-8144-f357c9562a7b.png)

**Comment by leoendless** [comment]
这个应该是你的 spec.schedule 格式不正确问题， 可以参考[CRON](https://en.wikipedia.org/wiki/Cron)语法进行设置

**Comment by leoendless** [comment]
Fixed

**Comment by leoendless** [comment]
> 这个应该是你的 spec.schedule 格式不正确问题， 可以参考[CRON](https://en.wikipedia.org/wiki/Cron)语法进行设置

Fixed

**Comment by ellaye** [comment]
没有问题
/close
