### ISSUE TITLE
创建流程线时无法选择证书

### ISSUE THREAD

**Issue by guoh1988** [kubesphere/kubesphere#1528]
**General remarks**

> Please delete this section including header before submitting
> 也可以使用中文
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug(描述下问题)**

For UI issues please also add a screenshot that shows the issue.

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere:2.1.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
3 masters:  12核64G

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**
1.选择DevOps工程选择创建流程线，下选择代码仓库添加代码仓库
2.选择SVN，点击证书一栏无法选择已经创建的证书，点击新建凭证也无法保存，并且弹框会出现无法取消
**Expected behavior(预期行为)**

**Comment by minghaoye** [comment]
刷新一下也没有么，有时返回较慢，当前页面的刷新还没拿到新数据

**Comment by guoh1988** [comment]
没有，如

**Comment by guoh1988** [comment]
没有

**Comment by guoh1988** [comment]
选择一直看不到填写的凭据
![201911181](https://user-images.githubusercontent.com/28557169/69029544-3ef1a600-0a10-11ea-9af8-d6d3f1b46210.PNG)
点击确定后凭据创建好了还是不消失
![201911182](https://user-images.githubusercontent.com/28557169/69029694-a871b480-0a10-11ea-9ff5-8b396abf86b8.PNG)

还有个问题S2I的时候的代码仓库只能选择git形式的吗，SVN不可以吗
![201911183](https://user-images.githubusercontent.com/28557169/69030307-1e2a5000-0a12-11ea-8d5f-3e02bf2b20eb.PNG)

**Comment by minghaoye** [comment]
1.点击确定后凭据创建好了还是不消失（名称冲突），可以去凭证页面查看是否有创建的凭证
2.只支持SVN

**Comment by guoh1988** [comment]
首先感谢你的回复，可能我对问题的表达不够清楚
1.首先我的凭据里面是凭据的，但是下拉里面显示没有，点击下拉下面的新建凭据
![图片](https://user-images.githubusercontent.com/28557169/69051650-e33f1100-0a3f-11ea-85ba-a8997cc986a6.png)
2.如下就是我的新建凭据，我点确认以后可以提交凭据信息但是这个对话框没有消失，再点击确认就显示用户名已经存在，我去凭据里面查看凭据一个存在，无论我点击确定还是取消这个对话框都不会消失，必须要要F5刷新才消失
![图片](https://user-images.githubusercontent.com/28557169/69051843-6fe9cf00-0a40-11ea-94a4-cf11ed4c02db.png)

**Comment by minghaoye** [comment]
了解，这个问题我们还没法复现，可以提供一下kubesphere版本，浏览器版本，可以的话看一下浏览器控制台的报错。

**Comment by guoh1988** [comment]
@minghaoye 是浏览器的版本问题
kubesphere：2.1.0
firefox:52.0.2 打开有这个bug
firefox：68.1.0没有这个问题

**Comment by minghaoye** [comment]
谢谢反馈，建议使用新版本的chrome或Firefox，后面我们测试下这个问题。

/close
