### ISSUE TITLE
Pipeline deployment failed due to wrong format of generated kubeconfig

### ISSUE THREAD

**Issue by hlwanghl** [kubesphere/kubesphere#1529]
**Describe the bug(描述下问题)**
Wrong format of generated kubeconfig in DevOps projects.

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/4861515/69023391-8e78a780-09f9-11ea-9ab9-a225f55fa12b.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**

**Expected behavior(预期行为)**

**Comment by wansir** [comment]
fixed  #1763

**Comment by pixiake** [comment]
verify
