### ISSUE TITLE
扩展GPU节点失败

### ISSUE THREAD

**Issue by zhanlinfeng** [kubesphere/kubesphere#1533]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**：在扩展GPU节点时失败了，提示：
`nvidia-container-runtime-hook (< 2.0.0) but it is not going to be installed`
于是我在GPU节点安装了nvidia-docker2，但是这没有生效。并且在/usr/bin/nvidia-container-runtime-hook 是存在的（但存在一个软链接,问题会在这吗？）。

**安装环境的硬件配置**：GPU节点，内存60G, GPU型号K80<云主机>

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
![image](https://user-images.githubusercontent.com/32413524/69050437-07e5b980-0a3d-11ea-9fa4-b9cc33bf99d3.png)

**Installer版本**：2.0.2

**Comment by FeynmanZhou** [comment]
@zhanlinfeng GPU Node 的操作系统是什么？

**Comment by zhanlinfeng** [comment]
> @zhanlinfeng GPU Node 的操作系统是什么？

ubuntu 16.04

**Comment by FeynmanZhou** [comment]
@benjaminhuo 帮忙看看这个问题吧
