### ISSUE TITLE
无法通过应用仓库部署应用

### ISSUE THREAD

**Issue by aiguanglee** [kubesphere/kubesphere#1534]
系统环境：CentOS Linux release 7.7.1908 (Core)
主机：4核12G
KubeSphere 版本 : v2.1.0

问题描述

通过应用仓库部署应用，提示
rpc error: code = PermissionDenied desc = access denied for resource [runtime-Ny7zqKOEpBY6]: rpc error: code = PermissionDenied desc = Runtime [runtime-Ny7zqKOEpBY6] not found: <nil>

**Comment by FeynmanZhou** [comment]
导入的应用仓库的 URL 是什么呢？

**Comment by aiguanglee** [comment]
通过官方提供的应用商店，任何一个应用都是如此

**Comment by FeynmanZhou** [comment]
看了这个 issue #1532 ，应该是后来开启的 openpitrix 功能组件安装未成功，`kubectl get pod -n openpitrix-system` 看下

**Comment by aiguanglee** [comment]
issue #1532  通过重装已经解决了，现在是无法通过helm部署应用，无论是官方应用商店，还是私有helm charts

**Comment by pengcong06** [comment]
找到你创建的那个namespace 然后执行这个:
kubectl annotate ns <namespace> openpitrix_runtime-

**Comment by wansir** [comment]
```
for ns in `kubectl get ns -o jsonpath="{range .items[*]}{.metadata.name}{'\n'}{end}"`; do kubectl annotate ns $ns openpitrix_runtime-; done
```

**Comment by aiguanglee** [comment]
执行之后，能够正常部署了，应该是这个ns是通过命令行手动创建的，而非通过kubesphere控制台创建，谢谢！
