### ISSUE TITLE
The kubectl tool loses connection sometimes

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1536]
The kubectl tool loses connection sometimes

![image](https://user-images.githubusercontent.com/22350668/69114437-48d2e200-0ac0-11ea-862a-2d29c368e1bb.png)

**Comment by leoendless** [comment]
是长时间没有操作导致连接断开了吗，如果是，这种现象可以避免 ws 端口一直被占用。

@Carlosfengv @justahole 可以在 UI上提供个重连的按钮。

**Comment by wansir** [comment]
反代有超时设置，需要把心跳加上
/assign @wansir

**Comment by justahole** [comment]
加个重连吧。

**Comment by huanggze** [comment]
未解决

![image](https://user-images.githubusercontent.com/22350668/74134760-0a177880-4c26-11ea-8882-84b7040f9196.png)

**Comment by huanggze** [comment]
![image](https://user-images.githubusercontent.com/22350668/74144410-a302bf80-4c37-11ea-8de7-1fb3a2e912d5.png)

**Comment by huanggze** [comment]
fixed

**Comment by huanggze** [comment]
unfixed
