### ISSUE TITLE
kubesphere-installer is ok

### ISSUE THREAD

**Issue by xiexiao072** [kubesphere/kubesphere#1537]
<FAILED - RETRYING: kubesphere-installer is ok (30 retries left).
>没有任何报错信息尝试30次后退出

**Comment by pixiake** [comment]
检查下k8s集群状态 
`kubectl  get pod -n kube-system`
 看看集群正不正常

**Comment by xiexiao072** [comment]
[root@ks-allinone scripts]# kubectl get pod -n kube-system
NAME                                           READY   STATUS             RESTARTS   AGE
calico-kube-controllers-6bcc47d5c8-wsj8k       1/1     Running            12         22h
calico-node-mlpt9                              1/1     Running            2          22h
coredns-647d4f64c4-b25kx                       0/1     Running            0          4m6s
dns-autoscaler-77486c4479-lhzh5                1/1     Running            0          22h
kube-apiserver-ks-allinone                     1/1     Running            12         22h
kube-controller-manager-ks-allinone            1/1     Running            0          22h
kube-proxy-lv9xp                               1/1     Running            0          22h
kube-scheduler-ks-allinone                     1/1     Running            0          22h
nodelocaldns-d2xmf                             1/1     Running            0          22h
openebs-localpv-provisioner-7b55587dbd-8gggm   0/1     CrashLoopBackOff   8          22h
openebs-ndm-475z4                              1/1     Running            2          22h
openebs-ndm-operator-69cbc86975-9stlb          0/1     CrashLoopBackOff   8          22h
tiller-deploy-55fc49c595-tzdk2                 1/1     Running            0          22h

**Comment by yingmingzongyu** [comment]
我也碰到同样问题，
[root@ks-allinone logs]# kubectl get pod -n kube-system
NAME                                           READY   STATUS             RESTARTS   AGE
calico-kube-controllers-6d94847b5-qwjws        1/1     Running            6          4h14m
calico-node-gxg4c                              1/1     Running            6          4h14m
coredns-647d4f64c4-qd85s                       0/1     Running            1          26m
dns-autoscaler-77486c4479-6kdq9                1/1     Running            5          4h13m
kube-apiserver-ks-allinone                     1/1     Running            23         4h15m
kube-controller-manager-ks-allinone            1/1     Running            5          4h15m
kube-proxy-zg9gb                               1/1     Running            5          4h15m
kube-scheduler-ks-allinone                     1/1     Running            5          4h15m
nodelocaldns-llgdj                             1/1     Running            5          4h13m
openebs-localpv-provisioner-7b55587dbd-nnzm8   0/1     CrashLoopBackOff   53         4h10m
openebs-ndm-ktv6w                              1/1     Running            8          4h10m
openebs-ndm-operator-69cbc86975-fp58r          0/1     CrashLoopBackOff   53         4h10m
tiller-deploy-55fc49c595-8b59h                 1/1     Running            5          4h13m

**Comment by yingmingzongyu** [comment]
我也碰到类似问题。
[root@ks-allinone logs]# kubectl get pod -n kube-system
NAME                                           READY   STATUS             RESTARTS   AGE
calico-kube-controllers-6d94847b5-qwjws        1/1     Running            6          4h14m
calico-node-gxg4c                              1/1     Running            6          4h14m
coredns-647d4f64c4-qd85s                       0/1     Running            1          26m
dns-autoscaler-77486c4479-6kdq9                1/1     Running            5          4h13m
kube-apiserver-ks-allinone                     1/1     Running            23         4h15m
kube-controller-manager-ks-allinone            1/1     Running            5          4h15m
kube-proxy-zg9gb                               1/1     Running            5          4h15m
kube-scheduler-ks-allinone                     1/1     Running            5          4h15m
nodelocaldns-llgdj                             1/1     Running            5          4h13m
openebs-localpv-provisioner-7b55587dbd-nnzm8   0/1     CrashLoopBackOff   53         4h10m
openebs-ndm-ktv6w                              1/1     Running            8          4h10m
openebs-ndm-operator-69cbc86975-fp58r          0/1     CrashLoopBackOff   53         4h10m
tiller-deploy-55fc49c595-8b59h                 1/1     Running            5          4h13m

**Comment by pixiake** [comment]
可以kubectl  logs  看下这两个pod 日志

**Comment by FeynmanZhou** [comment]
openebs 没有起来，kubectl describe 和 logs 看看这两个异常 pod ？

**Comment by tian007-lu** [comment]
防火墙的原因，我在centos上安装的时候也遇到了，最后关闭了防火墙就好了。
systemctl stop firewalld.service

**Comment by tian007-lu** [comment]
[root@localhost scripts]# kubectl logs openebs-ndm-operator-59c75c96fc-j2xcx -n kube-system
{"level":"info","ts":1591008076.330904,"logger":"ndm-operator","msg":"Go Version: go1.12.7"}
{"level":"info","ts":1591008076.330986,"logger":"ndm-operator","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1591008076.3310008,"logger":"ndm-operator","msg":"operator-sdk Version: v0.5.0"}
{"level":"info","ts":1591008076.3314772,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1591008076.4110398,"logger":"leader","msg":"No pre-existing lock was found."}
{"level":"info","ts":1591008076.4164941,"logger":"leader","msg":"Became the leader."}
{"level":"info","ts":1591008076.4638371,"logger":"ndm-operator","msg":"Installing the components"}
{"level":"info","ts":1591008088.4919488,"logger":"ndm-operator","msg":"Registering Components"}
{"level":"info","ts":1591008088.5542057,"logger":"ndm-operator","msg":"Check if CR has to be upgraded, and perform upgrade"}
{"level":"info","ts":1591008088.5593307,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"blockdevice-controller","source":"kind source: /, Kind="}
{"level":"error","ts":1591008088.5594614,"logger":"kubebuilder.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"BlockDevice.openebs.io","error":"no matches for kind \"BlockDevice\" in version \"openebs.io/v1alpha1\"","stacktrace":"github.com/openebs/node-disk-manager/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/openebs/node-disk-manager/vendor/sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go:89\ngithub.com/openebs/node-disk-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Watch\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:122\ngithub.com/openebs/node-disk-manager/pkg/controller/blockdevice.add\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/pkg/controller/blockdevice/blockdevice_controller.go:72\ngithub.com/openebs/node-disk-manager/pkg/controller/blockdevice.Add\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/pkg/controller/blockdevice/blockdevice_controller.go:55\ngithub.com/openebs/node-disk-manager/pkg/controller.AddToManager\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/pkg/controller/controller.go:29\nmain.main\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/cmd/manager/main.go:135\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/runtime/proc.go:200"}
{"level":"error","ts":1591008088.5596054,"logger":"ndm-operator","msg":"","error":"no matches for kind \"BlockDevice\" in version \"openebs.io/v1alpha1\"","stacktrace":"github.com/openebs/node-disk-manager/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/vendor/github.com/go-logr/zapr/zapr.go:128\nmain.main\n\t/home/travis/gopath/src/github.com/openebs/node-disk-manager/cmd/manager/main.go:136\nruntime.main\n\t/home/travis/.gimme/versions/go1.12.7.linux.amd64/src/runtime/proc.go:200"}
[root@localhost scripts]#
