### ISSUE TITLE
我把istio集群2.0的版本卸载了，问下怎么安装

### ISSUE THREAD

**Issue by gongjx11** [kubesphere/kubesphere#1538]
我不小心把istio全部卸载了，问一下怎么安装，如果我使用官方文档去部署，平台操作界面会不会有影响？

**Comment by FeynmanZhou** [comment]
ks 的版本现在是 2.1 吗？

**Comment by gongjx11** [comment]
2.0版本

**Comment by FeynmanZhou** [comment]
2.0 不支持单独装 istio，如果已经在 2.0 环境卸载了内置的 istio，再重装或升级 2.1 都可能有问题。我的建议是 参考 2.1 的安装指南，重新装 2.1，安装前把 istio 开启

**Comment by gongjx11** [comment]
好的 我知道了，谢谢

**Comment by FeynmanZhou** [comment]
@gongjx11 2.1 的 installer 解耦了，可以最小化安装的同时 只开启 istio 的安装，UI 也能支持微服务治理和灰度发布的，仔细看 2.1 的安装说明

**Comment by gongjx11** [comment]
我现在按照官方的例子来装的，装上去了，但是在操作同看不到流量制理，是不是我安装的问题，还是说我新安装的和平台哪个方面配置没有兼容到
![image](https://user-images.githubusercontent.com/21954004/69203547-96faea80-0b7f-11ea-8a65-7ba411a1d94c.png)

![image](https://user-images.githubusercontent.com/21954004/69203565-a4b07000-0b7f-11ea-9fa0-d5c1af733a0b.png)


这里也没有，想问一下这个原因和平台是不是有相关，谢谢

**Comment by FeynmanZhou** [comment]
流量治理和 tracing 都是需要有实时请求的，参考这个跑一遍 https://kubesphere.io/docs/v2.1/zh-CN/quick-start/bookinfo-canary/

**Comment by gongjx11** [comment]
好的 我试一下  非常感谢
