### ISSUE TITLE
redis pending

### ISSUE THREAD

**Issue by chenJz1012** [kubesphere/kubesphere#1539]
![image](https://user-images.githubusercontent.com/11772351/69123048-52b60e80-0adb-11ea-9d3c-c890da2c58d6.png)

pod has unbound immediate PersistentVolumeClaims (repeated 3 times)

**Comment by wansir** [comment]
检查一下pvc 的状态， 和存储配置有关

**Comment by chenJz1012** [comment]
> 检查一下pvc 的状态， 和存储配置有关

是的，解决了！ 感谢，存储使用local 添加pv后解决了
