### ISSUE TITLE
b2i 任务完成后，已完成的pod没有被删除

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1545]
通过构建b2i创建的任务，任务执行结束后，pod也已完成，但是pod没有被删除：
![image](https://user-images.githubusercontent.com/7677050/69131416-53f03700-0aed-11ea-9bd8-fd81718d2583.png)

期望结果：执行完成的pod可以删除

**Comment by soulseen** [comment]
这个是pod由job创建的，是不能自动删的，他记录了构建的日志等信息。构建完成后这个pod不会占用资源，只是作为一个完成记录。

**Comment by mayuhope** [comment]
好的，了解了
