### ISSUE TITLE
文章需要完善的地方

### ISSUE THREAD

**Issue by yongnights** [kubesphere/kubesphere#1548]
文章地址：https://kubesphere.io/docs/v2.1/zh-CN/quick-start/hpa/
在这个文章中，hpa使用的镜像应该是mirrorgooglecontainers/hpa-example，但是文档中给的镜像是mirrorgooglecontainers/hpa，截图中给的镜像是对的，说白了就是文字跟图片上的不匹配

**Comment by zryfish** [comment]
欢迎给文档提PR https://github.com/kubesphere/docs.kubesphere.io

**Comment by FeynmanZhou** [comment]
Fixed, see  https://kubesphere.io/docs/v2.1/zh-CN/quick-start/hpa/
