### ISSUE TITLE
全新安装版本v2.1.0（servicemesh 已开启），部署自制应用时，应用治理选项被禁用

### ISSUE THREAD

**Issue by johntostring** [kubesphere/kubesphere#1549]
**问题描述**
通过 All in one 方式全新安装的 v2.1.0，Pod 全部 Running 无异常。

然后通过 web console 登录 admin 账号，创建一个空间、项目，尝试部署自制应用，出现**应用治理选项被禁用无法选择**。

![image](https://user-images.githubusercontent.com/5723484/69214951-4e552880-0ba3-11ea-89aa-6e647955cf98.png)

![image](https://user-images.githubusercontent.com/5723484/69214918-3c738580-0ba3-11ea-9344-4746ab574fb2.png)

安装前通过修改 config/common.yaml，开启了如下几个选项：
[Gist common.yaml 完整文件](https://gist.github.com/johntostring/7162783f614f624119dca4d0e7eaa771)
```diff
- logging_enabled: false
+ logging_enabled: true
...
- openpitrix_enabled: false
- metrics_server_enabled: false
- servicemesh_enabled: false
- notification_enabled: false
- alerting_enabled: false
+ openpitrix_enabled: true
+ metrics_server_enabled: true
+ servicemesh_enabled: true
+ notification_enabled: true
+ alerting_enabled: true
```

**安装环境的硬件配置**

- VMware虚拟机
![image](https://user-images.githubusercontent.com/5723484/69215377-80b35580-0ba4-11ea-9dea-25f155b9a0f2.png)

- CentOS 7.3
```bash
[root@ks-allinone scripts]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

[root@ks-allinone scripts]# cat /proc/version
Linux version 3.10.0-514.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Nov 22 16:42:41 UTC 2016
```

**错误信息或截图**

**Installer版本**
kubesphere-all-v2.1.0

还需要补充什么信息？

**Comment by FeynmanZhou** [comment]
在项目设置-> 网关设置下开启应用治理

**Comment by johntostring** [comment]
@FeynmanZhou 谢谢！
在项目设置 -> 高级设置然后选择**创建网关**中找到了，不过个人感觉这个设置有点太隐蔽了。

**Comment by FeynmanZhou** [comment]
@Carlosfengv 是不是在有些需要开启应用治理的地方  以文案提示一下

**Comment by Carlosfengv** [comment]
下一版调整一下
