### ISSUE TITLE
2.0 更新到2.1 版本执行报错，麻烦帮忙看一下，谢谢

### ISSUE THREAD

**Issue by gongjx11** [kubesphere/kubesphere#1550]
![image](https://user-images.githubusercontent.com/21954004/69220219-70ed3e80-0baf-11ea-8c6e-8f11d72d8d8e.png)

问下，更新2.1版本这一行报错，问一下是什么原因

**Comment by FeynmanZhou** [comment]
你不是在 2.0 的环境上删掉了 istio 么？删了 istio 直接 upgrade 可能会有问题，建议找一个干净的机器重装 2.1

**Comment by gongjx11** [comment]
是的我删掉了，我想试一下更新，好吧我直接重装系统吧。上面问题解决了，谢谢了
