### ISSUE TITLE
单节点的 安装  devops  一直报错

### ISSUE THREAD

**Issue by whbq** [kubesphere/kubesphere#1552]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**

**安装环境的硬件配置**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
![image](https://user-images.githubusercontent.com/41784434/69221077-616ef500-0bb1-11ea-98fe-2bad0054179a.png)
![image](https://user-images.githubusercontent.com/41784434/69221089-68960300-0bb1-11ea-9fed-80e5c226836b.png)

**Installer版本**

**Comment by whbq** [comment]
我的是阿里云的云服务器

**Comment by zryfish** [comment]
duplicate #1553
