### ISSUE TITLE
安装组件  报 0/1 nodes are available: 1 Insufficient cpu.

### ISSUE THREAD

**Issue by whbq** [kubesphere/kubesphere#1553]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
在安装devops 组件的时间 报0/1 nodes are available: 1 Insufficient cpu.  
**安装环境的硬件配置**
阿里云 2核 8g  40g  云主机
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
0/1 nodes are available: 1 Insufficient cpu.
**Installer版本**
最新版

**Comment by zryfish** [comment]
看下官网的资源配置要求，你的节点资源不足了

**Comment by whbq** [comment]
![image](https://user-images.githubusercontent.com/41784434/69224715-0260ae80-0bb8-11ea-971e-e9be5b0fea03.png)
![image](https://user-images.githubusercontent.com/41784434/69224776-1ad0c900-0bb8-11ea-9580-220bd0012c0e.png)
我看了下，除了磁盘不够，其他都满足的。磁盘也是硬性要求吗？

**Comment by zryfish** [comment]
那是最小安装的，不包含devops，https://kubesphere.com.cn/docs/v2.1/zh-CN/installation/intro/

**Comment by FeynmanZhou** [comment]
你应该要对你的机器 CPU 进行扩容，而不是在 KubeSphere UI 去扩容

**Comment by whbq** [comment]
> 你应该要对你的机器 CPU 进行扩容，而不是在 KubeSphere UI 去扩容
有没有可能降低cpu  要求去完成这个事情。

**Comment by FeynmanZhou** [comment]
暂不支持，新安装组件，是会有更多资源的消耗，如果手动装 jenkins、ES 这些开源的组件 也是会有这么多的资源消耗呀

**Comment by whbq** [comment]
通过修改组件请求的cpu   大小，已经解决问题。

**Comment by hannq** [comment]
> 

老哥 在哪可以改
