### ISSUE TITLE
cannot create log: open /tmp/kube-rbac-proxy.centos01.unknownuser.log.INFO.20191120-101651.6461: permission denied

### ISSUE THREAD

**Issue by huntunshule** [kubesphere/kubesphere#1556]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
![image](https://user-images.githubusercontent.com/52652738/69230803-e44c7b80-0bc2-11ea-93b6-2a30ebc49de9.png)

**安装环境的硬件配置**
kubernetes 安装 kubesphere,本地物理机
安装命令kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/kubesphere-minimal.yaml
没有做过其他更改
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
![image](https://user-images.githubusercontent.com/52652738/69231050-6046c380-0bc3-11ea-9ea8-7a859b36759d.png)
![image](https://user-images.githubusercontent.com/52652738/69231073-69379500-0bc3-11ea-871a-a89b05fa3841.png)
![image](https://user-images.githubusercontent.com/52652738/69231090-72286680-0bc3-11ea-903c-5b2ab83ef335.png)

**Installer版本**
2.1.0

**Comment by klj890** [comment]
可以参考 https://github.com/brancz/kube-rbac-proxy/issues/54
