### ISSUE TITLE
安装完成后显示成功、但是打开应用商店提示表结构不存在

### ISSUE THREAD

**Issue by mqmjingba** [kubesphere/kubesphere#1557]
安装完成后显示成功、但是打开应用商店提示表结构不存在
系统为纯净版Ubuntu 16.0.4.5、4C8G，按照官方手册进行安装，提示信息如下图所示
![图片](https://user-images.githubusercontent.com/5761267/69302729-8f0d7a00-0c55-11ea-98e8-73230debf4c3.png)
![图片](https://user-images.githubusercontent.com/5761267/69302754-a77d9480-0c55-11ea-95ee-a42975164579.png)
![image](https://user-images.githubusercontent.com/40452856/69303310-66867f80-0c57-11ea-8b5c-c67eaaccdd1c.png)

**Comment by zryfish** [comment]
重新执行下openpitrix-syste下的job

**Comment by pengcong06** [comment]
job执行失败,用下面的脚本重新跑一下
`kubectl get job openpitrix-db-init-job -n openpitrix-systm -o json | jq 'del(.spec.selector)' | jq 'del(.spec.template.metadata.labels)' | kubectl replace --force -f -`

**Comment by mqmjingba** [comment]
![图片](https://user-images.githubusercontent.com/5761267/69315222-fbe23d80-0c70-11ea-8e44-483372f4efc5.png) 执行了有下面这个结果openpitrix-systm这个是不是openpitrix-system？
@pengcong06

**Comment by pengcong06** [comment]
> ![图片](https://user-images.githubusercontent.com/5761267/69315222-fbe23d80-0c70-11ea-8e44-483372f4efc5.png) 执行了有下面这个结果openpitrix-systm这个是不是openpitrix-system？
> @pengcong06

是的,更正过来了

**Comment by mqmjingba** [comment]
> > ![图片](https://user-images.githubusercontent.com/5761267/69315222-fbe23d80-0c70-11ea-8e44-483372f4efc5.png) 执行了有下面这个结果openpitrix-systm这个是不是openpitrix-system？
> > @pengcong06
> 
> 是的,更正过来了

按照这个命令执行了，显示了那两行，但是应用商店里面还没有东西

**Comment by mqmjingba** [comment]
> 重新执行下openpitrix-system下的job

![图片](https://user-images.githubusercontent.com/5761267/69317804-b9bbfa80-0c76-11ea-8231-c34b9e558ba9.png)
是执行这个吗？

**Comment by zryfish** [comment]
对

**Comment by mqmjingba** [comment]
> 对

执行了，还是没啥用，商城里面还是没东西

**Comment by mqmjingba** [comment]
> 对

奇怪的是半小时后好了，全部OK了

**Comment by zryfish** [comment]
/close
due to inactivity and issue already fixed
