### ISSUE TITLE
What is the password of offline installer？

### ISSUE THREAD

**Issue by lujs678** [kubesphere/kubesphere#156]
https://drive.yunify.com/s/DZ8FAIEaKfU98JT/authenticate

$ curl -O -k https://139.198.5.33/kubesphere/express/offline/Ubuntu/kubesphere-all-offline-express-1.0.0-alpha_amd64.tar.gz -u kubesphere

This two urls all need password

**Comment by mysugar** [comment]
i need it too.

**Comment by rayzhou2017** [comment]
Kubesphere@666
