### ISSUE TITLE
Kubesphere2.1.0 的 devops流水线列表页面 无法正常展示

### ISSUE THREAD

**Issue by geniussheep** [kubesphere/kubesphere#1562]
![image](https://user-images.githubusercontent.com/7587017/69328065-8898f580-0c89-11ea-8460-5310641842da.png)

上图错误：目前无法重现

经排查：
发现该错误是 ks-apiserver抛出的 日志如下：
`E1121 09:45:19.025588       1 devops.go:1077] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/organizations/jenkins/pipelines/project-XX2QnMAPrEwk/pipelines/dbms/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:45:19.025690       1 devops.go:55] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/organizations/jenkins/pipelines/project-XX2QnMAPrEwk/pipelines/dbms/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:45:19.025711       1 devops.go:640] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/organizations/jenkins/pipelines/project-XX2QnMAPrEwk/pipelines/dbms/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:45:29.984611       1 devops.go:1077] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/organizations/jenkins/pipelines/project-XX2QnMAPrEwk/pipelines/dbms/runs/67/nodes/?limit=10000: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:45:29.984667       1 devops.go:851] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/organizations/jenkins/pipelines/project-XX2QnMAPrEwk/pipelines/dbms/runs/67/nodes/?limit=10000: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:45:29.984684       1 devops.go:1013] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/organizations/jenkins/pipelines/project-XX2QnMAPrEwk/pipelines/dbms/runs/67/nodes/?limit=10000: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:45:29.984694       1 devops.go:640] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/organizations/jenkins/pipelines/project-XX2QnMAPrEwk/pipelines/dbms/runs/67/nodes/?limit=10000: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:45:35.818405       1 devops.go:1077] Post http://ks-jenkins.kubesphere-devops-system.svc/pipeline-model-converter/toJson: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:45:35.818495       1 devops.go:919] Post http://ks-jenkins.kubesphere-devops-system.svc/pipeline-model-converter/toJson: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:45:35.818512       1 devops.go:640] Post http://ks-jenkins.kubesphere-devops-system.svc/pipeline-model-converter/toJson: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:46:36.891626       1 devops.go:1077] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/organizations/jenkins/pipelines/project-XX2QnMAPrEwk/pipelines/dbms/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:46:36.891697       1 devops.go:55] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/organizations/jenkins/pipelines/project-XX2QnMAPrEwk/pipelines/dbms/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:46:36.891713       1 devops.go:640] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/organizations/jenkins/pipelines/project-XX2QnMAPrEwk/pipelines/dbms/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:47:09.737931       1 project_pipeline_handler.go:187] Get http://ks-jenkins.kubesphere-devops-system.svc/job/project-51LqkJ8Wqqmv/job/msite/config.xml/: read tcp 10.233.104.115:46916->10.233.24.225:80: read: connection reset by peer
E1121 09:47:09.738079       1 project_pipeline.go:128] [ServiceError:500] Get http://ks-jenkins.kubesphere-devops-system.svc/job/project-51LqkJ8Wqqmv/job/msite/config.xml/: read tcp 10.233.104.115:46916->10.233.24.225:80: read: connection reset by peer
E1121 09:47:33.289793       1 project_pipeline_handler.go:187] Get http://ks-jenkins.kubesphere-devops-system.svc/job/project-51LqkJ8Wqqmv/job/msite/config.xml/: read tcp 10.233.104.115:47498->10.233.24.225:80: read: connection reset by peer
E1121 09:47:33.289880       1 project_pipeline.go:128] [ServiceError:500] Get http://ks-jenkins.kubesphere-devops-system.svc/job/project-51LqkJ8Wqqmv/job/msite/config.xml/: read tcp 10.233.104.115:47498->10.233.24.225:80: read: connection reset by peer
E1121 09:47:40.790197       1 devops.go:1077] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/search/?q=type:pipeline;organization:jenkins;pipeline:project-XX2QnMAPrEwk%2F*;excludedFromFlattening:jenkins.branch.MultiBranchProject,hudson.matrix.MatrixProject&filter=no-folders&start=0&limit=10: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:47:40.790238       1 devops.go:72] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/search/?q=type:pipeline;organization:jenkins;pipeline:project-XX2QnMAPrEwk%2F*;excludedFromFlattening:jenkins.branch.MultiBranchProject,hudson.matrix.MatrixProject&filter=no-folders&start=0&limit=10: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:47:40.791220       1 devops.go:640] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/search/?q=type:pipeline;organization:jenkins;pipeline:project-XX2QnMAPrEwk%2F*;excludedFromFlattening:jenkins.branch.MultiBranchProject,hudson.matrix.MatrixProject&filter=no-folders&start=0&limit=10: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:48:09.641867       1 project_pipeline_handler.go:187] Get http://ks-jenkins.kubesphere-devops-system.svc/job/project-51LqkJ8Wqqmv/job/msite/config.xml/: read tcp 10.233.104.115:48378->10.233.24.225:80: read: connection reset by peer
E1121 09:48:09.641967       1 project_pipeline.go:128] [ServiceError:500] Get http://ks-jenkins.kubesphere-devops-system.svc/job/project-51LqkJ8Wqqmv/job/msite/config.xml/: read tcp 10.233.104.115:48378->10.233.24.225:80: read: connection reset by peer
E1121 09:49:09.673941       1 project_pipeline_handler.go:187] Get http://ks-jenkins.kubesphere-devops-system.svc/job/project-51LqkJ8Wqqmv/job/msite/config.xml/: read tcp 10.233.104.115:49802->10.233.24.225:80: read: connection reset by peer
E1121 09:49:09.674001       1 project_pipeline.go:128] [ServiceError:500] Get http://ks-jenkins.kubesphere-devops-system.svc/job/project-51LqkJ8Wqqmv/job/msite/config.xml/: read tcp 10.233.104.115:49802->10.233.24.225:80: read: connection reset by peer
E1121 09:51:10.021460       1 devops.go:1077] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/search/?q=type:pipeline;organization:jenkins;pipeline:project-XX2QnMAPrEwk%2F*;excludedFromFlattening:jenkins.branch.MultiBranchProject,hudson.matrix.MatrixProject&filter=no-folders&start=0&limit=10: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:51:10.021524       1 devops.go:72] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/search/?q=type:pipeline;organization:jenkins;pipeline:project-XX2QnMAPrEwk%2F*;excludedFromFlattening:jenkins.branch.MultiBranchProject,hudson.matrix.MatrixProject&filter=no-folders&start=0&limit=10: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:51:10.021545       1 devops.go:640] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/search/?q=type:pipeline;organization:jenkins;pipeline:project-XX2QnMAPrEwk%2F*;excludedFromFlattening:jenkins.branch.MultiBranchProject,hudson.matrix.MatrixProject&filter=no-folders&start=0&limit=10: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:55:30.749975       1 devops.go:1077] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/search/?q=type:pipeline;organization:jenkins;pipeline:project-51LqkJ8Wqqmv%2F*;excludedFromFlattening:jenkins.branch.MultiBranchProject,hudson.matrix.MatrixProject&filter=no-folders&start=0&limit=10: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:55:30.750015       1 devops.go:72] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/search/?q=type:pipeline;organization:jenkins;pipeline:project-51LqkJ8Wqqmv%2F*;excludedFromFlattening:jenkins.branch.MultiBranchProject,hudson.matrix.MatrixProject&filter=no-folders&start=0&limit=10: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:55:30.750027       1 devops.go:640] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/search/?q=type:pipeline;organization:jenkins;pipeline:project-51LqkJ8Wqqmv%2F*;excludedFromFlattening:jenkins.branch.MultiBranchProject,hudson.matrix.MatrixProject&filter=no-folders&start=0&limit=10: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 09:59:45.531715       1 resources.go:154] namespaced resource ingress not found
E1121 09:59:45.531758       1 applications.go:309] namespaced resource ingress not found
E1121 10:05:21.145812       1 devops.go:1077] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/search/?q=type:pipeline;organization:jenkins;pipeline:project-XX2QnMAPrEwk%2F*;excludedFromFlattening:jenkins.branch.MultiBranchProject,hudson.matrix.MatrixProject&filter=no-folders&start=0&limit=10: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 10:05:21.145860       1 devops.go:72] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/search/?q=type:pipeline;organization:jenkins;pipeline:project-XX2QnMAPrEwk%2F*;excludedFromFlattening:jenkins.branch.MultiBranchProject,hudson.matrix.MatrixProject&filter=no-folders&start=0&limit=10: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1121 10:05:21.145885       1 devops.go:640] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/search/?q=type:pipeline;organization:jenkins;pipeline:project-XX2QnMAPrEwk%2F*;excludedFromFlattening:jenkins.branch.MultiBranchProject,hudson.matrix.MatrixProject&filter=no-folders&start=0&limit=10: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
error: unexpected EOF`

在错误日志中 还发现有 如下错误：
`E1121 09:49:09.674001       1 project_pipeline.go:128] [ServiceError:500] Get http://ks-jenkins.kubesphere-devops-system.svc/job/project-51LqkJ8Wqqmv/job/msite/config.xml/: read tcp 10.233.104.115:49802->10.233.24.225:80: read: connection reset by peer
`
上述 connection reset by peer我们在使用KubeSphere2.0.2时，也是发现其频繁曝出；最后我们把 KubeSphere2.0.2内的calico版本 从3.1.3升级到3.8后 得以解决。
但是 在KubeSphere2.1升级后 发现 calico版本 从3.8 降级到 3.7.3
故不知道是不是  上述所有在ks-apiserver中的错误都是calico的bug导致的

**Comment by runzexia** [comment]
/cc @magicsong @zheng1 
我上去看了下，ks apiserver 和 jenkins 是没有问题的。
怀疑是calico版本调整造成的网络问题

**Comment by geniussheep** [comment]
我们将calico升级到可 3.8.4但是依然还有 devops页面流水线页面、活动页面那块依然数据展示不出来，然后会曝出timeout异常
![image](https://user-images.githubusercontent.com/7587017/69596051-49c5bf80-103c-11ea-8332-26b0f5dcd779.png)
在api-server日志里 会有各种超时日志
`E1126 03:02:10.032712       1 devops.go:1077] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/organizations/jenkins/pipelines/project-XX2QnMAPrEwk/pipelines/dbms/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1126 03:02:10.032787       1 devops.go:55] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/organizations/jenkins/pipelines/project-XX2QnMAPrEwk/pipelines/dbms/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1126 03:02:10.032799       1 devops.go:640] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/organizations/jenkins/pipelines/project-XX2QnMAPrEwk/pipelines/dbms/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1126 03:02:13.341084       1 devops.go:1077] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/organizations/jenkins/pipelines/project-XX2QnMAPrEwk/pipelines/dbms/runs/?start=0&limit=30: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1126 03:02:13.341147       1 devops.go:161] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/organizations/jenkins/pipelines/project-XX2QnMAPrEwk/pipelines/dbms/runs/?start=0&limit=30: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1126 03:02:13.341170       1 devops.go:640] Get http://ks-jenkins.kubesphere-devops-system.svc/blue/rest/organizations/jenkins/pipelines/project-XX2QnMAPrEwk/pipelines/dbms/runs/?start=0&limit=30: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1126 03:02:14.697894       1 project_pipeline_handler.go:239] Get http://ks-jenkins.kubesphere-devops-system.svc/job/project-XX2QnMAPrEwk/job/dbms/16/api/json?depth=1: read tcp 10.233.104.115:33102->10.233.24.225:80: read: connection reset by peer
E1126 03:02:14.697951       1 project_pipeline.go:149] [ServiceError:500] Get http://ks-jenkins.kubesphere-devops-system.svc/job/project-XX2QnMAPrEwk/job/dbms/16/api/json?depth=1: read tcp 10.233.104.115:33102->10.233.24.225:80: read: connection reset by peer
E1126 03:02:15.026669       1 devops.go:1077] Post http://ks-jenkins.kubesphere-devops-system.svc/pipeline-model-converter/toJson: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1126 03:02:15.026755       1 devops.go:919] Post http://ks-jenkins.kubesphere-devops-system.svc/pipeline-model-converter/toJson: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
E1126 03:02:15.026766       1 devops.go:640] Post http://ks-jenkins.kubesphere-devops-system.svc/pipeline-model-converter/toJson: net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

**Comment by magicsong** [comment]
有相关的环境可以看一下吗？

**Comment by geniussheep** [comment]
今天又复现了   你们有人需要上来看吗？加我微信:liangtouyang

**Comment by FeynmanZhou** [comment]
@geniussheep 可以把远程连接 kubesphere@yunify.com

**Comment by geniussheep** [comment]
邮件发啦，请查收

**Comment by magicsong** [comment]
@geniussheep 你的pipeline jenkinsfile大小如何？是否有一些大的jenkinsfile

**Comment by geniussheep** [comment]
没有呀 我现在的jenkins pipeline  都是用的  share library

**Comment by magicsong** [comment]
能看一下你们的jenkinfile的大小吗

**Comment by geniussheep** [comment]
可以呀

**Comment by geniussheep** [comment]
![image](https://user-images.githubusercontent.com/7587017/69793729-fc944a00-1203-11ea-80c0-9ebc67eaec44.png)

**Comment by geniussheep** [comment]
就这两个
