### ISSUE TITLE
Kubesphere2.1.0 的 devops流水线详情页面 无法正常展示

### ISSUE THREAD

**Issue by geniussheep** [kubesphere/kubesphere#1563]
![image](https://user-images.githubusercontent.com/7587017/69329066-512b4880-0c8b-11ea-821f-a00f829d2dfd.png)
上图错误：目前无法重现
经排查 在ks-apiserver日志内发现相关错误日志，日志如下：
[log.txt](https://github.com/kubesphere/kubesphere/files/3874167/log.txt)

**Comment by runzexia** [comment]
ref https://github.com/kubesphere/kubesphere/issues/1562
/close
