### ISSUE TITLE
helm应用部署后删除再部署时报名称已存在

### ISSUE THREAD

**Issue by ethanxzw** [kubesphere/kubesphere#1564]
helm应用部署后删除再部署时报名称已存在。
![image](https://user-images.githubusercontent.com/41108414/69333043-e7af3800-0c92-11ea-9d4c-aae8ac74c0bc.png)
![image](https://user-images.githubusercontent.com/41108414/69333059-ee3daf80-0c92-11ea-9fe5-6e714ee3bbbc.png)

**Comment by ethanxzw** [comment]
后台用helm list --all查看，发现之前删除的应用还在且状态为DELETE
![image](https://user-images.githubusercontent.com/41108414/69389395-d9026880-0d06-11ea-9411-d3776e86ac4d.png)

**Comment by wansir** [comment]
https://github.com/kubesphere/kubesphere/issues/1606
https://github.com/kubesphere/kubesphere/issues/1559

/assign @pengcong06

**Comment by zheng1** [comment]
Fixed in 2.1.1

/close
