### ISSUE TITLE
2.0.2 升级2.1 出现coredns 配置丢失

### ISSUE THREAD

**Issue by hewenhong** [kubesphere/kubesphere#1568]
**问题描述**
从2.0.2 离线版升级 2.1 离线版 后，出现coredns 配置丢失。

**安装环境的硬件配置**
easystack  云主机

**Installer版本**
2.0.2 >> 2.1

**Comment by pixiake** [comment]
目前升级会默认还原系统组件配置，后续版本中会增加配置备份，如有其他需要备份的配置也请提供

**Comment by hewenhong** [comment]
另外升级的2.0.2 升级的时候请关注helm repo ，原来有的仓库也被清空了。

**Comment by dpp814** [comment]
> **问题描述**
> 从2.0.2 离线版升级 2.1 离线版 后，出现coredns 配置丢失。
> 
> **安装环境的硬件配置**
> easystack 云主机
> 
> **Installer版本**
> 2.0.2 >> 2.1

兄弟，2.0.2版本的安装包可否发我一个

**Comment by benjaminhuo** [comment]
test case:
1. install 2.0.2 and change coredns config,  install helm chart
2. 2.0.2 => 2.1.1
3. verify if coredns config changes and if the install helm chart is cleared

**Comment by calvinyv** [comment]
as design
/kind documentation
