### ISSUE TITLE
创建存储类型时qingcloud-csi访问模式只有ReadWriteOnce，但是创建完成后yarm里面却有ReadWriteOnce, ReadOnlyMany, ReadWriteMany 三种

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1569]
![image](https://user-images.githubusercontent.com/57089340/69526231-b3928a80-0fa4-11ea-845a-25f6f7dfab4a.png)

PS：ceph也有这个问题

**Comment by rayzhou2017** [comment]
Need to verify on v3.0

**Comment by zryfish** [comment]
/close  
due to inactivity and issue already fixed and verified
