### ISSUE TITLE
Local Volume Create is waiting

### ISSUE THREAD

**Issue by xewn** [kubesphere/kubesphere#1572]
我使用的v2.1.0版本
**Describe the bug(描述下问题)**
安装成功后，第一个项目是没有问题的，可以正常运行。
创建第二个项目的时候，添加新的存储卷，本地的。
状态一直显示等待中，大概一小时了，也还是等待中，我重启服务器后，也还是等待中

电脑配置是thinkpad 4核16G，ssd 240G，centos7.5

**Comment by Forest-L** [comment]
1、可以到服务器上，检查下cpu和磁盘的使用情况；
2、kubectl get pvc --all-namespaces   看下

**Comment by xewn** [comment]
好的

**Comment by xewn** [comment]
有两个显示不一样的。一个是pending，一个是lost(这个被我修改过多次yaml配置文件)，分配的空间都是0

**Comment by xewn** [comment]
有两个显示不一样的。一个是pending，一个是lost(这个被我修改过多次yaml配置文件)，分配的空间都是0
rootmodel                      rootmodelpv                                        Pending   pvc-9e0f5d32-a0cf-4247-ac9d-f476adb7y43a   0                         local          8h
smopng                         smopngpv                                           Lost      pvc-E86B67FF-305B-4AC2-94E6-B653036838EB   0                         local          8h

第二个是我自己修改过配置文件的，GUID也是我手动创建后改了的。

**Comment by xewn** [comment]
@Forest-L    我是240G的固态，是不是硬盘空间不够了？创建存储卷的时候，是如何分配硬盘空间的？我改成2G的存储卷，也是一直等待种。
pvc-e29be34b-f470-4456-9669-61c791786cd1   20Gi       RWO            local          4d5h
prometheus-k8s-system-db-prometheus-k8s-system-0   Bound     pvc-2313ebe6-b240-4170-9c72-3b2120880533   20Gi       RWO            local          4d5h
openldap-pvc-openldap-0                            Bound     pvc-9e0f5d32-a0cf-4247-ac9d-f476adb9a690   2Gi        RWO            local          4d5h
redis-pvc                                          Bound     pvc-2990afd7-0a80-42d7-8ec2-9859b09923ad   2Gi
如何查看创建存储卷的空间还够不够呢？
/dev/mapper/centos-root   50G  9.5G   41G   19% /
/dev/sda1               1014M  229M  786M   23% /boot
/dev/mapper/centos-home  174G   33M  174G    1% /home

**Comment by xewn** [comment]
这个是机器人回复的，官方出来回复一下呢？

**Comment by FeynmanZhou** [comment]
Has your local PVC been mounted to a Pod?
