### ISSUE TITLE
流水线构建完成后邮件通知报错

### ISSUE THREAD

**Issue by tzghost** [kubesphere/kubesphere#1575]
邮件服务器配置正常，测试发送邮件成功，但流水线发布时使用邮件通知报错，提示Unknown SMTP host: mail.example.com，这个问题怎么处理？在哪里修改？
![image](https://user-images.githubusercontent.com/17000535/69506537-0864df80-0f6a-11ea-9b75-5078def78ed7.png)
![image](https://user-images.githubusercontent.com/17000535/69506541-0b5fd000-0f6a-11ea-8c4f-e3035197025d.png)
![image](https://user-images.githubusercontent.com/17000535/69506546-0f8bed80-0f6a-11ea-8778-2d410c6aa87e.png)

**Comment by soulseen** [comment]
可以参考下文档
https://kubesphere.io/docs/v2.1/zh-CN/devops/jenkins-setting/#%E4%BF%AE%E6%94%B9-jenkins-%E9%82%AE%E4%BB%B6%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AE%BE%E7%BD%AE

**Comment by tzghost** [comment]
解决了，原来是使用jenkins通知的

**Comment by soulseen** [comment]
嗯，后续会计划改进。https://github.com/kubesphere/kubesphere/issues/1426
/close

**Comment by soulseen** [comment]
/close
prow is back😄
