### ISSUE TITLE
当有存储卷使用了存储类型时，删除存储类型没有提示

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1579]
![image](https://user-images.githubusercontent.com/57089340/69704575-a903fc80-112e-11ea-802c-c14a8ac36f0b.png)

管理员可以随便删除存储类型，也不管有没有存储卷在用这个存储类型，也没有提示说有存储卷在用

**Comment by xewn** [comment]
你这个，我们都可以访问嗯。
SMTP配置，咋个还把密码也返回来了？
<input name="password" type="password" id="password" class="input is-default" value="P@ssw0rd">

**Comment by xewn** [comment]
input name="password" type="password" id="password" class="input is-default" value="P@ssw0rd"

**Comment by ellaye** [comment]
fixed
/close
