### ISSUE TITLE
存储卷列表部分异常没有显示在前端

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1581]
![image](https://user-images.githubusercontent.com/57089340/69531204-6d422900-0fae-11ea-9ccf-f9c9088c8b2b.png)

![image](https://user-images.githubusercontent.com/57089340/69531229-7af7ae80-0fae-11ea-9685-778349511ec9.png)

**Comment by wnxn** [comment]
这个在 2.1.1 后端要设计一下。

**Comment by wnxn** [comment]
@justahole 2.1.1 先在前端修复一下，把这个异常 event 处理下。

**Comment by wnxn** [comment]
列表页警告从资源 status 而来，event 有警告时资源 status 不一定会警告，所以这里前端处理没问题。
NFS 没扩容功能，为了避免出现这个警告，3.0.0 统一存储管理会在后端开发。
