### ISSUE TITLE
存储卷列表中状态查询条件不生效

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1582]
存储列表中有准备就绪和等待中的存储卷
查询条件状态选择等待中，查询出来没有数据
![image](https://user-images.githubusercontent.com/57089340/69608243-f5cdd180-1061-11ea-848d-f37ff76c9d36.png)

![image](https://user-images.githubusercontent.com/57089340/69608253-fbc3b280-1061-11ea-80b9-11dedbe0eafd.png)

**Comment by xewn** [comment]
这个等待中的存储卷，是不是提示下，为啥一直处于等待呢？
我创建了几次，一直是等待中，就是不成功。也不懂为什么等待。

**Comment by ellaye** [comment]
fixed
