### ISSUE TITLE
平台组件收录日志问题---中文日志不收录

### ISSUE THREAD

**Issue by whbq** [kubesphere/kubesphere#1584]
**General remarks**

> Please delete this section including header before submitting
> 也可以使用中文
>平台组件收录日志问题---中文日志不收录
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug(描述下问题)**
在使用日志组件的过程中，日志带有中文字符，不会显示
For UI issues please also add a screenshot that shows the issue.

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 
64c 512g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**

**Expected behavior(预期行为)**

**Comment by huanggze** [comment]
请问使用的 KubeSphere 哪个版本？

**Comment by huanggze** [comment]
I think we can close the issue.

Please refer to KubeSphere 2.1.0 release note https://kubesphere.com.cn/docs/v2.1/zh-CN/release/release-v210/
