### ISSUE TITLE
kubesphere 安装

### ISSUE THREAD

**Issue by zops** [kubesphere/kubesphere#1585]
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/kubesphere-minimal.yaml

在现有K8s集群安装kubesphere，需要先执行上面命令安装初始化容器，此容器会自动执行ansible安装各种组件。

想咨询，如果我要卸载kubesphere时，通过什么方式卸载呢？

**Comment by huanglei288766** [comment]
also need uninstall guides.
