### ISSUE TITLE
kubesphere 2.1 工作负载副本显示一个，但在容器组里显示为2个。

### ISSUE THREAD

**Issue by hewenhong** [kubesphere/kubesphere#1592]
**Describe the bug(描述下问题)**
新建部署，在部署下看到一个容器组，但在容器组中可以看到两个容器组，删除其中一个，会重新建立。
![image](https://user-images.githubusercontent.com/8400716/69688563-62e47400-1101-11ea-9518-700ad385254d.png)

![image](https://user-images.githubusercontent.com/8400716/69688596-7db6e880-1101-11ea-9841-2a901af78bd6.png)

![image](https://user-images.githubusercontent.com/8400716/69688689-b9ea4900-1101-11ea-89a2-7afc1675c37e.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**

How many nodes and their hardware configuration: 
easystack kvm

3 masters:  8cpu/16g
12 nodes: 8cpu/16g

**Comment by wansir** [comment]
https://github.com/kubernetes/kubernetes/issues/24330
https://github.com/kubernetes/kubernetes/issues/41641

看来这个bug依旧存在， 可以清理一下遗留的 replicaset 或是通过限制 revisionHistoryLimit.

**Comment by calvinyv** [comment]
@hewenhong this is bug from K8s, and we will keep watch the update from K8s, if any fix is provided from community, we will integrate it in KubeSphere 2.1.1

@wansir is there any workaround? some double check in ks code to make sure this rs is clear?

**Comment by wansir** [comment]
May be an intermediate state when updating.

**Comment by zryfish** [comment]
/cose 
due to not a bug

**Comment by hewenhong** [comment]
due to not a bug
