### ISSUE TITLE
helm repo 可以增加，但是无法在kubesphere 应用仓库中增加。

### ISSUE THREAD

**Issue by hewenhong** [kubesphere/kubesphere#1594]
**Describe the bug(描述下问题)**
通过helm repo add  可以直接增加helm 仓库，但是同样路径无法在kubesphere 界面中增加。

![image](https://user-images.githubusercontent.com/8400716/69690958-64656a80-1108-11ea-8040-5513191dc56e.png)
![image](https://user-images.githubusercontent.com/8400716/69690975-6fb89600-1108-11ea-8ea7-0e7c26579456.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 
kvm
For example:
3 masters:  8cpu/16g
12 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**

**Expected behavior(预期行为)**

**Comment by pengcong06** [comment]
![Screenshot from 2019-11-27 13-46-17](https://user-images.githubusercontent.com/5153147/69697072-8cf75f80-111c-11ea-9f38-c79625f607f5.png)

**Comment by calvinyv** [comment]
@hewenhong go ahead to communicate with pengcong directly and provide your env

**Comment by hewenhong** [comment]
> ead to communicate with pengcong directly and provide your env

@calvinyv 这个很奇怪的现象就在这里，我在所有的node和master 上都可以通过helm repo add 增加，但是界面就是增加不了。

**Comment by hewenhong** [comment]
@pengcong06 已经提供日志，如果需要其他日志，请联系我。

**Comment by hewenhong** [comment]
已经找到问题，原因是客户dns 解析问题。此issue 关闭，多谢。

**Comment by calvinyv** [comment]
@hewenhong 要是有借鉴意义的经验，建议在此处分享出来

**Comment by hewenhong** [comment]
> 鉴意义的经验，建议在此处分享出来
@calvinyv 

恩，原虚拟机上的dns  是不能解析到外网的，修改了vm 中的虚拟机中的dns ，但是没有重启coredns 和nodelocaldns 造成pod 还是无法解析到外网。

解决方法：修改虚拟机上的dns ，需要重启下 coredns和nodelocaldns 重新载入虚拟机上的dns，才能生效了。
