### ISSUE TITLE
创建项目设置了配额，创建完成后发现配额变成了无限制

### ISSUE THREAD

**Issue by hewenhong** [kubesphere/kubesphere#1595]
**Describe the bug(描述下问题)**
创建项目时设置项目配额为4core cpu， 8000Mi 内存。
创建项目完成，查看项目，发现项目的配额变成了无限制。

![image](https://user-images.githubusercontent.com/8400716/69691239-7398e800-1109-11ea-9459-93759466601e.png)
![image](https://user-images.githubusercontent.com/8400716/69691257-7f84aa00-1109-11ea-985a-fb189c641050.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
3 masters:  8cpu/16g
12 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**
查看问题步骤

**Expected behavior(预期行为)**
项目配额出现无限制

**Comment by zryfish** [comment]
创建项目时设置的不是项目配额，是默认的工作负载配额，上面文字提示有。项目配额是在项目的高级设置中单独设置。这两个不一样

**Comment by hewenhong** [comment]
> 创建项目时设置的不是项目配额，是默认的工作负载配额，上面文字提示有。项目配额是在项目的高级设置中单独设置。这两个不一样

ok，这个很容易产生误解，建议从界面上做修改。以免造成误解。

**Comment by calvinyv** [comment]
/assign @leoendless @Carlosfengv 
/kind bug
/area console
maybe we should remove the text '配额' from the page title

**Comment by leoendless** [comment]
@wansir 这里可以将项目资源的默认 limitrange 创建移到 controller 里面完成吗。
@Carlosfengv UI 上项目创建就不显示这个设置了，只在项目基本信息里提供修改方式。

**Comment by leoendless** [comment]
3.0.0 这里将简化
