### ISSUE TITLE
kubesphere 创建svc 后指定工作负载，前端加载问题

### ISSUE THREAD

**Issue by hewenhong** [kubesphere/kubesphere#1596]
**Describe the bug(描述下问题)**
创建service 后进行指定工作负载，当工作负载较多的情况，前端需要通过加载，并且加载窗口会消失
![image](https://user-images.githubusercontent.com/8400716/69692419-f0799100-110c-11ea-8f0d-443e9d4a6f6d.png)
![image](https://user-images.githubusercontent.com/8400716/69692431-fa02f900-110c-11ea-9f01-e8da88ff5a33.png)

2.0.2 窗口下有搜索，为啥升级到2.1 界面反而没有了搜索？：
![image](https://user-images.githubusercontent.com/8400716/69692481-2cacf180-110d-11ea-9d66-cb6def5653f5.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**

3 masters:  8cpu/16g
12 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**
创建服务 ===>  自定义创建=== > 指定工作负载 ===> 创建  ====> 选择工作负载

**Expected behavior(预期行为)**
选择工作负载，往下拖，窗口消失，多次打开后，才能看到全部工作负载。

**Comment by leoendless** [comment]
Will be fixed in 2.1.1

**Comment by bmingithub** [comment]
v2.1.1 验证OK
