### ISSUE TITLE
logging模块开启 kibana，无法下载镜像

### ISSUE THREAD

**Issue by Tianny** [kubesphere/kubesphere#1597]
默认是从青云仓库拉去的。导致镜像拉去不了。
![image](https://user-images.githubusercontent.com/11434826/69693517-8662eb00-1110-11ea-921e-f5dc2c494cc7.png)

**Comment by huanggze** [comment]
请尝试 docker.elastic.co/kibana/kibana-oss:6.7.0

**Comment by Tianny** [comment]
> docker.elastic.co/kibana/kibana-oss:6.7.0

直接本机 docker pull 这个镜像吗？还是需要修改对应配置文件，如果需要修改，请告诉下路径。谢谢哈

**Comment by huanggze** [comment]
把 kibana Deployment 的 .spec.template.containers.image 字段修改成上面这个哈。因为qingcloud 的镜像仓库是写到 ks-installer 里了，只有master 分支更新了,2.1.0 release 没有。所以要改 kibana Deployment

**Comment by Tianny** [comment]
> 把 kibana Deployment 的 .spec.template.containers.image 字段修改成上面这个哈。因为qingcloud 的镜像仓库是写到 ks-installer 里了，只有master 分支更新了。2.1.0 release 没有。所以要改 kibana Deployment

谢谢
