### ISSUE TITLE
2.1 版本istio helm 更新后无法注册

### ISSUE THREAD

**Issue by gongjx11** [kubesphere/kubesphere#1599]
2.1 版本 istio helm 更新后pod 无法注册,没有更新前是可以的，部署官方恢度示例也是这样的，无法注册，
请求时流量制理也没有。
![image](https://user-images.githubusercontent.com/21954004/69698259-da290080-111f-11ea-9f87-0ab134b715ef.png)

![image](https://user-images.githubusercontent.com/21954004/69698321-03e22780-1120-11ea-9e2b-fdc7d883218b.png)
下面是流量请求
![image](https://user-images.githubusercontent.com/21954004/69698372-1eb49c00-1120-11ea-9a9e-364cf9cb8de3.png)
![image](https://user-images.githubusercontent.com/21954004/69698420-3724b680-1120-11ea-82ef-7c831a819f84.png)

这个以经弄了好久，一直都是这样的问题，麻烦帮忙看一下这是什么问题？

**Comment by FeynmanZhou** [comment]
论坛已回复
