### ISSUE TITLE
安装devops后界面上面不显示devops

### ISSUE THREAD

**Issue by ftlynx** [kubesphere/kubesphere#1604]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
我用k8s安装最小化版本
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/kubesphere-minimal.yaml
然后编辑configmap
kubectl edit cm -n kubesphere-system ks-installer
将devops 打开
    devops:
      enabled: true
      jenkinsMemoryLim: 2Gi
      jenkinsMemoryReq: 1500Mi
      jenkinsVolumeSize: 8Gi
      jenkinsJavaOpts_Xms: 512m
      jenkinsJavaOpts_Xmx: 512m
      jenkinsJavaOpts_MaxRAM: 2g
      sonarqube:
        enabled: true
我看所有容器都启动起来了，并且看了ks-installer日志未发现出错，但是界面上面没有devops创建的地方呢，请问下是否还需要安装其它组件。

**Comment by FeynmanZhou** [comment]
@ftlynx  如果是在 k8s 安装的，开启 devops 组件创建证书前需要先创建证书，参考 [ks-installer](https://github.com/kubesphere/ks-installer)

**Comment by ftlynx** [comment]
我看了下，只需要这个操作？
$ kubectl create ns kubesphere-system
$ kubectl -n kubesphere-system create secret generic kubesphere-ca  \
--from-file=ca.crt=/etc/kubernetes/pki/ca.crt  \
--from-file=ca.key=/etc/kubernetes/pki/ca.key

上面这步我是执行了的，如果没执行安装的时候会报错。我现在是安装成功了。
etcd的没有创建，我现在创建了，但是还是没有，我看也不是必须的。
是否还差步骤呢？

**Comment by ftlynx** [comment]
![image](https://user-images.githubusercontent.com/9986883/69770516-45c4a980-11c4-11ea-835d-54a04bcd92b6.png)
左边的“devops工程” 一直没有

**Comment by ftlynx** [comment]
![image](https://user-images.githubusercontent.com/9986883/69775014-70b5fa00-11d2-11ea-95a0-eaf307a0b325.png)
还差服务组件吗

**Comment by wansir** [comment]
@ftlynx  system-workspace 是系统保留的，需要新建workspace 创建项目、devops工程

**Comment by ftlynx** [comment]
可以了。。。
但是我怎么能把system-workspace的项目移动到这个空间下面呢？我看编辑功能里面没有移动的说法。

**Comment by ftlynx** [comment]
已找到，修改 namespace的标签就可以了。
