### ISSUE TITLE
删除应用后，新建相同名称应用会报已存在。

### ISSUE THREAD

**Issue by hewenhong** [kubesphere/kubesphere#1606]
**Describe the bug(描述下问题)**
将原有名称为postgresql的应用删除后（因建立版本错误，需重新建立），新建同样名称的postgresql会报已存在，在后台通过helm list -a 查看，实际没有删除。

![image](https://user-images.githubusercontent.com/8400716/69770862-92f54b00-11c5-11ea-8e0a-321c8550842a.png)

![image](https://user-images.githubusercontent.com/8400716/69770848-883ab600-11c5-11ea-8922-479f286827e1.png)

For UI issues please also add a screenshot that shows the issue.

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

3 masters:  8cpu/16g
12 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**
新建应用postgresql，名称：postgresql-app
将应用删除。
重新建立postgresq，名称：postgresql-app 
会报错已存在。

建议删除使用命令：
helm delete --purge postgresql-app -n xxxx
这样才不会残留。

**Expected behavior(预期行为)**

**Comment by zheng1** [comment]
duplicate with https://github.com/kubesphere/kubesphere/issues/1564
/close
