### ISSUE TITLE
安装以后应用商店报错

### ISSUE THREAD

**Issue by lijinbang** [kubesphere/kubesphere#1608]
**General remarks**

> Please delete this section including header before submitting
> 也可以使用中文
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug(描述下问题)**
安装以后打开应用商店报错
![image](https://user-images.githubusercontent.com/18083299/69774723-c1792300-11d1-11ea-8da9-72092dc6ee8c.png)

For UI issues please also add a screenshot that shows the issue.

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: v2.1.0

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

**Comment by wansir** [comment]
可以检查一下openpitrix-system下openpitrix-db-init-job这个job是否完成，或重新执行该job，初始化数据库
```
 kubectl -n openpitrix-system get job openpitrix-db-init-job -o json | jq 'del(.spec.selector)' | jq 'del(.spec.template.metadata.labels)' | kubectl replace --force -f -
```

**Comment by wansir** [comment]
需要检查一下存储卷的读写权限，可能是因为数据无法写入

**Comment by lijinbang** [comment]
检查了一下权限正常

**Comment by lijinbang** [comment]
执行上条代码以后把job删除了然后还是报同样的错误

**Comment by simonxlh** [comment]
请问解决了吗，我执行replace job 之后，报错变成 
```
{
 "message": "rpc error: code = Internal desc = internal error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.102.238.38:9118: i/o timeout\""
}
```
@lijinbang
