### ISSUE TITLE
无法找到openldap-pvc

### ISSUE THREAD

**Issue by guoh1988** [kubesphere/kubesphere#1611]
**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0
Kubernetes: 1.13.7

**To Reproduce(复现步骤)**
1. 选择项目kubesphere-system
2. 选择工作负载，点击有状态副本集
3. 点击openldap，右上角出没有openldap-pvc的报错
![微信图片_20191128144318](https://user-images.githubusercontent.com/28557169/69782982-808f0780-11ed-11ea-929e-27969fa78ef4.jpg)

4.查看后台是有两个openldap的pvc，浏览器版本firefox68.1.0
![微信图片_20191128144326](https://user-images.githubusercontent.com/28557169/69783074-b59b5a00-11ed-11ea-8149-a3b966ef735f.jpg)

**Comment by wansir** [comment]
It's wrong to get pvc name through  `spec.template.spec.volumes[*].persistentVolumeClaim.claimName` field of statefulset

/kind bug
/milestones 2.1.1

/assign @leoendless
