### ISSUE TITLE
kubesphere 界面无法调整istio gateway 的hpa 最小副本

### ISSUE THREAD

**Issue by hewenhong** [kubesphere/kubesphere#1615]
**Describe the bug(描述下问题)**
![image](https://user-images.githubusercontent.com/8400716/69802254-2190b900-1214-11ea-9e4f-c13eaf9817f5.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

3 masters:  8cpu/16g
12 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

需求是需要修改最小副本为2，最大为6，但是在页面上无法修改。

**To Reproduce(复现步骤)**

**Expected behavior(预期行为)**
目前只能通过kubectl 来修改。

**Comment by zryfish** [comment]
内存目标使用量不能是0%，得是正的

**Comment by hewenhong** [comment]
> 内存目标使用量不能是0%，得是正的

不好意思。错了
