### ISSUE TITLE
The value of Local Storage is different with df command

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1616]
![image](https://user-images.githubusercontent.com/57089340/69840229-bab3e400-1295-11ea-83a3-1eb7a4c74419.png)

![image](https://user-images.githubusercontent.com/57089340/69840218-aec82200-1295-11ea-8f50-f384a32f5fdb.png)

![image](https://user-images.githubusercontent.com/57089340/69840250-cef7e100-1295-11ea-9e05-62098398aa9d.png)

**Comment by huanggze** [comment]
df -h 与 df -H 的区别

```
-h, --human-readable  print sizes in powers of 1024 (e.g., 1023M)
-H, --si              print sizes in powers of 1000 (e.g., 1.1G)
```
