### ISSUE TITLE
charts中的readme有中文，在界面中显示乱码

### ISSUE THREAD

**Issue by jinjie2088** [kubesphere/kubesphere#1631]
![image](https://user-images.githubusercontent.com/4155721/70116462-c2acc300-169d-11ea-8b73-19c110be86ff.png)

**Comment by whDongRui** [comment]
这个问题已经解决了，同 https://github.com/kubesphere/kubesphere/issues/1490

**Comment by FeynmanZhou** [comment]
@jinjie2088 kubesphere 是什么版本？

**Comment by rayzhou2017** [comment]
duplicate with #1490
