### ISSUE TITLE
应用商店界面访问集群内部IP，出现timeout

### ISSUE THREAD

**Issue by simonxlh** [kubesphere/kubesphere#1632]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
使用 `kubesphere-minimal.yaml` 安装kubesphere 2.1.0版本后，编辑 `cm ks-installer` 打开`openpitrix` 功能后，打开应用商店界面 `\apps` ，发送 `/kapis/openpitrix.io/v1/apps` 响应500
返回结果为
```
{
 "message": "rpc error: code = Internal desc = internal error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.102.238.38:9118: i/o timeout\""
}
```
10.102.238.38 对应为 `openpitrix-isv-manager` 这个 `Service`
`job` `deployment` 均正常状态
![error2](https://user-images.githubusercontent.com/32514225/70120238-fe985600-16a6-11ea-941f-fcc4b22b5fc3.png)
![error3](https://user-images.githubusercontent.com/32514225/70120243-03f5a080-16a7-11ea-9813-6ab86a6afc87.png)

**安装环境的硬件配置**

- 集群： 在 `VirtualBox` 安装的 `Ubuntu 16.04` 虚拟机上使用 `minikube` 搭建的集群
- 配置如下图
 
![info1](https://user-images.githubusercontent.com/32514225/70120360-5d5dcf80-16a7-11ea-89d8-77cc2ebfab81.png)

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
![error1](https://user-images.githubusercontent.com/32514225/70120385-6c448200-16a7-11ea-9fb5-3d61d95b9325.png)

**Installer版本**
2.1.0

**Comment by simonxlh** [comment]
补充一下，根据[开发者论坛](https://kubesphere.com.cn/forum/d/301/3)中的回复，在 `ks-apiserver` 的pod 里检查一下 `openpitrix-isv-manager.openpitrix-system.svc:9118` 的端口是通的，`nslookup` 对应的IP也是 service 中对应的 `ClusterIP`。
```bash
/ # nc -zv openpitrix-isv-manager.openpitrix-system.svc 9118
openpitrix-isv-manager.openpitrix-system.svc (10.96.219.124:9118) open
/ # nslookup openpitrix-isv-manager.openpitrix-system.svc localhost
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      openpitrix-isv-manager.openpitrix-system.svc
Address 1: 10.96.219.124 openpitrix-isv-manager.openpitrix-system.svc.cluster.local
```
IP 是因为我重新部署过，所以和上图不太一样。

**Comment by zryfish** [comment]
/close  
due to inactivity and issue already fixed
