### ISSUE TITLE
更新到kubesphere2.1版本 无法解析镜像名称问题

### ISSUE THREAD

**Issue by dpp814** [kubesphere/kubesphere#1633]
拉取自己私有docker仓库就会报无法解析镜像名称错误
![image](https://user-images.githubusercontent.com/22487387/70125431-baf71980-16b1-11ea-8e03-f68afcda2b98.png)
![image](https://user-images.githubusercontent.com/22487387/70125461-c3e7eb00-16b1-11ea-8d8e-b627502067ba.png)
2.0版本没有这个问题

**Comment by zryfish** [comment]
试下在节点上能否拉取这个镜像，如果还是不能拉取，看下这个 yaml 配置里是否添加了 imagePullSecrets
