### ISSUE TITLE
2.1 弹性伸缩 hpa 显示bug。

### ISSUE THREAD

**Issue by hewenhong** [kubesphere/kubesphere#1634]
**Describe the bug(描述下问题)**
在hpa 上查看到

![image](https://user-images.githubusercontent.com/8400716/70140155-0d92fe80-16cf-11ea-8664-e15d0868e2e4.png)
![image](https://user-images.githubusercontent.com/8400716/70140161-11268580-16cf-11ea-8618-9e38bc799c3b.png)

单位显示不正确。

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

3 masters:  8cpu/16g
12 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**
1. Go to '弹性伸缩'

**Expected behavior(预期行为)**
查看单位不准

**Comment by zryfish** [comment]
这里单位显示错误 

/kind bug
/assign @leoendless

**Comment by leoendless** [comment]
@zryfish 需要后端将内存已使用量格式化后返回

**Comment by zheng1** [comment]
@zryfish 这个问题在 2.1.1 是否已经修复？

**Comment by zryfish** [comment]
这个问题不是经常发生，3.0会重构这部分代码，放到3.0一起修复吧

**Comment by calvinyv** [comment]
@zryfish does this fix in 3.0 or pending to 3.1?
