### ISSUE TITLE
是否会支持导入现有基础设施的东西

### ISSUE THREAD

**Issue by puluto** [kubesphere/kubesphere#1635]
是否会支持导入现有基础设施的东西，比如gitlab，jenkins，harbor，现有的用了很久迁移起来是个挺费事的
是否支持导入集群中已有的ingress作为应用网关？
集群中有一些重复的组件，是否可以支持直接导入，比如metric-server，kubernetes-dashboard这些.

比较期待3.0的多集群管理

**Comment by FeynmanZhou** [comment]
@puluto 可以用 [ks-installer](https://github.com/kubesphere/ks-installer) 来装在已有的 k8s，内置 的 gitlab 和 harbor 是可选安装项，当然可以对接已有的，metrics-server 和 k8s-dashborad 都是可以，jenkins 对接已有的目前比较困难。
