### ISSUE TITLE
官网在线安装2.0.2版本的包怎么没有了

### ISSUE THREAD

**Issue by dpp814** [kubesphere/kubesphere#1638]
官网在线安装2.0.2版本的包怎么没有了？谁能提供个下载吗？不想安装2.1版本的

**Comment by FeynmanZhou** [comment]
切换到 2.0 的文档即可找到  https://kubesphere.com.cn/docs/v2.0/zh-CN/installation/all-in-one/

BTW，不想装 2.1 的原因是？

**Comment by dpp814** [comment]
> 切换到 2.0 的文档即可找到 https://kubesphere.com.cn/docs/v2.0/zh-CN/installation/all-in-one/
> 
> BTW，不想装 2.1 的原因是？

https://kubesphere.io/download/stable/advanced-2.0.2这个地址在线下载不了，你自己打开试试

**Comment by dpp814** [comment]
> > 切换到 2.0 的文档即可找到 https://kubesphere.com.cn/docs/v2.0/zh-CN/installation/all-in-one/
> > BTW，不想装 2.1 的原因是？
> 
> [https://kubesphere.io/download/stable/advanced-2.0.2这个地址在线下载不了，你自己打开试试](https://kubesphere.io/download/stable/advanced-2.0.2%E8%BF%99%E4%B8%AA%E5%9C%B0%E5%9D%80%E5%9C%A8%E7%BA%BF%E4%B8%8B%E8%BD%BD%E4%B8%8D%E4%BA%86%EF%BC%8C%E4%BD%A0%E8%87%AA%E5%B7%B1%E6%89%93%E5%BC%80%E8%AF%95%E8%AF%95)

我从自己私有镜像仓库拉取镜像部署就报无法解析镜像名称，2.0.2版本是可以的，2.1版本就有问题了，现在我都部署不了，我要装2.0.2在线版本，发现你们给的地址下载不了了

**Comment by FeynmanZhou** [comment]
@dpp814 现在应该可以下载 2.0.2 了。你的私有镜像仓库是什么？我们在 2.1 用 harbor 没有复现这个问题，应该是仓库的 docker 配置有问题吧
