### ISSUE TITLE
使用All-in-One 模式安装，不能登录的情况

### ISSUE THREAD

**Issue by tengshe789** [kubesphere/kubesphere#1642]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**

使用All-in-One 模式安装成功后，日志提示：
```
#####################################################
###              Welcome to KubeSphere!           ###
#####################################################

Console: http://192.168.127.129:30000
Account: admin
Password: P@88w0rd

NOTES：
  1. After logging into the console, please check the
     monitoring status of service components in
     the "Cluster Status". If the service is not
     ready, please wait patiently. You can start
     to use when all components are ready.
  2. Please modify the default password after login.

#####################################################
```
然而使用`admin`账户不能登录，提示`Internal Server Error``,

**安装环境的硬件配置**

VMware虚拟机

**错误信息或截图**

**Installer版本**
在线版2.0.2
https://kubesphere.io/docs/v2.0/zh-CN/installation/all-in-one/

**Comment by tengshe789** [comment]
抱歉，版本Installer版本是2.1.0

**Comment by FeynmanZhou** [comment]
@tengshe789 kubectl get pod -n  kubesphere-system 看看 pod 状态，刚装好的环境，可能还要 Pod 在初始化状态

**Comment by tengshe789** [comment]
> @tengshe789 kubectl get pod -n kubesphere-system 看看 pod 状态，刚装好的环境，可能还要 Pod 在初始化状态

天呐，我这开着电脑放了一天了，ks-account为什么没有ready呢？

NAME                                     READY   STATUS     RESTARTS   AGE
etcd-555778878f-lwzdx                    1/1     Running    0          11h
ks-account-75fdc96f65-9czhq              0/1     Init:0/2   0          11h
ks-apigateway-65dd54f989-g6vbb           1/1     Running    0          11h
ks-apiserver-5d98f5d7cb-tkrcm            1/1     Running    8          11h
ks-console-6f7f75bb48-mrft5              1/1     Running    0          11h
ks-controller-manager-6dd9b76d75-ztfjg   1/1     Running    0          11h
ks-installer-7987c659d6-wqzxs            1/1     Running    0          11h
minio-8cd46c8d9-pdvvk                    1/1     Running    0          11h
mysql-b5597d996-zfvzj                    1/1     Running    0          11h
openldap-0                               1/1     Running    0          11h
redis-5d4844b947-gwqkr                   1/1     Running    0          11h

**Comment by FeynmanZhou** [comment]
@tengshe789 你的环境 DNS 可能有问题，参考这个 issue 看是否有帮助：https://github.com/kubesphere/kubesphere/issues/1555

**Comment by FeynmanZhou** [comment]
@tengshe789 问题已经搞定了么？

**Comment by tengshe789** [comment]
> @tengshe789 问题已经搞定了么？

目前没有，确认dns问题以后，我将宿主机dns添加8.8.8.8，然后卸载安装一遍，现在提示：
```shell
root@ks-allinone:/home/user# kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l app=ks-install -o jsonpath={.items[0].metadata.name}) -f
Error from server (BadRequest): container "installer" in pod "ks-installer-7987c659d6-7cfl6" is not available

```

**Comment by FeynmanZhou** [comment]
@wansir 有空了帮忙看看吧

**Comment by wansir** [comment]
@tengshe789  需要查看kubesphere-system 下的异常pod，查看日志， 检查原因

**Comment by wansir** [comment]
@tengshe789  需要查看kubesphere-system 下的异常pod，查看日志， 检查原因
