### ISSUE TITLE
应用里无法看到通过常规方式选择关联应用创建的服务

### ISSUE THREAD

**Issue by knowwinter** [kubesphere/kubesphere#1645]
在应用里创建了一个自建的应用，创建了一些比如mysql、redis以及我自己的前端的应用程序，然后在服务里创建了一个有状态服务，并且在创建时选择了关联应用到我创建的那个应用，并且默认选择了开启服务治理，但是创建完之后，该服务里信息里的应用显示了我对应的应用，在应用里的组件却并没有该组件，并且这个服务虽然选择开启了服务治理，但是并没有在部署里同时创建istio-proxy，应该是无法实现服务治理的，这个关联应用默认是不关联，且看不到其他应用，必须主动选一次不关联后才会刷新出应用里的应用，这个应该也是bug吧，必须选择后触发一次，这个还不要紧，关键是无法通过这种方式关联到应用并实现服务治理
![1575822267036](https://user-images.githubusercontent.com/25719964/70392369-83be9a80-1a1a-11ea-8eac-76570b4f17e7.jpg)
![1575822351370](https://user-images.githubusercontent.com/25719964/70392374-8caf6c00-1a1a-11ea-84b7-c4776fb2c1b7.jpg)
![1575822494132](https://user-images.githubusercontent.com/25719964/70392403-cda78080-1a1a-11ea-80bf-06a89b7bbe9d.jpg)

**Comment by zryfish** [comment]
这个应该是个bug，我们会修复下，可以在应用详情里添加组件

/kind bug
