### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by zryfish** [kubesphere/kubesphere#1647]
Our project code structure is not easy to write unit tests, things need to done to enable unit tests across whole project.

- [ ] Refactor clientset factory, use Interface instead of component clients directly. Such as redis/ldap/mysql
- [ ] Refactor apis handler to not use singleton client
- [x] Migrate kubebuilder to [v2]( https://book.kubebuilder.io/migration/guide.html)

**Comment by imjoey** [comment]
Hi @zryfish , could you please show me where I can get the source codes that makes use of kubebuilder  v2 ? Thanks so much.

**Comment by zryfish** [comment]
You can't use kubebuilder v2 directly,  we only upgrade kubebuilder dependent modules to v2, but since initial kubebuilder v2 applies to different code structures(only single API group supported), it will mess our repo if using directly. Currently, we create necessary folders and files manually.

**Comment by zryfish** [comment]
Just checked the documentation, kubebuilder v2 now supports multigroup API, we will get back with this soon

**Comment by imjoey** [comment]
> Just checked the documentation, kubebuilder v2 now supports multigroup API, we will get back with this soon

@zryfish Thank you very much for the efforts. In addition, will the code structures be refactored along with kubebuilder v2? If not, we could provide a script  for automatically transferring to codes auto-generated by v2 to v1 for easing the development. Please let me know your insight. Thanks.
