### ISSUE TITLE
KubeSphere已有k8s集群安装ks的从2.0.2升级2.1版本呢？

### ISSUE THREAD

**Issue by yanxinquanboe** [kubesphere/kubesphere#1649]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**目前我们使用的是KubeSphere 2.0.2的版本，但是K8S 是独立安装的，现在想在已有的K8S上面升级KubeSphere到最新的2.1版本，但是最新的KubeSphere2.1的版本并没有明确的说明，该场景下如何正确的进行升级和相关的注意事项。不知道如何升级，升级如果有问题的化，如何回退**

**CentOS 7 虚拟机**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**

**2.1**

**Comment by FeynmanZhou** [comment]
@yanxinquanboe  获取 ks-installer 仓库 master 分支代码，存储类型与 2.1 的保持一致，然后其它参数如果在 2.1 改动过的，也需要保持一致，确认参数项匹配后，参考 2.1 的 ks-installer 安装方法即可完成升级。
