### ISSUE TITLE
容器日志显示延迟很大。

### ISSUE THREAD

**Issue by hewenhong** [kubesphere/kubesphere#1650]
**Describe the bug(描述下问题)**
点击容器日志后，无法实时获取容器日志，延迟大概2-3分钟。

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere:  2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

3 masters:  8cpu/16g
12 nodes: 8cpu/16g

**To Reproduce(复现步骤)**
点击部署的应用，查看日志。存在延迟比较严重，建议实时日志使用kubectl log tailf 去获取日志。
历史日志信息，建议留存在es 中。

**Expected behavior(预期行为)**
日志延迟在2-3分钟

**Comment by rayzhou2017** [comment]
这个问题是怎么计划的？

**Comment by calvinyv** [comment]
容器日志详情页日志通过k8s原生api获取
日志检索控制台走ks monitoring api获取
@huanggze 对否？

**Comment by benjaminhuo** [comment]
@rayzhou2017 @calvinyv 是的容器日志详情页走 k8s 原生 api， 其他的走原路线 es。
这个问题陈豪会在 2.1.1 改好

**Comment by huanggze** [comment]
是的。因为从 fluent bit 采集日志、转发到 es、es 分片建立索引 到前段可查有个延迟。所以最新的容器页日志会采用 k8s log api，其他不变

**Comment by zheng1** [comment]
@benjaminhuo 这个问题在 2.1.1 是否已经修复？

**Comment by leoendless** [comment]
这个应该已经修复了，最新的 dev installer 里可以验证，直接调用的 k8s log api

**Comment by benjaminhuo** [comment]
![Snip20200210_22](https://user-images.githubusercontent.com/18525465/74138551-c6743d00-4c2c-11ea-8cff-49fae9937606.png)

Verified in the latest 2.1.1 dev build.
Container logs can be seen without the logging module enabled.

**Comment by benjaminhuo** [comment]
Verified and closed
