### ISSUE TITLE
The  application about container is - 

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1652]
![image](https://user-images.githubusercontent.com/57089340/70506967-672f7900-1b66-11ea-8e8c-2a1e51c59551.png)

![image](https://user-images.githubusercontent.com/57089340/70507012-79111c00-1b66-11ea-91a9-daa6f8b0b9e0.png)

**Comment by leoendless** [comment]
应该可以在 container 详情页里拿到所属 pod 的 label

**Comment by ellaye** [comment]
fixed
