### ISSUE TITLE
流水线发布后，node拉取镜像失败

### ISSUE THREAD

**Issue by tzghost** [kubesphere/kubesphere#1653]
流水线发布成功后，进行deployment时，node拉取镜像失败。比如在流水线运行过程中，在node1创建构建镜像并push到harbor，deployment时，调度到node2节点，会出现无法pull镜像的问题，如下：
![image](https://user-images.githubusercontent.com/17000535/70582546-cbe5e480-1bf5-11ea-9ba3-d170f9370d1c.png)
![image](https://user-images.githubusercontent.com/17000535/70582551-cee0d500-1bf5-11ea-8152-5189e2467075.png)
![image](https://user-images.githubusercontent.com/17000535/70582555-d1dbc580-1bf5-11ea-98cb-b1d5f8b7a586.png)

**Comment by shaowenchen** [comment]
/area devops

请先直接在命令行中，登录，推、拉镜像，确定 Harbor 是否安装成功。

**Comment by tzghost** [comment]
这些功能原来都正常的，在流水线发布成功后，进行deployment时，node拉取镜像失败。比如在流水线运行过程中，在node1创建构建镜像并push到harbor，deployment时，调度到node2节点，会出现无法pull镜像的问题，社区上有说是harbor 的 docker 相关参数配置问题，我暂时没找到解决办法，麻烦帮忙看下
https://kubesphere.com.cn/forum/d/410-node/4
