### ISSUE TITLE
问一个关于 kubesphere 阿里云K8S 混合云问题

### ISSUE THREAD

**Issue by gongjx11** [kubesphere/kubesphere#1654]
目前环境是这样的。IDC 机房部署的是kubesphere ，阿里云部署是K8S集群，网络目前以经打通，可以实现内部互通，需求是，我在kubesphere  阿里云K8S 同时部署了一个POD nginx test.现在我想在kubesphere 上面做一个nginx pod负载均衡，

阿里云这边SVC 我以配好了，也指出来了，通过域名可以访问，下面是访问的截图。
![image](https://user-images.githubusercontent.com/21954004/70586179-5f70e280-1c01-11ea-84e6-3b06b314f548.png)

现在就是想把两个POD 应用做一人负载，比如我IDC kubesphere pod 应用挂了，我阿里云可以提供服务。

**Comment by shaowenchen** [comment]
你这是需要一个 LB 吧，将域名解析到 LB，LB 指向多套服务。

**Comment by gongjx11** [comment]
好的， 谢谢

**Comment by noprom** [comment]
@gongjx11 请教一个问题，你们是如何将IDC机房的ks和阿里云的k8s的网络打通的？
能不能实现下面这种功能呢：
1. 计算资源使用部署在IDC机房的kubesphere;
2. 流量走云平台的按量付费。

**Comment by calvinyv** [comment]
@noprom 可以搜寻类似的友商服务 https://www.qingcloud.com/products/sd-wan/

**Comment by noprom** [comment]
@calvinyv 好的，谢谢。
