### ISSUE TITLE
The default storage class should not be set more than 1

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#1656]
I guess KubeSphere should not allow users to set 2 default StorageClass in UI, when you set one as default, the other one should be unset automaticlly.
![image](https://user-images.githubusercontent.com/40452856/70608158-a16a4a80-1c3a-11ea-83ae-f8a0541ba9e4.png)

**Comment by leoendless** [comment]
应当在后端代码中控制此逻辑 @wnxn

**Comment by wnxn** [comment]
好的，后端加个设置默认存储类型的 API
