### ISSUE TITLE
OAuth2单点认证集成

### ISSUE THREAD

**Issue by sunzj1989** [kubesphere/kubesphere#1660]
kubesphere是否有与其他认证体系集成的方案，例如OAuth2

**Comment by wansir** [comment]
OAuth2 认证会在 3.0 提供

**Comment by sunzj1989** [comment]
请问3.0大约什么时候发布？

**Comment by calvinyv** [comment]
2.1.1 后端已支持

**Comment by calvinyv** [comment]
/assign @wansir @leoendless 
/

**Comment by calvinyv** [comment]
> 请问3.0大约什么时候发布？

按目前的推进情况，估计在五月份

**Comment by calvinyv** [comment]
@wansir we should already support it, right? if so, pls help to close this issue, thx.
