### ISSUE TITLE
start request repeated too quickly for docker.service

### ISSUE THREAD

**Issue by RuvikVan** [kubesphere/kubesphere#1662]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)
当我使用 curl -L https://kubesphere.io/download/stable/v2.1.0 > installer.tar.gz \
 && tar -zxf installer.tar.gz &&  cd kubesphere-all-v2.1.0 / scripts
$ ./install.sh 命令进行快速安装时候
**问题描述**
运行到最后报错
start request repeated too quickly for docker.service
**安装环境的硬件配置**
ubuntu 1804和centos 7
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)
VMware虚拟机
**错误信息或截图**

**Installer版本**
2.1.0

**Comment by zryfish** [comment]
贴下详细的日志或错误截图看下

**Comment by RuvikVan** [comment]
> 贴下详细的日志或错误截图看下

只有这部分start request repeated too quickly for docker.service 上面只是显示了其他信息
