### ISSUE TITLE
节点分配不均

### ISSUE THREAD

**Issue by xwb2535** [kubesphere/kubesphere#1664]
集群模式，
master  16核32G
node1  8核16G
node2 8核16Ｇ。

现在每次部署应用，应用都在master 和node1 两个节点之前生成容器。
![image](https://user-images.githubusercontent.com/20022334/70764862-d3db8b00-1d93-11ea-9f54-51f11a4b01ed.png)

node2基本除了少量的系统带的应用，我新增加的部署等，都不会在node2创建。导致master节点压力好大。

**Comment by panhaitao** [comment]
你可以手动master上的pod驱逐走，看看会不会在node2上启动pod。还有收集点 node2节点的kubelet日志 看看为啥不往node2上调度pod

**Comment by xwb2535** [comment]
> 你可以手动master上的pod驱逐走，看看会不会在node2上启动pod。还有收集点 node2节点的kubelet日志 看看为啥不往node2上调度pod
一直在master和node1上跑。不会在node2上去，除非创建的时候手动指定到node2

**Comment by zryfish** [comment]
执行下面这个命令看下
```
kubectl describe node node2 
```
