### ISSUE TITLE
KubeSphere2.1 LDAP 脚本 inject-ks-account.sh 如何指定Search Filter

### ISSUE THREAD

**Issue by yanxinquanboe** [kubesphere/kubesphere#1666]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**各位社区同学：
用户的需求只想导入旧LDAP 部分数据，
请问 KubeSphere2.1 LDAP 脚本 inject-ks-account.sh 如何指定Search Filter
例子如下： (&(objectclass=organizationalPerson)(memberOf=cn=BJ,ou=groups,dc=test,dc=com))

还有想问下，目前老的LDAP 由大概15万的用户，这个kubesphere 接入有啥问题码？是不是更新，查询较慢呢

谢谢！**

**KubeSphere 2.1**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**

**Installer版本**

**Comment by wansir** [comment]
可以调整同步间隔试试，查询效率会受影响。如果活跃用户占比不高的话，可以考虑通过脚本做账户迁移。

另外，会在3.0 提供OAuth2 认证的方案
