### ISSUE TITLE
Unable to login to demo environment

### ISSUE THREAD

**Issue by sdil** [kubesphere/kubesphere#1668]
**General remarks**

**Describe the bug(描述下问题)**
Could not login to demo environment with username demo1 and password demo123

![image](https://user-images.githubusercontent.com/461537/70799805-9c95ca00-1de5-11ea-886f-e8e1a93a8e95.png)

**Versions used(KubeSphere/Kubernetes的版本)**
https://demo.kubesphere.io/login

**Environment(环境的硬件配置)**
https://demo.kubesphere.io/login

**To Reproduce(复现步骤)**
1. Go to https://demo.kubesphere.io/login
2. Insert username demo1
3. Insert password demo123

**Expected behavior(预期行为)**
Login successfully

**Comment by FeynmanZhou** [comment]
@sdil  
- username: demo1
- password: Demo123

**Comment by sdil** [comment]
opsss thank you @FeynmanZhou

**Comment by 1Const1** [comment]
![изображение](https://user-images.githubusercontent.com/40315470/137557872-c00d09e0-c4fa-4328-ae47-c0f8a7a75fad.png)
try this like on picture - received error

does password was changed?
