### ISSUE TITLE
centos7.6安装几小时之后机器卡死

### ISSUE THREAD

**Issue by huanghe** [kubesphere/kubesphere#1669]
**General remarks**

> 
> 全新安装centos7.6，然后安装KubeSphere v2.1，正常运行一段时间后，机器卡死
>

**Describe the bug(描述下问题)**
1. 全新安装的centos7.6，然后再关闭firewalld，安装最新版KubeSphere v2.1；
2. 安装后能正常使用，top的load average在1左右如图：![](https://static.extremevision.com.cn/donkey_f9b4adfb-83d7-41d8-8c67-2e667a15d97b)
3. 过几小时，top命令的load average能够飙涨到200以上，而且登录不上去，手动重启服务器后，又能够重新使用了，会有报错信息，情况如图：![](https://static.extremevision.com.cn/donkey_868801d9-51d4-46ad-9275-b0a382e1072b)

4. 登录页面正常显示，输入账号密码登录之后返回500，如图:![](https://static.extremevision.com.cn/donkey_e70f5b5c-9d1f-4ca3-a454-7da9a4f45e9b)

For UI issues please also add a screenshot that shows the issue.

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere:kubesphere-all-v2.1.0

**Environment(环境的硬件配置)**

1 masters:  72cpu/32g
0 nodes
centos版本：CentOS Linux release 7.6.1810 (Core)

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**
1. uninstall kubeSphere，第二天来查看机器，能够正常使用，负载正常；
2. 重新安装kubeSphere, 第二天来查看，机器无法登录，登录页面可以正常显示，问题复现。

**Comment by Forest-L** [comment]
1、cpu配置蛮高的；
2、可以看下那些服务的负载飙高，截图看下

**Comment by huanghe** [comment]
> 1、cpu配置蛮高的；
> 2、可以看下那些服务的负载飙高，截图看下

运行一段时间已经登录不进去了，卡死了

**Comment by huanghe** [comment]
> 1、cpu配置蛮高的；
> 2、可以看下那些服务的负载飙高，截图看下

> 1、没有服务明显高负载，top里面会偶现报错： NMI watchdog: BUG: soft lockup - CPU#18 stuck for 67s
> 2、如图:
![](https://static.extremevision.com.cn/donkey_b8179593-dcaf-4814-826d-6bc31f7bde60)
![](https://static.extremevision.com.cn/donkey_ffa64b51-a2b1-4df7-8a0a-0d6fc10318dd)
![](https://static.extremevision.com.cn/donkey_e9382cc2-e1ed-407a-8a88-9297d843ac90)

**Comment by Forest-L** [comment]
1、目前上面部署了你们的应用吗？
2、soft lockup，查看下cat /proc/sys/kernel/watchdog_thresh的值。
3、参考下，https://www.cnblogs.com/nulige/p/8000490.html     https://blog.csdn.net/fuyuande/article/details/82874521

**Comment by huanghe** [comment]
> 1、目前上面部署了你们的应用吗？
> 2、soft lockup，查看下cat /proc/sys/kernel/watchdog_thresh的值。
> 3、参考下，https://www.cnblogs.com/nulige/p/8000490.html https://blog.csdn.net/fuyuande/article/details/82874521

> 1、没有部署应用；
> 2、之前设置过，值为30；
> 3、这些文档已经查看过了。
> 4、换成centos7.5,再安装kubeshere也会有这个问题，中间执行过两个操作：
`pip install --upgrade pip  pip install --upgrade setuptools`
`systemctl stop firewalld，systemctl disable firewalld`

**Comment by Forest-L** [comment]
可以登录到你们环境看下吗？tv12或者向日葵，可以的话，发到官方邮箱中。

**Comment by huanghe** [comment]
> 可以登录到你们环境看下吗？tv12或者向日葵，可以的话，发到官方邮箱中。

可以的，那我发到官方邮箱哈

**Comment by huanghe** [comment]
> 可以登录到你们环境看下吗？tv12或者向日葵，可以的话，发到官方邮箱中。

邮箱是哪个，没有找到哈

**Comment by Forest-L** [comment]
是的，因为我们之前也没有遇到上面描述的问题，目前kubesphere最小安装2C，4G即可，且蛮稳定。

**Comment by huanghe** [comment]
> 是的，因为我们之前也没有遇到上面描述的问题，目前kubesphere最小安装2C，4G即可，且蛮稳定。
> OK，已经发送了

**Comment by Forest-L** [comment]
现在看机器是正常，但之前看你截图，里面出现了大量的kwork进程。

**Comment by huanghe** [comment]
> 现在看机器是正常，但之前看你截图，里面出现了大量的kwork进程。

> 不正常，现在（14:08）又登录不进去了，我重启下

**Comment by Forest-L** [comment]
54157 polkitd   20   0 9987060 540108  23548 S 466.8  1.7   0:57.24 java    

polkitd   54157  51823 99 16:56 ?        00:01:29 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -cp ./lib/common/*:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.2.5.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process944445372298762772properties


这个服务有问题，cpu达到了500%来了，可以查下这个服务。

**Comment by huanghe** [comment]
> 54157 polkitd 20 0 9987060 540108 23548 S 466.8 1.7 0:57.24 java
> 
> polkitd 54157 51823 99 16:56 ? 00:01:29 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -cp ./lib/common/*:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.2.5.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process944445372298762772properties
> 
> 这个服务有问题，cpu达到了500%来了，可以查下这个服务。

> 好的，我查下，问题是除了kubesphere,我们啥也没装

**Comment by zryfish** [comment]
> 54157 polkitd 20 0 9987060 540108 23548 S 466.8 1.7 0:57.24 java
> 
> polkitd 54157 51823 99 16:56 ? 00:01:29 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -cp ./lib/common/*:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.2.5.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process944445372298762772properties
> 
> 这个服务有问题，cpu达到了500%来了，可以查下这个服务。

@huanghe 这个进程看着是 sonarqube 导致的，可以先试下将 sonarqube 禁用了，看下是否仍有这个问题了，另外可以将内核版本和cpu信息贴下么，执行下下面两个命令
```
uname -a 
lscpu
```

**Comment by huanghe** [comment]
> > 54157 polkitd 20 0 9987060 540108 23548 S 466.8 1.7 0:57.24 java
> > polkitd 54157 51823 99 16:56 ? 00:01:29 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -cp ./lib/common/*:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.2.5.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process944445372298762772properties
> > 这个服务有问题，cpu达到了500%来了，可以查下这个服务。
> 
> @huanghe 这个进程看着是 sonarqube 导致的，可以先试下将 sonarqube 禁用了，看下是否仍有这个问题了，另外可以将内核版本和cpu信息贴下么，执行下下面两个命令
> 
> ```
> uname -a  
```  Linux ks-allinone 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux ```
> lscpu
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                72
On-line CPU(s) list:   0-71
Thread(s) per core:    2
Core(s) per socket:    18
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
Stepping:              4
CPU MHz:               1000.000
CPU max MHz:           2301.0000
CPU min MHz:           1000.0000
BogoMIPS:              4600.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              25344K
NUMA node0 CPU(s):     0-17,36-53
NUMA node1 CPU(s):     18-35,54-71
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt mba tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local ibpb ibrs stibp dtherm ida arat pln pts pku ospke spec_ctrl intel_stibp
```
> kill -9 掉 进程sonarqube，你们的服务也会崩掉，过一会会自己起来，程序如下
```
polkitd   43003  42185 64 14:08 ?        00:01:46 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -cp ./lib/common/*:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.2.5.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process8887729332037402992properties
```

**Comment by Forest-L** [comment]
先这样处理下：看下cpu情况
```
1、kubectl get deployment -n kubesphere-devops-system | grep sonarqube
ks-sonarqube-postgresql                   1/1     1            1           5m23s
ks-sonarqube-sonarqube                    1/1     1            1           5m23s

kubectl scale deployment -n kubesphere-devops-system ks-sonarqube-postgresql --replicas=0
kubectl scale deployment -n kubesphere-devops-system ks-sonarqube-sonarqube --replicas=0
```

**Comment by huanghe** [comment]
> 先这样处理下：看下cpu情况
> 
> ```
> 1、kubectl get deployment -n kubesphere-devops-system | grep sonarqube
> ks-sonarqube-postgresql                   1/1     1            1           5m23s
> ks-sonarqube-sonarqube                    1/1     1            1           5m23s
> 
> kubectl scale deployment -n kubesphere-devops-system ks-sonarqube-postgresql --replicas=0
> kubectl scale deployment -n kubesphere-devops-system ks-sonarqube-sonarqube --replicas=0
> 这样sonarqube确实起不来，但是install-plugins.sh会尝试重启，重启的时候，网页打不开
```
ps -ef|grep sona
root      28115  27874  0 15:56 ?        00:00:00 /bin/bash -eu /usr/local/bin/install-plugins.sh ace-editor:1.1 apache-httpcomponents-client-4-api:4.5.5-3.0 async-http-client:1.9.40.0 authentication-tokens:1.3 azure-commons:1.0.3 blueocean:1.19.0 blueocean-autofavorite:1.2.3 blueocean-bitbucket-pipeline:1.19.0 blueocean-commons:1.19.0 blueocean-config:1.19.0 blueocean-core-js:1.19.0 blueocean-dashboard:1.19.0 blueocean-display-url:2.2.0 blueocean-events:1.19.0 blueocean-executor-info:1.19.0 blueocean-git-pipeline:1.19.0 blueocean-github-pipeline:1.19.0 blueocean-i18n:1.19.0 blueocean-jira:1.19.0 blueocean-jwt:1.19.0 blueocean-personalization:1.19.0 blueocean-pipeline-api-impl:1.19.0 blueocean-pipeline-editor:1.19.0 blueocean-pipeline-scm-api:1.19.0 blueocean-rest-impl:1.19.0 blueocean-rest:1.19.0 blueocean-web:1.19.0 bouncycastle-api:2.17 branch-api:2.2.0 build-monitor-plugin:1.12+build.201809061734 build-timeout:1.19 cloudbees-bitbucket-branch-source:2.4.5 cloudbees-folder:6.9 command-launcher:1.3 conditional-buildstep:1.3.6 configuration-as-code:1.27 configuration-as-code-support:1.18 config-file-provider:3.6 credentials-binding:1.18 credentials:2.3.0 display-url-api:2.3.2 docker-commons:1.15 docker-workflow:1.17 durable-task:1.30 favorite:2.3.2 generic-webhook-trigger:1.45 git-client:2.7.6 git-server:1.7 git:3.9.3 github-api:1.95 github-branch-source:2.4.2 github:1.29.4 handlebars:1.1.1 handy-uri-templates-2-api:2.1.7-1.0 htmlpublisher:1.18 jackson2-api:2.9.9.1 javadoc:1.5 jaxb:2.3.0.1 jdk-tool:1.2 jenkins-design-language:1.19.0 jira:3.0.8 job-dsl:1.75 jquery:1.11.2-0 jquery-detached:1.2.1 jquery-ui:1.0.1 jsch:0.1.55 junit:1.27 kubernetes-cd:2.1.2 kubernetes-client-api:1.0.0 kubernetes-credentials:0.4.0 kubernetes:1.19.2 kubesphere-extension:0.0.1 kubesphere-token-auth:0.2.0 ldap:1.20 lockable-resources:2.5 mailer:1.24 managed-scripts:1.4 mapdb-api:1.0.9.0 maven-plugin:3.4 matrix-auth:2.4.2 matrix-project:1.14 mercurial:2.4 metrics:4.0.2.5 momentjs:1.1.1 multibranch-action-triggers:1.4 node-iterator-api:1.5 parameterized-trigger:2.35.2 pipeline-build-step:2.8 pipeline-graph-analysis:1.10 pipeline-input-step:2.10 pipeline-milestone-step:1.3.1 pipeline-model-api:1.3.9 pipeline-model-declarative-agent:1.1.1 pipeline-model-definition:1.3.9 pipeline-model-extensions:1.3.9 pipeline-rest-api:2.10 pipeline-stage-step:2.3 pipeline-stage-tags-metadata:1.3.9 pipeline-stage-view:2.10 plain-credentials:1.5 pubsub-light:1.13 run-condition:1.2 resource-disposer:0.12 role-strategy:2.13 ruby-runtime:0.12 scm-api:2.6.3 script-security:1.62 sonar:2.8.1 sse-gateway:1.20 ssh-credentials:1.17.1 ssh-slaves:1.29.4 structs:1.20 subversion:2.12.1 support-core:2.56 token-macro:2.8 variant:1.3 workflow-aggregator:2.6 workflow-api:2.37 workflow-basic-steps:2.18 workflow-cps-global-lib:2.15 workflow-cps:2.73 workflow-durable-task-step:2.31 workflow-job:2.32 workflow-multibranch:2.21 workflow-scm-step:2.9 workflow-step-api:2.20 workflow-support:3.3 ws-cleanup:0.37
```

**Comment by huanghe** [comment]
> 先这样处理下：看下cpu情况
> 
> ```
> 1、kubectl get deployment -n kubesphere-devops-system | grep sonarqube
> ks-sonarqube-postgresql                   1/1     1            1           5m23s
> ks-sonarqube-sonarqube                    1/1     1            1           5m23s
> 
> kubectl scale deployment -n kubesphere-devops-system ks-sonarqube-postgresql --replicas=0
> kubectl scale deployment -n kubesphere-devops-system ks-sonarqube-sonarqube --replicas=0
> ```

> 还是不行，机器崩得更快了，刚才又崩了,估计是很多个install-plugins.sh会尝试重启的原因；
> 我把ssh打开，你们可以登录web和ssh进来看看。

**Comment by Forest-L** [comment]
可以，但现在连不上。

**Comment by hg-developer** [comment]
解决了么？我这也发生了这个问题

**Comment by huanghe** [comment]
> 解决了么？我这也发生了这个问题

没有解决，换机器可以。
