### ISSUE TITLE
安装前如何开启安装 DevOps 系统

### ISSUE THREAD

**Issue by zhoulei232** [kubesphere/kubesphere#1674]
使用 kubectl edit cm -n kubesphere-system ks-installer 命令 
修改如下：
devops:
      enabled: True
      jenkinsMemoryLim: 8Gi
      jenkinsMemoryReq: 4Gi
      jenkinsVolumeSize: 8Gi
      jenkinsJavaOpts_Xms: 3g
      jenkinsJavaOpts_Xmx: 6g
      jenkinsJavaOpts_MaxRAM: 8g
      sonarqube:
        enabled: True

openpitrix:
      enabled: True

devops启动后：
   ks-sonarqube-sonarqube，s2ioperator， s2ioperator-metrics-service这几个服务一直异常
OpenPitrix启动后：
  openpitrix-rp-kubernetes服务一直异常

**Comment by FeynmanZhou** [comment]
@zhoulei232  是用的 Linux installer 还是把 kubesphere 装在 k8s 上了呢？

**Comment by zhoulei232** [comment]
是安装在k8s后，现在已经解决了 ------------------ 原始邮件 ------------------
发件人: "pengfei"<notifications@github.com>
发送时间: 2019年12月18日(星期三) 下午4:59
收件人: "kubesphere/kubesphere"<kubesphere@noreply.github.com>;
抄送: "zhoulei232"<2470576197@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [kubesphere/kubesphere] 安装前如何开启安装 DevOps 系统 (#1674)



@zhoulei232  是用的 Linux installer 还是把 kubesphere 装在 k8s 上了呢？
 
&mdash;
