### ISSUE TITLE
How can i enable istio ?

### ISSUE THREAD

**Issue by matty111** [kubesphere/kubesphere#1680]
I changed the config map ks-installer with the flag true in servicemesh key, but in the ui istio is not enabled

**Comment by zryfish** [comment]
It'll take a while to fully enable a component, depends on the network speed, lots of images need to be pulled. You can inspect installation logs by executing following command
```
kubectl -n kubesphere-system logs [ks-installer-pod-name] -f 
```

**Comment by matty111** [comment]
I found istio resource, but for my bookinfo application found only deployment and pod. I don't find virtualservice and gateway and monitoring the traffic of my application from application menu

**Comment by zryfish** [comment]
virutalservice/destinationrule/gateway such resources are designed to be hid from users, it's too complicated to setup. KubeSphere console only exposes `Strategy`/`ServicePolicy` for simplification.  It's a lot easier if you follow this doc https://kubesphere.com.cn/docs/v2.1/en/quick-start/canary-release/ step by step.

**Comment by matty111** [comment]
in your prerequisites you see "You need to turn on the Application Governance to enable the tracing feature. (Choose Project Settings → Internet Access → Edit Gateway → Turn it On)". But i can't do set gateway. 
Did I get the installation wrong of kubesphere?

**Comment by zryfish** [comment]
Which version of KubeSphere you are using ?
