### ISSUE TITLE
增加 nodeSelector 

### ISSUE THREAD

**Issue by aaronsssya** [kubesphere/kubesphere#1682]
**问题描述**
我的環境中有 windows node，所以可以加一個 nodeselector 在 CM 中嗎？

**Comment by zryfish** [comment]
没有理解你的意思，需要给哪个资源增加nodeSelector，你想要达到什么样的效果

**Comment by aaronsssya** [comment]
把所有的資源都加 kubernetes.io/os: linux, 因為如果 kube-scheduler assign 到 windows node, 就會出現錯誤

**Comment by vanniszsu** [comment]
@zryfish 我觉得这个是很有必要的

在企业环境里面，我们希望 kubesphere的 pod,  譬如 ks-apiserver,  ks-controller-manager 等等都运行在特定的节点上，因为我们不想kubesphere的平台workload影响到真正的业务节点

所以希望 cluster-configuration.yaml 中增加 nodeSelector 的配置，可以让用户选择kubesphere的pod跑在哪些节点上

**Comment by zryfish** [comment]
You can create a feature-request for kubesphere/ks-installer

**Comment by finalha** [comment]
I have a question:  How to add nodeSelector in cluster-configuration.yaml of kubeshere 3.3.1? I can not find in https://github.com/kubesphere/ks-installer/releases/download/v3.3.1/cluster-configuration.yaml
