### ISSUE TITLE
拉取不了dockerhub仓库的镜像

### ISSUE THREAD

**Issue by Boblis** [kubesphere/kubesphere#1684]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
拉取不了dockerhub仓库的镜像

**安装环境的硬件配置**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
![image](https://user-images.githubusercontent.com/45844993/71149420-7058ce00-2269-11ea-9c64-a9668478a0ea.png)

**Installer版本**
v2.1

**Comment by zhoulei232** [comment]
这种应该怎么解决，我配置了dockerhub 的密钥

**Comment by zryfish** [comment]
手动执行 docker pull 试下
