### ISSUE TITLE
以前部署过相同名字的，从应用中删除了，但第二次部署相同名字的应用就提示already exist

### ISSUE THREAD

**Issue by catcomyou** [kubesphere/kubesphere#1686]
版本：KubeSphere v2.1
安装模式：Multi-Node
以前部署过相同名字的，从应用中删除了，但第二次部署就提示already exist
![image](https://user-images.githubusercontent.com/19699251/71155994-f67d1080-2279-11ea-9f10-da4380753541.png)

**Comment by zryfish** [comment]
duplicate https://github.com/kubesphere/kubesphere/issues/1564
