### ISSUE TITLE
离线安装2.1版本 检查报错

### ISSUE THREAD

**Issue by PYIsOk** [kubesphere/kubesphere#1692]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
安装完成后 执行检查程序报错，还有api-server pod 状态为CrashLoopBackOff，登录页面有，但是登录进去就提示 Internal Server Error

**安装环境的硬件配置**
8G 16C 100G硬盘
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)
虚拟机
**错误信息或截图**
Task 'devops' failed:
******************************************************************************************************************************************************
{
  "counter": 167, 
  "created": "2019-12-20T05:16:43.184634", 
  "end_line": 163, 
  "event": "runner_on_failed", 
  "event_data": {
    "event_loop": null, 
    "host": "localhost", 
    "ignore_errors": null, 
    "play": "localhost", 
    "play_pattern": "localhost", 
    "play_uuid": "be87cac8-003f-6f09-f0db-000000000005", 
    "playbook": "/kubesphere/playbooks/devops.yaml", 
    "playbook_uuid": "76331f3a-835f-46d2-806d-ab8b6768d3bb", 
    "remote_addr": "127.0.0.1", 
    "res": {
      "_ansible_no_log": false, 
      "attempts": 60, 
      "changed": true, 
      "cmd": "/usr/local/bin/kubectl get pod -n kubesphere-system -o wide | grep ks-account | awk '{print $3}'", 
      "delta": "0:00:00.516697", 
      "end": "2019-12-20 05:16:43.148520", 
      "invocation": {
        "module_args": {
          "_raw_params": "/usr/local/bin/kubectl get pod -n kubesphere-system -o wide | grep ks-account | awk '{print $3}'", 
          "_uses_shell": true, 
          "argv": null, 
          "chdir": null, 
          "creates": null, 
          "executable": null, 
          "removes": null, 
          "stdin": null, 
          "stdin_add_newline": true, 
          "strip_empty_ends": true, 
          "warn": true
        }
      }, 
      "rc": 0, 
      "start": "2019-12-20 05:16:42.631823", 
      "stderr": "", 
      "stderr_lines": [], 
      "stdout": "Init:0/2", 
      "stdout_lines": [
        "Init:0/2"
      ]
    }, 
    "role": "ks-devops/jenkins", 
    "task": "KubeSphere | Waiting for ks-account", 
    "task_action": "command", 
    "task_args": "", 
    "task_path": "/kubesphere/installer/roles/ks-devops/jenkins/tasks/check_sonar.yaml:1", 
    "task_uuid": "be87cac8-003f-6f09-f0db-000000000044", 
    "uuid": "b312c46e-90f4-4d1f-8767-109d7d6c2b01"
  }, 
  "parent_uuid": "be87cac8-003f-6f09-f0db-000000000044", 
  "pid": 3625, 
  "runner_ident": "devops", 
  "start_line": 162, 
  "stdout": "fatal: [localhost]: FAILED! => {\"attempts\": 60, \"changed\": true, \"cmd\": \"/usr/local/bin/kubectl get pod -n kubesphere-system -o wide | grep ks-account | awk '{print $3}'\", \"delta\": \"0:00:00.516697\", \"end\": \"2019-12-20 05:16:43.148520\", \"rc\": 0, \"start\": \"2019-12-20 05:16:42.631823\", \"stderr\": \"\", \"stderr_lines\": [], \"stdout\": \"Init:0/2\", \"stdout_lines\": [\"Init:0/2\"]}", 
  "uuid": "b312c46e-90f4-4d1f-8767-109d7d6c2b01"
}
******************************************************************************************************************************************************
#####################################################
#####################################################

Console: http://10.0.3.34:30880
Account: admin
Password: P@88w0rd

NOTES：
  1. After logging into the console, please check the
     monitoring status of service components in
     the "Cluster Status". If the service is not
     ready, please wait patiently. You can start
     to use when all components are ready.
  2. Please modify the default password after login.

#####################################################

E1220 05:20:03.737645       1 reflector.go:283] github.com/flant/shell-operator/pkg/kube_events_manager/kube_events_manager.go:354: Failed to watch *unstructured.Unstructured: Get https://10.233.0.1:443/api/v1/namespaces/kubesphere-system/configmaps?fieldSelector=metadata.name%3Dks-installer&resourceVersion=1119&timeoutSeconds=431&watch=true: dial tcp 10.233.0.1:443: connect: connection refused
E1220 05:20:04.744706       1 reflector.go:125] github.com/flant/shell-operator/pkg/kube_events_manager/kube_events_manager.go:354: Failed to list *unstructured.Unstructured: Get https://10.233.0.1:443/api/v1/namespaces/kubesphere-system/configmaps?fieldSelector=metadata.name%3Dks-installer&limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: connect: connection refused
E1220 05:20:05.746334       1 reflector.go:125] github.com/flant/shell-operator/pkg/kube_events_manager/kube_events_manager.go:354: Failed to list *unstructured.Unstructured: Get https://10.233.0.1:443/api/v1/namespaces/kubesphere-system/configmaps?fieldSelector=metadata.name%3Dks-installer&limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: connect: connection refused
E1220 05:20:06.747605       1 reflector.go:125] github.com/flant/shell-operator/pkg/kube_events_manager/kube_events_manager.go:354: Failed to list *unstructured.Unstructured: Get https://10.233.0.1:443/api/v1/namespaces/kubesphere-system/configmaps?fieldSelector=metadata.name%3Dks-installer&limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: connect: connection refused
E1220 05:20:07.749181       1 reflector.go:125] github.com/flant/shell-operator/pkg/kube_events_manager/kube_events_manager.go:354: Failed to list *unstructured.Unstructured: Get https://10.233.0.1:443/api/v1/namespaces/kubesphere-system/configmaps?fieldSelector=metadata.name%3Dks-installer&limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: connect: connection refused
E1220 05:20:08.751700       1 reflector.go:125] github.com/flant/shell-operator/pkg/kube_events_manager/kube_events_manager.go:354: Failed to list *unstructured.Unstructured: Get https://10.233.0.1:443/api/v1/namespaces/kubesphere-system/configmaps?fieldSelector=metadata.name%3Dks-installer&limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: connect: connection refused
E1220 05:20:19.754721       1 reflector.go:125] github.com/flant/shell-operator/pkg/kube_events_manager/kube_events_manager.go:354: Failed to list *unstructured.Unstructured: Get https://10.233.0.1:443/api/v1/namespaces/kubesphere-system/configmaps?fieldSelector=metadata.name%3Dks-installer&limit=500&resourceVersion=0: net/http: TLS handshake timeout
E1220 05:20:27.771923       1 reflector.go:125] github.com/flant/shell-operator/pkg/kube_events_manager/kube_events_manager.go:354: Failed to list *unstructured.Unstructured: Get https://10.233.0.1:443/api/v1/namespaces/kubesphere-system/configmaps?fieldSelector=metadata.name%3Dks-installer&limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: connect: connection refused

**Installer版本**
2.1

**Comment by Forest-L** [comment]
此issue已关联kubesphere官方论坛，https://kubesphere.com.cn/forum/d/490-2-1
