### ISSUE TITLE
如何进行集群备份和恢复

### ISSUE THREAD

**Issue by wartih** [kubesphere/kubesphere#1694]
我在文档里看到在2.0.0版本中添加了etcd的备份功能
但是似乎没有其他关于备份和恢复的文档了。

**Comment by pixiake** [comment]
etcd备份在第一个etcd节点的/var/backups/kube_etcd中，也可参考k8s开源备份方案：https://github.com/vmware-tanzu/velero

**Comment by wartih** [comment]
kubesphere的集群信息也是保存在etcd中吗？恢复了etcd能否恢复kubesphere？
主要希望可以实现在所有Master节点挂掉的情况下，通过恢复一些保存在共享存储中的文件来恢复整个集群。请问目前可以达到吗？还是说只能依赖多节点的HA功能

**Comment by pixiake** [comment]
技术上是可行的，kubesphere的组件也是以pod的形式运行在k8s上的，所以相关信息也是在etcd中的，但是组件的数据是持久化在挂盘(共享存储)中的，这些挂盘可以恢复的话，可以使用etcd的备份来恢复集群状态，不过还是建议试试专门的k8s备份工具。

如果是正式环境，建议采用高可用方式部署。
