### ISSUE TITLE
ks-jenkins没有安装上

### ISSUE THREAD

**Issue by weiliang-ms** [kubesphere/kubesphere#1696]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
离线安装后，jenkins没有自动安装
**安装环境的硬件配置**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
![image](https://user-images.githubusercontent.com/18642754/71248445-d0c53980-2355-11ea-90e0-cb743dde0692.png)

cm配置如下：
`kubectl edit cm -n kubesphere-system ks-installer`
![image](https://user-images.githubusercontent.com/18642754/71248523-ffdbab00-2355-11ea-90f9-dc2070c7d675.png)

**Installer版本**
2.1

**Comment by weiliang-ms** [comment]
可以提供相关yaml文件手动安装吗？

**Comment by FeynmanZhou** [comment]
@weiliang-ms  这是在 Linux 环境安装的还是 K8s 上装的 KubeSphere？

**Comment by weiliang-ms** [comment]
您好是linux安装的，用的离线方式装的1master 2worker



---原始邮件---
发件人: "pengfei"<notifications@github.com&gt;
发送时间: 2019年12月20日(周五) 晚上11:06
收件人: "kubesphere/kubesphere"<kubesphere@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"xzx.weiliang"<1067599390@qq.com&gt;;
主题: Re: [kubesphere/kubesphere] ks-jenkins没有安装上 (#1696)



@weiliang-ms  这是在 Linux 环境安装的还是 K8s 上装的 KubeSphere？

**Comment by FeynmanZhou** [comment]
1master 2worker 的机器配置分别是多大呢？

**Comment by pixiake** [comment]
helm list看下是否有ks-jenkins的release

**Comment by weiliang-ms** [comment]
这边由于纯内网没有安装 helm

**Comment by pixiake** [comment]
安装kubesphere需要helm，我看有些组件已经安装了，应该环境里已经有helm了

**Comment by weiliang-ms** [comment]
手动创建ks-jenkins的话会有问题吗

**Comment by pixiake** [comment]
有些参数是定制的，可以看下ks-installer的日志，机器上没有helm的话，也可以到ks-installer那个容器里执行相关命令

**Comment by weiliang-ms** [comment]
请问后续版本还会提供离线部署方式吗？

**Comment by pixiake** [comment]
@weiliang-ms  只要把用到的镜像导入自己的镜像仓库，就可以离线部署

**Comment by weiliang-ms** [comment]
好的。
