### ISSUE TITLE
容器日志不显示

### ISSUE THREAD

**Issue by nzlov** [kubesphere/kubesphere#1697]
**General remarks**

> Please delete this section including header before submitting
> 也可以使用中文
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug(描述下问题)**
正常运行的容器日志不显示，而停掉或崩溃的容器日志显示正常。

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1
Kubernetes: 1.14

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

1 master: 4c8g
4 worker: 4c8g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**
部署应用

**Expected behavior(预期行为)**
正常显示日志。

**Comment by wansir** [comment]
正常日志是否通过STDOUT/STDERR进行输出呢，可以通过 kubectl logs 检查是否有日志输出

**Comment by huanggze** [comment]
https://github.com/kubesphere/kubesphere/issues/1505

**Comment by nzlov** [comment]
@huanggze Upgrade `kubespheredev/fluent-bit:v1.3.3-reload` fix .
