### ISSUE TITLE
关于 ES 日志 每日单一索引的改善建议

### ISSUE THREAD

**Issue by panhaitao** [kubesphere/kubesphere#1698]
在实际企业客户场景中，日志落盘策略的有很多细节期望，我列出目前收集到的多数云平台的相同痛点：

1. 期望容器PaaS平台区分平台日志和业务应用日志，不能把每日日志全部写入到一个单一的ES索引中
2. 期望可以灵活设置日志索引的配置策略，比如，针对不同项目或者应用定义不同索引，能为不同索引定义不同 TTL

**Comment by benjaminhuo** [comment]
现在虽然是单一索引，平台日志和应用日志是可以通过 namespace 区分的
分不同索引的情况我们会考虑下，实现这个需要根据日志标签进行过滤，会增加 agent 的处理时间，使得日志收集变慢。所以得权衡下。
我们也会考虑非 es 的日志存储方案

**Comment by panhaitao** [comment]
确实加重agent端的压力，或许应该在日志过滤lanaya之类的组件哪里做条件匹配分流，写入不同索引，这样问题或许能迎刃而解



---原始邮件---
发件人: "Benjamin Huo"<notifications@github.com&gt;
发送时间: 2019年12月23日(周一) 晚上6:30
收件人: "kubesphere/kubesphere"<kubesphere@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"潘海涛"<xz@onwalk.net&gt;;
主题: Re: [kubesphere/kubesphere] 关于 ES 日志 每日单一索引的改善建议 (#1698)



现在虽然是单一索引，平台日志和应用日志是可以通过 namespace 区分的
 分不同索引的情况我们会考虑下，实现这个需要根据日志标签进行过滤，会增加 agent 的处理时间，使得日志收集变慢。所以得权衡下。
 我们也会考虑非 es 的日志存储方案
