### ISSUE TITLE
使用官方例子 图形化构建流水线 部署失败

### ISSUE THREAD

**Issue by leowucn** [kubesphere/kubesphere#1700]
**Describe the bug(描述下问题)**

使用的是这个例子
https://kubesphere.io/docs/v2.1/zh-CN/quick-start/jenkinsfile-out-of-scm/ 
运行流水线时 `Unit Test` 步骤报错，错误信息为
```
container [maven] does not exist in pod [base-z61js]
```
**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0
Kubernetes: 1.15.7

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
1 masters:  4cpu/16g
3 nodes: 4cpu/16g

**Comment by chinazj** [comment]
看一下jenkinsfile。

**Comment by chinazj** [comment]
注意代理，需要填写maven
![image](https://user-images.githubusercontent.com/15140157/72694318-92e34d00-3b6f-11ea-8343-700b902605f4.png)
这个在jenkinsfile的表现为agent部分

```
pipeline {
  agent {
    node {
      label 'go'
    }

  }
}
```
