### ISSUE TITLE
给官方例子 构建流水线提的建议

### ISSUE THREAD

**Issue by leowucn** [kubesphere/kubesphere#1701]
**Describe the bug(描述下问题)**
在这个例子里
https://kubesphere.io/docs/v2.1/zh-CN/quick-start/devops-online/
`unit test` 阶段会从 `https://repo.maven.apache.org` 和 `http://repo.spring.io` 下载很多文件，这俩地址服务器都在国外，下载非常缓慢，估计很多人都遇到这个问题了。我不熟悉java开发，不清楚怎么配置。建议把这俩地址做成可以环境变量可修改源吧

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0
Kubernetes: 1.15.7

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
1 masters:  4cpu/16g
3 nodes: 4cpu/16g

**Comment by soulseen** [comment]
感谢反馈
/assign @soulseen
