### ISSUE TITLE
给图形化构建流水线功能提的建议

### ISSUE THREAD

**Issue by leowucn** [kubesphere/kubesphere#1702]
**Describe the bug(描述下问题)**
在图形化构建流水线中，可以添加多个阶段，有时候为了测试或者快速部署，希望能临时下线某个阶段，在随后的一个时间在上线，目前来看，要下线的话只能删除，虽然可以通过保存jenkins文件的方式，但是显然没有图形化展示清晰

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0
Kubernetes: 1.15.7

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
1 masters:  4cpu/16g
3 nodes: 4cpu/16g

**Comment by minghaoye** [comment]
![Screen Shot 2019-12-24 at 2 15 40 PM](https://user-images.githubusercontent.com/22934997/71397232-e4bfb280-2657-11ea-81e2-b5ee79fdfcd3.png)

可以先定义一个变量，然后给不需要执行的阶段设置执行条件，每次运行时可以指定这个变量值

![Screen Shot 2019-12-24 at 2 19 23 PM](https://user-images.githubusercontent.com/22934997/71397413-792a1500-2658-11ea-930e-c64ad94cb90a.png)

**Comment by leowucn** [comment]
嗯，这样做可以满足需求，谢谢
