### ISSUE TITLE
2.1版本 ks-apiserver和ks-installer pod 状态为CrashLoopBackOff

### ISSUE THREAD

**Issue by PYIsOk** [kubesphere/kubesphere#1703]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
2.1版本离线安装 ks-apiserver和ks-installer pod 状态为CrashLoopBackOff
**安装环境的硬件配置**
8C 16G 100G硬盘
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)
虚拟机
**错误信息或截图**
ks-apiserver 描述的events：
  Type     Reason          Age                  From                  Message
  ----     ------          ----                 ----                  -------
  Normal   SandboxChanged  63m                  kubelet, kubesphere1  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          61m (x5 over 2d23h)  kubelet, kubesphere1  Container image "10.0.3.34:5000/kubesphere/ks-apiserver:v2.1.0" already present on machine
  Normal   Created         61m (x5 over 2d23h)  kubelet, kubesphere1  Created container ks-apiserver
  Normal   Started         61m (x5 over 2d23h)  kubelet, kubesphere1  Started container ks-apiserver
  Warning  BackOff         52m (x49 over 62m)   kubelet, kubesphere1  Back-off restarting failed container
  Normal   SandboxChanged  45m                  kubelet, kubesphere1  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          44m (x4 over 45m)    kubelet, kubesphere1  Container image "10.0.3.34:5000/kubesphere/ks-apiserver:v2.1.0" already present on machine
  Normal   Created         44m (x4 over 45m)    kubelet, kubesphere1  Created container ks-apiserver
  Normal   Started         44m (x4 over 45m)    kubelet, kubesphere1  Started container ks-apiserver
  Warning  BackOff         44s (x212 over 45m)  kubelet, kubesphere1  Back-off restarting failed container

ks-installer 描述 events：
 Warning  FailedCreatePodSandBox  43m                    kubelet, kubesphere2  Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "799ed466c9235974bc8f396d22ceac16b4df231c0e346bf9cc8ab88f9b9dfa8e" network for pod "ks-installer-6cb6ddcc79-vldrx": NetworkPlugin cni failed to set up pod "ks-installer-6cb6ddcc79-vldrx_kubesphere-system" network: failed to find plugin "calico" in path [/opt/cni/bin], failed to clean up sandbox container "799ed466c9235974bc8f396d22ceac16b4df231c0e346bf9cc8ab88f9b9dfa8e" network for pod "ks-installer-6cb6ddcc79-vldrx": NetworkPlugin cni failed to teardown pod "ks-installer-6cb6ddcc79-vldrx_kubesphere-system" network: failed to find plugin "calico" in path [/opt/cni/bin]]
  Normal   SandboxChanged          43m (x2 over 43m)      kubelet, kubesphere2  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled                  41m (x4 over 43m)      kubelet, kubesphere2  Container image "10.0.3.34:5000/kubesphere/ks-installer:v2.1.0" already present on machine
  Normal   Created                 41m (x4 over 43m)      kubelet, kubesphere2  Created container installer
  Normal   Started                 41m (x4 over 43m)      kubelet, kubesphere2  Started container installer
  Warning  BackOff                 3m17s (x181 over 42m)  kubelet, kubesphere2  Back-off restarting failed container

查看/opt/cni/bin 目录有"calico" 不知为什么还报找不到

**Installer版本**
2.1

**Comment by Forest-L** [comment]
看下ks-apiserver的日志，kubectl describe pod 或者kubectl logs

**Comment by PYIsOk** [comment]
> 看下ks-apiserver的日志，kubectl describe pod 或者kubectl logs

日志如下：
kubectl logs -f ks-apiserver-69d9fd84c-ljbqx -n kubesphere-system
W1225 04:18:05.240783       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1225 04:18:05.252045       1 server.go:179] Start cache objects
Error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request

**Comment by Forest-L** [comment]
参考下这个：https://kubesphere.com.cn/forum/d/144-metrics-server-serviceunavailable/12
