### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by leowucn** [kubesphere/kubesphere#1705]
**Describe the bug(描述下问题)**
我不清楚多集群功能长什么样子，但是有一种场景可以考虑下。我在集群A部署了kubesphere，通过kubesphere部署了很多应用，这个集群A只是个测试环境，然后我想把集群A里部署的应用按照相同的配置，重新部署到集群B，应用很多的情况下，手动操作容易出现错误，导致配置不一样。如果能有个导入导出功能就好了。

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0
Kubernetes: 1.15.7

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
1 masters:  4cpu/16g
3 nodes: 4cpu/16g

**Comment by shaowenchen** [comment]
这是个不错的想法，研发团队会考虑。

就目前版本，可以使用 Velero ，以 namespace 为维度进行负载的备份和恢复，达到迁移的目的。

可以参考 https://kubesphere.com.cn/forum/d/256-kubesphere-velero

/milestones 3.0.0
