### ISSUE TITLE
应用商店 测试部署 失败

### ISSUE THREAD

**Issue by leowucn** [kubesphere/kubesphere#1706]
**Describe the bug(描述下问题)**
按照官方例子进行测试
https://kubesphere.io/docs/v2.1/zh-CN/quick-start/app-store/
在测试部署阶段，点击`部署`，结果如下
<img width="1636" alt="Snipaste_2019-12-23_17-53-27" src="https://user-images.githubusercontent.com/16133390/71350819-27788080-25ad-11ea-8b2f-8d87fbcfd6ed.png">

为什么会有权限问题？应该如何解决？

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0
Kubernetes: 1.15.7

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
1 masters:  4cpu/16g
3 nodes: 4cpu/16g

**Comment by wansir** [comment]
https://kubesphere.com.cn/forum/d/471-openpitrix-appstore-faq-and-answer

**Comment by leowucn** [comment]
嗯，可以了，希望能在2.1.1版本中考虑到这种情况并进行修复，谢谢
