### ISSUE TITLE
流量治理中，修改负载均衡算法报错

### ISSUE THREAD

**Issue by leowucn** [kubesphere/kubesphere#1710]
**Describe the bug(描述下问题)**
部署了bookinfo例子，流量治理功能中，修改productpage的负载均衡算法，第一次把默认的轮训修改为了最小链接数成功了，第二次再修改就报错了
<img width="1627" alt="Snipaste_2019-12-24_15-14-51" src="https://user-images.githubusercontent.com/16133390/71400032-83e8a800-2660-11ea-83b2-ae445010918e.png">

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0
Kubernetes: 1.15.7

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
1 masters:  4cpu/16g
3 nodes: 4cpu/16g

**Comment by leoendless** [comment]
需要修复后端接口对 resourceVersion 的处理
