### ISSUE TITLE
源码请教 关于struct FlagSet 

### ISSUE THREAD

**Issue by zhoulei232** [kubesphere/kubesphere#1713]
狗解释一下Command 是命令对象，FlagSet 指的是命令的选项对嘛。

pflags *flag.FlagSet 对于这个不太理解，persistent flags指的是具体的哪一类呢

大佬能否解释一下。

**Comment by bmingithub** [comment]
这个你还是google一下吧

**Comment by zhoulei232** [comment]
不是，这个是你们写的，定义的，和谷歌没关系啊




发自我的iPhone

------------------ 原始邮件 ------------------
发件人: bmingithub <notifications@github.com&gt;
发送时间: 2019年12月25日 11:21
收件人: kubesphere/kubesphere <kubesphere@noreply.github.com&gt;
抄送: zhoulei232 <2470576197@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[kubesphere/kubesphere] 源码请教 关于struct FlagSet  (#1713)




这个你还是google一下吧

**Comment by zryfish** [comment]
https://golang.org/pkg/flag/
