### ISSUE TITLE
点击"应用"，出现空白页面 ，控制台报错

### ISSUE THREAD

**Issue by Forget-C** [kubesphere/kubesphere#1714]
![image](https://user-images.githubusercontent.com/25631506/71430807-ebf2c900-2708-11ea-8e67-357df601c01e.png)

点击之后进入空白页面
![image](https://user-images.githubusercontent.com/25631506/71430804-e6957e80-2708-11ea-9e8d-27fcb7fea028.png)

console报错
![image](https://user-images.githubusercontent.com/25631506/71430883-5ad02200-2709-11ea-975e-a078c92b0105.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1
Kubernetes: (If KubeSphere installer used, you can skip this)
1.15.5

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

3 masters:  48cpu/512g
3 nodes: 48cpu/512g

有73个 svc，不知道是不是svc较多导致的

**Comment by leoendless** [comment]
是指这个应用下有 73 个 SVC 吗

**Comment by bmingithub** [comment]
2.1.1 验证OK
