### ISSUE TITLE
KubeSphere Console 监控中心-资源监控 报表是否支持导出Excel

### ISSUE THREAD

**Issue by yanxinquanboe** [kubesphere/kubesphere#1715]
**KubeSphere Console **

> KubeSphere Console 监控中心-资源监控 报表是否支持导出Excel
>

**Describe the bug(描述下问题)**
KubeSphere Console 监控中心-资源监控 报表是否支持导出Excel

For UI issues please also add a screenshot that shows the issue.

![2019-12-25_150553](https://user-images.githubusercontent.com/43054659/71436393-3a639000-2728-11ea-90ba-74c85cc662dd.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0

**Comment by bmingithub** [comment]
目前不支持
