### ISSUE TITLE
change the language switch button to an obvious location

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#1717]
Some users's browser language setting may not be English or Chinese, in this case, UI will display Chinese by default, we should make this switch button to an obvious location.

![image](https://user-images.githubusercontent.com/40452856/71441872-625dee00-273e-11ea-8322-01890ff3daf6.png)

**Comment by Carlosfengv** [comment]
非中文的环境默认就是英文，切换不切换意义不大，语言丰富后可以再考虑。而且语言是跟着用户来记录的信息。另外频繁切换语言的场景是？
