### ISSUE TITLE
ks控制台通过一个外部nginx转发访问请求无法登陆容器终端

### ISSUE THREAD

**Issue by knowwinter** [kubesphere/kubesphere#1719]
ks的平台是30880端口的，我在外部使用了一个nginx做了域名转发，例如ks.xxx.com，使用https转发到ks平台一个master节点的30880端口，登陆平台都没什么问题，但是在登陆容器终端时提示没有权限无法登陆，无论任何权限的帐号都无法登陆，但是如果用ks平台master实际的地址或域名解析到ks平台实际的ip地址+30880端口都可以正常访问的，是否在登陆终端判断权限时有什么来源控制还是什么问题，导致从外部nginx转发过来的请求无法访问登陆容器终端？
![image](https://user-images.githubusercontent.com/25719964/71445950-76fbaf80-2759-11ea-8899-e0d7ac4c7204.png)

**Comment by soulseen** [comment]
@wansir

**Comment by wansir** [comment]
@knowwinter 
通过nginx代理，需要配置 websocket proxy
参考，https://www.nginx.com/blog/websocket-nginx/
