### ISSUE TITLE
最新的2.0.2版本centos7.6安装问题，已经加载了最新的centos7.6的安装iso

### ISSUE THREAD

**Issue by dahaian** [kubesphere/kubesphere#1724]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
已经加载最新的centos7.6的iso，通过百度云下载的
[root@linhuiyy-pc scripts]# ./install.sh 

################################################
         KubeSphere Installer Menu
################################################
*   1) All-in-one
*   2) Multi-node
*   3) Quit
################################################
https://kubesphere.io/               2019-12-26
################################################
Please input an option: 1
1
umount: /kubeinstaller/yum_repo/iso: mountpoint not found
/etc/yum.repos.d /home/zenghong/kubesphere-all-offline-advanced-2.0.2/scripts
/etc/yum.repos.d
umount: /kubeinstaller/pip_repo/pip27/iso: mountpoint not found
umount: /kubeinstaller/k8s_repo/iso/: mountpoint not found
mount: /dev/loop0 is write-protected, mounting read-only
mount: /dev/loop1 is write-protected, mounting read-only
mount: /dev/loop2 is write-protected, mounting read-only
Loaded plugins: fastestmirror
Cleaning repos: bash
Loaded plugins: fastestmirror
Determining fastest mirrors
bash                                                                                                                                            | 2.9 kB  00:00:00     
(1/3): bash/filelists_db                                                                                                                        |  78 kB  00:00:00     
(2/3): bash/primary_db                                                                                                                          | 109 kB  00:00:00     
(3/3): bash/other_db                                                                                                                            |  66 kB  00:00:00     
Metadata Cache Created
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package docker-ce.x86_64 0:18.06.2.ce-3.el7 will be installed
--> Processing Dependency: container-selinux >= 2.9 for package: docker-ce-18.06.2.ce-3.el7.x86_64
--> Processing Dependency: libcgroup for package: docker-ce-18.06.2.ce-3.el7.x86_64
---> Package python-netaddr.noarch 0:0.7.5-9.el7 will be installed
---> Package python2-pip.noarch 0:8.1.2-9.el7 will be installed
--> Processing Dependency: python-setuptools for package: python2-pip-8.1.2-9.el7.noarch
---> Package sshpass.x86_64 0:1.06-2.el7 will be installed
--> Running transaction check
---> Package container-selinux.noarch 2:2.107-1.el7_6 will be installed
--> Processing Dependency: policycoreutils-python for package: 2:container-selinux-2.107-1.el7_6.noarch
---> Package libcgroup.x86_64 0:0.41-20.el7 will be installed
---> Package python-setuptools.noarch 0:0.9.8-7.el7 will be installed
--> Processing Dependency: python-backports-ssl_match_hostname for package: python-setuptools-0.9.8-7.el7.noarch
--> Running transaction check
---> Package policycoreutils-python.x86_64 0:2.5-29.el7_6.1 will be installed
--> Processing Dependency: policycoreutils = 2.5-29.el7_6.1 for package: policycoreutils-python-2.5-29.el7_6.1.x86_64
--> Processing Dependency: setools-libs >= 3.3.8-4 for package: policycoreutils-python-2.5-29.el7_6.1.x86_64
--> Processing Dependency: libsemanage-python >= 2.5-14 for package: policycoreutils-python-2.5-29.el7_6.1.x86_64
--> Processing Dependency: audit-libs-python >= 2.1.3-4 for package: policycoreutils-python-2.5-29.el7_6.1.x86_64
--> Processing Dependency: python-IPy for package: policycoreutils-python-2.5-29.el7_6.1.x86_64
--> Processing Dependency: libqpol.so.1(VERS_1.4)(64bit) for package: policycoreutils-python-2.5-29.el7_6.1.x86_64
--> Processing Dependency: libqpol.so.1(VERS_1.2)(64bit) for package: policycoreutils-python-2.5-29.el7_6.1.x86_64
--> Processing Dependency: libapol.so.4(VERS_4.0)(64bit) for package: policycoreutils-python-2.5-29.el7_6.1.x86_64
--> Processing Dependency: checkpolicy for package: policycoreutils-python-2.5-29.el7_6.1.x86_64
--> Processing Dependency: libqpol.so.1()(64bit) for package: policycoreutils-python-2.5-29.el7_6.1.x86_64
--> Processing Dependency: libapol.so.4()(64bit) for package: policycoreutils-python-2.5-29.el7_6.1.x86_64
---> Package python-backports-ssl_match_hostname.noarch 0:3.5.0.1-1.el7 will be installed
--> Processing Dependency: python-ipaddress for package: python-backports-ssl_match_hostname-3.5.0.1-1.el7.noarch
--> Processing Dependency: python-backports for package: python-backports-ssl_match_hostname-3.5.0.1-1.el7.noarch
--> Running transaction check
---> Package audit-libs-python.x86_64 0:2.8.4-4.el7 will be installed
---> Package checkpolicy.x86_64 0:2.5-8.el7 will be installed
---> Package libsemanage-python.x86_64 0:2.5-14.el7 will be installed
---> Package policycoreutils-python.x86_64 0:2.5-29.el7_6.1 will be installed
--> Processing Dependency: policycoreutils = 2.5-29.el7_6.1 for package: policycoreutils-python-2.5-29.el7_6.1.x86_64
---> Package python-IPy.noarch 0:0.75-6.el7 will be installed
---> Package python-backports.x86_64 0:1.0-8.el7 will be installed
---> Package python-ipaddress.noarch 0:1.0.16-2.el7 will be installed
---> Package setools-libs.x86_64 0:3.3.8-4.el7 will be installed
--> Finished Dependency Resolution
Error: Package: policycoreutils-python-2.5-29.el7_6.1.x86_64 (bash)
           Requires: policycoreutils = 2.5-29.el7_6.1
           Installed: policycoreutils-2.5-29.el7.x86_64 (@anaconda)
               policycoreutils = 2.5-29.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Error: Install the base packages failed!
sudo: pip: command not found
Error: Install the base packages failed!
grep: /etc/lsb-release: No such file or directory
./all-in-one.sh: line 36: ansible-playbook: command not found
failed!

**安装环境的硬件配置**
cup 8核
内存 16g
硬盘300g

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)
是vmware虚拟机
**错误信息或截图**
Error: Package: policycoreutils-python-2.5-29.el7_6.1.x86_64 (bash)
           Requires: policycoreutils = 2.5-29.el7_6.1
           Installed: policycoreutils-2.5-29.el7.x86_64 (@anaconda)
               policycoreutils = 2.5-29.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Error: Install the base packages failed!
sudo: pip: command not found
Error: Install the base packages failed!
grep: /etc/lsb-release: No such file or directory
./all-in-one.sh: line 36: ansible-playbook: command not found
failed!
**Installer版本**
最新的2.0.2版本

**Comment by FeynmanZhou** [comment]
现在最新的版本是 v2.1.0，为什么还安装 2.0.2？ @dahaian

**Comment by dahaian** [comment]
@FeynmanZhou 2.1.0的好像没离线安装版本的？

**Comment by FeynmanZhou** [comment]
有，https://kubesphere.com.cn/docs/v2.1/zh-CN/installation/intro/#%E5%AE%89%E8%A3%85%E5%9C%A8-linux
![image](https://user-images.githubusercontent.com/40452856/71461464-d950c080-27ea-11ea-8910-4892fc7bfc80.png)

**Comment by dahaian** [comment]
@FeynmanZhou 哦，我是all in one模式的

**Comment by FeynmanZhou** [comment]
@dahaian 下载地址都是一样的，同样可以参考上面的链接
