### ISSUE TITLE
elasticsearch-logging-discovery 会自己变成0副本

### ISSUE THREAD

**Issue by Forget-C** [kubesphere/kubesphere#1725]
**Describe the bug(描述下问题)**

kubesphere-logging-system 中的 elasticsearch-logging-discovery 每过一段时间就会自己变成0副本
![image](https://user-images.githubusercontent.com/25631506/71511270-b1398e00-28cc-11ea-8439-882651372fba.png)
去进群中查看，确实时变成了0副本。
调整副本数后可以启动
![image](https://user-images.githubusercontent.com/25631506/71511308-d6c69780-28cc-11ea-9084-6de66cfa2a82.png)
但是过段时间又会变成0副本
**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1
Kubernetes: (If KubeSphere installer used, you can skip this) 1.15.5

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
3 masters:  48cpu/256g
3 nodes: 48cpu/512g

**Comment by huanggze** [comment]
应该不会。有什么 debug 信息吗？

**Comment by Forget-C** [comment]
是看k8s的调度日志么？ 我不太清楚该从哪里debug， 能提供一个思路吗

**Comment by huanggze** [comment]
```
kubectl describe -n kubesphere-monitoring-system sts elasticsearch-logging-discovery
kubectl logs -n kubesphere-monitoring-system elasticsearch-logging-discovery-0 --previous
```
