### ISSUE TITLE
tutorial issue: 1.5

### ISSUE THREAD

**Issue by anothernetwork** [kubesphere/kubesphere#1727]
**General remarks**
1.5. "Fill in the new user's basic information. Set the username as user-manger; select the role user-manger. Other information can be customized. Then click Create."
Impossible! should be:

1.5. 
Click **Create**:
then:
Set the username as **user-manger;** select the role **user-manger**. Other information can be customized. 
Then click OK.
**Expected behavior(预期行为)**
You create a new user

**Comment by huanggze** [comment]
https://github.com/kubesphere/kubesphere.github.io/blob/master/blog/advanced-2.0/en/admin-quick-start.md

/kind documentation

**Comment by FeynmanZhou** [comment]
It's outdated, close this issue since it's duplicate, we will update the English version of v2.1 docs.
