### ISSUE TITLE
2.1 looks like this

### ISSUE THREAD

**Issue by anothernetwork** [kubesphere/kubesphere#1729]
**Describe the bug(描述下问题)**
![image](https://user-images.githubusercontent.com/48926486/71536918-50827380-2915-11ea-8567-d401a902c2a8.png)

**Expected behavior(预期行为)**
![image](https://user-images.githubusercontent.com/48926486/71536916-43fe1b00-2915-11ea-95dc-62e1f4f73c70.png)
and:
![image](https://user-images.githubusercontent.com/48926486/71536938-79a30400-2915-11ea-8f31-bf184fbf68fb.png)
and:

![image](https://user-images.githubusercontent.com/48926486/71536967-dc949b00-2915-11ea-965a-d482fc454cf2.png)

**Comment by FeynmanZhou** [comment]
It's outdated, close this issue since it's duplicate, we will update the English version of v2.1 docs soon.
