### ISSUE TITLE
Kubesphere installer. Helm tls issue

### ISSUE THREAD

**Issue by Medd1er** [kubesphere/kubesphere#1734]
Greetings!
Having trouble with installing kubesphere ontop of K8s cluster using tls for helm. The thing is that kubesphere tries to run helm and gets an error: **Transport is closing** which is related to --tls key accordingly. I tried to add **HELM_TLS_ENABLE=true** environment variable to installer pod, but no luck and I get the same problem.
Did I miss something or, perhaps, you do have some sort of workaround?

Thank you in advance!

**Comment by FeynmanZhou** [comment]
@Medd1er Hi, we suggest you to close the TLS in your helm client, then you can follow the [ks-installer](https://github.com/kubesphere/ks-installer) to install KubeSphere on your on your K8s cluster.

**Comment by FeynmanZhou** [comment]
@Medd1er Have you solved this issue yet? Please let me know if you need help, thanks.

**Comment by Medd1er** [comment]
@FeynmanZhou hi! thanks a lot for your help, it works(installs) without tls, but I need to use it in terms of environment. If there is no other way to use tls - we can close this issue

**Comment by FeynmanZhou** [comment]
@Medd1er Hey, have you joined KubeSphere [slack channel](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE)?
