### ISSUE TITLE
ks-account这个pod一直起不来

### ISSUE THREAD

**Issue by ltgentoo** [kubesphere/kubesphere#1741]
ks-account这个pod一直起不来,奇怪的问题，之前起来过，有一次休眠之后这个pod就起不来
kube-system和kubesphere-system下的其他pod都正常，看这个容器的日志，应该是不能解析redis的dns，日志如下

`nc: bad address 'redis.kubesphere-system.svc'
waiting for redis

nc: bad address 'redis.kubesphere-system.svc'
waiting for redis
waiting for redis
nc: bad address 'redis.kubesphere-system.svc'
nc: bad address 'redis.kubesphere-system.svc'
waiting for redis
`

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
all in one:  4cpu/16g

**Comment by weiliang-ms** [comment]
kubectl get pod -A 查看pod的状态呢?

**Comment by ljh2057** [comment]
`kubectl edit deploy ks-account -n kubesphere-system`
修改所有的` busybox` tag 为 `glibc`

**Comment by JokerDevops** [comment]
我也遇到了这个问题 @ljh2057  没有找到 `busybox` 这个tag啊

**Comment by FeynmanZhou** [comment]
@wansir Please help to look at this issue. It looks like the cluster has a DNS that is not available?

**Comment by JokerDevops** [comment]
My DNS server is normal, I started a redis pod in the same domain space and then used redis-cli to link to the built-in redis. But not ks-apigateway @FeynmanZhou

**Comment by BlueSky-YJS** [comment]
nc: bad address 'redis.kubesphere-system.svc'
waiting for redis
nc: bad address 'redis.kubesphere-system.svc'
waiting for redis
nc: bad address 'redis.kubesphere-system.svc'
waiting for redis
waiting for redis
nc: bad address 'redis.kubesphere-system.svc'
waiting for redis
nc: bad address 'redis.kubesphere-system.svc'
nc: bad address 'redis.kubesphere-system.svc'
waiting for redis
nc: bad address 'redis.kubesphere-system.svc'
waiting for redis
nc: bad address 'redis.kubesphere-system.svc'
waiting for redis
nc: bad address 'redis.kubesphere-system.svc'
waiting for redis 

我的也是这样，那个ks-account  一直在init  然后这个ks-apigateway一直不能正常运行。。不知道这个怎么解决呢。？

**Comment by wansir** [comment]
https://github.com/kubesphere/ks-installer/issues/33
https://github.com/kubesphere/kubesphere/issues/1555

**Comment by JokerDevops** [comment]
close

**Comment by moyee** [comment]
redis 可以用本地的，
用ep,svc 的方式桥接一个就可以了

**Comment by benjaminhuo** [comment]
Pls upgrade to ks v3.0.0, there is no ks-account anymore
