### ISSUE TITLE
Macbook Pro, Kubernetes: v1.14.8, Helm: v3.0.2 kubesphere-minimal.yaml 安装失败

### ISSUE THREAD

**Issue by quzhixue-Kimi** [kubesphere/kubesphere#1743]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

Hi there,

Macbook Pro 2019年款, 16G内存, 4核, 硬盘空间都足够的情况下,
参考https://kubesphere.com.cn/docs/v2.1/zh-CN/installation/install-on-k8s/
运行kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/kubesphere-minimal.yaml

根据kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l app=ks-install -o jsonpath='{.items[0].metadata.name}') -f

得到以下日志错误:

TASK [preinstall : check helm status] ******************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm list\n", "delta": "0:00:00.513794", "end": "2020-01-08 03:03:07.672434", "msg": "non-zero return code", "rc": 1, "start": "2020-01-08 03:03:07.158640", "stderr": "Error: could not find tiller", "stderr_lines": ["Error: could not find tiller"], "stdout": "", "stdout_lines": []}
...ignoring

TASK [preinstall : Stop if Helm is not available] ******************************
fatal: [localhost]: FAILED! => {
    "assertion": "helm_check.rc == 0",
    "changed": false,
    "evaluated_to": false,
    "msg": "Helm is not available"
}

但是我本地Helm是有的,并且PATH环境变量也存在
/usr/local/bin/helm

请问是我少了什么步骤么?

前置步骤中的 '集群已有存储类型（StorageClass），若还没有存储类型可参考" 请问是什么意思?和这个错误有关么?

BR
Kimi

**Comment by quzhixue-Kimi** [comment]
helm init --service-account=tiller --tiller-image=gcr.io/kubernetes-helm/tiller:v2.14.1   --history-max 300

rror: unknown flag: --service-account

**Comment by quzhixue-Kimi** [comment]
ks-apigateway and node-exporter container failed to run and, ks-account container is in init status.

**Comment by calvinyv** [comment]
https://kubesphere.com.cn/forum/d/555-kubesphere-minimal-2-1

看下这个有帮助吗

**Comment by quzhixue-Kimi** [comment]
Hi @calvinyv

多谢,多谢.

BR
Kimi

**Comment by FeynmanZhou** [comment]
Helm: v3.0.2？ 目前还不支持 Helm v3，你看看文档里的前提条件 @quzhixue-Kimi
