### ISSUE TITLE
The return button in DevOps pipeline directs to 403

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#1744]
Click the return button in DevOps pipeline, it will direct the page to Not found page and 403 outputs.
![image](https://user-images.githubusercontent.com/40452856/71952530-fb4e3800-3219-11ea-9d1e-0db55c24b9b5.png)
![image](https://user-images.githubusercontent.com/40452856/71952542-02754600-321a-11ea-98be-8f91a712fdb9.png)

**Comment by harrisonliu5** [comment]
The back icon has been deleted. Its function is the same as that of the browser’s back button, and the breadcrumbs are better than the back button.

**Comment by rayzhou2017** [comment]
verified
