### ISSUE TITLE
系统默认安装的项目中无法设置网关，新建工作负载等

### ISSUE THREAD

**Issue by sirennishi2** [kubesphere/kubesphere#1745]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
在安装完成后，希望minio发布出去，其他命名空间或者项目直接调用，但是在kubesphere-system项目下，无法创建网关配置。
**安装环境的硬件配置**
VMware虚拟机，三个节点。

**错误信息或截图**

**Installer版本**
2.1.0

**Comment by shaowenchen** [comment]
kubesphere-system 是系统相关组件，配置不会完全对外开放。

可以直接 minio.kubesphere-system.svc:9000
账户 openpitrixminioaccesskey : openpitrixminiosecretkey 进行使用
