### ISSUE TITLE
在新建的命名空间中，创建Minio应用不成功

### ISSUE THREAD

**Issue by sirennishi2** [kubesphere/kubesphere#1746]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
创建应用后，总是提示“”容器退出，kubelet正在将它重启“”
**安装环境的硬件配置**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
![image](https://user-images.githubusercontent.com/52621475/71955316-ea55f480-3222-11ea-8cc1-c1996663eb21.png)

**Installer版本**
2.1.0

**Comment by shaowenchen** [comment]
调整下项目配额，可能是CPU或者内存不够，被强制终止了。
