### ISSUE TITLE
默认生成的CA证书有效期是多长时间，是否支持修改？以及续期？

### ISSUE THREAD

**Issue by UnknowName** [kubesphere/kubesphere#1754]
使用的版本为v2.1

**Comment by huanggze** [comment]
可以输入以下命令查看 k8s 证书有效期：
`openssl x509 -in /etc/kubernetes/pki/ca.crt -noout -text`

k8s 证书管理请参考：
`https://kubernetes.io/docs/tasks/tls/certificate-rotation/`
