### ISSUE TITLE
KubeSphere's workspace ,namespaces and workload need description

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1756]
# Workspace

![image](https://user-images.githubusercontent.com/22350668/72231332-e1379f80-35f5-11ea-99a8-7b0d7690fe9b.png)

# Namespace

![2020-01-13_11-12](https://user-images.githubusercontent.com/22350668/72231320-cf55fc80-35f5-11ea-83e0-2288bd8672f3.png)

# Workload
![image](https://user-images.githubusercontent.com/22350668/72588068-16175f80-3932-11ea-9b45-c0db3e081505.png)

# ConfigMap
![image](https://user-images.githubusercontent.com/22350668/72619355-028ee780-3978-11ea-9928-361facbc38ad.png)

# Secret
![image](https://user-images.githubusercontent.com/22350668/72619375-10dd0380-3978-11ea-9776-e912dd2d452d.png)

# Job

# Ingress

**Comment by leoendless** [comment]
需要提供相关文案，并在 ks-installer 中对应模板加上描述
``metadata.annotations['kubesphere.io/description']``

**Comment by FeynmanZhou** [comment]
@huanggze  We will provide description in Docs, will let you know when it ready.
