### ISSUE TITLE
Java应用构建时间长

### ISSUE THREAD

**Issue by WangBenpeng** [kubesphere/kubesphere#1759]
springboot应用构建时间3分钟，下载速度很慢，请问正常吗？或者有其他的解决办法吗？
`+ mvn package
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.1.10.RELEASE/spring-boot-starter-parent-2.1.10.RELEASE.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.1.10.RELEASE/spring-boot-starter-parent-2.1.10.RELEASE.pom (9.5 kB at 7.8 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.1.10.RELEASE/spring-boot-dependencies-2.1.10.RELEASE.pom                  
Downloaded from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.1.10.RELEASE/spring-boot-dependencies-2.1.10.RELEASE.pom (123 kB at 187 kB/s)
`

**Comment by weiliang-ms** [comment]
换源

**Comment by weiliang-ms** [comment]
[更换为阿里云源](https://blog.csdn.net/genius_pig/article/details/95402325)

**Comment by WangBenpeng** [comment]
> [更换为阿里云源](https://blog.csdn.net/genius_pig/article/details/95402325)

在IDEA中很快，设置的是阿里云源，在kube中没找到配置的地方，请问在哪里修改？

**Comment by weiliang-ms** [comment]
> > [更换为阿里云源](https://blog.csdn.net/genius_pig/article/details/95402325)
> 
> 在IDEA中很快，设置的是阿里云源，在kube中没找到配置的地方，请问在哪里修改？

你是devops工程么，我的devops是把settings.xml放到项目里了

**Comment by WangBenpeng** [comment]
> > > [更换为阿里云源](https://blog.csdn.net/genius_pig/article/details/95402325)
> > 
> > 
> > 在IDEA中很快，设置的是阿里云源，在kube中没找到配置的地方，请问在哪里修改？
> 
> 你是devops工程么，我的devops是把settings.xml放到项目里

> > > [更换为阿里云源](https://blog.csdn.net/genius_pig/article/details/95402325)
> > 
> > 
> > 在IDEA中很快，设置的是阿里云源，在kube中没找到配置的地方，请问在哪里修改？
> 
> 你是devops工程么，我的devops是把settings.xml放到项目里了

是dev工程，我试一下这样设置，谢谢！
