### ISSUE TITLE
界面是否可以添加初始化容器（initcontainer）

### ISSUE THREAD

**Issue by guoh1988** [kubesphere/kubesphere#1762]
在部署服务或者deploy的时候容器添加并没有initcontainer，感觉部署带有initcontainer的服务很不方便

![72241452-df83d100-3621-11ea-95b3-511551a3e1f2](https://user-images.githubusercontent.com/28557169/72321666-71054880-36df-11ea-9291-861ab2b5f0c9.PNG)

**Comment by yunkunrao** [comment]
Good news! This feature will be supported in 2.1.1 release. :smile:

**Comment by calvinyv** [comment]
supported in 2.1.1
