### ISSUE TITLE
应用商店charts解析问题

### ISSUE THREAD

**Issue by huanglei288766** [kubesphere/kubesphere#1770]
**问题描述**
应用商店chart的values无法载入，无法部署。
第三方仓库chart的values可以载入，可以部署，无法实例化。

**安装环境的硬件配置**
aws云主机，Ubuntu18。
在kubernetes上部署的ks.

**错误信息或截图**

![解析问题](https://user-images.githubusercontent.com/41362385/72340984-234f0700-3704-11ea-99a8-03d1ea91d18c.png)

**Installer版本**
2.1.0

**Comment by leoendless** [comment]
> 应用商店chart的values无法载入，无法部署。

这里的 chart 是哪个应用呢

**Comment by huanglei288766** [comment]
> > 应用商店chart的values无法载入，无法部署。
> 
> 这里的 chart 是哪个应用呢

是ks官方文档里的emqx，其他应用也有这个问题。

**Comment by leoendless** [comment]
这个问题在  https://github.com/kubesphere/console/pull/99 里修复了，会在 v2.1.1 正式 release。

**Comment by huanglei288766** [comment]
> 这个问题在 [kubesphere/console#99](https://github.com/kubesphere/console/pull/99) 里修复了，会在 v2.1.1 正式 release。

thank u.
今天在做测试的时候我发现并不是所有仓库都会有这种情况，在使用了阿里云的仓库进行了几次部署，都成功了。
