### ISSUE TITLE
KubeSphere 2.1.0 安装失败

### ISSUE THREAD

**Issue by qqqlllei** [kubesphere/kubesphere#1773]
MSG:

Error from repoquery: ['/bin/repoquery', '--show-duplicates', '--plugins', '--quiet', '--disablerepo', '', '--enablerepo', '', '--qf', '%{name}|%{epoch}|%{version}|%{release}|%{arch}|%{repoid}', 'container-selinux']: Not using downloaded docker-ce/repomd.xml because it is older than what we have:
  Current   : Fri Nov 15 01:47:37 2019
  Downloaded: Wed Oct  9 00:45:37 2019
Could not match packages: failure: repodata/repomd.xml from docker-engine: [Errno 256] No more mirrors to try.
https://yum.dockerproject.org/repo/main/centos/7/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden

2020-01-15 17:55:33,546 p=14222 u=root |  fatal: [master]: FAILED! => {
    "changed": false
}

**Comment by yunkunrao** [comment]
Hi, could you please provide more details about your installation environment, such as OS, distribution etc.

**Comment by qqqlllei** [comment]
自己好了，猜想是https://yum.dockerproject.org/repo/main/centos/7/repodata/repomd.xml 这个地址不能访问了，点击进去响应码是403，现在可以了。

**Comment by qqqlllei** [comment]
解决
