### ISSUE TITLE
keep max old branches in devops scm is not work

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1775]
reproduce steps:
1、Create a scm，git code repo select ellaye/devops-branch-test
2、Max old branches to keep is 2
3、Discover Branches is All branches
4、Click create button
Exceptd result: scan branch is 2
Actual result: scan branch is 4

![image](https://user-images.githubusercontent.com/57089340/72490822-3d4b2f80-3853-11ea-84f0-242085dc6c2d.png)
![image](https://user-images.githubusercontent.com/57089340/72490930-800d0780-3853-11ea-89fa-553e645703d3.png)
![image](https://user-images.githubusercontent.com/57089340/72491281-864fb380-3854-11ea-9887-145217197fc3.png)

**Comment by runzexia** [comment]
not a bug
/close
Consider one of the following scenarios.
`create pipeline(keep 2 branch) -> scan scm(4 branch) -> quick re scan scm -> clean 2 branch?`

In this case, if re scan will delete the branch, some branches may be deleted before the user could see it.

Therefore, in the implementation, only the creation of a new branch event will trigger the cleaning strategy.
like
`create pipeline(keep 2 branch) -> scan scm(4 branch) -> quick re scan scm(not change) -> create new branch in scm(5 branch) -> clean 3 branch`
