### ISSUE TITLE
2.1.0项目中存储卷容量显示错误

### ISSUE THREAD

**Issue by scott-wong** [kubesphere/kubesphere#1777]
**General remarks**

项目中存储卷容量显示错误

**Describe the bug(描述下问题)**

基础设施中的容量
![image](https://user-images.githubusercontent.com/1947609/72491998-b304ca80-3856-11ea-9d61-c4f361f1f653.png)

项目存储卷容量显示
![image](https://user-images.githubusercontent.com/1947609/72492187-4938f080-3857-11ea-9d3d-ea819a6e7db8.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0

**Environment(环境的硬件配置)**
allinone
1 masters:  4cpu/16g

**To Reproduce(复现步骤)**
通过helm安装redis-ha后发现的。

**Expected behavior(预期行为)**

**Comment by min-zh** [comment]
@scott-wong @zryfish On storage provisioner **openebs.io/local**， multi **pvc**s share one **device**.  In the logic of  kubelet,  it use **unix.Statfs** to get capacity and innode of pv, it's almost the same as command **df**. So the data of pvc's capacity&usage&innode is as the same of the device of the pvc, and it has difference with the pvc's capacity.

**Comment by benjaminhuo** [comment]
so this is an openebs limitation? @min-zh
