### ISSUE TITLE
days to keep old branches in devops scm is not work

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1778]
reproduce steps:
1、Create a scm，git code repo select ellaye/devops-branch-test
2、days to keep old items is 2
3、Discover Branches is All branches
4、Click create button
Exceptd result: scan branch is 1
Actual result: scan branch is 4

![image](https://user-images.githubusercontent.com/57089340/72491516-39201180-3855-11ea-9656-3c7f4be18be1.png)
![image](https://user-images.githubusercontent.com/57089340/72491604-856b5180-3855-11ea-97a8-8044efac4ecd.png)

**Comment by runzexia** [comment]
not a issue 
this days means Days of the pipeline
/close
