### ISSUE TITLE
There is no PullRequest 

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1779]
reproduce steps:
1、Create a scm，git code repo select ellaye/devops-branch-test
2、Discover Branches select All branches
3、Pull Stategy select [Source code version of PR merged with target branch]
4、Click create button
Exceptd result: there is one PullRequest
Actual result: there is no PullRequest

![image](https://user-images.githubusercontent.com/57089340/72494583-4641fe00-385f-11ea-866d-37b8c52ddd94.png)
![image](https://user-images.githubusercontent.com/57089340/72494587-4e9a3900-385f-11ea-8d2a-d1165ea6f280.png)

**Comment by runzexia** [comment]
https://github.com/jenkinsci/github-branch-source-plugin/pull/264

upstream bug

**Comment by ellaye** [comment]
fixed
/close
