### ISSUE TITLE
There is only one pullRequest when select [Two pipelines are created when PR is discovered]

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1780]
reproduce steps:
1、Create a scm，git code repo select ellaye/devops-branch-test
2、Discover Branches select All branches
3、Pull Stategy select [Two pipelines are created when PR is discovered......]
4、Click create button
Exceptd result: there is two PullRequest
Actual result: there is one PullRequest

![image](https://user-images.githubusercontent.com/57089340/72494829-092a3b80-3860-11ea-82d7-bf22e1ed8a76.png)
![image](https://user-images.githubusercontent.com/57089340/72494897-468ec900-3860-11ea-9517-7cabb9bcc349.png)

**Comment by runzexia** [comment]
This problem needs to be resolved in the upstream (jenkinsci). It is possible to milestone 3.0.0.

**Comment by runzexia** [comment]
same ref: https://github.com/kubesphere/kubesphere/issues/1780

**Comment by ellaye** [comment]
fixed
/close
