### ISSUE TITLE
The commit is empty in Branch when repository is svn

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1783]
reproduce steps:
1、create a scm，code repo select svn
2、type select svn
3、click OK button
4、after a few minutes, check Branch
Exceptd result: the commit is not empty
Actual result: the commit is  empty
![image](https://user-images.githubusercontent.com/57089340/72501481-e012a680-3871-11ea-945c-cc933805203b.png)

**Comment by minghaoye** [comment]
none commit data in this page, i'll remove this header

**Comment by ellaye** [comment]
fixed
/colse
