### ISSUE TITLE
什么样的服务才能使用流量治理

### ISSUE THREAD

**Issue by yuenwah** [kubesphere/kubesphere#1787]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
按示例的应用是没问题，然后我自己从应用商店部署了个nginx，想用这个nginx模拟流量治理但不能操作，点击灰度发布的时候无法选择 组件，什么样的应用才能识别为支持灰度的组件
我目前是想部署一个v1版本的nginx，然后灰度到v2，其实镜像不变，我只是通过修改html判断
**安装环境的硬件配置**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
![image](https://user-images.githubusercontent.com/34834139/72581764-6931e800-391b-11ea-8bc6-4dc50a3a6025.png)
![image](https://user-images.githubusercontent.com/34834139/72581876-cded4280-391b-11ea-97a9-45475fa3bbb2.png)

**Installer版本**
KubeSphere 版本 : v2.1.0

**Comment by shaowenchen** [comment]
需要创建一个 nginx 的 ingress 应用，可以参考下面的文档。
https://kubesphere.com.cn/docs/v2.1/zh-CN/quick-start/ingress-canary/#___gatsby
