### ISSUE TITLE
centos8.1安装报错

### ISSUE THREAD

**Issue by bmwcyq520** [kubesphere/kubesphere#1788]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
fatal: [ks-allinone]: FAILED! => {
    "changed": false,
    "cmd": "dnf install -y python2-dnf",
    "rc": 1
}
STDOUT:
上次元数据过期检查：0:05:51 前，执行于 2020年01月17日 星期五 15时21分08秒。
未找到匹配的参数： python2-dnf
STDERR:
错误：没有任何匹配: python2-dnf
MSG:
错误：没有任何匹配: python2-dnf
**安装环境的硬件配置**
虚拟机环境centos8.1  ,刚装的干净虚拟机.没有安装任何软件,跟任何操作,直接安装报错.
安装的是all-in-one.
$ curl -L https://kubesphere.io/download/stable/v2.1.0 > installer.tar.gz \
&& tar -zxf installer.tar.gz && cd kubesphere-all-v2.1.0/scripts
 ./install.sh

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
![图片](https://user-images.githubusercontent.com/4714200/72592748-3cdb9300-393e-11ea-9955-85e79c46f27e.png)

**Installer版本**

**Comment by shaowenchen** [comment]
目前暂时不支持 CentOS 8，可以关注下这个项目 https://github.com/kubesphere/ks-installer ，后续会支持。

**Comment by bmwcyq520** [comment]
好的,谢谢!
