### ISSUE TITLE
openpitrix安装时机问题。

### ISSUE THREAD

**Issue by hl8437** [kubesphere/kubesphere#1790]
**问题描述**
以下是我的两种安装openpitrix的方式
1. 最小化安装ks，然后修改configmap，将openpitrix设置为true
2. 安装ks时候直接将openpitrix设置为true。
第一种方式会导致一些安装不顺畅，比如openpitrix-system空间下的一些job卡在等待mysql和etcd的initContainer上。

**安装环境的硬件配置**
aws云主机，ubuntu18
在k8s上部署ks

**错误信息或截图**

**Installer版本**
2.1

**Comment by FeynmanZhou** [comment]
目前第二种安装方式是否可以安装成功呢？ @huanglei288766

**Comment by huanglei288766** [comment]
> 目前第二种安装方式是否可以安装成功呢？ @huanglei288766

可以
