### ISSUE TITLE
The storage class is empty in createing Volume

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1791]
Reproduces steps:
1、create storage class more than 10
2、create a pvc，check storage class
excpeted result ：the storage class is  the default sc
actual result：the storage is empty

![image](https://user-images.githubusercontent.com/57089340/72674074-85fe2500-3aad-11ea-8d10-653f7a9fd14d.png)

**Comment by calvinyv** [comment]
API limitation because of result set, and user could still choose the sc which he want to use, so mark as low priority and move to next release.

**Comment by calvinyv** [comment]
@min-zh pls double check if this issue is fixed or not in 3.0

**Comment by benjaminhuo** [comment]
fixed in 3.0? @min-zh

**Comment by stoneshi-yunify** [comment]
this issue is fixed in 3.1, not 3.0.

**Comment by zryfish** [comment]
fixed in v3.1.0
/close
