### ISSUE TITLE
监控组件可插拔

### ISSUE THREAD

**Issue by hl8437** [kubesphere/kubesphere#1797]
**问题描述**
当前2.1版本下，即使最小化安装也会进行监控组件的自动安装。
因为线上已经有相同的组件，并且进行了个性化配置，所以必然会产生一些冲突。

**建议**
1. 将monitoring相关组件做成可插拔
2. 将monitoring相关组件做成可以接入现有系统
3. 或者提供可以配置monitoring组件的方法

**Comment by huanggze** [comment]
2.1 很多功能依赖监控，所以暂未开放监控可拔插。但可以尝试修改 ks-apiserver 的参数，切换到自由的 Prometheus
