### ISSUE TITLE
All-in-one 安装报错  centos 7.5  离线安装

### ISSUE THREAD

**Issue by wangweiIT** [kubesphere/kubesphere#1798]
fatal: [ks-allinone]: FAILED! => {
    "changed": true, 
    "cmd": "systemctl daemon-reload && service docker restart", 
    "delta": "0:00:00.349668", 
    "end": "2020-01-21 09:13:49.189002", 
    "rc": 1, 
    "start": "2020-01-21 09:13:48.839334"
}

STDERR:

Redirecting to /bin/systemctl restart docker.service
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

MSG:

non-zero return code

PLAY RECAP ************************************************************************************************************************************
ks-allinone                : ok=4    changed=2    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

**Comment by chinazj** [comment]
关闭防火墙和selinux
