### ISSUE TITLE
在k8s集群上安装ks2.1.0，启动组件遇到的问题

### ISSUE THREAD

**Issue by F-liuhui** [kubesphere/kubesphere#1800]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
原k8s集群没有.csr和.key文件相关证书文件，只有.pem格式的文件，例如kube-ca.pem和kube-ca-key.pem文件,要启动devops组件，secret要如何创建？在ks-installer工程下提过相关issue,没人解答，希望这里能有人解答一下。遇到问题得不到解答不利于ks的推广
**安装环境的硬件配置**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**

**Installer版本**

**Comment by huanggze** [comment]
请问你是通过什么方式安装的 k8s？

/help-wanted
/milestone 3.0.0
/area devops
/assign @runzexia

**Comment by F-liuhui** [comment]
通过rancher安装的k8s集群，证书都是.pem格式的，二进制安装的也是.pem格式的证书

**Comment by F-liuhui** [comment]
> 请问你是通过什么方式安装的k8s？
> 
> / help希望
> /里程碑3.0.0
> /区域devops
> / assign @runzexia

通过rancher安装的k8s整合，证书都是.pem格式的，二进制安装的也是.pem格式的证书
