### ISSUE TITLE
前端关于中的版本号没更新、logo上的copyright依然在

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#1802]
版本：2.1.1
问题：

![image](https://user-images.githubusercontent.com/43693241/73625438-ccdc4500-467f-11ea-95fb-03fe70823ede.png)

1，当前版本信息应该更新为 2.1.1
2，logo 右上角的版权信息 R 应该去掉

/area console
/assign @leoendless 
/milestone 2.1.1

**Comment by leoendless** [comment]
@pixiake 版本问题需要这里更改

https://github.com/kubesphere/ks-installer/blob/4b4d89459c1a3e806741655015b1a05218a6636f/roles/ks-core/ks-core/defaults/main.yaml#L6

**Comment by leoendless** [comment]
@Carlosfengv @calvinyv 这个logo 里的 R 应该有吗

**Comment by shaowenchen** [comment]
> @Carlosfengv @calvinyv 这个logo 里的 R 应该有吗

这个上次讨论的是，开源项目的 logo 都没有 R。需要确认、统一下

**Comment by leoendless** [comment]
logo 问题已修复
