### ISSUE TITLE
应用商店部署时，无法选择企业空间下的项目

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#1803]
版本：2.1.1
问题：

企业空间 a 下有三个项目，但是在应用商店部署应用时，无法选择项目

![image](https://user-images.githubusercontent.com/43693241/73628969-b688b600-468c-11ea-861f-73949dca7da8.png)

![image](https://user-images.githubusercontent.com/43693241/73628985-c0aab480-468c-11ea-8b85-2b9337faccf8.png)

/area console
/area app-management
/assign @pengcong06  @leoendless

**Comment by leoendless** [comment]
@wansir  创建项目没有在 op 里创建对应的runtime

**Comment by wansir** [comment]
https://github.com/openpitrix/openpitrix/issues/983

**Comment by zheng1** [comment]
Fixed at https://github.com/openpitrix/runtime-provider-kubernetes/commit/e5097e2adcf00d21aa2f916dfecd25c0ec2a0d8c

**Comment by shaowenchen** [comment]
OK
/close
