### ISSUE TITLE
Devops and logging upgrade error when upgrade from ks2.1.0 to ks2.1.1 

### ISSUE THREAD

**Issue by ellaye** [kubesphere/kubesphere#1807]
steps to reproduce
1.install ks2.1.0
2.upgrage to ks2.1.1
excepted result: upgrade success
actual result: devops and logging upgrade error
error info:
 \"apps/v1beta2\"",
      "stderr_lines": [
        "Error: UPGRADE FAILED: failed decoding reader into objects: unable to recognize \"\": no matches for kind \"Deployment\" in version \"apps/v1beta2\""
"stderr": "Error: UPGRADE FAILED: failed decoding reader into objects: unable to recognize \"\": no matches for kind \"Deployment\" in version \"apps/v1beta2\"",
      "stderr_lines": [
        "Error: UPGRADE FAILED: failed decoding reader into objects: unable to recognize \"\": no matches for kind \"Deployment\" in version \"apps/v1beta2\""
![image](https://user-images.githubusercontent.com/57089340/73710188-4470a980-473e-11ea-92f5-bc547e304698.png)

**Comment by pixiake** [comment]
https://github.com/kubesphere/kubesphere/issues/1822

**Comment by ellaye** [comment]
用最新安装包升级遇到2个问题：
问题一：安装的时候configmap里面没有sc
问题二：安装升级完devops升级失败，
![image](https://user-images.githubusercontent.com/57089340/74150290-8c169a00-4c44-11ea-89ac-8a1095328d4d.png)

**Comment by pixiake** [comment]
https://github.com/kubesphere/ks-installer/issues/619

**Comment by ellaye** [comment]
fixed
/close
