### ISSUE TITLE
应用商店部署失败，相关镜像 not found

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#1808]
版本：2.1.1

问题：

![image](https://user-images.githubusercontent.com/43693241/73713797-9e2aa100-4749-11ea-948e-50587022017e.png)

打开应用商店页面报错，查看相关 Pod 的 event 发现相关镜像无法拉取；

![image](https://user-images.githubusercontent.com/43693241/73713694-4855f900-4749-11ea-9a12-e40d98728ae1.png)

初步判断：

镜像 tag 错误，openpitrix/openpitrix:latest 可以拉取。

/area app-management 
/milestone 2.1.1
/assign @zheng1

**Comment by zheng1** [comment]
Fixed at https://github.com/kubesphere/ks-installer/pull/582

**Comment by shaowenchen** [comment]
OK
/close
