### ISSUE TITLE
B2i service failed to build the image

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1809]
Steps ：
1、Install 2.1.1 through installer and enable the devops component；
2、Create a project, create a key in the configuration center；
3、Build a new service through the artifact，for example, select jar；
4、Upload Artifacts；
5、Setting up the build environment，and set the  image name , tag  and target image repository；

Test Results：
Build image failed
![image](https://user-images.githubusercontent.com/7677050/73719425-5ceebd00-475a-11ea-99b9-fbf8b773705d.png)
![image](https://user-images.githubusercontent.com/7677050/73719444-709a2380-475a-11ea-8986-cced3cd48c39.png)

**Comment by runzexia** [comment]
Any more information?
Such as the status/logs of the b2i container

**Comment by mayuhope** [comment]
使用最新的installer测试验证，已经没有这个问题，因此关闭issue
