### ISSUE TITLE
Does kubersphere 2.1.0 support arm64 ?

### ISSUE THREAD

**Issue by wuscloud** [kubesphere/kubesphere#1810]
Does kubersphere 2.1.0 support arm64 ?
Can arm64 be supported by recompiling ?

thx

**Comment by calvinyv** [comment]
> Does kubersphere 2.1.0 support arm64 ?
yes,  our service team used to support some customers to do that.

> Can arm64 be supported by recompiling ?
sure you can, go ahead to do that.

**Comment by wuscloud** [comment]
Do I have to recompile to support amr64?
if so, Can you provide a simple manual or idea, I'm new user of kubersphere.
Thank you very much.

**Comment by calvinyv** [comment]
there's no some kind of guide to build just specific kubesphere arm, you could just use general guide of docker to build multi arch image, some helpful reference link:
https://github.com/docker/buildx
https://github.com/multiarch/qemu-user-static
https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/getting-started-with-docker-for-arm-on-linux

take ks-apigatewa as an example:
`$ docker buildx build -f  build/ks-apigateway/Dockerfile --output=type=registry --platform linux/amd64,linux/arm64  -t kubesphere/ks-apigateway:all .`

**Comment by wuscloud** [comment]
Ok, I'll try, thanks

**Comment by LoveJT** [comment]
Did it build successfully？arm64
