### ISSUE TITLE
Import application repo error

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#1813]
/kind bug
/milestone 2.1.1
/area app-management
/cc @zheng1 @wansir 
![image](https://user-images.githubusercontent.com/31230341/73822012-297e6200-4830-11ea-9682-5e9fe7412470.png)
![image](https://user-images.githubusercontent.com/31230341/73822027-2daa7f80-4830-11ea-8a55-a048e9686163.png)
![image](https://user-images.githubusercontent.com/31230341/73822034-2f744300-4830-11ea-8f2e-dad1af2db2ad.png)

**Comment by wansir** [comment]
1. `openpitrix.io/v1/apps`   conditions: repo -> repo_id
https://github.com/kubesphere/kubesphere/commit/05e949103ecd799c4c0f40cd4f0dbff400ded640#diff-e471cde9c812dd4b5256562b1dee8138L60
2. `openpitrix.io/v1/apps/{app}/versions/{version}/audits` conditions: version -> version_id
https://github.com/kubesphere/kubesphere/commit/05e949103ecd799c4c0f40cd4f0dbff400ded640#diff-e471cde9c812dd4b5256562b1dee8138L581
3. `openpitrix.io/v1/apps/{app}/versions`   conditions: app -> app_id
https://github.com/kubesphere/kubesphere/commit/05e949103ecd799c4c0f40cd4f0dbff400ded640#diff-e471cde9c812dd4b5256562b1dee8138L663

/kind api-change
/milestone 2.1.1
/assign @whDongRui
