### ISSUE TITLE
在测试s2i的过程中发现gitlab的解析问题

### ISSUE THREAD

**Issue by yuenwah** [kubesphere/kubesphere#1816]
此地址不清楚为什么会解析到图上的地址，我在本地还有kubesphere的主机上ping都不是这个地址
![image](https://user-images.githubusercontent.com/34834139/73827512-a57da780-483a-11ea-9088-59960a0f81e5.png)
![image](https://user-images.githubusercontent.com/34834139/73827567-be865880-483a-11ea-84cb-85bc83a4cb0a.png)
![Uploading image.png…]()

**Comment by soulseen** [comment]
进入ks-apiserver容器中nslooup 看下解析结果正确吗

**Comment by yuenwah** [comment]
解析的问题找到了，然后我们的gitlab登录会跳转到其它地方去认证，在kubesphere中填写对应账号密码不能认证，kubesphere是否可以通过gitlab的access token或ssh-key去认证呢
![image](https://user-images.githubusercontent.com/34834139/73911601-50e73480-48ed-11ea-9eb5-8deb68f9f7ce.png)

**Comment by soulseen** [comment]
非常抱歉，目前版本还不支持access token或ssh-key的认证方式。
