### ISSUE TITLE
一个用户能否让多人同时登陆在线?

### ISSUE THREAD

**Issue by tosptargogo** [kubesphere/kubesphere#1827]
问题描述：
  单个用户登陆能否同时登陆。每次有另一个人上线就会被踢下来。
  我们有4个cluster 部署4套。每套都要设置用户。工作量非常大。
  有没有办法所有人都只用一个账号登陆。同时在线。

**Comment by wansir** [comment]
你可以将kubesphere-system下ks-account组件，启动参数中的--enable-multi-login设置为true，以此来启用账户多处登录。

**Comment by tosptargogo** [comment]
万分感谢
