### ISSUE TITLE
关于jenkinsfile out of scm这个示例，有以下问题要咨询一下 

### ISSUE THREAD

**Issue by yuenwah** [kubesphere/kubesphere#1834]
![image](https://user-images.githubusercontent.com/34834139/74214278-be250c00-4cd7-11ea-9f01-bd22b8a50769.png)
这个页面一直卡死是哪个资源不足吗，另外这个Dockerfile-online报没找到，因为我用的不是示例中的git库，这个dockerfile文件是要自己写吗

**Comment by soulseen** [comment]
测试用的是官方示例吗，检查下路径graphical-pipeline下是否包含Dockerfile-online文件，可以参考下官方示例。

**Comment by soulseen** [comment]
页面无响应的问题麻烦说下复现步骤，可以检查下系统组件是否运行正常。
