### ISSUE TITLE
登录显示Internal Server Error，ks-console日志是Bad Gateway

### ISSUE THREAD

**Issue by flyforfreedom** [kubesphere/kubesphere#1841]
**What's your question**
如题，ks-console日志如下，请问如何进一步调试呢？
![图片](https://user-images.githubusercontent.com/3615229/74299637-46fb8080-4d88-11ea-9fa2-d818935fa67b.png)

**Environment: OS & Hardware Information**

> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).

**Error logs or message (Attach logs or screenshot)**

**Installer Version**

> e.g. v2.1.1

**Comment by huanggze** [comment]
Can you print pod status in kubesphere-system namespace?

`kubectl get po -n kubesphere-system`

**Comment by liangminhua** [comment]
@huanggze 
``` bash
NAME                                     READY   STATUS             RESTARTS   AGE
ks-account-596657f8c6-bchxn              0/1     Init:0/2           0          16m
ks-apigateway-78bcdc8ffc-gf6bs           0/1     CrashLoopBackOff   7          16m
ks-apiserver-5b548d7c5c-m42zv            1/1     Running            0          16m
ks-console-78bcf96dbf-jslv5              1/1     Running            0          16m
ks-controller-manager-696986f8d9-6fb6q   1/1     Running            0          16m
ks-installer-7d9fb945c7-hvgct            1/1     Running            0          18m
openldap-0                               0/1     Pending            0          16m
redis-6fd6c6d6f9-vshjb                   0/1     Pending            0          17m

```

**Comment by heppytt** [comment]
> @huanggze
> 
> ```shell
> NAME                                     READY   STATUS             RESTARTS   AGE
> ks-account-596657f8c6-bchxn              0/1     Init:0/2           0          16m
> ks-apigateway-78bcdc8ffc-gf6bs           0/1     CrashLoopBackOff   7          16m
> ks-apiserver-5b548d7c5c-m42zv            1/1     Running            0          16m
> ks-console-78bcf96dbf-jslv5              1/1     Running            0          16m
> ks-controller-manager-696986f8d9-6fb6q   1/1     Running            0          16m
> ks-installer-7d9fb945c7-hvgct            1/1     Running            0          18m
> openldap-0                               0/1     Pending            0          16m
> redis-6fd6c6d6f9-vshjb                   0/1     Pending            0          17m
> ```

解决了吗？我也遇到和你一样的问题了。
![image](https://user-images.githubusercontent.com/17058423/85826293-e7da5d80-b7b6-11ea-805d-669c885152bc.png)

**Comment by FeynmanZhou** [comment]
> > @huanggze
> > ```shell
> > NAME                                     READY   STATUS             RESTARTS   AGE
> > ks-account-596657f8c6-bchxn              0/1     Init:0/2           0          16m
> > ks-apigateway-78bcdc8ffc-gf6bs           0/1     CrashLoopBackOff   7          16m
> > ks-apiserver-5b548d7c5c-m42zv            1/1     Running            0          16m
> > ks-console-78bcf96dbf-jslv5              1/1     Running            0          16m
> > ks-controller-manager-696986f8d9-6fb6q   1/1     Running            0          16m
> > ks-installer-7d9fb945c7-hvgct            1/1     Running            0          18m
> > openldap-0                               0/1     Pending            0          16m
> > redis-6fd6c6d6f9-vshjb                   0/1     Pending            0          17m
> > ```
> 
> 解决了吗？我也遇到和你一样的问题了。
> ![image](https://user-images.githubusercontent.com/17058423/85826293-e7da5d80-b7b6-11ea-805d-669c885152bc.png)

@heppytt  You need to check the PVC status, this might be caused by the persistent storage issue.

**Comment by heppytt** [comment]
> > > @huanggze
> > > ```shell
> > > NAME                                     READY   STATUS             RESTARTS   AGE
> > > ks-account-596657f8c6-bchxn              0/1     Init:0/2           0          16m
> > > ks-apigateway-78bcdc8ffc-gf6bs           0/1     CrashLoopBackOff   7          16m
> > > ks-apiserver-5b548d7c5c-m42zv            1/1     Running            0          16m
> > > ks-console-78bcf96dbf-jslv5              1/1     Running            0          16m
> > > ks-controller-manager-696986f8d9-6fb6q   1/1     Running            0          16m
> > > ks-installer-7d9fb945c7-hvgct            1/1     Running            0          18m
> > > openldap-0                               0/1     Pending            0          16m
> > > redis-6fd6c6d6f9-vshjb                   0/1     Pending            0          17m
> > > ```
> > 
> > 
> > 解决了吗？我也遇到和你一样的问题了。
> > ![image](https://user-images.githubusercontent.com/17058423/85826293-e7da5d80-b7b6-11ea-805d-669c885152bc.png)
> 
> @heppytt You need to check the PVC status, this might be caused by the persistent storage issue.

![image](https://user-images.githubusercontent.com/17058423/85836569-5a543900-b7c9-11ea-91ab-f561cb94effe.png)
this is my PVC status 。is pending how to resove it？

**Comment by FeynmanZhou** [comment]
@heppytt  Are there any Taints in your master nodes?

**Comment by FeynmanZhou** [comment]
@heppytt You would better to refer to this [blog](https://kubesphere.com.cn/forum/d/1471-k8s-kubesphere) provided by another user, it's a step-by-step guide.

**Comment by heppytt** [comment]
> Are there any Taints in your master nodes?

![image](https://user-images.githubusercontent.com/17058423/85837156-478e3400-b7ca-11ea-9ce5-afd2c6795903.png)
Yes！

**Comment by heppytt** [comment]
> @heppytt You would better to refer to this [blog](https://kubesphere.com.cn/forum/d/1471-k8s-kubesphere) provided by another user, it's a step-by-step guide.

我是按照这个去做的 前面都没有出错，就在装kubesphere的时候出错了。而且一错错了三天了 都没有解决。这是我装的第二遍了。

**Comment by FeynmanZhou** [comment]
> > Are there any Taints in your master nodes?
> 
> ![image](https://user-images.githubusercontent.com/17058423/85837156-478e3400-b7ca-11ea-9ce5-afd2c6795903.png)
> Yes！

Remove those Taints, please.

**Comment by heppytt** [comment]
> > > Are there any Taints in your master nodes?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/17058423/85837156-478e3400-b7ca-11ea-9ce5-afd2c6795903.png)
> > Yes！
> 
> Remove those Taints from master and reinstall it, please.

why reinstall it？I use  [openebs](https://kubesphere.io/docs/zh-CN/appendix/install-openebs/)

**Comment by FeynmanZhou** [comment]
> > > > Are there any Taints in your master nodes?
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/17058423/85837156-478e3400-b7ca-11ea-9ce5-afd2c6795903.png)
> > > Yes！
> > 
> > 
> > Remove those Taints from master and reinstall it, please.
> 
> why reinstall it？I use [openebs](https://kubesphere.io/docs/zh-CN/appendix/install-openebs/)

I mean reinstall KubeSphere after removing Taints, or you can retrigger the ks-installer Pod, see this [guide](https://kubesphere.io/docs/zh-CN/installation/verify-components/#%E5%A6%82%E4%BD%95%E9%87%8D%E5%90%AF-ks-installer). Taints should not exist on master nodes before kubesphere installation.

**Comment by heppytt** [comment]
> > > > > Are there any Taints in your master nodes?
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/17058423/85837156-478e3400-b7ca-11ea-9ce5-afd2c6795903.png)
> > > > Yes！
> > > 
> > > 
> > > Remove those Taints from master and reinstall it, please.
> > 
> > 
> > why reinstall it？I use [openebs](https://kubesphere.io/docs/zh-CN/appendix/install-openebs/)
> 
> I mean reinstall KubeSphere after removing Taints, you can retrigger the ks-installer Pod, see this [guide](https://kubesphere.io/docs/zh-CN/installation/verify-components/#%E5%A6%82%E4%BD%95%E9%87%8D%E5%90%AF-ks-installer). Taints should not exist on master nodes before kubesphere installation.

thank you!
redis and openldap is no problem! but i down know why? Taints Last hook up to that node？
but have other question . 
![image](https://user-images.githubusercontent.com/17058423/85844404-44e50c00-b7d5-11ea-956e-234a6b1b5261.png)
