### ISSUE TITLE
pod count in nodes/workspaces not match

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#1842]
![B39B813856BFCF11547ACA5B6BEC39E3](https://user-images.githubusercontent.com/31230341/74299779-ac4f7180-4d88-11ea-995c-69633797a138.jpg)
![0CA5B731D693BBEC107A67366A5EACB9](https://user-images.githubusercontent.com/31230341/74299781-ad809e80-4d88-11ea-937a-534d9f800094.jpg)
![image](https://user-images.githubusercontent.com/31230341/74299790-b40f1600-4d88-11ea-9065-8be63b0a0ebd.png)
/area monitoring
/cc @huanggze 
In a single-node environment, all pods belong to the one node and belong to the one worksapce. Query at the same time, the results do not match

**Comment by huanggze** [comment]
the same with https://github.com/kubesphere/kubesphere/issues/1861
