### ISSUE TITLE
workspace memory usage exceeds total cluster memory usage

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#1843]
![image](https://user-images.githubusercontent.com/31230341/74299971-47e0e200-4d89-11ea-988f-3296cd2d4ed6.png)
workspace memory usage exceeds total cluster memory usage
/area monitoring
/cc @huanggze
/milestone 2.1.1

**Comment by huanggze** [comment]
CPU usage for node and workspace are from different data source. The former is from node exporter while the latter cAdvisor. They are evaluated independently. So this may cause inconsistent results sometimes, though both are correct literally.

I would leave this issue to milestone 3.0.0

**Comment by huanggze** [comment]
This may be relative to issue https://github.com/kubesphere/kubesphere/issues/992 

It would be better apply different metrics rules for different Linux kernel versions when installing KubeSphere
