### ISSUE TITLE
scheduler monitoring  is blank

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#1847]
/cc @huanggze 
/area monitoring
/kind bug
/milestone 2.1.1
![image](https://user-images.githubusercontent.com/31230341/74316669-efbfd500-4db4-11ea-86a2-2906c9f7bf71.png)
![image](https://user-images.githubusercontent.com/31230341/74316691-f8b0a680-4db4-11ea-89ec-807bac586753.png)

**Comment by huanggze** [comment]
k8s bug, fixed since 1.16.6

https://github.com/kubernetes/kubernetes/blob/release-1.16/CHANGELOG/CHANGELOG-1.16.md#changes-by-kind

**Comment by huanggze** [comment]
Should we bump k8s version in installer?
/assign @pixiake

**Comment by pixiake** [comment]
update k8s to v1.16.7
