### ISSUE TITLE
Incorrect number of tasks and scheduled tasks

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1855]
Test steps：
1、Enter an existing project, such as project p11；
2、Go into the application load-task, then create a task and a timed task

Test  result：
2、It was found that the number of tasks and scheduled tasks was incorrect
![image](https://user-images.githubusercontent.com/7677050/74338899-fd3d8500-4ddd-11ea-804d-6c848e9f8ce5.png)

**Comment by leoendless** [comment]
Will be solved in v3.0，watch resourcequota to update the resource used status.

**Comment by leoendless** [comment]
Function removed.
