### ISSUE TITLE
2.1.1版本部署实例应用bookinfo，点击流量治理界面报错

### ISSUE THREAD

**Issue by Forest-L** [kubesphere/kubesphere#1859]
* 2.1.1allinone 
* centos 7.5
### 部署实例应用bookinfo,进入bookinfo中，点击流量治理界面报错。
![image](https://user-images.githubusercontent.com/50984129/74399459-dae74e00-4e55-11ea-815c-5805b8b4fed9.png)

**Comment by leoendless** [comment]
@zryfish
