### ISSUE TITLE
The image size limit is not correct

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#1862]
![image](https://user-images.githubusercontent.com/40452856/74407635-56a0c500-4e6d-11ea-9893-10d7419ff997.png)

How to reproduce? Follow the link below, upload a picture (`only 300+ kb`, less than 2M) to KubeSphere, but I upload failed: 

https://kubesphere.com.cn/docs/v2.1/zh-CN/quick-start/app-store/#%E4%B8%8A%E4%BC%A0%E5%BA%94%E7%94%A8%E6%8F%90%E4%BA%A4%E5%AE%A1%E6%A0%B8

![image](https://user-images.githubusercontent.com/40452856/74407723-92d42580-4e6d-11ea-94e0-db33d0197a79.png)

**Comment by FeynmanZhou** [comment]
@leoendless 
one more error log outputs:

when I upload a picture, then I remove it from the list, it displays as following screenshot:

![image](https://user-images.githubusercontent.com/40452856/74617651-39b80a80-5169-11ea-9555-353b68b79d49.png)

**Comment by leoendless** [comment]
@pengcong06 @zheng1  it seems like a backend error occured

**Comment by FeynmanZhou** [comment]
> @pengcong06 @zheng1 it seems like a backend error occured

This issue still exit.
![image](https://user-images.githubusercontent.com/40452856/74708802-79a9eb00-5258-11ea-93e0-7e68cde37f62.png)

**Comment by rayzhou2017** [comment]
verified
