### ISSUE TITLE
An error occurs when accessing the  traffic governance page of the sample application

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1863]
Test steps ：
1、Enter a project, enter the application load-application page；
2、Click to deploy the sample application and follow the steps to deploy the sample application  bookinfo；
3、Enter homemade app，click  bookinfo，click traffic governance，an  error occurred at this time：

<img width="959" alt="1581578784(1)" src="https://user-images.githubusercontent.com/7677050/74411323-e77b9e80-4e75-11ea-88a7-c7553c62dc23.png">

**Comment by leoendless** [comment]
same with https://github.com/kubesphere/kubesphere/issues/1859
