### ISSUE TITLE
Error deploying gitlab via app store

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1866]
Test steps：
1、Enter the project, application load-application, click to deploy a new application；
2、Choose to deploy from the app store，choose gitlab and click to deploy
3、An error occurred after waiting for a while

<img width="920" alt="1581584862(1)" src="https://user-images.githubusercontent.com/7677050/74430822-9e891180-4e98-11ea-8e86-2c4e14a8338b.png">

**Comment by mayuhope** [comment]
Test steps：
1、Enter the project, application load-application, click to deploy a new application；
2、Choose to deploy from the app store，choose  gitlab and click to deploy
3、An error occurred after waiting for a while

**Comment by mayuhope** [comment]
报错截图

**Comment by LinuxSuRen** [comment]
When I create an application, I got below error information. I suggest that we can give more human readable information.

![image](https://user-images.githubusercontent.com/1450685/90333029-df531600-dff4-11ea-80db-0168eefa3401.png)

**Comment by rayzhou2017** [comment]
> When I create an application, I got below error information. I suggest that we can give more human readable information.
> 
> KubeSphere Version : v2.1.0
> 
> ![image](https://user-images.githubusercontent.com/1450685/90333029-df531600-dff4-11ea-80db-0168eefa3401.png)
Please verify if it is fixed on v3.0.0

**Comment by zryfish** [comment]
@LinuxSuRen Does this issue still exist in v3.0 latest build?

**Comment by LinuxSuRen** [comment]
@rayzhou2017 @zryfish I'm not sure due to don't have the v3.0 environment.

**Comment by rayzhou2017** [comment]
We decide to remove gitlab now since the official chart is not good.
