### ISSUE TITLE
There is no response for a long time after clicking save when Create a CI/CD Pipeline in a Graphical Panel

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#1867]
**Describe the Bug**
There is no response for a long time after clicking save when Create a CI/CD Pipeline in a Graphical Panel

![下载](https://user-images.githubusercontent.com/53003665/74413434-5bb84100-4e7a-11ea-9e28-7ce20f280237.png)

**Versions Used**
KubeSphere:
Kubernetes: 2.1.1

**Environment**
all in one

**How To Reproduce**
Follow the kubersphere quick start part 10

/area devops
/kind bug
/milestone 2.1.1

**Comment by runzexia** [comment]
/assign @minghaoye 
![image](https://user-images.githubusercontent.com/31230341/74415891-37ab2e80-4e7f-11ea-9654-6cb01abd2a61.png)
