### ISSUE TITLE
Why kubesphere add a colon after my ldap's port?

### ISSUE THREAD

**Issue by ZhangSIming-blyq** [kubesphere/kubesphere#1868]
**Describe the Bug**
Why kubesphere add a colon after my ldap's port?
My config is:
![image](https://user-images.githubusercontent.com/58658883/74441235-6a1e5100-4eaa-11ea-9a04-c40d3c413e07.png)

But the error logs is:
![image](https://user-images.githubusercontent.com/58658883/74441412-bec1cc00-4eaa-11ea-837d-54c377c4ec70.png)

KubeSphere: v2.1(Maybe ks-installer v2.1)
Kubernetes: v1.14.3

**Environment**
Use ks-installer to deploy kubesphere on a existing kubernetes cluster
Ubuntu18.04 / 1 masters:  2cpu/4g; 1 nodes: 16cpu/64g

**How To Reproduce**
1.have a cluster without ldap
2.bash your ldap shell script

**Expected behavior**
Successfully inject ldap to my kubesphere on k8s.

**Comment by ZhangSIming-blyq** [comment]
I need your help! Thanks

**Comment by wansir** [comment]
Paste the results of this command `kubectl -n kubesphere-system get cm ad-sync-config -o yaml`

**Comment by wansir** [comment]
@ZhangSIming-blyq  `ldap://` is not  not required

**Comment by ZhangSIming-blyq** [comment]
> @ZhangSIming-blyq `ldap://` is not not required

Thanks for your reply.
But if dont add ldap://, the error is:
```
"LDAP error 13: Confidentiality Required."
```

**Comment by ZhangSIming-blyq** [comment]
As you can see below:
![image](https://user-images.githubusercontent.com/58658883/74507803-6df8b480-4f38-11ea-921b-345898097301.png)

**Comment by wansir** [comment]
So sorry, LDAP over SSL is not supported now.

**Comment by ZhangSIming-blyq** [comment]
> So sorry, LDAP over SSL is not supported now.

OK，I'll try http, I'll update the result later.

**Comment by ZhangSIming-blyq** [comment]
> > So sorry, LDAP over SSL is not supported now.
> 
> OK，I'll try http and update the result later.

**Comment by ZhangSIming-blyq** [comment]
Finally I inject ldap to kubesphere by using another ldap server without ssl, thanks.
But it seems still have some problem.
**Here is my config:**
```
#!/bin/bash
set -e

host="10.20.31.205:389"    # 将 host 的值改为实际的服务器 IP 与 端口
managerDN="cn=devpi,ou=project,dc=shannonai,dc=com"  # 值修改为实际的 AD 域的管理账号, 可以为只读账号
managerPWD="******"    #  管理账号密码
userSearchBase="dc=shannonai,dc=com"   # 根据实配置进行修改
sidecar="kubespheredev/ad-sidecar:v0.0.1"
```

**Here is my ldap server like:**
![image](https://user-images.githubusercontent.com/58658883/74634515-f7112500-519e-11ea-810f-bf004e114127.png)

It is obviously I add user "zhangsiqi" in project "devpi. but as a result, I didn't see the accout show in kubesphere, I need some help, thanks

**Comment by wansir** [comment]
The default synchronization interval is 300s.

**Comment by ZhangSIming-blyq** [comment]
> The default synchronization interval is 300s.

Ok, I see.
