### ISSUE TITLE
Project viewer role can edit and delete build images

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1873]
Test  steps：
1、The role of user user1 is cluster regular + workspace viewer + project viewer；
2、Login  with  user1；
3、Enter the project, enter the build image page；
4、Choose an image that has been built. 

Test  results：
4、It was found that an operation bar was provided, and the editing information and deletion appeared after clicking, and the operation was successful，See this picture：

Expect results:
4、No operation bar is provided, operation is prohibited；

**Comment by wansir** [comment]
/assign @leoendless 

If policy rules only have `s2ibuilders.view`，the button needs to be hidden.

**Comment by mayuhope** [comment]
经验证已修复
