### ISSUE TITLE
user with workspace-manager role，the number of project displayed incorrect 

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#1877]
Testing premise:
userA has workspace-manager role
workspaceA has  2 projects

steps:
1.userA login system
2. find that the number of workspaceA's projects displayed in workspace page is 0
3. but click the workspaceA and enter workspaceA's page,find that the number of workspaceA's projects displayed in workspace page is 2

/assign @wansir
/kind bug
/area iam
/milestone 2.1.1

**Comment by liuyp2018** [comment]
<img width="648" alt="123" src="https://user-images.githubusercontent.com/36271543/74510903-b4054680-4f3f-11ea-85d4-be18d80ff7c0.png">

**Comment by wansir** [comment]
The number in the workspace list indicates the number of projects that can be accessed. The workspaces manager cannot manage these projects, but the number in the workspace overview page indicates the total number of projects in the workspace.

**Comment by liuyp2018** [comment]
在3.0.0中待 workspace-manager角色功能优化后，再验证测试。
/milestone 3.0.0

**Comment by liuyp2018** [comment]
close
