### ISSUE TITLE
resource asc and desc order results are incorrect

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#1878]
![image](https://user-images.githubusercontent.com/31230341/74512162-9f767d80-4f42-11ea-98f0-8d1723940fb2.png)
/kind bug
/area console
/area api
/milstone 2.1.1
Includes the following resources
- user
- role
- application
- apps
- app catlog
- app repo
- workspace
- namespace
- service
- sc
- sts
- secret
- s2ib
- s2ibt
- po
- pvc
- node
- job
- ingress
- hpa
- daemonsets
- deployments
- cronjobs
- configmaps
- clusterroles

**Comment by wansir** [comment]
fixed: #1875 #1879

**Comment by runzexia** [comment]
![image](https://user-images.githubusercontent.com/31230341/74580433-3db82100-4fdf-11ea-898d-a0251d80eec1.png)
pod list sort by updateTime has some error

**Comment by runzexia** [comment]
![image](https://user-images.githubusercontent.com/31230341/74581376-cb007300-4fe9-11ea-93f1-49403860e6bd.png)
job list
