### ISSUE TITLE
In Invite members to workspace page,only 10 records can be displayed at most

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#1880]
<img width="742" alt="111" src="https://user-images.githubusercontent.com/36271543/74514633-f5015900-4f47-11ea-94ca-7850c21eb374.png">

/assign @leoendless
/kind bug
/area console
/milestone 2.1.1

**Comment by leoendless** [comment]
这里应当有下拉加载的功能，我本地测试可以触发下拉加载。你这里是什么测试环境呢

**Comment by liuyp2018** [comment]
有下拉框，但是最多只能展示10条数据，不能展示超出10条的数据

**Comment by liuyp2018** [comment]
浏览器版本：Microsoft Edge 44.18362.449.0

**Comment by benjaminhuo** [comment]
From guangzhe:
问题原因是对total pod 的讲法界面上没统一。有的地方只看running pod（集群管理也节点total pod/pod capacity）。有的地方看all pods，有的地方看non- terminated pods（除开job产生的completed pod）, 现在界面上都叫【容器组数量】导致混乱. 设计上的问题 没有统一标准 哪里显示什么 用什么术语后端api都是支持的比如 xxx_pods_count，xxx_running_pods_count
