### ISSUE TITLE
Select multiple members in the workspace , modify member roles ,then an error occurs

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#1881]
![image](https://user-images.githubusercontent.com/36271543/74517917-fdf52900-4f4d-11ea-94d4-2830a3bcc29e.png)

/assign @leoendless
/kind bug
/area console
/milestone 2.1.1

**Comment by leoendless** [comment]
这里的原因是有成员的数据被修改了，但页面里的列表数据还是旧的

**Comment by liuyp2018** [comment]
去掉了批量修改成员角色的功能
/colse
