### ISSUE TITLE
The number of pod in the project details includes pod of all states

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#1882]
![image](https://user-images.githubusercontent.com/31230341/74581430-45c98e00-4fea-11ea-8b68-ea9877759d08.png)
![image](https://user-images.githubusercontent.com/31230341/74581468-b2dd2380-4fea-11ea-91ee-a02a3b14c944.png)

In other pages, the running  pods is displayed.
Is the display here expected?
/cc @huanggze 
/area monitoring
/milestone 2.1.1

**Comment by huanggze** [comment]
the same with https://github.com/kubesphere/kubesphere/issues/1861

**Comment by calvinyv** [comment]
@huanggze pls help to confirm if this issue is fixed or not in 3.0, thx

**Comment by benjaminhuo** [comment]
@leoendless any change in the backend monitoring api call to resolve this issue in ks v3.0?

**Comment by benjaminhuo** [comment]
From guangzhe:
问题原因是对total pod 的讲法界面上没统一。有的地方只看running pod（集群管理页节点total pod/pod capacity）。有的地方看all pods，有的地方看non- terminated pods（除开job产生的completed pod）, 现在界面上都叫【容器组数量】导致混乱. 设计上的问题 没有统一标准 哪里显示什么 用什么术语后端api都是支持的比如 xxx_pods_count，xxx_running_pods_count
