### ISSUE TITLE
Does kubesphere support "helm upgrade"?

### ISSUE THREAD

**Issue by ZhangSIming-blyq** [kubesphere/kubesphere#1883]
**Describe the Bug**
I can't find anywhere to upgrade my project chart?
In my scene, I deploy a project use my private helm chart from app repo.
When I update my code and push a new version helm chart to my app repo, I want to upgrade my project(before kubesphere, I only need to do helm upgrade command)，but I can't fan anywhere to do this thing? 
Do kubesphere support upgrade the chart?
![image](https://user-images.githubusercontent.com/58658883/74584281-8ab1ec80-500b-11ea-99b1-79e89137f06d.png)

**Versions Used**
KubeSphere: v2.1.0
Kubernetes: v1.14.3

**Environment**
Ubuntu18.04 / 1 masters:  2cpu/4g; 1 nodes: 16cpu/64g

**Expected behavior**
When I have a new version of chart, All I need to do is:
1.reindex my app repo
2.click upgrade helm chart to use the new version
Do kubesphere support this? Or tell my what is the current method for upgrade, thanks

**Comment by FeynmanZhou** [comment]
@ZhangSIming-blyq  I guess this [guide](https://kubesphere.io/docs/v2.1/en/quick-start/app-store/) can answer your question. Please take a look at this tutorial, let me know if this can resolve your question or not.

**Comment by ZhangSIming-blyq** [comment]
> @ZhangSIming-blyq I guess this [guide](https://kubesphere.io/docs/v2.1/en/quick-start/app-store/) can answer your question. Please take a look at this tutorial, let me know if this can resolve your question or not.

Hi, FeynmanZhou.
Thanks for your reply, after total read your tutirual, I think your suggestion seems ill-suited for my scene.

In my situation, I use **app repo** to connect my own chartmuseum, and use charts in it.Not upload chart file to **App Templatle**.
Since I see **App Template** may have some way to upgrade, is there any way to upgrade chart in app repo?
![image](https://user-images.githubusercontent.com/58658883/74619969-5b69bf80-5172-11ea-9b13-d8785471ece9.png)

**Comment by ZhangSIming-blyq** [comment]
Maybe I need this place be "upgrade" but not deploy a new application?
![image](https://user-images.githubusercontent.com/58658883/74628520-d7730000-5190-11ea-8635-95519d99a55f.png)

**Comment by zryfish** [comment]
@ZhangSIming-blyq Can you verify this issue? It should be fixed in v3.0 the latest build.

**Comment by benjaminhuo** [comment]
Close this issue for now because it's fixed in v3.0
