### ISSUE TITLE
Failed to deploy EMQ X helm App

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#1884]
@pengcong06 @zheng1 
These two helm charts can be deployed successfully in KubeSphere v2.1.0, but failed to deploy in v2.1.1 after uploading by following with this [guide](https://kubesphere.com.cn/docs/v2.1/zh-CN/quick-start/app-store/#%E4%B8%8A%E4%BC%A0%E5%BA%94%E7%94%A8%E6%8F%90%E4%BA%A4%E5%AE%A1%E6%A0%B8).

- [emqx-v1.0.0-beta.1.tgz (Please download)](https://github.com/kubesphere/tutorial/raw/master/tutorial%205%20-%20app-store/emqx-v1.0.0-beta.1.tgz)
- [emqx-v1.0.0-beta.2.tgz (Please download)](https://github.com/kubesphere/tutorial/raw/master/tutorial%205%20-%20app-store/emqx-v1.0.0-beta.2.tgz)

### Issue 1
When I upload [emqx-v1.0.0-beta.1.tgz (Please download)](https://github.com/kubesphere/tutorial/raw/master/tutorial%205%20-%20app-store/emqx-v1.0.0-beta.1.tgz) :

![](https://pek3b.qingstor.com/kubesphere-docs/png/20200217092443.png)
### Issue 2
When I upload [emqx-v1.0.0-beta.2.tgz (Please download)](https://github.com/kubesphere/tutorial/raw/master/tutorial%205%20-%20app-store/emqx-v1.0.0-beta.2.tgz), it can be uploaded successfully, but it hangs out at `1/3` for its deployment replicas.

![image](https://user-images.githubusercontent.com/40452856/74617384-c8c42300-5167-11ea-9877-5dcd953eb0a9.png)

## My Qustion

Is any issues with the Helm chart or the k8s version change (now 1.16)?  Do we need to make changes in the chart files?

**Comment by calvinyv** [comment]
@FeynmanZhou I think you should post this issue to emq, not to ks, they should upgrade their chart to support 1.16

**Comment by zheng1** [comment]
This is not the bug of KubeSphere. 
But we can notice the user "cannot deploy the legacy version" before him/her click the "Deploy" button.

/milestone 3.0.0

**Comment by calvinyv** [comment]
@FeynmanZhou pls double-check this issue on 3.0

**Comment by liuyp2018** [comment]
the problem still exists in ks3.0

/remove-kind need-to-verify

**Comment by zheng1** [comment]
This is not the bug of KubeSphere.
/close
