### ISSUE TITLE
Default StorageClass conflict in 2.1.1

### ISSUE THREAD

**Issue by zheng1** [kubesphere/kubesphere#1886]
**Describe the Bug**
```
[root@master scripts]# kubectl get storageclass
NAME                              PROVISIONER                       AGE
csi-alibabacloud-disk (default)   diskplugin.csi.alibabacloud.com   34m
local (default)                   openebs.io/local                  4h47m
[root@master scripts]# kubectl get storageclass csi-alibabacloud-disk -o yaml | grep default
    storageclass.beta.kubernetes.io/is-default-class: "false"
    storageclass.kubernetes.io/is-default-class: "true"
[root@master scripts]# kubectl get storageclass local -o yaml | grep default
    storageclass.beta.kubernetes.io/is-default-class: "true"
    storageclass.kubernetes.io/is-default-class: "false"
```

**Versions Used**
KubeSphere: 2.1.1

**Environment**
How many nodes and their hardware configuration:

CentOS 7.5 / 1 masters:  8cpu/8g; 3 nodes: 8cpu/16g at AliCloud

**How To Reproduce**
1. Install 2.1.0 and enable default local storage
2. Update to 2.1.1 and config AliCloud CSI
3. After installation going done
4. Goto KubeSphere Console and set AliCloud CSI as default StorageClass

**Expected behavior**
AliCloud CSI is default StorageClass, and Local storage is not.

**Comment by wnxn** [comment]
@leoendless In KS 2.11, please use the new api to set default storage class (https://github.com/kubesphere/kubesphere/pull/1757).

**Comment by wnxn** [comment]
Need to merge #1890

**Comment by zryfish** [comment]
/close
verified in v3.0 with the latest build
