### ISSUE TITLE
How to inject existing prometheus and EFK to kubesphere?

### ISSUE THREAD

**Issue by ZhangSIming-blyq** [kubesphere/kubesphere#1889]
**What's your question**
![image](https://user-images.githubusercontent.com/58658883/74709218-9abf0b80-5259-11ea-8fab-54e9b4b4993c.png)
I want to inject my own prometheus to kubesphere, not deploy a new one, can anyone give my some suggestion? I use ks-installer to deploy kubesphere over my kubernetes cluster.

**Environment: OS & Hardware Information**

> Kubernetes: v1.14.3
ks-install: v2.1.0
Ubuntu 18.04

> v2.1.0

**Comment by huanggze** [comment]
You may get help from the system design and development guide for ks monitoring component (work-in-progress).

https://github.com/kubesphere/kubesphere/blob/4edf909c2f1acae8e2ae28d577a5e38558951dfc/docs/en/concepts-and-designs/kubesphere-monitoring.md

https://github.com/kubesphere/kubesphere/blob/4edf909c2f1acae8e2ae28d577a5e38558951dfc/docs/en/guides/kubesphere-monitoring-development-guide.md
