### ISSUE TITLE
Can kubesphere create workspace role?

### ISSUE THREAD

**Issue by ZhangSIming-blyq** [kubesphere/kubesphere#1891]
**What's your question**
![image](https://user-images.githubusercontent.com/58658883/74722676-4bd29f80-5274-11ea-8d45-e34ee398049e.png)
I can't find anywhere to create workspace role(not cluster role)

**Environment: OS & Hardware Information**

> kubernetes: v1.14.3

**Installer Version**

> v2.1.0

**Comment by wansir** [comment]
It's a new feature in 3.0.

**Comment by ZhangSIming-blyq** [comment]
> It's a new feature in 3.0.

Ok. thanks~
