### ISSUE TITLE
workspace App Templates can't parse value.yaml file

### ISSUE THREAD

**Issue by ZhangSIming-blyq** [kubesphere/kubesphere#1892]
**Describe the Bug**
workspace App Templates can't parse value.yaml file
1.click app template
![image](https://user-images.githubusercontent.com/58658883/74736262-4cc3fb00-528d-11ea-9313-651449dc79e2.png)
2.use a passed template
![image](https://user-images.githubusercontent.com/58658883/74736290-5c434400-528d-11ea-8e93-4eebbca825b6.png)
3.failed to parse the value.yaml file
![image](https://user-images.githubusercontent.com/58658883/74736070-ee971800-528c-11ea-9f9c-84ea4461e52a.png)
4.After force click deploy button, got some error:
![image](https://user-images.githubusercontent.com/58658883/74736373-898ff200-528d-11ea-8dfb-792cf76da676.png)

**Versions Used**
KubeSphere: v2.1.0
Kubernetes: v1.14.3

**Environment**
Ubuntu 18.04 

**How To Reproduce**
1.Upload an helm chart and get passed.
2.click deploy.

**Expected behavior**
Deploy the app template successfully.

**Comment by ZhangSIming-blyq** [comment]
Every components worked fine.
![image](https://user-images.githubusercontent.com/58658883/74736502-dc69a980-528d-11ea-8527-60e0a3d9d4ae.png)

**Comment by zheng1** [comment]
Fixed in 3.0
