### ISSUE TITLE
some service components without description

### ISSUE THREAD

**Issue by soulseen** [kubesphere/kubesphere#1896]
**Describe the Bug**
`mysql,mimo,etcd...`etc, without description.

![image](https://user-images.githubusercontent.com/16031013/74821298-58232f00-533e-11ea-8a0f-1dcccb9c6f2e.png)

/priority low
/milestone 2.1.1
/cc @leoendless

**Comment by leoendless** [comment]
Duplicated with https://github.com/kubesphere/kubesphere/issues/1167
