### ISSUE TITLE
Workload revision yaml presentation misses some meta fields

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1899]
Each revision is actually a ReplicaSet object, so there should be `apiVersion`, `kind`, etc. in yaml. But that content disappears on console, making the look very weird.

![image](https://user-images.githubusercontent.com/22350668/74909851-210f5500-53f4-11ea-8f20-142c3500ce38.png)

![image](https://user-images.githubusercontent.com/22350668/74909557-89116b80-53f3-11ea-8adc-f118cedd2d5b.png)

![image](https://user-images.githubusercontent.com/22350668/74909524-7860f580-53f3-11ea-9efb-9aad223d9051.png)

**Comment by leoendless** [comment]
This is exactly the data returned by the native api.

**Comment by huanggze** [comment]
/remove-kind need-to-verify

![image](https://user-images.githubusercontent.com/22350668/87893004-27702e80-ca71-11ea-8352-3e7450ad9d7c.png)

**Comment by zryfish** [comment]
Yeah, there is a related issue https://github.com/kubernetes/kubernetes/issues/3030
