### ISSUE TITLE
kubesphere2.1存储卷扩容后显示的容量没有变

### ISSUE THREAD

**Issue by xingchen360** [kubesphere/kubesphere#1902]
kubesphere2.1
项目里面=》存储卷=》更多操作里面=》存储卷扩容
修改了容量，但是外面的显示还是原来的大小，但是再次点击存储卷扩容按钮里面的横条是修改后的大小，这到底改成功了还是失败了。

![WechatIMG12006](https://user-images.githubusercontent.com/28859385/74914570-a21f1a00-53fd-11ea-8eb1-7de2c9cd5a4f.png)

**Comment by wnxn** [comment]
在 KubeSphere 2.1 里， KubeSphere 扩容功能仅支持 QingCloud 云平台块存储，NFS 没有支持扩容功能 https://kubesphere.com.cn/docs/v2.1/zh-CN/installation/storage-configuration/

**Comment by rayzhou2017** [comment]
你扩容这个按钮没有变灰或者屏蔽掉吗？对不能扩容的需要处理一下

**Comment by wnxn** [comment]
屏蔽功能是在 KS 3.0 统一存储管理功能里的，需要把各种类型存储统一考虑。
KS 2.1 扩容功能可以在前端限制，仅允许 storageclass provisioner 字段符合条件的放行。

**Comment by justahole** [comment]
是否禁止这个按钮是根据创建 storageclass 是写入值来判断的。
不过前端缺少相应的日志，这边确实需要提示用户。
