### ISSUE TITLE
The status is not consistent

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1904]
* [ ] The status wording of app from template and from composing way is different. One is `active`, the other one is `Ready`

**Comment by zryfish** [comment]
/cc @zheng1  

I think our new OpenPitrix will solve this issue permanently, right?

**Comment by zheng1** [comment]
> /cc @zheng1
> 
> I think our new OpenPitrix will solve this issue permanently, right?

Yes
