### ISSUE TITLE
pipeline logs have wrong author

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1912]
* [ ] When open the scan repo logs, it shows `Started By: undefined`
<img width="963" alt="Screen Shot 2020-02-21 at 7 58 28 PM" src="https://user-images.githubusercontent.com/28859385/75033041-eafdce00-54e4-11ea-941e-8716e6671910.png">

**Comment by minghaoye** [comment]
fixed
/close
