### ISSUE TITLE
Modify the jenkins email configuration

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#1916]
The  default value of `EMAIL_SMTP_PORT` within dpeloyment `ks-jenkins` needs to be changed to `25`, instead of `465`, since [25 is much popular](https://blog.csdn.net/hssdw25172008/article/details/8729469)

**Comment by soulseen** [comment]
port `25` used in SMTP, SMTPS uses `465` by default. and the default value of `EMAIL_SMTP_PORT` just an example, if users want to use email will change it.
