### ISSUE TITLE
Can't invite members into DevOps project

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#1918]
- [ ] I use `project-admin` to create a devops projet in v2.1.0. Then I upgraded from 2.1.0 to 2.1.1. Now I got this error as following screenshot when I invite members into DevOps project.
![image](https://user-images.githubusercontent.com/40452856/75089325-85681b00-5592-11ea-9090-49b9f32bd922.png)

- [ ]  I use `admin` to create a pipeline in the same DevOps project, but the `project-admin` can't see this pipeline. 

![image](https://user-images.githubusercontent.com/40452856/75089475-1e4b6600-5594-11ea-8d53-154477179bb7.png)

**Comment by runzexia** [comment]
ref https://kubesphere.com.cn/forum/d/283-jenkins
