### ISSUE TITLE
How to use exist system data when cluster reboot?

### ISSUE THREAD

**Issue by leeon1982** [kubesphere/kubesphere#1921]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**What's your question**

**Environment: OS & Hardware Information**

> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).

**Error logs or message (Attach logs or screenshot)**

**Installer Version**

> e.g. v2.1.0, v2.1.1

**Comment by calvinyv** [comment]
@leeon1982 could you give more detail about your question? what kind of data for re-use purpose? we did recovering test, something like that restarting master or worker node to check if our core processes could restart automatically and related config data is not lost.

**Comment by leeon1982** [comment]
Kubesphere was installed,but the server down for some reason,how to start the master and worknode with exist configure?

**Comment by pixiake** [comment]
docker and kubelet can auto reboot

**Comment by leeon1982** [comment]
which command? @pixiake

**Comment by leeon1982** [comment]
kubesphere v2.1,storage class is nfs，which command can restart master and worknode?

**Comment by Forest-L** [comment]
> which command? @pixiake

systemctl enable docker;systemctl enable kubelet

**Comment by leeon1982** [comment]
everyting is ok,kubelet service bring up all kubesphere containers,thanks!
