### ISSUE TITLE
Cluster Status shows completed minio job as unhealthy component

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1926]
issue from forum: https://kubesphere.com.cn/forum/d/829-minio/4

**How To Reproduce**
1. Install KubeSphere with minimal setup
2. Switch on openpitrix component
3. Go to console main page

![image](https://user-images.githubusercontent.com/22350668/75321574-fd448700-58ab-11ea-8779-889d5f0227b6.png)

![image](https://user-images.githubusercontent.com/22350668/75321582-00d80e00-58ac-11ea-934f-14cb0b30c279.png)

**Comment by zryfish** [comment]
/unassign @wansir 
/cc @huanggze 
Is this issue still existing in latest build?

**Comment by huanggze** [comment]
verified
