### ISSUE TITLE
Service doesn't show port name

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#1929]
Port name is more meaningful than port number

![image](https://user-images.githubusercontent.com/22350668/75419415-bd93a300-5970-11ea-9473-7582b8aa5e5d.png)

![image](https://user-images.githubusercontent.com/22350668/75419468-d56b2700-5970-11ea-986c-30de39afac6b.png)

**Comment by leoendless** [comment]
By design @Carlosfengv

**Comment by Carlosfengv** [comment]
ui中显示portname 会带来额外的理解和操作成本，所以做了处理

**Comment by huanggze** [comment]
got it，不过自定义监控选择数据源 port 的时候可能需要 port name 了，因为便于理解。后面做的时候再看看 @Carlosfengv
