### ISSUE TITLE
Kubesphere 2.1.1 can't edit ingress annotation via UI

### ISSUE THREAD

**Issue by deerjoe** [kubesphere/kubesphere#1931]
**General remarks**

**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: 2.1.1
Kubernetes: KubeSphere installer (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration: 
Ubuntu 18.04/3 master: 2cpu/5g
Ubuntu 3 node: 4cpu/10g

**How To Reproduce**
1.Use Helm Cli install a chart,in this case is stable/ghost,it conntend an ingress
2. Go to Project>Application Workloads>Routes
2. Click on Edit Annotations
3. I can type anything in key textbox ,but when i tpye in value textbox,UI shows nothing 
4. Both Chrome and firefox can reproduce this error

![微信图片_20200227204504](https://user-images.githubusercontent.com/9907508/75446401-51ca2e00-59a2-11ea-902d-692d37a8a5f5.png)
![微信图片_20200227195748](https://user-images.githubusercontent.com/9907508/75446404-555db500-59a2-11ea-9efb-b9ec4a4824e1.png)

**Expected behavior**

**Comment by zryfish** [comment]
Please edit ks-console deployment yaml to change imagePullPolicy to `Always`, you can do this by using following command
```
kubectl -n kubesphere-system edit deployement ks-console

....
   imagePullPolicy: IfNotPresent // change IfNotPresent to Always
...
```

**Comment by zryfish** [comment]
/close
due to inactivity and this issue already been fixed
