### ISSUE TITLE
./add-node.sh failed： dockerproject repo 404

### ISSUE THREAD

**Issue by rysinal** [kubesphere/kubesphere#1937]
**What's your question**
./add-node.sh failed

**Environment: OS & Hardware Information**
 CentOS 7.5

**Error logs or message (Attach logs or screenshot)**
fatal: [node-5]: FAILED! => {"changed": false, "msg": "Error from repoquery: ['/bin/repoquery', '--show-duplicates', '--plugins', '--quiet', '--disablerepo', '','--enablerepo', '', '--qf', '%{name}|%{epoch}|%{version}|%{release}|%{arch}|%{repoid}', 'container-selinux']: Could not match packages: failure: repodata/repomd.xml from docker-engine: [Errno 256] No more mirrors to try.\nhttps://yum.dockerproject.org/repo/main/centos/7/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found\n"}

**Installer Version**
v2.1.1

**Comment by Forest-L** [comment]
@rysinal https://yum.dockerproject.org/repo/main/centos/7/repodata/repomd.xml

**Comment by rysinal** [comment]
> @rysinal https://yum.dockerproject.org/repo/main/centos/7/repodata/repomd.xml

It looks like it is disabled. Where can I modify it in the installation script? 3q

**Comment by Forest-L** [comment]
Temporary repair plan:
First、Modify  /etc/yum.repos.d/docker.repo  and Comment on the following steps;
```
vi /etc/yum.repos.d/docker.repo 
[docker-ce]
name=Docker-CE Repository
baseurl=https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/centos/7/$basearch/stable
enabled=1
gpgcheck=1
keepcache=0
gpgkey=https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/centos/gpg

#[docker-engine]
#name=Docker-Engine Repository
#baseurl=https://yum.download.docker.com/repo/main/centos/7
#enabled=1
#gpgcheck=1
#keepcache=0
#gpgkey=https://yum.download.docker.com/gpg
#
```
Second、Execute yum clean all;yum makecache;
Third、Modify /root/kubesphere-all-v2.1.1/k8s/roles/container-engine/docker/templates/rh_docker.repo.j2 and Comment on the following steps;
```
vi /etc/yum.repos.d/docker.repo 
[docker-ce]
name=Docker-CE Repository
baseurl=https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/centos/7/$basearch/stable
enabled=1
gpgcheck=1
keepcache=0
gpgkey=https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/centos/gpg

#[docker-engine]
#name=Docker-Engine Repository
#baseurl=https://yum.download.docker.com/repo/main/centos/7
#enabled=1
#gpgcheck=1
#keepcache=0
#gpgkey=https://yum.download.docker.com/gpg
#
```
Four、Re-execute the script

**Comment by rysinal** [comment]
solved
