### ISSUE TITLE
Why the All-in-one of intall online not support centos 7.6 ?

### ISSUE THREAD

**Issue by leo-je** [kubesphere/kubesphere#1939]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**What's your question**
i want install online use all-in-one  in the Centos 7.6,but it failed.
info:
fatal: [ks-allinone]: FAILED! => {
    "changed": false
}

MSG:

Unable to restart service docker: Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

**Environment: OS & Hardware Information**

> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).

**Error logs or message (Attach logs or screenshot)**

**Installer Version**

> e.g. v2.1.0, v2.1.1

**Comment by Forest-L** [comment]
Support! you can view log about docker; See "systemctl status docker.service" and "journalctl -xe" for details.
