### ISSUE TITLE
Got Invaild Port error,after  apply change an existing deployment's image in UI

### ISSUE THREAD

**Issue by deerjoe** [kubesphere/kubesphere#1947]
**Describe the Bug**

Got Invaild Port error,after  apply change an existing deployment's image which deployment have pod Port Settings  in UI

![截屏2020-03-12下午11 15 59](https://user-images.githubusercontent.com/9907508/76536769-be235200-64b7-11ea-929b-65050da7cbc7.png)

**Versions Used**
KubeSphere: 2.1.1

**Environment**

 CentOS 7.8 / 3 masters:  4cpu/16g; 3 nodes: 4cpu/16g

**How To Reproduce**
1. Choose an existing deployment,Go to 'More' > 'Edit Config Template' > 'Pod Template'
2. Click on edit icon of Container Image
3. change image
4. apply,See error

**Comment by calvinyv** [comment]
https://kubernetes.io/docs/concepts/services-networking/service/

As with Kubernetes names in general, names for ports must only contain lowercase alphanumeric characters and -. Port names must also start and end with an alphanumeric character.
