### ISSUE TITLE
Click app screenshot and enter the enlarge view picture page, can't click '<' '>' to switch pictures

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#1953]
steps：
1、The user enters the app template page
2、Select an app template and enter the app details page
3、Click the application information to enter the application information page
4、Click on the image in the screenshot ,enter enlarge view image page
5、Click '<''>' to switch images

expected result：
can switch to the previous or the next image

actual result ：
cannot switch to the previous or the next image

<img width="560" alt="微信图片_20200317190803" src="https://user-images.githubusercontent.com/36271543/76850877-3eb0cc80-6883-11ea-9be3-2b2544e98ec4.png">

**Comment by harrisonliu5** [comment]
kind/need-to-verify
