### ISSUE TITLE
PVC not found！ 

### ISSUE THREAD

**Issue by zhanlinfeng** [kubesphere/kubesphere#1954]
**What's your question**
ks-install failed。Error log is as follows:
```
TASK [common : Kubesphere | Check redis ha PersistentVolumeClaim] **************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/kubectl get pvc -n kubesphere-system data-redis-ha-server-0 -o jsonpath='{.status.capacity.storage}'\n", "delta": "0:00:00.298301", "end": "2020-03-17 09:48:21.700293", "msg": "non-zero return code", "rc": 1, "start": "2020-03-17 09:48:21.401992", "stderr": "Error from server (NotFound): persistentvolumeclaims \"data-redis-ha-server-0\" not found", "stderr_lines": ["Error from server (NotFound): persistentvolumeclaims \"data-redis-ha-server-0\" not found"], "stdout": "", "stdout_lines": []}
...ignoring
```
Except redis，other components also have this error prompt，such as openldap，etcd and so on.
I use kubectl to get PVC and PV, I get two PVC and PV, I also see corresponding Cloud disk in aliyun console 。Besides I get three last time。Result is as follows:
PVC:
```
NAMESPACE           NAME                      STATUS   VOLUME                                         CAPACITY   ACCESS MODES   STORAGECLASS            AGE
kubesphere-system   openldap-pvc-openldap-0   Bound    pv-disk-00c0b29c-e416-4db7-af3e-eaf8e765b7ee   20Gi       RWO            csi-alibabacloud-disk   63m
kubesphere-system   redis-pvc                 Bound    pv-disk-5f4fc768-0bf1-4ceb-b152-8c6b879a2af7   20Gi       RWO            csi-alibabacloud-disk   63m
```
PV:
```
NAME                                           CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                       STORAGECLASS            REASON   AGE
pv-disk-00c0b29c-e416-4db7-af3e-eaf8e765b7ee   20Gi       RWO            Delete           Bound    kubesphere-system/openldap-pvc-openldap-0   csi-alibabacloud-disk            71m
pv-disk-5f4fc768-0bf1-4ceb-b152-8c6b879a2af7   20Gi       RWO            Delete           Bound    kubesphere-system/redis-pvc                 csi-alibabacloud-disk            71m
```
The storage type I use is aliblock storage, my config like this:
```
alicloud_disk_csi_enabled: true
alicloud_disk_csi_is_default_class: true
ali_access_key_id: *****
ali_access_key_secret: *****
ali_disk_zoneId: cn-shenzhen-a
ali_disk_regionId: cn-shenzhen
ali_disk_fsType: ext4
ali_disk_type: cloud_ssd

```
Meanwhile， There is an another error log about minio as follows， I'm not sure if pvc error cause that promble.
```
TASK [common : Kubesphere | Deploy minio] **************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm upgrade --install ks-minio /etc/kubesphere/minio-ha -f /etc/kubesphere/custom-values-minio.yaml --set fullnameOverride=minio --namespace kubesphere-system --wait --timeout 1800\n", "delta": "0:30:00.412040", "end": "2020-03-17 10:18:33.046253", "msg": "non-zero return code", "rc": 1, "start": "2020-03-17 09:48:32.634213", "stderr": "Error: release ks-minio failed: timed out waiting for the condition", "stderr_lines": ["Error: release ks-minio failed: timed out waiting for the condition"], "stdout": "Release \"ks-minio\" does not exist. Installing it now.", "stdout_lines": ["Release \"ks-minio\" does not exist. Installing it now."]}
...ignoring

```
**Environment: OS & Hardware Information**
os: ubuntu 16.04, Two node(4 core, 8G), one master(4 core, 16G) and mechain is clear.

**Installer Version**
 kubesphere v2.1.1

**Comment by zhanlinfeng** [comment]
The log shows that KS install seems to skip PVC declaration。This is part of the log：
```
TASK [common : Getting PersistentVolumeName (mysql)] ***************************
skipping: [localhost]

TASK [common : Getting PersistentVolumeSize (mysql)] ***************************
skipping: [localhost]

TASK [common : Setting PersistentVolumeName (mysql)] ***************************
skipping: [localhost]

TASK [common : Setting PersistentVolumeSize (mysql)] ***************************
skipping: [localhost]

TASK [common : Getting PersistentVolumeName (etcd)] ****************************
skipping: [localhost]

TASK [common : Getting PersistentVolumeSize (etcd)] ****************************
skipping: [localhost]

TASK [common : Setting PersistentVolumeName (etcd)] ****************************
skipping: [localhost]

TASK [common : Setting PersistentVolumeSize (etcd)] ****************************
skipping: [localhost]
```

**Comment by FeynmanZhou** [comment]
@zhanlinfeng Have you configured the PVC as mentioned in the following list?

![image](https://user-images.githubusercontent.com/40452856/76874296-f527a800-68a9-11ea-95ba-df2653355870.png)

**Comment by zhanlinfeng** [comment]
> @zhanlinfeng Have you configured the PVC as mentioned in the following list?
> 
> ![image](https://user-images.githubusercontent.com/40452856/76874296-f527a800-68a9-11ea-95ba-df2653355870.png)

Yes，I set all volume to 20G（Alibaba cloud's current minimum limit now，maybe you should update the documents）except jenkins，and DevOps not opened.

**Comment by zhanlinfeng** [comment]
> @zhanlinfeng Have you configured the PVC as mentioned in the following list?
> 
> ![image](https://user-images.githubusercontent.com/40452856/76874296-f527a800-68a9-11ea-95ba-df2653355870.png)

All configurations in common.yaml related to  volume size are as follows:
`# devops/openpitrix/notification/alerting components depend on
# mysql/minio/etcd/openldap/redis to store credentials.
# Configure parameters below to set how much storage they use.
mysql_volume_size: 20Gi
minio_volume_size: 20Gi
etcd_volume_size: 20Gi
openldap_volume_size: 20Gi
redis_volume_size: 20Gi


# MONITORING CONFIGURATION
# monitoring is a MUST required component for KubeSphere,
# monitoring deployment configuration
# prometheus replicas numbers,
# 2 means better availability, but more resource consumption
prometheus_replicas: 2

# prometheus pod memory requests
prometheus_memory_request: 400Mi

# prometheus storage size,
# 20Gi means every prometheus replica consumes 20Gi storage
prometheus_volume_size: 20Gi

# whether to install a grafana
grafana_enabled: true

# LOGGING CONFIGURATION
# logging is an optional component when installing KubeSphere, and
# Kubernetes builtin logging APIs will be used if logging_enabled is set to false. 
# Builtin logging only provides limited functions, so recommend to enable logging.
logging_enabled: true
elasticsearch_master_replicas: 1
elasticsearch_data_replicas: 2
logsidecar_replicas: 2
elasticsearch_master_volume_size: 20Gi
elasticsearch_data_volume_size: 20Gi
log_max_age: 7
elk_prefix: logstash
kibana_enabled: true
#external_es_url: SHOULD_BE_REPLACED
#external_es_port: SHOULD_BE_REPLACED

# DEVOPS CONFIGURATION
# Devops is an optional component for KubeSphere.
devops_enabled: false
jenkins_memory_lim: 8Gi
jenkins_memory_req: 4Gi
jenkins_volume_size: 8Gi
jenkinsJavaOpts_Xms: 3g
jenkinsJavaOpts_Xmx: 6g
jenkinsJavaOpts_MaxRAM: 8g
sonarqube_enabled: false
#sonar_server_url: SHOULD_BE_REPLACED
#sonar_server_token: SHOULD_BE_REPLACED
`

**Comment by zhanlinfeng** [comment]
> @zhanlinfeng Have you configured the PVC as mentioned in the following list?
> 
> ![image](https://user-images.githubusercontent.com/40452856/76874296-f527a800-68a9-11ea-95ba-df2653355870.png)
All configurations in common related to data volume size are as follows:
```
# devops/openpitrix/notification/alerting components depend on
# mysql/minio/etcd/openldap/redis to store credentials.
# Configure parameters below to set how much storage they use.
mysql_volume_size: 20Gi
minio_volume_size: 20Gi
etcd_volume_size: 20Gi
openldap_volume_size: 20Gi
redis_volume_size: 20Gi


# MONITORING CONFIGURATION
# monitoring is a MUST required component for KubeSphere,
# monitoring deployment configuration
# prometheus replicas numbers,
# 2 means better availability, but more resource consumption
prometheus_replicas: 2

# prometheus pod memory requests
prometheus_memory_request: 400Mi

# prometheus storage size,
# 20Gi means every prometheus replica consumes 20Gi storage
prometheus_volume_size: 20Gi

# whether to install a grafana
grafana_enabled: true

# LOGGING CONFIGURATION
# logging is an optional component when installing KubeSphere, and
# Kubernetes builtin logging APIs will be used if logging_enabled is set to false. 
# Builtin logging only provides limited functions, so recommend to enable logging.
logging_enabled: true
elasticsearch_master_replicas: 1
elasticsearch_data_replicas: 2
logsidecar_replicas: 2
elasticsearch_master_volume_size: 20Gi
elasticsearch_data_volume_size: 20Gi
log_max_age: 7
elk_prefix: logstash
kibana_enabled: true
#external_es_url: SHOULD_BE_REPLACED
#external_es_port: SHOULD_BE_REPLACED

# DEVOPS CONFIGURATION
# Devops is an optional component for KubeSphere.
devops_enabled: false
jenkins_memory_lim: 8Gi
jenkins_memory_req: 4Gi
jenkins_volume_size: 8Gi
jenkinsJavaOpts_Xms: 3g
jenkinsJavaOpts_Xmx: 6g
jenkinsJavaOpts_MaxRAM: 8g
sonarqube_enabled: false
#sonar_server_url: SHOULD_BE_REPLACED
#sonar_server_token: SHOULD_BE_REPLACED
```

**Comment by FeynmanZhou** [comment]
@zhanlinfeng Have this issue get resolved?

**Comment by zhanlinfeng** [comment]
> @zhanlinfeng Have this issue get resolved?

No

**Comment by Forest-L** [comment]
@zhanlinfeng   Install prompt:  ignoring, There are other error messages
