### ISSUE TITLE
delete the app screenshot, click the cancel button, the screenshotis actually deleted

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#1955]
steps:
1、The user enters the app template page
2、Select an app template and enter the app details page
3、Click the edit information button and enter the edit page
4、Delete the image in the application screenshot
5、Click the cancel button in the edit page
6、Go to the app information page and view the app screenshot

expected result：
Application screenshot not deleted

actual result ：
Application screenshot  deleted

<img width="916" alt="微信图片_20200317191646" src="https://user-images.githubusercontent.com/36271543/76851729-bb907600-6884-11ea-9c28-bb14b832cc82.png">

/area console
/kind bug
/priority low
/assign @leoendless

**Comment by harrisonliu5** [comment]
Need to discuss this issue with backend developers
