### ISSUE TITLE
app version list can only show 10 records at most

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#1957]
steps:
1、The user enters the app template page
2、Select an app template and enter the app details page
3、enter app information page,and view app vesion list data

expected result：
When the number of versions exceeds 10, all version records can be displayed

actual result ：
When the number of versions exceeds 10, the list can only show 10 records at most

<img width="833" alt="微信截图_20200318122524" src="https://user-images.githubusercontent.com/36271543/76925398-3fde0a00-6914-11ea-92fc-095d9fc56efa.png">

/area console
/kind bug
/priority low
/assign @leoendless

**Comment by liuyp2018** [comment]
The tests confirm that the problem still exists

**Comment by liuyp2018** [comment]
The tests confirm that the problem still exists
/remove-kind need-to-verify

**Comment by harrisonliu5** [comment]
can you tell me your test env address?

**Comment by liuyp2018** [comment]
In fact, this is not the latest 10 records
![image](https://user-images.githubusercontent.com/36271543/90368793-3a404800-e09d-11ea-88e5-beac9e5f3c05.png)


/remove-kind need-to-verify

**Comment by harrisonliu5** [comment]
assign @zheng1

**Comment by zheng1** [comment]
Works as expected, those versions sort by upload time.

**Comment by harrisonliu5** [comment]
but it does not sort by upload time

**Comment by harrisonliu5** [comment]
[GET] http://139.198.12.26:30884/kapis/openpitrix.io/v1/workspaces/one-cluster-ws/apps/app-nl149Dl6007x/versions?orderBy=sequence&paging=limit%3D10%2Cpage%3D1&conditions=status%3Ddraft%7Csubmitted%7Crejected%7Cin-review%7Cpassed%7Cactive%7Csuspended&reverse=true

![image](https://user-images.githubusercontent.com/17872673/90461090-f9494180-e137-11ea-9188-9996c89372e9.png)

**Comment by zheng1** [comment]
Fix at https://github.com/openpitrix/openpitrix/pull/1037

**Comment by zheng1** [comment]
/kind need-to-verify

It will be sorted with the version name.

![截屏2020-08-18 19 58 44](https://user-images.githubusercontent.com/4156721/90519786-0ea38780-e19b-11ea-8676-a30bde80546a.png)

![截屏2020-08-18 19 59 02](https://user-images.githubusercontent.com/4156721/90519783-0d725a80-e19b-11ea-838b-7d84cf06b903.png)
