### ISSUE TITLE
Install Error by  kubesphere-all-express-1.0.0-alpha

### ISSUE THREAD

**Issue by tangdu** [kubesphere/kubesphere#198]
ASK [kubernetes/preinstall : Update package management cache (APT)] ***********
fatal: [ks-allinone]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "E: The repository 'http://ppa.launchpad.net/wine/wine-builds/ubuntu bionic Release' does not have a Release file.", "rc": 100, "stderr": "E: The repository 'http://ppa.launchpad.net/wine/wine-builds/ubuntu bionic Release' does not have a Release file.\n", "stderr_lines": ["E: The repository 'http://ppa.launchpad.net/wine/wine-builds/ubuntu bionic Release' does not have a Release file."], "stdout": "Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease\nHit:2 http://dl.google.com/linux/chrome/deb stable Release\nHit:4 http://cn.archive.ubuntu.com/ubuntu bionic InRelease\nHit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease\nHit:6 https://download.docker.com/linux/ubuntu bionic InRelease\nHit:7 https://dl.winehq.org/wine-builds/ubuntu bionic InRelease\nHit:8 http://cn.archive.ubuntu.com/ubuntu bionic-updates InRelease\nHit:9 http://cn.archive.ubuntu.com/ubuntu bionic-backports InRelease\nHit:10 http://ppa.launchpad.net/noobslab/macbuntu/ubuntu bionic InRelease\nHit:11 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu bionic InRelease\nIgn:12 http://ppa.launchpad.net/wine/wine-builds/ubuntu bionic InRelease\nErr:13 http://ppa.launchpad.net/wine/wine-builds/ubuntu bionic Release\n  404  Not Found [IP: 91.189.95.83 80]\nHit:14 http://linux.teamviewer.com/deb stable InRelease\nHit:15 http://linux.teamviewer.com/deb preview InRelease\nHit:16 http://packages.microsoft.com/repos/vscode stable InRelease\nReading package lists...\n", "stdout_lines": ["Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease", "Hit:2 http://dl.google.com/linux/chrome/deb stable Release", "Hit:4 http://cn.archive.ubuntu.com/ubuntu bionic InRelease", "Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease", "Hit:6 https://download.docker.com/linux/ubuntu bionic InRelease", "Hit:7 https://dl.winehq.org/wine-builds/ubuntu bionic InRelease", "Hit:8 http://cn.archive.ubuntu.com/ubuntu bionic-updates InRelease", "Hit:9 http://cn.archive.ubuntu.com/ubuntu bionic-backports InRelease", "Hit:10 http://ppa.launchpad.net/noobslab/macbuntu/ubuntu bionic InRelease", "Hit:11 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu bionic InRelease", "Ign:12 http://ppa.launchpad.net/wine/wine-builds/ubuntu bionic InRelease", "Err:13 http://ppa.launchpad.net/wine/wine-builds/ubuntu bionic Release", "  404  Not Found [IP: 91.189.95.83 80]", "Hit:14 http://linux.teamviewer.com/deb stable InRelease", "Hit:15 http://linux.teamviewer.com/deb preview InRelease", "Hit:16 http://packages.microsoft.com/repos/vscode stable InRelease", "Reading package lists..."]}

**Comment by pixiake** [comment]
Did it report an error when manual execution of command “apt-get update” ?
