### ISSUE TITLE
V2.1.1 应用创建成功后，状态仍显示更新中

### ISSUE THREAD

**Issue by Reminisd** [kubesphere/kubesphere#1991]
在 ”应用“ 下手动创建了示例应用，确认其 deployment 和svc都显示运行中，也可以正常访问，但该应用的状态还是 ”更新“。 服务治理不可用

**Comment by FeynmanZhou** [comment]
@Reminisd 
English only, this issue will be closed. For Chinese conversation, please go to [forum](https://kubesphere.com.cn/forum/).

It looks like a front-end bug. Please elaborate on how to reproduce this problem.
