### ISSUE TITLE
DevOps Credentials can't delete while add Name is url

### ISSUE THREAD

**Issue by vglede** [kubesphere/kubesphere#1994]
i use the kubesphere which version is 2.1.1. I created the creadentials which name is url like this flow picture.
![image](https://user-images.githubusercontent.com/38933373/78855476-9b547100-7a56-11ea-9412-c61ebbc7607e.png)

and i want to delete,  it imple the information of “not found”
![image](https://user-images.githubusercontent.com/38933373/78855357-40bb1500-7a56-11ea-8aa7-4a8cc4f6c25b.png)

**Comment by FeynmanZhou** [comment]
@leoendless  Is this a front end bug?

**Comment by leoendless** [comment]
Hi @vglede, the credential id cannot be an URL, that may cause redirect problems when entering the detail page. Please use a normal id with pattern ``/^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/`` , and we will add a format check before the credential form submitted.

**Comment by vglede** [comment]
Ok,thank you. i konw.
