### ISSUE TITLE
登录界面提示无法访问后端服务

### ISSUE THREAD

**Issue by xiaoyaolaotou** [kubesphere/kubesphere#1998]
[root@kvm-10-112-76-53 ~]# kubectl get po -n kubesphere-system -o wide
NAME                                     READY   STATUS     RESTARTS   AGE     IP            NODE           NOMINATED NODE   READINESS GATES
ks-account-7d57dc95fc-lk9wr              0/1     Init:1/2   0          4m17s   172.7.23.8    10.112.76.39   <none>           <none>
ks-apigateway-d6f89b96f-fzc5v            1/1     Running    0          4m19s   172.7.23.6    10.112.76.39   <none>           <none>
ks-apiserver-5dff5c594d-dhnpf            1/1     Running    0          4m18s   172.7.23.7    10.112.76.39   <none>           <none>
ks-console-5c666c644-74bxd               1/1     Running    0          4m14s   172.7.23.10   10.112.76.39   <none>           <none>
ks-controller-manager-779d9c6bbf-wfcf4   1/1     Running    0          4m16s   172.7.23.9    10.112.76.39   <none>           <none>
ks-installer-59fb465b7-rw2z4             1/1     Running    0          6m11s   172.7.23.4    10.112.76.39   <none>           <none>
redis-5d4844b947-j2fkm                   1/1     Running    0          4m49s   172.7.23.5    10.112.76.39   <none>           <none>

也能够解析：
~/KubeSphereUI # ping ks-account
PING ks-account (192.168.167.166): 56 data bytes
64 bytes from 192.168.167.166: seq=0 ttl=64 time=0.053 ms
64 bytes from 192.168.167.166: seq=1 ttl=64 time=0.089 ms

ks-account的日志：
[root@kvm-10-112-76-53 ~]# kubectl exec -it po/ks-console-5c666c644-74bxd -n kubesphere-system s
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"s\": executable file not found in $PATH": unknown

不知道怎么解决？

**Comment by xiaoyaolaotou** [comment]
[root@kvm-10-112-76-53 ~]# kubectl get po -n kubesphere-system
NAME                                     READY   STATUS     RESTARTS   AGE
ks-account-7d57dc95fc-lk9wr              0/1     Init:1/2   0          8m49s
ks-apigateway-d6f89b96f-fzc5v            1/1     Running    0          8m51s
ks-apiserver-5dff5c594d-dhnpf            1/1     Running    0          8m50s
ks-console-5c666c644-74bxd               1/1     Running    0          8m46s
ks-controller-manager-779d9c6bbf-wfcf4   1/1     Running    0          8m48s
ks-installer-59fb465b7-rw2z4             1/1     Running    0          10m
redis-5d4844b947-j2fkm                   1/1     Running    0          9m21s

**Comment by FeynmanZhou** [comment]
English only. 

It's duplicated with this [topic](https://kubesphere.com.cn/forum/d/1067-kubersphere/4), we will help you with this issue in the forum.
