### ISSUE TITLE
How can I search images from a local registry?

### ISSUE THREAD

**Issue by johdandc** [kubesphere/kubesphere#1999]
I have installed a local registry by harbor, and I have set an "Image Repository Secret".  But I can't search images from the local registry so I can only type the full name of the image to pull it.

So, how can I search images from a local registry?

BTW, because the local registry can only visited by intranet, so I can't use a trusted ssl cert while an untrusted cert can not let me set an "Image Repository Secret".

**Comment by aclk** [comment]
It will fix in the next release(v3.x.x).

**Comment by FeynmanZhou** [comment]
The invalid image search feature seems a bug after adding an https Harbor into KubeSphere. 
@calvinyv @shaowenchen Please take a look at this issue, I remember @aclk also encountered this bug.
