### ISSUE TITLE
Is it possible to connect to external OpenPitrix appstore?

### ISSUE THREAD

**Issue by 0000sir** [kubesphere/kubesphere#2006]
I would like to setup one external openpitrix application store for multiple kubesphere clusters, All kubesphere clusters are protected by firewalls, so the openpitrix will not connect to kubesphere directly. 

Is that possible for kubesphere to work like this and how to configure it ? Thank you

Deployment typo is demonstrated as below:
<img width="1181" alt="typo" src="https://user-images.githubusercontent.com/9480755/79108305-a71e9b00-7da8-11ea-96f1-269a374db26d.png">

**Comment by zheng1** [comment]
Hi, @0000sir , in version 2.1 we only support deploying applications from openpitrix in the current cluster. In the next 3.0 release, we will support multi-cluster, which means distributing applications to multiple clusters. The architecture is similar to your diagram.

**Comment by 0000sir** [comment]
That's a good news, we will see it in the middle of May, thank you !

**Comment by juan-vg** [comment]
Hello @zheng1 

Your answer is not completely accurate, so let me try to open this again. What I mean is that you're mixing stuff. Have a shared application repository is not actually linked to cluster federation. I could have 2 different clusters (obviously NOT federated) and use the same app repo. Just to reuse the apps

As I've been able to see on a [DZone tutorial](https://dzone.com/articles/deploy-grafana-to-kubernetes-using-application-tem-1) there was a time where the app repositories could be managed on the kubesphere console. **Where's that "Add app respository" button?** It's not possible to manage repos anymore? I want to have just 1 app repo, and several clusters -not federated among them- getting apps from there. It must be possible someway :)

**Comment by FeynmanZhou** [comment]
Hello @juan-vg,

The [DZone tutorial](https://dzone.com/articles/deploy-grafana-to-kubernetes-using-application-tem-1) is out-of-date, that post was demonstrated using v2.0.2.

Now you can refer to [this guide](https://kubesphere.io/docs/quick-start/one-click-deploy/) to import an external app repository to KubeSphere 2.1.1. This feature has been moved into the workspace in v2.1.1, I hope it can help you. 

If you have any questions, feel free to join us in [slack](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE).

**Comment by zheng1** [comment]
> Hello @zheng1
> 
> Your answer is not completely accurate, so let me try to open this again. What I mean is that you're mixing stuff. Have a shared application repository is not actually linked to cluster federation. I could have 2 different clusters (obviously NOT federated) and use the same app repo. Just to reuse the apps
> 
> As I've been able to see on a [DZone tutorial](https://dzone.com/articles/deploy-grafana-to-kubernetes-using-application-tem-1) there was a time when the app repositories could be managed on the kubesphere console. **Where's that "Add app respository" button?** It's not possible to manage repos anymore? I want to have just 1 app repo, and several clusters -not federated among them- getting apps from there. It must be possible someway :)

In the upcoming 3.0 version, multi-cluster management will be supported. You can **deploy the apps in the repo to different clusters on one dashboard**.

In version 2.x we can only support one dashboard to manage one cluster. But you can also use the same repo in multiple clusters, as long as the repo can be accessed.

**Comment by juan-vg** [comment]
So you will be able to manage several clusters which are completely independent between themselves (no federation)?

**Comment by zheng1** [comment]
> So we will be able to manage several clusters which are completely independent between themselves (no federation)?

yep.

**Comment by juan-vg** [comment]
Awesome! 😎
