### ISSUE TITLE
Anti affinity problem of KS-account and other components under high availability

### ISSUE THREAD

**Issue by jinxin3** [kubesphere/kubesphere#2009]
On the three nodes, high availability deployment is carried out. All three nodes have the roles of master and node. The following problems occur in the components KS-account and KS-apiserver under the kubesphere system namespace.

$kubectl describe pod -n kubesphere-system ks-account-cdd474f84-b49nr
....
Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 3 node(s) didn't match pod affinity/anti-affinity, 3 node(s) didn't satisfy existing pods anti-affinity rules.
...

When the number of copies of KS account and other components is changed to 2, it can run successfully.

**Comment by pixiake** [comment]
Current schedule policy of ks-core:
`nodeAffinity`: preferred
`podAntiAffinity`: required

@zryfish Should `podAntiAffinity` be replaced by `preferred`?
