### ISSUE TITLE
 Metrics-Server | Waitting for v1beta1.metrics.k8s.io ready]

### ISSUE THREAD

**Issue by weixiao122** [kubesphere/kubesphere#2010]
日志一直报错：
$ kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l app=ks-install -o jsonpath='{.items[0].metadata.name}') -f

error info：
TASK [metrics-server : Metrics-Server | Waitting for v1beta1.metrics.k8s.io ready] ***
FAILED - RETRYING: Metrics-Server | Waitting for v1beta1.metrics.k8s.io ready (60 retries left).
FAILED - RETRYING: Metrics-Server | Waitting for v1beta1.metrics.k8s.io ready (59 retries left).
FAILED - RETRYING: Metrics-Server | Waitting for v1beta1.metrics.k8s.io ready (58 retries left).
FAILED - RETRYING: Metrics-Server | Waitting for v1beta1.metrics.k8s.io ready (57 retries left).
FAILED - RETRYING: Metrics-Server | Waitting for v1beta1.metrics.k8s.io ready (56 retries left).
FAILED - RETRYING: Metrics-Server | Waitting for v1beta1.metrics.k8s.io ready (55 retries left).
FAILED - RETRYING: Metrics-Server | Waitting for v1beta1.metrics.k8s.io ready (54 retries left).
FAILED - RETRYING: Metrics-Server | Waitting for v1beta1.metrics.k8s.io ready (53 retries left).

$ kubectl get apiservices v1beta1.metrics.k8s.io -o jsonpath='{.status.conditions[0].status}'
False

**Comment by ixiejun** [comment]
me too

**Comment by FeynmanZhou** [comment]
@ixiejun @weixiao122 

Please refer to this post: https://kubesphere.com.cn/forum/d/882-kubesphere-2-1-1-metrics-server/5

**Comment by rayzhou2017** [comment]
@ixiejun @weixiao122 Is your problem solved?

**Comment by ixiejun** [comment]
> @ixiejun @weixiao122 Is your problem solved?

no, I have to close the metrics functionality,.

**Comment by kuwaitman** [comment]
i'm having the same issue. is there a solution?

**Comment by FeynmanZhou** [comment]
> i'm having the same issue. is there a solution?

@kuwaitman  Which version are you installing?

**Comment by kuwaitman** [comment]
> > i'm having the same issue. is there a solution?
> 
> @kuwaitman Which version are you installing?

kubesphere 3.0 ..
i'm trying to reinstall it. please send me a guide i am not able to install it ..

**Comment by FeynmanZhou** [comment]
> > > i'm having the same issue. is there a solution?
> > 
> > 
> > @kuwaitman Which version are you installing?
> 
> kubesphere 3.0 ..
> i'm trying to reinstall it. please send me a guide i am not able to install it ..

Actually, you can find the documents from [https://kubesphere.io/docs](https://kubesphere.io/docs).

**Comment by YANGBoSunning** [comment]
I had the same problem! Please solve it.
