### ISSUE TITLE
最新版本中凭证密码不能有特殊字符

### ISSUE THREAD

**Issue by rechardwang** [kubesphere/kubesphere#2023]
我在最新版本中使用“图形化构建流水线” 其中创建了账户凭证，但是我密码中含有 $ 符号，我按照文档里面进行了urlencode编码之后  还是错误，我在最原始的jenkins中创建凭证 即使有再多特殊字符也不会出问题，请问我该如何解决它？

**Comment by FeynmanZhou** [comment]
English only. For Chinese conversation, please go to [Forum](https://kubesphere.com.cn/forum/).

BTW, could you paste the error logs from your pipeline?
