### ISSUE TITLE
Local development environment

### ISSUE THREAD

**Issue by hadoop835** [kubesphere/kubesphere#2025]
Can a complete local open environment running document be provided，for example： /etc/kubesphere/...yaml,mysql init .sql

**Comment by zryfish** [comment]
It's a little bit time consuming to set up a complete development environment from scratch. You can install an all-in-one kubesphere using minikube or microk8s etc. Replace component you wish to debug, using tools like telepresence to connect to kubesphere.

**Comment by hadoop835** [comment]
Without a profile, it's hard to get started as a novice. There can be one operation step

**Comment by rayzhou2017** [comment]
> Without a profile, it's hard to get started as a novice. There can be one operation step

Yes, you are right. We are working on it. Because all of us are busy with closing the dev of 3.0, it might take time to release the guide.

**Comment by yuswift** [comment]
See the [pr](https://github.com/kubesphere/community/pull/230) for more details.
