### ISSUE TITLE
Create videos for the quick start demo cases

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2029]
There are a few samples at https://kubesphere.io/docs/quick-start/admin-quick-start/ helping users how to use KubeSphere. It would be better to create tutorial videos in English for these samples so that we can distribute them in some channels such as Youtube making more people get familiar with KubeSphere.

So call for English native speaker from the community to help us.

**Comment by FeynmanZhou** [comment]
I have finished four of them, and post them on [Youtube channel](https://www.youtube.com/channel/UCyTdUQUYjf7XLjxECx63Hpw). If anyone is willing to help us to do English video narration, please join us on [Slack](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE) or leave your comments in the current issue.
