### ISSUE TITLE
Failed to create any resources using KubeSphere on K3s

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#2030]
No Pod is created after a Deployment has been created on K3s.

![image](https://user-images.githubusercontent.com/40452856/80294765-6f4b2680-879e-11ea-8f34-05d3459afecf.png)

![image](https://user-images.githubusercontent.com/40452856/80294767-75d99e00-879e-11ea-8146-bb331bb4bebd.png)

**Comment by benjaminhuo** [comment]
@FeynmanZhou found this issue in your own testing env ?

**Comment by FeynmanZhou** [comment]
> @FeynmanZhou found this issue in your own testing env ?

This issue is reproduced in @yunkunrao 's testing env.
