### ISSUE TITLE
CoreDNS cluster ip doesn't appear in resolv.conf in all containers when using all-in-one deployment

### ISSUE THREAD

**Issue by wynn5a** [kubesphere/kubesphere#2031]
**What's your question**

I want to know why nameserver in containers does not match cluster ip of coredns.

It makes all containers don't work as expect.

```
~/KubeSphereUI # cat /etc/resolv.conf
nameserver 10.233.0.10
search kubesphere-system.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```

svc:

```
kubectl get svc -n kube-system
NAME                               TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                  AGE
coredns                            ClusterIP   10.233.0.2    <none>        53/UDP,53/TCP,9153/TCP   37m
```
**Environment: OS & Hardware Information**
Bare Metal, 64G 32C

**Installer Version**

v2.1.1

**Comment by pixiake** [comment]
The nameserver in the pod is specified by the kubelet's parameter(`clusterDNS`).

I think ,old kubelet configurations in your environment that have not been cleared, or have been modified kubelet and coredns config.

**Comment by wynn5a** [comment]
@pixiake but `/var/lib/kubelet/config.yaml` which `clusterDNS` appears  mostly like is generated by install.sh script.

My old cluster use different CIDR like 192.168.xxx.xxx for pod network and I execute `kubeadm reset` successfully that will delete all `/var/lib/kubelet/*`

Execute the install script more than one time maybe the root cause of the issue.

Please check the install script and make sure it can be executed multiple times.
