### ISSUE TITLE
Bad upgrade experience

### ISSUE THREAD

**Issue by 53537** [kubesphere/kubesphere#2034]
Kubesphere v2.1.0 upgrade v2.1.1:
Could you please separate kubernetes from Kubesphere and minimize the upgrade of kubernetes? We encountered calico, Prometheus, ks-ldap in both upgrades... Configuration and version changes were forced, resulting in significant failures, and we strongly wanted to minimize the impact on upgrades or optional configurations of existing clusters；
The current upgrade is terrible

**Comment by 53537** [comment]
The upgrade process should be inclusive, not necessarily kubernetes components and should allow us to have our own configuration as much as possible without overwriting our necessary custom components

**Comment by pixiake** [comment]
Yes, kubernetes and kubesphere should be separate.
If you just want to upgrade kubesphere you can use ks-installer：
https://github.com/kubesphere/ks-installer

**Comment by 53537** [comment]
Now our test environment has been upgraded according to the website ks and k8s; Can we still use the website upgrade method, but comment out the calico upgrade configuration? Because we want to keep the formal environment consistent with the test environment

**Comment by pixiake** [comment]
You can comment out calico or network_plugin's tasks in `k8s/upgrade-cluster.yml`.

The k8s cluster is also managed through open source tools:
https://github.com/kubernetes-sigs/kubespray
