### ISSUE TITLE
v2.1.1 some pods not in running

### ISSUE THREAD

**Issue by tmpm697** [kubesphere/kubesphere#2036]
## English only!

**General remarks**
I find some pods: istio-telemetry-795466fc84-776qv is pending, istio-init-crd-10-1.3.3-dmzfd and istio-init-crd-11-1.3.3-tqmsp and istio-init-crd-12-1.3.3-429bf is in completed state.

kubectl logs istio-init-crd-12-1.3.3-429bf -n istio-system
`Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply`

**What's your question**
Why istio-init-crd not in running state even though I had provided many resources?

**Environment: OS & Hardware Information**
archlinux up-to-date, cpu 2 core, 32GB rams, each kvm vm has 8GB of ram, 2 vcpus.

> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).
bare metal, installed k8s using as sudo ./install.sh with three nodes all 8gb of ram and 2 vcpus, 1 master and 2 worker nodes.

**Installer Version**
v2.1.1

**Comment by yunkunrao** [comment]
@zryfish

**Comment by tmpm697** [comment]
I've noticed that all `istio-init-crd-*` have been scheduled to the same worker node -- that may cause resources contest. How to schedule them to two worker nodes? (I have two worker nodes)

**Comment by tmpm697** [comment]
In case of I installed `calico` instead of `flannel`, I didn't see `istio-telemetry-??` anymore.

**Comment by zryfish** [comment]
istio-init-crd-* are jobs, once they are completed, they are done. Can you check your cluster resources usage, pending state usually means resource starvation. Please run following command on your cluster node, and check resource requests, see if their numbers are very high
```
kubectl describe node  | grep "Allocated resources:" -A 6
```

**Comment by zryfish** [comment]
/close
due to inactivity
