### ISSUE TITLE
ks-apigateway pod in CrashLoopBackOff after fresh install of kubesphere v2.1.1

### ISSUE THREAD

**Issue by hc2900** [kubesphere/kubesphere#2044]
**Describe the Bug**
I installed kubesphere v2.1.1 on kubernetes, every seems ok, when I tried to login to kubesphere ui,
it display the "internal error" on web page. 

**kubernetes cluster work ok**
```
[root@k8s-worker1 ks-installer]# kubectl get nodes
NAME          STATUS   ROLES    AGE   VERSION
k8s-master1   Ready    master   26h   v1.17.0
k8s-master2   Ready    master   26h   v1.17.0
k8s-master3   Ready    master   26h   v1.17.0
k8s-worker1   Ready    <none>   26h   v1.17.0
k8s-worker2   Ready    <none>   26h   v1.17.0
k8s-worker3   Ready    <none>   26h   v1.17.0
[root@k8s-worker1 ks-installer]# `

`
**the pod's status :** 
[root@k8s-worker2 ~]# kubectl get pods -n kubesphere-system
NAME                                     READY   STATUS             RESTARTS   AGE
ks-account-57949cb644-8xvp8              0/1     Init:0/2           0          144m
ks-account-69bbf866b7-tjcsz              0/1     Init:0/2           0          109m
ks-account-789cd8bbd5-5nczk              0/1     Init:0/2           0          172m
ks-account-789cd8bbd5-gtn2d              0/1     Init:0/2           0          172m
ks-apigateway-66675f79b6-9vxvv           0/1     CrashLoopBackOff   25         109m
ks-apigateway-66675f79b6-dmdzp           0/1     CrashLoopBackOff   25         109m
ks-apigateway-66675f79b6-zmvvh           0/1     CrashLoopBackOff   25         109m
ks-apiserver-554f487b9d-5jwjs            1/1     Running            0          109m
ks-apiserver-554f487b9d-fcg27            1/1     Running            0          109m
ks-apiserver-554f487b9d-lvj29            1/1     Running            0          109m
ks-console-5d487dcf88-5w5fd              1/1     Running            0          109m
ks-console-5d487dcf88-kzth7              1/1     Running            0          109m
ks-console-5d487dcf88-ps6bp              1/1     Running            0          109m
ks-controller-manager-6496bf84c5-2ltpp   1/1     Running            0          109m
ks-controller-manager-6496bf84c5-g9msr   1/1     Running            0          109m
ks-controller-manager-6496bf84c5-pl46k   1/1     Running            0          109m
ks-installer-75b8d89dff-qm2dd            1/1     Running            0          112m
```

[root@k8s-worker2 ~]# kubectl describe po -n kubesphere-system ks-apigateway-66675f79b6-9vxvv
```
Name:         ks-apigateway-66675f79b6-9vxvv
Namespace:    kubesphere-system
Priority:     0
Node:         k8s-master2/172.23.112.31
Start Time:   Sat, 02 May 2020 18:41:18 +0800
Labels:       app=ks-apigateway
              pod-template-hash=66675f79b6
              tier=backend
              version=v2.1.1
Annotations:  cni.projectcalico.org/podIP: 10.100.224.19/32
              kubectl.kubernetes.io/restartedAt: 2020-05-02T10:41:18Z
Status:       Running
IP:           10.100.224.19
IPs:
  IP:           10.100.224.19
Controlled By:  ReplicaSet/ks-apigateway-66675f79b6
Containers:
  ks-apigateway:
    Container ID:  docker://d8a721f9bdca6781f79854e174c97668e993c576eede292791113202d56a4939
    Image:         kubesphere/ks-apigateway:v2.1.1
    Image ID:      docker-pullable://kubesphere/ks-apigateway@sha256:805d1e89aebd391d04bcc0d10fcef2529bad88e0919b5751c043a83fd1781592
    Port:          2018/TCP
    Host Port:     0/TCP
    Command:
      /bin/sh
      -c
      export KUBESPHERE_TOKEN=`cat /var/run/secrets/kubernetes.io/serviceaccount/token` && ks-apigateway --conf=/etc/caddy/Caddyfile --log=stderr
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 02 May 2020 20:37:12 +0800
      Finished:     Sat, 02 May 2020 20:37:17 +0800
    Ready:          False
    Restart Count:  27
    Limits:
      cpu:     1
      memory:  500Mi
    Requests:
      cpu:     20m
      memory:  100Mi
    Environment:
      JWT_SECRET:  <set to the key 'jwt-secret' in secret 'ks-account-secret'>  Optional: false
    Mounts:
      /etc/caddy from caddyfile (rw)
      /etc/kubesphere from kubesphere-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubesphere-token-w9dxq (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  caddyfile:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      caddyfile
    Optional:  false
  kubesphere-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kubesphere-config
    Optional:  false
  kubesphere-token-w9dxq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubesphere-token-w9dxq
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 60s
                 node.kubernetes.io/unreachable:NoExecute for 60s
Events:
  Type     Reason   Age                   From                  Message
  ----     ------   ----                  ----                  -------
  Normal   Pulled   21m (x24 over 116m)   kubelet, k8s-master2  Container image "kubesphere/ks-apigateway:v2.1.1" already present on machine
  Warning  BackOff  61s (x520 over 116m)  kubelet, k8s-master2  Back-off restarting failed container
```

the log output
````
[root@k8s-worker2 ~]# kubectl logs -n kubesphere-system ks-apigateway-66675f79b6-9vxvv
[DEV NOTICE] Registered directive 'authenticate' before 'jwt'
[DEV NOTICE] Registered directive 'authentication' before 'jwt'
[DEV NOTICE] Registered directive 'swagger' before 'jwt'
Activating privacy features... done.
2020/05/02 12:37:12 [INFO][cache:0xc00045d680] Started certificate maintenance routine
E0502 12:37:17.292808       1 redis.go:51] unable to reach redis hostdial tcp: i/o timeout
2020/05/02 12:37:17 dial tcp: i/o timeout
```


**Versions Used**
- [ ] KubeSphere: 2.1.1
- [ ] CentOS 7.7
- [ ] Kubernetes: 1.7
- [ ] helm v2.12.3


**Environment**
3 master + 3 worker
CentOS7.7 3 masters: 8CPU + 16G every node
CentOS7.7 3 nodes: 8CPU + 16G every node
SeLinux disabled ，Swap off, Firewall closed

|  hostname	| IP                   |  role         | requirement 	|  		Remark	                |    
| :------------   -|------------:|:- |------------|---------------       |--------------------------------|
| k8s-master1	|172.23.112.30 | master        |16G+100G   	|			                        |
| k8s-master2	|172.23.112.31 | master        |16G+100G   	|			                        |
| k8s-master3	|172.23.112.32 | master        |16G+100G   	|			                        |
| k8s-worker1	|172.23.112.33 | worker        |16G+100G   	|			                        |
| k8s-worker2	|172.23.112.34 | worker        |16G+100G   	|                                               |
| k8s-worker3	|172.23.112.35 | worker        |16G+100G   	|                                               |
| lvs01              |172.23.112.36| keepalived    |2G+20G     	|  VIP172.23.112.40                  |
| lvs02              |172.23.112.37| keepalived    |2G+20G   	        |  VIP172.23.112.40                  |



**How To Reproduce**
Steps to reproduce the behavior:
1. install the kubernetes cluster on 3 master and 3 nodes, ensure cluster works ok，I setup the kubernetes with _kubeadm_
2. ```git clone https://github.com/kubesphere/ks-installer.git``` to download kubesphere2.1.1 
3. ```vi kubesphere-minimal.yaml ``` to modify the etcd ip 
4. ``` kubectl apply -f  kubesphere-minimal.yaml```
5. ```kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l app=ks-install -o jsonpath='{.items[0].metadata.name}') -f ```  to check the install status 🔢 
```
..........................................
Start installing monitoring
**************************************************
task monitoring status is successful
total: 1     completed:1
**************************************************
#####################################################
###              Welcome to KubeSphere!           ###
#####################################################

Console: http://172.23.112.30:30880
Account: admin
Password: P@88w0rd

NOTES：
  1. After logging into the console, please check the
     monitoring status of service components in
     the "Cluster Status". If the service is not
     ready, please wait patiently. You can start
     to use when all components are ready.
  2. Please modify the default password after login.

#####################################################
```
**Expected behavior**
all pods in the kubesphere-system up and running, then be able to login to the console

**Comment by hc2900** [comment]
I used OpenEBS 
[root@k8s-worker1 ks-installer]# kubectl get sc
```
NAME                         PROVISIONER                                                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
openebs-device               openebs.io/local                                           Delete          WaitForFirstConsumer   false                  11h
openebs-hostpath (default)   openebs.io/local                                           Delete          WaitForFirstConsumer   false                  11h
openebs-jiva-default         openebs.io/provisioner-iscsi                               Delete          Immediate              false                  11h
openebs-snapshot-promoter    volumesnapshot.external-storage.k8s.io/snapshot-promoter   Delete          Immediate              false                  11h
```

**Comment by wansir** [comment]
It seems that the pods of sts/redis and sts/openldap have not been created, it is related to the storage class. You can check the status of sts/redis and pvc status.

**Comment by Forest-L** [comment]
Check out the redis log.

**Comment by whalecold** [comment]
The same problem:
```
1:C 17 Jun 2020 03:20:18.831 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 17 Jun 2020 03:20:18.831 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 17 Jun 2020 03:20:18.831 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 17 Jun 2020 03:20:18.835 * Running mode=standalone, port=6379.
1:M 17 Jun 2020 03:20:18.835 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 17 Jun 2020 03:20:18.835 # Server initialized
1:M 17 Jun 2020 03:20:18.835 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 17 Jun 2020 03:20:18.835 * DB loaded from disk: 0.000 seconds
1:M 17 Jun 2020 03:20:18.835 * Ready to accept connections
```
The redis log has no error message.

**Comment by rarecrane** [comment]
[root@k8s-master ~]# kubectl discribe -n kubesphere-system ks-apigateway-78bcdc8ffc-pkgm6
Error: unknown command "discribe" for "kubectl"

Did you mean this?
	describe

Run 'kubectl --help' for usage.
[root@k8s-master ~]# kubectl describe -n kubesphere-system ks-apigateway-78bcdc8ffc-pkgm6
error: the server doesn't have a resource type "ks-apigateway-78bcdc8ffc-pkgm6"
[root@k8s-master ~]# kubectl describe pod  -n kubesphere-system ks-apigateway-78bcdc8ffc-pkgm6
Name:         ks-apigateway-78bcdc8ffc-pkgm6
Namespace:    kubesphere-system
Priority:     0
Node:         k8s-master/192.168.0.171
Start Time:   Thu, 10 Sep 2020 00:30:29 +0800
Labels:       app=ks-apigateway
              pod-template-hash=78bcdc8ffc
              tier=backend
              version=v2.1.1
Annotations:  cni.projectcalico.org/podIP: 10.244.235.225/32
              cni.projectcalico.org/podIPs: 10.244.235.225/32
Status:       Running
IP:           10.244.235.225
IPs:
  IP:           10.244.235.225
Controlled By:  ReplicaSet/ks-apigateway-78bcdc8ffc
Containers:
  ks-apigateway:
    Container ID:  docker://db47c14c22fd884ea802bda305cda4109c09738599c153235f749371e6409a93
    Image:         kubesphere/ks-apigateway:v2.1.1
    Image ID:      docker-pullable://kubesphere/ks-apigateway@sha256:805d1e89aebd391d04bcc0d10fcef2529bad88e0919b5751c043a83fd1781592
    Port:          2018/TCP
    Host Port:     0/TCP
    Command:
      /bin/sh
      -c
      export KUBESPHERE_TOKEN=`cat /var/run/secrets/kubernetes.io/serviceaccount/token` && ks-apigateway --conf=/etc/caddy/Caddyfile --log=stderr
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 10 Sep 2020 01:53:17 +0800
      Finished:     Thu, 10 Sep 2020 01:53:17 +0800
    Ready:          False
    Restart Count:  24
    Limits:
      cpu:     1
      memory:  500Mi
    Requests:
      cpu:     20m
      memory:  100Mi
    Environment:
      JWT_SECRET:  <set to the key 'jwt-secret' in secret 'ks-account-secret'>  Optional: false
    Mounts:
      /etc/caddy from caddyfile (rw)
      /etc/kubesphere from kubesphere-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubesphere-token-8jsqh (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  caddyfile:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      caddyfile
    Optional:  false
  kubesphere-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kubesphere-config
    Optional:  false
  kubesphere-token-8jsqh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubesphere-token-8jsqh
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 60s
                 node.kubernetes.io/unreachable:NoExecute for 60s
Events:
  Type     Reason          Age                    From                 Message
  ----     ------          ----                   ----                 -------
  Warning  BackOff         10m (x346 over 85m)    kubelet, k8s-master  Back-off restarting failed container
  Normal   SandboxChanged  5m40s (x2 over 6m24s)  kubelet, k8s-master  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled          3m58s (x4 over 5m37s)  kubelet, k8s-master  Container image "kubesphere/ks-apigateway:v2.1.1" already present on machine
  Normal   Created         3m57s (x4 over 5m36s)  kubelet, k8s-master  Created container ks-apigateway
  Normal   Started         3m57s (x4 over 5m35s)  kubelet, k8s-master  Started container ks-apigateway
  Warning  BackOff         62s (x22 over 5m32s)   kubelet, k8s-master  Back-off restarting failed container
[root@k8s-master ~]# kubectl  get pods -n kubesphere-system
NAME                                     READY   STATUS             RESTARTS   AGE
ks-account-596657f8c6-nrftn              0/1     Init:0/2           1          87m
ks-apigateway-78bcdc8ffc-pkgm6           0/1     CrashLoopBackOff   25         87m
ks-apiserver-5b548d7c5c-zfdjw            1/1     Running            1          87m
ks-console-78bcf96dbf-d59kl              1/1     Running            1          87m
ks-controller-manager-696986f8d9-8tlvv   1/1     Running            1          87m
ks-installer-75b8d89dff-xl4qs            1/1     Running            0          89m
redis-6fd6c6d6f9-v88zv                   0/1     Pending            0          88m
[root@k8s-master ~]# kubectl  get pods --all-namespaces -o wide
NAMESPACE                      NAME                                            READY   STATUS             RESTARTS   AGE     IP               NODE         NOMINATED NODE   READINESS GATES
kube-system                    calico-kube-controllers-578b7dcd94-ptz9b        1/1     Running            2          3d19h   10.244.169.142   k8s-node2    <none>           <none>
kube-system                    calico-node-djs4b                               1/1     Running            4          3d19h   192.168.0.171    k8s-master   <none>           <none>
kube-system                    calico-node-krvgk                               1/1     Running            2          3d19h   192.168.0.173    k8s-node2    <none>           <none>
kube-system                    calico-node-pr744                               1/1     Running            2          3d19h   192.168.0.172    k8s-node1    <none>           <none>
kube-system                    coredns-6955765f44-m6l6k                        1/1     Running            4          3d20h   10.244.235.221   k8s-master   <none>           <none>
kube-system                    coredns-6955765f44-wt4fr                        1/1     Running            4          3d20h   10.244.235.223   k8s-master   <none>           <none>
kube-system                    etcd-k8s-master                                 1/1     Running            154        3d20h   192.168.0.171    k8s-master   <none>           <none>
kube-system                    kube-apiserver-k8s-master                       1/1     Running            105        3d20h   192.168.0.171    k8s-master   <none>           <none>
kube-system                    kube-controller-manager-k8s-master              1/1     Running            5          3d20h   192.168.0.171    k8s-master   <none>           <none>
kube-system                    kube-proxy-b2p2d                                1/1     Running            2          3d20h   192.168.0.172    k8s-node1    <none>           <none>
kube-system                    kube-proxy-jcp4j                                1/1     Running            4          3d20h   192.168.0.171    k8s-master   <none>           <none>
kube-system                    kube-proxy-vbmlv                                1/1     Running            2          3d20h   192.168.0.173    k8s-node2    <none>           <none>
kube-system                    kube-scheduler-k8s-master                       1/1     Running            5          3d20h   192.168.0.171    k8s-master   <none>           <none>
kube-system                    tiller-deploy-86445968c5-k974n                  1/1     Running            1          13h     10.244.36.88     k8s-node1    <none>           <none>
kubesphere-controls-system     default-http-backend-5d464dd566-946xx           1/1     Running            1          12h     10.244.36.91     k8s-node1    <none>           <none>
kubesphere-monitoring-system   kube-state-metrics-566cdbcb48-tqwq6             4/4     Running            4          12h     10.244.169.148   k8s-node2    <none>           <none>
kubesphere-monitoring-system   node-exporter-58jrq                             2/2     Running            2          12h     192.168.0.173    k8s-node2    <none>           <none>
kubesphere-monitoring-system   node-exporter-6lmfd                             2/2     Running            4          12h     192.168.0.171    k8s-master   <none>           <none>
kubesphere-monitoring-system   node-exporter-zjkws                             2/2     Running            2          12h     192.168.0.172    k8s-node1    <none>           <none>
kubesphere-monitoring-system   prometheus-k8s-0                                3/3     Running            1          12h     10.244.36.98     k8s-node1    <none>           <none>
kubesphere-monitoring-system   prometheus-k8s-system-0                         3/3     Running            4          12h     10.244.169.147   k8s-node2    <none>           <none>
kubesphere-monitoring-system   prometheus-operator-6b97679cfd-q8hj5            1/1     Running            2          12h     10.244.36.89     k8s-node1    <none>           <none>
kubesphere-system              ks-account-596657f8c6-nrftn                     0/1     Init:0/2           1          88m     10.244.235.224   k8s-master   <none>           <none>
kubesphere-system              ks-apigateway-78bcdc8ffc-pkgm6                  0/1     CrashLoopBackOff   25         88m     10.244.235.225   k8s-master   <none>           <none>
kubesphere-system              ks-apiserver-5b548d7c5c-zfdjw                   1/1     Running            1          88m     10.244.235.227   k8s-master   <none>           <none>
kubesphere-system              ks-console-78bcf96dbf-d59kl                     1/1     Running            1          88m     10.244.235.228   k8s-master   <none>           <none>
kubesphere-system              ks-controller-manager-696986f8d9-8tlvv          1/1     Running            1          88m     10.244.235.226   k8s-master   <none>           <none>
kubesphere-system              ks-installer-75b8d89dff-xl4qs                   1/1     Running            0          90m     10.244.36.99     k8s-node1    <none>           <none>
kubesphere-system              redis-6fd6c6d6f9-v88zv                          0/1     Pending            0          89m     <none>           <none>       <none>           <none>
openebs                        init-pvc-e2566796-2d37-4df3-8210-a96e9ecf4c65   0/1     Pending            0          89s     <none>           <none>       <none>           <none>
openebs                        openebs-admission-server-5cf6864fbf-7qzz7       1/1     Running            2          21h     10.244.169.144   k8s-node2    <none>           <none>
openebs                        openebs-apiserver-bc55cd99b-tntsp               1/1     Running            12         21h     10.244.36.87     k8s-node1    <none>           <none>
openebs                        openebs-localpv-provisioner-85ff89dd44-2scn7    1/1     Running            8          21h     10.244.169.145   k8s-node2    <none>           <none>
openebs                        openebs-ndm-kns9m                               1/1     Running            4          21h     192.168.0.173    k8s-node2    <none>           <none>
openebs                        openebs-ndm-operator-87df44d9-mh2fm             1/1     Running            3          21h     10.244.169.143   k8s-node2    <none>           <none>
openebs                        openebs-ndm-t5pth                               1/1     Running            6          21h     192.168.0.171    k8s-master   <none>           <none>
openebs                        openebs-ndm-zpktj                               1/1     Running            3          21h     192.168.0.172    k8s-node1    <none>           <none>
openebs                        openebs-provisioner-7f86c6bb64-c6rj8            1/1     Running            10         21h     10.244.169.146   k8s-node2    <none>           <none>
openebs                        openebs-snapshot-operator-54b9c886bf-6xjb2      2/2     Running            7          21h     10.244.36.86     k8s-node1    <none>           <none>
[root@k8s-master ~]#

**Comment by rarecrane** [comment]
kubectl describe pod redis-6fd6c6d6f9-v88zv  -n kubesphere-system
Name:           redis-6fd6c6d6f9-v88zv
Namespace:      kubesphere-system
Priority:       0
Node:           <none>
Labels:         app=redis
                pod-template-hash=6fd6c6d6f9
                tier=database
                version=redis-4.0
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/redis-6fd6c6d6f9
Containers:
  redis:
    Image:      redis:5.0.5-alpine
    Port:       6379/TCP
    Host Port:  0/TCP
    Limits:
      cpu:     1
      memory:  1000Mi
    Requests:
      cpu:        20m
      memory:     100Mi
    Environment:  <none>
    Mounts:
      /data from redis-pvc (rw,path="redis-data")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-dj46l (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  redis-pvc:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  redis-pvc
    ReadOnly:   false
  default-token-dj46l:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-dj46l
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  Failed to bind volumes: timed out waiting for the condition
  Warning  FailedScheduling  <unknown>  default-scheduler  Failed to bind volumes: timed out waiting for the condition
  Warning  FailedScheduling  <unknown>  default-scheduler  Failed to bind volumes: timed out waiting for the condition
  Warning  FailedScheduling  <unknown>  default-scheduler  Failed to bind volumes: timed out waiting for the condition
  Warning  FailedScheduling  8m34s      default-scheduler  Failed to bind volumes: timed out waiting for the condition
