### ISSUE TITLE
ks-account docker built succeed but failed when creating users with report "Internal Server Error open /etc/kubernetes/pki/ca.crt: no such file or directory"

### ISSUE THREAD

**Issue by wartih** [kubesphere/kubesphere#2046]
Following https://github.com/kubesphere/community/tree/master/developer-guide/development 
"For Building KubeSphere Core Images", I built ks-account docker image,after recreate ks-account pod, I find I can't create user with error"Internal Server Error open /etc/kubernetes/pki/ca.crt: no such file or directory"

I notice build/ks-account has been deleted, why it happend? And how can i build ks-account after making some change in iam?

KubeSphere: 2.1.1

Ubuntu 16.04.6 all-in-one 32cpu/64g

**Comment by wansir** [comment]
We merged ks-apigateway, ks-apiserver, ks-account in 3.0, we only kept ks-apiserver and ks-controller-manager to make the system architecture simple. Sorry that the developer guide has caused you confusion, your error is related to these lines of code: https://github.com/kubesphere/kubesphere/blob/v2.1.1/cmd/ks-iam/app/options/options.go#L70
https://github.com/kubesphere/kubesphere/blob/v2.1.1/cmd/ks-iam/app/options/options.go#L83-L91

We'll improve the developer guide in 3.0, thanks for your attention.

**Comment by wartih** [comment]
Mounting hostpath /etc/kubernetes/ssl to pod /etc/kubernetes/pki solved this problem. Expecting the new version~
