### ISSUE TITLE
Pod had failured to reduce copies on schedule

### ISSUE THREAD

**Issue by vglede** [kubesphere/kubesphere#2064]
Hello
    I am using the kubersphere at v2.1.0 version.when I used the Horizontal Pod Autoscaling  function i found the Pod had failured to reduce copies on schedule .I set params like below picture.
![20200513](https://user-images.githubusercontent.com/38933373/81810363-6657a480-9555-11ea-9eb4-2604ab94c546.png)
what should need i do i can reduce copies on schedule.

**Comment by yunkunrao** [comment]
Hi, the num of copies are mainly based on the actual pod resource utilization. First please make sure the request and traffic has dropped. And you can reference ks doc: https://kubesphere.io/docs/installation/install-metrics-server/#introduction-to-hpa

**Comment by vglede** [comment]
Ok.I will check  it later.

**Comment by vglede** [comment]
> Hi, the num of copies are mainly based on the actual pod resource utilization. First please make sure the request and traffic has dropped. And you can reference ks doc: https://kubesphere.io/docs/installation/install-metrics-server/#introduction-to-hpa

Ok.i will check it later.Thank you.
