### ISSUE TITLE
hitting an issue when running installation

### ISSUE THREAD

**Issue by TomMann** [kubesphere/kubesphere#2067]
Im running the latest installer in a air-gapped setup. I'm getting the following error when it tries install the packages

TASK [kubernetes/preinstall : Install packages requirements] *******************************************************************************************************************************************************************************************
Wednesday 13 May 2020  13:23:08 +0200 (0:00:00.186)       0:01:13.575 *********
FAILED - RETRYING: Install packages requirements (4 retries left).
FAILED - RETRYING: Install packages requirements (3 retries left).
FAILED - RETRYING: Install packages requirements (2 retries left).
FAILED - RETRYING: Install packages requirements (1 retries left).
fatal: [ks-allinone]: FAILED! => {
    "attempts": 4,
    "changed": false,
    "rc": 1,
    "results": []
}

looks like the local repo doesnt  load (its trying to connect to its self)  and so the installation fails. any suggestions would be great.

**Comment by pixiake** [comment]
which OS ？ 
If you use offline pkg，`apt `or `yum` source is setup by a container which named pkg-download-center，and  software pkg is in /kubeinstaller

**Comment by Forest-L** [comment]
try to apt update or yum clean all && yum makecache

**Comment by TomMann** [comment]
Thanks for your responses, using RHEL 7.8.
running yum clean all && yum makecache fails with the same error 
http://<serversIP>:5080/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#7 - "Failed connect to <serversIP>:5080; Connection refused"

**Comment by pixiake** [comment]
`docker ps -a`

**Comment by pixiake** [comment]
`RHEL 7.8` 
Since RHEL requires lisence, the offline  pkg does not adapt to this operating system.
It is recommended that you can  use `ubuntu` or `centos`，or deploy kubernetes yourself and install KubeSphere by [ks-installer](https://github.com/kubesphere/ks-installer).

**Comment by TomMann** [comment]
Seems strange that you have RHEL as a listed supported os. But thanks

**Comment by pixiake** [comment]
If you RHEL get license, you can install KubeSphere by online pkg.

**Comment by TomMann** [comment]
Thanks @pixiake we do have license. I work at a large enterprise, the issue is our repos are internal with only an approved subset on a satelite setup which is why the offline/airgapped setup was a requirement. Anyways thanks for taking the time to look at this.

**Comment by rayzhou2017** [comment]
The doc will be updated for the clarification. Right now you can install K8s by yourself using kubeadmin for instance. Then deploy KubeSphere by following the guide from github.com/kubesphere/ks-installer which is able to deploy KubeSphere on existing K8s cluster. We will fix the air gapped installer for RHEL soon. Sorry for the confusion.
