### ISSUE TITLE
When deploying applications or upgrading applications, container name generation cannot automatically ignore those that do not meet the rules.

### ISSUE THREAD

**Issue by vglede** [kubesphere/kubesphere#2081]
Hello:
   When deploying applications or upgrading applications, container name generation cannot automatically ignore those that do not meet the rules.
![20200518](https://user-images.githubusercontent.com/38933373/82173481-facc5900-98ff-11ea-98a8-0ac774550e16.png)
if support automatically ignore those that do not meet the rules when  container name generation. i think  it will better for use.

**Comment by leoendless** [comment]
It’s bug of kubesphere console, and will be fixed in 3.0
