### ISSUE TITLE
Install openpitrix  initContainers fail

### ISSUE THREAD

**Issue by hewenhong** [kubesphere/kubesphere#2082]
**General remarks**
install openpitrix  initContainers fail
> Please delete this section including header before submitting
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the Bug**
[root@prod-master01 conf]# kubectl logs  -n openpitrix-system openpitrix-hyperpitrix-deployment-b968486ff-6htk7 -c openpitrix-cluster-db-ctrl 
DEBUG: Loading config file: /flyway/conf/flyway.conf
DEBUG: Unable to load config file: /root/flyway.conf
DEBUG: Unable to load config file: /flyway/flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> /flyway/jars
DEBUG: flyway.locations -> filesystem:/flyway/sql/cluster
DEBUG: flyway.password -> ********
DEBUG: flyway.url -> jdbc:mysql://mysql.kubesphere-system.svc/cluster
DEBUG: flyway.user -> root
DEBUG: flyway.validateOnMigrate -> false
DEBUG: Adding location to classpath: /flyway/drivers/derbyshared-10.15.1.3.jar
DEBUG: Adding location to classpath: /flyway/drivers/sqlite-jdbc-3.23.1.jar
DEBUG: Adding location to classpath: /flyway/drivers/h2-1.4.199.jar
DEBUG: Adding location to classpath: /flyway/drivers/derbyclient-10.15.1.3.jar
DEBUG: Adding location to classpath: /flyway/drivers/mariadb-java-client-2.4.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/jaybird-jdk18-3.0.6.jar
DEBUG: Adding location to classpath: /flyway/drivers/mssql-jdbc-7.2.0.jre8.jar
DEBUG: Adding location to classpath: /flyway/drivers/mysql-connector-java-8.0.17.jar
DEBUG: Adding location to classpath: /flyway/drivers/derby-10.15.1.3.jar
DEBUG: Adding location to classpath: /flyway/drivers/jna-platform-4.5.2.jar
DEBUG: Adding location to classpath: /flyway/drivers/jna-4.5.2.jar
DEBUG: Adding location to classpath: /flyway/drivers/hsqldb-2.5.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/derbytools-10.15.1.3.jar
DEBUG: Adding location to classpath: /flyway/drivers/postgresql-42.2.8.jre6.jar
DEBUG: Adding location to classpath: /flyway/drivers/jtds-1.3.1.jar
Flyway Community Edition 6.0.6 by Redgate
DEBUG: Scanning for filesystem resources at '/flyway/sql/cluster'
DEBUG: Scanning for resources in path: /flyway/sql/cluster (/flyway/sql/cluster)
DEBUG: Found filesystem resource: /flyway/sql/cluster/V0_10__resource_owner_path.sql
DEBUG: Found filesystem resource: /flyway/sql/cluster/V0_11__cluster_debug.sql
DEBUG: Found filesystem resource: /flyway/sql/cluster/V0_12__cluster_additional_info_to_text.sql
DEBUG: Found filesystem resource: /flyway/sql/cluster/V0_13__increase_role_length.sql
DEBUG: Found filesystem resource: /flyway/sql/cluster/V0_1__init.sql
DEBUG: Found filesystem resource: /flyway/sql/cluster/V0_2__cluster_index.sql
DEBUG: Found filesystem resource: /flyway/sql/cluster/V0_3__cluster_zone.sql
DEBUG: Found filesystem resource: /flyway/sql/cluster/V0_4__cluster_upgrade_time.sql
DEBUG: Found filesystem resource: /flyway/sql/cluster/V0_5__clusternode_eip.sql
DEBUG: Found filesystem resource: /flyway/sql/cluster/V0_6__key_pair.sql
DEBUG: Found filesystem resource: /flyway/sql/cluster/V0_7__cluster_role_and_node.sql
DEBUG: Found filesystem resource: /flyway/sql/cluster/V0_8__cluster_additional_info.sql
DEBUG: Found filesystem resource: /flyway/sql/cluster/V0_9__cluster_env.sql
Database: jdbc:mysql://mysql.kubesphere-system.svc/cluster (MySQL 8.0)
DEBUG: Driver  : MySQL Connector/J mysql-connector-java-8.0.17 (Revision: 16a712ddb3f826a1933ab42b0039f7fb9eebc6ec)
DEBUG: DDL Transactions Supported: false
DEBUG: Schema: cluster
DEBUG: Scanning for SQL callbacks ...
DEBUG: Filtering out resource: /flyway/sql/cluster/V0_10__resource_owner_path.sql (filename: V0_10__resource_owner_path.sql)
DEBUG: Filtering out resource: /flyway/sql/cluster/V0_11__cluster_debug.sql (filename: V0_11__cluster_debug.sql)
DEBUG: Filtering out resource: /flyway/sql/cluster/V0_12__cluster_additional_info_to_text.sql (filename: V0_12__cluster_additional_info_to_text.sql)
DEBUG: Filtering out resource: /flyway/sql/cluster/V0_13__increase_role_length.sql (filename: V0_13__increase_role_length.sql)
DEBUG: Filtering out resource: /flyway/sql/cluster/V0_1__init.sql (filename: V0_1__init.sql)
DEBUG: Filtering out resource: /flyway/sql/cluster/V0_2__cluster_index.sql (filename: V0_2__cluster_index.sql)
DEBUG: Filtering out resource: /flyway/sql/cluster/V0_3__cluster_zone.sql (filename: V0_3__cluster_zone.sql)
DEBUG: Filtering out resource: /flyway/sql/cluster/V0_4__cluster_upgrade_time.sql (filename: V0_4__cluster_upgrade_time.sql)
DEBUG: Filtering out resource: /flyway/sql/cluster/V0_5__clusternode_eip.sql (filename: V0_5__clusternode_eip.sql)
DEBUG: Filtering out resource: /flyway/sql/cluster/V0_6__key_pair.sql (filename: V0_6__key_pair.sql)
DEBUG: Filtering out resource: /flyway/sql/cluster/V0_7__cluster_role_and_node.sql (filename: V0_7__cluster_role_and_node.sql)
DEBUG: Filtering out resource: /flyway/sql/cluster/V0_8__cluster_additional_info.sql (filename: V0_8__cluster_additional_info.sql)
DEBUG: Filtering out resource: /flyway/sql/cluster/V0_9__cluster_env.sql (filename: V0_9__cluster_env.sql)
Current version of schema `cluster`: 0.10
DEBUG: Memory usage: 35 of 487M
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: Schema `cluster` contains a failed migration to version 0.10 !
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:227)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:162)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:159)
	at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60)
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:161)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:159)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:137)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:189)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:149)
	at org.flywaydb.core.Flyway.execute(Flyway.java:511)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:149)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:176)
	at org.flywaydb.commandline.Main.main(Main.java:123)

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: 2.1.1
Kubernetes: 1.16.7

**Environment**
How many nodes and their hardware configuration:

CentOS 7.6  / 3 masters:  8cpu/16g; 12 nodes: 8cpu/32g
kernel:4.19.12-1.el7.elrepo.x86_64

**Comment by zheng1** [comment]
Maybe need repair https://flywaydb.org/documentation/command/repair

**Comment by rayzhou2017** [comment]
should be fixed in 3.0.0
