### ISSUE TITLE
Whether the binary kubernetes cluster deployed by itself is supported

### ISSUE THREAD

**Issue by Ruilkyu** [kubesphere/kubesphere#2088]

**Comment by FeynmanZhou** [comment]
Yes, you can refer to the installation guide.

**Comment by rayzhou2017** [comment]
https://kubesphere.io/docs/installation/prerequisites/

**Comment by Ruilkyu** [comment]
If you want to manage a deployed kubernetes cluster, can you only deploy it under the kubernetes cluster through yaml? whether can you deploy it on a physical machine, and then connect to the existing kubernetes cluster.

**Comment by FeynmanZhou** [comment]
@Ruilkyu I this [guide](https://kubesphere.io/docs/installation/install-on-k8s/) can meet your demands.

**Comment by rayzhou2017** [comment]
The second question seems a requirement for multi-cluster management which will be offered in the upcoming v3.0.0.

**Comment by Ruilkyu** [comment]
When will V3.0 be released.
