### ISSUE TITLE
Failed to start tiller when install ks

### ISSUE THREAD

**Issue by Andriydang** [kubesphere/kubesphere#2092]
**What's your question**
Failed to start tiller when feature-gate "BoundServiceAccountTokenVolume" is enabled on apiserver.
Because tiller process is not excuted under uid 0 and does not have access to serviceaccount file.
Additional security context configs should be added to installation scripts,such as runAsUser and etc.

**Environment: OS & Hardware Information**

> CentOS 7.6, 2 C / 8 G.

**Error logs or message (Attach logs or screenshot)**
kubectl logs -f -n kube-system tiller-deploy-db759df74-jwdt5
[main] 2020/05/19 09:13:02 Cannot initialize Kubernetes connection: open /var/run/secrets/kubernetes.io/serviceaccount/token: permission denied

**Installer Version**

> v2.1.1

**Comment by calvinyv** [comment]
@Andriydang from the description, it looks like the root cause is from tiller, right? which can't start because of enabling BoundServiceAccountTokenVolume, correct me if I miss sth.

**Comment by Andriydang** [comment]
Thanks! I think it has something to do with the Kubernetes version，“BoundServiceAccountTokenVolume” is enabled Kubernetes 1.17 or later will not cause this problem.

**Comment by calvinyv** [comment]
Yes, we think this issue should be reported to helm community for further investigation. Anyways, really appreciate letting us know this limitation.
