### ISSUE TITLE
Dose 2.1.1 support 1.18.+?  

### ISSUE THREAD

**Issue by Paul0523** [kubesphere/kubesphere#2101]
**What's your question**
Dose 2.1.1 support 1.18.+?

**Comment by rayzhou2017** [comment]
No, the upcoming v3.0.0 will support 1.18.x

**Comment by Paul0523** [comment]
@rayzhou2017 expect publish time is ?

**Comment by rayzhou2017** [comment]
tentative date is by the end of June.

**Comment by Paul0523** [comment]
@rayzhou2017 ok, thank you
