### ISSUE TITLE
Through yaml deployment,Is there another set of kubernetes in kubernetes?

### ISSUE THREAD

**Issue by Ruilkyu** [kubesphere/kubesphere#2102]

**Comment by FeynmanZhou** [comment]
Not clear for another set of Kubernetes in Kubernetes, could you give us an explanation?

**Comment by Ruilkyu** [comment]
When the physical machine is deployed, a set of k8s is deployed, so whether the existing k8s cluster will also start a set of k8s through yaml deployment。
