### ISSUE TITLE
The error appears to be in '/root/kubesphere-all-v2.1.1/k8s/roles/kubernetes/master/tasks/kubeadm-setup.yml': line 133, column 3, but may be elsewhere in the file depending on the exact syntax problem.

### ISSUE THREAD

**Issue by 1007chenbaojun** [kubesphere/kubesphere#2131]
when i use multi-one install in Tencent Cloud.i find
"""
TASK [kubernetes/master : set kubeadm certificate key] *************************************************************
Wednesday 27 May 2020  21:44:56 +0800 (0:00:39.656)       0:08:42.727 ********* 
fatal: [master1]: FAILED! => {}

MSG:

The conditional check 'item | trim | match('.*--certificate-key .*')' failed. The error was: template error while templating string: no filter named 'match'. String: {% if item | trim | match('.*--certificate-key .*') %} True {% else %} False {% endif %}

The error appears to be in '/root/kubesphere-all-v2.1.1/k8s/roles/kubernetes/master/tasks/kubeadm-setup.yml': line 133, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: set kubeadm certificate key
  ^ here

fatal: [master2]: FAILED! => {}

MSG:

The conditional check 'item | trim | match('.*--certificate-key .*')' failed. The error was: template error while templating string: no filter named 'match'. String: {% if item | trim | match('.*--certificate-key .*') %} True {% else %} False {% endif %}

The error appears to be in '/root/kubesphere-all-v2.1.1/k8s/roles/kubernetes/master/tasks/kubeadm-setup.yml': line 133, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: set kubeadm certificate key
  ^ here

fatal: [master3]: FAILED! => {}

MSG:

The conditional check 'item | trim | match('.*--certificate-key .*')' failed. The error was: template error while templating string: no filter named 'match'. String: {% if item | trim | match('.*--certificate-key .*') %} True {% else %} False {% endif %}

The error appears to be in '/root/kubesphere-all-v2.1.1/k8s/roles/kubernetes/master/tasks/kubeadm-setup.yml': line 133, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: set kubeadm certificate key
  ^ here
"""
this problem

**Comment by pixiake** [comment]
which version  of ansible and  jinja2 ？

**Comment by 1007chenbaojun** [comment]
> 哪个版本的ansible和jinja2？
> 
> ```
> ansible==2.7.12
> jinja2==2.10.1
> netaddr==0.7.19
> pbr==5.2.0
> hvac==0.8.2
> jmespath==0.9.4
> ruamel.yaml==0.15.96
> ```

**Comment by 1007chenbaojun** [comment]
> > 哪个版本的ansible和jinja2？
> > ```
> > ansible==2.7.12
> > jinja2==2.10.1
> > netaddr==0.7.19
> > pbr==5.2.0
> > hvac==0.8.2
> > jmespath==0.9.4
> > ruamel.yaml==0.15.96
> > ```

ansible ==2.9.9 jinjia2==2.10.1

**Comment by 1007chenbaojun** [comment]
change ansible==2.7.12 it is used
