### ISSUE TITLE
请问容器组上限是不是锁死110个，可以设置吗？我是all-in-one部署

### ISSUE THREAD

**Issue by chankamlam** [kubesphere/kubesphere#2142]
请问容器组上限是不是锁死110个，可以设置吗？我是all-in-one部署

**Comment by FeynmanZhou** [comment]
English only.

It can be changed in K8s. For Chinese reference, go to [China Forum](https://kubesphere.com.cn/forum/d/721-master/4).

**Comment by chankamlam** [comment]
> English only.
> 
> It can be changed in K8s. For Chinese reference, go to [China Forum](https://kubesphere.com.cn/forum/d/721-master/4).

get it ,had been changed by edit config ,thx
