### ISSUE TITLE
Support Ubuntu 20.04 installation

### ISSUE THREAD

**Issue by tingkai-zhang** [kubesphere/kubesphere#2150]
**What's your question**
Hi thanks for making this awesome app.

Im installing the latest kbsphere on a Ubuntu 20.04 machine and encountered the following error:

```
TASK [container-engine/docker : ensure docker packages are installed] ***************************************************************************************************************
Wednesday 03 June 2020  04:05:40 +0200 (0:00:00.030)       0:00:24.077 ********
FAILED - RETRYING: ensure docker packages are installed (4 retries left).
FAILED - RETRYING: ensure docker packages are installed (3 retries left).
FAILED - RETRYING: ensure docker packages are installed (2 retries left).
FAILED - RETRYING: ensure docker packages are installed (1 retries left).
failed: [ks-allinone] (item={u'force': True, u'name': u'docker-ce-cli=5:18.09.7~3-0~ubuntu-focal'}) => {
    "attempts": 4,
    "cache_update_time": 1591149853,
    "cache_updated": false,
    "changed": false,
    "item": {
        "force": true,
        "name": "docker-ce-cli=5:18.09.7~3-0~ubuntu-focal"
    },
    "rc": 100
}

STDOUT:

Reading package lists...
Building dependency tree...
Reading state information...



STDERR:

W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Version '5:18.09.7~3-0~ubuntu-focal' for 'docker-ce-cli' was not found



MSG:

'/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"  --force-yes   install 'docker-ce-cli=5:18.09.7~3-0~ubuntu-focal'' failed: W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Version '5:18.09.7~3-0~ubuntu-focal' for 'docker-ce-cli' was not found


FAILED - RETRYING: ensure docker packages are installed (4 retries left).
FAILED - RETRYING: ensure docker packages are installed (3 retries left).
FAILED - RETRYING: ensure docker packages are installed (2 retries left).
FAILED - RETRYING: ensure docker packages are installed (1 retries left).
failed: [ks-allinone] (item={u'force': True, u'name': u'docker-ce=5:18.09.7~3-0~ubuntu-focal'}) => {
    "attempts": 4,
    "cache_update_time": 1591149853,
    "cache_updated": false,
    "changed": false,
    "item": {
        "force": true,
        "name": "docker-ce=5:18.09.7~3-0~ubuntu-focal"
    },
    "rc": 100
}

STDOUT:

Reading package lists...
Building dependency tree...
Reading state information...



STDERR:

W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Version '5:18.09.7~3-0~ubuntu-focal' for 'docker-ce' was not found



MSG:

'/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"  --force-yes   install 'docker-ce=5:18.09.7~3-0~ubuntu-focal'' failed: W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Version '5:18.09.7~3-0~ubuntu-focal' for 'docker-ce' was not found

```

**Environment: OS & Hardware Information**

Ubuntu 20.04

It was a fresh install attempt. The machine is newly provisioned with no other software installed.

**Error logs or message (Attach logs or screenshot)**
The summary shows below:
![image](https://user-images.githubusercontent.com/20318562/83588346-2e71ca80-a51f-11ea-82da-f9683f84c945.png)

![image](https://user-images.githubusercontent.com/20318562/83588283-084c2a80-a51f-11ea-8899-485a5130cdf5.png)

According to the log, it's also recommended to replace the `--force-yes` flag with other another option.

**Installer Version**

v2.1.1

**Comment by Forest-L** [comment]
You can refer to https://github.com/kubesphere/kubekey  to install k8s,  and refer to https://github.com/kubesphere/ks-installer to install KubeSphere.

**Comment by tingkai-zhang** [comment]
Hi, thanks for the quick response.

Could you elaborate more on the installation issue on Ubuntu 20.04? 

If the reason is valid, I would like to create a PR for the kbshere docs for clarification.

**Comment by FeynmanZhou** [comment]
Ubuntu 20.04 is not supported in Linux installer, the supported OS are listed [here](https://kubesphere.io/docs/installation/all-in-one/#hardware-recommendation). So, we suggest you install K8s by yourself, then [install KubeSphere on existing K8s cluster](https://kubesphere.io/docs/installation/install-on-k8s/).

**Comment by tingkai-zhang** [comment]
OK, I will just leave this issue open to you cuz I think the support for Ubuntu 20.04 may be of low priority but should be on the road map. 

I would also like to update installation instructions for kbsphere docs just for people like me who would like to try installing kbsphere on Ubuntu 20.04 machines.
