### ISSUE TITLE
show number of instances for a crd

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2158]
I think it would be better to show how many custom resources for each crd in the list.
<img width="965" alt="Screen Shot 2020-06-04 at 5 10 33 PM" src="https://user-images.githubusercontent.com/28859385/83738172-870fa780-a686-11ea-8d62-6113ac6c5487.png">

**Comment by zryfish** [comment]
That's not cost-effective, count instances of every crd is very time consuming, by the way you can check the total items inside one CRD template.
