### ISSUE TITLE
 kubesphere-monitoring-system/node-exporter  error

### ISSUE THREAD

**Issue by shixud** [kubesphere/kubesphere#2162]
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/kubesphere-minimal.yaml
node-exporter tips:
0/4 nodes are available: 1 node(s) didn't match node selector, 3 node(s) didn't have free ports for the requested pod ports.

**Comment by huanggze** [comment]
Plz check if 9100 is occupied, which is used by node-export by default. Or you may also modify node exporter's  default port to any number else.
