### ISSUE TITLE
No access list of resources for platform regular role?

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2170]
The list is empty
![Screen Shot 2020-06-08 at 10 09 38 AM](https://user-images.githubusercontent.com/28859385/83986701-48bd0580-a970-11ea-9b33-0ab3b3c73101.png)

**Comment by wansir** [comment]
By default, platform regular does not have any cluster resource authorization. We define the default roles at here, https://github.com/kubesphere/ks-installer/blob/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml.

**Comment by rayzhou2017** [comment]
If this role has no access to any resource, why built in it here? Is it like anonymous role? If so, why call it platform-regular?

**Comment by wansir** [comment]
Anonymous role is bind to unauthenticated user group. Like cluster-regular, the regular user has no rights in global scope, but they can be added to workspace or namespace.

**Comment by rayzhou2017** [comment]
If it is that case, what is the working flow for a new user to start work? The admin will only create user account for him. Then who creates ws for the user?

**Comment by wansir** [comment]
We will built-in more roles, such as user manager and workspace manager. A global role that can create workspace but cannot manage other workspaces is also needed.

**Comment by rayzhou2017** [comment]
verified
