### ISSUE TITLE
Failed to roll back deployments in v2.1.1 due to the api version

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#2171]
Users were failed to roll back deployments in v2.1.1 since the K8s api version changes.

This is a known bug, please refer to [forum](https://kubesphere.com.cn/forum/d/1048-v2-1-1).

**Comment by rayzhou2017** [comment]
@wanjunlei can you help check if it still exists in 3.0.0?

**Comment by wanjunlei** [comment]
@leoendless Dose the console image has updated? This bug is also exists in the latest version.

**Comment by wanjunlei** [comment]
verified

**Comment by zryfish** [comment]
> verified
Is this issue fixed? Can we close it now?
/cc @wanjunlei

**Comment by wanjunlei** [comment]
yes, it has fixed.
