### ISSUE TITLE
kubectl does not work

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2172]
When I create a platform custom role with view/edit platform access, and log in with a user granted with the role, click the kubectl shows error. I think this may be similar as the issue https://github.com/kubesphere/console/issues/362#issuecomment-640330124
<img width="1217" alt="Screen Shot 2020-06-08 at 10 44 44 AM" src="https://user-images.githubusercontent.com/28859385/83988319-79536e00-a975-11ea-94d2-6f6b9fbf536f.png">

**Comment by rayzhou2017** [comment]
The same user has no access to the following pages.
<img width="1214" alt="Screen Shot 2020-06-08 at 10 53 22 AM" src="https://user-images.githubusercontent.com/28859385/83988615-56758980-a976-11ea-8be4-769e9fa253df.png">

**Comment by rayzhou2017** [comment]
I found lots of the same issue. It seems we should provide more grained access control. Right now only for view/edit access control for platform, no control for the items under platform.

**Comment by wansir** [comment]
Kubectl can only be used by cluster-admin (platform-admin is cluster-admin of all clusters). It is unnecessary to provide kubectl toolbox authorization unless we provide the kubectl plug-in let regular user use kubectl well. Custom roles does not have full platform access(unable to customize a platform-admin), we can add more description of authorization items. Generally, edit, delete and create permissions are not separated. We only need to distinguish view and manage permissions.

**Comment by wansir** [comment]
https://github.com/kubesphere/ks-installer/pull/752

**Comment by rayzhou2017** [comment]
> Kubectl can only be used by cluster-admin (platform-admin is cluster-admin of all clusters). It is unnecessary to provide kubectl toolbox authorization unless we provide the kubectl plug-in let regular user use kubectl well. Custom roles does not have full platform access(unable to customize a platform-admin), we can add more description of authorization items. Generally, edit, delete and create permissions are not separated. We only need to distinguish view and manage permissions.

OK，I see the kubectl does not appear now.
