### ISSUE TITLE
Provide the description of the network policy

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2173]
The requisite of network policy is empty here.
<img width="1020" alt="Screen Shot 2020-06-08 at 11 02 20 AM" src="https://user-images.githubusercontent.com/28859385/83989086-d9e3aa80-a977-11ea-948c-61901ea753c6.png">

**Comment by zheng1** [comment]
Make sure that the CNI network plugin used by the cluster support [NetworkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/). There are a number of CNI network plugins that support NetworkPolicy, including: Calico, Cilium, Kube-router, Romana, Weave Net.

**Comment by Sherlock113** [comment]
Noted. I will add that.

**Comment by rayzhou2017** [comment]
verified
