### ISSUE TITLE
Issues on Volumes

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2174]
* [x] when I clicked into the redis volume, it throws error. @min-zh 
* [x] When I click the back link, it goes back the project instead of the storage management.
<img width="1224" alt="Screen Shot 2020-06-08 at 12 48 31 PM" src="https://user-images.githubusercontent.com/28859385/83993662-a2c8c580-a986-11ea-908e-fda12f17cd86.png">

**Comment by min-zh** [comment]
Not every storageclass has corresponding storageclasscapability. Storage class of  CSI deployed on KS has storageclasscapability, for exmaple: qingcloud-csi, qingstor-csi, ceph-csi, aws-ebs-csi. Storage vendors like openebs/localpv, nfs-client, rbd(in tree), glusterfs(in tree) don't have the storageclasscapability. I think storageclass without correspondign storaegeclasscapability could be dealed as they don't have the senior featrues like cloning, expansion, snapshot.

**Comment by rayzhou2017** [comment]
> Not every storageclass has corresponding storageclasscapability. Storage class of CSI deployed on KS has storageclasscapability, for exmaple: qingcloud-csi, qingstor-csi, ceph-csi, aws-ebs-csi. Storage vendors like openebs/localpv, nfs-client, rbd(in tree), glusterfs(in tree) don't have the storageclasscapability. I think storageclass without correspondign storaegeclasscapability could be dealed as they don't have the senior featrues like cloning, expansion, snapshot.

The capability isn't a unified interface for all SC? Who is responsible to write the capability? by each SC provider?

**Comment by min-zh** [comment]
> > Not every storageclass has corresponding storageclasscapability. Storage class of CSI deployed on KS has storageclasscapability, for exmaple: qingcloud-csi, qingstor-csi, ceph-csi, aws-ebs-csi. Storage vendors like openebs/localpv, nfs-client, rbd(in tree), glusterfs(in tree) don't have the storageclasscapability. I think storageclass without correspondign storaegeclasscapability could be dealed as they don't have the senior featrues like cloning, expansion, snapshot.
> 
> The capability isn't a unified interface for all SC? Who is responsible to write the capability? by each SC provider?

The capability is an unified interface for all SC of **CSI**, as we get the capability from the standard interface. The other SC, which are non-CSI, they don't have the standard interface, so we can't get their capabilities. Most of the non-CSI storage class just has the basic feature, so we can hanler them without senior features.

**Comment by min-zh** [comment]
@justahole please handle this on frontend

**Comment by rayzhou2017** [comment]
> > > Not every storageclass has corresponding storageclasscapability. Storage class of CSI deployed on KS has storageclasscapability, for exmaple: qingcloud-csi, qingstor-csi, ceph-csi, aws-ebs-csi. Storage vendors like openebs/localpv, nfs-client, rbd(in tree), glusterfs(in tree) don't have the storageclasscapability. I think storageclass without correspondign storaegeclasscapability could be dealed as they don't have the senior featrues like cloning, expansion, snapshot.
> > 
> > 
> > The capability isn't a unified interface for all SC? Who is responsible to write the capability? by each SC provider?
> 
> The capability is an unified interface for all SC of **CSI**, as we get the capability from the standard interface. The other SC, which are non-CSI, they don't have the standard interface, so we can't get their capabilities. Most of the non-CSI storage class just has the basic feature, so we can hanler them without senior features.

I see. So it is bug here then. We should fix it.

**Comment by rayzhou2017** [comment]
verified
