### ISSUE TITLE
project member page throws error

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2177]
Can't open the page using the default user admin. The project is created by admin. The project role page can't open either.
<img width="1230" alt="Screen Shot 2020-06-08 at 2 49 56 PM" src="https://user-images.githubusercontent.com/28859385/84000720-c2b4b500-a997-11ea-8a82-81c39bbffa51.png">

**Comment by rayzhou2017** [comment]
Now I can open the page without error, but it shows no users. I think `admin` should be in the list since I created it using admin. Also the ws member is empty too. /cc @wansir @leoendless

**Comment by wansir** [comment]
https://github.com/kubesphere/kubesphere/pull/2164

**Comment by rayzhou2017** [comment]
verified
