### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2181]
I created a custom role with cluster edit permission, then created a user with the role. Log in using the user and try to create a workspace, throws the following error. It seems it requires user view permission. It is hard for users to understand.

Should it be like this logic? If the role has no access to view users, then only show itself in the dropdown list. Otherwise ,show all users in the list.

<img width="1208" alt="Screen Shot 2020-06-09 at 8 43 29 PM" src="https://user-images.githubusercontent.com/28859385/84148900-3935dd80-aa92-11ea-91b6-d679354851be.png">
<img width="1129" alt="Screen Shot 2020-06-09 at 8 41 36 PM" src="https://user-images.githubusercontent.com/28859385/84148988-579bd900-aa92-11ea-8b1f-cd1818510401.png">

**Comment by wansir** [comment]
The user only has the cluster manage permission, cannot open the access control page and create a workspace, did you refresh the page.

**Comment by rayzhou2017** [comment]
but it does show `create workspace` for the user.

**Comment by rayzhou2017** [comment]
check the logic I said above

**Comment by rayzhou2017** [comment]
verified
