### ISSUE TITLE
[Proposal] Using a simple and open-source Jenkins distribution solution

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/kubesphere#2182]
[Jenkins formula](https://github.com/jenkins-zh/jenkins-formulas) is a open-source project which allow users to create their own Jenkins distribution. What do you need to do is just create a YAML file.
There some beneficial you can enjoy:
- Do not need update-center
- Easily to package this distribution from a private environment
- More collaborations

**Comment by FeynmanZhou** [comment]
@shaowenchen Please help to evaluate and follow up on this proposal.

**Comment by shaowenchen** [comment]
It sounds great. There is a brief introduction about how to deploy Jenkins in KubeSphere DevOps.

1. using helm to install Jenkins , https://github.com/kubesphere/ks-installer/tree/master/roles/ks-devops/jenkins/files/jenkins/jenkins
2. using UC to provide Jenkins Plugins

There are some configure files used in deploying DevOps.

jenkins-casc-config -  https://github.com/kubesphere/ks-installer/blob/master/roles/ks-devops/jenkins/templates/jenkins-casc-config.yml.j2
InstalledPlugins - https://github.com/kubesphere/ks-installer/blob/master/roles/ks-devops/jenkins/templates/custom-values-jenkins.yaml.j2#L57

Is this information enough for this feature?

**Comment by LinuxSuRen** [comment]
It sounds pretty good. It can help me going deep it.

**Comment by FeynmanZhou** [comment]
@LinuxSuRen Feel free to join us in [Slack](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE) and find the channel #SIG-DevOps. If you need any resources or help, let us know.

**Comment by LinuxSuRen** [comment]
If I understand correctly, I need to create a formula which contains [these plugins](https://github.com/kubesphere/ks-installer/blob/master/roles/ks-devops/jenkins/templates/custom-values-jenkins.yaml.j2#L57). Then change the Jenkins docker image to a new one. Right?

**Comment by shaowenchen** [comment]
Yes , this image will be used in helm chart to deploy jenkins.  Others，it is necessary to provide a convenient method to maintain this image.

**Comment by LinuxSuRen** [comment]
Hi @shaowenchen , I met some problems. I was wondering if you can give me a hand.

There're a few plugins I cannot found them:
```
handlebars:1.1.1
build-monitor-plugin:1.12+build.201809061734
configuration-as-code-support:1.18
kubesphere-extension:0.0.1
kubesphere-token-auth:0.2.0
momentjs:1.1.1
pipeline-stage-tags-metadata:1.3.9
```

Below are not a maven project.
```
jquery-detached:1.2.1
```

**Comment by shaowenchen** [comment]
Most of plugins are downloaded from 
`"https://mirrors.tuna.tsinghua.edu.cn/jenkins/plugins/$name/$version/$name.hpi"`

But, kubesphere-extension:0.0.1 \kubesphere-token-auth:0.2.0 are developed by Kubesphere. All plugins are saved in the docker image named of kubespheredev/jenkins-uc:3.0.0

How do you get the plugins? Offline , or online?

**Comment by LinuxSuRen** [comment]
In the project of 'Jenkins formulas', it downloads plugins from a maven repo. So all those plugins need to be access from a public maven repo(e.g. a public Nexus sever).

**Comment by shaowenchen** [comment]
Can you give me a suggestion? Or , we just need to deploy/find a public maven repo and upload plugins about kubesphere?

**Comment by LinuxSuRen** [comment]
If all kubesphere plugins already hosted in [the official org](https://github.com/jenkinsci/). I believe that you just need to deploy it to the official repo. Which means just simply execute the following command:
`mvn release:prepare release:perform` or `jcli plugin release`

**Comment by shaowenchen** [comment]
Only kubesphere-token-auth-plugin is not in it. Do I need to transfer https://github.com/shaowenchen/kubesphere-token-auth-plugin to https://github.com/jenkinsci ?
Please verify that other plugins can be downloaded properly.

**Comment by LinuxSuRen** [comment]
Yes, it's better if we publish it to the official. I already pushed the Jenkins image to my personal account below:
`surenpi/jenkins-kubesphere:2.204.5`

Please take a look at it. Please tell me if there's any issues about this distribution.

**Comment by shaowenchen** [comment]
I'm sorry not to reply to you immediately. Recently,  KubeSphere 3.0 will be released soon and I'm busy with it. There is a small adjustment for the Jenkins in 3.0, and I will back after about two weeks.

**Comment by LinuxSuRen** [comment]
Got you.

**Comment by LinuxSuRen** [comment]
A new project for this was created. If anyone wants to follow the details, please see [here](https://github.com/kubesphere/ks-jenkins). You're welcome to provide any kind of contribution.

**Comment by LinuxSuRen** [comment]
Project [ks-jenkins](https://github.com/kubesphere/ks-jenkins) is ready now. I'm going to close this PR.
