### ISSUE TITLE
为什么必须配置内网ip

### ISSUE THREAD

**Issue by romantictravel01** [kubesphere/kubesphere#2185]
多节点安装,必须设置个内网ip感觉莫名其妙,有ip连通就可以了,为什么必须搞个内网ip,而且必填
为什么不是设置了内网ip就访问内网ip,如果不设置就访问host对应的域名或者ip

**Comment by FeynmanZhou** [comment]
English only.

In some environments, SSH addresses are not the same as machines' internal IP addresses. For Chinese questions, please raise it on [China forum](https://kubesphere.com.cn/forum/).

**Comment by romantictravel01** [comment]
所以设计必填的人逗B

**Comment by rayzhou2017** [comment]
Please go to the forum if you prefer Chinese. BTW, you can contribute if you think you have better idea.
