### ISSUE TITLE
Assignment of ws admin does not work

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2186]
When creating a ws, I assign a created platform-regular user as its admin. The user is not in the ws. Then I try to invite the user, it shows please choose a role but no one available over there.
<img width="960" alt="Screen Shot 2020-06-10 at 2 49 18 PM" src="https://user-images.githubusercontent.com/28859385/84236161-cb3cf500-ab29-11ea-8e4d-d6155aa7d657.png">
<img width="715" alt="Screen Shot 2020-06-10 at 2 49 40 PM" src="https://user-images.githubusercontent.com/28859385/84236190-d728b700-ab29-11ea-89b2-2e49dccc0e97.png">

**Comment by rayzhou2017** [comment]
Obviously, missing ws built-in roles
<img width="1045" alt="Screen Shot 2020-06-10 at 2 52 20 PM" src="https://user-images.githubusercontent.com/28859385/84236312-0808ec00-ab2a-11ea-9b6c-2e4abc2c6a38.png">

**Comment by wansir** [comment]
https://github.com/kubesphere/kubesphere/pull/2164

**Comment by rayzhou2017** [comment]
verified
