### ISSUE TITLE
Apiserver monitoring indicator is empty

### ISSUE THREAD

**Issue by ktpktr0** [kubesphere/kubesphere#2189]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**What's your question**
Apiserver monitoring indicator is empty

**Environment: OS & Hardware Information**

> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).

VMware CentOS 7.7，k8s 1.17.3

**Error logs or message (Attach logs or screenshot)**
![image](https://user-images.githubusercontent.com/41657218/84249043-d5b4ba00-ab3c-11ea-8b61-22ba18798b82.png)

prometheus error
![image](https://user-images.githubusercontent.com/41657218/84249130-f41ab580-ab3c-11ea-9668-e4d74a01251d.png)

**Installer Version**
v2.1.1

I want to know which SA and clusterrole are used to get apiserver
Because the error notification uses anonymous users

I checked and found that RBAC permissions were correct

![image](https://user-images.githubusercontent.com/41657218/84353633-1cb0b700-abf2-11ea-8c91-4c46fd5738d2.png)
![image](https://user-images.githubusercontent.com/41657218/84353588-09055080-abf2-11ea-97e4-8403c2969855.png)
![image](https://user-images.githubusercontent.com/41657218/84353688-2df9c380-abf2-11ea-843a-8dc0c63ee7c1.png)
![image](https://user-images.githubusercontent.com/41657218/84353754-4cf85580-abf2-11ea-877a-7f88f6069a62.png)

**Comment by huanggze** [comment]
k8s 1.17.3 introduced break changes in kube-apiserver metric naming. We cannot do much now in ks 2.1.1. We will fix this in ks 3.0

**Comment by rayzhou2017** [comment]
verified
