### ISSUE TITLE
Can't open project

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2199]
<img width="1225" alt="Screen Shot 2020-06-13 at 2 30 04 PM" src="https://user-images.githubusercontent.com/28859385/84561867-7f38bd00-ad82-11ea-9197-0fd9a4fd1cac.png">

**Comment by wansir** [comment]
Due to the API change https://github.com/kubesphere/kubesphere/pull/2195

**Comment by rayzhou2017** [comment]
verified
