### ISSUE TITLE
建议将应用商店内应用被三方引用可将应用镜像细分至应用内部服务（或组件）镜像

### ISSUE THREAD

**Issue by zanglei80231314** [kubesphere/kubesphere#2200]
建议能遵照OAM模型更细粒度的实现应用全生命周期的管理至实现组件级的全生命周期管理，例如应用商店内已发布应用被三方引用可将应用镜像细分至应用内部服务（或组件）镜像。解决组件间依赖问题，包括不同应用内的组件之间的依赖和传输传递。
此建议如有不当或已实现请回复“建议删除”，谢谢

**Comment by FeynmanZhou** [comment]
English only.

Thank you for your suggestion. For Chinese proposal, please go to [China forum](https://kubesphere.com.cn/forum/t/Feedback).
