### ISSUE TITLE
容器环境变量配置优化

### ISSUE THREAD

**Issue by jayzch** [kubesphere/kubesphere#2201]
![image](https://user-images.githubusercontent.com/5292764/84625569-15e9b300-af16-11ea-935c-2cd3bd8e81dc.png)

是否可以在引用配置中心时，配置项的名称默认取配置中心的key

**Comment by FeynmanZhou** [comment]
English only.

Thanks for your suggestion, it's duplicated with this [one](https://kubesphere.com.cn/forum/d/1558), so we close it.
