### ISSUE TITLE
admin missing in project members

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2208]
![Screen Shot 2020-06-16 at 3 58 38 PM](https://user-images.githubusercontent.com/28859385/84747805-587cbf80-afea-11ea-85f7-aa3e1d854d0c.png)

**Comment by wansir** [comment]
Account `admin` is `platform-admin` (can manage all resources), not a member of any project by default.

**Comment by rayzhou2017** [comment]
verified
