### ISSUE TITLE
can't add ws admin user in the ws

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2209]
create a ws manager user `ws-manager` and a platform regular user `ray`, using `ws-manager` to create a ws and grant the admin to the user `ray`. Then log in using `ray`, can't see the ws. And check the ws members, `ray` is not there.
![Screen Shot 2020-06-16 at 4 11 54 PM](https://user-images.githubusercontent.com/28859385/84749371-7519f700-afec-11ea-8434-6d9f66f42e9f.png)

**Comment by wansir** [comment]
https://github.com/kubesphere/kubesphere/pull/2212

**Comment by rayzhou2017** [comment]
verified
