### ISSUE TITLE
navigation menu missing items

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2211]
`ray` is the admin of the project, but can't see the project navigation items such workload...
![Screen Shot 2020-06-16 at 4 17 58 PM](https://user-images.githubusercontent.com/28859385/84749838-17d27580-afed-11ea-956a-dc69398e27f6.png)

**Comment by rayzhou2017** [comment]
also the member menu is missing
![Screen Shot 2020-06-16 at 4 20 01 PM](https://user-images.githubusercontent.com/28859385/84749973-43edf680-afed-11ea-87fa-470170754fa1.png)

**Comment by wansir** [comment]
https://github.com/kubesphere/kubesphere/pull/2206

**Comment by rayzhou2017** [comment]
verified
