### ISSUE TITLE
cluster basic info

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2215]
* [ ] How does a user edit the name of the cluster? If this cluster is added to a multicluster, the name may be duplicate?
* [ ] The monitoring data seems used ones. Do we need to provide total values here?
<img width="1148" alt="Screen Shot 2020-06-16 at 8 29 46 PM" src="https://user-images.githubusercontent.com/28859385/84774438-6a715900-b010-11ea-8b47-c71202b9b26c.png">

**Comment by zryfish** [comment]
Cluster name is just placeholder here(we can use another name), for a consistent experience. We need an actual name when a cluster joining multicluster.

**Comment by rayzhou2017** [comment]
verified
