### ISSUE TITLE
creating ws，no cluster elected，actually selected all cluster

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2220]
steps：
1、creating ws，no cluster elected
![image](https://user-images.githubusercontent.com/36271543/84885350-7f5bf400-b0c5-11ea-9559-29ea50a5bd93.png)

2、Go to the cluster visibility page to see the ws created, which already exists in the visibility list
![image](https://user-images.githubusercontent.com/36271543/84885462-a7e3ee00-b0c5-11ea-8411-7b5c485da113.png)

/kind bug
/area console
/assign @leoendless
/Milestone 3.0.0

**Comment by leoendless** [comment]
Fixed
