### ISSUE TITLE
创建资源型项目，最后一步点击创建按钮没反应

### ISSUE THREAD

**Issue by Tufeiming** [kubesphere/kubesphere#2234]
chrome控制台信息
![image](https://user-images.githubusercontent.com/22171113/85188907-beb05d80-b2dc-11ea-825e-e83608137c14.png)
请问怎么解决？

**Comment by Tufeiming** [comment]
![image](https://user-images.githubusercontent.com/22171113/85188932-f0c1bf80-b2dc-11ea-9279-5f0be83ca791.png)

**Comment by Tufeiming** [comment]
Failed to load resource: the server responded with a status of 409 ()
dashboard:1 Uncaught (in promise) Objectmessage: undefinedreason: ""status: 409__proto__: Object

**Comment by FeynmanZhou** [comment]
English only.

For Chinese questions, please raise it on [China form](https://kubesphere.com.cn/forum).
