### ISSUE TITLE
pkg-download-center 镜像起不了， 安装失败

### ISSUE THREAD

**Issue by dearblen** [kubesphere/kubesphere#2235]
pkg-download-center
6c00ab5b141563b11d513b7b74f3a9406c386cc4e4c98cfd88848596751b19fc

docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"nginx:1.14-alpine\": executable file not found in $PATH": unknown.

**Comment by FeynmanZhou** [comment]
English only.

Which kind of installation are you using? online or offline? Please give more details about your system and installer information.

**For Chinese questions, please raise it on [China form](https://kubesphere.com.cn/forum).**
