### ISSUE TITLE
Failed to modify admin password in KS 3.0.0

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/kubesphere#2242]
**Describe the Bug**
Modify admin password on new installed KS 3.0.0, UI popup 'Bad Request' error and password is not modified.

![image](https://user-images.githubusercontent.com/38337958/85274675-d856ce00-b4b1-11ea-8483-a3228eb27918.png)

**Versions Used**
KubeSphere: v3.0.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: Ubuntu 18.04.3 / 1 masters:  4cpu/8g

**How To Reproduce**
1. Download kk
2. Run ./kk create config --with-kubesphere
3. Modify config yaml to fit cluster config
4. After installation success, login KS UI with admin and modify admin password

**Expected behavior**
No error occurs and password modified as requested.

**Comment by rayzhou2017** [comment]
same as  #2292

**Comment by loxiaopohaiol** [comment]
I don't see the default password of the kubesphere console to admin, what is the password of admin?

**Comment by rayzhou2017** [comment]
It is `P@88w0rd`. Also you can get it from the following command

```bash
kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l app=ks-install -o jsonpath='{.items[0].metadata.name}') -f
```

**Comment by loxiaopohaiol** [comment]
I tried to execute this command, but there is no admin information like version 2.0, but all my pods have started normally
