### ISSUE TITLE
Create a secret by choosing 'custom' type, but created as default type

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#2246]
**Describe the Bug**
Create a secret by choosing 'custom' type, but created as the default type

**Versions Used**
KubeSphere: 2.1.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**How To Reproduce**
1. Go to some project
2. Create a secret as 'custom' type
3. the type will be shown as blank type, click 'save' the secret will be saved as default type.
<img width="600" alt="Xnip2020-06-23_14-08-57" src="https://user-images.githubusercontent.com/28883416/85367117-38557f00-b55b-11ea-9bec-b29ddcede660.png">

<img width="508" alt="Xnip2020-06-23_14-09-14" src="https://user-images.githubusercontent.com/28883416/85367147-46a39b00-b55b-11ea-9424-5c4d50ddc7fa.png">

<img width="677" alt="Xnip2020-06-23_14-09-28" src="https://user-images.githubusercontent.com/28883416/85367159-4d321280-b55b-11ea-8ed7-c99a932db321.png">

**Comment by leoendless** [comment]
Please input the custom type value.

**Comment by calvinyv** [comment]
verified
