### ISSUE TITLE
change cluster visibility got error msg

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2247]
When I edit ws the access to cluster, got the error msg below. Set the cluster public also got the msg.
<img width="1146" alt="Screen Shot 2020-06-23 at 2 23 03 PM" src="https://user-images.githubusercontent.com/28859385/85368132-3ab8d880-b55d-11ea-9ff4-fade4e23ac4c.png">

**Comment by rayzhou2017** [comment]
Now the error msg is gone. However, I grant the cluster to the demo-ws, but it does not work.
<img width="1013" alt="Screen Shot 2020-06-23 at 5 14 10 PM" src="https://user-images.githubusercontent.com/28859385/85385498-f33e4680-b574-11ea-8875-970978ef75f8.png">

**Comment by leoendless** [comment]
@wansir

**Comment by rayzhou2017** [comment]
still have the problem

**Comment by rayzhou2017** [comment]
verified
