### ISSUE TITLE
Fed project without cluster available throws error 

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2248]
The ws has no cluster granted. Click the fed project tab, throws error as below. Also I suggest to add loud msg such as "No cluster for the ws..., please...." on the project page too.
<img width="1230" alt="Screen Shot 2020-06-23 at 5 01 05 PM" src="https://user-images.githubusercontent.com/28859385/85384154-7068bc00-b573-11ea-8b23-146e980eb742.png">

**Comment by leoendless** [comment]
this use should have the permission of list federatednamespaces in the workspace

**Comment by rayzhou2017** [comment]
verified
