### ISSUE TITLE
Creating ws throws error

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2259]
I have a multi-cluster env. When try to create a ws, it throws error and finally it creates a ws without any cluster granted to it.
![error](https://user-images.githubusercontent.com/28859385/85939957-13db1780-b94c-11ea-8969-b227f44e768b.png)

**Comment by leoendless** [comment]
it's a mistake of clusters API version. `kapis/tenant.kubesphere.io/v1alpha3/clusters` need to be changed to `kapis/tenant.kubesphere.io/v1alpha2/clusters`

**Comment by leoendless** [comment]
Fixed

**Comment by rayzhou2017** [comment]
verified
