### ISSUE TITLE
No creation button for fed project

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2261]
`ray` is the admin of the workspace `demo-ws`. He can create a regular project, but can't find the button to create a fed project.

![Screen Shot 2020-06-28 at 3 12 55 PM](https://user-images.githubusercontent.com/28859385/85941021-bf876600-b952-11ea-9edf-71189891b5f9.png)
![Screen Shot 2020-06-28 at 3 13 00 PM](https://user-images.githubusercontent.com/28859385/85941024-c4e4b080-b952-11ea-976f-0b2becb9fac6.png)

**Comment by leoendless** [comment]
@wansir  Could we provide a special rule to access the federated projects.

**Comment by rayzhou2017** [comment]
Now the problem becomes a self-provisioner can't see the fed project tab.

<img width="1177" alt="Screen Shot 2020-07-09 at 1 29 36 PM" src="https://user-images.githubusercontent.com/28859385/87000755-620fd680-c1e8-11ea-9723-f7587d350521.png">

**Comment by rayzhou2017** [comment]
verified
