### ISSUE TITLE
login error after add cluster

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#2269]
**Describe the Bug**
User will be logout after add cluster, and has a error "The session timed out or this account is logged in elsewhere, please log in again" when login.

**Versions Used**
KubeSphere: 3.0.0(2020-06-29)
Kubernetes: (If KubeSphere installer used, you can skip this)

**Comment by rayzhou2017** [comment]
Did you change the token of the member cluster by following the guide https://github.com/kubesphere/community/tree/master/sig-multicluster/how-to-setup-multicluster-on-kubesphere

**Comment by WaysonWei** [comment]
I had this issue before. Just clear the cache of the browser or login again under Guest mode with Chrome.
