### ISSUE TITLE
namespace is not show on the page projects of workspaces after created

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#2271]
**Describe the Bug**
When i create namespace  through ui, if i choose two same clusters, then the namespace  will be not show on the page projects of workspaces after created, but it will be show on the page projects of cluster.

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/53003665/85989152-b8c82400-ba22-11ea-902f-72245fb3b729.png)

![image](https://user-images.githubusercontent.com/53003665/85989230-d3020200-ba22-11ea-9d56-2bde7e2a5fb5.png)

![image](https://user-images.githubusercontent.com/53003665/85989292-e7de9580-ba22-11ea-9c38-6192603c6815.png)

**Versions Used**
KubeSphere: 3.0.0(2020-06-29)
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug

**Comment by leoendless** [comment]
These two roles will no longer be preset in the cluster.

**Comment by Forest-L** [comment]
/assign @leoendless 
Why is it possible to select two production clusters

**Comment by wanjunlei** [comment]
verified
