### ISSUE TITLE
no authorization list for custom cluster role 

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2277]
When custom a cluster role, nothing shows in the authorization resource list.
![Screen Shot 2020-07-01 at 2 46 46 PM](https://user-images.githubusercontent.com/28859385/86211985-d5db2f00-bba9-11ea-8c8c-1eb31294d634.png)
![Screen Shot 2020-07-01 at 2 46 31 PM](https://user-images.githubusercontent.com/28859385/86211998-da9fe300-bba9-11ea-8dba-2a3c948a6d2c.png)

**Comment by wansir** [comment]
@wansir Single cluster grant does not support now. Cluster scope IAM API is read-only until we improve the multi-cluster api-server architecture.

**Comment by leoendless** [comment]
Cluster roles end members are now removed from UI. We only need global-ws-ns authorization control.

**Comment by rayzhou2017** [comment]
verified
