### ISSUE TITLE
Tips somewhere in console to tell users where to enable components

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2278]
@Carlosfengv We put the configuration into the installer crd so user can go there to enable/disable components. But it is hidden too deeply. Is there any way in console to tell users this info?
<img width="1004" alt="Screen Shot 2020-07-02 at 11 25 24 AM" src="https://user-images.githubusercontent.com/28859385/86313058-c8c84980-bc56-11ea-876d-8c2cca6d667b.png">

**Comment by Carlosfengv** [comment]
We designed the management and installation of the components, but currently lack the relevant back-end development support.  
![image](https://user-images.githubusercontent.com/23092051/86314071-455c2780-bc59-11ea-8e8d-480b3b72924f.png)

**Comment by leoendless** [comment]
Can all the plugins be enabled/disabled through API?

**Comment by zryfish** [comment]
Not supported right now. Maybe in next release
