### ISSUE TITLE
the deleted multi-cluster project became a single-cluster project

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2281]
step:
Select a multi-cluster project and delete it

expected result:
delete the multi-cluster successful

actual result:
the deleted multi-cluster project appears in the single cluster list

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0

**Comment by zryfish** [comment]
@liuyp2018 single cluster list, do you mean the project is still in host cluster ?

**Comment by liuyp2018** [comment]
After the multi-cluster project is deleted, see that the project exists in the single cluster list
<img width="788" alt="multi-project" src="https://user-images.githubusercontent.com/36271543/88014500-a6d52f00-cb51-11ea-8ba0-ffaa5d8ad3f9.png">

**Comment by zryfish** [comment]
should be fixed in the latest build, please verify again
