### ISSUE TITLE
devops rbac error

### ISSUE THREAD

**Issue by ConnorLH** [kubesphere/kubesphere#2284]
**Describe the Bug**
After create devops project, there is some rbac errors when enter that project. Neither workspace-manager nor self-provisioner can enter.

**Versions Used**
KubeSphere: 3.0.0
Kubernetes: 1.18.3

**How To Reproduce**
1. Go to 'DevOps Projects.'
2. Click on Project
3. See error

**Comment by zryfish** [comment]
@ConnorLH Can you verify this issue? It should be fixed in v3.0 the latest build

**Comment by rayzhou2017** [comment]
This should be fixed
