### ISSUE TITLE
Error happened when changing password

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2292]
**Describe the Bug**
Error happened when changing password

**Versions Used**
KubeSphere:3.0

**Environment**
Testing enviroment
URL:http://139.198.12.26:30880/

**How To Reproduce**
1. Go to 'http://139.198.12.26:30880/'  and login
2. Click on 'username' and then click  'personal setting' 
3. Click password setting
4. Input original password and new password,submit
5. See error "Bad request"

**Expected behavior**
password changed successfully.

![image](https://user-images.githubusercontent.com/67785532/86461218-3a3df000-bd5c-11ea-87bd-70a4ae9ff36c.png)

/kind bug
/area iam
/assign @wansir
/milestone 3.0.0

**Comment by zryfish** [comment]
This is a known issue and we are working on it. PR is currently under review.

**Comment by rayzhou2017** [comment]
#2264
