### ISSUE TITLE
In the scripts install.sh, the server(node) password does not support #

### ISSUE THREAD

**Issue by dudiao** [kubesphere/kubesphere#2295]
**What's your question**
conf/hosts.ini, I configured the password for node, the password contains ‘#’, here is error:
```
root@192.168.0.3 # ssh 192.168.0.2
Warning: Permanently added 'node1,192.168.0.2' (ECDSA) to the list of known hosts.
root@192.168.0.2's password: 
Permission denied, please try again.
```
When I changed the password(123456) and updated the host.ini, the installation was successful

**Environment: OS & Hardware Information**

CentOS 7.5

**Error logs or message (Attach logs or screenshot)**

**Installer Version**

v2.1.1

**Comment by Forest-L** [comment]
@dudiao
Yes, the SSH password in ansible syntax should not be a '#', the ‘#’ in the password needs to be escaped.
such as: 12345#22  to 12345\#22

**Comment by dudiao** [comment]
ok, thanks.
