### ISSUE TITLE
throws error when adding member cluster via public IP direct connect

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2300]
Host cluster and member cluster are in different cities. Use port forward to member apiserver and copy the kubeconfig of the member cluster to the host cluster. It throws error when clicking importing the member cluster. What should I do?
<img width="1213" alt="Screen Shot 2020-07-05 at 1 46 10 PM" src="https://user-images.githubusercontent.com/28859385/86526404-552c7380-bec6-11ea-8f40-a41ddd40aa8e.png">

**Comment by rayzhou2017** [comment]
I think it is as design. For this case, either use tunnel or use agent connection. Using port forward is unsafe since it is exposing apiserver to public access.

**Comment by zryfish** [comment]
If you planning to use another IP to access kube-apiserver, MUST add the IP address to  kube-apiserver certificate. https://blog.scottlowe.org/2019/07/30/adding-a-name-to-kubernetes-api-server-certificate/ here is great post shows how to do that
