### ISSUE TITLE
project page 404 error

### ISSUE THREAD

**Issue by lxm** [kubesphere/kubesphere#2303]
![image](https://user-images.githubusercontent.com/1918195/86550827-02aa9000-bf76-11ea-941a-59a7e90b554b.png)

![image](https://user-images.githubusercontent.com/1918195/86550844-10f8ac00-bf76-11ea-8c92-a3feb4f72fd2.png)

**Comment by rayzhou2017** [comment]
Please provide more info such as what kind of user are you using. Step-by-step instructions is extremely helpful.

**Comment by lxm** [comment]
user: admin
first create a cluster on eks use ks-installer
then change install config to enable multi cluster, set role to host, enable logging sevicemesh etc...
create agent.yaml in the host cluster, so that the cluster can be added
then go to the project page, error occoured

**Comment by leoendless** [comment]
Fixed in https://github.com/kubesphere/kubesphere/pull/2293/files#diff-1c4600d7da1963c53dedd0886112786a
