### ISSUE TITLE
The host cluster is not shown in the cluster list

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2304]
Login the console of the Host cluster
the host cluster is not shown in the cluster list

<img width="903" alt="host cluster" src="https://user-images.githubusercontent.com/36271543/86551093-b27ffd80-bf76-11ea-9253-e8d594ee905e.png">

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.0.0

**Comment by WaysonWei** [comment]
Is this was designed in this way or a bug? 

Host cluster have to add itself as member cluster in the beginning.

**Comment by zryfish** [comment]
It works as designed. Host cluster is where the multicluster control plane installed, we don't want there are too many workloads or any misconfiguration there since it will cause problems. If host cluster is down, then you can't access control plane any more. So we encourage users do not add host  as a member cluster, but we are still open to suggestions.

**Comment by WaysonWei** [comment]
ok, got it. But the number of cluster showing in dashboard was very confused as it is showing 1 when I have host cluster up without any member cluster joined( empty cluster list ). Then it stay at 1 if I have 1st member cluster joined.

Would it be better to show Host cluster & Member cluster  separately? like
Host Cluster : 1
Member Cluster : ( 0 - many )

<img width="1726" alt="Screen Shot 2020-07-08 at 11 42 51 AM" src="https://user-images.githubusercontent.com/54336863/86859265-623fa180-c116-11ea-9f5f-b0258a029a64.png">
<img width="1726" alt="Screen Shot 2020-07-08 at 11 43 42 AM" src="https://user-images.githubusercontent.com/54336863/86859302-7388ae00-c116-11ea-9eca-0ed423e4c742.png">

**Comment by rayzhou2017** [comment]
That sounds good to me. @Carlosfengv @leoendless

**Comment by rayzhou2017** [comment]
Host is added automatically now. Please check the latest build.
