### ISSUE TITLE
How to install v 3.0？where is the gz file ? thx.

### ISSUE THREAD

**Issue by wanminny** [kubesphere/kubesphere#2305]
How to install v 3.0？where is the gz file ? thx.

**Comment by FeynmanZhou** [comment]
- Install on Linux：https://github.com/kubesphere/kubekey
- Install on Kubernetes：https://github.com/kubesphere/ks-installer

> Attention: The stable release is KubeSphere v2.1.1. KubeSphere v3.0 will be officially GA in mid-to-late July; and v3.0 is currently undergoing high-frequency testing. If you want to try out 3.0 and help the community test it, you can download the v3.0.0 to test it and report bugs to GitHub.

**Comment by wanminny** [comment]
If you want to try out 3.0 and help the community test it, you can download the v3.0.0 to test it and report bugs to GitHub.?
====== 
download the v3.0.0 ,where ? how to got it .

**Comment by FeynmanZhou** [comment]
The readme guide in those two repos.
