### ISSUE TITLE
when a member cluster was down , it cannot be deleted against the host

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/kubesphere#2306]
One way to delete a member cluster , is to handle it in the web console. But if the member cluster was down and cannot be rescued, now it can not be deleted.

**Comment by rayzhou2017** [comment]
Unbind the cluster from the host control panel, is it what you want?
![Screen Shot 2020-07-06 at 12 45 43 PM](https://user-images.githubusercontent.com/28859385/86556725-b6b41700-bf86-11ea-8c2a-e37b59c670cc.png)

**Comment by zackzhangkai** [comment]
If this member cluster was down, and it would be lose connect to the cluster center . So this *unbind* buttom was not availble in the control panel.

**Comment by rayzhou2017** [comment]
Host cluster is not down. You can access its console to click unbind.

**Comment by zryfish** [comment]
When unbind a cluster from multicluster control plane, there are some resource cleanup work needed to be done by Kubefed, which can only be completed when member cluster is accessible. If member cluster is down, it's true that the unbind process will be blocked by Kubefed.

**Comment by rayzhou2017** [comment]
If it is not, it should be a bug.

**Comment by rayzhou2017** [comment]
> When unbind a cluster from multicluster control plane, there are some resource cleanup work needed to be done by Kubefed, which can only be completed when member cluster is accessible. If member cluster is down, it's true that the unbind process will be blocked by Kubefed.

aha, that is true. But I still think it should provide the way to force unbind just in case the cluster is really gone.

**Comment by zryfish** [comment]
Fixed it. Now you can delete a cluster even the cluster is disconnected from control plane.
/kind need-to-verify

**Comment by zackzhangkai** [comment]
when delete a cluster which is disconnected, an error occured also, even though update the ks-console/ks-apiserver/ks-controller-manager mirrors to the newest.

![image](https://user-images.githubusercontent.com/20178386/88192916-a7fc7e00-cc6f-11ea-88ad-d3a3fa4a1d06.png)

Below is the host, you can use it to verify again.
http://103.61.37.76:30880/login

**Comment by rayzhou2017** [comment]
using kubectl delete cluster <name>

**Comment by I321065** [comment]
@rayzhou2017 I have the same issue, and try it by the command "kubectl delete cluster <name>", but I will be blocked, and the cluster can not be deleted.  
reproduce env：
k8s version: 1.26
kubesphere version: 3.4.0
please give me some tips

**Comment by rayzhou2017** [comment]
@zheng1 Please look at this issue

**Comment by zheng1** [comment]
@I321065  I wasn't able to reproduce it. But I think it's probably because there's something wrong with the controller-manager, can you post its logs here?
```
kubectl logs -n kubesphere-system -l app=ks-controller-manager
```

**Comment by I321065** [comment]
@zheng1  I used the command 
`kubectl logs -n kubesphere-system -l app=ks-controller-manager`
but I didnot see any now logs, And I delete the cluster on the cluster management page, it returns success, but when I refresh the page, the cluster still exists
![image](https://github.com/kubesphere/kubesphere/assets/16135063/a34e7d66-8eef-4194-a873-f729124d02ab)

**Comment by I321065** [comment]
@zheng1 attach a screen record:

https://github.com/kubesphere/kubesphere/assets/16135063/3de7834d-707d-42f3-8e6e-508890308e57

**Comment by zheng1** [comment]
@iawia002 PTAL

**Comment by I321065** [comment]
Hi @zheng1，could you give me some tips？

**Comment by I321065** [comment]
@iawia002 could you give me some tips？

**Comment by iawia002** [comment]
This is because we have some cleanup work to do after deleting the cluster, but we encountered some problems when performing these cleanup tasks. As a result, the finalizers of the cluster were not deleted, so it kept getting stuck.
The error details can be found in the `ks-controller-manager` Pod logs. Please double-check for any error logs. If you wish to force delete this cluster, you can use the following command:

```
kubectl patch cluster {xxx} -p "{\"metadata\":{\"finalizers\":null}}" --type=merge
```

**Comment by I321065** [comment]
@iawia002  Thanks your reply, I tries this method, but returned "Unable to connect to the server:EOF"
![image](https://github.com/kubesphere/kubesphere/assets/16135063/a4fca2a6-75f0-43d4-8319-e48f6dd79bc4)

I re-describe the scene:
1.  host-member deploy way, and the cluster need to delete is a member cluster
2. the member cluster has been deleted from cloud provider, such as huawei cloud

BTW: It is ok if we delete the cluster of kubesphere before the cluster being deleted on huawei cloud

**Comment by iawia002** [comment]
> the member cluster has been deleted from cloud provider, such as huawei cloud

This might be the reason why you can't delete it from the console, cause the controller can't even connect to the member cluster, in this scenario, you can force delete it by using the command I provided before.

> Unable to connect to the server: EOF

As for the EOF problem you encountered, this command needs to be executed on the host cluster, can you connect to the k8s cluster normally?

**Comment by I321065** [comment]
@iawia002 I can connect the host cluster, but when I execute the command  in host cluster, it returned error I provided before, and I can not edit the cluster resource successfully.
BTW, when I want to edit the cluster resource on  customize resource page, it also can not succeed, the result like 
![image](https://github.com/kubesphere/kubesphere/assets/16135063/50a7b1a6-77e2-40d7-9f3a-fd5c84d03ae4)
and I find that the resource has deletionTimestamp before I edit it

**Comment by I321065** [comment]
![image](https://github.com/kubesphere/kubesphere/assets/16135063/5ccfc4d2-487a-4d85-be69-062a1fa6c4de)
I think if it need to communicate the member cluster to verify the member cluster when change the cluster resource

**Comment by I321065** [comment]
@iawia002 FYI

**Comment by iawia002** [comment]
This is weird. This webhook is provided by the ks-controller-manager of the host cluster. Is the status of the ks-controller-manager of the host cluster normal?

**Comment by I321065** [comment]
@iawia002 I could not find any error log, but when I execute the command you provider, the ks-controller-manager not produce any log
BTW, I restart the ks-controller-manager pod and I found the log like this
![image](https://github.com/kubesphere/kubesphere/assets/16135063/da49a2dd-7905-413b-a7d6-55d1fe8352ad)

It is right, the clusters  red window in are active clusters and the cluster I need to delete not in the log, is it normal?

**Comment by I321065** [comment]
![image](https://github.com/kubesphere/kubesphere/assets/16135063/e6389740-096b-493e-8ab7-1019d1949255)

**Comment by iawia002** [comment]
> It is right, the clusters red window in are active clusters and the cluster I need to delete not in the log, is it normal?

Yes, clusters marked for deletion will no longer enter the join process.

Let's focus on solving your problem first, due to an unknown reason webhook error, the cluster object cannot be updated. Let's disable this webhook and then perform the deletion:

```
kubectl get validatingwebhookconfigurations cluster.kubesphere.io -o yaml > webhook.yml
kubectl delete validatingwebhookconfigurations cluster.kubesphere.io
kubectl patch cluster {xxx} -p "{\"metadata\":{\"finalizers\":null}}" --type=merge
kubectl apply -f webhook.yml
```

Next time you want to delete the cluster, try to delete it on the ks console first and then delete the K8s cluster.

**Comment by I321065** [comment]
@iawia002  thanks a lot for your help, and next time I will delete the cluster on ks console first
