### ISSUE TITLE
Encountered an unexpected logout during normal operation

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#2313]
As admin, I was forced to exit. Here is logs from ks-apiserver

![image](https://user-images.githubusercontent.com/22350668/86577733-44a2f880-bfad-11ea-9a93-706f89778fa7.png)

**Comment by wansir** [comment]
Support token refresh.
/assign @leoendless

**Comment by huanggze** [comment]
This has never occurred for a long time
