### ISSUE TITLE
how to add an exist cluster to kubesphere in order to manager?

### ISSUE THREAD

**Issue by wanminny** [kubesphere/kubesphere#2315]
how to add an exist cluster to kubesphere in order to manager?

**Comment by wanminny** [comment]
why cannot find add cluster in webui?

**Comment by FeynmanZhou** [comment]
See [How to Enable the Multi-cluster Feature
](https://github.com/kubesphere/community/blob/master/sig-multicluster/how-to-setup-multicluster-on-kubesphere/README.md).
