### ISSUE TITLE
The container exited and kubelet is restarting it when creating appliction under muti-cluster project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2330]
**Describe the Bug**
The container exited and kubelet is restarting it when creating appliction under muti-cluster project

![image](https://user-images.githubusercontent.com/67785532/86762424-391d0380-c079-11ea-8f89-58bf28db63dd.png)

**Versions Used**
KubeSphere:3.0.0

**Environment**
testing env
http://139.198.12.26:30880/

**How To Reproduce**
1. login with  'admin'
2. Click on 'platform management' and then 'access control'
3. Select  'multi-cluster-ws'
4.Click 'project management' and then switch to 'muti-cluster project' tab
5.Select 'multi-cluster-project1'
6.Select 'app' under ‘app load’ in the left navigation bar
7.Click 'muti-clustor-app'
8.Click 'statless-service' under 'member-cluster-1' or  'member-cluster-2'
9. See error

**Expected behavior**
successful

/kind bug
/area iam
/assign @wansir
/milestone 3.0.0

**Comment by wansir** [comment]
A Docker container runs a process (the "command" or "entrypoint") that keeps it alive, exits when its main process finishes.

**Comment by wangtian-010** [comment]
verified pass.close this issue
