### ISSUE TITLE
Clicking version back button did not send  request

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2331]
In the deployment details page, click version back without sending a request
<img width="783" alt="version" src="https://user-images.githubusercontent.com/36271543/86767133-1b05d200-c07e-11ea-9ead-ff325320fb8e.png">

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority medium

**Comment by zryfish** [comment]
Fixed in https://github.com/kubesphere/console/pull/855 
/kind need-to-verify
