### ISSUE TITLE
Duplicated label group happened when create state service under muti-cluster  project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2332]
**Describe the Bug**
Duplcated label group happened when create state service under muti-cluster  project

**Versions Used**
KubeSphere:3.0.0

**Environment**
testing env

http://139.198.12.26:30880/

**How To Reproduce**
1. Click on  'platform management'  on home page then click 'access control'
2. Click on 'multi-cluster-ws' and then click 'project management' and then switch to 'muti-clustor project' tab
3. Click project  'multi-cluster-project1' and then create stat service 
5.Input name ,click next 
6.select influxdb image 
7.Select temp store volume,click next
8.Uncheck add meta data checkbox and click create button directly
![image](https://user-images.githubusercontent.com/67785532/86772580-ddf20d80-c086-11ea-9db1-7ff742a8ec1b.png)

9. See error,Duplcated label group happened 
![image](https://user-images.githubusercontent.com/67785532/86772481-b9963100-c086-11ea-9f46-d62095bfea20.png)

**Expected behavior**
create successful

/kind bug
/area iam
/assign @wansir
/milestone 3.0.0

**Comment by leoendless** [comment]
This problem has been fixed, Please update the ks-console image.

**Comment by wangtian-010** [comment]
fixed,close this issue
