### ISSUE TITLE
Configuration files and keys mounted on deployment are read and write, but cannot be written

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2338]
steps:
1. When a deployment is created, the key or configuration file is mounted as read/write mode
2. After creating the deployment, enter the container terminal, under the directory where the configuration file or key mount, and do the write operation

problem:
The configuration file or key is mounted as read or write, but cannot be written when entering the mount directory

<img width="793" alt="读写" src="https://user-images.githubusercontent.com/36271543/86875641-8babfd80-c115-11ea-898f-eaf06258cefb.png">
/kind bug
/area console
/assign @zryfish 
/milestone 3.0.0
/priority medium

**Comment by zryfish** [comment]
In the latest build, configmap or secret can only mounted with ReadOnly,  can you check it again?

![截屏2020-07-21 10 17 53](https://user-images.githubusercontent.com/3326354/88005224-74b8d280-cb3b-11ea-8702-b92d571a632b.png)
