### ISSUE TITLE
Can not enter container terminal when pod contains two containers

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/kubesphere#2347]
**Describe the Bug**
Can not enter terminal from UI when pod contains two containers, kubectl exec can enter.

![image](https://user-images.githubusercontent.com/38337958/86893459-3d5a2700-c134-11ea-8020-f06f61c3c5dc.png)
![image](https://user-images.githubusercontent.com/38337958/86893822-ca04e500-c134-11ea-9d84-3a4646372f46.png)

**Versions Used**
KubeSphere: v3.0.0

**Expected behavior**
Enter container terminal correctly.

**Comment by leoendless** [comment]
It's not a problem of multiple containers.

**Comment by zryfish** [comment]
Only happens on member cluster under multiple cluster setup, it related to kube-apiserver proxy. We use kube-apiserver proxy requests to member cluster ks-apiserver, but it loses query parameters when proxying terminal APIs, the rest APIs are ok, interesting.

**Comment by zryfish** [comment]
We are heavily using kubernetes components UpgradeAwareHandler, but there is bug in it, it failed to carry query parameters when proxying a `Upgrade` request. Submit a PR to kubernetes, https://github.com/kubernetes/kubernetes/pull/93290. It's unlikely it get merged before our release,  so still need another solution.

**Comment by zryfish** [comment]
There is already an issue reported in the community https://github.com/kubernetes/kubernetes/issues/89360 ,  and a PR https://github.com/kubernetes/kubernetes/pull/90721 , but not likely it will get merged soon.

**Comment by Ma-Dan** [comment]
Verified, close issue.
