### ISSUE TITLE
method not allowed when create secret

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/kubesphere#2348]
when create secret, method not allowd

![image](https://user-images.githubusercontent.com/20178386/86893870-d9842e00-c134-11ea-9809-e7a7f14a67e9.png)

```
root@node1:/root # kubectl -n kubesphere-system logs -f -l app=ks-console
...
  <-- POST /api/clusters/node1-v2/v1/secrets 2020/07/08T07:43:39.633
...
```

the log just has a record, but has no reponse code, maybe it is also a problem.

/assign @leoendless 
/priority medium
/kind bug
/area console

**Comment by wansir** [comment]
Create a secret, `namespace` must be defined in the API path, such as `/api/v1/namespaces/{namespace}/secrets`
