### ISSUE TITLE
a role which has been granted to some user can be delete

### ISSUE THREAD

**Issue by duanjiong** [kubesphere/kubesphere#2349]
![image](https://user-images.githubusercontent.com/3678855/86898479-56b2a180-c13b-11ea-9b35-185b755b118b.png)

**Comment by rayzhou2017** [comment]
Should it be prohibited in the backend?

**Comment by leoendless** [comment]
If a user is in this role, there will be a prompt when deleting the role.
![image](https://user-images.githubusercontent.com/8739949/87238277-2ddc2600-c433-11ea-8ba3-f079155112e6.png)

**Comment by duanjiong** [comment]
You need to check here
![image](https://user-images.githubusercontent.com/3678855/87273617-2fc5e800-c50c-11ea-8f1f-3af2b6d5c9e3.png)

**Comment by leoendless** [comment]
I think it's better to remove batch delete operation for roles. It should be confirmed one by one. I will fix this.
