### ISSUE TITLE
application description should be more accurate for muticluster-project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2350]
**Describe the Bug**
application description should be more accuracy for muticlustor-project

**Versions Used**
KubeSphere:3.0.0

**Environment**
testing env
http://139.198.12.26:30880/

**How To Reproduce**
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click application under application load
5.'self-made applications' displayed under 'How to use application governance?' ,but these is no 'self-made' operation in this page.
![image](https://user-images.githubusercontent.com/67785532/86898852-ca54ae80-c13b-11ea-830b-dfca003845eb.png)

**Expected behavior**
advice to set the decription of 'build applcation' button to 'self-made application'

/kind bug
/area iam
/assign @wansir
/milestone 3.0.0

**Comment by zryfish** [comment]
Agree 
/cc @leoendless

**Comment by wangtian-010** [comment]
verified passed,close this issue
![image](https://user-images.githubusercontent.com/67785532/87894196-9d29c980-ca74-11ea-8f8b-39543d9f7c83.png)
