### ISSUE TITLE
the status is always updating after application created for muticlustor-project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2351]
**Describe the Bug**
the status is always updating after application created for muticlustor-project

**Versions Used**
KubeSphere:3.0.0

**Environment**
testing env
http://139.198.12.26:30880/

**How To Reproduce**
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click application under application load
5.the status is always updating after application created for muticlustor-project.

![image](https://user-images.githubusercontent.com/67785532/86899362-801ffd00-c13c-11ea-88a5-343486af4fe3.png)

**Expected behavior**
status should be completed or other normal status

/kind bug
/area iam
/assign @wansir
/milestone 3.0.0

**Comment by zryfish** [comment]
working on it
/priority medium

**Comment by zryfish** [comment]
duplicate https://github.com/kubesphere/kubesphere/issues/2608
Please verify again using the latest build
/kind need-to-verify

**Comment by wangtian-010** [comment]
verification passed,close this issue
