### ISSUE TITLE
Pipeine page dont show any pipelines

### ISSUE THREAD

**Issue by Warden-Thresh** [kubesphere/kubesphere#2360]
**Describe the Bug**
Pipeine page dont show any pipelines,when i create the same name pipeline ,without any 
warning dialog but get the response
![image](https://user-images.githubusercontent.com/22620409/86992133-6251a700-c1d3-11ea-92ed-4d7ccbb3c179.png)
In a few minutes，i cant create any pipeline 
`pipelines.devops.kubesphere.io "gg" is forbidden: unable to create new content in namespace eem-devopsdvw9g because it is being terminated`
![image](https://user-images.githubusercontent.com/22620409/86992439-0f2c2400-c1d4-11ea-9e73-33283a401266.png)

**Versions Used**
KubeSphere: 3.0
Kubernetes: 1.18.5

**Environment**
How many nodes and their hardware configuration:
3 node
CentOS 7.8.2003 / 1 masters:  4cpu/32g; 2 nodes: 4cpu/32g

**How To Reproduce**
1. Go to devops project
2. Create pipelines

**Expected behavior**

**Comment by shaowenchen** [comment]
Please using the token in Console to replace the password of DevOps.

```bash
devops:
  host: http://lb.kubesphere.local:30180/
  username: admin
  password: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidWlkIjoiMmVjZDk3ZmMtODI5Ni00NGEyLWFkZjMtZWMzMWU5MDRkYTdmIiwiZXhwIjoxNTkzNzY0ODQ3LCJpYXQiOjE1OTM2Nzg0NDcsImlzcyI6Imt1YmVzcGhlcmUiLCJuYmYiOjE1OTM2Nzg0NDd9.kLrwcOv5dk5J1W85CHpX1lakMseWCejhGjyf_PHCc38~
  maxConnections: 100
```

And  restart ks-apiserver and ks-controller-manager

**Comment by shaowenchen** [comment]
In the new environment, ks-installer has solved the problem of the invalid token.

**Comment by rayzhou2017** [comment]
So change the image pull policy to `Always` and restart it to verify the issue, right @shaowenchen ?

```shell
kubectl edit deployments ks-installer -n kubesphere-system
kubectl rollout restart deployments ks-installer -n kubesphere-system
```

**Comment by shaowenchen** [comment]
That's not enough. while ks-installer installs DevOps component, the generated token is incorrect by calling API. So，we need to replace it and restart ks-controller-manager.

```bash
kubectl edit cm kubesphere-config -n kubesphere-system
kubectl rollout restart deployments ks-controller-manager -n kubesphere-system
```

The token may expire in a few hours. This problem has been solved in the new environment

**Comment by Warden-Thresh** [comment]
> That's not enough. while ks-installer installs DevOps component, the generated token is incorrect by calling API. So，we need to replace it and restart ks-controller-manager.
> 
> ```shell
> kubectl edit cm kubesphere-config -n kubesphere-system
> kubectl rollout restart deployments ks-controller-manager -n kubesphere-system
> ```
> 
> The token may expire in a few hours. This problem has been solved in the new environment

it doesnot worker

**Comment by shaowenchen** [comment]
If you have set the password and restart deploys, it will take some time to synchronize the data. Or, you can create another DevOps project for testing.

**Comment by Warden-Thresh** [comment]
> If you have set the password and restart deploys, it will take some time to synchronize the data. Or, you can create another DevOps project for testing.
My config
`    devops:
      host: http://ks-jenkins.kubesphere-devops-system.svc/
      username: admin
      password: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidWlkIjoiMmVjZDk3ZmMtODI5Ni00NGEyLWFkZjMtZWMzMWU5MDRkYTdmIiwiZXhwIjoxNTkzNzY0ODQ3LCJpYXQiOjE1OTM2Nzg0NDcsImlzcyI6Imt1YmVzcGhlcmUiLCJuYmYiOjE1OTM2Nzg0NDd9.kLrwcOv5dk5J1W85CHpX1lakMseWCejhGjyf_PHCc38~
      maxConnections: 100
`
I deployed the cluster again，but still has error

Created pipeline but cant list
![image](https://user-images.githubusercontent.com/22620409/87035813-740b6c80-c21c-11ea-9072-312b783f6d7d.png)

===
### ks-apiserver log
![image](https://user-images.githubusercontent.com/22620409/87036686-c600c200-c21d-11ea-85a3-cb96fb8e91b4.png)

### ks-controller-manager log
![image](https://user-images.githubusercontent.com/22620409/87036877-0a8c5d80-c21e-11ea-9567-3c6c7795691d.png)


This is ks images 
![image](https://user-images.githubusercontent.com/22620409/87035741-5b9b5200-c21c-11ea-802e-dcd1663af7d3.png)


It`s sames like the token is incorrect

**Comment by Warden-Thresh** [comment]
![image](https://user-images.githubusercontent.com/22620409/87039334-95228c00-c221-11ea-86dd-3d36176c3c22.png)

**Comment by shaowenchen** [comment]
@Warden-Thresh try to get token from Console and restart deploys.

@wansir the token of the new environment is incorrect

**Comment by Warden-Thresh** [comment]
> @Warden-Thresh try to get token from Console and restart deploys.
> 
> @wansir the token of the new environment is incorrect

How to create token ?I don't find ti in Document

**Comment by rayzhou2017** [comment]
What is status of this issue, @shaowenchen ?
