### ISSUE TITLE
admin can add multiple clusters for a regular project

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2362]
`admin` seems open the fed project creation page. A self-provisioner user is as expected.
<img width="1092" alt="Screen Shot 2020-07-09 at 1 12 50 PM" src="https://user-images.githubusercontent.com/28859385/86999808-24aa4980-c1e6-11ea-805c-12575781b2d9.png">

**Comment by leoendless** [comment]
What's the problem?

**Comment by rayzhou2017** [comment]
typo, the problem is for a regular project. It is supposed only one cluster is selected for it. But here it can add more than one cluster.

**Comment by leoendless** [comment]
When multiple clusters are selected, a multi-cluster project will be created.

**Comment by rayzhou2017** [comment]
This is not user experience consistent since a self-provisioner is only one cluster to select. And given two different tabs available (Project, Multi-cluster Project), why mess up the regular and fed project here based on how many clusters to select?
<img width="953" alt="Screen Shot 2020-07-09 at 1 36 52 PM" src="https://user-images.githubusercontent.com/28859385/87001109-435e0f80-c1e9-11ea-9bb7-056754c6e673.png">

**Comment by rayzhou2017** [comment]
verfied

**Comment by panpan0000** [comment]
@rayzhou2017 , Hi, greeting. I've installed kubeSphere 3.0.0 with  2 clusters  (one host and one member)
But I couldn't find the page where the "create multiple-cluster project" page like you showed. can you help a bit ?
![image](https://user-images.githubusercontent.com/14049268/90006936-6d18c380-dccc-11ea-8c36-3e723f2a76ca.png)
![image](https://user-images.githubusercontent.com/14049268/90006963-79048580-dccc-11ea-826a-dd9852c78f02.png)

**Comment by rayzhou2017** [comment]
> @rayzhou2017 , Hi, greeting. I've installed kubeSphere 3.0.0 with 2 clusters (one host and one member)
> But I couldn't find the page where the "create multiple-cluster project" page like you showed. can you help a bit ?
> ![image](https://user-images.githubusercontent.com/14049268/90006936-6d18c380-dccc-11ea-8c36-3e723f2a76ca.png)
> ![image](https://user-images.githubusercontent.com/14049268/90006963-79048580-dccc-11ea-826a-dd9852c78f02.png)

Create a workspace and select your clusters for it. Then create a multi-cluster project in the workspace. It is recommended to create a platform-regular user to be the admin of the workspace. `admin` is the platform-admin which means do not use `admin` to work in any workspace.
