### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/kubesphere#2366]
![image](https://user-images.githubusercontent.com/20178386/87002376-0b0c0080-c1ec-11ea-9b71-c14aa925e875.png)

http://ssa:30880/workspace1/clusters/node1-v2/projects/xxx/s2ibuilders/ii-b2i-ylqg/records

/assign @leoendless 
/priority medium
/kind bug
/area console

**Comment by leoendless** [comment]
Duplicate of #https://github.com/kubesphere/kubesphere/issues/2361
