### ISSUE TITLE
when use docker registry secret , 400 error occured

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/kubesphere#2367]
1. First create a key of docker-registry type.  http://ssa:30880/clusters/node1-v2/secrets
2. deploy use this key, then 400 error occured  .  http://ssa:30880/clusters/node1-v2/deployments

![image](https://user-images.githubusercontent.com/20178386/87005305-61c80900-c1f1-11ea-9278-0c33f7495f78.png)

/assign @leoendless 
/priority medium
/kind bug
/area console

**Comment by zackzhangkai** [comment]
This is the link  address, maybe need to proxy this api from the host to the member.

http://ssa:30880/kapis/resources.kubesphere.io/v1alpha2/registry/blob?namespace=xxx&image=docker.io%2Faaa&secret=mainrepo

@leoendless

**Comment by leoendless** [comment]
@harrisonliu5 Please help to check this issue.
