### ISSUE TITLE
Delete success message should display after record disappears

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2371]
**Describe the Bug**
delete success message should display after record disappears

**Versions Used**
KubeSphere:3.0.0

**Environment**
testing env
http://139.198.12.26:30880/

**How To Reproduce**
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click app router under application load
5.Click ... after record  and select delete
6.Delete success message should display before record disappears.By the way, other applications have the same issue.

![image](https://user-images.githubusercontent.com/67785532/87017923-30f0cf80-c203-11ea-92d0-cd6776d35d36.png)

**Expected behavior**
Delete success message should display after record disappears

/kind bug
/area iam
/assign leoendless
/milestone 3.0.0

**Comment by leoendless** [comment]
It is difficult to distinguish whether the resource is directly deleted at the front end.
`Delete successfully` tip shows because the API returns success.
`Resource Deleting` status shows because it takes some time for backend service to delete the resource.

**Comment by wangtian-010** [comment]
But there is a proplem in this condition,if record did not disappear.I can delete this record again, it is not friendly for customer
