### ISSUE TITLE
here is a problem with the number of versions show

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2374]
deploy version record page , there is a problem with the number of versions show

![image](https://user-images.githubusercontent.com/36271543/87115883-13754180-c2a7-11ea-87cc-ae14fc5d08c8.png)

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority low

**Comment by leoendless** [comment]
It seems a problem with backend service.

**Comment by zryfish** [comment]
Just inspect the source, `revisionsHistoryLimit` means how much history revisions will be preserved, plus one current active replicaset, there should be 11 ( 10 + 1 ) revisions by default. Old replicasets are not deleted immediately after new replicasets created, there is some delay.  So it's not a bug.
