### ISSUE TITLE
no event records for muti-cluster project application router

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2375]
**Describe the Bug**
no event records for muti-cluster project application router  

**Versions Used**
KubeSphere:3.0.0

**Environment**
testing env
http://139.198.12.26:30880/

**How To Reproduce**
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click app router under application load
5.Create or edit app router etc.
6.Switch envent tab and there is no event records

![image](https://user-images.githubusercontent.com/67785532/87112421-541c8d00-c29e-11ea-8149-a2f3010df136.png)

**Expected behavior**
Display envent records

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.0.0

**Comment by wansir** [comment]
It's not a bug, events are removed one hour after the last occurrence.

**Comment by wangtian-010** [comment]
envent displays,close this issue
