### ISSUE TITLE
next page icon is overlayed 

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2377]
**Describe the Bug**
next page icon is overlayed 

**Versions Used**
KubeSphere:3.0.0

**Environment**
testing env
http://139.198.12.26:30880/

**How To Reproduce**
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click app router  under application load
5.next page icon is overlayed in list page

![image](https://user-images.githubusercontent.com/67785532/87115308-6d750780-c2a5-11ea-90a3-bb5ad043e3ee.png)
**Expected behavior**
Should not overlay

/kind bug
/area iam
/assign leoendless
/milestone 3.0.0

**Comment by rayzhou2017** [comment]
You can drag and move the toolbox icon

**Comment by wangtian-010** [comment]
can drag and move the toolbox icon，close this issue
