### ISSUE TITLE
Internal Server Error happened for servicemesh not started service under multi-cluster project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2383]
**Describe the Bug**
Internal Server Error happened for servicemesh not started service under multi-cluster project

**Versions Used**
KubeSphere:3.0.0

**Environment**
testing env
http://139.198.12.26:30880/

**How To Reproduce**
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click application menu  under application load
5.Select one application and switch to Tracing tab
6.Select the cluster that servicemesh not started
7.Click service and error happened

![image](https://user-images.githubusercontent.com/67785532/87122158-e6c92600-c2b6-11ea-8f60-83009889f6c6.png)

**Expected behavior**
Should display the error message

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.0.0

**Comment by zryfish** [comment]
Yeah, istio is not enabled in member-cluster-1, so it's expected behavior.  /cc @leoendless I think it's better not to issue the request if servicemesh is not enabled here.

**Comment by wangtian-010** [comment]
verification passed,close this issue
