### ISSUE TITLE
Too many operations with add-Node scripts

### ISSUE THREAD

**Issue by 53537** [kubesphere/kubesphere#2387]
Kubesphere v2.1.1
If a new node is added to the cluster by using the add-node.sh  script, the docker configuration of the previous node will be reset(/etc/systemd/system/docker.service.d/docker-options.conf), and the business of the old node will be interrupted (it is speculated that the docker configuration will be reset and then restarted). And the new node firewall is not closed, resulting in some necessary network communication is blocked

**Comment by pixiake** [comment]
You may only add the new nodes in the kube-node group of the hosts.ini,  when you plan to add new nodes to your cluster.

In the next version, we will improve this and use new tools which named [KubeKey](https://github.com/kubesphere/kubekey) to create and operate kubernetes clusters.

**Comment by 53537** [comment]
当申请完新的主机后，在主机配置文件 conf/hosts.ini根据需要增加的主机信息在 [all] 和 [kube-node] 部分对应添加一行参数，若扩容多台主机则依次添加多行参数。需要注意的是，扩容新的节点时不能修改原节点的主机名如 master、node1 和 node2，如下添加新节点 node3

The documentation states that you cannot just add new servers because information such as hosts needs to be added to previous nodes

**Comment by 53537** [comment]
Maybe you need to add hosts and other operations to the previous node

**Comment by pixiake** [comment]
example:

`master / node1 / node2` are already existed in cluster,  now  you want to add `node3 / node4` to your cluster.

All nodes must be added in the `all` group, but only add the new nodes in the `kube-node` group.

```
[all]
master ansible_connection=local  ip=192.168.0.5
node1  ansible_host=192.168.0.6  ip=192.168.0.6  
node2  ansible_host=192.168.0.8  ip=192.168.0.8 
node3  ansible_host=192.168.0.9  ip=192.168.0.9
node4  ansible_host=192.168.0.10  ip=192.168.0.10 

[kube-master]
master

[kube-node]
node3
node4

[etcd]
master

[k8s-cluster:children]
kube-node
kube-master 
```

**Comment by 53537** [comment]
Examples in the documentation：

[kube-node]
master
node1
node2 
node3

**Comment by 53537** [comment]
And the new node firewall is not closed

**Comment by pixiake** [comment]
Of course you can add all nodes in `kube-node` group，but to avoid a refresh of docker‘s configuration，you can add only the new nodes in the kube-node group.

`firewall` need to close by yourself.

**Comment by 53537** [comment]
Ok, thank you. Please update the document

**Comment by FeynmanZhou** [comment]
> /cc @FeynmanZhou @Sherlock113 This is asked by quite a few users. Can you update the 2.1.x doc?

ok

**Comment by FeynmanZhou** [comment]
It has been fixed by @Sherlock113 in [kubesphere/docs.kubesphere.io#737](https://github.com/kubesphere/docs.kubesphere.io/pull/737).

See [this guide](https://kubesphere.com.cn/docs/zh-CN/installation/add-nodes/).

**Comment by 53537** [comment]
Hello, after adding the new node, I found that the disk IO of the new node is very sensitive. The pod disk with high pressure can even be written up to 300M/s. However,The POD itself does not need to write to disk, and the DISK IO is normal when POD runs on the old node.Please help me if there is any other configuration operation needed for the new node. Thank you

**Comment by rayzhou2017** [comment]
Did you check the root cause. It is unlikely the addition causing the problem.

**Comment by 53537** [comment]
I checked other processes in the system, but found no system processes occupying IO. The way to found is when the POD pressure is slightly higher

**Comment by rayzhou2017** [comment]
I did not reproduce it in v3.0.0
