### ISSUE TITLE
pv name maybe should be displayed in the volume web

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/kubesphere#2388]
In the web , I cannot get the pv name, mybe it should be displayed.

http://ssa:30880/clusters/node1-v2/projects/xxx/volumes/iii/resource-status

![image](https://user-images.githubusercontent.com/20178386/87129338-c0f64e00-c2c3-11ea-8681-8f57784cb73e.png)

![image](https://user-images.githubusercontent.com/20178386/87129391-d5d2e180-c2c3-11ea-88b1-9f4b36330a86.png)

```
root@node1:/root # kubectl get pv pvc-fc318ad4-b874-49a9-baa6-46be4ee946fe
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM     STORAGECLASS    REASON   AGE
pvc-fc318ad4-b874-49a9-baa6-46be4ee946fe   40Gi       RWO            Delete           Bound    xxx/iii   csi-qingcloud            63m
```

@leoendless 

/priority low
/kind need-to-verify
/area console

**Comment by leoendless** [comment]
Kubesphere console omits the concept of PV on the UI to reduce the complexity of the volume.
