### ISSUE TITLE
when resized a mounted volume, the size stayed unchanged

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/kubesphere#2389]
1. Resize the volume in the web , it return success. But indeed it not changed.
2. When directly edit the storage of the pv by kubectl tool, the pv shows the changed size. But in the web, it still shown unchanged.

```
root@node1:/root # kubectl get pv pvc-fc318ad4-b874-49a9-baa6-46be4ee946fe
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM     STORAGECLASS    REASON   AGE
pvc-fc318ad4-b874-49a9-baa6-46be4ee946fe   40Gi       RWO            Delete           Bound    xxx/iii   csi-qingcloud            63m
```

http://ssa:30880/clusters/node1-v2/projects/xxx/volumes/iii/resource-status

@leoendless 
/priority low
/kind bug
/area console

**Comment by leoendless** [comment]
@min-zh Please help to check this problem.
