### ISSUE TITLE
安装到kube proxy这一步负载很高

### ISSUE THREAD

**Issue by Nocturnana** [kubesphere/kubesphere#239]
![image](https://user-images.githubusercontent.com/3982917/50005961-1f275600-ffe7-11e8-87c0-a9d789abbda4.png)

![image](https://user-images.githubusercontent.com/3982917/50005939-0323b480-ffe7-11e8-972e-f3375f114a70.png)

**Comment by wansir** [comment]
感谢反馈，从截图中看到在安装之前load average就已经很高了，如果安装完成之后内核CPU占用率还是居高不下，需要定位到具体进程，查看日志。

如果可以，请提供操作系统信息，便于我们排查问题。

**Comment by Nocturnana** [comment]
安装的前负载为0 是安装的时候负载才很高  操作系统 版本CentOS Linux release 7.2.1511 (Core)
