### ISSUE TITLE
the status of sc is not correct

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/kubesphere#2390]
http://ssa:30880/clusters/node1-v2/storageclasses

![image](https://user-images.githubusercontent.com/20178386/87132200-1b91a900-c2c8-11ea-819b-5529a14e4526.png)

/assign @leoendless 
/priority medium
/kind bug
/area console

**Comment by leoendless** [comment]
Does the annotation `storageclass.kubesphere.io/support-snapshot` add to these storageclasses?
