### ISSUE TITLE
LDAP enhancement suggestions

### ISSUE THREAD

**Issue by k0ngk0ng** [kubesphere/kubesphere#2391]
1.  Support to display the username as DisplayName, or provide such a field can be configured.
     Only sAMAccountName can be displayed as the username now.
2.  Support MemberOf filtering

**Comment by rayzhou2017** [comment]
@wansir @leoendless @k0ngk0ng This sounds a good suggestion. Can you make a decision if we can finish it in v3.0.0? Please note it may affect several places such as `welcome xxx`, account list etc. in my opinion.

**Comment by wansir** [comment]
We will provide LDAP identity provider in 3.0, these two suggestions are in the plan.

**Comment by rayzhou2017** [comment]
> We will provide LDAP identity provider in 3.0, these two suggestions are in the plan.

3.0 in plan？We already dcut. So you mean it will provide this feature in the upcoming release (v3.0.0)?

**Comment by wansir** [comment]
Now the identity provider framework has been completed, it's convenient to configure plug-ins, we can use the authentication code of LDAP in 2.x. We don't have enough time to test it, we can provide a simple LDAP identity provider plugin, improve it in version 3.0.x.
