### ISSUE TITLE
how to add my  test k8s cluster to kubesphere

### ISSUE THREAD

**Issue by wanminny** [kubesphere/kubesphere#2393]
1.  already enable 
  multicluster:
    clusterRole: host

2.   kubesphere cluster is running ,as below:
![image](https://user-images.githubusercontent.com/6701531/87143309-77642e00-c2d8-11ea-83a2-d5cd323d1fa8.png)

3. but add the cluster , error 
![image](https://user-images.githubusercontent.com/6701531/87143469-b72b1580-c2d8-11ea-9d5d-94e0398b1a62.png)

how to solve it .thank you  in advance.

**Comment by wanminny** [comment]
the svc   ks-apiserver is exists.

![image](https://user-images.githubusercontent.com/6701531/87143659-0a04cd00-c2d9-11ea-96fb-d25a86eaa9c2.png)

**Comment by zryfish** [comment]
Where is your test cluster?  Have you installed ks-installer on your test cluster?

**Comment by wanminny** [comment]
> Where is your test cluster? Have you installed ks-installer on your test cluster? If not, try https://github.com/kubesphere/ks-installer#minimal-installation


ks-allinone cluster is running , so  ks-installer  is ok ?
 
my test cluster and kube-sphere in my same local netwrok ,eg: 10.1.x.x ; ping and telnet is ok.

**Comment by wanminny** [comment]
> Where is your test cluster? Have you installed ks-installer on your test cluster? If not, try https://github.com/kubesphere/ks-installer#minimal-installation

ks-allinone cluster is running on the upper pic , so ks-installer is ok ?

my test cluster and kube-sphere in my same local netwrok ,eg: 10.1.x.x ; ping and telnet is ok.

**Comment by zryfish** [comment]
> > Where is your test cluster? Have you installed ks-installer on your test cluster? If not, try https://github.com/kubesphere/ks-installer#minimal-installation
> 
> ks-allinone cluster is running on the upper pic , so ks-installer is ok ?
> 
> my test cluster and kube-sphere in my same local netwrok ,eg: 10.1.x.x ; ping and telnet is ok.

Can you run the following command on your member cluster, not on your allinone cluster
```
kubectl -n kubesphere-system get po 
```

If there is nothing there, then you need to install components via https://github.com/kubesphere/ks-installer#minimal-installation
