### ISSUE TITLE
Suggest records display in list order by create time desc under multi-cluster project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2395]
**Describe the Bug**
Suggest records display in list order by create time desc under multi-cluster project

**Versions Used**
KubeSphere:3.0.0

**Environment**
testing env
http://139.198.12.26:30880/

**How To Reproduce**
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click application/service/workload/app router menu  under application load
5.See the records in list
7.Records display order by name
![image](https://user-images.githubusercontent.com/67785532/87211536-87b5f080-c34c-11ea-9c31-e5ce71e447c0.png)
![image](https://user-images.githubusercontent.com/67785532/87211553-9e5c4780-c34c-11ea-8a4d-0a0c8bad142a.png)

**Expected behavior**
Suggest records display in list order by create time desc under multi-cluster project

/kind bug
/area console
/assign leoendless
/milestone 3.0.0

**Comment by leoendless** [comment]
Currently, we use native k8s API for the federated resources list. It doesn't support sort, fuzzy search, etc. Will these resources be rewritten to ks resource APIs? @zryfish

**Comment by zryfish** [comment]
> Currently, we use native k8s API for the federated resources list. It doesn't support sort, fuzzy search, etc. Will these resources be rewritten to ks resource APIs? @zryfish

Yes, working on it, but it's not likely finished before release, so probably in next version

**Comment by zryfish** [comment]
@leoendless If I remember correctly, this is already included in v3.0, right?

**Comment by leoendless** [comment]
Yes, this bug has been fixed in v3.0.0

**Comment by benjaminhuo** [comment]
Close this issue because it has been fixed
/close
