### ISSUE TITLE
self-provisioner can't create pv

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2396]
**Describe the Bug**
log in as the self-provisioner, and enter its project. Then create a PV. Error msg shows as below
<img width="1280" alt="Screen Shot 2020-07-11 at 9 21 05 AM" src="https://user-images.githubusercontent.com/28859385/87213515-2bf16480-c358-11ea-87c4-4da28529a077.png">

**Versions Used**
KubeSphere: 3.0.0-dev

**Environment**
allinone

**Expected behavior**
self-provisioner is able to create pv

**Comment by rayzhou2017** [comment]
not fixed

**Comment by wansir** [comment]
I've verified this issue yesterday, may need to reinstall or create a new workspace.

**Comment by rayzhou2017** [comment]
verified
