### ISSUE TITLE
no event records for service under muti-cluster project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2399]
Describe the Bug
no event records for application router under muti-cluster project 
Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click service menu under application load
5.Create or edit service etc.
6.Switch envent tab and no any event records
![image](https://user-images.githubusercontent.com/67785532/87238307-84496480-c433-11ea-9402-064451e77953.png)

Expected behavior
Display envent records

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.0.0

**Comment by rayzhou2017** [comment]
This place holds short-time events. You need to search history of events from toolbox. So trigger an event and check if it is a valid bug by scaling replicas.

**Comment by junotx** [comment]
Events of muti-cluster loads are not currently supported for presentation and will be added later
/assign @leoendless

**Comment by wangtian-010** [comment]
envent displays correctly,close this issue
