### ISSUE TITLE
一个角色为project admin的用户邀请成员到项目中有报错

### ISSUE THREAD

**Issue by jerryjedi** [kubesphere/kubesphere#240]
一个用户，workspace-regular，同时是project admin，邀请一个角色为workspace-regular的用户成为project的viewer时，第一次没有显示成功（没有显示打勾）也没有报错，再配置一次则报错“Already Exist  rolebindings.rbac.authorization.k8s.io "viewer-smpv" already exists“ ，我猜测后台数据库改了，但前端没有正确显示。
在项目用户列表，刷新后可以看到修改结果。

![_20181215203304](https://user-images.githubusercontent.com/7875026/50043079-ce783180-00a8-11e9-80d8-40981fe41e3d.png)

**Comment by calvinyv** [comment]
数据同步问题为偶发情况，我们正在优化后端架构以期在后面的版本中fix这个问题

**Comment by rayzhou2017** [comment]
2.0.0版本已解决
