### ISSUE TITLE
Allow to set the number of ingress-controller replicas before creating Ingress

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#2401]
Currently, only one replica will be deployed, which is not robust in production environments.

![image](https://user-images.githubusercontent.com/22350668/87246225-913f7580-c47e-11ea-8307-9f9e8a3b0d35.png)

**Comment by zryfish** [comment]
/kind feature

Will refactor gateway

**Comment by zryfish** [comment]
#3055

**Comment by zryfish** [comment]
duplicate with #3055
/close
