### ISSUE TITLE
project custom role is incomplete

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2403]
**Describe the Bug**
Create a custom project role as follows. Then log in a user with the role, got error msg. Another question, why there is no configmap authorization in the resource list?

<img width="958" alt="Screen Shot 2020-07-13 at 11 51 41 AM" src="https://user-images.githubusercontent.com/28859385/87269254-3732c480-c4ff-11ea-8757-e2a49ff7285e.png">

<img width="1227" alt="Screen Shot 2020-07-13 at 11 45 48 AM" src="https://user-images.githubusercontent.com/28859385/87269285-487bd100-c4ff-11ea-8f93-06f926120ef4.png">

**Versions Used**
KubeSphere: 3.0.0-dev

**Environment**
allinone, minimal installation

**Comment by wansir** [comment]
The authorization list can be configured dynamically through  CRD, we will improve the missing parts.

**Comment by leoendless** [comment]
configmap is included in workload management

**Comment by rayzhou2017** [comment]
> configmap is included in workload management

I do not see it. And why make consistent with the navigation with project?
<img width="973" alt="Screen Shot 2020-07-13 at 12 36 54 PM" src="https://user-images.githubusercontent.com/28859385/87271362-9c89b400-c505-11ea-8f60-0785987cdfc4.png">

**Comment by wansir** [comment]
We have aggregated some closely related permissions, it might be confusing, require more explanation(or adjust an intuitive name).
