### ISSUE TITLE
Bad UI experience on the workspace monitoring page

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#2405]
**Describe the Bug**
Bad UI experience on the workspace monitoring page

**Versions Used**
KubeSphere: 3.0 dev

**Environment**
How many nodes and their hardware configuration:
Ubuntu 18.04.3 / 1 masters:  8cpu/16g; 2 nodes: 8cpu/16g

**How To Reproduce**
1. Go to some workspace monitoring dashboard, 
2. There are  'Physical Resources Usage' and 'Application Resources Usage' section
3. Select to host cluster in 'Physical Resources Usage', and then click physical memory data
4. on platform workspace list page, click 'system-workspace'

**Expected behavior**
For #2 step, you could see there are two clusters drop-down list, that's very inconvenient for users
For #3 step, I select host cluster, but it's still set to member cluster when I go to the memory monitoring page
For #4 step, the 'system-workspace' monitoring dashboard choose member cluster as default in cluster drop-down list

<img width="1637" alt="Xnip2020-07-13_13-48-16" src="https://user-images.githubusercontent.com/28883416/87275012-cb0c8c80-c50f-11ea-904b-bf57a259a8a8.png">

<img width="1047" alt="Xnip2020-07-13_13-48-35" src="https://user-images.githubusercontent.com/28883416/87275035-d9f33f00-c50f-11ea-861f-d598d2fcd933.png">

**Comment by leoendless** [comment]
I could fix Step 3. Any comments for Step 2 @benjaminhuo.

**Comment by benjaminhuo** [comment]
Regarding step 2, Two cluster selecting drop boxes in one page is indeed  a bit inconvenient.
One cluster selector for one page is ok for me 
@leoendless @calvinyv

**Comment by leoendless** [comment]
@Carlosfengv Please help to re-design the UI.

**Comment by calvinyv** [comment]
> I could fix Step 3. Any comments for Step 2?@benjaminhuo

pls also take a look @step3

1. 

step3

**Comment by benjaminhuo** [comment]
Regarding step4, maybe we needn't to do anything specific to system-workspace according to cluster's role: host or member.
Use the default logic for all workspace is ok

@calvinyv @leoendless

**Comment by calvinyv** [comment]
verified
