### ISSUE TITLE
the problem of Inconsistent jwtSecret

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2406]
After installing a multi-cluster environment, enter the management page of member-cluster, prompt session timeout
<img width="720" alt="重新登录" src="https://user-images.githubusercontent.com/36271543/87282818-3a41ab00-c527-11ea-9071-df9320dc99ec.png">

problem:
1. The jwtSecret of the host and member cluster is inconsistent
2. need to add a description of the problem to the document

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.0.0
/priority high

**Comment by rayzhou2017** [comment]
Did you change the clusterRole to member in the member cluster?

**Comment by rayzhou2017** [comment]
kubectl edit cc ks-installer -n kubesphere-system

**Comment by zryfish** [comment]
Yeah, it's introduced by https://github.com/kubesphere/ks-installer/pull/877 , working on it

**Comment by kubeshared** [comment]
thk
