### ISSUE TITLE
pod/service/application/app router always display deleting status when delete them under muti-cluster project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2407]
Describe the Bug
pod/service/application/app router always display deleting status after delete them under muti-cluster project

Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click workload menu under application load
5.Create workload and add container(Jenkins)
6.Select this pod and delete
7.workload is always deleting status under muti-cluster project but this pod should be deleted via 'kubectl get pod -n muti-clustor-project'
![image](https://user-images.githubusercontent.com/67785532/87285216-d4a2ee00-c529-11ea-9c2f-2db3fa1a28d9.png)
![image](https://user-images.githubusercontent.com/67785532/87285253-e2587380-c529-11ea-8345-0b679f9355cd.png)

By the way,service,application,app router have the same phenomenon

Expected behavior
pod is deleted should not display

/kind bug
/area console
/assign leoendless
/milestone 3.0.0

**Comment by leoendless** [comment]
You may need to refresh the list manually because the WebSocket communication is unstable.

**Comment by wangtian-010** [comment]
I tried and get the same result 
![image](https://user-images.githubusercontent.com/67785532/87389539-7af9fc80-c5d9-11ea-87b8-03c7ef8bd321.png)

**Comment by wangtian-010** [comment]
![image](https://user-images.githubusercontent.com/67785532/87390524-9a922480-c5db-11ea-80a7-8e3ac688da69.png)
can not be deleted

**Comment by wangtian-010** [comment]
verification passed,close this issue
