### ISSUE TITLE
no event records for workload under muti-cluster project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2411]
Describe the Bug
no event records for workload under muti-cluster project
Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click workload menu under application load
5.Create or edit one pod
6.Switch envent tab and no any event records
Note: envent is true for config-sample.yaml
![image](https://user-images.githubusercontent.com/67785532/87297789-93b3d500-c53b-11ea-9621-9181c4122114.png)

Expected behavior
Display envent records

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.0.0

**Comment by rayzhou2017** [comment]
This place only show a short time event which is stored in memory by K8s. For history you need go to the tookbox to search event.

**Comment by zryfish** [comment]
Yeah, kube-apiserver only keeps the latest one-hour events by default.

**Comment by wangtian-010** [comment]
verification passed,close this isuue
