### ISSUE TITLE
Changing the image in the container image does not take effect

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2417]
Describe the Bug
Changing the image in the container image does not take effect
Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muti-clustor-project' and then click workload menu under application load
5.Create statful set and change the image from httpd to tomcat for 'member-cluster-1'
![image](https://user-images.githubusercontent.com/67785532/87399905-aa653500-c5ea-11ea-819a-651158f0e406.png)

6.Check the pod and find the image is httpd
![image](https://user-images.githubusercontent.com/67785532/87399934-b3ee9d00-c5ea-11ea-8c5f-5eae7fe71a59.png)

Expected behavior
should be tomcat image for for 'member-cluster-1'

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.0.0

**Comment by zryfish** [comment]
Can't reproduce in the environment given, can you verify it again using latest image?

**Comment by wangtian-010** [comment]
can't be reproduced，close this issue
