### ISSUE TITLE
ServiceUnavailable no endpoints available for service ":ks-apiserver:" error happened

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2418]
Describe the Bug
ServiceUnavailable no endpoints available for service ":ks-apiserver:" error happened
Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
ServiceUnavailable no endpoints available for service ":ks-apiserver:" error happened very freqently.
not sure the reason
![image](https://user-images.githubusercontent.com/67785532/87400397-5575ee80-c5eb-11ea-8d1e-50b02538088b.png)
![image](https://user-images.githubusercontent.com/67785532/87402891-c23eb800-c5ee-11ea-92d5-96fc58d2a136.png)

Expected behavior
should avoid this happen

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.0.0

**Comment by zryfish** [comment]
Yes, this could happen if service `ks-apiserver` in member cluster is down. Not a bug, error returned by kube-apiserver.

/close
