### ISSUE TITLE
创建devops project失败报错

### ISSUE THREAD

**Issue by jerryjedi** [kubesphere/kubesphere#242]
用户role为”workspace-regular“ 时创建 devops工程时失败，如果用workspace-manager角色创建则没有问题。

报错信息：
<!DOCTYPE html><html><head resURL="/static/8229c2bd" data-rooturl="" data-resurl="/static/8229c2bd"> <title>Jenkins [Jenkins]</title><link rel="stylesheet" href="/static/8229c2bd/css/layout-common.css" type="text/css" /><link rel="stylesheet" href="/static/8229c2bd/css/style.css" type="text/css" /><link rel="stylesheet" href="/static/8229c2bd/css/color.css" type="text/css" /><link rel="stylesheet" href="/static/8229c2bd/css/responsive-grid.css" type="text/css" /><link rel="shortcut icon" href="/static/8229c2bd/favicon.ico" type="image/vnd.microsoft.icon" /><link color="black" rel="mask-icon" href="/images/mask-icon.svg" /><script>var isRunAsTest=false; var rootURL=""; var resURL="/static/8229c2bd";</script><script src="/static/8229c2bd/scripts/prototype.js" type="text/javascript"></script><script src="/static/8229c2bd/scripts/behavior.js" type="text/javascript"></script><script src='/adjuncts/8229c2bd/org/kohsuke/stapler/bind.js' type='text/javascript'></script><script src="/static/8229c2bd/scripts/yui/yahoo/yahoo-min.js"></script><script src="/static/8229c2bd/scripts/yui/dom/dom-min.js"></script><script src="/static/8229c2bd/scripts/yui/event/event-min.js"></script><script src="/static/8229c2bd/scripts/yui/animation/animation-min.js"></script><script src="/static/8229c2bd/scripts/yui/dragdrop/dragdrop-min.js"></script><script src="/static/8229c2bd/scripts/yui/container/container-min.js"></script><script src="/static/8229c2bd/scripts/yui/connection/connection-min.js"></script><script 
。。。。
无法copy完，不知系统是否有日志文件可以查询到。

**Comment by rayzhou2017** [comment]
2.0.0已fix
