### ISSUE TITLE
Added annotation to the service, it is not present in the config file after creation

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2420]
1. create service,add annotation
2. after creation, the annotation is not present in the config file
<img width="767" alt="annotation" src="https://user-images.githubusercontent.com/36271543/87405040-80fbd780-c5f1-11ea-9538-87530b17496f.png">

/kind bug
/area console
/assign @leoendless 
/milestone 3.0.0
/priority Medium

**Comment by Carlosfengv** [comment]
Annotations => Annotations(Apply to the workload)
