### ISSUE TITLE
Replicate creating do not always using the same strategy under muti-cluster project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2426]
Describe the Bug
Replicate creating do not always using the same strategy under muti-cluster project
Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click service menu under application load
5.Create service with aggregation deployment strategy
![image](https://user-images.githubusercontent.com/67785532/87508383-dbed0780-c6a1-11ea-9c42-00f876081140.png)
6.Create replicate and only the first three replicas adopt this strategy.
![image](https://user-images.githubusercontent.com/67785532/87508606-574eb900-c6a2-11ea-8f08-832eb6e4e4c5.png)

Expected behavior
This strategy should be used for all replicas

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.0.0

**Comment by zryfish** [comment]
The selected placement strategy is working as expected. We use `prefer` not `required`, `prefer` is softer  constraint, means kube-scheduler will try its best to schedule these pods into one node, but not guarantee. You can refer https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity for more details

**Comment by zryfish** [comment]
/close
close issue as it's not a bug, but feel free to reopen if there are more questions
