### ISSUE TITLE
Only running and deleting status display for service/workload/app router under muti-cluster project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2429]
Describe the Bug
Only running and deleting status display for service/workload/app router under muti-cluster project
Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click service menu under application load
5.Create service or updating service 
6.Only running and deleting status display,no other status display(such as:updating).
![image](https://user-images.githubusercontent.com/67785532/87512667-ffb44b80-c6a9-11ea-9507-355dea307676.png)

Expected behavior
Should display other status

/kind bug
/area console
/assign leoendless
/milestone 3.0.0

**Comment by leoendless** [comment]
Currently, there are only two statuses for federated resources.

**Comment by benjaminhuo** [comment]
So this is expected behavior or something needs to improve?

**Comment by yuswift** [comment]
The kubefed community is working on the status of federeatdresources. We can get more status in the future. Please see the [pr](https://github.com/kubernetes-sigs/kubefed/pull/1292).
