### ISSUE TITLE
展现devops工程详情报错

### ISSUE THREAD

**Issue by jerryjedi** [kubesphere/kubesphere#243]
用户角色为"workspace-manager"，创建devops工程，系统报”成功“，点击进入该工程时，系统报错：见附件。

![_20181219002259](https://user-images.githubusercontent.com/7875026/50167737-cf1cfc00-0324-11e9-95e2-b65a84f319a3.png)

**Comment by runzexia** [comment]
@jerryjedi 需要将jenkins的deployment scale到0再scale到1等待jenkins启动后再尝试一下
