### ISSUE TITLE
No container display after created under muti-cluster project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2430]
Describe the Bug
No container display after created under muti-cluster project
Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click service menu under application load
5.Create service
6.No container display
![image](https://user-images.githubusercontent.com/67785532/87519066-aea95500-c6b3-11ea-8bcd-a4e8963a0d26.png)

Expected behavior
Should display the created container just now

/kind bug
/area console
/assign leoendless
/milestone 3.0.0

**Comment by leoendless** [comment]
Please check the workload's status or events.

**Comment by leoendless** [comment]
We update the workload conditions. Now you can check the workload conditions in the UI.

**Comment by rayzhou2017** [comment]
Is this fixed or not?

**Comment by wangtian-010** [comment]
verification passed,close this issue
