### ISSUE TITLE
Problem with creating the same deployment and service name

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2433]
**Describe the Bug**
The deployment is created with the same name as the service, prompting for duplicate labels
<img width="707" alt="重复名称" src="https://user-images.githubusercontent.com/36271543/87527011-19f82480-c6be-11ea-8fa4-76bf33cb51ee.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.16.12
member1-v1.18.5
member2-v1.17.8

**Environment**
host: 1node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

**How To Reproduce**
1. Create a service with the name name-test
2. Create a deployment with the name name-test, Prompt for label repetition when creating

**Expected behavior**
1. If the name of the service and deployment cannot be repeated, then when the name is set, it is checked and prompted to repeat the name
2. If the name of the service and deployment can be repeated, then it should be created successfully here

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority medium

**Comment by leoendless** [comment]
This is not a bug. Labels group has been used, you need to add a new label or modify current labels.

**Comment by liuyp2018** [comment]
when adding a new label or modifying current labels, the error occurres

<img width="828" alt="重复名称2" src="https://user-images.githubusercontent.com/36271543/87532944-77906f00-c6c6-11ea-9853-ff914ee8a1e7.png">
