### ISSUE TITLE
The build mirror list page turning function has not taken effect

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2434]
**Describe the Bug**
The build mirror list page turning function has not taken effect
<img width="942" alt="翻页功能" src="https://user-images.githubusercontent.com/36271543/87528810-a277c480-c6c0-11ea-9ee9-2b207326f67f.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.16.12
member1-v1.18.5
member2-v1.17.8

**Environment**
host: 1node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority medium

**Comment by harrisonliu5** [comment]
has fixed in [#765](https://github.com/kubesphere/console/pull/765)
