### ISSUE TITLE
how to run kubeshere

### ISSUE THREAD

**Issue by zys0505** [kubesphere/kubesphere#2436]
I want to run kubesphere and console locally, and see how kubesphere works locally

**Comment by rayzhou2017** [comment]
https://github.com/kubesphere/community/blob/master/developer-guide/development/development-workflow.md

**Comment by yuswift** [comment]
See the [pr](https://github.com/kubesphere/community/pull/230) for more details.

**Comment by benjaminhuo** [comment]
Question answered, close this issue
