### ISSUE TITLE
删除自定义角色报错

### ISSUE THREAD

**Issue by jerryjedi** [kubesphere/kubesphere#244]
一个用户，其角色为workspace-admin，在一个project中创建了一个角色（无所谓具体权限），在删除改角色时（没有用户关联到该角色），删除成功的同时会有一个报错信息，如下图：
![_20181222103344](https://user-images.githubusercontent.com/7875026/50369760-76c05580-05d5-11e9-973e-d207da730f9f.png)

自己估计时删除后界面没有回退到上层角色列表，而是继续试图展现该被删除角色的信息，所以会有报错。因为界面如下图展现了undefined信息：
![_20181222103455](https://user-images.githubusercontent.com/7875026/50369772-a8392100-05d5-11e9-857b-710aec072745.png)

**Comment by rayzhou2017** [comment]
2.0.0 fixed
