### ISSUE TITLE
Incorrect page display after retrun from secrect in workload under muti-cluster project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2442]
Describe the Bug
Incorrect page display after retrun from secrect in workload under muti-cluster project
Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click workload menu under application load
5.Create workload with Key as Mount disk
6.Find the key from workload and click the link
![image](https://user-images.githubusercontent.com/67785532/87642586-51c5a180-c77c-11ea-8dc5-4bfa57002135.png)

7.Secret page display
![image](https://user-images.githubusercontent.com/67785532/87642658-630eae00-c77c-11ea-8400-57141d9682bf.png)

8.Return by click Secret button
![image](https://user-images.githubusercontent.com/67785532/87642707-7457ba80-c77c-11ea-804b-4ee864b4853b.png)

9.Incorrect page（one clustor project page） display
![image](https://user-images.githubusercontent.com/67785532/87642844-a5d08600-c77c-11ea-9213-e1e2aa7e788e.png)

Expected behavior
Should display the correct page(muti-cluster project page)

/kind bug
/area console
/assign leoendless
/milestone 3.0.0

**Comment by leoendless** [comment]
There is a bug of volume cards on the pods' detail page.

**Comment by wangtian-010** [comment]
verification passed,close this issue
