### ISSUE TITLE
项目的事件展现能否按时间倒序，能否展现更多的内容？

### ISSUE THREAD

**Issue by jerryjedi** [kubesphere/kubesphere#245]
如截图，在观察HPA的过程日志时发现日志展现方式不合理，能否按时间倒序，另外能否展现更长时间内的内容?
![_20181223113921](https://user-images.githubusercontent.com/7875026/50380636-e9016a80-06a7-11e9-9a87-bc962883b28d.png)

**Comment by leoendless** [comment]
目前原生 k8s event api 接口不支持 sort, 可以在前端直接排序, 
@zryfish 看下更多数据的问题吧

**Comment by zryfish** [comment]
更长的时间需要将event事件存储到es里，目前还没有支持，3.0会支持
