### ISSUE TITLE
Bulk deletion is missing from the build image list

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2450]
**Describe the Bug**
Build image list, cannot be bulk deleted
<img width="611" alt="构建镜像" src="https://user-images.githubusercontent.com/36271543/87654976-36fa2980-c78a-11ea-89b3-3fb32a56f7b8.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.16.12
member1-v1.18.5
member2-v1.17.8

**Environment**
host: 1node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area console
/assign @harrisonliu5 
/milestone 3.0.0
/priority medium

**Comment by harrisonliu5** [comment]
[fix: Fix the query in the build mirror list has not taken effect](https://github.com/kubesphere/console/pull/765)

**Comment by liuyp2018** [comment]
close
