### ISSUE TITLE
There is problems with the mirror image search function

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2452]
**Describe the Bug**
There is problems with the mirror image search function, See the replay steps for details.

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.16.12
member1-v1.18.5
member2-v1.17.8

**Environment**
host: 1node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

**How To Reproduce**
1. In the Build image details page, go to the Mirror Artifacts page
![image](https://user-images.githubusercontent.com/36271543/87661073-9a885500-c792-11ea-834b-0ecaf970eb41.png)

Problem 1:
 In the search input box of mirror image, enter some name fields of existing mirror image for query, and the query result is empty
<img width="845" alt="1" src="https://user-images.githubusercontent.com/36271543/87661528-56498480-c793-11ea-9e1d-b6e67ac75f88.png">

Problem 2:
After clearing the query fields, the mirror artifacts that are not part of the build image are also displayed
![image](https://user-images.githubusercontent.com/36271543/87661678-96a90280-c793-11ea-90e3-c74cf7fb9a58.png)

/kind bug
/area console
/assign @harrisonliu5 
/milestone 3.0.0
/priority medium

**Comment by liuyp2018** [comment]
The same problem exists in execution records
<img width="647" alt="problem" src="https://user-images.githubusercontent.com/36271543/87770966-447ae680-c852-11ea-886e-95522aa34124.png">

**Comment by harrisonliu5** [comment]
[GET] kapis/clusters/shire/resources.kubesphere.io/v1alpha2/namespaces/harry-project001/s2iruns?conditions=labels.devops.kubesphere.io%2Fbuilder-name%3D%232&paging=limit%3D10%2Cpage%3D1&orderBy=createTime&reverse=true

this API returns the wrong data
