### ISSUE TITLE
Click 'edit resource default request' does not respond under muti-cluster project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2456]
Describe the Bug
Click Edit resource default request does not respond under muti-cluster project
Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click project setting menu under 'configer center'
5.Click 'basic info' and then 'project management'
6.Click 'Edit resource default request'
7.No page pop up
![image](https://user-images.githubusercontent.com/67785532/87746380-04503f80-c823-11ea-9410-a7b0edfd2774.png)

Expected behavior
Should display "容器资源默认请求" page

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.0.0

**Comment by leoendless** [comment]
We fixed this problem yesterday, you might need to update the console.

**Comment by wangtian-010** [comment]
verification passed ,close this issue
![image](https://user-images.githubusercontent.com/67785532/87917770-0b3bb400-caa8-11ea-862e-f11c5481679f.png)
