### ISSUE TITLE
Always deleting status when delete project under muti-cluster project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2457]
Describe the Bug
Always deleting status when delete project under muti-cluster project
Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click project setting menu under 'configer center'
5.Click 'basic info' and then 'project management'
6.Click 'Delete project'
7.Always deleting status
![image](https://user-images.githubusercontent.com/67785532/87746612-96f0de80-c823-11ea-9e11-1f736f2d9989.png)

Expected behavior
Should be deleted successfully

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.0.0

**Comment by leoendless** [comment]
Could you merge the `deleting status` issues into one? They should be caused by the same reason.

**Comment by wangtian-010** [comment]
merge these deleting status issues into one and close this issue
