### ISSUE TITLE
Failed to download the product successfully

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2472]
**Describe the Bug**
Failed to download the product successfully
<img width="749" alt="下载制品" src="https://user-images.githubusercontent.com/36271543/87773686-139cb080-c856-11ea-9838-f646222aa41b.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.16.12
member1-v1.18.5
member2-v1.17.8

**Environment**
host: 1node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area console
/assign @harrisonliu5
/milestone 3.0.0
/priority medium

**Comment by harrisonliu5** [comment]
the download link is right?

[GET] b2i_download/kapis/devops.kubesphere.io/v1alpha2/namespaces/harry-project001/s2ibinaries/b2i-war-java8-warpqfo/file/b2i-war-java8.war

**Comment by shaowenchen** [comment]
In a multi-cluster environment, cluster parameters need to be added to download URL.
