### ISSUE TITLE
Create batch users status issue

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2476]
When I create lots of users such as 1000 at a time, I found it takes a long time for the status of users changed from waiting to active. I guess it might be the algorithm problem at the backend.

<img width="1280" alt="Screen Shot 2020-07-18 at 7 55 45 AM" src="https://user-images.githubusercontent.com/28859385/87839257-9c563380-c8cc-11ea-88c6-b12eb112a722.png">

**Comment by rayzhou2017** [comment]
Also the real time cpu load seems a little high, my machine is 4c8g.

<img width="1011" alt="Screen Shot 2020-07-18 at 8 35 16 AM" src="https://user-images.githubusercontent.com/28859385/87840365-ec83c480-c8d1-11ea-8d36-cd76c85167af.png">

**Comment by rayzhou2017** [comment]
CPU load around 2 seems reasonable. It is concurrent issue which we should test. Another issue I am concerned is the memory consumption. It is about 100k per user. Can we reduce it to about 10k per user?

**Comment by rayzhou2017** [comment]
So the status from waiting to active is actually on encrypting, am I right?

**Comment by wansir** [comment]
> So the status from waiting to active is actually on encrypting, am I right?

You're right.

**Comment by rayzhou2017** [comment]
The memory consumption seems less and less with the number of users increasing. I am not sure what logic behind it. Is it using something like LRU? Now it takes around 1.5G for 50,000 users. I think it is OK.
