### ISSUE TITLE
user password shows in plain text

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2477]
It is not safe to show plain text of password.
<img width="448" alt="Screen Shot 2020-07-18 at 9 03 16 AM" src="https://user-images.githubusercontent.com/28859385/87841119-a3ce0a80-c8d5-11ea-971c-7f64a9f34fa5.png">

**Comment by wansir** [comment]
Password will be encrypted if ks-controller-manager is running, cpu high load is due to the encryption algorithm.

**Comment by rayzhou2017** [comment]
You are right. It seems taking long time to get encrypted.
<img width="538" alt="Screen Shot 2020-07-18 at 12 28 31 PM" src="https://user-images.githubusercontent.com/28859385/87844691-45fbeb80-c8f2-11ea-9c7f-75364b1f842e.png">
