### ISSUE TITLE
self provisioner can't see the project menu

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2481]
**Describe the Bug**
`ws-self-provisioner` is the self provisioner of the workspace, but can't see the menu to provision a project.
<img width="1238" alt="Screen Shot 2020-07-19 at 7 19 06 PM" src="https://user-images.githubusercontent.com/28859385/87873564-35806980-c9f5-11ea-8ab7-eb7e241e3116.png">
<img width="1100" alt="Screen Shot 2020-07-19 at 7 20 37 PM" src="https://user-images.githubusercontent.com/28859385/87873565-3c0ee100-c9f5-11ea-9047-de32780e7aa2.png">

**Versions Used**
KubeSphere: 3.0.0-dev
Kubernetes: 1.15.12

**Expected behavior**
The `Projece` should show in the left navigation menu and allow self-provisioner to create a project.

**Comment by wansir** [comment]
@leoendless  I've deleted the wrong policy rules. https://github.com/kubesphere/kubesphere/issues/2397#issuecomment-657004707

**Comment by wansir** [comment]
Some API needs to be added to fit the federated project, we will fix it today.

**Comment by rayzhou2017** [comment]
verified
