### ISSUE TITLE
write user authority to devops

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#2483]
**General remarks**

Write permissions to Jenkins.

About link https://github.com/kubesphere/kubesphere/pull/2392

**Versions Used**

KubeSphere: 3.0.0

/area iam
/assign @wansir

**Comment by rayzhou2017** [comment]
what is this issue for in details?

**Comment by shaowenchen** [comment]
write all users to DevOps admin. We need to solve the approval problem in 3.1.0

/milestone 3.1.0

/remove-kind need-to-verify
