### ISSUE TITLE
In the project overview, the resource monitoring data is 0

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2488]
**Describe the Bug**
In the project overview, the resource monitoring data in the application resource and physical Resource diagram is 0

<img width="648" alt="监控" src="https://user-images.githubusercontent.com/36271543/87909607-2227d980-ca9b-11ea-8009-96fff921cff4.png">
<img width="685" alt="物理资源监控" src="https://user-images.githubusercontent.com/36271543/87909616-26ec8d80-ca9b-11ea-83c1-4769b1771cb3.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.18.5
member1-v1.17.8

**Environment**
host: 3node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area monitoring
/assign @huanggze 
/milestone 3.0.0
/priority medium

**Comment by huanggze** [comment]
There may be a deplay. Plz wait for a minute if you just deploy a workload.

/kind need-to-verify
