### ISSUE TITLE
版本和回退

### ISSUE THREAD

**Issue by jerryjedi** [kubesphere/kubesphere#249]
在定义部署后，可以通过【编辑配置模板】进行修改，并且可以有新的版本，从而可以版本回退，但如果通过【编辑配置文件】修改则好像没有版本显示，也没有版本回退。这个是work on design还是可以增强使【编辑配置文件】也支持版本和回退？

**Comment by jerryjedi** [comment]
这个为何是对的？能否保留配置文件多版本以提供回退？

**Comment by zryfish** [comment]
配置文件是保留着的，在deployment的版本列表那里可以执行回滚
