### ISSUE TITLE
When uploading the binary, the files in all formats are displayed without filtering

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2492]
**Describe the Bug**
When uploading the binary, the files in all formats are displayed without filtering
<img width="719" alt="binary" src="https://user-images.githubusercontent.com/36271543/87915537-e265ef80-caa4-11ea-9211-9bc66b92081b.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.18.5
member1-v1.17.8

**Environment**
host: 3node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area console
/assign @leoendless 
/milestone 3.0.0
/priority medium

**Comment by leoendless** [comment]
The front end does not have a suitable method to identify binary files. Every file could be read as binary.

**Comment by harrisonliu5** [comment]
the binary files do not require file filtering
