### ISSUE TITLE
enable snapshot failed

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2494]
**Describe the Bug**
Using https://github.com/kubesphere/helm-charts/tree/master/src/test/csi-qingcloud#installing to install qingcloud csi, and can create a pvc. When I go to storage class and try to enable the snapshot capability. It failed.
<img width="1221" alt="Screen Shot 2020-07-20 at 4 21 12 PM" src="https://user-images.githubusercontent.com/28859385/87915848-3d97e200-caa5-11ea-9d2c-1a8715f39249.png">

**Versions Used**
KubeSphere: 3.0.0-dev
Kubernetes: 1.15.12

**Environment**
allinone

**Expected behavior**
Be able to enable the snapshot capability

**Comment by leoendless** [comment]
This function should be removed.

**Comment by rayzhou2017** [comment]
< K8s 1.17 does not support snapshot, but the error msg needs to be nicer

**Comment by rayzhou2017** [comment]
> This function should be removed.

It is also OK. However, it must show if the csi supports snapshot.

**Comment by leoendless** [comment]
Yes, it's detected by backend service, and the property is display in the list.

**Comment by rayzhou2017** [comment]
verified
