### ISSUE TITLE
Master the migration

### ISSUE THREAD

**Issue by 53537** [kubesphere/kubesphere#2497]
Hello, is there a master migration scheme for K8S +Kubesphere? Is it recommended for migration

**Comment by Forest-L** [comment]
Migration is not recommended, but backup and restoration can be done. Based on Velero technology, we have validated the K8s+KubeSphere backup and restore scheme.

**Comment by Forest-L** [comment]
If you are interested or have a need, discuss it separately.

**Comment by 53537** [comment]
I have seen the scheme of Velero on the forum. I think it is not a better plan. Is there any other scheme, such as installing master and then initializing it

**Comment by Forest-L** [comment]
Such as installing master and then initializing it？ Can you describe it more clearly.

**Comment by 53537** [comment]
For example, install a new master node, then initialize it and join the cluster

**Comment by Forest-L** [comment]
This is also possible now, but notice the number of Etcds and the lb associated with them.

**Comment by umialpha** [comment]
@Forest-L hi，is there any docs about migration?  we want to migrate our host cluster.
