### ISSUE TITLE
在web管理控制台创建configmap成功后不显示，需要手工刷新

### ISSUE THREAD

**Issue by blueftss** [kubesphere/kubesphere#250]
![configmap bug](https://user-images.githubusercontent.com/11399484/50408991-f8102600-0829-11e9-9f3c-5de9dcda0079.png)

**Comment by calvinyv** [comment]
@leoendless 类似的地方还有workload创建

**Comment by leoendless** [comment]
这个主要原因是 api server 的同步问题, 将会在下一版本修复
