### ISSUE TITLE
No container display after Statful service created under muti-cluster project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2501]
Describe the Bug
No container display after Statful service created under muti-cluster project
Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click application menu under application load
5.Create one statful service correctly
6.No container display for this statful service
![image](https://user-images.githubusercontent.com/67785532/87928476-79d43e00-cab7-11ea-84d6-5da5f5a0cbec.png)

Expected behavior
Should display correct container

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.0.0

**Comment by zryfish** [comment]
Cannot reproduce using the latest build, can you verify it again?
/cc @wangtian-010

**Comment by wangtian-010** [comment]
verification passed,close this isuue
