### ISSUE TITLE
Select binary to create service. Operation failed

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2502]
**Describe the Bug**
Select binary to create service. Operation failed
note:The binary artifact file is the sample file in KS2.1

<img width="588" alt="111" src="https://user-images.githubusercontent.com/36271543/87928920-329a7d00-cab8-11ea-9419-c09c5be20d14.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.18.5
member1-v1.17.8

**Environment**
host: 3node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area devops
/assign @shaowenchen 
/milestone 3.0.0
/priority high

**Comment by shaowenchen** [comment]
S2ibulder Pod get the file using http://ks-apiserver.kubesphere-system.svc/kapis/devops.kubesphere.io/v1alpha2/namespaces/asd/s2ibinaries/b2i-war-java8-war0hg8/file/b2i-war-java8.war，but return 403.

need to discuss a solution @wansir

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/87940288-f40ebd80-cacb-11ea-8b86-1af33e661ab9.png)

**Comment by wansir** [comment]
Need to add `Authorization Header` to S2ibulder, we plan to provide a token similar to serviceaccount for authentication.
