### ISSUE TITLE
CPU and mem do not use the default value from 'Resource default request' under muti-cluster project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2504]
Describe the Bug
CPU and mem do not use the default value from 'Resource default request' under muti-cluster project
Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click 'project setting' under application load
5.Set 'Resource default request' as below
![image](https://user-images.githubusercontent.com/67785532/87941632-00941580-cace-11ea-94c9-e031994e098c.png)
6.Create one workload and CPU and mem of image do not use the default value from 'Resource default request'
![image](https://user-images.githubusercontent.com/67785532/87941646-0689f680-cace-11ea-9b3a-b8a7e458b9d8.png)

Expected behavior
Should display default resource request

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.0.0

**Comment by leoendless** [comment]
@zryfish The federated limitrange didn't work.

**Comment by zryfish** [comment]
multicluster installation failed, please verify again using the latest build

**Comment by wangtian-010** [comment]
verification passed,close this issue
