### ISSUE TITLE
title of the resource should be changed to 'resource name&type' on event and audit query panel

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#2507]
**Describe the Bug**
tile of the resource should be changed to 'resource name&type' on event and audit query panel

**Versions Used**
KubeSphere: 3.0 alpha 1

**How To Reproduce**
1. Go to 'toolbox'
2. Click on 'event search' or 'audit operation'
3. title of the resource should be changed to 'resource name&type' on event and audit query panel
资源 -> 资源名称和类型

<img width="1001" alt="Xnip2020-07-21_10-19-10" src="https://user-images.githubusercontent.com/28883416/88005310-adf14280-cb3b-11ea-895d-b65083e0e8b6.png">

**Comment by leoendless** [comment]
@benjaminhuo Could you help to check this problem?

**Comment by benjaminhuo** [comment]
@leoendless we've discussed this in slack, and pls move on to change accordingly for both event and audit search.
Thanks
Ben
