### ISSUE TITLE
如何源码编译到其他平台？

### ISSUE THREAD

**Issue by liupeng0518** [kubesphere/kubesphere#251]
可以编译到arm mips平台么？

**Comment by calvinyv** [comment]
目前还不支持，arm64在明年下半年的roadmap里

**Comment by liupeng0518** [comment]
> 目前还不支持，arm64在明年下半年的roadmap里

奥感谢，那mips也不支持了？目前只支持x86/64的么？

**Comment by calvinyv** [comment]
是的，2018年只支持 x86/64，明年会做平台扩展
