### ISSUE TITLE
Only one cluster's the probe info  full displays  under muti-cluster project

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2512]
Describe the Bug
Only one cluster's the probe info  full displays  under muti-cluster project
Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management' and switch to 'multi-cluster project' tab
4.Click 'muticlustor-project' and then click 'workload' under 'application workload '
5.Create workload and set three probes
6.Only one cluster's the probe info display correctly
First cluster
![image](https://user-images.githubusercontent.com/67785532/88018445-4e565f80-cb5a-11ea-8af2-2f1c771bbee2.png)
Second cluster
![image](https://user-images.githubusercontent.com/67785532/88018469-5dd5a880-cb5a-11ea-8d61-0bc44a573616.png)

Expected behavior
the probe info for all cluster's should  display correctly

/kind bug
/area console
/assign leoendless
/milestone 3.0.0

**Comment by leoendless** [comment]
You need to enable the `StartupProbe` in the second cluster.

https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/.

**Comment by wangtian-010** [comment]
verification passed,close this issue
