### ISSUE TITLE
Status of task is not automatically updated in the task detail page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2515]
**Describe the Bug**
in the task detail page, click rerun button
the status of the rerun task is always running, even though the state is actually complete
After a manual refresh, the state changes
<img width="793" alt="status" src="https://user-images.githubusercontent.com/36271543/88021348-e73ba980-cb5f-11ea-8663-757579813f3a.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.18.5
member1-v1.17.8

**Environment**
host: 3node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority medium

**Comment by leoendless** [comment]
Need to refresh manually.
