### ISSUE TITLE
KS dockers time zone

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2516]
**Describe the Bug**
The time zone of images are incorrect which affects the timestamp of logs, causing debug problem. Please follow https://github.com/kubesphere/ks-installer/blob/e552bfbe5e45c29c256e6315110426ced8ad0f9b/deploy/kubesphere-installer.yaml#L233 to fix them including ks-apiserver, ks-controller-manager, ks-console and etc. Currently installer is already fixed as shown below.
![Screen Shot 2020-07-21 at 2 49 36 PM](https://user-images.githubusercontent.com/28859385/88022178-61206280-cb61-11ea-870b-ca2c73effdb3.png)

**Versions Used**
KubeSphere: 3.0.0-dev

**Expected behavior**
The timestamp of logs are line with the local time zone.

**Comment by benjaminhuo** [comment]
@wanjunlei would you help to fix timezone issue for ks-apiserver, ks-controller-manager.
@zryfish is there any other backend component left?

**Comment by rayzhou2017** [comment]
ks-apiserver, ks-console are already fixed. ks-controller-manager must use root right now to access storage.

**Comment by rayzhou2017** [comment]
Sorry, I made a mistake with the root issue. For timezone issue, ks-installer may be the only one fixed.

**Comment by wanjunlei** [comment]
It had fixed in pr kubesphere/ks-installer#915

**Comment by benjaminhuo** [comment]
kubectl has timezone issue? Is there an issue number?

**Comment by rayzhou2017** [comment]
<img width="1243" alt="Screen Shot 2020-07-25 at 12 22 35 PM" src="https://user-images.githubusercontent.com/28859385/88448556-ad291b00-ce71-11ea-822d-c2a7d9c83810.png">

**Comment by wanjunlei** [comment]
It will be fixed in #2613

**Comment by rayzhou2017** [comment]
verified
