### ISSUE TITLE
部署列表无法加载，在一直在 loading

### ISSUE THREAD

**Issue by fireball2018** [kubesphere/kubesphere#252]
<img width="1400" alt="sp01" src="https://user-images.githubusercontent.com/74476/50466470-c12c4280-09d8-11e9-9a77-b6947fe54772.png">
效果如图，一直在显示loading画面，在浏览器控制台查看，这个接口一直在加载中: `/apis/kubesphere.io/v1alpha1/resources/deployments?conditions=namespace%3Dwahaha-testing&paging=limit%3D10%2Cpage%3D1 `

查看 ks-apigateway 日志显示请求是成功的：
<img width="1217" alt="log" src="https://user-images.githubusercontent.com/74476/50466546-15372700-09d9-11e9-9005-30d5e1b9cc57.png">

**Comment by zryfish** [comment]
能否提供下环境信息，操作系统版本，部署模式(从节点和主节点个数)，主机配置?

**Comment by dogearcn** [comment]
找到原因了，当 env的 value 值超过64个字符，会自动格式化成 `>-`换行的格式就会造成无法部署，通过kubectl 命令部署后网页无法加载列表

<img width="739" alt="wx20181228-001812 2x" src="https://user-images.githubusercontent.com/74476/50486731-39752100-0a36-11e9-911f-d60861df595e.png">

**Comment by rayzhou2017** [comment]
那这个需要前端fix吧？

**Comment by leoendless** [comment]
@dogearcn "会自动格式化成 >-换行的格式就会造成无法部署" 这个应该不是问题, 属于正常的 yaml 语法

可以贴一下 无法部署的具体报错吗

**Comment by dogearcn** [comment]
@leoendless 报错信息是空的

**Comment by dogearcn** [comment]
[api.yaml.txt](https://github.com/kubesphere/kubesphere/files/2717006/api.yaml.txt)

**Comment by leoendless** [comment]
@dogearcn 你提供的测试文件里的 namespace 与你访问的 namespace 不一致, 尝试更改 namespace 试试

**Comment by dogearcn** [comment]
@dogearcn 和 namespace 无关, namespace 是我手动修改过，因为敏感信息

**Comment by leoendless** [comment]
可以提供下你当前的环境信息吗(installer 版本),
目前根据你提供的文件, 在我们的测试环境里没有发现对于问题
