### ISSUE TITLE
After deleting all the data on the second page of the app routing, the list shows 0 data

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2521]
**Describe the Bug**
Go to page 2 of the application routing list and delete all data on page 2
problem: The first page data is not shown
<img width="951" alt="delete" src="https://user-images.githubusercontent.com/36271543/88035613-00028a00-cb75-11ea-8985-e3e01984c57a.png">

<img width="790" alt="delete1" src="https://user-images.githubusercontent.com/36271543/88035617-03961100-cb75-11ea-808a-93dbbf49cb08.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.18.5
member1-v1.17.8

**Environment**
host: 3node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority medium

**Comment by liuyp2018** [comment]
After the second page of data, it is recommended to display the first page of data directly
The same problem exists with other lists, such as application lists, pipeline list, storage lists

![image](https://user-images.githubusercontent.com/36271543/90373822-1da80e00-e0a5-11ea-8ede-70971c1dfbcd.png)

/remove-kind need-to-verify

**Comment by leoendless** [comment]
> After the second page of data, it is recommended to display the first page of data directly
> The same problem exists with other lists, such as application lists, pipeline list, storage lists
> 
> ![image](https://user-images.githubusercontent.com/36271543/90373822-1da80e00-e0a5-11ea-8ede-70971c1dfbcd.png)
> 
> /remove-kind need-to-verify

Please create a new issue for this one.

**Comment by leoendless** [comment]
``The first page data is not shown`` should have been fixed.
