### ISSUE TITLE
Error in edit permission in project role of one-cluster project under muti-cluster-ws

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2529]
Describe the Bug
Error in edit permission in project role of one-cluster project under muti-cluster-ws
Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management'
4.Click 'one-cluster-project' and then click 'project role' under 'project setting '
5.Create one role and then edit  alias and description
6.Edit permission and Error happened

![image](https://user-images.githubusercontent.com/67785532/88136631-3e9f4f80-cc1c-11ea-8225-71c283dd6a8c.png)

Expected behavior
Should be edited correctly

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.0.0

**Comment by wansir** [comment]
Before saving, the object has been modified, conflict is expected. It should not be an internal server error. I will change the status code.
