### ISSUE TITLE
Recently login status is incorrect under access control

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2531]
Describe the Bug
Recently login status is incorrect under access control

Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'Account management' 
3.Recently login status is incorrect
![image](https://user-images.githubusercontent.com/67785532/88137323-e49f8980-cc1d-11ea-96ab-529f88735f38.png)

By the way,login time is incorrect in below page
![image](https://user-images.githubusercontent.com/67785532/88160356-1b3acb80-cc41-11ea-8870-97c1ccb47fd9.png)
 

Expected behavior
Should be ‘已登录’

/kind bug
/area iam
/assign @zryfish
/milestone 3.0.0

**Comment by rayzhou2017** [comment]
duplicate https://github.com/kubesphere/console/issues/495
