### ISSUE TITLE
user with role that no any permission can operate resource in one cluster project under muti-clustor namespace

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2534]
Describe the Bug
user with role that no any permission can operate resource in one cluster project under muti-clustor namespace
Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management'
4.Click 'one-cluster-project' and then click 'project role' under 'project setting '
5.Create one role and don't select any permission
![image](https://user-images.githubusercontent.com/67785532/88146624-b1192b00-cc2e-11ea-8d0c-bf7a4fabab4f.png)

6.Assign this role to user wangtian@yunify.com
7.Login with wangtian@yunify and can operate any resource
![image](https://user-images.githubusercontent.com/67785532/88146725-d27a1700-cc2e-11ea-9bb2-7cffeb2a0b2b.png)

Expected behavior
Should have no any permission

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.0.0

**Comment by wansir** [comment]
`workspaces-manager` is able to manage the project. But the project viewer authorization list should not be empty.
/assign @leoendless

**Comment by wangtian-010** [comment]
verification failed,still can operate

**Comment by wansir** [comment]
> verification failed,still can operate

What are the user's platform role and workspace role?

**Comment by wangtian-010** [comment]
verification passed,close this issue
