### ISSUE TITLE
stor volume/Alarm strategy permission is incorrect in one cluster project under muti-clustor namespace

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2535]
Describe the Bug
stor volume/Alarm strategy permission is incorrect in one cluster project under muti-clustor namespace
Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management'
4.Click 'one-cluster-project' and then click 'project role' under 'project setting '
5.Create one role and set stor volume and Alarm strategy are viewer permission
![image](https://user-images.githubusercontent.com/67785532/88147985-8c25b780-cc30-11ea-84c7-a9260b0f1f93.png)
![image](https://user-images.githubusercontent.com/67785532/88148366-1110d100-cc31-11ea-81da-5e6aa3f53267.png)
6.Assign this role to user wangtian@yunify.com
7.Login with wangtian@yunify and can operate stor volume and Alarm strategy
![image](https://user-images.githubusercontent.com/67785532/88148023-98aa1000-cc30-11ea-814d-897579a952bb.png)
![image](https://user-images.githubusercontent.com/67785532/88148407-2128b080-cc31-11ea-8ab7-cca0b18dac54.png)

Expected behavior
Can not operate stor volume and Alarm strategy

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.0.0

**Comment by wansir** [comment]
It's as expected, wangtian's platform role is `workspaces-manager`.

**Comment by wangtian-010** [comment]
Now it works as expected,close this issue

**Comment by wangtian-010** [comment]
why application workload can not operate,only stor volume/Alarm strategy can edit?

**Comment by wansir** [comment]
/assign @leoendless 
![image](https://user-images.githubusercontent.com/8263040/88246624-95189680-cccd-11ea-905e-24c873bceb77.png)

**Comment by wangtian-010** [comment]
verification failed,reopen it
![image](https://user-images.githubusercontent.com/67785532/88445148-6b897780-ce53-11ea-9d02-aea715eba5ab.png)

/kind reopen

**Comment by wangtian-010** [comment]
verification failed,
![image](https://user-images.githubusercontent.com/67785532/88679175-c22bd580-d121-11ea-8b78-84f99ad92e46.png)
![image](https://user-images.githubusercontent.com/67785532/88679205-ca841080-d121-11ea-92f3-ebd8564ebfd8.png)

![image](https://user-images.githubusercontent.com/67785532/88679251-d4a60f00-d121-11ea-9d46-a3838727d928.png)
![image](https://user-images.githubusercontent.com/67785532/88679290-dcfe4a00-d121-11ea-906a-6ee939fffe1a.png)

**Comment by wangtian-010** [comment]
Verification passed,close this issue
