### ISSUE TITLE
Lack of configuration, custom monitoring, grayscale publishing and build image permission settings in one cluster project under muti-clustor namespace

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2536]
Describe the Bug
Lack of configuration, custom monitoring, grayscale publishing and build image permission settings in one cluster project under muti-clustor namespace
Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Click on 'multi-cluster-ws' namespace
3.Click 'project management'
4.Click 'one-cluster-project' and then click 'project role' under 'project setting '
5.Create one role and select permission
6.Lack of configuration, custom monitoring, grayscale publishing and build image permission settings
![image](https://user-images.githubusercontent.com/67785532/88149530-ca23db00-cc32-11ea-913b-7533a2dacbc9.png)
![image](https://user-images.githubusercontent.com/67785532/88149582-db6ce780-cc32-11ea-94dc-e5f99b83ec57.png)
![image](https://user-images.githubusercontent.com/67785532/88149608-e58ee600-cc32-11ea-9b04-cc3eb41f21a8.png)

Expected behavior
advise add these permissions

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.0.0

**Comment by wansir** [comment]
duplicate https://github.com/kubesphere/kubesphere/issues/2717

/close
