### ISSUE TITLE
when enable log on disk , cannot see the logsidecar

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/kubesphere#2537]
![image](https://user-images.githubusercontent.com/20178386/88150663-436ffd80-cc34-11ea-9efc-ccc8cf76f1ac.png)

![image](https://user-images.githubusercontent.com/20178386/88151062-c8f3ad80-cc34-11ea-8085-36b86c0feb5b.png)

already enable log sidecar, but cannot see the sidcar in  deploy 

/kind bug
/area multicluster

**Comment by benjaminhuo** [comment]
@junotx pls help to take a look at this issue.
Looks like it's a usage problem

**Comment by junotx** [comment]
It was a usage problem. @zackzhangkai if there is no problem, you can close this issue

**Comment by benjaminhuo** [comment]
@junotx would you tell @zackzhangkai how to setup logging sidecar?

**Comment by junotx** [comment]
@zackzhangkai you can refer [logs-on-disk part in kubesphere doc](https://kubesphere.com.cn/docs/zh-CN/workload/logs-on-disk/) to configure log sidecar on console ui. If you switch to yaml edit mode, you can find help from [kubesphere/logsidecar-injector doc](https://github.com/kubesphere/logsidecar-injector).  At afternoon you have resolved the problem based on the documentation and configuration issues I mentioned.  If there are no other problems on using it, you can close this issue
