### ISSUE TITLE
custom project role no permission error

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2547]
**Describe the Bug**
Customize a project role without project setting access as below. Loggin using the user and throws error
![Screen Shot 2020-07-23 at 10 31 33 AM](https://user-images.githubusercontent.com/28859385/88247296-d4e07d80-cccf-11ea-986b-0a635b95b94d.png)
![Screen Shot 2020-07-23 at 10 29 29 AM](https://user-images.githubusercontent.com/28859385/88247305-da3dc800-cccf-11ea-92c5-891edfa0a442.png)

**Versions Used**
KubeSphere: 3.0.0-dev
Kubernetes: 1.15.12

**Environment**
allinone, minimal installation

**Expected behavior**
Project setting should not appear for the custom project role

**Comment by rayzhou2017** [comment]
Not fixed yet. Here is the error (two places: 1. the custom role page shows undefined. 2. the custom role user got a different error msg this time)
<img width="916" alt="Screen Shot 2020-07-25 at 9 20 39 AM" src="https://user-images.githubusercontent.com/28859385/88445901-61b64300-ce58-11ea-8a47-24331948d3c7.png">
<img width="1280" alt="Screen Shot 2020-07-25 at 9 21 12 AM" src="https://user-images.githubusercontent.com/28859385/88445907-6aa71480-ce58-11ea-9dd1-4773d765379d.png">

**Comment by rayzhou2017** [comment]
This issue may have more problems. I click each menu in the project and got error every time. Here is the user roles
<img width="1120" alt="Screen Shot 2020-07-25 at 9 26 09 AM" src="https://user-images.githubusercontent.com/28859385/88445996-20726300-ce59-11ea-93a1-a03a5095aca0.png">
<img width="1180" alt="Screen Shot 2020-07-25 at 9 26 31 AM" src="https://user-images.githubusercontent.com/28859385/88445998-27997100-ce59-11ea-8923-bf100f08c222.png">

**Comment by wansir** [comment]
update ks-apisetver to the latest version, create a new role or update `test-role1` to verify.

**Comment by rayzhou2017** [comment]
verified, but have other problem. I am going to create new issues
