### ISSUE TITLE
Project number is incorrect

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2548]
**Describe the Bug**
A user with custom project role is invited into only one project. But it shows the total number of the workspace in the overview page.
![Screen Shot 2020-07-23 at 10 35 15 AM](https://user-images.githubusercontent.com/28859385/88247480-6cde6700-ccd0-11ea-9f37-fa696530569b.png)
![Screen Shot 2020-07-23 at 10 35 23 AM](https://user-images.githubusercontent.com/28859385/88247486-723bb180-ccd0-11ea-8b1b-da089cb1f868.png)

**Versions Used**
KubeSphere: 3.0.0-dev
Kubernetes: 1.15.12

**Environment**
allinone, minimal installation

**Expected behavior**
Should only show the number of projects that the user is invited(able to access).

**Comment by leoendless** [comment]
@huanggze Please fixed the api.

**Comment by huanggze** [comment]
Permission to workspace overvew should be well handled.

**Comment by leoendless** [comment]
Now, only users who can view all the workspace's projects could view the workspace overview page.

**Comment by rayzhou2017** [comment]
verified
