### ISSUE TITLE
新建任务后，刷新时间太长

### ISSUE THREAD

**Issue by shizgchina** [kubesphere/kubesphere#255]
新建 job，配置完成后，前端没有展示新建的记录，要等大概 7-10 秒后才能看到。

![image](https://user-images.githubusercontent.com/41432506/50505535-281c2b00-0aaf-11e9-8f33-af232d4eb494.png)

Job 失败的话，显示的结束时间不正确。
![image](https://user-images.githubusercontent.com/41432506/50505555-4d109e00-0aaf-11e9-8a92-2c38b8dc509a.png)

**Comment by leoendless** [comment]
这两个问题会在1.0.1 修复
