### ISSUE TITLE
should we allow ingress traffic from the kubesphere-monitoring-system default

### ISSUE THREAD

**Issue by duanjiong** [kubesphere/kubesphere#2550]
By default we only allow traffic from the same workspace or project, but if user enable custom monitoring, then p8s will not be able to access the monitored data, should we allow it by default or let user add it by themselves?

I think not everyone will use custom monitoring, should let users add their own rules

**Comment by benjaminhuo** [comment]
kubesphere-monitoring-system is our own ns, it should be allowed to access other ns by default for custom monitoring. 
Adding a manual step is a bit inconvenient for users because there already are some manual steps to do custom monitoring.
@huanggze

**Comment by zheng1** [comment]
I think it makes sense to allow `kubesphere-monitoring-system` by default. If the user needs to deny it, it should also be configured in the configuration file.
