### ISSUE TITLE
self-provisioner got error msg when enter fed project

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2557]
**Describe the Bug**
A self provisioner goes into the fed project created by him/her, got error msg. I checked, there are two pages having problem, overview and quota management under project setting.
![Screen Shot 2020-07-23 at 3 25 40 PM](https://user-images.githubusercontent.com/28859385/88261497-0588dd00-ccf9-11ea-834a-87e4eae62b1b.png)

**Versions Used**
KubeSphere: 3.0.0-dev
Kubernetes: 1.15.12(host), 1.18.6(member)

**Environment**
allinone, minimal, one host with one member

**Comment by benjaminhuo** [comment]
@huanggze would you help hongming to fix this security & role issue ?

**Comment by rayzhou2017** [comment]
verified
