### ISSUE TITLE
示例五 - 设置弹性伸缩，第四步：标签设置，点击 创建 后，提示 Forbidden

### ISSUE THREAD

**Issue by shizgchina** [kubesphere/kubesphere#256]
第四步：标签设置
标签是一个或多个关联到资源如容器组上的键值对，通过标签来识别、组织或查找资源对象，此处标签设置为 app : nginx-hpa。

节点选择器无需设置，kube-scheduler 将根据各主机 (Node) 的负载状态，将 Pod 随机调度到各台主机上。点击 创建，即可查看 Nginx 的运行状态详情。

结果界面显示如下：
![image](https://user-images.githubusercontent.com/41432506/50532325-c8775b80-0b52-11e9-928b-3027cc4fd8f4.png)

而实际上这个 deployment 被正常创建了。
![image](https://user-images.githubusercontent.com/41432506/50532339-ed6bce80-0b52-11e9-9faf-dd214ea8c04a.png)

**Comment by wansir** [comment]
1. 2.1.0 不再允许直接选择节点，禁用了 普通用户 list nodes 的权限
2. 依旧可以通过label selector的方式限制调度，在用户引导层面上不再推荐这么做
