### ISSUE TITLE
Some Description is not showing completely including language

### ISSUE THREAD

**Issue by WaysonWei** [kubesphere/kubesphere#2560]
"Automatically created by kubesphere, we encourage you to use host cluster for ..."

This notice should automatic wrap into lines, not able to read it completely.Also, missing the chinese version as well. 

![Screen Shot 2020-07-23 at 7 51 21 PM](https://user-images.githubusercontent.com/54336863/88263662-80b0ba00-cd1e-11ea-8df7-472c23cacdc1.png)
![Screen Shot 2020-07-23 at 7 51 07 PM](https://user-images.githubusercontent.com/54336863/88263668-83abaa80-cd1e-11ea-87cf-540441853759.png)
<img width="1504" alt="Screen Shot 2020-07-23 at 7 48 28 PM" src="https://user-images.githubusercontent.com/54336863/88263672-84dcd780-cd1e-11ea-9294-f320785b68d0.png">

**Comment by zryfish** [comment]
Yeah, that's self crated host cluster by KubeSphere itself, it's cluster description, user can change it by themselves.
