### ISSUE TITLE
Always 'Not logged in yet' even for a login user

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#2561]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**General remarks**

> Please delete this section including header before submitting
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the Bug**
Always 'Not logged in yet' even for a login user

**Versions Used**
KubeSphere: 3.0 alpha 1

**How To Reproduce**
1. Create a user and use it to log in
2. Login as admin and go to account list
3. See 'Not logged in yet' for this user

**Comment by rayzhou2017** [comment]
duplicate https://github.com/kubesphere/console/issues/495
