### ISSUE TITLE
No suggested password hint is pop up when creating second user

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#2562]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**General remarks**

> Please delete this section including header before submitting
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the Bug**
No suggested password hint is pop up when creating second user

**Versions Used**
KubeSphere: 3.0 Alpha 1

**How To Reproduce**
1. Create a user, and choose the suggested generated password by KubeSphere console
2. Then create another user, that suggested password popup panel is missing

**Comment by rayzhou2017** [comment]
Isn't it the browser capability?

**Comment by calvinyv** [comment]
yeah, u r correct.
