### ISSUE TITLE
删除 deployment 后，再次创建，提示错误

### ISSUE THREAD

**Issue by shizgchina** [kubesphere/kubesphere#257]
明明已经删除了 deployment ，界面中也没有了，但是新建同名的 deployment 时收到错误提示，而且其实已经创建成功了 。

![image](https://user-images.githubusercontent.com/41432506/50533310-12b40900-0b62-11e9-9636-62c3709aa63f.png)

**Comment by rayzhou2017** [comment]
这个是不是也是同步的问题？

**Comment by jerryjedi** [comment]
你的安装是All-in-one还是多节点？如果等几分钟才操作是否还是遇到同样问题？我删除过多次好像都没有遇到问题。
