### ISSUE TITLE
Helm repo can not be added

### ISSUE THREAD

**Issue by WaysonWei** [kubesphere/kubesphere#2573]
Try to add bitnami helm repo, validate is ok, but not added. If try it again, show error with conflict repo name, even it only have kubesphere default helm repo available. 

![Screen Shot 2020-07-24 at 10 11 57 AM](https://user-images.githubusercontent.com/54336863/88343951-b3969480-cd96-11ea-8768-3b93d168e077.png)
<img width="2556" alt="Screen Shot 2020-07-24 at 10 11 40 AM" src="https://user-images.githubusercontent.com/54336863/88343957-b5f8ee80-cd96-11ea-9ffb-d42379bbb5de.png">
<img width="2556" alt="Screen Shot 2020-07-24 at 10 11 22 AM" src="https://user-images.githubusercontent.com/54336863/88343964-b85b4880-cd96-11ea-9ab2-8961c2a6df58.png">
<img width="2556" alt="Screen Shot 2020-07-24 at 10 09 51 AM" src="https://user-images.githubusercontent.com/54336863/88343970-b98c7580-cd96-11ea-8cd8-6b16f085bf4b.png">

**Comment by zheng1** [comment]
Fixed in https://github.com/kubesphere/kubesphere/pull/2567 

Please wait for the PR merge and image push
