### ISSUE TITLE
'How to modify platform info' link is invalid

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#2574]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**General remarks**

> Please delete this section including header before submitting
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the Bug**
'How to modify platform info' link is invalid

**Versions Used**
KubeSphere: 3.0 alpha 1

**How To Reproduce**
1. Go to 'Platform' through top left corner menu, and then go to 'Platform Settings'
2. Click on 'How to modify platform info' link
3. it redirect to https://kubesphere.io/docs/v2.1/en/developer/custom_console/, but nothing is shown, then the page is redirected to docs home page.

**Comment by leoendless** [comment]
The link is `https://kubesphere.io/docs/zh-CN/platform-settings/customize-basic-information/`, but need to wait for the v3.0 docs's release.

**Comment by benjaminhuo** [comment]
This issue should have been fixed, the link is https://v3-0.docs.kubesphere.io/docs/cluster-administration/platform-settings/customize-basic-information/ now
