### ISSUE TITLE
ws admin can't view multi-cluster deployment pods

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2577]
**Describe the Bug**
`ray` is the admin of the workspace. Using this user to create a multi-cluster deployment in the multi-cluster project, then go into the pod list page, got error msg.
![Screen Shot 2020-07-24 at 1 20 36 PM](https://user-images.githubusercontent.com/28859385/88362912-bef6b980-cdb0-11ea-866a-df8fe5b87f2e.png)
![Screen Shot 2020-07-24 at 1 20 23 PM](https://user-images.githubusercontent.com/28859385/88362920-c322d700-cdb0-11ea-8690-14400839628b.png)

**Versions Used**
KubeSphere: 3.0.0-dev

**Comment by wansir** [comment]
Unexpected request here `/kapis/clusters/rohan/resources.kubesphere.io/v1alpha3/pods?limit=10&ownerKind=&labelSelector=&sortBy=startTime`, @leoendless

**Comment by rayzhou2017** [comment]
verified
