### ISSUE TITLE
creator is not in members of devops project

### ISSUE THREAD

**Issue by junotx** [kubesphere/kubesphere#2578]
**Describe the Bug**

The members of devops do not contain the creator
![image](https://user-images.githubusercontent.com/49136171/88366263-4ba67500-cdbb-11ea-935c-2ebd944a6828.png)

**Versions Used**
KubeSphere(2020-07-24)

/kind bug
/area devops
/milestone 3.0.0
/priority high

**Comment by rayzhou2017** [comment]
Please check the latest build. I found it is fixed.

**Comment by junotx** [comment]
verified
/close
