### ISSUE TITLE
Fail to deploy skywalking app because of a nil error

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#2579]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**General remarks**

> Please delete this section including header before submitting
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the Bug**
Fail to deploy skywalking app because of a nil error

**Versions Used**
KubeSphere: 3.0 alpha 1

**How To Reproduce**
1. Go to some workspace and add 'https://charts.kubesphere.io/test' app repo
2. Go to some project and select this repo, you could all test app under this repo
3. Deploy skywalking app to some project, but get a nil error msg

<img width="1062" alt="Xnip2020-07-24_14-35-35" src="https://user-images.githubusercontent.com/28883416/88366445-bfe11880-cdbb-11ea-8942-321ee7cab421.png">

**Comment by zheng1** [comment]
Fixed at https://github.com/openpitrix/openpitrix/pull/1032

**Comment by rayzhou2017** [comment]
verified
