### ISSUE TITLE
输入一个错误的用户账号登录，显示信息为" internal server error"

### ISSUE THREAD

**Issue by jerryjedi** [kubesphere/kubesphere#258]
输入正确的user/password，登录成功。如输入没有创建过的账号登录，系统显示"internal server error“，如截图，建议修改显示信息为”用户名或密码错误“。

![_20181231152221](https://user-images.githubusercontent.com/7875026/50556209-e5598d80-0d10-11e9-98a0-aa1c779d55eb.png)

**Comment by leoendless** [comment]
这个应该会在1.0.1修复
