### ISSUE TITLE
the app list page doesn't refresh automatically after deploying an app from some helm repo

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#2580]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**General remarks**

> Please delete this section including header before submitting
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the Bug**
the app list page doesn't refresh automatically after deploying an app from some helm repo

**Versions Used**
KubeSphere: 3.0 alpha 1

**How To Reproduce**
1. Deploy some app from a custom helm repo
2. The app list page doesn't refresh automatically after clicking 'deploy' button, you need to refresh browser manually to see this new app

**Comment by leoendless** [comment]
openpitrix app list doesn't support auto refresh now.

**Comment by zryfish** [comment]
duplicate https://github.com/kubesphere/kubesphere/issues/1903

/close

**Comment by benjaminhuo** [comment]
Per previous comments, this issue is duplicated, close it now
/close
