### ISSUE TITLE
ws viewer can't open overview page - cluster info tab - multicluster

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2586]
**Describe the Bug**
`tester4` is the ws viewer. Open the cluster info tab, got error msg
![Screen Shot 2020-07-24 at 3 52 20 PM](https://user-images.githubusercontent.com/28859385/88371074-ec9a2d80-cdc5-11ea-9102-ded3d4d8813b.png)

**Versions Used**
KubeSphere: 3.0.0-dev
Kubernetes: 1.18.6

**Comment by zryfish** [comment]
Cannot reproduce the issue using the latest build. Please verify it again.

**Comment by rayzhou2017** [comment]
verified
