### ISSUE TITLE
A Pipeline for a Devops project created in Kubesphere 3.0 cannot be displayed in the interface

### ISSUE THREAD

**Issue by weekyuan** [kubesphere/kubesphere#2589]

**Comment by shaowenchen** [comment]
when did you install it?

**Comment by hawking-lab** [comment]
I have the same problem, I installed it yesterday。
![image](https://user-images.githubusercontent.com/47567011/88375687-9a113f00-cdce-11ea-9578-75e6e680c1b8.png)
![image](https://user-images.githubusercontent.com/47567011/88375704-a2697a00-cdce-11ea-89fd-99a895c882b5.png)

**Comment by shaowenchen** [comment]
DevOps that installed today is OK. Is it multi-cluster?

Another way is to run:

```bash
kubectl edit cm kubesphere-config -n kubesphere-devops-system
```

replace the password of DevOps with console token
