### ISSUE TITLE
可视化编辑流水线不能支持中文输入？

### ISSUE THREAD

**Issue by jerryjedi** [kubesphere/kubesphere#259]
在使用”可视化编辑流水线“时，就算是作为message，看上去也不支持中文输入？如有中文会出现报错，请问是kubernetes原生不支持还是KubeSphere的问题，是否有计划支持？
![_20181231225930](https://user-images.githubusercontent.com/7875026/50562643-83207d00-0d50-11e9-9650-87115ab35e43.png)

**Comment by rayzhou2017** [comment]
这个什么进展了？

**Comment by runzexia** [comment]
这个暂时还没来得及看，需要在v1.0.1发布吗？

**Comment by rayzhou2017** [comment]
这个在2.0.0支持了吗？ @runzexia

**Comment by runzexia** [comment]
支持了
