### ISSUE TITLE
The links on the page should be updated

### ISSUE THREAD

**Issue by duanjiong** [kubesphere/kubesphere#2592]
**Describe the Bug**
the url should be updated to "https://kubesphere.io/docs/zh-CN/developer/helm-specification/“

![image](https://user-images.githubusercontent.com/3678855/88378928-8a94f480-cdd4-11ea-8a7f-cc098c5becfe.png)

**Versions Used**
KubeSphere: 3.0

**Environment**

**How To Reproduce**

**Expected behavior**
should be "https://kubesphere.io/docs/zh-CN/developer/helm-specification/"

**Comment by duanjiong** [comment]
This too should be updated.
![image](https://user-images.githubusercontent.com/3678855/88380424-20318380-cdd7-11ea-9cde-e72202ab8209.png)

**Comment by leoendless** [comment]
These links will be updated after 3.0 docs released.
