### ISSUE TITLE
error when an user as invited project admin enters devops project 

### ISSUE THREAD

**Issue by junotx** [kubesphere/kubesphere#2594]
**Describe the Bug**

user `devops-pm (ws-admin)` created a devops project `caps`
`devops-pm (ws-admin)`  invited `devops-pr (ws-admin)` as admin to `caps`
`devops-pr (ws-admin)`  encountered error as follows when he entered `caps`
![image](https://user-images.githubusercontent.com/49136171/88379236-258dce80-cdd5-11ea-9ebf-2e21badca1c3.png)

**Versions Used**
KubeSphere(2020-07-24)

/kind bug
/milestone 3.0.0
/area devops

**Comment by shaowenchen** [comment]
It is not ready about iam for DevOps

/assign @wansir

**Comment by junotx** [comment]
@wansir `devops-pr` was invited as devops project admin, but he could not see `Pipelines` menu and `Credentials` menu in `Project Management`
![image](https://user-images.githubusercontent.com/49136171/88754178-91cf5000-d190-11ea-8ce0-06ef3d4116f0.png)

**Comment by junotx** [comment]
verified
/close
