### ISSUE TITLE
create volume in multi-cluster project, cannot select the storage type under all clusters

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2597]
**Describe the Bug**
create volume in multi-cluster project, cannot select the storage type under all clusters
<img width="683" alt="v3" src="https://user-images.githubusercontent.com/36271543/88383865-edd75480-cddd-11ea-9280-230ec488669c.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.15.12
member1-v1.17.9

**Environment**
host: 3node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area multicluster
/assign @zryfish 
/milestone 3.0.0
/priority medium

**Comment by zryfish** [comment]
Should be fixed now. Please check again.

**Comment by RolandMa1986** [comment]
/kind need-to-verify
@liuyp2018

**Comment by liuyp2018** [comment]
fixed
/close
