### ISSUE TITLE
The status of homemade apps is always updated

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2608]
**Describe the Bug**
The status of homemade apps is always updated
<img width="721" alt="status" src="https://user-images.githubusercontent.com/36271543/88445038-d38b8e00-ce52-11ea-8e98-193b32626193.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.15.12
member1-v1.17.9

**Environment**
host: 3node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority medium

**Comment by zryfish** [comment]
fixed in https://github.com/kubesphere/kubesphere/pull/3014
