### ISSUE TITLE
Error setting LB access mode while creating service

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2610]
**Describe the Bug**
Error setting LB access mode while creating service
<img width="947" alt="lb" src="https://user-images.githubusercontent.com/36271543/88446936-c2e21480-ce60-11ea-832d-5371eb733a00.png">

Load balancer and service configuration
<img width="744" alt="lb1" src="https://user-images.githubusercontent.com/36271543/88446988-51569600-ce61-11ea-8f46-7b0c8f173e53.png">

Cloud platform LB configuration
<img width="911" alt="lb2" src="https://user-images.githubusercontent.com/36271543/88447012-97135e80-ce61-11ea-967c-b0134d881a2f.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.15.12
member1-v1.17.9

**Environment**
host: 3node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area networking
/assign @duanjiong 
/milestone 3.0.0
/priority medium

**Comment by duanjiong** [comment]
It is possible that the hostname has been modified, and when adding the backend, you can't find the host by the hostname。 we should adding annotation "node.beta.kubernetes.io/instance-id" to the node
