### ISSUE TITLE
Custom project role gives too much permission

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2611]
**Describe the Bug**
A custom project role with limited permission, but the user can manage all items under the project. Also please be aware of the undefined issue.
<img width="970" alt="Screen Shot 2020-07-25 at 10 37 03 AM" src="https://user-images.githubusercontent.com/28859385/88447160-df7f4c00-ce62-11ea-9467-f79b8708169d.png">
<img width="1236" alt="Screen Shot 2020-07-25 at 10 37 26 AM" src="https://user-images.githubusercontent.com/28859385/88447164-e60dc380-ce62-11ea-9be7-14e2443edbbb.png">

**Versions Used**
KubeSphere: 3.0.0-dev
Kubernetes: 1.18.6

**Comment by wansir** [comment]
1. @leoendless  pls filter out the undefined rules.
2. tester2's global role `test-platform-role1` is able to manage all workspaces.

**Comment by rayzhou2017** [comment]
please platform, workspace and project levels, I found platform also has undefined

**Comment by rayzhou2017** [comment]
one more problem here /cc @wansir I create a new user with the custom project role.
<img width="1280" alt="Screen Shot 2020-07-25 at 1 23 24 PM" src="https://user-images.githubusercontent.com/28859385/88449516-1ad94500-ce7a-11ea-89f5-f9a0ac192063.png">

**Comment by wansir** [comment]
> one more problem here /cc @wansir I create a new user with the custom project role.
> <img width="1280" alt="Screen Shot 2020-07-25 at 1 23 24 PM" src="https://user-images.githubusercontent.com/28859385/88449516-1ad94500-ce7a-11ea-89f5-f9a0ac192063.png">
> 

I'll check role templates one by one.

**Comment by rayzhou2017** [comment]
verified
