### ISSUE TITLE
user could not see devops project after he was invited as operator

### ISSUE THREAD

**Issue by junotx** [kubesphere/kubesphere#2612]
**Describe the Bug**

The user is a `ws-self-provisioner`. He was invited as operator of a devops project by the project admin, but he could not see the project

**Versions Used**
KubeSphere(2020-07-25)

/kind bug
/milestone 3.0.0
/area devops
/assign @shaowenchen

**Comment by shaowenchen** [comment]
It is not ready about iam for DevOps

**Comment by junotx** [comment]
verified
/close
