### ISSUE TITLE
Description information is not saved when creating a custom monitor

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2616]
**Describe the Bug**
Description information is not saved when creating a custom monitor
<img width="910" alt="des" src="https://user-images.githubusercontent.com/36271543/88450546-60017500-ce82-11ea-8858-045f98bec607.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.15.12
member1-v1.17.9

**Environment**
host: 3node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority medium

**Comment by liuyp2018** [comment]
The first time a custom monitor template is created, the description information is correct;
Create the same type of custom monitor template again. The description information is incorrect

![image](https://user-images.githubusercontent.com/36271543/89159891-bc5f4580-d5a2-11ea-96a0-f043a5b007e1.png)

**Comment by benjaminhuo** [comment]
Have put this into v3.1 custom monitoring enhancement https://github.com/kubesphere/kubesphere/issues/3067
