### ISSUE TITLE
Jenkins version might be higher

### ISSUE THREAD

**Issue by Warden-Thresh** [kubesphere/kubesphere#2618]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**What's your question**
 Jenkins will refuse to load many plugins under version 2.176.2

**Environment: OS & Hardware Information**

> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).

**Error logs or message (Attach logs or screenshot)**
![image](https://user-images.githubusercontent.com/22620409/88452390-e4f38b00-ce90-11ea-8227-4f20fe61a419.png)

**Installer Version**

> v3.0

**Comment by shaowenchen** [comment]
While updating the Jenkins version, the plugin will have compatibility issues and need to be upgraded. It will take a lot of time. We will do it in 3.1. 

On the other hand, Jenkins will be deployed using war packages to replace the helm chart. The maintained method will change.

**Comment by LinuxSuRen** [comment]
I'm already working on this. Please see also kubesphere/ks-jenkins/pull/7

**Comment by LinuxSuRen** [comment]
The experimental image is `kubespheredev/ks-jenkins:2.249.1`. The official one is not ready, but it should be `kubesphere/ks-jenkins:2.249.1`.

So I'm going to close this PR.
/close
