### ISSUE TITLE
Error happened when deploy gitlab app from app store

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2620]
Describe the Bug
Error happened when deploy gitlab app from app store

Versions Used 
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'app store' from 'platform management' of home page
2.Select 'Gotlab' and deployment
3.Error happened
![image](https://user-images.githubusercontent.com/67785532/88458149-85ac6f80-cebe-11ea-9036-0ae2d09a31b0.png)

Expected behavior
Should be sucessful deployment

/kind bug
/area app-management
/assign @zheng1 @hlwanghl
/milestone 3.0.0

**Comment by rayzhou2017** [comment]
Any update?

**Comment by wangtian-010** [comment]
verification passed,close this issue
