### ISSUE TITLE
no workload be created for mongodb\redis\rabbitmq\postgreSql apps after deployment from app store

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2622]
Describe the Bug
no workload be created for mongodb\redis\rabbitmq\postgreSql apps after deployment from app store

Versions Used 
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30880/

How To Reproduce
1.Go to 'app store' from 'platform management' of home page
2.Select 'mongodb\redis\rabbitmq\postgreSql' apps separately and deployment
3.no workload be created for these apps
![image](https://user-images.githubusercontent.com/67785532/88458954-12a5f780-cec4-11ea-8ba3-124df9131298.png)
![image](https://user-images.githubusercontent.com/67785532/88458956-176aab80-cec4-11ea-8fd9-0ab8aaf1865a.png)
![image](https://user-images.githubusercontent.com/67785532/88458967-38cb9780-cec4-11ea-9008-7c08773794df.png)
![image](https://user-images.githubusercontent.com/67785532/88458971-3d904b80-cec4-11ea-9450-13d750b359d6.png)

Expected behavior
workloads should be created correctly

/kind bug
/area app-management
/assign @zheng1 @hlwanghl
/milestone 3.0.0

**Comment by zheng1** [comment]
Please install the latest installer and check the version of the apps has upgraded to 0.3+

**Comment by wangtian-010** [comment]
verification passed,close this issue
