### ISSUE TITLE
Record don't disappear after checking record to delete for devops

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2626]
Describe the Bug
Record don't disappear after checking record to delete for devops

Versions Used 
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30887/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Enter 'one-cluster-ws'
3.Click 'Devops project'
4.Check one record and delete
5.Record don't disappear and error happened when delete it again
![image](https://user-images.githubusercontent.com/67785532/88460052-01f97f80-cecc-11ea-972e-0d93baae9a92.png)

Expected behavior
Should disappear after delete it

/kind bug
/area console
/assign leoendless
/milestone 3.0.0

**Comment by leoendless** [comment]
@harrisonliu5 You should add a terminating status for the devops projects just like the projects.

**Comment by wangtian-010** [comment]
verification passed ,close this isuue
