### ISSUE TITLE
Page turning function is not available for devops

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2628]
Describe the Bug
Page turning function is not available for devops

Versions Used 
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30887/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Enter 'one-cluster-ws'
3.Click 'Devops project'
4.Create 12 records from d1 to d12
5.total number is  always 10 and page turning function is not available
![image](https://user-images.githubusercontent.com/67785532/88460219-518c7b00-cecd-11ea-9ced-8246e32ed350.png)

Expected behavior
Should display correct numbers and page turning function is ok

/kind bug
/area console
/assign leoendless
/milestone 3.0.0

**Comment by rayzhou2017** [comment]
It should be fixed as I checked today.

**Comment by wangtian-010** [comment]
verification failed, the numbers of record of every page  is the same.such as 12 records total,the second page also display  12 records

**Comment by wangtian-010** [comment]
![image](https://user-images.githubusercontent.com/67785532/88671536-fe0e6d00-d118-11ea-805e-ed3b20c3900a.png)

**Comment by wangtian-010** [comment]
verification passed,close this issue
