### ISSUE TITLE
devops 流水线活动页面出错

### ISSUE THREAD

**Issue by fireball2018** [kubesphere/kubesphere#263]
devops 流水线活动页面出错，在某些情况下显示为空白页面， 页面地址：

> http://***.io/demo-workspace/devops/project-Om9z13jMA7A7/pipelines/web-deploy-test/pipeline

<img width="1207" alt="error" src="https://user-images.githubusercontent.com/74476/50591862-9ce6cf00-0ecc-11e9-8bf1-7b0ad87e3b4b.png">

**Comment by runzexia** [comment]
这个问题我们会在v1.01版本当中提供修复

**Comment by runzexia** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-55398
相关jenkins问题
