### ISSUE TITLE
elasticsearch image not found

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2631]
**Describe the Bug**
elasticsearch image not found
<img width="906" alt="image1" src="https://user-images.githubusercontent.com/36271543/88470944-4c631680-cf35-11ea-9eb2-583c78aa7596.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.15.12
member1-v1.17.9

**Environment**
host: 3node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority medium

**Comment by harrisonliu5** [comment]
[GET]  https://console.kubesphere.io/kapis/resources.kubesphere.io/v1alpha2/registry/blob?namespace=testshire&image=traefik

This interface is not stable, sometimes the mirror cannot be found
