### ISSUE TITLE
Unmounted storage volume, capacity in details not updated after expansion

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2633]
**Describe the Bug**
Unmounted storage volume, capacity in details not updated after expansion

<img width="708" alt="pvc" src="https://user-images.githubusercontent.com/36271543/88471363-3193a080-cf3b-11ea-8e2b-f5b70ceba305.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.15.12
member1-v1.17.9

**Environment**
host: 3node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority medium

**Comment by leoendless** [comment]
The storage capacity use `status.capacity.storage || spec.resources.requests.storage`. The status capactiy hasn't been updated after expansion. @min-zh

**Comment by min-zh** [comment]
**resource.request.storage** is the size to be expanded, **status.capacity.storage** is the size of pvc before expansion. So before pvc has expand successfully, they are different.

**Comment by leoendless** [comment]
@liuyp2018 Did the capacity updated finally?

**Comment by liuyp2018** [comment]
> @liuyp2018 Did the capacity updated finally?

After the final expansion is successful, it will be updated
