### ISSUE TITLE
Different versions of the chart file should not upload successfully

### ISSUE THREAD

**Issue by duanjiong** [kubesphere/kubesphere#2635]
**Describe the Bug**

We are able to upload a different version of the chart file, but after uploading the file, the old version is still displayed.

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/3678855/88472429-3bba9c80-cf45-11ea-829b-c9f5b6711d44.png)

**Expected behavior**
Different versions of the chart file should not upload successfully.

**Comment by rayzhou2017** [comment]
This should be working as design since it is for enterprise. Usually various versions are needed for enterprise to choose.
