### ISSUE TITLE
Applications should not be able to be deleted after they have been approved

### ISSUE THREAD

**Issue by duanjiong** [kubesphere/kubesphere#2636]
**Describe the Bug**
Applications can be deleted even after they have been approved

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/3678855/88472519-56414580-cf46-11ea-9fff-ae43106420ae.png)

**Expected behavior**
Applications should not be able to be deleted after they have been approved

**Comment by rayzhou2017** [comment]
This should work as design. The author wants to sunset an old version of his application.
