### ISSUE TITLE
Can't see just created devops project in devops project list for the user of devops only role

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#2640]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**General remarks**

> Please delete this section including header before submitting
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the Bug**
Can't see just created devops project in devops project list for the user of devops only role

**Versions Used**
KubeSphere: 3.0 alpha 2

**How To Reproduce**
1. Create a workspace role with devops view, create and management access
2. Assign this workspace role to a user, this user only gets this role
3. Login as this user, and create a devops project
4. back to devops project list page, nothing is shown, then create another devops project with duplicated name, just get 
5. Then go to member list under this workspace, open this user detail page, you could see the devops project created by this user.

<img width="1483" alt="Xnip2020-07-26_19-13-51" src="https://user-images.githubusercontent.com/28883416/88477614-345eb780-cf74-11ea-9d56-f3980fa3ffb8.png">

<img width="1175" alt="Xnip2020-07-26_20-41-22" src="https://user-images.githubusercontent.com/28883416/88479289-886f9900-cf80-11ea-9203-c019ecfc7b6b.png">

**Comment by rayzhou2017** [comment]
This one is fixed
