### ISSUE TITLE
missing audits in multi-tenant space

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2648]
**Describe the Bug**
`ray` is the admin of the ws, `ws-self-provisioner1` is the self-provisioner of the ws. Use this user to create `demo-project1`. Now the default platform `admin` can see the audit of the project creation, but `ray` and `ws-self-provisioner1` can't. Please also check logging/events to see if having the same problem.
<img width="1068" alt="Screen Shot 2020-07-26 at 9 29 10 PM" src="https://user-images.githubusercontent.com/28859385/88480264-970d7e80-cf87-11ea-9ea4-ffc99b77ee14.png">
<img width="1195" alt="Screen Shot 2020-07-26 at 9 29 40 PM" src="https://user-images.githubusercontent.com/28859385/88480267-9bd23280-cf87-11ea-9003-71299560bd44.png">
<img width="1023" alt="Screen Shot 2020-07-26 at 9 29 59 PM" src="https://user-images.githubusercontent.com/28859385/88480270-9f65b980-cf87-11ea-87bb-6a9f03624da0.png">

**Versions Used**
KubeSphere: 3.0.0-dev
Kubernetes: 1.18.6

**Comment by wanjunlei** [comment]
Only the cluster administrator can see the audit log with empty namespace, the namespace of audit of the project creation is empty, so platform admins can see it，but ws-admin and ws-self-provisioner can not see it

**Comment by benjaminhuo** [comment]
If the project creation/deletion API has the namespace field set, then ws-admin and ws-self-provisioner will be able to see the creation/deletion of projects. Is this possible or reasonable to add this in our API ? @wansir @wanjunlei

**Comment by rayzhou2017** [comment]
At least ws admin should be aware of anything happened in its workspace.

**Comment by rayzhou2017** [comment]
verified
