### ISSUE TITLE
The content displayed by pipeline adding voucher is inconsistent with that displayed by editing for devops

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2649]
Describe the Bug
The content displayed by pipeline adding voucher is inconsistent with that displayed by editing for devops

Versions Used 
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30887/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Enter 'muti-cluster-ws'
3.Click 'Devops project'
4.Create one pipeline refer to this link
https://kubesphere.io/docs/zh-CN/quick-start/jenkinsfile-out-of-scm/
5.At below step,the content displayed by pipeline adding voucher is inconsistent with that displayed by editing.
![image](https://user-images.githubusercontent.com/67785532/88480966-a393d600-cf8b-11ea-8102-094064ae33d7.png)

Add page
![image](https://user-images.githubusercontent.com/67785532/88480976-af7f9800-cf8b-11ea-8a77-4354d0ffee76.png)

Edit page
![image](https://user-images.githubusercontent.com/67785532/88480983-b8706980-cf8b-11ea-8dc4-bca7d5d98dff.png)

Expected behavior
Should display Text variable

/kind bug
/area devops
/assign shaowenchen
/milestone 3.0.0

**Comment by harrisonliu5** [comment]
have fixed in #[#979](https://github.com/kubesphere/console/pull/979)

**Comment by wangtian-010** [comment]
verification passed,close this issue
