### ISSUE TITLE
Incomplete display of page content when running pipeline for devops

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2650]
Describe the Bug
Incomplete display of page content when running pipeline for devops

Versions Used 
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30887/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Enter 'muti-cluster-ws'
3.Click 'Devops project'
4.Create one pipeline refer to this link
https://kubesphere.io/docs/zh-CN/quick-start/jenkinsfile-out-of-scm/
5.Run pipeline,incomplete display of page content
![image](https://user-images.githubusercontent.com/67785532/88481055-fd949b80-cf8b-11ea-9136-e44e18e13964.png)
![image](https://user-images.githubusercontent.com/67785532/88481165-798ee380-cf8c-11ea-81b1-fc60c0472b60.png)

Expected behavior
Should display all content

/kind bug
/area devops
/assign shaowenchen
/milestone 3.0.0

**Comment by harrisonliu5** [comment]
http://139.198.12.26:30887/muti-cluster-ws/clusters/host/devops/test2vkd4r/pipelines/pipe001/pipeline

![image](https://user-images.githubusercontent.com/17872673/88518708-814d9700-d023-11ea-95ed-d517119d7d0b.png)

**Comment by wangtian-010** [comment]
Verification passed,close this issue
