### ISSUE TITLE
Failed for check SCM when running pipeline for devops

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2651]
Describe the Bug
Failed for check SCM when running pipeline for devops

Versions Used 
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30887/

How To Reproduce
1.Go to 'Access control' from 'platform management' of home page
2.Enter 'muti-cluster-ws'
3.Click 'Devops project'
4.Create one pipeline refer to this link
https://kubesphere.io/docs/zh-CN/quick-start/jenkinsfile-out-of-scm/
5.Run pipeline and failed for below reason,but REGISTRY have value
![image](https://user-images.githubusercontent.com/67785532/88481445-228a0e00-cf8e-11ea-9864-a5b2d9605ab9.png)
![image](https://user-images.githubusercontent.com/67785532/88481477-58c78d80-cf8e-11ea-98bd-61afd85b72d2.png)

Expected behavior
Should run success for check SCM stage

/kind bug
/area devops
/assign shaowenchen
/milestone 3.0.0

**Comment by Warden-Thresh** [comment]
The same as #2699 , but jenkins ui is working well

**Comment by huanggze** [comment]
verified

**Comment by wangtian-010** [comment]
verification passed,close this issue
