### ISSUE TITLE
Unbound clusters should not appear on enterprise space

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2654]
**Describe the Bug**
Unbound clusters should not appear on enterprise space
<img width="788" alt="cluster" src="https://user-images.githubusercontent.com/36271543/88504588-c49a0c80-d007-11ea-8319-f68b4c03e457.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.15.12
member1-v1.17.9

**Environment**
host: 3node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority medium

**Comment by yuswift** [comment]
The bug has been fixed. However, the related resources are not deleted. See this [issue](https://github.com/kubesphere/kubesphere/issues/2912). The issue should be closed.
