### ISSUE TITLE
Service does not support sort and edit service functions in muti-cluster project of muti-cluster namespace

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2658]
Describe the Bug
Service does not support sort and edit service functions in muti-cluster project of muti-cluster namespace

Versions Used 
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30887/

How To Reproduce
1.Service does not support sort and edit service functions in muti-cluster project of muti-cluster namespace now
![image](https://user-images.githubusercontent.com/67785532/88507117-442ada00-d00e-11ea-9613-2210f05ff1e1.png)

Expected behavior
Suggest to support sort and edit service functions in muti-cluster project of muti-cluster namespace

/kind bug
/area multicluster
/assign @zryfish
/milestone 3.1.0

**Comment by liuyp2018** [comment]
verified and fixed 
/close
