### ISSUE TITLE
Fail to load app detail page as workspace admin

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#2667]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**General remarks**

> Please delete this section including header before submitting
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the Bug**
Fail to load app detail page as workspace admin

**Versions Used**
KubeSphere: 3.0 alpha 2

**How To Reproduce**
1. Create a user with 'Platform Regular' role
2. Create a workspace and assign this user as the workspace admin
3. login as this user and access above workspace
4. Add a custom app repo: https://charts.kubesphere.io/test
5. Create single cluster project and deploy skywalking app from above app repo, the app detail page is empty and lots of js error

<img width="1649" alt="Xnip2020-07-27_16-54-04" src="https://user-images.githubusercontent.com/28883416/88523382-6f232700-d02a-11ea-9604-3a8202d27101.png">

**Comment by wansir** [comment]
same as this issue https://github.com/kubesphere/kubesphere/issues/2347#issuecomment-661833402

**Comment by zryfish** [comment]
> same as this issue [#2347 (comment)](https://github.com/kubesphere/kubesphere/issues/2347#issuecomment-661833402)

Not the same cause. Also, I can't reproduce the issue with the latest build, @calvinyv can you verify it again?

**Comment by calvinyv** [comment]
can't reproduce, closed
