### ISSUE TITLE
点击创建凭证后，界面仍保留了上次创建的凭证数据

### ISSUE THREAD

**Issue by shizgchina** [kubesphere/kubesphere#267]
示例 6，第 2 次创建凭证时：

第二步：创建 GitHub 凭证
同上，创建一个用于 GitHub 的凭证，凭证 ID 命名为 github-id，类型选择 账户凭证，输入您个人的 GitHub 用户名和密码，备注描述信息，完成后点击 确定。

此时，弹出的界面仍带有第一次创建时填写的信息，没有清空：
![image](https://user-images.githubusercontent.com/41432506/50748289-97460c00-1273-11e9-99e3-fa2c3ce9f998.png)

**Comment by minghaoye** [comment]
我们会在v1.01版本当中优化一下。
