### ISSUE TITLE
Kubernetes component validation is inconsistent

### ISSUE THREAD

**Issue by Forest-L** [kubesphere/kubesphere#2670]
* There are fewer names and different times
* 1、UI show：
![image](https://user-images.githubusercontent.com/50984129/88540016-dc43b600-d044-11ea-818f-f565b67c2483.png)

* 2、Terminal show:
![image](https://user-images.githubusercontent.com/50984129/88540227-2331ab80-d045-11ea-9071-c44c42ca7b0c.png)

* k8sv1.17.8+v3.0.0

**Comment by zryfish** [comment]
https://github.com/kubesphere/ks-installer/pull/944

**Comment by zryfish** [comment]
/cc @Forest-L 
can you verify it again using the latest build? It should be fixed now

**Comment by zackzhangkai** [comment]
The pr above is just fix the service of istio .  This issue is about the api-server sevice in kube-system is missed.

**Comment by zackzhangkai** [comment]
The reason why the website is not match with the terminal is that, when the service in terminal has no selector , this service will be omited. This sitituation maybe more suitable.  If the website show the services, which had no selector, which means they had no backend pods, when clicked into this item on the website, and it would show you the blank, maybe it's strange.
