### ISSUE TITLE
When creating a project, the interface has no network isolation Settings

### ISSUE THREAD

**Issue by Forest-L** [kubesphere/kubesphere#2671]
* When creating a project, the interface has no network isolation Settings
![image](https://user-images.githubusercontent.com/50984129/88547292-18304880-d050-11ea-9f43-973b6281a8b6.png)

* The project created in the test document contains network isolation
![image](https://user-images.githubusercontent.com/50984129/88547433-5168b880-d050-11ea-8493-5fbc79e10864.png)

* k8sv1.17.8+v3.0.0

**Comment by leoendless** [comment]
network isolation setting has been removed from project creating and workspace creating. It can only be configured in the project base-info page.
