### ISSUE TITLE
Error displaying project quota terminal

### ISSUE THREAD

**Issue by Forest-L** [kubesphere/kubesphere#2673]
* There is a problem with memory size display

* UI show:
![image](https://user-images.githubusercontent.com/50984129/88612133-151f7180-d0bd-11ea-8460-62a864b7b440.png)

* Terminal show:
![image](https://user-images.githubusercontent.com/50984129/88612164-2bc5c880-d0bd-11ea-973c-8a8158bbbf8c.png)

* k8sv1.17.8+ksv3.0.0

**Comment by zryfish** [comment]
We did some conversion, they are actually the same
