### ISSUE TITLE
Error opening network isolation in enterprise space

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2678]
**Describe the Bug**
Error opening network isolation in enterprise space
<img width="920" alt="erro" src="https://user-images.githubusercontent.com/36271543/88635029-bde3c600-d0e9-11ea-84f8-a1c17c52a1ee.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.15.12
member1-v1.18.6

**Environment**
host: 2node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area iam
/assign @wansir 
/milestone 3.0.0
/priority high

**Comment by liuyp2018** [comment]
There are still problems

<img width="917" alt="error" src="https://user-images.githubusercontent.com/36271543/89381235-68cc3380-d72b-11ea-9263-2a1f861ef061.png">

/remove-kind need-to-verify

**Comment by wansir** [comment]
```
kubectl replace -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/common/files/ks-crds/tenant.kubesphere.io_workspacetemplates.yaml
```

/kind need-to-verify

**Comment by wansir** [comment]
```
kubectl replace -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/common/files/ks-crds/tenant.kubesphere.io_workspacetemplates.yaml
```

/kind need-to-verify
