### ISSUE TITLE
示例6 第二步：添加仓库 时报错

### ISSUE THREAD

**Issue by shizgchina** [kubesphere/kubesphere#268]
首次添加是正常的，第 2 次重复该 Lab 时，做到

4、复制生成的 token，在 KubeSphere Token 框中输入该 token 然后点击保存。

报 internal server error
![image](https://user-images.githubusercontent.com/41432506/50750928-438eef00-1282-11e9-8958-a00e116425ff.png)

**Comment by runzexia** [comment]
没有复现这个问题，可以通过青云的工单系统给我们一下环境信息吗？我们上去看一下

**Comment by rayzhou2017** [comment]
这个有进展吗？

**Comment by runzexia** [comment]
> 这个有进展吗？

这个问题我们换了几个环境都没有复现
