### ISSUE TITLE
hyperlink is unreachable

### ISSUE THREAD

**Issue by Forest-L** [kubesphere/kubesphere#2680]
* Click here for a link to the previous step, not a link to the relevant content.
![image](https://user-images.githubusercontent.com/50984129/88637604-f5a03d00-d0ec-11ea-9a1c-c4f3ed40a4c4.png)

![image](https://user-images.githubusercontent.com/50984129/88637834-3dbf5f80-d0ed-11ea-9ca1-2ce503fd8ea7.png)

* K8s1.17.8+KubeSpherev3.0.0

**Comment by rayzhou2017** [comment]
duplicate with https://github.com/kubesphere/console/issues/493
