### ISSUE TITLE
The display of physical resource memory under the project does not match the actual display

### ISSUE THREAD

**Issue by Forest-L** [kubesphere/kubesphere#2681]
* Physical resource memory is zero:
![image](https://user-images.githubusercontent.com/50984129/88642796-8417bd00-d0f3-11ea-96fd-dfd1f47b8b44.png)

* Actual show:
![image](https://user-images.githubusercontent.com/50984129/88642903-a14c8b80-d0f3-11ea-8e3d-17e2a9cb64f8.png)

* create 2020-07-28-16:00   K8sv1.17.8+KubeSphere

**Comment by huanggze** [comment]
verified
