### ISSUE TITLE
Service mesh decouples from logging

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2682]
**Describe the Bug**
The service mesh component depends on es, furthur on logging. We already made es a common part so logging, events, audits are loose coupling. I think service mesh should do the same thing.

**Versions Used**
KubeSphere: 3.0.0-dev

**Comment by huanggze** [comment]
As we discussed, jeager tracing relys on es for storage. So enabling service mesh will get es installed @zryfish (BUT NOT Fluent Bit Operaor)

Besides, s2i will rely on es as persistent storage for build logs. However, enaling devops won't install es becasue it requires extra work from devops team.

**Comment by rayzhou2017** [comment]
What do you mean? Do you mean I can enable service mesh only without logging enabled now?

**Comment by huanggze** [comment]
Yes, you can enable service mesh only without logging enabled. It will only deploy es, but NOT the entire logging stack (such as fluent bit operator)

**Comment by rayzhou2017** [comment]
Not fixed yet. Please try it again.

**Comment by rayzhou2017** [comment]
verified
