### ISSUE TITLE
ws member sees all devops projects

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2683]
**Describe the Bug**
self provisioner creates about 11 devops projects. Then use another user `tester1` to create `tester-a` devops project. Now use the ws admin to log in and check the users' info and found all devops projects under every ws member. Is that correct?
![Screen Shot 2020-07-28 at 6 02 15 PM](https://user-images.githubusercontent.com/28859385/88652149-02c52800-d0fd-11ea-899e-e485a7dd06f2.png)
![Screen Shot 2020-07-28 at 6 01 59 PM](https://user-images.githubusercontent.com/28859385/88652169-0a84cc80-d0fd-11ea-8e48-649585241c80.png)
![Screen Shot 2020-07-28 at 6 06 34 PM](https://user-images.githubusercontent.com/28859385/88652212-17092500-d0fd-11ea-9eed-ccc61758efb3.png)

**Versions Used**
KubeSphere: 3.0.0-dev

**Comment by shaowenchen** [comment]
It seems like a bug.  Projects with permissions should be listed here.  @wansir

**Comment by rayzhou2017** [comment]
same issue with https://github.com/kubesphere/console/issues/1020 not fixed yet

**Comment by rayzhou2017** [comment]
verified
