### ISSUE TITLE
self provisioner has nowhere to delete its devops project

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2684]
**Describe the Bug**
Self provisioner creates devops project, but nowhere to delete it.
<img width="1226" alt="Screen Shot 2020-07-28 at 8 17 32 PM" src="https://user-images.githubusercontent.com/28859385/88664379-9142a500-d10f-11ea-8661-b7e1228f67db.png">

**Versions Used**
KubeSphere: 3.0.0-dev

**Comment by wansir** [comment]
fixed in https://github.com/kubesphere/kubesphere/issues/2684

![image](https://user-images.githubusercontent.com/8263040/88945218-4d42d200-d2c0-11ea-9d33-d455421c35c8.png)

**Comment by rayzhou2017** [comment]
verified
