### ISSUE TITLE
 The monitoring data is not real-time when the switch is turned on

### ISSUE THREAD

**Issue by yuswift** [kubesphere/kubesphere#2686]
**Describe the Bug**
![Jietu20200729-100757](https://user-images.githubusercontent.com/37265389/88748409-89bce380-d183-11ea-9145-13094e04426d.png)

**Versions Used**
KubeSphere: 3.0.0

**How To Reproduce**
1. Go to cluster management page
2. Click on node management and go to monitoring page
3. turn on the real-time switch

**Expected behavior**
the monitoring data should be real-time 
@leoendless 
/kind bug

**Comment by rayzhou2017** [comment]
verified
