### ISSUE TITLE
删除失败的 流水线 有时报 internal error

### ISSUE THREAD

**Issue by shizgchina** [kubesphere/kubesphere#269]
有的情况下报错，无法删除；
有的情况下报错，可以删除；
![image](https://user-images.githubusercontent.com/41432506/50758215-852c9380-129c-11e9-8951-65aa7087fbcc.png)

![image](https://user-images.githubusercontent.com/41432506/50758220-8c53a180-129c-11e9-88e8-680af4d7de75.png)

**Comment by runzexia** [comment]
是nfs server in k8s导致的问题
https://support.cloudbees.com/hc/en-us/articles/115001371588-Device-or-resource-busy-error

**Comment by rayzhou2017** [comment]
那这个问题怎么fix？

**Comment by runzexia** [comment]
> 那这个问题怎么fix？

如果正式环境部署，换存储就可以解决这个问题
