### ISSUE TITLE
how to get access Token  in ks3.0?

### ISSUE THREAD

**Issue by bingws** [kubesphere/kubesphere#2696]
I reported 403 forbidden according to the [2.0 token method](https://kubesphere.com.cn/docs/zh-CN/api-reference/api-guide/).
![image](https://user-images.githubusercontent.com/10806595/88765704-73c21980-d1a9-11ea-8ba7-07f61a0e4371.png)
![image](https://user-images.githubusercontent.com/10806595/88765738-850b2600-d1a9-11ea-8995-ad8d447f567c.png)

**Comment by wansir** [comment]
```
curl -X POST 'http://ks-apiserver.kubesphere-system.svc/oauth/token?grant_type=password' -H 'Content-Type: application/x-www-form-urlencoded' -d 'grant_type=password&username=admin&password=P@88w0rd'
```

**Comment by bingws** [comment]
then, how can I access the Swagger UI in 3.0?
