### ISSUE TITLE
Parameterized pipeline dont send parameter's value

### ISSUE THREAD

**Issue by Warden-Thresh** [kubesphere/kubesphere#2699]
**Describe the Bug**

#### Parameterized pipeline dont send parameter's value

![image](https://user-images.githubusercontent.com/22620409/88780025-faccbd00-d1bc-11ea-99fe-fa1e1831d9c5.png)

![image](https://user-images.githubusercontent.com/22620409/88779276-2a2efa00-d1bc-11ea-889b-04b88d95f05a.png)
![image](https://user-images.githubusercontent.com/22620409/88779201-12577600-d1bc-11ea-93bc-8c43fab64896.png)
![image](https://user-images.githubusercontent.com/22620409/88779236-1f746500-d1bc-11ea-96a0-6779c1f4990a.png)

#### But it is work well when i use jenkisn UI to start Pipeline
![image](https://user-images.githubusercontent.com/22620409/88779806-c22ce380-d1bc-11ea-8526-faff9d28b6da.png)
![image](https://user-images.githubusercontent.com/22620409/88779758-b7724e80-d1bc-11ea-9893-4ccedc7fcaf6.png)

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: 3.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by huanggze** [comment]
verified
