### ISSUE TITLE
how can I access the Swagger UI in 3.0?

### ISSUE THREAD

**Issue by bingws** [kubesphere/kubesphere#2701]
according to [2.0  method](https://kubesphere.com.cn/docs/zh-CN/api-reference/api-guide/)，I can't  access the the Swagger UI in 3.0. 

![image](https://user-images.githubusercontent.com/10806595/88782381-19808300-d1c0-11ea-8358-9552896548b8.png)

**Comment by zryfish** [comment]
Not supported now, but welcome any contribution to implement it.

**Comment by bingws** [comment]
ok.thanks
