### ISSUE TITLE
custom ws with app repo permission denied

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2710]
**Describe the Bug**
`ws-tester14` is the user with custom ws role `app repo view access`. Log in the user and drill down, got error msg.
![Screen Shot 2020-07-30 at 1 13 25 PM](https://user-images.githubusercontent.com/28859385/88883418-e1804b00-d266-11ea-82d4-28b5c6864ef1.png)
![Screen Shot 2020-07-30 at 1 13 10 PM](https://user-images.githubusercontent.com/28859385/88883428-e6dd9580-d266-11ea-980a-24c4419d6f86.png)

**Versions Used**
KubeSphere: 3.0.0-dev

**Comment by wansir** [comment]
`kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml`

Update custom ws role to verify.

**Comment by rayzhou2017** [comment]
verified
