### ISSUE TITLE
audit log missing name for app repo

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2713]
**Describe the Bug**
I create an app repo called `test`, but the audit logs only show the type, no name here like other resource.
![Screen Shot 2020-07-30 at 5 33 20 PM](https://user-images.githubusercontent.com/28859385/88907501-49488d00-d28b-11ea-8a07-015f95ba5549.png)
![Screen Shot 2020-07-30 at 5 36 05 PM](https://user-images.githubusercontent.com/28859385/88907518-4d74aa80-d28b-11ea-96c9-fc7ef2f88a0e.png)

**Versions Used**
KubeSphere: 3.0.0-dev

**Comment by wanjunlei** [comment]
The add repos API is a non-standard API, the name of repos is in the request body like this 

![image](https://user-images.githubusercontent.com/53003665/88909606-e9071a80-d28d-11ea-93cf-2a263567bb0f.png)

Now the auditing is not handler the non-standard apps.
This problem also exists in other APIs of openpitrix and devops.
Does this problem need to be resolved in 3.0 or 3.1?

**Comment by rayzhou2017** [comment]
Move to 3.1. @zheng1 @shaowenchen please take a look at this one
