### ISSUE TITLE
Fuzzy search issue

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2714]
**Describe the Bug**
I test on audit and found the following problem. I guess logging/event may have the same problem
It is OK to use exach search on project `my-project` and use fuzzy search using keywork `my`. But can't search anything using keywork `my-`, `my-pr`, `my-project` for fuzzy search.

![Screen Shot 2020-07-30 at 5 50 55 PM](https://user-images.githubusercontent.com/28859385/88909475-beb55d00-d28d-11ea-9dba-bdb7f96242cd.png)

![Screen Shot 2020-07-30 at 5 51 05 PM](https://user-images.githubusercontent.com/28859385/88909495-c6750180-d28d-11ea-9e4b-7ed5a68331a5.png)

![Screen Shot 2020-07-30 at 5 51 19 PM](https://user-images.githubusercontent.com/28859385/88909543-d7257780-d28d-11ea-901d-6206a3230805.png)

![Screen Shot 2020-07-30 at 5 51 42 PM](https://user-images.githubusercontent.com/28859385/88909557-dbea2b80-d28d-11ea-8a2d-3631c7d6b9fe.png)

![Screen Shot 2020-07-30 at 5 51 55 PM](https://user-images.githubusercontent.com/28859385/88909569-e0164900-d28d-11ea-8e14-531c5564aa15.png)

**Versions Used**
KubeSphere: 3.0.0-dev

**Comment by benjaminhuo** [comment]
/assign @wanjunlei 
@wanjunlei pls take a look at this

**Comment by huanggze** [comment]
Logging doesn't have this issue. I am using Match Phrase Prefix for fuzzy search @wanjunlei 

![image](https://user-images.githubusercontent.com/22350668/88918628-5e79e780-d29c-11ea-832c-36f23a3321f4.png)

**Comment by rayzhou2017** [comment]
verified
