### ISSUE TITLE
action fuzzy search not work on audit

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2721]
**Describe the Bug**
I try to search the action `create` using fuzzy search, but it does not work. Please check other condition search.
![Screen Shot 2020-07-31 at 1 21 34 PM](https://user-images.githubusercontent.com/28859385/89002950-03460480-d331-11ea-9026-6b0dccf6f251.png)
![Screen Shot 2020-07-31 at 1 21 49 PM](https://user-images.githubusercontent.com/28859385/89002964-0a6d1280-d331-11ea-83ef-c594878356d7.png)

**Versions Used**
KubeSphere: 3.0.0-dev

**Comment by wanjunlei** [comment]
The action does not support fuzzy search.

**Comment by wanjunlei** [comment]
The action field is an enumerated value, fuzzy searching has little meaning.
There are similar problems as below:
  Resource Type only support fuzzy search
  verb only support exact search
  Status code only support exact search
  Source IP only support fuzzy search

Dose these all need to support exact and fuzzy search?

**Comment by rayzhou2017** [comment]
I don't think so. But you need to explain somewhere, e.x., in docs.

**Comment by rayzhou2017** [comment]
source ip should support exact search. I used it.

**Comment by wanjunlei** [comment]
Ok, these will be reflected in the user guider。

**Comment by rayzhou2017** [comment]
Please give an accurate guide for it.

**Comment by benjaminhuo** [comment]
`exact search` should be changed to `accurate search`
