### ISSUE TITLE
FAILED - RETRYING: Create kubeadm token for joining nodes with 24h expiration

### ISSUE THREAD

**Issue by stringk245** [kubesphere/kubesphere#2723]
step-1：cd kubesphere-all-v2.1.1/scripts ; then    ./install.sh
step-2: All-in-one
i got this failed!  !!!!!!!!!, how to do ?????????

FAILED - RETRYING: Create kubeadm token for joining nodes with 24h expiration (default) (1 retries left).
fatal: [ks-allinone -> ks-allinone]: FAILED! => {"attempts": 5, "changed": true, "cmd": ["/usr/local/bin/kubeadm", "--kubeconfig", "/etc/kubernetes/admin.conf", "token", "create"], "delta": "0:01:15.301364", "end": "2020-07-31 15:26:06.987901", "msg": "non-zero return code", "rc": 1, "start": "2020-07-31 15:24:51.686537", "stderr": "timed out waiting for the condition\nTo see the stack trace of this error execute with --v=5 or higher", "stderr_lines": ["timed out waiting for the condition", "To see the stack trace of this error execute with --v=5 or higher"], "stdout": "", "stdout_lines": []}

ks-allinone                : ok=443  changed=10   unreachable=0    failed=1   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

Friday 31 July 2020  15:26:07 +0800 (0:07:58.334)       0:13:34.806 *********** 
=============================================================================== 
kubernetes/master : Create kubeadm token for joining nodes with 24h expiration (default)
download : download_container | Download image if required ( mirrorgooglecontainers/pause-amd64:3.1 ) 
Gathering Facts
Gathering Facts
Gathering Facts
Gathering Facts
Gathering Facts
kubernetes/preinstall : Install packages requirements 
etcd : Install | Copy etcdctl binary from docker container
download : download | Download files / images
bootstrap-os : Install libselinux python package
download : download | Sync files / images from ansible host to nodes 
bootstrap-os : Assign inventory name to unconfigured hostnames (non-CoreOS, Suse and ClearLinux)
chrony : start chrony server 
download : download_file | Download item
kubernetes/node : Enable bridge-nf-call tables
etcd : Check certs | check if a cert already exists on node
kubernetes/preinstall : Create kubernetes directories
etcd : Check certs | check if a cert already exists on node
kubernetes/master : kubeadm | Create kubeadm config
failed!
**********************************
env:
Distributor ID: CentOS
Description:    CentOS Linux release 7.8.2003 (Core)
Release:        7.8.2003
Codename:       Core

kubesphere-all-v2.1.1

**Comment by pixiake** [comment]
`/usr/local/bin/kubeadm  --kubeconfig  /etc/kubernetes/admin.conf  token  create`
`timed out waiting for the condition`
This is due to the inability to access kube-apiserver. Usually a firewall or security group configuration issue.
