### ISSUE TITLE
All-in-One  how to add worker?

### ISSUE THREAD

**Issue by TonyK-T** [kubesphere/kubesphere#2724]
All-in-One  how to add worker?
i want a Master and some workers, if i use All-in-One, how to add worker? (only just a Master)
have QQ群 or Wechat群？ to Facilitate communication and problem solving !!!!!!!!!!

**Comment by rayzhou2017** [comment]
Are you using version < 3.0? Those do not support scaling from allinone. KubeSphere v3.0 does. Please check github.com/kubesphere/kubekey

**Comment by TonyK-T** [comment]
> kubekey

i user kubesphere-all-v2.1.1.zip   to install (All-in-One), i  want to add workers,
i have 3 Local physical machine (8G memory)

**Comment by rayzhou2017** [comment]
For 2.1.1, as I said, you need to reinstall.
