### ISSUE TITLE
self provisioner can't invite member to its project

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2731]
**Describe the Bug**
<img width="1229" alt="Screen Shot 2020-08-01 at 11 49 38 AM" src="https://user-images.githubusercontent.com/28859385/89093461-34840a80-d3ed-11ea-889b-7fcd8ce6eda5.png">

**Versions Used**
KubeSphere: 3.0.0-dev

**Comment by wansir** [comment]
```
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml
kubectl -n kubesphere-system rollout restart deploy ks-controller-manager
```

/kind need-to-verify

**Comment by rayzhou2017** [comment]
verified
