### ISSUE TITLE
some unexpected behaviors when creating project role in one-cluster project of muti-cluster namespace

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2734]
Describe the Bug
some unexpected behaviors when creating project role in one-cluster project of muti-cluster namespace

Versions Used 
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30884/

How To Reproduce
1.Click 'Platform management' 
2.Click 'Access control'
3.Click 'muti-cluster-ws' namespace
4.Click 'project management'
5.Click one project
6.Click project role under project setting
7.Create one role and select authorization
![image](https://user-images.githubusercontent.com/67785532/89095383-df052900-d3ff-11ea-829a-9655bfa2e0c6.png)
![image](https://user-images.githubusercontent.com/67785532/89095386-ef1d0880-d3ff-11ea-8aaf-b52be6679aac.png)
Actual Result:
1.no authorization to select for application workload 
2.Stor value only display viewer
3.Page closed when click access control

Expected behavior
1.can see the application workload authorization
2.display edit authorization for Stor value
3.Page don't close when click access control

![image](https://user-images.githubusercontent.com/67785532/89095528-761eb080-d401-11ea-9527-9f5aad0ec2ee.png)
![image](https://user-images.githubusercontent.com/67785532/89095537-89318080-d401-11ea-860e-e7e96dc99e71.png)

/kind bug
/area iam
/assign @wansir
/milestone 3.0.0

**Comment by wansir** [comment]
```
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml
kubectl -n kubesphere-system rollout restart deploy ks-controller-manager
```

**Comment by wangtian-010** [comment]
vericiation passed ,close this issue
