### ISSUE TITLE
Error happened when modify devops project under muti-cluster ws

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2736]
Describe the Bug
Error happened when modify devops project under muti-cluster ws

Versions Used 
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30884/

How To Reproduce
1.Click 'Platform management' 
2.Click 'Access control'
3.Click 'muti-cluster-ws' namespace
4.Click 'Devops project'
5.Create one devopse project and then edit it
6.Error happened 
![image](https://user-images.githubusercontent.com/67785532/89103657-f535d800-d445-11ea-8a11-4cd42fe89f1f.png)

/kind bug
/area devops
/assign harrisonliu5
/milestone 3.0.0

**Comment by harrisonliu5** [comment]
This error will occur if the created devops project data is modified without synchronization

**Comment by wangtian-010** [comment]
varification passed,close this issue
