### ISSUE TITLE
Custom platform role permission - multi-cluster

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2737]
**Describe the Bug**
A user `p-tester2` with custom platform role `Clusters View` logs in a multi-cluster env and has the following error. There are three pages have permission problem: overview, cluster settings (basic info that has same issue with overview, cluster visibility).
<img width="1238" alt="Screen Shot 2020-08-02 at 4 36 06 PM" src="https://user-images.githubusercontent.com/28859385/89119166-983a3080-d4de-11ea-9167-294620a9234d.png">
<img width="1236" alt="Screen Shot 2020-08-02 at 4 41 31 PM" src="https://user-images.githubusercontent.com/28859385/89119226-1991c300-d4df-11ea-9ca0-7160732d7396.png">

<img width="1203" alt="Screen Shot 2020-08-02 at 4 38 18 PM" src="https://user-images.githubusercontent.com/28859385/89119178-ab4d0080-d4de-11ea-8629-9ba2e7de80e7.png">

**Versions Used**
KubeSphere: 3.0.0-dev
Kubernetes: 1.15.12 (host), 1.18.6(member)

**Comment by wansir** [comment]
```
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml
kubectl -n kubesphere-system rollout restart deploy ks-controller-manager
```

The custom role needs to be updated.

/kind need-to-verify

**Comment by rayzhou2017** [comment]
verified
