### ISSUE TITLE
Custom platform role permission problem

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2738]
**Describe the Bug**
A user `p-tester5` with the custom platform role `Roles View / Users Management` logs in and got the following error msg
<img width="1238" alt="Screen Shot 2020-08-02 at 4 50 47 PM" src="https://user-images.githubusercontent.com/28859385/89119373-af7a1d80-d4e0-11ea-81d2-fe05fcf5a6c2.png">
<img width="1220" alt="Screen Shot 2020-08-02 at 4 51 36 PM" src="https://user-images.githubusercontent.com/28859385/89119379-b86aef00-d4e0-11ea-8f89-36091f6efe5e.png">

**Versions Used**
KubeSphere:3.0.0-dev
Kubernetes: 1.15.12 (host), 118.6(member)

**Comment by wansir** [comment]
```
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml
kubectl -n kubesphere-system rollout restart deploy ks-controller-manager
```

The custom role needs to be updated.

/kind need-to-verify

**Comment by rayzhou2017** [comment]
verified
