### ISSUE TITLE
Error happened when one-cluster-project viewer login under muti-cluster ws

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2740]
Describe the Bug
Error happened when one-cluster-project viewer under muti-cluster ws

Versions Used 
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30884/

How To Reproduce
1.Invite members to be view roles for one cluster project under muti-cluster-ws
  account role is platform-regular for member,ws role is mutil-cluster-ws-viewer
2.Login in with this member
3.Error happened 
![image](https://user-images.githubusercontent.com/67785532/89121267-06d3ba00-d4f0-11ea-8f45-82d46da7cc4d.png)

click muti-cluster-project,below message displays.
![image](https://user-images.githubusercontent.com/67785532/89121343-ac872900-d4f0-11ea-9cd9-baad151aa6a7.png)

Expected behavior
should not display error message

/kind bug
/area iam
/assign @wansir
/milestone 3.0.0

**Comment by wansir** [comment]
https://github.com/kubesphere/kubesphere/issues/2742#issuecomment-667674315

**Comment by rayzhou2017** [comment]
The latest installer fixed this one.

**Comment by wangtian-010** [comment]
verification passed,close this issue
