### ISSUE TITLE
Record didn't dispaly after pipeline saved under muti-cluster-ws

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2741]
Describe the Bug
Record didn't display after pipeline saved under muti-cluster ws
Versions Used 
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30884/

How To Reproduce
1.Click 'Platform management' 
2.Click 'Access control'
3.Click 'muti-cluster-ws' namespace
4.Click 'Devops project'
5.Create devops and then pipeline
6.Record didn't display after pipeline saved，the record displays when refresh page 
Expected behavior
should  display the record after saved

/kind bug
/area devops
/assign harrisonliu5
/milestone 3.0.0

**Comment by shaowenchen** [comment]
Console gets data from Jenkins，but  it takes time to synchronize crd data. Please delay refreshing the page to optimize the experience.  @harrisonliu5 

The design needs to be modified in 3.1 @Carlosfengv

**Comment by wangtian-010** [comment]
verification passed,close this issue
