### ISSUE TITLE
member didn't display after was invited to one cluster project under muti-cluster ws

### ISSUE THREAD

**Issue by wangtian-010** [kubesphere/kubesphere#2742]
Describe the Bug
member didn't display after was invited to one cluster project under muti-cluster ws
Versions Used 
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30884/

How To Reproduce
1.Click 'Platform management' 
2.Click 'Access control'
3.Click 'muti-cluster-ws' namespace
4.Click 'one cluster project'
5.Create devops and then pipeline
6.Invite memeber to project and pop up success message,but didn't display record 
![image](https://user-images.githubusercontent.com/67785532/89121849-45b83e80-d4f5-11ea-9c56-f2c8178cb59e.png)

Expected behavior
should  display the record after invited

/kind bug
/area iam
/assign @wansir
/milestone 3.0.0

**Comment by wansir** [comment]
federated resources synchronization fails.
/assign @zryfish

**Comment by rayzhou2017** [comment]
The latest installer should fix this one.

**Comment by wangtian-010** [comment]
verification passed,close this issue
