### ISSUE TITLE
custom platform role permission

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2743]
**Describe the Bug**
A custom role and the erro msg are as follows
<img width="1280" alt="Screen Shot 2020-08-02 at 7 20 57 PM" src="https://user-images.githubusercontent.com/28859385/89121921-c9722b00-d4f5-11ea-8a48-ad8c2ff52a78.png">
<img width="1209" alt="Screen Shot 2020-08-02 at 7 23 35 PM" src="https://user-images.githubusercontent.com/28859385/89121927-cf680c00-d4f5-11ea-9e3c-aa438f19609c.png">

**Versions Used**
KubeSphere: 3.0.0e-dev
Kubernetes: 1.15.12(host), 1.18.6(member)

**Comment by wansir** [comment]
```
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml
kubectl -n kubesphere-system rollout restart deploy ks-controller-manager
```

The custom role needs to be updated.

/kind need-to-verify

**Comment by rayzhou2017** [comment]
verified
