### ISSUE TITLE
custom platform role permission

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2744]
**Describe the Bug**
A custom platform role and the err msg (go into devops project crendential) as follows
<img width="1280" alt="Screen Shot 2020-08-02 at 7 26 38 PM" src="https://user-images.githubusercontent.com/28859385/89122007-6339d800-d4f6-11ea-9a42-011bf10dd052.png">
<img width="1216" alt="Screen Shot 2020-08-02 at 7 27 23 PM" src="https://user-images.githubusercontent.com/28859385/89122011-69c84f80-d4f6-11ea-9c0a-7a5f4f63b95b.png">

**Versions Used**
KubeSphere: 3.0.0-dev
Kubernetes: 1.15.12(host), 1.18.6(member)u expected to happen.

**Comment by wansir** [comment]
```
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml
kubectl -n kubesphere-system rollout restart deploy ks-controller-manager
```

The custom role needs to be updated.

/kind need-to-verify

**Comment by rayzhou2017** [comment]
verified
