### ISSUE TITLE
Custom platform role can't view crd

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2749]
**Describe the Bug**
Please check the screenshots
![Screen Shot 2020-08-03 at 12 08 23 PM](https://user-images.githubusercontent.com/28859385/89145080-2e736280-d582-11ea-84ee-980eec8b90be.png)
![Screen Shot 2020-08-03 at 12 09 38 PM](https://user-images.githubusercontent.com/28859385/89145088-359a7080-d582-11ea-8940-7dbc7bad9f80.png)

**Versions Used**
KubeSphere: 3.0.0-dev

**Comment by rayzhou2017** [comment]
I applied the latest iam-account.yaml, but still have the same problem

**Comment by wansir** [comment]
> I applied the latest iam-account.yaml, but still have the same problem

The custom role needs to be updated.

**Comment by rayzhou2017** [comment]
verified
