### ISSUE TITLE
project custom role permission

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2752]
**Describe the Bug**
A custom project role with role management, but can't delete a role.
![Screen Shot 2020-08-03 at 2 42 03 PM](https://user-images.githubusercontent.com/28859385/89153560-b6b03280-d597-11ea-8ae7-583b47ddf842.png)
![Screen Shot 2020-08-03 at 2 42 13 PM](https://user-images.githubusercontent.com/28859385/89153579-c29bf480-d597-11ea-8008-367aba1a6ba6.png)

**Versions Used**
KubeSphere: 3.0.0-dev

**Comment by rayzhou2017** [comment]
It seems role management depends on member view, right?

**Comment by wansir** [comment]
> It seems role management depends on member view, right?

yes

**Comment by rayzhou2017** [comment]
verified
