### ISSUE TITLE
Error happens when a workspace admin tries to edit a pipeline by 'Edit' quick link menu

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#2754]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**General remarks**

> Please delete this section including header before submitting
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the Bug**
Error happens when a workspace admin tries to edit a pipeline by 'Edit' quick link menu

**Versions Used**
KubeSphere: 3.0 alpha 2

**How To Reproduce**
1. Create a user and a workspace
2. Assign this user as this workspace admin
3. Go to this workspace, create a devops project
4. Create a devops project and an empty pipeline
5. On the devops pipeline list page, click the 'Edit' menu of above pipeline record, got error msg

<img width="1641" alt="Xnip2020-08-03_16-23-33" src="https://user-images.githubusercontent.com/28883416/89162090-21686a80-d5a6-11ea-9bff-d84a3921c582.png">

<img width="673" alt="Xnip2020-08-03_16-23-42" src="https://user-images.githubusercontent.com/28883416/89162107-275e4b80-d5a6-11ea-884f-4624c1631424.png">

**Comment by harrisonliu5** [comment]
this issue has fixed

**Comment by harrisonliu5** [comment]
this issue has fixed in #[#1057](https://github.com/kubesphere/console/pull/1057)

**Comment by calvinyv** [comment]
verified
