### ISSUE TITLE
self provisioner can't create alert policy

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2758]
**Describe the Bug**
Here is the error msg
<img width="1240" alt="Screen Shot 2020-08-03 at 9 17 26 PM" src="https://user-images.githubusercontent.com/28859385/89186815-e7f82500-d5ce-11ea-8484-45d9f3d42b56.png">

**Versions Used**
KubeSphere: 3.0.0-dev

**Comment by wansir** [comment]
```
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml
```
/kind need-to-verify

**Comment by rayzhou2017** [comment]
verified
