### ISSUE TITLE
Nothing happens when validating docker registry

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2762]
**Describe the Bug**
Create a docker registry secret and validate, but nothing happens.
![Screen Shot 2020-08-04 at 12 49 01 PM](https://user-images.githubusercontent.com/28859385/89254146-04d53c80-d651-11ea-8b97-27953533f186.png)

**Versions Used**
KubeSphere: 3.0.0-dev

**Comment by wansir** [comment]
```
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml
```

/kind need-to-verify

**Comment by rayzhou2017** [comment]
verified
