### ISSUE TITLE
Custom platform role permission problem

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2765]
**Describe the Bug**
A user with `Workspace view` or ` Workspace management` can not open the following page
![Screen Shot 2020-08-04 at 3 50 27 PM](https://user-images.githubusercontent.com/28859385/89268034-8d140b80-d66a-11ea-824b-62623fb4aa73.png)
![Screen Shot 2020-08-04 at 3 53 03 PM](https://user-images.githubusercontent.com/28859385/89268052-9604dd00-d66a-11ea-9756-30ff8172627e.png)
 

**Versions Used**
KubeSphere: 3.0.0-dev

**Comment by wansir** [comment]
```
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml
```

needs to update the custom role.

/kind need-to-verify

**Comment by rayzhou2017** [comment]
not fixed yet

**Comment by rayzhou2017** [comment]
verified
