### ISSUE TITLE
Network policy question

### ISSUE THREAD

**Issue by iamruhua** [kubesphere/kubesphere#2768]
I installed kubesphere 3.0 preview with EKS(k8s v1.17)

After I enabled the network isolation function, request from outside of the eks cluster, can not reach the service anymore( which I think is the very typical scenario).

I have alb,calico and domain working before this step. When I disable the network isolation, everything went back well. I think the problem is, the isolation functionality blocked all request from ELB(which the external requests pass through). I tried to search for the documentation and tutorial, can not find any.

By the way, the purpose of doing this, is I am implementing a SaaS service, with multi-tenant support. I want to isolate internal traffic from different namespaces(tenant), and allow k8s namespace, kubesphere namespaces and aws infra traffic to be able to pass the network policy.

**Comment by duanjiong** [comment]
> I installed kubesphere 3.0 preview with EKS(k8s v1.17)
> 
> After I enabled the network isolation function, request from outside of the eks cluster, can not reach the service anymore( which I think is the very typical scenario).
> 
> I have alb,calico and domain working before this step. When I disable the network isolation, everything went back well. I think the problem is, the isolation functionality blocked all request from ELB(which the external requests pass through). I tried to search for the documentation and tutorial, can not find any.

Depending on your kube-proxy and service configuration, the corresponding source ip address will change when the traffic is forwarded. You can only set up network policy ingress CIDR correctly if you know the source IP address.

For more information on how IP address changes work, you can refer to [this document](https://github.com/kubesphere/community/blob/master/sig-network/concepts-and-designs/kubesphere-network-policy.md#source-ip) and [the following links](https://github.com/kubesphere/community/blob/master/sig-network/concepts-and-designs/kubesphere-network-policy.md#references).

> 
> By the way, the purpose of doing this, is I am implementing a SaaS service, with multi-tenant support. I want to isolate internal traffic from different namespaces(tenant), and allow k8s namespace, kubesphere namespaces and aws infra traffic to be able to pass the network policy.

**Comment by iamruhua** [comment]
Thanks for your quick response. I read the document.
Here is my use case:

Service:
http, with ALB and external dns setup.
tcp, with external policy=local

network policy to deny traffics from other tenant namespaces:
Allow all traffic by default. (Which accept traffic from eks cluster external)
Deny traffic from namespace which does not belong to the system workspace.(Deny only traffics from other tenant)


From my current understanding, I can not setup the policy unless I label all tenant namespaces with some tag (like createdByUser=true) to distinguish user traffic, k8s and ks system traffic and external request traffic. 


Am I right? @duanjiong

**Comment by duanjiong** [comment]
> Thanks for your quick response. I read the document.
> Here is my use case:
> 
> Service:
> http, with ALB and external dns setup.
> tcp, with external policy=local
> 
> network policy to deny traffics from other tenant namespaces:
> Allow all traffic by default. (Which accept traffic from eks cluster external)
> Deny traffic from namespace which does not belong to the system workspace.(Deny only traffics from other tenant)
> 
> From my current understanding, I can not setup the policy unless I label all tenant namespaces with some tag (like createdByUser=true) to distinguish user traffic, k8s and ks system traffic and external request traffic.
> 
> Am I right? @duanjiong

Yes， you are right.  
In fact, all ks and k8s namespaces are now automatically labeled with "kubesphere.io/workspace=system-workspace."  

But now the kubesphere project network policy allow granularity is namespace, to implement your requirements you need to allow namespace by namespace, which is cumbersome. Later kubesphere will add workspace level network policy, to achieve your requirements will be easier.

BTW， Your need feels like a blacklist, and it feels like a lot of people have similar needs right now.

**Comment by iamruhua** [comment]
Thanks a lot.
Now I am move forward to use calico policy:

First label user created namespace with some label like "userCreated='true'", then for each user created namespace, deny access from all namespace with userCreate=="true".

I am not sure about the traffic from original namespace and traffics from outside of cluster like ELB of Amazon.
Can you give me some advice? @duanjiong

**Comment by duanjiong** [comment]
> Thanks a lot.
> Now I am move forward to use calico policy:
> 
> First label user created namespace with some label like "userCreated='true'", then for each user created namespace, deny access from all namespace with userCreate=="true".
> 
> I am not sure about the traffic from original namespace and traffics from outside of cluster like ELB of Amazon.
> Can you give me some advice? @duanjiong

Maybe I misunderstood you earlier.  Read my comment below.




`

`

> Thanks a lot.
> Now I am move forward to use calico policy:
> 
> First label user created namespace with some label like "userCreated='true'", then for each user created namespace, deny access from all namespace with userCreate=="true".
> 
> I am not sure about the traffic from original namespace and traffics from outside of cluster like ELB of Amazon.
> Can you give me some advice? @duanjiong

Maybe I misunderstood you earlier.  Read my comment below.

**Comment by duanjiong** [comment]
> I installed kubesphere 3.0 preview with EKS(k8s v1.17)
> 
> After I enabled the network isolation function, request from outside of the eks cluster, can not reach the service anymore( which I think is the very typical scenario).
> 
> I have alb,calico and domain working before this step. When I disable the network isolation, everything went back well. I think the problem is, the isolation functionality blocked all request from ELB(which the external requests pass through). I tried to search for the documentation and tutorial, can not find any.
> 
> By the way, the purpose of doing this, is I am implementing a SaaS service, with multi-tenant support. I want to isolate internal traffic from different namespaces(tenant), and allow k8s namespace, kubesphere namespaces and aws infra traffic to be able to pass the network policy.



> Thanks for your quick response. I read the document.
> Here is my use case:
> 
> Service:
> http, with ALB and external dns setup.

For http traffic with ALB， You can do this below：
```
kubectl edit -n kubesphere-system cm kubesphere-config -o yaml

network:
      enableNetworkPolicy: true
      nsnpOptions:
          allowedIngressNamespaces:
               - kubesphere-system
               -  ****

kubectl rollout restart deployments ks-controller-manager -n kubesphere-system
```
Put the namespaces you want to allow by default under the allowedIngressNamespaces, e.g. the namespace where your ELB is, the namespace where your ks is, etc.   

After the ks-controller-manager starts, turn the project network isolation switch off and on again.


> tcp, with external policy=local
> 

For tcp external traffic, you have to add the CIDR rule to allow the aws infra traffic as I said before.



> network policy to deny traffics from other tenant namespaces:
> Allow all traffic by default. (Which accept traffic from eks cluster external)
> Deny traffic from namespace which does not belong to the system workspace.(Deny only traffics from other tenant)
> 
> From my current understanding, I can not setup the policy unless I label all tenant namespaces with some tag (like createdByUser=true) to distinguish user traffic, k8s and ks system traffic and external request traffic.
> 
> Am I right? @duanjiong

**Comment by iamruhua** [comment]
> Put the namespaces you want to allow by default under the allowedIngressNamespaces, e.g. the namespace where your ELB is, the namespace where your ks is, etc.

In the previous reply, by ELB, you mean the alb-ingress-controller right? That's what I am trying to do. I am trying to use calico to prevent namespaces with label like globalTraffic!='yes' to talk to each other. And allow all external traffic from both AWS elastic load balancer(ELB) and those namespaces with globalTraffic==‘yes’. The reason I have to use this logic is that, I can not identify the namespace or label for traffic from ELB, so I have to allow all traffic by default, but prevent user created namespace to talk to each other by lable themselves globalTraffic='no'.

> For tcp external traffic, you have to add the CIDR rule to allow the aws infra traffic as I said before.

CIDR for aws ELB is ephemeral, and I dont think it's possible for me to identify the range.

**Comment by iamruhua** [comment]
Solved by labeling user namespaces with tag, default allow all traffic, deny by label.
Thanks @duanjiong
