### ISSUE TITLE
custom devops role sees more info

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2778]
**Describe the Bug**
A user with custom devops role `pipeline view` can see regular project.
<img width="1220" alt="Screen Shot 2020-08-05 at 6 16 04 PM" src="https://user-images.githubusercontent.com/28859385/89401494-f4ec5400-d747-11ea-9f67-82806d0b53b6.png">

<img width="785" alt="Screen Shot 2020-08-05 at 6 15 49 PM" src="https://user-images.githubusercontent.com/28859385/89401526-0170ac80-d748-11ea-9035-358cd060c65e.png">

**Versions Used**
KubeSphere: 3.0.0-dev

**Comment by wansir** [comment]
view all projects permission is granted by workspace role.
![image](https://user-images.githubusercontent.com/8263040/89475959-f8212780-d7bb-11ea-84de-044cc83163a5.png)
![image](https://user-images.githubusercontent.com/8263040/89475814-98c31780-d7bb-11ea-9599-d16c7c361858.png)

**Comment by rayzhou2017** [comment]
my mistake, gave wrong ws role
