### ISSUE TITLE
prometeus No datapoints found node_uname_info

### ISSUE THREAD

**Issue by zpLang** [kubesphere/kubesphere#2780]
默认监控指标node_uname_info，meminfo, network等没有

**Comment by FeynmanZhou** [comment]
English only

**Comment by benjaminhuo** [comment]
@zpLang The Prometheus stack KubeSphere offering includes the most commonly used metrics and excludes others.

I think I found the name and network metrics you mentioned: `node_uname_info` and `node_network_info` and will include these into KubeSphere v3.1 Prometheus stack.

which meminfo metrics you're talking about?

**Comment by benjaminhuo** [comment]
https://github.com/kubesphere/ks-installer/pull/1498 node uname & network metrics have been added now
