### ISSUE TITLE
Multi-cluster project alias and description will be reset after edit them from one cluster

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/kubesphere#2785]
**Describe the Bug**
Create a multi-cluster project with initial alias and description, then edit alsias and description from clusters/xxx/projects list, modification will take effect for a short period of time only on this cluster, then alias and description will be set back to initial values.

**Versions Used**
KubeSphere: v3.0.0

**How To Reproduce**
1. Create a multi cluster project from a multi-cluster workspace (path /workspaces/xxx/projects), set initial alias and description
2. Enter this project from one cluster, path clusters/xxx/projects
3. Edit the alias and description of this project
4. Wait about 10 seconds, then alias and description will be reset

**Expected behavior**
New edited alias and description can be synced to all clusters.

**Comment by leoendless** [comment]
Better to remove the operations of the fed managed project in the cluster.

**Comment by rayzhou2017** [comment]
verified
