### ISSUE TITLE
The accounts/account roles search box does not handle Spaces

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#2786]
**Describe the Bug**
The accounts/account roles search box does not handle Spaces

**Versions Used**
KubeSphere:3.0.0

**Environment**
testing env
http://139.198.12.26:30884/

**How To Reproduce**
1.Click 'Platform management'
2.Click 'Access control'
3.click 'accounts'/‘account roles’
4.Enter spaces in the search box

**Expected behavior**
The list displays all accounts/account roles

**Actual behavior**
The list is empty

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority medium

**Comment by leoendless** [comment]
Does this scene have any meaning?

**Comment by wenxin-01** [comment]
The copied content may contain whitespace. After pasting, the user is not easily aware of the existence of whitespace

**Comment by wenxin-01** [comment]
verified fix
testing env http://139.198.12.26:30881
