### ISSUE TITLE
Access Control/accounts,After selecting the account, switch to the next page or the previous page, the selected account is not selected

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#2789]
Describe the Bug
After selecting the account, switch to the next page or the previous page, the selected account is not selected

Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30884/

How To Reproduce
1.Click 'Platform management'
2.Click 'Access control'
3.click 'accounts’
4.Select an account
5.switch to the next page or the previous page

Expected behavior
the account is selected

Actual behavior
the account is not selected
/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority  medium

**Comment by leoendless** [comment]
By design. 
It's not property to keep selected keys after data paging. The user may not realize the previous choice. Better to divide into multiple operations.

**Comment by wenxin-01** [comment]
1、After selecting the content, the page will be prompted.
![image](https://user-images.githubusercontent.com/68640256/89713141-5c183b80-d9c8-11ea-9cc1-c36207ebf187.png)

2、user may want to delete accounts on different page.

**Comment by leoendless** [comment]
This operation is not supported in ks.  Better to divide into multiple operations.
