### ISSUE TITLE
Access Control/account Roles,The prompt for deleting a role should use the same template as the prompt for deleting an account

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#2792]
Describe the Bug
The prompt for deleting a role should use the same template as the prompt for deleting an account

Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30884/

How To Reproduce
1.Log in with account 'A'
2.Click 'Platform management'
3.Click 'Access control'
4.click 'account Roles’
5.delete role 'test'

Expected behavior
The prompt for deleting a role should use the same template as the prompt for deleting an account
![image](https://user-images.githubusercontent.com/68640256/89618485-c5ac2300-d8be-11ea-95a9-f413ed1605d6.png)

Actual behavior
![image](https://user-images.githubusercontent.com/68640256/89618507-d65c9900-d8be-11ea-9479-42b96772f790.png)

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority low

**Comment by leoendless** [comment]
Role deletion will check the related users. If no users with the role, it could be deleted directly. It's not the same as user deletion.

**Comment by wenxin-01** [comment]
ok
