### ISSUE TITLE
custom role has no authorization to get credentials 

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#2795]
**Describe the Bug**
`user1` is a `platform-regular` user, it was invited to workspace `ws2` as `ws2-regular`, and add to a devops project as a custom role which only has authorization  `Credentials View / Credentials Management`. Login with `user1`, view the details of credential, it has the error `credentials.devops.kubesphere.io \"admin1\" is forbidden: User \"user1\" cannot get resource \"credentials/usage\" in API group \"devops.kubesphere.io\" at the cluster scope`

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/53003665/89628396-d19fe100-d8ce-11ea-94ee-23d43dd048ca.png)

**Versions Used**
KubeSphere:3.0.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by wansir** [comment]
```
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml
kubectl -n kubesphere-system rollout restart deploy ks-controller-manager
```

Update the custom role to verify.

**Comment by wanjunlei** [comment]
verified
/close
