### ISSUE TITLE
When creating a volume, should set the fields that need to fill to be required fields

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2797]
**Describe the Bug**
When creating a volume, should set the fields that need to fill to be required fields

![image](https://user-images.githubusercontent.com/36271543/89631331-39f0c180-d8d3-11ea-9387-32efa107a247.png)

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority medium

**Comment by leoendless** [comment]
Could you provide a way to validate the parameters?

**Comment by min-zh** [comment]
Curcurrently, there is no method to validate the parameters.
