### ISSUE TITLE
Duplicated events found in event search UI

### ISSUE THREAD

**Issue by benjaminhuo** [kubesphere/kubesphere#2799]
**Describe the Bug**
1. Delete a pod of a deployment with 2 replicas
2. waiting for the new pod created
3. After half an hour, duplicated events can be found in event search UI

![Snip20200807_54](https://user-images.githubusercontent.com/18525465/89635469-9820a300-d8d9-11ea-95ca-541fd48e1d13.png)

![Snip20200807_56](https://user-images.githubusercontent.com/18525465/89635429-8a6b1d80-d8d9-11ea-8337-09fd18612153.png)

**Comment by junotx** [comment]
fixed by [kubesphere/kube-events#7](https://github.com/kubesphere/kube-events/pull/7)
/kind need-to-verify

**Comment by benjaminhuo** [comment]
verified and close
/close
