### ISSUE TITLE
ks-install tiller keep CrashLoopBackOff

### ISSUE THREAD

**Issue by imkratos** [kubesphere/kubesphere#2800]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**What's your question**
install process tiller CrashLoopBackOff

**Environment: OS & Hardware Information**
os:Linux master 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
centos7.6 16C/128G

k8s version:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:34:02Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"be3d344ed06bff7a4fc60656200a93c74f31f9a4", GitTreeState:"clean", BuildDate:"2020-02-11T19:24:46Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).

**Error logs or message (Attach logs or screenshot)**
kube-system         tiller-deploy-79b566b5ff-clbcl                 0/1     CrashLoopBackOff   58         163m   10.233.90.1   node1  

kubectl describe pod tiller-deploy-79b566b5ff-clbcl -n kube-system

  Warning  Unhealthy  33m (x126 over 163m)    kubelet, node1  Readiness probe failed: Get http://10.233.90.1:44135/readiness: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff    8m27s (x620 over 160m)  kubelet, node1  Back-off restarting failed container
  Normal   Pulled     3m19s (x58 over 163m)   kubelet, node1  Container image "kubesphere/tiller:v2.14.3" already present on machine

kubectl logs tiller-deploy-79b566b5ff-clbcl -n kube-system

[main] 2020/08/07 12:24:44 Starting Tiller v2.14.3 (tls=false)
[main] 2020/08/07 12:24:44 GRPC listening on :44134
[main] 2020/08/07 12:24:44 Probes listening on :44135
[main] 2020/08/07 12:24:44 Storage driver is ConfigMap
[main] 2020/08/07 12:24:44 Max history per release is 0

**Installer Version**
kubesphere 2.1.1 

> e.g. v2.1.0, v2.1.1

**Comment by FeynmanZhou** [comment]
How did you install KubeSphere? Install it on Linux or K8s?

**Comment by imkratos** [comment]
> Did Install KubeSphere on Linux or K8s?

on linux

**Comment by imkratos** [comment]
healthy check failed , but host machine ping pod ip is connected , i have no idea

**Comment by FeynmanZhou** [comment]
@pixiake @Forest-L Could you pls help to take a look at this issue?

**Comment by pixiake** [comment]
You can use `kubectl logs` to check tiller's logs.

**Comment by imkratos** [comment]
> You can use `kubectl logs` to check tiller's logs.

this is logs 

kubectl logs tiller-deploy-79b566b5ff-clbcl -n kube-system

[main] 2020/08/07 12:24:44 Starting Tiller v2.14.3 (tls=false)
[main] 2020/08/07 12:24:44 GRPC listening on :44134
[main] 2020/08/07 12:24:44 Probes listening on :44135
[main] 2020/08/07 12:24:44 Storage driver is ConfigMap
[main] 2020/08/07 12:24:44 Max history per release is 0

**Comment by pixiake** [comment]
Whether the firewall is enabled on the server ?

**Comment by imkratos** [comment]
@pixiake  
![image](https://user-images.githubusercontent.com/3302461/89706686-9f5bb580-d99a-11ea-9378-9bb5590a5fea.png)

![image](https://user-images.githubusercontent.com/3302461/89706694-b1d5ef00-d99a-11ea-8c9a-4b6541efe109.png)

Selinux is opening, set status to permissive。

**Comment by pixiake** [comment]
Is there a firewall between servers ?

**Comment by imkratos** [comment]
![image](https://user-images.githubusercontent.com/3302461/89723579-fdd07480-da2a-11ea-888c-f52582e92e93.png)

The node1 status , none firewall

**Comment by imkratos** [comment]
Any body help me ?
