### ISSUE TITLE
For a new storage type, see that volume already exists in the volume page associated with it.

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2801]
**Describe the Bug**
Create a storage type and view the volume data in the volume page associated with it.
Displays the volume associated with the deleted storage type of the same name.

![image](https://user-images.githubusercontent.com/36271543/89698351-49175400-d953-11ea-85a7-6495e5736b5e.png)

**steps**
1.Create a storage type 
2. In the volume page, create a volume using this storage type
3.Delete the storage type created in Step 1
4.Create a storage type with the same name as the storage type in Step 1
5.In the details page for the newly created storage type, the volume list shows the volume associated with the storage type in Step 1

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority medium

**Comment by leoendless** [comment]
@min-zh Please take a look.

**Comment by min-zh** [comment]
Yes, it looks as designed.   StorageClass is just like a set of configs for pvc on k8s. So after delete and recreate, pvc still  associate with the sc., because the name of sc is the PVC's  spec.storageClassName.
