### ISSUE TITLE
The alias setting item was missing when the storage type was created

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2802]
**Describe the Bug**
There are alias Settings when editing the storage type
but there is no alias setting when the storage type is created
![image](https://user-images.githubusercontent.com/36271543/89698558-80d2cb80-d954-11ea-893b-59aebbf42a8d.png)

![image](https://user-images.githubusercontent.com/36271543/89698582-9b0ca980-d954-11ea-93dc-b94659c4065c.png)

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority low

**Comment by leoendless** [comment]
There is also an alias setting when creating a storageclass now.
