### ISSUE TITLE
when creating rbd storage type , the default value of the storage system was incorrect 

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2803]
**Describe the Bug**
when creating rbd storage type , the default value of the storage system was 'kubernetes.io/rbd' ;The correct value should be 'ceph.com/rbd'

![image](https://user-images.githubusercontent.com/36271543/89700258-8d105600-d95f-11ea-8208-19dd8c54bc7f.png)

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority medium

**Comment by leoendless** [comment]
@min-zh Is that so?

**Comment by min-zh** [comment]
Yes~!  as rbd has problem on new version of k8s(1.15+?),  [rbd-external](https://github.com/kubernetes-retired/external-storage/tree/master/ceph/rbd)  was introduced by KubeKey. Maybe both "kubernetes.io/rbd" and "ceph.com/rbd" are listed here, and user can select. On old version of k8s, "kubernetes.io/rbd" may work, on k8s installed by Kubekey "ceph.com/rbd" work. As user can modify the provisioner, so this could be write by users.  @pixiake  is this right?

**Comment by pixiake** [comment]
Yes，if the cluster is started with hyperkube,  `kubernetes.io/rbd` can be used，but hyperkube has been deprecated from the kubernetes project，so the rbd-external was used in kubekey.

**Comment by leoendless** [comment]
I think it would better to provide this value from API. Users may not know which type can be successfully created.
