### ISSUE TITLE
ReadOnlyMany storage volumes should not be able to be written

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2804]
**Describe the Bug**
A storage volume with access mode ReadOnlyMany, mounted into a container group, should not be able to write in the mount directory
![image](https://user-images.githubusercontent.com/36271543/89700567-b336f580-d961-11ea-8605-a5d301625e64.png)

/kind bug
/area storage
/assign @min-zh 
/milestone 3.0.0
/priority medium

**Comment by min-zh** [comment]
i think it's still bug of [nfs-client](https://github.com/kubernetes-retired/external-storage/tree/master/nfs-client)

**Comment by stoneshi-yunify** [comment]
I raised a [issue](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/18) to nfs-client to confirm this limitation.

But anyway, this is not a KS bug and there is nothing we can do if it's indeed a limitation.

**Comment by stoneshi-yunify** [comment]
Quote from reply of https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/18 :
```
A volume’s AccessModes are descriptors of the volume’s capabilities. They are not enforced constraints. The storage provider is responsible for runtime errors resulting from invalid use of the resource.

this is a common misunderstanding of what the access modes are.
those modes are for matching between PVC's and PV's. nfs support RWO/RWX/ROX but doesn't enforce them. it just one of it's capabilities.
```

Therefore, this issue is working as design.

/close
