### ISSUE TITLE
点击项目 有报错 无法通过应用商店部署

### ISSUE THREAD

**Issue by JVMAK** [kubesphere/kubesphere#2805]
已参考  #1640

`错误信息  点击项目 查看项目信息右上角的提示信息如下：`
```
Internal Server Error
rpc error: code = Internal desc = describe resources failed: Error 1049: Unknown database 'app'
```
---

` ks版本 2.1.1 `

---

`ubuntu version`
```  
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
```

执行  for job in `kubectl -n openpitrix-system get job -o jsonpath="{.items[*].metadata.name}"`; do kubectl -n openpitrix-system get job $job -o json | jq 'del(.spec.selector)' | jq 'del(.spec.template.metadata.labels)' | kubectl replace --force -f -; done  无效

执行如下无效

first:
kubectl edit cm -n kubesphere-system ks-installer
openpitrix:
      enabled: True  //modify true to false
second:
kubectl edit cm -n kubesphere-system ks-installer
openpitrix:
      enabled: False   //modify False to True

![image](https://user-images.githubusercontent.com/7867513/89701118-c00a1800-d966-11ea-86f6-05ea3edea7fd.png)
![image](https://user-images.githubusercontent.com/7867513/89701105-ab2d8480-d966-11ea-8433-c567a4df920e.png)
![image](https://user-images.githubusercontent.com/7867513/89701163-ed56c600-d966-11ea-838d-c11aec3920b3.png)
![image](https://user-images.githubusercontent.com/7867513/89701178-03648680-d967-11ea-9702-070a4bda2400.png)
![image](https://user-images.githubusercontent.com/7867513/89701193-2000be80-d967-11ea-81b9-f09ccf0ae875.png)
![image](https://user-images.githubusercontent.com/7867513/89701205-2ee77100-d967-11ea-9645-b2528c831660.png)
![image](https://user-images.githubusercontent.com/7867513/89701237-6524f080-d967-11ea-94a6-58b8509c95c7.png)
![image](https://user-images.githubusercontent.com/7867513/89701248-84238280-d967-11ea-97c9-836dcde0d684.png)
![image](https://user-images.githubusercontent.com/7867513/89701240-70781c00-d967-11ea-87c6-20f4d8bcfba6.png)

**Comment by FeynmanZhou** [comment]
English only.

**Comment by rayzhou2017** [comment]
please verify on 3.0
