### ISSUE TITLE
Volumes of the RBD storage type cannot be scaled up

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2806]
**Describe the Bug**
Volumes of the RBD storage type cannot be scaled up

![image](https://user-images.githubusercontent.com/36271543/89701217-4292d780-d967-11ea-8a45-618f68fc6788.png)

/kind bug
/area console
/assign @leoendless 
/milestone 3.0.0
/priority medium

**Comment by min-zh** [comment]
ceph.com/rbd  not surpport volume expansion.

**Comment by rayzhou2017** [comment]
So the yaml is incorrect?

**Comment by min-zh** [comment]
volume expansion has two prerequisites:
1.  underlying storage system support volume expansion
2.  StorageClass's **allowVolumeExpansion** is true. 
In this case,  ceph.com/rbd not support volume expansion.
