### ISSUE TITLE
After modifying the account role, the account can still access the permissions granted by the previous role

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#2814]
Describe the Bug
After modifying the account role, the account can still access the permissions granted by the previous role
(By staying on the permission page given by the previous role, and access history)

Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30884/

How To Reproduce
1.There is an account A, whose role is ‘platform-admin’
2.Log in with account 'A'
3.go to the ‘Clusters Management’ page
4.Go to the ‘Host’ cluster page
5.use admin account Modify the role of ‘A’ to be ‘workspaces-Manager’
6.Refresh the page based on Step 3（Access the ‘Host’ cluster in the history）

Expected behavior
The rights in ‘Clusters Management’ （'host' cluster）are no longer available for account  ‘A’

Actual behavior
account A has access to  'Clusters Management'('host' cluster)

/kind bug
/area console
/assign @wansir
/milestone 3.0.0
/priority medium

**Comment by wansir** [comment]
Not a bug, both of  platform-admin and workspaces-manager can list clusters.
