### ISSUE TITLE
Workspace/Failed to create a workspace role with the same name as a workspace role in another workspace

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#2815]
Describe the Bug
Failed to create a workspace role with the same name as a workspace role in another workspace

Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30884/

How To Reproduce
1.There is an workspace A, it has a workspace role named 'test-wx'
2.create a workspace role named 'test-wx' in workspace 'B'

Expected behavior
created successfully

Actual behavior
failed
![image](https://user-images.githubusercontent.com/68640256/89712158-a0540d80-d9c1-11ea-9040-9870a1c1f7b1.png)

/kind bug
/area console
/assign @wansir
/milestone 3.0.0
/priority medium

**Comment by wansir** [comment]
Not a bug, `WorkspaceRole` is global scope CRD, workspace role name is unique within the cluster.
