### ISSUE TITLE
The hint is misleading and its return is not correct when import an invalid member cluster

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#2817]
## Issue
I have successfully imported an invalid member cluster into KubeSphere, then click into it, it hints the session timeout and I was logged out automatically. At that time, the hint is misleading and users don't know this is caused by the invalid imported cluster.

![image](https://user-images.githubusercontent.com/40452856/89712406-52d8a000-d9c3-11ea-9f96-15c4b22c0e6a.png)

Look at its URL, when I logged in again, it will loop back to the invalid member cluster and hints the same misleading message again. This must be an endless cycle. 

![image](https://user-images.githubusercontent.com/40452856/89712608-9c75ba80-d9c4-11ea-9194-1fb745fcd985.png)

## Suggestion

Modify the hint word and give a correct return page to navigate users to remove the invalid cluster.

**Comment by FeynmanZhou** [comment]
BTW, my member cluster is ready, but it looks not available in my host cluster. How to delete the invalid member cluster that I imported before?

![image](https://user-images.githubusercontent.com/40452856/89713298-769ee480-d9c9-11ea-9830-971a91ad412a.png)

**Comment by kubeshared** [comment]
see https://github.com/kubesphere/ks-installer/pull/877

**Comment by LinuxSuRen** [comment]
I met the same issue in KubeSphere: `nightly-20210405`.

/reopen
