### ISSUE TITLE
Workspace/When the account only has the role of workspace, the page reports an error after login

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#2820]
Describe the Bug
When the account only has the role of workspace, the page reports an error after login

Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30884/

How To Reproduce
1.There is an account A, it has all the authority of workSpace 'text-wx'
2.Log in with account 'A'

Expected behavior
Successfully enter  workspace ‘test-wx’ and has access to all content

Actual behavior
the page reports an error 
![image](https://user-images.githubusercontent.com/68640256/89713556-0a24e500-d9cb-11ea-96b7-8359ab754cde.png)

/kind bug
/area console
/assign @wansir
/milestone 3.0.0
/priority medium

**Comment by wansir** [comment]
Update ks-console to verify.

/kind need-to-verify
