### ISSUE TITLE
Request response to low when run kubesphere run on 3 node

### ISSUE THREAD

**Issue by Sonek-HoangBui** [kubesphere/kubesphere#2822]
I have the issue
I run 3 node master on 3 VM, and backed are etcd cluster (I have 3 instances), VM run with multipass tool.
And I run k3s cluster, when I install kubesphere on kubenertes, everything is installed well i have no bug.
And after that I access kubephere-console and login with admin account and login success.
But when logged in the kubesphere dashboard, request to api server to long to take response, I don't know why?

Addition information: When I run kubesphere on 1 node is run normal, request and response back instant.
Please help!!!

Image when logged in kubesphere dashboard
![image](https://user-images.githubusercontent.com/65322226/89728058-857ea900-da54-11ea-96ba-5b7f1809ff49.png)

Request first logged in without monitor etcd
![image](https://user-images.githubusercontent.com/65322226/89728106-f6be5c00-da54-11ea-9861-d0b9a11092a5.png)

 Request logged in with monitor etcd
![image](https://user-images.githubusercontent.com/65322226/89728184-8106c000-da55-11ea-860b-e45532ccb170.png)

Image after wait the response (but it to long :( )
![image](https://user-images.githubusercontent.com/65322226/89728306-95978800-da56-11ea-8ab3-8cc4de6b2974.png)

Sometime it got error because of request timeout
![image](https://user-images.githubusercontent.com/65322226/89728350-e7401280-da56-11ea-9197-06c1e84aa86b.png)

More information about my clusters:
RAM 4gb, Disk 30GB (ssd), CPU Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz,
kubesphere image is kubesphere/ks-installer:v2.1.1
I run kubesphere minimum version
I run etcd cluster now (I tried default storage "sqlite" but get the same result)
And I re-install many time, scale api server but get the same result too 
Please tell me how to solve this if you know, Thanks so much

Thank everyone.

**Comment by Forest-L** [comment]
@wansir  @benjaminhuo

**Comment by benjaminhuo** [comment]
@Sonek-HoangBui 

We haven't tested and verified k3s yet, there might be problems installing kubesphere on k3s.
Let's confirm your env first:
3 node k3s cluster, 3 master node, no worker node?
3 node etcd cluster is also installed on the same vm?

Ben

**Comment by Sonek-HoangBui** [comment]
> @Sonek-HoangBui
> 
> We haven't tested and verified k3s yet, there might be problems installing kubesphere on k3s.
> Let's confirm your env first:
> 3 node k3s cluster, 3 master node, no worker node?
=> Yes, currently I ran 3 master nodes.
> 3 node etcd cluster is also installed on the same vm?
=> 3 node etcd ran on 3 vm separate and connect each other to cluster
> 
> Ben

**Comment by Sonek-HoangBui** [comment]
@benjaminhuo @wansir

**Comment by Sonek-HoangBui** [comment]
@benjaminhuo @wansir

**Comment by benjaminhuo** [comment]
K3s compatibility will be tested after KubeSphere v3.1 is released
