### ISSUE TITLE
ws-viewer cannot list resource "clusters" in API group "resources.kubesphere.io" at the cluster scope

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#2823]
**Describe the Bug**
The `user1` is a `platform-regular` user and was invented to workspace `ws` as `ws-viewer`. When login with `user1`, there is a error `clusters.resources.kubesphere.io is forbidden: user1 cannot list resource "clusters" in API group "resources.kubesphere.io" at the cluster scope`.

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/53003665/89748254-f1b0e980-daf4-11ea-87ec-f149f3b30281.png)

**Versions Used**
KubeSphere:3.0.0(2020-08-10)

/kind bug
/area iam
/assign @wansir
/milestone 3.0.0

**Comment by wansir** [comment]
Same as https://github.com/kubesphere/kubesphere/issues/2820, update ks-console to the latest version to verify.

**Comment by wanjunlei** [comment]
This platform was installed today，the ks-console is the latest version.

**Comment by wansir** [comment]
@wanjunlei update ks-console to the latest version to verify.

**Comment by wanjunlei** [comment]
verified
/close
