### ISSUE TITLE
the latest version in the list and app store is not updated

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2824]
**Describe the Bug**
After deleting the latest version, the latest version in the list and app store is not updated

![image](https://user-images.githubusercontent.com/36271543/89748899-24a8ac80-daf8-11ea-86b9-f53a03689bfc.png)

![image](https://user-images.githubusercontent.com/36271543/89749126-1d35d300-daf9-11ea-9f2a-2b1491bcdde3.png)

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority medium

**Comment by zheng1** [comment]
Fix at https://github.com/openpitrix/openpitrix/pull/1038

/kind need-to-verify

**Comment by liuyp2018** [comment]
The latest version has been removed ,  the latest version of the application has been updated;
but the latest version has been taken off the shelves,   the latest version of the app store has not been updated

![image](https://user-images.githubusercontent.com/36271543/90611283-1b76b880-e239-11ea-9b31-9d76059a9c10.png)

/remove-kind need-to-verify

**Comment by zheng1** [comment]
Fix at https://github.com/openpitrix/openpitrix/pull/1039

/kind need-to-verify

**Comment by liuyp2018** [comment]
The latest version of the app store app remains the one that has been taken off the shelves
/remove-kind need-to-verify
/remove-milestone 3.0.0
/milestone 3.1.0
