### ISSUE TITLE
error occurred while setting the Jenkins mail configuration

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2825]
**Describe the Bug**
error occurred while setting the Jenkins mail configuration

![image](https://user-images.githubusercontent.com/36271543/89749646-33dd2980-dafb-11ea-8730-cd36299ed6bd.png)

/kind bug
/area devops
/assign @shaowenchen 
/milestone 3.0.0
/priority high

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/89866417-0f0fb180-dbe2-11ea-8c0f-d25c15a42794.png)

I can edit ks-jenkins deploy yaml.

@harrisonliu5

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/89866773-b42a8a00-dbe2-11ea-85ea-4fe4f23cdac4.png)

![image](https://user-images.githubusercontent.com/43693241/89866899-e76d1900-dbe2-11ea-9dd2-0223104dc882.png)

**Comment by rayzhou2017** [comment]
@harrisonliu5 Please share your env with @shaowenchen to check the problem. It might be a bug indeed.

**Comment by shaowenchen** [comment]
It is a bug that I have reproduced in his env.
