### ISSUE TITLE
Optional query fields are not displayed

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2826]
**Describe the Bug**
In the pipeline list query input box, no optional query fields, such as name, are displayed

<img width="668" alt="11" src="https://user-images.githubusercontent.com/36271543/89754635-495c4e80-db0f-11ea-9332-6894452d4e95.png">

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority low

**Comment by harrisonliu5** [comment]
![image](https://user-images.githubusercontent.com/17872673/89767311-458af500-db2c-11ea-8a43-1069f4eac855.png)

**Comment by harrisonliu5** [comment]
![image](https://user-images.githubusercontent.com/17872673/89767845-4ff9be80-db2d-11ea-99e8-79f805ea9fa6.png)

Have changed to this style
