### ISSUE TITLE
Delete app template which has versions pops error

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/kubesphere#2832]
**Describe the Bug**
Delete app template with existing versions will cause a Internal Server Error

![image](https://user-images.githubusercontent.com/38337958/89763354-ea093900-db24-11ea-94d2-9381cfc42eb9.png)

**Versions Used**
KubeSphere: v3.0.0

**Expected behavior**
It's a business logical error which could be handled and prompted more friendly, no need to cause an internal server error.

**Comment by rayzhou2017** [comment]
Actually this is not a functional bug. It just returns a wrong code. #2860
