### ISSUE TITLE
App template test deploy on multi-cluster can not create workload, and workspace-manager can not see application

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/kubesphere#2833]
**Describe the Bug**
(1)One a two cluster kubesphere, host (1 node), product (3 nodes).
(2)Create a user ws-manager with workspace-manager access only
(3)Login with this ws-manager, creat a workspace openpitrix-test, then create a project openpitrix-project under it, use admin to set product cluster visible to workspace openpitrix-test.
(4)Create an app template with ws-manager, then test deploy it on openpitrix-project and product cluster.

Result:
(1)Admin can see the test deploy pending
![image](https://user-images.githubusercontent.com/38337958/89767926-73bd0480-db2d-11ea-8dc5-e34672706e5f.png)
(2)ws-manager can not see any apps deployed, and its path is /composing, if enter path /template in address, then it can see deployed app
![image](https://user-images.githubusercontent.com/38337958/89767997-93ecc380-db2d-11ea-91a8-35aa48ff7b43.png)
(3)App deployed hangs on pending, and no workload is created, helm list -n openpitrix-project on product cluster also get empty. But helm install manually with the same chart tgz can create workload on product cluster.

**Versions Used**
KubeSphere: v3.0.0

**Expected behavior**
App test deploy can ceate workload,  and both users with correct access can view apps deployed.

**Comment by zheng1** [comment]
Please upload the chart tgz of this app

**Comment by Ma-Dan** [comment]
This is the chart tgz file
[https://apptest-bucket.sh1a.qingstor.com/tensorflow-notebook-0.1.2.tgz](https://apptest-bucket.sh1a.qingstor.com/tensorflow-notebook-0.1.2.tgz)

**Comment by Ma-Dan** [comment]
This should be the chart's problem, other charts can test deploy successfully.

**Comment by zheng1** [comment]
In the latest version, OpenPitrix uses the latest Helm package as SDK. Cannot handle hooks correctly, just delete the "helm.sh/hook" annotation and it can work well. 
![截屏2020-08-11 16 04 45](https://user-images.githubusercontent.com/4156721/89873222-af6ad380-dbec-11ea-8592-80269cb51db5.png)

We will find out how to fix it in 3.1.0

/millstone 3.1.0
/priority medium

**Comment by Ma-Dan** [comment]
Verified, close issue.
