### ISSUE TITLE
Alarm rules have been met, but there are no alarms

### ISSUE THREAD

**Issue by Forest-L** [kubesphere/kubesphere#2834]
* Alarm rules have been met, but there are no alarms
![image](https://user-images.githubusercontent.com/50984129/89769436-b8e23600-db2f-11ea-88a0-52b1e9424dbc.png)
![image](https://user-images.githubusercontent.com/50984129/89769448-bbdd2680-db2f-11ea-9e2f-abbf591b1d17.png)
![image](https://user-images.githubusercontent.com/50984129/89769458-bed81700-db2f-11ea-985d-e919477ebb34.png)
![image](https://user-images.githubusercontent.com/50984129/89769565-e9c26b00-db2f-11ea-850b-877c221e021c.png)

**Comment by junotx** [comment]
@huanggze `http://ks-apiserver.kubesphere-system.svc/kapis/monit
oring.kubesphere.io/v1alpha3/namespaces/test/workloads/deployment?resources_filter=nginx-gty3r1|nginxaa-v1|mysql-e-6ctygc-mysql-exporter|m
ysql-u70ph8|testapp-nginx|nginx8-v1|nginx6-v1|nginx5-v1|nginx4-v1|nginx3-v1|nginx2-v1|nginx1-v1|ratings-v1|details-v1|reviews-v1|productpa
ge-v1|tomcat-v1|nginx-v1&metrics_filter=workload_cpu_usage` did not respond properly, and `resources_filter` parameter did not take effect.
![image](https://user-images.githubusercontent.com/49136171/89784076-a295a380-db4a-11ea-9256-4d74f42fa383.png)
