### ISSUE TITLE
Copy related to network policy needs to be translated

### ISSUE THREAD

**Issue by duanjiong** [kubesphere/kubesphere#2836]
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/3678855/89848102-4b2e1c80-dbb8-11ea-97af-ed192ca11f0e.png)

**Versions Used**
KubeSphere: 3.0-dev
Kubernetes: (If KubeSphere installer used, you can skip this)

**Comment by leoendless** [comment]
The translation process is quite complicated and difficult to maintain. It is better to use this text directly.

**Comment by rayzhou2017** [comment]
It is composed by static text and variables piece by piece. So it is indeed not easy to localize. Let's put it in next release.
![Screen Shot 2020-08-12 at 11 40 22 AM](https://user-images.githubusercontent.com/28859385/89972527-a6cbd900-dc90-11ea-9ef8-664932a70da0.png)
