### ISSUE TITLE
kubesphere 3.0-dev jenkins The background error：org.acegisecurity.userdetails.UsernameNotFoundException: User admin not found in directory

### ISSUE THREAD

**Issue by ynhao** [kubesphere/kubesphere#2838]
Hi,
      After the kubesphere Jenkins installation components, using kubesphere admin account login Jenkins front-end error: do not use the User name or password, the background last error: org. Acegisecurity. Populated userdetails. UsernameNotFoundException: User admin not found in the directory

**Comment by deerjoe** [comment]
has same issue

**Comment by LinuxSuRen** [comment]
Hi @ynhao , please check something by the following list:
* Can you create a pipeline via kubesphere DevOps front-end?
  * If you can create it. Does the pipeline work fine?
* Have you got any pods which are error? Please pay attention to these namespaces: kubesphere-devops-system, kubesphere-system

**Comment by yangyang122** [comment]
this problem is resolved?

**Comment by FeynmanZhou** [comment]
> in kubesphere 3.2.1 have the problem ,this problem is resolved?

Hi @yangyang122 ,

As I don't find the associated PR with this issue, I am not sure if it is an existing bug. Could you create a new issue in https://github.com/kubesphere/ks-devops?

**Comment by LinuxSuRen** [comment]
This is not caused by ks-devops. Please pay attention on [the LDAP-related isseus](https://github.com/kubesphere/kubesphere/issues?q=is%3Aissue+is%3Aopen+ldap).
