### ISSUE TITLE
ReadWriteOnce mount storage volume should not be mounted to 2 pods

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2844]
**Describe the Bug**
ReadWriteOnce mounted storage volume, can be mounted to 2 pods
![image](https://user-images.githubusercontent.com/36271543/89864103-f00f2080-dbdd-11ea-9abd-899e7a7b1897.png)

/kind bug
/area storage
/assign @min-zh 
/milestone 3.0.0
/priority medium

**Comment by min-zh** [comment]
i think it's bug of [nfs-client](https://github.com/kubernetes-retired/external-storage/tree/master/nfs-client)

**Comment by stoneshi-yunify** [comment]
nfs-client bug/limitation, please see https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/18

**Comment by stoneshi-yunify** [comment]
Quote from reply of https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/18 :
```
A volume’s AccessModes are descriptors of the volume’s capabilities. They are not enforced constraints. The storage provider is responsible for runtime errors resulting from invalid use of the resource.

this is a common misunderstanding of what the access modes are.
those modes are for matching between PVC's and PV's. nfs support RWO/RWX/ROX but doesn't enforce them. it just one of it's capabilities.
```

Therefore, this issue is working as design.

/close
