### ISSUE TITLE
kubesphere/vendor/github.com/coreos/etcd目录下缺少相关依赖包

### ISSUE THREAD

**Issue by soulseen** [kubesphere/kubesphere#285]
**General remarks**

**Describe the bug(描述下问题)**
执行make build命令，缺少相关依赖包，具体信息如下：
cannot find modified files from git
fmt done
```mkdir -p ./tmp/bin && cp -r ./install/ ./tmp/```
```docker run -it --rm -v `pwd`:/go/src/kubesphere.io/kubesphere -v `pwd`/tmp/cache:/root/.cache/go-build  -w /go/src/kubesphere.io/kubesphere -e GOBIN=/go/src/kubesphere.io/kubesphere/tmp/bin -e USER_ID=`id -u` -e GROUP_ID=`id -g` kubesphere/kubesphere-builder time go install -ldflags '-X kubesphere.io/kubesphere/pkg/version.ShortVersion="advanced-1.0.1-1-g15ef509" -X kubesphere.io/kubesphere/pkg/version.GitSha1Version="15ef50984b7d45ca277f1be273c780eeb4fa94cf" -X kubesphere.io/kubesphere/pkg/version.BuildDate="2019-02-25T19:07:42"' kubesphere.io/kubesphere/cmd/...```
pkg/client/etcdclient.go:20:2: cannot find package "github.com/coreos/etcd/clientv3" in any of:
	/go/src/kubesphere.io/kubesphere/vendor/github.com/coreos/etcd/clientv3 (vendor tree)
	/usr/local/go/src/github.com/coreos/etcd/clientv3 (from $GOROOT)
	/go/src/github.com/coreos/etcd/clientv3 (from $GOPATH)
pkg/client/etcdclient.go:27:2: cannot find package "github.com/coreos/etcd/etcdserver/api/v3rpc/rpctypes" in any of:
	/go/src/kubesphere.io/kubesphere/vendor/github.com/coreos/etcd/etcdserver/api/v3rpc/rpctypes (vendor tree)
	/usr/local/go/src/github.com/coreos/etcd/etcdserver/api/v3rpc/rpctypes (from $GOROOT)
	/go/src/github.com/coreos/etcd/etcdserver/api/v3rpc/rpctypes (from $GOPATH)
pkg/client/etcdclient.go:21:2: cannot find package "github.com/coreos/etcd/pkg/transport" in any of:
	/go/src/kubesphere.io/kubesphere/vendor/github.com/coreos/etcd/pkg/transport (vendor tree)
	/usr/local/go/src/github.com/coreos/etcd/pkg/transport (from $GOROOT)
	/go/src/github.com/coreos/etcd/pkg/transport (from $GOPATH)
Command exited with non-zero status 1
real	0m 21.71s
user	0m 0.57s
sys	0m 1.58s
make: *** [build] Error 1

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
Mac OS 8cpu/8g
go version go1.11.5 darwin/amd64

**Comment by calvinyv** [comment]
@zryfish @wansir 帮忙看一下

**Comment by wansir** [comment]
感谢反馈，可以通过执行`dep ensure`重新拉取依赖，稍后会进行修复

**Comment by soulseen** [comment]
嗯。
