### ISSUE TITLE
Failed to Build a New Service from Source Code Repository

### ISSUE THREAD

**Issue by zheng1** [kubesphere/kubesphere#2851]
**Describe the Bug**
Permission error
![截屏2020-08-11 20 58 31](https://user-images.githubusercontent.com/4156721/89900368-41d39d00-dc16-11ea-9409-ae29c50c114d.png)

**Versions Used**
KubeSphere: 3.0.0

**How To Reproduce**

Build a New Service from Source Code Repository
Language Type : java

**Expected behavior**

**Comment by wansir** [comment]
The issue is already fixed, apply the latest configuration to verify.
```
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml
```

**Comment by zheng1** [comment]
Fixed in latest version
