### ISSUE TITLE
multi-cluster project created in single cluster workspace is not displayed in the host cluster

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2854]
**Describe the Bug**
multi-cluster project created in single cluster workspace is not displayed in the host cluster
<img width="799" alt="host cluster" src="https://user-images.githubusercontent.com/36271543/89969556-45ecd280-dc89-11ea-89ea-7a2c0a8ff0ff.png">

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority high

**Comment by zryfish** [comment]
Work as expected, namespace on the host cluster is where the multicluster project metadata saved, we don't want users to change them randomly, so we hide them temporarily. We can find a better way to handle this later.
/milestone 3.1.0
