### ISSUE TITLE
create allert policy error when notification component not installed

### ISSUE THREAD

**Issue by min-zh** [kubesphere/kubesphere#2856]
**Describe the Bug**
When Notificaiton component not installed,  creating Allert Policy has error in UI. 

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/35321102/89986292-e5708c00-dcae-11ea-973d-e93e96cc8e89.png)

**Versions Used**
KubeSphere: v3.0.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Comment by rayzhou2017** [comment]
Should hide the notification tab page if no notification module installed. But I think it is OK for now since without notification module installed, alerting does not make sense.

**Comment by leoendless** [comment]
These two modules are strongly coupled, and it is risky to distinguish them in the console currently.

**Comment by zryfish** [comment]
/

**Comment by leoendless** [comment]
Yes, we are going to refactor current page with custom alerting
