### ISSUE TITLE
The processing advice information in the alarm message is not displayed

### ISSUE THREAD

**Issue by Forest-L** [kubesphere/kubesphere#2857]
* create information

![image](https://user-images.githubusercontent.com/50984129/89986433-22d51980-dcaf-11ea-996b-a52c7e30aa0d.png)

* information succeed
![image](https://user-images.githubusercontent.com/50984129/89986581-53b54e80-dcaf-11ea-8260-4f25717f4157.png)

* The processing advice information in the alarm message is not displayed

![image](https://user-images.githubusercontent.com/50984129/89986683-78a9c180-dcaf-11ea-84a3-3c7363509f2c.png)

/assign @leoendless @junotx

**Comment by rayzhou2017** [comment]
It works in my env. You'd better to provide your env for reproducing.

![Screen Shot 2020-08-12 at 4 46 07 PM](https://user-images.githubusercontent.com/28859385/89994911-587fff80-dcbb-11ea-908f-61dc7f261ce5.png)

**Comment by rayzhou2017** [comment]
I know what the problem is. It does not refresh automatically. This is a minor bug.

**Comment by Forest-L** [comment]
This may be caused by insufficient environmental resources
