### ISSUE TITLE
If the check does not pass, the page does not give prompt message

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2858]
**Describe the Bug**
Bitbucket Server address verification failed when creating pipeline, and no prompt message was given on the page

![image](https://user-images.githubusercontent.com/36271543/89988476-2e760f80-dcb2-11ea-8e38-f4bf7f056e7b.png)

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority low

**Comment by harrisonliu5** [comment]
https://github.com/kubesphere/console/pull/1170
