### ISSUE TITLE
Using the Bitbucket repository, exception occurred

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2859]
**Describe the Bug**
An exception occurred when the Bitbucket repository was used to create the pipeline
![image](https://user-images.githubusercontent.com/36271543/89991598-a21a1b80-dcb6-11ea-9c1a-dc32e528aee1.png)

/kind bug
/area devops
/assign @shaowenchen 
/milestone 3.0.0
/priority high

**Comment by shaowenchen** [comment]
1，generate id from random numbers, not md5(url, username, password)
2,  use ~username replace username to get repo list 

@harrisonliu5

**Comment by liuyp2018** [comment]
Operator role user, report 403 error

![image](https://user-images.githubusercontent.com/36271543/90362139-7a4dfd80-e092-11ea-9940-50c64c39f65d.png)

/remove-kind need-to-verify

**Comment by wansir** [comment]
> Operator role user, report 403 error
> 
> ![image](https://user-images.githubusercontent.com/36271543/90362139-7a4dfd80-e092-11ea-9940-50c64c39f65d.png)
> 
> /remove-kind need-to-verify

kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml

Fix unexpected forbidden response.
