### ISSUE TITLE
The submission record is not displayed on the pipeline activity details page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2861]
**Describe the Bug**
The submission record is not displayed on the pipeline activity details page

![image](https://user-images.githubusercontent.com/36271543/90000814-34c0b780-dcc3-11ea-88e7-85d0001901c3.png)

**Versions Used**
host-k8s:  v1.15.12
member-k8s: v1.18.6

/kind bug
/area console
/assign @leoendless
/milestone 3.1.0
/priority medium

**Comment by liuyp2018** [comment]
not fixed yet
/remove-kind need-to-verify

**Comment by harrisonliu5** [comment]
The current commit can only be displayed when it is entered through the PR list, and there is no data for other pipelines. It needs to be confirmed again in 3.1

![image](https://user-images.githubusercontent.com/17872673/90364781-44f7de80-e097-11ea-921c-21b1cc836250.png)

![image](https://user-images.githubusercontent.com/17872673/90364805-52ad6400-e097-11ea-95d9-f36e604bebab.png)
