### ISSUE TITLE
Workbench/Cluster Management/jobs，The job created using upload YAML was not successful

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#2876]
Describe the Bug
jobs list,Sorting by “Last Executed Time” is wrong

Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30881/

How To Reproduce
1.Log in with account 'A'
2.Click 'workbench'
3.Click 'cluster number'
4.click any 'cluster’
5.click 'jobs'
6.click ‘create’
7.click 'Edit More'
8.upload yaml

Expected behavior
create job successful
Actual behavior
The popover indicates that the creation was successful, but there is no newly created job in the list
/kind bug
/area console
/assign @wansir
/milestone 3.1.0
/priority medium

**Comment by leoendless** [comment]
Please attach your YAML file.

**Comment by wenxin-01** [comment]
[wxjob41-zs9kw.kubesphere-devops-system.pod.yaml.zip](https://github.com/kubesphere/kubesphere/files/5073766/wxjob41-zs9kw.kubesphere-devops-system.pod.yaml.zip)

**Comment by wenxin-01** [comment]
The YAML file is downloaded from the created job

**Comment by leoendless** [comment]
You should use a job YAML, not the pod.

**Comment by wenxin-01** [comment]
use a job yaml, page prompt error。
![image](https://user-images.githubusercontent.com/68640256/90361826-bb91dd80-e091-11ea-9f61-37be485488e4.png)
[wx1355.kubesphere-devops-system.job.yaml.zip](https://github.com/kubesphere/kubesphere/files/5082398/wx1355.kubesphere-devops-system.job.yaml.zip)

**Comment by leoendless** [comment]
This is normal, there are some automatically generated attributes that need to be removed.
