### ISSUE TITLE
repeated network policies can be added

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2878]
**Describe the Bug**
The option to add network policies does not filter added network policies, and duplicate network policies can be added
![image](https://user-images.githubusercontent.com/36271543/90265756-9892de00-de85-11ea-9d87-5697afb0fcac.png)
![image](https://user-images.githubusercontent.com/36271543/90265793-aba5ae00-de85-11ea-9a9b-c9fa70854267.png)

/kind bug
/area console
/assign @leoendless
/milestone 3.1.0
/priority medium

**Comment by duanjiong** [comment]
This shouldn't be a bug, the two policies added here don't have the same name, just the same content, and as a native k8s network policy, it's also possible to add policies with the same content, just like it's allowed to create pods with the same content. Maybe it's weird for users to see the same content here.
