### ISSUE TITLE
The ui cannot view the cluster log, audit and events data

### ISSUE THREAD

**Issue by shenhonglei** [kubesphere/kubesphere#2879]
**Describe the Bug**
The interface cannot view the cluster log, audit and events data

**Versions Used**
KubeSphere Version : v3.0.0
Kubernetes: v1.17.9
<img width="1630" alt="log-search" src="https://user-images.githubusercontent.com/20896372/90327970-2af0ca00-dfcb-11ea-8014-49a79f6c2995.png">
<img width="1680" alt="event-search" src="https://user-images.githubusercontent.com/20896372/90327976-393ee600-dfcb-11ea-9c1b-6f9663353b13.png">
<img width="1639" alt="audit" src="https://user-images.githubusercontent.com/20896372/90327978-3f34c700-dfcb-11ea-93b8-886eb3b62971.png">

**Environment**
CentOS Linux release 7.6.1810 (Core)  / 3 masters:  8cpu/16g/100 G; 3 nodes: 8cpu/16g/100 G
    etcd:
    - master1
    - master2
    - master3
    master: 
    - master1
    - master2
    - master3
    worker:
    - node1
    - node2
    - node3
<img width="1399" alt="master+node" src="https://user-images.githubusercontent.com/20896372/90327983-478d0200-dfcb-11ea-9aa6-b87fc76577d1.png">
<img width="1680" alt="服务组件2" src="https://user-images.githubusercontent.com/20896372/90328005-7efbae80-dfcb-11ea-8bf4-baee5c9380d7.png">

**How To Reproduce**
1. Go to 'Toolbox'
2. Click on 'analysis tools: log search、event search、auditing search'
3. See error

**Expected behavior**
Can view log, event, aduiting data

**Comment by shenhonglei** [comment]
KubeSphere On  VMware vSphere
***vSphere Client version 7.0.0.10400***

**Comment by rayzhou2017** [comment]
Please send your login info to kubesphere@yunify.com so that we can log in to check what is going on.

**Comment by shenhonglei** [comment]
> Please send your login info to [kubesphere@yunify.com](mailto:kubesphere@yunify.com) so that we can log in to check what is going on.

sent email

**Comment by huanggze** [comment]
What's difference between  vSphere machines and your member machines?

Can we look into your vSphere machines? Teamviewer v12 is preferred

**Comment by huanggze** [comment]
Or you can check hostPath specified in Fluent Bit DaemonSet in  kubesphere-logging-system. Do those dirs exist in your vSphere machines?

**Comment by shenhonglei** [comment]
system: Mac
TV version:15.0.24
ID:900 850 085
pwd: 1k89he

**Comment by rayzhou2017** [comment]
Is this problem solved?

**Comment by shenhonglei** [comment]
He @huanggze knows the reason, the installation document has been given, and he wants to reproduce.

**Comment by huanggze** [comment]
Need to manually configure logging driver

https://docs.docker.com/config/containers/logging/configure/

**Comment by shenhonglei** [comment]
#查看docker的状态，找到/usr/lib/systemd/system/docker.service
systemctl status docker
#check docker.service to change EnvironmentFile=-/etc/sysconfig/docker
cat /usr/lib/systemd/system/docker.service
#edit /etc/sysconfig/docker 
vi /etc/sysconfig/docker
#OPTIONS='--selinux-enabled --log-driver=journald --signature-verification=false'
#OPTIONS='--selinux-enabled --signature-verification=false'
#edit daemon.json
vi /etc/docker/daemon.json
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3",
    "labels": "production_status",
    "env": "os,customer"
  }
}
sudo systemctl daemon-reload
sudo systemctl restart docker

[see more detail](https://docs.docker.com/config/containers/logging/configure/)
