### ISSUE TITLE
After you type in the workspaces search box, do not click Enter. After clicking the refresh button on the page, it should Filters out what is entered in the input box

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#2880]
Describe the Bug
After you type in the workspace search box, do not click enter. After clicking the refresh button on the page, it should Filters out what is entered in the input box

Versions Used
KubeSphere:3.0.0

Environment
testing env
http://139.198.12.26:30881/

How To Reproduce
1.Click 'workbench'
2.Click 'workspaces'
3.Enter 'test' in the search box
4.do not click enter
5.clicking the refresh button on the page

Expected behavior
The list displays the workspace containing test

Actual behavior
The list displays all workspace

/kind bug
/area console
/assign @leoendless
/milestone 3.1.0
/priority low

**Comment by leoendless** [comment]
I don’t think it is appropriate to display search results when refreshing the list. We should keep each function simple.

**Comment by wenxin-01** [comment]
You have a point there, but I think this kind of user experience will be better
