### ISSUE TITLE
Harbor username pass error

### ISSUE THREAD

**Issue by eeokee** [kubesphere/kubesphere#2881]
**Describe the Bug**

I created a harbor user robot$ci
![image](https://user-images.githubusercontent.com/3079825/90373434-7b882600-e0a4-11ea-8bd0-15e4f117931a.png)

Then add a secret
![image](https://user-images.githubusercontent.com/3079825/90373897-36b0bf00-e0a5-11ea-974e-3ec808a220b4.png)

But in devops pipeline this name is robot$$ci
![image](https://user-images.githubusercontent.com/3079825/90373654-d3bf2800-e0a4-11ea-8b6d-88f7136dd3ff.png)

User robot$ci can login in console 

**Versions Used**
KubeSphere: v3.0
Kubernetes: 1.18.6

**How To Reproduce**
1. use devops's project: https://github.com/kubesphere/devops-java-sample
 

**Expected behavior**
Do not replace username $ to $$

**Comment by yuswift** [comment]
Sorry for the late reply. In short, you can not use `harbor robot account` by Jenkins credential. You must pass it to `docker login -u ` apparently. See the [docs](https://github.com/kubesphere/website/pull/411/files) for more details.
