### ISSUE TITLE
Upgrading from K8s 1.15.5/KS 2.1.1 to K8s 1.18.6/ KS 3.0.0, volume snapshot can not use 

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/kubesphere#2883]
**Describe the Bug**
Volume snapshot CRDs are not upgraded and user can not create snapshot from UI.
![image](https://user-images.githubusercontent.com/38337958/90395600-59ec6600-e0c7-11ea-90c6-1a7e8e3dacf0.png)
![image](https://user-images.githubusercontent.com/38337958/90395605-5ce75680-e0c7-11ea-8b21-0a3d00e74351.png)

**Environment**
3 nodes HA master (master1 192.168.10.8, master2 192.168.10.9, master3 192.168.10.10) 8C16G
3 worker nodes (node1 192.168.10.11, node2 192.168.10.12, node3 192.168.10.13) 8C16G

**Comment by rayzhou2017** [comment]
any update? @min-zh

**Comment by min-zh** [comment]
> any update? @min-zh

yes，this has been fixed

**Comment by Ma-Dan** [comment]
Update:
After upgraded to 3.0.0, crd is updated to v1beta1 today, but then I did a test which needs to enable Network Policy which 2.1.1 is not suppoted, after edit cluster config with ```kubectl edit cc ks-installer -n kubesphere-system```, ks-installer run again and snapshort crd is deleted, then user will get 404 error when creating snapshow from UI.
![image](https://user-images.githubusercontent.com/38337958/90872396-26fbe800-e3cf-11ea-8d87-288a5b80142d.png)

**Comment by benjaminhuo** [comment]
@pixiake would you take a look why cc deletes the snapshot crd?

**Comment by pixiake** [comment]
https://github.com/kubesphere/ks-installer/pull/1072

**Comment by Ma-Dan** [comment]
Qingcloud CSI need to be upgraded to work with snapshot CRD. So this issue https://github.com/kubesphere/kubekey/issues/249 must also be solved.

**Comment by benjaminhuo** [comment]
@min-zh @zheng1 snapshot feature depends on new QingCloud CSI plugin?

**Comment by min-zh** [comment]
> @min-zh @zheng1 snapshot feature depends on new QingCloud CSI plugin?

yes, old Qingcloud CSI plugin's snapshot fearture based on alpha CRD.

**Comment by benjaminhuo** [comment]
Snapshot feature should work on other cloud like aws or aliyun, right?  In such case, snapshot feature will not depend on QingCloud CSI plugin. So it's platform/cloud dependent actually.

**Comment by min-zh** [comment]
> Snapshot feature should work on other cloud like aws or aliyun, right? In such case, snapshot feature will not depend on QingCloud CSI plugin. So it's platform/cloud dependent actually.

yes, snapshot work any other cloud. In other cloud, aliyun-csi or aws-csi will be used. If aliyun-csi or aws-csi supported snapshot fearture, Snapshot Featrure can be used on KubeSphere.
