### ISSUE TITLE
Old jaeger operator is not deleted after upgrading from K8s 1.15.5/KS 2.1.1 to K8s 1.18.6/ KS 3.0.0

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/kubesphere#2884]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/38337958/90395971-0595b600-e0c8-11ea-9251-ce71d7e4d883.png)

**Environment**
3 nodes HA master (master1 192.168.10.8, master2 192.168.10.9, master3 192.168.10.10) 8C16G
3 worker nodes (node1 192.168.10.11, node2 192.168.10.12, node3 192.168.10.13) 8C16G
Ubuntu 18.04

**Expected behavior**
Old jaeger operator is deleted.

**Comment by Ma-Dan** [comment]
Verified on Debian 9.8 k8s 1.14.8/KS2.1.1 -> k8s 1.16.13/KS3.0.0 upgading.

**Comment by rayzhou2017** [comment]
So is it OK to close?

**Comment by Ma-Dan** [comment]
I will verify it one more time on next upgrading test and then close.

**Comment by Ma-Dan** [comment]
Verified, close issue.
