### ISSUE TITLE
error occur when set incorrect bitbucket repo url

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2885]
**Describe the Bug**
error occur when set incorrect bitbucket repo url

![image](https://user-images.githubusercontent.com/36271543/90474306-923b8500-e157-11ea-84cf-f291bc900b52.png)

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority low

**Comment by leoendless** [comment]
@harrisonliu5 Is this problem fixed?

**Comment by harrisonliu5** [comment]
yes, this problem is fixed

**Comment by liuyp2018** [comment]
fixed
/close
