### ISSUE TITLE
[Proposal] Potential code quality issues found

### ISSUE THREAD

**Issue by chsatyap** [kubesphere/kubesphere#2889]
I forked this repo a while ago and ran a DeepSource analysis on it. DeepSource found a variety of different issues categorized based on their types and severity which you can view [here](https://deepsource.io/gh/chsatyap/kubesphere/).

Brief description -
Anti-Patterns: 194
Bug Risks: 413
Performance issues: 17
Security Issues: 5

You can find a detailed description and fixes for some of them [here](https://deepsource.io/gh/chsatyap/kubesphere/issues/?category=recommended).

Please let me know what issues you'd like to focus on fixing and I'd be happy to take a look into it. Also, you can choose to hide certain types of issues too (if you wish to ignore them or you believe it is a false positive). I'd also be happy to send a patch with the DeepSource configuration file with the required fixes.

You can find the required configuration file for DeepSource [here](https://github.com/chsatyap/kubesphere/blob/master/.deepsource.toml).

**Comment by zryfish** [comment]
Thanks for your interest. We will look into the results.

**Comment by chsatyap** [comment]
Alright! If you need anything else, lmk!
