### ISSUE TITLE
ingress to specific path of service

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2890]
When create a route rule, user wants to route to a specific path of a service.
<img width="998" alt="Screen Shot 2020-08-19 at 12 15 56 PM" src="https://user-images.githubusercontent.com/28859385/90591587-09cfe980-e216-11ea-9196-f80114e55d69.png">

**Comment by zryfish** [comment]
It can be achieved by annotation https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#rewrite 

/close
