### ISSUE TITLE
miss devops project creator after upgrading 2.1.1 to 3.0.0

### ISSUE THREAD

**Issue by junotx** [kubesphere/kubesphere#2893]
**Describe the Bug**
the creator is gone after upgrading
![image](https://user-images.githubusercontent.com/49136171/90603851-84a4fe80-e22e-11ea-92f3-59ae77ab1778.png)

**Versions Used**
upgrade ks2.1.1(k8s1.16.7) to ks3.0.0(k8s1.16.7), including one master(4c8g) and two nodes(8c16g)

/assign @wansir
/area upgrade
/kind bug
/milestone 3.0.0

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/90611276-19145e80-e239-11ea-9e9e-a5906986b445.png)

@harrisonliu5

**Comment by harrisonliu5** [comment]
in 3.0 https://console.kubesphere.io/testliu/clusters/shire/devops/asdk8w6j/base-info

![image](https://user-images.githubusercontent.com/17872673/90617393-364d2b00-e241-11ea-97d2-fefc80a89dec.png)

**Comment by shaowenchen** [comment]
fixed

/kind need-to-verify

**Comment by junotx** [comment]
verified
/close
