### ISSUE TITLE
When creating workspace, private clusters should not be displayed

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2896]
**Describe the Bug**
When creating workspace, private clusters should not be displayed
![image](https://user-images.githubusercontent.com/36271543/90613174-96d96980-e23b-11ea-810c-6e685cdd845b.png)

/kind bug
/area iam
/assign @wansir 
/milestone 3.1.0
/priority medium

**Comment by zryfish** [comment]
@liuyp2018 which user are you using

**Comment by liuyp2018** [comment]
> @liuyp2018 which user are you using

User of custom workspace management role
