### ISSUE TITLE
Push images to kubesphere repo 

### ISSUE THREAD

**Issue by zryfish** [kubesphere/kubesphere#2899]
The following images needed to be pushed to the official image repo before release.

- [x] kubespheredev/ks-apiserver:latest -> kubesphere/ks-apiserver:v3.0.0
- [x] kubespheredev/ks-controller-manager:latest -> kubesphere/ks-controller-manager:v3.0.0
- [x] kubespheredev/ks-console:latest -> kubesphere/ks-console:v3.0.0
- [x] kubespheredev/tower:latest -> kubesphere/tower:v0.1.0

/priority high
/assign
/milestone 3.0.0

**Comment by shaowenchen** [comment]
## devops

kubespheredev/jenkins-uc:v3.0.0 -> kubesphere/jenkins-uc:v3.0.0
kubespheredev/ks-devops:flyway-v3.0.0 -> kubesphere/ks-devops:flyway-v3.0.0

**Comment by wanjunlei** [comment]
- [ ] kubespheredev/kube-auditing-operator:v0.1.0 -> kubesphere/kube-auditing-operator:v0.1.0
- [ ] kubespheredev/kube-auditing-webhook:v0.1.0 -> kubesphere/kube-auditing-webhook:v0.1.0

**Comment by wansir** [comment]
* [ ] kubespheredev/ks-upgrade:latest -> kubesphere/ks-upgrade:v3.0.0

**Comment by junotx** [comment]
- [ ] kubespheredev/log-sidecar-injector:1.1 -> kubesphere/log-sidecar-injector:1.1
- [ ] kubespheredev/kube-events-operator:v0.1.0 -> kubesphere/kube-events-operator:v0.1.0
- [ ] kubespheredev/kube-events-exporter:v0.1.0 -> kubesphere/kube-events-exporter:v0.1.0
- [ ] kubespheredev/kube-events-ruler:v0.1.0 -> kubesphere/kube-events-ruler:v0.1.0
- [ ] kubespheredev/notification:flyway_v2.1.2 -> kubesphere/notification:flyway_v2.1.2
- [ ] kubespheredev/notification:v2.1.2 -> kubesphere/notification:v2.1.2
- [ ] kubespheredev/alerting-dbinit:v3.0.0 -> kubesphere/alerting-dbinit:v3.0.0
- [ ] kubespheredev/alerting:v2.1.2 -> kubesphere/alerting:v2.1.2
- [ ] kubespheredev/alert_adapter:v3.0.0 -> kubesphere/alert_adapter:v3.0.0

**Comment by huanggze** [comment]
- [ ] kubespheredev/fluentbit-operator:v0.2.0 -> kubesphere/fluentbit-operator:v0.2.0
- [ ] kubespheredev/fluentbit-operator:migrator -> kubesphere/fluentbit-operator:migrator
- [ ] kubespheredev/fluent-bit:v1.4.6 -> kubesphere/fluent-bit:v1.4.6

**Comment by zryfish** [comment]
```
kubesphere/ks-apiserver:v3.0.0
kubesphere/ks-controller-manager:v3.0.0
kubesphere/ks-console:v3.0.0
kubesphere/tower:v0.1.0
kubesphere/jenkins-uc:v3.0.0
kubesphere/ks-devops:flyway-v3.0.0
kubesphere/kube-auditing-operator:v0.1.0
kubesphere/kube-auditing-webhook:v0.1.0
kubesphere/ks-upgrade:v3.0.0
kubesphere/log-sidecar-injector:1.1
kubesphere/kube-events-operator:v0.1.0
kubesphere/kube-events-exporter:v0.1.0
kubesphere/kube-events-ruler:v0.1.0
kubesphere/notification:flyway_v2.1.2
kubesphere/notification:v2.1.2
kubesphere/alerting-dbinit:v3.0.0
kubesphere/alerting:v2.1.2
kubesphere/alert_adapter:v3.0.0
kubesphere/fluentbit-operator:v0.2.0
kubesphere/fluentbit-operator:migrator
kubesphere/fluent-bit:v1.4.6
```

**Comment by zheng1** [comment]
Has this issue been completed yet? @zryfish
