### ISSUE TITLE
为什么github下载的没有安装脚本？

### ISSUE THREAD

**Issue by pennpeng** [kubesphere/kubesphere#290]
同题目？？？？

**Comment by calvinyv** [comment]
您好，目前此开源项目为 kubesphere 社区版的后端代码，我们会有计划的将前端、installer 等组件的代码逐步开源。如果您想下载带有安装脚本的安装包，可访问 https://docs.kubesphere.io/advanced-v1.0/zh-CN/installation/intro/ ，参考文档指引下载

**Comment by huapox** [comment]
同问+1

像之前caicloud/cyclone就是放个半成品，博噱头。
前后端都要开源出来，并建议具备让大家可以自行安装的方式， 
这样他人受益的基础，才能玩转并反馈，进而推进项目的迭代，
再者这样才是真正借助开源塑造产品，同时也回报于社区的可行之道。

**Comment by calvinyv** [comment]
@huapox 前后端肯定会开源，请放心。KubeSphere 的团队还在成长，我们暂时没法铺太多的人力在开源的运营上，但我们已经加入的cncf，并对cncf承诺未来会全开源，所以请放心。现在团队基本都铺在新版发布的事情上，预计五月份到六月份会抽出一部分人力整理开源相关的资料。

**Comment by pennpeng** [comment]
@huapox 你说的对，不过是博眼球噱头罢了

**Comment by rayzhou2017** [comment]
先直接到https://kubesphere.io上下载安装体验，官网下载的是完整的安装包，安装就可以用，没有任何block的东西，人手有限，前端开源需要点时间整理，后端一直是开源的。
