### ISSUE TITLE
Ver 3.0 on EKS. At pipline page run job , they dont have any option.     

### ISSUE THREAD

**Issue by niutendo** [kubesphere/kubesphere#2905]
on the pipline page
![image](https://user-images.githubusercontent.com/17611978/90760394-674a6000-e314-11ea-80c5-d556a4d9e9dc.png)
![image](https://user-images.githubusercontent.com/17611978/90760408-6e716e00-e314-11ea-89c5-dda41402737a.png)

in to the job
![image](https://user-images.githubusercontent.com/17611978/90760626-bee8cb80-e314-11ea-8b9b-68b2a57d4026.png)
![image](https://user-images.githubusercontent.com/17611978/90760543-a37dc080-e314-11ea-830e-3b3f744ab4c1.png)

**Comment by zheng1** [comment]
@harrisonliu5 Please check to ensure that the issue is already fixed. If it has been fixed, you can close it.
