### ISSUE TITLE
How does Kubesphere 3.0 synchronize external OpenLDAP accounts for centralized authentication?

### ISSUE THREAD

**Issue by weekyuan** [kubesphere/kubesphere#2908]
The injection-Ks-account.sh script is not available because the Ks-Account resource object is no longer found in Kubesphere 3.0.
How do I do that?

**Comment by wansir** [comment]
LDAP identity provider is supported in 3.0, we will explain how to configure it in the documentation.

**Comment by technologynongmin** [comment]
> LDAP identity provider is supported in 3.0, we will explain how to configure it in the documentation.

how to configure it

**Comment by xiaomabetter** [comment]
how to configure it

**Comment by wansir** [comment]
@technologynongmin @xiaomabetter 

https://5f83bcd16abf8c0008b60e2e--kubesphere-v3.netlify.app/docs/access-control-and-account-management/configuring-authentication/

https://github.com/kubesphere/website/blob/064b2f8b9d39150e1ed4445dff22094e84ca8aa4/content/en/docs/access-control-and-account-management/configuring-authentication.md
