### ISSUE TITLE
Platform-regular +workspace-regular+ project-Operator role, query and export the log, the log file is empty

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2911]
**Describe the Bug**
Platform-regular +workspace-regular+ project-Operator role, query and export the log, the log file is empty
![image](https://user-images.githubusercontent.com/36271543/90868174-092b8480-e3c9-11ea-92a9-fcc4690966cf.png)

/kind bug
/area logging
/assign @huanggze 
/milestone 3.0.0
/priority high

**Comment by huanggze** [comment]
https://github.com/kubesphere/console/pull/1226
