### ISSUE TITLE
Network policy allow list can not take effect on upgraded cluster

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/kubesphere#2913]
**Describe the Bug**
(1)Create a cluster on CentOS 7.7, k8s 1.16.7/KS2.1.1, then upgraded using kk to k8s 1.18.6/KS3.0.0
(2)Edit cluster config ```kubectl edit cc ks-installer -n kubesphere-system``` to enable network policy
(3)Create a namespace and mysql svc, kubesphere-system could access it using mysql client
(4)Enable network isolation, set allow list to kubepshere-system, kubesphere-system could not access it using mysql client

![image](https://user-images.githubusercontent.com/38337958/90876056-9de7af80-e3d4-11ea-8479-e66c06da6fe7.png)

![image](https://user-images.githubusercontent.com/38337958/90876093-acce6200-e3d4-11ea-9a98-e792fea3cef5.png)
**Environment**
How many nodes and their hardware configuration:
3 nodes HA master (master1 192.168.10.29, master2 192.168.10.30, master3 192.168.10.31) 8C16G
3 worker nodes (node1 192.168.10.32, node2 192.168.10.33, node3 192.168.10.34) 8C16G
calico network

**Expected behavior**
Allow list can work correctly.

**Comment by benjaminhuo** [comment]
network policy relies on the kubesphere.io/namespace lable of a namespace? 
In 2.1.x, there is no such label and that's the reason network policy doesn't work after upgrading ?
@duanjiong

**Comment by duanjiong** [comment]
> network policy relies on the kubesphere.io/namespace lable of a namespace?
> In 2.1.x, there is no such label and that's the reason network policy doesn't work after upgrading ?
> @duanjiong

yes

**Comment by Ma-Dan** [comment]
Verified, close issue.
