### ISSUE TITLE
Expand volume failed

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#2914]
**Describe the Bug**
1. Upgrade ks from 2.1.0 + 1.14.8 -> 3.0.0 + 1.15.12
2. Create a volume with 10g
3. Expand volume to 15g
4. Create a pod and mounted this volume.
5. The volume expanded failed, volume status is `FileSystemResizePending`

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/53003665/90879054-e7d29480-e3d8-11ea-9573-8b55bb85e37a.png)

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
3 master on ubuntu16.4
3 node on ubuntu16.4

/assign @min-zh

**Comment by rayzhou2017** [comment]
any update?

**Comment by min-zh** [comment]
qingcloud-csi not update.

**Comment by min-zh** [comment]
Log of Kube-controller-manager: 
Ignoring the PVC "ns/12" (uid: "b9301c58-eb8a-4594-b4a4-c5a03e75ecab") : didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.

Log of csi-resizer: 
I0826 08:10:09.395574       1 connection.go:184] GRPC error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
W0826 08:10:09.430446       1 common.go:124] CSI driver probe timed out

Refrence:  https://github.com/kubernetes/kubernetes/issues/85253#issuecomment-554192563

add --feature-gates=ExpandCSIVolumes=true  on kubelet. (ExpandCSIVolumes is alpha and false on 1.14&1.15)

**Comment by wanjunlei** [comment]
Does this argument need to add manually? Is there a doc?

**Comment by min-zh** [comment]
@pixiake when k8s upgrade to 1.14&1.15 by kk, kubelet **feature-gate ExpandCSIVolumes=ture** should be set.

**Comment by pixiake** [comment]
https://github.com/kubesphere/kubekey/pull/263

**Comment by wanjunlei** [comment]
verified
/close
