### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by botzill** [kubesphere/kubesphere#292]
Sorry to ask this stupid question, but is there an English version of the dashboard and docs?

Thx!

**Comment by FeynmanZhou** [comment]
Hi @botzill , we do have an English version of the dashboard and docs:

- Installation: We suggest you to install KubeSphere in a single node to preview its dashboard and features, it supports one-click installation, see [Installation Guide](https://kubesphere.io/install).
Could you leave your email here? We will send you the download command directly.

- Docs: https://docs.kubesphere.io/advanced-v1.0/en/installation/intro/   
(Docs is in draft and we are continuing to support internationalization)

You will be able to change the language by following this screenshot after installation.
![image](https://user-images.githubusercontent.com/40452856/54323044-7c589500-4632-11e9-8bbe-c176c811c6aa.png)

Feel free to contact us if you have any questions.

**Comment by botzill** [comment]
Thx @FeynmanZhou!

Will give it a try and see, basically I'm looking for a better management dashboard for k8s.

**Comment by FeynmanZhou** [comment]
> Thx @FeynmanZhou!
> 
> Will give it a try and see, basically I'm looking for a better management dashboard for k8s.

@botzill Yes, KubeSphere is designed as a better management dashboard without learning curve, suggest you to download advanced edition and try it. Could you leave your email, we will send a demo to you.

**Comment by FeynmanZhou** [comment]
Hi @botzill , you can download KubeSphere Installer from this [link](https://kubesphere.anybox.qingcloud.com/s/JE7NWkkT6EaI9Oksr0aJ5HvPFwtO2peL?type=file&id=3114265).

**Comment by botzill** [comment]
Hi @FeynmanZhou , thx for the link. 

I was wondering if it's possible to have a helm chart to install the dashboard?

Thx.

**Comment by FeynmanZhou** [comment]
> Hi @FeynmanZhou , thx for the link.
> 
> I was wondering if it's possible to have a helm chart to install the dashboard?
> 
> Thx.

Hi @botzill , 

The helm chart is still in development. KubeSphere adds some annotations and labels to the k8s native resources, which cannot be completely controlled on KubeSphere right now, It's highly recommended to install the dashboard using [installer](https://kubesphere.anybox.qingcloud.com/s/JE7NWkkT6EaI9Oksr0aJ5HvPFwtO2peL?type=file&id=3114265) before its helm chart ready. 

Thanks.
