### ISSUE TITLE
Research on Volume Monitoring

### ISSUE THREAD

**Issue by min-zh** [kubesphere/kubesphere#2921]
## Introduction
Volume Monitoring on KubeSphere use metrics of Kubelet as data source. In detail, capacity data come from:
- kubelet_volume_stats_available_bytes 
- kubelet_volume_stats_used_bytes 
- kubelet_volume_stats_capacity_bytes

These metrics data can be get from Kubernetes with Prometheus referring to [method](https://github.com/yunify/qingcloud-csi/issues/87#issuecomment-514912319). 
What we expected is: 
* **kubelet_volume_stats_capacity_bytes** == Capacity of the PVC
* **kubelet_volume_stats_used_bytes** == Size of data written in the PVC

On some storage systems, data are correct, like ceph-rbd and common-used cloud-disk. 
However, it seems to be with big difference with we expected when using certain storage systems like **NFS-client**, **OpenEBS/LocalVolume**. 

In this passage, we try to explain how these metrics data collected. Then you will understand the reason of this phenomenon.

### Storage Systems
Choose the following typically storage system to research:
- RBD 
- OpenEBS/LocalPV
- NFS-Client

### Steps 
Steps for each storage system
- Create and attach PVC: two PVC capacity of which are 10G and 20G, and attach them to workload
- Write on PVC: one 2G file on the 10G PVC, one 5G file on the 20G PVC
- Collect data: the **metrics** and capacity of volume **in Pod**, **on Node**

## Create and Attach PVC
 PVC created
```bash
kubectl get pvc
NAME               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc-local          Bound    pvc-56b180e2-99a5-42dd-ae00-699406e93d01   20Gi       RWO            local          4d1h
pvc-local-2        Bound    pvc-4ddafe22-6076-4502-adeb-b421969dcf91   10Gi       RWO            local          103s
pvc-nfs-client     Bound    pvc-d568db09-2a02-450b-8fee-707fb3326f26   20Gi       RWO            nfs-client     4d1h
pvc-nfs-client-2   Bound    pvc-c4049b5a-9633-4f65-9e12-8926c9fb7f2a   10Gi       RWO            nfs-client     103s
pvc-rbd            Bound    pvc-62fff7c9-0272-4305-8d8c-999789a45e9f   20Gi       RWO            rbd            4d1h
pvc-rbd-2          Bound    pvc-60217411-3ec8-4f68-b9b3-e51fadce5593   10Gi       RWO            rbd            103s
```
Workload Created
```bash
kubectl get deployment
NAME                 READY   UP-TO-DATE   AVAILABLE   AGE
nginx-local          1/1     1            1           4d1h
nginx-local-2        1/1     1            1           9m13s
nginx-nfs-client     1/1     1            1           4d1h
nginx-nfs-client-2   1/1     1            1           9m13s
nginx-rbd            1/1     1            1           4d1h
nginx-rbd-2          1/1     1            1           9m13s

kubectl get pod
NAME                                  READY   STATUS    RESTARTS   AGE
nginx-local-2-7848d7f545-wwzjq        1/1     Running   0          6m18s
nginx-local-756d49dcdf-2r77p          1/1     Running   0          4d1h
nginx-nfs-client-2-69cb845557-mgz74   1/1     Running   0          6m18s
nginx-nfs-client-9b998595-wwcnd       1/1     Running   0          4d1h
nginx-rbd-2-86c6b4c557-2294b          1/1     Running   0          6m18s
nginx-rbd-f58f8497-tfxrm              1/1     Running   0          4d1h
```

## Write on PVC
Take 20G rbd PVC for example, write one 5G file on PVC by command:
```bash
kubectl exec -it deployment/nginx-rbd -- dd if=/dev/zero of=/mnt/5G.file bs=1G count=5
```

### Collect Data
We collect capacity data of created PVC from the following aspects:
- Execute **df** in Pod of which the created PVC attached
- Execute **df** on Node of which the created PVC attached
- Get metrics data using [method](https://github.com/yunify/qingcloud-csi/issues/87#issuecomment-514912319)

Take 20G rbd PVC for example, write one 5G file on PVC by command:
#### Data in Pod 
``` bash
kubectl exec -it deployment/nginx-rbd -- df -h /mnt
Filesystem      Size  Used Avail Use% Mounted on
/dev/rbd1        20G  5.1G   15G  26% /mnt
```
#### Data on Node
```bash 
df -h /dev/rbd1
Filesystem      Size  Used Avail Use% Mounted on
/dev/rbd1        20G  5.1G   15G  26% /var/lib/kubelet/plugins/kubernetes.io/rbd/mounts/rbd-image-kubernetes-dynamic-pvc-6f17fc0f-ee7d-11ea-a231-7a8a3ec49482
```
#### Metrics
```json
      {
        "metric": {
          "__name__": "kubelet_volume_stats_capacity_bytes",
          "instance": "192.168.0.21:10250",
          "job": "kubelet",
          "namespace": "default",
          "node": "storage",
          "persistentvolumeclaim": "pvc-rbd"
        },
        "value": [
          1599465884.103,
          "21003583488"
        ]
      }
```
```json
      {
        "metric": {
          "__name__": "kubelet_volume_stats_used_bytes",
          "instance": "192.168.0.21:10250",
          "job": "kubelet",
          "namespace": "default",
          "node": "storage",
          "persistentvolumeclaim": "pvc-rbd"
        },
        "value": [
          1599465920.743,
          "5414875136" 
        ]
      }
```
```json
      {
        "metric": {
          "__name__": "kubelet_volume_stats_available_bytes",
          "instance": "192.168.0.21:10250",
          "job": "kubelet",
          "namespace": "default",
          "node": "storage",
          "persistentvolumeclaim": "pvc-rbd"
        },
        "value": [
          1599472853.421,
          "15571931136"
        ]
      }
```

### Summary
For better comparision, we put capacity data of the PVC into the following table. 

Storage| DataType| Filesystem| Size|Used |Avail |Use% |Mounted on |
---| ---| ---| ---| ---| ---| ---| ---|   
rbd| InPod|   /dev/rbd1| 20G| 5.1G| 15G| 26%| /mnt
rbd| OnNode|  /dev/rbd1| 20G| 5.1G| 15G| 26%| /var/lib/kubelet/plugins/kubernetes.io/rbd/xxx
rbd| Metrics| -| 21003583488| 5414875136| 15571931136|  -| - 
rbd2| InPod|  /dev/rbd2| 9.8G| 2.1G| 7.7G| 21%| /mnt
rbd2| OnNode| /dev/rbd2| 9.8G| 2.1G| 7.7G| 21%| /var/lib/kubelet/plugins/kubernetes.io/rbd/xxx
rbd2| Metrics| -| 10434662400| 2185261056| 8232624128|  -| - 
OpenEBS/LocalVolume| InPod| /dev/vda1| 99G| 27G| 67G| 29%| /mnt
OpenEBS/LocalVolume| OnNode| /dev/vda1| 99G| 27G| 67G| 29%| /
OpenEBS/LocalVolume| Metrics| -| 105552781312| 28382687232| 71785164800| -| -
OpenEBS/LocalVolume2| InPod| /dev/vda1| 99G| 27G| 67G| 29%| /mnt
OpenEBS/LocalVolume2| OnNode| /dev/vda1| 99G| 27G| 67G| 29%| /
OpenEBS/LocalVolume2| Metrics| -| 105552781312| 28382392320| 71785459712| -| -
NFS-Client| InPod|  {NFS}/xx| 99G| 19G| 75G| 21%| /mnt
NFS-Client| OnNode| {NFS}/xx| 99G| 19G| 75G| 21%| /var/lib/kubelet/pods/xxx 
NFS-Client| Metrics| -| 105555296256| 20258488320| 79911321600| -| -
NFS-Client2| InPod|  {NFS}/xx| 99G| 19G| 75G| 21%| /mnt
NFS-Client2| OnNode| {NFS}/xx| 99G| 19G| 75G| 21%| /var/lib/kubelet/pods/xxx 
NFS-Client2| Metrics| -| 105555296256| 20258488320| 79911321600| -| -

## Conclusion
From the table, we could get some conclusions:
1. Command **df** in Pod and on Node get the same data. 
Because volume in Pod is mounted from node by **docker --volume**, so they are the same device or path essentially. 
2. Metrics data is consistent with command **df**. 
See code of **Kubernetes**, we could find kubelet get metric volume data of most storage plugin using [NewMetricsStatFS](https://github.com/kubernetes/kubernetes/blob/323f34858de18b862d43c40b2cced65ad8e24052/pkg/volume/nfs/nfs.go#L129).
Under function NewMetricsStatFS, it is [unix.Statfs](https://github.com/kubernetes/kubernetes/blob/2590f6cc77a7946bd69d71bb3d5ae9d340296b9e/pkg/volume/util/fs/fs.go#L35) used to get capacity data.
Function unix.Statfs is almost the same with command **df**. 
3. Data of the two RBD PVC are different, because they are different **device**.
Device of rbd is **/dev/rbd1/**, and device of rbd2 is **/dev/rbd2**
4. Data of the two OpenEBS/LocalVolume PVC and the two NFS-Client PVC are the same, because the share the same device.

So metrics data of PVC is the **device** capacity data. The data of **device based PVC** is consistent with PVC's capacity and size of data write in PVC like ceph-rbd. 
But if the device of PVC is not occupied only by itself which means that the PVC is one path of filesystem we call **path based PVC**, data may be different.
Path of filesystem does not have capacity data, the metric data is the underlying **device** data.

**Comment by stoneshi-yunify** [comment]
as @min-zh stated in above comments, the metrics data for filesystem based volume could be very wrong, comparing with the PVC's size. This is storage provisioner's problem (or linux restriction), there is no way for KS side to get the correct data.

/close

**Comment by stoneshi-yunify** [comment]
there is no way to calculate the hostpath-based volume usage, users need to know this limitation.
