### ISSUE TITLE
preinstall fatal: [localhost]: FAILED on v1.18.0

### ISSUE THREAD

**Issue by zhangchunsheng** [kubesphere/kubesphere#2922]
TASK [preinstall : Stop if kuernetes version is nonsupport] ********************
fatal: [localhost]: FAILED! => {
    "assertion": "kubernetes_version.stdout is version('v1.18.0', '<')",
    "changed": false,
    "evaluated_to": false,
    "msg": "The current k8s version is not supported"
}

**Comment by FeynmanZhou** [comment]
Please install 3.0.0, k8s 1.18 is already supported in v3.0.0, see this [guide](https://github.com/kubesphere/ks-installer#install-kubesphere-v300-dev-on-existing-kubernetes-cluster).

**Comment by zhangchunsheng** [comment]
> Please install 3.0.0, k8s 1.18 is already supported in v3.0.0, see this [guide](https://github.com/kubesphere/ks-installer#install-kubesphere-v300-dev-on-existing-kubernetes-cluster).

ok
