### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by xuelangos** [kubesphere/kubesphere#2924]
##  v3.0.0 runner Jenkinsfile from gitlab repository,Browser page is blank

Jenkinsfile content
```
pipeline {
   //agent {label 'local-slave'}
   agent any
   
   environment { 
        def registry_url = "hub.xxx.com"
		def imageName = "${group_id}/${project_name}"
		def build_tag = "${registry_url}/${group_id}/${project_name}:${img_tag}"
    }
    parameters {
        choice(choices: 'A\nB', description: '测试一下', name: 'project_name')
        choice(choices: 'RD\nQA\nPRE\nONLINE', description: '环境选择', name: 'runer_env')
        choice(choices: '发布\n回滚', description: '动作选择', name: '执行动作')
        //string(name:'git_url',defaultValue: 'xxxx',description: 'git工程路径')
        string(name:'group_id', defaultValue: 'idc', description: '业务小组')
    }
    stages {
        stage('build') {
            steps {
                echo "Hello World!"
            }
        }
    }
    }
```
*Official example**
>https://github.com/kubesphere/devops-java-sample/blob/master/Jenkinsfile-online
problem at deploy input confirm

*Describe the Bug**
![image](https://user-images.githubusercontent.com/13230347/91280018-cbf43780-e7b8-11ea-8efc-8a7eb2f5aa7c.png)
![image](https://user-images.githubusercontent.com/13230347/91280052-d4e50900-e7b8-11ea-90ad-cb68bdbb4834.png)

**Environment**
How many nodes and their hardware configuration:
os:centos7.8 
node:1master,2work
v:kubespherev3.0.0,kubernetes1.17.9
installer:kubekey

**Comment by harrisonliu5** [comment]
could you show me the config

![image](https://user-images.githubusercontent.com/17872673/91284073-04e2db00-e7be-11ea-8ba2-8210566bbf7f.png)

**Comment by xuelangos** [comment]
> could you show me you're the config in this pipeline?
> 
> ![image](https://user-images.githubusercontent.com/17872673/91284073-04e2db00-e7be-11ea-8ba2-8210566bbf7f.png)

![image](https://user-images.githubusercontent.com/13230347/91288677-dbc54900-e7c3-11ea-9e5e-11fecf047f8d.png)

**Comment by xuelangos** [comment]
No problem at the moment
![image](https://user-images.githubusercontent.com/13230347/91376015-b4678e00-e84e-11ea-9239-ffdbe1ec52ea.png)

**Comment by xuelangos** [comment]
New problem
Option parameters become character parameters
![image](https://user-images.githubusercontent.com/13230347/91376142-01e3fb00-e84f-11ea-97e9-b92b7d24be83.png)

**Comment by harrisonliu5** [comment]
Have you updated the mirror file?

**Comment by xuelangos** [comment]
> Have you updated the mirror file?

yeah, updated  16 hours ago,kubespheredev/ks-console

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/91510357-69fa1600-e90f-11ea-8e50-3e0877a1d4d1.png)

```bash
docker images

REPOSITORY                                TAG                 IMAGE ID            CREATED             SIZE
kubespheredev/ks-console                  latest              6405ad64647e        9 days ago          95.5MB
kubespheredev/ks-controller-manager       latest              a96e816c224f        10 days ago         82MB
kubespheredev/ks-apiserver                latest              2b4c909e94ea        10 days ago         120MB
```

We need to check the latest changes. @harrisonliu5 

/remove-kind need-to-verify

**Comment by harrisonliu5** [comment]
Your problem is that there is no drop-down option in Choice, which causes the test to continue or the function reports an error？

@xuelangos

**Comment by harrisonliu5** [comment]
If there is no drop-down option for choice, the back-end colleague is working on this issue

**Comment by xuelangos** [comment]
> If there is no drop-down option for choice, the back-end colleague is working on this issue

yeah，we can Continue test，but，we need to test the entire process to determine whether to use external jenkins

**Comment by harrisonliu5** [comment]
you should wait a moment until our back-end colleagues have dealt with this issue

**Comment by xuelangos** [comment]
come on  on  on

**Comment by xuelangos** [comment]
try,try,update k-console image，the probelm is still

**Comment by shaowenchen** [comment]
Using kubespheredev/ks-apiserver:latest to test your case

**Comment by xuelangos** [comment]
No problem  at now，oligei
