### ISSUE TITLE
Snapshot created volume attach failed

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/kubesphere#2925]
## English only!

**Describe the Bug**
Create a volume from snapshot, add some annotation and custom meta data. Then create a workload to attach it, attachment failed.
But volume with out annotaion and custom meta data can attach successfully.

![image](https://user-images.githubusercontent.com/38337958/91293270-55f8cc00-e7ca-11ea-9b22-f8dc8f98f91c.png)

**Versions Used**
KubeSphere: v3.0.0

**Environment**
3 nodes HA master 8C16G
3 worker nodes 8C16G
CentOS 7.7

**Expected behavior**
Volume attach successfully.

**Comment by rayzhou2017** [comment]
@leoendless is this a bug?

**Comment by Ma-Dan** [comment]
This maybe not related with annotation, only first volume can attach successfully, following volumes created from same snapshot with or without annotation, iaas tried to attach vox-xxx instead of vol-xxx, attaching with name vox-xxx will fail.

**Comment by min-zh** [comment]
This issue may be put to Qingcloud-CSI. It almost has no relationship with KubeSpehere.
