### ISSUE TITLE
Network policy allow list can not add service from other projects before user is added to them

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/kubesphere#2926]
**Describe the Bug**
Log in with user with access to one project only, then add network policy allow list by service, service from other projects can not list or add. Users should be invited to target project before they can listadd service to source project.

![image](https://user-images.githubusercontent.com/38337958/91376760-65baf380-e850-11ea-844a-b3057aa4ecfe.png)

**Versions Used**
KubeSphere: v3.0.0

**Expected behavior**
Users don't need to be added to target project to list its service.

**Comment by wansir** [comment]
```
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml
```

/kind need-to-verify

**Comment by Ma-Dan** [comment]
Verified, close issue.
