### ISSUE TITLE
bug caused by creating and then deleting user called kubesphere in ks2.1.1

### ISSUE THREAD

**Issue by junotx** [kubesphere/kubesphere#2927]
**Describe the Bug**
the problem is as follows after creating and then deleting user called `kubesphere` in 2.1.1
![image](https://user-images.githubusercontent.com/49136171/91380792-6ce5ff80-e858-11ea-990a-8d1a268dedd3.png)
then clusterrolebinding called `kubesphere` is found to be missing 
![image](https://user-images.githubusercontent.com/49136171/91380895-aa4a8d00-e858-11ea-811b-4a59a3eecfa0.png)

**Versions Used**
KubeSphere(2.1.1)

/assign @wansir 
/kind bug
/area iam

**Comment by wansir** [comment]
Username conflict with existing cluster role binding. In kubesphere 2.x, cluster role binding with the same name as the user will be created, it will conflict with the existing cluster role binding.

This bug was fixed in 3.0.0.

**Comment by zryfish** [comment]
/reopen
/cc @wansir  

Is this bug fixed in v3.0
