### ISSUE TITLE
How can I change platform info?

### ISSUE THREAD

**Issue by zhangchunsheng** [kubesphere/kubesphere#2937]
How can I change platform info?

https://v3-0.docs.kubesphere.io/docs/cluster-administration/platform-settings/customize-basic-information/
There is no information about this.

The title is Role and Member Management.

![image](https://user-images.githubusercontent.com/831839/91690776-1b5fac80-eb99-11ea-99da-af7348403583.png)

**Comment by FeynmanZhou** [comment]
You are allowed to customize the logo after our commercial authorization.

**Comment by zhangchunsheng** [comment]
> You are allowed to customize the logo after our commercial authorization.

Ok, actually I want to use kubesphere for our customers. Anyway I just do some research.
