### ISSUE TITLE
The project is not fully displayed in the workload

### ISSUE THREAD

**Issue by qiaokebaba** [kubesphere/kubesphere#2943]
I have 21 namespaces, all of which have been added to enterprise space, but only 10 are shown in the workload,

**Comment by FeynmanZhou** [comment]
@cool-ops  Not clear with your issue, could you please give any screenshots?

**Comment by RolandMa1986** [comment]
/close
/kind support
/question
Please feel free to reopen the issue, if you think this is a bug.
