### ISSUE TITLE
Project Gateway: provide dynamic nodeport IPs

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2946]
Current gateway of nodeport type chooses one of master nodes which is not good. First it is not HA in multi-node env. Second, some cloud K8s services such as AWS EKS do not expose master info. The proposal is like this. Write a crd, use controller to watch nodes info and randomly choose two of them (in multi-node env) or one (in allinone env) as the gateway IP(s). If there is any node changed such as get down then update the IP(s).

In addition, the LB type might be included in this design.

**Comment by duanjiong** [comment]
The problem is with the front end display, the principle of nodeport is that it works through the same port regardless of which node is accessed.

The load balancer does not add the master to the back end.

**Comment by rayzhou2017** [comment]
It is not front-end responsibility. Backend needs to provide an API for frond-end to show the info since the node list may change. That is why it is using one of the masters right now since master is supposed not to get down but worker node is not guaranteed to be online.

**Comment by leoendless** [comment]
Please check if `kapis/resources.kubesphere.io/v1alpha2/namespaces/{namespace}/router` works right.

**Comment by duanjiong** [comment]
> kapis/resources.kubesphere.io/v1alpha2/namespaces/{namespace}/router

My bad, I thought the front end was getting the node information directly from the display.

**Comment by rayzhou2017** [comment]
You guys may not understand what I am talking about. Please read my first post carefully especially about gateway HA requirement.

**Comment by zryfish** [comment]
Planning using a whole new way to implement gateway. This issue should be resolved then.

**Comment by zheng1** [comment]
@zryfish Is this issue in the plan for 3.1?

**Comment by zryfish** [comment]
yes

**Comment by zryfish** [comment]
#3055

**Comment by zryfish** [comment]
duplicate with #3055 

/close
