### ISSUE TITLE
Does kubesphere v2.1.1 support Alibaba Cloud OSS storage

### ISSUE THREAD

**Issue by haerr** [kubesphere/kubesphere#2949]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**What's your question**
Does kubesphere v2.1.1 support Alibaba Cloud OSS storage？

**Environment: OS & Hardware Information**
alicloud ECS 
> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).
centos7.7  k8sv1.16

**Error logs or message (Attach logs or screenshot)**

**Installer Version**
v2.2.1
> e.g. v2.1.0, v2.1.1

**Comment by stoneshi-yunify** [comment]
@haerr No, KS does not support Alibaba Cloud OSS or any other object storage.

If you want to a mount an object storage to a pod as block/filesystem, it really depends on the OSS vendor whether it has the capability (driver/plugin etc) to let you do this. I checked Alibaba Cloud OSS and it seems it doesn't have such driver/plugin.  But I found IBM has the plugin, you may take a look https://cloud.ibm.com/docs/containers?topic=containers-object_storage#add_cos

/close
