### ISSUE TITLE
Pod boot log visualization requirement

### ISSUE THREAD

**Issue by liaoyinfeng** [kubesphere/kubesphere#2950]
I hope KubeSphere can view the boot log of Pod by web view, easy to maintenance without through kubectl describe pod command.

**Comment by benjaminhuo** [comment]
The boot log you refer to is actually event logs, and KubeSphere 3.0 support this by `Event Query` function. 
The guide is here https://kubesphere.io/docs/toolbox/events-query/ 

And we have an issue opened already to track the correlation of log, events, auditing, monitoring in issue https://github.com/kubesphere/kubesphere/issues/3074.

So I'll close this issue
