### ISSUE TITLE
failed to add external helm repo

### ISSUE THREAD

**Issue by lxm** [kubesphere/kubesphere#2952]
another quesion about app store is that i’ll always got a error " target not reachable" when add an external helm repo

but i can manually add repo use command helm repo add --username xx --password https://my-repo

**Comment by zheng1** [comment]
You can add your repo in the format below.
`https://username:password@your-repo.com/path`

**Comment by FeynmanZhou** [comment]
> You can add your repo in the format below.
> `https://username:password@your-repo.com/path`

@zheng1 This should be included in the documentation 3.0.0
