### ISSUE TITLE
The user password of LDAP does not comply with the rules

### ISSUE THREAD

**Issue by ynhao** [kubesphere/kubesphere#2953]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**What's your question**
Error logging in after accessing AD domain account：
![image](https://user-images.githubusercontent.com/33625720/92192342-611dbd00-ee98-11ea-8ea5-5eb4f486ec01.png)

**Environment: OS & Hardware Information**
centos7.8，18c/44G k8s 1.16.9   ks 3.0

> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).

**Error logs or message (Attach logs or screenshot)**
![image](https://user-images.githubusercontent.com/33625720/92192502-b0fc8400-ee98-11ea-98ea-919b032c07cd.png)

**Installer Version**
3.0.0
> e.g. v2.1.0, v2.1.1

**Comment by wansir** [comment]
/kind bug
/area iam
/assign @wansir @calvinyv 

Currently, `loginAttribute` is mapped to `username` by LDAP login, but the CRD naming convention is different from `uid` and `sAMAccountName`. KubeSphere account binding is required after logging in through a third-party account, to solve the problem of account naming conventions and email conflicts.

**Comment by wansir** [comment]
@ynhao If the username matches `[a-z0-9]([-a-z0-9]*[a-z0-9])?` you can log in directly.  The account binding process needs to be improved.

**Comment by ynhao** [comment]
Okay, thank you. I hope that subsequent versions of ks can be compatible with the naming rules like [a-z0-9]([_a-z0-9]*[ a-z0-9])? of Naming rules

**Comment by ynhao** [comment]
> @ynhao If the username matches `[a-z0-9]([-a-z0-9]*[a-z0-9])?` you can log in directly. The account binding process needs to be improved.

Okay, thank you. I hope that subsequent versions of ks can be compatible with the naming rules like [a-z0-9]([_a-z0-9]*[ a-z0-9])? of Naming rules

**Comment by technologynongmin** [comment]
@ynhao  my kubesphere version is 3.0 , how to configure with openldap  .

**Comment by ynhao** [comment]
> @ynhao my kubesphere version is 3.0 , how to configure with openldap .

Maybe this post can help you https://kubesphere.com.cn/forum/d/2033-ga-ldap-oauth2

**Comment by zryfish** [comment]
/reopen
@wansir Is this issue fixed now?

**Comment by wansir** [comment]
Fixed in https://github.com/kubesphere/kubesphere/pull/3140

Related: https://github.com/kubesphere/kubesphere/pull/3257#issuecomment-755859785

/kind need-to-verify
