### ISSUE TITLE
app status confusion

### ISSUE THREAD

**Issue by lxm** [kubesphere/kubesphere#2954]
1. There is a failure, such as app1. 
2. I forget how to trigger it, and I can deploy a new one still called app1
3. The new app1 is successfully deployed, but the status is always being creating. 
4. Delete the failed app1, and then the normal app1 will be deleted
5. After that, the failed app1 can never be deleted

**Comment by zheng1** [comment]
The current bypass is to delete the apps that failed to deploy before deploying new ones.

We'll fix this in 3.1.
