### ISSUE TITLE
Unable to connect to the server: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by Carriezhangyan** [kubesphere/kubesphere#2958]
**Describe the Bug**
         Unable to connect to the server: x509: certificate has expired or is not yet valid
  

**Versions Used**
KubeSphere:   V2.0.2 

**Environment**
 CentOS 7.5 / 3 masters:  16cpu/32g; 4 nodes: 16cpu/32g

**Expected behavior**
       # kubectl get pod --all-namespaces
          Unable to connect to the server: x509: certificate has expired or is not yet valid

How does a Kubesphere environment regenerate certificates ？

**Comment by wansir** [comment]
The Kubernetes cluster certificates have a lifespan of one year.  [You can renew your certificates manually at any time with the kubeadm alpha certs renew command](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/).
