### ISSUE TITLE
Installation of V3.0.0 using glusterfs failed

### ISSUE THREAD

**Issue by tzghost** [kubesphere/kubesphere#2959]
Environment:
OS: centos7.7 
makster: 3
work: 3
glusterfs node: 4

Multi-node Installation on linux，Kubernetes 1.18.6 and 1.17.9 both failed to install，The following are pod status and failure information：
![image](https://user-images.githubusercontent.com/17000535/92350849-c7127a80-f10c-11ea-97a3-509ab155d9b9.png)

[root@BG-003-KVM004-VMS003 ~]# kubectl describe pod redis-ha-server-2 -n kubesphere-system
![image](https://user-images.githubusercontent.com/17000535/92350898-e3aeb280-f10c-11ea-97a9-357183cfcaf9.png)

[root@BG-003-KVM004-VMS003 ~]# kubectl describe pod minio-764b67f6fb-h98ll -n kubesphere-system
![image](https://user-images.githubusercontent.com/17000535/92351201-997a0100-f10d-11ea-8b13-d2ecf3064096.png)

Glusterfs node looks normal：
![image](https://user-images.githubusercontent.com/17000535/92351115-633c8180-f10d-11ea-82d8-fecfeef32a34.png)

**Comment by FeynmanZhou** [comment]
Could you paste the configuration of **addons** within `config-sample.yaml`?

**Comment by tzghost** [comment]
[root@BG-003-KVM004-VMS003 ks]# cat config.yaml 
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: kubesphere-bg
spec:
  hosts:
  - {name: bg-003-kvm004-vms003, address: 192.168.0.55, internalAddress: 192.168.0.55, user: root, password: 123456}
  - {name: bg-003-kvm006-vms001, address: 192.168.0.58, internalAddress: 192.168.0.58, user: root, password: 123456}
  - {name: bg-003-kvm006-vms002, address: 192.168.0.59, internalAddress: 192.168.0.59, user: root, password: 123456}
  - {name: bg-003-kvm001-vms003, address: 192.168.0.52, internalAddress: 192.168.0.52, user: root, password: 123456}
  - {name: bg-003-kvm006-vms003, address: 192.168.0.60, internalAddress: 192.168.0.60, user: root, password: 123456}
  - {name: bg-003-kvm006-vms004, address: 192.168.0.61, internalAddress: 192.168.0.61, user: root, password: 123456}
  roleGroups:
    etcd:
    - bg-003-kvm004-vms003
    - bg-003-kvm006-vms001
    - bg-003-kvm006-vms002
    master: 
    - bg-003-kvm004-vms003
    - bg-003-kvm006-vms001
    - bg-003-kvm006-vms002
    worker:
    - bg-003-kvm001-vms003
    - bg-003-kvm006-vms003
    - bg-003-kvm006-vms004
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: "192.168.0.129"
    port: "6443"
  kubernetes:
    version: v1.17.9
    imageRepo: kubesphere
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
  addons: 
  - name: glusterfs
    namespace: kube-system
    sources: 
      yaml: 
        path: 
        - /root/ks/glusterfs.yaml  # or https://raw.githubusercontent.com/xxx/glusterfs.yaml

---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.0.0
spec:
  local_registry: ""
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  etcd:
    monitoring: true
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    es:
      elasticsearchDataVolumeSize: 20Gi
      elasticsearchMasterVolumeSize: 4Gi
      elkPrefix: logstash
      logMaxAge: 7
    mysqlVolumeSize: 20Gi
    minioVolumeSize: 20Gi
    etcdVolumeSize: 20Gi
    openldapVolumeSize: 2Gi
    redisVolumSize: 2Gi
  console:
    enableMultiLogin: true  # enable/disable multi login
    port: 30880
  alerting:
    enabled: true
  auditing:
    enabled: true
  devops:
    enabled: true
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
    jenkinsJavaOpts_Xms: 512m
    jenkinsJavaOpts_Xmx: 512m
    jenkinsJavaOpts_MaxRAM: 2g
  events:
    enabled: true
    ruler:
      enabled: true
      replicas: 2
  logging:
    enabled: true
    logsidecarReplicas: 2
  metrics_server:
    enabled: true
  monitoring:
    prometheusMemoryRequest: 400Mi
    prometheusVolumeSize: 20Gi
  multicluster:
    clusterRole: none  # host | member | none
  networkpolicy:
    enabled: true
  notification:
    enabled: true
  openpitrix:
    enabled: true
  servicemesh:
    enabled: true



[root@BG-003-KVM004-VMS003 ks]# cat glusterfs.yaml 
﻿---
apiVersion: v1
kind: Secret
metadata:
  name: heketi-secret
  namespace: kube-system
type: kubernetes.io/glusterfs
data:
  key: frPCQiQNSjt7

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name:  glusterfs
  annotations:
    storageclass.kubesphere.io/supported-access-modes: '["ReadWriteOnce","ReadOnlyMany","ReadWriteMany"]'
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: http://192.168.0.50:8080
  clusterid: 55058919a7641bcc64d1b8763200843a
  restauthenabled: "true"
  restuser: admin
  secretNamespace: "kube-system"
  secretName: heketi-secret
  gidMin: "40000"
  gidMax: "50000"
  volumetype: "replicate:2"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate

**Comment by tzghost** [comment]
Node network problem, resolved

**Comment by FeynmanZhou** [comment]
> Node network problem, resolved

Did you install KubeSphere v3.0.0 with GlusterFS successfully?

**Comment by tzghost** [comment]
Yes , Glusterfs each node needs to open ports 49152 to 49251
https://github.com/gluster/gluster-kubernetes/blob/master/docs/setup-guide.md

**Comment by FeynmanZhou** [comment]
> Yes , Glusterfs each node needs to open ports 49152 to 49251
> https://github.com/gluster/gluster-kubernetes/blob/master/docs/setup-guide.md

Thanks, the related configuration of GlusterFS above is correct?

**Comment by tzghost** [comment]
Yes, the configuration of glusterfs is correct. The reason for the failure is that the port is not open
