### ISSUE TITLE
kubesphere3.0 UnauthorizedError: Not Login 

### ISSUE THREAD

**Issue by hidao** [kubesphere/kubesphere#2962]
kubectl logs ks-console-b4df86d6f-xdgz8 -n kubesphere-system -f --tail=10
{ UnauthorizedError: Not Login
at Object.throw (/opt/kubesphere/console/server/server.js:31701:11)
at getCurrentUser (/opt/kubesphere/console/server/server.js:9037:14)
at renderView (/opt/kubesphere/console/server/server.js:23231:46)
at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
at next (/opt/kubesphere/console/server/server.js:6871:18)
at /opt/kubesphere/console/server/server.js:70183:16
at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
at next (/opt/kubesphere/console/server/server.js:6871:18)
at /opt/kubesphere/console/server/server.js:77986:37
at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
at next (/opt/kubesphere/console/server/server.js:6871:18)
at /opt/kubesphere/console/server/server.js:70183:16
at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
at next (/opt/kubesphere/console/server/server.js:6871:18)
at /opt/kubesphere/console/server/server.js:77986:37
at dispatch (/opt/kubesphere/console/server/server.js:6870:32) message: 'Not Login' }
--> GET / 302 2ms 43b 2020/09/08T02:34:07.984
<-- GET /login 2020/09/08T02:34:07.984
-x- GET /login 200 12ms 14.82kb 2020/09/08T02:34:07.996

**Comment by hidao** [comment]
![image](https://user-images.githubusercontent.com/9458518/92428607-15f8f800-f17f-11ea-9ebd-004e76aedf3a.png)

**Comment by hidao** [comment]
![image](https://user-images.githubusercontent.com/9458518/92428659-3fb21f00-f17f-11ea-833b-eaafc4bf8a79.png)

**Comment by hidao** [comment]
![Uploading image.png…]()

**Comment by hidao** [comment]
![image](https://user-images.githubusercontent.com/9458518/92428846-c404a200-f17f-11ea-88dc-2d715e7b26de.png)

**Comment by wansir** [comment]
Use the following command: `kubectl -n kubesphere-system logs -l app=ks-apiserver` check `ks-apiserver` logs.

Same as this issue https://github.com/kubesphere/ks-installer/issues/1109

**Comment by hidao** [comment]
![Uploading image.png…]()

**Comment by hidao** [comment]
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: "2020-09-01T15:57:31Z"
    finalizers:
    - kubernetes.io/pvc-protection
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: dashboard
      operation: Update
      time: "2020-09-01T15:57:31Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
        f:spec:
          f:volumeName: {}
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      time: "2020-09-01T15:57:31Z"
    name: nfs-pvc
    namespace: default
    resourceVersion: "1715449"
    selfLink: /api/v1/namespaces/default/persistentvolumeclaims/nfs-pvc
    uid: dd23f013-992f-4d76-8862-c394fa1ed82c
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: manual
    volumeMode: Filesystem
    volumeName: nfs-pv
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"volume.beta.kubernetes.io/storage-class":"managed-nfs-storage"},"name":"test-claim","namespace":"default"},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"1Mi"}}}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-class: managed-nfs-storage
      volume.beta.kubernetes.io/storage-provisioner: fuseim.pri/ifs
    creationTimestamp: "2020-09-02T02:33:35Z"
    finalizers:
    - kubernetes.io/pvc-protection
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
            f:volume.beta.kubernetes.io/storage-class: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:volumeMode: {}
      manager: kubectl
      operation: Update
      time: "2020-09-02T02:33:35Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
            f:volume.beta.kubernetes.io/storage-provisioner: {}
        f:spec:
          f:volumeName: {}
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      time: "2020-09-02T02:38:42Z"
    name: test-claim
    namespace: default
    resourceVersion: "1831630"
    selfLink: /api/v1/namespaces/default/persistentvolumeclaims/test-claim
    uid: 04a16bbd-e8f9-435d-95ad-140a7e937020
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Mi
    volumeMode: Filesystem
    volumeName: pvc-04a16bbd-e8f9-435d-95ad-140a7e937020
  status:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 1Mi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: fuseim.pri/ifs
    creationTimestamp: "2020-09-01T16:45:23Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: prometheus
      prometheus: k8s
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
            f:volume.beta.kubernetes.io/storage-provisioner: {}
          f:labels:
            .: {}
            f:app: {}
            f:prometheus: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:storageClassName: {}
          f:volumeMode: {}
          f:volumeName: {}
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      time: "2020-09-02T02:38:42Z"
    name: prometheus-k8s-db-prometheus-k8s-0
    namespace: kubesphere-monitoring-system
    resourceVersion: "1831626"
    selfLink: /api/v1/namespaces/kubesphere-monitoring-system/persistentvolumeclaims/prometheus-k8s-db-prometheus-k8s-0
    uid: ec9c079d-fb84-4c75-8f38-e282d1203228
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: managed-nfs-storage
    volumeMode: Filesystem
    volumeName: pvc-ec9c079d-fb84-4c75-8f38-e282d1203228
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 20Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: fuseim.pri/ifs
    creationTimestamp: "2020-09-01T16:45:23Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: prometheus
      prometheus: k8s
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
            f:volume.beta.kubernetes.io/storage-provisioner: {}
          f:labels:
            .: {}
            f:app: {}
            f:prometheus: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:storageClassName: {}
          f:volumeMode: {}
          f:volumeName: {}
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      time: "2020-09-02T02:38:42Z"
    name: prometheus-k8s-db-prometheus-k8s-1
    namespace: kubesphere-monitoring-system
    resourceVersion: "1831620"
    selfLink: /api/v1/namespaces/kubesphere-monitoring-system/persistentvolumeclaims/prometheus-k8s-db-prometheus-k8s-1
    uid: af64c905-5182-4506-b6fa-829defe449be
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    storageClassName: managed-nfs-storage
    volumeMode: Filesystem
    volumeName: pvc-af64c905-5182-4506-b6fa-829defe449be
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 20Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: fuseim.pri/ifs
    creationTimestamp: "2020-09-03T15:07:02Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/instance: ks-openldap
      app.kubernetes.io/name: openldap-ha
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
            f:volume.beta.kubernetes.io/storage-provisioner: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/name: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:storageClassName: {}
          f:volumeMode: {}
          f:volumeName: {}
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      time: "2020-09-03T15:07:02Z"
    name: openldap-pvc-openldap-0
    namespace: kubesphere-system
    resourceVersion: "2298902"
    selfLink: /api/v1/namespaces/kubesphere-system/persistentvolumeclaims/openldap-pvc-openldap-0
    uid: f10815c7-d2e0-4494-92d4-0d8ad45d0a65
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: managed-nfs-storage
    volumeMode: Filesystem
    volumeName: pvc-f10815c7-d2e0-4494-92d4-0d8ad45d0a65
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"redis-pvc","namespace":"kubesphere-system"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"2Gi"}},"storageClassName":"managed-nfs-storage"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: fuseim.pri/ifs
    creationTimestamp: "2020-09-03T15:06:51Z"
    finalizers:
    - kubernetes.io/pvc-protection
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
            f:volume.beta.kubernetes.io/storage-provisioner: {}
        f:spec:
          f:volumeName: {}
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      time: "2020-09-03T15:06:51Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: kubectl
      operation: Update
      time: "2020-09-03T15:06:51Z"
    name: redis-pvc
    namespace: kubesphere-system
    resourceVersion: "2298813"
    selfLink: /api/v1/namespaces/kubesphere-system/persistentvolumeclaims/redis-pvc
    uid: 96078df3-9653-4930-97cb-6751f3b8f194
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: managed-nfs-storage
    volumeMode: Filesystem
    volumeName: pvc-96078df3-9653-4930-97cb-6751f3b8f194
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Comment by hidao** [comment]
[root@bsp-96 ~]# kubectl -n kubesphere-system logs -l app=ks-apiserver -f --tail=10
kubesphere.io/kubesphere/pkg/apiserver/filters.WithRequestInfo.func1(0x38c1b80, 0xc0001c5340, 0xc002e43f00)
        /home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/requestinfo.go:67 +0x3c5
net/http.HandlerFunc.ServeHTTP(0xc0009bd110, 0x38c1b80, 0xc0001c5340, 0xc002e43f00)
        /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
net/http.serverHandler.ServeHTTP(0xc0001c41c0, 0x38c1b80, 0xc0001c5340, 0xc002e43f00)
        /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2831 +0xa4
net/http.(*conn).serve(0xc002168280, 0x38d4780, 0xc001d35040)
        /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1919 +0x875
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2957 +0x384
2020/09/08 03:28:21 http: panic serving 10.244.0.32:50830: runtime error: invalid memory address or nil pointer dereference
goroutine 325431 [running]:
net/http.(*conn).serve.func1(0xc000ba1360)
        /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1795 +0x139
panic(0x2d36da0, 0x5450320)
        /opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
kubesphere.io/kubesphere/pkg/models/resources/v1alpha2/storageclass.(*storageClassesSearcher).countPersistentVolumeClaims(0xc0009244a0, 0xc000ed1940, 0x13, 0x54c6d68)
        /home/runner/work/kubesphere/kubesphere/pkg/models/resources/v1alpha2/storageclass/storageclasses.go:110 +0x12c
kubesphere.io/kubesphere/pkg/models/resources/v1alpha2/storageclass.(*storageClassesSearcher).Search(0xc0009244a0, 0x0, 0x0, 0xc002bea2e0, 0xc000dc4a62, 0xa, 0x1, 0x2e5db20, 0xc001e4ac60, 0x0, ...)
        /home/runner/work/kubesphere/kubesphere/pkg/models/resources/v1alpha2/storageclass/storageclasses.go:92 +0x2f0
kubesphere.io/kubesphere/pkg/models/resources/v1alpha2/resource.(*ResourceGetter).ListResources(0xc00000e068, 0x0, 0x0, 0xc000dc4a4c, 0xe, 0xc002bea2e0, 0xc000dc4a62, 0xa, 0x299a801, 0xa, ...)
        /home/runner/work/kubesphere/kubesphere/pkg/models/resources/v1alpha2/resource/resources.go:123 +0x23e
kubesphere.io/kubesphere/pkg/kapis/resources/v1alpha3.(*Handler).fallback(0xc0009244c0, 0xc000dc4a4c, 0xe, 0x0, 0x0, 0xc001e25bc0, 0x0, 0x3856240, 0xc0004a2060)
        /home/runner/work/kubesphere/kubesphere/pkg/kapis/resources/v1alpha3/handler.go:155 +0xb0b
kubesphere.io/kubesphere/pkg/kapis/resources/v1alpha3.(*Handler).handleListResources(0xc0009244c0, 0xc001e4aa50, 0xc000b74a80)
        /home/runner/work/kubesphere/kubesphere/pkg/kapis/resources/v1alpha3/handler.go:97 +0x2cb
github.com/emicklei/go-restful.(*Container).dispatch.func5(0xc001e4aa50, 0xc000b74a80)
        /home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:283 +0x3e
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc001e4aae0, 0xc001e4aa50, 0xc000b74a80)
        /home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/filter.go:21 +0x8b
kubesphere.io/kubesphere/pkg/apiserver.logRequestAndResponse(0xc001e4aa50, 0xc000b74a80, 0xc001e4aae0)
        /home/runner/work/kubesphere/kubesphere/pkg/apiserver/apiserver.go:531 +0x82
github.com/emicklei/go-restful.(*FilterChain).ProcessFilter(0xc001e4aae0, 0xc001e4aa50, 0xc000b74a80)
        /home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/filter.go:19 +0x65
github.com/emicklei/go-restful.(*Container).dispatch(0xc000926000, 0x38c1b80, 0xc00053f7a0, 0xc002e42800)
        /home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:285 +0x866
net/http.HandlerFunc.ServeHTTP(0xc000404a90, 0x38c1b80, 0xc00053f7a0, 0xc002e42800)
        /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0008f60c0, 0x38c1b80, 0xc00053f7a0, 0xc002e42800)
        /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2416 +0x1bd
github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc000926000, 0x38c1b80, 0xc00053f7a0, 0xc002e42800)
        /home/runner/go/pkg/mod/github.com/emicklei/go-restful@v2.9.5+incompatible/container.go:303 +0x4d
kubesphere.io/kubesphere/pkg/apiserver/filters.WithKubeAPIServer.func1(0x38c1b80, 0xc00053f7a0, 0xc002e42800)
        /home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/kubeapiserver.go:71 +0x37f
net/http.HandlerFunc.ServeHTTP(0xc0008f7000, 0x38c1b80, 0xc00053f7a0, 0xc002e42800)
        /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthorization.func1(0x38c1b80, 0xc00053f7a0, 0xc002e42800)
        /home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/authorization.go:50 +0x37c
net/http.HandlerFunc.ServeHTTP(0xc0008f7080, 0x38c1b80, 0xc00053f7a0, 0xc002e42800)
        /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthentication.func1(0x38c1b80, 0xc00053f7a0, 0xc000a3e900)
        /home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/authentication.go:95 +0xb6b
net/http.HandlerFunc.ServeHTTP(0xc0001820a0, 0x38c1b80, 0xc00053f7a0, 0xc000a3e900)
        /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithRequestInfo.func1(0x38c1b80, 0xc00053f7a0, 0xc000a3e700)
        /home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/requestinfo.go:67 +0x3c5
net/http.HandlerFunc.ServeHTTP(0xc0009bd110, 0x38c1b80, 0xc00053f7a0, 0xc000a3e700)
        /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
net/http.serverHandler.ServeHTTP(0xc0001c41c0, 0x38c1b80, 0xc00053f7a0, 0xc000a3e700)
        /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2831 +0xa4
net/http.(*conn).serve(0xc000ba1360, 0x38d4780, 0xc001f0e380)
        /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1919 +0x875
created by net/http.(*Server).Serve
        /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2957 +0x384

**Comment by hidao** [comment]
I using nfs  storageClass

**Comment by wansir** [comment]
/kind bug
/milestone 3.1.0

PersistentVolumeClaim without `storageClassName` will crash the ks-apiserver.

**Comment by zheng1** [comment]
@stoneshi-yunify Has this issue been resolved? Is it verifiable?

**Comment by stoneshi-yunify** [comment]
this issue had been fixed by https://github.com/kubesphere/kubesphere/pull/2976, use latest ks-control-manager can verify it.

/close
