### ISSUE TITLE
how to uninstall kubesphere in 3.0.0 ?

### ISSUE THREAD

**Issue by sunnoy** [kubesphere/kubesphere#2969]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**What's your question**
3.0.0

# how to uninstall kubesphere ?

**Comment by hantmac** [comment]
kubectl delete ns kubesphere or kubectl delete ns kubesphere-system

**Comment by sunnoy** [comment]
in 3.0 there is no kubesphere or  kubesphere-system ns

**Comment by hantmac** [comment]
> in 3.0 there is no kubesphere or kubesphere-system ns

Impossible! namespace `kubesphere-system` exist definitly.

**Comment by Forest-L** [comment]
Refer to this docs https://github.com/kubesphere/ks-installer/blob/master/scripts/kubesphere-delete.sh

**Comment by sunnoy** [comment]
> Refer to this docs https://github.com/kubesphere/ks-installer/blob/master/scripts/kubesphere-delete.sh

tks
