### ISSUE TITLE
How to invoke authentication API manually？

### ISSUE THREAD

**Issue by sunshuyan** [kubesphere/kubesphere#2977]
**Describe the Bug**

I use the same set of account and password, and the password intercepted in the browser is encrypted into different strings. Manual call authentication is 401. Is there any way to call authentication API manually?

url:http://172.31.178.157:31904/oauth/token

{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "Unauthorized: incorrect password",
    "reason": "Unauthorized",
    "code": 401
}

**Versions Used**
KubeSphere:v3.0.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Comment by xgy560501** [comment]
EMMM.I just got the error when i tried to excute the api to login system with python.

**Comment by wansir** [comment]
> EMMM.I just got the error when i tried to excute the api to login system with python.

https://kubesphere.io/docs/api-reference/api-docs/
