### ISSUE TITLE
A page of docs was losted

### ISSUE THREAD

**Issue by yeongjet** [kubesphere/kubesphere#2979]
https://kubesphere.com.cn/docs/quick-start/deploy-bookinfo-to-k8s/

**Comment by FeynmanZhou** [comment]
> https://kubesphere.com.cn/docs/quick-start/deploy-bookinfo-to-k8s/

The Chinese version of documentation will be ready around one month, you can change to the [English version](https://kubesphere.com.cn/en/docs/quick-start/deploy-bookinfo-to-k8s/) to get the latest docs.
