### ISSUE TITLE
Create pipeline, /var/kenkins_home/logs/health-checker.log: Read-only file system

### ISSUE THREAD

**Issue by lishitiancn** [kubesphere/kubesphere#2985]
**Describe the Bug**
Create pipeline, a error hanppen.
/var/kenkins_home/logs/health-checker.log: Read-only file system
Failed to create a temporary file in /var/jenkins_home

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: v3.0.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
Using OpenEBS as iscsi storage provisioner.

**Comment by hzliangbin** [comment]
@lishitiancn Sounds like your JENKINS_HOME has the wrong permissions or ownership. Something misconfig with your storage.
