### ISSUE TITLE
Once the user has the users-manager role, he can modify himself to become any role

### ISSUE THREAD

**Issue by siu91** [kubesphere/kubesphere#2989]
**Describe the Bug**
Once the user has the users-manager role, he can modify himself to become any role, even the role of the platform-admin.

**Versions Used**
KubeSphere: v3.0.0
Kubernetes: 1.18.6

**Environment**
 CentOS 7.5 / 3 masters:  2cpu/8g; 3 nodes: 4cpu/16g

**How To Reproduce**
As described.

**Expected behavior**
The user has the users-manager role and cannot modify his role as a platform-admin.

**Comment by wansir** [comment]
The permissions that users-manager has are a subset of platform-admin, which is a privileged role. Platform admin shouldn't do everything. Similarly, in K8s you have the permission to create cluster role binding, you can also set yourself as cluster-admin. Maybe we can make some restrictions as you said.
