### ISSUE TITLE
when change jenkinsfile or jenkinsfile name in git repo kubesphere ui not update anything

### ISSUE THREAD

**Issue by willzhang** [kubesphere/kubesphere#2991]
when change jenkinsfile content or jenkinsfile name in git repo，kubesphere ui not update anything ，still use old jenkinsfile and can not find new jenkinsfile name

**Comment by shaowenchen** [comment]
1. You should change the path of Jenkinsfile manually in KubeSphere UI if you change the Jenkinsfile name.

2. Only the parameters will display on the KubeSphere UI if using the InSCM Jenkinsfile.
