### ISSUE TITLE
Unable to get workloads running properly

### ISSUE THREAD

**Issue by sleekmike** [kubesphere/kubesphere#3005]
**What's your question**
I successfully installed  Kubernetes and Kubesphere, I am following the article  **Deploy Bookinfo and Manage Traffic** on KubeSphere website but when I create and deploy the sample application and check the Workloads, the status of all four deployments displays updating as depicted in the screenshots below.

<img width="1026" alt="kkk" src="https://user-images.githubusercontent.com/37389692/95594740-44e6e000-0a43-11eb-8f6a-79d1139b48dd.png">

Also in the **Set Gateway** step  after setting access method to NodePort and saving the changes I noticed that Under Internet Access gateway address seems to be blank or empty. 

<img width="1004" alt="kulprit" src="https://user-images.githubusercontent.com/37389692/95594839-5b8d3700-0a43-11eb-9848-8d05ce0bf6ce.png">

Please I need help resolving these issues ASAP. Thanks

**Environment: OS & Hardware Information**
Docker 2.2.0.5, 
Kubernetes v1.15.5,  
KubeSphere installer version: v3.0.0.

I am running all these application on MacOS  Catalina 10.15, and I am connecting to a linux instance/clusters on linode, the spec are shown below:

<img width="825" alt="linode-cluster" src="https://user-images.githubusercontent.com/37389692/95596884-d9ead880-0a45-11eb-8a9c-b1a8e96971cb.png">

**Comment by zryfish** [comment]
Hover your mouse over the warning icon, it will give the reason why your deployments **FailedCreate**. Also, AFAIK, linode Kubernetes is a managed Kubernetes, which means you won't see master nodes of your cluster, which will cause the problem you just encountered, no gateway address shown, we're working on it. Meanwhile, you can use any node IP as your gateway address IP, it's the same.

**Comment by sleekmike** [comment]
Thanks @zryfish for your helpful response.
