### ISSUE TITLE
Feature: Support muti cluster scheduling

### ISSUE THREAD

**Issue by yuswift** [kubesphere/kubesphere#3008]
Feature Description

- Distribute total replicas such as FederatedDeployment evenly in all available clusters
- Distribute total replicas in different weight in all available clusters
- Distribute replicas in different weight, also enforcing replica limits per cluster

How it works

- Firstly, users should create a FederatedNamespace and FederatedDeployment under a FederatedWorkspace
- Secondly, users specify different replicas weight and min&max replicas in all available clusters by [RSP](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#replicaschedulingpreference)
- Lastly, the kubesphsere console submits FederatedDeployment&RSP together

**Comment by yuswift** [comment]
kind/feature

**Comment by zryfish** [comment]
> kind/feature

wrong label, command always start with a / 

/kind feature

**Comment by luoMonkeyKing** [comment]
> Feature Description
> 
> * Distribute total replicas such as FederatedDeployment evenly in all available clusters
> * Distribute total replicas in different weight in all available clusters
> * Distribute replicas in different weight, also enforcing replica limits per cluster
> 
> How it works
> 
> * Firstly, users should create a FederatedNamespace and FederatedDeployment under a FederatedWorkspace
> * Secondly, users specify different replicas weight and min&max replicas in all available clusters by [RSP](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#replicaschedulingpreference)
> * Lastly, the kubesphsere console submits FederatedDeployment&RSP together

Excuse me, is there a detailed operation document? Is it to create Federated enterprise space on kubesphere first, and then create FederatedNamespace and FederatedDeploymen&RSP on kubesphere console? I tried it like this, but it didn't work.

**Comment by yuswift** [comment]
> > Feature Description
> > 
> > * Distribute total replicas such as FederatedDeployment evenly in all available clusters
> > * Distribute total replicas in different weight in all available clusters
> > * Distribute replicas in different weight, also enforcing replica limits per cluster
> > 
> > How it works
> > 
> > * Firstly, users should create a FederatedNamespace and FederatedDeployment under a FederatedWorkspace
> > * Secondly, users specify different replicas weight and min&max replicas in all available clusters by [RSP](https://github.com/kubernetes-sigs/kubefed/blob/master/docs/userguide.md#replicaschedulingpreference)
> > * Lastly, the kubesphsere console submits FederatedDeployment&RSP together
> 
> Excuse me, is there a detailed operation document? Is it to create Federated enterprise space on kubesphere first, and then create FederatedNamespace and FederatedDeploymen&RSP on kubesphere console? I tried it like this, but it didn't work.

In v3.1.0, kubesphere doesn't support creating rsp on console. But you can create a FederatedNamespace and FederatedDeployment on console. see [here](https://kubesphere.io/zh/docs/project-administration/project-and-multicluster-project/)
