### ISSUE TITLE
Question: what happened to the service mesh views?

### ISSUE THREAD

**Issue by Morriz** [kubesphere/kubesphere#3011]
In the demo only one tab is left: "Applications", but in the images shared on reddit long time ago, the bookinfo app showed also tabs for "Traffic Management", "Grayscale Release", "Tracing" and "Events".

Any idea how to see those views in the demo?

**Comment by FeynmanZhou** [comment]
> In the demo only one tab is left: "Applications", but in the images shared on reddit long time ago, the bookinfo app showed also tabs for "Traffic Management", "Grayscale Release", "Tracing" and "Events".
> 
> Any idea how to see those views in the demo?

@Morriz I assume you want to see these features including on this page, right?

![image](https://user-images.githubusercontent.com/40452856/95680594-6e536780-0c0d-11eb-9b7a-c6fa20ecbee4.png)

Please refer to [this guide](https://kubesphere.io/docs/quick-start/deploy-bookinfo-to-k8s/) and make sure you enable the KubeSphere Service Mesh. 

Let us know if you have any questions : )
