### ISSUE TITLE
Failed to enable kubelet service

### ISSUE THREAD

**Issue by itlidaye** [kubesphere/kubesphere#3012]
/kk create cluster –with-kubernetes v1.18.6 –with-kubesphere v3.0.0

Configuration file already exists
Waiting for etcd to start
INFO[16:10:46 CST] Refreshing etcd configuration 
INFO[16:10:47 CST] Get cluster status 
[shiku183 192.168.0.120] MSG:
Cluster will be created.
INFO[16:10:48 CST] Installing kube binaries 
Push /opt/kubekey/v1.18.6/amd64/kubeadm to 192.168.0.120:/tmp/kubekey/kubeadm Done
Push /opt/kubekey/v1.18.6/amd64/kubelet to 192.168.0.120:/tmp/kubekey/kubelet Done
Push /opt/kubekey/v1.18.6/amd64/kubectl to 192.168.0.120:/tmp/kubekey/kubectl Done
Push /opt/kubekey/v1.18.6/amd64/helm to 192.168.0.120:/tmp/kubekey/helm Done
Push /opt/kubekey/v1.18.6/amd64/cni-plugins-linux-amd64-v0.8.6.tgz to 192.168.0.120:/tmp/kubekey/cni-plugins-linux-amd64-v0.8.6.tgz Done
ERRO[16:11:30 CST] Failed to enable kubelet service: Failed to exec command: sudo -E /bin/sh -c “systemctl enable kubelet && ln -snf /usr/local/bin/kubelet /usr/bin/kubelet” 
Failed to execute operation: File exists: Process exited with status 1 node=192.168.0.120
WARN[16:11:30 CST] Task failed … 
WARN[16:11:30 CST] error: interrupted by error 
Error: Failed to install kube binaries: interrupted by error
Usage:
kk create cluster [flags]

Flags:
-f, –filename string Path to a configuration file
-h, –help help for cluster
–skip-pull-images Skip pre pull images
–with-kubernetes string Specify a supported version of kubernetes
–with-kubesphere Deploy a specific version of kubesphere (default v3.0.0)
-y, –yes Skip pre-check of the installation

Global Flags:
–debug Print detailed information (default true)

Failed to install kube binaries: interrupted by error

**Comment by RolandMa1986** [comment]
Hi @itlidaye , have you created your cluster successfully? It seems you have already installed a k8s before on the machine before.
