### ISSUE TITLE
 How do I get the image  kube-auditing-operator of arm64

### ISSUE THREAD

**Issue by haomi123** [kubesphere/kubesphere#3019]
**What's your question**

I made an error when I ran kube-operation-Operator on ARM64, because kube - auditing - operator is amd64

**Environment: OS & Hardware Information**

os: linux centos 7.6
k8s: 1.15.1

**Error logs or message (Attach logs or screenshot)**
```
kubectl logs  kube-auditing-operator-84cff5cd48-qstxs  -n kubesphere-logging-system 
standard_init_linux.go:178: exec user process caused "exec format error"
------------------------------------------------------------------------------------------------

###docker images |grep kube-auditing-operator
docker.io/kubesphere/kube-auditing-operator                      v0.1.0              e451cd49a4a7        2 months ago        66.7 MB
###docker inspect e451cd49a4a7 |grep 'Arch'
 Architecture": "amd64"
```

**Installer Version**
kubesphere:3.0.0

Does kube-auditor-operator provide source code or when will arm64 be supported

**Comment by haomi123** [comment]
I've got it，thank you

**Comment by ciiiii** [comment]
> I've got it，thank you

How do you do? Where can i find the source code of kube-auditing-operator? Thank you very much

**Comment by haomi123** [comment]
Sorry, I forgot, I did not get the source code&nbsp; of kube-auditing-operator, finally skipped the image




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubesphere/kubesphere"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月28日(星期天) 晚上6:58
收件人:&nbsp;"kubesphere/kubesphere"<kubesphere@noreply.github.com&gt;;
抄送:&nbsp;"郝咪咪"<1272022137@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kubesphere/kubesphere]  How do I get the image  kube-auditing-operator of arm64 (#3019)





  
I've got it，thank you
  
How do you do? Where can i find the source code of kube-auditing-operator? Thank you very much

**Comment by goodqinjin** [comment]
@wanjunlei  how can i get  the souce code of kube-auditor-operator? thx
