### ISSUE TITLE
jenkins api 可以提出来做一个单独的库吗

### ISSUE THREAD

**Issue by xmapst** [kubesphere/kubesphere#3020]
jenkins api 可以提出来做一个单独的库吗

**Comment by shaowenchen** [comment]
We have finished it. Please refer to https://github.com/kubesphere/kubesphere/tree/master/pkg/simple/client/devops .

**Comment by xmapst** [comment]
> 我们已经完成了。请参考https://github.com/kubesphere/kubesphere/tree/master/pkg/simple/client/devops。



> We have finished it. Please refer to https://github.com/kubesphere/kubesphere/tree/master/pkg/simple/client/devops .

Thank you

**Comment by xmapst** [comment]
@shaowenchen Why no node related operations

**Comment by shaowenchen** [comment]
We don't use the API to modify the node. It's a configuration.  

At the same time, the node is provided by the Kubernetes cd plugins, not Jenkins directly.

**Comment by xmapst** [comment]
> We don't use the API to modify the node. It's a configuration.
> 
> At the same time, the node is provided by the Kubernetes cd plugins, not Jenkins directly.

好的
