### ISSUE TITLE
devops-ci,while deploy the kind:applications.app.k8s.io    not be supported

### ISSUE THREAD

**Issue by gaomiup20** [kubesphere/kubesphere#3022]
cat deploy.yaml
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: 'test-app'
  namespace: juslink-dev
  labels:
    app.kubernetes.io/version: v1
  annotations:
    servicemesh.kubesphere.io/enabled: 'false'
spec:
  selector:
    matchLabels: 
      juslink/group: test-app
  addOwnerRef: true
![image](https://user-images.githubusercontent.com/26083944/96101191-ca690500-0f07-11eb-8636-0ee2d4eb0837.png)

notie:
1.when kubectl apply -f deploy.yaml in controller is successful（控制台直接命令行apply）
application.app.k8s.io/test-app created
service/test-app created
deployment.apps/test-app created
2.when ui also suucessful(界面上自建应用，通过构建应用->编辑模式)
![image](https://user-images.githubusercontent.com/26083944/96101447-0ac88300-0f08-11eb-8c0a-1172e2c824ce.png)

**Comment by gaomiup20** [comment]
升级了jenkins-agent指定的maven镜像中的kubectl版本和控制台kubectl一致，但仍然报错找不到kind:applicaiton

**Comment by shaowenchen** [comment]
DevOps component uses the plugin of kubernetes-cd-plugin to deploy workloads. The kind of application not in the supported list https://github.com/jenkinsci/kubernetes-cd-plugin/blob/dev/src/main/java/io/kubesphere/jenkins/kubernetes/generated/KubernetesModelClasses.java.

**Comment by gaomiup20** [comment]
但是为什么界面和控制台可以直接应用The kind of application，除了在jenkinsfile（devops流水线）
