### ISSUE TITLE
Unable to To Create Kubesphere-System Gateway

### ISSUE THREAD

**Issue by kivo360** [kubesphere/kubesphere#3024]
## English only!

Unable to create kubesphere-system gateway. When I go to the project is only has an empty field. I need to be able to use this gateway to add HTTPs settings.

The image below shows what I'm having problems with:

![image](https://user-images.githubusercontent.com/2403240/96309910-7de2ff80-0fc3-11eb-93e5-ec10c31080bf.png)

In the event that I can't do this. Is there any https forwarding I can do on the loadbalancer (I use digitalocean).

**Comment by rayzhou2017** [comment]
It is system project which is not allowed to edit via console. You can create a project under your own workspace and create the gateway.

**Comment by FeynmanZhou** [comment]
@kivo360  Do you want to configure https forwarding for the KubeSphere Console (ks-console) service?

**Comment by kivo360** [comment]
Yeah, I want the console to use https. It's a personal preference.

**Comment by kivo360** [comment]
Is there a way I can use kubectl to create the gateway?

**Comment by FeynmanZhou** [comment]
@zryfish I remember there is a way to allow this configuration, please help @kivo360 to resolve it, thanks.

**Comment by zryfish** [comment]
@kivo360  actually you can, but it requires more effort. Gateway is a standard Nginx controller service [installation](https://github.com/kubesphere/kubesphere/blob/master/install/ingress-controller/ingress-controller.yaml) just like the nginx controller example, the biggest difference is KubeSphere create gateway per namespace.  We are planning to refactor this part in our next release, using CRD.

**Comment by kivo360** [comment]
@zryfish Wonderful! I wanted to cover my bases. For the most part I'm using KubeSphere for a demo, therefore it's not mission critical stuff right now. 

I see it as a means to solve many problems inside of the organization I'm apart of. Out of curiosity, what is the new roadmap now that you've reached 3.0.0?

One of the biggest things I've been really looking at is the use of serverless functions and event-based architecture. Primarily looking heavily at [OpenFaaS](https://www.openfaas.com/blog/schedule-your-functions/) and [argo-events](https://github.com/argoproj/argo-events). That lead me to the entire argo ecosystem. I'm amazed at how tightly integrated it is.

Here's the question I wanted to ask:

Would you ever consider turning Argo ecosystem into a first class citizen inside of the KubeSphere project? Here's why I ask that:

1. I could see the possibility that the CI/CD system could become faster. That would largely be due to the fact that the steps involved inside of the
2. Argo Rollouts, Events and Workflows can expand to much more functionality throughout the rest of the system.
    * A standardized rollout that's decoupled from service meshes.
    * Events can be used to better tie the entire platform together. For example, communication between applications in different namespaces, and triggering of serverless functions to add more functionality.
    * Those serverless functions could aid in adding features like billing.
3. A UI with events could allow for easy migration from old databases and message queues to more modern ones. A problem I'm seeing a company face is porting from an older legacy queue to something more modern. They're using AWS EventBridge to make a transition. 
    * I would be hard pressed to say that if Argo-Events was a less difficult to configure alternative they wouldn't be making the major mistake of going 100% AWS. The ease of setting everything up is a huge selling point for them. 


I didn't see your roadmap, figured you all were planning, and wanted to ask your thoughts and plans were. 

**If this can't be helped for a while I'm going to close this issue.**

**Comment by benjaminhuo** [comment]
@kivo360 , we're currently considering the future Serverless/FaaS support in KubeSphere.

And I agreed that events play an important role in the comm of apps. For example, [knative eventing](https://knative.dev/docs/eventing/sources/) supports many event sources including apache camel which can connect to more sources, knative eventing can also covert these events into standard CloudEvents format .

As for serverless/FaaS support, we're investigating various choices like knative and OpenFaaS.
Argo is good for CI/CD, we'll see if it's possible to integrate it into KubeSphere.

Ben
