### ISSUE TITLE
 kubectl  get applications.app.k8s.io waybill  -n xxx

### ISSUE THREAD

**Issue by gaomiup20** [kubesphere/kubesphere#3025]
[root@master ~]# kubectl  get applications.app.k8s.io waybill  -n juslink-dev        
NAME      TYPE   VERSION   OWNER   READY   AGE
waybill                    true    0/0     19m

控制台中的application的ready是0/0，然而界面能看到部署的deploy,svc在正常运行
基于应用在编排文件自建的applicaiton（自制应用）
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: waybill
  namespace: juslink-dev
  labels:
    app.kubernetes.io/version: v1
  annotations:
    servicemesh.kubesphere.io/enabled: 'false'
spec:
  selector:
    matchLabels:
      juslink/group: waybill
  addOwnerRef: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipment-app-service
  labels:
    app: shipment-app-service
    app.kubernetes.io/name: waybill
    juslink/group: waybill
  namespace: juslink-dev
spec:
  replicas: 1
  minReadySeconds: 10
  revisionHistoryLimit: 3
  strategy: # dev enviroment will kill the old pods and start the new pods
    type: Recreate
  selector:
    matchLabels:
      app: shipment-app-service
      app.kubernetes.io/name: waybill
      juslink/group: waybill
  template:
    metadata:
      name: shipment-app-service
      labels:
        app: shipment-app-service
        app.kubernetes.io/name: waybill
        juslink/group: waybill
    spec:
      containers:
        - name: shipment-app-service
           image: "x'x'x'x'x'x'x'x'x'xxxxxxxxxxxxxxx'x'x'x'x"
          ports:
            - name: java-webs
              containerPort: 8080 # 容器端口
              protocol: TCP
          env:
            - name: JAVA_OPTS
              value: >-
                -XX:codecachetotal=64m
                -Denv=DEV -Dapp.id=juslink-shipment -Dapollo.meta=http://apollo--5t0oku-apollo-configservice.toolkit:8080 -Dspring.profiles.active=apollo
            - name: SW_AGENT_NAME
              value: "juslink-sccp-shipment-demand-app"
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "skywalk-i9us5f-skywalking-skywalking-oap.toolkit:11800"    
          resources:
            limits:
              cpu: "1" # cpu 限制
              memory: "700Mi" # 内存限制
            requests:
              cpu: "200m"
              memory: "300Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: shipment-app-service
  namespace: juslink-dev
  labels:
    app: shipment-app-service
    app.kubernetes.io/name: waybill
    juslink/group: waybill
spec:
  type: NodePort
  selector:
    app: shipment-app-service
    app.kubernetes.io/name: waybill
    juslink/group: waybill
  ports:
    - port: 8080 # 服务端口
      targetPort: 8080
<img width="851" alt="企业微信截图_16031620721388" src="https://user-images.githubusercontent.com/26083944/96534161-c5b69f00-12c1-11eb-8678-a2510d61b5dd.png">

**Comment by zackzhangkai** [comment]
Please add these labels to your subresources:
```
  labels:
    app: details
    app.kubernetes.io/name: bookinfo
    app.kubernetes.io/version: v1
    version: v1
```
You can go to KubeSphere Forum to search your questions.
https://kubesphere.com.cn/forum/

**Comment by gaomiup20** [comment]
请问下，可以在deployment自定义lable，再将这个lablel被applicaiton的matchLabels匹配吧

> Please add these labels to your subresources:
> 
> ```
>   labels:
>     app: details
>     app.kubernetes.io/name: bookinfo
>     app.kubernetes.io/version: v1
>     version: v1
> ```
> 
> You can go to KubeSphere Forum to search your questions.
> https://kubesphere.com.cn/forum/

请问下，可以在deployment自定义lable，再将这个lablel被applicaiton的matchLabels匹配吧
