### ISSUE TITLE
Help getting my services running on KubeSphere

### ISSUE THREAD

**Issue by sleekmike** [kubesphere/kubesphere#3049]
Hello Guys,

I have been having an issue with creating and running services(source to image) on KubeSphere.
I have followed the tutorials(video and written) verbatim but each time I start the service the jobs and pods always fail to start, I have tried various resource settings/configurations but this has not helped either.

<img width="1007" alt="Screenshot at Oct 31 04-29-21" src="https://user-images.githubusercontent.com/37389692/97770288-34052800-1b32-11eb-96c8-5be117772f58.png">
<img width="1032" alt="my-issue3" src="https://user-images.githubusercontent.com/37389692/97770296-41baad80-1b32-11eb-83aa-35154b634e86.png">
<img width="950" alt="job-setting" src="https://user-images.githubusercontent.com/37389692/97770297-454e3480-1b32-11eb-87d3-035e59fa0014.png">
<img width="912" alt="my-resource" src="https://user-images.githubusercontent.com/37389692/97770300-50a16000-1b32-11eb-8940-5929c9ec3912.png">

**Environment**
Environment: OS & Hardware Information
Docker 2.2.0.5,
Kubernetes v1.15.5,
KubeSphere installer version: v3.0.0.

I am accessing the cluster(KubeSphere UI) on MacOS Catalina 10.15 which is connecting to a linux instance/clusters on Digital Ocean with 4 Cores per node and 8gigabytes of storage per node.

Please I need some help resolving this issue, so that my services can be deployed successfully, my jobs and pods run smoothly and I also want to be able to access this jobs externally(through internet).

Best regards, Mike O.

**Comment by zackzhangkai** [comment]
@sleekmike it's likely because of your project quota, pls do check as follows:

![image](https://user-images.githubusercontent.com/20178386/97776891-f2629480-1ba6-11eb-8dcd-9557e53ab4fd.png)

**Comment by sleekmike** [comment]
Ok thanks @zackzhangkai, I was editing resource default request instead.
