### ISSUE TITLE
feature:clone pipeline

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#3053]
![image](https://user-images.githubusercontent.com/43693241/97824479-03222000-1cf7-11eb-9f5f-6fe663852102.png)

/area devops

**Comment by LinuxSuRen** [comment]
This feature is ready. You can see it from the screenshot below:

![image](https://user-images.githubusercontent.com/1450685/102743982-9c82bf80-4393-11eb-8815-f1452728fe3a.png)

In case anyone does not know how to use it. There's a simple tutorial for it. [This tutorial was written by Chinese](https://kubesphere.com.cn/forum/d/3066-31-devops).

So, I guess we can close this. /cc @zryfish and @shaowenchen 

Again, make a connection between a PR and the related issues is a good practice. Please link it if you know it @kubesphere/developers

**Comment by LinuxSuRen** [comment]
ping @shaowenchen
