### ISSUE TITLE
Open the App Store and report an error(kubesphere-v3.0.0)

### ISSUE THREAD

**Issue by misteruly** [kubesphere/kubesphere#3072]
####  kubectl get pod  -n  openpitrix-system
NAME                                                 READY   STATUS      RESTARTS   AGE
hyperpitrix-generate-kubeconfig-8rgkl                0/2     Completed   4          144m
hyperpitrix-release-app-job-9j2j2                    0/1     Completed   2          144m
openpitrix-hyperpitrix-deployment-797d5774f8-vlsls   1/1     Running     0          144m

####   kubectl get sc  -n  openpitrix-system   
NAME                         PROVISIONER                                                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
openebs-device               openebs.io/local                                           Delete          WaitForFirstConsumer   false                  3h12m
openebs-hostpath (default)   openebs.io/local                                           Delete          WaitForFirstConsumer   false                  3h12m
openebs-jiva-default         openebs.io/provisioner-iscsi                               Delete          Immediate              false                  3h12m
openebs-snapshot-promoter    volumesnapshot.external-storage.k8s.io/snapshot-promoter   Delete          Immediate              false                  3h12m

####  kubectl get pod  -n  kubesphere-system  
NAME                                     READY   STATUS    RESTARTS   AGE
etcd-5b879f67bc-wzvrt                    1/1     Running   0          148m
ks-apiserver-f84999969-kggvt             1/1     Running   0          141m
ks-console-6945fdb8bc-nxgwj              1/1     Running   0          148m
ks-controller-manager-7b57f5d464-69mdr   1/1     Running   0          141m
ks-installer-75bff4fb5c-p9rf7            1/1     Running   0          151m
minio-676974644d-zl7kx                   1/1     Running   0          149m
mysql-865f7d5d4b-gq4fg                   1/1     Running   0          148m
openldap-0                               1/1     Running   0          149m
redis-5f47f9f685-j8wnd                   1/1     Running   0          3h8m

####  kubectl get pvc  --all-namespaces
NAMESPACE                      NAME                                     STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS       AGE
kubesphere-devops-system       ks-jenkins                               Bound    pvc-e01d8c90-21f3-41b2-9dca-e10c1702a8e2   8Gi        RWO            openebs-hostpath   145m
kubesphere-logging-system      data-elasticsearch-logging-data-0        Bound    pvc-bb328dd5-af8b-468f-a82a-0e1efc8d22bd   20Gi       RWO            openebs-hostpath   149m
kubesphere-logging-system      data-elasticsearch-logging-data-1        Bound    pvc-ea1aaa4a-2cb9-414e-a91f-f04cc3c33c57   20Gi       RWO            openebs-hostpath   149m
kubesphere-logging-system      data-elasticsearch-logging-discovery-0   Bound    pvc-9e8eed89-67cd-4acf-b34f-a53e7058f936   4Gi        RWO            openebs-hostpath   149m
kubesphere-monitoring-system   prometheus-k8s-db-prometheus-k8s-0       Bound    pvc-78c520ff-2768-4cc4-975b-b8bab8920ff7   20Gi       RWO            openebs-hostpath   144m
kubesphere-monitoring-system   prometheus-k8s-db-prometheus-k8s-1       Bound    pvc-168cbc9c-41f6-400a-b5fc-812e20a17e5c   20Gi       RWO            openebs-hostpath   144m
kubesphere-system              etcd-pvc                                 Bound    pvc-a23b6c6f-de42-43bf-b3ef-8df5593133d3   20Gi       RWO            openebs-hostpath   149m
kubesphere-system              minio                                    Bound    pvc-03df79e3-1420-4ac0-95aa-7f7145084fd9   20Gi       RWO            openebs-hostpath   150m
kubesphere-system              mysql-pvc                                Bound    pvc-9e337df0-3e0b-4e63-ab47-6d070c090c24   20Gi       RWO            openebs-hostpath   150m
kubesphere-system              openldap-pvc-openldap-0                  Bound    pvc-c7971177-c6e8-4350-9b9f-9bd0eafa7817   2Gi        RWO            openebs-hostpath   151m
kubesphere-system              redis-pvc                                Bound    pvc-a426c9b5-cfa0-4356-8257-2878696bc355   2Gi        RWO            openebs-hostpath   151m

####  Open the App Store web page and report an error

Request URL: http://139.198.1.16:30880/kapis/openpitrix.io/v1/apps?orderBy=create_time&paging=limit%3D12%2Cpage%3D1&conditions=status%3Dactive%2Crepo_id%3Drepo-helm&reverse=true
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 139.198.1.16:30880
Referrer Policy: strict-origin-when-cross-origin

####  openpitrix-hyperpitrix  logs

create_time, status_time, update_time FROM app_version WHERE (`active` = 0) AND (`app_id` = 'app-qp8XP60qPJvQ') AND (`status` != 'deleted') ORDER BY sequence DESC] (event.go:48)

2020-11-03 06:21:46.37088 -DEBUG- dbr.select spend 0.42ms: map[sql:SELECT version_id, active, app_id, owner, owner_path, name, description, package_name, home, icon, screenshots, maintainers, keywords, sources, readme, status, review_id, message, type, sequence, create_time, status_time, update_time FROM app_version WHERE (`active` = 0) AND (`app_id` = 'app-R0GYQBQmLDoM') AND (`status` != 'deleted') ORDER BY sequence DESC] (event.go:48)

2020-11-03 06:21:46.37132 -DEBUG- dbr.select spend 0.38ms: map[sql:SELECT version_id, active, app_id, owner, owner_path, name, description, package_name, home, icon, screenshots, maintainers, keywords, sources, readme, status, review_id, message, type, sequence, create_time, status_time, update_time FROM app_version WHERE (`active` = 0) AND (`app_id` = 'app-V2kANRQ6Jw7p') AND (`status` != 'deleted') ORDER BY sequence DESC] (event.go:48)

2020-11-03 06:21:46.37176 -DEBUG- dbr.select spend 0.38ms: map[sql:SELECT version_id, active, app_id, owner, owner_path, name, description, package_name, home, icon, screenshots, maintainers, keywords, sources, readme, status, review_id, message, type, sequence, create_time, status_time, update_time FROM app_version WHERE (`active` = 0) AND (`app_id` = 'app-XZKl4OVyWqO0') AND (`status` != 'deleted') ORDER BY sequence DESC] (event.go:48)

2020-11-03 06:21:46.37229 -DEBUG- dbr.select spend 0.47ms: map[sql:SELECT version_id, active, app_id, owner, owner_path, name, description, package_name, home, icon, screenshots, maintainers, keywords, sources, readme, status, review_id, message, type, sequence, create_time, status_time, update_time FROM app_version WHERE (`active` = 0) AND (`app_id` = 'app-y7VMNVQ6Jw7p') AND (`status` != 'deleted') ORDER BY sequence DESC] (event.go:48)

2020-11-03 06:21:46.37233 -INFO- Handled request [DescribeApps] [&{UserId:system OwnerPath::system AccessPath:}] exec_time is [2.057169771s] (grpc_server.go:188)

####  kubectl get job -n openpitrix-system

NAME                              COMPLETIONS   DURATION   AGE
hyperpitrix-generate-kubeconfig   1/1           82s        26m
hyperpitrix-release-app-job       1/1           4s         13m

####  ks-apiserver  logs

E1103 21:51:46.218389       1 utils.go:32] /home/runner/work/kubesphere/kubesphere/pkg/kapis/openpitrix/v1/handler.go:931 rpc error: code = Unavailable desc = transport is closing
E1103 21:51:46.218396       1 utils.go:32] /home/runner/work/kubesphere/kubesphere/pkg/kapis/openpitrix/v1/handler.go:931 rpc error: code = Unavailable desc = transport is closing
I1103 21:51:46.218440       1 apiserver.go:539] 10.233.97.8 - "GET /kapis/openpitrix.io/v1/apps?orderBy=create_time&paging=limit%3D12%2Cpage%3D1&conditions=status%3Dactive%2Crepo_id%3Drepo-helm&reverse=true HTTP/1.1" 500 58 69504ms
I1103 21:51:46.218454       1 apiserver.go:539] 10.233.97.8 - "GET /kapis/openpitrix.io/v1/apps?orderBy=create_time&paging=limit%3D12%2Cpage%3D1&conditions=status%3Dactive%2Crepo_id%3Drepo-helm&reverse=true HTTP/1.1" 500 58 69901ms
E1103 21:54:16.222724       1 apps.go:93] rpc error: code = Unavailable desc = transport is closing
E1103 21:54:16.222739       1 apps.go:93] rpc error: code = Unavailable desc = transport is closing
E1103 21:54:16.222758       1 handler.go:419] rpc error: code = Unavailable desc = transport is closing
E1103 21:54:16.222750       1 handler.go:419] rpc error: code = Unavailable desc = transport is closing
E1103 21:54:16.222764       1 handler.go:930] rpc error: code = Unavailable desc = transport is closing
E1103 21:54:16.222766       1 handler.go:930] rpc error: code = Unavailable desc = transport is closing

Openebs has successfully created PVC, I wonder what the problem is??

**Comment by wangchengli** [comment]
I have the same issue, I have tired redeploy, redo the job followed the guide from forums. not resolved.

**Comment by xyz-li** [comment]
Does the service `hyperpitrix` exists?

`kubectl get svc -n openpitrix-system`

**Comment by misteruly** [comment]
> Does the service `hyperpitrix` exist?
> 
> `kubectl get svc -n openpitrix-system`

openpitrix-system              hyperpitrix                               ClusterIP   None            <none>        9123/TCP,9121/TCP,9100/TCP,9102/TCP,9113/TCP,9122/TCP,9104/TCP,9118/TCP,9106/TCP,9101/TCP,9108/TCP,9103/TCP,9107/TCP   8m55s

**Comment by misteruly** [comment]
> I have the same issue, I have tired redeploy, redo the job followed the guide from forums. not resolved.

<img width="1063" alt="open app store job" src="https://user-images.githubusercontent.com/31399968/98126426-89ee1d00-1ef0-11eb-829e-5e6214e33797.png">

All jobs were started and no errors were reported

**Comment by xyz-li** [comment]
May  I login `http://139.198.1.16:30880/apps`?

**Comment by misteruly** [comment]
> May I login `http://139.198.1.16:30880/apps`?

Yes, the default account and password

**Comment by wangchengli** [comment]
Any progress about this? or Is there any workaround way to bypass?

**Comment by wangchengli** [comment]
New update about this issue. I found calico network set mtu=1500 in my env, could not transfer message with large body across nodes. So I update calico, set mtu=1440, then re-apply by kubectl command. Now it works for me. Hope it is help for you.

**Comment by misteruly** [comment]
> New update about this issue. I found calico network set mtu=1500 in my env, could not transfer message with large body across nodes. So I update calico, set mtu=1440, then re-apply by kubectl command. Now it works for me. Hope it is help for you.

@xyz-li    They're working on it,That doesn't seem to be the problem

**Comment by zheng1** [comment]
Resolved. The reason is that the tcp window returned is too small due to 100% cpu on the node where the hyperpitrix is located.
