### ISSUE TITLE
Feature: multi-cluster helm app deploy

### ISSUE THREAD

**Issue by lxm** [kubesphere/kubesphere#3075]
# multi-cluster helm app deploy

Applications need to be deployed to multi clustes or one cluster in diffent namespaces, There is no communication between application's releases. Configs are almost the same between different releases, some config need to be set differently between releases. Sometimes need to do batch configs change for releases.

**Comment by zryfish** [comment]
That requires lots of effort to achieve that goal.  
First, we use kube-federation to do multicluster deployment, which can only support K8s native object and CRD. But we use OpenPitrix to install helm chart, that means OpenPitrix needs to find a way to deploy helm chart using CRD.
Second, not only using CRD to deploy application, but also needs to find a way to federate those CRDs, and treat them as parts of an application. 
We are glad to hear from the community, and any proposals are welcome.
