### ISSUE TITLE
Feature: Add member cluster on console

### ISSUE THREAD

**Issue by lxm** [kubesphere/kubesphere#3076]
When addingh/removing member clusters. We need to do as follows:

```
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/v3.0.0/deploy/kubesphere-installer.yaml
```

// edit cluster-configuration.yaml (or maybe just use the previous one)

```
kubectl apply -f cluster-configuration.yaml

```

## Direct connection

The console requires a kubeconfig. So when kubesphere host cluster got a kubeconfig, it can execute `kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/v3.0.0/deploy/kubesphere-installer.yaml` automatically, if add a editor or some options to generate a `cluster-configuration.yaml` for member cluster and add some default values such as `jwtToken`, the next operation `kubectl apply -f cluster-configuration.yaml` will get to be automatically.

## Reverse connection(Tower)
Just as the `Direct connection`, there's a precondition is that host cluster need to get connected by member cluster before it can do operation on the member cluster. Then do the rest as `Direct connection`

If you add or delete clusters frequently, the above functions will be very useful

**Comment by zryfish** [comment]
Yeah, that's reasonable, we are working on provisioning KubeSphere clusters from the console. I'll update this issue once there is progress.

**Comment by yuswift** [comment]
> Yeah, that's reasonable, we are working on provisioning KubeSphere clusters from the console. I'll update this issue once there is progress.

Is there any progress on provisioning KubeSphere clusters from the console :)
