### ISSUE TITLE
Feature: Support use external prometheus-operator

### ISSUE THREAD

**Issue by lxm** [kubesphere/kubesphere#3078]
Kubesphere must install a custom prometheus-operator into member cluster to provide monitor functions currently. In some managed kubernetes such as alibaba ACK, there will be exists prometheus-operator like ack-prometheus-operator that provide prom CRD.

So if we can support not to install prometheus-operator and still enable the monitor function, in this situation, we need to set the monitor datasource, set datasource for custom monitor Dashabord

**Comment by benjaminhuo** [comment]
This feature is in KubeSphere v3.1's plan

**Comment by RolandMa1986** [comment]
/duplicate
@lxm Please close this issue, if you think #3068 can cover your scenario.
