### ISSUE TITLE
Feature: Support import dashboards on grafana.com

### ISSUE THREAD

**Issue by lxm** [kubesphere/kubesphere#3079]
Support import dashboards on grafana.com

**Comment by FeynmanZhou** [comment]
+1, It looks pretty cool if the [Grafana dashboards](https://grafana.com/grafana/dashboards) can be imported to KubeSphere Custom Monitoring Dashboard.

**Comment by benjaminhuo** [comment]
We do have plans to import Grafana dashboard into KubeSphere custom monitoring dashboard: https://github.com/kubesphere/kubesphere/issues/3067

@huanggze @junotx

**Comment by benjaminhuo** [comment]
You're welcomed to participate in the development of this feature

**Comment by benjaminhuo** [comment]
Let's close this issue and track it in https://github.com/kubesphere/kubesphere/issues/3067
