### ISSUE TITLE
DevOps Project admin cannot download artifacts

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#3083]
**Describe the Bug**
DevOps Project admin cannot download artifacts.

![image](https://user-images.githubusercontent.com/8263040/98190877-f6016d00-1f52-11eb-90c0-8da543ad205a.png)

**Versions Used**
KubeSphere: v3.0.0

/kind bug
/milestone 3.1.0
/assign @wansir

**Comment by LinuxSuRen** [comment]
It works with a user who has the role `platform-admin`. Which role do you use in this case?
