### ISSUE TITLE
Can not operate offline cluster

### ISSUE THREAD

**Issue by lxm** [kubesphere/kubesphere#3084]
In some cases, we need to delete a member cluster.

The right thing to do is to delete cluster in  kubesphere first and then shutdown or delete the member cluster.

But if we delete the member cluster first permanently, we cloud not enter kubesphere's cluster manage page any more.

Then we can execute `kubectl delete cluster xxxx`,but if some workspaces were associated with the deleted cluster, the cluster will keep on the workspace.

**Comment by yuswift** [comment]
@zryfish @wansir 
Should we delete ws while unbound clusters?

**Comment by LinuxSuRen** [comment]
> @zryfish @wansir
> Should we delete ws while unbound clusters?

It be good to let users make this decision.
