### ISSUE TITLE
show installed success,but cannot login

### ISSUE THREAD

**Issue by chengliangkaka** [kubesphere/kubesphere#3088]
# show installed success,but cannot login
redis,openldap is pending
ks-apiserver,ks-controller-manager show CrashLoopBackOff
![image](https://user-images.githubusercontent.com/11498055/98235361-a8a9ed80-1f9c-11eb-8ffb-fb454a0e784e.png)
![image](https://user-images.githubusercontent.com/11498055/98235431-c11a0800-1f9c-11eb-97fe-47fe771b08c5.png)
![image](https://user-images.githubusercontent.com/11498055/98235490-d0995100-1f9c-11eb-9d12-f1e87a26eb41.png)

**Comment by yuswift** [comment]
Could you show the logs of `ks-apiserver`? It may be caused by storage.
Run `kubectl get pvc -a` to make all of your pvc have been created successfully. If not, see `openebs` pod error if you are using `openebs` as your default storage class.

**Comment by chengliangkaka** [comment]
this is ks-apiserver logs, show cannot connect to redis
![image](https://user-images.githubusercontent.com/11498055/98248902-8e7a0a80-1fb0-11eb-96b5-c94442c24266.png)
i use openebs as default storage class
![image](https://user-images.githubusercontent.com/11498055/98249055-c5502080-1fb0-11eb-85c3-98af06577221.png)

**Comment by RolandMa1986** [comment]
Hi @chengliangkaka ,  Thanks for your feedback.  It seems like you have met an issue of storage, which blocked the Redis pod.
Please make sure you have enough disk space on your host. And you have right permission on "/var/openebs/local/" of the host. If both of the conditions are satisfied. Please find logs of the following pod `kubectl get pod -n kube-system |grep openebs`.

You are welcomed to join our [forum](https://kubesphere.com.cn/forum/), If you have further questions.

**Comment by chengliangkaka** [comment]
thank you, i use All-in-one Installation mode install master/worker node,
then on two else worker machine install k8s, then join the master node.
success installed
