### ISSUE TITLE
openpitrix-hyperpitrix-deployment 在创建过程 提示数据库不能链接

### ISSUE THREAD

**Issue by lzdtech** [kubesphere/kubesphere#3090]
openpitrix-db-init 容器查看日志提示如下（XXX是IP地址）
ERROR 1130 (HY000): Host 'XXX.XXX.XXX.XXX' is not allowed to connect to this

更改 "mysql" 数据库里的 "user" 表里的 "host" 项，从"localhost"改称"%"

却提示：Access denied for user 'root'@'XXX.XXX.XXX.XXX' (using password: YES)

**Comment by RolandMa1986** [comment]
Hi @lzdtech ,
We appreciate your feedback. But please also notice that:
**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**
You are welcomed to join the forum. And there are more contributors who would like to provide help.

**Comment by RolandMa1986** [comment]
/close
I'm going to close this one because of no further info. Please reopen it, if you think this is a bug.
