### ISSUE TITLE
.git/info/refs?service=git-upload-pack: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by kahramanakyil** [kubesphere/kubesphere#3093]
**What's your question**
I am getting git-upload-pack: x509: certificate signed by unknown authority when building a New Service from Source Code Repository. Kubesphere has been installed behind a corporates proxy, I have installed the certificate inside '-n kubesphere-devops-system ks-jenkins' but did not work. 
cp ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
update-ca-certificates
To connect https Code URL what should I do? Also adding App Repository with https url is not working with same reason. 

**Environment: OS & Hardware Information**
k8s v1.18.6 on Ubuntu 18.04 EC2
8cpu 32GB

**Error logs or message (Attach logs or screenshot)**
.git/info/refs?service=git-upload-pack: x509: certificate signed by unknown authority

**Installer Version**
v3.0.0

**Comment by RolandMa1986** [comment]
Hi @kahramanakyil , 
The pipeline is run inside of a "Node" Agent. Which is based on the [Jenkins Kubernetes plugin](https://plugins.jenkins.io/kubernetes/).  If you are using a self-signed certificate, you probably need `update-ca-certificates` inside the node. 

Please Join the [slack](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE) if you need more helps.

/support
/area devops

**Comment by kahramanakyil** [comment]
Actually I have added Host Path Volume(/usr/local/share/ca-certificates/ and /etc/ssl/certs/) for each Kubernetes Pod Template on the Jenkins GUI -> Manage Jenkins -> Configure Settings.  So, agent will use the same certificate which is shared by host, but did not work. 
Is there any guide that I can follow to solve this problem? 


I1109 15:05:46.122557 1 docker.go:575] pulling image kubesphere/java-8-runtime:v2.1.0: [==================================================>] 6.708kB/6.708kB
I1109 15:05:46.382107 1 sti.go:205] Preparing to build 192.168.1.29:5000/herobackend:latest
I1109 15:05:46.382053 1 docker.go:800] Image sha256:ac3c7f3ffb7bc3a3aba93510a1d948a2a33970a1947b80122db92b810df39423 contains scripts-url set to "image:///usr/local/s2i"
I1109 15:05:46.383469 1 docker.go:506] Using locally available image "kubesphere/java-8-runtime:v2.1.0"
I1109 15:05:46.384917 1 clone.go:39] Cloning sources into "/tmp/s2i106645238/upload/tmp"
Cloning into '/tmp/s2i106645238/upload/tmp'...
fatal: unable to access 'https://git.hero.com/demo-projects/devops.git/': SSL certificate problem: unable to get local issuer certificate
I1109 15:05:46.774953 1 cleanup.go:33] Removing temporary directory /tmp/s2i106645238
E1109 15:05:46.774899 1 git.go:193] Clone failed: source https://username:password@git.hero.com/demo-projects/devops.git, target /tmp/s2i106645238/upload/tmp, with output "exit status 128"
I1109 15:05:46.775360 1 s2i.go:75] Build failed
I1109 15:05:46.774939 1 clone.go:47] error: git clone failed: exit status 128
I1109 15:05:46.774960 1 fs.go:302] Removing directory '/tmp/s2i106645238'
E1109 15:05:46.775381 1 errors.go:307] An error occurred: exit status 128

**Comment by RolandMa1986** [comment]
It seems like you are using S2I to build the source code. Please follow the [guidance](https://v2-1.docs.kubesphere.io/docs/developer/s2i-template/) to customize your image. S2I is not part of the Jenkins.

**Comment by kahramanakyil** [comment]
Yes this is exactly what I am looking for. Thanks a lot. @RolandMa1986

**Comment by idlej** [comment]
> Yes this is exactly what I am looking for. Thanks a lot. @RolandMa1986

HI,
but how  to add self-signed CA to this s2i tool?

**Comment by RolandMa1986** [comment]
> HI,
> but how to add self-signed CA to this s2i tool?

Hi there,
Please see the [document ](https://v2-1.docs.kubesphere.io/docs/developer/s2i-template/) about how to customize the s2i tool.  Generally, You can change the dockerfile and add the following steps:

```
# 1. Install ca-certificates package:
yum install ca-certificates
# 2. Enable dynamic CA configuration feature:
update-ca-trust force-enable
# 3. Add your cert as a new file to /etc/pki/ca-trust/source/anchors/:
cp foo.crt /etc/pki/ca-trust/source/anchors/
# 4. Fininally:
update-ca-trust extract
```
