### ISSUE TITLE
ks 二次开发相关文档

### ISSUE THREAD

**Issue by long0419** [kubesphere/kubesphere#3095]
请问是否有针对ks 二次开发相关的详细文档？ 包含比如技术架构方面的一些问题。

**Comment by FeynmanZhou** [comment]
English only in GitHub.

You can see these guides in the [Chinese forum](https://kubesphere.com.cn/forum/t/development) and [kubesphere/community](https://github.com/kubesphere/community/tree/master/developer-guide).
