### ISSUE TITLE
[Question] return nil error if configuration file not exists

### ISSUE THREAD

**Issue by arugal** [kubesphere/kubesphere#3099]
https://github.com/kubesphere/kubesphere/blob/675823b978bac7560673b7509a616a79435a266a/pkg/apiserver/config/config.go#L125-L149

Hi, community

I found the comment on the `TryLoadFromDisk` method inconsistent with the actual code logic. No nil error is returned when the configuration file does not exist , please confirm :)

**Comment by RolandMa1986** [comment]
The code looks good to me. The comment may not very accurate, it should be something like:
`return nil and error, if configuration file not exists `

**Comment by arugal** [comment]
> The code looks good to me. The comment may not very accurate, it should be something like:
> `return nil and error, if configuration file not exists `

Thanks for your reply. Can I submit the PR to update comment :)

**Comment by RolandMa1986** [comment]
Sure, please go ahead.
/kind documentation
/priority low
/area apiserver
