### ISSUE TITLE
install kubesphere error always show waiting for etcd to start

### ISSUE THREAD

**Issue by Widerstehen** [kubesphere/kubesphere#3101]
[master1 172.16.0.2] MSG:
Configuration file already exists
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
WARN[23:31:55 CST] Task failed ...                              
WARN[23:31:55 CST] error: Failed to start etcd cluster: Failed to exec command: sudo -E /bin/sh -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-master1.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-master1-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://172.16.0.2:2379,https://172.16.0.3:2379,https://172.16.0.4:2379 cluster-health | grep -q 'cluster is healthy'" 
Error:  client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint https://172.16.0.4:2379 exceeded header timeout
; error #1: client: endpoint https://172.16.0.2:2379 exceeded header timeout
; error #2: client: endpoint https://172.16.0.3:2379 exceeded header timeout

error #0: client: endpoint https://172.16.0.4:2379 exceeded header timeout
error #1: client: endpoint https://172.16.0.2:2379 exceeded header timeout
error #2: client: endpoint https://172.16.0.3:2379 exceeded header timeout: Process exited with status 1 
Error: Failed to start etcd cluster: Failed to start etcd cluster: Failed to exec command: sudo -E /bin/sh -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-master1.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-master1-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://172.16.0.2:2379,https://172.16.0.3:2379,https://172.16.0.4:2379 cluster-health | grep -q 'cluster is healthy'" 
Error:  client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint https://172.16.0.4:2379 exceeded header timeout
; error #1: client: endpoint https://172.16.0.2:2379 exceeded header timeout
; error #2: client: endpoint https://172.16.0.3:2379 exceeded header timeout

error #0: client: endpoint https://172.16.0.4:2379 exceeded header timeout
error #1: client: endpoint https://172.16.0.2:2379 exceeded header timeout
error #2: client: endpoint https://172.16.0.3:2379 exceeded header timeout: Process exited with status 1
Usage:
  kk create cluster [flags]

Flags:
  -f, --filename string          Path to a configuration file
  -h, --help                     help for cluster
      --skip-pull-images         Skip pre pull images
      --with-kubernetes string   Specify a supported version of kubernetes
      --with-kubesphere          Deploy a specific version of kubesphere (default v3.0.0)
  -y, --yes                      Skip pre-check of the installation

Global Flags:
      --debug   Print detailed information (default true)

Failed to start etcd cluster: Failed to start etcd cluster: Failed to exec command: sudo -E /bin/sh -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-master1.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-master1-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://172.16.0.2:2379,https://172.16.0.3:2379,https://172.16.0.4:2379 cluster-health | grep -q 'cluster is healthy'" 
Error:  client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint https://172.16.0.4:2379 exceeded header timeout
; error #1: client: endpoint https://172.16.0.2:2379 exceeded header timeout
; error #2: client: endpoint https://172.16.0.3:2379 exceeded header timeout

error #0: client: endpoint https://172.16.0.4:2379 exceeded header timeout
error #1: client: endpoint https://172.16.0.2:2379 exceeded header timeout
error #2: client: endpoint https://172.16.0.3:2379 exceeded header timeout: Process exited with status 1

**Comment by Widerstehen** [comment]
config-sample.yaml 

apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master1, address: 172.16.0.2, internalAddress: 172.16.0.2, user: root, password: xxxxxxxx}
  - {name: master2, address: 172.16.0.3, internalAddress: 172.16.0.3, user: root, password: xxxxxxxx}
  - {name: master3, address: 172.16.0.4, internalAddress: 172.16.0.4, user: root, password: xxxxxxxx}
  - {name: node1, address: 172.16.0.7, internalAddress: 172.16.0.7, user: root, password: xxxxxxxx}
  - {name: node2, address: 172.16.0.8, internalAddress: 172.16.0.8, user: root, password: xxxxxxxx}
  - {name: node3, address: 172.16.0.9, internalAddress: 172.16.0.9, user: root, password: xxxxxxxx}
  roleGroups:
    etcd:
    - master1
    - master2
    - master3
    master:
    - master1
    - master2
    - master3
    worker:
    - node1
    - node2
    - node3
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: "公网ip"
    port: "6443"
  kubernetes:
    version: v1.17.9
    imageRepo: kubesphere

**Comment by RolandMa1986** [comment]
/area installation
@Widerstehen Please check your firewall settings. You need to ensure all ports are accessible on the [list](https://github.com/kubesphere/kubekey/blob/master/docs/network-access.md).

**Comment by Widerstehen** [comment]
@RolandMa1986 firewalld and selinux all been closed，and 2379 2380 running

**Comment by RolandMa1986** [comment]
/cc @Forest-L 
Can you help check this one? Is there something he can do to locate the root cause?

**Comment by Forest-L** [comment]
@Widerstehen  Try clearing the cluster first, ./kk delete cluster -f config-sample.yaml

**Comment by Widerstehen** [comment]
./kk delete cluster -f config-sample.yaml

./kk create cluster -f config-sample.yaml

error log

Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
ERRO[14:36:22 CST] Failed to start etcd cluster: Failed to exec command: sudo -E /bin/sh -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-master1.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-master1-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://172.16.0.2:2379,https://172.16.0.3:2379,https://172.16.0.4:2379 cluster-health | grep -q 'cluster is healthy'" 
Error:  client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint https://172.16.0.3:2379 exceeded header timeout
; error #1: client: endpoint https://172.16.0.4:2379 exceeded header timeout
; error #2: client: endpoint https://172.16.0.2:2379 exceeded header timeout

error #0: client: endpoint https://172.16.0.3:2379 exceeded header timeout
error #1: client: endpoint https://172.16.0.4:2379 exceeded header timeout
error #2: client: endpoint https://172.16.0.2:2379 exceeded header timeout: Process exited with status 1  node=172.16.0.2
Waiting for etcd to start
ERRO[14:36:22 CST] Failed to start etcd cluster: Failed to exec command: sudo -E /bin/sh -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-master3.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-master3-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://172.16.0.2:2379,https://172.16.0.3:2379,https://172.16.0.4:2379 cluster-health | grep -q 'cluster is healthy'" 
Error:  client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint https://172.16.0.2:2379 exceeded header timeout
; error #1: client: endpoint https://172.16.0.4:2379 exceeded header timeout
; error #2: client: endpoint https://172.16.0.3:2379 exceeded header timeout

error #0: client: endpoint https://172.16.0.2:2379 exceeded header timeout
error #1: client: endpoint https://172.16.0.4:2379 exceeded header timeout
error #2: client: endpoint https://172.16.0.3:2379 exceeded header timeout: Process exited with status 1  node=172.16.0.4
Waiting for etcd to start
ERRO[14:36:22 CST] Failed to start etcd cluster: Failed to exec command: sudo -E /bin/sh -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-master2.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-master2-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://172.16.0.2:2379,https://172.16.0.3:2379,https://172.16.0.4:2379 cluster-health | grep -q 'cluster is healthy'" 
Error:  client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint https://172.16.0.4:2379 exceeded header timeout
; error #1: client: endpoint https://172.16.0.3:2379 exceeded header timeout
; error #2: client: endpoint https://172.16.0.2:2379 exceeded header timeout

error #0: client: endpoint https://172.16.0.4:2379 exceeded header timeout
error #1: client: endpoint https://172.16.0.3:2379 exceeded header timeout
error #2: client: endpoint https://172.16.0.2:2379 exceeded header timeout: Process exited with status 1  node=172.16.0.3
WARN[14:36:22 CST] Task failed ...                              
WARN[14:36:22 CST] error: interrupted by error                  
Error: Failed to refresh etcd configuration: interrupted by error
Usage:
  kk create cluster [flags]

Flags:
  -f, --filename string          Path to a configuration file
  -h, --help                     help for cluster
      --skip-pull-images         Skip pre pull images
      --with-kubernetes string   Specify a supported version of kubernetes
      --with-kubesphere          Deploy a specific version of kubesphere (default v3.0.0)
  -y, --yes                      Skip pre-check of the installation

Global Flags:
      --debug   Print detailed information (default true)

Failed to refresh etcd configuration: interrupted by error

**Comment by Forest-L** [comment]
Execute the following instructions on the master1
```
export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-master1.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-master1-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://172.16.0.2:2379,https://172.16.0.3:2379,https://172.16.0.4:2379 cluster-health
```

**Comment by Widerstehen** [comment]
[root@master1 ~]# export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-master1.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-master1-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://172.16.0.2:2379,https://172.16.0.3:2379,https://172.16.0.4:2379 cluster-health
cluster may be unhealthy: failed to list members
Error:  client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint https://172.16.0.2:2379 exceeded header timeout
; error #1: client: endpoint https://172.16.0.3:2379 exceeded header timeout
; error #2: client: endpoint https://172.16.0.4:2379 exceeded header timeout

error #0: client: endpoint https://172.16.0.2:2379 exceeded header timeout
error #1: client: endpoint https://172.16.0.3:2379 exceeded header timeout
error #2: client: endpoint https://172.16.0.4:2379 exceeded header timeout

**Comment by Widerstehen** [comment]
https://172.16.0.3:2379 ? 
 http://172.16.0.3:2379 ?

**Comment by Forest-L** [comment]
https.  
systemctl status etcd and journalctl -u etcd -f

**Comment by Widerstehen** [comment]
[root@master1 ~]# systemctl status etcd or journalctl -u etcd -f
systemctl：无效选项 -- u
[root@master1 ~]# systemctl status etcd or journalctl etcd -f
● etcd.service - etcd docker wrapper
   Loaded: loaded (/etc/systemd/system/etcd.service; enabled; vendor preset: disabled)
   Active: active (running) since 三 2020-11-11 14:32:46 CST; 17min ago
 Main PID: 22628 (etcd)
    Tasks: 10
   Memory: 29.3M
   CGroup: /system.slice/etcd.service
           ├─22628 /bin/bash /usr/local/bin/etcd
           └─22633 /usr/bin/docker run --restart=on-failure:5 --env-file=/etc/etcd.env --net=host -v /etc/ssl/certs:/etc/ssl/certs:ro -v /etc/ssl/etcd/ssl:/etc/ssl/etcd/ssl:ro -v /var/lib/etcd:/var/lib...

11月 11 14:50:30 master1 etcd[22628]: 2020-11-11 06:50:30.167886 I | raft: 417ed790da614471 is starting a new election at term 144
11月 11 14:50:30 master1 etcd[22628]: 2020-11-11 06:50:30.167919 I | raft: 417ed790da614471 became candidate at term 145
11月 11 14:50:30 master1 etcd[22628]: 2020-11-11 06:50:30.167930 I | raft: 417ed790da614471 received MsgVoteResp from 417ed790da614471 at term 145
11月 11 14:50:30 master1 etcd[22628]: 2020-11-11 06:50:30.167942 I | raft: 417ed790da614471 [logterm: 1, index: 3] sent MsgVote request to 91db84284ef942cc at term 145
11月 11 14:50:30 master1 etcd[22628]: 2020-11-11 06:50:30.167950 I | raft: 417ed790da614471 [logterm: 1, index: 3] sent MsgVote request to a18da502a9d184fa at term 145
11月 11 14:50:34 master1 etcd[22628]: 2020-11-11 06:50:34.198465 E | etcdserver: publish error: etcdserver: request timed out
11月 11 14:50:34 master1 etcd[22628]: 2020-11-11 06:50:34.240560 W | rafthttp: health check for peer a18da502a9d184fa could not connect: dial tcp 172.16.0.4:2380: i/o timeout (prober "RO...RAFT_MESSAGE")
11月 11 14:50:34 master1 etcd[22628]: 2020-11-11 06:50:34.240587 W | rafthttp: health check for peer 91db84284ef942cc could not connect: dial tcp 172.16.0.3:2380: i/o timeout (prober "RO...PER_SNAPSHOT")
11月 11 14:50:34 master1 etcd[22628]: 2020-11-11 06:50:34.240595 W | rafthttp: health check for peer 91db84284ef942cc could not connect: dial tcp 172.16.0.3:2380: i/o timeout (prober "RO...RAFT_MESSAGE")
11月 11 14:50:34 master1 etcd[22628]: 2020-11-11 06:50:34.249797 W | rafthttp: health check for peer a18da502a9d184fa could not connect: dial tcp 172.16.0.4:2380: i/o timeout (prober "RO...PER_SNAPSHOT")
Unit or.service could not be found.
Unit journalctl.service could not be found.

● etcd.service - etcd docker wrapper
   Loaded: loaded (/etc/systemd/system/etcd.service; enabled; vendor preset: disabled)
   Active: active (running) since 三 2020-11-11 14:32:46 CST; 17min ago
 Main PID: 22628 (etcd)
    Tasks: 10
   Memory: 29.3M
   CGroup: /system.slice/etcd.service
           ├─22628 /bin/bash /usr/local/bin/etcd
           └─22633 /usr/bin/docker run --restart=on-failure:5 --env-file=/etc/etcd.env --net=host -v /etc/ssl/certs:/etc/ssl/certs:ro -v /etc/ssl/etcd/ssl:/etc/ssl/etcd/ssl:ro -v /var/lib/etcd:/var/lib...

11月 11 14:50:30 master1 etcd[22628]: 2020-11-11 06:50:30.167886 I | raft: 417ed790da614471 is starting a new election at term 144
11月 11 14:50:30 master1 etcd[22628]: 2020-11-11 06:50:30.167919 I | raft: 417ed790da614471 became candidate at term 145
11月 11 14:50:30 master1 etcd[22628]: 2020-11-11 06:50:30.167930 I | raft: 417ed790da614471 received MsgVoteResp from 417ed790da614471 at term 145
11月 11 14:50:30 master1 etcd[22628]: 2020-11-11 06:50:30.167942 I | raft: 417ed790da614471 [logterm: 1, index: 3] sent MsgVote request to 91db84284ef942cc at term 145
11月 11 14:50:30 master1 etcd[22628]: 2020-11-11 06:50:30.167950 I | raft: 417ed790da614471 [logterm: 1, index: 3] sent MsgVote request to a18da502a9d184fa at term 145
11月 11 14:50:34 master1 etcd[22628]: 2020-11-11 06:50:34.198465 E | etcdserver: publish error: etcdserver: request timed out
11月 11 14:50:34 master1 etcd[22628]: 2020-11-11 06:50:34.240560 W | rafthttp: health check for peer a18da502a9d184fa could not connect: dial tcp 172.16.0.4:2380: i/o timeout (prober "RO...RAFT_MESSAGE")
11月 11 14:50:34 master1 etcd[22628]: 2020-11-11 06:50:34.240587 W | rafthttp: health check for peer 91db84284ef942cc could not connect: dial tcp 172.16.0.3:2380: i/o timeout (prober "RO...PER_SNAPSHOT")
11月 11 14:50:34 master1 etcd[22628]: 2020-11-11 06:50:34.240595 W | rafthttp: health check for peer 91db84284ef942cc could not connect: dial tcp 172.16.0.3:2380: i/o timeout (prober "RO...RAFT_MESSAGE")
11月 11 14:50:34 master1 etcd[22628]: 2020-11-11 06:50:34.249797 W | rafthttp: health check for peer a18da502a9d184fa could not connect: dial tcp 172.16.0.4:2380: i/o timeout (prober "RO...PER_SNAPSHOT")
Hint: Some lines were ellipsized, use -l to show in full.
[root@master1 ~]#

**Comment by Forest-L** [comment]
journalctl -u etcd -f

**Comment by Widerstehen** [comment]
[root@master1 ~]# journalctl -u etcd -f
-- Logs begin at 三 2020-11-11 14:19:43 CST. --
11月 11 14:56:04 master1 etcd[22628]: 2020-11-11 06:56:04.264469 W | rafthttp: health check for peer a18da502a9d184fa could not connect: dial tcp 172.16.0.4:2380: i/o timeout (prober "ROUND_TRIPPER_SNAPSHOT")
11月 11 14:56:09 master1 etcd[22628]: 2020-11-11 06:56:09.254623 W | rafthttp: health check for peer 91db84284ef942cc could not connect: dial tcp 172.16.0.3:2380: i/o timeout (prober "ROUND_TRIPPER_SNAPSHOT")
11月 11 14:56:09 master1 etcd[22628]: 2020-11-11 06:56:09.254687 W | rafthttp: health check for peer 91db84284ef942cc could not connect: dial tcp 172.16.0.3:2380: i/o timeout (prober "ROUND_TRIPPER_RAFT_MESSAGE")
11月 11 14:56:09 master1 etcd[22628]: 2020-11-11 06:56:09.254711 W | rafthttp: health check for peer a18da502a9d184fa could not connect: dial tcp 172.16.0.4:2380: i/o timeout (prober "ROUND_TRIPPER_RAFT_MESSAGE")
11月 11 14:56:09 master1 etcd[22628]: 2020-11-11 06:56:09.264686 W | rafthttp: health check for peer a18da502a9d184fa could not connect: dial tcp 172.16.0.4:2380: i/o timeout (prober "ROUND_TRIPPER_SNAPSHOT")
11月 11 14:56:09 master1 etcd[22628]: 2020-11-11 06:56:09.668050 I | raft: 417ed790da614471 is starting a new election at term 188
11月 11 14:56:09 master1 etcd[22628]: 2020-11-11 06:56:09.668147 I | raft: 417ed790da614471 became candidate at term 189
11月 11 14:56:09 master1 etcd[22628]: 2020-11-11 06:56:09.668173 I | raft: 417ed790da614471 received MsgVoteResp from 417ed790da614471 at term 189
11月 11 14:56:09 master1 etcd[22628]: 2020-11-11 06:56:09.668198 I | raft: 417ed790da614471 [logterm: 1, index: 3] sent MsgVote request to a18da502a9d184fa at term 189
11月 11 14:56:09 master1 etcd[22628]: 2020-11-11 06:56:09.668224 I | raft: 417ed790da614471 [logterm: 1, index: 3] sent MsgVote request to 91db84284ef942cc at term 189
11月 11 14:56:14 master1 etcd[22628]: 2020-11-11 06:56:14.254784 W | rafthttp: health check for peer 91db84284ef942cc could not connect: dial tcp 172.16.0.3:2380: i/o timeout (prober "ROUND_TRIPPER_SNAPSHOT")
11月 11 14:56:14 master1 etcd[22628]: 2020-11-11 06:56:14.254819 W | rafthttp: health check for peer a18da502a9d184fa could not connect: dial tcp 172.16.0.4:2380: i/o timeout (prober "ROUND_TRIPPER_RAFT_MESSAGE")
11月 11 14:56:14 master1 etcd[22628]: 2020-11-11 06:56:14.254826 W | rafthttp: health check for peer 91db84284ef942cc could not connect: dial tcp 172.16.0.3:2380: i/o timeout (prober "ROUND_TRIPPER_RAFT_MESSAGE")
11月 11 14:56:14 master1 etcd[22628]: 2020-11-11 06:56:14.264861 W | rafthttp: health check for peer a18da502a9d184fa could not connect: dial tcp 172.16.0.4:2380: i/o timeout (prober "ROUND_TRIPPER_SNAPSHOT")
11月 11 14:56:16 master1 etcd[22628]: 2020-11-11 06:56:16.917914 I | raft: 417ed790da614471 is starting a new election at term 189
11月 11 14:56:16 master1 etcd[22628]: 2020-11-11 06:56:16.917944 I | raft: 417ed790da614471 became candidate at term 190
11月 11 14:56:16 master1 etcd[22628]: 2020-11-11 06:56:16.917956 I | raft: 417ed790da614471 received MsgVoteResp from 417ed790da614471 at term 190
11月 11 14:56:16 master1 etcd[22628]: 2020-11-11 06:56:16.917964 I | raft: 417ed790da614471 [logterm: 1, index: 3] sent MsgVote request to 91db84284ef942cc at term 190
11月 11 14:56:16 master1 etcd[22628]: 2020-11-11 06:56:16.917971 I | raft: 417ed790da614471 [logterm: 1, index: 3] sent MsgVote request to a18da502a9d184fa at term 190
11月 11 14:56:19 master1 etcd[22628]: 2020-11-11 06:56:19.203885 E | etcdserver: publish error: etcdserver: request timed out
11月 11 14:56:19 master1 etcd[22628]: 2020-11-11 06:56:19.254939 W | rafthttp: health check for peer 91db84284ef942cc could not connect: dial tcp 172.16.0.3:2380: i/o timeout (prober "ROUND_TRIPPER_RAFT_MESSAGE")
11月 11 14:56:19 master1 etcd[22628]: 2020-11-11 06:56:19.254968 W | rafthttp: health check for peer 91db84284ef942cc could not connect: dial tcp 172.16.0.3:2380: i/o timeout (prober "ROUND_TRIPPER_SNAPSHOT")
11月 11 14:56:19 master1 etcd[22628]: 2020-11-11 06:56:19.254975 W | rafthttp: health check for peer a18da502a9d184fa could not connect: dial tcp 172.16.0.4:2380: i/o timeout (prober "ROUND_TRIPPER_RAFT_MESSAGE")
11月 11 14:56:19 master1 etcd[22628]: 2020-11-11 06:56:19.264997 W | rafthttp: health check for peer a18da502a9d184fa could not connect: dial tcp 172.16.0.4:2380: i/o timeout (prober "ROUND_TRIPPER_SNAPSHOT")
11月 11 14:56:22 master1 etcd[22628]: 2020-11-11 06:56:22.418039 I | raft: 417ed790da614471 is starting a new election at term 190
11月 11 14:56:22 master1 etcd[22628]: 2020-11-11 06:56:22.418072 I | raft: 417ed790da614471 became candidate at term 191
11月 11 14:56:22 master1 etcd[22628]: 2020-11-11 06:56:22.418085 I | raft: 417ed790da614471 received MsgVoteResp from 417ed790da614471 at term 191
11月 11 14:56:22 master1 etcd[22628]: 2020-11-11 06:56:22.418093 I | raft: 417ed790da614471 [logterm: 1, index: 3] sent MsgVote request to 91db84284ef942cc at term 191
11月 11 14:56:22 master1 etcd[22628]: 2020-11-11 06:56:22.418101 I | raft: 417ed790da614471 [logterm: 1, index: 3] sent MsgVote request to a18da502a9d184fa at term 191
11月 11 14:56:24 master1 etcd[22628]: 2020-11-11 06:56:24.255089 W | rafthttp: health check for peer a18da502a9d184fa could not connect: dial tcp 172.16.0.4:2380: i/o timeout (prober "ROUND_TRIPPER_RAFT_MESSAGE")
11月 11 14:56:24 master1 etcd[22628]: 2020-11-11 06:56:24.255119 W | rafthttp: health check for peer 91db84284ef942cc could not connect: dial tcp 172.16.0.3:2380: i/o timeout (prober "ROUND_TRIPPER_RAFT_MESSAGE")
11月 11 14:56:24 master1 etcd[22628]: 2020-11-11 06:56:24.255129 W | rafthttp: health check for peer 91db84284ef942cc could not connect: dial tcp 172.16.0.3:2380: i/o timeout (prober "ROUND_TRIPPER_SNAPSHOT")
11月 11 14:56:24 master1 etcd[22628]: 2020-11-11 06:56:24.265315 W | rafthttp: health check for peer a18da502a9d184fa could not connect: dial tcp 172.16.0.4:2380: i/o timeout (prober "ROUND_TRIPPER_SNAPSHOT")
^C
[root@master1 ~]#

**Comment by Forest-L** [comment]
netstat -anp | grep 2380   
If netstat does not exist, you can `yum install net-tools -y`

**Comment by Widerstehen** [comment]
[root@master1 ~]# netstat -anp | grep 2380
tcp        0      0 172.16.0.2:2380         0.0.0.0:*               LISTEN      22694/etcd          
tcp        0      1 172.16.0.2:50334        172.16.0.4:2380         SYN_SENT    22694/etcd          
tcp        0      1 172.16.0.2:50322        172.16.0.4:2380         SYN_SENT    22694/etcd          
tcp        0      1 172.16.0.2:50324        172.16.0.4:2380         SYN_SENT    22694/etcd          
tcp        0      1 172.16.0.2:52410        172.16.0.3:2380         SYN_SENT    22694/etcd          
tcp        0      1 172.16.0.2:52416        172.16.0.3:2380         SYN_SENT    22694/etcd          
tcp        0      1 172.16.0.2:52421        172.16.0.3:2380         SYN_SENT    22694/etcd          
tcp        0      1 172.16.0.2:52420        172.16.0.3:2380         SYN_SENT    22694/etcd          
tcp        0      1 172.16.0.2:50328        172.16.0.4:2380         SYN_SENT    22694/etcd          
unix  3      [ ]         STREAM     CONNECTED     22380    1263/master

**Comment by Widerstehen** [comment]
```
[root@master1 ~]# netstat -anp | grep 2380
tcp        0      0 172.16.0.2:2380         0.0.0.0:*               LISTEN      22694/etcd          
tcp        0      1 172.16.0.2:50334        172.16.0.4:2380         SYN_SENT    22694/etcd          
tcp        0      1 172.16.0.2:50322        172.16.0.4:2380         SYN_SENT    22694/etcd          
tcp        0      1 172.16.0.2:50324        172.16.0.4:2380         SYN_SENT    22694/etcd          
tcp        0      1 172.16.0.2:52410        172.16.0.3:2380         SYN_SENT    22694/etcd          
tcp        0      1 172.16.0.2:52416        172.16.0.3:2380         SYN_SENT    22694/etcd          
tcp        0      1 172.16.0.2:52421        172.16.0.3:2380         SYN_SENT    22694/etcd          
tcp        0      1 172.16.0.2:52420        172.16.0.3:2380         SYN_SENT    22694/etcd          
tcp        0      1 172.16.0.2:50328        172.16.0.4:2380         SYN_SENT    22694/etcd          
unix  3      [ ]         STREAM     CONNECTED     22380    1263/master

**Comment by Forest-L** [comment]
cat /etc/etcd.env

**Comment by Widerstehen** [comment]
```
[root@master1 ~]# cat /etc/etcd.env
# Environment file for etcd v3.3.12
ETCD_DATA_DIR=/var/lib/etcd
ETCD_ADVERTISE_CLIENT_URLS=https://172.16.0.2:2379
ETCD_INITIAL_ADVERTISE_PEER_URLS=https://172.16.0.2:2380
ETCD_INITIAL_CLUSTER_STATE=new
ETCD_METRICS=basic
ETCD_LISTEN_CLIENT_URLS=https://172.16.0.2:2379,https://127.0.0.1:2379
ETCD_ELECTION_TIMEOUT=5000
ETCD_HEARTBEAT_INTERVAL=250
ETCD_INITIAL_CLUSTER_TOKEN=k8s_etcd
ETCD_LISTEN_PEER_URLS=https://172.16.0.2:2380
ETCD_NAME=etcd1
ETCD_PROXY=off
ETCD_INITIAL_CLUSTER=etcd1=https://172.16.0.2:2380,etcd2=https://172.16.0.3:2380,etcd3=https://172.16.0.4:2380
ETCD_AUTO_COMPACTION_RETENTION=8
ETCD_SNAPSHOT_COUNT=10000

# TLS settings
ETCD_TRUSTED_CA_FILE=/etc/ssl/etcd/ssl/ca.pem
ETCD_CERT_FILE=/etc/ssl/etcd/ssl/member-master1.pem
ETCD_KEY_FILE=/etc/ssl/etcd/ssl/member-master1-key.pem
ETCD_CLIENT_CERT_AUTH=true

ETCD_PEER_TRUSTED_CA_FILE=/etc/ssl/etcd/ssl/ca.pem
ETCD_PEER_CERT_FILE=/etc/ssl/etcd/ssl/member-master1.pem
ETCD_PEER_KEY_FILE=/etc/ssl/etcd/ssl/member-master1-key.pem
ETCD_PEER_CLIENT_CERT_AUTH=True

# CLI settings
ETCDCTL_ENDPOINTS=https://127.0.0.1:2379
ETCDCTL_CA_FILE=/etc/ssl/etcd/ssl/ca.pem
ETCDCTL_KEY_FILE=/etc/ssl/etcd/ssl/admin-master1-key.pem
ETCDCTL_CERT_FILE=/etc/ssl/etcd/ssl/admin-master1.pem
[root@master1 ~]#

**Comment by Forest-L** [comment]
`telnet 172.16.0.2 2380` at the master2

**Comment by Forest-L** [comment]
Are there firewalls between the machines?

**Comment by Widerstehen** [comment]
Every host firewalld is closed, telnet not work

[root@master2 ~]# telnet 172.16.0.2 2380 
Trying 172.16.0.2...

**Comment by Forest-L** [comment]
The firewall of the machine itself is off, but the firewall between the machines is not closed.

**Comment by Widerstehen** [comment]
How to close ？

**Comment by Forest-L** [comment]
How are machines created?

**Comment by Forest-L** [comment]
How to create the machines?

**Comment by Widerstehen** [comment]
I use QingCloud ECS, Centos7.7 OS , firewalld and selinux are closed by default. I don't know how to handle the firewall  between the two machaines?

**Comment by Forest-L** [comment]
@Widerstehen 
 1. Find the firewall corresponding to the machine on the cloud.
 2. Add port rules, port refer to this document https://github.com/kubesphere/kubekey/blob/master/docs/network-access.md
![image](https://user-images.githubusercontent.com/50984129/98784965-d8427500-2436-11eb-9a0a-5322923f168e.png)

**Comment by RolandMa1986** [comment]
We have a guide about [how to install Kubershere on QingCloud](https://kubesphere.com.cn/docs/installing-on-linux/public-cloud/kubesphere-on-qingcloud-instance/). 
I guess you have chosen a "基础网络" when creating VMs.  But a "VPC 私有网络" is recommended.
/kind support

**Comment by Widerstehen** [comment]
> @Widerstehen
> 
> 1. Find the firewall corresponding to the machine on the cloud.
> 2. Add port rules, port refer to this document https://github.com/kubesphere/kubekey/blob/master/docs/network-access.md
>    ![image](https://user-images.githubusercontent.com/50984129/98784965-d8427500-2436-11eb-9a0a-5322923f168e.png)

I add port rule ,and telnet 172.16.0.2 2380, it works ,I will retry install.

**Comment by Widerstehen** [comment]
> We have a guide about [how to install Kubershere on QingCloud](https://kubesphere.com.cn/docs/installing-on-linux/public-cloud/kubesphere-on-qingcloud-instance/).
> I guess you have chosen a "基础网络" when creating VMs. But a "VPC 私有网络" is recommended.
> /kind support

I used private network, not vpc

**Comment by RolandMa1986** [comment]
Have you resolved your issues, @Widerstehen ? Please let me know if you have any other questions or close this issue.

**Comment by Cloud-Shen** [comment]
@Widerstehen I wonder how did you solve the problem in the end, I've encountered the same problem as you recently.
