### ISSUE TITLE
install ks3 on aws's eks cluster, ks3-kubectl version is too low,could i upgrade kubectl version on ks-console?

### ISSUE THREAD

**Issue by ssmmray** [kubesphere/kubesphere#3103]
### when install ks3 on eks cluster,found ks3's kubectl client version is 1.15.3,but server version is v1.18+,how to solve it  
 

/ # kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.8-eks-7c9bda", GitCommit:"7c9bda52c425d0d56d7b93f1377a826b4132c05c", GitTreeState:"clean", BuildDate:"2020-08-28T23:04:33Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
could i upgrade kubectl version of the toos kubectl on ks console ?

**Comment by RolandMa1986** [comment]
Hi @ssmmray , 
Thanks for your feedback. We will upgrade kubectl in the next release. For a temp solution, you can build your own kubectl image. 
The docker file can be found at https://github.com/kubesphere/kubectl.
After you build your image and pushed to your docker hub，edit the deployment _kubectl-admin_ under _kubesphere-controls-system_
namespace, and replace the image with yours.
`kubectl edit deployment kubectl-admin -n kubesphere-controls-system`

**Comment by ssmmray** [comment]
i execute command `kubectl edit deployment kubectl-admin -n kubesphere-controls-system` ,found images is  "- image: kubesphere/kubectl:v1.0.0"

**Comment by RolandMa1986** [comment]
kubesphere/kubectl:v1.0.0 is our latest image with kubectl 1.15.3. You can replace the image with your own build as I said.
/area console
/kind kind/feature-request
/assign @RolandMa1986

**Comment by ssmmray** [comment]
> kubesphere/kubectl:v1.0.0 is our latest image with kubectl 1.15.3. You can replace the image with your own build as I said.
> /area console
> /kind feature-request
> /assign @RolandMa1986

![image](https://user-images.githubusercontent.com/72238499/101762482-769a2700-3b18-11eb-871d-cae73d66cbfa.png)
i have replaced the images , but  the client version still no

**Comment by RolandMa1986** [comment]
@ssmmray, Please try to replace the image with "kubespheredev/kubectl:v1.18.0". And in the 3.1 release, Ks-install will install a kubectl that match to Kubernetes server version.

**Comment by ssmmray** [comment]
> @ssmmray, Please try to replace the image with "kubespheredev/kubectl:v1.18.0". And in the 3.1 release, Ks-install will install a kubectl that match to Kubernetes server version.

it's ok now, thanks
