### ISSUE TITLE
KubeSphere on AWS Quickstart occured an error "The following resource(s) failed to create: [EKSClusterStack]."

### ISSUE THREAD

**Issue by ssmmray** [kubesphere/kubesphere#3110]
create stack with s3 url  "https://aws-quickstart.s3.amazonaws.com/quickstart-qingcloud-kubesphere/templates/kubesphere-entrypoint-existing-vpc.template.yaml"  failed

the status is The following resource(s) failed to create: [EKSClusterStack].    

the eks cluster has been created and existed in aws eks-console

**Comment by Forest-L** [comment]
@ssmmray  Error message provided below

**Comment by ssmmray** [comment]
> @ssmmray Error message provided below

where could i see the error massage? i only found the status reason is "The following resource(s) failed to create: [EKSClusterStack]"

**Comment by Forest-L** [comment]
You can click the Resource button, such as:
![image](https://user-images.githubusercontent.com/50984129/99039654-ad852780-25c2-11eb-8a4a-48ac913caea8.png)

**Comment by ssmmray** [comment]
![Uploading ks_error.png…]()

**Comment by ssmmray** [comment]
> You can click the Resource button, such as:
> ![image](https://user-images.githubusercontent.com/50984129/99039654-ad852780-25c2-11eb-8a4a-48ac913caea8.png)

<img width="1312" alt="ks_error" src="https://user-images.githubusercontent.com/72238499/99040233-b88c8780-25c3-11eb-849b-2a3400750f93.png">

**Comment by ssmmray** [comment]
> You can click the Resource button, such as:
> ![image](https://user-images.githubusercontent.com/50984129/99039654-ad852780-25c2-11eb-8a4a-48ac913caea8.png)

<img width="1312" alt="ks_error" src="https://user-images.githubusercontent.com/72238499/99040716-92b3b280-25c4-11eb-92dd-80872369855a.png">

**Comment by Forest-L** [comment]
@ssmmray  Any other steps that Failed?

**Comment by ssmmray** [comment]
> @ssmmray Any other steps that Failed?

EKSStack                 The following resource(s) failed to create: [ALBIngressStack, BastionStack].
BastionStack           Resource creation cancelled
ALBIngressStack    The following resource(s) failed to create: [ALBIngressIAMRole, ALBClusterRole].
ALBClusterRole      An error occurred (InvalidParameterValueException) when calling the UpdateFunctionConfiguration operation: SubnetIds and SecurityIds must coexist or be both empty list.

**Comment by Forest-L** [comment]
Refer to this issue https://forums.aws.amazon.com/thread.jspa?threadID=246719.
If there is a problem with the VPC in your environment, try the new VPC script.

**Comment by ssmmray** [comment]
> Refer to this issue https://forums.aws.amazon.com/thread.jspa?threadID=246719.
> If there is a problem with the VPC in your environment, try the new VPC script.

Our requirement is to use the existing vpc for creating eks cluster

**Comment by Forest-L** [comment]
* You can set the Tags values like the following VPC
![image](https://user-images.githubusercontent.com/50984129/99046515-d1019f80-25cd-11eb-93fd-c0c18b73af6f.png)
* Can you try it in another area?

**Comment by ssmmray** [comment]
> * You can set the Tags values like the following VPC
>   ![image](https://user-images.githubusercontent.com/50984129/99046515-d1019f80-25cd-11eb-93fd-c0c18b73af6f.png)
> * Can you try it in another area?

how to delete the failed stack and clean up all resouce has created by the stack?

**Comment by Forest-L** [comment]
Such as:
![image](https://user-images.githubusercontent.com/50984129/99048065-0d35ff80-25d0-11eb-886f-5558fdef47db.png)

**Comment by ssmmray** [comment]
> Such as:
> ![image](https://user-images.githubusercontent.com/50984129/99048065-0d35ff80-25d0-11eb-886f-5558fdef47db.png)

![image](https://user-images.githubusercontent.com/72238499/99080347-248ae200-25fc-11eb-8379-87e7e0bf73e9.png)




delete stack failed

**Comment by ssmmray** [comment]
> Such as:
> ![image](https://user-images.githubusercontent.com/50984129/99048065-0d35ff80-25d0-11eb-886f-5558fdef47db.png)

![image](https://user-images.githubusercontent.com/72238499/99082419-19858100-25ff-11eb-93cf-f02cbde0d63b.png)
