### ISSUE TITLE
增加节点报错

### ISSUE THREAD

**Issue by freemankevin** [kubesphere/kubesphere#3111]
![image](https://user-images.githubusercontent.com/71524776/99044892-749d8080-25cb-11eb-99cc-93d4b6626830.png)

**Comment by freemankevin** [comment]
新加四个node，workrer04-07

**Comment by freemankevin** [comment]
是不支持1.17.3版本？？？？

**Comment by zryfish** [comment]
是的，不支持1.17.3，1.17目前只支持v1.17.9。中文问题请到 https://kubesphere.com.cn/forum 提交，github issue 只接受英文 issue

/cose

**Comment by freemankevin** [comment]
感谢,thanks
