### ISSUE TITLE
Prometheus pod can't be completed for a long time

### ISSUE THREAD

**Issue by freemankevin** [kubesphere/kubesphere#3114]
![image](https://user-images.githubusercontent.com/71524776/99116048-5d43af00-262e-11eb-956e-15d259e454c5.png)
![image](https://user-images.githubusercontent.com/71524776/99116099-6cc2f800-262e-11eb-9fdd-ece8838de5a9.png)

Prometheus, nothing can be done here，for help

**Comment by xyz-li** [comment]
kubectl describe po -n kubesphere-monitoring-system prometheus-k8s-0
