### ISSUE TITLE
currently use kubebuilder1,Planned upgrade kubebuilder2?

### ISSUE THREAD

**Issue by hadoop835** [kubesphere/kubesphere#3116]
currently use kubebuilder1,Planned upgrade kubebuilder2?

**Installer Version**

> v3.0.0

**Comment by RolandMa1986** [comment]
We don't have a plan to upgrade KubeBuilder yet. You may already found that most of our controllers are using the [sample-controller](https://github.com/kubernetes/sample-controller) pattern instead of KubeBuilder.
