### ISSUE TITLE
Grayscale Release is not working well, when the service app label is not the same with the servicename

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/kubesphere#3128]
**Describe the Bug**

The Grayscale Release is not working well, when the service app label is not the same with the servicename.

The service name is `reviews`, its app label is `app=reviews-test`

![image](https://user-images.githubusercontent.com/20178386/99489499-3923fd00-29a3-11eb-8559-8b2ccb16281f.png)

The deployment name is `reviews-v1`, and its app label is `app=reviews-test`

![image](https://user-images.githubusercontent.com/20178386/99489752-62448d80-29a3-11eb-93a7-e81986ac3510.png)

When create canary release, there is a mistake:

![image](https://user-images.githubusercontent.com/20178386/99490323-95d3e780-29a4-11eb-9a1b-4c2c30337341.png)

The reason is that , the workload name is `reviews-test-v2`, but it is `reviews-v2` in the API.

![image](https://user-images.githubusercontent.com/20178386/99490350-a2f0d680-29a4-11eb-9de0-d6653dbafa20.png)

![image](https://user-images.githubusercontent.com/20178386/99490503-efd4ad00-29a4-11eb-9473-fa3cca24211b.png)

The reference API URL is `http://xxx:30880/kapis/servicemesh.kubesphere.io/v1alpha2/namespaces/test/workloads/reviews-v2/health?rateInterval=30s

You can use my enviroment to identify:

139.198.120.86:30880

/assign @leoendless 
/area microservice

**Comment by leoendless** [comment]
It’s best to integrate the information needed on the UI on the backend. The current implementation is not stable.

**Comment by leoendless** [comment]
The gray release strategy is only associated with the service in the yaml, but the number of copies of workload needs to be displayed in the UI. That is the cause of instability.

**Comment by leoendless** [comment]
@zackzhangkai @zryfish
