### ISSUE TITLE
Internal error occurred: account is not active

### ISSUE THREAD

**Issue by lovewuqiang** [kubesphere/kubesphere#3132]
k8s version：v1.16.3
### **ks-controller-manager logs：**
error syncing 'admin': context deadline exceeded, requeuing
### **ks-console logs：**
{ UnauthorizedError: Not Login
    at Object.throw (/opt/kubesphere/console/server/server.js:31701:11)
    at getCurrentUser (/opt/kubesphere/console/server/server.js:9037:14)
    at renderView (/opt/kubesphere/console/server/server.js:23231:46)
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:70183:16
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:77986:37
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:70183:16
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32)
    at next (/opt/kubesphere/console/server/server.js:6871:18)
    at /opt/kubesphere/console/server/server.js:77986:37
    at dispatch (/opt/kubesphere/console/server/server.js:6870:32) message: 'Not Login' }
  --> GET / 302 1ms 43b 2020/11/19T15:13:01.701
  <-- GET /login 2020/11/19T15:13:01.702
  --> GET /login 200 5ms 14.82kb 2020/11/19T15:13:01.707
ks-apiserver logs：
E1119 15:10:14.472376       1 authenticator.go:88] account is not active, username: admin
E1119 15:10:14.472400       1 handler.go:275] account is not active
I1119 15:10:14.472415       1 apiserver.go:539] 10.244.7.130 - "POST /oauth/token HTTP/1.1" 500 46 0ms
### **other logs：**
**************************************************
#####################################################
#####################################################

Console: http://172.16.147.67:30880
Account: admin
Password: P@88w0rd

NOTES：
  1. After logging into the console, please check the
     monitoring status of service components in
     the "Cluster Management". If any service is not
     ready, please wait patiently until all components 
     are ready.
  2. Please modify the default password after login.

#####################################################
https://kubesphere.io             2020-11-19 15:10:03
#####################################################

**Comment by RolandMa1986** [comment]
Hi @lovewuqiang ,
There are some related topics in our forum, please visit https://kubesphere.com.cn/forum/d/2217-account-is-not-active for more information.

/area installation
/kind support

**Comment by wansir** [comment]
Some improvement in this PR  https://github.com/kubesphere/ks-installer/pull/1143,  admin user status is active by default. 

BTW, if the network or storage is abnormal will cause other problems.

/kind need-to-verify

**Comment by youpai** [comment]
我也遇到了这个问题，感觉安装过程太黑盒了，排查问题不方便

**Comment by wansir** [comment]
> 我也遇到了这个问题，感觉安装过程太黑盒了，排查问题不方便

Please check the pod status under `kubesphere-system`, check the logs of ks-controller-manager. Usually caused by the storage or network.

Related: https://github.com/kubesphere/kubesphere/issues/2928

**Comment by youpai** [comment]
controller-manager第一次出错的信息：
```
error syncing 'admin': Internal error occu
rred: failed calling webhook "validating-user.kubesphere.io": Post https://ks-controller-manager
.kubesphere-system.svc:443/validate-email-iam-kubesphere-io-v1alpha2-user?timeout=4s: context de
adline exceeded, requeuing
Internal error occurred: failed calling we
bhook "validating-user.kubesphere.io": Post https://ks-controller-manager.kubesphere-system.svc:
443/validate-email-iam-kubesphere-io-v1alpha2-user?timeout=4s: context deadline exceeded
```

**Comment by wansir** [comment]
After kubesphere is installed, the default account admin/P@88w0rd will be created. After the ks-controller-manager is ready to start, the user controller will encrypt the password defined in the user CRD, and the user will be converted to the active state, and then the account can log in normally. If there is a problem with storage or network, the user controller will not work properly, you can get some useful logs from ks-controller-manager. We [encrypt the password during installation](https://github.com/kubesphere/ks-installer/pull/1143), but still can’t avoid other problems caused by storage and network.

**Comment by wansir** [comment]
> failed calling webhook "validating-user.kubesphere.io": Post https://ks-controller-manager
.kubesphere-system.svc:443/validate-email-iam-kubesphere-io-v1alpha2-user?timeout=4s: context de
adline exceeded

Means that `https://ks-controller-manager.kubesphere-system.svc`cannot be accessed from kube-apiserver. Please check the status of calico-node and kube-proxy.

**Comment by youpai** [comment]
可能是`当使用 --cluster-signing-cert-file 和 --cluster-signing-key-file 参数启动时，在 kube-apiserver 中会激活 CSR 签名功能`问题，官方是RKE问题参考，二进制手动安装的集群，证书参数应该如何添加呢

**Comment by youpai** [comment]
编辑controller，command启动参数添加`--cluster-signing-cert-file`和`--cluster-signing-key-file`吗

**Comment by wansir** [comment]
> 编辑controller，command启动参数添加`--cluster-signing-cert-file`和`--cluster-signing-key-file`吗

https://github.com/kubesphere/kubesphere/issues/1925#issuecomment-591698309

I don’t think so, the main issue is request time out.

**Comment by youpai** [comment]
参考：https://kubesphere.com.cn/forum/d/2315-kubesphere30-admin/2，执行`kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io users.iam.kubesphere.io`，登录成功了……

**Comment by wansir** [comment]
> https://kubesphere.com.cn/forum/d/2315-kubesphere30-admin/2，执行`kubectl

:sweat_smile: Validatingwebhook is used for data verification, network problem still exist.

**Comment by Suozz** [comment]
@wansir `2021/03/02 15:36:23 http: TLS handshake error from 10.42.0.0:24028: remote error: tls: bad certificate
2021/03/02 15:36:23 http: TLS handshake error from 10.42.0.0:41717: remote error: tls: bad certificate
E0302 15:36:23.081687       1 user_controller.go:332] Internal error occurred: failed calling webhook "validating-user.kubesphere.io": Post "https://ks-controller-manager.kubesphere-system.svc:443/validate-email-iam-kubesphere-io-v1alpha2-user?timeout=30s": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
E0302 15:36:23.081726       1 user_controller.go:226] error syncing 'admin': Internal error occurred: failed calling webhook "validating-user.kubesphere.io": Post "https://ks-controller-manager.kubesphere-system.svc:443/validate-email-iam-kubesphere-io-v1alpha2-user?timeout=30s": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0, requeuing
E0302 15:38:59.770389       1 clusterrolebinding_controller.go:209] clusterrolebinding 'pod-impersonation-shell-x6h2m' in work queue no longer exists
I0302 15:38:59.770417       1 clusterrolebinding_controller.go:186] Successfully synced key:pod-impersonation-shell-x6h2m`

**Comment by Suozz** [comment]
> @wansir 2021/03/02 15:36:23 http: TLS handshake error from 10.42.0.0:24028: remote error: tls: bad certificate
> 2021/03/02 15:36:23 http: TLS handshake error from 10.42.0.0:41717: remote error: tls: bad certificate
> E0302 15:36:23.081687 1 user_controller.go:332] Internal error occurred: failed calling webhook "validating-user.kubesphere.io": Post "https://ks-controller-manager.kubesphere-system.svc:443/validate-email-iam-kubesphere-io-v1alpha2-user?timeout=30s": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
> E0302 15:36:23.081726 1 user_controller.go:226] error syncing 'admin': Internal error occurred: failed calling webhook "validating-user.kubesphere.io": Post "https://ks-controller-manager.kubesphere-system.svc:443/validate-email-iam-kubesphere-io-v1alpha2-user?timeout=30s": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0, requeuing
> E0302 15:38:59.770389 1 clusterrolebinding_controller.go:209] clusterrolebinding 'pod-impersonation-shell-x6h2m' in work queue no longer exists
> I0302 15:38:59.770417 1 clusterrolebinding_controller.go:186] Successfully synced key:pod-impersonation-shell-x6h2m

this is my issue. seems like some certification is incorrect. I am running kubesphere on rancher.
So sad. --!

**Comment by wansir** [comment]
@Suozz  For more information about the issue and solution, https://github.com/kubesphere/kubesphere/issues/2928
