### ISSUE TITLE
Deploy snapshot controller failed in google gke

### ISSUE THREAD

**Issue by willzhang** [kubesphere/kubesphere#3137]
GKE version，static version 1.17.13-gke.2001

error log:
```
TASK [common : Kubesphere | Creating snapshot controller values] ***************
changed: [localhost] => (item={'name': 'custom-values-snapshot-controller', 'file': 'custom-values-snapshot-controller.yaml'})
TASK [common : Kubesphere | Remove old snapshot crd] ***************************
changed: [localhost]
TASK [common : Kubesphere | Deploy snapshot controller] ************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm upgrade --install snapshot-controller /kubesphere/kubesphere/snapshot-controller
 -f /kubesphere/kubesphere/custom-values-snapshot-controller.yaml --namespace kube-system\n", "delta": "0:00:01.131094", "end": "2020-11-19 05:55:53.560930",
 "msg": "non-zero return code", "rc": 1, "start": "2020-11-19 05:55:52.429836", "stderr": "Error: rendered manifests contain a resource that already exists. 
Unable to continue with install: ClusterRole \"snapshot-controller-runner\" in namespace \"\" exists and cannot be imported into the current release: invalid
 ownership metadata; label validation error: missing key \"app.kubernetes.io/managed-by\": must be set to \"Helm\"; annotation validation error: missing key 
\"meta.helm.sh/release-name\": must be set to \"snapshot-controller\"; annotation validation error: missing key \"meta.helm.sh/release-namespace\": must be s
et to \"kube-system\"", "stderr_lines": ["Error: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole \"sn
apshot-controller-runner\" in namespace \"\" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: miss
ing key \"app.kubernetes.io/managed-by\": must be set to \"Helm\"; annotation validation error: missing key \"meta.helm.sh/release-name\": must be set to \"s
napshot-controller\"; annotation validation error: missing key \"meta.helm.sh/release-namespace\": must be set to \"kube-system\""], "stdout": "Release \"sna
pshot-controller\" does not exist. Installing it now.", "stdout_lines": ["Release \"snapshot-controller\" does not exist. Installing it now."]}
PLAY RECAP *********************************************************************
localhost                  : ok=18   changed=13   unreachable=0    failed=1    skipped=3    rescued=0    ignored=0
```

change version to 1.16.13-gke.401 install success.

**Comment by stoneshi-yunify** [comment]
It looks like GKE already have snapshot-controller installed, so ks should not install it again.

Possible fixes:
- verify if snapshot-controller already installed, skip to next step if installed 
- continue install no matter if snapshot-controller already presents, but don't treat the failure like this case as an error.

/cc @pixiake

**Comment by pixiake** [comment]
I saw the logic of installing snapshot-controller，there is already the task of deleting old resources.
https://github.com/kubesphere/ks-installer/blob/659c0cc3f9bda78951ec5315882ed83e6d73dbff/roles/common/tasks/main.yaml#L61
Is it possible to delete all the resources in the chart ?
https://github.com/kubesphere/ks-installer/tree/master/roles/common/files/snapshot-controller

@min-zh @stoneshi-yunify

**Comment by ItGeneral** [comment]
you can build a configmap replace rbac-snapshot-controller.yaml, then mount this configmap to container.
this blog can solve this problem: [how to install kubesphere on gke 1.18](https://mp.weixin.qq.com/s?__biz=MzIxMzY1NTM3Nw==&tempkey=MTEwN19hYmI3b1UxVFQ5WlN6RDVLckdPZ1NmNkJWWEV2R1BYQmttX2J5QThFamNtMUJtX3J4WklBX0VVeTQ5Q0o0NEFMSl94ZVhEOFMwSEg2TUQ0X3J3ci0tQmdzdnluWmVWMHY2bWtYbzlfWWRpdFBFSlEzWTVYd1RfRjhCRDd4ZUNJWmRCRnpTc0x3WkhVY0lCbTEwVHEzUlVmb1pwSUR5QTZ3Mm5uRVRnfn4%3D&chksm=17b2c8c420c541d28b86509b7ec816ece9526dcc0e6de2a03f2cc47809a7e92d9d81efe3ee4d#rd)
