### ISSUE TITLE
Using yaml mode to create endpoints indicates that the creation is successful. Actually, endpoints are not created, but can be created successfully through kubectl

### ISSUE THREAD

**Issue by stxufnupyud** [kubesphere/kubesphere#3150]
endpoints.yaml

apiVersion: v1
kind: Endpoints
metadata:
  name: oracle
  namespace: my-service
subsets:
  - addresses:
      - ip: 192.168.100.161
    ports:
      - port: 1521

**Comment by stxufnupyud** [comment]
kubectl apply -f endpoints can be created successfully

**Comment by RolandMa1986** [comment]
Hi @stxufnupyud, is this a feature request or something else? I don't think we can edit Endpoints in Kubesphere UI currently.

**Comment by RolandMa1986** [comment]
Hi @stxufnupyud, Could you provide detailed comments on this issue? 

/kind support
/question
/area console
