### ISSUE TITLE
Transsfer `StorageClass config` from front to bancend

### ISSUE THREAD

**Issue by min-zh** [kubesphere/kubesphere#3166]

**Comment by stoneshi-yunify** [comment]
The background:

Currently we have several built-in storage provisioners which aims to ease the user's input when they want to create the storage class for these storages:

![image](https://user-images.githubusercontent.com/70880165/101568243-4023b580-3a0d-11eb-85f7-372e63ff92df.png)

But the storage provisioners are hard coded in ks-console (see https://github.com/kubesphere/console/blob/master/src/utils/constants.js#L611-L786) , so it's not flexible and scalable. The thought is moving them to the kubesphere backend so user can manage and extend them easily.

/cc @stoneshi-yunify

**Comment by stoneshi-yunify** [comment]
this issue won't be fixed. in future we may remove the gluterfs and ceph template, as we don't have effort the test their changes. user need to use the custom template for their storage provisioners.
