### ISSUE TITLE
some risks of multi-cluster authorization for workspace

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#3169]
**Describe the Bug**
When adding a member cluster (some workspaces have been created) to the new host cluster, if the workspace in the member cluster contains the label `kubefed.io/managed: true`, and then create a workspace with the same name in the new host cluster but do not authorize the member cluster. The workspace on the member cluster will be managed by kubefed-controller, but the member cluster is not authorized to this workspace so that the workspace will be deleted by kubefed-controller.

**Versions Used**
KubeSphere: v3.0.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Comment by RolandMa1986** [comment]
@liuyp2018  This scenario needs to be verified. 
/kind need-to-verify
