### ISSUE TITLE
KubeSphere web console support ephemeral-storage

### ISSUE THREAD

**Issue by vincenthe11** [kubesphere/kubesphere#3184]
**What's it about?**
 Currently KubeSphere web console doesn't support ephemeral-storage to configure limit and request. 
k8s support in 1.15
![image](https://user-images.githubusercontent.com/8400716/101321640-a63efa00-38a0-11eb-9908-104e970e2a1d.png)

/area console
/area storage
/kind feature-request

**Comment by stoneshi-yunify** [comment]
dup of #4993
