### ISSUE TITLE
Choose whether to cascade delete related resources when deleting workspace

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#3192]
**What's it about?**

Choose whether to cascade delete related resources when deleting workspace, avoid accidental deletion of related resources.

/kind feature-request

**Comment by RolandMa1986** [comment]
@wansir 
The following resources are directly owned by CRD _WorkspaceTemplate_ and _Workspace_.  
## WorkspaceTemplate
- [ ] WorkspaceRoleBinding
- [ ] WorkspaceRole
- [ ] Workspace
- [ ] Groups(todo)

## Workspace
- [x] Namespace
- [ ] DevOpsProject

By using PropagationPolicy options, we can choose whether those resources are cascade deleted. However, this would leave a lot of garbage. And not all of the resources can be re-assigned after the workspace deleted. It's also not convinced that associate with those resources automatically when creating a workspace with the same name.
So we should decide which resources can be kept or always be deleted.

**Comment by wansir** [comment]
I think namespace and devops project can be deleted in cascade or not, we need to force delete resources that cannot be transferred(such as workspacerole/workspacerolebinding). Related to:  https://github.com/kubesphere/kubesphere/issues/3028

**Comment by RolandMa1986** [comment]
/milestone BackLog
This feature depends on the new Kubefed feature https://github.com/kubernetes-sigs/kubefed/issues/1348.

**Comment by xuliwenwenwen** [comment]
![13001617780676_ pic](https://user-images.githubusercontent.com/74528885/113828137-a4396900-97b6-11eb-968a-2430bda801fd.jpg)
