### ISSUE TITLE
Query logs failed when there are more than 1000 namespaces

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#3196]
**Describe the Bug**
When a user query auditing, events, and logs, it needs to list all namespaces that the user can access. These namespaces will become the parameters of the elasticsearch query DSL. The parameter of elasticsearch query DSL has a limit of 1024. So if there are many namespaces that the user can access, for example, more than 1000, the elasticsearch query DSL will be illegal, and the query will be failed.

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: 3.0.0

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by nanjofan** [comment]
Hello，Is this bug fixed in v3.1.0？
