### ISSUE TITLE
ks3  pipeline failed to deploy images to k8s 

### ISSUE THREAD

**Issue by ssmmray** [kubesphere/kubesphere#3197]
ERROR: ERROR: java.lang.RuntimeException: io.kubernetes.client.openapi.ApiException: Unauthorized
hudson.remoting.ProxyException: java.lang.RuntimeException: io.kubernetes.client.openapi.ApiException: Unauthorized

**Comment by LinuxSuRen** [comment]
hi @ssmmray , thanks for reporting this to us. I hope I can help you with this. But I've no idea how to reproduce according to your description. So I'm wondering if you can take a few minutes to provide more details about it. By the way, create an issue with [an issue template](https://github.com/kubesphere/kubesphere/issues/new?template=bug_report.md) is the best practice when you're working with or participating with the open-source community.

**Comment by ssmmray** [comment]
pipeline task can not get kubeconfig-id
![image](https://user-images.githubusercontent.com/72238499/102183843-7b305800-3ee9-11eb-9da4-fd740339a7ba.png)

**Comment by ssmmray** [comment]
at the last sttp "kubernetesDeploy", occureed this error
![image](https://user-images.githubusercontent.com/72238499/102184058-cb0f1f00-3ee9-11eb-8487-6b24d7544091.png)

**Comment by ssmmray** [comment]
![image](https://user-images.githubusercontent.com/72238499/102184372-4f61a200-3eea-11eb-984b-3452155446e6.png)

**Comment by LinuxSuRen** [comment]
It looks like you got an incorrect kubeconfig file. See also kubesphere/community#165.

**Comment by ssmmray** [comment]
> It looks like you got an incorrect kubeconfig file. See also [kubesphere/community#165](https://github.com/kubesphere/community/issues/165).
i used user "admin" to execute the task, The article is for non admin

**Comment by ssmmray** [comment]
i have tried the methods , a new error occurred 
![image](https://user-images.githubusercontent.com/72238499/102187541-137d0b80-3eef-11eb-8ad7-2eafa61fb50b.png)

**Comment by zryfish** [comment]
Make sure your credential do have the permission to deploy application in the target namespace

**Comment by ssmmray** [comment]
> Make sure your credential do have the permission to deploy application in the target namespace
 you can see the picture above , i use admin user to deploy,   the error is  " ApiException: Unauthorized" , then i tried the method in kubesphere/community#165 , my Enterprise space is test ,  so replaced " your project name" by "test", the error is "forbidden"

**Comment by LinuxSuRen** [comment]
In my view, this is not a bug. So I'm going to give a support flag. /kind support

**Comment by LinuxSuRen** [comment]
Hi @ssmmray, have you resolved this issues or not? Do you need some help here? I'm glad to help you out of it.

**Comment by wjl120** [comment]
hello, I have the same issue on AWS EKS .
I want to know how to manually change the kubeconfig on kubesphere?
which item need to be change on below?

- cluster:
    certificate-authority-data: 
    server: https://10.100.0.1:443
  name: local
contexts:
- context:
    cluster: local
    namespace: default
    user: admin
  name: admin@local
current-context: admin@local

**Comment by LinuxSuRen** [comment]
hi @wjl120 , please try to change the user part.
