### ISSUE TITLE
Installing kubesphere

### ISSUE THREAD

**Issue by Bruce-Stark** [kubesphere/kubesphere#3200]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**General remarks**

> Please delete this section including header before submitting
>
> This form is to report installation issues. For general usage questions you can refer to [KubeSphere Documentation](https://kubesphere.io/docs) or join our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE)

Can kubesphere be installed only on Ubuntu 16.04, 18.04 systems? Can't I install it on an Ubuntu 20 system

**Environment: OS & Hardware Information**

> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).

**Error logs or message (Attach logs or screenshot)**

**Installer Version**

> e.g. Ubuntu 20.04

**Comment by RolandMa1986** [comment]
Hi @Bruce-Stark,

**Comment by RolandMa1986** [comment]
Hi @Bruce-Stark, Surly you can install KubeSphere on Ubuntu 20. Please try [Kubekey](https://github.com/kubesphere/kubekey) to install Kubernetes and Kubesphere. I hope you can enjoy it.
/kind support
/area installation
