### ISSUE TITLE
DevOps 工程：流水线 报错

### ISSUE THREAD

**Issue by xuguangyao** [kubesphere/kubesphere#3205]
KubeSphere 版本 : v2.1.1
问题：
DevOps 工程：流水线，搜索关键字,报错 
![image](https://user-images.githubusercontent.com/32193099/102303123-7a550000-3f95-11eb-9fc1-1942209aaa3f.png)
![image](https://user-images.githubusercontent.com/32193099/102303127-7de88700-3f95-11eb-8433-e3124337013e.png)

**Comment by LinuxSuRen** [comment]
hi @xuguangyao Thanks for contact with us. Considering KubeSphere is a global community, not all users can understand Chinese. Communicating in English can benefit everyone. So it's appreciated if you could rewrite your issue in English.

Before we can keep this forward, providing more context is necessary. In my view, I cannot figure it out without the related logs. Please post the following log output:

* The HTTP response header and body when you search the Pipelines with a keyword
* Log output of component `kubesphere-system/ks-apiserver` in this case

I know not everyone has the same English written skills. But you can just try it. An easy way that you can do this is that post log output and screenshot as many as possible.

**Comment by FeynmanZhou** [comment]
Closed. Please reopen it if you think this is a blocking issue.
