### ISSUE TITLE
kubesphere-devops-system error No valid crumb was included in the request

### ISSUE THREAD

**Issue by eavae** [kubesphere/kubesphere#3209]
**Describe the Bug**

Jenkins input can not be triggered after upgrade Jenkins version.

**Versions Used**
KubeSphere: v3.0.0
Kubernetes: v1.17.9
Jenkins: jenkins/jenkins:2.254

**Environment**
Ubuntu / 3 masters:  8cpu/8g; 3 nodes: 8cpu/8g

**How To Reproduce**
1. Go to devops project and create a pipeline
2. Configure the pipeline use pipeline as code
3. Use Jenkins Input like `input "Retry?"`
4. Click continue button via kubesphere devops system
5. See the error message blow:

```
Request URL: http://****/kapis/devops.kubesphere.io/v1alpha2/devops/defaultrrzxq/pipelines/****/branches/master/runs/33/nodes/60/steps/61/
Request Method: POST
Status Code: 500 Internal Server Error
Referrer Policy: strict-origin-when-cross-origin

-----

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 403 No valid crumb was included in the request</title>
</head>
<body><h2>HTTP ERROR 403 No valid crumb was included in the request</h2>
<table>
<tr><th>URI:</th><td>/blue/rest/organizations/jenkins/pipelines/defaultrrzxq/pipelines/shuotu-fun-server/branches/master/runs/33/nodes/60/steps/61/</td></tr>
<tr><th>STATUS:</th><td>403</td></tr>
<tr><th>MESSAGE:</th><td>No valid crumb was included in the request</td></tr>
<tr><th>SERVLET:</th><td>Stapler</td></tr>
</table>
<hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.30.v20200611</a><hr/>

</body>
</html>
```

**Expected behavior**
Can trigger the pipeline continue to run.

**Comment by shaowenchen** [comment]
How do you upgrade Jenkins? currently, it's not supported to upgrade the Jenkins version yourself.

**Comment by eavae** [comment]
I changed yaml file, the image property.

**Comment by shaowenchen** [comment]
Please let it recover. We will upgrade it in 3.1.0.

In addition, what caused you to upgrade Jenkins Version?

**Comment by LinuxSuRen** [comment]
Hi @eavae , I believe that you can get more details about this from the Jenkins community [security report](https://www.jenkins.io/security/advisory/2019-07-17/) and [version upgrade guide](https://www.jenkins.io/doc/upgrade-guide/2.176/#SECURITY-626).

In my view, this is not a bug of KubeSphere. But we can definitely improve our document about how to upgrade Jenkins in KubeSphere. So I guess we can close this issue and create another one (for document improvement) if you agree with me.

**Comment by eavae** [comment]
Thanks, I totally agree with you. By the way, I'm struggling with different versions of Jenkins plugins, and try hard to make it works well with the kubernetes cd plugin. Since if there are huge of plugins when using Jenkins with K8s. If there are some documents or mechanism to avoid this, it would be great.

**Comment by LinuxSuRen** [comment]
hi @eavae , Actually, I'm not sure what you want to describe.

By the way, I have no power to close this issue. And in my view, discussion about the best practice of using Jenkins with k8s is another topic. I'd suggest we just close this issue, then start a new thread at [GitHub Discusssion](https://github.com/kubesphere/kubesphere/discussions) or [KubeSphere Chinese Forum](https://kubesphere.com.cn/forum/).
