### ISSUE TITLE
Failed to configure LDAP login, error message: socket hang up

### ISSUE THREAD

**Issue by weekyuan** [kubesphere/kubesphere#3226]
**Describe the Bug**

Failed to configure LDAP login, error message:
**Internal Server Error
request to http://ks-apiserver.kubesphere-system.svc/kapis/iam.kubesphere.io/v1alpha2/users failed, reason: socket hang up**

![image](https://user-images.githubusercontent.com/5857374/103068141-7eb59480-45f7-11eb-8584-5e17c5b52c42.png)

Follow the ks-apiserver log:
`E1224 15:08:40.839438       1 login_recoder.go:71] LoginRecord.iam.kubesphere.io "system:pre-registration-wk9z6" is invalid: [metadata.generateName: Invalid value: "system:pre-registration-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.name: Invalid value: "system:pre-registration-wk9z6": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: "system:pre-registration": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]
E1224 15:08:40.839484       1 handler.go:263] Failed to record successful login for user yuanyuan-g, error: LoginRecord.iam.kubesphere.io "system:pre-registration-wk9z6" is invalid: [metadata.generateName: Invalid value: "system:pre-registration-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.name: Invalid value: "system:pre-registration-wk9z6": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: "system:pre-registration": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]
2020/12/24 15:08:56 http: panic serving 192.168.17.76:40216: assignment to entry in nil map
goroutine 13964 [running]:
net/http.(*conn).serve.func1(0xc0020f95e0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1795 +0x139
panic(0x2d6b7e0, 0x38941e0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
kubesphere.io/kubesphere/pkg/apiserver/auditing.(*auditing).LogRequestObject(0xc0009fb7d0, 0xc000f78300, 0xc0003b0930, 0x2b15c20)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/auditing/types.go:187 +0x89a
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuditing.func1(0x393b1a0, 0xc000d23340, 0xc000f78300)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/auditing.go:51 +0x100
net/http.HandlerFunc.ServeHTTP(0xc0009fb800, 0x393b1a0, 0xc000d23340, 0xc000f78300)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthorization.func1(0x393b1a0, 0xc000d23340, 0xc000f78300)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/authorization.go:50 +0x37c
net/http.HandlerFunc.ServeHTTP(0xc0009f43c0, 0x393b1a0, 0xc000d23340, 0xc000f78300)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithMultipleClusterDispatcher.func1(0x393b1a0, 0xc000d23340, 0xc000f78300)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/dispatch.go:43 +0xd9
net/http.HandlerFunc.ServeHTTP(0xc000862120, 0x393b1a0, 0xc000d23340, 0xc000f78300)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthentication.func1(0x393b1a0, 0xc000d23340, 0xc000f78300)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/authentication.go:68 +0x5ce
net/http.HandlerFunc.ServeHTTP(0xc0009f4480, 0x393b1a0, 0xc000d23340, 0xc000f5a100)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithRequestInfo.func1(0x393b1a0, 0xc000d23340, 0xc0029b4d00)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/requestinfo.go:67 +0x3c5
net/http.HandlerFunc.ServeHTTP(0xc0008629f0, 0x393b1a0, 0xc000d23340, 0xc0029b4d00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
net/http.serverHandler.ServeHTTP(0xc0007f0460, 0x393b1a0, 0xc000d23340, 0xc0029b4d00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2831 +0xa4
net/http.(*conn).serve(0xc0020f95e0, 0x394da20, 0xc002b0c880)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1919 +0x875
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2957 +0x384
2020/12/24 15:08:56 http: panic serving 192.168.17.76:40224: assignment to entry in nil map
goroutine 13972 [running]:
net/http.(*conn).serve.func1(0xc0015af360)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1795 +0x139
panic(0x2d6b7e0, 0x38941e0)
	/opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2
kubesphere.io/kubesphere/pkg/apiserver/auditing.(*auditing).LogRequestObject(0xc0009fb7d0, 0xc000f5ae00, 0xc0003b09a0, 0x2b15c20)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/auditing/types.go:187 +0x89a
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuditing.func1(0x393b1a0, 0xc000d23500, 0xc000f5ae00)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/auditing.go:51 +0x100
net/http.HandlerFunc.ServeHTTP(0xc0009fb800, 0x393b1a0, 0xc000d23500, 0xc000f5ae00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthorization.func1(0x393b1a0, 0xc000d23500, 0xc000f5ae00)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/authorization.go:50 +0x37c
net/http.HandlerFunc.ServeHTTP(0xc0009f43c0, 0x393b1a0, 0xc000d23500, 0xc000f5ae00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithMultipleClusterDispatcher.func1(0x393b1a0, 0xc000d23500, 0xc000f5ae00)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/dispatch.go:43 +0xd9
net/http.HandlerFunc.ServeHTTP(0xc000862120, 0x393b1a0, 0xc000d23500, 0xc000f5ae00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuthentication.func1(0x393b1a0, 0xc000d23500, 0xc000f5ae00)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/authentication.go:68 +0x5ce
net/http.HandlerFunc.ServeHTTP(0xc0009f4480, 0x393b1a0, 0xc000d23500, 0xc000f5ad00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
kubesphere.io/kubesphere/pkg/apiserver/filters.WithRequestInfo.func1(0x393b1a0, 0xc000d23500, 0xc000f5ac00)
	/home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/requestinfo.go:67 +0x3c5
net/http.HandlerFunc.ServeHTTP(0xc0008629f0, 0x393b1a0, 0xc000d23500, 0xc000f5ac00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
net/http.serverHandler.ServeHTTP(0xc0007f0460, 0x393b1a0, 0xc000d23500, 0xc000f5ac00)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2831 +0xa4
net/http.(*conn).serve(0xc0015af360, 0x394da20, 0xc002b7f040)
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1919 +0x875
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2957 +0x384`

**Versions Used**
KubeSphere:  Install via **kubespheredev/ks-installer:latest** image
Kubernetes:  v1.18.6

**How To Reproduce**
1. Install kubepshere cluster via **kubespheredev/ks-installer:latest**
2. Edit configMap kubesphere-config：
![image](https://user-images.githubusercontent.com/5857374/103068676-99d4d400-45f8-11eb-95bd-090db3c4deb0.png)

3. Restart ks-apiserver: kubectl -n kubesphere-system rollout restart deploy ks-apiserver.
4. Visit http://***:30880/login, click on 'Login'
5. The page automatically jumps to：http://***:30880/login/confirm
![image](https://user-images.githubusercontent.com/5857374/103068942-3ac38f00-45f9-11eb-9e7f-d52c1e3219f4.png)
6. Change the username **system:pre-registration** to your own name，click on 'Login'
7. See error:
**Internal Server Error
request to http://ks-apiserver.kubesphere-system.svc/kapis/iam.kubesphere.io/v1alpha2/users failed, reason: socket hang up**

**Expected behavior**
Click on 'Login', login successfully.

**Comment by wansir** [comment]
/remove-area iam
/assign @wanjunlei 

The branch you are using is not stable, the auditing filter reported some errors.

The auditing filter should catch the exception do not crash the goroutine. 

```
15:08:56 http: panic serving 192.168.17.76:40224: assignment to entry in nil map goroutine 13972 [running]: net/http.(*conn).serve.func1(0xc0015af360) /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:1795 +0x139 panic(0x2d6b7e0, 0x38941e0) /opt/hostedtoolcache/go/1.13.15/x64/src/runtime/panic.go:679 +0x1b2 kubesphere.io/kubesphere/pkg/apiserver/auditing.(*auditing).LogRequestObject(0xc0009fb7d0, 0xc000f5ae00, 0xc0003b09a0, 0x2b15c20) /home/runner/work/kubesphere/kubesphere/pkg/apiserver/auditing/types.go:187 +0x89a kubesphere.io/kubesphere/pkg/apiserver/filters.WithAuditing.func1(0x393b1a0, 0xc000d23500, 0xc000f5ae00) /home/runner/work/kubesphere/kubesphere/pkg/apiserver/filters/auditing.go:51 +0x100 net/http.HandlerFunc.ServeHTTP(0xc0009fb800, 0x393b1a0, 0xc000d23500, 0xc000f5ae00) /opt/hostedtoolcache/go/1.13.15/x64/src/net/http/server.go:2036 +0x44
```
