### ISSUE TITLE
code compiled failed due to the container of maven is killed by unkown error

### ISSUE THREAD

**Issue by ethanxzw** [kubesphere/kubesphere#3227]
Hi guys, we face an issue when build pipeline task to complie maven project. could you please help to check it.

ENV version:
kubesphere version: v3.0.0
kubernetes version: v1.17.9

the maven container is killed with unkown error during compiling code. in jenkins logs, one file named "Purge expired KubernetesClients.log" is found. the data of file as below:
```
Started at Thu Dec 24 07:48:52 UTC 2020
Finished at Thu Dec 24 07:48:52 UTC 2020. 61ms
Started at Thu Dec 24 08:18:52 UTC 2020
Finished at Thu Dec 24 08:18:52 UTC 2020. 1ms
```
![image](https://user-images.githubusercontent.com/41108414/103079273-7ddc2d00-460e-11eb-8102-e3ed11d1764f.png)

**Comment by RolandMa1986** [comment]
Hi @ethanxzw, is there any pipeline log shows the detail of the failure reason? 
![pipeline_log](https://user-images.githubusercontent.com/1720333/103113459-cd197080-4695-11eb-897a-2659169c62ae.png)

/kind support
/area devops

**Comment by ethanxzw** [comment]
![image](https://user-images.githubusercontent.com/41108414/103114944-b118cd80-469b-11eb-98fc-784d37e46ba0.png)

pipeline logs as above. no obvious error details in it.

**Comment by RolandMa1986** [comment]
Seems like maven was oom killed. Do you know how much memory does it consume on a local machine? 
The kubesphere itself has a limit of 8GB for maven container. If your build consumes more than that, you have to adjust either maven setting or the container limit.

**Comment by ethanxzw** [comment]
it's done after increase memory resource. thanks.
