### ISSUE TITLE
Kubesphere stopps after restarting master node

### ISSUE THREAD

**Issue by yasir2000** [kubesphere/kubesphere#3230]
**Describe the Bug**
i suddenly lost ks web running after soft reboot of main master node, when I run:
kubectl edit cm -n kubesphere-system ks-installer

 I run logger now it gives failure of ansible playbook :
```
 (kubectl get pod -n kubesphere-system -l app=ks-install -o jsonpath='{.items[0].metadata.name}') -f > d-log
 Throttling request took 1.114905039s, request: GET:https://lb.kubesphere.local:6443/apis/rbac.istio.io/v1alpha1?timeout=32s
```

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)
3.0

**Environment**
How many nodes and their hardware configuration:
8 nodes, 2 master, 6 workers
For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)
CentOS 7.5

**How To Reproduce**

**Expected behavior**
Expect to get ks running smoothly after reboot

**Comment by FeynmanZhou** [comment]
Please do not paste the error logs in the screenshots, this is not friendly for debugging.

**Comment by yasir2000** [comment]
I removed log, only I put error

**Comment by pixiake** [comment]
Logs show request `apis/rbac.istio.io/v1alpha1` timeout.
1. Check k8s component status
```
kubectl get componentstatuses
```
2. Determine if istio is running properly. 
```
kubectl get pod -n istio-system
```
3. If istio is running properly, try to restart ks-installer
```
kubectl rollout restart deploy -n kubesphere-system ks-installer
```

**Comment by yasir2000** [comment]
Second step showed istio is having problems :

jaeger-es-index-cleaner-1609102500-h6sft   0/1     Error                        0          14h
jaeger-es-index-cleaner-1609102500-j5hck   0/1     Error                        0          14h
jaeger-es-index-cleaner-1609102500-lhrzk   0/1     Error                        0          15h
jaeger-es-index-cleaner-1609102500-lklkj   0/1     Error                        0          15h

And though still ks web UI is showing after login:

`Internal Server Error`

**Comment by yasir2000** [comment]
One of kubesphere-system : kubesphere-system/ks-controller-manager-698d6fbcd6-jtmzm:ks-controller-manager)

is giving :

│ E1226 00:01:36.798315       1 reflector.go:307] pkg/mod/k8s.io/client-go@v0.17.3/tools/cache/reflector.go:105: Failed to watch *v1al │
│ pha2.GlobalRole: Get https://10.233.0.1:443/apis/iam.kubesphere.io/v1alpha2/globalroles?allowWatchBookmarks=true&resourceVersion=322 │
│ 05280&timeout=8m5s&timeoutSeconds=485&watch=true: dial tcp 10.233.0.1:443: connect: connection refused

**Comment by pixiake** [comment]
```
dial tcp 10.233.0.1:443: connect: connection refused
```
Looks like a problem for k8s apiserver.
Please execute the following command to view the relevant information：
```
kubectl get node,svc,ep -o wide
```
```
kubectl get pod -n kube-system -o wide
```

**Comment by yasir2000** [comment]
Yes second command showed only one pod running of kube-apiserver while other are crashed , the log for first running is : 

```
Failed calling webhook, failing open sidecar-injector.dapr.io: failed calling webhook "sidecar-injector.dapr.io": Post https://dapr-sidecar-injector.dapr │
│ -ns.svc:443/mutate?timeout=10s: service "dapr-sidecar-injector" not found      
1228 14:11:22.120983       1 trace.go:116] Trace[1742544122]: "Call mutating webhook" configuration:istio-sidecar-injector,webhook:sidecar-injector.istio.io,resource:/v1, Resource=pods,subresource:,ope │
│ ration:CREATE,UID:8b23c61e-7187-4a8d-8066-e651568d7d4c (started: 2020-12-28 14:10:52.118419671 +0000 UTC m=+191079.862833822) (total time: 30.002427305s):                                                 │
│ Trace[1742544122]: [30.002427305s] [30.002427305s] END                                                                                                                                                     │
│ W1228 14:11:22.121173       1 dispatcher.go:181] Failed calling webhook, failing closed sidecar-injector.istio.io: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector │
│ .istio-system.svc:443/inject?timeout=30s: context deadline exceeded                                                                                                                                        │
```

**Comment by pixiake** [comment]
> Yes second command showed only one pod running of kube-apiserver while other are crashed , the log for first running is :
> 
> ```
> Failed calling webhook, failing open sidecar-injector.dapr.io: failed calling webhook "sidecar-injector.dapr.io": Post https://dapr-sidecar-injector.dapr │
> │ -ns.svc:443/mutate?timeout=10s: service "dapr-sidecar-injector" not found      
> 1228 14:11:22.120983       1 trace.go:116] Trace[1742544122]: "Call mutating webhook" configuration:istio-sidecar-injector,webhook:sidecar-injector.istio.io,resource:/v1, Resource=pods,subresource:,ope │
> │ ration:CREATE,UID:8b23c61e-7187-4a8d-8066-e651568d7d4c (started: 2020-12-28 14:10:52.118419671 +0000 UTC m=+191079.862833822) (total time: 30.002427305s):                                                 │
> │ Trace[1742544122]: [30.002427305s] [30.002427305s] END                                                                                                                                                     │
> │ W1228 14:11:22.121173       1 dispatcher.go:181] Failed calling webhook, failing closed sidecar-injector.istio.io: failed calling webhook "sidecar-injector.istio.io": Post https://istio-sidecar-injector │
> │ .istio-system.svc:443/inject?timeout=30s: context deadline exceeded                                                                                                                                        │
> ```



With this information it seems to be related to `istio-sidecar-injector`. 
@zackzhangkai Can it be solved by the following method ？
```
kubectl get mutatingwebhookconfigurations.admissionregistration.k8s.io istio-sidecar-injector -o yaml > injector.yaml
kubectl delete mutatingwebhookconfigurations.admissionregistration.k8s.io istio-sidecar-injector
```
After waiting for the cluster to return to normal，execute the following command
```
kubectl apply -f injector.yaml
```

**Comment by yasir2000** [comment]
Did all steps above and when I do :
`
kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l app=ks-install -o jsonpath='{.items[0].metadata.name}') -f`

I get :

`1 reflector.go:131] pkg/mod/k8s.io/client-go@v0.0.0-20190411052641-7a6b4715b709/tools/cache/reflector.go:99: Failed to list *unstructured.Unstructured: Get "https://10.233.0.1:443/apis/installer.kubesphere.io/v1alpha1/namespaces/kubesphere-system/clusterconfigurations?fieldSelector=metadata.name%3Dks-installer&limit=500&resourceVersion=0": dial tcp 10.233.0.1:443: connect: connection refused`

**Comment by zackzhangkai** [comment]
`dial tcp 10.233.0.1:443: connect: connection refused` means your kube-apiserver didn't work correctly. 
Check your k8s component firstly.

```bash
kubectl get pods -n kube-system
```

**Comment by yasir2000** [comment]
Only one pod is running out of 3 : 


```
kube-apiserver-st000kks01.tiga.local            1/1     Running            12         51d
kube-apiserver-st000kks02                       0/1     CrashLoopBackOff   14500      51d
kube-apiserver-st000kks03                       0/1     CrashLoopBackOff   14471      51d
```
log of running pod: 

│ I1229 06:29:00.631297       1 trace.go:116] Trace[1124139313]: "Update" url:/api/v1/namespaces/kubesphere-controls-system/configmaps/kubesphere-router-kubecost-nginx,user-agent:nginx │
│ -ingress-controller/v0.0.0 (linux/amd64) kubernetes/$Format,client:10.5.3.51 (started: 2020-12-29 06:29:00.070429308 +0000 UTC m=+938.474685537) (total time: 560.793024ms):           │
│ Trace[1124139313]: [557.201735ms] [557.201735ms] About to convert to expected version                                                                                                  ```
│
│ W1229 06:30:06.983297       1 dispatcher.go:169] Failed calling webhook, failing open sidecar-injector.dapr.io: failed calling webhook "sidecar-injector.dapr.io": Post https://dapr-s │
│ idecar-injector.dapr-ns.svc:443/mutate?timeout=10s: service "dapr-sidecar-injector" not found                                                                                          │
│ E1229 06:30:06.983361       1 dispatcher.go:170] failed calling webhook "sidecar-injector.dapr.io": Post https://dapr-sidecar-injector.dapr-ns.svc:443/mutate?timeout=10s: service "da │
│ pr-sidecar-injector" not found                                                                                                                                                         │
│                                          
```

**Comment by yasir2000** [comment]
After doing the same with dapr-sidecar-injector by deleting it, now am getting same connection refused bu log of running pod is:
```
│ Trace[590501274]: [19.069931536s] [19.066947733s] Transformed response object                                                                                     │
│ I1229 07:04:36.212814       1 trace.go:116] Trace[1995726404]: "Get" url:/api/v1/namespaces/kubesphere-system/pods/ks-installer-6fb7fb8d88-bwlk4/log,user-agent:k │
│ ubectl/v1.18.6 (linux/amd64) kubernetes/dff82dc,client:10.5.3.47 (started: 2020-12-29 07:04:31.625993616 +0000 UTC m=+3070.030249751) (total time: 4.586723334s): │
│ Trace[1995726404]: [4.586716764s] [4.580080069s] Transformed response object   
```

**Comment by yasir2000** [comment]
KS is still not popping up !!!, while K8 is running without an issue
