### ISSUE TITLE
All the apps in the App Store are disappeared. 

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#3231]
**Describe the Bug**

All the apps in the App Store are disappeared. 

![image](https://user-images.githubusercontent.com/40452856/103206881-e6414c00-4937-11eb-9d54-c492ff6f178f.png)

![image](https://user-images.githubusercontent.com/40452856/103206871-dde91100-4937-11eb-86f2-0e65b37a8872.png)

**Versions Used**

KubeSphere: v3.0.0

**Environment**
How many nodes and their hardware configuration:

Host Cluster: Ubuntu 16.04, 1 master 2 nodes

**How To Reproduce**

Log in to https://demo.kubesphere.io/apps with the admin account, you will find the node1's status shows `Warning` from the Host cluster, and the App Store is empty.

**Comment by focusme** [comment]
我在kubesphere集群里安装了kubesphere自带的harbor,改了其中的harbor的yaml里的参数值，将ssl改为false，nodeport等，点击下一步，则all the apps in the app store are disappeared.

**Comment by zheng1** [comment]
> 我在kubesphere集群里安装了kubesphere自带的harbor,改了其中的harbor的yaml里的参数值，将ssl改为false，nodeport等，点击下一步，则all the apps in the app store are disappeared.

@focusme Can you send the login for the environment to kubesphere@yunify.com?

**Comment by zheng1** [comment]
I fixed https://demo.kubesphere.io/apps. The error is due to insufficient node resources causing mysql, etcd, on which the appstore depends, not to run correctly.
The way to fix it is to bring the abnormal node back to normal
@FeynmanZhou

**Comment by FeynmanZhou** [comment]
> I fixed https://demo.kubesphere.io/apps. The error is due to insufficient node resources causing mysql, etcd, on which the appstore depends, not to run correctly.
> The way to fix it is to bring the abnormal node back to normal
> @FeynmanZhou

Okay. thanks.
