### ISSUE TITLE
The tower server shouldn't update the cluster.status

### ISSUE THREAD

**Issue by yuswift** [kubesphere/kubesphere#3234]
**What's it about?**
Currently, when cluster.spec.connection.type is proxy, the tower server updates the cluster.status filed, and the cluster controller determines if the cluster is ready according to the status.

**What's the reason why we need it?**
Actually, the tower server shouldn't update the cluster.status filed.
The cluster controller can try to connect to the proxy service, determines if the cluster is ready by the response HTTP code.
This proposal can reduce the complexity between tower server and clsuter-controller.
/area multicluster
/kind feature-request

**Comment by lxm** [comment]
```
kubernetesAPIEndpoint
kubernetesAPIServerPort
kubesphereAPIEndpoint
kubesphereAPIServerPort
```

It may be a good choice to manage the above fields in tower

**Comment by lxm** [comment]
On the other hand, the creation of the service `mc-xxxx` is best placed in the tower

**Comment by yuswift** [comment]
> ```
> kubernetesAPIEndpoint
> kubernetesAPIServerPort
> kubesphereAPIEndpoint
> kubesphereAPIServerPort
> ```
> 
> It may be a good choice to manage the above fields in tower

LGTM. @zryfish

**Comment by zryfish** [comment]
yeah, agreed

**Comment by zryfish** [comment]
@yuswift Any update on this issue?
