### ISSUE TITLE
Upgrade istio to 1.6.10

### ISSUE THREAD

**Issue by zryfish** [kubesphere/kubesphere#3236]
**What's it about?**
There are major changes after istio 1.5, KubeSphere v3.0.0 is still using istio 1.4.8 due to legacy problems.  We should keep up with istio community and upgrade soon.

**What's the reason why we need it?**
Older istio versions are not supported by the community anymore.

**Area Suggestion**
/area upgrade
/assign @zackzhangkai

**Comment by zackzhangkai** [comment]
@zryfish We had supported Istio 1.6.10 indeed now in the master branch. Do you mean we should support istio 1.6.10 in KubeSphere 3.0.0 , not from KubeSphere 3.1.0 ?

**Comment by zackzhangkai** [comment]
https://github.com/kubesphere/ks-installer/pull/1125

**Comment by Remember2015** [comment]
why not upgrade to newer version after 1.8 (Mixer is removed in 1.8)

**Comment by zackzhangkai** [comment]
@Remember2015 Agree with you. The time we want to upgrade istio, the version is  still 1.7.0. So we choose the 1.6.10 as our version.  But now , the version maybe too old. On the other hand, we are planning to release our version. Maybe there is no time to change our version. Please to confirm this. I tend to upgrade to istio 1.8. A week is enough for us. @zryfish

**Comment by zackzhangkai** [comment]
@Remember2015 https://github.com/istio/istio/issues/19885.  Because istio1.8 use xds 3.0 and no longer support 2.0.  So we should have a full test on this scene. So this time, we still upgrade to 1.6.10.
