### ISSUE TITLE
Have some problem with the log collecting system

### ISSUE THREAD

**Issue by WorldWay** [kubesphere/kubesphere#3244]
I can not provide more useful information ,because of the log collecting system can not collect my app's logs well.
I build an docker image and publish it on kubesphere 3.0 then name it as emqx-prod
I can find the logs in web docker logs,like this:
![image](https://user-images.githubusercontent.com/24239063/103497530-c3a1bc80-4e7c-11eb-8dab-6fc8111463ac.png)

but i can not find these in log search:
![image](https://user-images.githubusercontent.com/24239063/103497540-c8ff0700-4e7c-11eb-814d-3b918a791a1b.png)

then I publish a new project on kubesphere 3.0 with the same image named as emqx-test
now I can find these in both web docker logs and log search,like this:
![image](https://user-images.githubusercontent.com/24239063/103497721-53476b00-4e7d-11eb-9477-e5d94725fffc.png)

this problem has not been resolved until today and logs of the project named emqx-test can not be collected now:
![image](https://user-images.githubusercontent.com/24239063/103497894-e680a080-4e7d-11eb-826b-096509a115f9.png)

what can i do to resolve this problem next step?

**Comment by wanjunlei** [comment]
It searched no logs of your app when your app is deployed in project `emqx-prod`, and it searched logs correctly when your app is deployed in project `emqx-test`. Is this is your problem?

What is the user you use to query the log, and does this user have permission to access project `emqx-prod`?

**Comment by WorldWay** [comment]
I create the two project with the same user and image.every thing looks like the same except the name.
And now the project emqx-test can not collect logs correctly either

**Comment by wanjunlei** [comment]
There are any errors in the fluent bit log? It is in the kubesphere-logging-system project.

**Comment by WorldWay** [comment]
error like this:
![image](https://user-images.githubusercontent.com/24239063/103747160-35286900-503d-11eb-8beb-81d76267dfb6.png)

**Comment by wanjunlei** [comment]
This is log of fluentbit operator. You need to see the log of fluent-bit
![image](https://user-images.githubusercontent.com/53003665/103749228-35763380-5040-11eb-8524-f06ebd4e1188.png)

**Comment by WorldWay** [comment]
there has no error logs:
![image](https://user-images.githubusercontent.com/24239063/103749578-a4ec2300-5040-11eb-979a-da2b4cf4a75d.png)

**Comment by wanjunlei** [comment]
Can you view the log with kubectl logs or pod log, and past them, it is useful for locate the problem.

**Comment by WorldWay** [comment]
do you mean the logs in this path of the machine?
![image](https://user-images.githubusercontent.com/24239063/103750924-73745700-5042-11eb-9738-425522fc93a5.png)

**Comment by WorldWay** [comment]
[0.log](https://github.com/kubesphere/kubesphere/files/5774855/0.log)

**Comment by wanjunlei** [comment]
Yes, this is fine too.

**Comment by wanjunlei** [comment]
The fluent bit does not collect logs from 2021/01/06 01:50:51, please past the data of secret fluent-bit-config in project kubesphere-logging-system.

**Comment by WorldWay** [comment]
It does not collect logs since 2020/12/31.
[fluent-bit.conf.txt](https://github.com/kubesphere/kubesphere/files/5774958/fluent-bit.conf.txt)
