### ISSUE TITLE
Can not login with admin on kubesphere 3.0

### ISSUE THREAD

**Issue by WorldWay** [kubesphere/kubesphere#3245]
before the holiday, I can login with admin successfully. but I can not login after the holiday.
during the holiday,no one use the kubesphere 3.0 or change the password

how does it happen with no useful logs ?

now I use kubectl edit user admin to reset the password.but this problem is still exists and i can not know how does it happen.

**Comment by LinuxSuRen** [comment]
I was wondering if you could provide the process about how to reset the password? In case of that, you might do not reset it appropriately. Please checkout out https://github.com/kubesphere/kubesphere/issues/3105#issuecomment-725784472

**Comment by WorldWay** [comment]
I reset it this way:
![image](https://user-images.githubusercontent.com/24239063/103500835-40399880-4e87-11eb-8bf7-bc5344c9bb23.png)
![image](https://user-images.githubusercontent.com/24239063/103500850-50517800-4e87-11eb-951f-c01bb18bcb1b.png)

and now i can login, but i still don't now how does it happen that the password is invalid.

**Comment by LinuxSuRen** [comment]
I guess this caused by the unstabled LDAP. The community is going to integrate OIDC. I should be better. If you're interested in it, please follow up https://github.com/kubesphere/kubesphere/pull/3189

**Comment by wansir** [comment]
@WorldWay It may be due to the encrypted transmission feature of password, which relies on Redis(`ks-console` share session via Redis). You can check whether the Redis service is abnormal if you cannot log in. Please pay attention to the error message. Related: https://kubesphere.io/docs/faq/access-control/session-timeout.

/assign @wansir @leoendless

**Comment by WorldWay** [comment]
ok，now i will check the expired time of the key in redis and to see whether it caused this problem or not

**Comment by csuffyy** [comment]
@WorldWay Hi WorldWay, I got the same problem today, have you solved the problem yet?

**Comment by WorldWay** [comment]
@csuffyy 
just can login but not resolve finally.
you can just use kubectl edit user <your username> to change password.

now I guess the token was expired and can not authenticate with database again.
if you have other viewpoint,we can discuss more.

**Comment by wansir** [comment]
@csuffyy The error prompt will be different in different situations. Please check the pod status of Redis, check the log of ks-apiserver and ks-console. You can check whether the password is correct by the following command:

```
curl -X POST 'http://ks-apiserver.kubesphere-system.svc/oauth/token' -H 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'grant_type=password' --data-urlencode 'username=<USERNAME>' --data-urlencode 'password=<YOURPASSWORD>'
```

**Comment by csuffyy** [comment]
@WorldWay @wansir Thank you very much! I checked the logs of Redis, found the error message is
"1:M 05 Jan 2021 01:22:43.148 # Background saving error
1:M 05 Jan 2021 01:22:49.066 * 1 changes in 3600 seconds. Saving...
1:M 05 Jan 2021 01:22:49.068 * Background saving started by pid 9713
9713:C 05 Jan 2021 01:22:49.069 # Write error saving DB on disk: No space left on device"

then I clear some files, now I can login in KubeSphere.

**Comment by tagGeeY** [comment]
> @csuffyy The error prompt will be different in different situations. Please check the pod status of Redis, check the log of ks-apiserver and ks-console. You can check whether the password is correct by the following command:
> 
> ```
> curl -X POST 'http://ks-apiserver.kubesphere-system.svc/oauth/token' -H 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'grant_type=password' --data-urlencode 'username=<USERNAME>' --data-urlencode 'password=<YOURPASSWORD>'
> ```

@wansir , Hi, I got the same problem, I follow up [#3015 #commont](https://github.com/kubesphere/kubesphere/issues/3105#issuecomment-725784472) , then I exec this curl command and it execute ok:
`$curl -X POST 'http://ks-apiserver.kubesphere-system.svc/oauth/token' -H 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'grant_type=password' --data-urlencode 'username=admin' --data-urlencode 'password=admin'

{
 "access_token": "...",
 "token_type": "Bearer",
 "refresh_token": "...",
 "expires_in": 7200
}`

But when I login kubesphere console with admin/admin, it still prompt wrong user or password.

**Comment by tagGeeY** [comment]
Finally, I restarted ks-controller-manager, ks-console, then successfully login.
and the log of ks-controller-manager shows: `Successfully synced key:admin`.
