### ISSUE TITLE
Why we use a such older version of Jenkins?  no even not support JCasS 

### ISSUE THREAD

**Issue by gotoworld** [kubesphere/kubesphere#3248]
As title, Just because of curiosity

**Comment by LinuxSuRen** [comment]
Duplicated topic. See also #3235 
The community already have [a higher version of Jenkins](https://github.com/kubesphere/ks-jenkins). Cut it to short, you can have an external Jenkins instead of waiting the next release. I would suggest close this issue. Then track it via #3064
/support

**Comment by gotoworld** [comment]
Got it now, thanks
