### ISSUE TITLE
There was a problem installing kubesphere 3.0

### ISSUE THREAD

**Issue by Bruce-Stark** [kubesphere/kubesphere#3252]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**General remarks**

> Please delete this section including header before submitting
>
> This form is to report installation issues. For general usage questions you can refer to [KubeSphere Documentation](https://kubesphere.io/docs) or join our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE)

**What's your question**
There was a problem installing kubesphere 3.0

**Environment: OS & Hardware Information**

> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).

**Error logs or message (Attach logs or screenshot)**
 failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory
FAIL    kubesphere.io/kubesphere/pkg/apis/auditing/v1alpha1     0.012s

**Installer Version**

> e.g. v2.1.0, v2.1.1, v3.0.0

**Comment by RolandMa1986** [comment]
Hi @Bruce-Stark, I don't quite understand what's your issue. Would you please describe the issue more clearly? If you are trying to build KubeSphere. Please following our [guidance](https://github.com/kubesphere/community/blob/master/developer-guide/development/quickstart.md).
