### ISSUE TITLE
Some questions about modifying console (frontend) by myself.

### ISSUE THREAD

**Issue by Bruce-Stark** [kubesphere/kubesphere#3260]
I'm writing this issue to ask about how to modify the frontend when running nodes. I was using the instruction "./kk create cluster --with-kubernetes v1.17.9 --with-kubesphere v3.0.0" to create the cluster. I wonder if I can modify the IP:30880 frontend by myself. Can you give me some related instructions?

**Comment by LinuxSuRen** [comment]
I'm not sure what you want to know. But [console](https://github.com/kubesphere/console) is the front-end project if you are looking for it. 

/kind support

**Comment by Bruce-Stark** [comment]
> I'm not sure what you want to know. But [console](https://github.com/kubesphere/console) is the front-end project if you are looking for it.
> 
> /kind support

Thank you so much sir, I know what to do now
