### ISSUE TITLE
Ldap config Covered

### ISSUE THREAD

**Issue by hulengjing** [kubesphere/kubesphere#3264]
**Describe the Bug**
After LDAP is modified to external configuration, if you modify the configuration of ks_install and restart, the ldap configuration will be cleared and the local ldap will continue to be used

**Versions Used**
KubeSphere: v3.0.0
Kubernetes: v1.16.13   ks_install

**Environment**
Ubuntu 18.04.3 LTS / 3 master/node:  16cpu/64g;

**How To Reproduce**
1. Restart ks_apiserver to take effect after modifying the ldap configuration
2. Take effect after modifying ks_install configuration
```
kubectl -n kubesphere-system edit clusterconfiguration ks-installer
```
3. After waiting for the configuration to take effect, it is found that ldap cannot be logged in and can only be logged in through admin

**Comment by wansir** [comment]
related: https://github.com/kubesphere/ks-installer/issues/1113

/kind bug
