### ISSUE TITLE
Kubesphere source code compilation

### ISSUE THREAD

**Issue by wizard2318-dunk** [kubesphere/kubesphere#3265]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**General remarks**

> Please delete this section including header before submitting
>
> This form is to report installation issues. For general usage questions you can refer to [KubeSphere Documentation](https://kubesphere.io/docs) or join our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE)

**What's your question**
When installing and deploying kubesphere, you will always be prompted:

fork/exec /usr/local/kubebuilder/bin/etcd: permission denied

**Environment: OS & Hardware Information**
unbuntu 20.04 System
> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).

**Error logs or message (Attach logs or screenshot)**
failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: permission denied

**Installer Version**

> e.g. v2.1.0, v2.1.1, v3.0.0

**Comment by RolandMa1986** [comment]
Hi @wizard2318-dunk, I'm going to close the issue since it's not a kubesphere issue.
/close
