### ISSUE TITLE
Unable to find property 'startupProbe' on class ,jenkins plugin don't support startupProbe

### ISSUE THREAD

**Issue by wujunwei** [kubesphere/kubesphere#3269]
**Describe the Bug**
When I use jenkins pipeline to deploy my app ,the error appeared  `Unable to find property 'startupProbe' on class: io.kubernetes.client.openapi.models.V1Container` and I found someone [who](https://github.com/jenkinsci/kubernetes-cd-plugin/issues/140) faced the same error as I faced.

The  jenkins kubernetes-cd-plugin doesn't support this feature, it 's too old to use. do you have any plan to solve this problem?

**Versions Used**
KubeSphere:3.0
Kubernetes: v1.18.6

**Environment**
How many nodes and their hardware configuration: 4

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
just deploy your application with the attribute --startupProbe

**Expected behavior**

**Comment by RolandMa1986** [comment]
Hi @wujunwei , Thanks for engaging in the KubesSphere community. We will watch this issue closely and update the plugin once the upstream is updated.
/area devops
/kind support
/cc @LinuxSuRen

**Comment by LinuxSuRen** [comment]
Of course, we will keep an on eye this. But it looks like that resolving this problem mainly relies on the Jenkins community.

**Comment by wujunwei** [comment]
> i

Changing another jenkins plugin may be a good way。 Have any Plan B ?
