### ISSUE TITLE
The secret key of habor has been added. Select image prompt x509 when adding container

### ISSUE THREAD

**Issue by yyt6200** [kubesphere/kubesphere#3272]
The private warehouse has created a self signed certificate, and the node has verified that it can log in directly. Kubesphere has successfully set the secret key of the warehouse, but when creating the task selection container, the return value of the interface for selecting the input content of the private warehouse is still **x509: Certificate signed by unknown authority.**

**Comment by wansir** [comment]
@yyt6200 Actually x509 error is on docker side. The daemon failed to pull image from that insecure registry. You can trust/skip the registry security，see also https://docs.docker.com/registry/insecure.

**Comment by yyt6200** [comment]
@wansir Thank you for your reply. I have made a self signed certificate, and the node docker can log in to harbor without configuring the insure registry. In this case, do you still have to configure the insure registry?

**Comment by wansir** [comment]
You should install and trust your self-signed certificate in all nodes.

**Comment by yyt6200** [comment]
@wansir For all nodes of k8s, I have copied the self signed certificate to /etc/docker/certs.d/harbor.od.com/ Folder, I would like to ask, this is to do a trust certificate operation? The docker of each node can log in to the harbor without configuring the insurance registry.

**Comment by wansir** [comment]
So strange, please follow this document https://docs.docker.com/registry/insecure/#use-self-signed-certificates, make sure that you can pull images from the private registry in all of the nodes.

**Comment by yyt6200** [comment]
Yes, I have tried to pull the mirror image on all nodes, and there is no problem. If you disable the HTTPS of harbor and change to HTTP, kubesphere can retrieve the image from the private warehouse.
