### ISSUE TITLE
node-exporter CrashLoopBackOff

### ISSUE THREAD

**Issue by baojunz** [kubesphere/kubesphere#3277]
本地使用 docker for mac v1.18.8 版本，安装的 k8s后。
使用最小化安装方式开始安装 kubesphere，目前发现 node-exporter 不停重启 显示 CrashLoopBackOff

使用  kubectl describe 命令进行查看，发现错误提示为：

Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  8m23s                   default-scheduler  Successfully assigned kubesphere-monitoring-system/node-exporter-hgsmq to docker-desktop
  Normal   Pulled     8m23s                   kubelet            Container image "kubesphere/kube-rbac-proxy:v0.4.1" already present on machine
  Normal   Created    8m23s                   kubelet            Created container kube-rbac-proxy
  Normal   Started    8m22s                   kubelet            Started container kube-rbac-proxy
  Normal   Pulled     6m54s (x5 over 8m23s)   kubelet            Container image "kubesphere/node-exporter:ks-v0.18.1" already present on machine
  Normal   Created    6m54s (x5 over 8m23s)   kubelet            Created container node-exporter
  Warning  Failed     6m54s (x5 over 8m23s)   kubelet            Error: failed to start container "node-exporter": Error response from daemon: path /sys is mounted on /sys but it is not a shared or slave mount
  Warning  BackOff    3m13s (x23 over 8m21s)  kubelet            Back-off restarting failed container

![37321610789554_ pic_hd](https://user-images.githubusercontent.com/48702961/104808392-db842380-5820-11eb-98cd-dd425b8db2d2.jpg)

**Comment by RolandMa1986** [comment]
Hi @baojunz, 
Node-Exporter is not designed to run on Mac. So you may disable the monitoring component. 
/area monitoring
/kind support

**Comment by baojunz** [comment]
您好，我是使用  https://kubesphere.io/docs/quick-start/minimal-kubesphere-on-k8s/ 这个地址下的文档进行的安装使用，请问我该如何禁用Node-Exporter 该组件呢。

**Comment by RolandMa1986** [comment]
@baojunz, 
1. Please follow our guidance. 
**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**
2. You can download the config file first and change components as needed before you apply it. 
`wget https://github.com/kubesphere/ks-installer/releases/download/v3.0.0/cluster-configuration.yaml`
Disable **monitoring** component by :
```yaml
  monitoring:
    enabled: false
```
/close

**Comment by baojunz** [comment]
According to your tips, I am interested in cluster- configuration.yaml In the file

monitoring:
    enable: false

The adjustment has been made, but the error reported is as follows. In addition, the error reported during login is: internal error occurred: account is not active

Task 'monitoring' failed:
******************************************************************************************************************************************************
{
  "counter": 75,
  "created": "2021-01-19T02:04:00.880054",
  "end_line": 78,
  "event": "runner_on_failed",
  "event_data": {
    "duration": 2.984759,
    "end": "2021-01-19T02:04:00.879946",
    "event_loop": "items",
    "host": "localhost",
    "ignore_errors": null,
    "play": "localhost",
    "play_pattern": "localhost",
    "play_uuid": "e2ef30c7-5c87-5bd0-0226-000000000005",
    "playbook": "/kubesphere/playbooks/monitoring.yaml",
    "playbook_uuid": "80f919b3-c66d-469d-9dff-e0eeba4a7cab",
    "remote_addr": "127.0.0.1",
    "res": {
      "changed": true,
      "msg": "All items completed",
      "results": [
        {
          "_ansible_item_label": {
            "file": "prometheus-operator-deployment.yaml",
            "path": "prometheus/init"
          },
          "_ansible_no_log": false,
          "ansible_loop_var": "item",
          "changed": true,
          "checksum": "ada1b4f961b0f9a3ca501369fd91dafeea451476",
          "dest": "/kubesphere/kubesphere/prometheus/init/prometheus-operator-deployment.yaml",
          "diff": [],
          "failed": false,
          "gid": 1002,
          "group": "kubesphere",
          "invocation": {
            "module_args": {
              "_original_basename": "prometheus-operator-deployment.yaml.j2",
              "attributes": null,
              "backup": false,
              "checksum": "ada1b4f961b0f9a3ca501369fd91dafeea451476",
              "content": null,
              "delimiter": null,
              "dest": "/kubesphere/kubesphere/prometheus/init/prometheus-operator-deployment.yaml",
              "directory_mode": null,
              "follow": false,
              "force": true,
              "group": null,
              "local_follow": null,
              "mode": null,
              "owner": null,
              "regexp": null,
              "remote_src": null,
              "selevel": null,
              "serole": null,
              "setype": null,
              "seuser": null,
              "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021837.9242253-4651-128560186167502/source",
              "unsafe_writes": null,
              "validate": null
            }
          },
          "item": {
            "file": "prometheus-operator-deployment.yaml",
            "path": "prometheus/init"
          },
          "md5sum": "0524e4801f473fe646e25568be7b45b8",
          "mode": "0644",
          "owner": "kubesphere",
          "size": 2131,
          "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021837.9242253-4651-128560186167502/source",
          "state": "file",
          "uid": 1002
        },
        {
          "_ansible_item_label": {
            "file": "prometheus-prometheus.yaml",
            "path": "prometheus/prometheus"
          },
          "_ansible_no_log": false,
          "ansible_loop_var": "item",
          "changed": false,
          "failed": true,
          "item": {
            "file": "prometheus-prometheus.yaml",
            "path": "prometheus/prometheus"
          },
          "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'prometheusVolumeSize'"
        },
        {
          "_ansible_item_label": {
            "file": "kube-state-metrics-deployment.yaml",
            "path": "prometheus/kube-state-metrics"
          },
          "_ansible_no_log": false,
          "ansible_loop_var": "item",
          "changed": true,
          "checksum": "dc147b18eedef8416cdeb69a2d1425bc333c727b",
          "dest": "/kubesphere/kubesphere/prometheus/kube-state-metrics/kube-state-metrics-deployment.yaml",
          "diff": [],
          "failed": false,
          "gid": 1002,
          "group": "kubesphere",
          "invocation": {
            "module_args": {
              "_original_basename": "kube-state-metrics-deployment.yaml.j2",
              "attributes": null,
              "backup": false,
              "checksum": "dc147b18eedef8416cdeb69a2d1425bc333c727b",
              "content": null,
              "delimiter": null,
              "dest": "/kubesphere/kubesphere/prometheus/kube-state-metrics/kube-state-metrics-deployment.yaml",
              "directory_mode": null,
              "follow": false,
              "force": true,
              "group": null,
              "local_follow": null,
              "mode": null,
              "owner": null,
              "regexp": null,
              "remote_src": null,
              "selevel": null,
              "serole": null,
              "setype": null,
              "seuser": null,
              "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021838.2956707-4651-35751775677512/source",
              "unsafe_writes": null,
              "validate": null
            }
          },
          "item": {
            "file": "kube-state-metrics-deployment.yaml",
            "path": "prometheus/kube-state-metrics"
          },
          "md5sum": "992828354950e78aed9bcca802cd3f00",
          "mode": "0644",
          "owner": "kubesphere",
          "size": 3087,
          "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021838.2956707-4651-35751775677512/source",
          "state": "file",
          "uid": 1002
        },
        {
          "_ansible_item_label": {
            "file": "node-exporter-daemonset.yaml",
            "path": "prometheus/node-exporter"
          },
          "_ansible_no_log": false,
          "ansible_loop_var": "item",
          "changed": true,
          "checksum": "c13991f80b760a4bcacd6d708ad988e11595c84f",
          "dest": "/kubesphere/kubesphere/prometheus/node-exporter/node-exporter-daemonset.yaml",
          "diff": [],
          "failed": false,
          "gid": 1002,
          "group": "kubesphere",
          "invocation": {
            "module_args": {
              "_original_basename": "node-exporter-daemonset.yaml.j2",
              "attributes": null,
              "backup": false,
              "checksum": "c13991f80b760a4bcacd6d708ad988e11595c84f",
              "content": null,
              "delimiter": null,
              "dest": "/kubesphere/kubesphere/prometheus/node-exporter/node-exporter-daemonset.yaml",
              "directory_mode": null,
              "follow": false,
              "force": true,
              "group": null,
              "local_follow": null,
              "mode": null,
              "owner": null,
              "regexp": null,
              "remote_src": null,
              "selevel": null,
              "serole": null,
              "setype": null,
              "seuser": null,
              "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021838.6247935-4651-81412181394115/source",
              "unsafe_writes": null,
              "validate": null
            }
          },
          "item": {
            "file": "node-exporter-daemonset.yaml",
            "path": "prometheus/node-exporter"
          },
          "md5sum": "935593cdf554aec8da0598f5c1086884",
          "mode": "0644",
          "owner": "kubesphere",
          "size": 2714,
          "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021838.6247935-4651-81412181394115/source",
          "state": "file",
          "uid": 1002
        },
        {
          "_ansible_item_label": {
            "file": "alertmanager-alertmanager.yaml",
            "path": "prometheus/alertmanager"
          },
          "_ansible_no_log": false,
          "ansible_loop_var": "item",
          "changed": true,
          "checksum": "0686dc3c7d7c727a5deb03c47d605d407c337c34",
          "dest": "/kubesphere/kubesphere/prometheus/alertmanager/alertmanager-alertmanager.yaml",
          "diff": [],
          "failed": false,
          "gid": 1002,
          "group": "kubesphere",
          "invocation": {
            "module_args": {
              "_original_basename": "alertmanager-alertmanager.yaml.j2",
              "attributes": null,
              "backup": false,
              "checksum": "0686dc3c7d7c727a5deb03c47d605d407c337c34",
              "content": null,
              "delimiter": null,
              "dest": "/kubesphere/kubesphere/prometheus/alertmanager/alertmanager-alertmanager.yaml",
              "directory_mode": null,
              "follow": false,
              "force": true,
              "group": null,
              "local_follow": null,
              "mode": null,
              "owner": null,
              "regexp": null,
              "remote_src": null,
              "selevel": null,
              "serole": null,
              "setype": null,
              "seuser": null,
              "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021838.951369-4651-44348857853002/source",
              "unsafe_writes": null,
              "validate": null
            }
          },
          "item": {
            "file": "alertmanager-alertmanager.yaml",
            "path": "prometheus/alertmanager"
          },
          "md5sum": "deb96b174b2b1e404be1bc5a52dd916e",
          "mode": "0644",
          "owner": "kubesphere",
          "size": 901,
          "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021838.951369-4651-44348857853002/source",
          "state": "file",
          "uid": 1002
        },
        {
          "_ansible_item_label": {
            "file": "prometheus-adapter-deployment.yaml",
            "path": "prometheus/prometheus-adapter"
          },
          "_ansible_no_log": false,
          "ansible_loop_var": "item",
          "changed": true,
          "checksum": "64b5e09c5618614bc71b85940e90a239f763cbb4",
          "dest": "/kubesphere/kubesphere/prometheus/prometheus-adapter/prometheus-adapter-deployment.yaml",
          "diff": [],
          "failed": false,
          "gid": 1002,
          "group": "kubesphere",
          "invocation": {
            "module_args": {
              "_original_basename": "prometheus-adapter-deployment.yaml.j2",
              "attributes": null,
              "backup": false,
              "checksum": "64b5e09c5618614bc71b85940e90a239f763cbb4",
              "content": null,
              "delimiter": null,
              "dest": "/kubesphere/kubesphere/prometheus/prometheus-adapter/prometheus-adapter-deployment.yaml",
              "directory_mode": null,
              "follow": false,
              "force": true,
              "group": null,
              "local_follow": null,
              "mode": null,
              "owner": null,
              "regexp": null,
              "remote_src": null,
              "selevel": null,
              "serole": null,
              "setype": null,
              "seuser": null,
              "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021839.2658885-4651-194295915963597/source",
              "unsafe_writes": null,
              "validate": null
            }
          },
          "item": {
            "file": "prometheus-adapter-deployment.yaml",
            "path": "prometheus/prometheus-adapter"
          },
          "md5sum": "ce13fa3af41bf2630f8aa1853d955c4e",
          "mode": "0644",
          "owner": "kubesphere",
          "size": 1512,
          "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021839.2658885-4651-194295915963597/source",
          "state": "file",
          "uid": 1002
        },
        {
          "_ansible_item_label": {
            "file": "grafana-deployment.yaml",
            "path": "prometheus/grafana"
          },
          "_ansible_no_log": false,
          "ansible_loop_var": "item",
          "changed": true,
          "checksum": "c097a9fd8b57c3f2eec185a664ed73f0148f6816",
          "dest": "/kubesphere/kubesphere/prometheus/grafana/grafana-deployment.yaml",
          "diff": [],
          "failed": false,
          "gid": 1002,
          "group": "kubesphere",
          "invocation": {
            "module_args": {
              "_original_basename": "grafana-deployment.yaml.j2",
              "attributes": null,
              "backup": false,
              "checksum": "c097a9fd8b57c3f2eec185a664ed73f0148f6816",
              "content": null,
              "delimiter": null,
              "dest": "/kubesphere/kubesphere/prometheus/grafana/grafana-deployment.yaml",
              "directory_mode": null,
              "follow": false,
              "force": true,
              "group": null,
              "local_follow": null,
              "mode": null,
              "owner": null,
              "regexp": null,
              "remote_src": null,
              "selevel": null,
              "serole": null,
              "setype": null,
              "seuser": null,
              "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021839.5913498-4651-213645902557879/source",
              "unsafe_writes": null,
              "validate": null
            }
          },
          "item": {
            "file": "grafana-deployment.yaml",
            "path": "prometheus/grafana"
          },
          "md5sum": "2b3e6fbb79d85c74aa3b1508f5aade53",
          "mode": "0644",
          "owner": "kubesphere",
          "size": 7234,
          "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021839.5913498-4651-213645902557879/source",
          "state": "file",
          "uid": 1002
        },
        {
          "_ansible_item_label": {
            "file": "prometheus-serviceMonitorEtcd.yaml",
            "path": "prometheus/etcd"
          },
          "_ansible_no_log": false,
          "ansible_loop_var": "item",
          "changed": true,
          "checksum": "bfcb4a6e15b229a77d0aa2e1856549c877a42d8a",
          "dest": "/kubesphere/kubesphere/prometheus/etcd/prometheus-serviceMonitorEtcd.yaml",
          "diff": [],
          "failed": false,
          "gid": 1002,
          "group": "kubesphere",
          "invocation": {
            "module_args": {
              "_original_basename": "prometheus-serviceMonitorEtcd.yaml.j2",
              "attributes": null,
              "backup": false,
              "checksum": "bfcb4a6e15b229a77d0aa2e1856549c877a42d8a",
              "content": null,
              "delimiter": null,
              "dest": "/kubesphere/kubesphere/prometheus/etcd/prometheus-serviceMonitorEtcd.yaml",
              "directory_mode": null,
              "follow": false,
              "force": true,
              "group": null,
              "local_follow": null,
              "mode": null,
              "owner": null,
              "regexp": null,
              "remote_src": null,
              "selevel": null,
              "serole": null,
              "setype": null,
              "seuser": null,
              "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021839.9296894-4651-239588708920897/source",
              "unsafe_writes": null,
              "validate": null
            }
          },
          "item": {
            "file": "prometheus-serviceMonitorEtcd.yaml",
            "path": "prometheus/etcd"
          },
          "md5sum": "046b96b96ca1d41487a26bd6f9380505",
          "mode": "0644",
          "owner": "kubesphere",
          "size": 599,
          "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021839.9296894-4651-239588708920897/source",
          "state": "file",
          "uid": 1002
        },
        {
          "_ansible_item_label": {
            "file": "prometheus-endpointsEtcd.yaml",
            "path": "prometheus/etcd"
          },
          "_ansible_no_log": false,
          "ansible_loop_var": "item",
          "changed": true,
          "checksum": "7c2ea94a248dbdb3d55ac1b2c9c87e974703602a",
          "dest": "/kubesphere/kubesphere/prometheus/etcd/prometheus-endpointsEtcd.yaml",
          "diff": [],
          "failed": false,
          "gid": 1002,
          "group": "kubesphere",
          "invocation": {
            "module_args": {
              "_original_basename": "prometheus-endpointsEtcd.yaml.j2",
              "attributes": null,
              "backup": false,
              "checksum": "7c2ea94a248dbdb3d55ac1b2c9c87e974703602a",
              "content": null,
              "delimiter": null,
              "dest": "/kubesphere/kubesphere/prometheus/etcd/prometheus-endpointsEtcd.yaml",
              "directory_mode": null,
              "follow": false,
              "force": true,
              "group": null,
              "local_follow": null,
              "mode": null,
              "owner": null,
              "regexp": null,
              "remote_src": null,
              "selevel": null,
              "serole": null,
              "setype": null,
              "seuser": null,
              "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021840.2453165-4651-44506086891447/source",
              "unsafe_writes": null,
              "validate": null
            }
          },
          "item": {
            "file": "prometheus-endpointsEtcd.yaml",
            "path": "prometheus/etcd"
          },
          "md5sum": "2fde535bbfc9461d7423a7e56710278d",
          "mode": "0644",
          "owner": "kubesphere",
          "size": 211,
          "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021840.2453165-4651-44506086891447/source",
          "state": "file",
          "uid": 1002
        },
        {
          "_ansible_item_label": {
            "file": "prometheus-system-pvc-cleanup.yaml",
            "path": "prometheus/upgrade"
          },
          "_ansible_no_log": false,
          "ansible_loop_var": "item",
          "changed": true,
          "checksum": "801e10ad4ab561bac27c91504718815705ee15b4",
          "dest": "/kubesphere/kubesphere/prometheus/upgrade/prometheus-system-pvc-cleanup.yaml",
          "diff": [],
          "failed": false,
          "gid": 1002,
          "group": "kubesphere",
          "invocation": {
            "module_args": {
              "_original_basename": "prometheus-system-pvc-cleanup.yaml.j2",
              "attributes": null,
              "backup": false,
              "checksum": "801e10ad4ab561bac27c91504718815705ee15b4",
              "content": null,
              "delimiter": null,
              "dest": "/kubesphere/kubesphere/prometheus/upgrade/prometheus-system-pvc-cleanup.yaml",
              "directory_mode": null,
              "follow": false,
              "force": true,
              "group": null,
              "local_follow": null,
              "mode": null,
              "owner": null,
              "regexp": null,
              "remote_src": null,
              "selevel": null,
              "serole": null,
              "setype": null,
              "seuser": null,
              "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021840.5655231-4651-38043071707093/source",
              "unsafe_writes": null,
              "validate": null
            }
          },
          "item": {
            "file": "prometheus-system-pvc-cleanup.yaml",
            "path": "prometheus/upgrade"
          },
          "md5sum": "c52b75775db0e6a2027eebacb3c487e3",
          "mode": "0644",
          "owner": "kubesphere",
          "size": 587,
          "src": "/home/kubesphere/.ansible/tmp/ansible-tmp-1611021840.5655231-4651-38043071707093/source",
          "state": "file",
          "uid": 1002
        }
      ]
    },
    "role": "ks-monitor",
    "start": "2021-01-19T02:03:57.895187",
    "task": "ks-monitor | Creating manifests",
    "task_action": "template",
    "task_args": "",
    "task_path": "/kubesphere/installer/roles/ks-monitor/tasks/generate_manifests.yaml:35",
    "task_uuid": "e2ef30c7-5c87-5bd0-0226-00000000002d",
    "uuid": "b44c35d8-1548-4c2d-97e9-1afaa367e9d0"
  },
  "parent_uuid": "e2ef30c7-5c87-5bd0-0226-00000000002d",
  "pid": 3582,
  "runner_ident": "monitoring",
  "start_line": 78,
  "stdout": "",
  "uuid": "b44c35d8-1548-4c2d-97e9-1afaa367e9d0"
}
******************************************************************************************************************************************************

**Comment by RolandMa1986** [comment]
Just need add "enabled: false". Do not delete any other attributes. Seems like you have deleted other attributes like 'prometheusVolumeSize'. 
And I suggest you can use Minikube instead or use a centos/ubuntu based Linux. Kubernetes On Docker for mac was never tested.

**Comment by baojunz** [comment]
Thank you very much. I tried to build it with Ubuntu.
