### ISSUE TITLE
DevOps/The pipeline list is wrong when more than 10 pipelines are created

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3278]
**Describe the Bug**
When the 11th pipeline is created successfully, the last pipeline in the pipeline list disappears and an exception pipeline is generated
For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: 

**Environment**
http://allinone:30880

**Preset conditions**
There is a DevOps project  'test', which consists of 10 pipelines

**How To Reproduce**
1. Go to 'DevOps project 'test''
2. Create a new pipeline 'test1'

**Expected behavior**
1、pipeline test1 create successful。
2、There are 11 pipelines in the pipeline list and they are in the correct state

**Actual behavior**
When the 11th pipeline is created successfully, the last pipeline in the pipeline list disappears and an exception pipeline is generated

/kind bug
/area devops
/assign @shaowenchen 
/milestone 3.1.0
/priority high

**Comment by LinuxSuRen** [comment]
This issue was fixed by #3279
