### ISSUE TITLE
The pipeline was removed by the Jenkins client is still in the pipeline list of KS.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3281]
**Describe the Bug**
There was a pipeline removed by Jenkins client, and is still in the pipeline list of KS. 

**Versions Used**
KubeSphere:

**Environment**
http://allinone:30880/

**Preset conditions**
There is a pipeline 'Test'

**How To Reproduce**
1. Go to Jenkins client and delete pipeline 'Test'.
2. Go to pipeline list of KS.
3. checkout pipeline 'Test'

**Expected behavior**
pipeline 'Test' disappeared in pipeline list of KS.

**Actual behavior**
pipeline 'Test' is still in test pipeline list of KS, and it's healthy state becomes abnormally.

/kind bug
/area devops
/assign @shaowenchen
/milestone 3.1.0
/priority high

**Comment by LinuxSuRen** [comment]
I'd like to say that we don't support this kind of operation currently. In my view, it's unnecessary to support this. Please comment here if you have a good use case.

/cc @kubesphere/sig-devops

**Comment by wenxin-01** [comment]
When I was using DevOps, I had a lot of interaction with Jenkins, such as looking at the state of pipeline、adding or removing things. So I expect some of the more routine operations at Jenkins to be synchronized to KS
