### ISSUE TITLE
The pipeline cannot be audited by the admin user of workspace.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3282]
**Describe the Bug**
There is account 'A' , whose platform role is platform-regular and workspace role is viewer and It is  an auditor of the pipeline, it cannot audit the pipeline.

**Versions Used**
KubeSphere:

**Environment**
http://allinone:30880/

**Preset conditions**
1、There is account 'A' , whose platform role is platform-regular and workspace role is admin and It is an auditor of the pipeline.
2、There is account 'B', it created pipeline 'test'. This pipeline needs to be audited during operation.

**How To Reproduce**
1. Log in with account B, and running pipeline 'test'.
2. Log in with account A and enter the activity details page of pipeline ’test‘.
3. Make pipeline 'test' pass the audit.

**Expected behavior**
The operation is successful and the pipeline continues.

**Actual behavior**
The operation is failed,  user 'A' can not audited  pipeline 'test'.

/kind bug
/area devops
/assign @shaowenchen
/milestone 3.1.0
/priority high

**Comment by LinuxSuRen** [comment]
related front-end issue https://github.com/kubesphere/console/issues/1431

**Comment by wenxin-01** [comment]
issue fixed
