### ISSUE TITLE
The creator of pipeline cannot audit this pipeline.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3283]
**Describe the Bug**
There is account A, whose platform role is platform-admin, and workspace role is admin, which is the creator and runner of the pipeline, and It is not the reviewer of the pipeline,  it cannot audit the pipeline.

**Versions Used**
KubeSphere:

**Environment**
http://allinone:30880/

**Preset conditions**
There is account A, whose platform role is platform-admin, and workspace role is admin

**How To Reproduce**
1. Log in with account 'A'.
2. create pipe 'test', add auditor B to pipeline 'test'.
3. running pipe 'test'.
4. Use account 'A' to audit the pipeline 'test'.

**Expected behavior**
account 'A' can audit pipeline 'test'.

**Actual behavior**
account 'A' can not audit pipeline 'test'.

/kind bug
/area devops
/assign @shaowenchen
/milestone 3.1.0
/priority high

**Comment by LinuxSuRen** [comment]
related front-end issue https://github.com/kubesphere/console/issues/1431

**Comment by LinuxSuRen** [comment]
It was fixed in `nightly-20210322`.

/close
