### ISSUE TITLE
The interface returns an error when accessing an enterprise organization with an account that has workspace view permission

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3297]
**Describe the Bug**
The interface returns an error when accessing an enterprise organization with an account that has workspace view permission

**Versions Used**
KubeSphere:

**Environment**
http://allinone:30880/

**Preset conditions**
1、There is account A, whose platform permission is workspace view and does not join workspace.
2、There is workspace 'ws-test'.

**How To Reproduce**
1. Log in with account 'A'.
2. go to workspace 'ws-test'
3. click enterprise organization

**Expected behavior**
Displays organizational structure and user information.

**Actual behavior**
![image](https://user-images.githubusercontent.com/68640256/105807632-5dbed580-5fe1-11eb-9b17-9419024a94f3.png)

/kind bug
/area iam
/assign @RolandMa1986 
/milestone 3.1.0
/priority high

**Comment by RolandMa1986** [comment]
@wenxin-01, It seems like an environment issue, please verify again.

**Comment by wenxin-01** [comment]
The current environment is problematic, this issue cannot be proved.

**Comment by wenxin-01** [comment]
@RolandMa1986, it is not an environment issus. it exists in the latest environment `dev:latest`
