### ISSUE TITLE
Why does the statistics of scheduling times not decrease

### ISSUE THREAD

**Issue by yyt6200** [kubesphere/kubesphere#3304]
for instance:

I expand the replica of a pod. For example, if I expand from one replica to 10 replicas, the number of scheduling times of cluster state monitoring will be 9, and the number of scheduling times will be maintained no matter how long it takes. Then I expand the replica to 15. At this time, the monitoring of scheduling times will remain at 14, no matter how long it has been. If I delete the endpoints of the scheduler, the scheduling times will become 0.

![image](https://user-images.githubusercontent.com/44914868/105824241-0d537200-5ff9-11eb-86a0-53be371dcbca.png)

**Comment by RolandMa1986** [comment]
Work as designed. 
/close
