### ISSUE TITLE
Inaccurate message when a role is not selected

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3307]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/68640256/105829120-eac45780-5ffe-11eb-830c-291786409526.png)

**Versions Used**
KubeSphere:

**Preset conditions**
There is workspace 'ws-demo‘,has  project 'q10'、’q8‘、’q7‘

**Environment**
http://allinone:8080/

**How To Reproduce**
1. Go to workspace 'ws-demo'
2. Click on 'Enterprise organization'
3. Click on 'Maintain Organizational Structure'
4. Click 'Add new group'
5.  input name
6. select project 'q10', role 'viewer'
7. click 'Add project', and select project 'q8'
8. click 'Save'

**Expected behavior**
There is a red prompt box in project 'q8'

**Actual behavior**
There is a red prompt box in project 'q8' and 'q10'

/kind bug
/area iam
/assign @xuliwenwenwen
/milestone 3.1.0
/priority low

**Comment by RolandMa1986** [comment]
/area console
It's a frontend component comment issue.

**Comment by wenxin-01** [comment]
issue fixed `v3.1.1-rc.1`
![image](https://user-images.githubusercontent.com/68640256/124211942-962e8680-db20-11eb-9e1c-ee7c6f7c84bc.png)
