### ISSUE TITLE
Create inscm pipelines using credentials from the credential list

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#3309]
## General remarks

![image](https://user-images.githubusercontent.com/43693241/105848959-ae065980-601a-11eb-9b57-a4c9458e4f65.png)

It makes the user confused while creating a pipeline from the git repo. A new credential will be created.

**What's the reason why we need it?**

Create pipelines using credentials from the credential list

refer to https://kubesphere.com.cn/forum/d/3589-devopsbitbucket

/area devops
/project devops

@kubesphere/sig-devops

**Comment by LinuxSuRen** [comment]
So I guess the solution is that allows users to choose an exist credential or provide a dialog to create a new one. Perhaps the front-end needs to make some changes. Right? Or the backend might also needs to make changes.

**Comment by shaowenchen** [comment]
> So I guess the solution is that allows users to choose an exist credential or provide a dialog to create a new one. Perhaps the front-end needs to make some changes. Right? Or the backend might also needs to make changes.

You are right.

**Comment by LinuxSuRen** [comment]
So, do we need to create an issue from the console side? The forks who is responsible for the front-end needs to know about this issue.

**Comment by shaowenchen** [comment]
If ready to implement it now, we can sync it to the console.

**Comment by LinuxSuRen** [comment]
We've implemented this feature.
/close
