### ISSUE TITLE
[workspace-quota]When the Workspace quota is not limited, The resource used returned by the interface is 0.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3323]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/68640256/106225912-09099d80-6221-11eb-961b-7bb75e9def49.png)

**Preset conditions**
there is a workspace 'wx-ws', has project ‘wx-pro’
**How To Reproduce**
1. Go to workspace 'wx-ws', modify his quota to unrestricted
2. Go to project 'wx-pro', and deploy app
3. Go to  workspace 'wx-ws'/quota management

**Expected behavior**
Correctly displays the resources that have been used

**Actual behavior**
The resource used display as 0

/kind bug
/assign @wansir
/priority high

**Comment by wenxin-01** [comment]
this problem persists in nightly-20210314 @wansir

**Comment by wansir** [comment]
By design, `used` is the current observed total usage of the resource in the namespace.

/remove-priority high
/priority low
