### ISSUE TITLE
[workspace-quota]Problem when project and workspace are both set quotas

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3325]
**Operation steps:**
1. Project quota is set to 1CPU and 1memory
2. workspace quota set to 2CPU, 2memory
3. Create a pod with limits of 1CPU and 1memory
4. Check the quota under the project, and its utilization rate is 100%
5. Check the quota utilization rate of the workspace

**Expected results:**
Usage rate is 50%
**Actual results:**
Usage rate is 100%

![image](https://user-images.githubusercontent.com/36271543/106229259-2726cc00-6228-11eb-8c09-e2dd338eb910.png)

![image](https://user-images.githubusercontent.com/36271543/106229271-3148ca80-6228-11eb-83a4-189581d02fa6.png)

/kind bug
/assign @wansir
/priority high

**Comment by wansir** [comment]
1. The pod will occupy the quota before it is terminated.
2. Projects under the workspace share the quota.

The resource quota will be updated after the pod is terminated.

**Comment by liuyp2018** [comment]
fixed
/close
