### ISSUE TITLE
kubersphere Installation Failture

### ISSUE THREAD

**Issue by tomcyndi** [kubesphere/kubesphere#3326]
install kubersphere failed  whith All-in-one mode

when i input the command:

./kk create cluster --with-kubernetes v1.17.9 --with-kubesphere v3.0.0

the console return :

Error: Please do not use uppercase letters in hostname: VM-146-110-centos

**Comment by RolandMa1986** [comment]
Hi @tomcyndi, 
You can't use upper case hostname when installing Kubernetes. 
Please refer to [Readme](https://github.com/kubesphere/kubekey#quick-start)
/kind support
/area installer
