### ISSUE TITLE
Incorrect count of branch activity in a multi-branch pipeline.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3327]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/68640256/106255623-3d974c80-6255-11eb-97ea-34014f284cf0.png)

**Preset conditions**
There is a multi-branch pipeline 'pipe-test'.
**Environment**
http://allinone:8080

**How To Reproduce**
1. Go to pipeline 'pipe-test' details page
2. Click on branch master

**Expected behavior**
The number of activities in the master branch is displayed correctly

/kind bug
/area devops
/assign @LinuxSuRen 
/milestone 3.1.0
/priority medium

**Comment by LinuxSuRen** [comment]
hi @wenxin-01 , We don't really need to assign to a particular person. In order to make sure the whole team aware of it. A better way is that /cc @kubesphere/sig-devops 

Anyway, I will take look at this issue.

See also https://github.com/kubesphere/community/issues/298

**Comment by wenxin-01** [comment]
ok
/cc @kubesphere/sig-devops
