### ISSUE TITLE
When creating a pipeline through GitLab, the popover will suddenly disappear.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3340]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/68640256/106563637-0d0e2600-6567-11eb-9693-f371fc75b7bc.png)

**Environment**
http://allinone:8080

**Preset conditions**
There is a devops 'dev1'

**How To Reproduce**
1. Go to devops 'dev1'
2. Click on 'Create'
3. After enter name, click 'Select Code Repository'
4. Click 'GitLab'
5. Select GitLab server
6. Input owener
7. Click anywhere in the popover

**Expected behavior**
The popover doesn't disappear

**Actual behavior**
The popover disappeared

/priority high
/area devops
/cc @kubesphere/sig-devops
/kind bug
/milestone 3.1.0

**Comment by LinuxSuRen** [comment]
hi @wenxin-01 , it looks like a front-end issue. Please move it to [console](https://github.com/kubesphere/console/issues) if it's true.
