### ISSUE TITLE
where can see "DNS" in service Tag

### ISSUE THREAD

**Issue by logonmy** [kubesphere/kubesphere#3351]
## where can see "DNS" in service Tag

In one man practice，and with project=>service=>tag. here can found DNS tag。this tag info is very important。

![have-dns](https://ae01.alicdn.com/kf/Ufe5867338fd04c4a82f360514dac8bd1u.jpg)

and in my practice, In project=>service=>tag, there have not DNS tag. what wrong with me?
installer version info on the pic.
![no-dns](https://ae01.alicdn.com/kf/Ue009a09c716644d49070f0fc3d1e32b7W.jpg)

**Comment by RolandMa1986** [comment]
It's duplicate with #3155
/close 
/xref: /kubesphere/console#1286
/kind bug
/area console
