### ISSUE TITLE
The interface reported an error while editing the pipeline.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3354]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/68640256/107136669-592ee100-6940-11eb-85fb-fba66d52b90f.png)

**Environment**
http://allinone:30880

**--single branch pipeline--**
**Preset conditions**
There is a single branch pipeline 'test1'
**How To Reproduce**
1. Go to pipeline 'test1'
2. Click on 'edit jenkinsfile' or 'edit pipeline'
3. Save the modified information
4. click on 'edit information' 、 'edit configuration' 、 'edit jenkinsfile' or 'edit pipeline'、
5. Save the modified information

**Expected behavior**
Save success
**Actual behavior**
Interface returns an error message

**--Multi-branch pipeline--**
**Preset conditions**
There is a multi-branch pipeline 'test2'
**How To Reproduce**
1. Go to pipeline 'test2'
2. Click on ’More operations‘, and then click on 'edit configuration'
3. Save the modified information
4. Repeat Step 2,3 or click on 'edit information', and then click on 'Select code factory'  
5. Save the modified information

**Expected behavior*
Save success
**Actual behavior**
Interface returns an error message

/kind bug
/area devops
/cc @kubesphere/sig-devops
/milestone 3.1.0
/priority high

**Comment by LinuxSuRen** [comment]
It's duplicated with #3284

**Comment by wenxin-01** [comment]
It's duplicated with #3284
