### ISSUE TITLE
Cannot login due to multiple replicas of ks-apiserver

### ISSUE THREAD

**Issue by CaiNiaoXiaoLi** [kubesphere/kubesphere#3357]
kubesphere-system命名空间下存在多个ks-apiserver副本时，用户登陆 kubesphere UI 无响应，需经过多次重试才能成功，此问题该如何解决呢。
I can't login in Kubesphere UI when I create more than one ks-apiserver copies in kubesphere-system namespace. I login in successfully after I try for many times. Somebody can tell me to solve this? Thanks.

**Comment by Forest-L** [comment]
Take a look at the ks-console pod log.

**Comment by LinuxSuRen** [comment]
hi @CaiNiaoXiaoLi , thanks for reporting this issue to the community. But we communicate with each other in English only. So please rewrite your PR title in English. Thanks again.

**Comment by GLTSC** [comment]
宿主机的时间是不是不一致？我当时是这种情况

**Comment by LinuxSuRen** [comment]
/retitle Cannot login due to multiple replicas of ks-apiserver

**Comment by CaiNiaoXiaoLi** [comment]
> 宿主机的时间是不是不一致？我当时是这种情况

不是的，主机时间没问题，我都检查过。

**Comment by CaiNiaoXiaoLi** [comment]
> /retitle Cannot login due to multiple replicas of ks-apiserver

thanks！
