### ISSUE TITLE
Graphical pipeline does not support "post" syntax

### ISSUE THREAD

**Issue by guidao** [kubesphere/kubesphere#3359]
**Describe the Bug**
Graphical pipeline does not support "post" syntax

**Versions Used**
KubeSphere: v3.0.0

https://www.jenkins.io/doc/pipeline/tour/post/

![image](https://user-images.githubusercontent.com/3192136/108321151-bc512b00-71fe-11eb-96ca-d2d1c9e08372.png)

**Comment by guidao** [comment]
My fault, it's normal. I added it in the wrong place.

**Comment by LinuxSuRen** [comment]
No worries, we encourage people to keep in touch with the community.
