### ISSUE TITLE
support grouping project resources by conditions

### ISSUE THREAD

**Issue by lxm** [kubesphere/kubesphere#3363]
**What's it about?**

**What's the reason why we need it?**

I believe this is an important feature for Kubesphere. There're a few use cases:

* case one
* case two
* ...

Please leave your comments below if there's anyone who agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

There are two scenarios:

When publishing:

Deploy the grayscale version in the same ns, and change the full deployment to the new version after verification

At this time, multiple namespaces are not applicable, because certificates, svcs can not be easily configured between namespaces

Development process:

Create a minimum available feature test unit based on the code branch, and it is not suitable for multiple ns at this time. The reason is the same as above. At this time, if each feature is in one ns, it is very difficult to find the corresponding workload in the console

So as above, consider supporting resources in project by label keys such as `app.kubernetes.io/name` `app.kubernetes.io/instance`

**Comment by zackzhangkai** [comment]
In namespace, we have composed-applications, which we can groups resources. We can specify resources to this application, by label it with `app.kubernetes.io/name` and `app.kubernetes.io/version`.

**Comment by lxm** [comment]
> In namespace, we have composed-applications, which we can group resources. We can specify resources to this application, by label them with `app.kubernetes.io/name` and `app.kubernetes.io/version`.

If we use helm charts for managing applications, when we want to perform A/B testing, we will deploy multiple releases use the same chart with different release name, label `app.kubernetes.io/name` will be the same, only `app.kubernetes.io/instance` can make a distinction between two releases

**Comment by zackzhangkai** [comment]
You use helm charts directly instead app store, right? What do you mean by "label app.kubernetes.io/name will be the same"? I cannot get you.

**Comment by lxm** [comment]
yes, we use helm charts directly.
labels of resources(such as deployment etc..) will be the same as chart name
but `app.kubernetes.io/instance` will be the release name of helm install
so if we deploy one chart with different release names in the same namespace, the resources can not be separated by label app.kubernetes.io/name

**Comment by zackzhangkai** [comment]
`labels of resources(such as deployment etc..) will be the same as chart name` , the labels are customized in fact. You set the label to be the same with the chart name, right?

**Comment by lxm** [comment]
yes, if we use command `helm create` to create a chart , the default value of label `app.kubernetes.io/name` will be the same as the chart name.
may be we can change our own chart

**Comment by zackzhangkai** [comment]
If there is no problem, can this issue be closed?

**Comment by lxm** [comment]
![image](https://user-images.githubusercontent.com/1918195/109009124-211df100-76e9-11eb-9051-7474346a3aff.png)

after all, a drop down select should be add to the console for `application`

**Comment by zackzhangkai** [comment]
This is another question, I think. You can create a new issue, and describe it with more details.
