### ISSUE TITLE
Proposal: Support Independent storage  configuration for the monitoring module

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3365]
#3320

Because NFS is not supported, by any version of Prometheus. [issue-3534](https://github.com/prometheus/prometheus/issues/3534) It requires a POSIX filesystem. But many users' Kubernetes clusters use NFS storage for pv/pvc. So KubeSphere users can easily fall into this trap when deploying a ks cluster.

Users may have two choices：

1. Use hostPath for Prometheus.
2. Use Independent StorageClass for Prometheus.

So I think this function can be developed like below:

1. Add 【ClusterConfiguration.spec.monitoring.storageClass (string)】 item to optionally specify the independent StorageClass. So if the users have storage other than nfs, they can use it easily.
2. Add 【ClusterConfiguration.spec.monitoring.hostPath(string)】 item to optionally specify Prometheus use hostPath. So if users only have nfs storage, they can run Prometheus steadily too.
3. Add nodeAffinity (preferredDuringSchedulingIgnoredDuringExecution) configuration for Prometheus replicas. In this way, if the users select hostPath configuration, they can specify which node the pods runs on, and the pods can run even if they forget to config labels at those nodes.

**Comment by zryfish** [comment]
I, personally, prefer the second option, `Use Independent StorageClass for Prometheus.`, because hostPath has many limitations. 


> * Add 【ClusterConfiguration.spec.monitoring.hostPath(string)】 item to optionally specify Prometheus use hostPath. So if users only have nfs storage, they can run Prometheus steadily too.

And if we can set sc for Prometheus independently, we can also set Prometheus to hostPath, right? If so, we don't need this configuration item.

> * Add nodeAffinity (preferredDuringSchedulingIgnoredDuringExecution) configuration for Prometheus replicas. In this way, if the users select hostPath configuration, they can specify which node the pods runs on, and the pods can run even if they forget to config labels at those nodes.

Set nodeAffinity for hostPath is complicated, and usage of hostPath should not be encouraged. So I think we can stick to `option 2`, which only allow users to set storageClass for Prometheus. As for hostPath, should not be encouraged.

**Comment by daniel-hutao** [comment]
@zryfish I think hostPath is useful because many environments only have nfs remote storage and local disks. 
Especially the test environment. So this feature allows users to deploy ks in more general scenarios.

**Comment by daniel-hutao** [comment]
The reason for being divided into two configuration items is like below:

- monitoring.storageClass=/data/prometheus   It's hard to distinguish whether “/data/prometheus” is a sc name or a dir path.

- monitoring.storageClass=ssd
- monitoring.hostPath=/data/prometheus  This configuration is more clearer.

**Comment by daniel-hutao** [comment]
Or divide this question into two parts, we can implement the part one first, and consider whether the second one needs to be implemented or not. Because the development of the second feature may has code intrusiveness in Prometheus operator.

1. Add 【ClusterConfiguration.spec.monitoring.storageClass (string)】 item to optionally specify the independent StorageClass.
2. Add 【ClusterConfiguration.spec.monitoring.hostPath(string)】 item to optionally specify Prometheus use hostPath. So if users only have nfs storage, they can run Prometheus steadily too.

Do you think the first requirement is reasonable? @zryfish

**Comment by zryfish** [comment]
> Or divide this question into two parts, we can implement the part one first, and consider whether the second one needs to be implemented or not. Because the development of the second feature may has code intrusiveness in Prometheus operator.

I agree hostPath is very useful in the local environment, but it introduces complexity too. So I think we can finish `set storageClass for Prometheus` first. And work on `use hostPath for Prometheus` next if we get more feedback.

cc  @kubesphere/sig-infra  @kubesphere/sig-observability What's your opinions?

**Comment by benjaminhuo** [comment]
add a storage class option in ks-installer for Prometheus is ok to me
