### ISSUE TITLE
Could not connect to the container. Do you have sufficient privileges?

### ISSUE THREAD

**Issue by zhujiancc** [kubesphere/kubesphere#3368]
When I use **ip:port**(http://192.168.100.181:30880) to open Kubectl , it is no problem.

But if I use **domain** (https://ks.xxx.com) , I can not open Kubectl shell dashboard.

![image](https://user-images.githubusercontent.com/19665595/108647755-6c22e300-74f4-11eb-90f1-d01c21c3dba0.png)
![image](https://user-images.githubusercontent.com/19665595/108648122-61b51900-74f5-11eb-9875-f555cdd576c2.png)

Is it caused by cert?

**Comment by wansir** [comment]
Please enable WebSocket proxy if you use Nginx as a reverse proxy, for more details please visit https://www.nginx.com/blog/websocket-nginx/

**Comment by zhujiancc** [comment]
thx~
