### ISSUE TITLE
Devops branch name like 'feature /xxx' exception

### ISSUE THREAD

**Issue by guohz-git** [kubesphere/kubesphere#3369]
**Describe the Bug**
Add a feature / xxx branch name to the Devops Java sample project provided by the official website, and prompt 404 exception in the interface when running the build
The screenshot is as follows:

![image](https://user-images.githubusercontent.com/12553259/108653947-ad21f400-7502-11eb-8c79-0ff7040b3c10.png)

**Versions Used**
KubeSphere: 3.0.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

CentOS 7.5 / 1 masters:  16cpu/16g; 2 nodes: 16cpu/16g

**How To Reproduce**
1. Go to github add branch name like feature / xxx 
2. run devops project and select ‘feature / xxx ’ branch to build， prompt 404 exception in the UI

**Comment by LinuxSuRen** [comment]
/area devops
/kind bug

It's duplicated with #3276

/close
