### ISSUE TITLE
change node-exporter default port

### ISSUE THREAD

**Issue by pcyan** [kubesphere/kubesphere#3373]
## environment

kubernetes v1.18.3
KubeSphere v3.0.0

## question

try to change the default port of kubesphere-monitoring-system/node-exporter.
i knew that i should rewrite the clusterConfiguration but how? any document?

**Comment by LinuxSuRen** [comment]
hi @pcyan , Thanks for reaching out to us. But I don't understand what's exactly the meaning of 'default port'. I'm wondering if you can explain it more?

**Comment by FeynmanZhou** [comment]
I guess I understand it, see this [guide](https://kubesphere.io/docs/faq/observability/monitoring/#host-port-9100-conflict-caused-by-the-node-exporter) to learn more details.

**Comment by LinuxSuRen** [comment]
@FeynmanZhou Thanks for given the context. I learned it.

**Comment by pcyan** [comment]
> I guess I understand it, see this [guide](https://kubesphere.io/docs/faq/observability/monitoring/#host-port-9100-conflict-caused-by-the-node-exporter) to learn more details.

every time i enable/disable some plugins by change kubesphere clusterConfiguration, the node-exporter port will be reset to 9100.
am i missing something?
