### ISSUE TITLE
Can I apply k8s yaml in ks dashboard for all kinds

### ISSUE THREAD

**Issue by zhujiancc** [kubesphere/kubesphere#3374]
I hope to apply all kinds  k8s yaml in here. 
No need jump to fixed page to apply yaml 
![image](https://user-images.githubusercontent.com/19665595/108790974-f6cd1600-75b8-11eb-8400-58178948d7c7.png)

**Comment by zryfish** [comment]
You can open control tools `kubectl` in toolbox and apply any YAML.

**Comment by zhujiancc** [comment]
I know that , but it need more step to apply yaml.
if I click the btn 
then popup a dialog to write yaml 
and then click aplly btn , 

 It will be easy for me~
