### ISSUE TITLE
Openldap pod can't start after I delete it.

### ISSUE THREAD

**Issue by CaiNiaoXiaoLi** [kubesphere/kubesphere#3382]
Openldap pod recreated faild.
![image](https://user-images.githubusercontent.com/45308218/108956790-41c75600-76ab-11eb-8e8a-ae7efbecfa73.png)
warning level log
![image](https://user-images.githubusercontent.com/45308218/108957029-b0a4af00-76ab-11eb-9bc2-d180e14e86a1.png)
debug level log
![image](https://user-images.githubusercontent.com/45308218/108958500-09754700-76ae-11eb-898f-74ea00797642.png)

**Comment by wansir** [comment]
You need to change the replicas value from 0 to 1.

**Comment by CaiNiaoXiaoLi** [comment]
> You need to change the replicas value from 0 to 1.

I did that,but doesn't work.

**Comment by wansir** [comment]
Did you make any changes?  Related issue, https://github.com/osixia/docker-openldap/issues/218.

You should use `kubectl rollout restart sts openldap -n kubesphere-system` instead of delete pod.

**Comment by LinuxSuRen** [comment]
It looks like this issue belongs to the upstream project. I'm going to mark this as support.

/support
