### ISSUE TITLE
Ippool with IP address 0.0.0.0 should not be created

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3385]
**Describe the Bug**
Ippool with IP address 0.0.0.0 should not be created
![image](https://user-images.githubusercontent.com/36271543/108959410-53aaf800-76af-11eb-8c83-4a13dcbe43c0.png)

ks version：nightly-20210222

/kind bug
/assign @leoendless
/priority Medium
/milestone 3.1
/area console
/area networking

**Comment by liuyp2018** [comment]
verified that not fixed
/remove-kind neet-to-verify

**Comment by duanjiong** [comment]
In some cases, it is normal that all network numbers are 0. In fact, it is unlikely that users will enter all 0 network numbers here, so I think we can ignore the restriction for now.

**Comment by zryfish** [comment]
/close 
due to not a bug
