### ISSUE TITLE
There is a problem with the 'All' field display

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3388]
**Describe the Bug**
There is a problem with the 'All' field display
![image](https://user-images.githubusercontent.com/36271543/108963252-d5e9eb00-76b4-11eb-8bc3-f604c745dbcc.png)

ks version：nightly-20210222

/kind bug
/assign @leoendless 
/priority Medium
/milestone 3.1
/area console

**Comment by duanjiong** [comment]
You also need to add an option to unbind ippool from workspace  @leoendless

**Comment by liuyp2018** [comment]
Verified, and fixed
