### ISSUE TITLE
Cannot modify user profile

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#3407]
**Describe the Bug**

Cannot modify user's language and description.

1. Change language settings

![image](https://user-images.githubusercontent.com/8263040/109281696-96a7cf80-7857-11eb-9d49-f71644a01e52.png)

2. There is no change after applying settings

![image](https://user-images.githubusercontent.com/8263040/109281881-ceaf1280-7857-11eb-9b6f-b30c503fdc39.png)

**Comment by zryfish** [comment]
Please add more description, it's very unclear now

**Comment by wansir** [comment]
> Please add more description, it's very unclear now

Added some descriptions
