### ISSUE TITLE
Proposal: Add GPU monitoring support

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3414]
NVIDIA provides dcgm-exporter to support the expose of GPU metrics. We can integrate this component in kube-prometheus to support GPU monitoring. In addition, this feature needs to have corresponding support in the console. I can integrate dcgm-exporter, I have integration experience in it. But I'm not good at web development. I hope someone can complete the development work in the console alone with me.

**Comment by zhu733756** [comment]
@daniel-hutao Hi, Can you give a detailed description? In recent days, we have a nvidia gpu dashboard in repo [monitoring-dashboard](https://github.com/kubesphere/monitoring-dashboard/tree/master/contrib/gallery) which can be compatible with ks3.0. [The link here](https://kubesphere.com.cn/forum/d/3810-gpu-operator-kubesphere-gpu) in our forum have a detailed description.

**Comment by benjaminhuo** [comment]
Currently, we've no plan to add GPU monitoring. You can use KubeSphere custom monitoring to monitoring GPU as mentioned in https://kubesphere.com.cn/forum/d/3810-gpu-operator-kubesphere-gpu

**Comment by daniel-hutao** [comment]
> Currently, we've no plan to add GPU monitoring. You can use KubeSphere custom monitoring to monitoring GPU as mentioned in https://kubesphere.com.cn/forum/d/3810-gpu-operator-kubesphere-gpu

All right~
