### ISSUE TITLE
Proposal: Use elastic/helm-charts replace helm/charts for elasticsearch

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3415]
> https://github.com/helm/charts/tree/master/stable/elasticsearch

README.md

This Helm chart is deprecated

As mentioned in #10543 this chart has been deprecated in favour of the official [Elastic Helm Chart](https://github.com/elastic/helm-charts/tree/master/elasticsearch).

**Comment by junotx** [comment]
It may be updated later, but not included in the 3.1 plan, and you can replace it manually for the time being. Thank you for your proposal

**Comment by daniel-hutao** [comment]
This proposal is already contained in:
kubesphere/kubesphere/issues/3457
