### ISSUE TITLE
Alarm policies that do not set thresholds and monitor targets can still generate alarms

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3419]
**Describe the Bug**
Alarm policies that do not set thresholds and monitor targets can still generate alarms

**Environment**
http://xxxx:79:30104

**Preset conditions**
1、There is account A, which has cluster management privileges.
2、Use account A to log in to KS, and go to Platform management--》Cluster management--》Alerting Policies.

**How To Reproduce**
1. click "create"
2. Enter the name "test"
3. Set the alarm duration to 1 minute
4. Set the alarm rule expression to "node:node_cpu_utilisation:avg1m"
5. save policy
6. Check whether policy “test” produces an alert message

**Expected behavior**
Policy “test” does not produce an alert message
![image](https://user-images.githubusercontent.com/68640256/109524343-5bbdca00-7aeb-11eb-9c61-a9c6cd9b791c.png)
![image](https://user-images.githubusercontent.com/68640256/109524376-68422280-7aeb-11eb-9ea3-09618ba85f5c.png)

/priority high
/area alerting
/cc @junotx 
/kind bug
/milestone 3.1.0

**Comment by junotx** [comment]
It has been fixed by https://github.com/kubesphere/console/pull/1516

**Comment by junotx** [comment]
Ignoring rules created through custom promql in which the threshold is not necessarily set

/kind need-to-verify
