### ISSUE TITLE
Only data larger than the threshold is shown in the alert monitoring trend chart

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3420]
**Describe the Bug**
Only data larger than the threshold is shown in the alert monitoring trend chart

**Environment**
http://xxxx.79:30104

**Preset conditions**
1、There is account A, which has cluster management privileges.
2、Use account A to log in to KS, and go to Platform management--》Cluster management--》Alerting Policies.

**How To Reproduce**
1. click "create"
2. After entering the name, click Next
3. Click Custom Rules and input "node:node_cpu_utilisation:avg1m{node="node-name"} > 0.12"
4. Change the custom rule to "node:node_cpu_utilisation:avg1m{node="node-name"} > 0.15"

**Expected behavior**
The returned data should not be affected by the threshold.(The alarm monitoring data in step 3 and 4 are consistent)

**Actual behavior**
Step 3 shows data greater than 0.12
Step 4 shows data greater than 0.15
![image](https://user-images.githubusercontent.com/68640256/109526173-421d8200-7aed-11eb-97a4-d091081c9686.png)
![image](https://user-images.githubusercontent.com/68640256/109526259-53668e80-7aed-11eb-8bd4-5f030d90d866.png)

/priority high
/area alerting
/cc @junotx
/kind bug
/milestone 3.1.0

**Comment by junotx** [comment]
@wenxin-01 That is true, only the data that matches the promql is displayed, unlike common monitoring. Because the promql for alerting may be complex and does not necessarily have the threshold condition, it may not be completely disassembled.

/priority low

**Comment by zryfish** [comment]
@junotx What's the status of this issue? Anything we need to do? If not, either close this issue or move it to the next milestone.

**Comment by junotx** [comment]
Since the promql configured by the custom rule may be very complicated, such as a combination of multiple sub-statements, it is difficult to separate their thresholds one by one. 

And it is reasonable to show only the results that satisfy the expression conditions including the threshold here, and alerts related to these results may be generated later. 

So close this issue here
