### ISSUE TITLE
The recent alarm time in the alarming policy detail is incorrect.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3421]
**Describe the Bug**

The recent alarm time in the alarming policy detail is incorrect.

**Environment**
http://xxxx.79:30104

**Preset conditions**
1、There is account A, which has cluster management privileges.
2、Use account A to log in to KS, and go to Platform management--》Cluster "B" management--》Alerting Policies.

**How To Reproduce**
1. Deployment  applications makes cluster "B" CPU utilization greater than 5%.
2. Create an alarm policy "C" with an alarm duration of 5 minutes and an alarm rule of ″CPU utilization > 2%“
3. Check the latest alarm time of policy "C"

**Expected behavior**
latest alarm time of policy "C" >= Creation time of policy C + 5 minutes

**Actual behavior**
latest alarm time of policy "C"  < Creation time of policy C + 5 minutes

![image](https://user-images.githubusercontent.com/68640256/109530255-785d0080-7af1-11eb-996c-bc52e886e07b.png)

/priority high
/area alerting
/cc @junotx
/kind bug
/milestone 3.1.0

**Comment by junotx** [comment]
It should not be the recent alert time. `activeTime` is the time when the alert is active, that is, the begin time. Please name this property to `active time` @leoendless

**Comment by wenxin-01** [comment]
@leoendless Please name this property to` Alert Active Time` too 
![image](https://user-images.githubusercontent.com/68640256/110424331-98865400-80dd-11eb-827d-59e26fb67c62.png)

**Comment by leoendless** [comment]
T

> @leoendless Please name this property to` Alert Active Time` too
> ![image](https://user-images.githubusercontent.com/68640256/110424331-98865400-80dd-11eb-827d-59e26fb67c62.png)

Already fixed, please update your enviroment.
