### ISSUE TITLE
Alarm is not retriggered after changing duration of alarm or alarm rule.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3422]
**Describe the bug**
Modify an alert policy that has already generated an alert without retriggering the alert.

**Environment**
http://xxxx.79:30104

Preset conditions
1、There is account A, which has cluster management privileges.
2、Use account A to log in to KS, and go to Platform management--》Cluster "B" management--》Alerting Policies.
3、There is an alarm policy 'test' that has already generated an alarm.
**To Reproduce**
1. Modify the alarm duration or alarm rules for the alarm policy 'test'.
2. Deploy applications to enable alarm policy to generate alarm.
3. Check to see if the alarm policy test has retriggered the alarm.

**Expected behavior**
The alarm policy 'test' has retriggered alert message.

The previously generated alert state should be cleared immediately after the rule change.

**Actual behavior**
The policy  ‘test’ did not trigger the alarm again.

/priority high
/area alerting
/cc @junotx
/kind bug
/milestone 3.1.0

**Comment by junotx** [comment]
Did the rule trigger an alert before the modification? If so, does the application deployed after the modification satisfy the rule condition?  @wenxin-01

**Comment by wenxin-01** [comment]
Alarm have been triggered before the modification, and the modified rule satisfies the trigger condition. @junotx

**Comment by junotx** [comment]
If tha same alert was triggered before and after the rule changed, it would generally continue the previous alert until the duration condition is met, and then send the alert downstream.

**Comment by wenxin-01** [comment]
【Expected behavior】The previously generated alert state should be cleared immediately after the rule change.
