### ISSUE TITLE
How to upgrade all-in-one single cluster to master worker mode

### ISSUE THREAD

**Issue by minicloudsky** [kubesphere/kubesphere#3434]
**What's your question**
I installed kubesphere in all-in-one mode,Now i Brought another server,So how can I upgrade My all-in-one kubesphere cluster to master-worker mode,to get a better performance，any tutorials,docs,suggestions will be nice and helpful to me,Thanks in advance!

**Environment: OS & Hardware Information**
My two server are both Centos 7 with 2 CPU and 4G RAM

**Error logs or message (Attach logs or screenshot)**

**Installer Version**

>  v3.0.0

**Comment by FeynmanZhou** [comment]
> **What's your question**
> I installed kubesphere in all-in-one mode,Now i Brought another server,So how can I upgrade My all-in-one kubesphere cluster to master-worker mode,to get a better performance，any tutorials,docs,suggestions will be nice and helpful to me,Thanks in advance!
> 
> **Environment: OS & Hardware Information**
> My two server are both Centos 7 with 2 CPU and 4G RAM
> 
> **Error logs or message (Attach logs or screenshot)**
> 
> **Installer Version**
> 
> > v3.0.0

I hope [this guide](https://kubesphere.io/docs/installing-on-linux/cluster-operation/add-new-nodes/) can help you to add the new master or worker nodes.

**Comment by minicloudsky** [comment]
thanks ,this solved my problem
