### ISSUE TITLE
The documentation for  Service Accounts cannot be accessed.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3439]
**Environment**
nightly-20210307

**Preset conditions**
1、There is account A, which has project 'B' management privileges.
2、Use account A to log in to KS, and go to Project 'B'--》Configurations--》ServiceAccounts.

**How To Reproduce**
1. Click 'learn more'

**Expected behavior**
Go to the documentation page of Service Accounts.

**Actual behavior**
![image](https://user-images.githubusercontent.com/68640256/110427472-c6ba6280-80e2-11eb-8863-3daf8809db00.png)

/kind bug
/assign @RolandMa1986
/milestone 3.1.0
/priority high

**Comment by RolandMa1986** [comment]
@leoendless @FeynmanZhou It's not reasonable to put a v3.1 document under the v3.0 documents right? So I should not put the document to the website currently. I think we are closing to the release of 3.1. Should a new document version be created too?

**Comment by wenxin-01** [comment]
issue fixed `kubesphere v3.1.1-rc.0`

![image](https://user-images.githubusercontent.com/68640256/123744289-22eb0180-d8e1-11eb-9ce4-a99e24891d9e.png)
