### ISSUE TITLE
The application's Tracing page is blank

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3454]
**Describe the Bug**
On the Application Details page, visit the Tracing page, no request is sent, and the page is blank
![image](https://user-images.githubusercontent.com/36271543/110603238-c47b0580-81c1-11eb-8134-27e0e7f77ba7.png)

/kind bug
/assign @leoendless
/priority High
/milestone 3.1.0
/area console

**Comment by leoendless** [comment]
fixed in https://github.com/kubesphere/console/pull/1541

**Comment by liuyp2018** [comment]
Verified, and fixed
