### ISSUE TITLE
Change '登陆' to '登录'

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3456]
**Describe the Bug**

Change '登陆' to '登录'

![image](https://user-images.githubusercontent.com/36271543/110608753-7b2db480-81c7-11eb-96e5-05f0077044ff.png)

/kind bug
/assign @leoendless
/priority Low
/milestone 3.1.0
/area console

**Comment by liuyp2018** [comment]
Verified with ks-console:latest image

**Comment by 94rain** [comment]
I believe this issue has already been resolved in https://github.com/kubesphere/console/commit/a8956cd040f0200186a1e3eef2c12031ee6740ca#diff-acb47e6725b473362aa8a0a1f573935c184cae2f6c2e4205cb56f9d196b84e94R53

**Comment by liuyp2018** [comment]
fixed
