### ISSUE TITLE
Proposal: Add external elasticsearch http basic auth support at cc

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3457]
kubesphere/ks-installer/issues/1311

ES enabling authentication is a very common scenario. We already have <common.es.externalElasticsearchUrl> to sepcify the url of external es, so we can simply use a similar approach add <common.es.externalElasticsearchUsername common.es.externalElasticsearchPassword> to specify the username and password of es with authentication enabled.

**Comment by zryfish** [comment]
Looks good

**Comment by daniel-hutao** [comment]
I suggest that we can let ks support optional configuration with external authentication and non-authentication es clusters first. It needs to code at ks-installer & ks-apiserver；I can finish it with ks-installer part.

**Comment by daniel-hutao** [comment]
@kubesphere/sig-observability

**Comment by zhu733756** [comment]
Maybe we can use (eck-oeprator)[https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-overview.html] for basic auth.

**Comment by daniel-hutao** [comment]
> Maybe we can use [eck-oeprator](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-overview.html) for basic auth.

It's another topic.  We can consider how to connect to the es that enables authentication first, and then consider how to enable authentication in the internal es; because es is mainly deployed outside the cluster.

**Comment by benjaminhuo** [comment]
> I suggest that we can let ks support optional configuration with external authentication and non-authentication es clusters first. It needs to code at ks-installer & ks-apiserver；I can finish it with ks-installer part.
> 
> cc.spec.common
> **es:
> ****externalUrl: ""
> ****externalPort: ""
> ****basicAuth:
> ******enabled: false
> ******username: ""
> ******password: ""

Thanks for the proposal, it's valuable.

Basic auth is necessary for both internal and external es and it shouldn't be limited to external es

I suggest being consistent with current ks-installer settings：https://github.com/kubesphere/ks-installer/blob/master/roles/common/defaults/main.yaml#L18

```yaml
cc.spec.common
  es:
    externalElasticsearchUrl: ""
    externalElasticsearchPort: ""
    basicAuth:
      enabled: false
      username: ""
      password: ""
```

**Comment by daniel-hutao** [comment]
> > I suggest that we can let ks support optional configuration with external authentication and non-authentication es clusters first. It needs to code at ks-installer & ks-apiserver；I can finish it with ks-installer part.
> > cc.spec.common
> > **es:
> > ****externalUrl: ""
> > ****externalPort: ""
> > ****basicAuth:
> > ******enabled: false
> > ******username: ""
> > ******password: ""
> 
> Thanks for the proposal, it's valuable.
> 
> Basic auth is necessary for both internal and external es and it shouldn't be limited to external es
> 
> I suggest being consistent with current ks-installer settings：https://github.com/kubesphere/ks-installer/blob/master/roles/common/defaults/main.yaml#L18
> 
> ```yaml
> cc.spec.common
>   es:
>     externalElasticsearchUrl: ""
>     externalElasticsearchPort: ""
>     basicAuth:
>       enabled: false
>       username: ""
>       password: ""
> ```

This task can be divided into three steps, everyone can claim separately：

1. Let ks-installer support optional configuration with authentication and non-authentication es clusters;
2. Let components such as ks-apiserver optionally support authentication enabled and es without authentication enabled;
3. Let es installation with authentication.

Ok, I'll code with 【1】 first, and if someone is willing to code with 【2/3】 synchronously, you can claim it.

**Comment by daniel-hutao** [comment]
1. Let ks-installer support optional configuration with authentication and non-authentication es clusters;
 
/assign

**Comment by benjaminhuo** [comment]
The following components in KubeSphere use Elasticsearch:
- fluent-bit outputs log/events/audit to Elasticsearch
- jaeger outputs istio trace data to Elasticsearch
- Log/Event/Audit search reads Elasticsearch in KubeSphere Console
- Istio tracing reads Elasticsearch in KubeSphere Console

**Comment by daniel-hutao** [comment]
- [ ] Let ks-installer support optional configuration with authentication and non-authentication es clusters; #kubesphere/ks-installer/pull/1333
- [ ] Let components such as ks-apiserver optionally support authentication enabled and es without authentication enabled;
- [ ] Let es installation with authentication.

**Comment by daniel-hutao** [comment]
2. Let components such as ks-apiserver optionally support es with authentication enabled and without authentication enabled;  

/assign daniel-hutao

**Comment by liguodongIOT** [comment]
I'll try to solve this problem

**Comment by daniel-hutao** [comment]
> **3. Let es installation with authentication.**
> 
> I'll try to solve this problem

@liguodongIOT You can consider using ECK to deploy es, with optional support for basic auth enabled.

/assign @liguodongIOT
