### ISSUE TITLE
Not loading screenshot from app store if user not logged in

### ISSUE THREAD

**Issue by WaysonWei** [kubesphere/kubesphere#3464]
I am not sure is this a bug, but user are not able to load any attachment from api if they are not logged in. 

![Screen Shot 2021-03-13 at 4 21 07 PM](https://user-images.githubusercontent.com/54336863/111017431-6b58df00-8418-11eb-9995-ea879a8a5d31.png)

**Comment by xyz-li** [comment]
It will be fixed in v3.1
