### ISSUE TITLE
When modifying the application repository,  there is no prompt message when the set name is repeated

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3472]
**Describe the Bug**
No prompt message is given when the set name is repeated

![image](https://user-images.githubusercontent.com/36271543/111130424-2b2d6400-85b2-11eb-8e73-736a488ecf91.png)

**steps:**
1. When modifying the application repository, the setting name is repeated with the name of the existing application repository
2. Click OK

**Expected results:**
Give a prompt message indicating a name conflict

**Actual results:**
when click the ok button, there is no pop-up message

/kind bug
/assign @leoendless
/priority Low
/milestone 3.1.0
/area console

**Comment by fuchunlan** [comment]
![image](https://user-images.githubusercontent.com/63338728/121500103-969b9c00-ca10-11eb-9e9b-7957a94859f4.png)
Follow your steps, and a prompt box pops up now, please check it



> **描述Bug**
> 设置名称重复时没有提示信息
> 
> ![图像](https://user-images.githubusercontent.com/36271543/111130424-2b2d6400-85b2-11eb-8e73-736a488ecf91.png)
> 
> **脚步：**
> 
> 1. 修改应用存储库时，设置名称与现有应用存储库的名称重复
> 2. 单击确定
> 
> **预期结果：**
> 提示名称冲突
> 
> **实际结果：**
> 点击确定按钮时，没有弹出消息
> 
> /kind 错误
> /assign @leoendless
> /priority Low
> /milestone 3.1.0
> /area console

**Comment by liuyp2018** [comment]
verified
