### ISSUE TITLE
kubesphere 3.1:  misleading description when deleting a devops pipeline

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/kubesphere#3476]
**Describe the Bug**

![Screen Shot 2021-03-15 at 5 49 10 PM](https://user-images.githubusercontent.com/70880165/111135393-90378880-85b7-11eb-8c33-a0b9c2fe211e.png)

The content of the dialog says "Please enter the user name ...", this is wrong, I'm deleting a pipeline, not a user.

**Versions Used**
KubeSphere: 3.1 (nightly-20210314)

Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by stoneshi-yunify** [comment]
The text is still not correct, tested with nightly-20210330 :

![Screen Shot 2021-03-31 at 3 25 10 PM](https://user-images.githubusercontent.com/70880165/113106486-688e2480-9235-11eb-90e6-09d69c4cccf9.png)

**Comment by LinuxSuRen** [comment]
It works in `kubespheredev/ks-console:nightly-20210412@sha256:74cd651a78c9d9a6c46658a7037b2706712c42a44b6c95239027eba3633af5f5`

![image](https://user-images.githubusercontent.com/1450685/114485719-007d0c80-9c3f-11eb-92e8-f1eb87bdec12.png)

/close
