### ISSUE TITLE
Inpropriate data validation prompt of alerting template rules in alerting policy 

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/kubesphere#3478]
**Describe the Bug**

The data is totally correct, but it still prompts an error of the alerting template rules in the alert policy creating page. Please see also the screenshot:

![image](https://user-images.githubusercontent.com/1450685/111242041-50b18080-8639-11eb-9558-eef8e5c09922.png)

![image](https://user-images.githubusercontent.com/1450685/111242085-6757d780-8639-11eb-887a-23191df107b2.png)

![image](https://user-images.githubusercontent.com/1450685/111242115-73dc3000-8639-11eb-8f30-4269f7213cc1.png)

/area console
/area alerting
/priority medium

**Versions Used**
KubeSphere: `nightly-20210314`

**Environment**
This is not an environmental issue.

**How To Reproduce**
1. Go to Monitoring and Alerting Page
2. Create a custom Policy
3. See the errors prompt

**Expected behavior**
The data validation should have a correct prompt.

**Comment by junotx** [comment]
This can be reproduced, and may be caused by the validation bug
/assign @leoendless
