### ISSUE TITLE
kubesphere 3.1: failed pipeline was showed as success

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/kubesphere#3479]
**Describe the Bug**
test-pipe2: the "Sync Status" is "SUCEESS", but the latest activity of this pipe was "Failure". 

I think the "Sync Status" should show the latest activity's status.

![Screen Shot 2021-03-16 at 9 49 58 AM](https://user-images.githubusercontent.com/70880165/111244609-362dd600-863e-11eb-8bb4-6958fe182826.png)
![Screen Shot 2021-03-16 at 9 50 05 AM](https://user-images.githubusercontent.com/70880165/111244621-3c23b700-863e-11eb-8b0a-28905e4fe770.png)

**Versions Used**
KubeSphere: 3.1 (nightly-20210314)
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by LinuxSuRen** [comment]
The `Sync Status` might makes people feel confused. But it means the communication status between Jenkins and KubeSphere instead of the build status. So I guess this is not a bug. It could be an enhancement if you have a better idea.

How do you think about this @shaowenchen

**Comment by stoneshi-yunify** [comment]
> The `Sync Status` might makes people feel confused. But it means the communication status between Jenkins and KubeSphere instead of the build status. So I guess this is not a bug. It could be an enhancement if you have a better idea.
> 
> How do you think about this @shaowenchen

Agreed as not bug.
