### ISSUE TITLE
kubesphere 3.1: copy a pipeline with description

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/kubesphere#3480]
**Describe the Bug**
Test case: ks-6145

Failed step 2, I got same description with original pipeline.

![Screen Shot 2021-03-16 at 10 18 30 AM](https://user-images.githubusercontent.com/70880165/111246441-38ddfa80-8641-11eb-90b9-5f1d404b2f60.png)

**Versions Used**
KubeSphere: 3.1 (nightly-20210314)
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by LinuxSuRen** [comment]
The front-end does send the data with a description. So I guess we might need to fix this from the front-end.

![image](https://user-images.githubusercontent.com/1450685/111405007-b4f04500-870a-11eb-9acd-66265d981fe1.png)

**Comment by stoneshi-yunify** [comment]
retested and passed with nightly-20200330
