### ISSUE TITLE
kubesphere 3.1: copy pipeline when jenkins stopped

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/kubesphere#3482]
**Describe the Bug**
Test case: ks-6568

Choose a pipepline and select `Copy Pipeline`, enter pipeline name, then stopped jenkins (scale the deployment to 0), then click `OK` to create the pipeline.

Expected result: copy failed

Actual result: copy succeeded

![Screen Shot 2021-03-16 at 12 05 09 PM](https://user-images.githubusercontent.com/70880165/111254684-8877f280-8650-11eb-84c2-dc6dde58291c.png)
![Screen Shot 2021-03-16 at 12 05 59 PM](https://user-images.githubusercontent.com/70880165/111254704-92015a80-8650-11eb-954d-3bde8f6bc4bf.png)
![Screen Shot 2021-03-16 at 12 06 13 PM](https://user-images.githubusercontent.com/70880165/111254707-93cb1e00-8650-11eb-8f33-08a729ad239f.png)

**Versions Used**
KubeSphere: 3.1 (nightly-20210314)
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

/area devops
/kind bug
/assign @kubesphere/sig-devops 
/milestone 3.1.0

**Comment by LinuxSuRen** [comment]
In my opinion, this should be a good feature instead of a bug. Firstly, users don't need to care about the status of Jenkins. So the PIpeline copy action should be successful no matter Jenkins is ok or not.

@liuyp2018 @stoneshi-yunify What's your opinion?

**Comment by stoneshi-yunify** [comment]
I agree with @LinuxSuRen , wonder what does @liuyp2018 think.

**Comment by liuyp2018** [comment]
I agree with that and will modify this test cases @stoneshi-yunify @LinuxSuRen

**Comment by LinuxSuRen** [comment]
Consider all people agree with each other. I'm going to close this issue.

/close
/kind-remove bug
