### ISSUE TITLE
PlaceHolder is not shown

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3483]
**Describe the Bug**
PlaceHolder is not shown in the input box when creating the service and adding environment variables
![image](https://user-images.githubusercontent.com/36271543/111286186-e7ebf780-867c-11eb-9aee-fc4cb91d8d10.png)

/kind bug
/assign @leoendless 
/priority low
/milestone 3.1.0
/area console

**Comment by fuchunlan** [comment]
> **Describe the Bug**
> PlaceHolder is not shown in the input box when creating the service and adding environment variables
> ![image](https://user-images.githubusercontent.com/36271543/111286186-e7ebf780-867c-11eb-9aee-fc4cb91d8d10.png)
> 
> /kind bug
> /assign @leoendless
> /priority low
> /milestone 3.1.0
> /area console

Follow your steps，and my page did not display this bug
![image](https://user-images.githubusercontent.com/63338728/121330576-b798ba00-c948-11eb-8941-e621240f9c10.png)

**Comment by liuyp2018** [comment]
fixed
