### ISSUE TITLE
The workload link page cannot be viewed on the service details page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3487]
**Describe the Bug**
The workload link page cannot be viewed on the service details page
![image](https://user-images.githubusercontent.com/36271543/111292746-78c5d180-8683-11eb-8e15-db2fd148e1cf.png)

/kind bug
/assign @leoendless 
/priority High
/milestone 3.1.0
/area console

**Comment by zryfish** [comment]
duplicate with https://github.com/kubesphere/kubesphere/issues/3538, and the issue is verified as fixed.
/close
