### ISSUE TITLE
the protocol is not fully displayed

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3488]
**Describe the Bug**
In the container group port protocol drop-down box, the protocol is not fully displayed
![image](https://user-images.githubusercontent.com/36271543/111294105-f1795d80-8684-11eb-99a2-455822447fad.png)

/kind bug
/assign @leoendless
/priority Medium
/milestone 3.1.0
/area console

**Comment by zryfish** [comment]
Yeah, still on v3.1.0, only visible when hovering on the combo box

/cc @kubesphere/sig-console

**Comment by liuyp2018** [comment]
verified in ks-console:latest image

**Comment by liuyp2018** [comment]
fixed
