### ISSUE TITLE
404 link problem in interface

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3492]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/36271543/111404666-22e83c80-870a-11eb-93c9-503a2a09d9bf.png)

![image](https://user-images.githubusercontent.com/36271543/111404844-6fcc1300-870a-11eb-93f4-e5664b20f731.png)

![image](https://user-images.githubusercontent.com/36271543/111431951-5f7e5d00-8737-11eb-8f8c-516759f15873.png)

![image](https://user-images.githubusercontent.com/36271543/111433123-d8ca7f80-8738-11eb-99af-81ec585c4aba.png)

![image](https://user-images.githubusercontent.com/36271543/111441859-b0e01980-8742-11eb-96ad-d56101590b3d.png)

![image](https://user-images.githubusercontent.com/36271543/111441927-c6edda00-8742-11eb-80c9-e904fae589e6.png)

/kind bug
/assign @leoendless 
/priority Low
/milestone 3.1.0
/area console

**Comment by FeynmanZhou** [comment]
/cc @kubesphere/sig-docs 
/assign @Felixnoo @Sherlock113 @Patrick-LuoYu 
These two links are also broken in v3.0.0.

**Comment by zryfish** [comment]
Verified as fixed. Only one question, they are linked to the English documentation no matter user's language settings, is that expected or we are going to fix it later?

**Comment by Sherlock113** [comment]
I assume this is expected. If I understand it correctly, users will be directed to the English doc website regardless of their console language. Is that correct? @leoendless 

![image](https://user-images.githubusercontent.com/65327072/113833849-b6b6a100-97bc-11eb-8bb5-8e0f754e553f.png)

**Comment by zhu733756** [comment]
Hi,  I just found the link (https://v3-1.docs.kubesphere.io/docs/project-user-guide/configuration/serviceaccounts/ )  also went 404, page not found.

**Comment by liuyp2018** [comment]
fixed
/close
