### ISSUE TITLE
jenkins initial password is not synced with KubeSphere

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/kubesphere#3494]
**Describe the Bug**

Sometimes, after enable devops plugin, cannot login Jenkins console with KubeSphere initial password.

Indeed, as we know, this is because of the sync between Jenkins with KubeSphere. But the status shows incorrect.

![image](https://user-images.githubusercontent.com/20178386/111407282-90966780-870e-11eb-8fad-123d9ac85ba4.png)

/assign @kubesphere/sig-devops

**Comment by LinuxSuRen** [comment]
> Sometimes, after enable devops plugin, cannot login Jenkins console with KubeSphere initial password.

We already had an issue tracking this issue. Please see #3105

> Indeed, as we know, this is because of the sync between Jenkins with KubeSphere. But the status shows incorrect.

This `Status` makes people feel confused. We already remove it from the list. For anyone who want to know the sync status, then can see it from the credential details.

/close
