### ISSUE TITLE
kubesphere 3.1: no response when clicking proceed in pipeline

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/kubesphere#3495]
**Describe the Bug**
I was following https://kubesphere.io/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile/ to run a pipeline, and stuck in step 5 point 4:
```
The pipeline pauses at the stage deploy to dev. You need to click Proceed manually. ...
```

No response when I clicked the `Proceed`, the pipeline still paused.

![Screen Shot 2021-03-17 at 11 06 11 AM](https://user-images.githubusercontent.com/70880165/111408862-de13d400-8710-11eb-9123-947a85382b3f.png)

**Versions Used**
KubeSphere: 3.1 (nightly-20210314)
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

/area devops
/kind bug
/assign @kubesphere/sig-devops 
/milestone 3.1.0

**Comment by LinuxSuRen** [comment]
Thanks for reporting this issue.
/assign
