### ISSUE TITLE
cannot use fuzzy queries when querying by the name of the application

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3496]
**Describe the Bug**

In the workload list, use fuzzy queries when querying by application name .  No matching data is queried
![image](https://user-images.githubusercontent.com/36271543/111409243-85910680-8711-11eb-928b-76dc2dd02674.png)

/kind bug
/assign @xyz-li 
/priority Medium
/milestone 3.1.0
/area app-management

**Comment by liuyp2018** [comment]
/reopen
Fuzzy search cannot be used in the workload list

**Comment by wansir** [comment]
@liuyp2018 Not a valid issue, we use labelSelector as the filter condition, which must be exactly.
