### ISSUE TITLE
workspace viewer can not view the workspace quota

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#3498]
**Describe the Bug**
A user with a global role `platform-regular`  and a workspace role `viewer`  can not view the workspace quote management.

For UI issues please also add a screenshot that shows the issue.

![1615953979(1)](https://user-images.githubusercontent.com/53003665/111413447-3e0e7880-8719-11eb-8ac2-1570ee9dad69.png)

**Versions Used**
KubeSphere: 3.1 20210317
Kubernetes: (If KubeSphere installer used, you can skip this)

**Expected behavior**
A user with a global role `platform-regular`  and a workspace role `viewer`  can view the workspace quote management.

**Comment by leoendless** [comment]
@wansir workspace roles should be updated.

**Comment by wanjunlei** [comment]
not fixed

**Comment by wansir** [comment]
![image](https://user-images.githubusercontent.com/8263040/114995508-7a77f480-9ed0-11eb-9888-2e584675fa35.png)

User granted to view `workspace-settings` should show workspace quota page.

/assign @harrisonliu5
