### ISSUE TITLE
Incorrect Components were selected when creating a Blue-green Deployment

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/kubesphere#3499]
**Describe the Bug**
Incorrect Components were selected when creating a Blue-green Deployment

**Versions Used**
KubeSphere: latest

**How To Reproduce**
1. Go to `Applications` and click `Deploy Sample Application`
2. Once the `bookinfo` is ready. Create a `Blue-green Deployment`
3. Under the `Grayscale Release Components` tab, Selelct Rating firstly. 
4. Then click the Applicaiotn dropbox, uncheck the `bookinfo`
5. Go next and create the Blue-green Deployment
6.  Check the Job Status all pods was shown as replicats under rating.
![bookinfo](https://user-images.githubusercontent.com/1720333/111414364-d6592d00-871a-11eb-9435-1da5ad102a60.png)

**Expected behavior**
Only Ratings pods can be  selected.

/kind bug
/area console
/area microservice

/cc @leoendless @zackzhangkai

**Comment by zackzhangkai** [comment]
@leoendless  the labels should be `app=ratings,app.kubernetes.io/name=bookinfo,app.kubernetes.io/version=v1`. But when do the `Then click the Applicaiotn dropbox, uncheck the bookinfo` steps as upon, the label `app=ratings` was removed.

![image](https://user-images.githubusercontent.com/20178386/111431564-e8e15f80-8736-11eb-9295-7fc762397c08.png)

**Comment by RolandMa1986** [comment]
Verified on build ks-console:nighlty-20210323
/close
