### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by cnicy** [kubesphere/kubesphere#350]
有RoadMap吗？我看官网说2.0会在4月份发布，不知道具体什么时间？
开发者应该怎么参与呢，有没有开发者文档呢，通过源码了解整体架构效率比较低。
前端UI计划什么时间发布呢？

**Comment by calvinyv** [comment]
我们4月19号会举办产品发布会，目前 2.0.0在最后的收尾测试工作，预计五一假期之后会正式发布，目前我们提供了开发版，尝鲜用户可以尝试。

开发者文档会在发布会之后酌情推出。

前端 UI 会在发布会之后先将易捷版UI开源，以后会逐步开源高级版UI，开源工作并不仅仅是把代码放到github上面这么简单，需要有复杂的推广、运维、服务能力的支持，我们目前还处于集中主要研发力量在产品研发这个阶段，望理解。

**Comment by cnicy** [comment]
@calvinyv  2.0会同步开源吗？

**Comment by calvinyv** [comment]
#290 duplicated

暂时无法做到同步，人手有限，但一定会开源的。青云appcenter整套架构现在通过 openpitrix 项目全开源，所以不用怀疑我们对开源的决心。
