### ISSUE TITLE
After selected credential, the interface 'projectlist' is not requested again.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3504]
**Describe the Bug**

**Versions Used**
KubeSphere: `dev:latest`

**Preset conditions**
There is a devops project 'dev1'

**How To Reproduce**
1. Go to devops project 'dev1'
2. Click on 'Create'
3. Select Code Repository after enter name
4. Click 'GitLab'
5. Select 'Gitlab Server'
6. Enter owner
7. select Credential

**Expected behavior**
After selected credential, the interface 'projectlist' is requested again.

**Actual behavior**
After selected credential, the interface 'projectlist' is requested again. so private projects are not displayed.

![image](https://user-images.githubusercontent.com/68640256/111433323-1af3c100-8739-11eb-960b-4abf097c344f.png)

/priority high
/area devops
/cc @kubesphere/sig-devops
/kind bug
/milestone 3.1.0

**Comment by harrisonliu5** [comment]
This API doesn't need the param of credential, so after the selected credential, the interface "projectlist" does not need to be requested.
