### ISSUE TITLE
When the number of branches is more than 10, no data is returned in the second page.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3507]
**Versions Used**
KubeSphere: `dev:latest`

**Preset conditions**
There is a multi-pipeline 'test1' with 12 branchs

**How To Reproduce**
1. Go to pipeline 'test1'
2. Check 'Activity List'
3. Go to page 2

**Expected behavior**
Show two branches

**Actual behavior**
Show no data
![image](https://user-images.githubusercontent.com/68640256/111446850-cad02b00-8747-11eb-985e-46785e7037b3.png)

![image](https://user-images.githubusercontent.com/68640256/111445915-d3743180-8746-11eb-8739-e68e6aaea2cc.png)

/priority high
/area devops
/cc @kubesphere/sig-devops
/kind bug
/milestone 3.1.0

**Comment by LinuxSuRen** [comment]
It caused by the bug of BlueOcean. The API of BlueOcean returns empty if the parameter `start` > 0.
