### ISSUE TITLE
Namespace quota can exceed the maximum resource of cluster

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#3508]
**Describe the Bug**
Namespace quota can exceed the maximum of the cluster

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/53003665/111446133-0caca180-8747-11eb-96d5-32ff3c8e9797.png)

**Versions Used**
KubeSphere: 3.1.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Expected behavior**
Namespace quota should not exceed the maximum value of cluster resources

/kind bug
/area console
/milestone 3.1.0
/assign @leoendless

**Comment by zwh417** [comment]
same with #3503
