### ISSUE TITLE
kubesphere 3.1: reviewer can not approve a pipeline

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/kubesphere#3514]
**Describe the Bug**
Test case: ks-6579

`stone1` has the `viewer` role for a devops project, and it's one of the reviewer of a pipeline. However, it can not approve the pipeline, it can click the button, but the pipeline did not continue.

![Screen Shot 2021-03-18 at 10 17 10 AM](https://user-images.githubusercontent.com/70880165/111564317-7fb02980-87d4-11eb-8ee9-ef5fbf744038.png)
![Screen Shot 2021-03-18 at 10 24 11 AM](https://user-images.githubusercontent.com/70880165/111564336-863ea100-87d4-11eb-8cee-06ed0387e017.png)

![Screen Shot 2021-03-18 at 10 28 40 AM](https://user-images.githubusercontent.com/70880165/111564500-c867e280-87d4-11eb-85de-66da4a8e22d0.png)
![Screen Shot 2021-03-18 at 10 28 45 AM](https://user-images.githubusercontent.com/70880165/111564504-caca3c80-87d4-11eb-82a5-5aaf2a70b053.png)

**Versions Used**
KubeSphere: 3.1 (nightly-20210314)
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

/area devops
/kind bug
/assign @kubesphere/sig-devops 
/milestone 3.1.0

**Comment by LinuxSuRen** [comment]
A reviewer only has the read permission. But the approve or reject operation is about to change the status of a Pipeline run. So I'm going to close this issue.
/close

**Comment by stoneshi-yunify** [comment]
@liuyp2018 @wenxin-01  please verify case ks-6579 and ks-6618 and change them accordingly. thanks.

**Comment by wenxin-01** [comment]
Test case modified
