### ISSUE TITLE
Incorrect roles selected when creating roles under access-control page

### ISSUE THREAD

**Issue by yuswift** [kubesphere/kubesphere#3515]
**Describe the Bug**

https://user-images.githubusercontent.com/37265389/111564569-e5041a80-87d4-11eb-93a7-90d3ce958eb5.mov

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: nightly-20210316

**How To Reproduce**
1. Login with admin user
2. Click on cluster management & access control
3. Click on create account role
4. See the error

**Expected behavior**
Roles should be selected correctly.

**Comment by fuchunlan** [comment]
> **Describe the Bug**
> A clear and concise description of what the bug is.
> 
>  2021-03-18.10.15.31.mov 
> For UI issues please also add a screenshot that shows the issue.
> 
> **Versions Used**
> KubeSphere: nightly-20210316
> 
> **How To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Login with admin user
> 2. Click on cluster management & access control
> 3. Click on create account role
> 4. See the error
> 
> **Expected behavior**
> Roles should be selected correctly.

Follow your steps, the bug doesn't exist now, please check it.

https://user-images.githubusercontent.com/63338728/121483022-4d435080-ca00-11eb-96a9-ab8a6199c974.mov

**Comment by yuswift** [comment]
> > **Describe the Bug**
> > A clear and concise description of what the bug is.
> > 2021-03-18.10.15.31.mov
> > For UI issues please also add a screenshot that shows the issue.
> > **Versions Used**
> > KubeSphere: nightly-20210316
> > **How To Reproduce**
> > Steps to reproduce the behavior:
> > 
> > 1. Login with admin user
> > 2. Click on cluster management & access control
> > 3. Click on create account role
> > 4. See the error
> > 
> > **Expected behavior**
> > Roles should be selected correctly.
> 
> Follow your steps, the bug doesn't exist now, please check it.
> 
>  2021-06-10.3.26.11.mov

Me neither.
/close
