### ISSUE TITLE
Left Quota does not change with the pod replicas

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#3518]
**Describe the Bug**
The `Left Quota` does not change with the pod replicas when create workload.

For UI issues please also add a screenshot that shows the issue.

![image](https://user-images.githubusercontent.com/53003665/111582317-9e72e800-87f5-11eb-9a63-1d8c4acd0724.png)

![image](https://user-images.githubusercontent.com/53003665/111582385-b480a880-87f5-11eb-98ce-43fedec92515.png)

**Versions Used**
KubeSphere: 3.1.0
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/area console
/milestone 3.1.0
/assign @leoendless

**Comment by leoendless** [comment]
Duplicate of #https://github.com/kubesphere/console/issues/1603
