### ISSUE TITLE
can't enter the container terminal on console

### ISSUE THREAD

**Issue by yuswift** [kubesphere/kubesphere#3519]
**Describe the Bug**
<img width="1879" alt="Jietu20210318-150751" src="https://user-images.githubusercontent.com/37265389/111586586-04626e00-87fc-11eb-88ca-6d2658a22acf.png">

Multi cluster enabled, the host cluster version is nightly-0316 and the member cluster version is v3.0.0. After merged this [pr](https://github.com/kubesphere/kubesphere/pull/3042), the console needs to be compatible with older version.

**Versions Used**
KubeSphere: host nightly-0316 member v3.0.0

**Expected behavior**
Return status code 200.

**Comment by zryfish** [comment]
verified as fixed 
/close
