### ISSUE TITLE
The network policy does not support multi-cluster projects

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3520]
**Describe the Bug**
**Test premise:**
In the multi-cluster environment, there is a project 'P1', which belongs to cluster 'Cluster1'
There is a project P2 that belongs to clusters 'Cluster1' and 'Cluster2'

**steps:**
1. Create service 'SVC1' in project 'P1'
2. Turn on the network policy in Project 'P1' and add project 'P2' whitelist: Allow 'P2' to access 'P1'
3. Create the POD resource under Project 'P2'
4. Enter the POD under Project 'P2' and access the service 'SVC1' under Project 'P1'

**Expected results:**
In Project 'P2', services in Project 'P1' are accessible

**Actual results:**
In Project 'P2', services in Project 'P1' cannot be accessed

/assign @duanjiong 
/priority High
/milestone 3.1.0
/area networking

**Comment by duanjiong** [comment]
Currently the network policy only applies to single clusters, can we filter out multi-cluster items when listing them on the front end, or can we hint at them and gray them out like in the image below  @leoendless 
![image](https://user-images.githubusercontent.com/3678855/112412004-c368dd00-8d58-11eb-9c75-4ae644039dc6.png)

**Comment by duanjiong** [comment]
The network policy relies on the namespace label kubesphere.io/namespace, but the multicluster project label will be overwritten by kubefed   @yuswift

**Comment by zryfish** [comment]
> Currently the network policy only applies to single clusters, can we filter out multi-cluster items when listing them on the front end, or can we hint at them and gray them out like in the image below @leoendless
> ![image](https://user-images.githubusercontent.com/3678855/112412004-c368dd00-8d58-11eb-9c75-4ae644039dc6.png)

I agree with @duanjiong, it requires extra effort to support network policy for multicluster projects.

**Comment by liuyp2018** [comment]
The prompt message needs to be optimized
![image](https://user-images.githubusercontent.com/36271543/115808960-d20ce780-a41d-11eb-997e-40e5843b46d3.png)
/remove-priority High
/priority Low

**Comment by harrisonliu5** [comment]
please give a suggestion for the message
