### ISSUE TITLE
When using 'Bitbucket Serve' to create pipeline, the interface reports an error of '500'

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3523]
**Versions Used**
KubeSphere: `dev:latest`
bitbucket: `image: docker.io/atlassian/bitbucket-server`

**Preset conditions**
There is a devops project 'dev1'

**How To Reproduce**
1. Go to devops project 'dev1'
2. Click on 'create'
3. click on 'Code Repository' after enter name
4. Click on 'Bitbucket Server'
5. Click on 'confirm' after enter Bitbucket Server,Username and password
6. click on project name

**Expected behavior**
Display  information of repositories

**Actual behavior**
![image](https://user-images.githubusercontent.com/68640256/111726736-72fb0680-88a4-11eb-8853-13efd10e73bf.png)

![image](https://user-images.githubusercontent.com/68640256/111726937-d9802480-88a4-11eb-954f-cebde1243a74.png)

/priority high
/area devops
/cc @kubesphere/sig-devops
/kind bug
/milestone 3.1.0

**Comment by LinuxSuRen** [comment]
Response JSON is:

```
{
  "message" : "An unknown error was reported from the BitBucket server",
  "code" : 404,
  "errors" : [ ]
}
```

**Comment by LinuxSuRen** [comment]
The PR https://github.com/jenkinsci/blueocean-plugin/pull/2141 can fix this issue.

`net.sf.json.JSONException: JSONObject["details"] is not a JSONArray.`

**Comment by LinuxSuRen** [comment]
Some issues are related to each other:

* https://github.com/kubesphere/kubesphere/issues/3530
* https://github.com/kubesphere/console/issues/1634

**Comment by zryfish** [comment]
Is this issue ready to verify?

**Comment by LinuxSuRen** [comment]
Still waiting for the release of BlueOcean plugin. See also [here](https://github.com/jenkinsci/blueocean-plugin/pull/2141#issuecomment-808987749)

**Comment by LinuxSuRen** [comment]
The front-end PR should be able to fix the front-end part issue. See https://github.com/kubesphere/console/pull/1770

**Comment by wenxin-01** [comment]
issue fixed
