### ISSUE TITLE
Modifying the configmap of `kubesphere-router` does not take effect, nor does restarting the pod

### ISSUE THREAD

**Issue by eltonbfw** [kubesphere/kubesphere#3528]
What can I do to make the changes to the configmap take effect?

**Comment by daniel-hutao** [comment]
Can you provide more information? For example, which field you modified, what status or logs you saw, how can we reproduce your problem, etc.

**Comment by eltonbfw** [comment]
Create an abc project in workspaces, enter abc and set the gateway, the steps are: Project Settings -> Advanced Settings -> Set Gateway. After that we can use ingress in the abc project.

When we finish the above steps, kubesphere will create 2 resources in the kubesphere-controls-system of system-workspace.
A deployment named kubesphere-router-abc and a configmap named kubesphere-router-abc-nginx

We can view the logs of the corresponding pods and see the corresponding log output once the ingress resource has changed in any way, e.g., annotations have changed or rules have changed. However, only if we modify the configmap, we won't see any log output. According to the official documentation of ingress-nginx, I can't make any changes to the configmap, such as gzip compression after setting `use-gzip: "false"` to access the resources. Even if I delete the old pods and access the newly generated pods, the configmap configuration does not take effect


在workspaces中创建一个abc项目, 进入abc并设置网关，步骤为：Project Settings -> Advanced Settings -> Set Gateway 。之后我们就能在abc项目中使用ingress了。

当我们完成上述步骤后，kubesphere会在system-workspace的kubesphere-controls-system创建2个资源：
一个名为kubesphere-router-abc的deployment和一个名为kubesphere-router-abc-nginx的configmap

我们可以查看到相应的pod的日志，一旦ingress资源发生任何变更，如：annotations发生变化或者rules发生变化，都会看到对应的日志输出。但唯独修改configmap不会看到任何的日志输出，我根据ingress-nginx官方文档的指引，对configmap进行任何修改都无法生效，如设置`use-gzip: "false"`之后访问资源，依然会gzip压缩。即便删除老的pod，访问新生成的pod，configmap的配置也不会生效
