### ISSUE TITLE
The link address is incorrect in the Create Application Template page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3531]
**Describe the Bug**
In the Create Application Template page, the links for 《Helm 规范及应用开发》 are different in the two places

![image](https://user-images.githubusercontent.com/36271543/111936506-c49fcd00-8b00-11eb-892f-90448e92e06d.png)

![image](https://user-images.githubusercontent.com/36271543/111936536-db462400-8b00-11eb-83dd-61a1186a3979.png)

/kind bug
/assign @leoendless
/priority Low
/milestone 3.1.0
/area console

**Comment by liuyp2018** [comment]
the links  are still different in the two pages
![image](https://user-images.githubusercontent.com/36271543/123025227-e1ec7c00-d40c-11eb-8035-737ed0ab096c.png)
![image](https://user-images.githubusercontent.com/36271543/123025262-f0d32e80-d40c-11eb-852d-cef757d44cfe.png)

/remove-kind need-to-verify

**Comment by fuchunlan** [comment]
> /remove-assign @leoendless
> /assign @fuchunlan

Which link is better ？

**Comment by liuyp2018** [comment]
fixed
