### ISSUE TITLE
Re-upload operation problem

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3532]
**Describe the Bug**
**steps**
1. Create the application template page
2. The HELM file has been selected and uploaded
3. Click the re-upload button
4. In the file selection box that pops up, select and double-click a Helm file package

**Expected results:**
The updated Helm package can be uploaded

**Actual results:**
The file selection box pops up again

![image](https://user-images.githubusercontent.com/36271543/111937356-82778b00-8b02-11eb-9a79-e0c631deb5f8.png)

/kind bug
/assign @leoendless
/priority High
/milestone 3.1.0
/area console

**Comment by leoendless** [comment]
By design.

**Comment by liuyp2018** [comment]
fixed
/close
