### ISSUE TITLE
The monitoring data of the edge node is incorrect.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3533]
**Versions Used**
KubeSphere:  `dev:latest`

**Preset conditions**
edge node 'edgenode-b815' has joined the cluster 'default' for more than one day.

**How To Reproduce**
1. Go to edge node 'edgenode-b815'
2. Click on 'Monitoring'
3. Select Time Range 'Last 1 day'

**Expected behavior**
The interface returns the monitoring data of the latest day

**Actual behavior**

![image](https://user-images.githubusercontent.com/68640256/111937566-f5810180-8b02-11eb-8bbf-a3b14575108a.png)

/priority high
/kind bug
/assign @zhu733756 
/milestone 3.1.0

**Comment by zhu733756** [comment]
Currently，we only support real-time  metrics for edge node .  Range queries will be supported in later versions

**Comment by zryfish** [comment]
@leoendless  Can we hide the range query for edge nodes?

**Comment by harrisonliu5** [comment]
The current edge node monitoring indicator can only monitor the usage of CPU and memory. The function is duplicated with other tags, so I will be deleted it

**Comment by wenxin-01** [comment]
The monitor tab in edge node detail was removed.
