### ISSUE TITLE
The 'upload icon' text  is not centered

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3534]
**Describe the Bug**

The 'upload icon' text  is not centered
![image](https://user-images.githubusercontent.com/36271543/111937720-5577a800-8b03-11eb-922b-68951c45440c.png)

/kind bug
/assign @leoendless
/priority Low
/milestone 3.1.0
/area console

**Comment by leoendless** [comment]
By desgin.
