### ISSUE TITLE
前端UI开源，配备仅paas层的安装脚本

### ISSUE THREAD

**Issue by huapox** [kubesphere/kubesphere#354]
1.求对前端也做开源；
2.具备让大家可以自行安装于现成k8s的脚本，不少用户有现成的集群并有定制，不需要配备一整套的AllInOne；

综上，大家能更好的玩转并反馈，进而推进项目的迭代~ 谢谢！

**Comment by cnicy** [comment]
同求前端！

**Comment by firheroicths** [comment]
WEB UI初始的用户名密码是多少？  admin/admin 用户名密码错误

**Comment by calvinyv** [comment]
#290 duplicated
