### ISSUE TITLE
misplaced typography on App Store Management/App Review page

### ISSUE THREAD

**Issue by yuswift** [kubesphere/kubesphere#3541]
**Describe the Bug**

https://user-images.githubusercontent.com/37265389/111950711-a1cfe180-8b1d-11eb-8fb7-c3163948d4b0.mov

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: latest
**How To Reproduce**
1. Click on 'App Store Management/App Review'
2. Choose an application
3. See the misplaced typography, if not, choose a workspace then go back to the page.

**Expected behavior**
The typography should not be misplaced.

**Comment by zryfish** [comment]
Does this issue still exist on your env? I can't reproduce it. @yuswift

**Comment by yuswift** [comment]
> Does this issue still exist on your env? I can't reproduce it. @yuswift

Me neither. Maybe it has been fixed.
/close
