### ISSUE TITLE
Consumption bill doesn't consistent when changing Time Interval

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/kubesphere#3542]
**Describe the Bug**
In the 'Consumption History' tab,  the Total Consumption was changed when changing Time Interval

**Versions Used**
KubeSphere: nightly-20210315
Kubernetes: 1.19.0

**How To Reproduce**
1. Click the 'Toolbox' icon and open ' Metering and Billing' 
2. Select a cluster and Check the 'Consumption History'
3. In the 'Consumption History' change the default 'Time Interval' from 1 hour to 4 hours.
4. Compare the Total Consumption for each Resource Type, those values are different.

**Expected behavior**
Total Consumption should be consistent whenever changes Time Interval.

/kind bug 
/assign @yunkunrao 
/priority High
/milestone 3.1.0

**Comment by yunkunrao** [comment]
This issue was fixed.

**Comment by zryfish** [comment]
> This issue was fixed.

Please paste PR link here

**Comment by yunkunrao** [comment]
> > This issue was fixed.
> 
> Please paste PR link here

Got it.

**Comment by yunkunrao** [comment]
This issue was fixed with PR: https://github.com/KubeSphereCloud/ks-store/pull/87

**Comment by RolandMa1986** [comment]
Verified
/close
