### ISSUE TITLE
Suggestion:  batch stop workloads

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#3544]
**What's it about?**

When I need to batch stop (scale replicas to 0) workloads, the operation is inconvenient. I suggest adding a stop button here.

![image](https://user-images.githubusercontent.com/8263040/111970996-dd2ada00-8b36-11eb-8b2e-414c3fa37958.png)

/area console
/kind feature-request

**Comment by nanjofan** [comment]
Does this need to modify the backend?

**Comment by wansir** [comment]
Supported by front-end.

**Comment by mangoGoForward** [comment]
I found that ks-apiserver only forward request to k8s to stop workload, so I only commit a PR in console. @wansir

**Comment by wenxin-01** [comment]
We only support to batch stop deployment in the cluster details for now.
In my opition, we should support bath stop workload(deployment,statefulsets,daemonets) in project details and cluster details. https://github.com/kubesphere/console/issues/3349
![image](https://user-images.githubusercontent.com/68640256/172280032-81fdb991-419f-41e3-a6ba-c5fa39457e33.png)
