### ISSUE TITLE
Cannot import cluster via agent

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/kubesphere#3545]
**Describe the Bug**

![image](https://user-images.githubusercontent.com/20178386/111972303-4828e080-8b38-11eb-877c-abb24f5e0265.png)

cannot import cluster via agent.

/assign @leoendless 
/kind multicluster
/priority high

**Comment by yuswift** [comment]
Tested this case and found it passed through. Please reopen this issue if there are problems while imports clusters via agent.
/close
