### ISSUE TITLE
Applications published via the application template cannot be viewed in the App Store

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3552]
**Describe the Bug**
**steps:**
1. Publish the app to the App Store in the App Template
2. Goto the App Store, view the published app in step 1

**Expected results:**
can view the published application in the app store

**Actual results:**
Cannot see the published application in the app store

![image](https://user-images.githubusercontent.com/36271543/112089914-815f6000-8bcd-11eb-9509-cf8c2140c062.png)

/kind bug
/assign @xyz-li 
/priority High
/milestone 3.1.0
/area app-management

**Comment by xyz-li** [comment]
#3551

**Comment by liuyp2018** [comment]
Verified, and fixed

**Comment by liuyp2018** [comment]
Verified, and fixed
