### ISSUE TITLE
Unable to modify notification settings in console

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/kubesphere#3555]
**Describe the Bug**
In platform settings -> Notification Management -> DingTalk

Enter a Secret, then click Update.

![Screen Shot 2021-03-23 at 2 43 56 PM](https://user-images.githubusercontent.com/70880165/112105222-1884e180-8be7-11eb-969e-7b5bbb9f6460.png)
![Screen Shot 2021-03-23 at 2 44 37 PM](https://user-images.githubusercontent.com/70880165/112105251-1f135900-8be7-11eb-83bf-1292eeed4a65.png)
![Screen Shot 2021-03-23 at 2 44 41 PM](https://user-images.githubusercontent.com/70880165/112105254-20448600-8be7-11eb-938d-ba5d456b629b.png)

**Versions Used**
KubeSphere: 3.1 (nightly-20210321)

/area notification
/kind bug
/assign @kubesphere/sig-observability
/milestone 3.1.0

**Comment by stoneshi-yunify** [comment]
And why there is a tiny dash `-` in each Conversation ID?

![Screen Shot 2021-03-23 at 2 59 41 PM](https://user-images.githubusercontent.com/70880165/112106338-8087f780-8be8-11eb-976d-f294205873d7.png)

**Comment by wanjunlei** [comment]
> And why there is a tiny dash `-` in each Conversation ID?
> 
> ![Screen Shot 2021-03-23 at 2 59 41 PM](https://user-images.githubusercontent.com/70880165/112106338-8087f780-8be8-11eb-976d-f294205873d7.png)

/assign @xuliwenwenwen

**Comment by wanjunlei** [comment]
> **Describe the Bug**
> In platform settings -> Notification Management -> DingTalk
> 
> Enter a Secret, then click Update.
> 
> ![Screen Shot 2021-03-23 at 2 43 56 PM](https://user-images.githubusercontent.com/70880165/112105222-1884e180-8be7-11eb-969e-7b5bbb9f6460.png)
> ![Screen Shot 2021-03-23 at 2 44 37 PM](https://user-images.githubusercontent.com/70880165/112105251-1f135900-8be7-11eb-83bf-1292eeed4a65.png)
> ![Screen Shot 2021-03-23 at 2 44 41 PM](https://user-images.githubusercontent.com/70880165/112105254-20448600-8be7-11eb-938d-ba5d456b629b.png)
> 
> **Versions Used**
> KubeSphere: 3.1 (nightly-20210321)
> 
> /area notification
> /kind bug
> /assign @kubesphere/sig-observability
> /milestone 3.1.0

It is a bug #3527

**Comment by wanjunlei** [comment]
It will be fixed in kubesphere/ks-installer#1350

**Comment by stoneshi-yunify** [comment]
retested and passed with nightly-20210330
