### ISSUE TITLE
The name of the application template is incorrect on the application review page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3556]
**Describe the Bug**

**steps:**
1. In the application template detail page, change the name of the application template
2. Select the version of the application under the application template and submit it for review
3. Enter the App Store -- >the Application Review page, view the name of the application template in the Application Review list

**Expected results:**
In the Application Review list, the name of the application template is the modified name

**Actual results:**
In the Application Review list, the name of the application template is the same as before the change

![image](https://user-images.githubusercontent.com/36271543/112112493-90a3d500-8bf0-11eb-9c8e-5bdd70504098.png)

/kind bug
/assign @xyz-li
/priority Medium
/milestone 3.1.0
/area app-management

**Comment by wansir** [comment]
Related to https://github.com/kubesphere/kubesphere/issues/3551

**Comment by liuyp2018** [comment]
Verified, and fixed
