### ISSUE TITLE
[Metering and Billing] Can't change cluster for system-workspace workspace

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/kubesphere#3557]
**Describe the Bug**
When multi cluster enabled, I can only view the 'system-workspace' Bill on host cluster，can't switch to member clusters.

**How To Reproduce**
1. Enable Multi-cluster feature on KubeSphere, and add one member cluster.
2. Click on 'Toolbox' and open ' Metering and Billing'
3. View Workspace (project) resource consumption 
4.  Select `system-workspace` 
Can't switch clusters on the Consumption Bill page.

**Expected behavior**
I can switch clusters and view Bills for all "system-workspace"

/assign @yunkunrao @harrisonliu5

**Comment by harrisonliu5** [comment]
[kubesphere/console/1705](https://github.com/kubesphere/console/pull/1705)

**Comment by RolandMa1986** [comment]
verfied
/close
