### ISSUE TITLE
 version information is not displayed in app details page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3562]
**Describe the Bug**

**steps:**
1. Deploy the application through the application template
2. After the application is deployed, enter the details page of the deployed application
3. View the version of the resource

**expected results:**
Can display version  information

**Actual results:**
No version information is displayed

![image](https://user-images.githubusercontent.com/36271543/112126616-96ed7d80-8bff-11eb-8d59-a06bffb70663.png)

/kind bug
/assign @xyz-li
/priority Medium
/milestone 3.1.0
/area app-management

**Comment by xyz-li** [comment]
Only deployment has version info.
