### ISSUE TITLE
Edit template function is not active

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3563]
**Describe the Bug**
1. Go to the deployed application details page
2. After editing the number of copies applied in the template, save the operation

**Expected results:**
The number of replicas of the workload in the application will change

**Actual results:**
The number of replicas has not changed

![image](https://user-images.githubusercontent.com/36271543/112132104-33664e80-8c05-11eb-8ce4-a33d88138670.png)

/kind bug
/assign @xyz-li
/priority High
/milestone 3.1.0
/area app-management

**Comment by xyz-li** [comment]
@leoendless

**Comment by liuyp2018** [comment]
/reopen
Unable to change successfully when changing to the default configuration

**Comment by zheng1** [comment]
Verified

/close
