### ISSUE TITLE
http://x.x.x.x:30880/clusters/default/monitor-cluster/ranking page is blank

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3565]
**Describe the Bug**

From http://x.x.x.x:30880/clusters/default/overview click View More button，then you'll get a blank page "http://x.x.x.x:30880/clusters/default/monitor-cluster/ranking"

**Versions Used**
KubeSphere: nightly-20210322
Kubernetes: 1.18.14

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

![image](https://user-images.githubusercontent.com/18692628/112262166-2b131f80-8ca8-11eb-8844-5808d53f76fc.png)

**Comment by zryfish** [comment]
Should be fixed now, you can verify it using v3.1.0 after tomorrow

**Comment by daniel-hutao** [comment]
ok

**Comment by daniel-hutao** [comment]
It has been fixed at v3.1.0
