### ISSUE TITLE
kubesphere 开源组件 和 部署组件的对应关系

### ISSUE THREAD

**Issue by Liuyanglong** [kubesphere/kubesphere#357]
你好：
我部署了 kubesphere adv 1.01，将他与 此repo中的组件做对比发现，有些不对应，想请教下两者之间的关系。

adv 1.01中的组件有：ks-console，ks-apiserver，ks-apigateway，ks-account，ks-devops
此repo的make 组件有：ks-apiserver，ks-apigateway ，ks-iam，controller-manager

这两者间的区别和联系是什么？

**Comment by calvinyv** [comment]
@zryfish

**Comment by zryfish** [comment]
ks-console 是 kubesphere 的 dashboard 项目，目前正在整理源代码，即将放到 github
ks-devops 代码在 1.0.1 版本中是单独 repo ，2.0 中会合并到 kubesphere 的 repo 中来
controller-manager 是 kubesphere 的controller模块， 属于 2.0 中新增的模块
