### ISSUE TITLE
'Net Received' and 'Net Transmitted' are incorrect in Consumption History

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3573]
**Environment**
http://192.168.18.71:30880/

**How To Reproduce**
1. Go to 'Toolbox'
2. Click on ' Metering and Billing'
3. Click on 'view consumptiob' in Cluster resource consumption
4. Select a time range of 1 day

**Expected behavior**

**Actual behavior**
![image](https://user-images.githubusercontent.com/68640256/112279863-59502980-8cbf-11eb-8b43-4079be6bfbbe.png)

/priority medium
/kind bug
/assign @yunkunrao 
/milestone 3.1.0

**Comment by yunkunrao** [comment]
This issue was fixed.

**Comment by wenxin-01** [comment]
issue fixed
