### ISSUE TITLE
In the exported data, the start time is wrong

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3578]
**Environment**
http://192.168.18.71:30880/

**How To Reproduce**
1. Go to 'toolboox'
2. Click on 'view consumption' in Cluster resource consumption
3. Select a time range of one day  and The interval  select one day
4. Select the cluster and export  data

**Expected behavior**
The time range is displayed correctly in export data

**Actual behavior**
![image](https://user-images.githubusercontent.com/68640256/112414925-e5b12980-8d5d-11eb-8cfc-7f4e95c67bbe.png)

/priority medium
/kind bug
/assign @yunkunrao
/milestone 3.1.0

**Comment by yunkunrao** [comment]
This issue was fixed.

**Comment by wenxin-01** [comment]
issue fixed
