### ISSUE TITLE
3.0.0 member cluster should not show sa related pages

### ISSUE THREAD

**Issue by duanjiong** [kubesphere/kubesphere#3579]
**Describe the Bug**
3.0.0 member cluster should not show sa related pages

![image](https://user-images.githubusercontent.com/3678855/112417918-7b02ec80-8d63-11eb-8fcd-17c43a8c214c.png)

**Versions Used**
KubeSphere: 3.1.0
Member KubeSphere: 3.0.0
Kubernetes:  v1.17.9

**Environment**

**How To Reproduce**

**Expected behavior**
3.0.0 member cluster should not show sa related pages

**Comment by duanjiong** [comment]
same in project    
![image](https://user-images.githubusercontent.com/3678855/112440950-de057b00-8d85-11eb-84e5-03497b0af4aa.png)

**Comment by wansir** [comment]
Duplicated https://github.com/kubesphere/kubesphere/issues/3664

/close
