### ISSUE TITLE
Can not get pipeline status of multicluster devops

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/kubesphere#3580]
**Describe the Bug**

KubeSphere Host 3.1  Member 3.0

Can not get pipeline status of multicluster devops

![image](https://user-images.githubusercontent.com/20178386/112418016-a685d700-8d63-11eb-982c-87e40f4272cf.png)

/priority low
/cc @kubesphere/sig-devops 
/kind bug

**Comment by LinuxSuRen** [comment]
hi @zackzhangkai, which cluster does this Pipeline come from? A host or a member cluster?
