### ISSUE TITLE
3.0.0 member cluster should not show custom-monitoring related pages

### ISSUE THREAD

**Issue by duanjiong** [kubesphere/kubesphere#3582]
**Describe the Bug**
3.0.0 member cluster should not show custom-monitoring related pages
![image](https://user-images.githubusercontent.com/3678855/112431325-52d2b800-8d7a-11eb-8829-25ed6938324e.png)

**Versions Used**
Host KubeSphere: v3.1.0
Member Kuberspher: v3.0.0 minimal
Kubernetes: v1.17.9

**Expected behavior**
3.0.0 member cluster should not show custom-monitoring related pages

**Comment by zryfish** [comment]
duplicate https://github.com/kubesphere/kubesphere/issues/3664

**Comment by benjaminhuo** [comment]
Global custom monitoring menu should not be shown in v3.0 while namespace custom monitoring should be available in v3.0 @leoendless @junotx
