### ISSUE TITLE
3.0.0 member cluster kube-federation-system should be system project

### ISSUE THREAD

**Issue by duanjiong** [kubesphere/kubesphere#3583]
**Describe the Bug**
3.0.0 member cluster kube-federation-system should be system project

![image](https://user-images.githubusercontent.com/3678855/112433298-0046cb00-8d7d-11eb-8099-c4603301ac84.png)

**Versions Used**
KubeSphere: 3.1.0
Member KubeSphere: 3.0.0
Kubernetes:  v1.17.9

**Environment**

**How To Reproduce**

**Expected behavior**
3.0.0 member cluster kube-federation-system should be system project

**Comment by yuswift** [comment]
The namespace is labeled when the cluster is created. Need to check the installer code.
