### ISSUE TITLE
[Metering and Billing] Workspace Permission is not accurate

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/kubesphere#3585]
**Describe the Bug**
When a user is assigned to a custom-defined workspace role, the user can't see the workspace 'Consumption Bill'. But users that assigned to a workspace-regular role can view Consumption Bill. This is unconvincing because workspace-regular don't have any authorization too.
**Versions Used**
KubeSphere: dev
Kubernetes: (If KubeSphere installer used, you can skip this)

**How To Reproduce**
1. Select an existing workspace and go to 'Workspace Roles', 
2. Create a new Role with user manager permission.
3. Invite a user to the workspace and as the role defined above.
4. login with the user and open 'Metering and Billing', nothing shows there.

**Expected behavior**
There are some possibles solutions:
1. As an invited user, the user should be able to see Consumption Bill as same as workspace-regular
2. Create a new permission for Consumption Bill . only specific user with the permission can the it.
3. ...

/kind bug
/priority Low
/milestone 3.1.0
/assign @yunkunrao

**Comment by yunkunrao** [comment]
This issue was fixed by https://github.com/kubesphere/ks-installer/pull/1371

**Comment by RolandMa1986** [comment]
@yunkunrao  What's the "Expected behavior" for the issue?
