### ISSUE TITLE
How to deal with the timeout of installation 3.1?

### ISSUE THREAD

**Issue by yinmin2020** [kubesphere/kubesphere#3599]
Deploy 3.1 on the virtual machine and follow the steps to download and execute the KK script. Automated deployment at this stage will get stuck and then report an incorrect KubeSphere installation timeout
POD is all normal

![image](https://user-images.githubusercontent.com/65068467/112597114-aa8b2500-8e47-11eb-9bba-e66d7dd3a3b3.png)
![image](https://user-images.githubusercontent.com/65068467/112597139-b4148d00-8e47-11eb-924e-05cda199aab9.png)
![image](https://user-images.githubusercontent.com/65068467/112597150-b7a81400-8e47-11eb-9063-07608547e9b9.png)

**Comment by yuswift** [comment]
What command dia you execute? It should be `kk create cluster --with-kubesphere nightly-0325` and so on. Check your installer image tag.

**Comment by yinmin2020** [comment]
> 您执行什么命令？应该`kk create cluster --with-kubesphere nightly-0325`如此等等。检查您的安装程序映像标签。

 I'm executing  ./kk create cluster --with-kubesphere nightly-20210208

**Comment by yinmin2020** [comment]
> 您执行什么命令？应该`kk create cluster --with-kubesphere nightly-0325`如此等等。检查您的安装程序映像标签。

Execute your command to report the following error, YAML is not written missing
![image](https://user-images.githubusercontent.com/65068467/112603989-a8799400-8e50-11eb-9bc3-c16f651f986d.png)
![image](https://user-images.githubusercontent.com/65068467/112604072-bb8c6400-8e50-11eb-91fc-5c40b600cd78.png)

**Comment by yinmin2020** [comment]
> 您执行什么命令？应该`kk create cluster --with-kubesphere nightly-0325`如此等等。检查您的安装程序映像标签。
What is the correct command to install KK? After using your command there is now a pull failure (-0325 mirror). The image is not available
![image](https://user-images.githubusercontent.com/65068467/112613393-001cfd00-8e5b-11eb-9dcd-4b4016494446.png)

**Comment by yuswift** [comment]
Please execute `kk version` to find out which version you are using.

**Comment by yinmin2020** [comment]
> 请执行`kk version`以找出您使用的版本。

How to get the latest kk execution file？Is this the address below?
https://github.com/kubesphere/kubekey/issues/473
