### ISSUE TITLE
The consumption information of the same pod in Cluster and WorkSpace is inconsistent.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3601]
**Environment**
http://192.168.18.71:30880/

**How To Reproduce**
1. Go to 'toolbox'
2. Click on 'Metering and Billing'
3. View consumption information of pod ‘A’ through cluster entrance
4. View consumption information of pod ‘A’ through WorkSpace entrance

**Expected behavior**
The consumption data of pod 'A' in the two ways are consistent

**Actual behavior**
![image](https://user-images.githubusercontent.com/68640256/112601592-99ddad80-8e4d-11eb-83a2-d19967b3b52e.png)

![image](https://user-images.githubusercontent.com/68640256/112601614-9fd38e80-8e4d-11eb-889b-cc9c4f35f4ad.png)

/priority high
/kind bug
/assign @yunkunrao
/milestone 3.1.0

**Comment by yunkunrao** [comment]
This issue was fixed.

**Comment by wenxin-01** [comment]
issue fixed
