### ISSUE TITLE
he result of the query by status is incorrect in the list of storage snapshots

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3603]
**Describe the Bug**
**steps:**
1. In the volume snapshot list
2. Select the 'creating' status to query

**problem:**
The query results contain snapshots with failed status

![image](https://user-images.githubusercontent.com/36271543/112608631-83d3eb00-8e55-11eb-9534-14e3aa4431eb.png)

/kind bug
/assign @stoneshi-yunify 
/priority Medium
/milestone 3.1.0
/area storage

**Comment by stoneshi-yunify** [comment]
There is no `creating unsuccessfully` status, as the creating will be retried endless, so `creating unsuccessfully` is `creating`.

There are 3 valid status for a snapshot:
```go
	statusCreating = "creating"
	statusReady    = "ready"
	statusDeleting = "deleting"
```

please change frontend code accordingly. thanks.

/assign @xuliwenwenwen
