### ISSUE TITLE
modifying configuration action did not take effect when deploying application

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3604]
**Describe the Bug**
**steps:**
1. When the application is deployed, modify the configuration file
2. Remove the health check Settings: ReadInessProbe and LivenessProbe
3. After deploying the application, review the configuration file for the application's workload

**Expected results:**
There are no health check items in the workload's configuration file

**Actual results:**
There are health check items in the workload's configuration file

![image](https://user-images.githubusercontent.com/36271543/112613672-525e1e00-8e5b-11eb-9291-605738c9ae87.png)
![image](https://user-images.githubusercontent.com/36271543/112613811-7cafdb80-8e5b-11eb-8059-dadac30f4e44.png)

/kind bug
/assign @xyz-li
/priority High
/milestone 3.1.0
/area app-management

**Comment by xyz-li** [comment]
/wontfix
 https://helm.sh/docs/chart_template_guide/values_files/
/close
