### ISSUE TITLE
page 404 - https://v3-0.docs.kubesphere.io/docs/project-administration/project-members/

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3605]
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: latest
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

![image](https://user-images.githubusercontent.com/18692628/112614351-21cab400-8e5c-11eb-9a6f-cfb17038261c.png)

**Comment by Sherlock113** [comment]
This issue was just fixed in https://github.com/kubesphere/console/pull/1692. Need verification.

**Comment by FeynmanZhou** [comment]
@daniel-hutao Please help to verify it, thanks.

**Comment by daniel-hutao** [comment]
I'll verify it after v3.1.0 released

**Comment by daniel-hutao** [comment]
It has been fixed.
