### ISSUE TITLE
UI Config the image repository username not support Chinese 

### ISSUE THREAD

**Issue by zengzhengrong** [kubesphere/kubesphere#3607]
It's not very common use  Chinese ， but use command "docker login --username=中文" is ok

![a1f47454f1fb7fd27b466094a735c26](https://user-images.githubusercontent.com/23110784/112709361-da900200-8ef3-11eb-96fd-962e13454897.png)

I  use command docker login and export configjson  and base64 to generate yaml solve it

**Comment by RolandMa1986** [comment]
/close 
It was fixed in v3.1.0  by 
https://github.com/kubesphere/console/pull/1247
