### ISSUE TITLE
3.1 Platform information display error, display 3.0.0

### ISSUE THREAD

**Issue by yinmin2020** [kubesphere/kubesphere#3608]
After installing 3.1, it is found that the platform version is still 3.0. Please confirm the repair. Thank you
![image](https://user-images.githubusercontent.com/65068467/112709927-4d9b7780-8ef8-11eb-9fa6-431ddfcdc8ce.png)
![image](https://user-images.githubusercontent.com/65068467/112709932-5b50fd00-8ef8-11eb-947b-c36d4d52100f.png)

**Comment by LinuxSuRen** [comment]
3.1 is not released yet. So it's not accurate to display 3.1. I guess you installed a nightly build version. In this case, it can be like this: `3.0.0-nightly-2021-xx-xx`.

If you or other people want to improve this, please checkout [ks-installer](https://github.com/kubesphere/ks-installer).

/help
/kind bug
/priority low
