### ISSUE TITLE
The accuracy of amount data needs to be optimized.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3610]
**Environment**
http://192.168.18.71:30880

**How To Reproduce**
Memory Consumption:   
sum_value: 23776596377.374 bytes = 23776596377.374/1024/1024/1024 GI =22.143680953769014 Gi
amount:  22.144 * 5 = `110.72`    Actual amount  = `110.50`

Net Received Consumption:
sum_value: 20968671262.640923 bytes =20968671262.640923/1024/1024 M = 19997.28323234646 M 
amount : 19997.283  * 1  = `19997.28`  Actual amount = `19997`

Net Transmitted Consumption:
sum_value: 5791040870.384695 bytes = 5791040870.384695/1024/1024 M = 5522.766943344779 M
amount：5522.767 * 1 = `5522.77`    Actual amount = `5523`

**Expected behavior**
The amount is accurate to two decimal places

**Actual behavior**

![image](https://user-images.githubusercontent.com/68640256/112745397-bb1fd480-8fda-11eb-896c-8fbb116f9ed3.png)

![image](https://user-images.githubusercontent.com/68640256/112745415-cd017780-8fda-11eb-86da-b2487d56d3cb.png)

/priority medium
/kind bug
/assign @yunkunrao
/milestone 3.1.0

**Expected behavior**

**Comment by yunkunrao** [comment]
OK, got it. Metering will keep 2 decimal places for fee caculation.

**Comment by wenxin-01** [comment]
issue fixed. 
The amount returned by back-end retains three decimal places
