### ISSUE TITLE
Helm Template changes not reflect to App Store ( eg. new screenshot ) 

### ISSUE THREAD

**Issue by WaysonWei** [kubesphere/kubesphere#3611]
Kubesphere v3.1.0 ( nightly-20210327)

1. )All helm template now has new url as http://192.168.122.150:30880/apps/app-id-store, but all new changes only reflect to url http://192.168.122.150:30880/apps/app-id, such as new screenshot added after the app released. 

2.)User can now access the screenshot in app store without login, but the [close] button not working in this mode, is working ok if you login to app store. 

<img width="2559" alt="Screen Shot 2021-03-28 at 8 53 52 PM" src="https://user-images.githubusercontent.com/54336863/112745860-f2f14100-9007-11eb-8f97-726b82a622b8.png">
<img width="2559" alt="Screen Shot 2021-03-28 at 8 55 03 PM" src="https://user-images.githubusercontent.com/54336863/112745868-fab0e580-9007-11eb-9ea9-bdafefe62382.png">
<img width="1314" alt="Screen Shot 2021-03-28 at 8 43 02 PM" src="https://user-images.githubusercontent.com/54336863/112745877-02708a00-9008-11eb-95ba-60a34f0e5b1e.png">

**Comment by xyz-li** [comment]
> 1. )All helm template now has new url as http://192.168.122.150:30880/apps/app-id-store, but all new changes only reflect to url http://192.168.122.150:30880/apps/app-id, such as new screenshot added after the app released.
1. It's designed to act like this. If you want to see new changes, you must publish new app version.

> 2.)User can now access the screenshot in app store without login, but the [close] button not working in this mode, is working ok if you login to app store.
2. What is you web browser.

**Comment by WaysonWei** [comment]
1. ok, I got it. Need to upload new version of helm package, right ?
2. Google Chrome Version 89 ( Still not about to click the [close] button in the nightly-20210331 build , same result with Firefox and Safari latest version )

**Comment by xyz-li** [comment]
> 1. ok, I got it. Need to upload new version of helm package, right ?
1.  Release a new version
![image](https://user-images.githubusercontent.com/6263928/113251727-6095b980-92f5-11eb-9c2e-0f46a3c04db9.png)

2.   First Susspend App, then Activate App.
![image](https://user-images.githubusercontent.com/6263928/113251769-70ad9900-92f5-11eb-9257-1010361a734e.png)
