### ISSUE TITLE
the associated service is not deleted when deleting the app in multi-cluster project

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3614]
**Describe the Bug**

**steps:**
1. In a multi-clustered project, create a homemade application
2. when finish created, delete the application
3. View the services associated with the application in the services list

**expected results:**
The associated service is deleted synchronously

**actual results:**
The associated service is not deleted

![image](https://user-images.githubusercontent.com/36271543/112785068-bf54fc00-9085-11eb-9f80-e70ebc4a48c7.png)

/kind bug
/assign @xyz-li 
/priority High
/milestone 3.1.0
/area app-management

**Comment by yuswift** [comment]
The svc should be deleted by the application controller. However, it will be recreated by kubefed sync controller because it is created by kubefed sync controller. Currently, we don't have a better solution.
