### ISSUE TITLE
The namespace weave does not belong to any workspace after topology is enabled

### ISSUE THREAD

**Issue by Sherlock113** [kubesphere/kubesphere#3618]
**Describe the Bug**
After you enable Service topology, the namespace `weave` will be created but it does not belong to any workspace on KubeSphere.

![Xnip2021-03-29_14-01-34](https://user-images.githubusercontent.com/65327072/112793145-54142580-9097-11eb-8d47-5524771727b1.png)

**Versions Used**
KubeSphere: v3.1.0
Kubernetes: 1.17.9

**Comment by duanjiong** [comment]
/kind need-to-verify
fixed in https://github.com/kubesphere/ks-installer/pull/1363

**Comment by liuyp2018** [comment]
verfied and fixed in v3.1.1-rc.1
