### ISSUE TITLE
The standard for computing CPU and memory at pod and node levels are inconsistent.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3619]
**Environment**
http://192.168.18.71:30880

**How To Reproduce**

**Expected behavior**
The same standard should be used to calculate CPU and memory consumption at pod and node levels.

**Actual behavior**
CPU and memory are calculated at pod level based on `requests`.
CPU and memory are calculated at the node level based on `actual usage`.

/priority high
/kind bug
/assign @yunkunrao
/milestone 3.1.0

**Comment by yunkunrao** [comment]
This issue was fixed.

**Comment by wenxin-01** [comment]
I hope it can be fixed in a later version

/priority low

**Comment by zheng1** [comment]
As expected
/close
