### ISSUE TITLE
Threshold can be Negative value when add alerting policy

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/kubesphere#3624]
**Describe the Bug**
Negative value can be input in Threshold when add alerting policy

**Versions Used**
KubeSphere: kubespheredev/ks-console:nightly-20210328

**How To Reproduce**
1. Go to 'Alerting Policies' and Click ’Create‘
2. Input alerting policy's Name and click 'Next'
3. Select one target on Monitoring Target.
4. Choice ' CPU Load average 1 minute' and input '-1 ' in Threshold textbox
5. Click next and create the police.
![altering validition](https://user-images.githubusercontent.com/1720333/112803474-e4f1fd80-90a5-11eb-9852-82d506d7378d.png)

**Expected behavior**
Only positive number can be inputed in the Threshold textbox

/area console
/area alerting
/kind bug
/priority low
/assign @leoendless

**Comment by fuchunlan** [comment]
This problem has been fixed in the new version, please check it in the new version, thanks.
