### ISSUE TITLE
安装2.0 all-in-one 出错

### ISSUE THREAD

**Issue by monkito** [kubesphere/kubesphere#363]
**General remarks**

> Please delete this section including header before submitting
> 也可以使用中文
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug(描述下问题)**

安装2.0，选择all-in-one，无论是使用本地存储，还是配置NFS （qingcloud vNAS），安装过程中均报错如下：

fatal: [ks-allinone]: FAILED! => {"attempts": 4, "changed": true, "cmd": ["/usr/bin/docker", "pull", "kubespheredev/devops:flyway"], "delta": "0:00:04.161648", "end": "2019-04-25 11:35:05.791355", "msg": "non-zero return code", "rc": 1, "start": "2019-04-25 11:35:01.629707", "stderr": "Error response from daemon: pull access denied for kubespheredev/devops, repository does not exist or may require 'docker login'", "stderr_lines": ["Error response from daemon: pull access denied for kubespheredev/devops, repository does not exist or may require 'docker login'"], "stdout": "", "stdout_lines": []}

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

vm 8c16g100g，centos 7.5

**Comment by pixiake** [comment]
你好   可以到官网获取最新的安装包连接下载安装
