### ISSUE TITLE
Without any cluster info in the workspace which was created before it became federation cluster 

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/kubesphere#3631]
**Describe the Bug**
I have a workspace in a regular KubeSphere cluster. I can create DevOps projects inside. But I cannot do it after I turned the cluster to a federation cluster as a host cluster. You can see it from the screenshot below:

![image](https://user-images.githubusercontent.com/1450685/112919170-1f58aa80-9139-11eb-8a63-cacc97cf1598.png)

I have tried to set the cluster-info for the workspace. But it seems that KubeSphere does not support it.

/priority high
/area multicluster

**Versions Used**
KubeSphere: `nightly-20210328`

**Environment**
This might not be an environmental issue.

**How To Reproduce**
1. Create a regular KubeSphere cluster
2. Create a workspace
3. Create some Pipelines in a workspace
4. Turn the cluster to a federation cluster according to this [guide](https://kubesphere.com.cn/en/docs/multicluster-management/introduction/overview/)
5. Check the exiting workspace

**Expected behavior**
The existing workspace should be avaible.

**Comment by wansir** [comment]
By design, after the cluster role changes, you need to reset the visibility of the workspace.
