### ISSUE TITLE
Message information is not displayed in the application repository event page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3636]
**Describe the Bug**

Message information is not displayed in the application repository event page
![image](https://user-images.githubusercontent.com/36271543/112940379-a91b6e80-915f-11eb-9799-3eed600a3a96.png)

and the creator is not displayed:
![image](https://user-images.githubusercontent.com/36271543/112941783-bb96a780-9161-11eb-903e-6d42b529c325.png)

/kind bug
/assign @xyz-li 
/priority Medium
/milestone 3.1.0
/area app-management

**Comment by liuyp2018** [comment]
The message bar in the list is always empty. 
Suggestion: shows the operation information in the message bar 
/reopen

**Comment by zheng1** [comment]
![截屏2021-04-08 16 50 30](https://user-images.githubusercontent.com/4156721/113997272-8f2e0a00-988a-11eb-96c1-5c153149d673.png)


Verified. The message is `-` because the sync status is success. If sync failed, this message will be verbose.

/close
