### ISSUE TITLE
the applications deployed under the project are not deleted when the project is deleted

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3637]
**Describe the Bug**
After the project is deleted, the applications deployed under the project are not deleted

After deleting the project p1, see the application under the project still exists:
![image](https://user-images.githubusercontent.com/36271543/112940624-f992cc00-915f-11eb-9ba3-c1f4fdbb017f.png)

/kind bug
/assign @xyz-li 
/priority High
/milestone 3.1.0
/area app-management

**Comment by zheng1** [comment]
This behavior is as expected and is retained for now in version 3.1.0. We'll optimize it in the next version

/milestone Backlog
