### ISSUE TITLE
Unable to view status and reason for deployed failure in the detail page of the application template

### ISSUE THREAD

**Issue by zheng1** [kubesphere/kubesphere#3646]
**Describe the Bug**
Unable to view status and reason for deployed failure in the detail page of the application template

![截屏2021-03-30 21 26 15](https://user-images.githubusercontent.com/4156721/112996349-adb34780-919e-11eb-8437-5d25991fe899.png)
![截屏2021-03-30 21 26 09](https://user-images.githubusercontent.com/4156721/112996352-aee47480-919e-11eb-9051-7418188cff51.png)

**Versions Used**
KubeSphere: v3.0.0-nightly-20210329

/kind bug
/assign @leoendless 
/priority High
/milestone 3.1.0
/area app-management

**Comment by xyz-li** [comment]
Add `app.kubesphere.io/instance` and `app.kubesphere.io/name` labels to helm resources.
