### ISSUE TITLE
After creating the application template, the list page is not automatically updated

### ISSUE THREAD

**Issue by zheng1** [kubesphere/kubesphere#3647]
**Describe the Bug**
After creating the application template, the list page is not automatically updated

https://user-images.githubusercontent.com/4156721/112997002-4a75e500-919f-11eb-9f98-dbdf9c01e603.mov

**Versions Used**
KubeSphere: v3.0.0-nightly-20210329

/kind bug
/assign @leoendless 
/priority High
/milestone 3.1.0
/area app-management

**Comment by harrisonliu5** [comment]
ws://localhost:8000/apis/application.kubesphere.io/v1alpha1/watch/helmreleases?labelSelector=kubesphere.io/cluster=member-01,kubesphere.io/namespace=pro

should check the websocket api
