### ISSUE TITLE
You cannot edit a policy that has deleted monitoring target in the policy details page

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3649]
**Versions Used**
KubeSphere:  `dev:latest`

**Environment**
http://139.198.9.112:30883

**How To Reproduce**
1. Go to workspace 'ws2'
2. Go to project  'pro'
3. Add alerting policy 'role-test'
4. delete monitoring target of policy 'role-test'
5. Enter the policy details page 
6. edit policy 'role-test'

**Expected behavior**
Edited successfully

**Actual behavior**
can not edit

![image](https://user-images.githubusercontent.com/68640256/113082762-9fe8db00-920d-11eb-94e6-48c70346253d.png)

/priority medium
/assign @junotx 
/kind bug
/milestone 3.1.0

**Comment by wenxin-01** [comment]
> /kind need-to-verify

issue has not been fixed in `kubesphere v3.1.1-rc.0`

**Comment by fuchunlan** [comment]
> > /kind need-to-verify
> 
> issue has not been fixed in `kubesphere v3.1.1-rc.0`

[kubesphere/console#1971](https://github.com/kubesphere/console/pull/1971) had been left out before，I added `/cherrypick release-3.1` 5 hours ago

**Comment by wenxin-01** [comment]
issue fixed `v3.1.1-rc.1`
