### ISSUE TITLE
the alert resource is not displayed on the page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3657]
**Describe the Bug**
Alert rules created using the template, In the alert message list, the alert resource is not displayed on the page
![image](https://user-images.githubusercontent.com/36271543/113124224-de9b8700-9247-11eb-9618-401b5a736aa8.png)

![image](https://user-images.githubusercontent.com/36271543/113123770-72b91e80-9247-11eb-9e60-4c9a359f59ad.png)

/kind bug
/assign @leoendless 
/priority Medium
/milestone 3.1.0
/area console
/area alerting

**Comment by leoendless** [comment]
If the alarm rule is created by template, the monitoring target cannot be obtained. Is there any way to get the monitoring target from the backend? @junotx

**Comment by junotx** [comment]
The targets may be parsed from the annotations of the alert mesage for templated rules. I can see them in the cluster-level alert messages but not in the namespace-level ones. @leoendless 

- alert messages with cluster level
![image](https://user-images.githubusercontent.com/49136171/113256311-976ece00-92fb-11eb-881b-8a49c102f9d6.png)
- alert messages with namespace level
![image](https://user-images.githubusercontent.com/49136171/113257116-b91c8500-92fc-11eb-8768-66587ac6d2d6.png)

**Comment by liuyp2018** [comment]
fixed
