### ISSUE TITLE
需要一个How to build or How to start developing....文档

### ISSUE THREAD

**Issue by guofengzh** [kubesphere/kubesphere#366]
想build一下kubeshpere。docs/中”Welcome to KubeSphere! (New Developer Guide)“好像还未完成。试了”Developing for KubeSphere **[deprecated]**“, 使用”go get -d kubesphere.io/kubesphere"找不到工程。试着clone，然后make，好像也不行。调整一下目录，使用make all构建时，源码的编译好像OK了，又出现下列错误:
failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: exec format error
kubebuilder的版本是 1.0.8. 怎么解决？

多谢!

**Comment by calvinyv** [comment]
代码还在整理中，我们争取在五月底整理出这个howto文档，人手有限，非常抱歉

**Comment by cnicy** [comment]
@calvinyv 2.0什么时间点回开源

**Comment by calvinyv** [comment]
暂时没有一个非常确定的时间点，我们会非常努力的往2019年3Q去努力，由于没有专门的开源团队，所有开源工作都是同事们个人时间去处理，进度较慢，望见谅
