### ISSUE TITLE
Failed to create multi cluster project

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3660]
**Environment**
`host 3.1 + member 3.1 + member 3.0`

http://139.198.9.112:30883

**How To Reproduce**
1. Go to worksapce 'ws3'
2. Click on 'project'
3. create Multi-cluster Project 'multi-pro1' with cluster 'member-01'(ks 3.1) and 'member-02' (ks 3.0)
4. Go to detail page of project 'multi-pro1'

**Expected behavior**
The project information is displayed correctly

**Actual behavior**
see error "namespaces "multi-pro1" not found"
use `kubectl get ns` in  'member-01' and 'member-02' did not found namespce 'multi-pro1'

![image](https://user-images.githubusercontent.com/68640256/113131508-e52dfc80-924f-11eb-9beb-5995fae56093.png)

/priority high
/kind bug
/assign @zryfish 
/milestone 3.1.0

**Comment by yuswift** [comment]
This bug is caused by kubefed sync controller and ks ns controller. It has been solved here. #3654 
Please update the environment to the latest to test if it has been solved.

**Comment by wenxin-01** [comment]
issue fixed
