### ISSUE TITLE
problem summary in host3.1 + member3.0 environment

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3664]
**Environment**
host cluster: kubesphere v3.1
member cluster: kubesphere v3.0

1. 404 error occurred on the alert policy and alert message page in v3.0 member cluster:
![image](https://user-images.githubusercontent.com/36271543/113235992-98413900-92d6-11eb-8ae3-caf1cb61a547.png)

2. The kubectl command tool could not connect to the v3.0 member cluster
![image](https://user-images.githubusercontent.com/36271543/113255668-ad2fc380-92fa-11eb-867f-7240740d8a18.png)

3.In v3.0 member cluster, 404 error occurred for editing quotas for workspace
![image](https://user-images.githubusercontent.com/36271543/113255759-c9cbfb80-92fa-11eb-8c54-5ff722b65b7c.png)

4. In v3.0 member cluster, the custom monitoring page reports error
![image](https://user-images.githubusercontent.com/36271543/113255958-11eb1e00-92fb-11eb-8db6-0f9ed3d3d403.png)

5. In v3.0 member cluster, the service account page reports error
![image](https://user-images.githubusercontent.com/36271543/113256102-4959ca80-92fb-11eb-94fa-aac6b499988b.png)

6. The department binds the project to the DevOps role. When saved, 404 error is reported
![image](https://user-images.githubusercontent.com/36271543/113263256-1ec03f80-9304-11eb-9d33-604fd08b2549.png)

/kind bug
/assign @leoendless
/priority High
/milestone 3.1.0
/area console
/area alerting

**Comment by yuswift** [comment]
- [ ] command tool bug #3665

**Comment by liuyp2018** [comment]
/remove-kind need-to-verify

When selecting the DevOps project role in a user group, no upgrade prompt is given
![image](https://user-images.githubusercontent.com/36271543/114985759-c2dde500-9ec5-11eb-9f9c-f6a7bfe40f1f.png)
