### ISSUE TITLE
The kubectl command tool could not connect to the member3.0 cluster

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3665]
**Environment**
host cluster: kubesphere v3.1
member cluster: kubesphere v3.0

**How To Reproduce**
1. Deploy a cluster with Host3.1 + Member 3.0 environment
2. Open the kubectl command line tool and connect to the member3.0 cluster
3. The kubectl command line tool could not connect to the member3.0 cluster

![image](https://user-images.githubusercontent.com/36271543/113236879-5a451480-92d8-11eb-93fd-30661480afaf.png)

/kind bug
/assign @yuswift 
/priority High
/milestone 3.1.0
/area multicluster

**Comment by yuswift** [comment]
/retitle The kubectl command tool could not connect to the member3.0 cluster

**Comment by yuswift** [comment]
/close
This issue has been merged into this one #3664

**Comment by wansir** [comment]
Work in progress, need to automatically switch API according to KubeSphere version.

/assign @leoendless

**Comment by liuyp2018** [comment]
fixed
/close
