### ISSUE TITLE
In member3.0, 404 error occurred when editing quotas for workspace

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3669]
**Environment**
host cluster: kubesphere v3.1
member cluster: kubesphere v3.0

**How To Reproduce**
1.Deploy a cluster with Host3.1 + Member 3.0 environment
2.In Member3.0, 404 error occurred for editing quotas

![image](https://user-images.githubusercontent.com/36271543/113253262-9471de80-92f7-11eb-91be-b1c776b539b6.png)

/kind bug
/assign @leoendless 
/priority High
/milestone 3.1.0
/area multicluster
/area console

**Comment by zryfish** [comment]
@liuyp2018 I can verify this issue fixed in my env, can you help verify it?

**Comment by liuyp2018** [comment]
fixed
/close
