### ISSUE TITLE
After the application is deleted, the associated application route is not deleted

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3672]
**Environment**

**How To Reproduce**
1. After deploying a homemade app
2. Add application routes
3. Delete the application
4. View the application routes associated with the application

**Expected results:**
The associated application route is deleted

**Actual results:**
The associated application route is not deleted

![image](https://user-images.githubusercontent.com/36271543/113273892-aa8b9900-930f-11eb-888e-314cb50680eb.png)

/priority medium
/kind bug
/assign @zackzhangkai 
/milestone 3.1.0

**Comment by zackzhangkai** [comment]
The problem cannot be repeated. Test some times, it's still OK.
