### ISSUE TITLE
Some CRD cannot be deleted bu kubepshere-delete.sh

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3678]
**Describe the Bug**

The CRD "helmcategories.application.kubesphere.io" and "workspacetemplates.tenant.kubesphere.io" cannot be deleted by kubepshere-delete.sh for "finalizers" reasons.

**Versions Used**
KubeSphere: latest version at 2021/04/02
Kubernetes: 1.18.14

**Environment**

**How To Reproduce**
1. Install ks by ks-installer
2. Delete the cluster by kubesphere-delete.sh

**Expected behavior**

/kind bug
@kubesphere/sig-installation

**Comment by xyz-li** [comment]
kind/need-to-verify
