### ISSUE TITLE
Failed to view the information of member-cluster in 'Log Search'、'Event Search' and ' Auditing Operating'

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3681]
**Environment**
`host 3.1 + member3.1 + member3.0 `

http://139.198.9.112:30883

**How To Reproduce**
1. Go to  'Toolbox'
2. Click on 'Log Search'
3. select cluster 'member-01' or 'member-02'

**Actual behavior**
![image](https://user-images.githubusercontent.com/68640256/113387670-5c35d300-93bf-11eb-8d68-19d2008fd0aa.png)

![image](https://user-images.githubusercontent.com/68640256/113388719-54772e00-93c1-11eb-816b-1b62e828cfd3.png)

![image](https://user-images.githubusercontent.com/68640256/113388686-46291200-93c1-11eb-9049-0937e46610ee.png)

/priority high
/area logging 
/kind bug
/assign @junotx 
/milestone 3.1.0

**Comment by benjaminhuo** [comment]
/assign @wanjunlei 
@wanjunlei Pls help to take a look at this

**Comment by wanjunlei** [comment]
The es in the member cluster is not ready.

![image](https://user-images.githubusercontent.com/53003665/113672318-2740bd80-96ea-11eb-9682-9b5fea082f5e.png)
