### ISSUE TITLE
proposal: use multi-stage build and docker buildx to produce multi-arch images

### ISSUE THREAD

**Issue by lxm** [kubesphere/kubesphere#3683]
currently, docker images are built after `make`, which only produces x86 binary.

use multi-stage dockerfile can be convenient to build multi arch images if base images already support multi arch

currently, most base images such as nodejs/golang/ubuntu etc... have already support multi arch

**Comment by zryfish** [comment]
Yeah, we are planning that too. Could you please give more details on how we are going to do it? Maybe we can break down to smaller work items, so others can help.

**Comment by lxm** [comment]
Change dockerfile to mulit-stage, use golang:tag as "builder" to build binary
When import external projects such as helm, use a bash script to get the binary which should judge the platform of cpu
then use `docker buildx --platform` to build expected images

**Comment by yuswift** [comment]
But not when building images under the local environment, not every user has docker buildx tools.

**Comment by lxm** [comment]
> But when building images under the local environment, not every user has docker buildx tools.

maybe we need a build target like `make dev`

**Comment by zryfish** [comment]
I think we should follow the way which K8s community did. They've built cross platform images using their own image `kube-cross`, https://github.com/kubernetes/kubernetes/blob/master/hack/build-cross.sh.  So we can build local platform image as usual, but there is a build target, for example `make cross` to build images for all supported platforms.

**Comment by lxm** [comment]
> I think we should follow the way which K8s community did. They've built cross platform images using their own image `kube-cross`, https://github.com/kubernetes/kubernetes/blob/master/hack/build-cross.sh. So we can build local platform image as usual, but there is a build target, for example `make cross` to build images for all supported platforms.


Do we need such a complicated way. currently, github actions config is  necessary for building. If truns to build in a container, all confs could list in the dockerfile, such as  FROM `golang:1.13` instead of 
```
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
        id: go
```

**Comment by zryfish** [comment]
Yeah, that's not easy. But how are you going to do? Can you provide more details, or is there any draft PR?

**Comment by lxm** [comment]
> Yeah, that's not easy. But how are you going to do? Can you provide more details, or is there any draft PR?

Going to make a example and a draft PR

**Comment by yuswift** [comment]
https://github.com/kubesphere/kubesphere/pull/3704 has been merged
/close
