### ISSUE TITLE
The quota value displayed on the workspace quota page is incorrect

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3684]
**Environment**
multi-cluster enviroment:
host cluster: v3.1
member cluster: v3.1

**How To Reproduce**
1. In a multi-clustered environment
2. Enter a multi-cluster (Host Cluster + Member Cluster) workspace -->quota management page
3. Sets quota management for the Host Cluster
4. Set quota management for member cluster , and the quota is different from the host cluster
5. Click the 'Quota Management' button of Member Cluster again to enter the Quota Management page of Member Cluster
6. See the page for quota Settings

**Expected results:**
The quota value is the same as that of the Member Cluster

**Actual results:**
The quota value is the same as the quota for the host cluster

![image](https://user-images.githubusercontent.com/36271543/113391457-22b49600-93c6-11eb-905c-5f7c93903551.png)

/kind bug
/assign @leoendless
/priority Low
/milestone 3.1.0
/area console

**Comment by harrisonliu5** [comment]
Maybe the API return  404. @liuyp2018 

![image](https://user-images.githubusercontent.com/17872673/129657743-1a70c1ee-996d-4c96-9393-bf4d6d80d347.png)
