### ISSUE TITLE
missing the edit and delete buttons for the service monitoring exporter

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3685]
missing the edit and delete buttons for the service monitoring exporter
![image](https://user-images.githubusercontent.com/36271543/113396965-ef2a3980-93ce-11eb-9dcf-8fe0cc424daf.png)

/kind bug
/assign @leoendless
/priority Medium
/milestone 3.1.0
/area console

**Comment by fuchunlan** [comment]
There is a button  'More'  on the left of the page，do we still need to add edit and delete buttons to each card module?
![image](https://user-images.githubusercontent.com/63338728/118254896-26b3f780-b4de-11eb-8c47-651606774cdb.png)

**Comment by liuyp2018** [comment]
> There is a button 'More' on the left of the page，do we still need to add edit and delete buttons to each card module?
> ![image](https://user-images.githubusercontent.com/63338728/118254896-26b3f780-b4de-11eb-8c47-651606774cdb.png)

the edit and delete buttons for the service monitoring exporter, not for the service

**Comment by fuchunlan** [comment]
> > There is a button 'More' on the left of the page，do we still need to add edit and delete buttons to each card module?
> > ![image](https://user-images.githubusercontent.com/63338728/118254896-26b3f780-b4de-11eb-8c47-651606774cdb.png)
> 
> the edit and delete buttons for the service monitoring exporter, not for the service


![image](https://user-images.githubusercontent.com/63338728/119633280-2869ad80-be44-11eb-80b6-45b0f0d08cfb.png)
Click 'Service Monitoring Exporter' , we can edit for it, now the operation of right module is all in the 'More' button.

**Comment by zryfish** [comment]
@liuyp2018  I think the above comment from @fuchunlan  would help to export service metrics now.  I will close this issue but feel free to reopen if it doesn't.

/close
