### ISSUE TITLE
on the create deployment page, does not display quota prompt information for all clusters

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3689]
**Environment**
multi-cluster:
host clustere : v 3.1
member cluster: v 3.1

**steps:**
1. there exists a multi-cluster workspace 'm-ws', and the workspace quota information for the Host and Membere clusters is set
2. there exists a multi-cluster project 'm-ws' under workspace 'm-ws', and the project quota information for host and member clusters is set
3. enter project 'm-p', create Deployment, and on the create page, view the quota prompt

Expected results:
The quota information for the host cluster and member is displayed

Actual results:
Only the quota information for the Host cluster is displayed

![image](https://user-images.githubusercontent.com/36271543/113676688-57d72600-96ef-11eb-818b-747d3b40c51e.png)

/kind bug
/assign @leoendless 
/priority Medium
/milestone 3.1.0
/area console

**Comment by zryfish** [comment]
Quota information removed when creating multicluster deployment, I think we can close this issue now.
