### ISSUE TITLE
[Bug] The log display order is not correct in kubesphere logging system 

### ISSUE THREAD

**Issue by ItGeneral** [kubesphere/kubesphere#3693]
1、banner log display dislocation
![image](https://user-images.githubusercontent.com/15844190/113830133-dea40580-97b8-11eb-8d2d-b4dd14ffdf59.png)

the correct log should be：
![image](https://user-images.githubusercontent.com/15844190/113830185-efed1200-97b8-11eb-962e-40399f174cfa.png)

2、The log display order is not correct
![image](https://user-images.githubusercontent.com/15844190/113830265-07c49600-97b9-11eb-8bf6-1d25ae5807ee.png)

the correct order should be：
![image](https://user-images.githubusercontent.com/15844190/113830309-13b05800-97b9-11eb-93e9-a6b62d3ae036.png)

**Comment by FeynmanZhou** [comment]
cc @kubesphere/sig-observability

**Comment by wanjunlei** [comment]
This is a bug of fluent bit.
https://github.com/fluent/fluent-bit/issues/1746
https://github.com/fluent/fluent-bit/pull/2777

You can try the fluent bit 0f v1.6.9.
```
kubectl edit fluentbits.logging.kubesphere.io -n kubesphere-logging-system fluent-bit
```
change the image to kubesephere/fluent-bit:v1.6.9

**Comment by zryfish** [comment]
> This is a bug of fluent bit.
> [fluent/fluent-bit#1746](https://github.com/fluent/fluent-bit/issues/1746)
> [fluent/fluent-bit#2777](https://github.com/fluent/fluent-bit/pull/2777)
> 
> You can try the fluent bit 0f v1.6.9.
> 
> ```
> kubectl edit fluentbits.logging.kubesphere.io -n kubesphere-logging-system fluent-bit
> ```
> 
> change the image to kubesephere/fluent-bit:v1.6.9

@ItGeneral Does this help?
