### ISSUE TITLE
when changing the alarm rule of the alarm policy, cannot receive the notification after the alarm is triggered

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3695]
**Environment**
ks v3.1

**How To Reproduce**
1. Create a alert policy with a alert rule for CPU utilization
2. Wait until the alarm policy triggers the alarm
3. Change the alert rule of the alert policy to available memory
4. Wait until the alert policy reaches the trigger condition, and the alert policy's state changes to trigger
5. Check the alert notification 

**Expected results:**
can receive the alert notification 

**Actual results:**
No alert notification received

/kind bug
/assign @junotx 
/priority High
/milestone 3.1.0
/area alerting

**Comment by benjaminhuo** [comment]
@liuyp2018 This should have been fixed

**Comment by liuyp2018** [comment]
verified, and fixed
/close
