### ISSUE TITLE
components status display

### ISSUE THREAD

**Issue by littlebeer2100** [kubesphere/kubesphere#37]
For now, in  kubesphere and k8s system,components are follow table   

| name | kind | namespace | label |
|---|---|----|----|
| kubectl | Deployment | default | k8s-app = kubectl |
| openpitrix | Deployment | default | app = openpitrix |
| iam | Deployment | default | run = iam |
| heapster | Deployment | kube-system | k8s-app = heapster |
| kibana-logging | Deployment | kube-system | k8s-app = kibana-logging |
| kube-dns | Deployment | kube-system | k8s-app = kube-dns |
| kube-state-metrics | Deployment | kube-system | k8s-app =kube-state-metrics |
| kubectl | Deployment | kube-system | k8s-app = kubectl |
| kubectl2| Deployment | kube-system | k8s-app = kubectl |
| kubernetes-dashboard | Deployment | kube-system | k8s-app = kubernetes-dashboard |
| kubespherebackend | Deployment | kube-system | k8s-app = kubespherebackend |
| kubesphereui | Deployment | kube-system | k8s-app = kubesphereui |
| metrics-server | Deployment | kube-system | k8s-app = metrics-server |
| monitoring-grafana | Deployment | kube-system | k8s-app = monitoring-grafana |
| monitoring-influxdb | Deployment | kube-system | k8s-app = monitoring-influxdb |
| cloud-controller-manager | Pod | kube-system | tier=control-plane |
| kube-apiserver | Pod | kube-system | tier=control-plane |
| etcd | Pod | kube-system | tier=control-plane |
| kube-controller | Pod | kube-system | tier=control-plane |
| qingcloud-volume-provisioner | Pod | kube-system | tier=control-plane |
| kube-proxy | Pod | kube-system | k8s-app = kube-proxy |

1. is there any component not appropriate?  
1. k8s api provided is GET /api/v1/componentstatuses,but it only return

**Comment by calvinyv** [comment]
1. why there are 3 kubectl comp? @richardxz 
2. storage/network plugin will be changed based on customer's installation
3. kube-state-metrics, monitoring-grafana are not necessary
4. kubesphere,openpitrix,iam should be under another namespace
5. kube-apiserver is also not necessary, because if you can get this list, it means api server is already working...
6. etcd may be outside of cluster, and deploy as etcd cluster

**Comment by littlebeer2100** [comment]
the item 2, if the storage/network plugins are  dynamic, is there some mark for developer recognition them?
