### ISSUE TITLE
The data for the exception node is not displayed correctly

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3700]
In the edge node, the data of the abnormal node is not displayed correctly
![image](https://user-images.githubusercontent.com/36271543/113965818-a8ba5c00-9860-11eb-8cf4-dd25b0c4a300.png)

/kind bug
/assign @leoendless 
/priority Medium
/milestone 3.1.0
/area edge
/area console

**Comment by zhu733756** [comment]
@liuyp2018 I see the edge node occured a error, the Internet connection cannot be reached. So the edge node metrics would be incorrect.

**Comment by zryfish** [comment]
So it's expected then, not a bug? If we can confirm it's not a bug, close the issue.
