### ISSUE TITLE
After deleting workspace, Multi-cluster Projects are not deleted.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3705]
**Environment**
http://139.198.9.112:30883

**How To Reproduce**
1. Go to 'Workspaces'
2. Create a workspace named 'test'
3. Create a multi-cluster project 'multi-test' in workspace 'test'
4. delete workspace 'test'
5. Create a workspace named 'test'

**Expected behavior**
There are no resources in workspace 'test'

**Actual behavior**
Multi-cluster Projects 'multi-test' in  workspace 'test'

`This problem also exists in version 3.0`

/priority high
/kind bug
/assign @yuswift 
/milestone 3.1.0

**Comment by wansir** [comment]
Related to https://github.com/kubesphere/kubesphere/pull/3667

/cc @leoendless

**Comment by zryfish** [comment]
@wansir  Any update on this issue?

**Comment by yuswift** [comment]
Could we close this issue?

**Comment by yuswift** [comment]
@wenxin-01

**Comment by wenxin-01** [comment]
issue fixed
