### ISSUE TITLE
Enable KubeEdge in a KubeSphere cluster on GCP

### ISSUE THREAD

**Issue by Sherlock113** [kubesphere/kubesphere#3707]
**Describe the Bug**

When you enable KubeEdge, the default download link of `keadm` is a QingStor link. This could cause trouble to GCP users as Google instances have trouble downloading QingStor links. See this [pr](https://github.com/kubesphere/website/pull/1331#discussion_r609519765). They need to manually create a ConfigMap and change the `region` field or customize the download link.

/cc @kubesphere/sig-edge

**Comment by zhu733756** [comment]
@harrisonliu5 @Sherlock113 we need to confirm what parameters can be selected. The optional parameters are region, download url, arch, and so on. Howerver, we can edit configmap `edge-watcher-config`  to modify it as a option.

**Comment by Sherlock113** [comment]
I just tested that the link https://kubeedge.pek3b.qingstor.com/bin/v1.6.1/x86_64/keadm-v1.6.1-linux-x86_64.tar.gz is accessible from GCP. It is slow, but it can be downloaded anyway....
