### ISSUE TITLE
An error was reported when installing 3.0

### ISSUE THREAD

**Issue by pcclvv** [kubesphere/kubesphere#3713]
> install v3.0.0
![image](https://user-images.githubusercontent.com/38095532/114132943-d7573600-9937-11eb-8e05-7e08220d228f.png)
![image](https://user-images.githubusercontent.com/38095532/114158762-a7b82600-9957-11eb-952f-43aa3fb69da9.png)

An error was reported when installing 3.0

**Comment by pcclvv** [comment]
ClusterIP limits the port range

**Comment by JohnNiang** [comment]
Please provide `kubernetes-controller-manager` command info, especially `--service-node-port-range` configuration.

**Comment by pcclvv** [comment]
> 请提供`kubernetes-controller-manager`命令信息，尤其是`--service-node-port-range`配置。

![image](https://user-images.githubusercontent.com/38095532/114328437-3783ed00-9b6f-11eb-94a2-311d670d308c.png)
80-30000

**Comment by zryfish** [comment]
It's your custom node-port-range, kubernetes default nodeport range is `30000-32676`, you need to set another range to keep `30880` in that range. Maybe `80-32676`
