### ISSUE TITLE
Some features are disabled after the upgrade

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3716]
**Environment**
Single node cluster

After upgrading from KS3.0 to KS3.1, check alert policy, alert message, service account, quota management module.
These modules cannot be used normally, and it prompt 'the current cluster version cannot use this function, please upgrade to V3.1.0 or above version.'

![image](https://user-images.githubusercontent.com/36271543/114492655-8e5ef480-9c4b-11eb-9e4a-aa736825cef4.png)
![image](https://user-images.githubusercontent.com/36271543/114492680-9d45a700-9c4b-11eb-84d8-2347f5b52329.png)
![image](https://user-images.githubusercontent.com/36271543/114492700-a8003c00-9c4b-11eb-86db-e39b880d02a8.png)

/priority high
/kind bug
/milestone 3.1.0
/assign @leoendless

**Comment by zhu733756** [comment]
@liuyp2018  The latest back-end image was released, the issue solved
