### ISSUE TITLE
Redirected to an invalid url when click Service Provider Website on APP Review Content page

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/kubesphere#3720]
**Describe the Bug**
On the `Review Content` page, there's a filed **Service Provider Website** that uses to link to the website. however, it was redirected to an internal page when I click it. 

**Versions Used**
KubeSphere: nightly-20210413

**How To Reproduce**
1. Create a new App Template under workspace1
2. Edit the App Information, and fill in _Service Provider Website_
3. Submit a new Review request
4. Go to the App Reviews page, and view the newly created Review request.
5. Click the Website link, it was redirected to an internal page.

![20210413172721](https://user-images.githubusercontent.com/1720333/114530501-8fa91500-9c7d-11eb-837b-7d139e7e64e3.png)

**Expected behavior**

/kind bug
/priority low
/milestone 3.1.0
/area app-management
/area console

**Comment by harrisonliu5** [comment]
Currently, if there is no URL starting with HTTP or HTTPS, the default is the route within the site. 
Whether to add HTTP or HTTPS when editing？
