### ISSUE TITLE
Multiple default storage classes can be set in the cluster.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3729]
**Environment**
http://139.198.121.240:30881/
`host 3.1 + member 3.0`

**Expected behavior**
Only one default storage class is allowed in a Kubernetes cluster.

**Actual behavior**
![image](https://user-images.githubusercontent.com/68640256/114675604-03f5be00-9d3b-11eb-980a-c36aa2d24e3a.png)

/priority high
/assign @stoneshi-yunify 
/kind bug
/milestone 3.1.0

**Comment by stoneshi-yunify** [comment]
Kubernetes allows multiple default storage classes (it's determined by an annotation), so this is not a bug.

Kubesphere console does not allow you to set multiple default storage classes. But we can not restrict user to do this by cli. If user set multiple default classes by cli, then in KS console you will see multiple default classes, which is working as expected.

/close
