### ISSUE TITLE
The link in 'Storage Classes' is not accessible

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3730]
**Actual behavior**
![image](https://user-images.githubusercontent.com/68640256/114676672-18868600-9d3c-11eb-93b1-12da373d0d64.png)
![image](https://user-images.githubusercontent.com/68640256/114676689-20462a80-9d3c-11eb-8a7a-af4c242d341a.png)

/priority medium
/assign @stoneshi-yunify
/kind bug
/milestone 3.1.0

**Comment by stoneshi-yunify** [comment]
/assign @xuliwenwenwen 

The link is wrong, the correct link is https://v3-1.docs.kubesphere.io/docs/cluster-administration/persistent-volume-and-storage-class/
