### ISSUE TITLE
Images which need to be synced to repo `kubesphere`

### ISSUE THREAD

**Issue by zryfish** [kubesphere/kubesphere#3737]
Please leave comments on images that are required by release v3.1.0 like the following format.  `source location` -> `destination location`

- [ ] `kubespheredev/ks-apiserver:nightly-20210413` -> `kubesphere/ks-apiserver:v3.1.0`

/milestone 3.1.0

The following images have been pushed to `kubesphere` already
```
kubespheredev/s2ioperator:v3.1.0 kubesphere/s2ioperator:v3.1.0
kubespheredev/ks-jenkins:2.249.1 kubesphere/ks-jenkins:2.249.1
kubespheredev/openpitrix-jobs:v3.1.0 kubesphere/openpitrix-jobs:v3.1.0
kubespheredev/notification-manager-operator:v1.0.0 kubesphere/notification-manager-operator:v1.0.0
kubespheredev/notification-manager:v1.0.0 kubesphere/notification-manager:v1.0.0
kubespheredev/fluentbit-operator:v0.5.0 kubesphere/fluentbit-operator:v0.5.0
kubespheredev/fluent-bit:v1.6.9 kubesphere/fluent-bit:v1.6.9
kubespheredev/thanos:v0.18.0 kubesphere/thanos:v0.18.0
kubespheredev/ks-alerting-migration:v3.1.0 kubesphere/ks-alerting-migration:v3.1.0
```

**Comment by shaowenchen** [comment]
- [ ] kubespheredev/s2ioperator -> kubesphere/s2ioperator

tag is v3.1.0

**Comment by LinuxSuRen** [comment]
DevOps related images:

* [ ] `kubespheredev/ks-jenkins:2.249.1` -> `kubesphere/ks-jenkins:2.249.1`

**Comment by zheng1** [comment]
- [ ] kubespheredev/openpitrix-jobs:v3.1.0 -> kubesphere/openpitrix-jobs:v3.1.0

**Comment by yuswift** [comment]
- [ ] kubespheredev/tower:0.2.0 -> kubesphere/tower:v0.2.0

**Comment by wanjunlei** [comment]
kubespheredev/notification-manager-operator:v1.0.0 -> kubesphere/notification-manager-operator:v1.0.0
kubespheredev/notification-manager:v1.0.0 -> kubesphere/notification-manager-operator:v1.0.0

**Comment by wanjunlei** [comment]
kubespheredev/fluentbit-operator:v0.5.0 -> kubesphere/fluentbit-operator:v0.5.0
kubespheredev/fluent-bit:v1.6.9 -> kubesphere/fluent-bit:v1.6.9

**Comment by junotx** [comment]
- [ ] kubespheredev/thanos:v0.18.0 -> kubesphere/thanos:v0.18.0

**Comment by zhu733756** [comment]
kubespheredev/edge-watcher-agent:v0.1.0 => kubesphere/edge-watcher-agent:v0.1.0
kubespheredev/edge-watcher:v0.1.0 => kubesphere/edge-watcher:v0.1.0
