### ISSUE TITLE
Images with Critical Vulnerability need to be updated

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/kubesphere#3740]
**Describe the Bug**
There are some Docker images that are still using older base images. Which may container Vulnerabilities, all images with critical (high) vulnerabilities should be fixed.

**Versions Used**
KubeSphere: lastest

/kind bug
/milestone 3.1.0
@zryfish

**Comment by LinuxSuRen** [comment]
We need to scan the vulnerabilities regularly. I will do that later. But I guess we might have not enough time to do that before the coming release.

**Comment by RolandMa1986** [comment]
- [ ]  kubesphere/kube-rbac-proxy:v0.4.1 CRITICAL: 2 
- [ ] xyzli/openpitrix-jobs:latest  CRITICAL: 2 
- [ ] kubespheredev/fluent-bit:v1.6.9 High 11 (optional)
- [ ] kubespheredev/tower:latest High 4 (optional)
- [ ] kubesphere/kubectl:v1.0.0 High 21 (optional)
- [ ] kubesphere/kube-events-exporter:v0.1.0 (optional)
@xyz-li @wanjunlei @yuswift 
Please help to check those images

**Comment by zryfish** [comment]
> * [ ]   kubesphere/kube-rbac-proxy:v0.4.1 CRITICAL: 2
> * [ ]  xyzli/openpitrix-jobs:latest  CRITICAL: 2
> * [ ]   osixia/openldap:1.3.0 CRITICAL: 6
> * [ ]  kubespheredev/fluent-bit:v1.6.9 High 11 (optional)
> * [ ]  kubespheredev/tower:latest High 4 (optional)
> * [ ]  kubesphere/kubectl:v1.0.0 High 21 (optional)
> * [ ]  kubesphere/kube-events-exporter:v0.1.0 (optional)
> 
> @xyz-li @wanjunlei @yuswift
> Please help to check those images

Can you also describe how do you find these vulnerabilities, the tool you use?

**Comment by RolandMa1986** [comment]
For a single image scan task, the Trivy /docker scan(docker desktop only) can be used to detect vulnerabilities.
Ubuntu:
`trivy i -s HIGH,CRITICAL osixia/openldap:1.5.0`

Mac/Window 
`docker scan osixia/openldap:1.5.0`

**Comment by yuswift** [comment]
Most of the vulnerabilities can be fixed by changing the base image.

**Comment by RolandMa1986** [comment]
osixia/openldap:1.3.0  was removed from the list. Because there are no official fixes for many of the issues in the base image(Debian), and we are going to remove LDAP dependencies in the next release. It's not necessary to change to another docker image.

**Comment by zryfish** [comment]
I'll this issue as resolved for release v3.1.0

**Comment by yuswift** [comment]
> I'll this issue as resolved for release v3.1.0

 `kubespheredev/fluent-bit:v1.6.9 High 11 (optional)`
 `kubesphere/kube-events-exporter:v0.1.0 (optional)`
 Those images havn't been updated.

**Comment by zryfish** [comment]
I think we can close the issue currently since the remaining unfixed images are optional, but feel free to reopen later if we gain enough feedback on this.

/close
