### ISSUE TITLE
platform user can not set notification settings

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/kubesphere#3749]
ks 3.1 host + member

1. In the host, create a role, grant it with platform privileges.
2. create a user, binding to the role.
3. Login to the host, go to the notification, and this error occurs.

![image](https://user-images.githubusercontent.com/20178386/114964918-3968eb80-9ea2-11eb-8cbe-4d8323415da1.png)

/priority high

**Comment by zackzhangkai** [comment]
same errors in member cluster.
/kind bug

**Comment by wenxin-01** [comment]
issue fixed https://github.com/kubesphere/kubesphere/issues/3771
