### ISSUE TITLE
The Monitoring component upgrade failed from KSV3.0 to KSV3.1

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3751]
**Versions Used**
kubesphere v3.0
The Monitoring component is enabled

**How To Reproduce**
1. Upgrade the cluster to KS v3.1

**Expected behavior**
All components were successfully upgraded

**actual results**
The Monitoring component upgrade failed 

![image](https://user-images.githubusercontent.com/36271543/114970734-91f1b600-9ead-11eb-9485-d468cfe975f4.png)

![image](https://user-images.githubusercontent.com/36271543/114970695-7c7c8c00-9ead-11eb-8260-6278e78bcefb.png)

/priority high
/kind bug
/milestone 3.1.0
/assign @junotx

**Comment by liuyp2018** [comment]
fixed
/close

**Comment by Kucing121** [comment]
#hasbiallah
