### ISSUE TITLE
Summary of bugs when creating custom alarm policies

### ISSUE THREAD

**Issue by yuswift** [kubesphere/kubesphere#3755]
**Describe the Bug**
Console doesn't verify the alarm duration input

https://user-images.githubusercontent.com/37265389/115011986-d9923500-9ee1-11eb-9dab-52ac1f68b920.mov

Console doesn't verify the `cpu average load(1m 5m 15m)` input

https://user-images.githubusercontent.com/37265389/115148510-857a8280-a092-11eb-9545-39fce9465c47.mov

Console doesn't verify the `iops` input

https://user-images.githubusercontent.com/37265389/115148643-1f422f80-a093-11eb-8638-c95067592eee.mov

When creating custom alarm policies under a project, console doesn't verify the `alarm duration` input nneither.

https://user-images.githubusercontent.com/37265389/115148896-1b62dd00-a094-11eb-8c3c-3e2b5351db94.mov

**Versions Used**
KubeSphere:latest

**Expected behavior**
`alert duration/cpu average load(1m 5m 15m)/iops`  should only be negative numbers.

**Comment by yuswift** [comment]
/retitle Summary of bugs when creating custom alarm policies

**Comment by fuchunlan** [comment]
@yuswift 
![image](https://user-images.githubusercontent.com/63338728/121638890-4bd85d80-cabe-11eb-884d-f0f74d1f1d4a.png)
Are these values only negative or can't be negative?

**Comment by yuswift** [comment]
> t

They can't be negative.

**Comment by yuswift** [comment]
> @yuswift
> ![image](https://user-images.githubusercontent.com/63338728/121638890-4bd85d80-cabe-11eb-884d-f0f74d1f1d4a.png)
> Are these values only negative or can't be negative?

They can't be negative.

**Comment by yuswift** [comment]
fixed
/close
