### ISSUE TITLE
how to refresh  api token like oauth2 token instead of getting token each time

### ISSUE THREAD

**Issue by zousheng** [kubesphere/kubesphere#3757]
HI,
I am using kubesphere api to manage k8s resources and stuck in the api token management, the document only mentioned how to generate token, but doens't mention how to refresh, it would be better if token management document is added.

Could you help with an example?

**Comment by FeynmanZhou** [comment]
cc @kubesphere/sig-docs

**Comment by yuswift** [comment]
> HI,
> I am using kubesphere api to manage k8s resources and stuck in the api token management, the document only mentioned how to generate token, but doens't mention how to refresh, it would be better if token management document is added.
> 
> Could you help with an example?

The API also returns a `refresh_token` field.

**Comment by zousheng** [comment]
> > HI,
> > I am using kubesphere api to manage k8s resources and stuck in the api token management, the document only mentioned how to generate token, but doens't mention how to refresh, it would be better if token management document is added.
> > Could you help with an example?
> 
> The API also returns a `refresh_token` field.

Yes, but I am still confused how to use it with kubesphere api, is there any guide ?

  I read Oauth2.0 go client, in which refresh token can be used to refresh token automaticall, no need to call it explicitly.

**Comment by wansir** [comment]
https://tools.ietf.org/html/rfc6749#page-47

```
     POST /oauth/token HTTP/1.1
     Host: ks-apiserver.kubesphere-system.svc
     Content-Type: application/x-www-form-urlencoded

     grant_type=refresh_token&refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwidG9rZW5fdHlwZSI6InJlZnJlc2hfdG9rZW4iLCJleHAiOjE2MTg4MDUwMzQsImlhdCI6MTYxODc5OTYzNCwiaXNzIjoia3ViZXNwaGVyZSIsIm5iZiI6MTYxODc5OTYzNH0.pz85fhlZUo8FfFjbGMcKj_jM7tvPrL6WaGkZD-InXxI

```

**Comment by yuswift** [comment]
/close
feel free to reopen this issue if have any questions
