### ISSUE TITLE
Invalidate token instead of returning 404 after upgrading to latest from v3.0.0

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/kubesphere#3758]
**Describe the Bug**

Invalidate token instead of returning 404 after upgrading to latest from v3.0.0

After upgrading kubesphere to latest, index page will show as follow:

![image](https://user-images.githubusercontent.com/16865714/115150667-fc684900-a09b-11eb-8b86-332ab80096c4.png)

However, it will return to normal when I open index page in private window or clear coolie(token field) manually.

**Versions Used**

KubeSphere: kubesphere:3.0.0 -> kubespheredev:latest
Kubernetes: 1.18.8

**Environment**

CentOS 7.9.2009 / 1 master: 4c/8g; 1 node: 4c/8g

**How To Reproduce**

1. Install kubesphere 3.0.0 with kubernetes 1.18.8
2. Login into console
3. Upgrade kubesphere to kubespheredev:latest(by updating image tag of ks-apiserver, ks-controller-manager, ks-console)
4. Request kubesphere index page

**I'm not sure if this update method is appropriate.**

**Expected behavior**

Return http 401 error and redirect to login page, or redirect to login page directly.

/kind bug
/priority medium

**Comment by LinuxSuRen** [comment]
Why closed this?

**Comment by JohnNiang** [comment]
It's my fault. I upgraded kubesphere incorrectly that raised the unexpected error. So I closes this issue immediately when I found some pods were down.
