### ISSUE TITLE
promql many-to-many error in prometheus container

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3760]
**Describe the Bug**

![image](https://user-images.githubusercontent.com/18692628/115174374-b8a52c00-a0fb-11eb-83ab-baa246605f7e.png)

![image](https://user-images.githubusercontent.com/18692628/115174514-f7d37d00-a0fb-11eb-89df-8efaa6a8a02c.png)

**Versions Used**
KubeSphere: latest version at 2021-04-19 (build from master branch)
Kubernetes: v1.18.14

**Comment by benjaminhuo** [comment]
What's the k8s version?

**Comment by daniel-hutao** [comment]
> What's the k8s version?

v1.18.14

**Comment by benjaminhuo** [comment]
@junotx Pls take a look at this issue

**Comment by junotx** [comment]
That is really what happened when prometheus evaluated the recording rules, which are configured to prometheus by default to precompute metrics to reduce the query cost. Many-to-many is not supported for [promql](https://prometheus.io/docs/prometheus/latest/querying/operators/#vector-matching), and what you post may be an extreme case that triggered this error. Please show how your cluster was deployed and what it's configuration is, and all recording rules in which errors occured @daniel-hutao . It looks like related to nodes from your screenshot.

**Comment by daniel-hutao** [comment]
![image](https://user-images.githubusercontent.com/18692628/115521031-52680700-a2bd-11eb-8340-12a04273a38d.png)
![image](https://user-images.githubusercontent.com/18692628/115521085-5eec5f80-a2bd-11eb-81b2-64f1ccbf1e7e.png)

This problem may be caused by multiple pods sharing pvc

**Comment by benjaminhuo** [comment]
> ![image](https://user-images.githubusercontent.com/18692628/115521031-52680700-a2bd-11eb-8340-12a04273a38d.png)
> ![image](https://user-images.githubusercontent.com/18692628/115521085-5eec5f80-a2bd-11eb-81b2-64f1ccbf1e7e.png)
> 
> This problem may be caused by multiple pods sharing pvc

Good catch, @junotx let's see how to fix the rules

**Comment by benjaminhuo** [comment]
fixed

**Comment by daniel-hutao** [comment]
![image](https://user-images.githubusercontent.com/18692628/117764712-86e93600-b25f-11eb-82a6-797cd9232a1d.png)

/reopen

**Comment by benjaminhuo** [comment]
@junotx Pls take a look at the new symptom
