### ISSUE TITLE
Internal error occurred: account is not active

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3761]
**Describe the Bug**

![image](https://user-images.githubusercontent.com/18692628/115187291-9f10de00-a115-11eb-8f6f-06a4d694fa2a.png)

![image](https://user-images.githubusercontent.com/18692628/115187489-0169de80-a116-11eb-8a91-624680a62878.png)

- logs at ks-apiserver

![image](https://user-images.githubusercontent.com/18692628/115187681-51e13c00-a116-11eb-93a0-27280e3cc403.png)

**Versions Used**
KubeSphere: latest version at 2021-04-19
Kubernetes: v1.18.14

**Environment**

**How To Reproduce**

1. Install ks with ks-installer
2. Login ks with admin adn create user: user-manager with role users-manager
3. Logout and login with user-manager

**Comment by yuswift** [comment]
please show ks-controller-manager log

**Comment by daniel-hutao** [comment]
![image](https://user-images.githubusercontent.com/18692628/115188505-97eacf80-a117-11eb-81be-87bb15365f43.png)

The certificates mentioned in the above log are expired. I created these certificates the last time I deployed ks cluster, and then I've redeployed ks cluster. @yuswift 

I used kubesphere-delete.sh to clean the cluster before redeploy ks cluster.

**Comment by daniel-hutao** [comment]
![image](https://user-images.githubusercontent.com/18692628/115190752-18f79600-a11b-11eb-9901-d2d44b5e7b72.png)

 logs about user_controller

**Comment by wansir** [comment]
@daniel-hutao 

```
kubectl -n kubesphere-system get deploy ks-installer -o jsonpath='{.spec.template.spec.containers[0].image}'
kubectl -n kubesphere-system get deploy ks-apiserver -o jsonpath='{.spec.template.spec.containers[0].image}'
kubectl -n kubesphere-system get deploy ks-controller-manager -o jsonpath='{.spec.template.spec.containers[0].image}'
kubectl get crd users.iam.kubesphere.io -o yaml
```

**Comment by daniel-hutao** [comment]
This problem has disappeared when deploying with the latest version of ks-core module. @wansir @yuswift 

/close
