### ISSUE TITLE
The 'compile template' link reports a 404 error on the build image page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3762]
The 'compile template' link reports a 404 error on the build image page
![image](https://user-images.githubusercontent.com/36271543/115185791-2446c380-a113-11eb-82cc-57b64f52e3b6.png)

/kind bug
/assign @Sherlock113 
/priority High
/milestone 3.1.0

**Comment by Sherlock113** [comment]
Fixed. Need verification.
