### ISSUE TITLE
devopscredential_controller error: cound not create or update credential xxx

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3769]
**Describe the Bug**

I found the error msg at ks-controller-manager below

![image](https://user-images.githubusercontent.com/18692628/115213849-85cb5a00-a134-11eb-8029-d11c09a0e982.png)

**Versions Used**
KubeSphere: nightly-2021-04-19
Kubernetes: v1.18.14

**How To Reproduce**
1. Create a ks cluster with ks-installer.
2. Create a DevOps project and create some credential inside this project.
3. Delete this cluster with kubesphere-delete.sh in ks-installer.
4. Re-install a cluster with ks-installer.
5. look at logs in ks-controller-manager.

/kind bug
/area devops

**Comment by daniel-hutao** [comment]
> It looks like you didn't delete the secrets that names `credential` on the DevOps Project page. So I guess the errors caused by the script `kubesphere-delete.sh`. Or the deletion process is stuck.
> 
> Anyway, this is not a bug of the DevOps component in my opinion. I'll remove the label `area/devops` if you agree with me.

I did not clean up the credential first when I deleted the ks cluster with kubesphere-delete.sh, so does it mean that if I need to reinstall the cluster in the future, I need to clean up all devops projects and related resources created by ks in advance? In addition, I see that there are actions related to deleting `pipeline & devopsprojects` resources in the kubesphere-delete.sh script. Is the credential also should be deleted in this script?

/remove area/devops

**Comment by LinuxSuRen** [comment]
`devopsprojects` is a wrapper of `namespace`. Normally the secrets should be removed once the `devopsprojects` disappeared. But if the status of Jenkins is not ok, then the secret deleting process might not finish. You might need to cleanup the `finalizer` manually before we have a better solution.

**Comment by daniel-hutao** [comment]
> `devopsprojects` is a wrapper of `namespace`. Normally the secrets should be removed once the `devopsprojects` disappeared. But if the status of Jenkins is not ok, then the secret deleting process might not finish. You might need to cleanup the `finalizer` manually before we have a better solution.

I found that after the successful execution of the *kubesphere-delete.sh*, the ns related to the devops projects still exists and the status is **Active**. To clean up these ns, I need to delete the internal secrets first, and deleting these secrets need to manually clean up the `finalizer`. If there is no suitable way for the time being, I'll pay attention to clean up the resources when I reinstall the ks cluster later.

**Comment by LinuxSuRen** [comment]
I would suggest that create a new issue to track how to clean up DevOps orphan credentials easily. If you think that is a necessary feature request.
