### ISSUE TITLE
创建企业空间的button不见了 kubesphere-all-advanced-2.0.0-dev-20190430

### ISSUE THREAD

**Issue by stevenqingcloud** [kubesphere/kubesphere#377]
**General remarks**

> Please delete this section including header before submitting
> 也可以使用中文
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug(描述下问题)**

For UI issues please also add a screenshot that shows the issue.

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**

**Expected behavior(预期行为)**
刚安装了kubesphere-all-advanced-2.0.0-dev-20190430，admin进入企业空间，找不到新建的按钮了，怎么回事啊？

**Comment by rayzhou2017** [comment]
下载最新的installer https://docs.kubesphere.io/advanced-v2.0/zh-CN/installation/all-in-one/， 应该有了
