### ISSUE TITLE
For users with platform setting authority, access notification management failed

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3771]
**Versions Used**
KubeSphere: `dev:latest`

**Preset conditions**
There is a user A with platform-role  `Platform Settings`

**How To Reproduce**
1. use user A log in ks
2. click on 'Platform'
3. Click on 'Platform Settings'
3. CLick on 'Notification Management'
4. click on 'Email','ding talk', 'wecom', 'slack', 'webhook'
5. See error

**Actual behavior**
![image](https://user-images.githubusercontent.com/68640256/115220422-1b69e800-a13b-11eb-951d-c16b396773de.png)

/kind bug
/assign @wansir 
/milestone 3.1.0
/priority high

**Comment by wanjunlei** [comment]
This bug had fixed in kubesphere/ks-installer#1413, try it with the latest version, you need deploy a new cluster.

**Comment by wenxin-01** [comment]
issue fixed
