### ISSUE TITLE
openldap is not enabled by default when the devops module is enabled

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3785]
**Describe the Bug**

openldap is not enabled by default when the devops module is enabled

![image](https://user-images.githubusercontent.com/18692628/115524897-2c446600-a2c1-11eb-9347-2a22378b9cc5.png)
![image](https://user-images.githubusercontent.com/18692628/115524962-3d8d7280-a2c1-11eb-81ab-bb119ea216ab.png)
![image](https://user-images.githubusercontent.com/18692628/115525143-6ada2080-a2c1-11eb-8844-3f10ff7e800a.png)

**Versions Used**
KubeSphere: nightly-20210419

/kind bug
@pixiake

**Comment by yuswift** [comment]
see this [pr](https://github.com/kubesphere/ks-installer/pull/1442)
/kind need-to-verify

**Comment by daniel-hutao** [comment]
# kubesphere/ks-installer/pull/1442

it works.
