### ISSUE TITLE
点击左侧导航栏的应用，“应用模板部署”，会出现 internal server error

### ISSUE THREAD

**Issue by stevenqingcloud** [kubesphere/kubesphere#380]
点击左侧导航栏的应用，“应用模板部署”，选择nginx （用户手册中的步骤），会出现internal server error。

如果是直接点击顶部的应用模板，再去选择这个应用，则可以成功。

**Comment by rayzhou2017** [comment]
我部署成功了，下载最新的installer测试一下，每天早上6:30和下午3:30会分别出一个installer
