### ISSUE TITLE
Integration of KubeEdge v1.6

### ISSUE THREAD

**Issue by heyc-iot-chinamobile** [kubesphere/kubesphere#3802]
**What's it about?**
Integration of KubeEdge v1.6

**What's the reason why we need it?**
Since KubeEdge v1.6 is recently released, there are some useful features been enabled.
In the scene of IoT, message routing between cloud and edge is widly used to controll device and do the syncs.
And the edge apiserver feature can make edge more powful to handle more k8s resources, aka edge autonomy.

In the rodemap, integrtion of KubeEdge is located in KubeSphere v3.1, is there any plan for the features of
KubeEdge v1.6 mentioned above?

**Area Suggestion**
/kind feature-request

**Comment by FeynmanZhou** [comment]
@heyc-iot-chinamobile Hi, The version of integrated KubeEdge is v1.6.1, you can find it on [this guide](https://v3-1.docs.kubesphere.io/docs/pluggable-components/kubeedge/).

**Comment by heyc-iot-chinamobile** [comment]
@FeynmanZhou  Really appreciate your quick reply!  I can see the default version of KubeEdge turned out to be v1.6.1.
BUT the new feature of KubeEdge v1.6, just like message routing, cannot be found in the Documentations.
Am I missing something, or the new features of KubeEdge v1.6 have not being integrated?

> @heyc-iot-chinamobile Hi, The version of integrated KubeEdge is v1.6.1, you can find it on [this guide](https://v3-1.docs.kubesphere.io/docs/pluggable-components/kubeedge/).

**Comment by FeynmanZhou** [comment]
> @FeynmanZhou Really appreciate your quick reply! I can see the default version of KubeEdge turned out to be v1.6.1.
> BUT the new feature of KubeEdge v1.6, just like message routing, cannot be found in the Documentations.
> Am I missing something, or the new features of KubeEdge v1.6 have not being integrated?
> 
> > @heyc-iot-chinamobile Hi, The version of integrated KubeEdge is v1.6.1, you can find it on [this guide](https://v3-1.docs.kubesphere.io/docs/pluggable-components/kubeedge/).

In v3.1, KubeSphere only supports edge node management,  retrieve the logs and metrics from edge node and display on KubeSphere Web console, you can find the demo on the [SIG-Edge meeting](https://www.bilibili.com/video/BV1j64y1m79g) (Chinese). 

This is the first release to integrate KubeEdge on KubeSphere, more features with the edge will be added in the feature. Welcome to describe your requirements in a proposal. Join our slack or WeChat group to keep up with the community : )

**Comment by heyc-iot-chinamobile** [comment]
Got it! Thanks for your explanations~

> In v3.1, KubeSphere only supports edge node management, retrieve the logs and metrics from edge node and display on KubeSphere Web console, you can find the demo on the [SIG-Edge meeting](https://www.bilibili.com/video/BV1j64y1m79g) (Chinese).

Definitely I want to keep up with the community and attend to meetings. 
Could you show me how to join the WeChat group of SIG-Edge, I got some problem with slack :(

> This is the first release to integrate KubeEdge on KubeSphere, more features with the edge will be added in the feature. Welcome to describe your requirements in a proposal. Join our slack or WeChat group to keep up with the community : )

**Comment by FeynmanZhou** [comment]
> Got it! Thanks for your explanations~
> 
> > In v3.1, KubeSphere only supports edge node management, retrieve the logs and metrics from edge node and display on KubeSphere Web console, you can find the demo on the [SIG-Edge meeting](https://www.bilibili.com/video/BV1j64y1m79g) (Chinese).
> 
> Definitely I want to keep up with the community and attend to meetings.
> Could you show me how to join the WeChat group of SIG-Edge, I got some problem with slack :(
> 
> > This is the first release to integrate KubeEdge on KubeSphere, more features with the edge will be added in the feature. Welcome to describe your requirements in a proposal. Join our slack or WeChat group to keep up with the community : )

You can find the KubeSphere WeChat subscription on [website](https://kubesphere.io), follow it and you will know how to join the WeChat group.

**Comment by heyc-iot-chinamobile** [comment]
Thanks! I will close this issue after.

> You can find the KubeSphere WeChat subscription on [website](https://kubesphere.io), follow it and you will know how to join the WeChat group.
