### ISSUE TITLE
Failed to define a Prometheus Probe CRD?

### ISSUE THREAD

**Issue by xuanyuanaosheng** [kubesphere/kubesphere#3803]
The kubesphere use the prometheus-operator:v0.38.3, Is this version support to define the blackbox-exporter probe ?

**Versions Used**
KubeSphere: 3.0
Kubernetes: v1.20.2

The related github issue:
1.  https://github.com/prometheus-community/helm-charts/issues/408
2.  https://github.com/prometheus-operator/kube-prometheus/issues/644
3.  https://stackoverflow.com/questions/64948392/prometheus-probe-crd-doesnt-probe-targets

**Comment by benjaminhuo** [comment]
kubesphere v3.1.0 has upgraded prometheus operator to v0.42.1 in which the probe crd is supported.

**Comment by xuanyuanaosheng** [comment]
@benjaminhuo Thanks

**Comment by xuanyuanaosheng** [comment]
The blackbox-exporter probe works fine on kubesphere v3.1.0
