### ISSUE TITLE
There is no use to click "No Concurrent builds" checkbox

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3807]
**Describe the Bug**

This checkbox cannot be resolved

![image](https://user-images.githubusercontent.com/18692628/115985060-a6842b80-a5dc-11eb-82a8-74d89a970bd6.png)

**Versions Used**
KubeSphere: nightly-20210422
Kubernetes: v1.18.14

/kind bug
/area devops

**Comment by LinuxSuRen** [comment]
The PR https://github.com/kubesphere/console/pull/1849 should be able to fix this.

**Comment by daniel-hutao** [comment]
If you confirm that the problem has been fixed, you can close this issue.
@harrisonliu5
