### ISSUE TITLE
Failed to Rerun a pipeline

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3810]
**Describe the Bug**

![image](https://user-images.githubusercontent.com/18692628/116021147-3330f700-a67a-11eb-9ee5-3a857a0bc522.png)

**Versions Used**
KubeSphere: nightly-20210422
Kubernetes:  v1.18.14

/kind bug
/area devops

**Comment by zryfish** [comment]
Could you also attach ks-apiserver logs?

**Comment by daniel-hutao** [comment]
> Could you also attach ks-apiserver logs?

```sh
E0426 10:44:17.396053       1 pure_request.go:70] {
  "message" : "Run was not added to queue.",
  "code" : 500,
  "errors" : [ ]
}
E0426 10:44:17.396090       1 pipeline.go:459] {
  "message" : "Run was not added to queue.",
  "code" : 500,
  "errors" : [ ]
}
E0426 10:44:17.396112       1 devops.go:624] {
  "message" : "Run was not added to queue.",
  "code" : 500,
  "errors" : [ ]
}
E0426 10:44:17.396119       1 devops.go:900] {
  "message" : "Run was not added to queue.",
  "code" : 500,
  "errors" : [ ]
}
I0426 10:44:17.396159       1 apiserver.go:615] 172.22.4.165 - "POST /kapis/devops.kubesphere.io/v1alpha2/devops/pai-serverhfcqq/pipelines/dev/branches/dev-ht/runs/8/replay HTTP/1.1" 500 81 12ms
```

**Comment by zryfish** [comment]
Not much useful information, could you also paste jenkins logs?

**Comment by LinuxSuRen** [comment]
Which button do you click, `Rerun` or `Run`? They're different. Rerun means run a Pipeline base on the particular build history. So, it will fail if you re-run a failure Pipeline that cannot parse the Jenkinsfile correctly. I know it's not the best solution. We already have an issue to track it.

**Comment by daniel-hutao** [comment]
> Which button do you click, `Rerun` or `Run`? They're different. Rerun means run a Pipeline base on the particular build history. So, it will fail if you re-run a failure Pipeline that cannot parse the Jenkinsfile correctly. I know it's not the best solution. We already have an issue tracking it.
> 
> See also #2777

Rerun
