### ISSUE TITLE
After modified role, the user still has the permissions of the previous role.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3815]
**Versions Used**
KubeSphere:  'dev:latest'

**Environment**
http://139.198.121.240:30888/

**Preset conditions**
There is a user 'test' with global-role `workspace-manager`

**How To Reproduce**
1. Use user 'test' login ks  in browser 'A'
2. Go to workspace 'wx'
3. Create devops  'test-devops' and go to devops 'test-devops'
4. Login with admin in other browsers, and change the role of 'test'  to `platform-regular`
5. Use user 'test' create pipeline in browser 'A'

**Expected behavior**
Failed to create, indicating that the user does not have corresponding permissions

**Actual behavior**
Created successfully

/priority medium
/kind bug
/milestone 3.1.0

**Comment by wansir** [comment]
@wenxin-01 

Not a valid issue, I saw that the regular user test has `self-provisioner` (able to create project by self) role in workspace wx.

**Comment by wenxin-01** [comment]
> @wenxin-01
> 
> Not a valid issue, I saw that the regular user test has `self-provisioner` (able to create project by self) role in workspace wx.

dvops 'test-devops' created by user 'test' and then change the role of 'test'.

**Comment by wenxin-01** [comment]
follow k8s
