### ISSUE TITLE
Failed to trigger a particular branch Pipeline of the Gitlab multi-branch

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3818]
**Describe the Bug**

step 1

![image](https://user-images.githubusercontent.com/18692628/116203584-6e145700-a76e-11eb-9bdc-30c1c645e193.png)

setp 2

![image](https://user-images.githubusercontent.com/18692628/116203705-8dab7f80-a76e-11eb-9c14-285476be5e8b.png)

step3

![image](https://user-images.githubusercontent.com/18692628/116203784-a3b94000-a76e-11eb-9fef-4f8281703821.png)

step 4 

![image](https://user-images.githubusercontent.com/18692628/116203867-baf82d80-a76e-11eb-83d0-7eff2eb2542b.png)

step5 Got nothing

![image](https://user-images.githubusercontent.com/18692628/116203916-c8adb300-a76e-11eb-858e-8fbf86509db4.png)

And there are no logs at ks-apiserver.

**Versions Used**
KubeSphere: nightly-20210422
Kubernetes: v1.18.14

/kind bug
/area devops

**Comment by LinuxSuRen** [comment]
/retitle Failed to trigger a particular branch Pipeline of the Gitlab multi-branch
/priority high

**Comment by LinuxSuRen** [comment]
Thanks to @JohnNiang , we finally figure the real reason. Please [see also](https://github.com/kubesphere/console/issues/1877#issuecomment-842085703) if you want to know the details.
