### ISSUE TITLE
Failed to allocate workspace and manager to a project

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3819]
**Describe the Bug**

![image](https://user-images.githubusercontent.com/18692628/116205425-576eff80-a770-11eb-8d4e-bd5438880dbe.png)

![image](https://user-images.githubusercontent.com/18692628/116205545-740b3780-a770-11eb-8d2d-19c55f136b39.png)

![image](https://user-images.githubusercontent.com/18692628/116205672-8d13e880-a770-11eb-8e50-1d35af72c3f1.png)

**Versions Used**
KubeSphere: nightly-20210427

/kind bug

**Comment by wansir** [comment]
/assign @kubesphere/sig-console 

https://github.com/kubesphere/kubesphere/pull/3966#issuecomment-862109099
