### ISSUE TITLE
Users with admin or viewer permissions in workspace cannot see the consumption data of projects.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3822]
**Versions Used**
KubeSphere: `dev:latest`

**Environment**
http://139.198.121.240:30888/

**Preset conditions**
There is a user 'test' with global-role `platform-regular`, with workspace-role `admin` or `viewer`

**How To Reproduce**
1. use user 'test' login ks
2. Click on 'Metering and Billing'
3. view Project Resource Consumption

**Expected behavior**
**Actual behavior**

https://user-images.githubusercontent.com/68640256/116342746-b76bb180-a815-11eb-9592-d21963f61aa2.mov

/kind bug
/assign @yunkunrao 
/priority Medium
/milestone 3.1.0
/area metering

**Comment by xyz-li** [comment]
Frontend need add query parameter `workspace` to path `/kapis/clusters/host/tenant.kubesphere.io/v1alpha2/metering`.
@harrisonliu5

**Comment by harrisonliu5** [comment]
![image](https://user-images.githubusercontent.com/17872673/118245112-f4e96380-b4d2-11eb-9319-257902ffc509.png)

**Comment by wenxin-01** [comment]
issue fixed ` nightly-20210610`
