### ISSUE TITLE
Request help: Where can I find the development documentation of kubesphere? 

### ISSUE THREAD

**Issue by Caelebs** [kubesphere/kubesphere#3825]
I have some requirements that may require secondary development on kubesphere and want some development-related documents, but I did not find what I need on the official website and github. Where can I find these documents?

**Comment by yuswift** [comment]
[here](https://github.com/kubesphere/community/tree/master/developer-guide/development)

**Comment by yuswift** [comment]
please join our slack channels for communication.

**Comment by Caelebs** [comment]
okay, thanks @yuswift
