### ISSUE TITLE
Authorized information is wrong in 'Assign the Cluster to Workspaces'.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3826]
**Versions Used**
KubeSphere: `dev:latest`
multi-cluster function enabled

**Preset conditions**
The environment is enabled multi-cluster function but only have one cluster 'host'.
Before enable multi-cluster function, there are many workspaces have been created.

**How To Reproduce**
1. Login ks with 'admin'
2. Click on 'platform' and then click on 'Cluster Management'
3. Clcik on 'host' -->click on 'Cluster Settings'--> click on 'Cluster Visibility'
4. Click on 'Edit Visibility'
5. Assign host cluster to  any workspace   
6. Click on 'Edit Visibility'

**Expected behavior**
Authorized list display the workspace of step5

**Actual behavior**

https://user-images.githubusercontent.com/68640256/116374874-4d690180-a841-11eb-8dcf-4dd803191c57.mov

/kind bug
/assign @yuswift 
/priority Medium
/milestone BackLog

**Comment by wansir** [comment]
@wenxin-01  Please check logs of kubefed-controller-manager.

```
kubectl -n kube-federation-system logs -l kubefed-control-plane=controller-manager
```

**Comment by wenxin-01** [comment]
![image](https://user-images.githubusercontent.com/68640256/116377752-15af8900-a844-11eb-9e29-32ed74b83253.png)

**Comment by wenxin-01** [comment]
@wansir 
![image](https://user-images.githubusercontent.com/68640256/116377837-2a8c1c80-a844-11eb-984d-c873050cadbd.png)

**Comment by yuswift** [comment]
@wenxin-01 could you reproduce the bug in v3.1?

**Comment by wenxin-01** [comment]
> @wenxin-01 could you reproduce the bug in v3.1?

Can not reproduce

**Comment by wenxin-01** [comment]
> @wenxin-01 could you reproduce the bug in v3.1?

can not reproduce, i will close this issue
