### ISSUE TITLE
The time of the alarm message displayed is incorrect

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3828]
The time of the alert message, which actually shows the current time;
It Should be displayed as the time the message was triggered
![image](https://user-images.githubusercontent.com/36271543/116380413-88216880-a846-11eb-848e-3fbb5ba56915.png)

/kind bug
/assign @junotx 
/priority Medium
/milestone BackLog
/area alerting

**Comment by junotx** [comment]
The display time did not correspond to the time in the response body. Please fix it later @harrisonliu5 

![image](https://user-images.githubusercontent.com/49136171/116643074-db103280-a9a2-11eb-8815-87dd20d43fed.png)

/assign @harrisonliu5 
/unassign @junotx
