### ISSUE TITLE
Change externalElasticsearchUrl to externalElasticsearchHost at cc

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3829]
I have been asked several times whether the value filled in `cc.spec.common.es.externalElasticsearchUrl` requires an http prefix, but it is actually not needed, but this key is a bit confusing. I don’t know if I need an http prefix sometimes when I look at it, so I think it’s clearer to change it to **externalElasticsearchUrl** to **externalElasticsearchHost**

/kind feature-request

**Comment by rayzhou2017** [comment]
@daniel-hutao @benjaminhuo Please help @himanshu007-creator with this issue after you get back from holiday.

**Comment by daniel-hutao** [comment]
https://github.com/kubesphere/ks-installer/blob/a5776b845bd691a6b9145c5435b1d9b9702af316/deploy/cluster-configuration.yaml#L41

The logic entry is in this place, you can search globally in the project to find which codes refer to this variable, and then modify all of those.
@himanshu007-creator

**Comment by benjaminhuo** [comment]
This change is not that urgent but with big impacts, 2 projects: https://github.com/kubesphere/ks-installer and https://github.com/kubesphere/website are involved. All the docs have to be changed accordingly. And there are already lots of info out there in the forum, website if you search externalElasticsearchUrl. 

So if someone upgrades from v3.1 or v3.0 to a future higher version like v3.1.1, you've to make it work and compatible.

So my opinion is to avoid making such significant changes, instead you can add a tip to the docs somewhere in https://github.com/kubesphere/website

@daniel-hutao @himanshu007-creator @pixiake @zryfish @wanjunlei @junotx

**Comment by daniel-hutao** [comment]
Functionally speaking, not modifying with `externalElasticsearchUrl` is the easiest way, but modifying it can make ks more refined. I personally have detailed obsessive-compulsive disorder, and I hope that any flaws can be corrected. Of course, I also understand the compatibility issues that may can be introduced by this modifying, which may require a lot of work.  I respect everyone's opinions and objectively speaking, I remain neutral.

**Comment by mangoGoForward** [comment]
Because there are remaining some related issues, and not solved.

/reopen
