### ISSUE TITLE
infinite loop on login page when token expired ks 3.1

### ISSUE THREAD

**Issue by lxm** [kubesphere/kubesphere#3833]
upgraded to ks 3.1 and use aliyunidaas as OAuth provider

when the ks jwt token expired, the user will get stuck on the login page.
a video as follows 

https://user-images.githubusercontent.com/1918195/116521092-1e689380-a906-11eb-86a0-d2ad155f8bd1.mov

**Comment by daniel-hutao** [comment]
I encountered the same problem, pay attention to your node time synchronization

**Comment by daniel-hutao** [comment]
https://kubesphere.com.cn/en/docs/faq/access-control/session-timeout/

The node clock skew affects time-sensitive operations such as validating the expiration time of a user token. You can configure the server time synchronization with an NTP server. MaximumClockSkew can also be set, which defaults to 10 seconds.

**Comment by daniel-hutao** [comment]
I configured MaximumClockSkew in kubesphere-config, but it failed again today and restored to the default value 10s. It seems to have been reset by ks-installer, so do I need to configure it in cc? Add authentication.maximumClockSkew configuration. The relevant part of the document is 404(https://kubesphere.com.cn/en/docs/access-control-and-account-management/configuring-authentication/#authentication-configuration)

/cc @zryfish

**Comment by wansir** [comment]
> I configured MaximumClockSkew in kubesphere-config, but it failed again today and restored to the default value 10s. It seems to have been reset by ks-installer, so do I need to configure it in cc? Add authentication.maximumClockSkew configuration. The relevant part of the document is 404(https://kubesphere.com.cn/en/docs/access-control-and-account-management/configuring-authentication/#authentication-configuration)
> 
> /cc @zryfish

You can configure it in `cc`, https://github.com/kubesphere/ks-installer/blob/v3.1.0/roles/ks-core/config/templates/kubesphere-config.yaml.j2#L8
