### ISSUE TITLE
About update kubesphere3.1 the problem

### ISSUE THREAD

**Issue by waidinsamkeit** [kubesphere/kubesphere#3835]
# 配置文件应用成功UI页面不更新
![问题1](https://kubesphere.com.cn/forum/assets/files/2021-04-30/1619752047-897688-image.png)
发现UI界面上的master角色依旧是master,worker
![问题2](https://kubesphere.com.cn/forum/assets/files/2021-04-30/1619752098-538156-image.png)
# 关于流量治理问题
- 3.0.0版本流量治理可以观看浏览
- 3.1.0不管怎么访问服务流量治理依旧无法展示
![问题3](https://kubesphere.com.cn/forum/assets/files/2021-04-30/1619752209-460188-image.png)

**Comment by yuswift** [comment]
please check if all of pods under istio-system ns are running

**Comment by zackzhangkai** [comment]
https://kubesphere.com.cn/forum/d/3192-kubesphere
