### ISSUE TITLE
Failed to create Deployments

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3840]
**Versions Used**
KubeSphere:  `ks3.1`
Kubernetes:  `v1.20.4`
GoVersion: `go1.15.8`

`ubuntu 16.04` 

**Actual behavior**
![image](https://user-images.githubusercontent.com/68640256/117247376-b7e8f580-ae70-11eb-89c6-c22954f301a0.png)

![image](https://user-images.githubusercontent.com/68640256/117247407-c0d9c700-ae70-11eb-9b54-94a3e9229e43.png)

/kind bug
/assign @wansir
/milestone 3.1.0
/priority medium

**Comment by wansir** [comment]
Related to https://github.com/helm/helm/issues/9046
