### ISSUE TITLE
Simplify provisioner and storageclass capabilities

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/kubesphere#3843]
**Describe the Bug**
Currently ks has two crd to define the provisioner and storageclass capabilities:
```
[root@test-ks ~]# kubectl get crd | egrep capab
provisionercapabilities.storage.kubesphere.io         2021-04-28T08:17:53Z
storageclasscapabilities.storage.kubesphere.io        2021-04-28T08:17:54Z
```

And we have code to automatically detect the provisioner capabilities, however, it does not work for most provisioners. 

The proposed change is:
- simplify the  provisioner and storageclass capabilities, I don't think we need the storageclass capabilities, and I don't think we need export so many capabilities as we do now. 
- remove the automatic detection of provisioner capabilities, it does not work well.
- work with ks-console developer to change the frontend logic. The provisioner capabilities should be provided by user, except the qingstor-csi and qingcloud-csi which can be built-in with ks.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by xyz-li** [comment]
https://kubesphere.com.cn/forum/d/4505-31-ks-controller-manager

**Comment by stoneshi-yunify** [comment]
for 3.1.1, we need to remove the auto detect part, but keep the storageclasscapabilities and provisionercapabilities, so ks-console does not need any change.

the ks-console part change will be tracked in https://github.com/kubesphere/kubesphere/issues/3921
