### ISSUE TITLE
APPSCAN security scan vulnerability-cross-site scripting-kubsphere login page

### ISSUE THREAD

**Issue by zhaolei0914** [kubesphere/kubesphere#3849]
**Versions Used**
KubeSphere:2.1 3.0
Kubernetes: 1.16.3

**Environment**
Single node，32C64G，centos7.7

APPSCAN security scan vulnerability-cross-site scripting-kubsphere login page

![企业微信截图_16204359242005](https://user-images.githubusercontent.com/7426709/117522338-5e560780-afe5-11eb-85a0-25b165ccfbab.png)

**Comment by yuswift** [comment]
please tell us which kubesphere version you are using

**Comment by yuswift** [comment]
> > please tell us which kubesphere version you are using
> 
> KubeSphere: 2.1 and KubeSphere 3.0

we have fixed it in v3.1.0. please upgrade your version.

**Comment by zhaolei0914** [comment]
ok,thank you
