### ISSUE TITLE
Failed to update Credentials

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3851]
**Describe the Bug**

I created a Credential. When I updated the Credential on the console, it would always be stuck in the update state. Then I refreshed the page, I saw that the update state has been Success, but the secret in the background is actually still keep the old state.

![image](https://user-images.githubusercontent.com/18692628/117522852-1c7a9080-afe8-11eb-9dc8-d2765c5b5acc.png)

![image](https://user-images.githubusercontent.com/18692628/117522988-e689dc00-afe8-11eb-9e82-fb1b41230b85.png)

![image](https://user-images.githubusercontent.com/18692628/117523011-06b99b00-afe9-11eb-9c17-bab9f85d12ce.png)

**Versions Used**
KubeSphere: v3.1.0
Kubernetes: v1.18.14

/kind bug
/area console

**Comment by daniel-hutao** [comment]
And if I delete this Credential and create a new one and enter the content of kubeconfig defined by myself, the kubeconfig in the Credential will be overwritten to the default value...

**Comment by JohnNiang** [comment]
But the sync status won't always be updating in my environmen.

**Comment by JohnNiang** [comment]
I suggest moving this issue into <https://github.com/kubesphere/console>.

**Comment by JohnNiang** [comment]
> > But the sync status won't always be updating in my environment.
> 
> How about after you refresh the page?

The sync status will be back to success. But I couldn't reproduce this issue every time after I updated credential.

**Comment by JohnNiang** [comment]
The sync status should be updated periodically instead of update immediately after updating credential.

**Comment by JohnNiang** [comment]
Another problem about kubeconfig has reported at <https://github.com/kubesphere/console/issues/1907>.

**Comment by JohnNiang** [comment]
This issue has been fixed by <https://github.com/kubesphere/console/pull/1902> and <https://github.com/kubesphere/console/pull/1911>.

I will close this issue for a while. Please feel free to reopen this issue if you have any problem.
