### ISSUE TITLE
need more test cases on service mesh

### ISSUE THREAD

**Issue by yuswift** [kubesphere/kubesphere#3856]
refer https://github.com/kubesphere/kubesphere/issues/3845
we need a full stack test on service mesh
/cc @liuyp2018 
/cc @wenxin-01 
please take a look at this issue if you are free

**Comment by yuswift** [comment]
see https://github.com/kubesphere/kubesphere/pull/3848#discussion_r628819167

**Comment by yuswift** [comment]
help wanted

**Comment by yuswift** [comment]
help-wanted

**Comment by wenxin-01** [comment]
I will test this

**Comment by yuswift** [comment]
@wenxin-01 
hi, could you share the testing results on service mesh with kubesphere v3.1?

**Comment by wenxin-01** [comment]
issue https://github.com/kubesphere/kubesphere/issues/3845 had been fixed, but there is another issue https://github.com/kubesphere/kubesphere/issues/3927
