### ISSUE TITLE
Invalid webhook push setting in pipeline

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/kubesphere#3857]
**Describe the Bug**

In DevOps project pipeline setting, a webhook push link is automatically set, which is invalid in Github webhook configuration. The specific result is as follows:

![image](https://user-images.githubusercontent.com/16865714/117564355-33031380-b0de-11eb-838d-9d5ff5371def.png)

![image](https://user-images.githubusercontent.com/16865714/117564313-149d1800-b0de-11eb-9d77-36769ed773ea.png)

**Versions Used**

KubeSphere: 3.1.0

**How To Reproduce**
1. Create a pipeline with Github repository.
1. After selecting a Github repository, you can see the settings of webhook push link at the bottom.
1. Add the webhook to the settings of corresponding Github repository.
1. View recently deliveries.

**Expected behavior**

Hope to increase the secret setting of webhook push, and make webhook work normally.

/kind bug
/area devops
/priority high

**Comment by LinuxSuRen** [comment]
hi @JohnNiang , thanks for reporting this issue.

**Comment by Felixnoo** [comment]
I suggest you guys also test the S2I webhook.

**Comment by LinuxSuRen** [comment]
> I suggest you guys also test the S2I webhook.

Okay.

**Comment by LinuxSuRen** [comment]
# Single cluster

The URL `http://ip:port/cluster/default/devops_webhook/github` is incorrect, you will get 404

The correct URL should be `http://ip:port/devops_webhook/github`

**Comment by LinuxSuRen** [comment]
> I suggest you guys also test the S2I webhook.

It works well.

**Comment by LinuxSuRen** [comment]
hi @JohnNiang and @harrisonliu5 , please help to confirm that if we can close this issue.

**Comment by JohnNiang** [comment]
The webhook works now.

- Github webhook setting
![image](https://user-images.githubusercontent.com/16865714/121472455-cc7e5780-c9f3-11eb-80c9-57b3086c86d7.png)

- Pipeline activity
![image](https://user-images.githubusercontent.com/16865714/121472530-e455db80-c9f3-11eb-9554-4db53f940763.png)
