### ISSUE TITLE
why installed it , it no application menu?

### ISSUE THREAD

**Issue by feeman89** [kubesphere/kubesphere#3874]
![image](https://user-images.githubusercontent.com/65520943/117937695-dc454600-b338-11eb-8eec-7e3ab331e982.png)

**Comment by JohnNiang** [comment]
You have to enable related component.

**Comment by RolandMa1986** [comment]
/kind support 
@feeman89 There's no Application menu in the Clusters management page. You have to create your own workspace and project to use `Application`.
