### ISSUE TITLE
Cannot log in after updating to 3.1 yesterday

### ISSUE THREAD

**Issue by crazylsq** [kubesphere/kubesphere#3875]
Problem Description

We have been using ldap for version 3.0，but there are some problems after upgrading to 3.1

ldap user login for the first time
![image](https://user-images.githubusercontent.com/16173894/118086396-7e773380-b3f6-11eb-87e3-970ba41972d3.png)

Users who have logged in using ldap in version 3.0 can log in normally, but the running pipeline reports an error
![image](https://user-images.githubusercontent.com/16173894/118086517-b1212c00-b3f6-11eb-8c5b-f2f51303cacc.png)
![image](https://user-images.githubusercontent.com/16173894/118086528-b54d4980-b3f6-11eb-9317-be0acdb6a4be.png)

Has affected normal use, please fix it as soon as possible

Thanks

**Comment by wansir** [comment]
/assign @harrisonliu5

Username regex `[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*`, maximum length 32.

**Comment by crazylsq** [comment]
Can you provide a repaired mirror tag？

Do you want me to pull the code to compile and mirror, and then replace the mirror?
