### ISSUE TITLE
Cluster management is default, how do I change it?

### ISSUE THREAD

**Issue by JUNgege10** [kubesphere/kubesphere#3877]
<img width="614" alt="image" src="https://user-images.githubusercontent.com/18061649/118112580-ca86a000-b417-11eb-962a-164bb3702115.png">

**Comment by wansir** [comment]
[Enable multi-cluster management in KubeSphere](https://kubesphere.io/docs/multicluster-management/enable-multicluster/direct-connection/)

**Comment by JUNgege10** [comment]
@wansir I have changed it according to the documentation, but nothing has changed.

**Comment by wansir** [comment]
> @wansir I have changed it according to the documentation, but nothing has changed.

Wait a moment, check ks-installer logs use the following command:
```
kubectl -n kubesphere-system logs -l app=ks-install -f
```

**Comment by JUNgege10** [comment]
@wansir The log is normal：


Waiting for all tasks to be completed ...
task multicluster status is successful  (1/4)
task openpitrix status is successful  (2/4)
task network status is successful  (3/4)
task monitoring status is successful  (4/4)
**************************************************
Collecting installation results ...
#####################################################
###              Welcome to KubeSphere!           ###
#####################################################

Console: http://10.241.43.26:30880
Account: admin
Password: P@88w0rd

NOTES：
  1. After you log into the console, please check the
     monitoring status of service components in
     "Cluster Management". If any service is not
     ready, please wait patiently until all components
     are up and running.
  2. Please change the default password after login.

#####################################################
https://kubesphere.io             2021-05-13 23:35:33
#####################################################

^C
[root@KVM-10-241-43-24 ~]# kubectl -n kubesphere-system logs -l app=ks-install -f
     monitoring status of service components in
     "Cluster Management". If any service is not
     ready, please wait patiently until all components
     are up and running.
  2. Please change the default password after login.

#####################################################
https://kubesphere.io             2021-05-13 23:35:33
#####################################################

**Comment by wansir** [comment]
> @wansir The log is normal：
> 
> Waiting for all tasks to be completed ...
> task multicluster status is successful (1/4)
> task openpitrix status is successful (2/4)
> task network status is successful (3/4)
> task monitoring status is successful (4/4)
> 
> Collecting installation results ...
> #####################################################
> 
> ### Welcome to KubeSphere!
> #####################################################
> 
> Console: http://10.241.43.26:30880
> Account: admin
> Password: P@88w0rd
> 
> NOTES：
> 
> 1. After you log into the console, please check the
>    monitoring status of service components in
>    "Cluster Management". If any service is not
>    ready, please wait patiently until all components
>    are up and running.
> 2. Please change the default password after login.
> 
> #####################################################
> https://kubesphere.io 2021-05-13 23:35:33
> #####################################################
> 
> ^C
> [root@KVM-10-241-43-24 ~]# kubectl -n kubesphere-system logs -l app=ks-install -f
> monitoring status of service components in
> "Cluster Management". If any service is not
> ready, please wait patiently until all components
> are up and running.
> 2. Please change the default password after login.
> 
> #####################################################
> https://kubesphere.io 2021-05-13 23:35:33
> #####################################################

Make sure that your cluster role is host.

```
kubectl -n kubesphere-system get cc ks-installer -o yaml
```

And then you can open the cluster management page.

![image](https://user-images.githubusercontent.com/8263040/118230465-4f2cf900-b4c0-11eb-803c-06fe4f9a7b41.png)

**Comment by JUNgege10** [comment]
@wansir cluster role changed to host succeeded，TKS

**Comment by JUNgege10** [comment]
resolved
