### ISSUE TITLE
prometheus-k8s unattached prometheus-k8s-rulefiles-0 

### ISSUE THREAD

**Issue by zhuch-h** [kubesphere/kubesphere#3879]
**Describe the Bug**
 Events: Unable to attach or mount volumes: unmounted volumes=[secret-kube-etcd-client-certs], unattached volumes=[prometheus-k8s-rulefiles-0 secret-kube-etcd-client-certs prometheus-k8s-token-khzdd config config-out tls-assets prometheus-k8s-db]: timed out waiting for the condition

**Versions Used**
KubeSphere: ks3.1
Kubernetes: kubeadm v1.20.0

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)
System：CentOS Linux 7 (Core) / 1 master: 4cpu12g;
Kubelet version:  v1.20.0
Containerd: 1.3.9
storage: nfs
 
--- 

I know resolve.

**Expected behavior**

**Comment by zhuch-h** [comment]
fix :
kubectl -n kubesphere-monitoring-system create  secret generic kube-etcd-client-certs \
 --from-file=etcd-client-ca.crt=/etc/kubernetes/pki/etcd/ca.crt \
 --from-file=etcd-client.crt=/etc/kubernetes/pki/etcd/healthcheck-client.crt \
 --from-file=etcd-client.key=/etc/kubernetes/pki/etcd/healthcheck-client.key

**Comment by yuswift** [comment]
> fix :
> kubectl -n kubesphere-monitoring-system create secret generic kube-etcd-client-certs
> --from-file=etcd-client-ca.crt=/etc/kubernetes/pki/etcd/ca.crt
> --from-file=etcd-client.crt=/etc/kubernetes/pki/etcd/healthcheck-client.crt
> --from-file=etcd-client.key=/etc/kubernetes/pki/etcd/healthcheck-client.key

Did you install kubesphere by kubekey? You don't need to create secrets manually.

**Comment by zhuch-h** [comment]
@yuswift install cluster by kubeadm, use kubekey install kubesphere3.1. 
The first, select minimal installation.  
Then, update member role to host.
