### ISSUE TITLE
DevOps build pipeline bug

### ISSUE THREAD

**Issue by shihaoH** [kubesphere/kubesphere#3885]
**Describe the Bug**
Pipeline initialization prompt `Jenkins not tag maven` or `maven-xxxx is offline`

**Versions Used**
KubeSphere: v3.1.0
Kubernetes: v1.18.6

**Comment by LinuxSuRen** [comment]
Normally, this is not a bug. Please check if there're some Pods are the pending status. The corresponding pod might still try to pull docker images.

/area devops
/kind support

**Comment by shihaoH** [comment]
I upgraded from v3 to v3.1 on offline
Maybe not load kubesphere/builder-maven:v3.1.0 to harbor repo

**Comment by shihaoH** [comment]
> Normally, this is not a bug. Please check if there're some Pods are the pending status. The corresponding pod might still try to pull docker images.
> 
> /area devops
> /kind support
