### ISSUE TITLE
registry.cn-beijing.aliyuncs.com/kubesphereio/flannel:v0.12.0  may require 'docker login'

### ISSUE THREAD

**Issue by zdwork** [kubesphere/kubesphere#3888]

**Comment by LinuxSuRen** [comment]
/retitle registry.cn-beijing.aliyuncs.com/kubesphereio/flannel:v0.12.0  may require 'docker login'

**Comment by LinuxSuRen** [comment]
This [repo](https://github.com/kubesphere/image-sync-config) responsible for sync images to `aliyunc.com`.
