### ISSUE TITLE
aws-auth was updated by a lambda which code is not open source

### ISSUE THREAD

**Issue by wqnner** [kubesphere/kubesphere#3889]
**Describe the Bug**
I installed kubesphere on aws using this template:https://aws-quickstart.s3.amazonaws.com/quickstart-qingcloud-kubesphere/templates/kubesphere-entrypoint-existing-vpc.template.yaml
When I edit all the supported resource tags on the AWS tag editor page,  lambda k8s-api-vpc-connector-MYEKSID  was triggered, and lambda k8s-api-vpc-connector-MYEKSID  modifies the aws-auth configmap in the kube-system namespace, causing the original content of the aws-auth configmap to be overridden. Also I found that lambda k8s-api-vpc-connector-MYEKSID is a golang binary file, The internal logic cannot be confirmed, and the code is not open source. Can the developer explain the function of lambda k8s-api-vpc-connector-MYEKSID?

**Versions Used**
KubeSphere:3.0

**Environment**
AWS EKS
worker nodes: c5a.4xlarge * 6  and g4dn.2xlarge * 6，
master node: hosted by AWS EKS

**How To Reproduce**
1. Follow this page https://aws-quickstart.github.io/quickstart-qingcloud-kubesphere/ and install kubesphere in an exist VPC
2. Search Tag Editor at aws home page, open it
3. At tag editor page, click Tag Editor at left side menu, then select Regions where eks installed and Resource Type we choose "All suported resource types" 
4. Check aws-auth configmap in the kube-system namespace , it was updated. And api-server-audit log also record that event. 
ps：this error was reproduced by  AWS customer representative.

**Expected behavior**
aws-auth configmap will not be overridden.

**Comment by ruiyaoOps** [comment]
EKS was created by referring to the Amazon KES template, the address is https://github.com/aws-quickstart/quickstart-amazon-eks.
For more about lambda, you can find something in the repository and the issues, also you can submit issues, and their reply may not be timely.

**Comment by ruiyaoOps** [comment]
@wqnner

**Comment by wqnner** [comment]
@ruiyaoOps 
I have contacted AWS technical support. After their confirmation, their official template will not register this lambda function in the user's environment. Can the developer of QingCloud confirm whether you have referenced a third-party template in the template?
Here is my communication record with AWS staff：
客户您好，

感谢您下午拨空接听我的电话，以下为我们讨论的几点项目以及我的测试结果：

➤ 我尝试参考与您同一份是由青云共同开发的 CloudFormation template [1] 来布建我的环境，确认到在我的环境同样也能布建出 k8s-api-vpc-connector-EKS-******* 的资源。接着我回找 Cloudtrail 事件，参照您同事的操作[1]，通过 Tag Editor 为相关的 CloudFormation Stack 添加 tag 后，我的 EKS 集群节点确实也变为 NotReady，进一步查看 audit 日志，能回查到同样是 Lambda Function 修改了 configmap。

➤ 对应您的环境，我将当时的时间轴以及我所推测的相关事件列下给您参考：

- IAM 用户 【脱敏】 于 2021-05-12T11:27:04.000Z 通过 Tag Editor 新增 project:voice 的 tag [1]，其中指定了 8 个 CloudFormation Stack 以及 2 个 ssm Parameter。
- 在同一个时间点前后 2021-05-12T11:27:04.000Z，确实有多个 UpdateStack 操作[1]。然而细部查找这些 Stack，未能查找到是哪个 Stack 更新了 Lambda 函数 k8s-api-vpc-connector-EKS-JYSGWAUO。
  我进一步查看这些 Stack 观察到里面有许多自定义的资源类型。对照到我的测试环境，我推测 Lambda 函式应该是由自定义的资源，或是此 template 所建立的 CloudFormation registry [2]来产生。您也可以参考截图[3][4]，这是我从 template 所创建出的 stack，其中包含 CloudFormation registry AWSQS::EKS:Cluster，您也可以您的 stack - "Kubesphere-prod-EKSClusterStack-OVCOTQYXJYI2-EKSStack-1GQ072DXVON0Q-EKSControlPlane-285FDEO16IR4/dbc2da60-8b8a-11eb-b460-0a63a40afddf" 查找到相同的资源。

- 后续如您所观察到 k8s-api-vpc-connector-EKS-JYSGWAUO 共被更新三次，最后一次更新时间为 2021-05-12T11:32:23.000Z
- 查看 Lambda 函数 k8s-api-vpc-connector-EKS-JYSGWAUO 指标，确实大约在 2021-05-12T11:32 有执行过的纪录[5]
- 对照您的 api-server-audit "aws-auth-updated.json" 档案， configmap 被修改的时间约为 2021-05-12T11:32:24.462147Z，与上述 Lambda 修改及操作的时间接近。对照 Source IP 【脱敏】，同样也是此 Lambda Function 所使用。

基于上述的信息以及我这端的测试，确实可以观察到的 Tad Editor 为 Stack 添加 tag 时，Lambda 函式会被触发 k8s-api-vpc-connector-EKS-*******。
为了进一步查找细部信息，我尝试将 k8s-api-vpc-connector-EKS-******* 的代码导出检查，然而此函式的代码已被打包为 Binary 档案，另一方面我也尝试以 k8s-api-vpc-connector-EKS 作为关键字，搜索有关的信息，当前仅查看到此 go 页面，当中虽然有类似的函式名称，但我尝试从此 github repo 搜索并未看到相关的代码[6]，可能的 Hanlder package[7] 也已被打包成 Binary 档案。 基于当前所能获取信息，我无法再细部查看此代码的内容来定位到更细部的原因。

由于此份 Template 是由青云共同开发，当中有些关键的 package 及 Lambda 代码我们当前无法查找到更细部的信息，建议您可以考虑我们的文档[8]，通过 eksctl 或是网页控制台来搭建环境较为单纯的 EKS 使用。

上述的信息我也和您的 TAM 【脱敏】同步，若您对上述有任何问题或疑虑，您可以随时回复此案例让我们知道，我们很乐意协助您！

**Comment by ruiyaoOps** [comment]
This lambda is to control Eks access authorization, just like after creating Eks, you need to create a cluster IAM role and attach the required Amazon EKS IAM managed policy to it.
EKS's external access authorization cannot be controlled by Kubesphere. This is neither reasonable nor necessary.
You can find more information about aws-auth at https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html
I don't know where you found tech support, but he doesn't seem to know anything.
