### ISSUE TITLE
Provide an API endpoint of KS to trigger a regular Pipeline

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/kubesphere#3891]
**What's it about?**

![image](https://user-images.githubusercontent.com/1450685/118579967-9a495380-b7c1-11eb-946f-1bd7ecdd2eed.png)

**What's the reason why we need it?**

Currently, ks only offer a description of the Pipeline remote build trigger. But users need to use Jenkins endpoint instead of ks endpoint. This is not appropriate.

We need two parts:
* backend
  * provide an endpoint
* front-end
  * modify the description on the regular Pipeline page

**Area Suggestion**

/kind feature-request
/area devops
/priority high

**Comment by LinuxSuRen** [comment]
The remote trigger feature relies on auth. In another word, it can not be triggered without any auth. So, there's no big difference between using API and a remote trigger.

I'd prefer to use https://github.com/LinuxSuRen/ks-devops/pull/13 to replace the remote trigger.

**Comment by wynn5a** [comment]
Hello, 
I am try to figure out how to use Kubesphere devops pipeline with gitlab events as remote trigger, but I failed to find any  helpful documents for this scenario.

[This is all I get](https://v3-1.docs.kubesphere.io/zh/docs/devops-user-guide/how-to-use/pipeline-settings/)

Do you have any suggestions for this? 
Thanks

**Comment by LinuxSuRen** [comment]
I don't recommend you use the remote trigger. Please use the webhook instead. But if you do really want to use the remote trigger. Please read me description from Jenkins Pipeline UI.

**Comment by LinuxSuRen** [comment]
I'm going to close this issue. Users might be able to use the [generic webhook](https://github.com/kubesphere-sigs/ks-devops/pull/13) in the next minor version.

/close
