### ISSUE TITLE
Cannot run svn Pipeline due to missing branch.

### ISSUE THREAD

**Issue by ysjjovo** [kubesphere/kubesphere#3895]
**Describe the Bug**
I follow the [instruction](https://kubesphere.io/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile/)
to create a git pipline,it succeed!,but when I modify jenkinsfile,remove git parts,then create a new pipline with svn source.
It failed with no error tips.whether the browser console or jenkins pods logs,screens snapshot shows below.
![image](https://user-images.githubusercontent.com/4216579/118749853-e8795800-b890-11eb-9ae5-5b8abed35360.png)

![image](https://user-images.githubusercontent.com/4216579/118749764-c1228b00-b890-11eb-9644-80fe98a33b79.png)

**Versions Used**
KubeSphere: v3.0.0
Kubernetes: (If KubeSphere installer used, you can skip this)
v1.18.0

**Environment**
How many nodes and their hardware configuration:  
CentOS Linux release 7.6.1810 (Core) 1 master ;4 nodes;

**Comment by LinuxSuRen** [comment]
hi @ysjjovo , thanks for reaching out to us. When you click the `Run` button, the frontend will call the API from `ks-apiserver`. So, I guess you might be able to find some clues from the log output of `ks-apiserver`. Hopefully I can help you.

By the way, v3.1.0 already released for a while. I'd suggest that you try to use v3.1.0 if you don't have a particular reason.

/kind support
/area devops

**Comment by ysjjovo** [comment]
I already resolved it.It seems svn repo must have a branch,for example trunk.When I create a trunk directory in the repo root,put all the content into it,It works!I think If ks-apiserver gives some tips about it would be more friendly to user.

**Comment by ysjjovo** [comment]
> hi @ysjjovo , thanks for reaching out to us. When you click the `Run` button, the frontend will call the API from `ks-apiserver`. So, I guess you might be able to find some clues from the log output of `ks-apiserver`. Hopefully I can help you.
> 
> By the way, v3.1.0 already released for a while. I'd suggest that you try to use v3.1.0 if you don't have a particular reason.
> 
> /kind support
> /area devops

I already resolved it.It seems svn repo must have a branch,for example trunk.When I create a trunk directory in the repo root,put all the content into it,It works!I think If ks-apiserver gives some tips about it would be more friendly to user.

**Comment by LinuxSuRen** [comment]
I feel happy that you resolved this issue. But I still feel confused, how about you just create a Pipeline job in Jenkins with svn, what happened when you trigger it?

In order to make this issue be more accurate. I'm going to rewrite it. Please correct me if you have a better one.

/retitle Cannot run svn Pipeline due to missing branch.
