### ISSUE TITLE
Uninstall pluggable components

### ISSUE THREAD

**Issue by Sherlock113** [kubesphere/kubesphere#3903]
Hi, please provide the necessary commands here to uninstall pluggable components and I will put them in our Doc. This is the uninstallation doc in [3.0 Doc](https://v3-0.docs.kubesphere.io/docs/faq/installation/uninstall-pluggable-components/), which I believe is outdated for most components. Thank you.

- [ ] App Store.
- [ ] DevOps.
- [ ] Logging.
- [ ] Events.
- [ ] Alerting.
- [ ] Auditing.
- [ ] Service Mesh.
- [ ] Networkpolicies.
- [ ] Metrics Server.
- [ ] Service Topology.
- [ ] Pod IP Pools.

**Comment by Sherlock113** [comment]
Please take a look at this. Thank you. @zheng1 @LinuxSuRen @benjaminhuo @junotx @wanjunlei @zackzhangkai @zryfish

**Comment by Sherlock113** [comment]
@zhu733756 As for KubeEdge, I reckon users can refer to [this part](https://kubesphere.io/docs/installing-on-linux/cluster-operation/add-edge-nodes/#remove-an-edge-node) directly if they want to uninstall it?

**Comment by zhu733756** [comment]
Yes.

**Comment by zackzhangkai** [comment]
servicemesh:


```bash
curl -L https://istio.io/downloadIstio | sh -
istioctl x uninstall --purge

kubectl -n istio-system delete kiali
helm -n istio-system delete kiali-operator

helm -n istio-system delete jaeger-operator
```

**Comment by benjaminhuo** [comment]
https://github.com/kubesphere/ks-installer/issues/924
We have a similar issue to collect uninstall script, most of the content is still valid
