### ISSUE TITLE
Failed to build a service through the artifact

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#3906]
**Describe the Bug**

Failed to build a service through the artifact, default builder template seems not selected.

![image](https://user-images.githubusercontent.com/8263040/119099512-8dd72c00-ba49-11eb-8dfa-323a892d2116.png)

![image](https://user-images.githubusercontent.com/8263040/119099526-92034980-ba49-11eb-8b3a-53f642818c74.png)

**Versions Used**
KubeSphere: v3.1.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Expected behavior**
Select the first builder template by default.

/kind bug
/area console
/assign @kubesphere/sig-console

**Comment by JohnNiang** [comment]
I have reported this problem in <https://github.com/kubesphere/console/issues/1908>.
