### ISSUE TITLE
After deleting workspace, the app templates  will not be deleted.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3915]
**Versions Used**
KubeSphere:  `kubesphere3.1`
Kubernetes:   `v1.20.4`

**Preset conditions**
There is a workspace named 'test-ws'

**How To Reproduce**
1. Go to workspace 'test-ws'
2. Create a template named 'app-test'
3. Delete workspace 'test-ws' 
4. Create a workspace named 'test-ws'
5. Go to workspace 'test-ws'
6. View App Templates

**Expected behavior**
There is no template in 'app templates' page

**Actual behavior**
Template 'app-test' in 'app templates' page

/kind bug
/milestone 3.1.1
/assign @xyz-li 
/priority medium

**Comment by xyz-li** [comment]
Duplicate of #3614

**Comment by wenxin-01** [comment]
issue fixed in `3.2.1-rc.2`
