### ISSUE TITLE
Canary Release set traffic comes from linux systems did not work

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3927]
**Versions Used**
KubeSphere: `nightly-20210530`
Kubernetes:  `v1.20.4`

**Environment**

**How To Reproduce**
1. Deploy app 'bookinfo'
2. Create 'Canary Release'
3. Edit 'Forward by request content'
4. Select 'linux' in 'Traffic comes from the following operating systems'
![image](https://user-images.githubusercontent.com/68640256/120183836-cf828680-c242-11eb-8590-b4b2bea53272.png)
5. Visit 'bookinfo' in 'Linux' 
`Linux version 3.10.0-1160.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44)`

**Expected behavior**
Visit new version
**Actual behavior**
Visit old version

/kind bug
/priority medium
/milestone 3.1.1
/assign @zackzhangkai

**Comment by zackzhangkai** [comment]
https://github.com/kubesphere/kubesphere/pull/3902
