### ISSUE TITLE
Deprecate NFS using with Kubesphere

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/kubesphere#3951]
**Describe the Bug**
We have many users (community users and business users) reported that they encountered various NFS issues when using with Kubesphere, e.g.
https://kubesphere.com.cn/forum/d/610-kubsphere-mysql-nfs-lock
https://kubesphere.com.cn/forum/d/3690-nfskubespheremysql-ibdata1
https://kubesphere.com.cn/forum/d/2633-ks30-es
https://kubesphere.com.cn/forum/d/990-kubesphere-system-etcd-error
https://kubesphere.com.cn/forum/d/2562-nfs/4

The problems include failed to obtain lock, input/output error, bad performance etc, and the impacted softwares include mysql, etcd, elasticsearch, prometheus etc. The symptom usually is unable to start the applicaiton/pod or pod crashloopbackoff because the mentioned problems.

We're pretty sure these problems are not caused by Kubesphere, and these problems are often very difficult to debug/resolve. We're not NFS experts and we won't waste time on debugging pure NFS issues.

That's to say, we should emphasis in our website (kubesphere.io/documentation) thats NFS is not recommended storage system and everyone will use it with own risks.

**Versions Used**
KubeSphere: all versions
Kubernetes: all versions

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by Sherlock113** [comment]
I see...I will add some notes in our doc.

**Comment by stoneshi-yunify** [comment]
ref: https://github.com/prometheus/prometheus/blob/03b354d4d9386e4b3bfbcd45da4bb58b182051a5/docs/storage.md#operational-aspects

Prometheus doesn't recommend NFS as its storage.

```
CAUTION: Non-POSIX compliant filesystems are not supported for Prometheus' local storage as unrecoverable corruptions may happen. NFS filesystems (including AWS's EFS) are not supported. NFS could be POSIX-compliant, but most implementations are not. It is strongly recommended to use a local filesystem for reliability.
```

**Comment by stoneshi-yunify** [comment]
ref: https://www.frakkingsweet.com/elasticsearch-nfs-and-locking-issues/
Elasticsearch failed to start with NFS

**Comment by stoneshi-yunify** [comment]
ref: https://kubesphere.com.cn/forum/d/4676-openebsnfsmonitoring-prometheus
nfs-client doesn't support k8s v1.20 and later versions

**Comment by dkeven** [comment]
> ref: https://kubesphere.com.cn/forum/d/4676-openebsnfsmonitoring-prometheus
> nfs-client doesn't support k8s v1.20 and later versions

To be more clear, the issue in this post is due to the particular old version of nfs-client used in KubeSphere helm chart (which is referenced in KS official doc), and will be fixed once [this PR](https://github.com/kubesphere/helm-charts/pull/145) is merged.

**Comment by Sherlock113** [comment]
Fixed in https://github.com/kubesphere/website/pull/1702.
