### ISSUE TITLE
Can filter function be added to pipeline?

### ISSUE THREAD

**Issue by yinmin2020** [kubesphere/kubesphere#3959]
**The problem**
When there are many pipelines, there is no filtering function and it is not easy to query the pipeline

**Want to solve**
Hope to add screening function, screening conditions hope is: create account, branch, etc

**Comment by VioZhang** [comment]
provide detail

**Comment by VioZhang** [comment]
The detail about the requirement:
Background:
1. There is a user scenario where we need to search the pipeline by the account name which created the pipeline esprcially when we log in the system through LDAP .
2. There are some highly frequent pipelines that the users need to check about ,and it would be better that there is a history selector helping the users to do it . And we‘d better make it stay the condition when we enter in the selected pipeline and return the last page .

Requirement:
1.Add the create user field in the pipeline list.
![pipeline create user.png](https://i.loli.net/2021/06/21/sCQBwzFnEc61HqX.png)
2.Add a condition filter in the pipeline list, through which we can search pipelines by Name , WeatherScore and create user. Such as the follow image.
![pipeline create user.png](https://i.loli.net/2021/06/21/sCQBwzFnEc61HqX.png)
![通知条件过滤2.png](https://i.loli.net/2021/06/21/FjCJlH3e9anxWRr.png)
3.Stay the filter condition when we enter in the selected pipeline and return the last page .

/cc @kubesphere/sig-devops
/remove-triage needs-information

**Comment by JohnNiang** [comment]
Hi @yinmin2020 , there's one thing we need to be sure of what filters should we provide exactly.
