### ISSUE TITLE
Support more storage quotas

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/kubesphere#3972]
**What's it about?**

storage quota in a given namespace

**What's the reason why we need it?**

ref: https://kubernetes.io/docs/concepts/policy/resource-quotas/#storage-resource-quota

So there are 4 types of storage quotas and currently ks only supports quota of `persistentvolumeclaims`, I saw many users are asking for the others. It will be nice we support all of them in ks-console.

**Area Suggestion**

/kind feature-request

**Comment by stoneshi-yunify** [comment]
ks v3.1.1 allows user to add customized quotas include storage quotas. So this issue has been solved.

**Comment by kkhung0829** [comment]
How to add customized quotas (including storage quotas) ? Can found any doc for it .
