### ISSUE TITLE
Internal Server Error for monitor

### ISSUE THREAD

**Issue by Goldenteamway** [kubesphere/kubesphere#3980]
how to resolve this error:
![image](https://user-images.githubusercontent.com/44332392/122525390-c28bd280-d04b-11eb-8828-284fe95aa02a.png)
this is ks-apiserver logs:
![image](https://user-images.githubusercontent.com/44332392/122525592-f7982500-d04b-11eb-847e-e9b722bf1f9d.png)
ks-console logs:
![image](https://user-images.githubusercontent.com/44332392/122526369-ca984200-d04c-11eb-96b2-6494dfcd849e.png)

**Comment by Goldenteamway** [comment]
kubesphere v3.1.0

**Comment by zhu733756** [comment]
The namespaced metrics missed.  As we discussed in the forum, It is recommended to re-upgrade with kubekey.
