### ISSUE TITLE
AI support?

### ISSUE THREAD

**Issue by gumowangfei** [kubesphere/kubesphere#3981]
Hello, does the current version support AI training, deployment, and inference?

**Comment by zhu733756** [comment]
No, you can install kube-flow or other platforms. The basic metrics can be visible  from the console. Later, we will make a  better support for it.

**Comment by zhu733756** [comment]
> No, you can install kube-flow or other AI integration tools. The basic metrics can be visible from the console. Later, we will make a better support for it.

BTW, you can use the gpu monitoring dashboard located at [here](https://github.com/kubesphere/monitoring-dashboard/blob/master/contrib/gallery/nvidia-gpu-dcgm-exporter-dashboard.yaml), or a cluster dashboard needs to convert the kind field to ` ClusterDashboard`  and  remove the given namespace field.
