### ISSUE TITLE
403 error when workspace manager role user viewing the monitoring of the workload

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3986]
**Describe the Bug**

1.The user has a Workspace Manager role
2.Go into the project and create the deployment
3.Go to the monitoring page in the depolyment details page

**Expected behavior**
The monitoring information can be viewed successfully
**actually behavior**
the page report error 403
![image](https://user-images.githubusercontent.com/36271543/123054080-17a65a80-d437-11eb-8489-a35864b3833d.png)

**Versions Used**
KubeSphere: ks v3.1.1

/kind bug
/assign @junotx 
/priority High
/milestone v3.1

**Comment by wansir** [comment]
The monitoring API does not match the K8s [API pattern](https://kubernetes.io/docs/reference/using-api/api-concepts/), incorrect request info will affect authorization. 

/assign @kubesphere/sig-observability

**Comment by benjaminhuo** [comment]
The monitoring API has to be handled specially

**Comment by liuyp2018** [comment]
Error 403 occur when user with Workspace Manager role accessing the grayscale publication -->task status page 
![image](https://user-images.githubusercontent.com/36271543/123619576-e44f3b80-d83b-11eb-9d4a-bcc942fbcc39.png)

**Comment by liuyp2018** [comment]
![image](https://user-images.githubusercontent.com/36271543/123620505-e5cd3380-d83c-11eb-8caf-ebfc906e9769.png)

**Comment by liuyp2018** [comment]
![image](https://user-images.githubusercontent.com/36271543/123620681-13b27800-d83d-11eb-9222-776e7ee1a16f.png)

**Comment by liuyp2018** [comment]
![image](https://user-images.githubusercontent.com/36271543/123727384-215f1080-d8c4-11eb-8010-94f375889465.png)

/assign @wansir

**Comment by liuyp2018** [comment]
![image](https://user-images.githubusercontent.com/36271543/123727641-874b9800-d8c4-11eb-99ae-d8cfca6e5e72.png)

**Comment by liuyp2018** [comment]
![image](https://user-images.githubusercontent.com/36271543/123727715-a518fd00-d8c4-11eb-91a3-6c41e51be3cd.png)
![image](https://user-images.githubusercontent.com/36271543/123727737-aea26500-d8c4-11eb-89c8-1a6ec656d48a.png)

**Comment by liuyp2018** [comment]
![image](https://user-images.githubusercontent.com/36271543/123727882-f0331000-d8c4-11eb-91a6-3db7f27273fc.png)

**Comment by liuyp2018** [comment]
![image](https://user-images.githubusercontent.com/36271543/123728036-3a1bf600-d8c5-11eb-9517-a716cb8bb875.png)
![image](https://user-images.githubusercontent.com/36271543/123728096-5750c480-d8c5-11eb-8cae-abb1620b1e21.png)
![image](https://user-images.githubusercontent.com/36271543/123728216-86ffcc80-d8c5-11eb-8b56-b42552868048.png)
