### ISSUE TITLE
Incorrect data when editing workspace resource quota

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#3987]
**Describe the Bug**

Multi cluster environment, incorrect data displayed while editing workspace resource quota.

![image](https://user-images.githubusercontent.com/8263040/123085787-3d425c80-d455-11eb-8e92-27726ea25204.png)

**Versions Used**
KubeSphere: v3.1.0

/kind bug
/area console
/assign @kubesphere/sig-console 
/milestone v3.1

**Comment by liuyp2018** [comment]
Multi cluster environment, problem exists while entering workspace resource quota page.
![image](https://user-images.githubusercontent.com/36271543/123897162-7e76c700-d995-11eb-9532-be490624adbb.png)

/remove-kind need-to-verify

**Comment by wansir** [comment]
I found that the API path already contains the cluster, the resource quota is not set?

**Comment by liuyp2018** [comment]
The interface reports 404 error when entering the quota setting page

**Comment by wansir** [comment]
By design, if resource quota is not set for the cluster the HTTP status code is 404.

**Comment by liuyp2018** [comment]
ok, in that case, the issue can be closed
