### ISSUE TITLE
KubeSphere 3.1.0 得不到集群基本信息

### ISSUE THREAD

**Issue by hvsop** [kubesphere/kubesphere#3988]
我是新手，安装了k8s 1.20.7 + kubesphere 3.1.0版本之后，左侧导航栏点击监控告警-->集群状态，可以看到集群资源使用情况，但是点击导航栏集群设置，基本信息，看到的节点数量是0，cpu/内存/存储的值都是0。有没有人帮忙debug一下，是哪里出错了呢？

需要我提供其他什么信息，请告诉我。谢谢！

**Comment by FeynmanZhou** [comment]
English only in GitHub. Chinese communication is recommended on [Chinese Forum](https://kubesphere.com.cn/forum/t/Monitoring&Logging).

You can also find similar issues and answers from [Chinese Forum](https://kubesphere.com.cn/forum/t/Monitoring&Logging).
