### ISSUE TITLE
the service monitor for the service creating by the specified workload  is not shown on the page after creating 

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3993]
**Describe the Bug**
1. Create a workload named 'd1'
2. Create the service by specifying the workload, specifying the workload with ' d1 '.
3. Enter the details page of the service and create Service Monitor for the service
4. After creation, the Service Monitor is not displayed in the view page
5. Enter the crd page of the Service Monitor and see that the Service Monitor of the service exists in the page

![image](https://user-images.githubusercontent.com/36271543/123199213-02860600-d4e1-11eb-9b7f-2fa643e494f4.png)

**Versions Used**
KubeSphere: v3.1.1
ks-console image : kubespheredev/ks-consloe:latest

/kind bug
/assign @harrisonliu5 
/priority medium
/milestone v3.1

**Comment by harrisonliu5** [comment]
`apis/clusters/host/monitoring.coreos.com/v1/namespaces/p/servicemonitors?labelSelector=app%3Dd1`

![image](https://user-images.githubusercontent.com/17872673/123211438-0c663400-d4f6-11eb-8fc3-4da32905169a.png)

**Comment by junotx** [comment]
@harrisonliu5 why is the `labelSelector` parameter in the url set to `app=d1`

**Comment by junotx** [comment]
The value of `app` label in the servicemonitor currently was set to the name of service, so set `labelSelector` parameter to `app=<service-name>` to query @harrisonliu5

**Comment by liuyp2018** [comment]
fixed
