### ISSUE TITLE
multi clusters deployed app, if delete one of clusters 'cluster-a',when will app in 'cluster-a' be deleted? or need Manually delete？

### ISSUE THREAD

**Issue by qingfeng777** [kubesphere/kubesphere#3994]
**What's it about?**
multi clusters deployed app

**What's the reason why we need it?**
just a question

multi clusters deployed app, if delete one of clusters 'cluster-a',when will app in 'cluster-a' be deleted? or need Manually delete？

**Area Suggestion**
> /area devops
> /area documentation

/kind feature-request

**Comment by yuswift** [comment]
Hi, I think we have discussed the issue on slack. Please reopen the issue if have other questions.
/close
