### ISSUE TITLE
Multi-cluster projects appear in the project list of a cluster

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#4016]
**Versions Used**
KubeSphere:  host `v3.1.1-rc.0`  memeber `v3.1`

**How To Reproduce**

https://user-images.githubusercontent.com/68640256/123781123-715ec700-d906-11eb-9a42-972f28f62913.mov

![image](https://user-images.githubusercontent.com/68640256/123781375-bf73ca80-d906-11eb-8692-a6e29e305b37.png)

/kind bug
/assign @wansir
/priority Medium
/milestone 3.1.1

**Comment by wansir** [comment]
Using label selector `kubesphere.io/kubefed-host-namespace!=true` to filter out namespaces.

/assign @kubesphere/sig-console

**Comment by wenxin-01** [comment]
issue fixed `v3.1.1-rc.1`
