### ISSUE TITLE
kubesphere return 400 status code for k8s api request which should return 422 and detailed information

### ISSUE THREAD

**Issue by zousheng** [kubesphere/kubesphere#4017]
**What's it about?**

It's about api response when deployment spec params not met the condition like resource request > resource limit. resp is 400 instead of 422 and details 
**What's the reason why we need it?**

when create or update deployment, and user configurd wrong for some spec field, and the response is 400. it should be k8s's response 422 and detailed information. This makes debugging much easier.

I believe this is an important feature for Kubesphere. There're a few use cases:

* case one
* case two
* ...

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

**Comment by wansir** [comment]
@zousheng 

K8s API request will forward to to kube-apiserver, whatever status code is 400 or 422 will be returned directly. ks-apiserver is a transparent proxy in a sense. Maybe you can provide more information, specific request messages.

![image](https://user-images.githubusercontent.com/8263040/123917878-dae9de80-d9b5-11eb-8a02-3022c64f759e.png)

https://github.com/kubesphere/kubesphere/blob/master/pkg/apiserver/filters/kubeapiserver.go

**Comment by zousheng** [comment]
thanks. I read the code, and the operation on webui is correct. My use case is, I used the deployment :

url:  /apis/clusters/host/apps/v1/namespaces/test/deployments,
method: POST
content-type: application/strategic-merge-patch+json
body: whole deployment json file
,
response is 

{
    "kind": "Status",
    "apiVersion": "v1",
    "metadata": {},
    "status": "Failure",
    "message": "the object provided is unrecognized (must be of type Deployment): couldn't get version/kind; json parse error: unexpected end of JSON input (<empty>)",
    "reason": "BadRequest",
    "code": 400
}.

The json body has kind and ApiVersion defined. 

Test with kubectl and same deployment json file,

I0701 11:23:37.581221   48850 request.go:1068] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Deployment.apps \"test\" is invalid: spec.template.spec.containers[0].resources.requests: Invalid value: \"3Gi\": must be less than or equal to memory limit","reason":"Invalid","details":{"name":"test","group":"apps","kind":"Deployment","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"3Gi\": must be less than or equal to memory limit","field":"spec.template.spec.containers[0].resources.requests"}]},"code":422}
F0701 11:23:37.582463   48850 helpers.go:115] The Deployment "test" is invalid: spec.template.spec.containers[0].resources.requests: Invalid value: "3Gi": must be less than or equal to memory limit

.  The kubectl test on k8s directly with api call kubesphere result is different. Very confusing

**Comment by zousheng** [comment]
@wansir I tested the post and patch method, and got the same error

**Comment by wansir** [comment]
> @wansir I tested the post and patch method, and got the same error

Could you provide the complete request message? The response will be consistent if the request is the same.

**Comment by zousheng** [comment]
Got the answer. Kubesphere indeed return 422 status and response body, but I set retry in http (with go-restry retry condition, status > 400 and status != 404) , after retrying the status changed to 400. I changed the retry codition to status =401 and status >=500, the problem was gone.

thanks for help
