### ISSUE TITLE
Installation hang there with no redis-ha-server created and redis-ha-proxy pods can't be created.

### ISSUE THREAD

**Issue by hvsop** [kubesphere/kubesphere#4022]
**What's your question**

The installation hang there, redis pods can't be created.

[root@kvm-10-115-6-11 demo]# kubectl -n kubesphere-system  get pods 
NAME                                     READY   STATUS             RESTARTS   AGE
ks-apiserver-6c6bcff4df-jxnw9            0/1     CrashLoopBackOff   9          25m
ks-apiserver-6c6bcff4df-q5wpr            0/1     CrashLoopBackOff   9          25m
ks-apiserver-6c6bcff4df-rb9h8            0/1     CrashLoopBackOff   9          25m
ks-console-7877478685-b22x7              1/1     Running            0          29m
ks-console-7877478685-rswml              1/1     Running            0          28m
ks-console-7877478685-wqjbn              1/1     Running            0          28m
ks-controller-manager-6ffb9df94c-5txt8   1/1     Running            0          25m
ks-controller-manager-6ffb9df94c-7fz64   1/1     Running            0          25m
ks-controller-manager-6ffb9df94c-lnkkq   1/1     Running            0          25m
ks-installer-6f4c9fcfcf-gfhvk            1/1     Running            0          31m
redis-ha-haproxy-68ff446d79-289pt        0/1     Init:0/1           2          18m
redis-ha-haproxy-68ff446d79-6s2mz        0/1     Init:0/1           3          29m
redis-ha-haproxy-68ff446d79-s8z55        0/1     Init:0/1           3          29m

**Environment: OS & Hardware Information**
CentOS 7.6 8C/16G/500G 
3Masters + 5 workers

**Error logs or message (Attach logs or screenshot)**
Error from server (BadRequest): container "haproxy" in pod "redis-ha-haproxy-68ff446d79-289pt" is waiting to start: PodInitializing

**Installer Version**

kubectl v1.20.7 with kubesphere v3.1.0

**Comment by hvsop** [comment]
I do have SC created:

[root@kvm-10-115-6-11 ~]# kubectl get sc
NAME                            PROVISIONER      RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
managed-nfs-storage (default)   fuseim.pri/ifs   Delete          Immediate           false                  14h

Please check the debug info as below:

[root@kvm-10-115-6-11 ~]# kubectl -n kubesphere-system get pods
NAME                                     READY   STATUS             RESTARTS   AGE
ks-apiserver-6c6bcff4df-jxnw9            0/1     CrashLoopBackOff   150        12h
ks-apiserver-6c6bcff4df-q5wpr            0/1     CrashLoopBackOff   150        12h
ks-apiserver-6c6bcff4df-rb9h8            0/1     CrashLoopBackOff   150        12h
ks-console-7877478685-b22x7              1/1     Running            0          12h
ks-console-7877478685-rswml              1/1     Running            0          12h
ks-console-7877478685-wqjbn              1/1     Running            0          12h
ks-controller-manager-6ffb9df94c-5txt8   1/1     Running            0          12h
ks-controller-manager-6ffb9df94c-7fz64   1/1     Running            0          12h
ks-controller-manager-6ffb9df94c-lnkkq   1/1     Running            0          12h
ks-installer-6f4c9fcfcf-gfhvk            1/1     Running            0          12h
redis-ha-haproxy-68ff446d79-289pt        0/1     Init:0/1           87         12h
redis-ha-haproxy-68ff446d79-6s2mz        0/1     Init:Error         88         12h
redis-ha-haproxy-68ff446d79-s8z55        0/1     Init:0/1           88         12h


[root@kvm-10-115-6-11 ~]# kubectl -n kubesphere-system describe pod ks-apiserver-6c6bcff4df-jxnw9
Name:         ks-apiserver-6c6bcff4df-jxnw9
Namespace:    kubesphere-system
Priority:     0
Node:         kvm-10-115-6-11/10.115.6.11
Start Time:   Wed, 30 Jun 2021 21:00:13 +0800
Labels:       app=ks-apiserver
              pod-template-hash=6c6bcff4df
              tier=backend
              version=v3.1.0
Annotations:  cni.projectcalico.org/podIP: 10.244.102.89/32
              cni.projectcalico.org/podIPs: 10.244.102.89/32
              kubectl.kubernetes.io/restartedAt: 2021-06-30T21:00:13+08:00
Status:       Running
IP:           10.244.102.89
IPs:
  IP:           10.244.102.89
Controlled By:  ReplicaSet/ks-apiserver-6c6bcff4df
Containers:
  ks-apiserver:
    Container ID:  containerd://39919caf690a0c5ba1105327abf2b9854ef2e9b30e9ab6e3819db28e6777da48
    Image:         kubesphere/ks-apiserver:v3.1.0
    Image ID:      docker.io/kubesphere/ks-apiserver@sha256:4f15c66506aa03b6c6e3928a6440bb2e3c43d13d6ee81bf8cfe73b02247d1c97
    Port:          9090/TCP
    Host Port:     0/TCP
    Command:
      ks-apiserver
      --logtostderr=true
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 01 Jul 2021 09:34:31 +0800
      Finished:     Thu, 01 Jul 2021 09:34:36 +0800
    Ready:          False
    Restart Count:  150
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:        20m
      memory:     100Mi
    Liveness:     http-get http://:9090/kapis/version delay=15s timeout=15s period=10s #success=1 #failure=8
    Environment:  <none>
    Mounts:
      /etc/kubesphere/ from kubesphere-config (rw)
      /etc/kubesphere/ingress-controller from ks-router-config (rw)
      /etc/localtime from host-time (rw)
      /var/run/docker.sock from docker-sock (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kubesphere-token-8sb7j (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  docker-sock:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:  
  ks-router-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      ks-router-config
    Optional:  false
  kubesphere-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kubesphere-config
    Optional:  false
  host-time:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/localtime
    HostPathType:  
  kubesphere-token-8sb7j:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubesphere-token-8sb7j
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly op=Exists
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 60s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 60s
Events:
  Type     Reason   Age                     From     Message
  ----     ------   ----                    ----     -------
  Warning  BackOff  3m42s (x3500 over 12h)  kubelet  Back-off restarting failed container
[root@kvm-10-115-6-11 ~]# kubectl -n kubesphere-system logs ks-apiserver-6c6bcff4df-jxnw9
W0701 09:39:41.942294       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0701 09:39:41.944401       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0701 09:39:41.959082       1 metricsserver.go:238] Metrics API not available.
Error: failed to connect to redis service, please check redis status, error: dial tcp: i/o timeout
2021/07/01 09:39:46 failed to connect to redis service, please check redis status, error: dial tcp: i/o timeout


[root@kvm-10-115-6-11 ~]#  kubectl -n kubesphere-system describe pod redis-ha-haproxy-68ff446d79-289pt
Name:         redis-ha-haproxy-68ff446d79-289pt
Namespace:    kubesphere-system
Priority:     0
Node:         kvm-10-115-6-11/10.115.6.11
Start Time:   Wed, 30 Jun 2021 21:07:17 +0800
Labels:       app=redis-ha-haproxy
              pod-template-hash=68ff446d79
              release=ks-redis
Annotations:  checksum/config: 46138f8b2005948188bc12c93b08a9c6460354af2db98eaa2158bcf1717e82de
              cni.projectcalico.org/podIP: 10.244.102.91/32
              cni.projectcalico.org/podIPs: 10.244.102.91/32
              prometheus.io/path: /metrics
              prometheus.io/port: 9101
              prometheus.io/scrape: true
Status:       Pending
IP:           10.244.102.91
IPs:
  IP:           10.244.102.91
Controlled By:  ReplicaSet/redis-ha-haproxy-68ff446d79
Init Containers:
  config-init:
    Container ID:  containerd://edc1cfc94dc84cc3fa04f533448712e6e8734fd6e7e15d3890b1585ff5657eb3
    Image:         haproxy:2.0.4
    Image ID:      docker.io/library/haproxy@sha256:cd4b3d4d27ae5931dc96b9632188590b7a6880469bcf07f478a3280dd0955336
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
    Args:
      /readonly/haproxy_init.sh
    State:          Running
      Started:      Thu, 01 Jul 2021 09:35:16 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 01 Jul 2021 09:27:30 +0800
      Finished:     Thu, 01 Jul 2021 09:35:01 +0800
    Ready:          False
    Restart Count:  87
    Environment:    <none>
    Mounts:
      /data from data (rw)
      /readonly from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from redis-ha-haproxy-token-gtkpn (ro)
Containers:
  haproxy:
    Container ID:   
    Image:          haproxy:2.0.4
    Image ID:       
    Port:           6379/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:8888/healthz delay=5s timeout=1s period=3s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /run/haproxy from shared-socket (rw)
      /usr/local/etc/haproxy from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from redis-ha-haproxy-token-gtkpn (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      redis-ha-configmap
    Optional:  false
  shared-socket:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  redis-ha-haproxy-token-gtkpn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  redis-ha-haproxy-token-gtkpn
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly op=Exists
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 60s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 60s
Events:
  Type     Reason   Age                    From     Message
  ----     ------   ----                   ----     -------
  Normal   Pulled   23m (x86 over 12h)     kubelet  Container image "haproxy:2.0.4" already present on machine
  Warning  BackOff  6m12s (x433 over 12h)  kubelet  Back-off restarting failed container

[root@kvm-10-115-6-11 ~]#  kubectl -n kubesphere-system logs redis-ha-haproxy-68ff446d79-289pt
Error from server (BadRequest): container "haproxy" in pod "redis-ha-haproxy-68ff446d79-289pt" is waiting to start: PodInitializing




Can anyone please help to advise what's wrong with my installation ? Same steps works fine in another cluster 1master+3workers ,but failed on this one (3masters + 5workers).

**Comment by hvsop** [comment]
I had reinstall the KubeSphere on my cluster, this time I can see the redis-ha-server-0   pod but it is still in pending status.

[root@kvm-10-115-6-11 ~]# kubectl -n kubesphere-system get pods 
NAME                                     READY   STATUS             RESTARTS   AGE
ks-apiserver-785fbdb85b-6bp2j            0/1     CrashLoopBackOff   205        17h
ks-apiserver-785fbdb85b-mvftr            0/1     CrashLoopBackOff   202        17h
ks-apiserver-785fbdb85b-xbv7s            0/1     CrashLoopBackOff   202        17h
ks-console-7877478685-nwzwx              1/1     Running            0          17h
ks-console-7877478685-vkpzq              1/1     Running            0          17h
ks-console-7877478685-xqqhm              1/1     Running            0          17h
ks-controller-manager-6c67dfbd8f-77v9j   1/1     Running            0          17h
ks-controller-manager-6c67dfbd8f-qvnjl   1/1     Running            0          17h
ks-controller-manager-6c67dfbd8f-r2c2g   1/1     Running            0          17h
ks-installer-6f4c9fcfcf-sprgg            1/1     Running            0          17h
redis-ha-haproxy-68ff446d79-2db98        0/1     Init:0/1           120        17h
redis-ha-haproxy-68ff446d79-vw6k6        0/1     Init:0/1           120        17h
redis-ha-haproxy-68ff446d79-wchds        0/1     Init:0/1           120        17h
redis-ha-server-0                        0/2     Pending            0          17h




[root@kvm-10-115-6-11 ~]# kubectl -n kubesphere-system logs redis-ha-haproxy-68ff446d79-wchds -c config-init
Waiting for service redis-ha-announce-0 to be ready (1) ...
Waiting for service redis-ha-announce-0 to be ready (2) ...
Waiting for service redis-ha-announce-0 to be ready (3) ...
Waiting for service redis-ha-announce-0 to be ready (4) ...
Waiting for service redis-ha-announce-0 to be ready (5) ...
Waiting for service redis-ha-announce-0 to be ready (6) ...
Waiting for service redis-ha-announce-0 to be ready (7) ...
Waiting for service redis-ha-announce-0 to be ready (8) ...


[root@kvm-10-115-6-11 ~]# kubectl -n kubesphere-system logs redis-ha-server-0 
error: a container name must be specified for pod redis-ha-server-0, choose one of: [redis sentinel] or one of the init containers: [config-init]

[root@kvm-10-115-6-11 ~]# kubectl -n kubesphere-system describe pod redis-ha-server-0 
Name:           redis-ha-server-0
Namespace:      kubesphere-system
Priority:       0
Node:           <none>
Labels:         app=redis-ha
                controller-revision-hash=redis-ha-server-85c4cd57b
                release=ks-redis
                statefulset.kubernetes.io/pod-name=redis-ha-server-0
Annotations:    checksum/init-config: 3536da7869ab409971a5b4fb4f3624e40b5484be59cba5ce0e741d5f28752cf7
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  StatefulSet/redis-ha-server
Init Containers:
  config-init:
    Image:      redis:5.0.5-alpine
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
    Args:
      /readonly-config/init.sh
    Environment:
      SENTINEL_ID_0:  76570abc73c20d3c0e6c21105777ed9b0898cb75
      SENTINEL_ID_1:  0c5b5dae5039679890d11c4d6b6fb66a08625c08
      SENTINEL_ID_2:  0b174d8f2a622ce4e7f303c67ce788c35729251d
    Mounts:
      /data from data (rw)
      /readonly-config from config (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from redis-ha-token-256z2 (ro)
Containers:
  redis:
    Image:      redis:5.0.5-alpine
    Port:       6379/TCP
    Host Port:  0/TCP
    Command:
      redis-server
    Args:
      /data/conf/redis.conf
    Liveness:     tcp-socket :6379 delay=15s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from redis-ha-token-256z2 (ro)
  sentinel:
    Image:      redis:5.0.5-alpine
    Port:       26379/TCP
    Host Port:  0/TCP
    Command:
      redis-sentinel
    Args:
      /data/conf/sentinel.conf
    Liveness:     tcp-socket :26379 delay=15s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from redis-ha-token-256z2 (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-redis-ha-server-0
    ReadOnly:   false
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      redis-ha-configmap
    Optional:  false
  redis-ha-token-256z2:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  redis-ha-token-256z2
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly op=Exists
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                    From               Message
  ----     ------            ----                   ----               -------
  Warning  FailedScheduling  2m34s (x932 over 17h)  default-scheduler  0/8 nodes are available: 8 pod has unbound immediate PersistentVolumeClaims.
  
  

[root@kvm-10-115-6-11 ~]# kubectl get pvc -A
NAMESPACE                      NAME                                 STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS          AGE
default                        test-claim                           Pending                                      managed-nfs-storage   19h
kubesphere-monitoring-system   prometheus-k8s-db-prometheus-k8s-0   Pending                                      managed-nfs-storage   17h
kubesphere-monitoring-system   prometheus-k8s-db-prometheus-k8s-1   Pending                                      managed-nfs-storage   17h
kubesphere-system              data-redis-ha-server-0               Pending                                      managed-nfs-storage   17h


I had already applied the patch "--feature-gates=RemoveSelfLink=false" to kube-apiserver, can anyone please help to advise what can I do right now? Thanks.

**Comment by yuswift** [comment]
Do you have a default storageclass?

**Comment by hvsop** [comment]
> Do you have a default storageclass?

yes I have:

NAME                            PROVISIONER      RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
managed-nfs-storage (default)   fuseim.pri/ifs   Delete          Immediate           false                  2d23h

**Comment by yuswift** [comment]
> > Do you have a default storageclass?
> 
> yes I have:
> 
> NAME PROVISIONER RECLAIMPOLICY VOLUMEBINDINGMODE ALLOWVOLUMEEXPANSION AGE
> managed-nfs-storage (default) fuseim.pri/ifs Delete Immediate false 2d23h

It looks like that the pvc can't be bound to pv. Please check your nfs server logs.
