### ISSUE TITLE
When the clusterRole of the added member cluster is set incorrectly, the prompt information is inaccurate

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#4038]
**Versions Used**
KubeSphere:  `v3.1.1-rc.1`

**Preset conditions**
There is a multi-cluster environment

**How To Reproduce**
1. Add member cluster
2. The clusterRole of member cluster is set incorrectly
3. jwtSecret set correctly

![image](https://user-images.githubusercontent.com/68640256/124233216-31d1ee00-db45-11eb-97bd-34c65d503f7b.png)

**Expected behavior**
Prompt the cause of the error accurately

/kind bug
/assign @wansir @harrisonliu5 
/priority Medium
/milestone 3.1.1

**Comment by wenxin-01** [comment]
issue fixed `v3.1.1-rc.1`
![image](https://user-images.githubusercontent.com/68640256/124539959-0d318b00-de51-11eb-8385-4e8fdfe0c2e0.png)

**Comment by wansir** [comment]
Similar problem, if the user is not synchronized to the member cluster authentication will fail, do not logout from the host cluster in this case.

![image](https://user-images.githubusercontent.com/8263040/127138472-cc21280d-84fb-4318-9c4b-707b5e83af63.png)


/reopen
