### ISSUE TITLE
When openpitrix is used for deployment, it will get stuck in the application configuration

### ISSUE THREAD

**Issue by yyt6200** [kubesphere/kubesphere#4046]
Operating environment：
system：CentOS Linux 7 (Core)
kubernetes： v1.19.10
kubesphere： v3.1.0
docker：20.10.6
**Kubernetes deployment mode：binary deployment**
**Kubesphere deployment mode：Minimal KubeSphere on Kubernetes**
From the browser console, it is found that the request URL contains an undefined response with "download file failed".
![image](https://user-images.githubusercontent.com/44914868/124689033-5e518580-df0a-11eb-9f2c-50430a0a97c2.png)
![image](https://user-images.githubusercontent.com/44914868/124688343-2d248580-df09-11eb-864c-d29466927745.png)
![image](https://user-images.githubusercontent.com/44914868/124688295-1a11b580-df09-11eb-85e7-5c67f45caa28.png)

**Comment by xyz-li** [comment]
Could you provide the log of ks-apiserver?

**Comment by yyt6200** [comment]
@xyz-li Thank you for you reply。
![image](https://user-images.githubusercontent.com/44914868/124708932-7f779d80-df2d-11eb-9f3b-a0f1de82cd6f.png)

**Comment by xyz-li** [comment]
Can you  view the details of other apps?

**Comment by yyt6200** [comment]
All apps are the same
![image](https://user-images.githubusercontent.com/44914868/124849724-dfc01b00-dfd1-11eb-9032-b73c0dc69cea.png)

**Comment by xyz-li** [comment]
Please run these commands.
`kubectl exec -ti $(kubectl  get po -n kubesphere-system -l app=minio -oname) -n kubesphere-system --  ls -al /data/`
`kubectl exec -ti $(kubectl  get po -n kubesphere-system -l app=minio -oname) -n kubesphere-system --  ls -al /data/app-store`

**Comment by yyt6200** [comment]
![image](https://user-images.githubusercontent.com/44914868/124851972-1c8e1100-dfd6-11eb-8b2b-dacb1838df68.png)

**Comment by xyz-li** [comment]
Looks like op job failed to upload charts data. 
Please provide the log of op job. You can just run this command `kubectl logs $(kubectl  get po -lapp=openpitrix -oname)`

**Comment by yyt6200** [comment]
This command cannot be executed. The prompt is as follows.
![image](https://user-images.githubusercontent.com/44914868/124856221-b3f66280-dfdc-11eb-9c54-35afbf928085.png)

**Comment by xyz-li** [comment]
`kubectl logs $(kubectl get po -lapp=openpitrix -oname -nkubesphere-system) -n kubesphere-system`

**Comment by yyt6200** [comment]
![image](https://user-images.githubusercontent.com/44914868/124879297-a7373600-dfff-11eb-92d5-574dbdf13cf3.png)

**Comment by yyt6200** [comment]
[root@k8s-master1 ~]# kubectl logs $(kubectl get po -lapp=openpitrix -oname -nkubesphere-system) -n kubesphere-system
I0515 03:36:37.902093       1 dumpconfig.go:22] configmap: authentication:
  authenticateRateLimiterMaxTries: 10
  authenticateRateLimiterDuration: 10m0s
  loginHistoryRetentionPeriod: 168h
  maximumClockSkew: 10s
  multipleLogin: True
  kubectlImage: kubesphere/kubectl:v1.19.0
  jwtSecret: "y87F3yIrbuC16gP5AF1pKwqP2Bxk3zCX"





network:
  ippoolType: none
openpitrix:
  s3:
    endpoint: http://minio.kubesphere-system.svc:9000
    region: us-east-1
    disableSSL: True
    forcePathStyle: True
    accessKeyID: openpitrixminioaccesskey
    secretAccessKey: openpitrixminiosecretkey
    bucket: app-store
monitoring:
  endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
W0515 03:36:37.903065       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0515 03:36:37.916431       1 import.go:163] start to create app, chart name: apisix, version: 0.1.7
I0515 03:36:37.941941       1 import.go:122] create category, name: Networking
I0515 03:36:37.949054       1 import.go:144] create category, name: Networking, icon: router
I0515 03:36:37.999634       1 import.go:248] start to create app version, chart name: apisix, version: 0.1.7
I0515 03:36:38.064080       1 import.go:326] create helm application version appv-86yn3plp4z4w5m success
I0515 03:36:38.064152       1 import.go:384] update app version status, chart name: apisix, version: 0.1.7
E0515 03:36:38.077541       1 import.go:404] update app version appv-86yn3plp4z4w5m status success
I0515 03:36:38.081325       1 import.go:163] start to create app, chart name: elasticsearch-exporter, version: 3.3.3
I0515 03:36:38.089918       1 import.go:122] create category, name: Prometheus Exporter
I0515 03:36:38.097425       1 import.go:144] create category, name: Prometheus Exporter, icon: export
I0515 03:36:38.131297       1 import.go:248] start to create app version, chart name: elasticsearch-exporter, version: 3.3.3
I0515 03:36:38.532317       1 import.go:326] create helm application version appv-yvkq2l8p4z4w5m success
I0515 03:36:38.532394       1 import.go:384] update app version status, chart name: elasticsearch-exporter, version: 3.3.3
E0515 03:36:38.732016       1 import.go:404] update app version appv-yvkq2l8p4z4w5m status success
I0515 03:36:38.733673       1 import.go:163] start to create app, chart name: etcd, version: 0.1.3
I0515 03:36:38.924727       1 import.go:122] create category, name: Database & Cache
I0515 03:36:39.126996       1 import.go:144] create category, name: Database & Cache, icon: database
I0515 03:36:39.531239       1 import.go:248] start to create app version, chart name: etcd, version: 0.1.3
I0515 03:36:39.929904       1 import.go:326] create helm application version appv-y9r6yn0lwow7z2 success
I0515 03:36:39.929976       1 import.go:384] update app version status, chart name: etcd, version: 0.1.3
E0515 03:36:40.133453       1 import.go:404] update app version appv-y9r6yn0lwow7z2 status success
I0515 03:36:40.150279       1 import.go:163] start to create app, chart name: harbor, version: 1.4.1
I0515 03:36:40.328583       1 import.go:122] create category, name: Image Registry
I0515 03:36:40.526817       1 import.go:144] create category, name: Image Registry, icon: cdn
I0515 03:36:40.939225       1 import.go:248] start to create app version, chart name: harbor, version: 1.4.1
I0515 03:36:41.331379       1 import.go:326] create helm application version appv-6vqxjvmoxzx13q success
I0515 03:36:41.331436       1 import.go:384] update app version status, chart name: harbor, version: 1.4.1
E0515 03:36:41.532719       1 import.go:404] update app version appv-6vqxjvmoxzx13q status success
I0515 03:36:41.536545       1 import.go:163] start to create app, chart name: memcached, version: 3.2.5
I0515 03:36:41.730541       1 import.go:122] create category, name: Database & Cache
I0515 03:36:42.133184       1 import.go:248] start to create app version, chart name: memcached, version: 3.2.5
I0515 03:36:42.529252       1 import.go:326] create helm application version appv-x72398o04z4w5m success
I0515 03:36:42.529328       1 import.go:384] update app version status, chart name: memcached, version: 3.2.5
E0515 03:36:42.730328       1 import.go:404] update app version appv-x72398o04z4w5m status success
I0515 03:36:42.735688       1 import.go:163] start to create app, chart name: minio, version: 6.0.5
I0515 03:36:42.931175       1 import.go:122] create category, name: Storage
I0515 03:36:43.127316       1 import.go:144] create category, name: Storage, icon: storage
I0515 03:36:43.538609       1 import.go:248] start to create app version, chart name: minio, version: 6.0.5
I0515 03:36:43.930683       1 import.go:326] create helm application version appv-6v470nj2xzx13q success
I0515 03:36:43.930754       1 import.go:384] update app version status, chart name: minio, version: 6.0.5
E0515 03:36:44.131326       1 import.go:404] update app version appv-6v470nj2xzx13q status success
I0515 03:36:44.133894       1 import.go:163] start to create app, chart name: mongodb, version: 0.3.2
I0515 03:36:44.330352       1 import.go:122] create category, name: Database & Cache
I0515 03:36:44.730810       1 import.go:248] start to create app version, chart name: mongodb, version: 0.3.2
I0515 03:36:45.188194       1 import.go:326] create helm application version appv-x7vn56z14z4w5m success
I0515 03:36:45.188271       1 import.go:384] update app version status, chart name: mongodb, version: 0.3.2
E0515 03:36:45.324895       1 import.go:404] update app version appv-x7vn56z14z4w5m status success
I0515 03:36:45.326419       1 import.go:163] start to create app, chart name: mysql, version: 1.6.8
I0515 03:36:45.526540       1 import.go:122] create category, name: Database & Cache
I0515 03:36:45.934125       1 import.go:248] start to create app version, chart name: mysql, version: 1.6.8
I0515 03:36:46.330972       1 import.go:326] create helm application version appv-nk271o561m17y0 success
I0515 03:36:46.331016       1 import.go:384] update app version status, chart name: mysql, version: 1.6.8
E0515 03:36:46.529250       1 import.go:404] update app version appv-nk271o561m17y0 status success
I0515 03:36:46.531681       1 import.go:163] start to create app, chart name: mysql-exporter, version: 0.5.6
I0515 03:36:46.731537       1 import.go:122] create category, name: Prometheus Exporter
I0515 03:36:47.133733       1 import.go:248] start to create app version, chart name: mysql-exporter, version: 0.5.6
I0515 03:36:47.529757       1 import.go:326] create helm application version appv-rx02oy88wow7z2 success
I0515 03:36:47.529826       1 import.go:384] update app version status, chart name: mysql-exporter, version: 0.5.6
E0515 03:36:47.732432       1 import.go:404] update app version appv-rx02oy88wow7z2 status success
I0515 03:36:47.736171       1 import.go:163] start to create app, chart name: nginx, version: 1.3.5
I0515 03:36:47.933422       1 import.go:122] create category, name: Networking
I0515 03:36:48.331521       1 import.go:248] start to create app version, chart name: nginx, version: 1.3.5
I0515 03:36:48.730882       1 import.go:326] create helm application version appv-wl0xmo7wr9rn7x success
I0515 03:36:48.730932       1 import.go:384] update app version status, chart name: nginx, version: 1.3.5
E0515 03:36:48.942986       1 import.go:404] update app version appv-wl0xmo7wr9rn7x status success
I0515 03:36:48.945368       1 import.go:163] start to create app, chart name: postgresql, version: 0.4.2
I0515 03:36:49.135364       1 import.go:122] create category, name: Database & Cache
I0515 03:36:49.544291       1 import.go:248] start to create app version, chart name: postgresql, version: 0.4.2
I0515 03:36:49.930434       1 import.go:326] create helm application version appv-6yxlymw6xzx13q success
I0515 03:36:49.930533       1 import.go:384] update app version status, chart name: postgresql, version: 0.4.2
E0515 03:36:50.139516       1 import.go:404] update app version appv-6yxlymw6xzx13q status success
I0515 03:36:50.141207       1 import.go:163] start to create app, chart name: rabbitmq, version: 0.3.2
I0515 03:36:50.336428       1 import.go:122] create category, name: Message Queueing
I0515 03:36:50.529083       1 import.go:144] create category, name: Message Queueing, icon: blockchain
I0515 03:36:50.930805       1 import.go:248] start to create app version, chart name: rabbitmq, version: 0.3.2
I0515 03:36:51.329763       1 import.go:326] create helm application version appv-0qy97n0r3m17y0 success
I0515 03:36:51.329804       1 import.go:384] update app version status, chart name: rabbitmq, version: 0.3.2
E0515 03:36:51.531911       1 import.go:404] update app version appv-0qy97n0r3m17y0 status success
I0515 03:36:51.535714       1 import.go:163] start to create app, chart name: radondb-mysql, version: 1.0.0
I0515 03:36:51.736431       1 import.go:122] create category, name: Database & Cache
I0515 03:36:52.135771       1 import.go:248] start to create app version, chart name: radondb-mysql, version: 1.0.0
I0515 03:36:52.530978       1 import.go:326] create helm application version appv-p68n95mq3ow7z2 success
I0515 03:36:52.531026       1 import.go:384] update app version status, chart name: radondb-mysql, version: 1.0.0
E0515 03:36:52.732000       1 import.go:404] update app version appv-p68n95mq3ow7z2 status success
I0515 03:36:52.733944       1 import.go:163] start to create app, chart name: redis, version: 0.3.5
I0515 03:36:52.937149       1 import.go:122] create category, name: Database & Cache
I0515 03:36:53.331433       1 import.go:248] start to create app version, chart name: redis, version: 0.3.5
I0515 03:36:53.729682       1 import.go:326] create helm application version appv-xoj6lj4zmz4w5m success
I0515 03:36:53.729736       1 import.go:384] update app version status, chart name: redis, version: 0.3.5
E0515 03:36:53.930037       1 import.go:404] update app version appv-xoj6lj4zmz4w5m status success
I0515 03:36:53.932592       1 import.go:163] start to create app, chart name: redis-exporter, version: 3.4.4
I0515 03:36:54.139434       1 import.go:122] create category, name: Prometheus Exporter
I0515 03:36:54.532606       1 import.go:248] start to create app version, chart name: redis-exporter, version: 3.4.4
I0515 03:36:54.930694       1 import.go:326] create helm application version appv-98zqkrjzkzx13q success
I0515 03:36:54.930750       1 import.go:384] update app version status, chart name: redis-exporter, version: 3.4.4
E0515 03:36:55.132966       1 import.go:404] update app version appv-98zqkrjzkzx13q status success
I0515 03:36:55.134957       1 import.go:163] start to create app, chart name: tomcat, version: 0.4.3
I0515 03:36:55.340712       1 import.go:122] create category, name: Web Server
I0515 03:36:55.528760       1 import.go:144] create category, name: Web Server, icon: ip
I0515 03:36:55.930720       1 import.go:248] start to create app version, chart name: tomcat, version: 0.4.3
I0515 03:36:56.366061       1 import.go:326] create helm application version appv-wzxw1zpo3m17y0 success
I0515 03:36:56.366105       1 import.go:384] update app version status, chart name: tomcat, version: 0.4.3
E0515 03:36:56.530784       1 import.go:404] update app version appv-wzxw1zpo3m17y0 status success

**Comment by xyz-li** [comment]
Did you remove the data in minio, op job has successfully upload data to minio.

If you want to restore the apps, you can run commands
`
kubectl delete happ --all
kubectl  get job -nkubesphere-system openpitrix-import-job -oyaml >job.yaml

kubectl delete -f job.yaml
kubectl apply -f job.yaml
`

**Comment by yyt6200** [comment]
Minio has been re installed. I don't know if it is the problem you described. I'll try your order. In addition, I would like to ask, when KS installer is updated, the contents of Jenkins CASC config will be reset. Is this a normal phenomenon

**Comment by xyz-li** [comment]
> Minio has been re installed. I don't know if it is the problem you described. I'll try your order. In addition, I would like to ask, when KS installer is updated, the contents of Jenkins CASC config will be reset. Is this a normal phenomenon

@LinuxSuRen
