### ISSUE TITLE
new feature about remove default apps in the app store

### ISSUE THREAD

**Issue by sunblack110** [kubesphere/kubesphere#4055]
Hi All,

I would like to delete all the apps in the app store, as we know that we have 15 apps in the store, I don't know where we can delete them. I don't want just unload them from app store, I would like where is these apps saved , in the local disk or from the Helm repo.

The reason why I would like to remove them is that I would like to build my own app store, in which we will submit some industry apps, it's not a tools, but some information applications, face to the user in the factory, they don't know anything about IT tools like Tomcat, Ngnix etc.

Thanks,
Han

**Comment by xyz-li** [comment]
This command will delete all the default apps in the app store.
```
kubectl delete happ -lapplication.kubesphere.io/builtin-app=true
```

**Comment by sunblack110** [comment]
Wow, that's great. Thanks very much

**Comment by kevinniu666** [comment]
tried to remove edge-mesh from app store, but encountered below error. Can anyone please help? Thanks.
