### ISSUE TITLE
ErrorInfo: failed calling webhook "logsidecar-injector.logging.kubesphere.io"

### ISSUE THREAD

**Issue by flycows01** [kubesphere/kubesphere#4056]
**When I enabled KubeSphere Logging System, Always report an error when creating a workload !**
Error Msg:
''' Internal error occurred: failed calling webhook "logsidecar-injector.logging.kubesphere.io": Post "https://logsidecar-injector-admission.kubesphere-logging-system.svc:443/?timeout=30s": x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0 '''

![image](https://user-images.githubusercontent.com/25563130/125405344-366e9000-e3ea-11eb-803c-912ee4f74824.png)

**other**
I believe this is an important feature for Kubesphere. but something is wrong, I had do like that:

* case one
Disabale KubeSphere Logging System:
logging:
    enabled: false
    logsidecar:
      enabled: false
* case two
[https://github.com/kubesphere/kubesphere/issues/2928](url)

but,None of this worked; Who can help me,please.

**Comment by tpiperatgod** [comment]
Here's a workaround, you can try this:
```shell
kubectl apply -f https://gist.githubusercontent.com/wansir/715eeefd3da0874272168ecd6925cfa5/raw/a452e5f2a429cd0356dfefc0ed81df8f797adcda/logsidecar-injector-certs.yaml
```

**Comment by flycows01** [comment]
The problem is solved，thanks a lot
