### ISSUE TITLE
When set replicas >1 of apiserver, you can not login ks

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#4060]
**Versions Used**
KubeSphere: `ks3.1.1`

**How To Reproduce**

![image](https://user-images.githubusercontent.com/68640256/125557940-a3177f39-47a9-40b4-99ea-d6e3cd2485c8.png)
![image](https://user-images.githubusercontent.com/68640256/125557989-027deeec-f570-4735-a460-50c6dfaf1d74.png)

/kind bug
/assign @wansir 
/priority High

**Comment by wansir** [comment]
By design, Redis needs to be installed in the case of multiple replicas. Using memory cache or redis depends on the number of ks-apiserver replicas.
