### ISSUE TITLE
View the cluster/project volume capacity error

### ISSUE THREAD

**Issue by yinmin090922** [kubesphere/kubesphere#4065]
Describe the Bug
On the cluster/project volume details page, the volume capacity information is different from the data set by the user.And all the volumes have the same capacity.

Versions Used
KubeSphere: v3.1.1

To Reproduce
1. Go to the cluster/project  'Storage'
2. Click on 'Volumes' and select any one of the volumes to view its details
3. See error:
   The volume capacity information is different from the data set by the user.And all the volumes have the same capacity.
![image](https://user-images.githubusercontent.com/50839324/125736263-f571efef-7732-42de-b204-8cd1d1343f1f.png)
![image](https://user-images.githubusercontent.com/50839324/125736274-e435fc5f-3166-4e6b-9ca1-fde88984c711.png)

Expected behavior
![image](https://user-images.githubusercontent.com/50839324/125736295-1cf49ec3-8f3f-46c2-90f9-5b54d6f3e7fa.png)
/kind bug
/assign @stoneshi-yunify
/priority medium

**Comment by stoneshi-yunify** [comment]
![image](https://user-images.githubusercontent.com/70880165/126254192-629105ef-5282-4252-bf89-e39809fbd4de.png)

Not a bug, it's working as design. Because this is a local storage.

/return
