### ISSUE TITLE
Proposal: Use beyondstorage/go-storage to replace s3 sdk

### ISSUE THREAD

**Issue by Xuanwo** [kubesphere/kubesphere#4069]
## Background

[BeyondStorage](https://beyondstorage.io/) is an open-source community that focused on cross-cloud data services, and [go-storage](https://github.com/beyondstorage/go-storage) is a vendor-neutral storage library for Golang aims at **Write once, run on every storage service**.

kubesphere depends on AWS S3 to store binaries like in https://github.com/kubesphere/kubesphere/tree/master/pkg/models/devops. It works for all s3 compatible services but not all, including azure and google cloud storage.

## Proposal

So I propose to replace s3 SDK with `go-storage`, so that we can store binaries on any storage services that are supported. (See [Service Integration Tracking](https://github.com/beyondstorage/go-storage/issues/536) for a list).

If this idea is OK, I will send a detailed proposal that includes the whole plan, migration route, and more.

---

Thanks for reading!

**Comment by LinuxSuRen** [comment]
hi @Xuanwo , thanks for your wonderful proposal.

We're working on a plan which makes DevOps be an independent cloud-native application. The DevOps project does use s3 as its storage backend. I'd like to see more details about your idea. Please don't forget to list the pros and cons of the solution.

You can get more details from the following links:

* https://github.com/kubesphere/kubesphere/issues/3962
* https://github.com/kubesphere-sigs/ks-devops
