### ISSUE TITLE
Move KubeSphere CI to Prow

### ISSUE THREAD

**Issue by zryfish** [kubesphere/kubesphere#4070]
**What's it about?**
Github workflows are great, very easy to use. But, it has several disadvantages for us:
1. We are under the free-tier account, workflows are limited by running duration, hardware configuration.
2. Permission is required to rerun failed tests, and it's not safe to give permission to any contributors. Problems will be solved by using ProwJobs.
3. It's not easy to leverage current community tools created by K8s team, we are sharing lots of development workflow in common. 

**What's the reason why we need it?**

**Area Suggestion**

/area performance
/area test

**Comment by yuswift** [comment]
Currently, we have migrated `testing` and `building` to prow. Are there any other works we need to do? BTW, IMO docs for prow are also needed cause the old docs are out of date.

**Comment by zryfish** [comment]
Yes, we have only moved for repo `kubesphere/kubesphere`, and lots of repos left to done. Sure, I'll update the docs later.

**Comment by yuswift** [comment]
> Yes, we have only moved for repo `kubesphere/kubesphere`, and lots of repos left to done. Sure, I'll update the docs later.

That's great. I think we need the docs first, then we can open pr for the left repositories by referring to it.
