### ISSUE TITLE
Scale Ingress Pod replicas on demand for Projects

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/kubesphere#4071]
**What's it about?**
As a Project admin, I need to scale Ingress Pod replicas on-demand.

**What's the reason why we need it?**
Currently, the Project Gateway can only be setup with default settings(1 Nginx Ingress Pod). The Nginx Ingress became the bottleneck when the workload increasing. Project admins should be able to adjust Nginx Ingress Pod numbers accordingly.
The project admins should also be able to monitor the CPU、Memory、 Networking for the Nginx Ingress Pods.
Besides the requirement above, we should also consider adding a quota to limit the max numbers of the Pods in the workspace level.

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/area console
/area microservice

/kind feature-request
/milestone v3.2

**Comment by zryfish** [comment]
I believe this can be covered by https://github.com/kubesphere/kubesphere/issues/3055. Mark as duplicated.

/close
