### ISSUE TITLE
Fail to delete\update cluster after update failed from 3.1.0 to 3.1.1 

### ISSUE THREAD

**Issue by badbruce** [kubesphere/kubesphere#4072]
**Describe the Bug**
Fail to delete\update cluster after update failed from 3.1.0 to 3.1.1 

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: 3.1.0
Kubernetes: 1.20.4(If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:
 CentOS 7.5 / 3 masters:  8cpu/16g; 3 nodes: 8cpu/16g
For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
First I use the words to update the cluster as follows:
`./kk upgrade --with-kubernetes v1.20.4 --with-kubesphere v3.1.1`
Which I actually means
`./kk upgrade --with-kubernetes v1.20.4 --with-kubesphere v3.1.1 -f sample.yaml`
So I tapped "ctrlC" to cancel the command,and then I tapped
`./kk delete cluster -f sample.yaml`
Then I get:
./kk delete cluster -f sample.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17c7a17]

goroutine 1 [running]:
github.com/kubesphere/kubekey/pkg/cluster/delete.ResetCluster(0x7ffdf1c3286a, 0xb, 0xc00070e000, 0x1, 0x1b87429, 0x4)
	/home/runner/work/kubekey/kubekey/pkg/cluster/delete/delete.go:44 +0xd7
github.com/kubesphere/kubekey/cmd.glob..func5(0x2e06800, 0xc000513a00, 0x0, 0x2, 0x0, 0x0)
	/home/runner/work/kubekey/kubekey/cmd/delete_cluster.go:14 +0x163
github.com/spf13/cobra.(*Command).execute(0x2e06800, 0xc0005139e0, 0x2, 0x2, 0x2e06800, 0xc0005139e0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x2e07a60, 0x0, 0x0, 0x2)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/kubesphere/kubekey/cmd.Execute()
	/home/runner/work/kubekey/kubekey/cmd/root.go:65 +0x125
main.main()
	/home/runner/work/kubekey/kubekey/cmd/kk/main.go:25 +0x20

**Expected behavior**

**Comment by pixiake** [comment]
Does the `sample.yam`  contain ClusterConfiguration ?
You can delete the ClusterConfiguration and try again.

**Comment by badbruce** [comment]
> Does the `sample.yam` contain ClusterConfiguration ?
> You can delete the ClusterConfiguration and try again.

It returns to normal after deleting the ClusterConfiguration
