### ISSUE TITLE
jenkins pipline问题

### ISSUE THREAD

**Issue by caicai19900921** [kubesphere/kubesphere#4077]
版本：v3.1.1
1.选择代码仓库无gitlab选项，请问是什么原因？
2.流水线支持原生jenkins中的 share library共享库的方式吗？如何加载share library共享库

**Comment by caicai19900921** [comment]
,

**Comment by qxx1994** [comment]
请问楼主 选择代码仓库无gitlab选项 最后解决了吗

**Comment by LinuxSuRen** [comment]
For Chinese speakers, please go to visit [this Chinese forum](https://kubesphere.com.cn/forum/) instead.
