### ISSUE TITLE
[v3.2/o11y/monitoring] GPU monitoring

### ISSUE THREAD

**Issue by benjaminhuo** [kubesphere/kubesphere#4082]
- [x] NVIDIA DCGM exporter installation
- [x] Support GPU monitoring through custom monitoring dashboard

/kind design
/area installation
/area monitoring
/area observability
/kind feature-request

**Comment by zhu733756** [comment]
## Background
To better integrate GPU monitoring, we need to solve GPU installation issues.
NVIDIA DCGM exporter exposes the metrics for GPU resources and Prometheus scrapies from it. Therefore, we can query the metrics through Prometheus query interfaces.
To support GPU monitoring through a custom dashboard,  we will import a standard GPU dashboard for monitoring the GPU metrics.
These CRDs will be applied to the KubeSphere plane if the GPU option is enabled in the Installation(ks-installer).

## Environmental preparation
- The master node that needs to join the GPU host with KubeSphere cloud control panel
- A properly configured GPU host runs the command `nvidia-smi` normally
   -  Install the `nvidia-docker` environment
   - Add nouveau to the blacklist
   - Driver installation
-  With KubeKey installed

## Plans
* [ ] NVIDIA DCGM exporter installation
* [ ] Support GPU monitoring through custom monitoring dashboard
