### ISSUE TITLE
need help! rook-ceph change glusterfs. There is a strange problem.

### ISSUE THREAD

**Issue by yyt6200** [kubesphere/kubesphere#4084]
**system version: centos7 
kubernetes version: 1.19.10
kubesphere version: 3.1.0**

Because the server is down and there is a problem with the storage of CEPH, we try to replace it with glusterfs. However, after deleting the hook CEPH and accessing glusterfs, we find that many components automatically installed by Ks report errors. The specific error is "unknown file system type" glusterfs "

There are Minio, openldap and other components with such problems, but KS Jenkins has no problems.

![1626790763-496988-image](https://user-images.githubusercontent.com/44914868/126345258-834e5095-60af-496b-a8a2-2de4d543b27e.png)

The following is a screenshot of the configuration information of the storageclass.

![1626790823-365403-image](https://user-images.githubusercontent.com/44914868/126345414-566a5eab-ba0a-4b0a-baff-3fa27ba47e9a.png)
![1626790835-598901-image](https://user-images.githubusercontent.com/44914868/126345638-c7b99290-b34f-495b-a02f-b319941a07e0.png)

**Comment by zoroglucihat** [comment]
Hi @yyt6200 I had similar issue with glusterfs not minio. How did you solve it?
