### ISSUE TITLE
[v3.2/Edge/KubeEdge] KubeEdge Integration Enhancement

### ISSUE THREAD

**Issue by benjaminhuo** [kubesphere/kubesphere#4086]
- [x] Upgrade KubeEdge to the latest version like 1.7+
- [x] Upgrade CRD version to v1
- [x] Fix bugs like https://github.com/kubeedge/kubeedge/issues/2921

/area edge
/kind feature-request

**Comment by zhu733756** [comment]
## Backgroud
We have integrated KubeEdge v1.5.1, v1.6.0, v1.6.1, v1.6.2 in the former work.
The latest KubeEdge version supports more [features](https://github.com/kubeedge/kubeedge/blob/master/CHANGELOG/CHANGELOG-1.7.md#kubeedge-v17-release-notes).
In the near future, we plan to upgrade the KubeEdge version to v1.7.0+ and need to fix the bug described at kubeedge/kubeedge#2921.

## Plans
- Upgrade KubeEdge to the latest version like 1.7+
-  Fix bugs like How to make a fixed metrics port for metrics server in version 1.7.0? kubeedge/kubeedge#2921

**Comment by benjaminhuo** [comment]
@zhu733756 The CRD is not upgrade to v1, right? So reopen this issue to track that

**Comment by zhu733756** [comment]
Yeah.

> @zhu733756 The CRD is not upgrade to v1, right? So reopen this issue to track that

**Comment by benjaminhuo** [comment]
KubeEdge CRDs have been upgraded to v1 in https://github.com/kubesphere/ks-installer/pull/1829
