### ISSUE TITLE
[v3.2] o11y/Edge/GPU plan

### ISSUE THREAD

**Issue by benjaminhuo** [kubesphere/kubesphere#4088]
- [x] https://github.com/kubesphere/kubesphere/issues/4087
- [x] https://github.com/kubesphere/kubesphere/issues/4081
- [x] https://github.com/kubesphere/kubesphere/issues/4082
- [x] https://github.com/kubesphere/kubesphere/issues/4148
- [x] https://github.com/kubesphere/kubesphere/issues/4149
- [x] https://github.com/kubesphere/kubesphere/issues/4150
- [x] https://github.com/kubesphere/kubesphere/issues/4083
- [x] https://github.com/kubesphere/kubesphere/issues/4086
- [x] https://github.com/kubesphere/kubesphere/issues/4169

/area console
/area edge
/area monitoring
/area notification
/area observability
/kind feature-request

**Comment by wanjunlei** [comment]
[v3.2/o11y/logging] Support external es which enabled HTTPS #4169
