### ISSUE TITLE
Supports more object fields in console when creating storageclass

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/kubesphere#4092]
**What's it about?**

![image](https://user-images.githubusercontent.com/70880165/126417487-127a63b8-7a86-4a53-b970-e0c122def5d2.png)

The ks-console doesn't support edit below fields:
- volumebindingmode
- allowedTopologies
- mountOptions

/area console
/milestone v3.2
/kind feature-request

**Comment by f10atin9** [comment]
Already fixed : https://github.com/kubesphere/console/pull/2220

**Comment by stoneshi-yunify** [comment]
The allowedTopologies and mountOptions are a bit complex to be configured via UI. So the decision is only putting volumebindingmode in the create sc UI.

verify in ks3.2 alpha.0,  looks good. thanks.
