### ISSUE TITLE
devops中jenkins构建过程问题

### ISSUE THREAD

**Issue by caicai19900921** [kubesphere/kubesphere#4097]
我们项目有现成的jenkinsfile，也不想移到kubesphere中，使用scm模式，但是需要使用到参数化构建（比如指定不同环境），且我不想用到input这种输入模式，请问有其他办法吗？

**Comment by FeynmanZhou** [comment]
English only in GitHub, please raise the Chinese questions on [Chinese Forum](https://kubesphere.com.cn/forum/).
