### ISSUE TITLE
ks-jenkins deploy often fail

### ISSUE THREAD

**Issue by yyt6200** [kubesphere/kubesphere#4098]
**system: centos7**
**k8s version: 1.19.10**
**kubesphere version: v3.1.0**

ks-Jenkins has raised the resource quota and provided JVM parameters, but the deployment failed. Moreover, even if Jenkins is successfully deployed, the UI page is very slow, especially in the system configuration of system management. It takes about 50 seconds to open the page.
![image](https://user-images.githubusercontent.com/44914868/126731194-d1f6f11f-859b-446f-a471-ff971de21e89.png)
![image](https://user-images.githubusercontent.com/44914868/126731260-9cb29846-0409-4114-931e-03a2c749ab98.png)
![image](https://user-images.githubusercontent.com/44914868/126731292-cf8c3aa4-151c-4539-b616-5ffb59af5120.png)

**Comment by yyt6200** [comment]
@LinuxSuRen Please, Mr. Rick, take a look

**Comment by yyt6200** [comment]
In addition, KS Jenkins does not always fail to deploy, and sometimes it can be deployed successfully. However, the successful deployment of Jenkins is also very slow to access, especially when the system configuration page is opened.
![image](https://user-images.githubusercontent.com/44914868/126734121-9d56c013-7b1f-43d6-9cae-a5b2f6a90427.png)

**Comment by LinuxSuRen** [comment]
> However, the successful deployment of Jenkins is also very slow to access, especially when the system configuration page is opened.

We didn't change anything of Jenkins. The best way is to push the Jenkins community to improve it. [Here](https://issues.jenkins.io/secure/Dashboard.jspa) is the issue system of the Jenkins community.

**Comment by yyt6200** [comment]
OK, thank you for your reply. At present, I'm not sure what caused the deployment failure. According to the relevant problems found in the forum, it is said to increase the quota, but after I increase it, I can't guarantee the successful deployment of KS Jenkins.

Finally, I'd like to ask whether the Jenkins configuration item involves the access restricted network, because it looks like some links are blocked. You can't open the system configuration until it times out.

@kubesphere/sig-devops

**Comment by JohnNiang** [comment]
Hi @yyt6200 , how about your machine configuration?

**Comment by yyt6200** [comment]
> Hi @yyt6200 , how about your machine configuration?

Hi,This is the configuration of the server
![image](https://user-images.githubusercontent.com/44914868/126855549-35a2538f-2215-43ab-b945-438ae78e2897.png)
This is the configuration assigned by the virtual machine
![image](https://user-images.githubusercontent.com/44914868/126855573-97d79643-3b16-4239-9a4f-d9ce20c48c33.png)

**Comment by JohnNiang** [comment]
You could have a look at ks-jenkins deployment monitoring:

![image](https://user-images.githubusercontent.com/16865714/126855783-b277eede-e3c2-4a8e-84dd-b610588c9f0b.png)

**Comment by yyt6200** [comment]
![image](https://user-images.githubusercontent.com/44914868/126855852-43eda4e4-ee52-43d1-8bf1-8e181229482a.png)

**Comment by JohnNiang** [comment]
Please raise JVM parameters(-Xmx4096m or higher) again.

**Comment by yyt6200** [comment]
According to your request, I adjusted Xmx to 5120. After many deployment tests, there are no more failures, but the opening of configure is still quite slow

**Comment by LinuxSuRen** [comment]
I'm glad that you fixed this problem.

> but the opening of configure is still quite slow

As I mentioned, the best way is that pushing the Jenkins community to improve it. But, IMO we don't rely on the UI too much. Because the best practice suggests we config Jenkins via CasC instead of UI.

**Comment by yyt6200** [comment]
OK, thanks for your help. I find it strange that Jenkins deployed separately outside the cluster do not have this problem, but the built-in KS Jenkins are like this. So I want to find out what causes it. Although we do not rely too much on Jenkins UI when using Devops

**Comment by LinuxSuRen** [comment]
Got you. Considering you've fixed this problem. Can we close this issue?

**Comment by yyt6200** [comment]
ok thx,
