### ISSUE TITLE
redisVolumSize should be redisVolumeSize in file cluster-configuration.yaml 

### ISSUE THREAD

**Issue by kuring** [kubesphere/kubesphere#4104]
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

File path: https://github.com/kubesphere/ks-installer/releases/download/v3.1.1/kubesphere-installer.yaml

The redisVolumSize should be redisVolumeSize.

in doc path: https://kubesphere.io/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack/
when run `cat cluster-configuration.yaml | grep VolumeSize` can't get the redisVolumSize, only get 3 volumes: openldapVolumeSize、elasticsearchMasterVolumeSize、jenkinsVolumeSize.

**Versions Used**
KubeSphere: 3.1.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by pixiake** [comment]
https://github.com/kubesphere/ks-installer/blob/ad0caeb0ebb95c38ba82bca2f1643aec8d55c18d/deploy/cluster-configuration.yaml#L44
