### ISSUE TITLE
The self-built application warehouse chart cannot be built

### ISSUE THREAD

**Issue by yinmin2020** [kubesphere/kubesphere#4105]
**Describe the Bug**
The chart that is packaged and uploaded can be successfully deployed in the command line mode, but an error message is displayed on the UI. Error is as follows
![image](https://user-images.githubusercontent.com/65068467/127792931-3f0bd3ab-347d-40e2-a390-f1c0765b21fd.png)
![image](https://user-images.githubusercontent.com/65068467/127792952-b399cdf1-62e2-47bf-90bb-c0f0b73fa24a.png)
**How To Reproduce**
1. The chart file is successfully uploaded and the application warehouse is selected. The warehouse builds a harbor by itself

2. Log in to ks to create the application, select the warehouse, select the newly uploaded chart, and click Deploy

3. Error (error is shown in the picture above)

**Comment by xyz-li** [comment]
@yinmin2020 Which chart do you use? This looks like the issue of go-yaml/yaml package.

**Comment by xyz-li** [comment]
Duplicate of #4115

**Comment by xyz-li** [comment]
Does the chart contains Chinese comment?
@yinmin2020

**Comment by yinmin2020** [comment]
> @yinmin2020 Which chart do you use? This looks like the issue of go-yaml/yaml package.

The YAML package is fine and can be created normally for use under helm
