### ISSUE TITLE
The new chart uploaded cannot be synchronized to ks platform in real time

### ISSUE THREAD

**Issue by yinmin2020** [kubesphere/kubesphere#4107]
**Describe the Bug**
After the self-built harbor uploaded chart, the KS platform could not synchronize the new chart in the new warehouse in real time. The newly uploaded chart can be displayed only after you enter the secret key and click authentication again

**Comment by xyz-li** [comment]
Add `sync_period` when create and update the helm repo. If this value is set to zero, then disable auto-synchronization. The minimum value of sync_period is 180.
