### ISSUE TITLE
The same account with different roles entered different items, menu display error

### ISSUE THREAD

**Issue by caojiele** [kubesphere/kubesphere#4109]
Bug recurrence operation: 
* A project, the role is admin, project Settings have advanced Settings menu;
![image](https://user-images.githubusercontent.com/29936718/127817761-997080db-45ac-42f9-bab7-b5c6762dd452.png)
* Then switch to project B, the role is operator, and there is no advanced setting menu in project Settings;
![image](https://user-images.githubusercontent.com/29936718/127817838-d104004b-9bcd-4aac-bb58-88c80e48c670.png)
* Finally click back to the A project, the advanced Settings are gone.
![image](https://user-images.githubusercontent.com/29936718/127817925-b05d3405-a617-4026-aca2-ae7a116abab6.png)

**Comment by JohnNiang** [comment]
Please let us know what's your environment and what's your account role in workspace as detailed as possible.

**Comment by caojiele** [comment]
> Please let us know what's your environment and what's your account role in workspace as detailed as possible.

KubeSphere version : v3.0.0, and roles are described above, the system default permissions are not customized.

**Comment by JohnNiang** [comment]
okay, thank you for the additional information.

**Comment by caojiele** [comment]
> okay, thank you for the additional information.

You're welcome.
