### ISSUE TITLE
如果安装节点需要通过代理上外网，是否支持通过代理上外网在线安装kubesphere?

### ISSUE THREAD

**Issue by liaoyinfeng** [kubesphere/kubesphere#411]
如果安装节点需要通过代理上外网，是否支持通过代理上外网在线安装kubesphere?

**Comment by calvinyv** [comment]
kubesphere不会提供代理配置，您需要确保集群各个节点能够访问外网

**Comment by wu0407** [comment]
文档里面的离线安装，什么时候出离线安装包

**Comment by FeynmanZhou** [comment]
@wu0407 本周内就可以出，离线安装包正在各个系统测试部署。

**Comment by zryfish** [comment]
离线安装包已经提供，可以在官网找到下载链接
