### ISSUE TITLE
Deployment using openpitrix failed

### ISSUE THREAD

**Issue by yyt6200** [kubesphere/kubesphere#4115]
KubeSphere Version : 3.1.0

Kubernetes Version：1.19.10

I created a chart of Nacos. Through experiments, helm3 can be deployed to k8s directly, but when using application deployment through openpitrix, Nacos application deployment fails. Please help me see what the problem is

------
Using openpitrix deployment, the error message is displayed
![image](https://user-images.githubusercontent.com/44914868/128114410-9e9c360b-12b6-441c-89c5-17e85b2f069b.png)
The error msg is :
**Error: error while running post render on files: error while running command /tmp/helm-operator/demo-project_nacos-oi0w2k_60lxz052nl307o/helm-post-render.sh. error output: panic: runtime error: index out of range [18] with length 17 [recovered] panic: runtime error: index out of range [18] with length 17 goroutine 1 [running]: gopkg.in/yaml%2ev3.handleErr(0xc000079980) /go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20200313102051-9f266ea9e77c/yaml.go:276 +0x85 panic(0xb87000, 0xc001c62220) /usr/local/go/src/runtim**

------
Using helm3 install, no problem.
![image](https://user-images.githubusercontent.com/44914868/128114626-66243713-c2a2-495f-9498-592acd9ec3a0.png)

**Comment by yyt6200** [comment]
Do I need to provide chart file？

**Comment by JohnNiang** [comment]
Yup, please feel free to provide detailed steps to reproduce this issue.

**Comment by yyt6200** [comment]
this is the chart file.
[nacos-0.1.8.zip](https://github.com/kubesphere/kubesphere/files/6928375/nacos-0.1.8.zip)
operation steps:
1.create 
![image](https://user-images.githubusercontent.com/44914868/128116964-6ff2ad34-004f-4007-9ef3-69b44b9c904c.png)
2.upload
![image](https://user-images.githubusercontent.com/44914868/128116982-4eb09c9b-6cd9-46e4-ab84-804a59f16715.png)
3.test
![image](https://user-images.githubusercontent.com/44914868/128117013-035fe35f-de0d-4ee6-bfa6-9cf8ad21a19a.png)

**Comment by yyt6200** [comment]
this is the ks-controller-manager log
![image](https://user-images.githubusercontent.com/44914868/128117179-716cdd8c-3899-49de-b190-a01b13b03995.png)

**Comment by xyz-li** [comment]
You should delete `    ## 兼容1.4.x版本的选举端口` in the service.yaml. I think this is a bug of kustomize. I will find how to fix it.

**Comment by yyt6200** [comment]
ok thx.The problem is solved.
