### ISSUE TITLE
Wrong numbers of deployment displayed under multi-cluster project ovewview page

### ISSUE THREAD

**Issue by yuswift** [kubesphere/kubesphere#4122]
**Describe the Bug**
![1628143659485](https://user-images.githubusercontent.com/37265389/128300050-62c200c8-b77b-484c-a8b6-5a3f67087025.jpg)
The numbers of the deployment should be `federateddeployment`, instead of `deployment`.
For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:latest
Kubernetes: (If KubeSphere installer used, you can skip this)
/kind bug
/area console

**Comment by harrisonliu5** [comment]
through the API `kapis/clusters/host/resources.kubesphere.io/v1alpha2/namespaces/apptest/quotas` to get the count of the resource

![image](https://user-images.githubusercontent.com/17872673/128307900-19ba4246-0036-482e-829d-e57ec907d7eb.png)

@yuswift

**Comment by yuswift** [comment]
Currently, the backend only queries the number of `deployment`. Under a multi-cluster project, we only provide the entrance of creating a `federateddeployment`. If the user creates a `federateddeployment` and only deploys it to part of the clusters, the numbers of `deployments` doesn't equal to to the `federateddeployment`. I can't find a better solution for this situation, we can't query the `federateddeployment` resource cause the member cluster doesn't have it.
