### ISSUE TITLE
Upgrade API that is deprecated in Kubernetes v1.22

### ISSUE THREAD

**Issue by yuswift** [kubesphere/kubesphere#4127]
/kind cleanup
ref https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22
ref https://github.com/kubesphere/kubesphere/issues/3708

**Comment by yuswift** [comment]
I found a tool that can help us find the deprecated API in cluster.
https://github.com/doitintl/kube-no-trouble

**Comment by yuswift** [comment]
ref https://github.com/kubesphere/ks-installer/pull/1639
ref https://github.com/kubesphere/ks-installer/pull/1632

webohook v1beta1 API remained
https://github.com/kubesphere/ks-installer/search?q=admissionregistration.k8s.io%2Fv1beta1

**Comment by yuswift** [comment]
CRD v1beta1 API remained 
https://github.com/kubesphere/ks-installer/search?p=1&q=apiextensions.k8s.io%2Fv1beta1
/cc @zhu733756

**Comment by yuswift** [comment]
authorization.k8s.io/v1beta1
https://github.com/kubesphere/ks-installer/search?q=authorization.k8s.io%2Fv1beta1
/cc @kubesphere/sig-devops

**Comment by yuswift** [comment]
extensions/v1beta1
/cc @RolandMa1986

**Comment by zhu733756** [comment]
> CRD v1beta1 API remained
> https://github.com/kubesphere/ks-installer/search?p=1&q=apiextensions.k8s.io%2Fv1beta1
> /cc @zhu733756

Currently, the Kubeedge official doesn't have a plan to support v1, refer to [the address](https://github.com/kubeedge/kubeedge/tree/master/build/crds).

**Comment by RolandMa1986** [comment]
/close 
For KubeSphere backend we have already refactored all the code to support Kubernetes v1.22.x.
