### ISSUE TITLE
Current setup conflicts with KubeFlow (cert-manager / istio)

### ISSUE THREAD

**Issue by fzhan** [kubesphere/kubesphere#4133]
**What's it about?**
KubeFlow is having a conflict with cert-manager / istio

**What's the reason why we need it?**
Would it be possible to place istio in a specific namespace?

I believe this is an important feature for Kubesphere. There're a few use cases:

* A lot of cases where Kubesphere will be used to manage Kubeflow

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

**Comment by zhu733756** [comment]
@fzhan Could you please send the conflicting information?
/assign @RolandMa1986

**Comment by fzhan** [comment]
istio 1-6-10 is having a conflicts with 1-9 which is used by the kubeflow.

**Comment by RolandMa1986** [comment]
Hi @fzhan,

I don't think it's necessary to move Istio to another namespace and it seems impossible. 
Could you provide more detailed information and your scenarios? like:
Do you really need to enable Service Mesh in KubeSphere and working with KubeFlow together? Maybe you can share your idea and plan.
Which KubeFlow version and [distribution ](https://www.kubeflow.org/docs/started/installing-kubeflow/)are you using? those distributors may have a different configuration.

Please try to [upgrade Istio to 1.9](https://istio.io/latest/docs/setup/upgrade/) manually before installing KubeFlow. I don't have an environment test yet. Could you help us test it?

Thanks,
Roland

**Comment by fzhan** [comment]
@RolandMa1986 Thanks for the reply,
We are new to KubeSphere and KubeFlow, it appears that kubesphere has higher priority than kubeflow. We will adept other solutions for ML/DL such as OneFlow.

Perhaps will raise this issue / request later on when we come across it.

Thanks,
