### ISSUE TITLE
Support creating init container and mounting the volume at the console.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#4142]
/kind feature-request

**Comment by liangyuanpeng** [comment]
@VioZhang  Maybe  we can provide this  issue to contributors


/kind feature-request
/help

**Comment by VioZhang** [comment]
> @VioZhang Maybe we can provide this issue to contributors.
> 
> /kind feature-request
> /help

I can provide the drawing design if needed.

**Comment by harrisonliu5** [comment]
If the UI changes, please provide a video or screenshot to make it more intuitive.
