### ISSUE TITLE
The status of project members in multi cluster environment is incorrect

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#4167]
**Describe the Bug**

The user is active on the account management page, but it's disabled on the member cluster project members page. The user status is incorrect if login from another identity provider.

![image](https://user-images.githubusercontent.com/8263040/130210544-097a5ac0-bd4f-4778-a1f3-d008515cca51.png)

![image](https://user-images.githubusercontent.com/8263040/130210718-f2283ea9-80b9-4bec-8163-15b2a158b3b0.png)

**Versions Used**
KubeSphere: v3.1.0

**Expected behavior**

The user's status is consistent.

**Comment by wansir** [comment]
Fix the wrong user status:
```
for user in `kubectl get users -l iam.kubesphere.io/identify-provider=<IDP> -o custom-columns=:metadata.name`; do kubectl get federatedusers.types.kubefed.io $user -o json | jq 'setpath(["spec","template","metadata","labels","iam.kubesphere.io/identify-provider"];<IDP>)' | jq 'del(.metadata.resourceVersion)' | kubectl apply -f - ; done
```

**Comment by zryfish** [comment]
@wansir Any update?

**Comment by wansir** [comment]
I'm working on it.
