### ISSUE TITLE
Automatic resizing of PVC before out of space

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/kubesphere#4185]
## Background
Many users want their PVCs to be automatically resized when certain contains met (e.g. usage > 90%), to prevent workload unavailability due to out of space.

## Proposal
- use crd/controller to monitor the pvc and do resize
- may integrate with Prometheus

/area storage
/kind feature-request

**Comment by f10atin9** [comment]
These few project may be helpful：
https://github.com/topolvm/pvc-autoresizer
https://github.com/opstree/dynamic-pv-scaler
