### ISSUE TITLE
The number in the input of the quota doesn't match the slider input.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#4192]
![image](https://user-images.githubusercontent.com/41519383/131291984-8c1a0cef-85fe-42e2-9239-3cec5f22bd86.png)

**Comment by liangyuanpeng** [comment]
Confuse that why just not create issue on [kubesphere/console](https://github.com/kubesphere/console/issues).

**Comment by VioZhang** [comment]
https://github.com/kubesphere/console/issues/2224
