### ISSUE TITLE
Delete the StatefulSets set edit in multi-cluster and single-cluster projects the storage volume template in the configuration template

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4196]
Describe the Bug

1.Enter the StatefulSets sets edit configuration templates page
2.Click volume
3. Add a storage volume template,Set the correct information
4. Click confirm,The page reported an error
<img width="960" alt="微信图片_20210830183303" src="https://user-images.githubusercontent.com/88183150/131326643-3d607bb4-16e6-41fb-a41a-80a71d78780f.png">

Versions Used
KubeSphere: v3.2

/kind bug
/assign @VioZhang 
priority medium
/milestone v3.2

**Comment by f10atin9** [comment]
Update volumeClaimTemplates is not allowed when updating StatefulSets，please remove this part in the console.
![image](https://user-images.githubusercontent.com/36705019/149444029-e3409051-7e2f-481b-a83c-efca422d8696.png)

**Comment by jioce** [comment]
issue is not fixed

**Comment by jioce** [comment]
issue fixed in v3.3.0-alpha.2
