### ISSUE TITLE
The Kubesphere Dashboard Have Some Bug When Opened On ios.

### ISSUE THREAD

**Issue by ByteFlyCoding** [kubesphere/kubesphere#4198]
**Describe the Bug**
When I open the demo of kubesphere(https://demo.kubesphere.io/) supported by you on my iphone . I found that, The UI hava some bug, both of Safaria and Chrome on my phone. It is similarity that the dashboard of kubephere is not compatiable for Mobile endpoint. I think you can open the demo on your phone browser in order to oberseve this bug.
(Notes: The test device of my is iphone se 2  and the ios version is ios14.7,  you can try test it on other device and other browser. )

**Comment by liangyuanpeng** [comment]
Any reason for use kubesphere with phone?  IMO it doesn't make sense.

**Comment by ByteFlyCoding** [comment]
> Any reason for use kubesphere with phone? IMO,It doesn't make sense.

I don't think so, if your leader call you to watch production enviroment, but your computer is not by your side. You hava to watch it by your SmartPhone.
