### ISSUE TITLE
服务器意外关机重启，服务如何恢复？

### ISSUE THREAD

**Issue by Liuyanglong** [kubesphere/kubesphere#420]
如题，服务器意外关机重启，服务如何恢复？

**Comment by calvinyv** [comment]
请问您用的是什么版本？kubesphere 高级版支持主机重启自动恢复服务

**Comment by Liuyanglong** [comment]
我用的2.0-dev,重启后发现 右下角工具箱中的工具异常：
1、kubectl提示“deployments.apps "kubectl-admin" not found”。
2、日志中容器组的日志看不了。

**Comment by calvinyv** [comment]
可否介绍一下您的环境，我们尝试本地复现一下：
包括：集群规模（几个节点），节点OS版本，节点资源配置等

如果您本地环境允许我们访问，可否把访问方式发到 kubesphere@yunify.com，比如teamviewer或者ssh等

**Comment by Liuyanglong** [comment]
单机器部署；
os为centos7.5 64位，vmware虚拟机部署；
16core cpu，32g mem，200GB disk

**Comment by Liuyanglong** [comment]
kubectl-admin对应的pod是哪个？
日志服务中有kube系统组件的日志，但是没有容器组的日志。

**Comment by calvinyv** [comment]
kubectl get pods -n kubesphere-controls-system

**Comment by Liuyanglong** [comment]
[root@ks-allinone ~]# kubectl get pods -n kubesphere-controls-system
NAME                                     READY   STATUS    RESTARTS   AGE
default-http-backend-96d94689d-c56b8     1/1     Running   1          5d2h
kubesphere-router-demo-7bbd5c9fb-nd8jp   1/1     Running   1          5d1h

**Comment by calvinyv** [comment]
kubectl-admin消失的问题是一个已知的bug，已经修复

我刚才部署了最新的daily dev installer，重启没有复现这个问题，你可以下载新的installer试试，环境不用充值，执行新installer里面的install.sh或者upgrade.sh就可以

**Comment by Liuyanglong** [comment]
问题依旧没解决，我重新下载最新的installer，并且执行了install.sh，提示成功，进入页面后，依然提示 “deployments.apps "kubectl-admin" not found”

```
[root@ks-allinone scripts]# kubectl get pods -n kubesphere-controls-system
NAME                                     READY   STATUS    RESTARTS   AGE
default-http-backend-96d94689d-c56b8     1/1     Running   2          7d1h
kubesphere-router-demo-7bbd5c9fb-nd8jp   1/1     Running   2          7d
```

**Comment by pixiake** [comment]
执行下upgrade.sh应该就可以了

**Comment by Liuyanglong** [comment]
其实还没好，我准备重新部署一套，做一下交叉对比
