### ISSUE TITLE
The deleted Deployment remains on the node

### ISSUE THREAD

**Issue by yinmin2020** [kubesphere/kubesphere#4217]
**Describe the Bug**
Redeploying the Deployment system does not automatically drive out or delete the old Deployment
The deleted Deployment is not provided with any logs

![image](https://user-images.githubusercontent.com/65068467/132168669-7c7e353e-7570-4edc-9e93-8b77cb7c9c05.png)

**Comment by liangyuanpeng** [comment]
Anything from `kubectl describe` or `kubectl logs` ?

**Comment by yinmin2020** [comment]
> Anything from `kubectl describe` or `kubectl logs` ?

`default       dmp-dev       dmpxcg2r      dtportal-dev  dtportal-sit  dtportal-uat  
[root@cn-hangzhou ~]# kubectl describe pod b-app-web-serv-v1-7d54d4bb67-4n4hp -n dtportal-sit 
Name:           b-app-web-serv-v1-7d54d4bb67-4n4hp
Namespace:      dtportal-sit
Priority:       0
Node:           node9/
Start Time:     Mon, 19 Jul 2021 09:56:32 +0800
Labels:         app=b-app-web-serv
                app.kubernetes.io/name=b-app-web-serv
                app.kubernetes.io/version=v1
                pod-template-hash=7d54d4bb67
                version=v1
Annotations:    cni.projectcalico.org/podIP: 10.233.100.229/32
                cni.projectcalico.org/podIPs: 10.233.100.229/32
                kubesphere.io/containerSecrets: {"b-app-web-serv":"ks-harbor"}
                kubesphere.io/restartedAt: 2021-07-19T01:56:32.459Z
                sidecar.istio.io/inject: false
Status:         Failed
Reason:         Evicted
Message:        The node was low on resource: memory. Container b-app-web-serv was using 1209516Ki, which exceeds its request of 0. 
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/b-app-web-serv-v1-7d54d4bb67
Containers:
  b-app-web-serv:
    Image:       ks-harbor.supaur.top/portal/b-app-user-center:dev-sprint2.4-19
    Ports:       8080/TCP, 5005/TCP
    Host Ports:  0/TCP, 0/TCP
    Environment:
      
Volumes:
  default-token-gj8t9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-gj8t9
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
`
