### ISSUE TITLE
sdk

### ISSUE THREAD

**Issue by qiuax** [kubesphere/kubesphere#4219]
I happened to use kubesphere and wrote some API SDKs. Can they be integrated into the project?

**Comment by RolandMa1986** [comment]
> I happened to use kubesphere and wrote some API SDKs. Can they be integrated into the project?

@qiuax  We are pleasured to accept any kind of contribution to KubeSphere that help us to improve KubeSphere. 
Please provide a little bit more information about the SDK. it's a good practice to follow our feature request template.
Thanks,
Roland

**Comment by qiuax** [comment]
Thank you, what should I do now to integrate into your side and contribute together.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月8日(星期三) 上午9:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kubesphere/kubesphere] sdk (#4219)






我碰巧使用了kubesphere并编写了一些APISDK。它们能被整合到项目中吗？

@qiuax我们乐于接受任何帮助我们改进KubeSphere的对KubeSphere的贡献。
请提供更多有关SDK的信息。遵循我们的特性请求模板是一个很好的实践。
谢谢,
罗兰

—
你收到这封信是因为有人提到了你。
直接回复这封电子邮件，在GitHub上查看，或取消订阅.
GitHub Mobile Go的分流通知IOS或机器人.

**Comment by RolandMa1986** [comment]
You can find our developer guide at https://github.com/kubesphere/community/tree/master/developer-guide/development.
But for SDKs, it doesn't need to be merged into our main repo. There's a Kubernetes style SDK for KubeSphere that can be found at https://github.com/kubesphere/client-go. For an SDK I think it's very important to cover most APIs and be well tested.

**Comment by qiuax** [comment]
Okay, I will continue to improve other APIs




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月8日(星期三) 上午10:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kubesphere/kubesphere] sdk (#4219)






你可以找到我们的开发者指南https://github.com/kubesphere/community/tree/master/developer-guide/development.
但是对于SDKs,不需要并入我们的主回购。有一种库伯内特式SDK对于 KubeSphere ，可以在https://github.com/kubesphere/client-go.对于一SDK我认为覆盖大多数 API 并进行良好测试是非常重要的。

—
你收到这个是因为你被提到了。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.
