### ISSUE TITLE
Failed to search the auditing logs from external ES in KubeSphere 3.1.1

### ISSUE THREAD

**Issue by zhbitzwz** [kubesphere/kubesphere#4226]
版本信息：
kubersphere：v3.1.1
fluent-operatro:kubesphere/fluentbit-operator:v0.11.0
fluent-bit:kubesphere/fluent-bit:v1.8.3

docker的路径：/data/lib/docker
日志的路径：/var/log/containers/*  查看软链接对应 /var/log/pods/*

现象：
![image](https://user-images.githubusercontent.com/11995740/132786996-e11b0e8b-d38f-40b4-b34c-55dd06ede4b9.png)

fluent-bit报错日志：
`
[2021/09/10 02:01:34] [error] [output:es:es.0] HTTP status=400 URI=/_bulk, response:

{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;2: an id must be provided if version type or value are set;3: an id must be provided if version type or value are set;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;2: an id must be provided if version type or value are set;3: an id must be provided if version type or value are set;"},"status":400}
`
![image](https://user-images.githubusercontent.com/11995740/132787278-0d870733-2612-4694-bfc2-d4400ba799f1.png)

**Comment by wenchajun** [comment]
Can I have a look at CRD (Output)? This may be the reason for misreading newspaper information.(https://github.com/kubesphere/ks-installer/blob/master/roles/ks-auditing/templates/custom-output-elasticsearch-auditing.yaml.j2#L13)
相关issue https://github.com/fluent/fluent-bit/issues/3909

**Comment by wenchajun** [comment]
I mixed up the version. The output plug-in in kubespherev3.1.1 did not configure the corresponding field, this bug has been changed in kubespherev3.2. You can add fields( generateID: true) to collect Fluentbit information. For details, see the previous comment。

**Comment by luorenjin** [comment]
I encountered the same problem. version: v3.2.0.
![image](https://user-images.githubusercontent.com/7892385/140875015-cc712a70-2018-4061-8586-ec4e1e010281.png)
![image](https://user-images.githubusercontent.com/7892385/140875016-fe65a87b-fd94-4711-a6f5-7ee4b25f7392.png)
![image](https://user-images.githubusercontent.com/7892385/140875031-8f5324ea-a215-4ffd-a966-753effab2bcd.png)
as you see, I find zhe fields ( generateID: true)
![image](https://user-images.githubusercontent.com/7892385/140875213-f926d1c4-a053-491a-94c3-0df4653b0b4c.png)

**Comment by luorenjin** [comment]
the problem solved，
`
apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"logging.kubesphere.io/v1alpha2","kind":"Output","metadata":{"annotations":{},"labels":{"logging.kubesphere.io/component":"logging","logging.kubesphere.io/enabled":"true"},"name":"es","namespace":"kubesphere-logging-system"},"spec":{"es":{"host":"elasticsearch-logging-data.kubesphere-logging-system.svc","logstashFormat":true,"logstashPrefix":"ks-logstash-log","port":9200,"timeKey":"@timestamp"},"match":"kube.*"}}
  labels:
    logging.kubesphere.io/component: logging
    logging.kubesphere.io/enabled: 'true'
  name: es
  namespace: kubesphere-logging-system
spec:
  es:
    generateID: true
    host: elasticsearch-logging-data.kubesphere-logging-system.svc
    logstashFormat: true
    logstashPrefix: ks-logstash-log
    port: 9200
    timeKey: '@timestamp'
  match: kube.*
`
