### ISSUE TITLE
need to add validation when changing the cluster role of multicluster to None

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4229]
Describe the Bug
1. Edit the configuration  of the host cluster ks-installer
2. Change the multi-cluster role to None
3. Cluster update succeeded,It is still the host cluster
<img width="956" alt="修改集群角色" src="https://user-images.githubusercontent.com/88183150/132798164-d0e2db2b-273f-4fc1-8701-a09dc4b1a9de.png">

**Expected behavior**
     An error was reported when updating the configuration  Procedure

Versions Used
KubeSphere: kubespheredev/ks-installer:nightly-20210908

/kind bug
/assign @yuswift 
priority medium
/milestone v3.2

**Comment by yuswift** [comment]
Once the cluster role is `host`, it shouldn't be changed to `None`. IMO, hanging the role is very dangerous and should be forbidden. @zryfish What's your suggestion? Should we verify it in the `ks-installer` or in the `ks-controller-manager`?

**Comment by jioce** [comment]
issue is not fixed
