### ISSUE TITLE
Account password settings can  have no capital letters

### ISSUE THREAD

**Issue by penghuima** [kubesphere/kubesphere#4242]
**Describe the Bug**
When changing the account password on the ks-console page, we must include uppercase and lowercase letters and numbers
But if we use the following command in the terminal, we can set the password without capital letters
```
kubectl patch users <user> -p '{"spec":{"password":"<password>"}}' --type='merge' && kubectl annotate users <user> iam.kubesphere.io/password-encrypted-
```
![image](https://user-images.githubusercontent.com/43670120/133396099-1b1d4e02-2810-4a96-84c4-f06ccc8a6772.png)

**Versions Used**
KubeSphere: 3.1.0
Kubernetes: 1.19.8

/kind bug

**Comment by live77** [comment]
hi, i would like to fix this. 
My solution is adding a ValidatingWebhookConfiguration to verify the password.
If the password is not valid, then the webhook will return error, then the patch or creation for the user will not be affected.
Just want to make sure that this is THE proper solution.

**Comment by live77** [comment]
Test result:
kubectl patch users test -p '{"spec":{"password":"12345678"}}' --type='merge'
Error from server: admission webhook "passwordvalidator.users.iam.kubesphere.io" denied the request: user password is not valid

kubectl patch users test -p '{"spec":{"password":"Hello1234"}}' --type='merge'
user.iam.kubesphere.io/test patched
