### ISSUE TITLE
Support import new Helm-based Apps into KubeSphere App Store dynamically

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#4244]
**What's it about?**

The built-in applications are tightly coupled with the KubeSphere version, this is not flexible for us to expand the application ecosystem of KubeSphere App Store and build the partnership with more ISVs and partners. 

I propose to support import new Helm-based apps into KubeSphere App Store dynamically. 

**What's the reason why we need it?**

I believe this is an important feature for Kubesphere. There're a few use cases:

* A lot of ISVs or partners are applied to add their Helm charts to KubeSphere App Store, see an [example](https://github.com/kubesphere/helm-charts/pull/150).
* Users can deploy the applications in time when the related Pull Request has been merged, they don't need to wait for a new release of KubeSphere

Please leave your comments below if there's anyone who agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request
/area app-management

**Comment by akhilerm** [comment]
Does builtin services like storage apps (eg: openebs) also need to be added to the app store?
