### ISSUE TITLE
Successfully mounted but there is no content in the pv (caused by spaces)

### ISSUE THREAD

**Issue by shenhonglei** [kubesphere/kubesphere#4255]
**Describe the Bug**
When mounting a storage volume, the path can contain spaces, and pv can be mounted successfully, but it is empty.
**Versions Used**
KubeSphere:3.1.1

**Environment**
Ubuntu 16 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g; openebs

**How To Reproduce**
1. Go to 'Create PersistentVolumeClaim>>Storage Class:local、rwo、10G'
2. Go to 'Create App by Service>>Create Stateful Service>>add Volumes'

**Stateful applications can successfully mount pv, but there is no content in pv. The cause is that there is an extra space on the path when mounting**

<img width="1157" alt="1" src="https://user-images.githubusercontent.com/20896372/133882633-29b5605d-3982-4e94-a527-108156cdc2b8.png">
<img width="1136" alt="2" src="https://user-images.githubusercontent.com/20896372/133882642-81e0bf77-5ba3-4a6a-be66-95aaa2454365.png">
<img width="1566" alt="3" src="https://user-images.githubusercontent.com/20896372/133882647-610387cc-63b4-4b8c-b3da-80174de00c5d.png">

**Comment by liangyuanpeng** [comment]
So  we should check space in front/backend and just remove it, right? 

I think it will be great as a first issue.
