### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by cnicy** [kubesphere/kubesphere#426]
OS Version:
CentOS Linux release 7.5.1804 (Core)
Kubesphere Version:
kubesphere-all-advanced-2.0.0-dev-20190514

selinux已关闭、swapoff已关闭、firewalld已关闭

报错信息如下：
kubernetes/preinstall : Update package management cache (YUM) ------------------------------------------------------------------------------------------------------------------------------- 25.34s
kubernetes/preinstall : Install packages requirements ---------------------------------------------------------------------------------------------------------------------------------------- 2.96s
gather facts from all instances -------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.72s
bootstrap-os : Install libselinux-python and yum-utils for bootstrap ------------------------------------------------------------------------------------------------------------------------- 0.70s
bootstrap-os : Check python-pip package ------------------------------------------------------------------------------------------------------------------------------------------------------ 0.69s
bootstrap-os : Install pip for bootstrap ----------------------------------------------------------------------------------------------------------------------------------------------------- 0.68s
download : Download items -------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.66s
bootstrap-os : Assign inventory name to unconfigured hostnames (non-CoreOS and Tumbleweed) --------------------------------------------------------------------------------------------------- 0.65s
kubernetes/preinstall : Create kubernetes directories ---------------------------------------------------------------------------------------------------------------------------------------- 0.64s
download : Sync container -------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.64s
download : Download items -------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.62s
download : Sync container -------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.62s
bootstrap-os : Gather nodes hostnames -------------------------------------------------------------------------------------------------------------------------------------------------------- 0.60s
kubernetes/preinstall : Set selinux policy --------------------------------------------------------------------------------------------------------------------------------------------------- 0.54s
container-engine/docker : Ensure old versions of Docker are not installed. | RedHat ---------------------------------------------------------------------------------------------------------- 0.44s
container-engine/docker : ensure service is started if docker packages are already present --------------------------------------------------------------------------------------------------- 0.44s
bootstrap-os : Install epel-release for bootstrap -------------------------------------------------------------------------------------------------------------------------------------------- 0.43s
kubernetes/preinstall : Create cni directories ----------------------------------------------------------------------------------------------------------------------------------------------- 0.41s
kubernetes/preinstall : Hosts | populate inventory into hosts file --------------------------------------------------------------------------------------------------------------------------- 0.41s
kubernetes/preinstall : Remove swapfile from /etc/fstab -------------------------------------------------------------------------------------------------------------------------------------- 0.39s
failed!

**Comment by cnicy** [comment]
kubernetes/preinstall : Install packages requirements --------------------------------------------------------------------------------------------------------------------------------------- 71.33s
container-engine/docker : ensure docker packages are installed ------------------------------------------------------------------------------------------------------------------------------ 36.88s
kubernetes/preinstall : Update package management cache (YUM) ------------------------------------------------------------------------------------------------------------------------------- 21.41s
container-engine/docker : Ensure old versions of Docker are not installed. | RedHat ---------------------------------------------------------------------------------------------------------- 4.07s
bootstrap-os : Install libselinux-python and yum-utils for bootstrap ------------------------------------------------------------------------------------------------------------------------- 3.43s
Gathering Facts ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ 1.25s
container-engine/docker : Docker | reload docker --------------------------------------------------------------------------------------------------------------------------------------------- 1.23s
bootstrap-os : Check python-pip package ------------------------------------------------------------------------------------------------------------------------------------------------------ 0.70s
download : Sync container -------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.68s
gather facts from all instances -------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.67s
download : Download items -------------------------------------------------------------------------------------------------------------------------------------------------------------------- 0.67s
kubernetes/preinstall : Create kubernetes directories ---------------------------------------------------------------------------------------------------------------------------------------- 0.66s
bootstrap-os : Assign inventory name to unconfigured hostnames (non-CoreOS and Tumbleweed) --------------------------------------------------------------------------------------------------- 0.65s
container-engine/docker : ensure service is started if docker packages are already present --------------------------------------------------------------------------------------------------- 0.63s
bootstrap-os : Install pip for bootstrap ----------------------------------------------------------------------------------------------------------------------------------------------------- 0.58s
kubernetes/preinstall : Set selinux policy --------------------------------------------------------------------------------------------------------------------------------------------------- 0.54s
container-engine/docker : Configure docker repository on RedHat/CentOS ----------------------------------------------------------------------------------------------------------------------- 0.48s
bootstrap-os : Install epel-release for bootstrap -------------------------------------------------------------------------------------------------------------------------------------------- 0.45s
kubernetes/preinstall : Remove swapfile from /etc/fstab -------------------------------------------------------------------------------------------------------------------------------------- 0.44s
kubernetes/preinstall : Hosts | populate inventory into hosts file --------------------------------------------------------------------------------------------------------------------------- 0.42s
failed!

**Comment by cnicy** [comment]
kubernetes/preinstall : Hosts | populate inventory into hosts file --------------------------------------------------------------------------------------------------------------------------- 0.42s
failed!

**Comment by pixiake** [comment]
具体的报错信息是红色字体   在这些上边   看看是什么 什么原因

**Comment by cnicy** [comment]
TASK [download : container_download | Download containers if pull is required or told to always pull (all nodes)] ***********************************************************************************
Wednesday 15 May 2019  21:51:02 +0800 (0:00:00.054)       0:00:09.788 ********* 
FAILED - RETRYING: container_download | Download containers if pull is required or told to always pull (all nodes) (4 retries left).

一直卡这里是不是需要翻墙呢？

**Comment by pixiake** [comment]
这个一般是由于到dockerhub网络不是特别好造成的

**Comment by cnicy** [comment]
等吧 挂个通宵

**Comment by rayzhou2017** [comment]
你的带宽是多少？一般100M 40分钟左右就能装好

**Comment by cnicy** [comment]
带宽差不多吧  就一直卡那一步

**Comment by pixiake** [comment]
这个可能也跟运营商有关

**Comment by cnicy** [comment]
REPOSITORY                                                                        TAG                 IMAGE ID            CREATED             SIZE
dockerhub.qingcloud.com/google_containers/hyperkube                               v1.13.5             7740a148dcf0        7 weeks ago         565MB
dockerhub.qingcloud.com/google_containers/coredns                                 1.4.0               a9e015907f63        2 months ago        42.6MB
dockerhub.qingcloud.com/kubernetes_helm/tiller                                    v2.12.3             ecd91fcf9f6d        3 months ago        81.4MB
dockerhub.qingcloud.com/google_containers/coredns                                 1.2.6               f59dcacceff4        6 months ago        40MB
dockerhub.qingcloud.com/google_containers/cluster-proportional-autoscaler-amd64   1.3.0               33813c948942        7 months ago        45.8MB
dockerhub.qingcloud.com/calico/node                                               v3.1.3              7eca10056c8e        11 months ago       248MB
dockerhub.qingcloud.com/calico/ctl                                                v3.1.3              b33deb8bd4f2        11 months ago       42.8MB
dockerhub.qingcloud.com/calico/kube-controllers                                   v3.1.3              240a82836573        11 months ago       55MB
dockerhub.qingcloud.com/calico/cni                                                v3.1.3              9f355e076ea7        11 months ago       68.8MB
busybox                                                                           1.28.4              8c811b4aec35        11 months ago       1.15MB
dockerhub.qingcloud.com/coreos/etcd                                               v3.2.18             e21fb69683f3        13 months ago       37.2MB
dockerhub.qingcloud.com/google_containers/pause                                   3.1                 da86e6ba6ca1        17 months ago       742kB

**Comment by cnicy** [comment]
2019-05-16 10:45:29,530 p=27840 u=root |  Thursday 16 May 2019  10:45:29 +0800 (0:00:00.042)       0:31:44.212 ********** 
2019-05-16 13:19:28,148 p=27840 u=root |  FAILED - RETRYING: container_download | Download containers if pull is required or told to always pull (all nodes) (4 retries left).

这一步是在下载什么东西呢？一直卡这里，我能不自己去pull到本地然后上传

**Comment by pixiake** [comment]
可以自己pull本地传上去    但镜像有很多   最新的安装包里加了mirror   可以下载最新的试下呢

**Comment by cnicy** [comment]
重新下载安装吗？

**Comment by pixiake** [comment]
嗯  按这个下载就行

**Comment by cnicy** [comment]
还是各种出问题，能不能在青云买一台虚拟机装。或者用appcenter，但是appcenter我看版本好像比较低。

**Comment by rayzhou2017** [comment]
下个星期青云会上线QKE，是基于KubeSphere的。我很好奇你安装出什么问题了？我们每天安装好几次很少出问题。

**Comment by cnicy** [comment]
{"changed": true, "cmd": ["/usr/local/bin/kubectl", "create", "namespace", "istio-system"], "delta": "0:00:34.560664", "end": "2019-05-17 09:40:35.780358", "failed_when_result": true, "item": "istio-system", "msg": "non-zero return code", "rc": 1, "start": "2019-05-17 09:40:01.219694", "stderr": "The connection to the server 10.211.55.43:6443 was refused - did you specify the right host or port?", "stderr_lines": ["The connection to the server 10.211.55.43:6443 was refused - did you specify the right host or port?"], "stdout": "", "stdout_lines": []}

**Comment by cnicy** [comment]
fatal: [ks-allinone]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/kubectl annotate node ks-allinone alpha.kubernetes.io/provided-node-ip=10.211.55.43", "delta": "0:00:16.820080", "end": "2019-05-17 09:14:43.174770", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2019-05-17 09:14:26.354690", "stderr": "Unable to connect to the server: net/http: TLS handshake timeout", "stderr_lines": ["Unable to connect to the server: net/http: TLS handshake timeout"], "stdout": "", "stdout_lines": []}

**Comment by rayzhou2017** [comment]
@pixiake 你帮忙看看

**Comment by cnicy** [comment]
QKE 具体什么时间会上，包含Kubesphere2.0的全部功能吗？

**Comment by pixiake** [comment]
@cnicy 能否把环境信息发到kubesphere@yunify.com  我们连上看下

**Comment by cnicy** [comment]
我现在是本地虚拟机搭建的 我马上找一台外网服务器搭建试一下。

**Comment by rayzhou2017** [comment]
明天正式GA KubeSphere 2.0.0，大概一周左右就上线QKE，包含完整的KubeSphere 2.0.0功能。

**Comment by cnicy** [comment]
重新找了一台服务器用KVM装了一个虚拟机就正常了，系统和本地一样。暂时得出一个结论PC电脑上开虚拟机有问题，不管是是centos还是ubuntu

**Comment by irradiate** [comment]
TASK [kubernetes/preinstall : Create local volume provisioner directories] *********************************************************************************************************************************
Tuesday 21 May 2019  10:58:03 +0800 (0:00:00.291)       0:00:35.792 ***********
fatal: [ks-allinone]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute \"dict_keys(['local'])\"\n\nThe error appears to have been in '/home/leon/kubesphere-all-advanced-2.0.0/k8s/roles/kubernetes/preinstall/tasks/0050-create_directories.yml': line 48, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create local volume provisioner directories\n  ^ here\n"}

**Comment by rayzhou2017** [comment]
@pixiake  你看看上面的问题

**Comment by bqsky** [comment]
> 等吧 挂个通宵

对，安装失败我们测试了基本都是由于下载镜像慢导致的。安装脚本没啥问题。
