### ISSUE TITLE
Unable to build kubesphere with make on Linux/ARM64 machine

### ISSUE THREAD

**Issue by odidev** [kubesphere/kubesphere#4261]
**Describe the Bug**
I am getting below error while trying to execute "make all" on Linux/ARM64 instance.
This error occurs on the following test suites:
- application_suit_test.go
- helm_controller_test.go
- namespace_controller_suite_test.go
- helm_application_controller_suite_test.go
- helm_category_controller_suite_test.go
- helm_repo_controller_suite_test.go
- workspace_controller_suite_test.go
- workspacerole_controller_suite_test.go
- workspacerolebinding_controller_suite_test.go

```
  Unexpected error:
      <*fmt.wrapError | 0x40004b6c20>: {
          msg: "unable to start control plane itself: failed to start the controlplane. retried 5 times: timeout waiting for process etcd to start successfully (it may have failed to start, or stopped unexpectedly before becoming ready)",
          err: {
              msg: "failed to start the controlplane. retried 5 times: timeout waiting for process etcd to start successfully (it may have failed to start, or stopped unexpectedly before becoming ready)",
              err: {
                  s: "timeout waiting for process etcd to start successfully (it may have failed to start, or stopped unexpectedly before becoming ready)",
              },
          },
      }
      unable to start control plane itself: failed to start the controlplane. retried 5 times: timeout waiting for process etcd to start successfully (it may have failed to start, or stopped unexpectedly before becoming ready)
  occurred
```

**Versions Used**
KubeSphere: Cloned the master branch for building

**Environment**
Linux/ARM64 

```
ubuntu@1pthunderx1-137:~$ uname -a
Linux 1pthunderx1-137 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:24:57 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```
```
kubesphere$ go version
go version go1.16 linux/arm64
```

**How To Reproduce**
1. Git clone https://github.com/kubesphere/kubesphere.git
2. cd kubesphere
3. make all

**Expected behavior**
Complete the test and build binaries successfully

**Comment by zryfish** [comment]
Have you installed kubebuilder, the test suite of contollers depends on kubebuilder.
