### ISSUE TITLE
timed out waiting for resources to be ready when install helm chart

### ISSUE THREAD

**Issue by lyzhang1999** [kubesphere/kubesphere#4262]
**Describe the Bug**
I was add a helm repo: https://nocalhost-helm.pkg.coding.net/nocalhost/nocalhost and install, the pod is running, but kubesphere application status got: timed out waiting for resources to be ready

![image](https://user-images.githubusercontent.com/8142348/134307342-2e23b326-9e89-45ec-ab05-c6c506b6dacf.png)

![image](https://user-images.githubusercontent.com/8142348/134307393-f556e9c3-b7e1-4173-877b-7ae821ed2b4c.png)

**Versions Used**
KubeSphere: v3.1.1
Kubernetes: v1.18.8

**Environment**

MacOS, minikube v1.15.1, docker

**How To Reproduce**
1. add helm repo: https://nocalhost-helm.pkg.coding.net/nocalhost/nocalhost
2. install application nocalhost
3. check application

**Comment by FeynmanZhou** [comment]
It might be a front-end bug in KubeSphere Console. 

Hi Team @kubesphere/sig-console @kubesphere/sig-apps , could you please help to verify if this issue has been fixed in v3.2.0?

**Comment by WhiteElytra** [comment]
The problem reappeared. Same as @racheng

![截屏2022-10-16 19.31.27.png](https://r2.img.baiyi.icu/2022/10/16/634beba5afd52.png)

![3ec4ce8d17e70539f382fe24319ed690_0.png](https://r2.img.baiyi.icu/2022/10/16/634beba620917.png)
