### ISSUE TITLE
kubesphere3.1 can not login when the username contain "_"

### ISSUE THREAD

**Issue by hurricane1988** [kubesphere/kubesphere#4267]
**Describe the Bug**
We integrated OIDC provider，but can't login when the username contain “_”. How can we fix the problem?
**Remark：** Our OIDC name format is xxxxxx_xx
![image](https://user-images.githubusercontent.com/16606960/134460546-bebd3750-cf70-4748-8a72-44d65016e33f.png)

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by wansir** [comment]
@hurricane1988 Please modify the mapped username according to the prompt.

**Comment by carefree666** [comment]
我集成了ldap也是这种格式用户名,无法登录😱

**Comment by hurricane1988** [comment]
> @hurricane1988 Please modify the mapped username according to the prompt.

We integrate the OIDC service, and we can't modify the OIDC provider username format( because other service like Harbor Jenkins use the OIDC too)

**Comment by wansir** [comment]
> > @hurricane1988 Please modify the mapped username according to the prompt.
> 
> We integrate the OIDC service, and we can't modify the OIDC provider username format( because other service like Harbor Jenkins use the OIDC too)

This is the account information confirmation process, create a mapped kubesphere account (automatically associate with the uid), you are able to redefine the username.

**Comment by wcwmsj2512** [comment]
> 
> 
> > > @hurricane1988 Please modify the mapped username according to the prompt.
> > 
> > 
> > We integrate the OIDC service, and we can't modify the OIDC provider username format( because other service like Harbor Jenkins use the OIDC too)
> 
> This is the account information confirmation process, create a mapped kubesphere account (automatically associate with the uid), you are able to redefine the username.

After integrating the OIDC service and login successfully,I want to change the account's password, but it notices me to fullfill the the old password(initial password),so what is the initial password?

**Comment by hurricane1988** [comment]
> > > @hurricane1988 Please modify the mapped username according to the prompt.
> > 
> > 
> > We integrate the OIDC service, and we can't modify the OIDC provider username format( because other service like Harbor Jenkins use the OIDC too)
> 
> This is the account information confirmation process, create a mapped kubesphere account (automatically associate with the uid), you are able to redefine the username.

Can login successfully now, But I have a question that is what the password
