### ISSUE TITLE
the notification configuration information verification does not report error

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#4268]
**Describe the bug**

The Notification Manager reports errors, but the notification configuration information verification interface does not report error
![image](https://user-images.githubusercontent.com/36271543/134474544-6091be0c-6e06-4dd9-b33e-ce4012bdd61d.png)

![image](https://user-images.githubusercontent.com/36271543/134473749-03d7652f-f446-41bd-8f56-4a7d7d1519d4.png)

**Versions Used**
KubeSphere: ks3.2 alpha
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/assign @wanjunlei 
/priority High

**Comment by wanjunlei** [comment]
fixed in #kubesphere/ks-installer#1704

**Comment by wanjunlei** [comment]
Fix in #kubesphere/ks-installer#1712

**Comment by liuyp2018** [comment]
fixed in v3.2.0-rc.1
