### ISSUE TITLE
Page filter and selected page can't be kept when switching back page

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#4277]
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: 3.0, 3.1 
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. Go to 'Cluster nodes' page or any page which is listing data, like pods list page, and the records are shown in more than one page
2. Filter the listed data and turn to the second page
3. Click on any node(pod...etc) to detail page
4. then click the 'Back' button of your browser
5. it shows the first page

**Expected behavior**
I should be kept on the second page or my filter should be saved.

**Comment by calvinyv** [comment]
/area console
/kind bug
@kubesphere/sig-console

**Comment by jioce** [comment]
issue is fixed in v3.3.0-rc.0
