### ISSUE TITLE
 field display problems on the pv details page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#4280]
**Describe the Bug**

 field display problems on the pv details page
![image](https://user-images.githubusercontent.com/36271543/134660241-903041de-6e79-47e0-9614-53ba39d62320.png)

**Versions Used**
KubeSphere: v3.2 alpha.0
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @harrisonliu5 
/area console
/milestone v3.2
/priority Low

**Comment by Patrick-LuoYu** [comment]
This issue has been fixed, as shown in the following figure.
![image](https://user-images.githubusercontent.com/76198553/143411760-ce789ccd-e62b-4c1c-969c-30785e2529fd.png)
