### ISSUE TITLE
One-click resizing pvc in ks-console

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/kubesphere#4285]
# Background
Resizing volume may require workload stop and restart, currently user has to do this manually.

# Proposal
stop and restart workload automatically based on the storage system and the pvc's status. One-click, wait for a while, it's done.
We may only be able to handle deployment and statefulset, not daemonset.
For the replicas controlled by another operator, directly scale down the deployment/stateful may not work either.

/area storage
/area console
/kind feature-request

**Comment by f10atin9** [comment]
Fixed: #4660 pvc-autoresizer also added the auto-restart feature, when the user enables the feature, the system can automatically complete the restart of the workload without a click.
