### ISSUE TITLE
The configuration of the Istio virtualservice is overwritten

### ISSUE THREAD

**Issue by cycwll** [kubesphere/kubesphere#4287]
**The configuration of the Istio virtualservice is overwritten **

For UI issues please also add a screenshot that shows the issue.

**Versions 3.1.1 **
KubeSphere:

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. Go to On the "application" - "traffic governance" of kubesphere, select a service, configure traffic governance parameters, start connection pool management, and set "maximum connections" to 1
2. Because fault the istio injection cannot be configured through kubesphere, edit the virtual service manually and add a 5-second delay
    #kubectl -n istio-test edit virtualservice web-service
        fault:
        delay:
        fixedDelay: 5s
        percentage:
        value: 100
3. After waiting for a period of time (3-10 minutes), the configuration is lost. 
    #kubectl -n istio-test get virtualservice web-service -o yaml

** Expected behavior **
It is expected that manual configuration will not be overwritten.

**Comment by jioce** [comment]
issue is fixed in v3.3.0-rc.0
