### ISSUE TITLE
failed to get calico-node daemonsets.apps in kube-system namespace

### ISSUE THREAD

**Issue by king-jingxiang** [kubesphere/kubesphere#4288]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/32818529/134838283-555b198a-28b9-4f55-b6c1-ab25d3105bfd.png)

**Versions Used**
KubeSphere: v3.1.1
Kubernetes: v1.21.4

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

[Install Calico ](https://docs.projectcalico.org/getting-started/kubernetes/quickstart) can't set namespace
```
# kubectl logs ks-controller-manager-586f44fb5b-mt2vv -nkubesphere-system
F0926 21:45:52.982421       1 provider.go:667] failed to get calico-node deployment in kube-system, err=daemonsets.apps "calico-node" not found
#  kubectl get ns
NAME                              STATUS   AGE
calico-apiserver                  Active   4d16h
calico-system                     Active   4d16h
default                           Active   4d16h
......
kubesphere-system                 Active   4d16h
tigera-operator                   Active   4d16h
[root@vmi-08 ~]# kubectl get ds -ncalico-system
NAME          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
calico-node   1         1         0       1            0           kubernetes.io/os=linux   4d16h
```
```
pkg/simple/client/network/ippool/calico/provider.go:77
CalicoNodeNamespace          = "kube-system"
```

**Expected behavior**
Looking forward to adding this `CalicoNodeNamespace` parameter to clusterconfigurations.installer.kubesphere.io network.

**Comment by yuswift** [comment]
It seems that there are some network problems in your cluster.

**Comment by king-jingxiang** [comment]
> It seems that there are some network problems in your cluster.

不是网络问题，是你代码里把namespace写死了，用calico operator部署不在kube-system下，所以期望把这个CalicoNodeNamespace放到配置文件里。

**Comment by toby1991** [comment]
> > It seems that there are some network problems in your cluster.
> 
> 不是网络问题，是你代码里把namespace写死了，用calico operator部署不在kube-system下，所以期望把这个CalicoNodeNamespace放到配置文件里。

找到解法了，开的时候先开networkpolicy，才会装calico，这样就不会报错了

**Comment by ColorfulDick** [comment]
> > > > It seems that there are some network problems in your cluster.
> > > 
> > > 
> > > 不是网络问题，是你代码里把namespace写死了，用calico operator部署不在kube-system下，所以期望把这个CalicoNodeNamespace放到配置文件里。
> > 
> > 
> > 找到解法了，开的时候先开networkpolicy，才会装calico，这样就不会报错了
> 
> 没用，这个问题是当在已经安装了calico的集群里安装kubesphere后，打开ippool后报错，按calico官方文档安装的话calico的namespace默认是calico-system,而kubesphere的代码里写死了kube-system。

老哥，现在有解决方案了吗
