### ISSUE TITLE
Wrong position of configmap edit icon

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#4291]
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.
<img width="1237" alt="Xnip2021-09-27_17-47-14" src="https://user-images.githubusercontent.com/28883416/134886027-9ae6c550-5649-40f9-888c-04627f3e0c1a.png">

**Versions Used**
KubeSphere: 3.1.1
Brower: Chrome
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by yuswift** [comment]
> /kind bug /area console /assign @kubesphere/sig-console

you can't assign an issue to a group, instead you can cc them.
/cc @kubesphere/sig-console

**Comment by liuyp2018** [comment]
fixed 
/close
