### ISSUE TITLE
There is a "Run" button at the page of CRD .

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#4303]
**Describe the Bug**

There is a "Run" button at the page of CRD .
![image](https://user-images.githubusercontent.com/41519383/135074131-3e03e940-dda0-4142-9c3b-2ae2994ee671.png)

**Versions Used**
KubeSphere:3.1.1

**How To Reproduce**
1. Go to the pipeline page
2. Click on any pipeline where we can see the "RUN" button.
3. Exit the pipeline page and then go to the CRD page and click any CRD.
4. Then we can see there is a "Run" button at the page of CRD .
5.When i switch the language，the button disappear.......

**Comment by LinuxSuRen** [comment]
IMO, this bug is not related to DevOps.

/remove-area devops
/kind bug

**Comment by zryfish** [comment]
Issue fixed since v3.2.0.

/close
