### ISSUE TITLE
cannot receive notification emails after filter criteria for alarm names are set

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#4306]
**Describe the Bug**
1. Set the filter criteria for notification: Alarm names contain 'alert'.
2. However, cannot receive the email notification whose alert name contains 'alert'

![image](https://user-images.githubusercontent.com/36271543/135194380-cb020c14-56c1-44fe-b237-fabe453bcb54.png)

**Versions Used**
KubeSphere: nightly-2-210927
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @wanjunlei 
/area notification
/kind bug
/priority Medium

**Comment by wanjunlei** [comment]
Notification filtering does not support fuzzy matching.

**Comment by liuyp2018** [comment]
ok, so that closes the question
/close
