### ISSUE TITLE
Can wen open to add, delete and update CRDs

### ISSUE THREAD

**Issue by jerryhu1234** [kubesphere/kubesphere#4307]
On the management interface of kubesphere, CRD resource objects can be managed, including adding, updating, deleting and other operations.

**Comment by zryfish** [comment]
CRD is critical for some components, it's highly not recommended to modify/delete unless you're very clear about what you do.  In KubeSphere, logging/monitoring also depends on CRD, we are deliberately removing this feature of modifying CRDs. Better do it with kubectl or helm.

/close
