### ISSUE TITLE
Token should be required field 

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#4310]
**Describe the Bug**

![image](https://user-images.githubusercontent.com/36271543/135242009-be50c837-592c-4d12-afdd-67da547e588c.png)
![image](https://user-images.githubusercontent.com/36271543/135242372-142c1d2f-38a5-4ea9-ab3c-d1b617e3aa0e.png)

**Versions Used**
KubeSphere: nightly-20210927
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @xuliwenwenwen 
/area console
/kind bug
/priority Low
/milestone v3.2

**Comment by jioce** [comment]
issue is fixed in v3.3.0-alpha.0
