### ISSUE TITLE
Kubesphere not running on kind cluster on Linux/ARM64 as ks-installer pod is failing to run

### ISSUE THREAD

**Issue by odidev** [kubesphere/kubesphere#4314]
**What's your question**
Tried the Quick Start guide given in the README.md. But Kubesphere is not getting installed in the cluster as kubesphere pod "ks-installer" is failing with Error for Linux/ARM64. Docker image for ks-installer, kubespheredev/shell-operator:v1.0.0-beta.5-alpine3.13 not available for Linux/ARM64. Please point to location for these images on Linux/ARM64.

**Environment: OS & Hardware Information**
```
kind version
kind v0.11.1 go1.16.4 linux/arm64
```
```
uname -a
Linux 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:24:57 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```
```
Kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/arm64"}
```

**Error logs or message (Attach logs or screenshot)**
Kubesphere falied to install as ks-installer pod failed to run properly on Kind cluster

**Installer Version**
Command used for installation:
```
kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.1.1/kubesphere-installer.yaml
kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.1.1/cluster-configuration.yaml
```

**Comment by yuswift** [comment]
The community does not support arm arch.
