### ISSUE TITLE
Perform the installation, no normal print log

### ISSUE THREAD

**Issue by WonderLand33** [kubesphere/kubesphere#4315]
Perform the installation, no normal print log.

## command
```
./kk create cluster --with-kubernetes v1.20.4 --with-kubesphere v3.1.1
```
then enter `yes`

## environment：

centos8
4h8g

![image](https://user-images.githubusercontent.com/10755158/135402228-ddd5788a-00ce-4aea-b852-b0b742ec5c8b.png)

**Comment by yuswift** [comment]
Does it work if you use another machine?
