### ISSUE TITLE
cannot view container logs on the console

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#4316]
**Describe the Bug**
cannot view container logs on the console
<img width="912" alt="8398467e72d541f275d5e6e62f19197" src="https://user-images.githubusercontent.com/36271543/135431401-628b846a-6250-485e-8263-f7a65b824083.png">

**Versions Used**
KubeSphere: v3.2.0 alpha.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @zryfish 
/kind bug
/priority high

**Comment by benjaminhuo** [comment]
@harrisonliu5 would you take a look at this issue from front end and you can reach to @wenchajun  @wanjunlei if you need help from backend

**Comment by liuyp2018** [comment]
fixed in v3.2.0-rc.1
