### ISSUE TITLE
Setting kubesphere as multi-cluster mode stucks

### ISSUE THREAD

**Issue by zhm9484** [kubesphere/kubesphere#4317]
**What's your question**
I wanna set the kubesphere works in multi-cluster mode.
The ks-installer stucks after modifying clusterrole as host.
And I find that multiple ``pod/kubefed-xxx``s fail.

**Environment: OS & Hardware Information**

* Kubernetes v1.16

**Error logs or message (Attach logs or screenshot)**

Log of ks-installer:

> Start installing monitoring
> Start installing multicluster
> Start installing openpitrix
> Start installing network
> **************************************************
> Waiting for all tasks to be completed ...
> task network status is successful  (1/4)
> task openpitrix status is successful  (2/4)
> task monitoring status is successful  (3/4)
> *... stucks here ...*

Log of kubefed:

> kubefedconfig.core.kubefed.io/kubefed patched (no change)
> Kubefedconfig patched successfully!
> Error from server (Forbidden): deployments.extensions "kubefed-controller-manager" is forbidden: User "system:serviceaccount:kube-federation-system:kubefed-config-hook" cannot get resource "deployments" in API group "extensions" in the namespace "kube-federation-system"

**Installer Version**

v3.1.1

**Comment by yuswift** [comment]
This has been tested many times, please try again.
