### ISSUE TITLE
The prompt information of gateway setting is wrong

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#4326]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/68640256/136504330-144c78b2-b0bb-4fca-a6e0-0445f045ec9f.png)

**Versions Used**
KubeSphere:   host :`v3.2.0-alpha.1`
                         member: `v3.1.1-dirty`

**Expected behavior**
The host cluster does not have an icon prompting upgrade

/kind bug
/priority medium
/milestone v3.2
/assign @harrisonliu5

**Comment by zryfish** [comment]
Is this fixed yet?
