### ISSUE TITLE
traffic management page errors

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#4327]
**Describe the Bug**
**steps:**
1. enter the cluster configuration page, creating Cluster Gateway and enable  application traffic management
2. Enter the project manage page and create an application
3. Enter application Details-->traffic management page
4. error displayed
![image](https://user-images.githubusercontent.com/36271543/136506026-4e8c5896-a723-4d6a-af93-6ea52101cece.png)

**Versions Used**
KubeSphere: v3.2.0 alpha.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @RolandMa1986 
/kind bug
/priority high

**Comment by zryfish** [comment]
duplicate #4274 
/close
