### ISSUE TITLE
An error occurs when creating a FederatedDeployment and mounting volume after adding a member cluster to multi-cluster

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4329]
**Describe the Bug**
1. Existing project test contains host cluster and mem cluster, and there is a volume "volume"
2. Add a member cluster member to the test project
3. Create a FederatedDeployment, choose to mount the volume “volume”，The pod of  member cluster cannot be scheduled

![image](https://user-images.githubusercontent.com/88183150/136514332-a9d1029a-b03a-4655-bfc4-5ab7327c9b06.png)

![image](https://user-images.githubusercontent.com/88183150/136514473-0a71532b-d9ef-4b68-b75f-a013912656d0.png)

![image](https://user-images.githubusercontent.com/88183150/136514559-3900dbda-ebe6-495d-b033-311256a1cdab.png)

**Versions Used**
KubeSphere: v3.2.0-alpha.1

/kind bug
/@kubesphere/sig-kubesphere
/priority medium

**Comment by iawia002** [comment]
I don't think this is a problem, there is no local PV on the new member cluster that the Pod needs and it certainly can't be scheduled.

> The same problem exists when mounting config or secret

This is the same reason as above, the target cluster does not have the config/secret it needs so the Pod cannot be created.

**Comment by jioce** [comment]
I think that after adding  member cluster, when creating FederatedDeployment and mounting a storage volume, you should not be able to select a volume that does not exist in the member cluster
