### ISSUE TITLE
ks-apiserver CrashLoopBackOff

### ISSUE THREAD

**Issue by Hyakusenrenma** [kubesphere/kubesphere#4339]
\# kubectl logs ks-apiserver-b69dc4bb-clsm7 -n kubesphere-system 

F1009 14:44:43.409834       1 server.go:47] Failed to load configuration from diskerror parsing configuration file While parsing config: yaml: line 53: mapping values are not allowed in this context

https://kubesphere.com.cn/forum/d/5725-ks-apiserver

**Versions Used**
KubeSphere:3.1

**Environment**
How many nodes and their hardware configuration:

CentOS 7.5 / 3 masters:  8cpu/32g; 3 nodes: 8cpu/32g

**Comment by yuswift** [comment]
please check if there are tabs in your config file.

**Comment by Hyakusenrenma** [comment]
It was the  configmap kubesphere-config  fault。
