### ISSUE TITLE
The version displayed on the console doesn't match the actual version

### ISSUE THREAD

**Issue by pixiake** [kubesphere/kubesphere#4340]
**Describe the Bug**
The version displayed on the console doesn't match the actual version

**Versions Used**
KubeSphere: v3.2.0-alpha.1

![171d7804f63da10e4c209e070193c42](https://user-images.githubusercontent.com/22290449/136648460-4a6fafea-2f7b-4dbc-9589-9f627eeb04b2.png)

**Comment by harrisonliu5** [comment]
the version is set by https://github.com/kubesphere/console/issues/2007
