### ISSUE TITLE
Failed to enable workspace network isolation after upgrade ks 3.1.1 to ks 3.2-alpha.1

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#4344]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/68640256/136722634-c8b26014-ebb2-479b-abe9-f464f4cb4d17.png)

**Versions Used**
KubeSphere:    ks3.1.1 -->ks3.2-alpha.1

**Precondition**
ks version is `v3.1.1`

**How To Reproduce**
1. set     
              networkpolicy:
                   enabled: true
2. upgrade ks to `3.2-alpha.1`
3. enable workspace network isolation
4. see error

**Expected behavior**
enable workspace network isolation successed

/kind bug
/assign @wansir 
/priority High

**Comment by zryfish** [comment]
Is there an existing issue related to this problem? Please take a look @wansir

**Comment by wenxin-01** [comment]
https://github.com/kubesphere/kubesphere/issues/4147
