### ISSUE TITLE
Delete container health check error

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4345]
**Describe the Bug**
1. click edit,delete Liveness Check,click save,click to confirm 
2. The cluster pod is not updated,view pod details,Liveness Check still exist
3. Edit the container again, modify the image，click save,click to confirm 
4. The cluster pod is not updated,view pod details,image unchanged

https://user-images.githubusercontent.com/88183150/136738702-60093a11-41a3-4450-8bb3-74b6b846be36.mp4

**Versions Used**
KubeSphere: v3.2.0-alpha.1

/kind bug
/@kubesphere/sig-kubesphere
/priority medium

**Comment by jioce** [comment]
issue is not fixed

**Comment by harrisonliu5** [comment]
The federatedDeployment has changed but the single deployment has not changed. 

![image](https://user-images.githubusercontent.com/17872673/151114839-9dc5142e-ac30-4350-ab7a-49c91fb2e744.png)

![image](https://user-images.githubusercontent.com/17872673/151114990-11f39bdb-602c-48ad-9a9e-09db7433b4a7.png)

![image](https://user-images.githubusercontent.com/17872673/151114998-cc011a03-195f-4893-82da-71511f8fc974.png)

**Comment by iawia002** [comment]
> The federatedDeployment has changed but the single deployment has not changed. @iawia002
> 
> ![image](https://user-images.githubusercontent.com/17872673/151114839-9dc5142e-ac30-4350-ab7a-49c91fb2e744.png)

When deleting a probe, the entire key should be deleted, not just its value:

```
Failed to update Deployment "pro/tt" in cluster "host": Deployment.apps "tt" is invalid: [spec.template.spec.containers[0].livenessProbe: Required value: must specify a handler type, spec.template.spec.containers[0].readinessProbe: Required value: must specify a handler type]
```

Wrong:

```diff
- livenesserobe: {"/", port: 80, scheme: "HTTP"}, timeoutSeconds: 1, periodSeconds: 10}
+ livenesserobe: {}
```

Correct:

```diff
- livenesserobe: {"/", port: 80, scheme: "HTTP"}, timeoutSeconds: 1, periodSeconds: 10}
```

**Comment by jioce** [comment]
Survival probes are deleted, other probes are also deleted

1、Deployment contains liveness probe and start probe
![image](https://user-images.githubusercontent.com/88183150/163091699-4d479217-912b-4b1e-9f70-4e0b4874ec14.png)

2、Edit container settings, remove liveness probes
![image](https://user-images.githubusercontent.com/88183150/163091772-ae46704d-3c9f-411b-ad3a-ccf16cc641a8.png)

3、pod update，start probe not showing
![image](https://user-images.githubusercontent.com/88183150/163091837-7e2e00dd-3e0f-46d1-ae6c-8d633a9a25bf.png)

![image](https://user-images.githubusercontent.com/88183150/163092216-e5e1cc97-e353-4b7e-b65f-7e572e2108dd.png)

4、View yaml，start probe exists
![image](https://user-images.githubusercontent.com/88183150/163091980-1ce7cb76-e57e-4111-98da-c7185aeb52fa.png)

Versions Used
KubeSphere: v3.3.0-alpha.0

**Comment by zheng1** [comment]
@jioce Please check again in v3.3.0-alpha.1

**Comment by jioce** [comment]
the problem still exists in v3.3.0-alpha.2
![image](https://user-images.githubusercontent.com/88183150/167323296-b966cd63-6f63-4249-bf5a-2a2875eec128.png)

![image](https://user-images.githubusercontent.com/88183150/167323260-d1618d2d-554a-4af3-b607-1b142f273c49.png)

**Comment by weili520** [comment]
> the problem still exists in v3.3.0-alpha.2 ![image](https://user-images.githubusercontent.com/88183150/167323296-b966cd63-6f63-4249-bf5a-2a2875eec128.png)
> 
> ![image](https://user-images.githubusercontent.com/88183150/167323260-d1618d2d-554a-4af3-b607-1b142f273c49.png)

Please check it again and use this image: kubespheredev/ks-console:nightly-20220507, the image that v3.3.0-alpha.2 doesn't include the merge code, thanks a lot.

**Comment by weili520** [comment]
> > the problem still exists in v3.3.0-alpha.2 ![image](https://user-images.githubusercontent.com/88183150/167323296-b966cd63-6f63-4249-bf5a-2a2875eec128.png)
> > ![image](https://user-images.githubusercontent.com/88183150/167323260-d1618d2d-554a-4af3-b607-1b142f273c49.png)
> 
> Please check it again and use this image: kubespheredev/ks-console:nightly-20220507, the image that v3.3.0-alpha.2 doesn't include the merge code, thanks a lot.

I have checked it, it works well: 
![截屏2022-05-09 18 28 14](https://user-images.githubusercontent.com/33231138/167392305-0f4d8010-219e-4eb5-925c-f968f1243c36.png)

**Comment by jioce** [comment]
issue is fixed 
version：kubespheredev/ks-console:nightly-20220507
