### ISSUE TITLE
Edit the container synchronization host timezone, pod update failed

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4350]
**Describe the Bug**
1. Edit container ，choose synchronization host timezone，click save,click to confirm 
2. Pod failed to start

https://user-images.githubusercontent.com/88183150/136767774-87b90351-6091-4ea8-afdc-c9f86304262e.mp4

**Versions Used**
KubeSphere: v3.2.0-alpha.1
Ks-Console: nightly-20211010

/kind bug
/@kubesphere/sig-kubesphere
/priority high

**Comment by zryfish** [comment]
@jioce Can you confirm this is fixed in the latest release?

**Comment by jioce** [comment]
issue is fixed in v3.2.1
