### ISSUE TITLE
After notification filtering is set, the test email cannot be received

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#4354]
**Describe the Bug**
**steps:**
1. Set up the correct mail configuration
2. Set notification filtering
3. Perform configuration verification
4. The verification is successful and a test message is sent, but no test email is received
![image](https://user-images.githubusercontent.com/36271543/136910731-a24c755c-65ba-4d22-a591-82ed6a627de6.png)

**Versions Used**
KubeSphere: ks3.2 alpha.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/assign @wanjunlei
/priority Medium

**Comment by wanjunlei** [comment]
/assign @xuliwenwenwen 
The receiver should not include the notification filter when verifying.
