### ISSUE TITLE
Gateway status error

### ISSUE THREAD

**Issue by wenxinll** [kubesphere/kubesphere#4359]
**Versions Used**
KubeSphere:  `ks3.2 nightly-20211011`

**How To Reproduce**
1. `Set up a gateway for the cluster`
2. Go to any project details page in the cluster
3. Click on ' Application Workloads'
4. Click on 'Routes'

**Expected behavior**
Do not show 'Gateway Not Set'
![image](https://user-images.githubusercontent.com/68640256/137084595-96edd6b2-51d6-4ee0-998d-685d13cddb09.png)

/kind bug
/assign @kubesphere/sig-console 
/priority medium

**Comment by wenxin-01** [comment]
issue fixed in `nightly-20211013`
