### ISSUE TITLE
The console is pending while switch the different cluster

### ISSUE THREAD

**Issue by hurricane1988** [kubesphere/kubesphere#4362]
**Describe the Bug**
【version information】
Kubesphere version: 3.1.1
Kubernetes version: 1.20.4
Docker version: 19.3
【issue detail】
I login into the host console UI, and sometime the member cluster is pending while switch the cluster member.
But will be fine after refresh the brower several times.
The member cluster always fine when single login.

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/16606960/137113079-52fa812f-925d-4bc0-b6d6-2a017c64945e.png)

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by iawia002** [comment]
When this happens, can you check the network panel of the browser and see if there are any errors?
