### ISSUE TITLE
Related federated namespace cannot be deleted after workspace has been deleted

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#4364]
**Describe the Bug**

Create a workspace without grant the host cluster, related federated namespace cannot be deleted after workspace has been deleted.

Host namaspace cannot bind the workspace's lifecycle if host cluster is not grant to the workspace.

OwnerReferences is missing:

![image](https://user-images.githubusercontent.com/8263040/137277225-f4409591-370d-4ce9-9e46-a893bb87669c.png)

**Versions Used**
KubeSphere: v3.1.0

/kind bug
/priority high

**Comment by JohnNiang** [comment]
Hi @wansir , will this issue be resolved in `v3.2.0`? If that's true, please add this issue into milestone `v3.2`.
/area controller-manager
