### ISSUE TITLE
 queues disaper in rabbit mq management  

### ISSUE THREAD

**Issue by javaXiaoHan** [kubesphere/kubesphere#4372]
<img width="960" alt="11" src="https://user-images.githubusercontent.com/32090060/137853035-5cd7d213-1aa0-4f72-af92-310b1cd5e735.png">
<img width="875" alt="22" src="https://user-images.githubusercontent.com/32090060/137853046-9cc12168-26e4-4cdd-b3c4-22c809bcb977.png">
<img width="666" alt="33" src="https://user-images.githubusercontent.com/32090060/137853643-9a8086cd-3a3e-403e-8fc1-4cae6fcde9e0.png">

**Comment by javaXiaoHan** [comment]
sometimes it shows queues ,sometimes there is no queue

**Comment by dkeven** [comment]
How did you deploy the rabbitmq cluster? Do the 2 mq instances belong to the same cluster?

Please paste the neccesary yaml/conf contents. I don't think this is a KubeSphere issue, though.

**Comment by RolandMa1986** [comment]
/close 
Hi @javaXiaoHan, I'm going to close this issue first since it's not a KubeSphere issue.
