### ISSUE TITLE
problem when adding or deleting gateway copies

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#4381]
**Describe the Bug**
After adding the number of copies, no new container group is displayed on the page

![image](https://user-images.githubusercontent.com/36271543/138204001-fee290ce-ab0b-45e7-8948-4a9a464969f1.png)

error occurred while reducing the number of copies
![image](https://user-images.githubusercontent.com/36271543/138204057-e645ed40-b22d-430e-a68d-ef7e8fab857f.png)

**Versions Used**

KubeSphere: v3.2.0-rc.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @harrisonliu5
/assign @RolandMa1986 
/area console
/kind bug
/priority Medium

**Comment by harrisonliu5** [comment]
This is the same as https://github.com/kubesphere/console/issues/2740

**Comment by jioce** [comment]
issue is fixed in v3.3.0-alpha.0
