### ISSUE TITLE
After the project is deleted, the gateway under the project is not deleted

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#4397]
**Describe the Bug**
After the project is deleted, the gateway under the project is not deleted

**Versions Used**
KubeSphere: v3.2.0-rc.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @RolandMa1986 
/kind bug
/priority Medium

**Comment by jioce** [comment]
issue fixed in v3.3.0-alpha.0
