### ISSUE TITLE
the cluster failed to start after restart the computer

### ISSUE THREAD

**Issue by john1337** [kubesphere/kubesphere#4403]
<!--
You don't need to remove this comment section, it's invisible on the issues page.

## General remarks

the kubesphere cluster failed to start after machine reboot,i think it's very common to restart the computer,so in my opinion it's critical to resolve,thanks 

**Describe the Bug**
the kubesphere cluster failed to start after machine reboot,there'are only about 9 containers starting in work nodes,thry are 
 k8s_calico、k8s_kube-rbac-proxy、k8s_node-exporter、k8s_node-cache、k8s_kube-proxy、k8s_POD_calico-node、k8s_POD_node-exporter、k8s_POD_nodelocaldns、k8s_POD_kube-proxy，only these contailer started,other containers didn't start

**Versions Used**
KubeSphere:
Kubernetes: 3.1.1

**Environment**

ubuntu20.04 1 master 3 workers

**Comment by iawia002** [comment]
Can you describe it more clearly and provide some screenshots and logs of the errors?

**Comment by john1337** [comment]
> Can you describe it more clearly and provide some screenshots and logs of the errors?

i run systemctl restart docker ,reboot in ubuntu20.04 ,the kubesphere failed to start,there are only 9 containers started in the work nodes,but there should be about 40+ containers in the work node 

![image](https://user-images.githubusercontent.com/11956341/139615025-7a1ff868-aba4-4589-9f01-ccd277aba95a.png)

**Comment by iawia002** [comment]
Can you use `kubectl get pod -n kubesphere-system` to see if the system components start properly?

**Comment by john1337** [comment]
> Can you use `kubectl get pod -n kubesphere-system` to see if the system components start properly?

here is the snapshot pic :

![image](https://user-images.githubusercontent.com/11956341/139617308-225aaf1c-c021-47c0-862a-60b4005f0da9.png)

**Comment by iawia002** [comment]
> > Can you use `kubectl get pod -n kubesphere-system` to see if the system components start properly?
> 
> here is the snapshot pic :
> 
> ![image](https://user-images.githubusercontent.com/11956341/139617308-225aaf1c-c021-47c0-862a-60b4005f0da9.png)

You need to check the pods in the `kubesphere-system` namespace too and figure out why some pods are in the `Error` status.

**Comment by john1337** [comment]
> > > Can you use `kubectl get pod -n kubesphere-system` to see if the system components start properly?
> > 
> > 
> > here is the snapshot pic :
> > ![image](https://user-images.githubusercontent.com/11956341/139617308-225aaf1c-c021-47c0-862a-60b4005f0da9.png)
> 
> You need to check the pods in the `kubesphere-system` namespace too and figure out why some pods are in the `Error` status.

here's the results

run kubectl get pod -n kubesphere-system
![image](https://user-images.githubusercontent.com/11956341/139630870-48c696cf-fc0b-4f77-9df5-432b8bb2dd98.png)

run kubectl get nodes 
![image](https://user-images.githubusercontent.com/11956341/139630895-b15b83c3-a202-4d55-9a25-3b5dc7e03971.png)

**Comment by john1337** [comment]
by the way,when i run kubectl get po -n kube-system on work nodes,it returns 

The connection to the server lb.kubesphere.local:6443 was refused - did you specify the right host or port?

**Comment by iawia002** [comment]
> run kubectl get nodes
> ![image](https://user-images.githubusercontent.com/11956341/139630895-b15b83c3-a202-4d55-9a25-3b5dc7e03971.png)

You need to solve the problem that the nodes are not ready. When their status becomes Ready, the cluster should be fine.

> by the way,when i run kubectl get po -n kube-system on work nodes,it returns
> 
> The connection to the server lb.kubesphere.local:6443 was refused - did you specify the right host or port?

This is normal, just execute this command on the master node.
