### ISSUE TITLE
Line Wrapping on KubeSphere console when specifying workload for a service 

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#4404]
**Describe the Bug**
Line Wrapping on KubeSphere console when specifying workload for a service 

For UI issues please also add a screenshot that shows the issue.
<img width="466" alt="Xnip2021-10-27_08-48-18" src="https://user-images.githubusercontent.com/28883416/139629800-8b690896-77ff-406d-b628-f2bd9aa7ddee.png">
**Versions Used**
KubeSphere: 3.1.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by tracer1023** [comment]
3.2.1 version has fixed

**Comment by jioce** [comment]
issue is fixed in v3.3.0-alpha.0
