### ISSUE TITLE
After v3.1.1 is deployed, perform operations described in the official document. Functions related to multiple clusters are unavailable

### ISSUE THREAD

**Issue by 2hangchen** [kubesphere/kubesphere#4409]
**Describe the Bug**
After v3.1.1 is deployed, perform operations described in the official document. Functions related to multiple clusters are unavailable
For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/31329928/139773224-bdaae06b-62e1-430a-a6cd-d7dfc93f3b7a.png)
![image](https://user-images.githubusercontent.com/31329928/139773424-4d64aa1e-bf97-4bb1-9990-9e603c8aa1cb.png)

**Versions Used**
KubeSphere:v3.1.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by iawia002** [comment]
Are you saying that the multi-cluster feature is not available? Check the documentation to see if you have enabled this feature.

https://v3-1.docs.kubesphere.io/docs/multicluster-management/

**Comment by 2hangchen** [comment]
> Are you saying that the multi-cluster feature is not available? Check the documentation to see if you have enabled this feature.
> 
> https://v3-1.docs.kubesphere.io/docs/multicluster-management/

There is no cluster import function

**Comment by zryfish** [comment]
Please go and read our docs first, https://v3-1.docs.kubesphere.io/docs/multicluster-management/enable-multicluster/direct-connection/

**Comment by 2hangchen** [comment]
> Please go and read our docs first, https://v3-1.docs.kubesphere.io/docs/multicluster-management/enable-multicluster/direct-connection/

I don't understand..I followed the instructions in the documentation and there was no related multi-cluster panel..
![1](https://user-images.githubusercontent.com/31329928/139794351-dce65daa-3718-4ee2-b00a-75af47225922.gif)
