### ISSUE TITLE
load the entire configmap as environment variables

### ISSUE THREAD

**Issue by wujie1993** [kubesphere/kubesphere#4410]
**What's it about?**

Able to load the entire configmap as environment variables, without specifying a key.

**What's the reason why we need it?**

In applications deployed in microservices, there are scenarios where multiple services share the same environment variables, and it is more convenient to load environment variables through configmap. If there are many environment variables, it is not convenient to import them one by one. 

I believe this is an important feature for Kubesphere. There're a few use cases:

* load env vars from configmap with many items.

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

**Comment by RolandMa1986** [comment]
@VioZhang

**Comment by XiaohuiSept** [comment]
Drawing design as follow:
https://www.figma.com/file/q3urPSh20JziH7RYn8v8Ox/KubeSphere-3.3.0?node-id=26%3A44102

**Comment by VioZhang** [comment]
![image](https://user-images.githubusercontent.com/41519383/157831218-b4986eab-c48b-4a53-8513-c998cda421e0.png)
![image](https://user-images.githubusercontent.com/41519383/157831262-33b4a771-327c-4ab8-9235-55b688d3280a.png)
![image](https://user-images.githubusercontent.com/41519383/157831299-e8cca0ab-38bc-495c-abab-cbd949ee26c9.png)

**Comment by jioce** [comment]
issue is fixed

version used
v3.3.0-rc.0
