### ISSUE TITLE
Can't add service when deleted metadata by advanced settings

### ISSUE THREAD

**Issue by yJunS** [kubesphere/kubesphere#4414]
When I deleted the metadata by advanced settings, I can't add the service. The default value is like this:
![default_value](https://user-images.githubusercontent.com/20575981/139813672-bd0d718d-9e53-425e-9641-49ceb1c29485.png)
but when I deleted the metadata, tips `the label can not null`, and checkbox of `Add metadata` can not cancel selection
![deleted_value](https://user-images.githubusercontent.com/20575981/139813783-0ae4af97-bff0-456a-b598-57c9806bc453.png)

**Comment by RolandMa1986** [comment]
@yJunS This is work as designed. You must have at least one label for deployment or statefulsets. And in KubeSpphere 3.2.0 the checkbox was removed from UI. 
/kind support
