### ISSUE TITLE
After using an external es cluster, the total number of logs is only 10000, 

### ISSUE THREAD

**Issue by bigfacewo** [kubesphere/kubesphere#4415]
**Describe the Bug**
After using an external es cluster, the total number of logs is only 10000, but the actual number of logs exceeds 10000.
![image](https://user-images.githubusercontent.com/31603897/140002776-0b96e57e-1d87-42cc-ac4c-b6d9440ff2ff.png)

**Versions Used**
KubeSphere:  3.1
Kubernetes:  v1.20.4

**Environment**
How many nodes and their hardware configuration:
Centos 7.1 / 3master: 8cpu/32g; 14 nodes:8cpu:32g

**How To Reproduce**
1. First, the logging system of kubesphere was started, but the external es cluster was not used
2. Modify the "ks-installer" configuration to use an external es cluster

**Expected behavior**
Displays the actual number of logs.

Of course, this has no impact on actual use...

**Comment by bigfacewo** [comment]
This is an ES configuration problem

**Comment by luoyuctl** [comment]
how it works?

**Comment by bigfacewo** [comment]
@luoyuctl Maybe you need to modify the "max_result_window" configuration of ES. I changed es to the "5.x" version.
https://zhuanlan.zhihu.com/p/401770571
https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html

**Comment by luoyuctl** [comment]
> @luoyuctl Maybe you need to modify the "max_result_window" configuration of ES. I changed es to the "5.x" version. https://zhuanlan.zhihu.com/p/401770571 https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html

i already try it , but it not works, what's your elasticsearch version?

**Comment by bigfacewo** [comment]
@luoyuctl 6.8.18
But it may also be the problem of kubesphere. Look here: https://kubesphere.com.cn/forum/d/6143-logginges1000010000/2
