### ISSUE TITLE
Failed to download image: harbork8s.example.com/kubesphere/pause:3.4.1 for 3.2.0

### ISSUE THREAD

**Issue by copenbusiness** [kubesphere/kubesphere#4421]
**Describe the Bug**
have not image pause

**Versions Used**
KubeSphere: 3.2.0
Kubernetes: (If KubeSphere installer used, you can skip this):1.21.5

**Environment**
How many nodes and their hardware configuration:

 CentOS 7.9 / 1 masters:  2cpu/8g; 2 nodes: 2cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. following the guide https://kubesphere.io/docs/installing-on-linux/introduction/air-gapped-installation,run :
./kk create cluster -f config-sample.yaml

**Expected behavior**
INFO[12:01:05 CST] Get cluster status
INFO[12:01:06 CST] Installing Container Runtime ...
INFO[12:01:07 CST] Start to download images on all nodes
[node2] Downloading image: harbork8s.example.com/kubesphere/pause:3.4.1
[master] Downloading image: harbork8s.example.com/kubesphere/pause:3.4.1
[node1] Downloading image: harbork8s.example.com/kubesphere/pause:3.4.1
ERRO[12:01:40 CST] Failed to download image: harbork8s.example.com/kubesphere/pause:3.4.1: Failed to exec command: sudo env PATH=$PATH docker pull harbork8s.example.com/kubesphere/pause:3.4.1
Error response from daemon: Get "https://harbork8s.example.com/v2/": x509: certificate signed by unknown authority: Process exited with status 1  node=10.11.13.242
ERRO[12:01:40 CST] Failed to download image: harbork8s.example.com/kubesphere/pause:3.4.1: Failed to exec command: sudo env PATH=$PATH docker pull harbork8s.example.com/kubesphere/pause:3.4.1
Error response from daemon: Get "https://harbork8s.example.com/v2/": x509: certificate signed by unknown authority: Process exited with status 1  node=10.11.13.241
ERRO[12:01:41 CST] Failed to download image: harbork8s.example.com/kubesphere/pause:3.4.1: Failed to exec command: sudo env PATH=$PATH docker pull harbork8s.example.com/kubesphere/pause:3.4.1
Error response from daemon: unknown: repository kubesphere/pause not found: Process exited with status 1  node=10.11.13.240
WARN[12:01:41 CST] Task failed ...
WARN[12:01:41 CST] error: interrupted by error
Error: Failed to pre-pull images: interrupted by error
Usage:
  kk create cluster [flags]

Flags:
      --container-manager string   Container runtime: docker, crio, containerd and isula. (default "docker")
      --download-cmd string        The user defined command to download the necessary binary files. The first param '%s' is output path, the second param '%s', is the URL (default "curl -L -o %s %s")
  -f, --filename string            Path to a configuration file
  -h, --help                       help for cluster
      --skip-pull-images           Skip pre pull images
      --with-kubernetes string     Specify a supported version of kubernetes (default "v1.21.5")
      --with-kubesphere            Deploy a specific version of kubesphere (default v3.2.0)
      --with-local-storage         Deploy a local PV provisioner
  -y, --yes                        Skip pre-check of the installation

Global Flags:
      --debug        Print detailed information (default true)
      --in-cluster   Running inside the cluster

Failed to pre-pull images: interrupted by error
[root@master kubesphere]# docker images | grep pause
[root@master kubesphere]#

**Comment by copenbusiness** [comment]
[root@master tmp]# cat images-list.txt | grep pause
[root@master tmp]# cat images-list.txt | grep wordpress
wordpress:4.8-apache
[root@master tmp]#

**Comment by copenbusiness** [comment]
if I download the image-list for 3.1.1

[root@master tmp]# curl -L -O https://github.com/kubesphere/ks-installer/releases/download/v3.1.1/images-list.txt
[root@master tmp]# cat images-list.txt | grep pause
kubesphere/pause:3.1
kubesphere/pause:3.2
[root@master tmp]#

**Comment by RolandMa1986** [comment]
/area  installation 
@kubesphere/sig-installation
