### ISSUE TITLE
Logging system fail to connect Amazon opensearch's es.

### ISSUE THREAD

**Issue by elizabethvik** [kubesphere/kubesphere#4424]
**Describe the Bug**
After I install logging system and config the es url, it didn't work, and the deamonset fluent-bit's log is :

[2021/11/05 07:21:44] [error] [output:es:es.0] HTTP status=403 URI=/_bulk, response:

 {"message":"Authorization header requires 'Credential' parameter. Authorization header requires 'Signature' parameter. Authorization header requires 'SignedHeaders' parameter. Authorization header requires existence of either a 'X-Amz-Date' or a 'Date' header. Authorization=Basic a2luZ2RhdGFFUzIxQCE6a2luZ2RhdGE="}

When I use 3.1.1, the logging system works(although I have to use my es's vpc ip than host). But now, neither host nor ip I can use to make logging system work properly.
**Versions Used**
KubeSphere:3.2.0
Kubernetes: 1.21
Amazon Opensearch's Elasticsearch 7.10

**Comment by FeynmanZhou** [comment]
@kubesphere/sig-observability

**Comment by wenchajun** [comment]
In kubesphere3.2, the default version of fluentbit was changed from 1.6.9 to 1.8.3.You can roll Fluentbit back to V1.6.9 yourself.
IMO, I think that's what's causing your problem.https://github.com/fluent/fluent-bit/pull/4147
Fortunately, they fixed it in fluentbitv1.8.8   
https://fluentbit.io/announcements/v1.8.8/

**Comment by elizabethvik** [comment]
> In kubesphere3.2, the default version of fluentbit was changed from 1.6.9 to 1.8.3.You can roll Fluentbit back to V1.6.9 yourself. IMO, I think that's what's causing your problem.[fluent/fluent-bit#4147](https://github.com/fluent/fluent-bit/pull/4147) Fortunately, they fixed it in fluentbitv1.8.8 https://fluentbit.io/announcements/v1.8.8/

I update fluentbit to v1.8.8, and in the fluentbit container it doesn't alarm error anymore. But when I click Tool box's container log search, it still raise a Internal Server Error:
```
Internal Server Error
ReadMapCB: expect { or n, but found &lt;, error found in #1 byte of ...|&lt;html&gt; &lt;he|..., bigger context ...|&lt;html&gt; &lt;head&gt;&lt;title&gt;400 The plain HTTP request was|...
```

I check the chrome console and it seems these api return code 500 and the error message.

`/kapis/tenant.kubesphere.io/v1alpha2/logs?operation=histogram&interval=30m&start_time=1636299822&end_time=1636343022`


`/kapis/tenant.kubesphere.io/v1alpha2/logs?operation=statistics&start_time=1636300800&end_time=1636343022`

Any idea to solve this problem?

**Comment by wenchajun** [comment]
> > In kubesphere3.2, the default version of fluentbit was changed from 1.6.9 to 1.8.3.You can roll Fluentbit back to V1.6.9 yourself. IMO, I think that's what's causing your problem.[fluent/fluent-bit#4147](https://github.com/fluent/fluent-bit/pull/4147) Fortunately, they fixed it in fluentbitv1.8.8 https://fluentbit.io/announcements/v1.8.8/
> 
> I update fluentbit to v1.8.8, and in the fluentbit container it doesn't alarm error anymore. But when I click Tool box's container log search, it still raise a Internal Server Error:
> 
> ```
> Internal Server Error
> ReadMapCB: expect { or n, but found &lt;, error found in #1 byte of ...|&lt;html&gt; &lt;he|..., bigger context ...|&lt;html&gt; &lt;head&gt;&lt;title&gt;400 The plain HTTP request was|...
> ```
> 
> I check the chrome console and it seems these api return code 500 and the error message.
> 
> `/kapis/tenant.kubesphere.io/v1alpha2/logs?operation=histogram&interval=30m&start_time=1636299822&end_time=1636343022`
> 
> `/kapis/tenant.kubesphere.io/v1alpha2/logs?operation=statistics&start_time=1636300800&end_time=1636343022`
> 
> Any idea to solve this problem?

what name of fluentbit image do you have? My advice is to change the image to the appropriate version. You can `kubectl edit fluentbits.logging.kubesphere.io  -n kubesphere-logging-system`,
then Modifying the `spec.image` field. You can set `kubesphere/fluent-bit:v1.6.9` or `kubesphere/fluent-bit:v1.7.3`
