### ISSUE TITLE
fluent-bit can not runing in KubeSphere version 3.2.0

### ISSUE THREAD

**Issue by 760515805** [kubesphere/kubesphere#4425]
**Describe the Bug**

fluent-bit can not runing，Every configuration is default

My KubeSphere is upgraded from 3.1.1 to 3.2.0, The log function is normally used in version 3.1.1

**Versions Used**
KubeSphere: 3.2.0
Kubernetes: 1.21.5

**Environment**
How many nodes and their hardware configuration:
CentOS 7.9 / 3 masters:  8cpu/32g; 3 nodes: 16cpu64g

**How To Reproduce**
![image](https://user-images.githubusercontent.com/16426260/140675485-6382017c-c9ec-4618-8c38-dfc45973c3f9.png)

**Expected behavior**

**Comment by 760515805** [comment]
When I close the log and audit function and delete the container and reopen it, the problem still exists
###fluent-bit-config
```
fluent-bit.conf:
[Service]
    Parsers_File    parsers.conf
[Input]
    Name    systemd
    Path    /var/log/journal
    DB    /fluent-bit/tail/docker.db
    DB.Sync    Normal
    Tag    service.docker
    Systemd_Filter    _SYSTEMD_UNIT=docker.service
[Input]
    Name    systemd
    Path    /var/log/journal
    DB    /fluent-bit/tail/kubelet.db
    DB.Sync    Normal
    Tag    service.kubelet
    Systemd_Filter    _SYSTEMD_UNIT=kubelet.service
[Input]
    Name    tail
    Path    /var/log/containers/*.log
    Exclude_Path    /var/log/containers/*_kubesphere-logging-system_events-exporter*.log,/var/log/containers/kube-auditing-webhook*_kubesphere-logging-system_kube-auditing-webhook*.log
    Refresh_Interval    10
    Skip_Long_Lines    true
    DB    /fluent-bit/tail/pos.db
    DB.Sync    Normal
    Mem_Buf_Limit    5MB
    Tag    kube.*
[Input]
    Name    tail
    Path    /var/log/containers/kube-auditing-webhook*_kubesphere-logging-system_kube-auditing-webhook*.log
    Refresh_Interval    10
    Skip_Long_Lines    true
    DB    /fluent-bit/tail/pos-auditing.db
    DB.Sync    Normal
    Mem_Buf_Limit    5MB
    Tag    kube_auditing
[Filter]
    Name    parser
    Match    kube_auditing
    Parser    json
[Filter]
    Name    modify
    Match    kube_auditing
    Condition    Key_does_not_exist    AuditID    
    Add    ignore    true
[Filter]
    Name    grep
    Match    kube_auditing
    Exclude    ignore true
[Filter]
    Name    kubernetes
    Match    kube.*
    Kube_URL    https://kubernetes.default.svc:443
    Kube_CA_File    /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File    /var/run/secrets/kubernetes.io/serviceaccount/token
    Labels    false
    Annotations    false
[Filter]
    Name    nest
    Match    kube.*
    Operation    lift
    Nested_under    kubernetes
    Add_prefix    kubernetes_
[Filter]
    Name    modify
    Match    kube.*
    Remove    stream
    Remove    kubernetes_pod_id
    Remove    kubernetes_host
    Remove    kubernetes_container_hash
[Filter]
    Name    nest
    Match    kube.*
    Operation    nest
    Wildcard    kubernetes_*
    Nest_under    kubernetes
    Remove_prefix    kubernetes_
[Filter]
    Name    lua
    Match    service.*
    script    /fluent-bit/config/systemd.lua
    call    add_time
    time_as_table    true
[Output]
    Name    es
    Match_Regex    (?:kube|service)\.(.*)
    Host    atai-testing-eck-cluster-es-http.elastic-system
    Port    9200
    Logstash_Format    true
    Logstash_Prefix    ks-k8s-log
    Time_Key    @timestamp
[Output]
    Name    es
    Match    kube_auditing
    Host    atai-testing-eck-cluster-es-http.elastic-system
    Port    9200
    Logstash_Format    true
    Logstash_Prefix    ks-k8s-auditing
    Generate_ID    true
```
![image](https://user-images.githubusercontent.com/16426260/140679689-1beeaf55-f5cc-47d4-bc37-94b83e28d406.png)

**Comment by wanjunlei** [comment]
You can resolve this by follow

Run this command
```
kubectl edit inputs.logging.kubesphere.io -n kubesphere-logging-system tail
```

Add

```
spec:
  tail:
    parser: docker
```

Run this command
```
kubectl edit filters.logging.kubesphere.io -n kubesphere-logging-system filter-auditing
```

Add
```
spec:
  filters:
  - parser:
      keyName: log
```

Then, wait for the fluent bit restart or manual restart of the fluent bit daemonset.

**Comment by 760515805** [comment]
> You can resolve this by follow
> 
> Run this command
> 
> ```
> kubectl edit inputs.logging.kubesphere.io -n kubesphere-logging-system tail
> ```
> 
> Add
> 
> ```
> spec:
>   tail:
>     parser: docker
> ```
> 
> Run this command
> 
> ```
> kubectl edit filters.logging.kubesphere.io -n kubesphere-logging-system filter-auditing
> ```
> 
> Add
> 
> ```
> spec:
>   filters:
>   - parser:
>       keyName: log
> ```
> 
> Then, wait for the fluent bit restart or manual restart of the fluent bit daemonset.

It can run normally according to the method provided
But when I turn off the log function and re-open the log function, filter-auditing will be overwritten back to the original configuration

**Comment by wenchajun** [comment]
In this path CRD -> ClusterConfiguration->ks-installer  Add ContainerRuntime: docker to the ks-installer file as follows
logging:
containerruntime: docker
enabled: true
logsidecar:
enabled: true
replicas: 2
Then let ks-Intaller perform the installation again

**Comment by zryfish** [comment]
@wenchajun Better to format these configurations with a code block, it's difficult to read now.

**Comment by 760515805** [comment]
How should I modify the configuration file fluent-bit-config, because now every time I modify the point and save, it will be restored back to the original configuration
Because my java program needs multiple lines to collect logs

**Comment by wenchajun** [comment]
> How should I modify the configuration file fluent-bit-config, because now every time I modify the point and save, it will be restored back to the original configuration
> Because my java program needs multiple lines to collect logs

Questions about use can be found here https://github.com/fluent/fluentbit-operator. Welcome to make relevant issue. Fluentbit is controlled by fluentbit-operator. You must modify the configuration by modifying the corresponding CRD

**Comment by 760515805** [comment]
When i delete the audit operator deployment And set ks-installer auditing to false
Waiting for the end of the restart, Then reopen auditing to true, audit operator deployment does not exist
After retrying a few times, it is still the same





when

**Comment by 760515805** [comment]
The UI is normal
![image](https://user-images.githubusercontent.com/16426260/140897986-7ae1abea-2f0e-4581-8f0c-eb6b0820fef2.png)
![image](https://user-images.githubusercontent.com/16426260/140898037-67cc50ae-dc98-40a8-a668-d1ef6ab0f3e7.png)

**Comment by wenchajun** [comment]
> And set ks-installer auditing to false
> Waiting for the end of the restart, Then reopen auditing to true, audit operator deployment does not exist
> After retrying a few times, it is still the same

That's a question about Ks-installer. You should do this `
kubectl edit cc -n kubesphere-system ks-installer`.then delete status that you want to reinstall.And `kubectl rollout restart deploy -n kubesphere-system ks-installer`.
Make sure you add this field.In this path CRD -> ClusterConfiguration->ks-installer Add ContainerRuntime: docker to the ks-installer file as follows
```
logging:
containerruntime: docker
enabled: true
logsidecar:
```

**Comment by 760515805** [comment]
It's useless, I restarted it many times
![image](https://user-images.githubusercontent.com/16426260/140904684-bd175a3f-b412-4f50-bf1b-fa92b6fd1b96.png)
The log shows success, but there is no deployment
![image](https://user-images.githubusercontent.com/16426260/140904911-bda73dcd-4fc5-4555-aa58-8cbfd05ae24e.png)

**Comment by 760515805** [comment]
> > And set ks-installer auditing to false
> > Waiting for the end of the restart, Then reopen auditing to true, audit operator deployment does not exist
> > After retrying a few times, it is still the same
> 
> That's a question about Ks-installer. You should do this ` kubectl edit cc -n kubesphere-system ks-installer`.then delete status that you want to reinstall.And `kubectl rollout restart deploy -n kubesphere-system ks-installer`. Make sure you add this field.In this path CRD -> ClusterConfiguration->ks-installer Add ContainerRuntime: docker to the ks-installer file as follows
> 
> ```
> logging:
> containerruntime: docker
> enabled: true
> logsidecar:
> ```

It's useless, I restarted it many times
![image](https://user-images.githubusercontent.com/16426260/140904684-bd175a3f-b412-4f50-bf1b-fa92b6fd1b96.png)
The log shows success, but there is no deployment
![image](https://user-images.githubusercontent.com/16426260/140904911-bda73dcd-4fc5-4555-aa58-8cbfd05ae24e.png)

**Comment by wenchajun** [comment]
> > > And set ks-installer auditing to false
> > > Waiting for the end of the restart, Then reopen auditing to true, audit operator deployment does not exist
> > > After retrying a few times, it is still the same
> > 
> > 
> > That's a question about Ks-installer. You should do this ` kubectl edit cc -n kubesphere-system ks-installer`.then delete status that you want to reinstall.And `kubectl rollout restart deploy -n kubesphere-system ks-installer`. Make sure you add this field.In this path CRD -> ClusterConfiguration->ks-installer Add ContainerRuntime: docker to the ks-installer file as follows
> > ```
> > logging:
> > containerruntime: docker
> > enabled: true
> > logsidecar:
> > ```
> 
> It's useless, I restarted it many times ![image](https://user-images.githubusercontent.com/16426260/140904684-bd175a3f-b412-4f50-bf1b-fa92b6fd1b96.png) The log shows success, but there is no deployment ![image](https://user-images.githubusercontent.com/16426260/140904911-bda73dcd-4fc5-4555-aa58-8cbfd05ae24e.png)

Did you execute the following command? `kubectl edit cc -n kubesphere-system ks-installer` and delete the status that you want to reinstall. Finally ` kubectl rollout restart deploy -n kubesphere-system ks-installer`

**Comment by 760515805** [comment]
> delete the status

delete the status

**Comment by 760515805** [comment]
> delete the status that you want to reinstall

what does this mean and where to modify?

**Comment by wenchajun** [comment]
> > delete the status that you want to reinstall
> 
> what does this mean and where to modify?

`kubectl edit cc -n kubesphere-system ks-installer` 
Delete the components shown in the red box and check whether the log system can be rebuilt
![1636510733(1)](https://user-images.githubusercontent.com/39892300/141038338-13517fa4-60b7-4483-9af1-5bd9b1e72e48.png)
then `kubectl rollout restart deploy -n kubesphere-system ks-installer`
It will take a while for the ks-installer to reinstall.

**Comment by 760515805** [comment]
> > > delete the status that you want to reinstall
> > 
> > 
> > what does this mean and where to modify?
> 
> `kubectl edit cc -n kubesphere-system ks-installer` Delete the components shown in the red box and check whether the log system can be rebuilt ![1636510733(1)](https://user-images.githubusercontent.com/39892300/141038338-13517fa4-60b7-4483-9af1-5bd9b1e72e48.png) then `kubectl rollout restart deploy -n kubesphere-system ks-installer` It will take a while for the ks-installer to reinstall.
It's useless，I tried the above operation several times
![Uploading image.png…]()
From the UI, the fluent-bit operator is deployed repeatedly, but there is still no audit operator 
![Uploading image.png…]()

**Comment by wenchajun** [comment]
> > > > delete the status that you want to reinstall
> > > 
> > > 
> > > what does this mean and where to modify?
> > 
> > 
> > `kubectl edit cc -n kubesphere-system ks-installer` Delete the components shown in the red box and check whether the log system can be rebuilt ![1636510733(1)](https://user-images.githubusercontent.com/39892300/141038338-13517fa4-60b7-4483-9af1-5bd9b1e72e48.png) then `kubectl rollout restart deploy -n kubesphere-system ks-installer` It will take a while for the ks-installer to reinstall.
> 
> It's useless，I tried the above operation several times ![image](https://user-images.githubusercontent.com/16426260/141042767-82cc3ce0-9995-4a40-84fe-16b0973ebdaa.png)
> 
> From the UI, the fluent-bit operator is deployed repeatedly, but there is still no audit operator ![image](https://user-images.githubusercontent.com/16426260/141042808-687ea437-35ea-4c40-ba95-68d2ca3bb199.png)

Each field is different, did you delete the Auditing field? If you have the installation problem, welcome to https://github.com/kubesphere/ks-installer to ask questions

**Comment by happywzy** [comment]
问题解决了吗？我遇到了同样的问题，试了上面的方法没有用啊 @760515805

**Comment by 760515805** [comment]
> 问题解决了吗？我遇到了同样的问题，试了上面的方法没有用啊 @760515805

```
logging:
    containerruntime: docker
    enabled: true
```
1. Add  `containerruntime: docker` 
2. delete status `kubectl edit cc -n kubesphere-system ks-installer`
![image](https://user-images.githubusercontent.com/16426260/142157284-e274095a-26e9-4148-9b5c-e57d4740eda5.png)
3. restart `kubectl rollout restart deploy -n kubesphere-system ks-installer`
