### ISSUE TITLE
Can't update kubesphere-router config file，save overwrite

### ISSUE THREAD

**Issue by zhouwenblog** [kubesphere/kubesphere#4427]
upgrade from 3.1.1 to kubesphere 3.2.0  then new  router compoment 'kubesphere-router-XXXX' can't worked in offline network environment.
the compoment image will download from 'kubesphere/nginx-ingress-controller:v0.48.1@sha256:e9fb216ace49dfa4a5983b183067e97496e7a8b307d2093f4278cd550c303899'。
in my environment ,  we want change then images from dockerhub to local register.
we edited and saved the yaml file in then portal , but open then configuration file again, then image field still write as "spec:
      containers:
        - name: controller
          image: >-
            kubesphere/nginx-ingress-controller:v0.48.1@sha256:e9fb216ace49dfa4a5983b183067e97496e7a8b307d2093f4278cd550c303899"

**Comment by RolandMa1986** [comment]
Hi @zhouwenblog,
This issue has been fixed by https://github.com/kubesphere/kubesphere/pull/4418.
You can replace those docker images in your private docker registry by the following steps:
```bash
docker pull kubespheredev/ks-controller-manager:release-3.2
docker pull pixiake/ks-installer:v3.2.0

docker tag  kubespheredev/ks-controller-manager:release-3.2 dockerhub.kubekey.local/kubesphere/ks-controller-manager:v3.2.0
docker tag  pixiake/ks-installer:v3.2.0 dockerhub.kubekey.local/kubesphere/ks-installer:v3.2.0

docker push dockerhub.kubekey.local/kubesphere/ks-controller-manager:v3.2.0
docker push dockerhub.kubekey.local/kubesphere/ks-installer:v3.2.0
``` 
After the image has been replaced, you can pull them on your master node and restart the ks-installer deployment.
