### ISSUE TITLE
3.1.1 Upgrade 3.2.0 Logs cannot be collected

### ISSUE THREAD

**Issue by tqtcloud** [kubesphere/kubesphere#4429]
System version: centos7.9
Kubernetes version: 1.20.6
Kubesphere version before upgrade: 3.1.1
Updated kubesphere version: 3.2.0

Monitoring alarm information: A Node-exporter alarm occurs CPUThrottlingHigh and the log component Fluent-bit. CPUThrottlingHigh occurs in all instances

Fluent-bit logs are as follows:
![image](https://user-images.githubusercontent.com/86145643/140857734-1ca9a570-6f38-40d3-8305-0a3e23dc0637.png)

Refer to the  ：https://github.com/kubesphere/kubesphere/issues/4425  Perform related configurations. 
Still no log collection，The alarm is cleared after the configuration

![image](https://user-images.githubusercontent.com/86145643/140858108-811f49e1-f68d-4015-93ef-f33713a23386.png)

Kubernetes is running properly, and the log collection component is running properly
![image](https://user-images.githubusercontent.com/86145643/140858193-a770f693-0b2f-424d-9cf0-f8426f7672bb.png)

What is the problem?

**Comment by wenchajun** [comment]
In this path CRD -> ClusterConfiguration->ks-installer Add ContainerRuntime: docker to the ks-installer file as follows
```
logging:
containerruntime: docker
enabled: true
logsidecar:
enabled: true
replicas: 2
````
Then let ks-Intaller perform the installation again

**Comment by tqtcloud** [comment]
Relevant configuration has been carried out. How can I ask him to reinstall it
![image](https://user-images.githubusercontent.com/86145643/140862293-b79df81f-e5d1-4a40-a2cb-c1117cecf49c.png)



> 在这个路径 CRD -> ClusterConfiguration->ks-installer 将 ContainerRuntime: docker 添加到 ks-installer 文件中，如下
> 
> ```
> logging:
> containerruntime: docker
> enabled: true
> logsidecar:
> enabled: true
> replicas: 2
> ```
> 
> 然后让 ks-Intaller 再次执行安装

**Comment by wenchajun** [comment]
You can execute kubectl rollout restart deploy -n kubesphere-system ks-installer to update image.

**Comment by tqtcloud** [comment]
replicas: 3
Is it the cause of the problem? After I made the above changes, the update was automatically triggered, but there was an error in the Fluent-bit log:

`[2021/11/09 05:39:01] [ warn] [engine] chunk '64-1636436331.43826494.flb' cannot be retried: task_id=18, input=tail.2 > output=es.0

 [2021/11/09 05:39:01] [error] [output:es:es.0] HTTP status=400 URI=/_bulk, response:

 {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;2: an id must be provided if version type or value are set;3: an id must be provided if version type or value are set;4: an id must be provided if version type or value are set;5: an id must be provided if version type or value are set;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;2: an id must be provided if version type or value are set;3: an id must be provided if version type or value are set;4: an id must be provided if version type or value are set;5: an id must be provided if version type or value are set;"},"status":400}

 

 [2021/11/09 05:39:01] [ warn] [engine] chunk '64-1636436326.709723087.flb' cannot be retried: task_id=3, input=tail.2 > output=es.0

 [2021/11/09 05:39:01] [error] [output:es:es.0] HTTP status=400 URI=/_bulk, response:

 {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;2: an id must be provided if version type or value are set;3: an id must be provided if version type or value are set;4: an id must be provided if version type or value are set;5: an id must be provided if version type or value are set;6: an id must be provided if version type or value are set;7: an id must be provided if version type or value are set;8: an id must be provided if version type or value are set;9: an id must be provided if version type or value are set;10: an id must be provided if version type or value are set;11: an id must be provided if version type or value are set;12: an id must be provided if version type or value are set;13: an id must be provided if version type or value are set;14: an id must be provided if version type or value are set;15: an id must be provided if version type or value are set;16: an id must be provided if version type or value are set;17: an id must be provided if version type or value are set;18: an id must be provided if version type or value are set;19: an id must be provided if version type or value are set;20: an id must be provided if version type or value are set;21: an id must be provided if version type or value are set;22: an id must be provided if version type or value are set;23: an id must be provided if version type or value are set;24: an id must be provided if version type or value are set;25: an id must be provided if version type or value are set;26: an id must be provided if version type or value are set;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;2: an id must be provided if version type or value are set;3: an id must be provided if version type or value are set;4: an id must be provided if version type or value are set;5: an id must be provided if version type or value are set;6: an id must be provided if version type or value are set;7: an id must be provided if version type or value are set;8: an id must be provided if version type or value are set;9: an id must be provided if version type or value are set;10: an id must be provided if version type or value are set;11: an id must be provided if version type or value are set;12: an id must be provided if version type or value are set;13: an id must be provided if version type or value are set;14: an id must be provided if version type or value are set;15: an id must be provided if version type or value are set;16: an id must be provided if version type or value are set;17: an id must be provided if version type or value are set;18: an id must be provided if version type or value are set;19: an id must be provided if version type or value are set;20: an id must be provided if version type or value are set;21: an id must be provided if version type or value are set;22: an id must be provided if version type or value are set;23: an id must be provided if version type or value are set;24: an id must be provided if version type or value are set;25: an id must be provided if version type or value are set;26: an id must be provided if version type or value are set;"},"status":400}

 

 [2021/11/09 05:39:01] [ warn] [engine] failed to flush chunk '64-1636436340.140600650.flb', retry in 10 seconds: task_id=16, input=tail.2 > output=es.0 (out_id=0)

 [2021/11/09 05:39:01] [error] [output:es:es.0] HTTP status=400 URI=/_bulk, response:

 {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;2: an id must be provided if version type or value are set;3: an id must be provided if version type or value are set;4: an id must be provided if version type or value are set;5: an id must be provided if version type or value are set;6: an id must be provided if version type or value are set;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;2: an id must be provided if version type or value are set;3: an id must be provided if version type or value are set;4: an id must be provided if version type or value are set;5: an id must be provided if version type or value are set;6: an id must be provided if version type or value are set;"},"status":400}

 

 [2021/11/09 05:39:01] [ warn] [engine] failed to flush chunk '64-1636436340.960191159.flb', retry in 10 seconds: task_id=17, input=tail.2 > output=es.0 (out_id=0)

 [2021/11/09 05:39:01] [error] [output:es:es.0] HTTP status=400 URI=/_bulk, response:

 {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;2: an id must be provided if version type or value are set;3: an id must be provided if version type or value are set;4: an id must be provided if version type or value are set;5: an id must be provided if version type or value are set;6: an id must be provided if version type or value are set;7: an id must be provided if version type or value are set;8: an id must be provided if version type or value are set;9: an id must be provided if version type or value are set;10: an id must be provided if version type or value are set;11: an id must be provided if version type or value are set;12: an id must be provided if version type or value are set;13: an id must be provided if version type or value are set;14: an id must be provided if version type or value are set;15: an id must be provided if version type or value are set;16: an id must be provided if version type or value are set;17: an id must be provided if version type or value are set;18: an id must be provided if version type or value are set;19: an id must be provided if version type or value are set;20: an id must be provided if version type or value are set;21: an id must be provided if version type or value are set;22: an id must be provided if version type or value are set;23: an id must be provided if version type or value are set;24: an id must be provided if version type or value are set;25: an id must be provided if version type or value are set;26: an id must be provided if version type or value are set;27: an id must be provided if version type or value are set;28: an id must be provided if version type or value are set;29: an id must be provided if version type or value are set;30: an id must be provided if version type or value are set;31: an id must be provided if version type or value are set;32: an id must be provided if version type or value are set;33: an id must be provided if version type or value are set;34: an id must be provided if version type or value are set;35: an id must be provided if version type or value are set;36: an id must be provided if version type or value are set;37: an id must be provided if version type or value are set;38: an id must be provided if version type or value are set;39: an id must be provided if version type or value are set;40: an id must be provided if version type or value are set;41: an id must be provided if version type or value are set;42: an id must be provided if version type or value are set;43: an id must be provided if version type or value are set;44: an id must be provided if version type or value are set;45: an id must be provided if version type or value are set;46: an id must be provided if version type or value are set;47: an id must be provided if version type or value are set;48: an id must be provided if version type or value are set;49: an id must be provided if version type or value are set;50: an id must be provided if version type or value are set;51: an id must be provided if version type or value are set;52: an id must be provided if version type or value are set;53: an id must be provided if version type or value are set;54: an id must be provided if version type or value are set;55: an id must be provided if version type or value are set;56: an id must be provided if version type or value are set;57: an id must be provided if version type or value are set;58: an id must be provided if version type or value are set;59: an id must be provided if version type or value are set;60: an id must be provided if version type or value are set;61: an id must be provided if version type or value are set;62: an id must be provided if version type or value are set;63: an id must be provided if version type or value are set;64: an id must be provided if version type or value are set;65: an id must be provided if version type or value are set;66: an id 

 [2021/11/09 05:39:01] [ warn] [engine] failed to flush chunk '64-1636436336.612524052.flb', retry in 8 seconds: task_id=0, input=tail.2 > output=es.0 (out_id=0)

 [2021/11/09 05:39:02] [error] [output:es:es.0] HTTP status=400 URI=/_bulk, response:

 {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;2: an id must be provided if version type or value are set;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;2: an id must be provided if version type or value are set;"},"status":400}

 `

**Comment by tqtcloud** [comment]
> 您可以执行`kubectl rollout restart deploy -n kubesphere-system ks-installer`更新图像。

replicas: 3
Is it the cause of the problem? After I made the above changes, the update was automatically triggered, but there was an error in the Fluent-bit log:

**Comment by tqtcloud** [comment]
> 您可以执行`kubectl rollout restart deploy -n kubesphere-system ks-installer`更新图像。

replicas: 3
Is it the cause of the problem? After I made the above changes, the update was automatically triggered, but there was an error in the Fluent-bit log:
![image](https://user-images.githubusercontent.com/86145643/140873190-b1c2bea6-c89f-4429-b856-d90298968558.png)

**Comment by wenchajun** [comment]
The reason for this is the missing the `generateID: true` field.You can refer to this
https://github.com/wenchajun/ks-installer/blob/master/roles/ks-logging/templates/custom-output-elasticsearch-logging.yaml.j2#L31
But I suggest you take the steps 
`kubectl edit cc -n kubesphere-system ks-installer`
Delete the red box and the information after it
![1636439212(1)](https://user-images.githubusercontent.com/39892300/140873376-e6377e42-c7a4-4e86-b1e1-5783769bd95d.jpg)
the `kubectl rollout restart deploy -n kubesphere-system ks-installer`

> In this path CRD -> ClusterConfiguration->ks-installer Add ContainerRuntime: docker to the ks-installer file as follows
> 
> ```
> logging:
> containerruntime: docker
> enabled: true
> logsidecar:
> enabled: true
> replicas: 2
> ```
> 
> Then let ks-Intaller perform the installation again
The reason for this is the missing the `generateID: true` field.You can refer to this
https://github.com/wenchajun/ks-installer/blob/master/roles/ks-logging/templates/custom-output-elasticsearch-logging.yaml.j2#L31
But I suggest you take the steps 
`kubectl edit cc -n kubesphere-system ks-installer`
Delete the red box and the information after it
![1636439212(1)](https://user-images.githubusercontent.com/39892300/140873376-e6377e42-c7a4-4e86-b1e1-5783769bd95d.jpg)
the `kubectl rollout restart deploy -n kubesphere-system ks-installer`

**Comment by tqtcloud** [comment]
> > In this path CRD -> ClusterConfiguration->ks-installer Add ContainerRuntime: docker to the ks-installer file as follows
> > ```
> > logging:
> > containerruntime: docker
> > enabled: true
> > logsidecar:
> > enabled: true
> > replicas: 2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then let ks-Intaller perform the installation again
> 
> The reason for this is the missing the `generateID: true` field.You can refer to this https://github.com/wenchajun/ks-installer/blob/master/roles/ks-logging/templates/custom-output-elasticsearch-logging.yaml.j2#L31 But I suggest you take the steps `kubectl edit cc -n kubesphere-system ks-installer` Delete the red box and the information after it ![1636439212(1)](https://user-images.githubusercontent.com/39892300/140873376-e6377e42-c7a4-4e86-b1e1-5783769bd95d.jpg) then `kubectl rollout restart deploy -n kubesphere-system ks-installer`

Is there a better way? GenerateID exists in the cluster.
![image](https://user-images.githubusercontent.com/86145643/140875203-0256dc8b-c1c6-433a-8ac6-21c1d7ea02c3.png)

**Comment by wenchajun** [comment]
You can keep the ClusterID and delete other fields in status.

**Comment by tqtcloud** [comment]
> You can keep the ClusterID and delete other fields in status.Alternatively, delete only the logging, Events, Fluentbit, and Auditing fields.then `kubectl rollout restart deploy -n kubesphere-system ks-installer`

Delete the components shown in the red box and check whether the log system can be rebuilt
![image](https://user-images.githubusercontent.com/86145643/140881709-8993ae4c-1247-48ce-8af3-4baa2261a3c5.png)

**Comment by wenchajun** [comment]
> > You can keep the ClusterID and delete other fields in status.Alternatively, delete only the logging, Events, Fluentbit, and Auditing fields.then `kubectl rollout restart deploy -n kubesphere-system ks-installer`
> 
> Delete the components shown in the red box and check whether the log system can be rebuilt ![image](https://user-images.githubusercontent.com/86145643/140881709-8993ae4c-1247-48ce-8af3-4baa2261a3c5.png)

yes

**Comment by tqtcloud** [comment]
> kubectl rollout restart deploy -n kubesphere-system ks-installer



> > > You can keep the ClusterID and delete other fields in status.Alternatively, delete only the logging, Events, Fluentbit, and Auditing fields.then `kubectl rollout restart deploy -n kubesphere-system ks-installer`
> > 
> > 
> > Delete the components shown in the red box and check whether the log system can be rebuilt ![image](https://user-images.githubusercontent.com/86145643/140881709-8993ae4c-1247-48ce-8af3-4baa2261a3c5.png)
> 
> yes

To delete related configurations, restart ks-install and the cluster does not change

**Comment by wenchajun** [comment]
It will take a while for the ks-installer to reinstall. If you add `containerruntime: docker` field, it should collect logs after a while.

**Comment by tqtcloud** [comment]
> 重新安装 ks-installer 需要一段时间。如果添加`containerruntime: docker`字段，它应该会在一段时间后收集日志。

It has been a while, and there is no response at present. I have redeployed ES, Fluent-bit, and the current fluent-bit log is:
![image](https://user-images.githubusercontent.com/86145643/140889289-75478c63-bb83-4961-ba8c-aca4f3603dda.png)

**Comment by wenchajun** [comment]
The error message is that the `generateID: true` field was not added. 
CRD->Output->es es-auditing es-events Add the following fields
```
 es:
    generateID: true//add ths
    host: elasticsearch-logging-data.kubesphere-logging-system.svc
    logstashFormat: true
    logstashPrefix: ks-logstash-auditing
```
it will work soon

**Comment by tqtcloud** [comment]
> 错误消息是该`generateID: true`字段未添加。 CRD->Output->es es-auditing es-events 添加如下字段
> 
> ```
>  es:
>     generateID: true//add ths
>     host: elasticsearch-logging-data.kubesphere-logging-system.svc
>     logstashFormat: true
>     logstashPrefix: ks-logstash-auditing
> ```
> 
> 它很快就会起作用




> The error message is that the `generateID: true` field was not added. CRD->Output->es es-auditing es-events Add the following fields
> 
> ```
>  es:
>     generateID: true//add this
>     host: elasticsearch-logging-data.kubesphere-logging-system.svc
>     logstashFormat: true
>     logstashPrefix: ks-logstash-auditing
> ```
> 
> it will work soon

I have modified it, it should be effective, but there are new problems
![image](https://user-images.githubusercontent.com/86145643/140894238-00052474-bc35-4df0-829a-f6e46cd3363e.png)

**Comment by wenchajun** [comment]
Well, in order to save time and effort, can you bring up your configuration file（about Input and Output）

**Comment by tqtcloud** [comment]
> 那么，为了省时省力，能不能调出你的配置文件（关于Input and Output）
You look under the

![image](https://user-images.githubusercontent.com/86145643/140895941-96b9b3b3-0884-45be-91ef-47ffeb704f8a.png)
![image](https://user-images.githubusercontent.com/86145643/140895985-37c1b686-012b-408a-b345-f8e57aadc447.png)
![image](https://user-images.githubusercontent.com/86145643/140896023-95880bc1-5ed9-4e0c-af41-eb8c92969c04.png)

**Comment by wenchajun** [comment]
According to the error message, the parse format is not correct, so could you please provide us with your environment.

**Comment by tqtcloud** [comment]
> According to the error message, the parse format is not correct, so could you please provide us with your container runtime.

docker 
![image](https://user-images.githubusercontent.com/86145643/140902550-69b578d9-5932-4f42-9cbf-90e4751bf8fd.png)

**Comment by wenchajun** [comment]
> > 那么，为了省时省力，能不能调出你的配置文件（关于Input and Output）
> > You look under the
> 
> ![image](https://user-images.githubusercontent.com/86145643/140895941-96b9b3b3-0884-45be-91ef-47ffeb704f8a.png) ![image](https://user-images.githubusercontent.com/86145643/140895985-37c1b686-012b-408a-b345-f8e57aadc447.png) ![image](https://user-images.githubusercontent.com/86145643/140896023-95880bc1-5ed9-4e0c-af41-eb8c92969c04.png)

Did you find it? Your first diagram has the same logstashPrefix field as the second diagram.The right thing to do is this
![5~7YXWEU(`F )_IBYM5W`8J](https://user-images.githubusercontent.com/39892300/140904924-edf4b3df-7b65-472a-b374-dce3f4c8989f.png)
