### ISSUE TITLE
pod belong to deployment

### ISSUE THREAD

**Issue by showjason** [kubesphere/kubesphere#4430]
Recently, I installed kubesphere in my own kubernetes cluster,  deployed two deployments, each of them was setted one replica, they are different names, but the same selector and same template.Two pods was created,  as kubernetes,  these two pods should belong to different deployments, but as you can see as below screenshot, these two pods are belonging to the same deployment.  I think the comparison between the name of pod  and name of rs or deployment shoud be taken into consideration, not only the selector and hash value of template.
![image](https://user-images.githubusercontent.com/27723125/140883499-91db1efc-9118-4c6a-a1b6-81b07c53c4a6.png)

**Versions Used**
KubeSphere: v3.1.1
Kubernetes: v1.21.2

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.9 / 1 masters:  4cpu/16g; 2 nodes: 8cpu/32g
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. Deploy two deployments that they are different names, but the same selector and same template

**Comment by hzliangbin** [comment]
@RolandMa1986 hi, I reproduce the bug as follows:
![kubesphere1](https://user-images.githubusercontent.com/9740458/144702926-dd0ed24a-8951-4f3d-9c0a-80049894cc62.png)

but I think it should be fix in frontend. the request from web ui as:
`https://abc.cloud.cn/kapis/clusters/10-16-10-125/resources.kubesphere.io/v1alpha3/namespaces/hello/pods?limit=10&ownerKind=ReplicaSet&labelSelector=app%3Dnginx&sortBy=startTime`

`kubectl get` return the same:
![ks2](https://user-images.githubusercontent.com/9740458/144703039-1c7973b6-bd93-4e18-ab05-0b14c2f76a85.png)

since the `resource handler` deals with different  kinds of resouces including pod. So may be the bug should be fix in frontend aspects. May I have your opinion? thx

**Comment by chaunceyjiang** [comment]
For some API types, such as ReplicaSets, the label selectors of two instances must not overlap within a namespace, or the controller can see that as conflicting instructions and fail to determine how many replicas should be present.


Reference
https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

**Comment by hzliangbin** [comment]
@chaunceyjiang you are right. Theoretically such case should not occured if we use kubesphere to manage all resources because kubesphere will add different lables to the resource. But users may create some deploys in their console or  command line so  we  may come to  such  a result.

**Comment by showjason** [comment]
@hzliangbin I agree with you that this bug is fixed by kubesphere console. However, as you said  if users create deploys by CLI, this case will happen. I also installed the kuberentes dashboard, I found this case did not occur in kubernetes dashboard, so I think this case could be avoided. Maybe add name of deploy to constraints, do you have some other solutions?

**Comment by showjason** [comment]
@RolandMa1986 I read the source code and find that the function named "podBelongToDeployment" is defined and logic is correct. [https://github.com/kubesphere/kubesphere/blob/master/pkg/models/resources/v1alpha2/pod/pods.go](url)
Maybe the filters in request URL is not correct, please look at below screenshot:

![image](https://user-images.githubusercontent.com/27723125/145528077-dffd9284-8085-4647-9aef-dab6afd4e922.png)

You can see that one of the filters is "ownerKind=ReplicaSet"  not "ownerKind=Deployment", I try to change value of "ownerKind" from "ReplicaSet" to "Deployment" , but get empty items , maybe KS API is not support this parmeter.

**Comment by RolandMa1986** [comment]
@showjason
For the backend, we do support query pod by owner. but when using the `ownerKind ` filter,  the `OwnerName `is also needed. 
For the frontend, I guess this component is shared by all kinds of work, such as Deployment, Statstufuset. So currently only the labels filter works.
It should be a front-end issue.

**Comment by hzliangbin** [comment]
@RolandMa1986  I'd like to take it and make a pr to kubesphere-console
