### ISSUE TITLE
[Enhance] Support importing Grafana templates to the workspace level.

### ISSUE THREAD

**Issue by zhu733756** [kubesphere/kubesphere#4433]
Support importing Grafana templates to the workspace level. Currently, this function only can be accessed by the cluster lever. 

# Solution

See https://github.com/kubesphere/kubesphere/blob/511d0d02fffc766c0ee218dab15d399888681672/pkg/kapis/monitoring/v1alpha3/handler.go#L404 for detail. Maybe we need to add a namespace parameter as an optional to determine to convert it to Dashboard struct or not.

Related pr https://github.com/kubesphere/kubesphere/pull/4194.

/good-first-issue 
/area observability
/kind feature-request
/assign @zhu733756

**Comment by ZY123454321YZ** [comment]
If you solve this issue, do you have any other problems? @zhu733756
