### ISSUE TITLE
kubesphere的项目概览里应该加上密钥和配置的数量

### ISSUE THREAD

**Issue by blueftss** [kubesphere/kubesphere#444]
kubesphere的项目概览里应该加上密钥和配置的数量，这样客户对所有的资源可以一目了然！
![image](https://user-images.githubusercontent.com/11399484/57999081-ab91f380-7b06-11e9-9038-4ebe386495b9.png)

**Comment by Fengwei1991** [comment]
已在新的版本中做了设计修改，这是一个很好的建议~
