### ISSUE TITLE
go mod vendor err:

### ISSUE THREAD

**Issue by cherry-hyx** [kubesphere/kubesphere#4440]
**Describe the Bug**
~~~
PS > go mod vendor
go: downloading github.com/go-resty/resty/v2 v2.5.0
verifying github.com/go-resty/resty/v2@v2.5.0: checksum mismatch
        downloaded: h1:GmCjQ7qW3Dzr3Lh7FvTrRJSWgYNWswDdOy+T8sgTAFI=
        go.sum:     h1:WFb5bD49/85PO7WgAjZ+/TJQ+Ty1XOcWEfD1zIFCM1c=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
~~~
For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: release-3.2
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:
windows 10 /

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by RolandMa1986** [comment]
@cherry-hyx, 
You should use the `hack/pin-dependency.sh` to pin dependence or update vendor, do not use the `go mod` command directly. Please go to our slack or forum for developing issues or discussions.
/kind support

**Comment by cherry-hyx** [comment]
> @cherry-hyx, You should use the `hack/pin-dependency.sh` to pin dependence or update vendor, do not use the `go mod` command directly. Please go to our slack or forum for developing issues or discussions. /kind support

tks

**Comment by cherry-hyx** [comment]
> @cherry-hyx, You should use the `hack/pin-dependency.sh` to pin dependence or update vendor, do not use the `go mod` command directly. Please go to our slack or forum for developing issues or discussions. /kind support

tks,i try!

**Comment by RolandMa1986** [comment]
Ok, I will close the issue first. Please feel free to contact us.
