### ISSUE TITLE
Can't access terminal on pods

### ISSUE THREAD

**Issue by omarpipos** [kubesphere/kubesphere#4444]
I installed Kubesphere v3.2 in an existing Kubernetes Cluster (v1.21), everything works ok but when I try to open a container's terminal it hangs with a white screen:

![image](https://user-images.githubusercontent.com/19807564/141607488-de18fe20-52ef-4444-9bc3-404c44217201.png)

I tried with several browsers with the same result.

**Comment by RolandMa1986** [comment]
/kind support
/area console
Please make sure the WebSocket proxy has been configured on your proxy server. 
refer: https://kubesphere.com.cn/forum/d/2709-nginxks-console

**Comment by zryfish** [comment]
> /kind support /area console Please make sure the WebSocket proxy has been configured on your proxy server. refer: https://kubesphere.com.cn/forum/d/2709-nginxks-console

Maybe we should display this tip message when the terminal failed to start, this is really a FAQ.

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-nightly20220524`
![image](https://user-images.githubusercontent.com/68640256/170228833-443afd15-8a8a-458c-ad5b-7ed6abbfe55c.png)
