### ISSUE TITLE
menu.sh: file not found

### ISSUE THREAD

**Issue by zzxwill** [kubesphere/kubesphere#445]
In Step 3 of [installation guide](https://kubesphere.io/install), I hit the issue
```
[root@iZ2ze096fvcdcq2k761gn9Z scripts]# sh install.sh
install.sh: line 40: .: menu.sh: file not found
```

I will try to download a express edition to have another try.

**Comment by zzxwill** [comment]
This issue recurred in `kubesphere-all-express-1.0.0-alpha.tar.gz`.

**Comment by zzxwill** [comment]
It worked by executing `./install.sh`. I think it would be better to also make it work for `sh install.sh`.

**Comment by rayzhou2017** [comment]
@pixiake Please check this requirement.

**Comment by zzxwill** [comment]
Fixed?
