### ISSUE TITLE
ks from 3.1.1 upgrade to 3.2 custom monitor page error

### ISSUE THREAD

**Issue by gzdreamfly** [kubesphere/kubesphere#4450]
no matches for kind "ClusterDashboard" in version "monitoring.kubesphere.io/v1alpha2"

**Comment by gzdreamfly** [comment]
![image](https://user-images.githubusercontent.com/13009409/141951760-932bad64-0040-4e6c-a2b6-4715f5beecaa.png)

**Comment by RolandMa1986** [comment]
/area monitoring
/triage needs-information
@kubesphere/sig-observability

**Comment by zhu733756** [comment]
Duplicated issue https://github.com/kubesphere/kubesphere/issues/4245
