### ISSUE TITLE
"Total Requests" is always zero in cluster gateway dashboard

### ISSUE THREAD

**Issue by webup** [kubesphere/kubesphere#4451]
**Describe the Bug**
With cluster gateway enabled and some ingress routes set up, we made some testing requests and confirmed the routes are working.
However, when checking the cluster gateway dashboard (as below figure indicates), it's so weird that the total requests number is always zero, while it's quite clear that we do have some connections from time to time.

So my question is whether it's kinda normal behavior, if so, how to make the total requests get some counts? 

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/2936504/141968730-fb3bcf73-6e1f-40af-9bbb-ab7b442c2be9.png)

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)
3.2.0

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by zryfish** [comment]
Try a different time range, the default is last 10 minutes.

**Comment by webup** [comment]
> Try a different time range, the default is last 10 minutes.

Ok, here we go~

![image](https://user-images.githubusercontent.com/2936504/141988121-247f62a5-b2b4-4cbb-bdac-476f5ac2caf7.png)

**Comment by RolandMa1986** [comment]
It seems like a bug. the Global gateway didn't show any metric at all.
/kind bug
/area monitoring

**Comment by zryfish** [comment]
No metrics for the cluster gateway, but the project gateway does have the metrics, right?

**Comment by webup** [comment]
> No metrics for the cluster gateway, but the project gateway does have the metrics, right?

Not yet tried, with cluster gateway enabled, project gateway is not available to create, is that a designed feature?

**Comment by zryfish** [comment]
That's expected, enabling both cluster and project gateways will confuse users.

**Comment by webup** [comment]
> No metrics for the cluster gateway, but the project gateway does have the metrics, right?

Now, here is the project gateway, looks pretty good~
![image](https://user-images.githubusercontent.com/2936504/142132318-aa050e46-9350-432d-82c1-3126f788d965.png)

**Comment by webup** [comment]
> No metrics for the cluster gateway, but the project gateway does have the metrics, right?

So are we going to enable metrics for the cluster gateway, what' our plan? :)
