### ISSUE TITLE
Alarm message monitoring target link error

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4453]
**Describe the Bug**
1. Create an alarm policy, the alarm rules are: container_cpu_usage_seconds_total{container="container-xnkum2",namespace="test",pod="nginx-84b94f84f4-fkcjp"} > 0
2. After the alarm is triggered, check the alarm message and show that the monitoring target is the node,
3. Click on the node name，404 error on the page
![image](https://user-images.githubusercontent.com/88183150/142144306-87232928-4f79-42c5-babc-a20b892c5d66.png)

![image](https://user-images.githubusercontent.com/88183150/142144391-081e7876-db00-4d26-849b-aada529f7851.png)

![image](https://user-images.githubusercontent.com/88183150/142144526-90f57f8a-3aef-4102-a390-d84b877af126.png)

**Versions Used**
KubeSphere: nightly-20211116

/kind bug
/@kubesphere/sig-kubesphere
/priority medium

**Comment by zryfish** [comment]
Is this issue still valid after v3.2.1 release?

**Comment by jioce** [comment]
issue is not fixed

**Comment by jioce** [comment]
issue is still exist
![image](https://user-images.githubusercontent.com/88183150/174521318-51b6ef24-0061-4698-9f02-845af233c1c1.png)

![image](https://user-images.githubusercontent.com/88183150/174521185-63d0b7a3-eec4-4a61-a10d-8516c7a308b2.png)

version used 
kubesphere：v3.3.0-rc.2
