### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by xwb-spec** [kubesphere/kubesphere#4456]
![image](https://user-images.githubusercontent.com/13009409/142345162-db8a288f-3897-4f6c-83f2-31764fed4efd.png)

After upgrading from 3.1.1 to 3.2, a certificate error occurred when adding private warehouse verification, and the public network certificate 3.1.1 version I used had no problem

**Comment by gzdreamfly** [comment]
I use the domain name of the public network. How do I solve it? The CA certificate has been added to docker

**Comment by FeynmanZhou** [comment]
Hi team @kubesphere/sig-console @kubesphere/sig-testing ,

Could you please take a look at this issue? I assume we have tested adding private image registry like Harbor to KubeSphere console in v3.2.0.

**Comment by gzdreamfly** [comment]
E1126 15:38:29.388412       1 handler.go:226] Get "https://dev-harbor.whitewolvesx.com/v2/": x509: certificate signed by unknown authority
E1126 15:38:29.388433       1 utils.go:76] /workspace/pkg/kapis/resources/v1alpha3/handler.go:227 Get "https://dev-harbor.whitewolvesx.com/v2/": x509: certificate signed by unknown authority

**Comment by FeynmanZhou** [comment]
Hi @gzdreamfly , it looks like your certificate of HTTPS registry is signed by unknown authority. From my experience, please try to connect and use the HTTP registry, or resign your certificate from a public Certification Authority.

**Comment by holdlg** [comment]
if docker login <harbor_ip>  success。
"x509: certificate signed by unknown authority" errors can be ignored temporarily.
You can ignore the certificate error temporarily on the app creation page.

refer: https://kubesphere.com.cn/forum/d/5930-kubesphere-32-harborbug31/3
