### ISSUE TITLE
二次开发需求

### ISSUE THREAD

**Issue by bqsky** [kubesphere/kubesphere#446]
为啥现在前端不开源呢，后端开源了部分，架构的文档也没有，360公司的Wayne都全部开源了，并且都迭代了那么多版本。但是感觉你们这边做的更符合企业的需求，想用但是文档太少，都是些介绍和部署文档，纠结ing。

**Comment by rayzhou2017** [comment]
前端开源还在整理，肯定会开源的，现在是在忙功能的开发，很多客户等着用。后端是全部开源的，API文档很快也会有的，你发现哪个部分没有开源？

**Comment by rayzhou2017** [comment]
另外你们有什么需求可以提，我们会根据用户的需求安排以后的开发计划，尽量让用户能直接使用。

**Comment by bqsky** [comment]
恩，后端是全部都开源了。我们先熟悉后端架构，前端这块希望能赶上进度，文档能尽快放出来。非常感谢

**Comment by zryfish** [comment]
https://kubesphere.io/docs/advanced-v2.0/zh-CN/api-reference/api-docs/ API 文档已经整理好上线了
