### ISSUE TITLE
Enabling multicluster fails with Error: UPGRADE FAILED: \"kubefed\" has no deployed releases" 

### ISSUE THREAD

**Issue by abhiniveshjain** [kubesphere/kubesphere#4461]
**What's your question**
I am getting below error while doing all in one installation on EC2 instance and then enabling multicluster feature.

**Environment: OS & Hardware Information**

EC2- t3.small Ubuntu 18.04

> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).

**Error logs or message (Attach logs or screenshot)**

Below is the error message that I am getting. I was able to launch kubesphere console without any issues however while enabling multicluster feature and I am getting below error.

Waiting for all tasks to be completed ...
task network status is successful (1/4)
task openpitrix status is successful (2/4)
task monitoring status is successful (3/4)

task multicluster status is failed (4/4)
**************************************************
Collecting installation results ...
Task 'multicluster' failed:
******************************************************************************************************************************************************
{
"counter": 48,
"created": "2021-11-19T13:54:30.658297",
"end_line": 47,
"event": "runner_on_failed",
"event_data": {
"duration": 2554.753815,
"end": "2021-11-19T13:54:30.658164",
"event_loop": null,
"host": "localhost",
"ignore_errors": null,
"play": "localhost",
"play_pattern": "localhost",
"play_uuid": "dee69a99-f600-dc3e-1490-000000000005",
"playbook": "/kubesphere/playbooks/multicluster.yaml",
"playbook_uuid": "893dd7de-6552-4cb6-aa54-83b63e7a4d1a",
"remote_addr": "127.0.0.1",
"res": {
"_ansible_no_log": false,
"attempts": 10,
"changed": true,
"cmd": "/usr/local/bin/helm upgrade --install kubefed /kubesphere/kubesphere/kubefed/kubefed -f /kubesphere/kubesphere/kubefed/custom-values-kubefed.yaml --namespace kube-federation-system --wait --timeout 1800s\n",
"delta": "0:00:02.307510",
"end": "2021-11-19 13:54:30.627538",
"invocation": {
"module_args": {
"_raw_params": "/usr/local/bin/helm upgrade --install kubefed /kubesphere/kubesphere/kubefed/kubefed -f /kubesphere/kubesphere/kubefed/custom-values-kubefed.yaml --namespace kube-federation-system --wait --timeout 1800s\n",
"_uses_shell": true,
"argv": null,
"chdir": null,
"creates": null,
"executable": null,
"removes": null,
"stdin": null,
"stdin_add_newline": true,
"strip_empty_ends": true,
"warn": true
}
},
"msg": "non-zero return code",
"rc": 1,
"start": "2021-11-19 13:54:28.320028",
"stderr": "Error: UPGRADE FAILED: \"kubefed\" has no deployed releases",
"stderr_lines": [
"Error: UPGRADE FAILED: \"kubefed\" has no deployed releases"
],
"stdout": "",
"stdout_lines": []
},
"role": "ks-multicluster",
"start": "2021-11-19T13:11:55.904349",
"task": "Kubefed | Initing kube-federation-system",
"task_action": "command",
"task_args": "",
"task_path": "/kubesphere/installer/roles/ks-multicluster/tasks/main.yml:36",
"task_uuid": "dee69a99-f600-dc3e-1490-00000000001c",
"uuid": "a4b9b0ba-35a4-4c1c-baca-5f8dec3f842c"
},
"parent_uuid": "dee69a99-f600-dc3e-1490-00000000001c",
"pid": 8380,
"runner_ident": "multicluster",
"start_line": 46,
"stdout": "fatal: [localhost]: FAILED! => {\"attempts\": 10, \"changed\": true, \"cmd\": \"/usr/local/bin/helm upgrade --install kubefed /kubesphere/kubesphere/kubefed/kubefed -f /kubesphere/kubesphere/kubefed/custom-values-kubefed.yaml --namespace kube-federation-system --wait --timeout 1800s\\n\", \"delta\": \"0:00:02.307510\", \"end\": \"2021-11-19 13:54:30.627538\", \"msg\": \"non-zero return code\", \"rc\": 1, \"start\": \"2021-11-19 13:54:28.320028\", \"stderr\": \"Error: UPGRADE FAILED: \\\"kubefed\\\" has no deployed releases\", \"stderr_lines\": [\"Error: UPGRADE FAILED: \\\"kubefed\\\" has no deployed releases\"], \"stdout\": \"\", \"stdout_lines\": []}",
"uuid": "a4b9b0ba-35a4-4c1c-baca-5f8dec3f842c"
}

**Installer Version**

v3.2.0

> e.g. v2.1.0, v2.1.1, v3.0.0

**Comment by FeynmanZhou** [comment]
Hi @kubesphere/sig-multicluster, please help to take a look at this issue, thanks.

**Comment by iawia002** [comment]
Hi @abhiniveshjain How did you install the KubeSphere, are you using the [kubekey](https://github.com/kubesphere/kubekey) tool?

**Comment by iawia002** [comment]
This is weird, I have also used the kubekey to install and upgrade several times, but I haven’t encountered this problem.

/cc @kubesphere/sig-installation

**Comment by yuswift** [comment]
@abhiniveshjain Please try to exec `usr/local/bin/helm upgrade --install kubefed /kubesphere/kubesphere/kubefed/kubefed -f /kubesphere/kubesphere/kubefed/custom-values-kubefed.yaml --namespace kube-federation-system --wait --timeout 1800s` in the ks-installer container.

**Comment by abhiniveshjain** [comment]
Yes @iawia002, I am using kubekey tool

**Comment by abhiniveshjain** [comment]
> @abhiniveshjain Please try to exec `usr/local/bin/helm upgrade --install kubefed /kubesphere/kubesphere/kubefed/kubefed -f /kubesphere/kubesphere/kubefed/custom-values-kubefed.yaml --namespace kube-federation-system --wait --timeout 1800s` in the ks-installer container.

I ran this and still getting same error.

**Comment by abhiniveshjain** [comment]
kubectl -n kubesphere-system patch configmap kubesphere-config --type=merge -p '{"metadata":{"labels":{"STATUS":"DEPLOYED"}}}' also didn't help

**Comment by abhiniveshjain** [comment]
> 

Have you ever tried on EC2 instance with current versions like v3.2.0 and k8s v1.21?

**Comment by pixiake** [comment]
> > @abhiniveshjain Please try to exec `usr/local/bin/helm upgrade --install kubefed /kubesphere/kubesphere/kubefed/kubefed -f /kubesphere/kubesphere/kubefed/custom-values-kubefed.yaml --namespace kube-federation-system --wait --timeout 1800s` in the ks-installer container.
> 
> I ran this and still getting same error.


I think you can try adding `--debug` to see more information.

`/usr/local/bin/helm upgrade --install kubefed /kubesphere/kubesphere/kubefed/kubefed -f /kubesphere/kubesphere/kubefed/custom-values-kubefed.yaml --namespace kube-federation-system --wait --timeout 1800s --debug`

**Comment by 2hangchen** [comment]
May I ask whether this problem has been solved? I have also encountered this problem.  
@abhiniveshjain

**Comment by 2hangchen** [comment]
> May I ask whether this problem has been solved? I have also encountered this problem. @abhiniveshjain

I solved this problem by installing `Kubefed`  offline.
