### ISSUE TITLE
Error on Traffic Monitoring and Tracing

### ISSUE THREAD

**Issue by YuriBucci2** [kubesphere/kubesphere#4464]
**Describe the Bug**
Traffic Monitoring and Tracing not working

**Versions Used**
KubeSphere: 3.2.0
Kubernetes: 1.21.5

**Environment**
How many nodes and their hardware configuration:

RHEL 8.5
1 master:  8cpu/24g
3 nodes: 8cpu/32g

Installed Kubernetes with latest KubeSpray branch master (22/11/2021)

**How To Reproduce**
1. Create Cluster Gateway or Project Gateway
2. Deploy Bookinfo Sample App
3. watch -n 0.5 'curl "http://productpage.k8sd09ds.X.X.X.X.nip.io/productpage?u=normal"'
4. I can't see any Traffic Monitoring
5. I can't see any tracing
6. I can't see any Requests in gateway

![image](https://user-images.githubusercontent.com/52977138/142937132-30e3a37b-b333-479d-95b7-55730b27a682.png)
![image](https://user-images.githubusercontent.com/52977138/142937165-1e358611-205d-4eee-9057-fdbdd775a13a.png)
![image](https://user-images.githubusercontent.com/52977138/142937759-010f6c18-30e6-489f-8c7d-3de29cd75639.png)

**Errors in pod Kiali**
![image](https://user-images.githubusercontent.com/52977138/142937503-bfad6fcd-b1c3-4624-bbfc-9922b8cdf647.png)

**Expected behavior**
Correction

**Comment by xyz-li** [comment]
This issue may be related to #4465 because the network does not work correctly.
