### ISSUE TITLE
Istio-init error

### ISSUE THREAD

**Issue by YuriBucci2** [kubesphere/kubesphere#4465]
**Describe the Bug**
I got error in istio-init container

**Versions Used**
KubeSphere: 3.2.0
Kubernetes: 1.21.5

**Environment**
How many nodes and their hardware configuration:

RHEL 8.5
1 master: 8cpu/24g
3 nodes: 8cpu/32g

Installed Kubernetes with latest KubeSpray branch master (22/11/2021)

Used calico iptables NFT not legacy

**How To Reproduce**
1. Create application with Application Governance

```
2021-11-22T20:48:48.022912Z	info	Istio iptables environment:
ENVOY_PORT=
INBOUND_CAPTURE_PORT=
ISTIO_INBOUND_INTERCEPTION_MODE=
ISTIO_INBOUND_TPROXY_ROUTE_TABLE=
ISTIO_INBOUND_PORTS=
ISTIO_OUTBOUND_PORTS=
ISTIO_LOCAL_EXCLUDE_PORTS=
ISTIO_SERVICE_CIDR=
ISTIO_SERVICE_EXCLUDE_CIDR=
ISTIO_META_DNS_CAPTURE=
2021-11-22T20:48:48.022956Z	info	Istio iptables variables:
PROXY_PORT=15001
PROXY_INBOUND_CAPTURE_PORT=15006
PROXY_TUNNEL_PORT=15008
PROXY_UID=1337
PROXY_GID=1337
INBOUND_INTERCEPTION_MODE=REDIRECT
INBOUND_TPROXY_MARK=1337
INBOUND_TPROXY_ROUTE_TABLE=133
INBOUND_PORTS_INCLUDE=*
INBOUND_PORTS_EXCLUDE=15090,15021,15020
OUTBOUND_IP_RANGES_INCLUDE=*
OUTBOUND_IP_RANGES_EXCLUDE=
OUTBOUND_PORTS_INCLUDE=
OUTBOUND_PORTS_EXCLUDE=
KUBEVIRT_INTERFACES=
ENABLE_INBOUND_IPV6=false
DNS_CAPTURE=false
CAPTURE_ALL_DNS=false
DNS_SERVERS=[],[]
OUTPUT_PATH=
NETWORK_NAMESPACE=
CNI_MODE=false
2021-11-22T20:48:48.023184Z	info	Writing following contents to rules file: /tmp/iptables-rules-1637614128023020808.txt719688497
* nat
-N ISTIO_INBOUND
-N ISTIO_REDIRECT
-N ISTIO_IN_REDIRECT
-N ISTIO_OUTPUT
-A ISTIO_INBOUND -p tcp --dport 15008 -j RETURN
-A ISTIO_REDIRECT -p tcp -j REDIRECT --to-ports 15001
-A ISTIO_IN_REDIRECT -p tcp -j REDIRECT --to-ports 15006
-A PREROUTING -p tcp -j ISTIO_INBOUND
-A ISTIO_INBOUND -p tcp --dport 22 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15090 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15021 -j RETURN
-A ISTIO_INBOUND -p tcp --dport 15020 -j RETURN
-A ISTIO_INBOUND -p tcp -j ISTIO_IN_REDIRECT
-A OUTPUT -p tcp -j ISTIO_OUTPUT
-A ISTIO_OUTPUT -o lo -s 127.0.0.6/32 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --uid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --uid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -o lo ! -d 127.0.0.1/32 -m owner --gid-owner 1337 -j ISTIO_IN_REDIRECT
-A ISTIO_OUTPUT -o lo -m owner ! --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -m owner --gid-owner 1337 -j RETURN
-A ISTIO_OUTPUT -d 127.0.0.1/32 -j RETURN
-A ISTIO_OUTPUT -j ISTIO_REDIRECT
COMMIT
2021-11-22T20:48:48.023211Z	info	Running command: iptables-restore --noflush /tmp/iptables-rules-1637614128023020808.txt719688497
2021-11-22T20:48:48.025622Z	error	Command error output: iptables-restore v1.8.4 (legacy): iptables-restore: unable to initialize table 'nat'

Error occurred at line: 1
Try `iptables-restore -h' or 'iptables-restore --help' for more information.

2021-11-22T20:48:48.025762Z	info	Writing following contents to rules file: /tmp/ip6tables-rules-1637614128025701269.txt116074716

2021-11-22T20:48:48.025782Z	info	Running command: ip6tables-restore --noflush /tmp/ip6tables-rules-1637614128025701269.txt116074716
2021-11-22T20:48:48.028589Z	info	Running command: iptables-save 
```

**Expected behavior**
No errors

**Comment by xyz-li** [comment]
What is the version of iptables on the host?

**Comment by YuriBucci2** [comment]
1.8.6 nf_tables

I think that is related issue, because with Istio operator  come with Kubespray don't have support for nftables of RHEL 8x 

https://github.com/Maistra/istio/issues/32

That's correctly?

**Comment by xyz-li** [comment]
> 1.8.6 nf_tables
> 
> I think that is related issue, because with Istio operator come with Kubespray don't have support for nftables of RHEL 8x
> 
> [maistra/istio#32](https://github.com/maistra/istio/issues/32)
> 
> That's correctly?

I think this is the root cause. Is it possible to change the os to Ubuntu/Centos?

**Comment by YuriBucci2** [comment]
> > 1.8.6 nf_tables
> > 
> > I think that is related issue, because with Istio operator come with Kubespray don't have support for nftables of RHEL 8x
> > 
> > [maistra/istio#32](https://github.com/maistra/istio/issues/32)
> > 
> > That's correctly?
> 
> I think this is the root cause. Is it possible to change the os to Ubuntu/Centos?

Unfortunately not, for security compliance reasons, we can only use RHEL in its latest version.

 I would like to know if there are any plans to update KubeSphere/Istio to support Centos8/RHEL8

**Comment by RolandMa1986** [comment]
@YuriBucci2 Thanks for your feedback. We checked this issue with the Istio community. This issue could be resolved by [enabling the Istio CNI feature](https://istio.io/latest/docs/setup/additional-setup/cni/). We tried on RHEL 8 with Calico, It works well as far as now.

In the ks-installer(which use to install the components), we provided a pre-configured Istio profile which suitable for most users. However, it didn't cover the case now.  I think we need to add some external configuration items in the ClusterConfiguraion, which allows users to customize the Istio profile.

Currently, you can configure Istio manually to fix this issue. The steps as bellow.

1. Enter ks-installer pod's terminal by : `kubectl -n kubesphere-system exec -it ks-installer-<tab> bash`
2. Edit the Istio profile to enable the CNIfeature.  The file is located in `/kubesphere/kubesphere/servicemesh/istio/istio-profile.yaml`
3. Reinstall Istio with: 

```
$ /kubesphere/kubesphere/servicemesh/istio/istio-1.11.2/bin/istioctl install -f /kubesphere/kubesphere/servicemesh/istio/istio-profile.yaml --set revision=1-11-2 -y
$ kubectl patch mutatingwebhookconfigurations istio-sidecar-injector-1-11-2 --type='json' -p='[{ "op": "remove", "path": "/webhooks/1/objectSelector/matchExpressions/1" }]'
```
Please let's know whether this solution works for you.
