### ISSUE TITLE
ES index can not auto create

### ISSUE THREAD

**Issue by chj9** [kubesphere/kubesphere#4467]
Describe the Bug

ES index can not auto create

Versions Used
KubeSphere: 3.2.0
Kubernetes: 1.21.6
ES Version：7.12.1

Environment
How many nodes and their hardware configuration:
CentOS 7.9 / 3 masters: 8cpu/32g; 3 nodes: 16cpu64g

How To Reproduce
1. Edit Input In `excludePath` add a path
2. my app log use filebeat collect，k8s and kubesphere and related components use fluent-bit
3. The fluent-bit  log is normal,  but the ES index cannot be created automatically，still the same the next day

**Comment by xyz-li** [comment]
This issue may be related to #4465 because the network does not work correctly.

**Comment by wenchajun** [comment]
Is it the same as this https://github.com/kubesphere/kubesphere/pull/4399?This has fixed.

**Comment by 760515805** [comment]
> 和这个[#4399 一样](https://github.com/kubesphere/kubesphere/pull/4399)吗？这个已经修复了。

not the same problem，myy problem is that the index cannot be created automatically

**Comment by wenchajun** [comment]
See if the prefix in es is configured correctly and if the connection is successful.

**Comment by 760515805** [comment]
> See if the prefix in es is configured correctly and if the connection is successful.

all correct, when I manually create the index, the log can be written normally

**Comment by wenchajun** [comment]
This requires checking your FileBeat profile to see if the es received the data. A simple test is to turn off fluent-bit and see if FileBeat outputs data to ES, or some other way to test it. In addition, in kubesphere v3.2, Fluentbit added the parameter `generateID :true` , generate _id for outgoing records. This prevents duplicate records when retrying ES.
