### ISSUE TITLE
cas authentication not work

### ISSUE THREAD

**Issue by phoenixwu0229** [kubesphere/kubesphere#4472]
**Describe the Bug**
cas  authentication not work, when i return ticket to ks, ks's status is still Not login.
**Versions Used**
KubeSphere: v3.2.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
config cas with:
         - name: cas
           type: CASIdentityProvider
           provider:
             casServerURL: "http://cas.xxx.xx.xxcas"
             redirectURL: "http://youfu.xxx.xxx.xxx:30880"
             insecureSkipVerify: false

ks-console log:
UnauthorizedError: Not Login
    at Object.throw (/opt/kubesphere/console/server/server.js:19619:11)
    at getCurrentUser (/opt/kubesphere/console/server/server.js:5422:14)
    at renderView (/opt/kubesphere/console/server/server.js:69297:7)
    at dispatch (/opt/kubesphere/console/server/server.js:3121:32)
    at next (/opt/kubesphere/console/server/server.js:3122:18)
    at /opt/kubesphere/console/server/server.js:37176:16
    at dispatch (/opt/kubesphere/console/server/server.js:3121:32)
    at next (/opt/kubesphere/console/server/server.js:3122:18)
    at /opt/kubesphere/console/server/server.js:45191:37
    at dispatch (/opt/kubesphere/console/server/server.js:3121:32)
  --> GET /?ticket=ST-184992-r71jdvsPX2iB3NnV7GyT&ext= 302 2ms 43b 2021/11/25T14:04:35.060
  <-- GET /login 2021/11/25T14:04:35.098
  --> GET /login 200 7ms 15.7kb 2021/11/25T14:04:35.10

**Expected behavior**

**Comment by wansir** [comment]
> redirectURL: "http://youfu.xxx.xxx.xxx:30880"

You need to set redirectURL to `redirectURL: "http://youfu.xxx.xxx.xxx:30880/oauth/redirect/<YOUR CAS IdentityProvider NAME>"`

**Comment by phoenixwu0229** [comment]
> 

should i create the user in kubesphere first? 

  code: 401,
  statusText: 'Unauthorized',
  message: 'Unauthorized: user.iam.kubesphere.io "wutong6" not found\n'

**Comment by wansir** [comment]
> > 
> 
> should i create the user in kubesphere first?
> 
> code: 401, statusText: 'Unauthorized', message: 'Unauthorized: user.iam.kubesphere.io "wutong6" not found\n'

Configure IdentityProvider `MappingMethod: auto`.

https://github.com/kubesphere/kubesphere/blob/f67e1baf34ac323b06a48db07f0b70d15a3c12a5/pkg/apiserver/authentication/oauth/options.go#L149-L155

**Comment by phoenixwu0229** [comment]
> MappingMethod

tks it works, a suggestion: maybe it can be add on kubesphere docs

**Comment by phoenixwu0229** [comment]
maybe it can be add on kubesphere docs
