### ISSUE TITLE
Failed to create federated deployment

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4474]
**Describe the Bug**
1. Click Create and set the correct deployment information
2. No pod created in the host cluster

![image](https://user-images.githubusercontent.com/88183150/143410208-f674e052-e987-4ed5-8588-ec86d90645a8.png)

**Versions Used**
KubeSphere: 3.2.1-rc.1
Kubernetes: 1.21.5

/kind bug
/@kubesphere/sig-kubesphere
/priority medium

**Comment by iawia002** [comment]
This is not a bug, the host cluster of this multi-cluster project is configured with a limit quota, but this application is not configured with quota, so the admission webhook of the host cluster rejected the request to create a pod, and the other cluster did not set a quota limit, so another pod of the cluster is created successfully, either do not set the limit quota or configure the quota of the pod when creating the application.
