### ISSUE TITLE
kubeedge logs exec can not work

### ISSUE THREAD

**Issue by loveplxf** [kubesphere/kubesphere#4477]
**Describe the Bug**

the edge node has metrics information, and the application can be deployed normally, but the log and exec  cannot be accessed.
the logs of edge nodes can be accessed on nodes 1, 2 and 3 (iptables deployed nodes), but they can't be accessed through web pages and APIs. What's the problem? How to check? Please help me out of your busy schedule. Thank you

For UI issues please also add a screenshot that shows the issue.

![image](https://user-images.githubusercontent.com/23065644/143536363-8e384b85-409d-43b0-984a-7794d16e26e1.png)
![image](https://user-images.githubusercontent.com/23065644/143536374-6986919d-120c-4f5e-a74c-8ebbb1e5fd31.png)
![image](https://user-images.githubusercontent.com/23065644/143536384-589b1a38-ad08-4276-8a4a-88cc75b548f6.png)
![image](https://user-images.githubusercontent.com/23065644/143536394-7bca63af-9c09-440c-83ea-9f11a4a76cda.png)
![image](https://user-images.githubusercontent.com/23065644/143536402-05c22f57-f71d-4cc4-a887-87dd80665853.png)
![image](https://user-images.githubusercontent.com/23065644/143536413-4efe18bb-69cb-4e34-8abf-e0815926d2cc.png)

**Versions Used**
KubeSphere: v3.2.0
Kubernetes: (If KubeSphere installer used, you can skip this)
v1.21.5

**Environment**
How many nodes and their hardware configuration:
CentOS 7.9 / 3 masters:  8cpu/16g; 3 nodes: 8cpu/16g
For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by loveplxf** [comment]
Reason found: there are stains on the master node after installation, and iptables are not deployed to the master node.
Solution update: after the stain on the master node is removed, the iptables daemon is automatically deployed, and the problem is solved.

**Comment by 8183736** [comment]
root@node1:~# kubectl exec -it pod/test1-hdf4c /bin/sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Error from server: error dialing backend: dial tcp 10.41.1.37:10350: i/o timeout
我这是超时
