### ISSUE TITLE
Add cluster failed

### ISSUE THREAD

**Issue by coolhok** [kubesphere/kubesphere#4480]
**Describe the Bug**
when Add Direct connection k8s cluster with kube-config,but ui return failed!

ks-apiserver log:
E1126 20:00:24.974365       1 utils.go:76] /workspace/pkg/kapis/cluster/v1alpha1/handler.go:282 unable validate kubesphere endpoint, invalid response: ks-apiserver , please make sure kubesphere-system.{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services \"ks-apiserver\" not found","reason":"NotFound","details":{"name":"ks-apiserver","kind":"services"},"code":404}
.svc of member cluster is up and running

**Versions Used**
KubeSphere: v3.2.0
Kubernetes: 1.21.0

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.6 / 1 masters:  24cpu/16g;

**How To Reproduce**

**Expected behavior**
no err log!!

**Comment by cherry-hyx** [comment]
The added cluster needs to also install kubesphere。

**Comment by zryfish** [comment]
Please read our documentation https://kubesphere.io/docs/multicluster-management/enable-multicluster/direct-connection/

/close
