### ISSUE TITLE
Login jenkins

### ISSUE THREAD

**Issue by xiongyunhua-star** [kubesphere/kubesphere#4483]
devops功能的jenkins用户名密码是什么？查看名为ks-jenkins的secret信息，也无法登陆

**Comment by JohnNiang** [comment]
Please refer to
- https://kubesphere.io/docs/devops-user-guide/how-to-use/jenkins-setting/
- https://kubesphere.io/zh/docs/devops-user-guide/how-to-use/jenkins-setting/ [In Chinese]

**Comment by xiongyunhua-star** [comment]
https://v2-1.docs.kubesphere.io/docs/zh-CN/devops/jenkins-setting/

resolved!
