### ISSUE TITLE
Replace ADD https://... with RUN wget in Dockerfile

### ISSUE THREAD

**Issue by anhoder** [kubesphere/kubesphere#4488]
**What's it about?**

Replace `ADD https://...` with `RUN wget` in Dockerfile

**What's the reason why we need it?**

I failed to build an image of ks-apiserver using kaniko. 
Because the kaniko does not support using HTTPS in `ADD` (It could be a bug, but I can't fix it: https://github.com/GoogleContainerTools/kaniko/issues/1590).

I want to replace 
`ADD https://get.helm.sh/helm-${HELM_VERSION}-${TARGETOS}-${TARGETARCH}.tar.gz /tmp` 
with 
`RUN wget -P /tmp https://get.helm.sh/helm-${HELM_VERSION}-${TARGETOS}-${TARGETARCH}.tar.gz` 
(It's easier for me).

**Area Suggestion**

/kind feature-request

**Comment by anhoder** [comment]
I found another way

**Comment by jolbax** [comment]
Hi @anhoder, which is your other way to solve this problem?
