### ISSUE TITLE
how to config the time span of Traffic monitoring？

### ISSUE THREAD

**Issue by happywzy** [kubesphere/kubesphere#4491]
Version:V3.2.0
![image](https://user-images.githubusercontent.com/26290710/144019730-7c7ec12b-d1a4-4e29-8481-24be8d5c3efd.png)
I want to monitor traffic over the past day， so how to config?

**Comment by happywzy** [comment]
this configuration is  about `kiali`,but useless when I change `1m` to `1440m`
![image](https://user-images.githubusercontent.com/26290710/144020218-3bddd27d-9b38-4c78-a398-dcbd34b34e7b.png)

The native Kiali interface makes it easy to choose which areas of traffic to monitor, and kubesphere is also recommended to be integrated.
![image](https://user-images.githubusercontent.com/26290710/144020324-f89ad4a9-15db-4498-ad71-9cdbfde23cad.png)

**Comment by RolandMa1986** [comment]
@weili520 There are some parameter issues that caused the traffic monitoring diagram is incorrectly displayed.
Could you help to fix the issue together?
https://github.com/kubesphere/kubesphere/issues/4498

**Comment by wenxin-01** [comment]
issue fix in `v3.3.0-alpha.2`
![image](https://user-images.githubusercontent.com/68640256/167233482-679c5e45-fff0-447c-bc00-bee2f2e170bd.png)
