### ISSUE TITLE
Incorrect number of cluster gateway requests

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4493]
**Describe the Bug**
1、View gateway details, select the last 12 hours
2、 Refresh the page, the total number of requests changes

![image](https://user-images.githubusercontent.com/88183150/144161772-706223f9-3787-4359-8cb7-a29eb8276620.png)

![image](https://user-images.githubusercontent.com/88183150/144161877-5249fef2-8b1c-4fa5-a690-c7349ecb4746.png)

**Versions Used**
KubeSphere: v3.2.1-rc.1

/kind bug
/assign @RolandMa1986 
/priority medium

**Comment by RolandMa1986** [comment]
This is a Prometheus Metrix issue, we can fix it currently. Suggest to close it.
There's no matrix for the total request in the last n minutes. So we had to calculate it through the increment in the last n minutes. But we found that if there's no "0" value in the first scrap window, the increment will be random. 
We can wait for a few second to let Prometheus scrap the 0 value before we send the request to bypass this issue.
