### ISSUE TITLE
2.0 branch

### ISSUE THREAD

**Issue by cnicy** [kubesphere/kubesphere#450]
发现有一个advanced2.0的branch，是2.0高级版的源代码吗，跟正式发布的2.0版本代码一致吗？

**Comment by rayzhou2017** [comment]
是的

**Comment by cnicy** [comment]
弱弱问一下，ui什么时候放出来，对于我们而言其实kubesphere的ui设计交互体验和qingcloud的基础设施是最大优势，所以希望UI能早些出来！
