### ISSUE TITLE
All node went NotReady after upgrading to 3.2.0

### ISSUE THREAD

**Issue by iwtctww** [kubesphere/kubesphere#4502]
**Describe the Bug**
I upgrade kubesphere with "./kk upgrade --with-kubernetes v1.21.5 --with-kubesphere v3.2.0 -f sample.yaml"
the kubernetes upgrade works fine but the kubesphere upgrade just keep me waiting. the log is like:

INFO[01:06:22 CST] Deploying KubeSphere ...                     
v3.2.0
WARN[01:06:23 CST] Currently, the logging function of KubeSphere does not support . If  is used, the logging function will be unavailable.  node=192.168.0.135
[kubesphere-x86-master-01 192.168.0.135] MSG:
namespace/kubesphere-system unchanged
namespace/kubesphere-monitoring-system unchanged
[kubesphere-x86-master-01 192.168.0.135] MSG:
namespace/kubesphere-system unchanged
serviceaccount/ks-installer unchanged
customresourcedefinition.apiextensions.k8s.io/clusterconfigurations.installer.kubesphere.io unchanged
clusterrole.rbac.authorization.k8s.io/ks-installer unchanged
clusterrolebinding.rbac.authorization.k8s.io/ks-installer unchanged
deployment.apps/ks-installer unchanged
Please wait for the installation to complete:   >>---> 

And when I check the nodes, I find all nodes are NotReady!!! Nothing running properly.
**#kubectl get nodes**
NAME                       STATUS     ROLES                         AGE    VERSION
kubesphere-arm-node-01     NotReady   worker                        174d   v1.20.4
kubesphere-x86-master-01   NotReady   control-plane,master,worker   174d   v1.20.4
kubesphere-x86-node-01     NotReady   worker                        161d   v1.20.4

this is all about the pods:
**#kubectl get pods -n kube-system** 
NAME                                                 READY   STATUS        RESTARTS   AGE
calico-kube-controllers-7f46b8b669-9mk24             1/1     Running       4          162d
calico-node-bqxhg                                    1/1     Running       3          174d
calico-node-dhblk                                    1/1     Running       10         161d
calico-node-sx7cm                                    1/1     Running       9          174d
coredns-65944cbcb8-2827n                             1/1     Terminating   3          162d
coredns-65944cbcb8-dd5qv                             1/1     Terminating   6          162d
coredns-b5648d655-7t6pg                              1/1     Running       0          139m
coredns-b5648d655-bs849                              0/1     Pending       0          139m
kube-apiserver-kubesphere-x86-master-01              1/1     Running       0          140m
kube-controller-manager-kubesphere-x86-master-01     0/1     Running       0          140m
kube-proxy-kxlqt                                     0/1     Pending       0          137m
kube-proxy-ns7k8                                     0/1     Pending       0          137m
kube-proxy-tm4qb                                     0/1     Pending       0          137m
kube-scheduler-kubesphere-x86-master-01              0/1     Running       0          140m
metrics-server-66785bf598-zj2q8                      1/1     Running       17         163d
nfs-client-nfs-client-provisioner-58c7bcdd64-r9m27   1/1     Running       9          132d
nodelocaldns-2rqhl                                   1/1     Running       3          163d
nodelocaldns-9zm2v                                   1/1     Running       10         161d
nodelocaldns-lz27l                                   1/1     Running       7          163d
openebs-localpv-provisioner-d848b7675-hq7z4          1/1     Running       4          85d
snapshot-controller-0                                1/1     Running       5          135d
upgrade-health-check-w9lxj                           0/1     Terminating   0          141m

I thought maybe something wrong with kube-proxy, but I didn't find any useful clue. 
I have tried restart the docker and kubelet, but still goes wrong.
anyone can help?

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: 3.2.0
Kubernetes: 1.21.5
(If KubeSphere installer used, you can skip this)

**Environment**
2*x86 node、1*arm node，all Ubuntu 20， 8c64g
How many nodes and their hardware configuration:
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by xyz-li** [comment]
The pods' status of kube-proxy is pending. You need to find the reason.
Please run this command.
kubectl describe po ${kube-proxy-pod-name} -n kube-system.

**Comment by iwtctww** [comment]
> The pod's status of kube-proxy is `Pending`. You need to find the reason. Please run this command. `kubectl describe po ${kube-proxy-pod-name} -n kube-system `

3 kube-proxy nodes are in the same status as below:

Name:                 kube-proxy-tm4qb
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 kubesphere-x86-master-01/
Labels:               controller-revision-hash=5ccdb8dc86
                      k8s-app=kube-proxy
                      pod-template-generation=5
Annotations:          <none>
Status:               Pending
IP:                   
IPs:                  <none>
Controlled By:        DaemonSet/kube-proxy
Containers:
  kube-proxy:
    Image:      kubesphere/kube-proxy:v1.21.5
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/local/bin/kube-proxy
      --config=/var/lib/kube-proxy/config.conf
      --hostname-override=$(NODE_NAME)
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/lib/kube-proxy from kube-proxy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-8l26w (ro)
Conditions:
  Type           Status
  PodScheduled   True 
Volumes:
  kube-proxy:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-proxy
    Optional:  false
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
  kube-api-access-8l26w:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 op=Exists
                             CriticalAddonsOnly op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:                      <none>

Acutally I know there must be something wrong with the network, but I just can't figure out where.
Thank u

**Comment by xyz-li** [comment]
The `Events` is empty. You can delete one of the kube-proxy pods, then describe the new pod.

**Comment by iwtctww** [comment]
> The `Events` is empty. You can delete one of the kube-proxy pods, then describe the new pod.

I force delete it, but how can I recreate the kube-proxy nodes? I tried "kubectl edit cm kube-proxy -n kube-system", but nothing happened.

**Comment by iwtctww** [comment]
> The `Events` is empty. You can delete one of the kube-proxy pods, then describe the new pod.

I have recreated the kube-proxy daemonset, and most of the system comes back.
Only one arm64 node still remains NotReady. The kube-proxy pod on it keeps "pending". 

`
Name:                 kube-proxy-szdft
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 kubesphere-arm-node-01/
Labels:               controller-revision-hash=5ccdb8dc86
                      k8s-app=kube-proxy
                      pod-template-generation=1
Annotations:          <none>
Status:               Pending
IP:                   
IPs:                  <none>
Controlled By:        DaemonSet/kube-proxy
Containers:
  kube-proxy:
    Image:      kubesphere/kube-proxy:v1.21.5
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/local/bin/kube-proxy
      --config=/var/lib/kube-proxy/config.conf
      --hostname-override=$(NODE_NAME)
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/lib/kube-proxy from kube-proxy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-f8954 (ro)
Conditions:
  Type           Status
  PodScheduled   True 
Volumes:
  kube-proxy:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-proxy
    Optional:  false
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
  kube-api-access-f8954:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 op=Exists
                             CriticalAddonsOnly op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  48m   default-scheduler  Successfully assigned kube-system/kube-proxy-szdft to kubesphere-arm-node-01

`
Can anyone help?

**Comment by iwtctww** [comment]
> > The `Events` is empty. You can delete one of the kube-proxy pods, then describe the new pod.
> 
> I have recreated the kube-proxy daemonset, and most of the system comes back. Only one arm64 node still remains NotReady. The kube-proxy pod on it keeps "pending".
> 
> ```
> Name:                 kube-proxy-szdft
> Namespace:            kube-system
> Priority:             2000001000
> Priority Class Name:  system-node-critical
> Node:                 kubesphere-arm-node-01/
> Labels:               controller-revision-hash=5ccdb8dc86
>                       k8s-app=kube-proxy
>                       pod-template-generation=1
> Annotations:          <none>
> Status:               Pending
> IP:                   
> IPs:                  <none>
> Controlled By:        DaemonSet/kube-proxy
> Containers:
>   kube-proxy:
>     Image:      kubesphere/kube-proxy:v1.21.5
>     Port:       <none>
>     Host Port:  <none>
>     Command:
>       /usr/local/bin/kube-proxy
>       --config=/var/lib/kube-proxy/config.conf
>       --hostname-override=$(NODE_NAME)
>     Environment:
>       NODE_NAME:   (v1:spec.nodeName)
>     Mounts:
>       /lib/modules from lib-modules (ro)
>       /run/xtables.lock from xtables-lock (rw)
>       /var/lib/kube-proxy from kube-proxy (rw)
>       /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-f8954 (ro)
> Conditions:
>   Type           Status
>   PodScheduled   True 
> Volumes:
>   kube-proxy:
>     Type:      ConfigMap (a volume populated by a ConfigMap)
>     Name:      kube-proxy
>     Optional:  false
>   xtables-lock:
>     Type:          HostPath (bare host directory volume)
>     Path:          /run/xtables.lock
>     HostPathType:  FileOrCreate
>   lib-modules:
>     Type:          HostPath (bare host directory volume)
>     Path:          /lib/modules
>     HostPathType:  
>   kube-api-access-f8954:
>     Type:                    Projected (a volume that contains injected data from multiple sources)
>     TokenExpirationSeconds:  3607
>     ConfigMapName:           kube-root-ca.crt
>     ConfigMapOptional:       <nil>
>     DownwardAPI:             true
> QoS Class:                   BestEffort
> Node-Selectors:              kubernetes.io/os=linux
> Tolerations:                 op=Exists
>                              CriticalAddonsOnly op=Exists
>                              node.kubernetes.io/disk-pressure:NoSchedule op=Exists
>                              node.kubernetes.io/memory-pressure:NoSchedule op=Exists
>                              node.kubernetes.io/network-unavailable:NoSchedule op=Exists
>                              node.kubernetes.io/not-ready:NoExecute op=Exists
>                              node.kubernetes.io/pid-pressure:NoSchedule op=Exists
>                              node.kubernetes.io/unreachable:NoExecute op=Exists
>                              node.kubernetes.io/unschedulable:NoSchedule op=Exists
> Events:
>   Type    Reason     Age   From               Message
>   ----    ------     ----  ----               -------
>   Normal  Scheduled  48m   default-scheduler  Successfully assigned kube-system/kube-proxy-szdft to kubesphere-arm-node-01
> ```
> 
> Can anyone help?

I made it. There is something wrong with the network and the haproxy node didn't work.
After I upgrade the system and network, everything goes fine
