### ISSUE TITLE
v3.2服务网关的deploy yaml文件无法修改

### ISSUE THREAD

**Issue by cyrpg520** [kubesphere/kubesphere#4503]
v3.2服务网关的deploy yaml文件无法修改，修改后又被还原。调度规则也修改后又还原，导致扩容多个pod后又被删除。
![2021123-92452](https://user-images.githubusercontent.com/8519597/144528897-a13a0da9-e2e0-4523-b620-4e471ac17bae.png)
![2021123-9250](https://user-images.githubusercontent.com/8519597/144528912-25a4d0bf-9d26-4abd-a5cc-7e90f6862ad8.png)

**Comment by RolandMa1986** [comment]
@cyrpg520 
Please read the documnet https://kubesphere.com.cn/docs/cluster-administration/cluster-settings/cluster-gateway/
/kind support
