### ISSUE TITLE
the roadmap is not updated to date

### ISSUE THREAD

**Issue by gongysh2004** [kubesphere/kubesphere#4505]
**Describe the Bug**

could you please update the roadmap and show what is the release life cycle plan, for example, 4 per year?

https://github.com/kubesphere/kubesphere/blob/master/docs/roadmap.md

**Comment by FeynmanZhou** [comment]
> **Describe the Bug**
> 
> could you please update the roadmap and show what is the release life cycle plan, for example, 4 per year?
> 
> https://github.com/kubesphere/kubesphere/blob/master/docs/roadmap.md

@gongysh2004 Thanks for pointing out this issue. This document is out-of-date, we will update it according to the current releases and feature requests. As I know, the next release is v3.2.1, it will fix the known bugs and add upgrades in this release. v3.2.1 will be available this month.
