### ISSUE TITLE
Browser compatibility issues

### ISSUE THREAD

**Issue by rockpanda** [kubesphere/kubesphere#4508]
version：v3.2.0
description：
To create an app from an app template, click Install No Response,After testing, it was found to be a browser probl
<img width="2573" alt="iShot2021-12-04 16 46 09" src="https://user-images.githubusercontent.com/42989547/144703601-d7d7b6c5-b6dc-4de8-8b66-faea07a76e47.png">
em

**Comment by xyz-li** [comment]
@harrisonliu5 
The `Install` button does not work on `360 browser`.

**Comment by zryfish** [comment]
@xyz-li Have you tried it on your computer? So it's a reproducible bug?

**Comment by rockpanda** [comment]
可以复现
