### ISSUE TITLE
Cluster worker node statistics error

### ISSUE THREAD

**Issue by rockpanda** [kubesphere/kubesphere#4510]
version:3.2.0
The total number of nodes in the cluster is 3 nodes, but there are only 2 working nodes, and 3 working nodes are displayed.

<img width="1425" alt="iShot2021-11-29 09 40 06" src="https://user-images.githubusercontent.com/42989547/144703738-bda1a3d5-4d19-4884-9973-61f03ef7bf15.png">

**Comment by xyz-li** [comment]
@VioZhang @harrisonliu5 

If a node has a label `node-role.kubernetes.io/control-plane=`, then this node is considered a `worker node`. This is a bug.

**Comment by weili520** [comment]
This issue has been resolved in this pr: [#2878](https://github.com/kubesphere/console/pull/2878).

**Comment by jioce** [comment]
issue fixed in v3.3.0-alpha.2
