### ISSUE TITLE
The log console is empty 

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#4511]
**Describe the Bug**

The logging console is empty when I use KubeSphere on K3s, I can't query any logs from the KubeSphere logging console. In terms of the reason to test this scenario, I have elaborated on https://github.com/kubesphere/kubesphere/issues/4468.

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: v3.2.0
Kubernetes:  K3s 1.21 (Installation with KubeKey)

**Environment**
How many nodes and their hardware configuration:

8 c 16 G

**How To Reproduce**
1. Go to 'Toolbox'
2. Click on 'Container Log Search'
3. See there is a log console without any data, you will find the error logs from the top right corner.
![image](https://user-images.githubusercontent.com/40452856/144704708-669b61d7-5bc1-4106-90c1-692f8b950101.png)
![image](https://user-images.githubusercontent.com/40452856/144704725-43d5f566-affe-4b75-8875-379ba200971a.png)

**Expected behavior**

The feature of KubeSphere logging should work well on k3s, we can effectively query historical logs from it.

**Comment by FeynmanZhou** [comment]
@kubesphere/sig-observability

**Comment by liangyuanpeng** [comment]
I also deploy kubesphere on k3s and i can see some log.  my k3s version is `v1.21.7+k3s1`

![image](https://user-images.githubusercontent.com/28711504/144754802-5e31890d-2466-4916-ac1a-7809264490bb.png)

**Comment by wenchajun** [comment]
Thank you for your quick reply. I replicated what you did. 

Here is K3s,you can see 
![1638785142(1)](https://user-images.githubusercontent.com/39892300/144827164-853844a2-7dc7-4248-aab6-03c1bac938b1.png)
K3s does not have a Docker environment, so the corresponding containerruntime should be set to contained. You should make the following changes:
```
kubectl edit cc -n kubesphere-system
```
change the  filed `spec.logging.containerruntime: docker ` to `spec.logging.containerruntime: containerd `

**Comment by FeynmanZhou** [comment]
> Thank you for your quick reply. I replicated what you did.
> 
> Here is K3s,you can see ![1638785142(1)](https://user-images.githubusercontent.com/39892300/144827164-853844a2-7dc7-4248-aab6-03c1bac938b1.png) K3s does not have a Docker environment, so the corresponding containerruntime should be set to contained. You should make the following changes:
> 
> ```
> kubectl edit cc -n kubesphere-system
> ```
> 
> change the filed `spec.logging.containerruntime: docker ` to `spec.logging.containerruntime: containerd `

Hi @liangyuanpeng @wenchajun , thanks for your help! This issue has been resolved after I change the `spec.logging.containerruntime: docker` to `spec.logging.containerruntime: containerd`. contained has been widely adopted in most cloud-hosted Kubernetes and k3s, we need to notice this configuration.
