### ISSUE TITLE
Delete crd cannot use 

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4514]
**Describe the Bug**
When uninstalling audit log component, delete related crd file command error

![image](https://user-images.githubusercontent.com/88183150/144818211-935bd62a-f7ed-4e6e-92ac-d65911c226f3.png)

![image](https://user-images.githubusercontent.com/88183150/144818377-07a83be0-de96-4a43-9c3b-df805270da5e.png)

**Versions Used**
KubeSphere: 3.2.1-rc.1
Documentation 3.2.0

**Expected behavior**
Need full crd name

/kind bug
/@kubesphere/sig-docs
/priority medium

**Comment by xyz-li** [comment]
Please use the full name of the crd.
`
 kubectl delete crd rules.auditing.kubesphere.io
`

/close
