### ISSUE TITLE
There is a messing number showed when we roll back to the old version of the workload.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#4516]
**Describe the Bug**
When we need to roll back to the old version of the workload,the version showed of the version should match the date ,and it is needless and not reasonable to create a new version number to match the original date.
![image](https://user-images.githubusercontent.com/41519383/144988527-6af7fb4a-8822-4855-a5a3-e3bb23620fab.png)
![image](https://user-images.githubusercontent.com/41519383/144989431-b5076fed-d2c4-4b79-a8fd-74b8328f0e59.png)

**Expected behavior**

When we choose to roll back to the old version such as the "#8" from "#9",we should the the version now is”#8“ not”#10“.
In a word,the number should be created by the order of the date,and should never be changed.

**Comment by zryfish** [comment]
Maybe a little misleading, but work as designed, not a bug. Every time you rollout to an old version, a new revision will be created, increasing the sequence number.

/close
