### ISSUE TITLE
Incorrect steps to uninstall the service topology diagram document

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4517]
**Describe the Bug**
The value of network.topology.type cannot be true or false
![image](https://user-images.githubusercontent.com/88183150/144990613-6561ff02-b457-448a-b8b2-808634a408a3.png)

After opening：

![image](https://user-images.githubusercontent.com/88183150/144990722-e2a655d3-4247-4973-a9ac-a299bf302189.png)
Before opening：

![image](https://user-images.githubusercontent.com/88183150/144990814-42917271-aa7c-4d8c-a018-21dd08cea4ad.png)

**Versions Used**
KubeSphere: v3.2.1-rc.2
document: 3.2.0

/kind bug
/@kubesphere/sig-docs
/priority medium

**Comment by Felixnoo** [comment]
I found out that the content for uninstalling IP Pod Pool is also incorrect. I'll update that part as well.
![image](https://user-images.githubusercontent.com/75110798/145008299-3d0f8c0e-21cf-42ca-9daf-6323b92227f5.png)

**Comment by jioce** [comment]
issue fixed
