### ISSUE TITLE
Harbor mirror repository cannot be selected

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#4518]
**Describe the Bug**
1. In configuration under the project, create a configuration for the Harbor mirror repository
2. To create the workload, select the Harbor Mirror repository

**problem:**
Harbor mirror repository cannot be selected

![image](https://user-images.githubusercontent.com/36271543/145005698-d921a3e2-e6d4-4923-8a5a-16a736a1f1be.png)

**Versions Used**
KubeSphere: kubespehre v3.2.1-rc.2
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/assign @zryfish 
/priority High

**Comment by harrisonliu5** [comment]
fixed by https://github.com/kubesphere/console/pull/2784/files

**Comment by liuyp2018** [comment]
fixed
