### ISSUE TITLE
In the existing Prometheus cluster deployment, CPU and memory data cannot be obtained

### ISSUE THREAD

**Issue by zhangmengid** [kubesphere/kubesphere#4519]
![image](https://user-images.githubusercontent.com/83331571/145142675-94aa7c7a-a090-4404-aeb8-8f36cbd0d34d.png)
![image](https://user-images.githubusercontent.com/83331571/145142727-b34b0766-1bd7-4e6d-af4f-32ad0fe5d6eb.png)

**Comment by zryfish** [comment]
Please wait for a while, Prometheus has a slow warmup in collecting these data.
