### ISSUE TITLE
安装方式支持现有k8s集群

### ISSUE THREAD

**Issue by wu0407** [kubesphere/kubesphere#452]
**General remarks**

现在安装方式只支持自动安装k8s集群，已经有了k8s集群如何集成kubesphere
官方文档里面有离线安装，可以这里细化

**Comment by rayzhou2017** [comment]
稍等两天，在existing k8s上安装kubeSphere还在测试

**Comment by wu0407** [comment]
还有就是all-in-one 定位是预览功能，不应该设置限制cpu和内存，我开个虚拟机3g内存，完全起不来，那么多组件都要cpu，安装之前可以选择安装部分功能

**Comment by rayzhou2017** [comment]
是的，这是一个好问题，会计划做的，第一，需要进一步优化footprint，第二，做成可插拔的系统。第一点会很快进行的。

**Comment by liangyuanpeng** [comment]
@rayzhou2017  
在existing k8s上安装kubeSphere 大概什么时候会推出

**Comment by pixiake** [comment]
@liangyuanpeng 现在的安装包已经支持在existing k8s上安装kubeSphere，但安装方法较为复杂，目前正在对这种安装方法进行优化。

**Comment by jingwanglong** [comment]
现在可以一键在existing k8s上安装kubeSphere了吗？kubeSphere支持kubernetes 1.13.8或者更高版本？

**Comment by pixiake** [comment]
@jingwanglong 可以参考https://github.com/pixiake/ks-installer尝试在existing k8s安装

**Comment by pixiake** [comment]
@jingwanglong 可以参考https://github.com/pixiake/ks-installer   尝试在existing k8s安装

**Comment by hyhy01** [comment]
> 还有就是all-in-one 定位是预览功能，不应该设置限制cpu和内存，我开个虚拟机3g内存，完全起不来，那么多组件都要cpu，安装之前可以选择安装部分功能

我用all in one方式装了之后消耗10g内存，笔记本i7消耗70%，确实希望可以选择部分安装

**Comment by ccc7574** [comment]
@rayzhou2017 快过去三个月了，啥时候搞定啊？我们希望kubesphere整合阿里云k8s集群和私有云k8s集群，如果这个功能支持了绝对利国利民啊

**Comment by pixiake** [comment]
@ccc7574    可以参考https://github.com/kubesphere/ks-installer
