### ISSUE TITLE
could not login kubesphere

### ISSUE THREAD

**Issue by eternalsilencer** [kubesphere/kubesphere#4520]
i use correct password ,but can not login in 
![image](https://user-images.githubusercontent.com/51810383/145144802-e44d1e9f-2a86-45cb-8c54-f86598afb89e.png)

**Comment by xyz-li** [comment]
Is the ks-apiserver ready?
`kubectl get po -n kubesphere-system`

**Comment by wansir** [comment]
> i use correct password ,but can not login in ![image](https://user-images.githubusercontent.com/51810383/145144802-e44d1e9f-2a86-45cb-8c54-f86598afb89e.png)

The root cause of getaddrinfo error is always DNS service in the cluster not working well. See also https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

**Comment by eternalsilencer** [comment]
i check api-server and core-dns ，all correct,but still can not login
![image](https://user-images.githubusercontent.com/51810383/146288444-268e7b9f-612c-4814-98a7-040a7695f912.png)

**Comment by eternalsilencer** [comment]
i check api-server and core-dns ，all correct,but still can not login
![image](https://user-images.githubusercontent.com/51810383/146288608-bd3b9194-89a2-4c8c-b930-971800f536b1.png)

**Comment by RolandMa1986** [comment]
@eternalsilencer Please try the following step:
1. edit the ks-console deployment. Add the following section under container. 
```yaml
          securityContext:
            privileged: false
            runAsUser: 0
            runAsGroup: 0
```
2. get a shell `kubectl -n kubesphere-system exec -it ks-console-xx sh`
3. Run ' nslookup ks-apiserver'  to find out if dns works correctlly.

**Comment by eternalsilencer** [comment]
> 

the privileged don not exist: i modify rnAsUser,runAsGroup,still can't work
![image](https://user-images.githubusercontent.com/51810383/146379995-85db74dd-7e07-4a2d-8c71-b267787eeb1a.png)
