### ISSUE TITLE
Project network isolation outbound error

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4522]
**Describe the Bug**
There is a project test, with deployment de and service service，and a project test, with deployment dd and service ss
1. Open the project tt network isolation, no whitelist added
![image](https://user-images.githubusercontent.com/88183150/145173701-5b7d5e4c-23ba-4d93-ba5a-8d82d9f261e3.png)

2. Log in to the container terminal where dd is deployed, access the service service in the project test, and the access is successful
![image](https://user-images.githubusercontent.com/88183150/145173679-cf52d56a-40d0-40a5-90c3-f3bceecc2217.png)

3. Enter the project test, there is deployment de, log in to the container terminal of the deployment de, access the service ss in the project tt, the access fails
![image](https://user-images.githubusercontent.com/88183150/145173650-6d8e0610-fc77-40cb-98e7-c5a8510347be.png)

4. Add inbound and outbound whitelists in the project tt, select the project test
 
![image](https://user-images.githubusercontent.com/88183150/145173630-bf5630c7-c886-43c8-af93-28bb1bc8f04d.png)

5. Log in again to the container terminal where dd is deployed, access the service service in the project test, and the access is successful
![image](https://user-images.githubusercontent.com/88183150/145173611-f7d89981-1781-445d-bfe3-16e49420512c.png)

6. Enter the project test again, there is deployment de, log in to the container terminal of the deployment de, access the service ss in the project tt, the access is successful
![image](https://user-images.githubusercontent.com/88183150/145173593-9aaafa56-0e6f-484e-b832-078a133927ee.png)

**Versions Used**
KubeSphere: v3.2.1-rc.2

/kind bug
/@kubesphere/sig-kubesphere
/priority medium

**Comment by renyunkang** [comment]
This is not a bug. After the network isolation of workspace or project is enabled, egress is unblocked by default, and ingress is limited to the same workspace or project

**Comment by jioce** [comment]
What does the outbound whitelist setting do?

**Comment by renyunkang** [comment]
> What does the outbound whitelist setting do?

When network isolation is turned on, egress traffic will be allowed by default, while ingress traffic will be denied for different projects. But when you add an egress network policy, only traffic that matches your policy will be allowed to go out.
https://kubesphere.com.cn/en/docs/project-administration/project-network-isolation/
