### ISSUE TITLE
Traffic Management and Tracing page data have problems in multi-cluster project

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#4523]
**Describe the Bug**
1. In a multi-cluster project, enable the Nodeport mode gateway
2. Create a composing application and set the application route
3. Access Application Route
4. viewing Traffic Management and tracking page
5. the  graph display on the Traffic Management page  is incomplete
6. The tracking page has no data

![image](https://user-images.githubusercontent.com/36271543/145188953-72fb6593-ffc6-4813-89cb-6ec2668e3d6b.png)

![image](https://user-images.githubusercontent.com/36271543/145188929-c4019364-762f-4c1f-b7f6-45455118da37.png)

**Versions Used**
KubeSphere: kubesphere v3.2.1-rc.2
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/assign @harrisonliu5
/priority high

**Comment by liuyp2018** [comment]
There's data from the backend api
![image](https://user-images.githubusercontent.com/36271543/145189711-0694a547-f179-4a61-b068-30af57437693.png)

**Comment by liuyp2018** [comment]
Another question:
the application router created is lack of annotation: "nginx.ingress.kubernetes.io/service-upstream: true"
![image](https://user-images.githubusercontent.com/36271543/145190471-5a627b9e-68c5-49c0-be37-fdf82b590e6a.png)

**Comment by tracer1023** [comment]
1. "nginx.ingress.kubernetes.io/service-upstream: true" will be set when the serviceMesh is enabled.
2.The tracking page is normal
![image](https://user-images.githubusercontent.com/33512446/150718243-4542f160-a8e2-4c3e-8662-7809ab17ea94.png)
