### ISSUE TITLE
Can resources be set when logSidecar is created？

### ISSUE THREAD

**Issue by klj890** [kubesphere/kubesphere#4525]
**What's it about?**

Can resources be set when logSidecar is created？
Not configMap.
For example, add annotations to deploy to set resources.

**What's the reason why we need it?**

can restrict logSidecar resources.

**Area Suggestion**

> /area apiserver
> /area console

**Comment by wenchajun** [comment]
It is just a webhook, You can refer to https://github.com/kubesphere/logsidecar-injector.
