### ISSUE TITLE
v3.2.0配置多集群修改ClusterConfiguration中对应内容后无法登录终端

### ISSUE THREAD

**Issue by gudaoyufu** [kubesphere/kubesphere#4527]
#修改内容如下：
![0c0a5cbf0ee90f2e33d051107994fc0](https://user-images.githubusercontent.com/32258973/145345145-e1d31359-767a-4236-ac64-75ba502335e1.png)

#无法登录终端 ，非密码问题
![50349b16c619731cf0e64ec57fe49f0](https://user-images.githubusercontent.com/32258973/145345216-3890d702-c846-4568-8e83-7b3eee82be47.png)

**Comment by 18965050** [comment]
确实,   clusterRole还原为none后可以登录

**Comment by zryfish** [comment]
Please read our manual, and follow the instructions.

/close
