### ISSUE TITLE
elasticsearch-logging-data failed to start

### ISSUE THREAD

**Issue by hchenc** [kubesphere/kubesphere#4529]
**Describe the Bug**
elasticsearch-logging-data sts got error like that:
`
Exec lifecycle hook ([/bin/bash /post-start-hook.sh]) for Container "elasticsearch" in Pod "elasticsearch-logging-data-1_kubesphere-logging-system(193fe212-c2bc-4515-9feb-768cd57bd5c2)" failed - error: command '/bin/bash /post-start-hook.sh' exited with 137: tee: /var/log/elasticsearch-hooks.log: Permission denied , message: "tee: /var/log/elasticsearch-hooks.log: Permission denied\n"
`

**Versions Used**
KubeSphere: 3.2.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Comment by wenchajun** [comment]
Please provide more information. Did you install it using Kubekey? That looks like a lack of access. Can you provide the deployment yaml？

**Comment by hchenc** [comment]
> Please provide more information. Did you install it using Kubekey? That looks like a lack of access. Can you provide the deployment yaml？

the root cause is the es sts failed to obtain node locks, delete the nodes directory on pvc works for me which makes me lost the log data, there should be better way to resolve the node locks.
