### ISSUE TITLE
All-in-one 方式安装出错

### ISSUE THREAD

**Issue by Allenxuxu** [kubesphere/kubesphere#453]
TASK [win_nodes/kubernetes_patch : Check current command for kube-proxy daemonset] *************************************************************************************************************************
Monday 27 May 2019  21:29:46 +0800 (0:00:00.240)       0:02:43.457 ************ 
fatal: [ks-allinone]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/kubectl --kubeconfig /etc/kubernetes/admin.conf get ds kube-proxy --namespace=kube-system -o jsonpath='{.spec.template.spec.containers[0].command}'", "delta": "0:00:00.138890", "end": "2019-05-27 21:29:46.700593", "msg": "non-zero return code", "rc": 1, "start": "2019-05-27 21:29:46.561703", "stderr": "Error from server (NotFound): daemonsets.extensions \"kube-proxy\" not found", "stderr_lines": ["Error from server (NotFound): daemonsets.extensions \"kube-proxy\" not found"], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT *****************************************************************************************************************************************************************************************

PLAY RECAP *************************************************************************************************************************************************************************************************
ks-allinone                : ok=341  changed=41   unreachable=0    failed=1   
localhost                  : ok=1    changed=0    unreachable=0    failed=0

**Comment by wu0407** [comment]
我是卡在安装openpitrix ，发现安装脚本/etc/kubesphere/openpitrix/kubernetes/scripts/deploy-k8s.sh，没有指定kubeconfig，修改之后pod还是pending状态

**Comment by wu0407** [comment]
k8s.io/client-go/informers/factory.go:132: Failed to list *v1.ReplicaSet: replicasets.apps is forbidden: User "system:kube-scheduler" cannot list resource "replicasets" in API group "apps" at the cluster scope

**Comment by rayzhou2017** [comment]
allinone安装怎么还会出错？说一下安装环境，比如os，节点配置，安装步骤等信息。

**Comment by Allenxuxu** [comment]
ubuntu 16.04  4核8g 
完全按照说明安装的

**Comment by rayzhou2017** [comment]
你看的是1.0版本的吧，2.0版本的要求高了，因为东西更多了，CPU：8 核， 内存：16 G， 系统盘：100 G。我们会优化这个最小配置的。

**Comment by Allenxuxu** [comment]
ok 非常感谢耐心解答
