### ISSUE TITLE
[Feature Request] Disk usage should display the usage per hard disk.

### ISSUE THREAD

**Issue by xyz-li** [kubesphere/kubesphere#4532]
**What's it about?**

`Disk Usage` should display the usage per hard disk.

**What's the reason why we need it?**

A node has two disks, the system disk capacity is 50G, and the data disk is 200G. If the system disk is full (which is critical for the user) and the data disk has no data, then the `Disk Usage` displayed on the page is 20%. This will confuse the user. So the `Disk Usage` should contain the usage of every disk.

**Area Suggestion**

/area monitoring
/kind feature-request
/assign @VioZhang

**Comment by VioZhang** [comment]
![image](https://user-images.githubusercontent.com/41519383/157841377-551320a9-2ef4-4527-b67f-a2db7010a748.png)

**Comment by VioZhang** [comment]
> <img alt="运行状态" width="1440" src="https://user-images.githubusercontent.com/72596911/157848223-e7df8c3c-c13e-419b-b768-9b8093a32b93.png">

There is not a better to devide the disk into the system disk and data disk, so it seems that we dont need the first design picture.

**Comment by jioce** [comment]
issue is fixed 
![image](https://user-images.githubusercontent.com/88183150/170229820-09ff42f7-fc1a-4b2f-8a40-e811048e9b17.png)

![image](https://user-images.githubusercontent.com/88183150/170229895-2b6b3ff1-0928-4687-9be9-0d29dff97a23.png)

version used
nightly-20220524
