### ISSUE TITLE
从kubesphere 应用商店安装的应用的配置文件路径

### ISSUE THREAD

**Issue by eternalsilencer** [kubesphere/kubesphere#4534]
从kubesphere 应用商店安装的应用的配置文件在哪,是存放在linux哪个目录下，有时候我想定制化开发部署

**Comment by FeynmanZhou** [comment]
Hi,
The built-in applications are loaded from [this folder](https://github.com/kubesphere/helm-charts/tree/master/src), they are helm charts.

English only in GitHub issue, we have a Chinese forum for Chinese questions.
