### ISSUE TITLE
工作节点监控数据,一直显示暂时没有数据

### ISSUE THREAD

**Issue by timchine** [kubesphere/kubesphere#4535]
![image](https://user-images.githubusercontent.com/33122791/145750339-78cdb76c-4c84-4212-abf6-ed9543d270f3.png)
如图我主节点是有监控数据的,但是工作节点没有,其他的pod也是一样,试着把节点删除,重新加进来,也不行.改了时区也不行.不知道啥问题导致监控数据为空

**Comment by zblzbl1991** [comment]
我也遇到这个问题,master有监控数据,但是worker没有监控数据
