### ISSUE TITLE
add a new filter function to filter the status of the container

### ISSUE THREAD

**Issue by chj9** [kubesphere/kubesphere#4536]
**What's it about?**
I hope to add a new filter function to filter the status of the container, which is very useful for large quantities of containers

![image](https://user-images.githubusercontent.com/16426260/145791562-d967af6f-1fbe-424d-8e1b-cedf7727bcee.png)

**Comment by zryfish** [comment]
This is supported by our latest release v3.2.1, please have a try and tell us what you feel.

**Comment by zryfish** [comment]
This is supported by our latest release v3.2.1, please have a try and tell us what you feel.
