### ISSUE TITLE
Edit alarm policy to monitor resource type error

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4538]
**Describe the Bug**
**Describe the Bug**
There is an alarm policy aa1, which monitors the stateful replica set st

![image](https://user-images.githubusercontent.com/88183150/145930030-da4ddd89-44de-4c0f-9ef2-d0b19086edea.png)

1、Click edit, click next
2、The rule setting interface is displayed, and the monitoring resource type is displayed as deployment

![image](https://user-images.githubusercontent.com/88183150/145930000-b7d96cfb-d179-4597-9919-9544ce3eecdc.png)

3、There is no deployment st in the project
![image](https://user-images.githubusercontent.com/88183150/145930543-48ce6021-735a-45ca-867b-e499aa7294a9.png)

**Versions Used**
KubeSphere: v3.2.1-rc.3

/kind bug
/@kubesphere/sig-kubesphere
/priority medium

**Comment by benjaminhuo** [comment]
@junotx Is this a design limitation?

**Comment by jioce** [comment]
issue is still exist
![image](https://user-images.githubusercontent.com/88183150/174520273-e33360de-bdb4-476c-8405-cd9f0653eda9.png)

version used 
kubesphere: v3.3.0-rc.2
