### ISSUE TITLE
operator can not create ingress 

### ISSUE THREAD

**Issue by luoyuctl** [kubesphere/kubesphere#4539]
**Describe the Bug**

> The operator developer can't create ingress but can create deployment,
can I customize the role permissions that come with the map?

![image](https://user-images.githubusercontent.com/51604064/145953384-ae57812c-4917-4771-be08-82a80bcfb652.png)

![image](https://user-images.githubusercontent.com/51604064/145954412-02ef11b0-6271-488e-b7e6-f7c393c5020d.png)

**Versions Used**
KubeSphere:v3.2.0
Kubernetes:v1.20.4

**How To Reproduce**
1. set project user role 'operator'
2. create ingress

**Expected behavior**
the ingress can be created successful by operator user

**Comment by RolandMa1986** [comment]
This issue has been fixed by https://github.com/kubesphere/ks-installer/pull/1841
/duplicate https://github.com/kubesphere/kubesphere/issues/4489
/kind need-to-verify

**Comment by luoyuctl** [comment]
> This issue has been fixed by [kubesphere/ks-installer#1841](https://github.com/kubesphere/ks-installer/pull/1841) /duplicate #4489 /kind need-to-verify

okey, when could we use kubesphere 3.2.1?
