### ISSUE TITLE
社区版安装最后没有提示账号密码是什么

### ISSUE THREAD

**Issue by juixtu** [kubesphere/kubesphere#454]
默认账号密码哪里查看？

**Comment by FeynmanZhou** [comment]
@juixtu 建议下载 KubeSphere 最新发布的高级版 2.0.0，参考 [安装指南](https://docs.kubesphere.io/advanced-v2.0/zh-CN/installation/intro/)

**Comment by blueftss** [comment]
如果安装成功，安装包kubesphere目录下的kubesphere_running文件中保存了最后的账号密码信息
