### ISSUE TITLE
open project gateway, cannot update the corresponds "CRD-ServiceMonitor"  config "kubesphere-router-xxx"

### ISSUE THREAD

**Issue by LeoDemon** [kubesphere/kubesphere#4540]
**Versions Used**
KubeSphere:  3.2.0
Kubernetes:  1.20.5

**Environment**
3 master nodes, 2 worker nodes

CentOS Linux release 7.5.1804 (Core)， all node are:  8C/16G  

**How To Reproduce**
1. Go to 'xxx' project,  open the gateway
2. Go to 'CRD-ServiceMonitor'，you will see a new config:  "kubesphere-router-xxx"
3. edit the "kubesphere-router-xxx",  modify "interval" from "30s" to "15s"
4. commit the update, close the window
5. open the "kubesphere-router-xxx" again, you will find the "interval" value has been rolled back.

![upl-image-preview](https://kubesphere.com.cn/forum/assets/files/2021-12-14/1639470381-352119-servicemonitor.png)

![upl-image-preview2](https://kubesphere.com.cn/forum/assets/files/2021-12-14/1639470381-436623-servicemonitor-router.png)

**Expected behavior**
 "kubesphere-router-xxx" config can be modified successfully.

And, where is the "kubesphere-router-xxx" default templates?

**Comment by gzdreamfly** [comment]
bug too much

**Comment by RolandMa1986** [comment]
This is a work-as-designed behavior. anyone should not change a resource created by the Helm.
