### ISSUE TITLE
install demo app bookinfo ，bookinfo app can not run 

### ISSUE THREAD

**Issue by zhuyaguang** [kubesphere/kubesphere#4541]
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/8857976/145971007-24c8edf4-6f4f-4dcc-a08f-5cac76fae341.png)

![image](https://user-images.githubusercontent.com/8857976/145971146-890e49e5-b873-4442-bfb8-a50deaa65042.png)

i change the details svc type from ClusterIP to NodePort 

so i can not visit {my-host-ip}: 32536

![image](https://user-images.githubusercontent.com/8857976/145971450-535d6b92-019a-42e5-8983-2d69633fc82d.png)

i looks like the details app can not run 
**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

 just run demo app  and visit it across NodePort

**Expected behavior**

**Comment by RolandMa1986** [comment]
@zhuyaguang **Details** is not a web UI. it's a restful service. The error shows that you are requesting an invalid URL.
Please check our [document ](https://kubesphere.com.cn/docs/quick-start/deploy-bookinfo-to-k8s/) about how to use the app.
The Bookinfo's source code can be found at https://github.com/istio/istio/tree/master/samples/bookinfo
/closes
