### ISSUE TITLE
Failed to deploy Redis-exporter

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4542]
**Describe the Bug**
Failed to deploy the redis-exporter application in the application store

![image](https://user-images.githubusercontent.com/88183150/146114098-2530ba94-c3a6-406a-a12b-2da679d1ab87.png)

**Versions Used**
KubeSphere: v3.2.1-rc.3
Kubernetes: v1.21.5

/kind bug
/@kubesphere/sig-kubesphere
/priority high

**Comment by chaunceyjiang** [comment]
hi, i can't repeat this issue in my environment,
![image](https://user-images.githubusercontent.com/17962021/147211709-dd1795ff-98b5-464e-992e-d4753b57658f.png)

KubeSphere: v3.2.1
Kubernetes: v1.21.5

**Comment by jioce** [comment]
Edited app settings when creating，Set redis password

![image](https://user-images.githubusercontent.com/88183150/147308995-0e784678-9285-41d3-a830-96523e88408b.png)

**Comment by chaunceyjiang** [comment]
![image](https://user-images.githubusercontent.com/17962021/147331668-24eaa51e-57fb-482d-ae6a-d2d79bfb34e1.png)
![image](https://user-images.githubusercontent.com/17962021/147331501-a8fa8cc9-c249-487d-8e19-cea61d1ac890.png)

**Comment by chaunceyjiang** [comment]
If your redis password is `123456`,you must set   `redisPassword: "\"123456\""`

**Comment by jioce** [comment]
Yes, the problem is solved
