### ISSUE TITLE
how to close cluster gateway, when i operate is get an error?

### ISSUE THREAD

**Issue by xwb-spec** [kubesphere/kubesphere#4543]
I1215 16:12:01.159371       1 apiserver.go:599] 10.10.10.26 - "DELETE /kapis/resources.kubesphere.io/v1alpha2/router HTTP/1.1" 405 23 0ms
I1215 16:12:02.400065       1 apiserver.go:599] 10.10.10.26 - "DELETE /kapis/resources.kubesphere.io/v1alpha2/router HTTP/1.1" 405 23 0ms
I1215 16:12:03.129882       1 apiserver.go:599] 10.10.10.26 - "DELETE /kapis/resources.kubesphere.io/v1alpha2/router HTTP/1.1" 405 23 0ms

I1215 16:22:08.933073       1 apiserver.go:599] 10.10.10.26 - "DELETE /kapis/resources.kubesphere.io/v1alpha2/router HTTP/1.1" 405 23 0ms

![image](https://user-images.githubusercontent.com/13009409/146152869-df0d2ec2-d144-4b43-aabc-8960806d0f1b.png)

when i click close cluster gateway, the error occurred, 

ks version: 3.2.0

**Comment by RolandMa1986** [comment]
@gzdreamfly Please follow our template. let's know how to reproduce this issue.
