### ISSUE TITLE
can not login ks

### ISSUE THREAD

**Issue by eternalsilencer** [kubesphere/kubesphere#4547]
i check dns，all fine ,but still can not login ks
![image](https://user-images.githubusercontent.com/51810383/146302646-766a40a3-bbdd-468d-95ec-e0e59cddac6e.png)

![image](https://user-images.githubusercontent.com/51810383/146302581-3d74d830-fb83-411c-8cc7-035aefc9b5da.png)

**Comment by RolandMa1986** [comment]
/duplicate
https://github.com/kubesphere/kubesphere/issues/4520
@eternalsilencer please use the other thread.THX
