### ISSUE TITLE
Gateway deployment failure due to K8s v1.22+ api removal

### ISSUE THREAD

**Issue by zryfish** [kubesphere/kubesphere#4548]
**Describe the Bug**
In Kubernetes v1.22, there are some API groups completely removed, https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes. After KubeSphere v3.2.0 release, we found there are still some compatibility issues left. In this article, https://kubesphere.com.cn/forum/d/6322-kubesphere, Gateway deployment still use `v1beta1/Ingress`, need to migrate to new API group `networking.k8s.io/v1`.

**Versions Used**
KubeSphere: v3.2.0
Kubernetes:  v1.22.1

**How To Reproduce**
1.  Enable gateway for a project.
2. Check the error log of the gateway

**Expected behavior**

/kind bug

**Comment by chaunceyjiang** [comment]
Hi,i will fix this issue

**Comment by RolandMa1986** [comment]
Same as https://github.com/kubesphere/kubesphere/issues/4486
