### ISSUE TITLE
Project Gateway issues

### ISSUE THREAD

**Issue by rockpanda** [kubesphere/kubesphere#4550]
KubeSphere version : v3.2.0
description：
After you enable the project gateway in project A, the cluster administrator opens the cluster gateway again, and after project A closes the project gateway, you cannot create a new project gateway
<img width="1284" alt="iShot2021-12-16 19 54 06" src="https://user-images.githubusercontent.com/42989547/146367148-59438ef2-65c9-489a-b3ab-5a4181c45071.png">

**Comment by RolandMa1986** [comment]
@rockpanda  This is work as designed. Users should either use a Project Gateway or Cluster gateway. But can use them together.

**Comment by rockpanda** [comment]
After the project administrator closes the gateway, he can only force the use of the cluster gateway, and cannot create a new one, which feels unreasonable

**Comment by rockpanda** [comment]
I understand that only one of the two gateways can be used at the same time, but when the project gateway is closed by mistake, it can only be forced to use the cluster gateway, and the project gateway cannot be reopened, which is not very friendly. So at this time, if you want to restore the project gateway, you need to close the cluster gateway, so what should the people who are using the cluster gateway do?

**Comment by rockpanda** [comment]
I understand that only one of the two gateways can be used at the same time, but when the project gateway is closed by mistake, it can only be forced to use the cluster gateway, and the project gateway cannot be reopened, which is not very friendly. So at this time, if you want to restore the project gateway, you need to close the cluster gateway, so what should the people who are using the cluster gateway do?

**Comment by zryfish** [comment]
That's actually about a legacy problem. If there are both cluster gateway and project gateway enabled, some wired issues will emerge. Because there are two ingress controllers trying to modify the same ingress object, which will cause inconsistencies. Sometimes you'll find the address of the ingress flashing from one to the other. From a technical perspective, we don't have a perfect solution now, so we are trying to encourage people to only use one at a time.

**Comment by rockpanda** [comment]
Thank you for your answers and look forward to the perfect solution in the future
