### ISSUE TITLE
projetc request hang on

### ISSUE THREAD

**Issue by github-zsw** [kubesphere/kubesphere#4552]
OS 
VM，Centos7.5，8C/16G

kubectl version 

Client Version: version.Info{Major:“1”, Minor:“20”, GitVersion:“v1.20.4”, GitCommit:“e87da0bd6e03ec3fea7933c4b5263d151aafd07c”, GitTreeState:“clean”, BuildDate:“2021-02-18T16:12:00Z”, GoVersion:“go1.15.8”, Compiler:“gc”, Platform:“linux/amd64”}

Server Version: version.Info{Major:“1”, Minor:“20”, GitVersion:“v1.20.4”, GitCommit:“e87da0bd6e03ec3fea7933c4b5263d151aafd07c”, GitTreeState:“clean”, BuildDate:“2021-02-18T16:03:00Z”, GoVersion:“go1.15.8”, Compiler:“gc”, Platform:“linux/amd64”}

container runtime

Client: Docker Engine - Community
Version: 20.10.11
API version: 1.41
Go version: go1.16.9
Git commit: dea9396
Built: Thu Nov 18 00:38:53 2021
OS/Arch: linux/amd64
Context: default
Experimental: true
Server: Docker Engine - Community
Engine:
Version: 20.10.11
API version: 1.41 (minimum version 1.12)
Go version: go1.16.9
Git commit: 847da18
Built: Thu Nov 18 00:37:17 2021
OS/Arch: linux/amd64
Experimental: false
containerd:
Version: 1.4.12
GitCommit: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
runc:
Version: 1.0.2
GitCommit: v1.0.2-0-g52b36a2
docker-init:
Version: 0.19.0
GitCommit: de40ad0

KubeSphere version v3.1.1。

projetc request hang on
![image](https://user-images.githubusercontent.com/27722136/146512035-f5677414-2d4e-4999-b462-50da3f40a701.png)

**Comment by zryfish** [comment]
504 means bad gateway, usually happens when upstream service failed. Please check ks-apiserver ks-controller-manager logs, and search forum(https://kubesphere.com.cn/forum) for help.
