### ISSUE TITLE
Support searching the k8s auditing log.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#4554]
**What's it about?**
Support searching the k8s auditing log when we have enable the auditing.

/area logging

/kind feature-request

**Comment by benjaminhuo** [comment]
K8s audit log searching is already supported.
Turning K8s audit log on needs some settings of k8s API server, and it will slow down the K8s apiserver a little bit, so it's not enabled by default.

**Comment by VioZhang** [comment]
![image](https://user-images.githubusercontent.com/41519383/157841130-af31d00d-d5ce-47cf-96c2-edf39ed65e2d.png)

**Comment by jioce** [comment]
issue is fixed 
![image](https://user-images.githubusercontent.com/88183150/170229377-5481275f-a1d1-44b1-ad15-9abbddb8d9cf.png)

version used
nightly-20220524

**Comment by wenxin-01** [comment]
![image](https://user-images.githubusercontent.com/68640256/170626344-9342647e-5fae-4a99-8b55-c20ffe767d70.png)
