### ISSUE TITLE
Error analysis of CI/CD in kubesphere version 3.2.0

### ISSUE THREAD

**Issue by zhaowwwjian** [kubesphere/kubesphere#4555]
When we use the page to complete the deployment, the yaml file shows:
![image](https://user-images.githubusercontent.com/24293009/146723024-a721b4f2-703a-4930-a2a5-3474d7afa460.png)
creationTimestamp:null is added by kubesphere.
But when I use this yml to update the CD, there is a code parsing Error.
![image](https://user-images.githubusercontent.com/24293009/146723092-68032fa1-e292-4782-8996-c811d37ac4c3.png)

When I delete the content in the red box, the deployment is successful.

The yml in the project cannot be deployed through the yml of CI/CD because kubesphere automatically adds the displayed creationTimestamp:null.

Important: This is the yml viewed on the page after deploying the kubesphere webpage, not a custom template, so I think this is a bug.

**Comment by showjason** [comment]
I don't think this is a bug, because KS just send a request to kubernetes to get the information of specified deployment, all of the data in yaml is the response of kubernetes. You can reproduce this case by excuting CLI in kubernetes.

**Comment by JohnNiang** [comment]
`KubernetesDeploy` plugin in `ks-jenkins` has been deprecated, especially in `Kubernetes 1.19` or later version. Please consider an alternative plan to deploy Kubernetes resources.

Refer to
- https://kubesphere.io/docs/devops-user-guide/how-to-use/create-a-pipeline-using-graphical-editing-panel/#stage-6-deploy-to-development
- https://github.com/kubesphere/devops-maven-sample/blob/d036579b139010e02716516281a7e742c4eafc1c/Jenkinsfile-online#L107-L116
