### ISSUE TITLE
how to upgrade from version 3.1.1 to 3.2.1

### ISSUE THREAD

**Issue by hurricane1988** [kubesphere/kubesphere#4556]
**What's it about?**

**What's the reason why we need it?**

I believe this is an important feature for Kubesphere. There're a few use cases:

* case one
* case two
* ...

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

**Comment by zryfish** [comment]
Please go through the documentation from our website https://kubesphere.io

/close
