### ISSUE TITLE
How to update image of the ks-apiserver in a running cluster

### ISSUE THREAD

**Issue by hurricane1988** [kubesphere/kubesphere#4557]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**General remarks**

> Please delete this section including header before submitting
>
> This form is to report installation issues. For general usage questions you can refer to [KubeSphere Documentation](https://kubesphere.io/docs) or join our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE)

**What's your question**
I hava a running kubesphere cluster with version of 3.1.1.
It has been auto rollback the image when I update the image of ks-apiserver.
**[remark]**
I just replace the image not update the whole cluster.

**Environment: OS & Hardware Information**

> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).

**Error logs or message (Attach logs or screenshot)**

**Installer Version**

> e.g. v2.1.0, v2.1.1, v3.0.0

**Comment by wenchajun** [comment]
Please see https://kubesphere.io/docs/upgrade/ . If you update ks-apiserver alone you may get an error.

**Comment by hurricane1988** [comment]
> Thanks, but how to update ks-apiserver image alone?
