### ISSUE TITLE
是不是要安装gitlab就必须使用vnas，不论是all-in-one，还是多节点部署？

### ISSUE THREAD

**Issue by liaoyinfeng** [kubesphere/kubesphere#456]

**Comment by FeynmanZhou** [comment]
@liaoyinfeng 目前是这样，安装 gitlab用 CSI 对接块存储会有块存储挂盘权限问题，正在修复中。

**Comment by blueftss** [comment]
可以不用vnas，allinone安装用本地盘也没有问题。

**Comment by Remember2015** [comment]
> 可以不用vnas，allinone安装用本地盘也没有问题。

问题是 all in one 不可靠额
