### ISSUE TITLE
Spell mistake

### ISSUE THREAD

**Issue by gaffeyQiu** [kubesphere/kubesphere#4568]
https://github.com/kubesphere/kubesphere/blob/e1df8bc5bbca133015bc345894b0764b5a0759c5/pkg/controller/cluster/cluster_controller.go#L159
spell mistake  on `hostClusterNmae string`

**Comment by FeynmanZhou** [comment]
> https://github.com/kubesphere/kubesphere/blob/e1df8bc5bbca133015bc345894b0764b5a0759c5/pkg/controller/cluster/cluster_controller.go#L159
> 
> 
> spell mistake on `hostClusterNmae string`

Thanks for pointing out this issue, it looks like a typo. Are you interested in helping us to fix it?

**Comment by songf0011** [comment]
> > https://github.com/kubesphere/kubesphere/blob/e1df8bc5bbca133015bc345894b0764b5a0759c5/pkg/controller/cluster/cluster_controller.go#L159
> > 
> > spell mistake on `hostClusterNmae string`
> 
> Thanks for pointing out this issue, it looks like a typo. Are you interested in helping us to fix it?

PTAL

**Comment by FeynmanZhou** [comment]
> > > https://github.com/kubesphere/kubesphere/blob/e1df8bc5bbca133015bc345894b0764b5a0759c5/pkg/controller/cluster/cluster_controller.go#L159
> > > 
> > > spell mistake on `hostClusterNmae string`
> > 
> > 
> > Thanks for pointing out this issue, it looks like a typo. Are you interested in helping us to fix it?
> 
> Can I have a try？This is my first PR. PTAL

Great, thanks for your PR!
