### ISSUE TITLE
Add a function to login to the edge host in the kubesphere edge node interface

### ISSUE THREAD

**Issue by lynxcat** [kubesphere/kubesphere#4569]
**What's it about?**

Add a function to log in to the edge host in the kubesphere edge node interface

**What's the reason why we need it?**

This function can make it easier for us to manage the edge host, such as
* Download Image before updating edge application
* Update edgecore or docker at the edge
* Modify the edge host configuration
* ...

** Solution **
- Option One：

> - 1.Add a ssh-client to this image [kubectl](https://github.com/kubesphere/kubectl)
> - 2.Use edgemesh's ssh proxy tunnel to forward traffic to the edge
- Option Two：
> - 1.Run a container on the edge to mount the root directory of the host into the container, and then use chroot to manage the host
> - 2.Use kubectl exec to connect to the container of the corresponding edge node

The Option One is relatively simple to implement.We only need to update the kubeedge version, then turn on edgemesh, and make a few changes to the kubesphere front-end code.
like this:
![1fdb3543285ff5732fed38c5f86ba53](https://user-images.githubusercontent.com/2222701/147314230-25f00378-6db6-4008-b395-49dccb7087b1.png)

The Option Two  will not need to change the code but will occupy more resources on the edge, and the security will be worse. Because kubectl exec has no security mechanism, but ssh and edgemesh do some security measures

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/area edge

/kind feature-request

**Comment by zhu733756** [comment]
It seems that option One will rely on the kubeedge edgemesh, option two can save one container resource for edge measurement, and more safety?

**Comment by zryfish** [comment]
I found an article addressing this issue https://alexei-led.github.io/post/k8s_node_shell/, I think it'll help a lot. IMO, the second option is more Kuberenetes and general could be used on any node of the cluster not only the Kubeedge node. 

Also, quote from the article above
> But this approach still requires from you to manage access to the bastion servers and protect SSH keys. IMHO, managing supporting SSH infrastructure, is a high price to pay.

**Comment by lynxcat** [comment]
> I found an article addressing this issue https://alexei-led.github.io/post/k8s_node_shell/, I think it'll help a lot. IMO, the second option is more Kuberenetes and general could be used on any node of the cluster not only the Kubeedge node.
> 
> Also, quote from the article above
> 
> > But this approach still requires from you to manage access to the bastion servers and protect SSH keys. IMHO, managing supporting SSH infrastructure, is a high price to pay.

In k8s clusters, we usually do not need this function because the network between nodes is unobstructed。I think this function is only used to manage edge nodes

**Comment by zryfish** [comment]
With shell access to the node on UI, I think it's helpful if users just want to run some commands, they don't need to login to the node, it's more convenient. Why do we only implement this for edge nodes if we can do this for all nodes in a general way? Also, I agree with the article above, it requires more effort to support SSH infrastructure and protect keys.

**Comment by benjaminhuo** [comment]
Sounds like an enhancement to the existing node mgmt if we could limit this to admin users.

**Comment by zhu733756** [comment]
If the second solution is integrated, we can set a timeout period. If the timeout period is exceeded, the edge container will be deleted automatically to ensure security. And you don't have to rely on Edgemesh.

**Comment by lynxcat** [comment]
If you consider managing all nodes on the UI, I agree that this method in the article will be better. Can I add an interface to api-server to implement this feature

**Comment by zhu733756** [comment]
> If you consider managing all nodes on the UI, I agree that this method in the article will be better. Can I add an interface to api-server to implement this feature

Welcome~

**Comment by lynxcat** [comment]
I implemented this function using the second method. The results are as follows. Please give me some suggestions.
I will submit a PR later.
![c8b6e652aeeac2a4027da319c026a68](https://user-images.githubusercontent.com/2222701/147526411-2979c636-2cc5-49a5-8232-3c29d807598d.png)
Exit shell to automatically clean up pod
![fafa5437c861b12aee9347c714e93e3](https://user-images.githubusercontent.com/2222701/147526615-920db169-1816-4e9b-9b13-f0ce5a45f2b3.png)

**Comment by benjaminhuo** [comment]
That's looks great.
There is a SIG meeting this Thursday afternoon at 3:30 pm, it'll be great if you can demo this and elaborate your PR on this meeting!

**Comment by zhu733756** [comment]
I think this function will include the sections of console/kubesphere/ks-installer.  Can we add a proposal in kubesphere/docs/propsals or more clear docs here in this issue.  What do you think? @lynxcat

**Comment by zhu733756** [comment]
> I think this function will include the sections of console/kubesphere/ks-installer or kubectl images. Can we add a proposal in kubesphere/docs/propsals or more clear docs here in this issue. What do you think? @lynxcat

**Comment by lynxcat** [comment]
Thanks, I added a [proposal](https://github.com/lynxcat/kubesphere/blob/master/docs/proposal/shell-access-to-node-proposal.md) about this issue.

**Comment by wenxin-01** [comment]
issue fixed in `v3.3.0-rc.0`. Now we can login all node in ks-console.
![image](https://user-images.githubusercontent.com/68640256/170223383-54cecda3-18f3-4b47-bac9-3fd88e22e38f.png)
