### ISSUE TITLE
2.0有离线安装版吗，好头疼啊，按文档装了一天没装起来，到处报错

### ISSUE THREAD

**Issue by godkillerwy** [kubesphere/kubesphere#457]
Wednesday 29 May 2019  21:20:12 +0800 (0:00:00.043)       0:00:13.127 ********* 
fatal: [ks-allinone]: FAILED! => {"changed": false, "cmd": "apt-get update", "msg": "E: The repository 'http://apt.byted.org/private stretch-private Release' does no longer have a Release file.\nW: GPG error: http://mirrors.ustc.edu.cn/kubernetes/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A030B21BA07F4FB\nW: The repository 'http://mirrors.ustc.edu.cn/kubernetes/apt kubernetes-xenial InRelease' is not signed.", "rc": 100, "stderr": "E: The repository 'http://apt.byted.org/private stretch-private Release' does no longer have a Release file.\nW: GPG error: http://mirrors.ustc.edu.cn/kubernetes/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A030B21BA07F4FB\nW: The repository 'http://mirrors.ustc.edu.cn/kubernetes/apt kubernetes-xenial InRelease' is not signed.\n", "stderr_lines": ["E: The repository 'http://apt.byted.org/private stretch-private Release' does no longer have a Release file.", "W: GPG error: http://mirrors.ustc.edu.cn/kubernetes/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6A030B21BA07F4FB", "W: The repository 'http://mirrors.ustc.edu.cn/kubernetes/apt kubernetes-xenial InRelease' is not signed."], "stdout": "Ign:1 http://apt.byted.org/private stretch-private InRelease\nErr:2 http://apt.byted.org/private stretch-private Release\n  404  Not Found\nGet:3 http://mirrors.ustc.edu.cn/kubernetes/apt kubernetes-xenial InRelease [8993 B]\nIgn:3 http://mirrors.ustc.edu.cn/kubernetes/apt kubernetes-xenial InRelease\nHit:4 https://download.docker.com/linux/debian stretch InRelease\nIgn:5 http://mirrors.163.com/debian stretch InRelease\nHit:6 http://mirrors.163.com/debian stretch-updates InRelease\nHit:7 http://mirrors.163.com/debian stretch-backports InRelease\nHit:8 http://mirrors.163.com/debian-security stretch/updates InRelease\nHit:9 http://mirrors.163.com/debian stretch Release\nReading package lists...\n", "stdout_lines": ["Ign:1 http://apt.byted.org/private stretch-private InRelease", "Err:2 http://apt.byted.org/private stretch-private Release", "  404  Not Found", "Get:3 http://mirrors.ustc.edu.cn/kubernetes/apt kubernetes-xenial InRelease [8993 B]", "Ign:3 http://mirrors.ustc.edu.cn/kubernetes/apt kubernetes-xenial InRelease", "Hit:4 https://download.docker.com/linux/debian stretch InRelease", "Ign:5 http://mirrors.163.com/debian stretch InRelease", "Hit:6 http://mirrors.163.com/debian stretch-updates InRelease", "Hit:7 http://mirrors.163.com/debian stretch-backports InRelease", "Hit:8 http://mirrors.163.com/debian-security stretch/updates InRelease", "Hit:9 http://mirrors.163.com/debian stretch Release", "Reading package lists..."]}

**Comment by FeynmanZhou** [comment]
@godkillerwy 用的什么配置的机器安装的呢？离线安装包正在最后的测试阶段

**Comment by pixiake** [comment]
这个看起来是apt源的配置问题

**Comment by FeynmanZhou** [comment]
@godkillerwy  离线安装包已经发布了，可参考 [All-in-One](https://docs.kubesphere.io/advanced-v2.0/zh-CN/installation/all-in-one/) 或 [Multi-node](https://docs.kubesphere.io/advanced-v2.0/zh-CN/installation/multi-node/) 来下载安装。
