### ISSUE TITLE
Integrate OpenELB in KubeSphere for exposing the LoadBalancer type of service

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#4574]
**What's it about?**

As we see a lot of users are puzzled with the LoadBalancer type of service, typically, most of them lack LoadBalancer plugins. It is not convenient for users to expose the LoadBalancer type of service outside the Kubernetes cluster. 

[OpenELB](https://openelb.github.io/) is an open-source load balancer implementation designed for exposing the LoadBalancer type of Kubernetes services in on-premises environments, it can help KubeSphere users to easily resolve this issue.

My expectation:

1. Make OpenELB work like Cloud Controller Manager, it can automatically assign EIP to the K8s services when switching to `LoadBalancer`.
2. When users choose OpenELB, it will automatically assign EIP to the K8s services/KubeSphere gateway and configure the annotations, users don't need to install and configure it manually. 

![image](https://user-images.githubusercontent.com/40452856/147432614-fbbc93e3-5321-4f2b-a11d-0538dbfd540e.png)

**What's the reason why we need it?**

I believe this is an important feature for Kubesphere. As we mentioned above, most of the users lack LoadBalancer plugins, they are not familiar with the service exposure mechanism. The built-in OpenELB option will be much helpful and easy to use, which makes users have the same experience with the public cloud when they choose the `LoadBalancer` type of services.

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request
/area networking

**Comment by FeynmanZhou** [comment]
I assume implementing this feature requires two prerequisites:
1. OpenELB works like Kubernetes Cloud Controller Manager, such as support assign EIP automatically. See https://github.com/openelb/openelb/issues/231
2. Integrate OpenELB to KubeKey as an addon

**Comment by FeynmanZhou** [comment]
Hi @harrisonliu5 @VioZhang ,

Is this feature need design support from @XiaohuiSept ? The backend has been supported by @chaunceyjiang, we are integrating OpenELB to KubeSphere and installer.

**Comment by weili520** [comment]
Hi @FeynmanZhou, what are the annotations that users can choose from?

![截屏2022-03-14 13 51 31](https://user-images.githubusercontent.com/33231138/158114247-5362354a-05f8-4fc7-b505-f57df88d255b.png)

an example I found in the code:
![截屏2022-03-14 13 58 08](https://user-images.githubusercontent.com/33231138/158114231-6aa75eb0-415a-4745-819f-dd113ca836a1.png)

**Comment by FeynmanZhou** [comment]
> 

There are two options for users to choose from. I think the OpenELB annotations with KubeSphere should be filled out align with [Layer 2 doc](https://openelb.github.io/docs/getting-started/usage/use-openelb-in-layer-2-mode/#step-5-create-a-service) and [BGP doc](https://openelb.github.io/docs/getting-started/usage/use-openelb-in-bgp-mode/#step-6-create-a-service):

- When users choose Layer 2:
![image](https://user-images.githubusercontent.com/40452856/158114902-239b52d0-d984-4794-83b3-8df075ad6845.png)

- When users choose BGP:
![image](https://user-images.githubusercontent.com/40452856/158115189-4759beb6-cd77-4aef-ae7e-ca50ff5a02fc.png)

@zheng1 @chaunceyjiang Do you agree?

**Comment by weili520** [comment]
> 

Ok.
![截屏2022-03-14 14 23 10](https://user-images.githubusercontent.com/33231138/158116802-53c96d2d-9e7a-4af8-bf6f-277babb000a3.png)

**Comment by zheng1** [comment]
@weili520 Can you post which specific file it is? That way we can submit our own PR to add it

**Comment by weili520** [comment]
> @weili520 Can you post which specific file it is? That way we can submit our own PR to add it

The file path is `console/src/pages/projects/components/Modals/GatewaySetting/contants.js`.

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-nightly20220525`
