### ISSUE TITLE
Add wizard-style user guidance in the web console for newbies

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#4576]
**What's it about?**

As there are a lot of KubeSphere newbies who don't aware that it is necessary to create their own workspace and project before using it, even some newbies don't aware of the pluggable components before deep dive into the official documentation.

See the typical examples published by users:

- https://www.bilibili.com/video/BV1cL4y167GV?p=5
- https://mp.weixin.qq.com/s/9qrWHoYEcQxUjGe8SzH_og

I propose to design and provide wizard-style user guidance in the web console for newbies, helping them to get started with KubeSphere and its fundamental design & concepts.

**What's the reason why we need it?**

I believe this is an important feature for Kubesphere. There're a few use cases:

* How to create your own workspace and project 
* How to enable the pluggable component installation
* ...

It would be better to design guidances or add the related doc links for these cases.

Please leave your comments below if there's anyone who agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request
/area console

**Comment by VioZhang** [comment]
https://github.com/kubesphere/kubesphere/issues/4738
