### ISSUE TITLE
Feat: "resources.kubesphere.io" Kapis group refactor

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/kubesphere#4580]
**What's it about?**

Refactor the "resources.kubesphere.io" Kapis group with a generalized implementation. And obsolete this APIs Group in the feature. 
In the feature, all the CRDs(or CRDs with a kapis server label) can be register to the ks-apiserver automatically, as same as the Kubernetes APIs(including the URI), but still can provider the  frond-end friendly API style. 

**What's the reason why we need it?**

"resources.kubesphere.io" Kapis group is a common List/Get APIs for the Custom Resources, which provided a powerful API with filter, sort and pagging abilities than the origin Kubernetes APIs. However, a "resources/v1alpha3.Interface" need to be implement for the CRDs which need to be regiested to the API group.  If we digger into the Interface implementation, we can found that more than 60% code are duplicated, Many CRDs don't need implictent the **Filter**, **Comparer** for itself. 

Another disadvantage of this group is that we need an other GRV for this Group, which means we had to grant the permission seperatetlly. If we can register the API GRV as same as the CRD definenation, we can save a lot of work during grant  permission. 

I believe this is an important feature for Kubesphere. There're a few use cases:

* case one
* case two
* ...

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**
/area api
/area apiserver

/kind feature-request

**Comment by VioZhang** [comment]
finished
