### ISSUE TITLE
When I search docker image with private docker server, The api return 404

### ISSUE THREAD

**Issue by txzqy123** [kubesphere/kubesphere#4583]
## General remarks

**Describe the Bug**
![image](https://user-images.githubusercontent.com/13378979/147733355-5165018b-a714-4476-84a7-9f683f12bbad.png)
When I search docker image with private server, The api return 404

the api is 
http://xxxxxxx/kapis/resources.kubesphere.io/v1alpha3/namespaces/project-lxsh/imageconfig?image=registry.cn-hangzhou.aliyuncs.com%2Fxxxxxx%2Flxshlll&secret=aliyun-docker

**Versions Used**
KubeSphere: 3.2.0

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.9 / 3 masters:  4cpu/8g; 2 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**Comment by FeynmanZhou** [comment]
It looks abnormal. Hi team @kubesphere/sig-console ,  can you please help to verify if it is as our expectation?

**Comment by zryfish** [comment]
Wrong image format,  `namespace/imageName`, please Google it first

**Comment by txzqy123** [comment]
> Wrong image format, `namespace/imageName:tag`, please Google it first

I have resovle it. But it's better not show me 404. It makes a wrong guide
