### ISSUE TITLE
The published Apps cannot be deleted

### ISSUE THREAD

**Issue by terryzwt** [kubesphere/kubesphere#4585]
**Describe the Bug**
通过应用模版发布的自定义应用无法删除。

**Versions Used**
KubeSphere:3.2.0
Kubernetes: 1.21.5

**Environment**
![image](https://user-images.githubusercontent.com/1829399/147748920-df6fccfe-3476-4e90-ab1a-9d69c7698f9f.png)

**How To Reproduce**
1. git clone https://github.com/bitnami/charts
2. cd bitnami
3. tar czvf drupal.tgz drupal
4. from "应用模版" 入口，上传 drupal.tgz 
5. 提交审核
6. 审核通过
7. 上架 => 通过这步操作后，在应用市场中可以看见
8. 安装应用，发现应用无法安装，尝试删除
相关截图如下：
![image](https://user-images.githubusercontent.com/1829399/147748746-9a819722-3084-4796-886a-ffa96b88c5dd.png)
![image](https://user-images.githubusercontent.com/1829399/147748759-5f809e30-24a3-47f2-bc46-e34bc173c1a4.png)
![image](https://user-images.githubusercontent.com/1829399/147748769-22825a74-6c61-43d3-a544-14cde05d81e7.png)

**Expected behavior**
可以删除自定义的应用模版

**Comment by FeynmanZhou** [comment]
IMO, I think you need to suspend an application before removing it. See [Application Lifecycle Management](https://kubesphere.io/zh/docs/application-store/app-lifecycle-management/#%E6%AD%A5%E9%AA%A4%E5%85%AB%E4%B8%8B%E6%9E%B6%E5%BA%94%E7%94%A8%E7%A8%8B%E5%BA%8F) for details.
