### ISSUE TITLE
kubesphere.io/api and kubesphere.io/client-go download error

### ISSUE THREAD

**Issue by rmzf9192** [kubesphere/kubesphere#4590]
I not get kubesphere.io/api code 

error msg:
  SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

**Comment by RolandMa1986** [comment]
/kind support
@rmzf9192 It seems like a go proxy issue, please clean your workspace and try again.
