### ISSUE TITLE
kubesphere-3.2.1 can't login with admin when integrate into OIDC

### ISSUE THREAD

**Issue by hurricane1988** [kubesphere/kubesphere#4593]
**Describe the Bug**
**Version：** kubesphere 3.2.1
**component：** OIDC
**bug:** Can‘t login with admin

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by wansir** [comment]
Could you provide more information, such as logs and custom configuration?

**Comment by hurricane1988** [comment]
@wansir the custom OIDC configuration and logs as below：
**【kubesphere.yaml】**
alerting:
    prometheusEndpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
    thanosRuleResourceLabels: thanosruler=thanos-ruler,role=thanos-alerting-rules
    thanosRulerEndpoint: http://thanos-ruler-operated.kubesphere-monitoring-system.svc:10902
auditing:
    enable: true
    host: http://elasticsearch-logging-data.kubesphere-logging-system.svc:9200
    indexPrefix: ks-logstash-auditing
    webhookURL: https://kube-auditing-webhook-svc.kubesphere-logging-system.svc:6443/audit/webhook/event
authentication:
    authenticateRateLimiterDuration: 10m0s
    authenticateRateLimiterMaxTries: 10
    jwtSecret: tJ3BLuWNjsEHLF5pjh9dCxh3lsXFnOmM
    kubectlImage: starimagerepo.qm.cn/kubesphere/kubectl:v1.20.0
    loginHistoryRetentionPeriod: 168h
    maximumClockSkew: 10s
    multipleLogin: true
    oauthOptions:
        accessTokenInactivityTimeout: 30m
        accessTokenMaxAge: 1h
        identityProviders:
            - mappingMethod: auto
              name: dev
              provider:
                clientID: xxx
                clientSecret: xxx
                emailKey: email
                endpoint:
                    authStyle: autoDetect
                    authURL: https://auth.dev.cn/auth/realms/cooperation/protocol/openid-connect/auth
                    tokenURL: https://auth.dev.cn/auth/realms/cooperation/protocol/openid-connect/token
                    userInfoURL: https://auth.dev.cn/auth/realms/cooperation/protocol/openid-connect/userinfo
                redirectURL: http://10.112.62.199:30880/oauth/redirect/dev
                scopes:
                    - openid
                    - offline_access
                    - email
              type: OIDCIdentityProvider
【ks-apiserver】logs
pods.monitoring.kubesphere.io is forbidden: User "system:anonymous" cannot list resource "pods" in API group "monitoring.kubesphere.io" in the namespace "kubesphere-system"
