### ISSUE TITLE
can not save  whehook setting

### ISSUE THREAD

**Issue by chj9** [kubesphere/kubesphere#4594]
**Versions Used**
KubeSphere:  3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)
1.21.6

![image](https://user-images.githubusercontent.com/16426260/148173295-9dc79dd2-a0c9-4c08-b8bd-4073b09f722b.png)

**Comment by RolandMa1986** [comment]
/area notification
@kubesphere/sig-observability

**Comment by wanjunlei** [comment]
Please run the following command, then reset the webhook.

```
kubectl get nr global-webhook-receiver
```
