### ISSUE TITLE
hostpath being set to pvc

### ISSUE THREAD

**Issue by phoenixwu0229** [kubesphere/kubesphere#4595]
![image](https://user-images.githubusercontent.com/49689460/148209999-5d07db2c-5b43-42ff-84c5-34448ccd3fb4.png)

![image](https://user-images.githubusercontent.com/49689460/148209981-01524d10-9c65-4de6-bb4f-b63068043ed4.png)

when i create volume with hostpath, in yaml it will be turn to pvc

**Comment by phoenixwu0229** [comment]
both in 3.0.0 and 3.2.0

**Comment by RolandMa1986** [comment]
THis issue should already be fixed in 3.2.1
https://github.com/kubesphere/console/pull/2579

/duplicate
/area console
