### ISSUE TITLE
KubeSphere v3.2.1 集群节点-工作节点数量显示错误

### ISSUE THREAD

**Issue by jingruhou** [kubesphere/kubesphere#4597]
只有5个工作节点，1个主节点；结果上面显示6个工作节点

![image](https://user-images.githubusercontent.com/6825570/148382609-004391b4-c6d7-4da4-b4ac-f934f8c2174e.png)

**Comment by FeynmanZhou** [comment]
Hi @jingruhou , I assume you have configured your control plane node (master) as a master role in your K8s node template. The control plane node (master) can also play the role as the worker.
