### ISSUE TITLE
Can the administrator account of the kubesphere login interface be randomly generated

### ISSUE THREAD

**Issue by liulangwa** [kubesphere/kubesphere#4598]
**Describe the Bug**

Can the administrator account of the kubesphere login interface be randomly generated? This default password is a security risk. It is recommended to generate a random password during installation, which can be seen in ks-install

kubesphere登陆界面管理员账号能随机生成么，这个默认密码是个安全隐患，建议安装时候生成一个随机密码，可以在ks-install看到

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by wansir** [comment]
The default password of the admin is defined in https://github.com/kubesphere/ks-installer/blob/release-3.2/roles/ks-core/ks-core/files/ks-core/templates/account.yaml#L12.

**Comment by LinuxSuRen** [comment]
/retitle Can the administrator account of the kubesphere login interface be randomly generated
/kind support
