### ISSUE TITLE
history and rollout for secrets/configmaps is need 

### ISSUE THREAD

**Issue by lowang-bh** [kubesphere/kubesphere#4606]
**What's it about?**

1.  to record the change history about secrets/configmaps, and the comparation between different versions
2.  support a quick rollout operation with selected version

**What's the reason why we need it?**

I believe this is an important feature for Kubesphere. There're a few use cases:

* case one: admins wants to inspect the change history
* case two: admins wants to rollout in case of fault deploy
* ...

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

**Comment by lxm** [comment]
configmaps and secrets are not versioned in kubernetes.

A similar workaround in spinnaker is to make configmaps versioned manually by add a `-v001` suffix to the configmap. when resource need to be changed the suffix will be added to `-v002`

**Comment by lowang-bh** [comment]
> configmaps and secrets are not versioned in kubernetes.
> 
> A similar workaround in spinnaker is to make configmaps versioned manually by add a `-v001` suffix to the configmap. when resource need to be changed the suffix will be added to `-v002`

yes, this is a solution, maybe. 
We have ever solved this issue by storing the config in db for history query and version comparison
