### ISSUE TITLE
建议增加利用filebeat等工具实现用户应用日志的管理

### ISSUE THREAD

**Issue by blueftss** [kubesphere/kubesphere#461]
建议增加利用filebeat等工具实现用户应用日志的管理

**Comment by benjaminhuo** [comment]
- filebeat 更多的是偏向于日志收集的 agent，并有一些日志格式化的能力，需要部署在应用的 pod 里。
- 可以在应用的 pod 里加入 sidecar 的 container 将 filebeat 收集的日志转而输出到 stdout，或者 filebeat 直接输出收集到的应用日志到 stdout。
- KubeSphere 默认安装了 fluentbit 的 daemonset 来收集各节点容器输出到 stdout 的日志并转发到 es，kafka 或者 fluentd。
- 我们会提升现在 KubeSphere 日志的搜索体验，加入更强大好用的 filter

**Comment by calvinyv** [comment]
already supported in 2.1.0
