### ISSUE TITLE
The deployment of Autoscaling can just incress but can't reduce

### ISSUE THREAD

**Issue by hurricane1988** [kubesphere/kubesphere#4614]
**Describe the Bug**
**The deployment of Autoscaling can just incress but can't reduce**
For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by RolandMa1986** [comment]
/triage needs-information
@hurricane1988 Could you provide more information about your environment information and how to reproduce the issue?

**Comment by hurricane1988** [comment]
@RolandMa1986 The environment as below :
1. OS: Centos7.8 x64
2. Kubesphere: 3.2.1
3. 3Master + 5Worker
4. I tested the HPA use metric RAW of official nginx image, and use wtr to pressure measurement. the trigger value is 20MB, and the min instances is 2, max 4, It could be increased when the raw greater than 20MB, but could not be reduced  when the raw is lesser than 10MB
