### ISSUE TITLE
403 error when entering pvc list page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#4619]
**Describe the Bug**
1 In multi-cluster environment，create a multi-cluster project
2 The user with operator role of the project goes into the pvc list under the project
3 the 403 error occurs

![image](https://user-images.githubusercontent.com/36271543/149468930-b7680df2-7f7b-4503-9a8c-a3cb7712d2ec.png)

**Versions Used**
KubeSphere: v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Comment by jinqinn** [comment]
i got same issue, any idea about this ?
