### ISSUE TITLE
grayscale release not work

### ISSUE THREAD

**Issue by hchenc** [kubesphere/kubesphere#4624]
**Describe the Bug**
when i create ingress through creating a composed apps the grayscale release function works fine which will add <b>nginx.ingress.kubernetes.io/upstream-vhost</b> annotation on ingress resource automatically, but when i create the ingress resource through the routes the grayscale release will not work for lack of <b>nginx.ingress.kubernetes.io/upstream-vhost</b> annotation, i'm not sure that's a bug or for some principle that i don't know.

**Versions Used**
KubeSphere: 3.2.0

**How To Reproduce**
1. create grayscale release
2. create ingress
3. let any deployment version takes over the inbound traffic
4. see the result

**Expected behavior**
pod will take the inbound traffic based on svc policy

**Comment by RolandMa1986** [comment]
/kind bug 
/area console
@kubesphere/sig-console 
@hchenc Thanks! we will fix it in the next coming release.

**Comment by iawia002** [comment]
> but when i create the ingress resource through the routes the grayscale release will not work

You are describing it in a very abstract way, this has nothing to do with how to create ingress. The prerequisite for using grayscale release in KubeSphere is to create a Composed Apps and enable application governance for the Composed Apps. I tested it and it is normal.
