### ISSUE TITLE
The host cluster cannot be removed when I add it as a member cluster.

### ISSUE THREAD

**Issue by 2hangchen** [kubesphere/kubesphere#4625]
**Describe the Bug**
When I mistakenly managed the host cluster itself as a member cluster, I tried to remove it but could not do so.

**Versions Used**
KubeSphere:v3.2.1
Kubernetes:v1.20

**Environment**
How many nodes and their hardware configuration:
Centos 7/3 master ,4 nodes

**How To Reproduce**
1. In the host cluster, click `Add Cluster`, fill in the related information, and select the `Direct Connection` mode
2. Paste the host cluster's own `Kubeconfig` file into the text box
3. Try to remove the newly managed cluster
![image](https://user-images.githubusercontent.com/31329928/149731143-6f4fc690-5b34-47f5-a832-5089b5e4c074.png)
![image](https://user-images.githubusercontent.com/31329928/149731199-19952331-cc6b-4115-8c81-e55c7dc94688.png)
There are no associated action buttons in the red box

**Expected behavior**
I think I cannot add myself as a member cluster,this is unreasonable.

**Comment by RolandMa1986** [comment]
/kind bug
/area multicluster
@kubesphere/sig-multicluster

**Comment by iawia002** [comment]
> I think I cannot add myself as a member cluster,this is unreasonable.

This is weird, we actually have this validation, I can't reproduce this issue:

<img width="373" alt="Screen Shot 2022-01-20 at 10 35 07 AM" src="https://user-images.githubusercontent.com/9134003/150262179-44b2d001-d327-4d12-8932-80d77e0268a4.png">

> There are no associated action buttons in the red box

For now you can delete the dev cluster by executing the following command in the host cluster:

```
kubectl delete cluster dev
```

**Comment by 2hangchen** [comment]
> > I think I cannot add myself as a member cluster,this is unreasonable.
> 
> This is weird, we actually have this validation, I can't reproduce this issue:
> 
> <img alt="Screen Shot 2022-01-20 at 10 35 07 AM" width="373" src="https://user-images.githubusercontent.com/9134003/150262179-44b2d001-d327-4d12-8932-80d77e0268a4.png">
> 
> > There are no associated action buttons in the red box
> 
> For now you can delete the dev cluster by executing the following command in the host cluster:
> 
> ```
> kubectl delete cluster dev
> ```
Maybe because I use haproxy? When I managed self after deploying kubesphere in k8s cluster , `sever` wrote the `vip` .

**Comment by zryfish** [comment]
@iawia002 Maybe we should use the cluster id of each joined cluster instead of the server address.  From this issue, the uuid of the kube-system namespace can be used as cluster id. https://github.com/kubernetes/kubernetes/issues/77487#issuecomment-489786023

**Comment by iawia002** [comment]
> Maybe because I use haproxy? When I managed self after deploying kubesphere in k8s cluster , sever wrote the vip .

It's gonna be tricky, if two kubeconfig files have different API server addresses, it is not easy to tell if it is the same cluster

**Comment by 2hangchen** [comment]
> > Maybe because I use haproxy? When I managed self after deploying kubesphere in k8s cluster , sever wrote the vip .
> 
> It's gonna be tricky, if two kubeconfig files have different API server addresses, it is not easy to tell if it is the same cluster
So why is it in the list of primary clusters and not in the list of member clusters?

**Comment by iawia002** [comment]
> @iawia002 Maybe we should use the cluster id of each joined cluster instead of the server address. From this issue, the uuid of the kube-system namespace can be used as cluster id. [kubernetes/kubernetes#77487 (comment)](https://github.com/kubernetes/kubernetes/issues/77487#issuecomment-489786023)

Yes, this is a way to identify them, I think we can add this validation in v3.3

/milestone v3.3

**Comment by zryfish** [comment]
> Yes, this is a way to identify them, I think we can add this validation in v3.3

Great, I've added it to our project To-Do list.

**Comment by jioce** [comment]
issue is fixed in v3.3.0-rc.0
