### ISSUE TITLE
How to develop kubesphere in arm architecture （Apple M1）？

### ISSUE THREAD

**Issue by yongxingMa** [kubesphere/kubesphere#4628]
**What's it about?**

Hello，everyone！Now I want to participate in the development of kubesphere, but I'm based on ARM architecture. I can't build a kubesphere cluster locally. 
How can I construction of the development environment? 
Welcome give some suggestions, thank you！

**Comment by wansir** [comment]
Usually, we installed the K8s cluster in a remote environment. Use telepresence to connect to remote services, and then you can develop your own feature locally. Please follow this guide https://github.com/kubesphere/community/blob/master/developer-guide/development/quickstart.md.

**Comment by yongxingMa** [comment]
> Usually, we installed the K8s cluster in a remote environment. Use telepresence to connect to remote services, and then you can develop your own feature locally. Please follow this guide https://github.com/kubesphere/community/blob/master/developer-guide/development/quickstart.md.

very nice！！Thank you！
I use telepresence run successfully！

**Comment by yongxingMa** [comment]
![image](https://user-images.githubusercontent.com/31605966/149887366-a2295ecc-efef-4f5c-96db-c02e4a83e0be.png)
