### ISSUE TITLE
Federated projects mysteriously disappear

### ISSUE THREAD

**Issue by 2hangchen** [kubesphere/kubesphere#4635]
**Describe the Bug**
When I create a federated project and do nothing, the project will delete itself.  
It's amazing..

**Versions Used**
KubeSphere:v3.2.1
Kubernetes:v1.20

**Environment**
Centos 7/3 master ,4 nodes

**How To Reproduce**
1.  Create federated project and do nothing, wait a few minutes.
![kubesphere](https://user-images.githubusercontent.com/31329928/150297619-9b3f946d-28c6-40ca-87a3-45c64f77ffd8.gif)

**Comment by iawia002** [comment]
That's weird, I can't reproduce the problem, can you look at the request list of the browser's network panel at that time?

**Comment by hey-law** [comment]
I have the same problem.
Versions Userd:
KubeSphere:v3.2.1
Kubernetes:v1.21.9

**Comment by hey-law** [comment]
> **Describe the Bug** When I create a federated project and do nothing, the project will delete itself. It's amazing..
> 
> **Versions Used** KubeSphere:v3.2.1 Kubernetes:v1.20
> 
> **Environment** Centos 7/3 master ,4 nodes
> 
> **How To Reproduce** Steps to reproduce the behavior:
> 
> 1. Create federated project and do nothing, wait a few minutes.
>    ![kubesphere](https://user-images.githubusercontent.com/31329928/150297619-9b3f946d-28c6-40ca-87a3-45c64f77ffd8.gif)
>          
>            [
>              
>            ](https://user-images.githubusercontent.com/31329928/150297619-9b3f946d-28c6-40ca-87a3-45c64f77ffd8.gif)
>            
>                ![kubesphere](https://user-images.githubusercontent.com/31329928/150297619-9b3f946d-28c6-40ca-87a3-45c64f77ffd8.gif)

Did you solve the bug？
