### ISSUE TITLE
Get kubeconfig file missing users info through KubeSphere platform UI

### ISSUE THREAD

**Issue by seanly** [kubesphere/kubesphere#4639]
**Describe the Bug**
Get kubeconfig file missing users info through KubeSphere platform UI

The following figure
![image](https://user-images.githubusercontent.com/232069/150495023-93c98250-66c2-4371-b428-9b7a5847911b.png)

**Versions Used**
KubeSphere: v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

```bash
rke up # install k8s cluster image: rancher/hyperkube:v1.21.5-rancher1

# install kubesphere
kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.2.1/kubesphere-installer.yaml
kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.2.1/cluster-configuration.yaml
```

component versions: 
![image](https://user-images.githubusercontent.com/232069/150495350-0777e490-91a3-42ea-92f5-381c8cc456c2.png)

**How To Reproduce**
1.  login ks ui
2. get kubeconfig by  ui
![image](https://user-images.githubusercontent.com/232069/150495953-3d880e32-b08a-4a77-bdd4-29f55cf6b151.png)

3. get kubeconfig-admin by kubectl command
![image](https://user-images.githubusercontent.com/232069/150496019-578b2d12-80e7-4db7-b385-9287172882f5.png)

**Expected behavior**

**Comment by JohnNiang** [comment]
Related issue: https://kubesphere.com.cn/forum/d/6370-v321-kubeconfig-usernull/10 (In Chinese)
