### ISSUE TITLE
Using the telepresence agent, the login fails all the time

### ISSUE THREAD

**Issue by yongxingMa** [kubesphere/kubesphere#4641]
**What's it about?**

1、sudo telepresence connect
2、sudo telepresence --namespace kubesphere-system --swap-deployment ks-apiserver --expose 9090 
3、start ks-apiserver success
I0124 17:19:38.386064   55144 apiserver.go:356] Start cache objects
I0124 17:19:46.212284   55144 apiserver.go:562] Finished caching objects
I0124 17:19:46.212341   55144 apiserver.go:278] Start listening on :9090
4、failure when login
![image](https://user-images.githubusercontent.com/31605966/150758116-2ef11e99-2586-4920-8c45-9cc44041a83c.png)
![image](https://user-images.githubusercontent.com/31605966/150758239-106b8aae-b2a9-46b3-9562-7b6f0b814bab.png)

**Comment by FeynmanZhou** [comment]
Hi @kubesphere/sig-multitenancy , could you please help to take a look at this issue?

**Comment by yongxingMa** [comment]
@eynmanZhou  Thank you,The problem has been solved. The kubesphere.yml file is missing parameters.

**Comment by yongxingMa** [comment]
@FeynmanZhou Thank you.
The problem has been solved. The kubesphere.yml file is missing parameters.

**Comment by FeynmanZhou** [comment]
Okay, you can close it if it is resolved by yourself.

**Comment by yongxingMa** [comment]
The "oauthOptions" is not configured, login failure,now is successful.
![image](https://user-images.githubusercontent.com/31605966/150906317-4dc47762-9682-4c70-ab55-916074e3e4d9.png)
