### ISSUE TITLE
资源用量显示异常

### ISSUE THREAD

**Issue by ghost** [kubesphere/kubesphere#4644]
k8s版本是1.20.0,二进制安装，kubesphere版本是v3.2.1。
![image](https://user-images.githubusercontent.com/89144807/150909003-dfad8d57-b42e-4ca7-ba3c-31b0d5dab573.png)
刷新了一下界面变成下面的了。
![image](https://user-images.githubusercontent.com/89144807/150909021-0c9ddced-ba85-4c1f-a1ec-e3d146b9021d.png)
之前装过一下，后来卸载了，采用的二进制的离线包安装的k8s，然后安装的kubesphere。请问是什么问题导致的呢？

**Comment by liangyuanpeng** [comment]
Provide more info for this question, something like how many pod is running or some else.
