### ISSUE TITLE
WebSocket connection recreate unexpected 

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#4648]
**Describe the Bug**

After a period of time, the WebSocket connection will be recreated.

![image](https://user-images.githubusercontent.com/8263040/150943581-36405399-53a4-4545-8ece-3b474d4bbfca.png)

**Versions Used**
KubeSphere: v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Expected behavior**

The WebSocket connection should not be recreated.

**Comment by wenxin-01** [comment]
Now, in `v3.3.0-alpha.2` this connection only request once, but have other issue. https://github.com/kubesphere/kubesphere/issues/4850
