### ISSUE TITLE
can't import  aws  eks cluster

### ISSUE THREAD

**Issue by FlynnMJ** [kubesphere/kubesphere#4649]
getting credentials: exec: executable aws not found It looks like you are trying to use a client-go credential plugin that is not installed.

**Comment by FeynmanZhou** [comment]
> getting credentials: exec: executable aws not found It looks like you are trying to use a client-go credential plugin that is not installed.

Hi, which documents did you follow? could you give more information about this issue?

**Comment by FlynnMJ** [comment]
Sorry, I didn't get your reply in time.  The problem has been solved for now.  It is the token generated by me that has a problem.

**Comment by FeynmanZhou** [comment]
> Sorry, I didn't get your reply in time. The problem has been solved for now. It is the token generated by me that has a problem.

Thanks for your feedback : ) Is everything working fine with KubeSphere on EKS?

**Comment by FlynnMJ** [comment]
> > Sorry, I didn't get your reply in time. The problem has been solved for now. It is the token generated by me that has a problem.
> 
> Thanks for your feedback : ) Is everything working fine with KubeSphere on EKS?

Not at present,  we are still trying to integrate CI/CD, if the result is ok , i will be promoted in the company 。 Thank you for reply  。
