### ISSUE TITLE
建议：能不能提供一套搭建好的环境供社区体验下，目前看安装门槛有点高

### ISSUE THREAD

**Issue by godkillerwy** [kubesphere/kubesphere#465]
**General remarks**

> Please delete this section including header before submitting
> 也可以使用中文
>
> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug(描述下问题)**

For UI issues please also add a screenshot that shows the issue.

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**

**Expected behavior(预期行为)**

**Comment by rayzhou2017** [comment]
体验的话可以安装allinone，那个很简单，不需要配置，只需要保证机器的配置满足最小要求。多节点安装基本都是因为存储的原因显得门槛高。如果需要体验多节点安装可以等几天青云的QKE上线，一键部署。lab环境我们以前也有，新版没有更新，我们考虑一下需不需要提供这种体验环境。
