### ISSUE TITLE
The public cloud serverless kubernetes cluster log collection problem

### ISSUE THREAD

**Issue by JoyWang831** [kubesphere/kubesphere#4652]
Hello, I use public cloud serverless kubernetes clusters(like Aliyun ASK), but it didn't support daemonset, the current log collection scheme cannot implementation requirements.
Is there any solution can fix my problem？

**Comment by FeynmanZhou** [comment]
> Hello, I use public cloud serverless kubernetes clusters(like Aliyun ASK), but it didn't support daemonset, the current log collection scheme cannot implementation requirements. Is there any solution can fix my problem？

Hi team @kubesphere/sig-observability , as I know KubeSphere runs FluentBit as DaemonSet on each node to collect logs. Could you please help to give any suggested workaround?
