### ISSUE TITLE
failed to try resolving symlinks in path "": lstat  no such file or directory

### ISSUE THREAD

**Issue by nickevin** [kubesphere/kubesphere#4653]
**Describe the Bug**
First use kubesphere(https://kubesphere.io/zh/docs/quick-start/minimal-kubesphere-on-k8s/), the issue: 

```
failed to try resolving symlinks in path "/var/log/pods/kubesphere-monitoring-system_node-exporter-9tfrm_d3f1ad6b-5d69-4f2f-a10d-8ee2940a4b9f/node-exporter/10.log": lstat /var/log/pods/kubesphere-monitoring-system_node-exporter-9tfrm_d3f1ad6b-5d69-4f2f-a10d-8ee2940a4b9f/node-exporter/10.log: no such file or directory
```

For UI issues please also add a screenshot that shows the issue.

![](https://s4.ax1x.com/2022/01/29/HphfgJ.png)
[![Hp4P58.md.png](https://s4.ax1x.com/2022/01/29/Hp4P58.md.png)](https://imgtu.com/i/Hp4P58)

**Versions Used**
KubeSphere: v3.2.1
Kubernetes: v1.22.4

**Environment**
For example: macOS 12.2

**Comment by filwu8** [comment]
failed to try resolving symlinks in path "/var/log/pods/kubesphere-monitoring-system_node-exporter-7wj6r_083027d6-8624-4c67-8a2b-bfb700e08098/node-exporter/6.log": lstat /var/log/pods/kubesphere-monitoring-system_node-exporter-7wj6r_083027d6-8624-4c67-8a2b-bfb700e08098/node-exporter/6.log: no such file or directory

**Comment by filwu8** [comment]
failed to try resolving symlinks in path "/var/log/pods/kubesphere-monitoring-system_node-exporter-7wj6r_083027d6-8624-4c67-8a2b-bfb700e08098/node-exporter/8.log": lstat /var/log/pods/kubesphere-monitoring-system_node-exporter-7wj6r_083027d6-8624-4c67-8a2b-bfb700e08098/node-exporter/8.log: no such file or directory

修复方案：

$ cat values.yaml

prometheus-node-exporter:
hostRootFsMount: false

$ helm list
$ helm upgrade --install XXXXXXX prometheus-community/kube-prometheus-stack -f values.yaml

对于那些使用 kube-prometheus-stack 且 prometheus-node-exporter 是依赖项的用户，您需要将此更改添加到 prometheus-node-exporter 值文件而不是 kube-prometheus-stack 值文件中。将启用的值更改为 false：
# Mount the node's root file system (/) at /host/root in the container
hostRootFsMount:
enabled: false
# Defines how new mounts in existing mounts on the node or in the container
# are propagated to the container or node, respectively. Possible values are
# None, HostToContainer, and Bidirectional. If this field is omitted, then
# None is used. More information on:
# https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
mountPropagation: HostToContainer
