### ISSUE TITLE
How to import the existing Helm Release ?

### ISSUE THREAD

**Issue by royeo** [kubesphere/kubesphere#4665]
I have created some Helm Releases in the K8S cluster, how to import the existing Helm Release to kubesphere ?

**Comment by FeynmanZhou** [comment]
You can try to package it into a zip file such as `.tgz` and upload it, see this [doc](https://kubesphere.io/docs/application-store/app-lifecycle-management/#step-2-upload-and-submit-an-application) for an example.

**Comment by royeo** [comment]
> You can try to package it into a zip file such as `.tgz` and upload it to KubeSphere, see this [doc](https://kubesphere.io/docs/application-store/app-lifecycle-management/#step-2-upload-and-submit-an-application) for an example.

I mean I have installed some Helm applications with Helm Install, How do I migrate these Helm applications to Kubesphere in bulk?

**Comment by FeynmanZhou** [comment]
> > You can try to package it into a zip file such as `.tgz` and upload it to KubeSphere, see this [doc](https://kubesphere.io/docs/application-store/app-lifecycle-management/#step-2-upload-and-submit-an-application) for an example.
> 
> I mean I have installed some Helm applications with Helm Install, How do I migrate these Helm applications to Kubesphere in bulk? @FeynmanZhou

IMO, it has not been supported in KubeSphere. But it seems to be a good feature request for listing the installed Helm appss on the App page. I am not sure if there is a workaround for this question.

Hi @kubesphere/sig-apps , could you please help to give any suggestion?

![image](https://user-images.githubusercontent.com/40452856/154214488-9aad2240-f299-414f-baf8-8e89b4d694f4.png)
