### ISSUE TITLE
 The cluster needs to know its cluster name in multi-cluster

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#4672]
**What's it about?**

It is necessary to provide a method that allows the application to easily obtain the name of the cluster in which it is located in multi-cluster mode.

**What's the reason why we need it?**

Now the Cluster CRD is only in the host cluster, the cluster does not know its own cluster name. This is very unfriendly to applications running on clusters. For example, when the notification manager sends a notification, it needs to add the cluster label to the notification to identify which cluster the notification comes from. However, the notification manager cannot obtain the name of the cluster where it is located, so it can only be set manually.

I believe this is an important feature for Kubesphere. There're a few use cases:

* case one
* case two
* ...

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

**Comment by iawia002** [comment]
I will add the name of the cluster into the `kubesphere-config` configmap:

```diff
multicluster:
  enable: true
  agentImage: kubesphere/tower:v0.2.0
  proxyPublishService: tower.kubesphere-system.svc
  proxyPublishAddress: http://103.61.38.60:30361
+ clusterName: xxx
```

**Comment by jioce** [comment]
![image](https://user-images.githubusercontent.com/88183150/170236830-fbe8b7bd-a438-45c9-92cd-173a318703db.png)

![image](https://user-images.githubusercontent.com/88183150/170236922-5762968c-a5e6-459e-895b-ab22f275c1a6.png)

version used
v3.3.0-rc.0
