### ISSUE TITLE
Failed to verify private docker registry caused by an invalid certificate error

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#4676]
**Describe the Bug**

Failed to verify private docker registry which uses self-signed certs, even if `secret.kubesphere.io/force-insecure"` appears.

![image](https://user-images.githubusercontent.com/8263040/154393393-bff91adb-2457-46e1-a997-c7b07051dccf.png)

```
Registry Verification Failed.
Get "https://harbor.xxx.com/v2/": x509: certificate is valid for xxxxx, not harbor.xxx.com
```

**Versions Used**
KubeSphere: v3.2.1

**Comment by fzhan** [comment]
Same issue here, need to add some configuration to ks-apiserver's image so it can access private registry.
