### ISSUE TITLE
notification-manager-template  is  Too many alarm contents affect reading, How to define your own content？

### ISSUE THREAD

**Issue by 13878168026** [kubesphere/kubesphere#4677]
There are too many contents in the default alarm template. How to keep the alarm contents you want? I tried to modify the content of "Notification Manager template" in kubesphere, but failed So I thought of a way to develop a jar service by myself, accept the content from "alertmanager", keep only the content I want to keep, and modify the content webhook of "secretname: alertmanager main"_ Configs configuration.

**Comment by 13878168026** [comment]
默认报警模板内容过多，如果保留自己想要的报警内容？我曾经尝试修改kubesphere “notification-manager-template“ ”的内容，但是没有成功. 所以我想了一个办法，自己开发一个jar服务，接受来自 “alertmanager” 的内容，只保留我自己想保留的内容，同时修改 “secretName: alertmanager-main” 的内容 webhook_configs配置。

**Comment by wenchajun** [comment]
Perhaps you could take a look at this https://github.com/kubesphere/notification-manager .
