### ISSUE TITLE
Request to proxy DevOps APIs with version v1alpha1

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/kubesphere#4684]
**What's it about?**

Request to make APIServer to proxy DevOps APIs with version v1alpha1.

**What's the reason why we need it?**

At present, we have separated DevOps application into independent project and let APIServer proxy DevOps APIs with version v1alpha2 and v1alpha3, please see below:

https://github.com/kubesphere/kubesphere/blob/9fbb69faa42b133d60065c4527754de6ba3e65f6/pkg/kapis/devops/v1alpha2/register.go#L33
https://github.com/kubesphere/kubesphere/blob/9fbb69faa42b133d60065c4527754de6ba3e65f6/pkg/kapis/devops/v1alpha3/register.go#L35

But recently, we added a little DevOps APIs with version v1alpha1, please see blow:

- https://github.com/kubesphere/ks-devops/pull/468
- https://github.com/kubesphere/ks-devops/pull/467
- https://github.com/kubesphere/ks-devops/pull/460

I believe this is an important step for KubeSphere to add some new features in DevOps area, like ArgoCD integration and Pipeline Template.

**Area Suggestion**

/area devops

/kind feature-request
/cc @kubesphere/sig-devops 
/assign

**Comment by LinuxSuRen** [comment]
This is a good catch! Great!
