### ISSUE TITLE
failed to connect to ldap service, please check ldap status, error: factory is not able to fill the pool

### ISSUE THREAD

**Issue by beyondyinjl2** [kubesphere/kubesphere#4687]
kubesphere-system              ks-apiserver-788599744c-58k5g                        1/1     Running             3          6m56s
kubesphere-system              ks-console-58cdc6b766-vtb6w                          1/1     Running             0          62m
kubesphere-system              ks-controller-manager-646b8fff9f-pd7w7               0/1     Error               6          6m4s
kubesphere-system              ks-installer-5678c55cff-q9l8g                        1/1     Running             0          11s
kubesphere-system              redis-5799d9b55-t5xqd                                1/1     Running             0          39m

 kubectl logs  ks-controller-manager-646b8fff9f-pd7w7 --namespace=kubesphere-system
W0224 11:36:55.643227       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
E0224 11:36:55.649703       1 server.go:101] failed to connect to ldap service, please check ldap status, error: factory is not able to fill the pool: LDAP Result Code 200 "Network Error": dial tcp: lookup openldap.kubesphere-system.svc on 10.1.0.10:53: no such host

**Comment by xiabai84** [comment]
I have the same problem after starting linux server.

**Comment by xiabai84** [comment]
Delete iptable rules and restart these two services worked for me :-)

$ iptables --flush
$ iptables --flush -tnat

$ kubectl rollout restart deploy -n kubesphere-system ks-controller-manager
$ kubectl rollout restart deploy -n kubesphere-system ks-apiserver
