### ISSUE TITLE
Are there plans to support the management of dapr ?

### ISSUE THREAD

**Issue by GreenShadeZhang** [kubesphere/kubesphere#4696]
**What's it about?**
Dapr is a portable, event-driven runtime that makes it easy for any developer to build resilient, stateless and stateful applications that run on the cloud and edge and embraces the diversity of languages and developer frameworks. Leveraging the benefits of a sidecar architecture, Dapr helps you tackle the challenges that come with building microservices and keeps your code platform agnostic.

**What's the reason why we need it?**
Dapr can greatly simplify the development complexity of developers, and it is also very popular in the community. In addition, it has a similar operating mechanism to istio. I think it is indeed a good idea to integrate into kubesphere for cloud-native operation and maintenance.

I believe this is an important feature for Kubesphere. There're a few use cases:

* Unify link tracking for istio and dapr
* One-stop management of dapr through kubesphere

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

**Comment by benjaminhuo** [comment]
@GreenShadeZhang 

KubeSphere SIG-Serverless open-sourced a FaaS project OpenFunction in which Dapr is used as an async runtime and in the meantime.

OpenFunction is planning to support native [Dapr Apps](https://github.com/OpenFunction/OpenFunction/issues/230). 

And finally, OpenFunction will have a good integration with KubeSphere

@tpiperatgod @wanjunlei

**Comment by GreenShadeZhang** [comment]
> @GreenShadeZhang
> 
> KubeSphere SIG-Serverless open-sourced a FaaS project [OpenFunction](https://github.com/OpenFunction/OpenFunction) in which Dapr is used as an async runtime.
> 
> In the meantime, OpenFunction is planning to support native [Dapr Apps](https://github.com/OpenFunction/OpenFunction/issues/230).
> 
> And finally, OpenFunction will have good integration with KubeSphere
> 
> @tpiperatgod @wanjunlei

Ok, I will study this OpenFunction carefully, thank you very much.
