### ISSUE TITLE
The repository will switch to the dockerhub even though we have set the private registry.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#4703]
**Describe the Bug**
The repository will switch to the dockerhub even though we have set the private registry when we deploy it.
For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/41519383/156555503-e92f6826-5e3e-4638-952a-390f02790957.png)
![image](https://user-images.githubusercontent.com/41519383/156555549-496da031-f0b1-4f7d-9443-7338f30f42bb.png)

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. Deploy a workload though the private registry.
2. Edit the container template.
3. The registry setting showed the "Docker Hub"

**Comment by wenxin-01** [comment]
issue fixed in 'v3.3.0-alpha.2'

**Comment by wenxin-01** [comment]
https://user-images.githubusercontent.com/68640256/218976530-8c54ba9f-20e6-463a-b30c-da8a352a2c86.mov
