### ISSUE TITLE
An error occurs when managing member's PV

### ISSUE THREAD

**Issue by klj890** [kubesphere/kubesphere#4704]
**Describe the Bug**
In Cluster Federation，

An error occurs when managing member's PV
Related ：https://github.com/kubesphere/console/pull/2226
![WechatIMG7889](https://user-images.githubusercontent.com/19380605/156707174-c17dcbd9-9401-4e68-9735-fdf99ef2f7c8.jpeg)
**Versions Used**
KubeSphere: 3.2.0

**Comment by wansir** [comment]
fixed  in https://github.com/kubesphere/console/pull/2926
