### ISSUE TITLE
Reinstall after uninstalling components

### ISSUE THREAD

**Issue by xiaokangshuai** [kubesphere/kubesphere#4716]
kubesphere v3.2.1
k8s 1.20.10
OS：centos 7.8

I uninstalled the log system, event system and other components, and then reinstalled with the following error
![image](https://user-images.githubusercontent.com/21293110/157193365-4fa83bd3-cf6e-47d0-a15b-0a4f4417f59d.png)

**Comment by showjason** [comment]
You can refer to [Uninstall Pluggable Components from KubeSphere 3.2.x](https://kubesphere.com.cn/en/docs/pluggable-components/uninstall-pluggable-components/)
