### ISSUE TITLE
Project gateway is not deleted when the workspace is deleted

### ISSUE THREAD

**Issue by wktsuiaa** [kubesphere/kubesphere#4719]
**Describe the Bug**
The ingress gateway of a project still exist after the workspace it belongs to is deleted already,
The ingress gateway can be access via a project with same name but belongs to another workspace

**Versions Used**
KubeSphere: 3.2.1
Kubernetes: 1.21.9

**Environment**
Ubuntu 20.0.5

**How To Reproduce**
1. Create a project and enable the gateway
2. Delete the whole workspace and select "delete all project"

**Expected behavior**
Execute "kubectl get pod -n kubesphere-controls-system"
The router of the project should be disappeared.

**Comment by wansir** [comment]
Related to https://github.com/kubesphere/kubesphere/issues/4397

/close
