### ISSUE TITLE
kubesphere   Notification The modified configuration cannot be saved

### ISSUE THREAD

**Issue by xiaokangshuai** [kubesphere/kubesphere#4724]
kubesphere v3.2.1
os： centos7.8
k8s： v1.20.10
After I configured the webhook, then the configuration of dingtalk cannot be saved

![f5b0755f13c43f0555bd125ac42ad97](https://user-images.githubusercontent.com/21293110/157578777-7d7dd251-c769-437b-a93a-fd8cc1958f2d.png)

**Comment by wenchajun** [comment]
Are you sure you have configured it correctly? You can send a test message to verify this.

**Comment by xiaokangshuai** [comment]
I have already configured it, but I cannot save it to take effect

**Comment by xiaokangshuai** [comment]
> Are you sure you have configured it correctly? You can send a test message to verify this.

 have already configured it, but I cannot save it to take effect
![image](https://user-images.githubusercontent.com/21293110/157602604-505ba70f-3618-4d00-bca0-2abb03b9d609.png)

**Comment by weili520** [comment]
Is there an error message in the browser console?

**Comment by xiaokangshuai** [comment]
Seems to have to add global-dingtalk-config-secret but it should be optional

![image](https://user-images.githubusercontent.com/21293110/157613369-84faaf23-8d12-4b38-9a12-5755ff85725f.png)


I found that the configuration of the webhook cannot be cleared, and the information filled in is always there, even if I clear the data

**Comment by benjaminhuo** [comment]
@wanjunlei Is this a mis-config?

**Comment by wanjunlei** [comment]
The `global-dingtalk-config-secret` is not optional, It should have been deleted by someone.

You can delete the dingtalk notification config then recreate it.

```
kubectl delete nr global-dingtalk-receiver
kubectl delete nc default-dingtalk-config
```

**Comment by xiaokangshuai** [comment]
> 不是可选的，它应该已被某人删除。`global-dingtalk-config-secret`
> 
> 您可以删除叮叮当通知配置，然后重新创建它。
> 
> ```
> kubectl delete nr global-dingtalk-receiver
> kubectl delete nc default-dingtalk-config
> ```

Dingtalk can be saved after this operation

![image](https://user-images.githubusercontent.com/21293110/157634322-d2ad5cf7-a942-4cd0-9822-3413c000b90b.png)

But the notification of webhook can't be saved when clicked to close
![image](https://user-images.githubusercontent.com/21293110/157634493-778ce054-dc94-4b6a-821c-491c1499c89c.png)

**Comment by wanjunlei** [comment]
It may be the same error as dingtalk, the secret is deleted,

```
kubectl get secrets -n kubesphere-monitoring-federated global-webhook-config-secret
```

If the secret does not exist, delete the webhook configuration and recreate it

```
kubectl delete nr global-webhook-receiver
```
