### ISSUE TITLE
kubesphere login failed

### ISSUE THREAD

**Issue by xiaokangshuai** [kubesphere/kubesphere#4726]
kubernetes:1.20.10 
kubesphere:v3.2.1
os:centos7.8 

ks-apiserver log

W0311 15:53:13.313847       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0311 15:53:13.315002       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0311 15:53:13.415426       1 interface.go:60] start helm repo informer
I0311 15:53:13.429191       1 apiserver.go:356] Start cache objects
W0311 15:53:15.358013       1 apiserver.go:551] resource monitoring.coreos.com/v1, Resource=prometheuses not exists in the cluster
W0311 15:53:15.358076       1 apiserver.go:551] resource monitoring.coreos.com/v1, Resource=prometheusrules not exists in the cluster
W0311 15:53:15.358108       1 apiserver.go:551] resource monitoring.coreos.com/v1, Resource=thanosrulers not exists in the cluster
E0311 15:53:15.362124       1 reflector.go:138] github.com/prometheus-operator/prometheus-operator/pkg/client/informers/externalversions/factory.go:115: Failed to watch *v1.PrometheusRule: failed to list *v1.PrometheusRule: the server could not find the requested resource (get prometheusrules.monitoring.coreos.com)
E0311 15:53:16.501425       1 reflector.go:138] github.com/prometheus-operator/prometheus-operator/pkg/client/informers/externalversions/factory.go:115: Failed to watch *v1.PrometheusRule: failed to list *v1.PrometheusRule: the server could not find the requested resource (get prometheusrules.monitoring.coreos.com)
E0311 15:53:19.421692       1 reflector.go:138] github.com/prometheus-operator/prometheus-operator/pkg/client/informers/externalversions/factory.go:115: Failed to watch *v1.PrometheusRule: failed to list *v1.PrometheusRule: the server could not find the requested resource (get prometheusrules.monitoring.coreos.com)
E0311 15:53:25.212837       1 reflector.go:138] github.com/prometheus-operator/prometheus-operator/pkg/client/informers/externalversions/factory.go:115: Failed to watch *v1.PrometheusRule: failed to list *v1.PrometheusRule: the server could not find the requested resource (get prometheusrules.monitoring.coreos.com)
E0311 15:53:32.213613       1 reflector.go:138] github.com/prometheus-operator/prometheus-operator/pkg/client/informers/externalversions/factory.go:115: Failed to watch *v1.PrometheusRule: failed to list *v1.PrometheusRule: the server could not find the requested resource (get prometheusrules.monitoring.coreos.com)
E0311 15:53:57.590446       1 reflector.go:138] github.com/prometheus-operator/prometheus-operator/pkg/client/informers/externalversions/factory.go:115: Failed to watch *v1.PrometheusRule: failed to list *v1.PrometheusRule: the server could not find the requested resource (get prometheusrules.monitoring.coreos.com)

**Comment by xiaokangshuai** [comment]
![image](https://user-images.githubusercontent.com/21293110/157827993-6c4f4b8b-083d-4318-b9b6-e28c77cb060a.png)

**Comment by FeynmanZhou** [comment]
Could you try this command and paste the result?
```
kubectl get po -n kubesphere-system
```

**Comment by xiaokangshuai** [comment]
![image](https://user-images.githubusercontent.com/21293110/157851243-4195ce1c-9088-48c4-9959-5364da0f7c5e.png)
