### ISSUE TITLE
helm application bug

### ISSUE THREAD

**Issue by Areturn** [kubesphere/kubesphere#4728]
**Describe the Bug**
<img width="1281" alt="b907c4b1f7754e4f2ce388de0ca153f" src="https://user-images.githubusercontent.com/25275823/158045481-318d88f9-9956-4c2f-afa3-9c939911e7a2.png">

**Versions Used**
KubeSphere: 3.2.1
Kubernetes: v1.21.5-eks-bc4871b

**How To Reproduce**
1. Created a loki-stack application
2. When modifying grafana to NodePort, it is written as Nodeport
3. Then it becomes a failure state, and the configuration cannot be updated, and the error in the upper right corner of the figure will be reported.

**Comment by FeynmanZhou** [comment]
@Areturn Thanks for reporting this issue!

Hi team @kubesphere/sig-testing @wenxin-01 ,

Could you please help to verify it? If it exists, we will fix it in the future release.

**Comment by CheckMySoul** [comment]
When the helm application status is failed, any modification will report an error, which is consistent with the picture.

**Comment by xzplays** [comment]
This issue has not been fixed yet and occurs frequently in areas with poor network conditions
