### ISSUE TITLE
Error: JWT secret MUST not be empty

### ISSUE THREAD

**Issue by GuoChanghe0220** [kubesphere/kubesphere#4729]
KubeSphere 前后端本地开发环境
 bin/cmd/ks-apiserver --kubeconfig ~/.kube/config
报错，错误如下：
Error: JWT secret MUST not be empty

**Comment by lesterhnu** [comment]
没有指定配置文件吧，有个kubesphere.yaml，放在根目录下 然后启动，kubectl get cm kubesphere-config -n kubesphere-system -o yaml 里面的kubesphere.yaml字段就是

**Comment by JohnNiang** [comment]
As @lesterhnu mentioned in https://github.com/kubesphere/kubesphere/issues/4729#issuecomment-1066590224, you could fetch kubesphere-config into your root folder of project by executing following command:

```bash
kubectl get cm -n kubesphere-system kubesphere-config -o=jsonpath="{.data['kubesphere\.yaml']}" > kubesphere.yaml
```

See link below for more:

- https://github.com/kubesphere/kubesphere/blob/19048d52dca1e874008b7a7ecd9f2ebb719f253e/pkg/apiserver/config/config.go#L136-L152
