### ISSUE TITLE
cloud-controller-manager pod运行不正常，设置lb网关不可用。

### ISSUE THREAD

**Issue by liaoyinfeng** [kubesphere/kubesphere#473]
一、检查Pod状态，发现异常。
root@master:~# kubectl get pod -n kube-system | grep cloud-controller-manager
cloud-controller-manager-68c4675975-s4b4g            0/1     CrashLoopBackOff   88         7h33m。
二、查看Pod日志，提示api key授权失败。
I0610 01:49:15.192360       1 flags.go:33] FLAG: --v="1"
I0610 01:49:15.192376       1 flags.go:33] FLAG: --version="false"
I0610 01:49:15.192439       1 flags.go:33] FLAG: --vmodule=""
I0610 01:49:24.905616       1 serving.go:319] Generated self-signed cert in-memory
W0610 01:49:28.901516       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0610 01:49:29.001096       1 controllermanager.go:113] Version: v0.0.0-master+$Format:%h$
E0610 01:49:30.300047       1 qingcloud.go:116] Failed to get userID
F0610 01:49:30.300176       1 controllermanager.go:117] Cloud provider could not be initialized: could not init cloud provider "qingcloud": QingCloud Error: Code (1200), Message (AuthFailure, illegal access key [XINAINYGJZBFTWKMKXEQ])
root@master:~#
三、在master节点上抓包发现cloud-controller-manager pod运行后，一直尝试连接青云公有云的api server，而不是var.yaml里指定的内网api server.

**Comment by magicsong** [comment]
installer已经修复。
