### ISSUE TITLE
i delete the cluster but it still exisit on workplace

### ISSUE THREAD

**Issue by szc1233444** [kubesphere/kubesphere#4730]
i use this doc  https://kubesphere.io/zh/docs/multicluster-management/enable-multicluster/direct-connection/
The first time I accidentally added the host kubeconfig to the added cluster, I deleted it in kubectl, then when I finished adding other clusters, I found this problem.
![image](https://user-images.githubusercontent.com/65069247/158113902-54eff48c-0ade-4e62-8f05-ee3530dac74a.png)

![image](https://user-images.githubusercontent.com/65069247/158114123-80685b08-cad6-40c2-87a8-c2efc62ac85a.png)

**Comment by szc1233444** [comment]
It's still on the workbench and cannot be unbound.

**Comment by zryfish** [comment]
That's wired, what's the output of `kubectl get clusters` on host cluster?

**Comment by szc1233444** [comment]
> That's wired, what's the output of `kubectl get clusters` on host cluster?

no,there is not a cluster which name undefined and everything works fine.
