### ISSUE TITLE
通过代码创建服务,镜像名称校验与提示不符

### ISSUE THREAD

**Issue by xiaohezi205** [kubesphere/kubesphere#4731]
通过代码创建服务,选择目标镜像仓库（harbor镜像），输入镜像名称如下：192.168.4.25:8889/devops-java-test/devops-java-sample
提示：名称无效。名称只能包含小写字母、数字和连字符（-），必须以小写字母或数字开头和结尾，最长 63 个字符。

**Comment by FeynmanZhou** [comment]
1. Please make sure the docker image name is in line with the convention. 
2. Have you successully created the Secret for your Harbor registry?

**Comment by xiaohezi205** [comment]
1.docker镜像名称是符合规定的，只是在通过代码创建服务，名称校验不通过，因为在拉取镜像失败后，我编辑了yaml文件，是可以拉取镜像的。如devops-java-sample-v1.yaml文件中的镜像名称：192.168.4.25:8889/devops-java-test/devops-java-sample:latest，但是在创建服务填入镜像名称时，校验失败（名称只能包含小写字母、数字、连字符（-）、句点（.）、斜钱（/）和冒号（:），并以小写字母或数字开头和结尾。），如下图：




***@***.***
 
发件人： pengfei
发送时间： 2022-03-15 17:01
收件人： kubesphere/kubesphere
抄送： xiaohezi205; Author
主题： Re: [kubesphere/kubesphere] 通过代码创建服务,镜像名称校验与提示不符 (Issue #4731)
Please make sure the docker image name is in line with the convention.
Have you successully created the Secret for your Harbor registry?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
