### ISSUE TITLE
BlackboxExporter Support

### ISSUE THREAD

**Issue by 10206334** [kubesphere/kubesphere#4733]
Do we support BlackboxExporter in the pre-existing kubeshere

**Comment by benjaminhuo** [comment]
I think you can install any exporter on existing kubesphere

**Comment by 10206334** [comment]
I already have monitoring enabled in kubeshere, I already have prometheus, but I want to integrate BlackboxExporter into monitoring enabled, how do I do that?

**Comment by 10206334** [comment]
> I think you can install any exporter on existing kubesphere

I already have monitoring enabled in kubeshere, I already have prometheus, but I want to integrate BlackboxExporter into monitoring enabled, how do I do that?

**Comment by 10206334** [comment]
Do we have demos？
