### ISSUE TITLE
Application can not update status

### ISSUE THREAD

**Issue by chj9** [kubesphere/kubesphere#4742]
### k8s version
v1.22.3-aliyun.1
### kubesphere version
3.2.1
![image](https://user-images.githubusercontent.com/16426260/159661073-55767ae7-df24-441d-9ccf-bd91d51b9669.png)
![image](https://user-images.githubusercontent.com/16426260/159660969-d08642bd-992d-40e4-84ec-25a8a3c15a1a.png)

**Comment by chj9** [comment]
recreating the deployment didn't change the application  state either

**Comment by noonme** [comment]
@chj9 
![image](https://user-images.githubusercontent.com/59679343/212368325-6db67bec-18e5-45fc-9038-8db8af4bf634.png)
![image](https://user-images.githubusercontent.com/59679343/212368532-c765f956-2398-4908-8964-a3168a691427.png)
