### ISSUE TITLE
Cannot create a snapshot from a volume that supports and is allowed to create a snapshot on the web console

### ISSUE THREAD

**Issue by serenashe** [kubesphere/kubesphere#4749]
**Describe the Bug**
Cannot create a snapshot from a volume that supports and is allowed to create a snapshot on the web console.

**Versions Used**
KubeSphere: v3.2.0

**Environment**
How many nodes and their hardware configuration:
3 masters; 3 nodes

**How To Reproduce**
1. For this volume that is allowed to create a snapshot on the web console, I go to the volumes details page and click **More > Create Snapshot**.
![image](https://user-images.githubusercontent.com/75245999/160348047-f53c9a09-2ab9-495a-b9ab-24c3d3d0ab24.png)
2. In the **Create Snapshot** dialog box, I entered all the necessary information. But when I clicked **OK**, nothing worked. It seemed that no request was sent.
3. On the Volume Snapshot list page, I tried to create a snapshot from this volume, but this option was disabled.
![image](https://user-images.githubusercontent.com/75245999/160349037-fbe347f7-2c1f-47e9-b4ad-07aeeb32348e.png)
4. On the Storage Classes list page, volume snapshot is allowed to be created for this storage class.
![image](https://user-images.githubusercontent.com/75245999/160349327-44a1e799-e17f-4b91-a502-4f70c97ec835.png)

/assign @stoneshi-yunify Please take a look, thanks very much!

**Comment by stoneshi-yunify** [comment]
![image](https://user-images.githubusercontent.com/70880165/160352908-12693ef4-86c0-49c3-8568-79e8630290c3.png)



@f10atin9  pls take a look.

**Comment by f10atin9** [comment]
> ![image](https://user-images.githubusercontent.com/70880165/160352908-12693ef4-86c0-49c3-8568-79e8630290c3.png)
> 
> @f10atin9 pls take a look.

Okay

**Comment by f10atin9** [comment]
Snapshots cannot be created in the pvc details page because there is a problem with the create button.
And some pvc's on the snapshot list page cannot be selected to create a snapshot because they are incorrectly identified as unmounted.

**Comment by f10atin9** [comment]
Already fixed in [fix: Volume mount judgment](https://github.com/kubesphere/console/pull/3026) and [fix: Update PV table item available action](https://github.com/kubesphere/console/pull/2860).  Thanks for the contribution of  @weili520
