### ISSUE TITLE
代理链接添中设置代理服务地址的说明示例中有错误

### ISSUE THREAD

**Issue by hanweisen** [kubesphere/kubesphere#4755]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**General remarks**

> Please delete this section including header before submitting
>
> This form is to report installation issues. For general usage questions you can refer to [KubeSphere Documentation](https://kubesphere.io/docs) or join our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE)

**What's your question**
https://kubesphere.com.cn/docs/multicluster-management/enable-multicluster/agent-connection/
代理链接proxyPublishAddress的配置教程存在误导，文档中tower的svc的配置是
`NAME       TYPE            CLUSTER-IP      EXTERNAL-IP     PORT(S)              AGE
tower      LoadBalancer    10.233.63.191   <pending>  8080:30721/TCP            16h`
后面给的参考配置为
proxyPublishAddress: http://139.198.120.120:8080 # Add this line to set the address to access tower
这里应该应该将8080改成30721才是正确的配置示例

**Environment: OS & Hardware Information**

> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).

**Error logs or message (Attach logs or screenshot)**

**Installer Version**

> e.g. v2.1.0, v2.1.1, v3.0.0

**Comment by iawia002** [comment]
Nope, you misunderstand it, the example is right, `8080:30721` means the port 8080 of this IP address will be forwarded to port 30721.
