### ISSUE TITLE
【急急急】【求远程】3.2.1版本部署完成所有得put和delete方法报以下错误

### ISSUE THREAD

**Issue by q383186554** [kubesphere/kubesphere#4756]
![image](https://user-images.githubusercontent.com/53943425/160953440-ef2cb30b-6a29-4157-b7c5-ce316e4032a9.png)

**Comment by q383186554** [comment]
![image](https://user-images.githubusercontent.com/53943425/160953257-d1fcb2e5-d8e4-499e-a29f-f0f50d84ae72.png)

**Comment by q383186554** [comment]
添加没问题 但是修改和删除报错  有关put和delete得方法都报错 响应无内容

**Comment by wenchajun** [comment]
Please use English in github, if you use Chinese, please ask questions on the forum.

**Comment by FeynmanZhou** [comment]
@q383186554 
Duplicated question: https://kubesphere.com.cn/forum/d/6993-v321k8s-putdelete
I will close it here. 

**Please note:** We don't provide remote one-on-one technical support in the open-source community. This is totally unreasonable and rude if you ask for any open source project maintainers to provide this kind of service.

**Comment by dragonly** [comment]
**WAITING ONLINE!!!**
**EXCITED!!!**
