### ISSUE TITLE
YAML file displays invalid parameters after configuring QingCloud CSI storage system on the web console.

### ISSUE THREAD

**Issue by serenashe** [kubesphere/kubesphere#4757]
**Describe the Bug**
YAML file displays invalid parameters after configuring QingCloud CSI storage system on the web console.
The following picture shows my QingCloud CSI storage system configuration on the web console:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/75245999/160580235-8884ffcb-5391-44d3-9dfb-772cf26cad9b.png">

When I view its YAML file, it looks like this:
<img width="655" alt="image" src="https://user-images.githubusercontent.com/75245999/160580397-5672cc97-6c22-4a83-86ec-1ab4ef047294.png">

**Versions Used**
KubeSphere: v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: 1 master; 3 nodes
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. Log in to the KubeSphere web console as the `admin` user.
2. In the upper-left corner, click Platform > Cluster Management.
3. For a multi-cluster environment, select a cluster.
4. On the left nevigation pane, select **Storage > Storage Classes**.
5. On the storage class list page, click **Create**.
6. On the **Basic Information** tab, set the necessary information and click **Next**.
7. On the **Storage System** tab, select **QingCloud CSI**.
8. Enter the parameters as showed in the previous picture and click **Create**.
9. Click the name of the storage class to go to its details page.
10. In the upper-left corner, click **Edit YAML** to view its YAML file.
You will see that something's wrong with all of those parameters.

**Expected behavior**
The parameters should be valid and can actually take effect.

/assign @stoneshi-yunify Please take a look, thx!

**Comment by stoneshi-yunify** [comment]
@f10atin9  pls take a look. thanks.
