### ISSUE TITLE
When create resouce with kapi, user can specify any creator does not use the right user

### ISSUE THREAD

**Issue by hanweisen** [kubesphere/kubesphere#4766]
**Describe the Bug**
For example. when create a workspace. the request is:
```
POST /kapis/clusters/{cluster-name}/tenant.kubesphere.io/v1alpha2/workspaces/{workspace}/namespaces.
{
  "apiVersion": "v1",
  "kind": "Namespace",
  "metadata": {
    "name": "delete-host",
    "labels": {
      "kubesphere.io/workspace": "hanweisen-workspace"
    },
    "annotations": {
      //here user can specify any user. does not use the current auth user
      "kubesphere.io/creator": "nonexist"
    }
  },
  "cluster": "member2"
}
```

**Versions Used**
KubeSphere: 3.2.1
Kubernetes: (1.21.5

**Environment**

**Expected behavior**
The  "kubesphere.io/creator" annontation should be the current operator user.

Is this a bug need fixed?

**Comment by wansir** [comment]
As you can see, `creator` is just a special annotation, the audit log records the user's operations.

**Comment by hanweisen** [comment]
ok
