### ISSUE TITLE
多台只能通过外网访问的云服务器如何创建kubesphere集群？

### ISSUE THREAD

**Issue by ppap6664180** [kubesphere/kubesphere#4768]
我有多台在不同云服务商下的服务器 ，服务器直接只能通过外网访问。没有外网地址网卡
我通过kk生成的默认配置 安装 kubesphere集群 失败。
请问我需要如何配置才能安装

**Comment by FeynmanZhou** [comment]
It is not recommended to use different nodes across multiple cloud providers to create a single cluster, it might have network latency. You would better create a cluster with different nodes in a VPC or run multiple clusters across different cloud providers.
