### ISSUE TITLE
When I open the multicluster function, login from member clusters was error

### ISSUE THREAD

**Issue by yongxingMa** [kubesphere/kubesphere#4771]
**Describe the Bug**
When I open the multicluster function, login from member clusters was error。

For example, I have a master cluster and multiple member clusters，When master cluster is disconnected, I want to login  from the member cluster，but I failed to login now。

<img width="689" alt="image" src="https://user-images.githubusercontent.com/40452856/167113280-714e1b37-11ed-44d4-977d-fdfe85d67d96.png">

**Versions Used**
KubeSphere: v3.2.1

**Comment by hanweisen** [comment]
I had the same problem in multicluster. Even you use member cluster console create user you can not login from member cluster.
I created 3 cluster and use one node proxy. you login in host cluster console. you can access member console without login they can share same cookie. This is why I can create user direct in member cluster console

**Comment by hanweisen** [comment]
I can not login console but I can access member cluster with command like this
`curl -u 'username:password' ip:port/kapis/resources.kubesphere.io/v1alpha3/statefulsets`

**Comment by hanweisen** [comment]
Is this issue intentionally designed this way, or is it a bug?. If it's a bug I'd like to try to fix it @FeynmanZhou

**Comment by hanweisen** [comment]
This problem can resolve by add some line in configmap kubesphere-config and restart ks-apiserver
```
authentication:
  oauthOptions:
    accessTokenMaxAge: 0
    clients:
    - name: kubesphere
      secret: kubesphere
      redirectURIs:
      - '*'
```

**Comment by hanweisen** [comment]
This is a ks-install problem, I create a pull request https://github.com/kubesphere/ks-installer/pull/1932

**Comment by FeynmanZhou** [comment]
> Is this issue intentionally designed this way, or is it a bug?. If it's a bug I'd like to try to fix it @FeynmanZhou

It was intentionally designed but I think it is not reasonable, it should provide a way for users to enable the login option in the member cluster.. Hi @kubesphere/sig-multitenancy @wansir , please help to verify it.

@hanweisen BTW, thanks for your contribution!

**Comment by wansir** [comment]
@hanweisen Thanks for your contribution! We have noticed this problem, it is related to this issue  https://github.com/kubesphere/kubesphere/issues/4610 and it is already fixed in https://github.com/kubesphere/ks-installer/pull/1923. The user experience of the member cluster will be improved in v3.3.
