### ISSUE TITLE
Can we get the source file of edge-watcher-agent ?

### ISSUE THREAD

**Issue by alongL** [kubesphere/kubesphere#4777]
The docker image of amd64 is OK.
   https://hub.docker.com/r/kubesphere/edge-watcher-agent/tags

But the image of arm64 is not OK on our environment.
We want to build this image by ourselves, can we get the source code of edge-watcher-agent ?

**Comment by benjaminhuo** [comment]
The edge-watcher will be removed in the upcoming KubeSphere v3.3 because KubeEdge adds similar functionality in the higher version and edge-watcher is no longer needed and not recommended.

**Comment by alongL** [comment]
Now kubeedge is v1.10 ,  but KubeSphere uses KubeEdge v1.7 .
Will KubeEdge v1.10 be used in KubeSphere v3.3 or newer version?

**Comment by alongL** [comment]
> The edge-watcher will be removed in the upcoming KubeSphere v3.3 because KubeEdge adds similar functionality in the higher version and edge-watcher is no longer needed and not recommended.

Now kubeedge is v1.10 , but KubeSphere uses KubeEdge v1.7 .
Will KubeEdge v1.10 be used in KubeSphere v3.3 or newer version?

**Comment by alongL** [comment]
When will KubeSphere v3.3 be released ? 
Expecting !
