### ISSUE TITLE
Users logged in via github cannot be disabled

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#4781]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/68640256/162869062-0eeae154-00f5-4cee-84fa-a7b229343fdb.png)

**Versions Used**
KubeSphere:   `v3.3.0-alpha.0`

**How To Reproduce**
1. Log in KS via github
2. Disable the github account with admin
3. Log in KS via the github account

**Expected behavior**
Can not log in kS via the github account and have reasonable prompts

**Actual behavior**
Can log in Ks via the github account

/priority high
/assign @wansir

**Comment by jioce** [comment]
issue fixed 
![image](https://user-images.githubusercontent.com/88183150/170219423-a6cfcad1-1c53-40e6-8d67-771bc9c90537.png)

version used
nightly-20220524
