### ISSUE TITLE
Two Elasticsearch instances are created after KubeSphere is upgraded from v3.2.1 to v3.3.0 alpha0

### ISSUE THREAD

**Issue by patrickluoyu** [kubesphere/kubesphere#4782]
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/76198553/162895844-20230581-02d3-4b3d-9e8e-23062017d6c7.png">

**Expected behavior**

Only one Elasticsearch instance exists.

**Comment by benjaminhuo** [comment]
> The `generateID: true` should be added to the events and audit log receiver.

`generateID: true` is related to the duplicated es log receivers?

If generateID should be added to the events and audit log receivers, we should add it from ks-installer side?

**Comment by wanjunlei** [comment]
The reason why the log receiver is duplicated is that the output created by the ui and the output created by the installer have different names, and there will be two outputs at the same time after ks upgrade.

The generateID had added in ks3.2.

**Comment by benjaminhuo** [comment]
So you mean, we should change from the UI side to the same output value as the ks-installer?

**Comment by wanjunlei** [comment]
Yes, this is an easy solution. 

Maybe we need to reconsider this function. At present, the previous function can no longer meet the needs. For example, the installer already supports setting the username and password of es and supports HTTPS, but it cannot be set here. And I don't think it makes sense for the user to remove the built-in output from the UI.
