### ISSUE TITLE
Duplicate add host cluster error

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4792]
**Describe the Bug**
1、There is a host cluster
2、Enter the cluster management, click Add Cluster, and enter the kubeconfig of the existing host cluster
3、The page reports an error and returns to the cluster page. The added cluster already exists
![image](https://user-images.githubusercontent.com/88183150/163298478-ace69cc0-9d2c-4112-99da-0abb8d445f7e.png)

![image](https://user-images.githubusercontent.com/88183150/163298509-1d075971-d23d-4600-b470-04d033706f0f.png)

**Versions Used**
KubeSphere: v3.3.0-alpha.0

/kind bug
/priority medium

**Comment by iawia002** [comment]
This is the same reason as #4790, the validation for adding clusters is not working anymore causing this problem, this is already fixed in https://github.com/kubesphere/ks-installer/pull/1941, you can test it again in the next version.
