### ISSUE TITLE
Failed to enable automatic restart of workloads

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4793]
**Describe the Bug**
1、Existing storage type qingcloud-csi, enter the details page, click more operations - "PVC regulator
2、Set the PVC scheduler and select Enable to automatically start the workload
3、Looking at the storage type yaml file, the tag is missing (restart.kubesphere.io/online-expansion-support: 'false')
![image](https://user-images.githubusercontent.com/88183150/163324918-9085932e-d7bc-421a-8bee-2c7fc4055fb1.png)

![image](https://user-images.githubusercontent.com/88183150/163324882-c68f79a5-7fa4-4048-9a8c-342dbae7af28.png)

![image](https://user-images.githubusercontent.com/88183150/163325102-bead486a-e912-4feb-909c-1f38ee0dca90.png)

**Versions Used**
KubeSphere: v3.3.0-alpha.0

/kind bug
/priority high
/assign @f10atin9

**Comment by f10atin9** [comment]
> /cc @weili520

The conditions for testarter to start are enable set to true and restart.kubesphere.io/online-expansion-support: set to 'false', can you add a check box in the console?

**Comment by weili520** [comment]
> > /cc @weili520
> 
> The conditions for testarter to start are enable set to true and restart.kubesphere.io/online-expansion-support: set to 'false', can you add a check box in the console?

OK

**Comment by f10atin9** [comment]
To ensure availability, remove the % option in the increase box

**Comment by f10atin9** [comment]
And @jioce  suggested, add the prompt text next to it: 
"Please set the increment according to the expansion step size of StorageClass-csi, otherwise it may not work"
"请根据StorageClass-csi的扩容步长设置增量，否则可能出现错误“

**Comment by f10atin9** [comment]
BTW, the limit cannot be greater than 100%.

**Comment by jioce** [comment]
Prompt error, the percentage option has been removed
 should prompt "Please set the increment according to the expansion step size of StorageClass-csi, otherwise it may not work"

![image](https://user-images.githubusercontent.com/88183150/163761486-7ffe9b0b-134c-4976-a494-577a59a2a11a.png)

version used: kubesphere 3.3.0-alpha.1

**Comment by jioce** [comment]
issue fixed in v3.3.0-alpha.2
