### ISSUE TITLE
The size of the expanded storage volume is greater than Storage Limit

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4799]
**Describe the Bug**
1、There is a storage type test, set the PVC regulator, the Storage Limit is 15G, the threshold is 99%, and the increase is 10G
2、Create a storage volume vv with a size of 10G, mount it to the existing workload deploy, and increase the storage volume usage to the threshold
3、After a period of time, the storage volume is successfully expanded
![image](https://user-images.githubusercontent.com/88183150/163541509-d4532b04-71de-4859-b0a6-378c714f475e.png)

**Versions Used**
KubeSphere: v3.3.0-alpha.0

**Expected behavior**
When the expanded size of the storage volume is greater than Storage Limit, the storage volume is not being expanded

/kind bug
/assign @f10atin9 
/priority Medium

**Comment by f10atin9** [comment]
When the capacity after resize is greater than the limit, it will expand to the limit value, we think this is reasonable

**Comment by f10atin9** [comment]
> **Describe the Bug** 1、There is a storage type test, set the PVC regulator, the Storage Limit is 15G, the threshold is 99%, and the increase is 10G 2、Create a storage volume vv with a size of 10G, mount it to the existing workload deploy, and increase the storage volume usage to the threshold 3、After a period of time, the storage volume is successfully expanded ![image](https://user-images.githubusercontent.com/88183150/163541509-d4532b04-71de-4859-b0a6-378c714f475e.png)
> 
> **Versions Used** KubeSphere: v3.3.0-alpha.0
> 
> **Expected behavior** When the expanded size of the storage volume is greater than Storage Limit, the storage volume is not being expanded
> 
> /kind bug /assign @f10atin9 /priority Medium

The reason for the above is that the csi step leads to a direct resize to 20G
