### ISSUE TITLE
The storage class accessor function does not function properly

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/kubesphere#4800]
**Describe the Bug**

![image](https://user-images.githubusercontent.com/76198553/163556584-2adaf451-1063-40b4-bd99-a840bce9b0b8.png)

![image](https://user-images.githubusercontent.com/76198553/163556598-202c7c3f-980c-46a4-8ad5-a72dd56d44b1.png)

![image](https://user-images.githubusercontent.com/76198553/163556612-4aaf384d-87df-43f9-9a52-653b7abf9027.png)

![image](https://user-images.githubusercontent.com/76198553/163556624-f49fa243-2d94-4834-ac04-3fb241aea4f7.png)

**Versions Used**
KubeSphere: 3.3.0 alpha0

/assign @zryfish @f10atin9 @harrisonliu5

**Comment by f10atin9** [comment]
By checking this cluster, we found that there is no CRD and validatingWebhook for storageclass-accessor. And ks-installer is still v3.2.1, maybe only the images was updated when upgrading.
