### ISSUE TITLE
Storage volume snapshot is missing error message

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4808]
**Describe the Bug**
1、The storage volume snapshot type test exists, create a storage volume snapshot test-vv of the test type
2、Delete the storage volume snapshot type test, click to view the storage volume snapshot details
3、There should be an error message here, the storage volume snapshot type does not exist
![image](https://user-images.githubusercontent.com/88183150/164144540-c4f79c30-1e1e-4408-bdaa-73280563d8a5.png)

![image](https://user-images.githubusercontent.com/88183150/164144617-02da7efc-1e05-4ffc-b610-be0851b73602.png)

![image](https://user-images.githubusercontent.com/88183150/164144657-8b90fe32-6e69-4f0b-a602-44bc6cedb107.png)

![image](https://user-images.githubusercontent.com/88183150/164144713-f087eb12-1019-4c3e-8457-5a79005d4112.png)

**Versions Used**
KubeSphere: v3.3.0-alpha.1

/priority medium
/assign @weili520

**Comment by f10atin9** [comment]
There will be an error in the pvc page because the console will send a get sc request, add it to the snapshot if necessary.

**Comment by weili520** [comment]
This page doesn't fetch the snapshot class related data, so it will not create an error tip, but there will have tip info as follow:

<img width="1272" alt="截屏2022-04-20 15 49 26" src="https://user-images.githubusercontent.com/33231138/164178502-53898497-2acc-4f66-958c-99f6611160d9.png">

**Comment by jioce** [comment]
After the storage snapshot type is deleted, the snapshot can successfully create a storage volume
![image](https://user-images.githubusercontent.com/88183150/164361053-b8496c7c-74f1-4909-a4e7-1ed0866d3e56.png)

![image](https://user-images.githubusercontent.com/88183150/164361161-3cf725d4-673d-4502-9e04-915ae327f722.png)

![image](https://user-images.githubusercontent.com/88183150/164361201-f325d386-7674-4193-89a7-2f77d1783120.png)

![image](https://user-images.githubusercontent.com/88183150/164361227-053ea663-b12c-4a9f-a379-5a284df6db22.png)

**Comment by jioce** [comment]
issue fixed in v3.3.0-alpha.2
