### ISSUE TITLE
Notification Configuration should be enabled by default

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#4809]
**What's it about?**

Notification Configuration should be enabled by default.

<img width="960" alt="1650440176" src="https://user-images.githubusercontent.com/53003665/164175632-dcb3add6-9ee8-4e75-bcf9-6ea014248b53.png">

Currently, the notification configuration is disabled by default when it is added. The location of the `enable` button is inconspicuous, and users often forget to enable it. This results in the user not being able to receive notifications. This error is relatively subtle and difficult for new users to find.

**What's the reason why we need it?**

I believe this is an important feature for Kubesphere. There're a few use cases:

* case one
* case two
* ...

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/area console

/kind feature-request

/assign @VioZhang

**Comment by VioZhang** [comment]
We’d better make it easy to recognize the ”enable“ button or the user could find the button easily after setting the config.

**Comment by benjaminhuo** [comment]
> We’d better make it easy to recognize the ”enable“ button or the user could find the button easily after setting the config.

It's two different things.
I agree with @wanjunlei, the notification should be enabled by default, not disabled by default.
As I can remember if the notification channel is created in a disabled state, the config cannot be displayed even after enabling it, @wanjunlei have you reproduce that issue?

Making it easy to find the enable button is a different issue.

**Comment by VioZhang** [comment]
Maybe you do not get the point which is that the core problem is that "users often forget to enable it".
If the button is enabled by default there will be some probelm such as that "why i could not receive the message when the button is enable when the form is empty? ".The button should be enabled by default.And it is a common sense rather not the different issue.

**Comment by benjaminhuo** [comment]
I don't think a user will ask "why i could not receive the message when the button is enable when the form is empty? "
He didn't config the email server, why can he receive an email?

We needn't make the user find the enable button when the config is empty. Simply remove the enable or disable button when there is no config set.

Whenever a user inputs the config and clicks save, the config should be enabled by default, not disabled by default.
 After saving the config, the disable button appears.

**Comment by VioZhang** [comment]
finished
