### ISSUE TITLE
can't login from dex after kubesphere is upgrade from v3.2.1 to v3.3.0-alpha.1

### ISSUE THREAD

**Issue by daixijun** [kubesphere/kubesphere#4811]
**Describe the Bug**
<img width="515" alt="image" src="https://user-images.githubusercontent.com/3611220/164212216-f0d2a723-8b5d-4233-b10e-45409333a8ce.png">
<img width="427" alt="image" src="https://user-images.githubusercontent.com/3611220/164212282-b1a3b8b7-8cb0-4173-9020-2074365189c3.png">

**Versions Used**
KubeSphere: v3.3.0-alpha.1
Kubernetes: v1.20.11

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by cs8w** [comment]
Same here with new KubeSphere 3.3.0 - I can't connect Dex. Everything works perfect after downgrade to 3.2.1.
