### ISSUE TITLE
 Kubesphpere is deployed in eks fargate mode, and the Prometheus node exporter cannot be scheduled 

### ISSUE THREAD

**Issue by kindnull** [kubesphere/kubesphere#4812]

**Comment by FeynmanZhou** [comment]
Hi @kindnull Is there a port conflict between KubeSphere and EKS? Any error logs?

**Comment by kindnull** [comment]
on deploy,An error occurred
--------------------------------
failed: [localhost] (item={'ns': 'kubesphere-system', 'kind': 'users.iam.kubesphere.io', 'resource': 'admin', 'release': 'ks-core'}) => {"ansible_loop_var": "item", "changed": true, "cmd": "/usr/local/bin/kubectl -n kubesphere-system annotate --overwrite users.iam.kubesphere.io admin meta.helm.sh/release-name=ks-core && /usr/local/bin/kubectl -n kubesphere-system annotate --overwrite users.iam.kubesphere.io admin meta.helm.sh/release-namespace=kubesphere-system && /usr/local/bin/kubectl -n kubesphere-system label --overwrite users.iam.kubesphere.io admin app.kubernetes.io/managed-by=Helm\n", "delta": "0:00:00.309337", "end": "2022-05-02 05:56:06.275961", "failed_when_result": true, "item": {"kind": "users.iam.kubesphere.io", "ns": "kubesphere-system", "release": "ks-core", "resource": "admin"}, "msg": "non-zero return code", "rc": 1, "start": "2022-05-02 05:56:05.966624", "stderr": "Error from server (InternalError): Internal error occurred: failed calling webhook \"users.iam.kubesphere.io\": Post \"https://ks-controller-manager.kubesphere-system.svc:443/validate-email-iam-kubesphere-io-v1alpha2?timeout=30s\": service \"ks-controller-manager\" not found", "stderr_lines": ["Error from server (InternalError): Internal error occurred: failed calling webhook \"users.iam.kubesphere.io\": Post \"https://ks-controller-manager.kubesphere-system.svc:443/validate-email-iam-kubesphere-io-v1alpha2?timeout=30s\": service \"ks-controller-manager\" not found"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
localhost                  : ok=15   changed=7    unreachable=0    failed=1    skipped=6    rescued=0    ignored=0

**Comment by kindnull** [comment]
run this command:
/usr/local/bin/kubectl -n kubesphere-system annotate --overwrite users.iam.kubesphere.io admin meta.helm.sh/release-name=ks-core && /usr/local/bin/kubectl -n kubesphere-system annotate --overwrite users.iam.kubesphere.io admin meta.helm.sh/release-namespace=kubesphere-system && /usr/local/bin/kubectl -n kubesphere-system label --overwrite users.iam.kubesphere.io admin app.kubernetes.io/managed-by=Helm

**Comment by haozileung** [comment]
As far as I  know, EKS Fargate is server less which means you don't have any logical node to install node exporter. Monitor tools needs to run in sidecar mode within pod. Basically it's not possible.

**Comment by kindnull** [comment]
sorry，the error logs 

> As far as I know, EKS Fargate is server less which means you don't have any logical node to install node exporter. Monitor tools needs to run in sidecar mode within pod. Basically it's not possible.

ok,thanks, i know, so if i  want  to install kubesphere on EKS for  Fargate mode，that is not support？

**Comment by benjaminhuo** [comment]
Currently running KubeSphere on serverless K8s like fargate is not supported yet.

**Comment by kindnull** [comment]
ok,thanks!There was no official reply from the official wechat group
