### ISSUE TITLE
建议增加备份或者数据导入导出功能

### ISSUE THREAD

**Issue by Gerrylinux** [kubesphere/kubesphere#4816]
kubesphere 服务重新创建或者集群迁移，导致用户和授权丢失，这块目前k8s集群和kuhesphere 存在强绑定， 集群迁移成本变大

**Comment by BigFCat** [comment]
我觉得也是，不然如果集群迁移，真的太麻烦了。devops需要全部重建

**Comment by rayzhou2017** [comment]
check https://kubesphere.cloud/self-service/disaster-recovery/
