### ISSUE TITLE
can't login node from ui

### ISSUE THREAD

**Issue by daixijun** [kubesphere/kubesphere#4819]
**Describe the Bug**
trying login to node from the "Open Terminal", I see the "shell-access" pod already created, but can't connect from the ui 

<img width="1654" alt="image" src="https://user-images.githubusercontent.com/3611220/164960565-0a17d456-31c8-4731-931d-fa2c05baf45d.png">
<img width="681" alt="image" src="https://user-images.githubusercontent.com/3611220/164960598-6e710967-432b-4441-94e5-a82e37a78ef6.png">

**Versions Used**
KubeSphere: v3.3.0-alpha.1
Kubernetes: v1.20.11

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by wansir** [comment]
Web terminal depends on WebSocket protocol, please make sure the WebSocket proxy rule is configured in your proxy server.

https://www.nginx.com/blog/websocket-nginx/

**Comment by daixijun** [comment]
<img width="830" alt="image" src="https://user-images.githubusercontent.com/3611220/164966403-c796b781-43ba-44c5-a6a5-6f8642d235b5.png">

The proxy server already support the WebSocket protocol.
These are other connections that use the WebSocket protocol .

**Comment by daixijun** [comment]
Alpine image is too slow to pull, wait for pod is ready, It works properly after being reconnected.
