### ISSUE TITLE
We should support the grafana dashboard at the namespace.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#4822]
**What's it about?**

We should support the grafana dashboard at the namespace.And now we can only find it by th level of the cluster.
![image](https://user-images.githubusercontent.com/41519383/165048764-80766c29-1c8f-4489-a708-b46893e68c77.png)
![image](https://user-images.githubusercontent.com/41519383/165048872-059d80d6-d38c-4a1a-9e7d-d3477726f758.png)

/kind feature-request
/cc @kubesphere/sig-console @kubesphere/sig-observability

**Comment by jioce** [comment]
issue is fixed
![image](https://user-images.githubusercontent.com/88183150/170223439-db145d4a-55cd-4748-9f1e-a19e9de81005.png)

version used
nightly-20220524
