### ISSUE TITLE
Can kubesphere integrate dapr to make kubesphere more powerful

### ISSUE THREAD

**Issue by dengyangxi** [kubesphere/kubesphere#4826]
Openfunction has introduced dapr to solve edge computing.

**Can kubesphere also introduce dapr to solve the microservice runtime ??**

Expect [dapr]( https://github.com/dapr/dapr ) integration to join . . . .  
Make kubesphere more powerful. It can not only manage kubernetes, but also have the basic components of microservices and distributed application runtime

 [https://github.com/dapr/dapr      |      Star 17.7K ](https://github.com/dapr/dapr)   

Hope to adopt the suggestion ！~   Thank you . .

**Comment by FeynmanZhou** [comment]
IMO, OpenFunction is not leveraging Dapr to support edge computing scenarios, it is used for FaaS runtime. Will it be much reasonable to integrate OpenFunction to KubeSphere for your scenario?

**Comment by benjaminhuo** [comment]
OpenFunction is a FaaS platform and running functions on the edge side is one of our goals although it's not well tested and supported yet.

And we're going to add a new runtime in OpenFunction called `ElasticApp`, and you can write and run native dapr applications with this runtime. https://github.com/OpenFunction/OpenFunction/issues/230

And KubeSphere's support to dapr will be done through OpenFunction.
