### ISSUE TITLE
Gateway random timeouts

### ISSUE THREAD

**Issue by hangvane** [kubesphere/kubesphere#4839]
**Describe the Bug**

Due to the default strategy of nginx-ingress, the project gateway will create spawn as many processes as cores are detected, which leads to error of

```
Ingress-controller exited with fatal code 2 and cannot be respawned
```

And most requests are assigned to the dead worker, resulting in random timeouts.

this issue can be fixed by pinning the worker processes to a lower value like 2x or 4x via config file as default config:

```
worker-processes: 4
```

or add some warning tips for the hosting machine with many cores, when enabling the project gateway.

Reference: https://github.com/kubernetes/ingress-nginx/issues/6141

**Versions Used**
KubeSphere: 3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

Ubuntu 18.04
Intel Xeon Gold 5118*2 (64 threads)
RAM 64G
single node with Kubesphere ALL-IN-ONE install

**How To Reproduce**
1. ALL-IN-ONE install Kubesphere on the host machine with many cores.
2. Run a http server as service, e.g., nginx:latest, e.g., kennethreitz/httpbin:latest
3. Enable the project gateway, map the http service to gateway, obtain the domain as "xxx.xx.192.168.xx.xx.nip.io:30000".
4. Execute command ``curl xxx.xx.192.168.xx.xx.nip.io:30000`` for many times, most of the requests are stucked, some of them are responsed.
5. Many errors are listed in project gateway controller
```
Ingress-controller exited with fatal code 2 and cannot be respawned
```
6. Disable the project gateway. Re-enable the project gateway with config option ``worker-processes: 4``.
7. Again, execute command ``curl xxx.xx.192.168.xx.xx.nip.io:30000`` for many times, all of the requests are responsed and the issue is fixed.

**Expected behavior**
As described.

**Comment by calvinyv** [comment]
maybe this issue is cased by the hard code parm podPidsLimit as 1000 from kubekey, kk will fix it in next version.
