### ISSUE TITLE
the document's description is wrong

### ISSUE THREAD

**Issue by shaly** [kubesphere/kubesphere#4842]
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. Go to 'https://kubesphere.io/docs/quick-start/create-workspace-and-project/'
2. Click on '[Create Workspaces, Projects, Users and Roles](https://kubesphere.io/docs/quick-start/create-workspace-and-project/)'
3. Scroll down to 'Step 1: Create a user'
![image](https://user-images.githubusercontent.com/20148706/166720724-9ce72a40-dbd9-4a22-86dd-fbe6c38b3159.png)

**Expected behavior**
The document's description is wrong. Seeing the picture detail.

**Comment by VioZhang** [comment]
The description is suitable for the" Account" rather than the "Role",and it means that what is the influence of the account.
It is surely a little confusing for the new,and we can make some enhancement./cc @kubesphere/sig-docs 
We also look forword to your idea.

**Comment by Bettygogo2021** [comment]
Hi, guys. This issue has been fixed in https://github.com/kubesphere/website/pull/2428. Pls check whether it works.
