### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#4843]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/68640256/166852693-da120071-7058-47c9-b6b1-605278e5cc5d.png)

**Versions Used**
KubeSphere:   `v3.3.0-alpha.2`

/priority high
/assign @kubesphere/sig-docs

**Comment by Patrick-LuoYu** [comment]
Resolved in [#3241](https://github.com/kubesphere/console/pull/3241).

**Comment by wenxin-01** [comment]
issue fixed in `master`

![image](https://user-images.githubusercontent.com/68640256/168197822-052b6b83-fb6a-4a86-9470-c0f8215e6db4.png)

![image](https://user-images.githubusercontent.com/68640256/168197882-fba7229c-86b2-4aa1-b55f-9caad47b37a6.png)
