### ISSUE TITLE
Can notification-Manager for Kubespherev3.2.1 be upgraded to 2.0? How to upgrade?

### ISSUE THREAD

**Issue by Changego** [kubesphere/kubesphere#4848]
Hello, excuse me！

Can notification-Manager for Kubespherev3.2.1 be upgraded to 2.0? How to upgrade?

**Comment by wanjunlei** [comment]
First, apply all files in `https://github.com/kubesphere/notification-manager/tree/v2.0.0/helm/crds`.

Second, update Notification Manage using helm

```
helm upgrade notification-manager --create-namespace -n kubesphere-monitoring-system https://github.com/kubesphere/notification-manager/releases/download/v2.0.0/notification-manager.tgz --set kubesphere=true
```
