### ISSUE TITLE
Interface request error

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#4850]
**Describe the bug**
Request URL: `/kapis/clusters/host/terminal.kubesphere.io/v1alpha2/namespaces/kubesphere-controls-system/pods/kubectl-admin-6667774bb-4mbnw/exec?container=kubectl&shell=bash`

![image](https://user-images.githubusercontent.com/68640256/167075058-d029cdcb-cb7c-450e-8fa2-08b188881548.png)
![image](https://user-images.githubusercontent.com/68640256/167075131-95882038-a8fd-4ea0-bcce-f0fef466442f.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:   `v3.3.0-alpha.2`

/priority medium
/assign @kubesphere/sig-console  @xyz-li

**Comment by weili520** [comment]
This request is to confirm that the bash terminal is supported within the container.

**Comment by wenxin-01** [comment]
issue fixed in `v3.3.0-rc.0`
![image](https://user-images.githubusercontent.com/68640256/170221431-227b486a-56b1-40c9-980e-5b81f4feed6d.png)
