### ISSUE TITLE
No traffic information in service details of Service Topology

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#4854]
**Describe the Bug**

As shown, no traffic information in service details of Service Topology. but in fact, this service have traffic information.

![image](https://user-images.githubusercontent.com/68640256/167106394-5fa70cde-2de5-4a52-8051-b845d34641d7.png)

![image](https://user-images.githubusercontent.com/68640256/167106534-e7e4b709-fd3e-4b52-92b4-966a7e4fd702.png)

**Versions Used**
KubeSphere:   `v3.3.0-alpha.2`

/priority high
/assign @weihongzhoulord

**Comment by renyunkang** [comment]
It's similar to https://github.com/kubesphere/console/issues/3103

**Comment by weihongzhoulord** [comment]
> **Describe the Bug**
> 
> As shown, no traffic information in service details of Service Topology. but in fact, this service have traffic information.
> 
> ![image](https://user-images.githubusercontent.com/68640256/167106394-5fa70cde-2de5-4a52-8051-b845d34641d7.png)
> 
> ![image](https://user-images.githubusercontent.com/68640256/167106534-e7e4b709-fd3e-4b52-92b4-966a7e4fd702.png)
> 
> **Versions Used** KubeSphere: `v3.3.0-alpha.2`
> 
> /priority high /assign @weihongzhoulord

This is the result of the default configuration. The display of the  traffic information and topology map is turned off by default because it is too resource-intensive. If you need to turn it on, you can do so by https://github.com/kubesphere/console/issues/3103#issuecomment-1120182234
