### ISSUE TITLE
FEAT: admin user should be of the capability to activate a `Login restricted` user.

### ISSUE THREAD

**Issue by xyz-li** [kubesphere/kubesphere#4857]
**What's it about?**

Admin user should be of the capability to activate a `Login restricted` user.

**What's the reason why we need it?**

If a user's status is `Login restricted`, even the admin can't activate the user. 

**Area Suggestion**

/area iam

/kind feature-request
/cc @wansir

**Comment by wansir** [comment]
Login record stored in etcd is not a good choice, it is time to change it.
