### ISSUE TITLE
应用商城上传应用le，里面没有helm的values配置

### ISSUE THREAD

**Issue by sxxpqp** [kubesphere/kubesphere#4863]
描述错误
确定开启了
openpitrix:
    store:
      enabled: true
后台查看日志表示安装成功，但是没有看到应用商城的工作负载
应用商城上传应用，里面没有helm的values配置，

使用的版本
KubeSphere：3.2.0
Kubernetes：19.16

环境
节点数量及其硬件配置：
一个主机集群和三个成员集群，每个集群有4个节点。

如何重现
重现行为的步骤：

打开系统工作区
打开 user-system企业空间
选择“应用管理”->“应用模板”
![image](https://user-images.githubusercontent.com/47712570/167445720-6312544a-4159-417e-a3a5-396d35bbea0e.png)
![image](https://user-images.githubusercontent.com/47712570/167445844-4e0715ac-805a-407a-8296-2acfa8a0ff1b.png)
一个上传成功，显示没有安装和发布按钮，以前上传成功的，配置文件没有values。
自己通过ks-install删除后并重新安装，安装日志显示正常安装。还是没有看到应用商城对应的工作负载。

**Comment by xyz-li** [comment]
helm chart使用helm package 还是 tar 打包的？

**Comment by sxxpqp** [comment]
helm package 打的包
![image](https://user-images.githubusercontent.com/47712570/167539411-6b6d6ff3-2214-4a83-9670-81c6d9179435.png)

**Comment by sxxpqp** [comment]
搭建好的时候是可以用的，以前上传的配置都没有了
![image](https://user-images.githubusercontent.com/47712570/167539637-96d4f09e-5eb3-43fa-b30c-3b5e03a2b6d8.png)

**Comment by sxxpqp** [comment]
![image](https://user-images.githubusercontent.com/47712570/167545635-80eeff86-5a3c-4f85-b01e-b02e5b7efbbd.png)

**Comment by xyz-li** [comment]
你看一下你的 minio是不是正常的。
```  kubectl exec -ti -n kubesphere-system  $(kubectl get po -n kubesphere-system -l app=minio -oname)  -- ls /data```

**Comment by sxxpqp** [comment]
kubectl exec -ti -n kubesphere-system $(kubectl get po -n kubesphere-system -l app=minio -oname) -- ls /data
没有显示数据




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubesphere/kubesphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 中午1:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubesphere/kubesphere] 应用商城上传应用le，里面没有helm的values配置 (Issue #4863)





 
你看一下你的 minio是不是正常的。
   kubectl exec -ti -n kubesphere-system  $(kubectl get po -n kubesphere-system -l app=minio -oname)  -- ls /data

**Comment by xyz-li** [comment]
执行kubectl get po -n kubesphere-system -l app=minio -oname  有没有pod.

如果有pod 执行 `kubectl exec -ti -n kubesphere-system $(kubectl get po -n kubesphere-system -l app=minio -oname) -- mkdir -p /data/app-store`

**Comment by sxxpqp** [comment]
/ # kubectl get po -n kubesphere-system -l app=minio -oname
pod/minio-f69748945-4mt9x 这个看到的pod





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubesphere/kubesphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 下午2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubesphere/kubesphere] 应用商城上传应用le，里面没有helm的values配置 (Issue #4863)





 
执行kubectl get po -n kubesphere-system -l app=minio -oname  有没有pod.
 
如果有pod 执行 kubectl exec -ti -n kubesphere-system $(kubectl get po -n kubesphere-system -l app=minio -oname) -- mkdir -p /data/app-store

**Comment by sxxpqp** [comment]
/ # kubectl get po -n kubesphere-system -l app=minio -oname
pod/minio-f69748945-4mt9x 有显示pod





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubesphere/kubesphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 下午2:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubesphere/kubesphere] 应用商城上传应用le，里面没有helm的values配置 (Issue #4863)





 
执行kubectl get po -n kubesphere-system -l app=minio -oname  有没有pod.
 
如果有pod 执行 kubectl exec -ti -n kubesphere-system $(kubectl get po -n kubesphere-system -l app=minio -oname) -- mkdir -p /data/app-store

**Comment by xyz-li** [comment]
那就是 app-store的目录不存在。 你可以看一下ks-installer 是不是有错误输出。 
或者在 minio中创建 /data/app-store目录

**Comment by sxxpqp** [comment]
没有报ks-installer错误输出。
通过 minio中创建 /data/app-store目录测试正常了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubesphere/kubesphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 下午2:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubesphere/kubesphere] 应用商城上传应用le，里面没有helm的values配置 (Issue #4863)





 
那就是 app-store的目录不存在。 你可以看一下ks-installer 是不是有错误输出。
 或者在 minio中创建 /data/app-store目录

**Comment by xyz-li** [comment]
你是通过修改 ClusterConfiguration 来更改配置么？

**Comment by sxxpqp** [comment]
不是，直接minio创建的目录




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubesphere/kubesphere"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月10日(星期二) 下午4:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubesphere/kubesphere] 应用商城上传应用le，里面没有helm的values配置 (Issue #4863)





 
你是通过修改 ClusterConfiguration 来更改配置么？

**Comment by xyz-li** [comment]
> 你是通过修改 ClusterConfiguration 来更改配置么？

我说安装app-store的时候， 是修改 ClusterConfiguration 而不是 configmap
