### ISSUE TITLE
The terminal is frequently reset

### ISSUE THREAD

**Issue by knowwinter** [kubesphere/kubesphere#4867]
**Describe the Bug**
The terminal is frequently reset
It is reset once in about 20 seconds
The experience was terrible
The link in the screenshot will be executed regularly, which feels like a heartbeat, but as soon as the execution session is reset 
This is a bug?
Or Where can I set the timeout？
I hope not to reset or disconnect the container terminal for at least half an hour
I used nginx as domain name reverse proxy
This is my conf

map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

upstream ks_web {
   server 192.168.12.118:30880 weight=2;
    server 192.168.12.119:30880 weight=10;
    server 192.168.12.120:30880 weight=10;
}

server {
    listen 80;
    server_name ks.meetsocial.cn;
    rewrite ^(.*)$ https://${server_name}$1 permanent;
}

server {
    listen 443 ssl;
    server_name ks.meetsocial.cn;
    index index.html index.htm index.php;
    ssl_certificate /etc/nginx/cert/meetsocial.cn.crt;
    ssl_certificate_key /etc/nginx/cert/meetsocial.cn.key;
    ssl_protocols TLSv1.1 TLSv1.2;
    ssl_ciphers '!aNULL:kECDH+AESGCM:ECDH+AESGCM:RSA+AESGCM:kECDH+AES:ECDH+AES:RSA+AES:';
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    access_log /services/weblogs/ks.access.log main;
    error_log  /services/weblogs/ks.error.log;
    location / {
            proxy_pass http://ks_web;
            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Real-PORT $remote_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            client_max_body_size 512m;
            proxy_connect_timeout 3600;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_send_timeout 3600;
            proxy_read_timeout 3600;
            proxy_buffering off;
            proxy_request_buffering off;
    }
}
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/25719964/167673891-069e349d-6e3e-46b0-84d5-94e7f48beb7a.png">

**Comment by rxf113** [comment]
the same problem

**Comment by rxf113** [comment]
> 同样的问题

经过确认，是网关代理 websocket 超时的问题，不是ks的问题

**Comment by kit101** [comment]
> > 同样的问题
> 
> 经过确认，是网关代理 websocket 超时的问题，不是ks的问题

你好，我也是使用 kubespher的集群网关，创建ks-console的ingress，应该怎么处理呢？
这是我在社区论坛发的详细描述：[集群网关，创建ks-console的路由](https://ask.kubesphere.io/forum/d/23075-ji-qun-wang-guan-chuang-jian-ks-consolede-lu-you-ingressrong-qi-zhong-duan-he-kubectlgong-ju-wu-fa-jia-zai)

**Comment by rxf113** [comment]
> > > 同样的问题
> > 
> > 
> > 经过确认，是网关代理 websocket 超时的问题，不是ks的问题
> 
> @rxf113 你好，我也是使用 kubespher的集群网关，创建ks-console的ingress，**容器终端总是无法进入或进入后一会儿就断开**，只能刷新。请教一下你是怎么处理的？ 这是我在社区论坛发的详细描述：[集群网关，创建ks-console的路由](https://ask.kubesphere.io/forum/d/23075-ji-qun-wang-guan-chuang-jian-ks-consolede-lu-you-ingressrong-qi-zhong-duan-he-kubectlgong-ju-wu-fa-jia-zai)

我们是因为网关(apisix)的超时时间太短了引起的，后面增大了超时时间解决的
