### ISSUE TITLE
 scroll behavior for subpage does not work

### ISSUE THREAD

**Issue by y0n1g** [kubesphere/kubesphere#487]
**General remarks**
As seen below, I was trying to put information for the subpage, but the scrolling bar does not work for the foreground subpage but only works on the background page.
 
![image](https://user-images.githubusercontent.com/9443988/59815581-93063a80-934b-11e9-8e51-fda08e4a5c6d.png)

**Describe the bug(描述下问题)**
As seen above

For UI issues please also add a screenshot that shows the issue.
As seen above

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere:2.0.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce(复现步骤)**
It can be easily met in my environment.
Chrome on a Mac.
Many "information filling subpage" has such issue.

**Expected behavior(预期行为)**
When the subpage is shown on the foreground for more information, it should support to scroll up and down, especially when the focus was on the foreground subpage, but not the background main page.

**Comment by minghaoye** [comment]
Can you provide the Chrome and mac os version information?
it might be a special bug in mac chrome, you can update your chrome to try (74.0.3729.169 (Official Build) (64-bit) not show this bug)

The next version we will do some processing to avoid

**Comment by y0n1g** [comment]
Environment: 
Chrome: 75.0.3770.100 64-bit
Mac: 10.14.5
