### ISSUE TITLE
Unable to access the shell of  edge node

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#4875]
**Describe the Bug**
As the title, the shell terminal of the edge node cannot be accessed. And there is no monitoring information of edge nodes.

![image](https://user-images.githubusercontent.com/68640256/168228304-1ac99f98-4429-47f0-aad4-146ad9901e26.png)

![image](https://user-images.githubusercontent.com/68640256/168228303-45d17e53-c988-41d1-b36d-cd21f0781edd.png)

**Versions Used**
KubeSphere:   `nightly-20220510`

/priority high
/assign @wenchajun

**Comment by jioce** [comment]
issue fiixed in v3.3.0-rc.0
1、After deployment, enter the `/etc/kubeedge/config/edgecore.yaml` file to view, modify `edgestream`, and change false to true
2、Then restart edgecore.service（systemctl restart edgecore.service）
