### ISSUE TITLE
After installing v3.2.1, I can't find openldap.svc in kubesphere-system

### ISSUE THREAD

**Issue by Gkirito** [kubesphere/kubesphere#4883]
**What's your question**
After installing `v3.2.1`, I can't find `openldap.svc` in `kubesphere-system`.
It cause `jenkins-dashboard` login error & store apps deploy error(because of ks-controller-manager startup failed)

**Environment: OS & Hardware Information**
Kubernetes: v1.21.9
AWS-eks

**Error logs or message (Attach logs or screenshot)**
![image-20220517OwmXx4aI@2x](https://user-images.githubusercontent.com/24670858/168751403-2e0228c2-11be-4c31-82ba-0d9fbc090a28.png)

![image-202205175aCoxNKV@2x](https://user-images.githubusercontent.com/24670858/168753351-8509502c-6103-4ad9-8597-6579019cbda7.png)

ks-controller-manager error log:
``` go
W0517 07:14:28.254071       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.

 E0517 07:14:28.283123       1 server.go:101] failed to connect to ldap service, please check ldap status, error: factory is not able to fill the pool: LDAP Result Code 200 "Network Error": dial tcp: lookup openldap.kubesphere-system.svc on xxxxxx:53: no such host
```

develop-jenkins error log 
```java
Caused: org.acegisecurity.AuthenticationServiceException: Unable to connect to LDAP server; nested exception is javax.naming.CommunicationException: openldap.kubesphere-system.svc:389 [Root exception is java.net.UnknownHostException: openldap.kubesphere-system.svc]; nested exception is org.acegisecurity.ldap.LdapDataAccessException: Unable to connect to LDAP server; nested exception is javax.naming.CommunicationException: openldap.kubesphere-system.svc:389 [Root exception is java.net.UnknownHostException: openldap.kubesphere-system.svc]
```

ks-installer
![image-20220517zZdfAaH4@2x](https://user-images.githubusercontent.com/24670858/168753064-c3d47e44-7f2c-4839-aa5f-894674f17aaa.png)

**Installer Version**

v3.2.1

**Comment by xyz-li** [comment]
Can you provide the log of ks-installer?

**Comment by Gkirito** [comment]
> Can you provide the log of ks-installer?

OK, This
[ks-installer.log](https://github.com/kubesphere/kubesphere/files/8715112/logs.log)

**Comment by Gkirito** [comment]
More detail 
I found using `helm list` to get the status of `ks-openldap` is deployed
![image-20220518mAHtjJYr@2x](https://user-images.githubusercontent.com/24670858/169011283-0fe901a1-3614-47a2-b859-9cfe5723d89d.png)
Also, There has a config map and a secret about `openldap` in the namespace of `kubesphere-system`
![image-20220518HCfu2yZ9@2x](https://user-images.githubusercontent.com/24670858/169012046-ef3339d1-599a-4f08-ab9c-591683328427.png)
But, It's still not found a stateful set and a service whose name is ks-openldap

**Comment by pixiake** [comment]
I found the service file of openldap is also in the chart of openldap.
https://github.com/kubesphere/ks-installer/blob/7bcde55add17891c4d83e00db8fb16aa40b96557/roles/common/files/openldap-ha/templates/statefulset.yaml#L1

The openldap's service is `headless services`, Is there a special setting in your cluster that prevents `headless services` from being created?

You can try to delete the `status.openldap` from the ClusterConfiguration and restart the ks-installer, which will automatically reinstall openldap.

**Comment by Gkirito** [comment]
> I found the service file of openldap is also in the chart of openldap. https://github.com/kubesphere/ks-installer/blob/7bcde55add17891c4d83e00db8fb16aa40b96557/roles/common/files/openldap-ha/templates/statefulset.yaml#L1
> 
> The openldap's service is `headless services`, Is there a special setting in your cluster that prevents `headless services` from being created?
> 
> You can try to delete the `status.openldap` from the ClusterConfiguration and restart the ks-installer, which will automatically reinstall openldap.

Thanks for your reply.
I check my cluster setting, not found any settings about preventing `headless services` from being created.
And I tried the plan you provided, It's still nothing happened.
Then I found this [code](https://github.com/kubesphere/ks-installer/blob/73e20baddf715f8b16027a6fca4b419c12590e79/roles/common/tasks/openldap-install.yaml#L41) in `ks-installer` repo.
Maybe using `helm` to get status is not a good idea, because I found `helm` using secret content to confirm the status was deployed.
![image-20220519CnHOsmsW@2x](https://user-images.githubusercontent.com/24670858/169201873-30965496-49d2-4f7a-b072-24927b7f5a24.png)
So I use `helm uninstall ks-openldap --namespace kubesphere-system`, and then tried your plan again, and it appeared.
But it still has some error
![image-20220519UqJh1reg@2x](https://user-images.githubusercontent.com/24670858/169202518-1846eb60-48f9-4cb5-b774-cd28f70d8775.png)
I will follow up

**Comment by wansir** [comment]
> > I found the service file of openldap is also in the chart of openldap. https://github.com/kubesphere/ks-installer/blob/7bcde55add17891c4d83e00db8fb16aa40b96557/roles/common/files/openldap-ha/templates/statefulset.yaml#L1
> > The openldap's service is `headless services`, Is there a special setting in your cluster that prevents `headless services` from being created?
> > You can try to delete the `status.openldap` from the ClusterConfiguration and restart the ks-installer, which will automatically reinstall openldap.
> 
> Thanks for your reply. I check my cluster settings, not found any settings about preventing `headless services` from being created. And I tried the plan you provided, It's still nothing happened. Then I found this [code](https://github.com/kubesphere/ks-installer/blob/73e20baddf715f8b16027a6fca4b419c12590e79/roles/common/tasks/openldap-install.yaml#L41) in `ks-installer` repo. Maybe using `helm` to get status is not a good idea, because I found `helm` using secret content to confirm the status was deployed. ![image-20220519CnHOsmsW@2x](https://user-images.githubusercontent.com/24670858/169201873-30965496-49d2-4f7a-b072-24927b7f5a24.png) So I use `helm uninstall ks-openldap --namespace kubesphere-system`, and then tried your plan again, and it appeared. But it still has some error ![image-20220519UqJh1reg@2x](https://user-images.githubusercontent.com/24670858/169202518-1846eb60-48f9-4cb5-b774-cd28f70d8775.png) I will follow up

You can change the log level from `warning` to `debug` by editing the LDAP statusfulset. Usually related to issues of storage.

**Comment by Gkirito** [comment]
> > > I found the service file of openldap is also in the chart of openldap. https://github.com/kubesphere/ks-installer/blob/7bcde55add17891c4d83e00db8fb16aa40b96557/roles/common/files/openldap-ha/templates/statefulset.yaml#L1
> > > The openldap's service is `headless services`, Is there a special setting in your cluster that prevents `headless services` from being created?
> > > You can try to delete the `status.openldap` from the ClusterConfiguration and restart the ks-installer, which will automatically reinstall openldap.
> > 
> > 
> > Thanks for your reply. I check my cluster settings, not found any settings about preventing `headless services` from being created. And I tried the plan you provided, It's still nothing happened. Then I found this [code](https://github.com/kubesphere/ks-installer/blob/73e20baddf715f8b16027a6fca4b419c12590e79/roles/common/tasks/openldap-install.yaml#L41) in `ks-installer` repo. Maybe using `helm` to get status is not a good idea, because I found `helm` using secret content to confirm the status was deployed. ![image-20220519CnHOsmsW@2x](https://user-images.githubusercontent.com/24670858/169201873-30965496-49d2-4f7a-b072-24927b7f5a24.png) So I use `helm uninstall ks-openldap --namespace kubesphere-system`, and then tried your plan again, and it appeared. But it still has some error ![image-20220519UqJh1reg@2x](https://user-images.githubusercontent.com/24670858/169202518-1846eb60-48f9-4cb5-b774-cd28f70d8775.png) I will follow up
> 
> You can change the log level from `warning` to `debug` by editing the LDAP statusfulset. Usually related to issues of storage.

Yea, I change the log level to `debug`. Unfortunatly this may not be easy to solve.
This is log
![image-20220519FA6kbyLr@2x](https://user-images.githubusercontent.com/24670858/169222085-f3cee2b3-a428-4ab2-9a47-f7819012e500.png)
I tried to change the env value of `HOSTNAME` from `$(MY_POD_NAME).openldap` to `$(MY_POD_NAME)`. It started normally. But other services still couldn't connect to `ks-openldap`
Btw, I using ipv6 in my cluster
And I found some issues from image repo([osixia/openldap](https://github.com/osixia/docker-openldap))
[#515](https://github.com/osixia/docker-openldap/issues/515)
[#252](https://github.com/osixia/docker-openldap/issues/252)

**Comment by Gkirito** [comment]
Finally, I built an `openldap` image base on [#252](https://github.com/osixia/docker-openldap/issues/252).
And the `ks-openldap` service runs normally with this image in the ipv6 environment

**Comment by Gkirito** [comment]
hello, Is this a bug of openldap in ipv6 cluster?
