### ISSUE TITLE
Storage Volume Expansion Fails After Editing the Auto Expansion Maximum Value

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4887]
**Describe the Bug**
1、There is a storage type csi-qingcloud, automatic expansion is enabled, the maximum value is 20, the threshold is 99%, and the increment is 10，auto-restart workload is turned on
2、There is a csi-qingcloud type storage volume test-zy that has been mounted to the workload. It has been expanded once and its size is 20，the storage volume usage is still greater than the threshold
3、Go to the storage type details page, click More operations - "Set automatic expansion, and modify the maximum value to 30.
4、After a period of time, the storage volume test-zy has been expanding
![image](https://user-images.githubusercontent.com/88183150/169232507-60be21f4-d8ea-4f54-a231-628ee54e1e92.png)

![image](https://user-images.githubusercontent.com/88183150/169232549-e51fe984-1c05-4321-bf74-7ac3c64f61e8.png)

![image](https://user-images.githubusercontent.com/88183150/169232634-43c8be7e-d699-40ab-ae99-d91ff7549015.png)

**Versions Used**
KubeSphere: v3.3.0-rc.0

**Expected behavior**
The storage volume can be expanded to 30

/kind bug
/priority medium
/assign @f10atin9

**Comment by f10atin9** [comment]
When I tried to reproduce it, I found that the second time resize failed because of a timeout.

**Comment by f10atin9** [comment]
auto-resizer and auto-restarter are working properly.

**Comment by f10atin9** [comment]
I tried many times and never had the error described before.

**Comment by jioce** [comment]
issue is fixed 
![image](https://user-images.githubusercontent.com/88183150/170909970-15b94cfe-fae0-4372-91c1-0d0024b9c09d.png)

version used
kubespheredev/ks-installer: nightly-0525
