### ISSUE TITLE
Prometheus storage how to modify cephfs storage

### ISSUE THREAD

**Issue by xiaolidw23456** [kubesphere/kubesphere#4893]
**Describe the Bug**
How to modify the storage of Prometheus in KS.
For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:V3.1.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:
CentOS 7.9/6 host: 4cpu / 8g; 6 nodes
For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. Adding configuration to CRD resource object of Prometheus cannot take effect.

**Expected behavior**

**Comment by xyz-li** [comment]
Prometheus uses the default storage class the create PVC. Is the cephfs storage a default storage class?
