### ISSUE TITLE
应用商店安装应用的时候提示未找到，但是实际上已经执行成功了！

### ISSUE THREAD

**Issue by shanyl2021** [kubesphere/kubesphere#4897]
安装应用选择项目的时候，没法选择，安装应用的时候提示未找到，但是实际上已经执行成功了！
![1cfd524e514b9487ede536700f139ff](https://user-images.githubusercontent.com/50799015/169644812-d5a20475-bc40-4617-a7a3-ff79e9f4427c.png)

![59dc7a1edc6b816817b239fd60bf6b8](https://user-images.githubusercontent.com/50799015/169644823-c641b7a7-cb08-4adf-81c3-732d9bd67bcc.png)

**Comment by xyz-li** [comment]
area/apps

**Comment by xyz-li** [comment]
Is there a namespace in the workspace `work-spaces`?

**Comment by shanyl2021** [comment]
![image](https://user-images.githubusercontent.com/50799015/169732239-ef57a81f-439b-4552-84ad-70c1725a925a.png)

这里选择项目的时候，没法选择需要手动输入!


![59dc7a1edc6b816817b239fd60bf6b8](https://user-images.githubusercontent.com/50799015/169732301-0b924fe9-c75d-4e9b-a3e6-c7eb248dd22c.png)
这里点击install安装软件提示这个报错，但实际上已经安装成功了！

**Comment by shanyl2021** [comment]
谢谢！已经解决了
