### ISSUE TITLE
Applications deployed through Helm do not support serviceMesh？

### ISSUE THREAD

**Issue by suwliang3** [kubesphere/kubesphere#4899]

**Comment by xyz-li** [comment]
Have you set the `istio-injection=enabled` label on the namespace?

**Comment by suwliang3** [comment]
@xyz-li What I mean is that the application deployed through the app-store or the app-template does not support the function of  enabling serviceMesh? I don't see a place where serviceMesh can be turned on in kubesphere.Do you mean I need to mamually label ns?
