### ISSUE TITLE
Sample app inaccessible after editing gateway type

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4903]
**Describe the Bug**
1、The gateway has been opened in the project tt, the type is nodeport, and the sample application bookinfo has been deployed
![image](https://user-images.githubusercontent.com/88183150/170169097-c218d32b-b6a9-4506-9083-6b2ba9e92c4f.png)

![image](https://user-images.githubusercontent.com/88183150/170169129-dfc93810-da0f-4373-9300-fcbc3e674b80.png)

2、Access application routing, successful access
![image](https://user-images.githubusercontent.com/88183150/170169224-a1a35626-1684-4806-ac5b-0e2a02a25cfb.png)

3、Edit the project gateway type, change to load balancer, provider is openelb
![image](https://user-images.githubusercontent.com/88183150/170169304-102bd49f-0220-48cc-b67e-958b9fd29bf2.png)

4、Access the application route again, the access fails
![image](https://user-images.githubusercontent.com/88183150/170169642-84d43762-8aec-4c7b-9af0-c965517706a9.png)

![image](https://user-images.githubusercontent.com/88183150/170169505-21a51379-c59f-49e5-a877-275221011470.png)

**Versions Used**
KubeSphere: nightly-20220523

/kind bug
/priority low

**Comment by wenxin-01** [comment]
After change url to  `http://producetpage.tt.192.168.100.91.nip.io:30325/` use gateway address, you can access the new url.
