### ISSUE TITLE
The cluster-admin should be able to do the following

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#4907]
**Versions Used**
KubeSphere:  
host : `kubespheredev/ks-installer:nightly-20220524`
member : `kubespheredev/ks-installer:nightly-20220524`

**Preconditions**
There is a user "wx", its platform role is `Cluster Viewing` , and the role of member cluster is `cluster-admin`.

**Expected behavior**
In my opinion, this user can do the following in member-cluster.

**Actual behavior**

Error when viewing the detail of storage class
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/68640256/170316049-1b779705-e1d4-4b29-be4a-1ca7e99a11c4.png">

Can not setting Cluster Visibility
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/68640256/170316207-68d217e9-7928-4c23-b9c6-23b71d41fea8.png">

**Comment by weili520** [comment]
> /assign

The accessor problem is a frontend issue

**Comment by wenxin-01** [comment]
This issue fixed in 'harrisonliu5/ks-console:master'
![image](https://user-images.githubusercontent.com/68640256/170621594-82d07de3-2ac1-4837-a903-1c5b5c429e18.png)

![image](https://user-images.githubusercontent.com/68640256/170621735-184cc698-68d5-4b27-9d4d-56a32cbc8ce9.png)


But still have other issues.
There is a user wx. its platform role is `cluster-admin`, the role of host-cluster is `cluster-viewing` and the role of member-cluster is `cluster-admin`.
![image](https://user-images.githubusercontent.com/68640256/170624500-bb9f0173-1238-4467-ace6-f729755f935c.png)

![image](https://user-images.githubusercontent.com/68640256/170624501-4d0464fa-5d32-4148-a140-878f612c2701.png)

Can not setting cluster visibility in host and member cluster.

![image](https://user-images.githubusercontent.com/68640256/170624665-8e192312-cac0-46c3-8614-68bac5c61f18.png)

**Comment by wenxin-01** [comment]
Issue fixed in  `console: harrisonliu5/ks-console:css`, and  `kubectl apply -f 
https://raw.githubusercontent.com/kubesphere/ks-installer/632717cdca66a80f89723011c4a521cb2fe45de4/roles/ks-core/prepare/files/ks-init/role-templates.yaml`
