### ISSUE TITLE
The cluster-admin should not be able to remove admin in cluster member

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#4908]
**Versions Used**
KubeSphere:  
host : `kubespheredev/ks-installer:nightly-20220524`
member : `kubespheredev/ks-installer:nightly-20220524`

**Preconditions**
There is a user "wx", its platform role is `Cluster Viewing`, and the role of member cluster is `cluster-admin`.

**Expected behavior**
In my opinion, this user can not remove admin in cluster member.
It is recommended that the front end makes the admin can not be selected.

**Actual behavior**
This user can remove admin in cluster member

https://user-images.githubusercontent.com/68640256/170318023-6f1ff3a7-0492-4334-8960-2bb01207b820.mov

/assign @kubesphere/sig-console  @wansir

**Comment by wansir** [comment]
As expected, administrators of the cluster are equivalent.
