### ISSUE TITLE
ClusterConfiguration missing configuration after cluster upgrade

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4912]
**Describe the Bug**
1、A cluster exists, version 3.2.1, upgrade it to v3.3.0-rc.0
2、View the ClusterConfiguration of the cluster, the configuration is missing
![image](https://user-images.githubusercontent.com/88183150/170442145-101e1846-cedf-4173-9f0b-5721f008fe90.png)

**Versions Used**
KubeSphere: v3.2.1->3.3.0-rc.0

**Expected behavior**
![image](https://user-images.githubusercontent.com/88183150/170442416-a76e5c38-5e67-497e-8374-90fc9154d4c4.png)

/kind bug
/priority medium
/assign @hongzhouzi

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.3`
![image](https://user-images.githubusercontent.com/68640256/176109935-f7cf1f1f-a095-42fc-8b34-b4cb10771391.png)
