### ISSUE TITLE
Some issue in member-cluster console

### ISSUE THREAD

**Issue by wenxinll** [kubesphere/kubesphere#4913]
**Describe the Bug**

**Versions Used**
KubeSphere:

host : `kubespheredev/ks-installer:nightly-20220524`
member : `kubespheredev/ks-installer:nightly-20220524`

1、 The count of worksapce is error
url: `/kapis/monitoring.kubesphere.io/v1alpha3/kubesphere?start=1653544689&end=1653556689&step=600s&times=20&metrics_filter=kubesphere_cluser_count%7Ckubesphere_workspace_count%7Ckubesphere_user_count%7Ckubesphere_app_template_count%24`

![image](https://user-images.githubusercontent.com/68640256/170458278-dd97f7e9-d682-4b65-a9e6-91ee739dfa0f.png)

url: `/kapis/tenant.kubesphere.io/v1alpha3/workspaces?sortBy=createTime&limit=10`
![image](https://user-images.githubusercontent.com/68640256/170458460-b44703aa-cd25-4409-8e71-c4be0009e305.png)

2、Federal project not showing up in the workspace
url: `/kapis/tenant.kubesphere.io/v1alpha2/workspaces/wx-multi/namespaces?labelSelector=kubefed.io%2Fmanaged%21%3Dtrue%2C%20kubesphere.io%2Fkubefed-host-namespace%21%3Dtrue&sortBy=createTime&limit=10`
![image](https://user-images.githubusercontent.com/68640256/170459062-2e9fd53a-724d-4767-8cd6-9b457ae47520.png)

url: `/kapis/resources.kubesphere.io/v1alpha3/namespaces?sortBy=createTime&limit=10&labelSelector=kubesphere.io%2Fworkspace%21%3Dsystem-workspace%2C%21kubesphere.io%2Fdevopsproject`
![image](https://user-images.githubusercontent.com/68640256/170459312-a717fd4a-0cc6-47ca-b217-a75b94fb0b1c.png)

/assign @kubesphere/sig-console

**Comment by wansir** [comment]
Not a valid issue, from the perspective of workspace, federated projects are different from ordinary projects, from the perspective of cluster management, they are the same.
