### ISSUE TITLE
从模板创建应用时添加的应用仓库无法展示内容也无法搜索

### ISSUE THREAD

**Issue by changkang520** [kubesphere/kubesphere#4919]
从模板创建应用时添加的应用仓库无法展示内容也无法搜索，同样的helm仓库在老版本上是可以使用的
![image](https://user-images.githubusercontent.com/27804613/170806627-e0d1f0a5-fe3b-4aef-919a-cd1710f7457e.png)

**Comment by xyz-li** [comment]
This is a bug of v3.2.1. Fixed by #4889.
