### ISSUE TITLE
Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 101.37.163.187:2379: connect: connection refused

### ISSUE THREAD

**Issue by zhaiyh131** [kubesphere/kubesphere#4922]
<img width="1588" alt="image" src="https://user-images.githubusercontent.com/44602981/171115912-d31c3c9e-e4ad-4d69-b006-aed77ca257b0.png">
<img width="961" alt="image" src="https://user-images.githubusercontent.com/44602981/171117833-77d59868-de40-48b0-83a9-5b2724e853bb.png">
两个服务都能ping通，几个端口都开放出来，就是etcd启动报错
大家知道是什么原因吗？

**Comment by xyz-li** [comment]
Is the IP address "101.37.163.187" bound to the machine's network card? 
What is the output of `ip a` on the machine?
