### ISSUE TITLE
Enterprise space to add users can not find the full user

### ISSUE THREAD

**Issue by xuelangos** [kubesphere/kubesphere#4923]
![image](https://user-images.githubusercontent.com/13230347/171142591-207cac33-c10c-4ab8-9f75-ebde5bbae89a.png)
![image](https://user-images.githubusercontent.com/13230347/171142756-64042405-552c-4005-99c1-418447ea1548.png)
env:
kubesphere host cluster,v1.21.5 and v3.2.1,use kubekey create；member cluster，aliyun ack 1.20.x
question:
Enterprise space to add users can not find the full user，OpenLDAP auth.

**Comment by VioZhang** [comment]
Have all the users once logged in the KubeSphere console？The users may not be showed if it never logged in the console.

**Comment by xuelangos** [comment]
> 
yeah，logged in，Now it is normal
