### ISSUE TITLE
failed to edit the default container limitrange when there is a limitrange in namespace.

### ISSUE THREAD

**Issue by yangzan0816** [kubesphere/kubesphere#4929]
问题描述：
编辑默认容器配额时，报pod无法建立默认限制的异常
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/23078733/171349482-30ea4fd8-c644-4d8e-9316-bd3891d08e07.png">
运行环境：
v3.2.1

**Comment by wansir** [comment]
Currently, the limit range created through the UI type always containers, we need to consider about this.

/assign @VioZhang
