### ISSUE TITLE
Enabling servicemesh breaks ks-apiserver and prevents kubeshphere from functioning

### ISSUE THREAD

**Issue by brandan-schmitz** [kubesphere/kubesphere#4934]
### Describe the Bug
When setting enabling the service mesh on a new install (environment details below) the pod created by ks-apiserver fails to start and goes into a crash loop with a runtime error. It should be noted that installation occurs fine and the apiserver runs without issue if the servicemesh is set to false. Installing the servicemesh after the cluster is already running as described in the 
`Enable Pluggable Components` section of the documentation also results in this issue which then breaks the installation.

```
W0601 18:15:22.577233       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0601 18:15:22.581954       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0601 18:15:22.881396       1 interface.go:60] start helm repo informer
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
kubesphere.io/kubesphere/pkg/kapis/servicemesh/metrics/v1alpha2.NewHandler(0xc0009c1d80, 0x41eea38, 0xc0008f2160, 0x41ae580, 0xc000556358, 0xd)
	/workspace/pkg/kapis/servicemesh/metrics/v1alpha2/handler.go:51 +0x57b
kubesphere.io/kubesphere/pkg/kapis/servicemesh/metrics/v1alpha2.AddToContainer(0xc0009c1d80, 0xc000c81320, 0x41eea38, 0xc0008f2160, 0x41ae580, 0xc000556358, 0xc000847ea0, 0x412d800)
	/workspace/pkg/kapis/servicemesh/metrics/v1alpha2/register.go:42 +0xfa
kubesphere.io/kubesphere/pkg/apiserver.(*APIServer).installKubeSphereAPIs(0xc000814000)
	/workspace/pkg/apiserver/apiserver.go:247 +0x12d4
kubesphere.io/kubesphere/pkg/apiserver.(*APIServer).PrepareRun(0xc000814000, 0xc0008ca000, 0xc000814000, 0x0)
	/workspace/pkg/apiserver/apiserver.go:172 +0x171
kubesphere.io/kubesphere/cmd/ks-apiserver/app.Run(0xc000aaf410, 0x4199eb8, 0xc000ac65c0, 0x0, 0x0)
	/workspace/cmd/ks-apiserver/app/server.go:98 +0x8d
kubesphere.io/kubesphere/cmd/ks-apiserver/app.NewAPIServerCommand.func1(0xc0009aef00, 0xc000717c20, 0x0, 0x1, 0x0, 0x0)
	/workspace/cmd/ks-apiserver/app/server.go:60 +0xc6
github.com/spf13/cobra.(*Command).execute(0xc0009aef00, 0xc000136010, 0x1, 0x1, 0xc0009aef00, 0xc000136010)
	/workspace/vendor/github.com/spf13/cobra/command.go:826 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0009aef00, 0x41ad01, 0x0, 0x0)
	/workspace/vendor/github.com/spf13/cobra/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/vendor/github.com/spf13/cobra/command.go:864
main.main()
	/workspace/cmd/ks-apiserver/apiserver.go:29 +0x2a
```

<br>

### Versions Used
KubeSphere: v3.2.1
Kubernetes: v1.24.0 (installed with Kubekey v2.1.1)

<br>

### Environment
1 node running Ubuntu Server 22.04 LTS using the minimal package option upon installation. This is running in a QEMU virtual machine on a Proxmox 7.2 hypervisor host.

VM specs:
2x CPUs with 4 cores each
24GB RAM
500GB HDD

Packages installed prior to kubekey cluster create command:
- socat
- conntrack
- ebtables
- ipset
- qemu-guest-agent

Only other thing done before running the command to create the cluster was to run an apt upgrade for all packages. The VM is about as vanilla as it can get.

<br>

### How To Reproduce
1. Use KubeKey to generate a sample config:
`./kk create config --with-kubernetes v1.24.0 --with-kubespehere v3.2.1`
2. Modify the config to fit your VM. Make sure to add the `containerManager: containerd` to the kubernetes section.
3. Set the networking CNI plugin to flannel
4. Enable the following in order to match what I had enabled:
  - redis
  - openldap
  - alerting
  - auditing
  - devops
  - events
  - logging (set containerruntime to containerd)
  - metrics_server
  - openpitrix store
  - servicemesh
5. Create the cluster with kubekey:
`/kk create cluster -f config-sample.yaml`
6. Monitor installation of kubernetes cluster, once the ks-apiserver deployment is created monitor the logs of that pod. You *should* see the error

<br>

### Expected behavior
I expect that the servicemesh plugin should be installed correctly and that the ks-apiserver deployment should be able to start its pods without the above error preventing Kubesphere from being unusable.

**Comment by xyz-li** [comment]
You need to set feature gate `LegacyServiceAccountTokenNoAutoGeneration=false` in kube-controller-manager.

**Comment by xyz-li** [comment]
After kubernetes v1.24, kube-controller-manager will not generate the default token.
 http://kep.k8s.io/2800

**Comment by brandan-schmitz** [comment]
> You need to set feature gate `LegacyServiceAccountTokenNoAutoGeneration=false` in kube-controller-manager.

That makes sense, I knew they were doing that but have not had time do dig through to code to determine the actual cause of this issue yet. I will just patch my container commands for now (unless there is a better where in Kubekey/kubesphere I do not know about), I assume this will be patched in a future version then?

**Comment by xyz-li** [comment]
Absolute Yes.

**Comment by chinapanpan** [comment]
I have encountered the same issue (kubesphere 3.3.1 on AWS EKS 1.24). however , I can't set feature gate LegacyServiceAccountTokenNoAutoGeneration=false in kube-controller-manager of EKS. 

Is there any solution for my scenario?

**Comment by chinapanpan** [comment]
I have encountered the same issue (kubesphere 3.3.1 on AWS EKS 1.24). however , I can't set feature gate LegacyServiceAccountTokenNoAutoGeneration=false in kube-controller-manager of EKS. 

Is there any solution for my scenario?
