### ISSUE TITLE
Centos7 Open the firewall problem

### ISSUE THREAD

**Issue by Yboos007** [kubesphere/kubesphere#4942]
您好，
       我这里有一个问题，使用的是Centos7服务器，k8s使用的是ipvs网络模式，当我开启iptables防火墙时，Kubesphere的console和apigateway在连接时就会被bad掉
![image](https://user-images.githubusercontent.com/51551864/172124534-e1b4dba4-7c3f-4c73-9e34-68f965f78654.png)
，前端登录不上的情况
![image](https://user-images.githubusercontent.com/51551864/172124449-d5cc74b7-bb4c-4c05-b673-98c2322b517f.png)
，在使用iptables网络模式就不会出现此问题，请问这两个之间网络情况是怎么样的？
谢谢！

**Comment by xyz-li** [comment]
Does the DNS of the cluster work?

**Comment by Yboos007** [comment]
> 集群的DNS工作吗？

Yes, at work.

**Comment by Yboos007** [comment]
> Does the DNS of the cluster work?

Yes, at work.
