### ISSUE TITLE
想问一下kubesphere的登录会话时长是否可以设置？

### ISSUE THREAD

**Issue by oomgomgxx** [kubesphere/kubesphere#4948]

**Comment by wansir** [comment]
@oomgomgxx https://kubesphere.com.cn/docs/access-control-and-account-management/external-authentication/set-up-external-authentication/

**Comment by oomgomgxx** [comment]
> @oomgomgxx https://kubesphere.com.cn/docs/access-control-and-account-management/external-authentication/set-up-external-authentication/

thank～
