### ISSUE TITLE
The node terminal is always showing connecting status

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/kubesphere#4950]
**Describe the Bug**
As I mentioned in the title.

![image](https://user-images.githubusercontent.com/1450685/173035670-b002abd0-fe06-47a8-abaf-16d36b84cab5.png)

**Versions Used**
KubeSphere: v3.3.0-rc.2

**Environment**
How many nodes and their hardware configuration:

* Ubuntu 20.04.4 LTS
* 1 node
* 1 master

**How To Reproduce**
1. Go to cluster management
2. Click on node terminal
3. See the status

**Expected behavior**
The node terminal feature could work well.

**Comment by wansir** [comment]
Related to https://github.com/kubesphere/kubesphere/issues/4875, it seems timeout waiting for the pod to be ready, image pull may cost too much time.

**Comment by LinuxSuRen** [comment]
> 

Is that possible to provide any tips to the users?

**Comment by wansir** [comment]
I suggest pulling the image in advance. @LinuxSuRen  What about the status of the terminal pod in kubesphere-controls-system. I think if the docker image has been pulled, the connection speed will be fast.

**Comment by LinuxSuRen** [comment]
> the terminal pod in kubesphere-controls-system

What the pod's name is?

**Comment by LinuxSuRen** [comment]
By the way, the control works well. See also the following screenshot:

![image](https://user-images.githubusercontent.com/1450685/173048643-9ea1a3b4-f5ad-4e4c-aba7-896bed1a0bd6.png)

**Comment by LinuxSuRen** [comment]
Sometimes, the terminal does not work due to `Could not connect the node. Do you have sufficient privileges?`. It happens often especially when you try to open it after you just installed it.

![image](https://user-images.githubusercontent.com/1450685/173225071-ddfcd4b1-7804-4b1c-82c7-df6e45079038.png)

**Comment by LinuxSuRen** [comment]
I guess this is not a real bug. This issue might be caused by the network being slow. But for those newcomers, the error information is misleading.

/kind-remove bug
/kind improve

**Comment by wenxin-01** [comment]
issue fixed in `ks v3.3.1-rc.0`
