### ISSUE TITLE
`Hooks` is displayed when there is no hook

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/kubesphere#4961]
**Describe the Bug**
test case http://qa.yunify.com/#/tests/case/edit/42674

damonset -> more -> edit settings -> containers -> click the container -> delete the prestop and poststart hooks, but leave the `Lifecycle management` checked -> save

pods restarted, hooks still displayed, mouse on it shows full black with no text

![Screen Shot 2022-06-13 at 09 42 14](https://user-images.githubusercontent.com/70880165/173264863-0c4467a9-8642-4562-bf6c-86222877a43e.png)

![image](https://user-images.githubusercontent.com/70880165/173265179-51132314-086d-4a84-abec-91aa63c52dd5.png)

**Versions Used**
KubeSphere: 3.3 rc2
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.3`
