### ISSUE TITLE
unable to delete the last character of env variable key

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/kubesphere#4962]
**Describe the Bug**
create deployment -> check Environment Variable -> Add Environment Variable -> choose from configmaps (or secrets) -> Enter `fff` as the key -> delete the `fff` key and I want to rename the key to `ggg`  -> delete failed, can not delete the last `f` character

![image](https://user-images.githubusercontent.com/70880165/173270753-34dcbdf0-9bfc-4246-8980-1f1cd9896fbb.png)

**Versions Used**
KubeSphere: 3.3.0 rc2
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.3`
