### ISSUE TITLE
CD syncStatus details page missing View/Edit button as platform-regular role.

### ISSUE THREAD

**Issue by frezes** [kubesphere/kubesphere#4967]
**Describe the Bug**

CD syncStatus details page missing View/Edit button as platform-regular role.
platform role:  platform-regular
workspace role: slef-provisioner
devops project role:  operator

<img width="1412" alt="企业微信截图_5b16c997-f0e6-48ee-97b9-8d57518f237c" src="https://user-images.githubusercontent.com/19492214/173303839-c518af91-18e4-4002-8edd-33fbc0fb4c46.png">

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: v3.3.0-rc.2 

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by frezes** [comment]
fixed in kubespheredev/ks-console:nightly-20220616

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-console:v3.3.0-rc.3`
