### ISSUE TITLE
There are only vda in disk usage details

### ISSUE THREAD

**Issue by fuchunlan** [kubesphere/kubesphere#4969]
**Describe the Bug**
In the KS environment, node A has one data disk, but there are only vda in disk usage details

ks disk usage details：
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/63338728/173307473-b42b4da1-e10c-4425-99d8-09bb6c1d9f78.png">

VM:
![image](https://user-images.githubusercontent.com/63338728/173307472-cb5525f4-0923-461f-a4bf-a01106765380.png)

**Versions Used**
KubeSphere: ks3.3.3-rc.2

**How To Reproduce**
1. Go to 'Cluster Management'
2. Click on 'Node'
3. Click on 'Cluster Nodes'
4. Click on Node name
5. Click on 'Monitoring'
6. Scroll down to 'Disk Usage Details'
7. See error

**Expected behavior**

Show sda Trend data

**Comment by junotx** [comment]
@fuchunlan which directory is the sda mounted ? The node-exporter component may have no read permission for it.

**Comment by fuchunlan** [comment]
Sda has been mounted to the root directory and has no read permission.
This is not a bug

**Comment by junotx** [comment]
It is not recommended to mount the device under the `/root` because it is unreadable by default to non-root users

**Comment by junotx** [comment]
It is not recommended to mount the device under the `/root` because it is unreadable by default to non-root users
