### ISSUE TITLE
安装 Multi-node 报错

### ISSUE THREAD

**Issue by DustFinger001** [kubesphere/kubesphere#497]
**Describe the bug(描述下问题)**
安装到calico插件这一步时报错，master1 的 8080 端口不能访问
使用kubectl get nodes 命令提示 
The connection to the server localhost:8080 was refused - did you specify the right host or port?

![image](https://user-images.githubusercontent.com/16345979/59994723-7b9aba80-9687-11e9-8654-6ede2e9f8b7a.png)

操作系统版本：ubuntu 16.04  用户: ubuntu  sudo 方式安装

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
3 masters:  6cpu/12g
2 nodes: 6cpu/24g

**Expected behavior(预期行为)**
能正确安装

**Comment by DustFinger001** [comment]
我换了root用户安装后这个问题就没出现了。
但是又出现了另外一个问题。
![image](https://user-images.githubusercontent.com/16345979/60007330-ac3d1d00-96a4-11e9-85a1-6861b2400ed5.png)

这个步骤尝试到最后就失败了

**Comment by pixiake** [comment]
这个一般是由于存储配置有问题或者存储服务端不可用造成的，可以检查下是存储的相关配置

**Comment by DustFinger001** [comment]
从dashboard 来看是这个db的pod 挂载卷有问题
![image](https://user-images.githubusercontent.com/16345979/60062589-76dc1200-972c-11e9-8c0a-04e7f74483dc.png)
我使用 nfs-server 启动了一个文件共享服务，然后配置到vars.yml 里了，这样的配置有问题吗？
![image](https://user-images.githubusercontent.com/16345979/60062671-bacf1700-972c-11e9-89ba-1e997527322f.png)

**Comment by DustFinger001** [comment]
已经安装好了，确实是存储的配置问题。
