### ISSUE TITLE
Grey release list page does not show the replica number

### ISSUE THREAD

**Issue by iawia002** [kubesphere/kubesphere#4971]
**Describe the Bug**

<img width="1728" alt="Screen Shot 2022-06-13 at 17 14 47" src="https://user-images.githubusercontent.com/9134003/173322331-63bb77d3-9db7-4648-adba-f66f4874622f.png">

The details page is displayed normally:

<img width="1361" alt="Screen Shot 2022-06-13 at 17 15 08" src="https://user-images.githubusercontent.com/9134003/173322317-2c311a01-a379-4412-a772-3fef2d66e418.png">

**Versions Used**

KubeSphere: v3.3.0-rc.2

Kubernetes: v1.22.1

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by harrisonliu5** [comment]
It is updated from v3.2.1 to v3.3-rc2
