### ISSUE TITLE
Volume snapshots of the deleted volume snapshot class can still create volumes

### ISSUE THREAD

**Issue by renyunkang** [kubesphere/kubesphere#4973]
**Describe the Bug**
Volume snapshots of the deleted volume snapshot class can still create volumes.

**How To Reproduce**
Create volume snapshot classes and volume snapshots normally and view details.
![1655115285724-bd20fc95-d3e2-46d1-9e79-24c3a2a25199](https://user-images.githubusercontent.com/33660223/173336488-34ed7c44-5ee7-4454-b98f-401183c1bac4.png)

![1655115302000-0ed4e943-ac79-4ca2-926f-3622504a7c21](https://user-images.githubusercontent.com/33660223/173336760-c76389e6-7364-488d-b0f9-0ade3df9318b.png)

When the volume snapshot class is deleted and the volume snapshot is not deleted, there is no prompt message on the details page, The volume snapshot cannot be used, only can be deleted.
![1655115330574-d5bc1e56-857c-49b4-badf-c2b22f21c804](https://user-images.githubusercontent.com/33660223/173336842-5386e51f-992d-4c80-9bcc-4e32da0bb7bc.png)

![1655115330574-d5bc1e56-857c-49b4-badf](https://user-images.githubusercontent.com/33660223/173336971-2532e7ef-3e6b-46e8-bac9-d162e71a4868.png)

There is no prompt on the list page, but the volume snapshot can be used, and the volume created by using the volume snapshot reports an error.

![1655115375089-34b352cd-507e-45c3-9079-1e42e8207b56](https://user-images.githubusercontent.com/33660223/173337230-321ff7e2-3135-47f7-b3d0-07cbb7fae6e6.png)

![1655115434467-d7d5cbf9-96c4-45d4-a9da-4b389fc37c35](https://user-images.githubusercontent.com/33660223/173337256-26f8e2d0-8f02-47e0-bfb9-49ee80536e4e.png)

**Expected behavior**
Volume Snapshots `test` cannot be operated on the list page.

**Versions Used**
KubeSphere: v3.3.0-rc.2
Kubernetes: v1.23.7

**Environment**
ubuntu 22.04
Single cluster. Single node

**Comment by renyunkang** [comment]
/kind/bug
/area/console

**Comment by weili520** [comment]
The storage category of the test volume is incorrect. This is the same as this issue #4957.

**Comment by jioce** [comment]
issue is fixed 
![image](https://user-images.githubusercontent.com/88183150/173730003-f4b2ec0f-7640-4c23-a160-39d33776ef66.png)

version used
ks-console: weili520/3.3_fix:v1.0.0

**Comment by jioce** [comment]
issue is fixed
![image](https://user-images.githubusercontent.com/88183150/174563102-84478104-a71b-4dc4-a3a5-070d9c20f476.png)

version used 
kubesphere: v3.3.0-rc.3
