### ISSUE TITLE
typo: Maximum Size

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/kubesphere#4978]
**Describe the Bug**
storage class -> set auto expansion 

the unit of `Maximum Size` should be `Gi` instead of `G`. 

![image](https://user-images.githubusercontent.com/70880165/173476386-30fe04d7-4712-4d5a-9494-02ad96fbd356.png)

**Versions Used**
KubeSphere: 3.3 rc2
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by wenxin-01** [comment]
issue fixed in `v3.3.0-rc.3`
![image](https://user-images.githubusercontent.com/68640256/174555162-64a37405-917b-4b8b-8ad3-2219d1fcaa24.png)
![image](https://user-images.githubusercontent.com/68640256/174555196-ccf6edf0-2076-4898-b3c3-45815a8507af.png)
