### ISSUE TITLE
In devops project, the Continuous Deployments update times  wrong

### ISSUE THREAD

**Issue by ruiyaoOps** [kubesphere/kubesphere#4979]
**Describe the Bug**
In the page of  Continuous Deployments , all Continuous Deployments update times are the last one CD update time.
![image](https://user-images.githubusercontent.com/35256376/173477512-519d0119-5563-48dc-8b87-f7e06d2de11c.png)

**Versions Used**
KubeSphere:  v3.3.0-rc.2 

**Expected behavior**
Each Continuous Deployments have real update time.

**Comment by LinuxSuRen** [comment]
Actually, we didn't have the `update time`. See also the following screenshot:

![image](https://user-images.githubusercontent.com/1450685/173523801-aeac7579-44f3-459e-b534-855706769feb.png)

**Comment by jioce** [comment]
issue is not fixed
![image](https://user-images.githubusercontent.com/88183150/174563494-e424473b-fd73-47f5-ab22-829550e75eaf.png)

version used
kubesphere: v3.3.0-rc.3

**Comment by harrisonliu5** [comment]
![image](https://user-images.githubusercontent.com/17872673/174566242-32761bdb-3ca8-41d6-be61-b40b07fd1c69.png)

@LinuxSuRen It is right?

**Comment by LinuxSuRen** [comment]
Actually, `reconciledAt` is not the update time. I prefer to show this time as `Last Sync  Time`.

/cc @VioZhang @Patrick-LuoYu

**Comment by harrisonliu5** [comment]
But the data of response does not have the `Last Sync Time` value.
