### ISSUE TITLE
The kubectl which is in the "toolbox" can't connect to the container

### ISSUE THREAD

**Issue by 24sama** [kubesphere/kubesphere#4982]
**Describe the Bug**
I have a kubespher multi-cluster enviroment. When I switch the cluster in the kubectl terminal, that will report a privilege error (I only have an admin user).
![image](https://user-images.githubusercontent.com/43993589/173524506-231c6bcd-9779-4133-bb73-875f0d9da307.png)

Then I switch it to my host cluster, it also report this error:
![image](https://user-images.githubusercontent.com/43993589/173524929-16fcf602-9491-4b47-8537-4093df6d6bb2.png)

**Versions Used**
KubeSphere: v3.3.0-rc.2
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
host cluster:
```
ubuntu@node1:~$ kubectl get node -owide
NAME    STATUS   ROLES                         AGE    VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE           KERNEL-VERSION      CONTAINER-RUNTIME
node1   Ready    control-plane,master,worker   3h7m   v1.23.7   192.168.100.3   <none>        Ubuntu 22.04 LTS   5.15.0-25-generic   containerd://1.6.4
```

member cluster:
```
ubuntu@node3:~$ kubectl get node -owide
NAME    STATUS   ROLES                         AGE    VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
node3   Ready    control-plane,master,worker   102m   v1.21.5   192.168.100.5   <none>        Ubuntu 20.04.4 LTS   5.4.0-104-generic   containerd://1.6.4
```

**How To Reproduce**

**Expected behavior**

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.30-rc.3`
