### ISSUE TITLE
multi-cluster failed to upgrade (KubeSphere Host : v3.2.0 -> v3.3.0-rc.2, Member:  v3.1.1 -> v3.2.1)

### ISSUE THREAD

**Issue by swiftrivergo** [kubesphere/kubesphere#4984]
**Describe the Bug**
Via KubeKey to upgrade for multiple-clustrer like the following:
Host-cluster upgrade: KubeSphere from v3.2.0 to v3.3.0-rc.2 (Kubernetes v1.21.5 hold)
Member-cluster upgrade: KubeSphere from from v3.1.1 to v3.2.1 (Kubernetes v1.21.5 hold)
1) There is a issue: "Failed to ansible-playbook result-info.yaml" in logs after all tasks complete.
2) After upgraded, Member-cluster console failed to login, alert: "Wrong username or password, please try again"

**Versions Used**
KubeSphere: v3.2.0 & Kubernetes v1.21.5
KubeSphere: v3.1.1 & Kubernetes v1.21.5

**Expected behavior**
upgrade suceessfuly

**Environment: OS & Hardware Information**
OS: ubuntu-20-04
Host-cluster: Kubernetes v1.21.5, KubeSphere v3.2.0 & CPU 8*core, memory 32GiB, Disk 100GiB, single node
Member-cluster: Kubernetes v1.21.5, KubeSphere v3.1.1 & CPU 8*core, memory 16GiB, Disk 50GiB, single node

**Error logs or message (Attach logs or screenshot)**
1) Host-cluster attachment & screenshot
![image](https://user-images.githubusercontent.com/51448423/173740213-deb6d0d6-eaf2-4e26-8a35-b2114abcf22e.png)

2) Member-Cluster attachment & screenshot
![image](https://user-images.githubusercontent.com/51448423/173741317-b06b227d-96c4-4a52-8db8-fd6a9d095a42.png)
![image](https://user-images.githubusercontent.com/51448423/173741192-54de4b07-295c-42b0-baf6-4049dc92a590.png)

**Installer Version**
KubeKey v2.2.0

**Comment by iawia002** [comment]
> Failed to ansible-playbook result-info.yaml

This needs @pixiake to take a look, I see that the multi-cluster task is executed successfully.

> After upgraded, Member-cluster console failed to login, alert: "Wrong username or password, please try again"

3.2.1 doesn't support logging in to the console of the member cluster and needs to be upgraded to 3.3.0, right? @wansir

**Comment by wansir** [comment]
duplicated https://github.com/kubesphere/kubesphere/issues/4771

**Comment by VioZhang** [comment]
Could you please provide @pixiake with more information ？ @swiftrivergo

**Comment by swiftrivergo** [comment]
@VioZhang 
Right. 
Just right there is an available multiple-cluster envirment:  host kubesphere  v3.2.0 + member v3.2.1 ( kubernetes v1.21.5 ).
Next let me try to upgrade the host cluster for v3.3.0-rc.2 again.

current host cluster's  kubesphere version: v3.2.0
target current host cluster's  kubesphere version: v3.3.0-rc.2

then I will execute like the following:
export KKZONE=cn

./kk upgrade --with-kubernetes v1.21.5 --with-kubesphere v3.3.0-rc.2

**Comment by swiftrivergo** [comment]
Maybe the issue caused when services were not ready due to docker's rate limit reached at that time.
upgrade screenshot:
![image](https://user-images.githubusercontent.com/51448423/173802172-d6f5983f-900c-41cd-afc5-9fdd3bf1fe82.png)
limit:
![image](https://user-images.githubusercontent.com/51448423/173803107-c5d74fae-9f6d-42ae-8786-89bfb8b6ba8e.png)

**Comment by pixiake** [comment]
This error is caused by the abnormal pod status of ks-core components.  It is usually caused by the inability to pull images normally.
