### ISSUE TITLE
Optimize the 'Application governance' parameter on the app details page

### ISSUE THREAD

**Issue by patrickluoyu** [kubesphere/kubesphere#4985]
## General remarks

* Move the 'Application governance' parameter to the 'Details' area because it is configured on the app level.

<img width="1409" alt="image" src="https://user-images.githubusercontent.com/76198553/173770457-c6604f38-a514-4aa4-9065-2bdaa625e282.png">

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/76198553/173770621-bda316e6-c7fd-475b-8efb-2280bb618a55.png">

* Remove the 'Application governance' parameter for template-based apps because template-based apps do not support this feature.

/assign @VioZhang @harrisonliu5

**Comment by wenxin-01** [comment]
issue fixed in `ks v3.3.1-rc.0`
![image](https://user-images.githubusercontent.com/68640256/185355226-d149c11e-d65a-4fb7-9d8c-bf82ccb5c59f.png)
