### ISSUE TITLE
Display the type of each workload on the app details page

### ISSUE THREAD

**Issue by patrickluoyu** [kubesphere/kubesphere#4986]
The 'Workloads' area on the app details page does not show the type of each workload, and users cannot know whether each workload is a deployment, statefulset or daemonset.

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/76198553/173771356-806770ad-04c5-4aab-8461-2eb32c413d6d.png">

/assign @VioZhang @harrisonliu5

**Comment by wenxin-01** [comment]
issue fixed in `ks v3.3.1-rc.0`
![image](https://user-images.githubusercontent.com/68640256/185354665-395ec96e-572a-48f4-8b45-dca2fd4fbc38.png)
