### ISSUE TITLE
Remove the 'App' field on the composed app details page

### ISSUE THREAD

**Issue by patrickluoyu** [kubesphere/kubesphere#4987]
The 'App' field is meaningless and should be removed.

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/76198553/173787998-7ea1d1e7-82cc-44c1-b21f-12be7a5ac1dc.png">

/assign @VioZhang @harrisonliu5

**Comment by wenxin-01** [comment]
issue not  fixed in `ks v3.3.1-rc.0`
![image](https://user-images.githubusercontent.com/68640256/185352096-d9bb3b44-6c37-464e-9997-cd16675940ea.png)

**Comment by jioce** [comment]
issue is fixed in v3.3.1-rc.1
![image](https://user-images.githubusercontent.com/88183150/187132826-34aed420-ea4b-469f-85a2-414a90f27acc.png)
