### ISSUE TITLE
kubesphere.io document 404 not found

### ISSUE THREAD

**Issue by nickfan** [kubesphere/kubesphere#4997]
**Describe the Bug**

https://kubesphere.io/zh/docs/quick-start/all-in-one-on-linux/
404

For UI issues please also add a screenshot that shows the issue.

![image](https://user-images.githubusercontent.com/100613/175862757-a337e6f6-a236-438d-8e10-c5c7cbf7d1e4.png)

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by wansir** [comment]
@nickfan Thanks for your feedback. The broken link has been fixed now.
