### ISSUE TITLE
error when  i update kubesphere from v3.2.1 to v3.3.0

### ISSUE THREAD

**Issue by javaXiaoHan** [kubesphere/kubesphere#5001]
**What's your question**
when i update the ks from v3.2.1 to v3.3.0 
error: Unsupported KubeSphere version: v3.3.0

**Environment: OS & Hardware Information**
centos 7.6  kubesphere 3.2.1

**Error logs or message (Attach logs or screenshot)**

**Installer Version**
kubekey-v2.2.1-linux-amd64.tar.gz
<img width="682" alt="1656319362839" src="https://user-images.githubusercontent.com/32090060/175897893-aa7a6b59-7168-4d14-88e6-5ed3deb7d478.png">

**Comment by javaXiaoHan** [comment]
@24sama haha could you please give me some help

**Comment by 24sama** [comment]
> @24sama haha could you please give me some help

Please use the following command to check the kk version:
```
./kk version
```

**Comment by 24sama** [comment]
> > ./kk version
> 
> version.BuildInfo{Version:"2.0.0", GitCommit:"ff9d30b7", GitTreeState:"", GoVersion:"go1.17.7"}

So, the kk version is not v2.2.1, and it doesn't support ks v3.3.0

**Comment by javaXiaoHan** [comment]
> > > ./kk version
> > 
> > 
> > version.BuildInfo{Version:"2.0.0", GitCommit:"ff9d30b7", GitTreeState:"", GoVersion:"go1.17.7"}
> 
> So, the kk version is not v2.2.1, and it doesn't support ks v3.3.0

kk is 'kubekey-v2.2.1-linux-amd64.tar.gz' this one?
