### ISSUE TITLE
upgrade to v3.3.0 , can't login

### ISSUE THREAD

**Issue by ivanmissu** [kubesphere/kubesphere#5003]
**Describe the Bug**
when i upgrade v3.2.1 to v3.3.0 ，when i login , tip
![image](https://user-images.githubusercontent.com/8721615/176064371-797add17-52d1-438c-8c1f-d08cbe3f9319.png)
i found the ks-apiserver status is CrashLoopBackOff
<img width="745" alt="image" src="https://user-images.githubusercontent.com/8721615/176064458-a883115b-351d-49ff-af65-83f86afd5942.png">
and logs view:
<img width="767" alt="image" src="https://user-images.githubusercontent.com/8721615/176064537-bf107d72-8f4d-4349-96ab-c68ba8547a0b.png">

**Versions Used**
KubeSphere: v3.3.0
Kubernetes: v1.21.5

**Environment**
How many nodes and their hardware configuration:
CentOS7.9  /  2masters: 8c/32g,  2nodes: 8c/32g

**How To Reproduce**
1. Go to kubesphere console, login page.
2. Click on login button
3. See error tip
request to http://ks-apiserver/oauth/token failed, reason: connect ECONNREFUSED 10.233.62.247:80

**Expected behavior**
can login

**Comment by ivanmissu** [comment]
i fix it ,  sorry,  yesterday i add metering config, but when i modify file kubesphere-config, i use tab indentation in file, but i saved success, and i restart ks-apiserver failed, so i can't login successd.   
so, when i modify kubesphere-config, the indentation syntax not match yaml indentation syntax, whether or not tips the indentation syntax is incorrect ??

**Comment by benjaminhuo** [comment]
kubesphere-config is a configmap whose validation is up to Kubernetes itself and not KubeSphere.
Close this for now.
