### ISSUE TITLE
Missing openelb annotation hint when creating service of type loadbalancer

### ISSUE THREAD

**Issue by renyunkang** [kubesphere/kubesphere#5006]
**Describe the Bug**
Missing openelb annotation hint when creating service of type loadbalancer.

![image](https://user-images.githubusercontent.com/33660223/176115120-83cfdfa3-e8fd-4446-b71c-794824939279.png)

It should be like this:
![image](https://user-images.githubusercontent.com/33660223/176147439-5612176d-f953-4db7-8406-4254a7166316.png)

**Versions Used**
KubeSphere: 3.3.0

**Comment by webup** [comment]
This would be really good for OpenELB enabling, because we commonly use OpenELB layer2 mode in private network.

**Comment by nonopanda998** [comment]
![image](https://user-images.githubusercontent.com/38211330/176330011-52165079-bf9e-463e-9152-243e180e9298.png)

**Comment by XiaohuiSept** [comment]
Design：
https://www.figma.com/file/8Ii6Y8PSf7kmcWFdWzaP9Y/OpenELB?node-id=110%3A60355

@renyunkang @weili520

**Comment by jioce** [comment]
Edit external access without openelb annotations
![image](https://user-images.githubusercontent.com/88183150/184815537-de99b2b3-3442-4816-85ba-83bfd206d099.png)

**Comment by jioce** [comment]
Edit service external access, load balancer provider shows error
![image](https://user-images.githubusercontent.com/88183150/187115072-c857df82-19ff-4052-8d15-1d5037ad71be.png)

**Comment by jioce** [comment]
Adding multiple annotations, showing errors
![image](https://user-images.githubusercontent.com/88183150/187117436-25e003c6-4208-4674-853c-8aa21a5fc464.png)

version used：
kubesphere： v3.3.1-rc.1

**Comment by jioce** [comment]
issue is fixed in v3.3.1-rc.2

**Comment by adrianoaguiar** [comment]
> Design： https://www.figma.com/file/8Ii6Y8PSf7kmcWFdWzaP9Y/OpenELB?node-id=110%3A60355
> 
> @renyunkang @weili520

@XiaohuiSept the link https://www.figma.com/file/8Ii6Y8PSf7kmcWFdWzaP9Y/OpenELB?node-id=110%3A60355 is not available to my user figma.

Do you can help me?
