### ISSUE TITLE
workspacetemplates.tenant.kubesphere.io is forbidden

### ISSUE THREAD

**Issue by dafanshu** [kubesphere/kubesphere#5009]
**Describe the Bug**
 
workspacetemplates.tenant.kubesphere.io is forbidden: User "ws-manager" cannot create resource "workspacetemplates" in API group "tenant.kubesphere.io" at the cluster scope

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: 3.3.0
Kubernetes: (If KubeSphere installer used, you can skip this)
--with-kubernetes v1.22.10 --with-kubesphere v3.3.0

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)
Linux dss 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
**How To Reproduce**

**Expected behavior**

**Comment by wenxin-01** [comment]
Same as https://github.com/kubesphere/kubesphere/issues/5013

**Comment by dafanshu** [comment]
thx

**Comment by geray-zsg** [comment]
`kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/release-3.3/roles/ks-core/prepare/files/ks-init/role-templates.yaml`
