### ISSUE TITLE
redhat7.4离线版2.0无法安装成功

### ISSUE THREAD

**Issue by lujs678** [kubesphere/kubesphere#501]
安装的是all-in-one模式
首先发现获取redhat版本脚本不对，没有判断redhat-release文件，只有判断centos-release文件，
这个改了后有新问题
![12384efdc98d035bfb7a2f5175d5fd7](https://user-images.githubusercontent.com/30866140/60096117-bdf4f200-9782-11e9-9ca0-bf0ce1af53a6.jpg)

这个把yum改成在线方式安装也算成功了，但最后还是失败
![b4486e7a951957163d5f322c1472674](https://user-images.githubusercontent.com/30866140/60096183-e67cec00-9782-11e9-91aa-dd996dda62c7.jpg)

**Comment by pixiake** [comment]
从哪下载的安装包，kube-apiserver起来了没有？kubectl get pod --all-namespaces

**Comment by wenhuozhou** [comment]
这里下载的安装包
https://docs.kubesphere.io/advanced-v2.0/zh-CN/installation/all-in-one/
没有起来

**Comment by lujs678** [comment]
这里下载的安装包
https://docs.kubesphere.io/advanced-v2.0/zh-CN/installation/all-in-one/
没有起来

**Comment by pixiake** [comment]
嗯  环境可以远程或者开tv吗？可以的话相关信息可以发到kubesphere@yunify.com

**Comment by eryajf** [comment]
同yum安装包的那个地方出了问题

**Comment by pixiake** [comment]
2.0.0的离线包不支持rhel，我用新的2.0.2的离线包试了下可以部署成功

**Comment by eryajf** [comment]
> 2.0.0的离线包不支持rhel，我用新的2.0.2的离线包试了下可以部署成功

官方似乎没有提供2.0.2的离线包，不知道您是从哪里下载的呢

**Comment by pixiake** [comment]
@eryajf  curl -L https://kubesphere.io/download/offline/advanced-2.0.2 > advanced-2.0.2.tar.gz

**Comment by pixiake** [comment]
> 
> 
> > 2.0.0的离线包不支持rhel，我用新的2.0.2的离线包试了下可以部署成功
> 
> 官方似乎没有提供2.0.2的离线包，不知道您是从哪里下载的呢

 curl -L https://kubesphere.io/download/offline/advanced-2.0.2 > advanced-2.0.2.tar.gz

**Comment by eryajf** [comment]
ok

**Comment by lujs678** [comment]
> > > 2.0.0的离线包不支持rhel，我用新的2.0.2的离线包试了下可以部署成功
> > 
> > 
> > 官方似乎没有提供2.0.2的离线包，不知道您是从哪里下载的呢
> 
> curl -L https://kubesphere.io/download/offline/advanced-2.0.2 > advanced-2.0.2.tar.gz

还是失败了

![微信图片_20190719202106](https://user-images.githubusercontent.com/30866140/61534657-caf3c100-aa62-11e9-9d40-1da0e60d40cc.jpg)

**Comment by lujs678** [comment]
> ok

请问成功了吗？

**Comment by lujs678** [comment]
> ok

请问安装成功了吗

**Comment by eryajf** [comment]
我在当时还没收到离线包的时候，采用了官方给的那个在线安装方式，然后前天晚上跑了一下，第二天看到自动安装成功了，目前在看各种功能什么的，2.0.2的离线包我没有测试安装，或许你可以尝试把环境还原，然后尝试使用在线安装的包

**Comment by lujs678** [comment]
> > > 2.0.0的离线包不支持rhel，我用新的2.0.2的离线包试了下可以部署成功
> > 
> > 
> > 官方似乎没有提供2.0.2的离线包，不知道您是从哪里下载的呢
> 
> curl -L https://kubesphere.io/download/offline/advanced-2.0.2 > advanced-2.0.2.tar.gz

发现好像缺了几个镜像？
sidecar_injector:1.1.1  这个我自己下载解决了，还有个
kubesphere/ks-console:advanced-2.0.2    这个也没有

**Comment by lilinlinlin** [comment]
@lujs678   2.0.2离线版本官网已经发布了。

**Comment by lujs678** [comment]
单机版安装成功了
