### ISSUE TITLE
External services cause the "Services" page to crash

### ISSUE THREAD

**Issue by patrickluoyu** [kubesphere/kubesphere#5010]
**Describe the Bug**
After an external service is created in a project, the "Services" page cannot be displayed.

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/76198553/176390733-42ebbcb5-c5a3-4275-875d-5dfe62f424b9.png">

**Versions Used**
KubeSphere: v3.3.0

**How To Reproduce**
1. Go to a project.
2. On the left navigation bar, select **Application Workloads > Services**.
3. Create an external service (ExternalName). The page cannot be displayed.

**Expected behavior**
The page is displayed properly.

/assign @zheng1 @harrisonliu5

**Comment by jioce** [comment]
issue is fixed in v3.3.1-rc.0
![image](https://user-images.githubusercontent.com/88183150/184824722-0013277a-c530-4408-ad0b-1125fad0ce4a.png)

**Comment by wenxin-01** [comment]
issue fixed in `ks v3.3.1-rc.0`
