### ISSUE TITLE
worksapce-manager cannot create worksapce

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#5013]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/68640256/176576960-7e34e6d2-1def-42cb-8242-c2454703e7e3.png)

![image](https://user-images.githubusercontent.com/68640256/176577053-72ecdb62-ba72-4c26-96d2-7f77f8b6fe52.png)

**Versions Used**
KubeSphere:   `v3.3.0`

**Comment by magitekbay** [comment]
same here,created a user ws-manager,and granted the role workspaces-manager.
![image](https://user-images.githubusercontent.com/88395653/176808205-21662314-6f45-4583-a920-c4e5f7244c95.png)
the admin account works fine.

**Comment by wansir** [comment]
Duplicated: https://github.com/kubesphere/kubesphere/issues/5009, @magitekbay  it can be fixed with the following command:

```
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/release-3.3/roles/ks-core/prepare/files/ks-init/role-templates.yaml
```

**Comment by magitekbay** [comment]
> Duplicated: #5009, @magitekbay it can be fixed with the following command:
> 
> ```
> kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/release-3.3/roles/ks-core/prepare/files/ks-init/role-templates.yaml
> ```

thx,it works.

**Comment by limengcanyu** [comment]
not work, can't down the yaml

https://raw.githubusercontent.com/kubesphere/ks-installer/release-3.3/roles/ks-core/prepare/files/ks-init/role-templates.yaml

**Comment by wenxin-01** [comment]
issue fixed in `ks v3.3.1-rc.0`

**Comment by tankilo** [comment]
> issue fixed in `ks v3.3.1-rc.0`

Is there a hotfix release version or any manually repair solution?

**Comment by wenxin-01** [comment]
> > issue fixed in `ks v3.3.1-rc.0`
> 
> Is there a hotfix release version or any manually repair solution?
The official version has not been released yet, you can temporarily solve it manually.
`kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/release-3.3/roles/ks-core/prepare/files/ks-init/role-templates.yaml`

**Comment by JasonChen86899** [comment]
> > `kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/release-3.3/roles/ks-core/prepare/files/ks-init/role-templates.yaml`
this command not works

**Comment by jiangguoqing** [comment]
not works tooooo,so disappointing......

**Comment by gs80140** [comment]
not work too
