### ISSUE TITLE
User with cluster view role, view storage class details error

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#5017]
**Describe the Bug**
1、There is a role test, the permission is cluster view, create a user cc, assign the test role
2、 cc to log in to the console，click Platform Management - "Cluster Management - "Storage - "Storage Class, click local to view the details, the page reports an error
![image](https://user-images.githubusercontent.com/88183150/176620684-81264285-49b2-436f-acad-89237260ff5e.png)

![image](https://user-images.githubusercontent.com/88183150/176620614-7b93240b-24a8-4426-bb04-0fb1ae8c0937.png)

![image](https://user-images.githubusercontent.com/88183150/176620448-0d6ad736-3a5c-4a5c-bb60-17d244a0c76a.png)

**Versions Used**
KubeSphere: v3.3.0
Kubernetes: v1.22.1

/kind bug
/priority medium
/assign @wansir

**Comment by f10atin9** [comment]
will be updated: when the user clicks the `Set Authorization Rules` button the console will check the existence of the accessor and create it.

**Comment by jioce** [comment]
issue is fixed in v3.3.1-rc.0
