### ISSUE TITLE
some kubesphere function suggestion

### ISSUE THREAD

**Issue by blueftss** [kubesphere/kubesphere#502]
1、增加pvc备份功能。
2、监控中增加对limit的监控。
3、官网docs增加kubectl管理qke的文档。
4、增加etcd数据库、configmap和各种yaml的备份功能。
5、增加审计功能。
6、增加操作日志功能。
7、gitlab、harbor等模块的pvc可以在vars.yml中自定义。
8、qke增加对nfs的ui支持。
9、增加l利用docker-machine driver在不同的云厂商创建kubesphere的集群功能。
10、qke增加备份到qingcloud对象存储的功能。
11、增加cicd日志导出功能和api对接。
12、cpu和vcpu的license策略还需要再优化一下。
13、和第三方对象，可以实现workplace的自动增加label功能。

**Comment by rayzhou2017** [comment]
plan in the versions of KubeSphere
1. 3.0.0
2. no plan
3. a couple of weeks
4. 3.0.0
5. 3.0.0
6. same req as 5
7. 2.1.0
8. no plan
9. no plan
10. 备份什么？
11. 2.1.0
12. 这是商务问题
13. 不清楚这个需求
