### ISSUE TITLE
cluster gateway will automatically turn on when the kubesphere-system project gateway is enabled.

### ISSUE THREAD

**Issue by dalamudx** [kubesphere/kubesphere#5021]
**Describe the Bug**
cluster gateway will automatically turn on when the kubesphere-system project gateway is enabled.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)
v3.3.0

**Environment**
How many nodes and their hardware configuration:
CentOS Linux release 7.9.2009 (Core)
3 master/16C32G
9 nodes/16C32G

**How To Reproduce**
![1656658765-494146-msedge-2022-07-01-14-58-52](https://user-images.githubusercontent.com/88395653/176913258-593ca77e-0e35-4725-935b-19c8ac260f78.gif)

**Expected behavior**
I want to know it is a bug or not

**Comment by iawia002** [comment]
This is not a bug, the cluster gateway and the project gateway are essentially the same thing, the cluster gateway is actually the project gateway for the kubesphere-system namespace, the cluster gateway concept is proposed for ease of use, users can use a single gateway to access all services.

We need to reorganize and unify the two concepts of cluster gateway and project gateway.

**Comment by magitekbay** [comment]
> This is not a bug, the cluster gateway and the project gateway are essentially the same thing, the cluster gateway is actually the project gateway for the kubesphere-system namespace, the cluster gateway concept is proposed for ease of use, users can use a single gateway to access all services.
> 
> We need to reorganize and unify the two concepts of cluster gateway and project gateway.

thx,i see.

**Comment by iawia002** [comment]
No need to close this issue, we can see if there is a better way to unify the cluster gateway and project gateway
