### ISSUE TITLE
kubesphere monitoring  node-exporter  exception  listen tcp 127.0.0.1:9100: bind: address already in use"

### ISSUE THREAD

**Issue by renwayle** [kubesphere/kubesphere#5025]
error egg  
ts=2022-07-03T03:09:24.247Z caller=node_exporter.go:199 level=info msg="Listening on" address=127.0.0.1:9100 
 ts=2022-07-03T03:09:24.247Z caller=node_exporter.go:202 level=error err="listen tcp 127.0.0.1:9100: bind: address already in use"

[root@k8swork3 ~]# netstat  -antp | grep 9100
tcp        0      0 192.168.2.2:9100        0.0.0.0:*               LISTEN      30725/kube-rbac-pro 
tcp        0      0 127.0.0.1:9100          0.0.0.0:*               LISTEN      12187/node_exporter 
tcp        0      0 127.0.0.1:9100          127.0.0.1:50960         ESTABLISHED 12187/node_exporter 
tcp        0      0 127.0.0.1:58278         127.0.0.1:9100          ESTABLISHED 30725/kube-rbac-pro 
tcp        0      0 192.168.2.2:9100        192.168.2.4:49616       ESTABLISHED 30725/kube-rbac-pro 
tcp        0      0 192.168.2.2:9100        10.233.89.54:43728      ESTABLISHED 30725/kube-rbac-pro 
tcp        0      0 127.0.0.1:50960         127.0.0.1:9100          ESTABLISHED 12257/prometheus    
tcp        0      0 127.0.0.1:9100          127.0.0.1:58278         ESTABLISHED 12187/node_exporter

**Comment by xyz-li** [comment]
I think there is a `node_exporter` running in the k8s. Can you find the namespace to which this node_exporter belongs?
