### ISSUE TITLE
Delete Helm and Kustomize binaries in Dockerfile

### ISSUE THREAD

**Issue by nioshield** [kubesphere/kubesphere#5031]
**What's it about?**
[#4852
](https://github.com/kubesphere/kubesphere/pull/4852)
In this PR, Helm Chart is need’t  Helm and Kustomize binary file. 
so, we can deleted the Helm and Kustomize binary file in ks-controller-manager Docker file ?
https://github.com/kubesphere/kubesphere/blob/8e00ba29ca9fe845fdebdd586ed1505a2d6ee5d8/build/ks-controller-manager/Dockerfile#L23
**What's the reason why we need it?**

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

**Comment by nioshield** [comment]
@wansir @xyz-li Any suggestions ?

**Comment by wansir** [comment]
LGTM
