### ISSUE TITLE
Code Analysis SonarQube  fail

### ISSUE THREAD

**Issue by javaXiaoHan** [kubesphere/kubesphere#5043]
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
3.3.0

**Environment**
How many nodes and their hardware configuration:
CentOS 7.6 / 6 masters:  8cpu/8g; 6 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

流水线
Wait for SonarQube analysis to be completed and return quality gate status21 ms失败
Checking status of SonarQube task 'AYHX4Z5CIs9QzNEG3GlC' on server 'sonar'
Error 401 on http://ks.whhkzn.com:32693/api/ce/task?id=AYHX4Z5CIs9QzNEG3GlC :

**Comment by javaXiaoHan** [comment]
you know whatis the proble is ? i  dont know solve it
<img width="950" alt="111" src="https://user-images.githubusercontent.com/32090060/177736199-dabad6dc-f19f-42c0-96c5-28af7ff7988a.png">

**Comment by javaXiaoHan** [comment]
@lshmouse  hello  could you pls give me some help

**Comment by lutixiaya** [comment]
401状态码通常是认证失败，你可以在sonarqube控制台重新创建了一个项目，并设置新的token，用这个新的token在devops中创建了新的凭证（名字可以保持一致），基于新的凭证，再次运行流水线，基本上可以解决你的问题。

**Comment by javaXiaoHan** [comment]
> 401状态码通常是认证失败，你可以在sonarqube控制台重新创建了一个项目，并设置新的token，用这个新的token在devops中创建了新的凭证（名字可以保持一致），基于新的凭证，再次运行流水线，基本上可以解决你的问题。
还是同样的错误
是shell里面是mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN（我现在按照官网这么设置的） 这个命令还是下面这个呢
mvn sonar:sonar \
  -Dsonar.projectKey=hkzn-app \
  -Dsonar.host.url=http://cs.fllkzn.com:19321\
  -Dsonar.login=869008955a65c926500cfc6aa2

**Comment by javaXiaoHan** [comment]
<img width="849" alt="1657188356673" src="https://user-images.githubusercontent.com/32090060/177748640-ae075782-cfac-41cf-afc5-6df92a7b0f7c.png">
zhe这是刚才新建的一个sonar token

**Comment by lutixiaya** [comment]
用下面的命令，不过设置了凭证，可以把命令中的token，用变量替换，即：`mvn sonar:sonar
-Dsonar.projectKey=hkzn-app
-Dsonar.host.url=[http://cs.fllkzn.com:19321\](http://cs.fllkzn.com:19321%5C/)
-Dsonar.login=$SONAR_TOKEN`

**Comment by javaXiaoHan** [comment]
> 用下面的命令，不过设置了凭证，可以把命令中的token，用变量替换，即：`mvn sonar:sonar -Dsonar.projectKey=hkzn-app -Dsonar.host.url=http://cs.fllkzn.com:19321 -Dsonar.login=$SONAR_TOKEN`

> 用下面的命令，不过设置了凭证，可以把命令中的token，用变量替换，即：`mvn sonar:sonar -Dsonar.projectKey=hkzn-app -Dsonar.host.url=http://cs.fllkzn.com:19321 -Dsonar.login=$SONAR_TOKEN`

<img width="960" alt="1657264178088" src="https://user-images.githubusercontent.com/32090060/177937084-304fae70-1d5d-4b58-8514-394eb143bb44.png">
是这么修改吗，现在还是报401错误

**Comment by javaXiaoHan** [comment]
@lutixiaya  非常抱歉打扰你，但是我真的需要你的帮助。我是按照官网和你说的去设置的。但是目前还是报401

**Comment by javaXiaoHan** [comment]
<img width="931" alt="1657595356822" src="https://user-images.githubusercontent.com/32090060/178400289-c9839441-9b77-4ceb-85e3-0cb624223a38.png">
<img width="581" alt="1657595378280" src="https://user-images.githubusercontent.com/32090060/178400328-c0bf9954-4bcc-4063-be51-aa30be277173.png">
后台任务都是成功的
这是什么原因呢

**Comment by javaXiaoHan** [comment]
<img width="581" alt="1657595378280" src="https://user-images.githubusercontent.com/32090060/178400482-d182757c-130f-4d2d-b600-71b03b84dc96.png">
![1657595489610](https://user-images.githubusercontent.com/32090060/178400528-ecd315b5-1c13-4e51-9d87-9218b7cbd538.jpg)
后台任务都是成功的

**Comment by javaXiaoHan** [comment]
@lshmouse 大佬 能帮忙看下吗，卡在这里好久了。确实没看出来是哪儿有问题

**Comment by javaXiaoHan** [comment]
Checking status of SonarQube task 'AYHyHilqIs9QzNEG3GmH' on server 'sonar'
Error 401 on http://ks.whc1n.com:693/api/ce/task?id=AYHyHilqIs9QzNEG3GmH : (这个地址我打码修改了)

但是我访问这个地址是正确的
{"task":{"id":"AYHyHilqIs9QzNEG3GmH","type":"REPORT","componentId":"AYHcs5Y8Is9QzNEG3Gl2","componentKey":"hkzn-app","componentName":"chargeserver","componentQualifier":"TRK","analysisId":"AYHyHi3UYPCMWHh2TaDN","status":"SUCCESS","submittedAt":"2022-07-12T11:14:32+0000","submitterLogin":"admin","startedAt":"2022-07-12T11:14:32+0000","executedAt":"2022-07-12T11:14:45+0000","executionTimeMs":12752,"hasScannerContext":true,"warningCount":1,"warnings":[]}}
