### ISSUE TITLE
It will overwirte the kubesphere-config configmap when use ks-installer upgrade

### ISSUE THREAD

**Issue by hurricane1988** [kubesphere/kubesphere#5052]
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by pixiake** [comment]
At present, the configuration in kubesphere-config configmap is managed by cc, so try to adjust the configuration through cc.
```
kubectl edit cc -n kubesphere-system ks-installer
```
