### ISSUE TITLE
K8s v1.22.10  Can't install  Kubesphere v3.3  

### ISSUE THREAD

**Issue by Changego** [kubesphere/kubesphere#5056]
**General remarks**
K8s v1.22.10  Can't install  Kubesphere v3.3  

**What's your question**
K8s v1.22.10  Can't install  Kubesphere v3.3,Can it be adapted to support?
**Environment: OS & Hardware Information**
vm Centos7.9 * 3 K8s v1.22.10 

**Error logs or message (Attach logs or screenshot)**

2022-07-14T14:33:43+08:00 INFO     : Running hook 'kubesphere/installRunner.py' binding 'KUBE_EVENTS' ...
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)'))': /apis/installer.kubesphere.io/v1alpha1/namespaces/kubesphere-system/clusterconfigurations/ks-installer
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)'))': /apis/installer.kubesphere.io/v1alpha1/namespaces/kubesphere-system/clusterconfigurations/ks-installer
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)'))': /apis/installer.kubesphere.io/v1alpha1/namespaces/kubesphere-system/clusterconfigurations/ks-installer

**Comment by magitekbay** [comment]
it doesn't support intermediate CA certificates.[feature request](https://github.com/kubesphere/ks-installer/issues/2047)
you can fix it with these steps,but it's at your own risk.
patch the ks-installer image.
```
FROM kubesphere/ks-installer:v3.3.0
USER root
RUN sed -i 's/self.verify_ssl = True/self.verify_ssl = False/g' /usr/local/lib/python3.10/site-packages/kubernetes/client/configuration.py
USER kubesphere
```

**Comment by Changego** [comment]
Thank you. I'll give it a try.

**Comment by simake2017** [comment]
this way is ok ,very thanks
