### ISSUE TITLE
Cluster Viewing / Cluster Management can access CRD by url

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#5057]
**Describe the Bug**
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/68640256/178925993-347abc16-34b4-4c66-bca2-8a296612f284.png">
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/68640256/178926105-86ce98d3-bda3-4776-96a7-e6442fb23585.png">
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/68640256/178926147-12f3255d-1c2f-4c93-95a3-b8130fbb01bf.png">

**Versions Used**
KubeSphere:   `v3.3.0`

**precondition**

The role of user ’wx‘ is ’qa‘.
The permissions of role 'qa' are Cluster Viewing and Cluster Management 

**How To Reproduce**
1. use user 'wx' login ks.
2. access url 'http://xxxxx/clusters/default/customresources'

**Expected behavior**
Access failed.

**Actual behavior**
Access success.

**Comment by zhou1203** [comment]
priority/low

**Comment by zhou1203** [comment]
We deliberately hide the button of CRDs for roles other than administrators at the front end, but they still have control rights over CRDs. So that it is not a bug，this is the expected result.
