### ISSUE TITLE
Demo Account number problem

### ISSUE THREAD

**Issue by dafeifei0218** [kubesphere/kubesphere#5058]
https://demo.kubesphere.io/login
account number: demo1
password: Demo123
unable to login. What is the account number and password?

**Comment by nanjofan** [comment]
Hello，you can use “https://kubesphere.cloud/console/resource/” instead

maybe “https://demo.kubesphere.io/login” is not used

**Comment by dafeifei0218** [comment]
I found it here: https://kubesphere.com.cn 
![image](https://user-images.githubusercontent.com/10148878/179161894-4714c031-4cee-4e67-bf4b-c6cb0c63ea27.png)

**Comment by nanjofan** [comment]
![1657870153158](https://user-images.githubusercontent.com/68266519/179174284-633f87aa-d2f6-44f0-9e1f-2b097a80cf9f.png)
