### ISSUE TITLE
After upgrading to V3.3.0, the “Container Log Search” cannot be queried

### ISSUE THREAD

**Issue by rui789** [kubesphere/kubesphere#5059]
After upgrading to V3.3.0, the “Container Log Search” prompts "No Available Cluster". Is there any solution to this?

![image](https://user-images.githubusercontent.com/37356689/178949705-9b887585-dd64-4704-88b3-afe70e1beec3.png)

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.1-rc.3`
