### ISSUE TITLE
Adjust the priority of bash and sh in the container terminal

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#5067]
**What's it about?**

Adjust the priority of bash and sh in the container terminal.

**What's the reason why we need it?**

Bash should have a higher priority than other shells.

**Area Suggestion**

/area apiserver
/kind feature-request
/good-first-issue

**Comment by Gerrylinux** [comment]
Front end code file：（console/src/stores/terminal.js）
When entering the terminal, access the websocket interface, and the shell seems to be set to sh,
The back-end code only adjusts and modifies the data priority, which should not be realized
The retry logic of the back-end terminal. When testing the first bash, the failure to enter the container terminal will cause the websocket link to close. The SH terminal environment will use the closed websocket link
![image](https://user-images.githubusercontent.com/31839722/188371637-bdd0cc0d-40c8-4391-a38b-75de109c2bc9.png)
