### ISSUE TITLE
after add helm repo, the helm repo page can't open correctly

### ISSUE THREAD

**Issue by ivanmissu** [kubesphere/kubesphere#5086]
**Describe the Bug**
after add helm repo, the helm repo page can't open correctly

For UI issues please also add a screenshot that shows the issue.
now, i can't open the page.  so  no ui screenshot.

**Versions Used**
KubeSphere: v3.3.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. go to enterprise space.
2. open application manage -> application repo.
3. add application repo.   repo url is https://cloudnativeapp.github.io/charts/curated/,  submit form.
4. the application repo refresh and page showed below
![image](https://user-images.githubusercontent.com/8721615/180178070-f6406c56-97a6-49db-ab70-793822c310c4.png)

**Expected behavior**
fix it

**Comment by xyz-li** [comment]
Can you provide the log of ks-apiserver?

**Comment by xyz-li** [comment]
/kind good-first-issue
Fill the field `status`  of CR in response.

**Comment by x893675** [comment]
i'm not reproduce this issue..

**Comment by xyz-li** [comment]
> i'm not reproduce this issue..

1. Scale deploy ks-controller-manager to 0. 
2. Add a new repo from ks-console

**Comment by x893675** [comment]
@xyz-li  kc-console has default value `syncing`.  https://github.com/kubesphere/console/pull/3455

**Comment by xyz-li** [comment]
> @xyz-li kc-console has default value `syncing`. [kubesphere/console#3455](https://github.com/kubesphere/console/pull/3455)

It's ok to fill the field status of CR in response.
