### ISSUE TITLE
edgemesh-server 重新创建无法成功，一直在创建新的容器

### ISSUE THREAD

**Issue by sunt89** [kubesphere/kubesphere#5089]
edgemesh-server 安装能够成功，但是点击重新创建时，会出现以下情况
![image](https://user-images.githubusercontent.com/20986998/180380051-dc372cb6-30f3-45f8-ad96-aa9be246f0aa.png)

**Comment by devillove084** [comment]
我在使用3.3.1和k8s1.23.10创建kubeedge后，开启edgemesh所需的条件，也都验证ok，但是edgemesh创建出现问题，具体和这个帖子一样https://kubesphere.io/forum/d/9054-edgemesh-agent
