### ISSUE TITLE
Log in to the web console as admin,but in USERS, i can't find create button

### ISSUE THREAD

**Issue by githubliuyang777** [kubesphere/kubesphere#5092]
k8s version:v1.19
kubesphere version: v3.3.0
![image](https://user-images.githubusercontent.com/97504419/180774976-49bbb906-71de-41b6-8740-c7ee0233981e.png)

**Comment by zhou1203** [comment]
Have you enabled multi-cluster and this cluster is a member cluster?

**Comment by githubliuyang777** [comment]
i have not enabled multi-cluster,if this is the reason, i will try later.

**Comment by zhou1203** [comment]
> i have not enabled multi-cluster,if this is the reason, i will try later.

You can use the following command to check the parameters of the multi -cluster
```bash
kubectl get cc -n kubesphere-system ks-installer -o jsonpath='{.spec.multicluster}'
```
If the output like `{"clusterRole":"member"}`. It means the cluster is a member within a multi-cluster enviroment.

**Comment by githubliuyang777** [comment]
# kubectl get cc -n kubesphere-system ks-installer -o jsonpath='{.spec.multicluster}'
map[clusterRole:member]
when i set clusterRole host, it shows user create and space create buttom.
thanks for your help.
