### ISSUE TITLE
‘CURRENT_RESOURCE_CONSUMPTION’ no translation

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#5104]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/68640256/181415811-20f2a9ce-6725-4868-80f9-b58b79652a7e.png)

**Versions Used**
KubeSphere:  `v3.3.0`

**Comment by Patrick-LuoYu** [comment]
Fixed in [3470](https://github.com/kubesphere/console/pull/3470).

**Comment by jioce** [comment]
issue is fixed inv3.3.1-rc.0
![image](https://user-images.githubusercontent.com/88183150/184826740-568ddad0-f68d-43bb-993a-49e67cfcae6f.png)

![image](https://user-images.githubusercontent.com/88183150/184826678-a9d26244-aca7-40ea-9f7c-1686ebfe7735.png)

![image](https://user-images.githubusercontent.com/88183150/184826618-69761b07-41f9-4f90-a7e1-30aa1058c93c.png)

**Comment by wenxin-01** [comment]
issue not fixed in `ks v3.3.1-rc.0`
@weili520

**Comment by wenxin-01** [comment]
Issue fixed in `ks 3.3.1-rc.1`.
![image](https://user-images.githubusercontent.com/68640256/187116174-57768383-36bd-462f-b8c9-070d9d70aa4c.png)
![image](https://user-images.githubusercontent.com/68640256/187116186-560cdf70-8b8b-447c-81df-0d6377f41413.png)
