### ISSUE TITLE
I want to add a CTL function to enter the container

### ISSUE THREAD

**Issue by wuqiang3424** [kubesphere/kubesphere#5105]
![image](https://user-images.githubusercontent.com/32158667/181470974-4d571ae9-fd2d-45a7-94c7-853f55db6548.png)

**Comment by wuqiang3424** [comment]
目前只能查看实时日志，历史日志是看不到的，当前实际情况是服务将日志写到了容器中的固定位置，通过k8s命令是也是只能看到实时的日志，看不到服务输出的日志文件，希望增加进入容器的功能，然后就可以找到对应路径下的日志进行查看了。我目前的方案是将业务写的日志挂载到宿主机目录下，然后进行查看。目前我看是支持直接进入node节点中，但不是进入到容器，如果已经存在该功能，麻烦告知一下使用方法，多谢。

**Comment by wuqiang3424** [comment]
目前在用的kubesphser版本为： v3.3.0

**Comment by xyz-li** [comment]
![image](https://user-images.githubusercontent.com/6263928/181666428-6e31e2db-ea58-4706-8cd7-5ea73d95e81f.png)
When the pod is running, there is a button to enter the container.

**Comment by wuqiang3424** [comment]
> ![image](https://user-images.githubusercontent.com/6263928/181666428-6e31e2db-ea58-4706-8cd7-5ea73d95e81f.png) When the pod is running, there is a button to enter the container.

这个是哪个版本，看我的图，咋就没有呢

**Comment by wuqiang3424** [comment]
> ![image](https://user-images.githubusercontent.com/6263928/181666428-6e31e2db-ea58-4706-8cd7-5ea73d95e81f.png) When the pod is running, there is a button to enter the container.

这个是哪个版本，看我的图，咋就没有呢

**Comment by zhou1203** [comment]
> > ![image](https://user-images.githubusercontent.com/6263928/181666428-6e31e2db-ea58-4706-8cd7-5ea73d95e81f.png) When the pod is running, there is a button to enter the container.
> 
> 这个是哪个版本，看我的图，咋就没有呢

From the diagram you provided, it can be seen that the container is in an exited state, and only the running container can enter the container console
