### ISSUE TITLE
Can not create harbor from app store

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#5109]
**Describe the Bug**
Can not create 'harbor' from app store.
**Versions Used**
KubeSphere:  `v3.3.0`
k8s: `v1.22.10`

**How To Reproduce**
1. Go to any project
2. Create app from app store

**Actual behavior**
![image](https://user-images.githubusercontent.com/68640256/182748379-ff2dcdd9-0bef-461a-b308-9903dbd79593.png)
![image](https://user-images.githubusercontent.com/68640256/182748410-357c25f7-4079-4398-9e0c-fc911726afea.png)

**Comment by xyz-li** [comment]
The chart needs to be updated.

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.1-rc.1`
