### ISSUE TITLE
求指点，maven package每次都从私服下jar包，很慢。好像镜像没有被缓存到宿主机

### ISSUE THREAD

**Issue by licocon** [kubesphere/kubesphere#5112]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/36863277/182168760-4d35b17a-c0cb-428a-a573-28aef9718402.png">

求指点。

**Comment by Macrow** [comment]
1.配置字典里面 ```ks-devops-agent```不要添加自定义localRepository配置
2.配置字典```jenkins-casc-config```核实一下是否包含以下配置
```
  - hostPathVolume:
      hostPath: "/var/data/jenkins_maven_cache"
      mountPath: "/root/.m2"
```
3.到你的服务器查看```/var/data/jenkins_maven_cache```目录，核实一下缓存是否生效
