### ISSUE TITLE
 How to deploy kubesphere in ARM architecture

### ISSUE THREAD

**Issue by huzk8** [kubesphere/kubesphere#5121]
**What's it about?**

**What's the reason why we need it?**

I believe this is an important feature for Kubesphere. There're a few use cases:

* case one
* case two
* ...

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

**Comment by Aoang** [comment]
What work needs to be done if we support ARM?

**Comment by VioZhang** [comment]
KubeSphere Enterprise supports ARM.
