### ISSUE TITLE
when  i  use  istio   to deploy bookinfo through  kubesphere doc(v3.3) , tracing is error

### ISSUE THREAD

**Issue by Ray-Sir-Like** [kubesphere/kubesphere#5123]
Internal Server Error
Get "http://jaeger-query.istio-system.svc:16686/api/traces?limit=5&amp;start=1659907212000000&amp;end=1659925212000000&amp;service=details.demo-project": dial tcp: lookup jaeger-query.istio-system.svc on 169.254.25.10:53: no such host

![image](https://user-images.githubusercontent.com/25659192/183325499-b08b1fd1-7d3c-4201-b487-42d07bd0fb8c.png)

**Comment by qfdk** [comment]
The same problem

**Comment by RunwangGuo** [comment]
一样的问题~
