### ISSUE TITLE
Can't mount a configMap to container path

### ISSUE THREAD

**Issue by aliuq** [kubesphere/kubesphere#5139]
Use the below configuration, it will can't deploy and not start a container

![image](https://user-images.githubusercontent.com/11707934/184604885-86df7163-162b-474e-9b0d-4bfb3dbd9252.png)

Use the below configuration, got errors in container `mkdir: cannot create directory '/mnt/sync/folders': Read-only file system`, this image must be using directory `/mnt/sync`, so what shoulud I do?

![image](https://user-images.githubusercontent.com/11707934/184605207-ffe94e70-a94b-4214-bb54-7ac94f272011.png)

**Comment by xyz-li** [comment]
Is there just one configmap volume? Do you mount other volumes?
Which docker image are you using?

**Comment by aliuq** [comment]
@xyz-li I resolved this question, it needs write `sync.conf` in all below position

![image](https://user-images.githubusercontent.com/11707934/184792552-65596d93-922d-4d00-9831-2ba11b801252.png)
