### ISSUE TITLE
devops-jenkins replicas error

### ISSUE THREAD

**Issue by javaXiaoHan** [kubesphere/kubesphere#5141]
kubesphere v3.3
3 master 4 nodes (all are aliyun ecs 8核 16G)

when i increase devops-jenkins replicas from 1 to 5 
<img width="952" alt="1660620596161" src="https://user-images.githubusercontent.com/32090060/184792142-7ce9d3ee-a338-4388-9060-0c3b251ccbfe.png">
<img width="851" alt="1660635241598" src="https://user-images.githubusercontent.com/32090060/184823551-a643cdec-81f7-451f-9120-cad3f96afd14.png">
<img width="880" alt="1660635217913" src="https://user-images.githubusercontent.com/32090060/184823562-3e13faf8-183c-48f1-b69c-80e4c040e112.png">

you know the reason  i really need you help!!!
@LinuxSuRen

**Comment by javaXiaoHan** [comment]
@larryliuqing hello 能帮忙看下吗。增加devops-jenkins，sonarqube-sonarqube副本数量 都失败了。

**Comment by javaXiaoHan** [comment]
现在导致我的流水线打不开

**Comment by javaXiaoHan** [comment]
@lshmouse 能帮忙看下吗，万分感谢！

**Comment by mangoGoForward** [comment]
Hi @javaXiaoHan Please provide more detail logs like pod logs or events, and it works well when I adjust the `devops-jenkins` replicas to 2

**Comment by javaXiaoHan** [comment]
我把devops-jenkins工作负载删除，然后重新增加副本数量又好了。请问这样能提高流水线执行速度吗，我现在有多个流水线。但是只有一个流水线才能启动，其他的都是在队列中等待。increase the value to your desired number jenkins_user.yaml > jenkins.clouds.containerCapStr  这个我也增加了

**Comment by javaXiaoHan** [comment]
> 我把devops-jenkins工作负载删除，然后重新增加副本数量又好了。请问这样能提高流水线执行速度吗，我现在有多个流水线。但是只有一个流水线才能启动，其他的都是在队列中等待。increase the value to your desired number jenkins_user.yaml > jenkins.clouds.containerCapStr 这个我也增加了

**Comment by javaXiaoHan** [comment]
> Hi @javaXiaoHan Please provide more detail logs like pod logs or events, and it works well when I adjust the `devops-jenkins` replicas to 2

我把devops-jenkins工作负载删除，然后重新增加副本数量又好了。请问这样能提高流水线执行速度吗，我现在有多个流水线。但是只有一个流水线才能启动，其他的都是在队列中等待。increase the value to your desired number jenkins_user.yaml > jenkins.clouds.containerCapStr 这个我也增加了

**Comment by chilianyi** [comment]
jenkins 只需要 1 个 replica，多个 replica 会对流水线运行产生影响。

提升流水线并发，是需要 修改 configmap jenkins-casc-config，调整 里面 jenkins-user.yaml 里的 containerCapStr， 默认值是 2， 改大成 10，70s 会自动生效。
