### ISSUE TITLE
ks-controller-manager not ready

### ISSUE THREAD

**Issue by kztao** [kubesphere/kubesphere#5142]
![Uploading image.png…]()

log:

` I0816 13:44:56.072935       1 globalrolebinding_controller.go:205] Successfully synced key:admin

 I0816 13:44:56.072955       1 event.go:282] Event(v1.ObjectReference{Kind:"GlobalRoleBinding", Namespace:"", Name:"admin", UID:"d89444af-1a36-4eb9-85ab-5a2b99739b1d", APIVersion:"iam.kubesphere.io/v1alpha2", ResourceVersion:"2458", FieldPath:""}): type: 'Normal' reason: 'Synced' GlobalRoleBinding synced successfully

 I0816 13:44:56.079874       1 controller.go:207] controller/namespace-controller "msg"="Starting workers" "reconciler group"="" "reconciler kind"="Namespace" "worker count"=1

 I0816 13:44:56.084945       1 controller.go:207] controller/workspacerole-controller "msg"="Starting workers" "reconciler group"="iam.kubesphere.io" "reconciler kind"="WorkspaceRole" "worker count"=1

 I0816 13:44:56.085340       1 controller.go:207] controller/gateway-controller "msg"="Starting workers"  "worker count"=2

 I0816 13:44:56.085364       1 controller.go:207] controller/serviceaccount-controller "msg"="Starting workers" "reconciler group"="" "reconciler kind"="ServiceAccount" "worker count"=1

 I0816 13:44:56.085723       1 controller.go:207] controller/nginx-controller "msg"="Starting workers"  "worker count"=2

 I0816 13:44:56.085745       1 controller.go:207] controller/workspacetemplate-controller "msg"="Starting workers" "reconciler group"="tenant.kubesphere.io" "reconciler kind"="WorkspaceTemplate" "worker count"=1

 I0816 13:44:56.085828       1 controller.go:207] controller/workspace-controller "msg"="Starting workers" "reconciler group"="tenant.kubesphere.io" "reconciler kind"="Workspace" "worker count"=1

 I0816 13:44:56.102019       1 controller.go:207] controller/resourcequota-controller "msg"="Starting workers" "reconciler group"="quota.kubesphere.io" "reconciler kind"="ResourceQuota" "worker count"=8

 I0816 13:44:56.102064       1 controller.go:207] controller/application-controller "msg"="Starting workers" "reconciler group"="app.k8s.io" "reconciler kind"="Application" "worker count"=1

 I0816 13:44:56.102194       1 controller.go:207] controller/helmrelease "msg"="Starting workers" "reconciler group"="application.kubesphere.io" "reconciler kind"="HelmRelease" "worker count"=10

 I0816 13:44:56.286702       1 clusterrolebinding_controller.go:190] Successfully synced key:admin-cluster-admin

 I0816 13:44:56.286724       1 event.go:282] Event(v1.ObjectReference{Kind:"ClusterRoleBinding", Namespace:"", Name:"admin-cluster-admin", UID:"7758ed5d-009f-46af-ad45-051297a572c4", APIVersion:"rbac.authorization.k8s.io/v1", ResourceVersion:"4177", FieldPath:""}): type: 'Normal' reason: 'Synced' ClusterRoleBinding synced successfully

 I0816 13:44:57.544705       1 helm_repo_controller.go:105] sync repo end: repo-3w19j0q79m6j1k, elapsed: 1.4834378s

 panic: runtime error: index out of range [0] with length 0

 

 goroutine 1027 [running]:

 kubesphere.io/kubesphere/pkg/simple/client/openpitrix/helmrepoindex.MergeRepoIndex(0xc000739680, 0xc0042a7800, 0xc004247630, 0x2d)

 	/workspace/pkg/simple/client/openpitrix/helmrepoindex/repo_index.go:106 +0x130f

 kubesphere.io/kubesphere/pkg/controller/openpitrix/helmrepo.(*ReconcileHelmRepo).syncRepo(0xc000bdd5f0, 0xc000739680, 0x0, 0x2facbc1)

 	/workspace/pkg/controller/openpitrix/helmrepo/helm_repo_controller.go:292 +0x245

 kubesphere.io/kubesphere/pkg/controller/openpitrix/helmrepo.(*ReconcileHelmRepo).Reconcile(0xc000bdd5f0, 0x3404380, 0xc0018cfd10, 0x0, 0x0, 0xc0009a4258, 0x13, 0xc0018cfd00, 0x0, 0x0, ...)

 	/workspace/pkg/controller/openpitrix/helmrepo/helm_repo_controller.go:161 +0x7fb

 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000510780, 0x34042d8, 0xc00107a7c0, 0x2c197c0, 0xc0016ff7a0)

 	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:298 +0x30d

 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000510780, 0x34042d8, 0xc00107a7c0, 0x455a786d73784200)

 	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253 +0x205

 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc0017c49a0, 0xc000510780, 0x34042d8, 0xc00107a7c0)

 	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:214 +0x6b

 created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2

 	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:210 +0x425`

**Comment by kztao** [comment]
![image](https://user-images.githubusercontent.com/1481448/184807496-1879019f-8625-4e8a-8613-45834ff5281b.png)

**Comment by xyz-li** [comment]
There is one helm repo with a zero chart version. You can delete that repo then the ks-controller-manger will not panic anymore. 
I will fix this bug.

**Comment by kztao** [comment]
ok
