### ISSUE TITLE
issues when reloading ks-apiserver 

### ISSUE THREAD

**Issue by xyz-li** [kubesphere/kubesphere#5148]
**Describe the Bug**
1. ks-apiserver may fail when reloading ks-apisever twice in 5 seconds, there  is a chance of incurring `concurrent map read and map write`.
 https://github.com/kubesphere/kubesphere/blob/b47736c50082a1b25d244602774711f8fd0d0295/cmd/ks-apiserver/app/options/options.go#L244-L246
2. ks-apiserver lost command line parameter after reloaded.

**Versions Used**
KubeSphere: v3.3

/kind bug

**Comment by wansir** [comment]
Related issues, https://github.com/kubesphere/kubesphere/issues/5185, https://github.com/kubesphere/kubesphere/issues/5355

**Comment by hongzhouzi** [comment]
> Related issues, #5185, #5355

This problem should be solved in this PR https://github.com/kubesphere/kubesphere/pull/5422

**Comment by hongzhouzi** [comment]
> 2\. ks-apiserver lost command line parameter after reloaded.

Only the configuration items configured in kubephere-config cm kubesphere.yaml will be overwritten by the configuration items in cm after live-reload if they are configured on the command line parameter, other parameters like klog and debug will not be affected.
Here in the code, the same configuration items in the command line parameter  are overwritten with the changed configuration information in cm.
https://github.com/kubesphere/kubesphere/blob/7162d4131042e318c178690c5856ce64ff158ae5/cmd/ks-apiserver/app/server.go#L121

Here we can't do both configuration items, the configuration of one place must prevail. You can write the configuration items in cm like this and leave them out of the command line parameters. The debug and logging parameters for debugging can be configured on the command line and will not be affected.


The same applies to the parameters in ks-controller-manger.

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-apiserver:release-3.3`
