### ISSUE TITLE
Container log did not auto refresh when turn on the real-time switch

### ISSUE THREAD

**Issue by I321065** [kubesphere/kubesphere#5151]
**Describe the Bug**
Container log did not auto refresh when turn on the real-time switch

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/16135063/185081176-63a21174-5abc-4e2b-bf2b-6591b1797ca2.png)

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. Go to any pod and select one container  
2. Click the container log button and get into the log console
3. turn on the real-time container log switch
4. See log do not refresh automactically

**Expected behavior**
when I turn on the real-time container log switch, the log should refresh automatically

**Comment by xyz-li** [comment]
@I321065 Which k8s and ks version do you use?
