### ISSUE TITLE
Statefulsets and daemonsets do not show rveision record in app details

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#5155]
<!--
You don't need to remove this comment section, it's invisible on the issues page.
**Describe the Bug**

![image](https://user-images.githubusercontent.com/68640256/185581667-7ac62a12-9d77-4049-bd0d-f465ea85340a.png)

**Versions Used**
KubeSphere:  `v3.3.1-rc.0`
Kubernetes: (If KubeSphere installer used, you can skip this)

**Expected behavior**

**Comment by jioce** [comment]
![10a3afb6730a1a0aa28ecdab693617e](https://user-images.githubusercontent.com/88183150/185582053-79df6e3f-b975-40a0-8f2d-15cb0bf12377.png)

**Comment by jioce** [comment]
issue is fixed in v3.3.1-rc.2
![image](https://user-images.githubusercontent.com/88183150/190548764-febe2d4a-1973-40be-bf3d-ee1ac4c60225.png)
