### ISSUE TITLE
When accessing the edge node terminal, it is always displayed as connecting

### ISSUE THREAD

**Issue by wenxinll** [kubesphere/kubesphere#5160]
**Describe the Bug**
1、when accessing the edge node terminal, a pod named 'xxxx-shell-access' will be created in edge node.
2、when the pod created successfully, the accessing edge node terminal page is always displayed as connecting.
3、If access the edge node terminal again, the access will be successful.

![image](https://user-images.githubusercontent.com/68640256/185870313-87aa4e14-6d45-4892-a06e-552d1d07410b.png)
![image](https://user-images.githubusercontent.com/68640256/185870356-dcf0d171-6c34-4745-88f0-f2cc5b001ac5.png)

**Versions Used**
KubeSphere:  `v3.3.0`
Kubernetes: `v1.21.9`

**Expected behavior**
When accessing the edge node terminal, after the pod 'xxxx-access-shell' is successfully created, the node terminal can be successfully accessed, and there is no need to reopen a page for accessing the node terminal.

**Comment by benjaminhuo** [comment]
This is the KubeEdge & K8s compatibility issue, we'll not fix it until we upgrade the KubeEdge version to a compatible one
