### ISSUE TITLE
In a multi-cluster scenario, if a single cluster has multiple Master nodes, the cluster can be added multiple times.

### ISSUE THREAD

**Issue by yuleichun2019** [kubesphere/kubesphere#5172]
**Describe the Bug**
In a multi-cluster scenario, if a single cluster has multiple Master nodes, the cluster can be added multiple times.

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/48045857/186607201-5f3e34c1-6a72-4f6f-89f7-7edb60afca98.png)
![image](https://user-images.githubusercontent.com/48045857/186607281-cfe06b5b-539b-4dff-ac99-c4973baf485d.png)
![image](https://user-images.githubusercontent.com/48045857/186607458-ff47970c-d000-4b9f-9f25-5e483c97b38f.png)

**Versions Used**
KubeSphere: 3.2.1
Kubernetes: 1.18

**Environment**
How many nodes and their hardware configuration:

Linux version 4.19.25-200.1.el7.bclinux.x86_64 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g

**How To Reproduce**

**Expected behavior**

**Comment by xyz-li** [comment]
Fixed by #4651
/close
