### ISSUE TITLE
No image found in containers with 'Edit Settings'

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#5173]
**Describe the Bug**

url: "/kapis/resources.kubesphere.io/v1alpha3/namespaces/pro-m/imageconfig?image=nginx"

![image](https://user-images.githubusercontent.com/68640256/186612835-a3134aec-8453-493f-8f4b-067bde182638.png)

**Versions Used**
KubeSphere:  `v3.3.0`
**How To Reproduce**
1. Create user test-user with Role platform-regular
2. Create workspace wx, Cluster Settings select member
3. Click on workspace wx, click on Workspace Settings, click on Workspace Members, Invote user 'test-user' and select role regular
4. Create project pro-m
5. Click on Project Settings, Click on Project Members, Invote test-user and select role admin
6. Create deployment nginx
7. Use user 'test-user' login KS, select deployment nginx -- > select edit settings --> containers --> edit->modify image, you will see the bug

**Comment by wansir** [comment]
![image](https://user-images.githubusercontent.com/8263040/186644702-a7f22dcd-305f-4e73-864b-fe2dce507972.png)

**Comment by jioce** [comment]
issue is fixed in v3.3.1-rc.1
![image](https://user-images.githubusercontent.com/88183150/187134170-d2cc01f9-dbd1-4ba6-9667-91f97a1edefb.png)
