### ISSUE TITLE
安装的时候minio有错误，访问9000端口号错误

### ISSUE THREAD

**Issue by jibingjie2** [kubesphere/kubesphere#5175]

**Comment by jibingjie2** [comment]
# kubectl logs -n kubesphere-system -l job-name=minio-make-bucket-job
mc: <ERROR> Unable to initialize new config from the provided credentials. Get http://minio:9000/probe-bucket-sign-ibyxmgrv22mc/?location=: dial tcp: i/o timeout.
"Failed attempts: 6"


![image](https://user-images.githubusercontent.com/101303865/187040488-3099d909-b7f1-466c-ac19-220815744da8.png)

pod是正常运行的

![Uploading image.png…]()

**Comment by zhangdan0525** [comment]
Encountered the same issue.

![image](https://user-images.githubusercontent.com/37334836/187060772-0bfd746d-fee2-4dfa-8143-f5e84b91f71f.png)

**Comment by xyz-li** [comment]
Do all the network plugin pods work as expected?

**Comment by jibingjie2** [comment]
> 所有网络插件 pod 是否都按预期工作？

Yes, I use the flannel network plug-in
