### ISSUE TITLE
Role 'platform-regular' should not access cluster manager

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#5177]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/68640256/187131610-64e4973b-0a9c-446a-862d-f3cf616fa912.png)
![image](https://user-images.githubusercontent.com/68640256/187131633-8a3341bd-e2f6-4e98-bb9d-b951547c82a0.png)

**Versions Used**
KubeSphere:  `v3.3.1-rc.1`

**Comment by wenxin-01** [comment]
![image](https://user-images.githubusercontent.com/68640256/187131610-64e4973b-0a9c-446a-862d-f3cf616fa912.png)
![image](https://user-images.githubusercontent.com/68640256/187131633-8a3341bd-e2f6-4e98-bb9d-b951547c82a0.png)

**Comment by wenxin-01** [comment]
role 'workspace-manager' have this issue too.
![image](https://user-images.githubusercontent.com/68640256/187132599-7f27cc5b-4a2b-4c8d-9519-8beac21668f1.png)
![image](https://user-images.githubusercontent.com/68640256/187132600-9707fb55-84d4-48af-aa2e-389a3b6bcab8.png)

**Comment by zhou1203** [comment]
![微信图片_20220830123118](https://user-images.githubusercontent.com/34303854/187349679-b805e107-6238-4343-a96b-0bce13a0578b.png)
It has been forbade by ks-apiserver, the console has to no display the button `Cluster Management`.

**Comment by weili520** [comment]
![屏幕截图 2022-09-13 172514](https://user-images.githubusercontent.com/33231138/189864883-93b30a22-57d2-41c3-a62b-fa5b8f5dd3f2.png)

**Comment by wenxin-01** [comment]
issue fixed in `ks 3.3.1-rc.2`
