### ISSUE TITLE
ks v3.1.1 allows user to add customized quotas include storage quotas. So this issue has been solved.

### ISSUE THREAD

**Issue by kkhung0829** [kubesphere/kubesphere#5178]
ks v3.1.1 allows user to add customized quotas include storage quotas. So this issue has been solved.

_Originally posted by @stoneshi-yunify in https://github.com/kubesphere/kubesphere/issues/3972#issuecomment-883824982_

**Comment by kkhung0829** [comment]
How to do it ? Cannot found any document nor figure out how to do it in web portal...

**Comment by stoneshi-yunify** [comment]
on ks-console,  Platform  management -> Access Management -> select one workspace -> choose one project/namespace, and click the three dots on the right side -> edit quota.

![image](https://user-images.githubusercontent.com/70880165/187129524-32b1b27d-c2cb-40ab-8cf7-4fa8ffeca5fd.png)

**Comment by kkhung0829** [comment]
Thanks. What's the list of resource quotas (requests.*) is supported currently ? Where can I found it in doc ?

**Comment by kkhung0829** [comment]
Can we add customized quota to limit the total runtime duration of the project (e.g. specify end date or number of day for running) ?
