### ISSUE TITLE
The status in the filter box is inconsistent with the status actually displayed by the pod

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#5186]
**Describe the Bug**

![image](https://user-images.githubusercontent.com/68640256/187841576-b0927fd5-1368-48c9-830a-eeda5c772469.png)

`The status of the pods and containers I found are as shown below. Do we need to modify the status of the pods and containers displayed in ks based on these?`

![image](https://user-images.githubusercontent.com/68640256/187842618-d80e8b22-4a3b-41ee-be66-d7f39a1eaf16.png)

![image](https://user-images.githubusercontent.com/68640256/187842654-b0c60268-8933-4052-bda5-48bff67d4a69.png)

**Versions Used**
KubeSphere:  `v3.3.1-rc.1`

**Comment by VioZhang** [comment]
https://github.com/kubesphere/kubesphere/issues/5262
