### ISSUE TITLE
kubesphere的相关镜像一直拉取不了

### ISSUE THREAD

**Issue by wekin** [kubesphere/kubesphere#5189]
exec failed after 3 retires: pull image failed: Failed to exec command: sudo -E /bin/bash -c "env PATH=$PATH docker pull kubesphere/kube-apiserver:v1.22.10" 
Error response from daemon: Head "https://registry-1.docker.io/v2/kubesphere/kube-apiserver/manifests/v1.22.10": Get "https://auth.docker.io/token?scope=repository%3Akubesphere%2Fkube-apiserver%3Apull&service=registry.docker.io": net/http: TLS handshake timeout: Process exited with status 1,
配了阿里云或者科技大学,中国区的镜像全都不管用, kubekey 2.2.2 kubesphere 3.3.0

**Comment by wekin** [comment]
我服了, 我投降, 不弄了, 真的很垃圾的产品

**Comment by yijianguanzhu** [comment]
> 我服了, 我投降, 不弄了, 真的很垃圾的产品

我没多长时间就装好了，看起来是你这镜像配置没生效
