### ISSUE TITLE
Kubesphere Dashboard cluster_cpu_usage metric value problem

### ISSUE THREAD

**Issue by Argalep** [kubesphere/kubesphere#5190]
**Describe the Bug**
I created my own promethues pods by following the instructions found at https://kubesphere.com.cn/en/docs/v3.3/faq/observability/byop/. However, the CPU metric values ​​appear as 0 on the dashboard on the kubesphere console. How can I solve this problem?

![image](https://user-images.githubusercontent.com/17765272/188228184-1bba7341-931a-45c2-9482-93c0bf609959.png)

![image](https://user-images.githubusercontent.com/17765272/188230460-f67de62d-783f-418a-85b9-1135a6133aed.png)

![image](https://user-images.githubusercontent.com/17765272/188229489-3ee44c5b-0b07-411b-abfa-0d61efeb61d0.png)

**Versions Used**
KubeSphere: 3.3.0
Kubernetes: v1.24.3

**Environment**
For example: Ubuntu 22.04 LTS / 3 masters:  4cpu/3g; 3 nodes: 8cpu/16g

**How To Reproduce**
1. After the kubesphere is installed, the operations in the document are done.
2. Metric values ​​are checked via the Kubernetes console.

**Expected behavior**
Cluster cpu values ​​should not be 0.

**Comment by 26tanishabanik** [comment]
@Argalep , I am not totally sure, but it might be due to division issues, like truncation and all
What does the command `kubectl top pods -namespace` show?
