### ISSUE TITLE
save Jenkins Pipeline will miss the webHooks config

### ISSUE THREAD

**Issue by hdgjun** [kubesphere/kubesphere#5193]
**Describe the Bug**

i add a  webHooks config to jenkins from gitlab,but the config will miss where i change and save pipeline config by
kubesphere .

**Versions Used**
KubeSphere: 3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by marksmansj** [comment]
do you solve this problem ?

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/devops-apiserver:ks-v3.3.2-rc.0`
