### ISSUE TITLE
Application Routing Rule when service type is externalName，no endpoint。

### ISSUE THREAD

**Issue by yongxingMa** [kubesphere/kubesphere#5198]
**Describe the Bug**

When the service type is externalName, 
The routing rule be saved when write 80 is failed,
But in fact it can be saved when edit yaml in cluster。

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/31605966/188770391-7d6c86e3-d300-42ef-be34-0169259355c7.png">
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/31605966/188770454-7c8db130-16e6-4396-8a40-1141ac2c961c.png">

**Note: I want to solve the problem of ingress routing accessing across namespaces**

**Versions Used**
KubeSphere: v3.2.1

**Comment by hongzhouzi** [comment]
@harrisonliu5 This is a ks-console bug, the manually entered ports are not converted to numbers and saved.
