### ISSUE TITLE
pipeline cron error

### ISSUE THREAD

**Issue by FatuityCookie** [kubesphere/kubesphere#5199]
**Describe the Bug**
Internal Server Error
parsing time "2022 at 8:20:36 PM Coordinated Universal" as "Monday, January 2, 2006 15:04:05 PM": cannot parse "2022 at 8:20:36 PM Coordinated Universal" as "Monday"

![image](https://user-images.githubusercontent.com/46119806/188805455-1ae8cd53-edc9-48a8-894b-152fd29afe1d.png)

**Versions Used**
KubeSphere: v3.3.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

CentOS 7.9 / 1 master:  8cpu/16g; 3 nodes: 8cpu/16g

**Comment by FatuityCookie** [comment]
jenkins

**Comment by 26tanishabanik** [comment]
@FatuityCookie , can you tell me, how to reproduce this error?

**Comment by nanjofan** [comment]
I encounter this bug，too

**Comment by FatuityCookie** [comment]
> reproduce

create a pipeline then edit it

**Comment by FatuityCookie** [comment]
@26tanishabanik create a pipeline then edit it
