### ISSUE TITLE
settings/dingtalk needs to improve DingTalk to support forward proxy settings

### ISSUE THREAD

**Issue by shenhonglei** [kubesphere/kubesphere#5209]
**What's it about?**

Enterprise WeChat, the proxy configuration in the intranet environment is
kubectl edit nc default-wechat-config
add spec.wechat.wechatApiUrl
![1](https://user-images.githubusercontent.com/20896372/189877113-a62fb9a7-532a-4bec-8bf5-b6b6814df565.jpg)

However, DingTalk cannot support it for the time being, and the following configurations are not available
kubectl edit nc default-dingtalk-config
**What's the reason why we need it?**

General enterprise scenario configuration necessary

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request
/area notification
/assign @wanjunlei

**Comment by benjaminhuo** [comment]
@wanjunlei Is it possible to do this for DingTalk?
wechatApiUrl is to set proxy for wechat notification?

**Comment by wanjunlei** [comment]
DingTalk does not support set proxy now.

**Comment by benjaminhuo** [comment]
> DingTalk does not support set proxy now.

Close it for now
