### ISSUE TITLE
Role 'platform-self-provisioner' should be able to delete worksapce created by it's self

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#5221]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/68640256/190944236-d67fd304-50dc-455d-91b5-3b3a5d966c1e.png)

**Versions Used**
KubeSphere:  `v3.3.1-rc.2`

**Comment by zhou1203** [comment]
From the current design point of view, it is the expected behavior that self-provisoner cannot delete the workspaces created by itself.
