### ISSUE TITLE
The permissions of access control in workspace role is wrong. 

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#5224]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/68640256/190968427-dff7032e-1a48-46b5-ab0e-e3586fc803e1.png)

**Versions Used**
KubeSphere:   `v3.3.1-rc.2`

**Expected behavior**
The permissions of access control in workspace role should be `Department Viewing`, `Role Viewing`, `Member Viewing`.

**Comment by zhou1203** [comment]
Fixing deparment management in this PR https://github.com/kubesphere/ks-installer/pull/2112

**Comment by zhou1203** [comment]
The workspace member view has been deleted and incorporated to workspace role basic in this version

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.1-rc.3`
![image](https://user-images.githubusercontent.com/68640256/192681807-2ca69a4e-d0fb-431c-b6b7-e651e036ed46.png)
