### ISSUE TITLE
The cluster role 'cluster-admin' and 'cluster-viewer' have no entry to cluster and resource consumption.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#5225]
**Describe the Bug**

When a user does not have the cluster permission of the platform but is `invited to a cluster`, the user should be able to view the information of the cluster and be able to view the resource consumption information of this cluster.

![image](https://user-images.githubusercontent.com/68640256/190974048-4d9fd818-2439-4aca-b260-abdadafba93d.png)

![image](https://user-images.githubusercontent.com/68640256/190972969-a8b1ec42-f9f5-45e1-a4eb-7cda91a76783.png)

**Versions Used**
KubeSphere:  `v3.3.1-rc.2`

**Expected behavior **
1. Add entry of cluster `Platform/Cluster Management`
2. Add entry of resource consumption in `Toolbox`

**Comment by wenxin-01** [comment]
After setting permissions, wait about two minutes. You can see the cluster management and resource consumption entry.

**Comment by zhou1203** [comment]
After testing, I found that this bug only occurs in a single cluster, which is a little different from multi-cluster in processing. So I suggest that moving out this issue from millstone v3.3.1, and we will handle in the next release.

**Comment by VioZhang** [comment]
duplicate with https://github.com/kubesphere/kubesphere/issues/5398
