### ISSUE TITLE
Role 'platform-self-provisioner' can not select public cluster when create workspcae.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#5226]
**Describe the Bug**
There is a user test, it's platform role is `platform-self-provisioner` and not a member of any cluster.

![image](https://user-images.githubusercontent.com/68640256/190992284-16cd3243-ab4f-4582-90ca-ce4c0f89c430.png)
![image](https://user-images.githubusercontent.com/68640256/190992203-2457f8d2-2168-4b5f-b335-50d6f58a3f0f.png)
![image](https://user-images.githubusercontent.com/68640256/190992431-d207ecba-5211-4296-909d-0e2db46a7561.png)

request url:  `tenant.kubesphere.io/v1alpha2/clusters?limit=-1&labelSelector=cluster.kubesphere.io%2Fvisibility%3Dpublic&sortBy=createTime&page=1`

**Versions Used**
KubeSphere:  `v3.3.1-rc2`

**Expected behavior**

**Comment by zhou1203** [comment]
![image](https://user-images.githubusercontent.com/34303854/191157781-5cfbae4f-eb3e-4d9d-8589-0c6f7b261d67.png)
There should be replaced with `/kapis/resources.kubesphere.io/v1alpha3/clusters`, right?

**Comment by weili520** [comment]
> here is a user test, it's platform role is `platform-self-provisioner` and not a member of any cluster.

![截屏2022-09-20 15 54 23](https://user-images.githubusercontent.com/33231138/191200399-c7c5b7dd-ee08-4c0a-8497-de3ced92d4b6.png)

`/kapis/resources.kubesphere.io/v1alpha3/clusters` is incrrect.

**Comment by wenxin-01** [comment]
Issue fixed in `ks v3.3.1-rc.3`

**Comment by wenxin-01** [comment]
Issue fixed in ks v3.3.1-rc.5
