### ISSUE TITLE
upgrade prometheus dependency version

### ISSUE THREAD

**Issue by junotx** [kubesphere/kubesphere#5229]
**What's it about?**

upgrade prometheus dependency version in go.mod which may also involve upgrade dependency of prometheus-operator, alertmanager, etc.

**What's the reason why we need it?**

- alert rule validation requires newer prometheus dependency which import new funtion supports
- related libraries provide more enhancements

**Area Suggestion**

/area monitoring

**Comment by benjaminhuo** [comment]
This has been done in KubeSphere v4.0 observability extension https://github.com/WhizardTelemetry/whizard-telemetry , we'll not do this in KubeSphere v3.x
