### ISSUE TITLE
Workspace custom role, no matter what permissions are set, you can access projects、devops projects and workspace settings.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#5230]
**Describe the Bug**
There is a user wx, it's platform-role is `platform-regular`, the workspace-permission is `App Repository Viewing  |  App Repository Management`.
This user only can  manage repository, but it can see projects、devops projects and workspace settings.

![image](https://user-images.githubusercontent.com/68640256/191156580-684bbbad-1668-4d9d-8f0d-4aaafa37035d.png)

![image](https://user-images.githubusercontent.com/68640256/191157222-aec4a3b3-e85b-4cf3-94fc-7ad198e65566.png)

![image](https://user-images.githubusercontent.com/68640256/191156675-1813e22f-b03e-47ab-8dc0-eddd1199f3f9.png)

![image](https://user-images.githubusercontent.com/68640256/191157765-42a1014c-c762-43a5-beda-87e1ef1398e3.png)

**Versions Used**
KubeSphere:  `v3.3.1-rc.2`

**Comment by zhou1203** [comment]
We make these entries open to everyone, but only those invited into the project can see the project

**Comment by wenxin-01** [comment]
The user did not been invited to project/devops project, but it can see those projects/devops project.
