### ISSUE TITLE
ks 3.3 cluster role-BUG

### ISSUE THREAD

**Issue by ZengIan** [kubesphere/kubesphere#5243]
**Describe the Bug**
I create a user to demo01, platformrole is platform-regular, there are host cluster and member cluster, then i invite demo01 to member cluster as a cluster-admin role. login in ks-console use demo01, it had a api fobidden error:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "clusters.resources.kubesphere.io is forbidden: User \"demo01\" cannot list resource \"clusters\" in API group \"resources.kubesphere.io\" at the cluster scope",
  "reason": "Forbidden",
  "details": {
    "group": "resources.kubesphere.io",
    "kind": "clusters"
  },
  "code": 403
}

```
![bfabe3397b9ee9f01772329f88035c0](https://user-images.githubusercontent.com/41040520/191892392-6b4f78f7-20ff-437e-98af-112509d302d9.jpg)
![d61aff5855a4bbbbe3dc491e2236a73](https://user-images.githubusercontent.com/41040520/191892417-404736ab-8dc5-4f30-aaeb-a652bca82c17.jpg)

**Versions Used**
KubeSphere: 3.3

**Comment by zhou1203** [comment]
this bug has been fixed at v3.3.1 /need-to-verify
