### ISSUE TITLE
Users who are not invited to the cluster should not see the cluster.

### ISSUE THREAD

**Issue by wenxinll** [kubesphere/kubesphere#5246]
**Describe the Bug**
There is a user wx, his platform-role is `platform-regular`. He has been invited to cluster `test-host`and not to cluster `member`.

`/kapis/resources.kubesphere.io/v1alpha3/clusters?sortBy=createTime&limit=10`

![image](https://user-images.githubusercontent.com/68640256/192213453-44222dc0-00ea-4c57-b659-e0a286d38ead.png)

`/kapis/resources.kubesphere.io/v1alpha3/clusters?page=1&limit=-1&labelSelector=%21cluster-role.kubesphere.io%2Fhost&sortBy=createTime`

![image](https://user-images.githubusercontent.com/68640256/192213955-bf9c8916-ffb7-4bf6-b5ef-cb87bd64a222.png)

**Versions Used**
KubeSphere:  `v3.3.1-rc.2`

**Expected behavior**
In the two places shown in the screenshot, the cluster 'member' should not appear

**Comment by zhou1203** [comment]
This issue is same as #5307
