### ISSUE TITLE
A small bug about pod resource limit and request

### ISSUE THREAD

**Issue by ZengIan** [kubesphere/kubesphere#5257]
**Describe the Bug**
if I only set resource limit, it's It is normal for YAML of workloads, but It is not normal for POD YAML, It causes the pod limit to be the same as the request, more details are as follows:
![a79a2d0a61a7c4789374993469af94a](https://user-images.githubusercontent.com/41040520/193010983-576a14c5-9c59-4ee6-a378-2108ddec145c.png)
![58e9881e6d15fe49b99491cee31528c](https://user-images.githubusercontent.com/41040520/193011283-94d6051d-68a2-40c4-bcbf-15ea3cf68174.png)

If I create a deployment.yaml and apply it on kubernetes, and request equal to 0, It is normal for POD YAML, as follow:
![49098fa748a164020d472feae189d0a](https://user-images.githubusercontent.com/41040520/193011426-1a554694-bdaa-4eb3-bbb8-39a39732598b.png)

**Versions Used**
KubeSphere: ks3.3/ks3.2.1
Kubernetes: 1.21.5

@VioZhang

**Comment by VioZhang** [comment]
fixed
