### ISSUE TITLE
The pod is already running, but the UI shows it as waiting

### ISSUE THREAD

**Issue by hongzhouzi** [kubesphere/kubesphere#5262]
**Describe the Bug**
Status.conditions has an extra ContainerDiskPressure of False which causes the pod status to be displayed incorrectly in the UI.
<img width="844" alt="image" src="https://user-images.githubusercontent.com/36416216/193241788-bf8d6b89-e597-411b-84ff-483e22c997f6.png">

**Versions Used**
KubeSphere: v3.2.1
Kubernetes: 1.20.4

**Comment by wenxinll** [comment]
fixed in `ks 3.3.2`
https://github.com/kubesphere/kubesphere/issues/5461
