### ISSUE TITLE
istio-proxy not ready on v3.3.0

### ISSUE THREAD

**Issue by hoanbc** [kubesphere/kubesphere#5269]
Hello anybody. 
I had issues with istio-proxy when deploy on kubesphere v3.3.0. Log container show as the picture. Someone has fix it, please help me.
Kubesphere v3.3.0
Cloud provider: OKE ( Oracle cloud)

![image](https://user-images.githubusercontent.com/26288807/193440204-779b5541-1f97-443c-8aac-101932bbfe20.png)
![image](https://user-images.githubusercontent.com/26288807/193440186-979de41e-a771-4499-ab31-07713432f877.png)

**Comment by hongzhouzi** [comment]
See if this is the problem https://kubesphere.com.cn/forum/d/6975-kubesphere-321-istio
