### ISSUE TITLE
Ubuntu 2204 Arm64 安装 v3.3.0 启用插件 一直卡在 Deploying minio 

### ISSUE THREAD

**Issue by shuqingzai** [kubesphere/kubesphere#5273]
**Describe the Bug**
启用插件时，`minio` 一直起不来

```shell
kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l 'app in (ks-install, ks-installer)' -o jsonpath='{.items[0].metadata.name}') -f
```
日志
```shell
........
TASK [common : KubeSphere | Creating manifests] ********************************
changed: [localhost] => (item={'name': 'custom-values-minio', 'file': 'custom-values-minio.yaml'})

TASK [common : KubeSphere | Checking minio] ************************************
changed: [localhost]

TASK [common : KubeSphere | Deploying minio] ***********************************

```
调度事件
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/44406033/194532072-294344b1-98da-4b26-abe6-148da7699f64.png">

容器日志
<img width="986" alt="image" src="https://user-images.githubusercontent.com/44406033/194531958-d4ecff39-8a29-4995-b43b-e187d42d69e4.png">

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: v3.3.0
Kubernetes: (If KubeSphere installer used, you can skip this)
```shell
kubectl version -oyaml
clientVersion:
  buildDate: "2022-09-21T13:19:24Z"
  compiler: gc
  gitCommit: b39bf148cd654599a52e867485c02c4f9d28b312
  gitTreeState: clean
  gitVersion: v1.24.6
  goVersion: go1.18.6
  major: "1"
  minor: "24"
  platform: linux/arm64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-09-21T13:12:04Z"
  compiler: gc
  gitCommit: b39bf148cd654599a52e867485c02c4f9d28b312
  gitTreeState: clean
  gitVersion: v1.24.6
  goVersion: go1.18.6
  major: "1"
  minor: "24"
  platform: linux/arm64
```

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

```shell
uname -a
Linux k8s01 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:31:33 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

| 主机名称 |      IP      |  角色  |                             配置                             |      系统      |
| :------: | :----------: | :----: | :----------------------------------------------------------: | :------------: |
|  k8s01   | 10.211.55.11 | Master |             CPU：4 核，内存：8 G，硬盘：一个 64G             | Ubuntu22.04LTS |
|  k8s02   | 10.211.55.12 | Worker | CPU：6 核，内存：12 G，硬盘：两个 64G （一个系统，一个ceph） | Ubuntu22.04LTS |
|  k8s03   | 10.211.55.13 | Worker |  CPU：6 核，内存：12G，硬盘：两个 64G（一个系统，一个ceph）  | Ubuntu22.04LTS |
|  k8s04   | 10.211.55.14 | worker | CPU：6 核，内存：12 G，硬盘：两个 64G（一个系统，一个ceph）  | Ubuntu22.04LTS |

**How To Reproduce**
1. 手动全新安装 kubernetes 
2. 使用 [ks-installer](https://github.com/kubesphere/ks-installer) 安装 kubesphere

**Expected behavior**

**Comment by mangoGoForward** [comment]
Debug:
 1. check the storage configuration and storage server
 2. make sure the DNS address in /etc/resolv.conf is available
 3. execute 'kubectl logs -n kubesphere-system -l job-name=minio-make-bucket-job' to watch logs
 4. execute 'helm -n kubesphere-system uninstall ks-minio && kubectl -n kubesphere-system delete job minio-make-bucket-job'
 5. Restart the installer pod in kubesphere-system namespace

**Comment by shuqingzai** [comment]
kubesphere/ks-installer#2020

**Comment by shuqingzai** [comment]
> Debug:
> 
> 1. check the storage configuration and storage server
> 2. make sure the DNS address in /etc/resolv.conf is available
> 3. execute 'kubectl logs -n kubesphere-system -l job-name=minio-make-bucket-job' to watch logs
> 4. execute 'helm -n kubesphere-system uninstall ks-minio && kubectl -n kubesphere-system delete job minio-make-bucket-job'
> 5. Restart the installer pod in kubesphere-system namespace

minio 版本太久，不支持 Arm64

**Comment by shuqingzai** [comment]
目前的解决方法参考：https://github.com/kubesphere/kubesphere/issues/5285#issuecomment-1305114885
<img width="924" alt="image" src="https://user-images.githubusercontent.com/44406033/200324936-48ac79ae-c059-4c4d-82c1-fe48881fd23b.png">
