### ISSUE TITLE
build devops pipeline , docker build step error docker: not found

### ISSUE THREAD

**Issue by kikyoulg** [kubesphere/kubesphere#5276]
+ docker build -t registry.zet-fl.com/msmp/fedx-api:4.2.0 .
/home/jenkins/agent/workspace/fedx-apisr79t8/fedx-apis@tmp/durable-6f886104/script.sh: 1: docker: not found
script returned exit code 127

use 'kubectl exec -it ' to login in devops worker pod , cant run docker bash

**Comment by chilianyi** [comment]
I see you want to run docker in jenkins agent，we build docker image with docker cmd in it : https://github.com/kubesphere/devops-agent/blob/master/base/hack/install_utils.sh#L12
So you are able to run docker in jenkins agent, maybe you did not assign container to run the cmd:
use container(‘’) around the docker cmd, such as:

```
pipeline {
  agent {
    node {
      label 'go'
    }

  }
  stages {
    stage('stage-go') {
      agent none
      steps {
        container('go') {
          sh 'docker -v'
        }

      }
    }

  }
} 
```

![image](https://user-images.githubusercontent.com/5917832/209488999-9fa50416-9a06-4c95-b51c-5f06956fd63b.png)

**Comment by nowll** [comment]
i face the same issue here.  is anyone already solve it?
