### ISSUE TITLE
offline environment , kubesphere imagePullPolicy=Always leads to cluster stuck

### ISSUE THREAD

**Issue by bjdaijun** [kubesphere/kubesphere#5281]
**Describe the Bug**

Environment with no internet connection, kubesphere will stuck , because of It's default imagePullPolicy is Always.

So Kubephere will always pull it's component container such as ks-api ,ks-controller, etc. But without internet connection , It's will fail, and leads to kubesphere broken.

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by bjdaijun** [comment]
It's seems that ks-installer will check and udpate kubesphere-system components configurations with default value.
So if close ks-installer , or replace ks-installer with some of modified versions may solve it,

**Comment by VioZhang** [comment]
![image](https://user-images.githubusercontent.com/41519383/209296928-3ff7c164-d893-41f5-a878-551ded5fb322.png)
You can try 3.3.1.
