### ISSUE TITLE
default minio image does not support arm64

### ISSUE THREAD

**Issue by Nathan7512** [kubesphere/kubesphere#5285]
**What's your question**
How to change the default image of minio  and pullpolicy in cluster-configuration.yaml before installation?

**Environment: OS & Hardware Information**
k8s version:1.21.8
air-gapped installation on Kubernetes

**Installer Version**
v3.3.0

**Comment by Nathan7512** [comment]
edit cluster configuration yaml

**Comment by shuqingzai** [comment]
Hi, is the problem solved? How to solve it?

**Comment by Nathan7512** [comment]
> Hi, is the problem solved? How to solve it?

you can edit cluster-configuration.yaml  to change default image
![image](https://user-images.githubusercontent.com/44249947/200234990-4245a926-c1f4-4425-a298-9f67f1827624.png)

**Comment by shuqingzai** [comment]
> > Hi, is the problem solved? How to solve it?
> 
> you can edit cluster-configuration.yaml to change default image ![image](https://user-images.githubusercontent.com/44249947/200234990-4245a926-c1f4-4425-a298-9f67f1827624.png)

Thanks, this is very useful to me @Nathan7512

**Comment by AlgoYu** [comment]
> 

请问这个文件在哪里呀，我也遇到这个问题了，感谢。

**Comment by Nathan7512** [comment]
> 

就是你安装的时候apply的两个文件之一，集群配置的那个。
![image](https://github.com/kubesphere/kubesphere/assets/44249947/92241b87-435a-4d72-8fd4-31a302bbb703)

**Comment by AlgoYu** [comment]
devops依旧不支持，有一个argocd没有arm的镜像可以换的，自己打包还挺麻烦。
