### ISSUE TITLE
All-in-one install results in `lb.kubesphere.local` lookup failed after reboot

### ISSUE THREAD

**Issue by gebrits** [kubesphere/kubesphere#5294]
**What's your question**

After following along the All-in-one install and having testing everything works, I did a reboot to see if k8s came back online which I expect it should (correct?)

However, trying to do a  `kubectl get pods` (or whatever other kubectl command) fails with: 
`Unable to connect to the server: dial tcp: lookup lb.kubesphere.local on 127.0.0.53:53: server misbehaving`

Apparently the system isn't able to resolve `lb.kubesphere.local`. I guess this should be persisted somewhere so it reloads on reboot? (With my limited linux knowledge I'd say something like `/etc/hosts`) 

I tried to get the cluster working manually again by editing `~/.kube/config` and changing `server: https://lb.kubesphere.local:6443 => https://localhost:6443`. 

At least `kubectl get pods` is working, but k8s is still in a bad state. Specifically, 
`kubectl get cs` shows: `scheduler            Unhealthy   Get "http://127.0.0.1:10251/healthz": dial tcp 127.0.0.1:10251: connect: connection refused`

At a loss now on how to try to restore manually furtherm although  not a big deal since I was just playing around and will bring up a new server. _However_, I feel k8s/kubesphere should be able to survive a reboot.

**Environment: OS & Hardware Information**

VMWare
Ubuntu 22.04.1 LTS
kubernetes v1.22.10 
kubesphere v3.3.0

**Comment by bracebrace008** [comment]
/etc/hosts 加上集群相关的节点映射。例如：
IP地址  lb.kubesphere.local
节点IP1  节点名1
节点IP2  节点名2
