### ISSUE TITLE
reboot fails for OS with manage_etc_hosts =true => /etc/hosts not persisted

### ISSUE THREAD

**Issue by 0xgeert** [kubesphere/kubesphere#5295]
**Describe the Bug**
Installs on an OS with `manage_etc_hosts =true` a reboot fails to properly restart K8S. 
This is due to `/etc/hosts` not being persisted. 

**Solution**
Either warn users OR, after probing this is an issue with OS, write to ` /etc/cloud/templates/hosts.debian.tmpl` below which does persist. The latter is probably most logical for the all-in-one install

For ref, `/etc/hosts` explains it as follows: 

```
# Your system has configured 'manage_etc_hosts' as True.
# As a result, if you wish for changes to this file to persist
# then you will need to either
# a.) make changes to the master file in /etc/cloud/templates/hosts.debian.tmpl
# b.) change or remove the value of 'manage_etc_hosts' in
#     /etc/cloud/cloud.cfg or cloud-config from user-data
#
```

Originally reported as an installation issue [here](https://github.com/kubesphere/kubesphere/issues/5294)

**Comment by 1265578519** [comment]
# This will cause the set+update hostname module to not operate (if true)
preserve_hostname: true

打开编辑 vi /etc/cloud/cloud.cfg 文件
preserve_hostname，该选项改为True
