### ISSUE TITLE
Cluster upgrade devops component error

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#5306]
**Describe the Bug**
1、devops component error after cluster upgrade
![image](https://user-images.githubusercontent.com/88183150/196647852-ea525c1d-feb9-4aec-82e0-5a248e3ea49b.png)

**Versions Used**
3node+ubuntu18.04+ubuntu18.04.4+ubuntu20.04+ks3.3.0+k8s1.22.10(全组件) -》ks3.3.1+k8s1.22.10

/king bug
/priority medium

**Comment by wenxin-01** [comment]
It worked after restart ks-installer

**Comment by wenxin-01** [comment]
@chilianyi

**Comment by chilianyi** [comment]
The pod is not started after upgrade?

Is there any other info, jenkins pod log or event?

**Comment by VioZhang** [comment]
we can provide a document @chilianyi

**Comment by chilianyi** [comment]
https://kubesphere.io/forum/d/9252-331-jenkins
