### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by taitaking** [kubesphere/kubesphere#531]
fatal: [ks-allinone]: FAILED! => {"ansible_facts": {"pkg_mgr": "yum"}, "changed": false, "msg": "The Python 2 bindings for rpm are needed for this module. If you require Python 3 support use the `dnf` Ansible module instead.. The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."}

**Comment by rayzhou2017** [comment]
有详细的安装环境吗？

**Comment by pixiake** [comment]
这个是什么操作系统呢？系统里默认是python3吗？
