### ISSUE TITLE
通知配置 中的webhook（企业微信机器人），测试成功，但消息未发送

### ISSUE THREAD

**Issue by chuchq** [kubesphere/kubesphere#5328]
**Describe the Bug**
1、通知配置 中的webhook（企业微信机器人），测试成功，但消息未发送
2、通知配置 下的企业微信也不支持机器人webhook
 

**Versions Used**
KubeSphere: 3.3
 

**Environment**
单节点、集群均如此

**Expected behavior**
通知配置 支持webhook（企业微信机器人）

**Comment by nekomeowww** [comment]
<img width="968" alt="image" src="https://user-images.githubusercontent.com/11081491/198184752-63752982-19a9-4844-9829-92c910ef7887.png">

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/11081491/198184871-bcc19391-33f2-4784-8c5a-ff0d9e41c80f.png">

我遇到了同样的问题。Webhook 消息测试是成功的，其所发送的消息在飞书自定义机器人侧也接收到了，这个流程是工作的。但当测试使用的告警触发时，消息将不再通过 Webhook 发送。

**Comment by chuchq** [comment]
> 

在论坛里面发帖后，官方的回复是企业微信机器人的webhook暂不支持，但是飞书的，如果kubesphere3.3，那[notification-manager](https://github.com/kubesphere/notification-manager)应该是1.4，notification-manager2.0.1我看是已经支持了飞书，你可以升级一下notification-manager试试

**Comment by chuchq** [comment]
> <img alt="image" width="968" src="https://user-images.githubusercontent.com/11081491/198184752-63752982-19a9-4844-9829-92c910ef7887.png">
> 
> <img alt="image" width="1185" src="https://user-images.githubusercontent.com/11081491/198184871-bcc19391-33f2-4784-8c5a-ff0d9e41c80f.png">
> 
> 我遇到了同样的问题。Webhook 消息测试是成功的，其所发送的消息在飞书自定义机器人侧也接收到了，这个流程是工作的。但当测试使用的告警被触发时，告警消息将不再通过 Webhook 发送。


1、如果是测试可以收到，被触发时收不到，那触发的时候你去看看notification-manager、alertmanager等日志，消息是否真的发送了，可以多开启几个渠道，测试一下
2、在论坛里面发帖后，官方的回复是企业微信机器人的webhook暂不支持，但是飞书的，如果kubesphere3.3，那[notification-manager](https://github.com/kubesphere/notification-manager)应该是1.4，notification-manager2.0.1我看是已经支持了飞书，你可以升级一下notification-manager试试

**Comment by nekomeowww** [comment]
> 1、如果是测试可以收到，被触发时收不到，那触发的时候你去看看notification-manager、alertmanager等日志，消息是否真的发送了，可以多开启几个渠道，测试一下

我在发送 Issue 前曾尝试去配置 elasticsearch 取得日志来了解更多情况，但是似乎 kubesphere3.3 还不支持我们公司所部署的 8.x 版本的 elasticsearch，后来也就不了了之，我可以去直接查看 container log 试试看，也许能找到一些线索。

> 2、在论坛里面发帖后，官方的回复是企业微信机器人的webhook暂不支持，但是飞书的，如果kubesphere3.3，那[notification-manager](https://github.com/kubesphere/notification-manager)应该是1.4，notification-manager2.0.1我看是已经支持了飞书，你可以升级一下notification-manager试试

听起来很棒，我去试试升级一下，非常感谢！
