### ISSUE TITLE
The specified global settings file does not exist  运行流水线的时候，单元测试报错

### ISSUE THREAD

**Issue by WangFeng-WF** [kubesphere/kubesphere#5329]
++ pwd
+ mvn clean -o -gs /home/jenkins/agent/workspace/demopmp7r/demo2/configuration/settings.xml test
[ERROR] Error executing Maven.
[ERROR] The specified global settings file does not exist: /home/jenkins/agent/workspace/demopmp7r/demo2/configuration/settings.xml
script returned exit code 1

**Comment by chilianyi** [comment]
报错显示 /home/jenkins/agent/workspace/demopmp7r/demo2/configuration/settings.xml 不存在，是不是再其他目录，可以加下 ls 命令看下。

**Comment by huangront** [comment]
> 

你给我了思路，谢谢，我一直在找问题所在。现在你给了我其他思路，这个setting路径可以找出，然后替换一下就可以了。

**Comment by enginewang** [comment]
该github项目之前提了一个commit（https://github.com/kubesphere/devops-maven-sample/pull/5/commits/9b1b30aab87cc405d68aafbf2e23136ac6ebcdb7），将这个settings.xml已经删掉了，所以没有该文件，可以将教程中流水线的bash指令：mvn clean -gs `pwd`/configuration/settings.xml test 修改为 mvn clean test  即可。

**Comment by chilianyi** [comment]
的确是这样，文档需要修改下：
https://www.kubesphere.io/zh/docs/v3.3/devops-user-guide/how-to-use/pipelines/create-a-pipeline-using-graphical-editing-panel/#%E9%98%B6%E6%AE%B5-2%E5%8D%95%E5%85%83%E6%B5%8B%E8%AF%95

@Bettygogo2021 帮忙安排修改下。

**Comment by zhuxiujuan28** [comment]
已修改
