### ISSUE TITLE
KubeSphere 版本 : v3.3.0  devops pipeline go-demo Reconciler error

### ISSUE THREAD

**Issue by alanmoleapfive** [kubesphere/kubesphere#5330]
**Describe the Bug**
(https://kubesphere.io/zh/docs/v3.3/devops-user-guide/examples/go-project-pipeline/)

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**
E1025 05:39:21.351037       1 devopsproject_controller.go:163] error syncing 'demo-devops86gj9': [ServiceError:302] 302, requeuing
I1025 05:39:21.425715       1 project_controller.go:52] ArgoCDProjectReconciler "msg"="start to reconcile project: /demo-devops86gj9"  
I1025 10:44:55.603939       1 project_controller.go:52] ArgoCDProjectReconciler "msg"="start to reconcile project: /go-devops4x5kz"  
I1025 10:44:55.684767       1 project_controller.go:52] ArgoCDProjectReconciler "msg"="start to reconcile project: /go-devops4x5kz"  
E1025 10:44:55.851540       1 project.go:46] GET http://devops-jenkins.kubesphere-devops-system/job/go-devops4x5kz/api/json: 404 <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404 Not Found</h2>
<table>
<tr><th>URI:</th><td>/job/go-devops4x5kz/api/json</td></tr>
<tr><th>STATUS:</th><td>404</td></tr>
<tr><th>MESSAGE:</th><td>Not Found</td></tr>
<tr><th>SERVLET:</th><td>Stapler</td></tr>
</table>
<hr><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.43.v20210629</a><hr/>

</body>
</html>
E1025 10:44:56.636649       1 project.go:29] 302
E1025 10:44:56.636760       1 devopsproject_controller.go:163] error syncing 'go-devops4x5kz': [ServiceError:302] 302, requeuing
I1025 10:44:56.659290       1 project_controller.go:52] ArgoCDProjectReconciler "msg"="start to reconcile project: /go-devops4x5kz"  
E1025 10:44:56.682246       1 devopsproject_controller.go:163] error syncing 'go-devops4x5kz': Operation cannot be fulfilled on devopsprojects.devops.kubesphere.io "go-devops4x5kz": the object has been modified; please apply your changes to the latest version and try again, requeuing
E1025 10:49:16.647224       1 project_pipeline.go:146] GET http://devops-jenkins.kubesphere-devops-system/job/go-devops4x5kz/job/go-demo/api/json: 404 <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404 Not Found</h2>
<table>
<tr><th>URI:</th><td>/job/go-devops4x5kz/job/go-demo/api/json</td></tr>
<tr><th>STATUS:</th><td>404</td></tr>
<tr><th>MESSAGE:</th><td>Not Found</td></tr>
<tr><th>SERVLET:</th><td>Stapler</td></tr>
</table>
<hr><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.43.v20210629</a><hr/>

</body>
</html>
E1025 10:49:16.660106       1 pipeline_metadata_controller.go:69] pipeline-metadata-controller "msg"="unable to obtain and update Pipeline metadata from Jenkins" "error"="not found resources" "Pipeline"={"Namespace":"go-devops4x5kz","Name":"go-demo"} 
E1025 10:49:16.669682       1 controller.go:246] controller "msg"="Reconciler error" "error"="not found resources" "controller"="pipeline" "name"="go-demo" "namespace"="go-devops4x5kz" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="Pipeline" 
E1025 10:49:20.436104       1 pipeline_controller.go:164] error syncing 'go-devops4x5kz/go-demo': Operation cannot be fulfilled on pipelines.devops.kubesphere.io "go-demo": the object has been modified; please apply your changes to the latest version and try again, requeuing
E1025 10:52:47.710918       1 pipelinerun_controller.go:184] pipelinerun-controller "msg"="unable to run pipeline" "error"="unexpected status code: 500" "Pipeline"="go-demo" "PipelineRun"={"Namespace":"go-devops4x5kz","Name":"go-demo-jsjpf"} "namespace"="go-devops4x5kz" "pipeline"="go-demo"
E1025 10:52:47.710990       1 controller.go:246] controller "msg"="Reconciler error" "error"="unexpected status code: 500" "controller"="pipelinerun" "name"="go-demo-jsjpf" "namespace"="go-devops4x5kz" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="PipelineRun"

**Comment by finalha** [comment]
I met the same issue.
The log of controller is: 
E1103 03:19:02.849314       1 pipelinerun_controller.go:184] pipelinerun-controller "msg"="unable to run pipeline" "error"="unexpected status code: 500" "Pipeline"="graphical-pipeline" "PipelineRun"={"Namespace":"demo-devopsbb9lr","Name":"graphical-pipeline-bs24g"} "namespace"="demo-devopsbb9lr" "pipeline"="graphical-pipeline"
E1103 03:19:02.849457       1 controller.go:246] controller "msg"="Reconciler error" "error"="unexpected status code: 500" "controller"="pipelinerun" "name"="graphical-pipeline-bs24g" "namespace"="demo-devopsbb9lr" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="PipelineRun" 
E1103 03:21:46.704390       1 pipelinerun_controller.go:184] pipelinerun-controller "msg"="unable to run pipeline" "error"="unexpected status code: 500" "Pipeline"="graphical-pipeline" "PipelineRun"={"Namespace":"demo-devopsbb9lr","Name":"graphical-pipeline-bs24g"} "namespace"="demo-devopsbb9lr" "pipeline"="graphical-pipeline"
E1103 03:21:46.704495       1 controller.go:246] controller "msg"="Reconciler error" "error"="unexpected status code: 500" "controller"="pipelinerun" "name"="graphical-pipeline-bs24g" "namespace"="demo-devopsbb9lr" "reconcilerGroup"="devops.kubesphere.io" "reconcilerKind"="PipelineRun" 

devops config in the ks-installer is:
  devops:
    enabled: true
    externalSonarToken: xxxxxxxxxxxxxxxxxxxxxxxxxx
    externalSonarUrl: 'http://172.16.132.97:59830'
    jenkinsJavaOpts_MaxRAM: 5g
    jenkinsJavaOpts_Xms: 1500m
    jenkinsJavaOpts_Xmx: 5000m
    jenkinsMemoryLim: 6Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 20Gi
    sonarqube: null

**Comment by yudong2015** [comment]
This is not a bug; The error message caused by the jenkins was not ready, and devops-controller can't connect to it;
