### ISSUE TITLE
通过ks-install 升级发现项目空间多了2个undefined

### ISSUE THREAD

**Issue by txyao** [kubesphere/kubesphere#5338]
![微信图片_20221028223813](https://user-images.githubusercontent.com/38243793/198652065-897a8821-1ddd-4994-9ead-f68e9b514c77.jpg)

**Comment by VioZhang** [comment]
多谢反馈，但是提issue尽量用英文，中文可以到中文论坛 https://kubesphere.com.cn/forum/

**Comment by zhou1203** [comment]
It may be cause by the cache gennerated by browser if you used KubeSphere before. Cleaning the cache can help you to fix the problem.
