### ISSUE TITLE
The signature is invalid after the member cluster is connected

### ISSUE THREAD

**Issue by yongxingMa** [kubesphere/kubesphere#5344]
**Describe the Bug**

**The signature is invalid after the member cluster is connected**

**Versions Used**
KubeSphere: v3.2.1

ks-apiserver log

[root@localhost ~]# docker logs -f 9a7946c29c90
W1101 15:35:42.825199       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W1101 15:35:42.828492       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W1101 15:35:42.846225       1 metricsserver.go:238] Metrics API not available.
W1101 15:35:42.846297       1 options.go:183] ks-apiserver starts without redis provided, it will use in memory cache. This may cause inconsistencies when running ks-apiserver with multiple replicas.
I1101 15:35:43.505114       1 interface.go:60] start helm repo informer
I1101 15:35:43.611714       1 apiserver.go:356] Start cache objects
I1101 15:35:45.611538       1 apiserver.go:562] Finished caching objects
I1101 15:35:45.611595       1 apiserver.go:278] Start listening on :9090
W1101 16:09:38.235967       1 issuer.go:187] jwt: failed to parse token: signature is invalid
W1101 16:09:38.236031       1 jwt.go:53] signature is invalid
W1101 16:09:38.237462       1 issuer.go:187] jwt: failed to parse token: signature is invalid
W1101 16:09:38.237506       1 jwt.go:53] signature is invalid
W1101 16:09:38.243739       1 issuer.go:187] jwt: failed to parse token: signature is invalid
W1101 16:09:38.243773       1 jwt.go:53] signature is invalid
W1101 16:10:30.473340       1 issuer.go:187] jwt: failed to parse token: signature is invalid
W1101 16:10:30.473381       1 jwt.go:53] signature is invalid
W1101 16:10:30.476224       1 issuer.go:187] jwt: failed to parse token: signature is invalid
W1101 16:10:30.476266       1 jwt.go:53] signature is invalid
W1101 16:12:50.029794       1 issuer.go:187] jwt: failed to parse token: signature is invalid
W1101 16:12:50.029842       1 jwt.go:53] signature is invalid
W1101 16:12:50.069957       1 issuer.go:187] jwt: failed to parse token: signature is invalid
W1101 16:12:50.069990       1 jwt.go:53] signature is invalid
W1101 16:12:50.152

![image](https://user-images.githubusercontent.com/31605966/199202140-a7a1f313-60d5-43d9-94fe-07db831e5d6a.png)

**Comment by iawia002** [comment]
@zhou1203 Can you help locate the problem? It looks like it has something to do with authentication.

**Comment by yongxingMa** [comment]
![image](https://user-images.githubusercontent.com/31605966/199212192-33011a1a-76e2-43e6-b2ec-d3d0a495254a.png)
it looks return error from here

**Comment by yongxingMa** [comment]
![image](https://user-images.githubusercontent.com/31605966/199212753-fc250940-6c69-4379-941d-8516c254e7e8.png)

**Comment by yongxingMa** [comment]
Problem solved！

`kubectl get cm -n kubesphere-system kubesphere-config -oyaml | grep jwt`

Because the jwtSecret of the host cluster and the member cluster are different
