### ISSUE TITLE
LDAP External Authentication not working

### ISSUE THREAD

**Issue by FlanniganColum** [kubesphere/kubesphere#5355]
**Describe the Bug**
After configuring the LDAP feature i attempted to login using a user account but i get nothing.. when i hit login it just does nothing at all, no error message no information absolutely nothing. Below is the config i used

I checked the ks-controller-manager and ks-console logs and could not see any issues or messages to identify the cause

    authentication:
    authenticateRateLimiterDuration: 10m0s
    authenticateRateLimiterMaxTries: 10
    jwtSecret: ""
    loginHistoryRetentionPeriod: 168h
    maximumClockSkew: 10s
    multipleLogin: true
    oauthOptions:
      accessTokenInactivityTimeout: 30m
      accessTokenMaxAge: 1h
      identityProviders:
      - mappingMethod: auto
        name: LDAP
        provider:
          host: X.X.X.X:389
          loginAttribute: cn
          mailAttribute: mail
          managerDN: CN=SERVICE_ACCOUNT,DC=example,DC=com
          managerPassword: SomePassword
          userSearchBase: CN=TestUsers,DC=example,DC=com
        type: LDAPIdentityProvider

**Versions Used**
KubeSphere: v3.3.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration: openSUSE 15.3 / 3 masters/workers

**How To Reproduce**
1. Configure LDAP to Active Directory
2. Wait for system to come back up
3. type username and password
4. nothing happens

**Expected behavior**
user to login

**Comment by UnknowViewer** [comment]
> same issue here, I'm using the '**sAMAccountName**' for `loginAttribute`

Finally found a workaround to fix this, I just restart the master/controller panel server and it works. You can refer to this [issue](https://github.com/kubesphere/kubesphere/issues/5185)
