### ISSUE TITLE
删除prometheus-operator和prometheus-k8s pod后，监控不可用，该如何修复

### ISSUE THREAD

**Issue by l19891223j** [kubesphere/kubesphere#5364]
KubeSphere v3.1.1 
因发现监控失效为NAN状态后，删除pod：prometheus-operator和prometheus-k8s ，无法自动拉起，监控不可用
#kubectl delete pod prometheus-k8s-0 -n kubesphere-monitoring-system
#kubectl delete pod prometheus-k8s-1 -n kubesphere-monitoring-system
#kubectl delete pod prometheus-operator-d7fdfccbf-hfxmp -n kubesphere-monitoring-system

![image](https://user-images.githubusercontent.com/538834/201371589-deb50a46-3870-48d4-b5bd-9dd7a3f979a7.png)
![image](https://user-images.githubusercontent.com/538834/201371657-812e46ff-8f83-4731-b7c7-37a729ad5fa5.png)
容器组找不到对应的容器，该如何恢复？

**Comment by hongzhouzi** [comment]
You can see if there are exception messages in the events. Also try to use English here, Chinese questions can be asked on the [kubesphere Chinese forum](https://kubesphere.com.cn/forum/), thanks.
