### ISSUE TITLE
Thare are same questions with cluster monitor data

### ISSUE THREAD

**Issue by ZengIan** [kubesphere/kubesphere#5366]
**Describe the Bug**

This is cluster monitor data, mainly CPU and Mem:
![image](https://user-images.githubusercontent.com/41040520/201571470-33e496cd-94d1-4874-a0b2-2840e611b796.png)
Mem usage is 41.6% at 06:50:15, it's about 3.24Gi
![image](https://user-images.githubusercontent.com/41040520/201570470-b062a449-91b8-4920-bc7c-1824b752eca6.png)
All namespace join to workspace.

I count all the workspaces'data with resource usage at 06:50, mainly these two:
![image](https://user-images.githubusercontent.com/41040520/201571904-1b74229b-185b-4a1a-8b1f-86346567459a.png)
![image](https://user-images.githubusercontent.com/41040520/201572144-13b6297b-7681-4441-9a12-361b559859a5.png)
The total is 2.28Gi, not 3.24Gi

**Environment**
How many nodes and their hardware configuration:
ubuntu 20.04
k8s 1.22.1
docker 20.10
ks 3.2.1

@viozhang

**Comment by frezes** [comment]
This is not a bug. Cluster monitoring is used to monitor physical resources, such as cpus, memory, and disks of nodes.  Namespace monitoring is monitoring of all Pods in a namespace. However, Cluster monitoring is not equal to all Namespace monitoring, but also includes resource consumption of the os and other binaries of the node.

**Comment by VioZhang** [comment]
We could add a tooltip to note the users the reason. 
/assign @XiaohuiSept @VioZhang
