### ISSUE TITLE
PV status display: Translation of the word "released"。

### ISSUE THREAD

**Issue by xianyuwu** [kubesphere/kubesphere#5371]
When the recycle mode is “Retain”，Perform the operation of deleting PVC.
Is it appropriate to translate "released" into "删除中"?
Easily misunderstood.
<img width="975" alt="image" src="https://user-images.githubusercontent.com/22258895/202338475-ea59874b-e56c-4af7-86eb-bd6ea784777c.png">
<img width="1024" alt="企业微信截图_f6c7d8ae-509a-4695-95e3-ce0696b623d8" src="https://user-images.githubusercontent.com/22258895/202337380-1d762007-e4d5-4774-b8c4-d8461f7af540.png">

@VioZhang

**Comment by VioZhang** [comment]
How about translate "released" to ”已释放“or”已解绑“？ @patrickluoyu @harrisonliu5

**Comment by xianyuwu** [comment]
The status indicator icon should be replaced by a static one, which is less eye-catching,Avoid users' wrong understanding.
