### ISSUE TITLE
Fresh install cant change admin password or add new user

### ISSUE THREAD

**Issue by dmoz-x** [kubesphere/kubesphere#5372]
I have a fresh install in Google kubernetes engine with private ip cluster, none of node has public ip but it can connect to internet via nat gateway. The installation is 100% success and can login to kubesphere but when i change password for the first time i got this error

`Internal error occurred: failed calling webhook "users.iam.kubesphere.io": Post "https://ks-controller-manager.kubesphere-system.svc:443/validate-email-iam-kubesphere-io-v1alpha2?timeout=30s": no endpoints available for service "ks-controller-manager"
`

Then I try to create another cluster with public ip in all nodes and everything work perfectly. 

Any suggest on this im not sure why private cluster is not work.

KubeSphere Version: v3.3.1
Kubernetest Version: 1.21.14-gke.9500

**Comment by hongzhouzi** [comment]
May be "ks-controller-manager" is not working, you can check the events and logs of "ks-controller-manager" to see what the problem is.

**Comment by halinwu** [comment]
I have same problem,  I think the services is ready , pls refer to the following info 
=======================================================
NAME                                         READY   STATUS    RESTARTS   AGE
pod/ks-apiserver-7c8c448bbb-ccz2r            1/1     Running   0          13h
pod/ks-console-54bd5bcbc6-9b4l8              1/1     Running   0          13h
pod/ks-controller-manager-86c48c45dd-rqc9m   1/1     Running   0          143m
pod/ks-installer-6976cf49f5-rwhpp            1/1     Running   0          13h

NAME                            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
service/ks-apiserver            ClusterIP   192.20.65.190   <none>        80/TCP         13h
service/ks-console              NodePort    192.20.78.179   <none>        80:30880/TCP   13h
service/ks-controller-manager   ClusterIP   192.20.67.57    <none>        443/TCP        13h
service/openldap                ClusterIP   None            <none>        389/TCP        13h

NAME                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/ks-apiserver            1/1     1            1           13h
deployment.apps/ks-console              1/1     1            1           13h
deployment.apps/ks-controller-manager   1/1     1            1           13h
deployment.apps/ks-installer            1/1     1            1           13h

NAME                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/ks-apiserver-7c8c448bbb            1         1         1       13h
replicaset.apps/ks-console-54bd5bcbc6              1         1         1       13h
replicaset.apps/ks-controller-manager-86c48c45dd   1         1         1       143m
replicaset.apps/ks-controller-manager-bdbb456f4    0         0         0       13h
replicaset.apps/ks-installer-6976cf49f5            1         1         1       13h

the log info 
======================================================================
I0113 04:21:05.957372       1 basecontroller.go:127] Successfully Synced key:admin-rc7mj in loginrecord-controller
I0113 04:21:05.957426       1 event.go:282] Event(v1.ObjectReference{Kind:"LoginRecord", Namespace:"", Name:"admin-rc7mj", UID:"a62a18a0-8ed4-4975-9f81-0bd14aa21dcb", APIVersion:"iam.kubesphere.io/v1alpha2", ResourceVersion:"160193", FieldPath:""}): type: 'Normal' reason: 'Synced' LoginRecord synced successfully
E0113 04:21:53.143748       1 pvc_autoresizer.go:108] pvc-autoresizer "msg"="metricsClient.GetMetrics failed" "error"="Post \"http://prometheus-operated.kubesphere-monitoring-system.svc:9090/api/v1/query\": dial tcp: lookup prometheus-operated.kubesphere-monitoring-system.svc on 192.20.64.10:53: no such host"
