### ISSUE TITLE
KubeKey | Cluster upgrade | Error: JWT secret MUST not be empty

### ISSUE THREAD

**Issue by FlanniganColum** [kubesphere/kubesphere#5376]
**Describe the Bug**
After performing an upgrade using the KubeKey for Kuberentes and Kubesphere version i am now getting the above error for the api-server which means i cannot login throught he UI and kubesphere is now broken

Upgrade command: ./kk upgrade --with-kubernetes v1.22.12 --with-kubesphere v3.3.1 -f sample.yaml

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/87829440/203126739-1b1cd580-9400-42c0-8bf3-9b4f71bb8dcd.png)

**Versions Used**
KubeSphere:v3.3.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters: openSUSE 15.3 / 3 nodes all master/control-plane nodes
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. Perform upgrade

**Expected behavior**

**Comment by FlanniganColum** [comment]
Log message 


# kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l 'app in (ks-apiserver)' -o jsonpath='{.items[0].metadata.name}') -f
Error: JWT secret MUST not be empty
2022/11/21 12:54:30 JWT secret MUST not be empty

**Comment by FlanniganColum** [comment]
When i changed something in the ks-installer and it redeployed it resolved this issue, i am guessing during the upgrade something went wrong and it didnt deploy the ks-installer correctly...

**Comment by undefine-man** [comment]
> When i changed something in the ks-installer and it redeployed it resolved this issue, i am guessing during the upgrade something went wrong and it didnt deploy the ks-installer correctly...

I am facing the same problem. Please tell me what didn't you changed.
