### ISSUE TITLE
3.3.1版集成外部kube-prometheus0.8，监控指标不全

### ISSUE THREAD

**Issue by lamesbond** [kubesphere/kubesphere#5377]
我在现有的k8s1.20.0版本上装的kubesphere3.3.1版本，执行这两步
kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.3.1/kubesphere-installer.yaml
kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.3.1/cluster-configuration.yaml
改了cluster-configuration.yaml配置，把type: external取消注释了，prometheus地址改成已有的：endpoint: http://prometheus-operated.monitoring.svc:9090，这样就不会和我集群里的kube-prometheus冲突，装完ks后页面上监控数据不全

有个令人费解的地方，文档上说用外部prometheus的话，只支持kube-prometheus0.6版的，但是安装ks带监控的话，里面的prometheus版本又是很高的，那理论上是不是支持高版本的外部kube-prometheus，只是我不知道怎么调serviceMonitor
![image](https://user-images.githubusercontent.com/53105658/204138101-091c129e-8a18-44a3-9915-53cce1d5e703.png)

**Comment by EndangeredF1sh** [comment]
最近有碰到相同问题，原因是自定义资源 `Prometheusrules` 缺少label导致用`kube-prometheus-stack`安装的Prometheus无法加载对应rules

解决方法为添加以下labels（未测试其中哪个有效，若有朋友测试请回复我）
```
app=kube-prometheus-stack
app.kubernetes.io/instance=prometheus
app.kubernetes.io/part-of=kube-prometheus-stack
```
至`Prometheusrules`: `prometheus-k8s-etcd-rules`和`prometheus-k8s-rules` （默认`namespace=monitoring`）

可一并删除在`namespace=kubesphere-monitoring-system`的`Prometheusrules`，其不起作用。

祝好

=============================
(English Version)
Some labels are missing in CR `Prometheusrules`, which causes the Prometheus installed with `kube-prometheus-stack` cannot load corresponding rules.

The solution is to add the following labels (I haven't tested which of them work, please reply if you have tested them)
```
app=kube-prometheus-stack
app.kubernetes.io/instance=prometheus
app.kubernetes.io/part-of=kube-prometheus-stack
```
to CR `Prometheusrules`: `prometheus-k8s-etcd-rules` and `prometheus-k8s-rules` (in namespace `monitoring` by default)

You may also remove `Prometheusrules` in namespace `kubesphere-monitoring-system`. They are not working.

Happy coding!

**Comment by lamesbond** [comment]
找到原因了，ks自带的kube-prometheus，在官方的基础上加了些record，生成了一些自定义指标，具体哪些我是直接在源码里找的

![image](https://user-images.githubusercontent.com/53105658/206945596-38ba0a60-53ba-4a83-96d5-7a8a90b87cb4.png)

**Comment by kalavt** [comment]
这个有啥办法解决么? 单独拎出来作为dashboard exporter?

**Comment by EndangeredF1sh** [comment]
> 这个有啥办法解决么? 单独拎出来作为dashboard exporter?

先在Prometheus面板上查看以下自定义Rules是否存在：
![image](https://user-images.githubusercontent.com/26084344/223459423-4ae9a91a-6f43-4f9b-8b75-84763f9a487c.png)

如果不存在，找到上面提到的自定义资源添加对应Label，Prometheus自动重新加载配置后可找到规则即可。

重点就在于如何使Prometheus加载写有这些自定义规则的配置

**Comment by kalavt** [comment]
感谢大佬指点，已经修复了

**Comment by duhao1027** [comment]
> 感谢大佬指点，已经修复了
大佬怎么解决的？我外部的Prometheus已经识别到了这些规则，但ks上还是没有数据

**Comment by EndangeredF1sh** [comment]
> > 感谢大佬指点，已经修复了
> > 大佬怎么解决的？我外部的Prometheus已经识别到了这些规则，但ks上还是没有数据

先看State是不是都OK，再重启ks-apiserver试试
如果不行就找指标对应的表达式手动执行下看看有没有结果，如果没有可能是ServiceMonitor的问题

**Comment by duhao1027** [comment]
可以了 多谢大佬
