### ISSUE TITLE
adding edge nodes edge.crt": x509: certificate is valid  helm uninstall kubeedge: release: not found

### ISSUE THREAD

**Issue by alanmoleapfive** [kubesphere/kubesphere#5382]
When adding kubeede in kubesphere 3.3.1, the following two problems occurred
Uninstall KubeEdge
Change the value of kubeedege.enabled and edgeruntime.enabled in parameter ks-installer in CRD ClusterConfiguration configuration file from true to false.
run the following command
helm list -n kubeedge
NAME NAMESPACE REVISION UPDATED STATUS CHART APP VERSION
cloudcore kubeedge 3 2022-11-24 16:19:46.005123977 +0800 CST deployed cloudcore-0.2.0 1.9.2
helm uninstall kubeedge -n kubeedge
Error: uninstall: Release not loaded: kubeedge: release: not found
how do i uninstall

Another problem arises when adding edge nodes
certmanager.go:93] Error: failed to get edge certificate from the cloudcore, error: Get "https://192.168.1.63:30002/edge.crt": x509: certificate is valid for 10.244.4.25, not 192.168.1.63
After using kubectl delete secret casecret cloudcoresecret -n kubeedge, there is still no way to add it successfully

**Comment by charnet1019** [comment]
@alanmoleapfive Did you resolved?
