### ISSUE TITLE
Deployment with a custom version number of a private container repository fails

### ISSUE THREAD

**Issue by GlodenBoy** [kubesphere/kubesphere#5384]
The private repository of Alibaba Cloud used during deployment has N images with the same content in the repository, but the versions are different, one version is latest, and the other is 1.0, 2.0, 3.0.

Only late can be deployed successfully, other deployments will prompt InvalidImageName, the image is the same.

After Yaml file troubleshooting, it was found that when deploying with UI, filling in the version number in the container search will come out, but when the final splicing is made, a / will be added before the version number, so the image will not be found, and latest is not required to add the version number So it is normal, it should be an official BUG

Example:
 correct -> registry.cn-beijing.aliyuncs.com/test_repositories/bug:1.0

Error-> registry.cn-beijing.aliyuncs.com/test_repositories/bug/:1.0    generated by kubesphere

**Comment by harrisonliu5** [comment]
Can you provide a current version and a screenshot to help us better understand this issue? @GlodenBoy

**Comment by GlodenBoy** [comment]
> 
Sorry, there are no screenshots, because this is a bug I found during the trial, this problem will cause me to be very inconvenient to use, so I temporarily abandoned using kubesphere, the version is the latest, until now I estimate that it has not been fixed, if you have Alibaba Cloud's container cloud, the repro method is very simple, just add the container cloud and search for your container name in the add container panel to add it

**Comment by wenxin-01** [comment]
I can't reproduce this problem
![image](https://user-images.githubusercontent.com/68640256/212652845-10333acf-8732-4c5c-8573-aa5417d6c6b8.png)
