### ISSUE TITLE
Error JWT Token Expired

### ISSUE THREAD

**Issue by vijaykumarmoki** [kubesphere/kubesphere#5385]
Error Description:

I am now getting the following error when i tried to login to ks console.(host) - 

Session Timeout or this account logged elsewhere, please login again

Kubernetes version: 1.24

in api-server logs following entries are present - (host)

I1118 12:00:12.538552       1 apiserver.go:298] Start listening on :9090
W1121 13:12:24.768193       1 jwt.go:53] jwt: token is expired by 79h22m56s
W1121 13:12:24.773310       1 jwt.go:53] jwt: token is expired by 79h22m56s
W1121 13:12:24.773425       1 jwt.go:53] jwt: token is expired by 79h22m56s
W1121 13:12:24.773451       1 jwt.go:53] jwt: token is expired by 79h22m56s
W1121 13:12:24.773426       1 jwt.go:53] jwt: token is expired by 79h22m56s

E1123 11:52:41.896732       1 utils.go:76] /workspace/pkg/kapis/iam/v1alpha2/handler.go:81 user.iam.kubesphere.io "xxxxxxxx" not found
I1123 11:52:41.896757       1 apiserver.go:637] undefined - "GET /kapis/iam.kubesphere.io/v1alpha2/users/user.test HTTP/1.1" 500 45 0ms
E1124 06:55:51.621013       1 upgradeaware.go:326] Proxy upgrade error: invalid upgrade response: status code 200
E1124 06:55:51.621051       1 errors.go:77] invalid upgrade response: status code 200

Tried restrting pods in kubsphere-system namespace but no luck.

following are logs in ks-console pod

{
  code: 403,
  kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message: 'configmaps "kubesphere-config" is forbidden: User "xxxxxxxx" cannot get resource "configmaps" in API group "" in the namespace "kubesphere-system"',
  reason: 'Forbidden',
  details: { name: 'kubesphere-config', kind: 'configmaps' },
  statusText: 'Forbidden'
}

checked jwt token on both host and member cluster value is same, in member cluster token expiry time is 0s(in kubesphere-config configmap)

**Comment by wansir** [comment]
Please check the status of kubefed in host cluster.

**Comment by vijaykumarmoki** [comment]
@wansir  thanks for response

kubefed status is up and running
checked status and logs of kubefed controller and webhook no error registered in logs.
