### ISSUE TITLE
内置策略达到阈值后没有触发

### ISSUE THREAD

**Issue by hhy62** [kubesphere/kubesphere#5391]
使用官网3.3.1版本demo环境，内置策略达到阈值后在告警栏中未发现已出发的告警

构造了一个失败pod
![image](https://user-images.githubusercontent.com/108912016/204458854-c2f1917c-3790-447f-9396-85f983f7e8b2.png)

查看内置策略中的KubePodNotReady，已达到阈值且超过持续时间
![image](https://user-images.githubusercontent.com/108912016/204459026-11e5ba93-b50b-48dd-b9f2-513b00b39bcc.png)

查看告警中的内置策略告警，没有已触发的告警
![image](https://user-images.githubusercontent.com/108912016/204459247-4e472416-b88d-4a6c-b88b-dc97b566333f.png)

**Comment by lijianzhi** [comment]
可以修改pkg\models\alerting\rules\cache.go的
&resourceRuleCache{
		//Name:      pr.Name,
		Name:      pr.Name + "-" + string(pr.UID),
		Labels:    pr.Labels,
		GroupSet:  groupSet,
		IdRules:   idRules,

**Comment by hhy62** [comment]
@lijianzhi 感谢您的解答，我试过您的方法，改完之后内置策略确实可以触发，但是自定义策略又不触发了
