### ISSUE TITLE
Kubesphere offline install too many image

### ISSUE THREAD

**Issue by ZZQ001010** [kubesphere/kubesphere#5397]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**General remarks**

> Please delete this section including header before submitting
>
> This form is to report installation issues. For general usage questions you can refer to [KubeSphere Documentation](https://kubesphere.io/docs) or join our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE)

**What's your question**
I installed kubesphere 3.3 offline, but I found that there are really too many images. There are 165, which are enough for 50G, which is too big. Can you provide a simplified version?

**Environment: OS & Hardware Information**

> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).

**Error logs or message (Attach logs or screenshot)**

**Installer Version**
3.3

**Comment by zzq1314zll** [comment]
https://kubesphere.io/zh/docs/v3.3/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped/#kubesphere-33-%E9%95%9C%E5%83%8F%E6%B8%85%E5%8D%95
