### ISSUE TITLE
Prometheus CrashLoopBackOff

### ISSUE THREAD

**Issue by dayongi** [kubesphere/kubesphere#5404]
I deployed kubesphere 3.3.0 in minikube, but CrashLoopBackOff occurs on prometheus-k8s-0：

![image](https://user-images.githubusercontent.com/41787764/206524539-a1f7f702-ecf8-46f6-bd91-6bd636959e7c.png)
![image](https://user-images.githubusercontent.com/41787764/206524603-8aeb59fa-a474-4017-9f3c-d89640935c5f.png)

I don't know what causes this？

**Comment by qingwave** [comment]
Hi @dayongi, 

Looks likes insufficient cpu quotas, sames with  https://www.singlestore.com/forum/t/deployment-error-on-k8s/3934/4

Solution as follows, increase cpus when start minikue:
> minikube start –cpus 16
