### ISSUE TITLE
Create Service by jar/war, the image url is unmatch

### ISSUE THREAD

**Issue by ZengIan** [kubesphere/kubesphere#5410]
**Describe the Bug**

When a service is created through a jar/war, the image address default is the dockerhub, not the private url at build time
![713ab2f797d569b12f436bab749c6d3](https://user-images.githubusercontent.com/41040520/206954159-eef97a3b-459d-46cf-b0fe-585e522f2c04.png)
![9e8505df77a1204f2cbcbfa75feefec](https://user-images.githubusercontent.com/41040520/206954171-6910a71f-0008-4f3a-8090-505bc6d2038f.png)

**Versions Used**
KubeSphere: ks 3.2.1

**Comment by chilianyi** [comment]
It is a bug, we will fix it next version, thanks for your feedback

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-console:nightly-20230131`

![image](https://user-images.githubusercontent.com/68640256/215964468-8e63e519-6042-4c62-b52c-b9ef8df7d156.png)

![image](https://user-images.githubusercontent.com/68640256/215964334-5b0066ed-c337-4ee2-8eff-13ee17f10c40.png)
