### ISSUE TITLE
[oidc] no scope query parameter in oidc authrization request 

### ISSUE THREAD

**Issue by Taoup** [kubesphere/kubesphere#5411]
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:3.3.0
Kubernetes: (If KubeSphere installer used, you can skip this)

cluster config:
![image](https://user-images.githubusercontent.com/22348542/207270639-157b96e2-9293-4007-9d62-1e41ef99e559.png)

no scope query parameter:
![image](https://user-images.githubusercontent.com/22348542/207269680-e5adf975-afec-45cd-889e-9a51457312da.png)

error response from oidc server:
![image](https://user-images.githubusercontent.com/22348542/207270950-c777c39e-dc5d-427d-ab44-cc8069901824.png)

& the response uri:
http://172.22.23.15:30880/oauth/redirect/test?error=invalid_request&error_description=missing%20required%20parameter(s)%20scope&state=test

**Comment by wansir** [comment]
@Taoup Please pay attention to indentation. 

```
...
provider:
  issuer: 'xxx'
  scopes:
  - openid
  - profile
...
```
