### ISSUE TITLE
offline install tools in v3.3.1 can't don't have -v argument

### ISSUE THREAD

**Issue by zj452008181** [kubesphere/kubesphere#5415]
curl -L -O https://github.com/kubesphere/ks-installer/releases/download/v3.3.1/offline-installation-tool.sh
![image](https://user-images.githubusercontent.com/26154743/207566181-0ea417fd-1ec5-449b-98dd-fc1d81c1cca8.png)

**Comment by fengshunli** [comment]
Assign it to me @wansir

**Comment by fengshunli** [comment]
see https://github.com/kubesphere/ks-installer/pull/2155
