### ISSUE TITLE
Error : Kubesphere Installation ks-apiserver-5f7b5dcd4c-99k7h

### ISSUE THREAD

**Issue by apsth456** [kubesphere/kubesphere#5423]
W1218 09:12:51.667563       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W1218 09:12:51.671321       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W1218 09:12:51.713050       1 metricsserver.go:238] Metrics API not available.
W1218 09:12:51.713182       1 options.go:191] ks-apiserver starts without redis provided, it will use in memory cache. This may cause inconsistencies when running ks-apiserver with multiple replicas.
I1218 09:12:51.713203       1 interface.go:50] start helm repo informer
I1218 09:12:52.077624       1 apiserver.go:417] Start cache objects
Error: failed to fetch group version resources batch/v1beta1: the server could not find the requested resource
2022/12/18 09:12:52 failed to fetch group version resources batch/v1beta1: the server could not find the requested resource

**Comment by dkeven** [comment]
Are you installing Kubesphere on top of a v1.25 or above (which is not supported, yet) Kubernetes cluster?

Please check the prerequisite section of this documentation: https://kubesphere.io/docs/v3.3/quick-start/minimal-kubesphere-on-k8s/

**Comment by apsth456** [comment]
Help me ? 

Available
Status: False
Reason: MinimumReplicasUnavailable
Message: Deployment does not have minimum availability.


ReplicaFailure
Status: True
Reason: FailedCreate
Message: admission webhook "resourcesquotas.quota.kubesphere.io" denied the request: pods "test-app2-7db8f6c85c-skfwm" is forbidden: exceeded quota: kubesphere-system, requested: limits.cpu=2, used: limits.cpu=4, limited: limits.cpu=2

**Comment by ymqing-sre** [comment]
I encountered the same problem.
