### ISSUE TITLE
Do not use metadata.generateName as display name of a Group in UI

### ISSUE THREAD

**Issue by 27149chen** [kubesphere/kubesphere#5433]
**Describe the Bug**
I try to backup a workspace and restore it to another ks system. But after restore, I find that the name of a Group is gone in UI (show undefined). It seems that metadata.generateName is used to display the name. But generateName will be removed during restore (I prefer to keep name instead of generateName because other resources may refer to it).

Here is the screenshot:
![209419194-07d5c3cc-2cf1-4580-89d2-bad2b46a0473](https://user-images.githubusercontent.com/7991675/209520166-4a206aa7-83a2-4f62-86e6-2386b1cc3fbe.png)

**Versions Used**
KubeSphere: v3.2.1

**How To Reproduce**
1. backup a workspace
2. restore it to another ks system
3. See the issue as the screenshot mentioned

**Expected behavior**
The right name should be displayed in UI

**Comment by Mcquang** [comment]
> **Mô tả lỗi** Tôi cố gắng sao lưu một không gian làm việc và khôi phục nó vào một hệ thống ks khác. Nhưng sau khi khôi phục, tôi thấy rằng tên của Nhóm đã biến mất trong giao diện người dùng (hiển thị không xác định). Có vẻ như metadata.generateName được sử dụng để hiển thị tên. Nhưng GenerName sẽ bị xóa trong quá trình khôi phục (Tôi thích giữ lại tên thay vì GenerName vì các tài nguyên khác có thể đề cập đến nó).
> 
> Đây là ảnh chụp màn hình: ![209419194-07d5c3cc-2cf1-4580-89d2-bad2b46a0473](https://user-images.githubusercontent.com/7991675/209520166-4a206aa7-83a2-4f62-86e6-2386b1cc3fbe.png)
> 
> **Các phiên bản** KubeSphere đã sử dụng: v3.2.1
> 
> **Cách tái tạo** Các bước để tái tạo hành vi:
> 
> 1. sao lưu không gian làm việc
> 2. khôi phục nó vào hệ thống ks khác
> 3. Xem vấn đề như ảnh chụp màn hình được đề cập
> 
> **Hành vi dự kiến**​​Tên đúng sẽ được hiển thị trong giao diện người dùng

ncc

**Comment by dkeven** [comment]
/cc @wansir 
seems spam bot here
