### ISSUE TITLE
Network isolation layer in projects display the services of other customers.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5444]
**Describe the Bug**
Now the services of other customers are displayed but only the customer's services to be visible on this screen
For UI issues please also add a screenshot that shows the issue.
![8defd95f9874283c1d2807054ab8ef4](https://user-images.githubusercontent.com/41519383/210951996-51026d46-a96c-469d-b7ad-08233043b752.png)

**Comment by wenxin-01** [comment]
`kubespheredev/ks-console:release-3.3`  Only allow communication within the same workspace, is it as expected? @VioZhang 

![image](https://user-images.githubusercontent.com/68640256/212623386-49873343-9a82-4c47-92f1-117388e8a841.png)
![image](https://user-images.githubusercontent.com/68640256/212623442-66c162b3-e454-4ca9-96d5-29f50938addd.png)

**Comment by Bettygogo2021** [comment]
Fixed in https://github.com/kubesphere/console/pull/4068.

**Comment by wenxin-01** [comment]
Chinese is not modified. @Bettygogo2021 
![image](https://user-images.githubusercontent.com/68640256/215371986-ed6f5e33-1533-47dd-ac75-922a1f2d3de7.png)

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-console:nightly-20230131`

![image](https://user-images.githubusercontent.com/68640256/215961807-4ce9c21c-21ec-472f-9efa-aa893012441d.png)
