### ISSUE TITLE
Bookinfo projects created without servicemesh enabled should have Application Governance turned off by default

### ISSUE THREAD

**Issue by hongzhouzi** [kubesphere/kubesphere#5449]
**Describe the Bug**
Bookinfo projects created without servicemesh enabled should have Application Governance **turned off by default**, otherwise it will create an application with application governance enabled but without the functionality that application governance should have, which will cause ambiguity.

![image](https://user-images.githubusercontent.com/36416216/211277023-ded69060-3c61-45ab-843d-2ad4d109a4d2.png)

**Versions Used**
KubeSphere: ks 3.2/3.3

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-console:release-3.3`

![image](https://user-images.githubusercontent.com/68640256/212613713-be293f02-5f6c-4af3-9944-b34e5510df62.png)
