### ISSUE TITLE
KubeSphere v3.3.1 does not support running on Kubernetes v1.24.9

### ISSUE THREAD

**Issue by todortanevski** [kubesphere/kubesphere#5452]
**Describe the Bug**
KubeSphere v3.3.1 does not support running on Kubernetes v1.24.9

This combination IS supported by:
* https://kubesphere.io/docs/v3.3/installing-on-linux/introduction/kubekey/#support-matrix
* ./kk version --show-supported-k8s

**Versions Used**
KubeSphere: v3.3.1
Kubernetes: v.1.23.15
containerd://1.6.14

**Environment**
Oracle Linux Server 8.7 / 3 masters:  6cpu/80g; 3 nodes: 8cpu/100g

**How To Reproduce**
1.  ./kk create config --from-cluster
2.  vim sample.yaml
3.  sudo ./kk upgrade --with-kubernetes v1.24.9 --with-kubesphere v3.3.1 -f sample.yaml

**Expected behavior**
Upgrade process completed without errors.

**Comment by wenxin-01** [comment]
Hi @todortanevski, do you want to install or upgrade kubesphere?

**Comment by todortanevski** [comment]
@wenxin-01 I want to *upgrade* existing kubesphere-installed cluster. evyrithing is set, sample.yaml has been produced using the kk, modified it with proper credentials and kubernetes version, and line is as described above.

**Comment by wenxin-01** [comment]
> @wenxin-01 I want to _upgrade_ existing kubesphere-installed cluster. evyrithing is set, sample.yaml has been produced using the kk, modified it with proper credentials and kubernetes version, and line is as described above.

There is an issue in kk, we will fix it in next version of kk. Maybe you can upgrade k8s with v1.23.x for now.
Thanks for you feedback.

**Comment by todortanevski** [comment]
@wenxin-01 this is already updated to v.1.23.x. I built kk from source to accommodate latest changes - that is how I installed v.1.24.x previous month (wouldn't do with the pre-built kk binaries). 
when can we expect the new improved kk?
thanks!!

**Comment by wenxin-01** [comment]
@todortanevski You can use kk after this fixed.
https://github.com/kubesphere/kubekey/issues/1705
