### ISSUE TITLE
The pods's status is not consistent with the list.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5461]
**Describe the Bug**
The pods's status is not consistent with the list.
For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/41519383/212015018-7e811eea-9d9c-4b46-9000-227fdea8afe1.png)
![image](https://user-images.githubusercontent.com/41519383/212015052-af475c48-c978-4076-a421-b9cc0dc7cc36.png)

**Comment by wenxin-01** [comment]
Issue not fixed in 'kubespheredev/ks-installer:release-3.3'

![image](https://user-images.githubusercontent.com/68640256/212617071-75668cf5-2d12-4773-a7ff-84a98a579857.png)

**Comment by wenxin-01** [comment]
Issue not fixed 
@harrisonliu5  
https://github.com/kubesphere/kubesphere/pull/5483   The mentioned status enum: ["Waitting", "Running", "Completed", "Error"], inconsistent with the modification here
![image](https://user-images.githubusercontent.com/68640256/212831953-4c589a6a-e640-4673-abcc-05cf516748cf.png)

**Comment by wenxin-01** [comment]
filter result error. @frezes 

![image](https://user-images.githubusercontent.com/68640256/213061871-51456471-bf67-4793-ae28-c502dac14556.png)
![image](https://user-images.githubusercontent.com/68640256/213061911-0613854d-9cd6-4756-85ed-65bfe2e50e03.png)

**Comment by wenxin-01** [comment]
Issue fixed in `kubesphere/ks-apiserver:release-3.3`  `kubespheredev/ks-console:release-3.3`

![image](https://user-images.githubusercontent.com/68640256/213064938-f95e0b0f-f9a9-4852-ad0b-75c2319b82ef.png)
![image](https://user-images.githubusercontent.com/68640256/213064980-d15b4720-f3f2-4501-9c50-e7fc0657e8ba.png)
