### ISSUE TITLE
There is a parsing error in sidecard's yaml file

### ISSUE THREAD

**Issue by lihai2099** [kubesphere/kubesphere#5469]
My namespace must have resource limit,So the default log auto-injection service cannot be injetced successfully.
I tried to modify the sidecard configuartion as follow:
![image](https://user-images.githubusercontent.com/32237482/211440045-506c8b2e-fd4a-4346-a08c-f366a683250f.png)
Then I restart the service,and found that a container failed to start.
![image](https://user-images.githubusercontent.com/32237482/211440071-6ea08096-f308-409d-8cc0-8c3a98227367.png)
The container log:
![image](https://user-images.githubusercontent.com/32237482/211440011-13184ac2-f611-4228-8b72-4743b3476080.png)

The suspect is thar there is a problem with yaml parsing.

**Comment by wenxin-01** [comment]
Issue fixed in `ks-installer v3.3.2-rc.1`

![image](https://user-images.githubusercontent.com/68640256/215372596-61025662-236c-46ea-85a2-8f7978b8339b.png)
