### ISSUE TITLE
There is no imformation of maintainers when importing the third-part registry.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5478]
https://github.com/kubesphere/kubesphere/pull/5401
/assign @isyes

**Comment by wenxin-01** [comment]
Issue fixed in `ks-v3.3.2-rc.1`

![image](https://user-images.githubusercontent.com/68640256/215665344-4a71a159-bc71-4e1a-a470-0ee70c3f5216.png)
![image](https://user-images.githubusercontent.com/68640256/215665622-5f167157-11fc-4493-861b-96e7ffe52d04.png)
