### ISSUE TITLE
devops custom  jenkins agent  deploy vue application error  docker: not found script returned exit code 127

### ISSUE THREAD

**Issue by qweqe417** [kubesphere/kubesphere#5526]
<img width="932" alt="微信截图_20230215224158" src="https://user-images.githubusercontent.com/56719201/219066498-af94d0fb-5ae2-4fb5-8a7d-481ff0777144.png">
<img width="716" alt="微信截图_20230215224219" src="https://user-images.githubusercontent.com/56719201/219066509-9f5e9749-c57d-4dbe-8566-f03e8abf1590.png">
<img width="781" alt="微信截图_20230215224241" src="https://user-images.githubusercontent.com/56719201/219066513-1dd75519-dc1a-4d12-80ee-c64031e81f7d.png">
<img width="716" alt="微信截图_20230215224258" src="https://user-images.githubusercontent.com/56719201/219066526-ec9fd629-e6aa-4825-b815-85275e73c10d.png">
<img width="648" alt="微信截图_20230215224317" src="https://user-images.githubusercontent.com/56719201/219066533-9e498bd7-b0b2-4e48-9570-725a8797f446.png">
<img width="932" alt="微信截图_20230215224626" src="https://user-images.githubusercontent.com/56719201/219066555-b3a747e2-488e-448b-b6fa-97a5af3be9ac.png">
<img width="649" alt="微信截图_20230215224832" src="https://user-images.githubusercontent.com/56719201/219066583-43c1c806-52f3-48e9-9355-9cb10173b9c3.png">
<img width="652" alt="微信截图_20230215230223" src="https://user-images.githubusercontent.com/56719201/219066618-d1a8ba70-afb7-4bcc-8234-2e19e6bc5ad9.png">
<img width="630" alt="微信截图_20230215230246" src="https://user-images.githubusercontent.com/56719201/219066633-e8484f34-4c18-44fc-be2d-4075c26afc0b.png">
<img width="520" alt="微信截图_20230215230329" src="https://user-images.githubusercontent.com/56719201/219066648-525d7476-62e7-4b56-b3bc-58decde709ec.png">

**Comment by qweqe417** [comment]
docker Manual sure structure image ，use devops  error

**Comment by thapld** [comment]
same issue

![image](https://user-images.githubusercontent.com/38736191/221092377-d615b52d-dd05-4d62-abb5-24c2415065d8.png)

**Comment by thapld** [comment]
@qweqe417 Solved it?

**Comment by littlejiancc** [comment]
same issue too!
<img width="911" alt="image" src="https://user-images.githubusercontent.com/23724009/223631664-c1d315a9-d1fb-49db-ac79-7b13dea4b0cf.png">
Docker has been installed in the agent
<img width="508" alt="image" src="https://user-images.githubusercontent.com/23724009/223631765-5520f054-64c3-4dcd-a89e-a2b17ebdede9.png">

**Comment by qweqe417** [comment]
resolved

**Comment by qweqe417** [comment]
I am consult https://github.com/kubesphere/devops-agent/blob/master/nodejs/Dockerfile  custom nodejs images Solved

**Comment by nowll** [comment]
hey i am facing the same issue, can you explain what you do to solve the error?

@qweqe417
