### ISSUE TITLE
从helm模板创建应用失败

### ISSUE THREAD

**Issue by DustFinger001** [kubesphere/kubesphere#554]
当使用模板仓库创建应用是，因为的我的应用服务特别多，会导致 openpitrix 报插入数据的additional_info 字段过长而出错。
![image](https://user-images.githubusercontent.com/16345979/60634679-602b6e80-9e42-11e9-93ca-3030d99e489f.png)

**Comment by zryfish** [comment]
这个字段大概有多长呢，我们调整下字段大小

**Comment by DustFinger001** [comment]
我这里一个应用大概有10-20个服务，算下来应该有200-400个字符
