### ISSUE TITLE
autoscaling/v2beta2 not support in k8s v1.26

### ISSUE THREAD

**Issue by HeWeiGitHub** [kubesphere/kubesphere#5549]
## autoscaling/v2beta2 not support in k8s v1.26

**when kubesphere v3.3.1 installing ，autoscaling/v2beta2 not find**

**Environment: OS & Hardware Information**

> ubuntu 22.04.
> k8s v1.26.1
> kubesphere v3.3.1

**Error logs or message (Attach logs or screenshot)**

root@ubuntu-one:/# kubectl logs -n kubesphere-system ks-apiserver-6fd879c6f9-7hnk4
W0222 13:51:08.814999       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0222 13:51:08.816313       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0222 13:51:08.827924       1 metricsserver.go:238] Metrics API not available.
W0222 13:51:08.828144       1 options.go:191] ks-apiserver starts without redis provided, it will use in memory cache. This may cause inconsistencies when running ks-apiserver with multiple replicas.
I0222 13:51:08.828232       1 interface.go:50] start helm repo informer
I0222 13:51:09.141686       1 apiserver.go:417] Start cache objects
Error: failed to fetch group version resources autoscaling/v2beta2: the server could not find the requested resource
2023/02/22 13:51:09 failed to fetch group version resources autoscaling/v2beta2: the server could not find the requested resource

the k8s web information:
![image](https://user-images.githubusercontent.com/25758090/220556001-79fe439b-387e-4f62-973a-32161134ea84.png)

**Installer Version**

> kubesphere v3.3.1

**Comment by liuhaichaogithub** [comment]
一样的问题，去哪里修改啊

**Comment by kilvn** [comment]
别改了，重启docker又恢复了，没意义。
