### ISSUE TITLE
kubesphere install

### ISSUE THREAD

**Issue by darrenli6** [kubesphere/kubesphere#5553]
**Describe the Bug**

<img width="696" alt="image" src="https://user-images.githubusercontent.com/23740296/221342417-d0a93f42-0800-4c73-9f89-4a493e90ba1d.png">

<img width="766" alt="image" src="https://user-images.githubusercontent.com/23740296/221342440-98e617af-2b67-4be9-a7db-4db8699479cb.png">

 

I have storageClass,but kubephere log show "Default StorageClass was not found !"
why? 

**Versions Used**
KubeSphere: v3.3.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:
ubuntu 8cpu/16g

 

**How To Reproduce**

**Expected behavior**
install successfully

**Comment by frezes** [comment]
https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/

**Comment by darrenli6** [comment]
> You need to set "nfs-csi" to default storage class. https://kubernetes.io/docs/tasks/administer-cluster/change-default-storage-class/

thanks .
