### ISSUE TITLE
能不能把创建pod时设置容器资源限制 滑动设置的功能给恢复回来

### ISSUE THREAD

**Issue by wwt164888** [kubesphere/kubesphere#5569]
**What's it about?**

**What's the reason why we need it?**

I believe this is an important feature for Kubesphere. There're a few use cases:

* case one
* case two
* ...

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

**Comment by Gentleelephant** [comment]
This will be discussed later.

**Comment by Gentleelephant** [comment]
@VioZhang

**Comment by VioZhang** [comment]
原因是?

**Comment by VioZhang** [comment]
4.0 之后我们会优化相关的设计
