### ISSUE TITLE
Devops issue: Internal Server Error, Run XXX not found in organization jenkins and pipeline

### ISSUE THREAD

**Issue by spygea** [kubesphere/kubesphere#5571]
Guys, I am trying demo project on kubesphere devops but failed, when I looked into logs it poped up:  "Internal Server Error, Run 18 not found in organization jenkins and pipeline" .  Any idea? Thanks 
![企业微信截图_16782464164575](https://user-images.githubusercontent.com/102199201/223614655-1751d702-21f0-4cae-965e-92a249cba16e.png)

**Comment by Gentleelephant** [comment]
@yudong2015 Help with this question.

**Comment by spygea** [comment]
> @yudong2015 Help with this question.

Thanks for your response. It's my operation problem  and I fixed it already, Now I will close the ticket.

Thanks again.
