### ISSUE TITLE
求助，监控面板获取不到POD的mem/cpu指标

### ISSUE THREAD

**Issue by huapox** [kubesphere/kubesphere#5597]
如图，ks-core及prom两部分为从ks-installer安装过后的文件中拷贝出来，再次手动安装的（当前其它都正常）

![图片](https://user-images.githubusercontent.com/6138651/225943640-1988d6f0-cd84-4637-a37d-755789272f3a.png)

接口返回数据如下图：（相关指标:""）无值

![图片](https://user-images.githubusercontent.com/6138651/225948098-036a45e3-8e3d-42ac-a311-a2a3d52c2074.png)

**Comment by huapox** [comment]
这里找不到`kube_pod_overhead_memory_bytes `

```bash
[root@kube-state-metrics-7db47c648c-t4mgz ~]# curl -s localhost:8081/metrics |grep overhead
# HELP kube_pod_overhead_cpu_cores The pod overhead in regards to cpu cores associated with running a pod.
# TYPE kube_pod_overhead_cpu_cores gauge
# HELP kube_pod_overhead_memory_bytes The pod overhead in regards to memory associated with running a pod.
# TYPE kube_pod_overhead_memory_bytes gauge
```

**Comment by hongzhouzi** [comment]
@frezes Can you help with this problem?

**Comment by frezes** [comment]
It looks like the `servicemonitor` configuration is missing. Check if [it](https://github.com/kubesphere/ks-installer/blob/master/roles/ks-monitor/files/prometheus/kubernetes/kubernetes-serviceMonitorKubelet.yaml) exists. @huapox

**Comment by wsndng** [comment]
我安装后，也是一样的情况，CPU和内存监控也没有，容器内的节点监控也是空的

**Comment by wsndng** [comment]
![w](https://user-images.githubusercontent.com/40561376/226512808-86690b84-dd20-46f7-9e81-b7f9d903ba48.png)
![w1](https://user-images.githubusercontent.com/40561376/226512894-6119dfc5-550f-49d6-9713-a5eb4858d663.png)

**Comment by frezes** [comment]
Expose the prometheus service and access its console. Check the kubelet target.

![image](https://user-images.githubusercontent.com/19492214/226842285-31649cd2-427d-4e7f-98a4-44b59faef1b2.png)

**Comment by huapox** [comment]
> It looks like the `servicemonitor` configuration is missing. Check if [it](https://github.com/kubesphere/ks-installer/blob/master/roles/ks-monitor/files/prometheus/kubernetes/kubernetes-serviceMonitorKubelet.yaml) exists. And [prometheusRule](https://github.com/kubesphere/ks-installer/blob/master/roles/ks-monitor/files/prometheus/kubernetes/kubernetes-prometheusRule.yaml) is also needed @huapox

In my case: it works with k3s-cri-docker, but none data with k3s-cri-containerd (KindMode)

**Comment by frezes** [comment]
@huapox  @wsndng https://kubesphere.io/forum/d/7713-kubesphere-330-pod/13

**Comment by huapox** [comment]
In my situation, Kind mode resolved!

- it works after my attch conf to ctd's config.toml

Dtl ref: https://github.com/k3s-io/k3s/issues/5782

```toml
#ref k3s's inner ctd's config:
[plugins."io.containerd.grpc.v1.cri"]
  #...
  # ++
  stream_server_address = "127.0.0.1"
  stream_server_port = "10010"
  enable_selinux = false
  
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
	SystemdCgroup = false
```

![图片](https://user-images.githubusercontent.com/6138651/227697556-8c144e2e-e7a4-4eed-bb23-1e0ad176618d.png)

![图片](https://user-images.githubusercontent.com/6138651/227697564-d61f3cb0-1297-41e3-9600-1d94aa178174.png)

![图片](https://user-images.githubusercontent.com/6138651/227697584-28b92dfa-e686-463d-876e-b2676d3dae48.png)

**Comment by huapox** [comment]
Pod and container detail:

![图片](https://user-images.githubusercontent.com/6138651/227697657-9d180ffc-d033-433f-b5d7-9ae6f3fce4df.png)

![图片](https://user-images.githubusercontent.com/6138651/227697669-81725545-1822-40ca-8071-4d1ff73be1aa.png)

**Comment by huapox** [comment]
> @huapox @wsndng https://kubesphere.io/forum/d/7713-kubesphere-330-pod/13

@frezes Thx again

-  `--kubelet-arg containerd=/run/containerd/containerd.sock` does not fit my situation, but the link let got the method to debug.  Detail at https://github.com/k3s-io/k3s/issues/5782
- my situation: run containerd+k3s at a customized container:
  - not the org's container k3s is binary mode. 
  - And with `--container-runtime-endpoint /run/containerd/containerd.sock` which will use the containerd outside of k3s.
