### ISSUE TITLE
The "Cluster Gateway" page keeps loading and reports an error "evaluating e.ip.includes".

### ISSUE THREAD

**Issue by hongzhouzi** [kubesphere/kubesphere#5604]
**Describe the bug**
The "Cluster Gateway" page keeps loading and reports an error "evaluating e.ip.includes".
The environment is installed on aws eks K8s, configured with AWS NLB.
Exception Information: `Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'e.ip.includes')`

![image](https://user-images.githubusercontent.com/36416216/226822147-ac18f90a-71b1-4e6a-acdf-e7eb04f219af.png)

![image](https://user-images.githubusercontent.com/36416216/226821849-23a7edff-2c28-4d4e-b11b-fa588006d0ec.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: ks v3.3.2

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0-rc.0`
![image](https://github.com/kubesphere/kubesphere/assets/24789703/9fdf5c80-c234-438c-881a-92f17ae55549)

**Comment by Imccccc** [comment]
Can I upgrade ks-console without another component? 
I believe 3.4.0 is unstable currently.
