### ISSUE TITLE
怎么用kubesphere在创建nodeport时指定对外暴露端口？

### ISSUE THREAD

**Issue by DBiao** [kubesphere/kubesphere#5605]
**What's it about?**

**What's the reason why we need it?**

I believe this is an important feature for Kubesphere. There're a few use cases:

* case one
* case two
* ...

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

**Comment by hongzhouzi** [comment]
You can specify the `spec.ports.nodePort` in the edit service YMAL.
