### ISSUE TITLE
Terminal failed to obtain container sh

### ISSUE THREAD

**Issue by freemankevin** [kubesphere/kubesphere#5616]
`kubesphere version: v3.3.2`
`k8s version: v1.22.12`

Such a container does not have `sh`, is there a good solution, the mode is to use `sh`.
![image](https://user-images.githubusercontent.com/71524776/229017417-785f07dc-368d-4b91-b11e-902ae73117e0.png)

**Comment by wansir** [comment]
Annotations can be utilized to annotate the default shell of web terminals.
