### ISSUE TITLE
why does the release version not update go.mod or vendor

### ISSUE THREAD

**Issue by littlejiancc** [kubesphere/kubesphere#5618]
**Describe the Bug**
I had a bug where deleting ns failed, and I find this has been fixed in the pr:
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/23724009/229423710-33b51e20-f09d-46fe-87c7-a10ba09de21d.png">

https://github.com/kubesphere/storageclass-accessor/pull/7
https://github.com/kubesphere/kubesphere/pull/5271
But this is only fixed in master, not in release.

**Versions Used**
KubeSphere: v3.3.1
Kubernetes: v1.24.11

**Comment by zpllz** [comment]
i‘m so sorry。this is indeed a bug。This will be fixed shortly。
