### ISSUE TITLE
kubesphere的apiserver组件如何使用外部的Redis集群

### ISSUE THREAD

**Issue by haiyangxuGY** [kubesphere/kubesphere#5621]
kubesphere的apiserver做多副本高可用默认是使用Redis，请问这个Redis能使用外部的Redis集群吗？具体怎么配置呢？

**Comment by wansir** [comment]
redis 的配置项在 kubesphere-system 下 kubesphere-config 这个 cm 中，你可以替换配置。此外 3.3 之后 KS 默认使用的是单副本的 redis

**Comment by haiyangxuGY** [comment]
> redis的配置项在kubesphere-system下kubesphere-config这个cm中，你可以更换配置。另外3.3之后KS默认使用的是单副本的redis

感谢回答，目前已经配置完毕
