### ISSUE TITLE
token contains an invalid number of segments

### ISSUE THREAD

**Issue by jiangxuhui** [kubesphere/kubesphere#5628]
Docker version 20.10.9, build c2ea9bc
openEuler  version 20.03
kubernetes version  v1.22.12
kubesphere version v3.3.2
```
curl -sfL https://get-kk.kubesphere.io | VERSION=v3.0.7 sh -

./kk create cluster --with-kubernetes v1.22.12 --with-kubesphere v3.3.2

```
when I install k8s+kubesphere,and it installed succesful. but when i open site http://my-ip:30880,it show not found.
so ,
```
kubectl logs -f --tail=100 ks-console-5c5ccc9b55-qhk8z -n kubesphere-system
```
![image](https://user-images.githubusercontent.com/28898668/230549576-6b090ca5-6ef0-4818-bb38-6b4451189685.png)

```
kubectl logs -f --tail=100 ks-apiserver-5696954b85-vj87d -n kubesphere-system
```
![image](https://user-images.githubusercontent.com/28898668/230549674-5ef0353d-546a-4bfc-a74d-1d82fef43163.png)

**Comment by wansir** [comment]
It could be due to the browser caching incorrect cookies. Please try clearing your cookies and trying again.
