### ISSUE TITLE
upgrade istio to 1.17.x to support k8s 1.24/25

### ISSUE THREAD

**Issue by chinapanpan** [kubesphere/kubesphere#5631]
**What's it about?**
when I install kubeshpere 3.3.2 on EKS (kubenetes 1.24),  the version of the istio is 1.11.2. However,  the istio 1.11.2 don't support the k8s 1.24

![image](https://user-images.githubusercontent.com/97090623/230727910-f30debe3-4794-4945-88dd-61cb3bb69af0.png)

**Suggestion**
I suggest kubeshpere can upgrade the istio to 1.16 or 1.17  to make sure the kubeshpere 3.3.X can totally support k8s 1.24 1.25

**Comment by hongzhouzi** [comment]
It is planned that istio will be upgraded in the next release, and the exact istio version may need to be determined by considering the overall supported version compatibility of KubeSphere.
