### ISSUE TITLE
the traffic monitoring report the internal error: kiali url is not defined

### ISSUE THREAD

**Issue by chinapanpan** [kubesphere/kubesphere#5632]
**Describe the Bug**
 I enabled the service mesh and deployed the bookinfo application. when I open the traffic monitoring web page, the page report the internal error:kiali url is not defined

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/97090623/230728381-81feb008-47ac-4014-85c3-6fcdba21d4b3.png">

in the ks-apiserver, we can see the log:
![image](https://user-images.githubusercontent.com/97090623/230728419-4fb059db-2cbb-48c9-abea-606979ed38cf.png)

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: 3.3.2 (upgraded from 3.3.1)
Kubernetes:  AWS EKS (k8s 1.24)

**How To Reproduce**
1. enable the service mesh
2. enable the cluster gateway with LoadBalancer
3. deploy the bookinfo
4. click the web page of traffic monitoring of bookinfo application.

**Comment by hongzhouzi** [comment]
https://github.com/kubesphere/kubesphere/blob/v3.3.2/pkg/kapis/servicemesh/metrics/v1alpha2/handler.go#L51-L63
It is possible that sa.secrets is empty and kialiClient is not created, see if the secret of kubesphere-sa-token exists in your environment under kubesphere-system namespace.

**Comment by adanskyy** [comment]
> https://github.com/kubesphere/kubesphere/blob/v3.3.2/pkg/kapis/servicemesh/metrics/v1alpha2/handler.go#L51-L63 可能是 sa.secrets 是空的，而 kialiClient 没有被创建，看看 kubesphere-sa-token 的秘密是否存在于你的环境中的 kubesphere-system 命名空间下。

![image](https://user-images.githubusercontent.com/108704575/232995206-311710a1-7694-4686-8c94-28d7e993444d.png)
![image](https://user-images.githubusercontent.com/108704575/232995848-92a1f7d1-6127-4342-bd24-8b9f3de3e857.png)


kubesphere-sa-token does not exist. How to solve the problem?

**Comment by hongzhouzi** [comment]
It is possible this [PR for sa token creation](https://github.com/kubesphere/ks-installer/pull/2007/files) is not working for some other reason, try to recreate the kubesphere sa token as follows:

1. Create kubesphere-sa-token
```yaml
kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: kubesphere-sa-token
  namespace: kubesphere-system
  annotations:
    kubernetes.io/service-account.name: kubesphere
type: kubernetes.io/service-account-token
EOF
```
2. Associate kubesphere-sa-token in kubesphere sa secrets
```sh
kubectl -n kubesphere-system patch sa kubesphere --patch '{"secrets":[{"name":"kubesphere-sa-token"}]}'
```

Finally restart `ks-apiserver` and see if it works.

**Comment by adanskyy** [comment]
The previous error was resolved, but a new error occurred and the page kept loading. The F12 check found the following error

![image](https://user-images.githubusercontent.com/108704575/233029723-1df8a0a2-07c6-4af2-ae7a-886f0f5515f4.png)

**Comment by hongzhouzi** [comment]
ok, this is the authentication failure when the client accesses kiali, restart the kiali component again.

**Comment by adanskyy** [comment]
重启kiali后依然如此
![image](https://user-images.githubusercontent.com/108704575/233045991-099b667b-b5ec-4ead-945c-592eaf2cfc11.png)
同时 kiali 报错。
**
![image](https://user-images.githubusercontent.com/108704575/233046169-1f8a5692-3485-4e23-86ca-2f49b2381d3d.png)
**
修改后，我重启了
kube-apiserver 以及 kiali、 kiali-operator
其他未重启

**Comment by adanskyy** [comment]
已经解决。 可以了谢谢

**Comment by Imccccc** [comment]
> 

How do i restart `ks-apiserver`, `kiali-operator`, `kiali`

**Comment by Imccccc** [comment]
> It is possible this [PR for sa token creation](https://github.com/kubesphere/ks-installer/pull/2007/files) is not working for some other reason, try to recreate the kubesphere sa token as follows:
> 
> 1. Create kubesphere-sa-token
> 
> ```yaml
> kubectl apply -f - <<EOF
> apiVersion: v1
> kind: Secret
> metadata:
>   name: kubesphere-sa-token
>   namespace: kubesphere-system
>   annotations:
>     kubernetes.io/service-account.name: kubesphere
> type: kubernetes.io/service-account-token
> EOF
> ```
> 
> 2. Associate kubesphere-sa-token in kubesphere sa secrets
> 
> ```shell
> kubectl -n kubesphere-system patch sa kubesphere --patch '{"secrets":[{"name":"kubesphere-sa-token"}]}'
> ```
> 
> Finally restart `ks-apiserver`, `kiali-operator`, `kiali` and see if it works.


How do i restart `ks-apiserver`, `kiali-operator`, `kiali`

**Comment by hongzhouzi** [comment]
> How do i restart `ks-apiserver`


```sh
kubectl rollout restart deployments/ks-apiserver -n kubesphere-system
```
