### ISSUE TITLE
How to perform cross namespace access in the same enterprise space？

### ISSUE THREAD

**Issue by MapleNow** [kubesphere/kubesphere#5634]
kubersphere version: v3.3.2
kubernetes   version: v1.22.12

how to set user roles to enable cross namespace access within the same enterprise space? 
i have three namespaces(dev, test, prod) in same enterprise space. 
I want to implement using 'service-name.test' in a namespace named dev to access services in a namespace named test

**Comment by wansir** [comment]
@MapleNow By default, network isolation is not enabled, so you can use in-cluster DNS to access services in other namespaces directly.  https://kubernetes.io/docs/concepts/services-networking/service/
