### ISSUE TITLE
开启servermesh后，ks-apiserver POD 无法启动

### ISSUE THREAD

**Issue by adanskyy** [kubesphere/kubesphere#5636]
环境是
AWS EKS 版本 1.24 
kubesphere 版本 3.3.1

问题描述：
开启servermesh 后，安装完毕后，ks-apiserver出现异常，无法启动
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/108704575/231106806-aef4e96c-2779-4c00-8c37-86f3799b16d3.png">
查看ks-apiserver pod日志显示如下
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/108704575/231107104-d68a1f08-f80e-44db-a503-a85cdc46c0fa.png">

详细日志如下
W0411 08:32:49.947265       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0411 08:32:49.949520       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0411 08:32:49.961240       1 options.go:191] ks-apiserver starts without redis provided, it will use in memory cache. This may cause inconsistencies when running ks-apiserver with multiple replicas.
I0411 08:32:49.961269       1 interface.go:50] start helm repo informer
panic: runtime error: index out of range [0] with length 0

goroutine 42 [running]:
kubesphere.io/kubesphere/pkg/kapis/servicemesh/metrics/v1alpha2.NewHandler(0xc00031e7c0, 0x422b638, 0xc0003aa160, 0x41eaba8, 0xc000306e68, 0xe)
        /workspace/pkg/kapis/servicemesh/metrics/v1alpha2/handler.go:51 +0x57b
kubesphere.io/kubesphere/pkg/kapis/servicemesh/metrics/v1alpha2.AddToContainer(0xc00031e7c0, 0xc0009713b0, 0x422b638, 0xc0003aa160, 0x41eaba8, 0xc000306e68, 0xc000c89480, 0x4169840)
        /workspace/pkg/kapis/servicemesh/metrics/v1alpha2/register.go:42 +0xfa
kubesphere.io/kubesphere/pkg/apiserver.(*APIServer).installKubeSphereAPIs(0xc0009983c0, 0xc00085a480)
        /workspace/pkg/apiserver/apiserver.go:259 +0x1534
kubesphere.io/kubesphere/pkg/apiserver.(*APIServer).PrepareRun(0xc0009983c0, 0xc00085a480, 0xc0009983c0, 0x0)
        /workspace/pkg/apiserver/apiserver.go:180 +0x17e
kubesphere.io/kubesphere/cmd/ks-apiserver/app.run(0xc0009ba660, 0x41d6278, 0xc00054f9c0, 0x0, 0x0)
        /workspace/cmd/ks-apiserver/app/server.go:141 +0x8d
kubesphere.io/kubesphere/cmd/ks-apiserver/app.Run.func1(0xc0009ba660, 0xc000531a30, 0xc00085a3c0)
        /workspace/cmd/ks-apiserver/app/server.go:106 +0x45
created by kubesphere.io/kubesphere/cmd/ks-apiserver/app.Run
        /workspace/cmd/ks-apiserver/app/server.go:105 +0x135

**Comment by wansir** [comment]
@adanskyy Related to https://github.com/kubesphere/kubesphere/issues/5427
