### ISSUE TITLE
Cannot change password after fresh install (kk: 3.0.7, ks: 3.3.2, k8s: 1.24.9)

### ISSUE THREAD

**Issue by todortanevski** [kubesphere/kubesphere#5638]
**Describe the Bug**
Cannot change password after fresh install (kk: 3.0.7, ks: 3.3.2, k8s: 1.24.9).

For UI issues please also add a screenshot that shows the issue.

**Internal error occurred: failed calling webhook "users.iam.kubesphere.io": failed to call webhook: Post "https://ks-controller-manager.kubesphere-system.svc:443/validate-email-iam-kubesphere-io-v1alpha2?timeout=30s": Service Unavailable**

![kk-pass-error](https://user-images.githubusercontent.com/43077767/231436230-cb63678e-aece-4ce3-b576-254a03c5ad1f.jpg)

**Versions Used**
KubeKey: 3.0.7
KubeSphere: 3.3.2
Kubernetes: 1.24.9
OS: Oracle Linux 8.7, VMware VM

**Environment**
How many nodes and their hardware configuration:

Oracle Linux 8.7
   - 3 masters 8cpu/8gb
   - 3 workers 8cpu/8gb

**How To Reproduce**
1. curl -sfL https://get-kk.kubesphere.io | sh -
2. ./kk create config --with-kubernetes v1.24.9 --with-kubesphere v3.3.2
3. mv config-sample.yaml config_k8s_1.24.9_3.3.2.yaml
4. vim config_k8s_1.24.9_3.3.2.yaml
5. ./kk create cluster --with-kubernetes v1.24.9 --with-kubesphere v3.3.2 -f config_k8s_1.24.9_3.3.2.yaml
6. wait for installation to finish
7. go to reported url:port
8. try to change password

**Expected behavior**
To be able to change password.

**Comment by wansir** [comment]
@todortanevski 
The error message indicates that there is an issue with the Kubernetes webhook "users.iam.kubesphere.io" and it failed to call the webhook with the service unavailable error.

Check if the ks-controller-manager pod is running correctly. You can use the following command to check the pod's status:

```
kubectl get pod ks-controller-manager-xxxxx -n kubesphere-system
```

Replace xxxxx with the actual name of the pod. If the pod is not running, check the pod logs for any related errors or warnings.

**Comment by vcakarov** [comment]
Thank you for your message. 
I am out of office until August 14, so please expect some delay in my response.

Kind Regards,
Vladimir

-- 
Vladimir Chakarov
PELAGUS IT d.o.o., http://www.pelagus-it.com/
