### ISSUE TITLE
Could not connect to the container. Do you have sufficient privileges?

### ISSUE THREAD

**Issue by dreamerkr** [kubesphere/kubesphere#5639]
When I use demo (https://ks.xxx.com/)   ,I can not open Kubectl shell dashboard.
error message:
1.enter KubeSphere demo env
2. click kubectl ,but https://ks-consolexxxxx.kubesphere.cloud:30443/terminal/kubectl/default show **Could not connect to the container. Do you have sufficient privileges?**

how slover the problem？

**Comment by wansir** [comment]
@dreamerkr similar to https://github.com/kubesphere/kubesphere/issues/3368
