### ISSUE TITLE
使用parameters 动态生成pipeline 参数运行后，在KS控制台不生效

### ISSUE THREAD

**Issue by Nacho-A** [kubesphere/kubesphere#5645]
现象描述：
使用了parameters动态生成pipeline参数；
流水线模式是多分支流水线，ks控制台没有下拉框选项，在jenkins控制台可以显示下拉框

pipeline代码：

pipeline {
xxx....
parameters {
            choice (name: 'Branch', description: '发布分支', choices: ['dev', 'test'] )
           choice (name: 'SERVICE_NAME', description: '部署的服务', choices: ['service-workflow', 'service-scbill',] )
            choice (name: 'Namespace', description: '命名空间', choices: ['owinfo-bjkj', 'owinfo-bjkj-test', 'owinfo-bjkj-dev', 'owinfo-4A'] )
            choice (name: 'ReplicaCount', description: '副本数目', choices: ['1', '3', '5', '7'] )
 }
xxxx...

}

![1](https://user-images.githubusercontent.com/67043152/233296869-72115989-3250-466a-9bad-2473032f26d3.png)

![2](https://user-images.githubusercontent.com/67043152/233296947-b5fc3721-3656-42a7-bec0-aef82314bb6a.png)

**Comment by Nacho-A** [comment]
kubesphere版本3.3.0

**Comment by hongzhouzi** [comment]
/cc @kubesphere/sig-devops  
@chilianyi Can you help with this problem?

**Comment by Nacho-A** [comment]
流水线模式是多分支流水线

**Comment by chilianyi** [comment]
是的，这是个 jenkins 的问题，定义的 在 jenkinsfile 中的参数，首次运行时，不会弹出修改参数值的框。

后续再提交运行时，就可以展示了。

**Comment by Nacho-A** [comment]
> 是的，这是个 jenkins 的问题，定义的 在 jenkinsfile 中的参数，首次运行时，不会弹出修改参数值的框。
> 
> 后续再提交运行时，就可以展示了。

不是不显示，而是只显示出了默认值，并且不是下拉框的框，也没有其他选项
![9f517184fdd9379679f62043ef289d1](https://user-images.githubusercontent.com/67043152/233366881-2fc4f6b4-95d6-418b-b582-218eeeed07fe.png)

**Comment by chilianyi** [comment]
https://github.com/kubesphere/ks-devops/issues/537

这个问题在 3.3.1 版本中修复了，可以升级，或者 替换先 ks console 的前端 image，修改 tag 从 3.3.0 改为 3.3.1
