### ISSUE TITLE
The link of download `offline-installation-tool.sh v3.3.2` is 404 not found

### ISSUE THREAD

**Issue by sologgfun** [kubesphere/kubesphere#5649]
**Describe the Bug**
In the web page [install-ks-on-linux-airgapped](https://kubesphere.io/zh/docs/v3.3/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped/) .
the link of download `offline-installation-tool.sh v3.3.2` is 404 not found.
```
curl -L -O https://github.com/kubesphere/ks-installer/releases/download/v3.3.2/offline-installation-tool.sh
```

For UI issues please also add a screenshot that shows the issue.

**Expected behavior**
We should change it to an available link.

**Comment by hongzhouzi** [comment]
```sh
https://raw.githubusercontent.com/kubesphere/ks-installer/v3.3.2/scripts/offline-installation-tool.sh
```
You can use this url instead.

**Comment by hongzhouzi** [comment]
@pixiake
Is this a wrong link in the documentation or did you forget to put this resource in Assets?
