### ISSUE TITLE
v3.3.0升级到v3.3.2 副本数量显示为0

### ISSUE THREAD

**Issue by lqc520** [kubesphere/kubesphere#5651]
v3.3.0升级到v3.3.2 出现了问题
![bug图](https://user-images.githubusercontent.com/33248612/233929575-b6fc74ee-0870-4263-9de6-42d101e9aaa6.png)

**Comment by hongzhouzi** [comment]
再明确一下是不是数据的问题。你打开浏览器控制台看看请求 deployment 的 API（`/apis/apps/v1/namespaces/{ns}/deployments/{deploy}`）返回的数据和查询 pods 的 API （`/kapis/resources.kubesphere.io/v1alpha3/namespaces/{ns}/pods?xxx`）返回的数据是否符合预期呢。
或者你在命令行查询下这个 deploy 是否还存在这个 pod，与期望的是否一致。

**Comment by lnchengzi** [comment]
![image](https://user-images.githubusercontent.com/131866263/236098361-c4c96ec3-d305-4ff6-bdc0-8c6c604ba644.png)
pod是正常的

**Comment by hongzhouzi** [comment]
> ![image](https://user-images.githubusercontent.com/131866263/236098361-c4c96ec3-d305-4ff6-bdc0-8c6c604ba644.png) pod是正常的

这个是 pod 监控 API 返回的监控数据，这儿没有应该是正常的。先看看查询 pod 返回的数据和查询 deployment 返回的数据是否符合预期呢

**Comment by lnchengzi** [comment]
![image](https://user-images.githubusercontent.com/131866263/236100205-a3c1aa96-afb0-4d98-a3a5-8862099ebf5c.png)
访问devops 报这个 这个是啥问题

**Comment by lnchengzi** [comment]
经过测试 副本数量用30880端口访问显示正常 代理后的域名访问不行 之前的版本可以 不知道啥原因

**Comment by hongzhouzi** [comment]
这个问题后面解决了么？
那很可能是代理的影响，可以从请求及返回内容分析下看看。
