### ISSUE TITLE
Kubesphere在删除namespaces会卡住，原因是因为finalizers导致，重启机器在web界面mamespaces 消失，但是在主机里面kubectl get ns 会显示namespaces 没有消失，而且被挂起了，建议增加finalizers删除选项。

### ISSUE THREAD

**Issue by binary01010** [kubesphere/kubesphere#5659]
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by hongzhouzi** [comment]
This situation generally needs to be analyzed and dealt with in the context of the actual situation, and it is more appropriate to deal with it manually in the CLI.
