### ISSUE TITLE
kubesphere 集群网关禁用后无法正常启动

### ISSUE THREAD

**Issue by airufei** [kubesphere/kubesphere#5660]
kubesphere网关被禁用重新开启后kubesphere-router副本数就为0了 这是在禁用的时候把deployment删除了？需要怎么恢复呢？

是否可以单独部署kubesphere-router-kubesphere-system deployment，需要怎么部署，谢谢。

论坛问题地址：https://kubesphere.io/forum/d/22127-kubesphere-ji-qun-wang-guan-jin-yong-hou-wu-fa-zheng-chang-qi-dong/2

**Comment by hongzhouzi** [comment]
> kubesphere网关被禁用重新开启后kubesphere-router副本数就为0了 这是在禁用的时候把deployment删除了？需要怎么恢复呢？
> 
> 是否可以单独部署kubesphere-router-kubesphere-system deployment，需要怎么部署，谢谢。
> 
> 论坛问题地址：https://kubesphere.io/forum/d/22127-kubesphere-ji-qun-wang-guan-jin-yong-hou-wu-fa-zheng-chang-qi-dong/2


Replied in the forum.
