### ISSUE TITLE
添加EKS Member集群时报错 sync KubeConfig expiration date for cluster dev-k8s failed: parseKubeConfigExpirationDate for cluster dev-k8s failed: empty CertData

### ISSUE THREAD

**Issue by qinghuawang1** [kubesphere/kubesphere#5664]
K8S： 1.24
KS：3.3.2
报错信息：sync KubeConfig expiration date for cluster dev-k8s failed: parseKubeConfigExpirationDate for cluster dev-k8s failed: empty CertData

报错分析：在添加member集群时，导入kubeconfig文件后，ks-controller-manager报上述错误，猜测K8S1.24后通过kubernetes.io/service-account-token建立的secret是永不过期的，并没有exp字段，所以会报这个错误

请帮助解决这个BUG

**Comment by hongzhouzi** [comment]
This is a bug that needs to be fixed in the code. duplicated: https://github.com/kubesphere/kubesphere/issues/5395
/cc @kubesphere/sig-multicluster 
@iawia002 help!
