### ISSUE TITLE
jaeger-operator-metrics is stopped

### ISSUE THREAD

**Issue by zhoudi94** [kubesphere/kubesphere#5670]
**Describe the Bug**
According to the documentation, v3.3.2 has been installed, but link tracking cannot be used
![image](https://user-images.githubusercontent.com/11438661/237052262-a7b01d8b-74f0-4b22-86c2-9c890076ffb5.png)
**Versions Used**
KubeSphere: v1.23.10
Kubernetes: v3.3.2

**Environment**
How many nodes and their hardware configuration:
CentOS 7.5 / 1 masters:  8cpu/16g; 1 nodes: 8cpu/16g

**How To Reproduce**
document 
https://kubesphere.io/zh/docs/v3.3/quick-start/minimal-kubesphere-on-k8s/

**Expected behavior**

my pods status
![image](https://user-images.githubusercontent.com/11438661/237053391-df6f0170-ca90-456a-bb1d-73b775b70e54.png)

**Comment by hongzhouzi** [comment]
The stop of this component has no direct impact on the inability to use link tracking. You can refer to this guide to troubleshoot. https://kubesphere.io/forum/d/3192-kubesphere
