### ISSUE TITLE
Cannot access bookinfo page with upstream-vhost nginx annotation

### ISSUE THREAD

**Issue by jinqinn** [kubesphere/kubesphere#5672]
**Describe the Bug**
I created an Bookinfo application project, but got a error when access the web page.
I found `nginx.ingress.kubernetes.io/upstream-vhost: productpage.demo-project.svc.cluster.local` was added automatically, then i remove this annotation, this issue got fixed. 
I donot know why ?

KubeSphere:
V3.2.1

Kubernetes:
V1.21

**Comment by wansir** [comment]
@jinqinn Is it a DNS resolution issue? How is clusterDomain configured in your cluster?

**Comment by hongzhouzi** [comment]
Can you confirm that you have enabled application governance in your application? Adding this annotation is mainly used to enable traffic governance/tracing to work properly after application governance is enabled.

**Comment by jinqinn** [comment]
> Can you confirm that you have enabled application governance in your application? Adding this annotation is mainly used to enable traffic governance/tracing to work properly after application governance is enabled.

yes, i  have already enabled Application Governance.
and now, it seems ok after restarting kubesphere-router-pod, so i will close this bug.
