### ISSUE TITLE
新增的member集群配置好devops后发现只有流水线，没有持续部署和代码仓库菜单，但单独登陆到member集群是有这二个菜单按钮

### ISSUE THREAD

**Issue by qinghuawang1** [kubesphere/kubesphere#5673]
K8S集群 H：1.24  M：1.24
KS：H：V3.3.2  M：v3.3.2

首先感谢你们仅用一天就解决了我发现的一个BUG #5664 ，为你们的效率点赞，现在遇到的这个问题也请同样效率的解决吧。
问题描述：
新增的member集群配置好devops后发现只有流水线，没有持续部署和代码仓库菜单，但单独登陆到member集群是有这二个菜单按钮
如图：
![image](https://github.com/kubesphere/kubesphere/assets/122425209/69253e78-7b23-44e5-8852-cd8cb31e624f)

**Comment by VioZhang** [comment]
持续部署要单独开启，配置了多集群后不建议登录member集群，这个文档中有标识

**Comment by qinghuawang1** [comment]
@VioZhang  我也不想登陆member集群，请问持续部署和代码仓库需要单独开启的文档麻烦发一下。

**Comment by qinghuawang1** [comment]
@yudong2015 @wenxinll @wansir 请问有进展吗？我希望能尽快解决这些问题。

**Comment by wenxinll** [comment]
持续部署只能在host集群的单集群项目中操作，在多集群环境的member集群的单集群项目中是不能使用持续部署的，只能使用流水线。

**Comment by qinghuawang1** [comment]
@wenxinll  感谢您的解答，但这也许是问题，从产品角度上讲，为啥只支持流水线，不支持多集群持续部署？这让使用者感到很困惑。

**Comment by VioZhang** [comment]
4.0 之后多集群会考虑更改为 kamarda，有很多社区开发者也在参与帮助 KubeSphere 相关改造，感兴趣可以参加社区例会了解
