### ISSUE TITLE
工作负载停止后，无法重新启动。

### ISSUE THREAD

**Issue by Will-Liang** [kubesphere/kubesphere#5679]
工作负载停止后，无法重新启动。
可以使用重新创建，但创建完后仍然不能启动。
也没有看到工作负载的启动按钮

**Comment by hongzhouzi** [comment]
无法重新创建这个问题看看该工作负载的事件记录呢？
没有看到启动按钮是指啥呢？页面上不能设置副本数么？

**Comment by chenshuanglin** [comment]
遇到同样的疑惑，现在把系统中的node_exporter在页面点了停止按钮后，在页面上也没找到启动的按钮
