### ISSUE TITLE
devops流水线除admin账号外，其余用户无法执行

### ISSUE THREAD

**Issue by lingdada1023** [kubesphere/kubesphere#5684]
# 描述
使用admin创建devops流水线后能正常执行。切换为其余账号（角色等权限均无问题）后，执行流水线无反应，一直处于【未运行】状态，查看ks-controller-manager日志后报错401。

随后，去jenkins中查看。发现jenkins为ks创建的角色【kubesphere-user】权限很低，而ks创建的用户在jenkins都会被分配到Anonymous用户组，该用户组会被赋予kubesphere-user角色，导致无法正常运行流水线。
![image](https://github.com/kubesphere/kubesphere/assets/38487529/83f3d224-cf7e-44e4-b256-b4b3cf069901)

为Anonymous用户组赋予admin角色权限后，问题解决
![image](https://github.com/kubesphere/kubesphere/assets/38487529/2666636e-360a-46bd-8458-0af2b9da9fe5)

# 问题
我不太清楚我的解决方法是否正确，同时这是否可以被认定为一个Bug？社区中有很多人遇到此类问题，还请给出统一的解决方法。

期待回复，谢谢

**Comment by chilianyi** [comment]
您好，具体可以参考 ：https://kubesphere.io/forum/d/9384-devops/4 来进行修复。 

这的确是一个 bug，主要发生在 ks 3.3.2 的版本中，由于 ks installer 使用的 openssl 版本存在 bug，导致生成的 token 缺少了部分内容，引发后续问题。
