### ISSUE TITLE
ks-devops-agent配置被重置

### ISSUE THREAD

**Issue by lingdada1023** [kubesphere/kubesphere#5686]
在ks-devops-agent中配置了maven仓库地址后，一段时间过去会配还原重置。比如：我配置了mirror，但会被还原清空。

不太清楚什么情况下会导致ks-devops-agent配置被重置，每次都是流水线无法正常运行时才发现配置被重置了，并没有进行任何重启节点的操作。

期待回复，谢谢

**Comment by chilianyi** [comment]
感谢您的反馈，具体操作步骤是什么尽可能描述清楚些，我们做下复现看是什么问题。 

这个配置是在哪里，修改了哪个字段。

**Comment by lingdada1023** [comment]
位置：集群管理->配置->配置字典
![image](https://github.com/kubesphere/kubesphere/assets/38487529/c6190b4b-ed99-497c-96f7-9d3617a78030)
修改其中的<mirrors>内容后，某些情况下会被重置还原为默认状态，添加的内容会被清空。
![image](https://github.com/kubesphere/kubesphere/assets/38487529/9bfea829-96ef-43e3-a216-4292be80c996)
还原的结果：<mirros></mirros>


该问题我无法准确复现，偶尔会出现该情况。猜测可能是以下情况？
1.当修改了其他配置后，该配置文件被重置（具体是哪个配置不太清楚）
2.节点自动重启，导致配置被还原

我是在配置devops流水线是遇到的该情况，目前出现过2-3次，具体出现原因不明。

**Comment by lingdada1023** [comment]
此问题已稳定复现，当每次修改【定制资源定义】-> 【ClusterConfiguration】文件配置后，ks-devops-agent会被重置为初始状态，配置会被清空 @chilianyi

**Comment by chilianyi** [comment]
感谢如此细致的反馈，ClusterConfiguration 是 ks-installer 组件的自定义资源文件，主要用于启停组件，目前看这个回滚不是预期的， @yudong2015 看下是否可规避。
