### ISSUE TITLE
pod的cpu、内存无监控信息

### ISSUE THREAD

**Issue by Mrzzzzz** [kubesphere/kubesphere#5702]
![ad18e4be7562992907b6056abdeda1e](https://github.com/kubesphere/kubesphere/assets/134244696/b563ee12-ba0f-45ae-8857-6a140ec62524)

**Comment by Mrzzzzz** [comment]
K8S版本1.26，kubesphere版本3.3.2，监控组件日志无报错
![cf9b120b96f280f110dc4d0fae98b91](https://github.com/kubesphere/kubesphere/assets/134244696/8c2d40a1-982d-42cb-a40a-6efba1d98238)

**Comment by hongzhouzi** [comment]
你可以先参考论坛这个帖子排查下呢，过程中遇到问题再把问题贴出来看看。
https://www.kubesphere.io/forum/d/22113-v331-suo-you-zu-jian-du-jian-kang-dan-shi-mei-you-ren-he-jian-kong-shu-ju

**Comment by Mrzzzzz** [comment]
prometheus-k8s日志
![image](https://github.com/kubesphere/kubesphere/assets/134244696/1609edf0-ec1d-4e85-a598-1042bf7c58ae)
kube-state-metrics 日志
![image](https://github.com/kubesphere/kubesphere/assets/134244696/9589d5c4-4446-4710-b28f-fa6f6c1dba55)
node-exporter日志
![image](https://github.com/kubesphere/kubesphere/assets/134244696/85a11e25-73c9-4094-bd5f-ffd440c39419)
只有容器组没有监控信息
![image](https://github.com/kubesphere/kubesphere/assets/134244696/c158dd4d-8623-44f2-9459-fc87bf9712f2)

**Comment by Mrzzzzz** [comment]
> 你可以先参考论坛这个帖子排查下呢，过程中遇到问题再把问题贴出来看看。 https://www.kubesphere.io/forum/d/22113-v331-suo-you-zu-jian-du-jian-kang-dan-shi-mei-you-ren-he-jian-kong-shu-ju

有参考这上面进行排查，但是还是没有pod的监控信息。

**Comment by Mrzzzzz** [comment]
更新installer的yaml文件，重启ks-api可以了

**Comment by chenshengshi** [comment]
大佬 你改了什么呢 我跟你一样的问题   我也一直解决不了 

我k8s 1.24.9
kubesphere 3.3.1

我pod 没有cpu内存信息 企业空间也没有  而且内存单位也是不正确的
![image](https://github.com/kubesphere/kubesphere/assets/43060901/268ab5a6-f8dd-4fa4-bbd2-00499e16f283)

promethues 这边看都是正常的

![image](https://github.com/kubesphere/kubesphere/assets/43060901/40731030-6ab2-420b-a92b-78e86d4d1b48)



kube-state-metrics 日志

![image](https://github.com/kubesphere/kubesphere/assets/43060901/20996567-80ee-46d8-b7fd-1f272641d414)


ks-apiserver 日志

![image](https://github.com/kubesphere/kubesphere/assets/43060901/35efa4a8-0f8e-4b94-93c3-b0c554094c30)

**Comment by chenshengshi** [comment]
我是sealos run 安装的kubesphere
