### ISSUE TITLE
Support Kubernetes 1.26

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5705]
KubeSphere will support Kubernetes 1.26 and we will provide a supporting list of the compents.

**Comment by code4alex** [comment]
我用EKS1.29安装的kubesphere3.3.2 建议官方文档最好注明一下支持Kubernetes 的版本清单

**Comment by VioZhang** [comment]
> 我用EKS1.29安装的kubesphere3.3.2 建议官方文档最好注明一下支持Kubernetes 的版本清单

@code4alex  文档有啊？
![image](https://github.com/kubesphere/kubesphere/assets/41519383/a60698cb-eeb1-4db4-90dd-7f387111a1f8)
