### ISSUE TITLE
Support pod grace period

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5707]
**What's it about?**

https://github.com/kubesphere/issues/issues/108
**What's the reason why we need it?**

I believe this is an important feature for Kubesphere. There're a few use cases:

* case one
* case two
* ...

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

**Comment by luqiaoshi** [comment]
创建页均新增了该字段，编辑页部分未加入到UI
与issue重复：https://github.com/kubesphere/kubesphere/issues/5830
