### ISSUE TITLE
Put alias in front of the name.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5708]
https://github.com/kubesphere/issues/issues/84
**What's it about?**

**What's the reason why we need it?**

I believe this is an important feature for Kubesphere. There're a few use cases:

* case one
* case two
* ...

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0-rc.0`
![image](https://github.com/kubesphere/kubesphere/assets/24789703/0ee3bc40-affe-4117-9a9d-9bd521c3b4b0)
