### ISSUE TITLE
Update the component of servicemesh.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5711]
**What's it about?**

https://github.com/kubesphere/issues/issues/726
**What's the reason why we need it?**

I believe this is an important feature for Kubesphere. There're a few use cases:

* case one
* case two
* ...

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

**Comment by hongzhouzi** [comment]
duplicated https://github.com/kubesphere/kubesphere/issues/5631
