### ISSUE TITLE
There shouldn't be project gateway at the list of cluster gateway.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5712]
https://github.com/kubesphere/issues/issues/732
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0-rc.0`
集群视角：
![image](https://github.com/kubesphere/kubesphere/assets/24789703/c5773907-63e6-4e3f-b209-f10dae9f9204)
项目视角：
![image](https://github.com/kubesphere/kubesphere/assets/24789703/2b4e3768-5bc9-4d6c-af06-c563712c1870)
