### ISSUE TITLE
Have the default value of the worker-processes 4 

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5713]
**What's it about?**

https://github.com/kubesphere/issues/issues/753
**What's the reason why we need it?**

I believe this is an important feature for Kubesphere. There're a few use cases:

* case one
* case two
* ...

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0-rc.0`
![image](https://github.com/kubesphere/kubesphere/assets/24789703/4b643c8d-ee56-42c8-9a74-e12042035ce4)
创建完毕，查看
```
kubectl -n kubesphere-controls-system get gateway kubesphere-router-kubesphere-system -oyaml
```
![image](https://github.com/kubesphere/kubesphere/assets/24789703/a2f719b0-a4a8-416c-9e07-eda5a2a47727)
