### ISSUE TITLE
Fix the bug of devops

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5721]
- [ ] https://github.com/kubesphere/issues/issues/827
- [ ] https://github.com/kubesphere/issues/issues/828
- [ ] https://github.com/kubesphere/issues/issues/831
- [ ] https://github.com/kubesphere/issues/issues/832
- [ ] https://github.com/kubesphere/issues/issues/878
- [ ] https://github.com/kubesphere/issues/issues/881
- [ ] https://github.com/kubesphere/issues/issues/882
- [ ] https://github.com/kubesphere/issues/issues/918
- [ ] https://github.com/kubesphere/issues/issues/919
- [ ] https://github.com/kubesphere/issues/issues/923
- [ ] https://github.com/kubesphere/issues/issues/933
- [ ] https://github.com/kubesphere/issues/issues/934
- [ ] https://github.com/kubesphere/issues/issues/936
- [ ] https://github.com/kubesphere/issues/issues/962
- [ ] https://github.com/kubesphere/issues/issues/880
- [ ] https://github.com/kubesphere/issues/issues/992
- [ ] https://github.com/kubesphere/issues/issues/993
- [ ] https://github.com/kubesphere/issues/issues/1008
- [ ] https://github.com/kubesphere/issues/issues/1013
- [ ] https://github.com/kubesphere/issues/issues/1020
- [ ] https://github.com/kubesphere/issues/issues/1033
- [ ] https://github.com/kubesphere/issues/issues/990
- [ ] https://github.com/kubesphere/issues/issues/992
- [ ] https://github.com/kubesphere/issues/issues/993
- [ ] https://github.com/kubesphere/issues/issues/994

**Comment by codering** [comment]
what are kubesphere doing....?!
