### ISSUE TITLE
Fix the error of the workload name checking.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5725]
https://github.com/kubesphere/issues/issues/935
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0-rc.0`
元数据重复，创建会返回true
请求url：/apis/clusters/qs-host/apps/v1/namespaces/qs-pro2/deployments?labelSelector=app%3Dnginx
![image](https://github.com/kubesphere/kubesphere/assets/24789703/a41e4f2f-f043-473f-a1f9-395436874571)

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0-rc.0`
元数据重复，创建会返回true
请求url：/apis/clusters/qs-host/apps/v1/namespaces/qs-pro2/deployments?labelSelector=app%3Dnginx
![image](https://github.com/kubesphere/kubesphere/assets/24789703/a41e4f2f-f043-473f-a1f9-395436874571)
