### ISSUE TITLE
There is a crash when deploying sonarqube from app store.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5729]
https://github.com/kubesphere/issues/issues/1026
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0-rc.0`
![image](https://github.com/kubesphere/kubesphere/assets/24789703/0bc416c0-777a-40c0-ac7d-91437df359a5)
