### ISSUE TITLE
no matches for kind "ClusterDashboard" in version "monitoring.kubesphere.io/v1alpha2"

### ISSUE THREAD

**Issue by littleBlackHouse** [kubesphere/kubesphere#5731]
**Describe the Bug**
install by kk. and the monitor server has installed success. but The interface returns an error of that : no matches for kind "ClusterDashboard" in version "monitoring.kubesphere.io/v1alpha2"

**Versions Used**
KubeSphere: 3.3.2
Kubernetes: 1.25.9

**Environment**
How many nodes and their hardware configuration:
  Ubuntu Server 22.04 LTS 64-bit/ 1 masters  4cpu/8g

**How To Reproduce**
1. i can find the cr in my cluster
![截屏2023-05-24 18 04 32 (2)](https://github.com/kubesphere/kubesphere/assets/54946465/64803255-8890-4957-a1ae-8e1f46095067)
2. the interface (http://172.31.53.139:30880/kapis/resources.kubesphere.io/v1alpha3/clusterdashboards?sortBy=createTime&limit=10) returns errors
![截屏2023-05-24 18 02 41 (2)](https://github.com/kubesphere/kubesphere/assets/54946465/08aba901-d77f-4fa8-843f-60e2874b436f)

**Expected behavior**

**Comment by frezes** [comment]
This is not a bug, it just needs to restart `ks-apiserver`.

The previous deployment failed due to PDB problems. The deployment was successfully deployed after adjustment, but `ks-apiserver` was not restarted. So that the `ks-apiserver` resouces API does not process the newly registered CRDs, 404 error.

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0-rc.0`
![image](https://github.com/kubesphere/kubesphere/assets/24789703/6b0978f7-6eb3-4a98-af52-a1a8b062f7ec)

**Comment by shadon178** [comment]
I also have this problem.

**Comment by frezes** [comment]
> problem

restart ks-apiserver?

**Comment by 1247776995** [comment]
> > I also have this problem.
> 
> Restart ks-apiserver?

it did not work
