### ISSUE TITLE
Note the probable reason why the pipeline doesn't run.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5738]
It seems to be a frequently problem for the users.
![c98b0edaa707a8c608cdb00bf1b9eb7](https://github.com/kubesphere/kubesphere/assets/41519383/d26e3e34-9297-4799-9470-f7ff141c6597)

/cc @kubesphere/sig-devops

**Comment by chilianyi** [comment]
same as: https://www.kubesphere.io/forum/d/9384-devops

ks v3.3.2 installer image，use openssl 3.0.7， there is a bug when generate secret.
Need to update the secret for this kind of environment.

Now we have already regenerate ks-installer v3.3.2 image, and update the docker hub, new created environment will not have the same problem.
