### ISSUE TITLE
The namespace quota doesn't rely on woekspace quota.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5740]
**Describe the Bug**
The namespace quota doesn't rely on woekspace quota and the quota note should be the workspace quota rather than the available quota.
For UI issues please also add a screenshot that shows the issue.
![image](https://github.com/kubesphere/kubesphere/assets/41519383/d7c2b6ec-5d32-403b-8f3d-f94ee8e73fe6)**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0-rc.0`
![image](https://github.com/kubesphere/kubesphere/assets/24789703/af3cda5b-510e-4a56-9f8e-06dffdadf84f)
