### ISSUE TITLE
Support setting the default registry.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5745]
https://github.com/kubesphere/issues/issues/95
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0-rc.0`
新建/编辑：可设置默认仓库
![image](https://github.com/kubesphere/kubesphere/assets/24789703/b38dfbde-63c1-4357-bf6f-47626d79fb74)
创建工作负载，默认展示该仓库
![image](https://github.com/kubesphere/kubesphere/assets/24789703/17906120-eb86-471b-811b-3cbd0d476fcb)
