### ISSUE TITLE
There is no detail promote when imput the wrong kubeconfig.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5753]
https://github.com/kubesphere/issues/issues/174
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0-rc.0`
图形化界面：
![image](https://github.com/kubesphere/kubesphere/assets/24789703/a54a9a98-01f4-4ab7-a170-dbacbc3b8f01)
编辑yaml界面：
![image](https://github.com/kubesphere/kubesphere/assets/24789703/daa1b0c6-2109-4ce0-a0f3-dc4aee925b92)
