### ISSUE TITLE
Update the slack notification setting failed.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5754]
https://github.com/kubesphere/issues/issues/310
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0-rc.0`
![image](https://github.com/kubesphere/kubesphere/assets/24789703/66309d0b-8e41-4387-ae30-2641e92aa40f)
