### ISSUE TITLE
重置密码

### ISSUE THREAD

**Issue by eugeneliu930909** [kubesphere/kubesphere#5767]
KubeSphere Cloud 轻量集群用户反馈：
创建的集群第一次进入kubesphere需要修改密码，如果密码忘记了就没法登录了，也没有重置密码的功能按钮很不合理
<img width="900" alt="image" src="https://github.com/kubesphere/kubesphere/assets/91418272/000bcbc8-6edc-42c4-b117-56fd5397e85e">

**Comment by VioZhang** [comment]
https://www.kubesphere.io/zh/docs/v3.3/faq/access-control/forgot-password/#%E9%87%8D%E7%BD%AE%E6%99%AE%E9%80%9A%E7%94%A8%E6%88%B7%E5%AF%86%E7%A0%81

**Comment by shyding** [comment]
如何不重置找回原来的密码呢?

**Comment by VioZhang** [comment]
> 如何不重置找回原来的密码呢?

只能重置
