### ISSUE TITLE
【Permission】only join host cluster：cluster-admin，Resource Consumption Statistics display all cluster info

### ISSUE THREAD

**Issue by luqiaoshi** [kubesphere/kubesphere#5812]
**Describe the Bug**
Pre：exist user：qs-admin，only join host cluster，role：cluster-admin
Steps：
1.click【cluster manager】-【Resource Consumption Statistics】
2.view：Cluster Resource Consumption
Actual：
display all cluster info

![image](https://github.com/kubesphere/kubesphere/assets/24789703/9dc2976b-d9ff-463f-8fe9-83ce847e03aa)

**Versions Used**
KubeSphere: `v3.4.0-rc.0`
Kubernetes: (If KubeSphere installer used, you can skip this)
```
root@node1:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:17:29Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by luqiaoshi** [comment]
The following modules are similar：
Container Log Search
Resource Event Search
Audit Log Search
![image](https://github.com/kubesphere/kubesphere/assets/24789703/8ead69f9-c8a1-4175-9962-8400312fd3c0)

**Comment by harrisonliu5** [comment]
This issue is not fixed yet. @luqiaoshi

**Comment by luqiaoshi** [comment]
ok 与研发侧确认，此处不做集群权限项区分展示，显示所有集群信息
