### ISSUE TITLE
【Permission】custom role-apps grant permission：App Viewing，menu not display

### ISSUE THREAD

**Issue by luqiaoshi** [kubesphere/kubesphere#5813]
**Describe the Bug**
Pre：create custom role：test-role，apps：App Viewing
Steps：
1.create user，bind role：test-role
2.login ks console，view the menu
Actual:
App Store not display

![image](https://github.com/kubesphere/kubesphere/assets/24789703/4ae856a2-02c0-4384-82ee-11ed313e2ca1)

**Versions Used**
KubeSphere: `v3.4.0-rc.0`
Kubernetes: (If KubeSphere installer used, you can skip this)
```
root@node1:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:17:29Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by zhou1203** [comment]
Users can only access the app management page by clicking the 'Platform Management' button on the banner. Should the banner display the 'Platform Management' button for users who have the 'App Viewing' permission?

**Comment by harrisonliu5** [comment]
According to the current settings, the viewing of the app store is not controlled by permissions.

**Comment by zhou1203** [comment]
It's acceptable for a user with 'App Viewing' permission to not have access to the app management page.
