### ISSUE TITLE
Merge image registry into KubeSphere

### ISSUE THREAD

**Issue by fairychild1** [kubesphere/kubesphere#582]
目前镜像仓库跟kubesphere是割裂的两个产品，后期可以考虑整合到一起，在一个平台里。

**Comment by FeynmanZhou** [comment]
@shaowenchen @rayzhou2017 Will this feature be included in v3.1.0?

**Comment by LinuxSuRen** [comment]
/retitle Merge image registry into KubeSphere

IMO, we don't have any plans on this. You can use Harbor as your private image registry. And I cannot figure out the benefits when merging image registry into KubeSphere.

So, I'm going to close this issue. Please feel free to reopen this issue if there's anyone wants to discuss it again.
/close
