### ISSUE TITLE
【devops】Multi-branch pipeline artifacts download failed

### ISSUE THREAD

**Issue by littlejiancc** [kubesphere/kubesphere#5821]
**Describe the Bug**
Multi-branch pipeline artifacts download failed

For UI issues please also add a screenshot that shows the issue.
<img width="1103" alt="image" src="https://github.com/kubesphere/kubesphere/assets/23724009/71ae8869-a72f-47d6-bd9b-e78af4c87a1f">

**Versions Used**
KubeSphere: v3.3.2
Kubernetes: v1.24.9

**Environment**
How many nodes and their hardware configuration:
CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. Go to 'Multi-branch pipeline artifacts'
2. Click on 'download'
3. download fail

**Expected behavior**
download success

**Comment by zjpjly** [comment]
KubeSphere: v3.4.1
Kubernetes: v1.26.0

![Image](https://github.com/kubesphere/kubesphere/assets/18654693/e7b6d0e0-92a3-423d-8605-1241ae9f1afc)
