### ISSUE TITLE
【Devops】delete pipelinerun，data not sync removed

### ISSUE THREAD

**Issue by luqiaoshi** [kubesphere/kubesphere#5825]
**Describe the Bug**
Pre：exist pipeline run
Steps：
1.Login Jenkins console，delete pipeline run record
2.ks console-》pipeline-》Run Records
Actual：
data not sync removed

![image](https://github.com/kubesphere/kubesphere/assets/24789703/3986ae81-6df0-444c-b027-546d1a066f49)

![image](https://github.com/kubesphere/kubesphere/assets/24789703/b7416403-9bc5-403d-98b9-c7e926caf779)
![image](https://github.com/kubesphere/kubesphere/assets/24789703/efd6a3ff-6a71-4e95-b6a6-ae60f9898717)

**Versions Used**
KubeSphere: `v3.4.0-rc.0`
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by chilianyi** [comment]
是的，这个目前没有反向同步机制，也就是删除 jenkins 里，不会影响 devops 的显示，这个也是为了防止 因为 jenkins 挂掉或者不可访问时，devops 误认为删除，导致用户看不到所有流水线。 

可以暂不认为是个问题。

**Comment by luqiaoshi** [comment]
ok jenkins反向删除后，不同步 暂不予解决，关闭该issue
