### ISSUE TITLE
【Alert】alert list lack of target

### ISSUE THREAD

**Issue by luqiaoshi** [kubesphere/kubesphere#5827]
**Describe the Bug**
Pre：exist alert-》Firing
Steps：
1.enter pro=》Monitoring & Alerting，view the list
Actual:
Monitoring Target is empty.
PS: Rule Groups->Monitoring Targets is empty.

![image](https://github.com/kubesphere/kubesphere/assets/24789703/bb564b58-1222-46d5-8cbf-cee211459e83)
![image](https://github.com/kubesphere/kubesphere/assets/24789703/566d2370-368e-4627-8b81-06f70a42e5ac)

**Versions Used**
KubeSphere: `v3.4.0-rc.0`
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/0fd52665-f37e-49bd-9988-72af2f4277e0)


![Image](https://github.com/kubesphere/kubesphere/assets/18654693/29861030-50a5-41e5-b586-8f3e89d2df32)
