### ISSUE TITLE
【Doc】disable multiple alerting rule，doc not translated

### ISSUE THREAD

**Issue by luqiaoshi** [kubesphere/kubesphere#5828]
**Describe the Bug**
Pre：exist multiple alerting rules : Enable
Steps：
1.Enter pro-》Monitoring & Alerting, select multiple: Disable
2.set rule->Enable
Actual:
doc not translated.

![image](https://github.com/kubesphere/kubesphere/assets/24789703/3f448d4d-3f27-44a7-a653-39d6e9152143)
![image](https://github.com/kubesphere/kubesphere/assets/24789703/0d5c6c37-f1cf-4743-b0bb-b5144f58ad4a)

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by luqiaoshi** [comment]
Cluster=》Rule Groups=》Built-in Rule Groups=>Reset
![image](https://github.com/kubesphere/kubesphere/assets/24789703/52088ea9-47dd-4a0f-b5d6-6d8ea48cbf4a)

**Comment by Bettygogo2021** [comment]
I checked the UI texts and found that these texts were not in the Locales file. If so, we cannot receive the updates. Pls ask the frontend developer to modify it.

**Comment by luqiaoshi** [comment]
【Technical Support】-【Kubesphere Cloud】：
![image](https://github.com/kubesphere/kubesphere/assets/24789703/9e6d2816-ddd7-48b8-864c-9a3a5d57a2fc)

**Comment by harrisonliu5** [comment]
> 【Technical Support】-【Kubesphere Cloud】： ![image](https://user-images.githubusercontent.com/24789703/253898910-9e6d2816-ddd7-48b8-864c-9a3a5d57a2fc.png)

Kubesphere console do not have this page

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/d8cb4359-eac9-413d-aad2-0cc3cafb6f49)


![Image](https://github.com/kubesphere/kubesphere/assets/18654693/808b5dcb-08aa-4e9a-8391-d2c6bf60269d)



![Image](https://github.com/kubesphere/kubesphere/assets/18654693/c0234f63-9d40-4d05-8484-ed5130c4fbe5)
