### ISSUE TITLE
【Project】Statefulsets edit setting，lack of Pod Grace Period

### ISSUE THREAD

**Issue by luqiaoshi** [kubesphere/kubesphere#5830]
**Describe the Bug**
Pre：exist Projects=》associating a single cluster
Steps：
1.Enter Pro，【Workloads】-【Statefulsets】，click sts-name
2.【More】-【Edit Settings】
Actual：
lack of field：Pod Grace Period
PS: 1.Daemonsets have similar issues
2.multi-cluster Projects have similar issues：deploy、statefulset、services

![image](https://github.com/kubesphere/kubesphere/assets/24789703/0a39224c-c1be-4448-a3d3-b5aedf1f59e2)

**Versions Used**
KubeSphere: `v3.4.0-rc.0`
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/ee33156e-5978-4290-a778-eb8c7660c41c)
