### ISSUE TITLE
【Workbench】Recent access page occlusion

### ISSUE THREAD

**Issue by luqiaoshi** [kubesphere/kubesphere#5831]
**Describe the Bug**
![image](https://github.com/kubesphere/kubesphere/assets/24789703/9c3682b7-ed38-45ad-b2cc-d2993a5872bf)

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: `v3.4.0-rc.0`
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by zjpjly** [comment]
this issue has been resolved 
![image](https://github.com/kubesphere/kubesphere/assets/18654693/86d997a7-a6dc-404a-bcde-d12e06e4880f)
