### ISSUE TITLE
【Platform】Unable to set notification channels by email

### ISSUE THREAD

**Issue by luqiaoshi** [kubesphere/kubesphere#5840]
**Describe the Bug**
Steps：
1.【Platform Setting】-【Notification Channels】-【Email】
2.input correct info，click：【OK】
Actual：
Unable to set notification channels by email：400 Bad Request

![image](https://github.com/kubesphere/kubesphere/assets/24789703/5ef35ceb-547a-4910-a623-77ae8b4f4ad5)

**Versions Used**
KubeSphere: `v3.4.0-rc.0`
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by wanjunlei** [comment]
fix with https://github.com/kubesphere/ks-installer/pull/2208

**Comment by luqiaoshi** [comment]
issue fixed in v3.4.0-rc.1
upgrade notification-manager version: v2.3.0
