### ISSUE TITLE
【Cluster】Project gateways is not displayed,  query param is wrong

### ISSUE THREAD

**Issue by luqiaoshi** [kubesphere/kubesphere#5843]
**Describe the Bug**
Pre：project gateways : enabled
Steps:
1.[cluster]->[Gateway Settings], switch: Project Gateways
Actual:
Project gateways is not displayed,  query param is wrong

![image](https://github.com/kubesphere/kubesphere/assets/24789703/97700bef-51f7-4098-83a5-c9f5dbf8ebd4)

**Versions Used**
KubeSphere: `v3.4.0-rc.0`
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/2819ab2a-ed2d-4cbb-8311-90516044f206)

this issue has been resolved
