### ISSUE TITLE
【Devops】Workspace is associated with host-cluster，create cd-applications，deployment location show all-clusters

### ISSUE THREAD

**Issue by luqiaoshi** [kubesphere/kubesphere#5844]
**Describe the Bug**
Pre：exist workspace：qs-host-dev，associated host-cluster
Steps：
1.enter pro【qs-host-dev】-【Devops Projects】：Continuous Deployments
2.create cd-applications，select field：Deployment Location
Actual：
show all clusters

![image](https://github.com/kubesphere/kubesphere/assets/24789703/eae923e0-075d-4824-8bfe-db0fe9e30343)

**Versions Used**
KubeSphere: `v3.4.0-rc.0`
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by chilianyi** [comment]
Argocd is able to deploy app to multi cluster. 

This is not bug

**Comment by chilianyi** [comment]
1. DevOps, as a holistic functionality, includes internal sub-functions such as image builder, pipeline (Jenkins), and continuous deployment (ArgoCD). These sub-functions can only be enabled or disabled together, even if they are not actively used, which may result in resource wastage.

2. Continuous deployment (ArgoCD) is exclusively supported on the host cluster. The continuous deployment functionality can facilitate deployments across clusters, and it can be configured on the continuous deployment page to deploy applications across clusters hosted by itself or any member cluster. The current issue is that even if DevOps is enabled on a member cluster, continuous deployment functionality cannot be utilized on that member cluster.

3. Image builder (S2I/B2I) and pipeline (Jenkins) can be used on both host clusters and member clusters, with resource consumption occurring within the respective clusters.

**Comment by yingmanji** [comment]
This is not a bug, but now, it is a bug

**Comment by Matthew-Zong** [comment]
I temporarily rolled back the code and recompiled it, and the problem is now solved.
