### ISSUE TITLE
【Platform】Notification send test message fail: unknown resource type verification

### ISSUE THREAD

**Issue by luqiaoshi** [kubesphere/kubesphere#5846]
**Describe the Bug**
Steps：
1.【Platform Setting】-【Notification Channels】-【Email】
2.input correct info，click：【Send Test Message】
Actual:
send test message fail: unknown resource type verification

![image](https://github.com/kubesphere/kubesphere/assets/24789703/f6433fa4-b784-44c9-889e-8d057819a920)

**Versions Used**
KubeSphere: `ks.v3.4.0-rc.1`
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by wanjunlei** [comment]
The API path needs to change.
https://github.com/kubesphere/kubesphere/blob/master/pkg/kapis/notification/v2beta2/register.go#L56

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0-rc.0`
![image](https://github.com/kubesphere/kubesphere/assets/24789703/31b85e33-178b-4377-9886-d2ab87308fbe)
