### ISSUE TITLE
【Platform】Notification add filter conditions fail: values set can't be empty

### ISSUE THREAD

**Issue by luqiaoshi** [kubesphere/kubesphere#5847]
**Describe the Bug**
Steps:
1.【Platform Setting】-【Notification Channels】-【Email】
2. input correct info, add filter conditions
Actual:
add filter conditions fail: values set can't be empty

![image](https://github.com/kubesphere/kubesphere/assets/24789703/e3e6250c-06e2-4b85-ae2d-925c9a435358)

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
4. Scroll down to '....'
5. See error

**Expected behavior**

**Comment by halil-bugol** [comment]
![image](https://github.com/kubesphere/kubesphere/assets/60687576/2c2e4df9-4943-4bb2-814e-690a6e764cdd)

After typing alert-test, you need to hit enter and have it set as a value. After it is assigned as a value, it will turn gray around.

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/6d06397c-82b9-4bad-8ed2-8d4b928524f1)
