### ISSUE TITLE
【Platform】Configure slack notification，using 'Bot user OAuth Token' send test message fail

### ISSUE THREAD

**Issue by luqiaoshi** [kubesphere/kubesphere#5849]
**Describe the Bug**
Pre: slack generated 'OAuth Tokens for Your Workspace'
Steps:
1. 【Platform Setting】-【Notification Channels】-【Slack】
2. slack token using 'Bot user OAuth Token', setting channel, click : Send Test Message
Actual:
send test message fail: not_in_channel

![image](https://github.com/kubesphere/kubesphere/assets/24789703/f12e1171-dafb-422f-bf64-df1b17165789)
![image](https://github.com/kubesphere/kubesphere/assets/24789703/bd479788-4043-4459-9d9b-d91e4b9e1bec)

**Versions Used**
KubeSphere: `ks v3.4.0-rc.0`
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
4. Click on '....'
5. Scroll down to '....'
6. See error

**Expected behavior**

**Comment by wanjunlei** [comment]
<img width="589" alt="1689661451997" src="https://github.com/kubesphere/kubesphere/assets/53003665/74cd5e19-a124-4498-a4b6-143a6d4b59e7">

**Comment by luqiaoshi** [comment]
已验证，无效问题
1.先邀请app加入channel
2.再发送至该channel即可
![image](https://github.com/kubesphere/kubesphere/assets/24789703/ba43eb3f-c030-49dc-9045-f2d3c982d5c1)
