### ISSUE TITLE
安装失败，没有ansible-playbook 命令

### ISSUE THREAD

**Issue by DustFinger001** [kubesphere/kubesphere#585]
看错误提示应该是没有成功安装一些依赖，ansible也就没有安装成功。
![image](https://user-images.githubusercontent.com/16345979/61353867-64747480-a8a3-11e9-8e3a-0a289a92c3e7.png)

是否可以考虑改成容器化的ansible实现，不需要在ansible的主控端安装额外的软件。

手工安装好这些依赖后又出现这个错误
![image](https://user-images.githubusercontent.com/16345979/61354933-d221a000-a8a5-11e9-8a0c-c6ae08b21445.png)

ps：使用的是离线版安装程序

**Comment by pixiake** [comment]
离线环境下确实会出现各种各样的依赖问题    这个是新装的操作系统吗？ 之后会考虑把一些以来较多的东西容器化的。下边那个报错可以看下/kubeinstaller/下的那几个目录有没有被挂载

**Comment by gaoyangy** [comment]
解决方案是啥
