### ISSUE TITLE
【Workloads】workloads details page lacks of monitoring charts

### ISSUE THREAD

**Issue by luqiaoshi** [kubesphere/kubesphere#5850]
**Describe the Bug**
Steps：
1.Enter Project，【Application Workloads】-【Workloads】-【Deployments】
2.select deployment，view details page
Actuals：
lack of monitoring charts

![image](https://github.com/kubesphere/kubesphere/assets/24789703/e0d1a5b5-c1b0-486b-b53e-b2af37d0a260)

**Versions Used**
KubeSphere: `ks v3.4.0-rc.0`
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/6ad278ae-b0bb-4ae9-a253-21731e790c3d)
