### ISSUE TITLE
【Workloads】Add container with image-version，query condition is missing.

### ISSUE THREAD

**Issue by luqiaoshi** [kubesphere/kubesphere#5851]
**Describe the Bug**
Steps:
1.【workloads】-【Deployments】: Create
2.Add Container , search by image: nginx:latest
Actual:
1.query condition is missing, display all image
2.select any image, api not found

![image](https://github.com/kubesphere/kubesphere/assets/24789703/50f81d36-f7f6-4b02-9c68-a9ceded49563)
![image](https://github.com/kubesphere/kubesphere/assets/24789703/751ecb04-016c-4de5-8e74-c7fbbc1e6704)

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/aea63066-4467-43e7-b16e-98fb8559e07f)
