### ISSUE TITLE
An error is reported when installing a chart from application template UI

### ISSUE THREAD

**Issue by PurplestViper** [kubesphere/kubesphere#5856]
**Describe the Bug**
Get a javascript error when click on "install" button from app template in UI:
![image](https://github.com/kubesphere/kubesphere/assets/30370418/2ba10cbf-ef05-4001-88cc-e7024a5240f7)
The new issue: https://github.com/kubesphere/kubesphere/issues/5873

**Versions Used**
KubeSphere: v3.4.0

**Comment by zjpjly** [comment]
KubeSphere: v3.4.1

![Image](https://github.com/kubesphere/kubesphere/assets/18654693/cdac8579-9072-4cac-9f31-0e6e63dfc36a)
