### ISSUE TITLE
官网不更新了吗

### ISSUE THREAD

**Issue by changkang520** [kubesphere/kubesphere#5857]
官网：https://www.kubesphere.io/

git仓库版本已经发布到3.4.0了，网站上的信息还是3.3.2 。 是不准备维护了吗。不维护了我们集团准备换其他软件了，还是另一个集团给我们公司说的

**Comment by wwt164888** [comment]
谁说的

**Comment by sigboom** [comment]
3.4.0 升级起来有不少问题，估计官方还在收集问题

**Comment by faweizhao26** [comment]
3.4.0 上周刚刚发布，官网上的相关信息肯定要滞后一些，大概一周左右时间。这也是一贯的节奏。
没有任何不维护的消息来源。
