### ISSUE TITLE
Components are not upgraded

### ISSUE THREAD

**Issue by PurplestViper** [kubesphere/kubesphere#5858]
**Describe the Bug**
After upgrading from 3.3.2 to 3.4.0, some system components still maintain the old version, including devops, ks-core helm chart, openpitrix-jobs, etc.
![image](https://github.com/kubesphere/kubesphere/assets/30370418/aebbf6b3-9a0f-493e-b865-4e54cd774418)
![image](https://github.com/kubesphere/kubesphere/assets/30370418/9b821ee2-f671-45fc-a991-28ae17b33875)
![image](https://github.com/kubesphere/kubesphere/assets/30370418/7b3a592e-40f3-49c7-9494-ea2264872602)

**Versions Used**
KubeSphere: v3.4.0
Kubernetes: 1.25.10

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/810a7ec2-7a6a-4ec5-afea-672b976bfd95)



![Image](https://github.com/kubesphere/kubesphere/assets/18654693/4cd87871-b8a2-45ef-aedd-4de8ae3592b1)
