### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by TongTrey** [kubesphere/kubesphere#586]
![image](https://user-images.githubusercontent.com/50939920/61358158-4c552300-a8ac-11e9-89af-2709be7bb36b.png)
![image](https://user-images.githubusercontent.com/50939920/61358261-858d9300-a8ac-11e9-9316-e812981fb1b7.png)

可以帮忙看看是啥原因吗？

**Comment by TongTrey** [comment]
用的自己搭建的nfs服务器，发现创建的pvc全是pending导致了相关的pod启动不起来。想问下nfs服务器最小硬盘空间需求多大？

**Comment by pixiake** [comment]
应该跟nfs的磁盘大小没有关系，可以参考 *(rw,insecure,sync,no_subtree_check,no_root_squash)这个配置下nfs，然后先试下主机上是否可以挂载nfs

**Comment by TongTrey** [comment]
谢谢可以挂载了但是又有问题出来了希望能给与解答 
![image](https://user-images.githubusercontent.com/50939920/61381216-4fb4d280-a8dd-11e9-8132-d1d0fd72f1c5.png)

**Comment by pixiake** [comment]
这个看样子是有特殊字符无法解析   如果编辑过jenkins的相关配置的话可以检查下是不是写入了特殊字符

**Comment by TongTrey** [comment]
卸载了，扩容到2个node节点就好了。。

**Comment by TongTrey** [comment]
安装好了之后关于girlab的pod运行不正常一直处于init的状态删掉了重新拉取镜像还是这样
![image](https://user-images.githubusercontent.com/50939920/61427229-f46ff800-a94f-11e9-90a8-b5c335e83ac5.png)
另外istio的ingressgateway其中一个pod运行不正常一直报错Envoy proxy is NOT ready另外pod一个没问题
![image](https://user-images.githubusercontent.com/50939920/61427314-37ca6680-a950-11e9-8764-87b13eb8455e.png)
![image](https://user-images.githubusercontent.com/50939920/61427379-8546d380-a950-11e9-8c5a-7650871bb4c5.png)
最后前台页面很多页面加载非常缓慢并且伴随着一些js加载ipa请求报错。（下图的集群状态间歇性的能加载出来）是我的服务器配置不够吗？
我是三台服务器4核16g内存100G硬盘 
![image](https://user-images.githubusercontent.com/50939920/61427680-ae1b9880-a951-11e9-8581-08a7c1924c4d.png)


希望能协助排查下

**Comment by TongTrey** [comment]
安装好了之后关于girlab的pod运行不正常一直处于init的状态删掉了重新拉取镜像还是这样
![image](https://user-images.githubusercontent.com/50939920/61427229-f46ff800-a94f-11e9-90a8-b5c335e83ac5.png)
另外istio的ingressgateway其中一个pod运行不正常一直报错Envoy proxy is NOT ready另外pod一个没问题
![image](https://user-images.githubusercontent.com/50939920/61427314-37ca6680-a950-11e9-8764-87b13eb8455e.png)
![image](https://user-images.githubusercontent.com/50939920/61427379-8546d380-a950-11e9-8c5a-7650871bb4c5.png)
最后前台页面很多页面加载非常缓慢并且伴随着一些js加载ipa请求报错。（下图的集群状态间歇性的能加载出来）是我的服务器配置不够吗？
我是三台服务器4核16g内存100G硬盘 
![image](https://user-images.githubusercontent.com/50939920/61427680-ae1b9880-a951-11e9-8581-08a7c1924c4d.png)

能给分析分析吗？

**Comment by pixiake** [comment]
可以看下init状态pod的容器日志，这个环境是1master+2node吗？感觉是cpu配置有点少

**Comment by TongTrey** [comment]
cpu配置应该还行。
总结一下
1. 最好把不要用内置的gitlab和harbor这样要出各种各样的问题。比如gitlab和harbor相关的容器一直处于init状态，然后iam的db pod创建日志少表需要手动去代码里面找相关sql语句,创建不了devops项目,创建路由不会自动加入注解等等。。。 使用自己单独安装gitlab和harbor均未发现以上问题
2. 发现运行缓慢调大服务器的最大文件打开数即可。
3. 安装除了问题不要尝试反复执行安装脚本这样问题会越来越多，先卸载干净了再安装。
4.内存一定要保证内存16G以上要不会报错内存不足。测试集群安装1个maser1个node即可安装，不用去配置2个node浪费资源，还可以大大的减少安装时间
5. nfs服务器挂载一定要先测试好要不之后创建的pod一直pending哈哈。

最后建议下能不能把脚本拆分开来。要不出问题了想要重装是一个非常耗时的事情。比如拆成k8s集群安装卸载脚本和kubesphere的安装卸载脚本？

**Comment by pixiake** [comment]
嗯   很好的建议    之后会拆开的    kubesphere部分会单独做成容器化安装
