### ISSUE TITLE
Devops cannot be used normally after upgrading to 3.4.0

### ISSUE THREAD

**Issue by PurplestViper** [kubesphere/kubesphere#5860]
**Describe the Bug**
An error is thrown when creating a Devops project and Pipeline, the problem may be related to https://github.com/kubesphere/kubesphere/issues/5858.
![image](https://github.com/kubesphere/kubesphere/assets/30370418/1d0e08a7-65a7-40a3-849c-68e368f124d4)
![image](https://github.com/kubesphere/kubesphere/assets/30370418/db6b2be0-82b4-45a3-8655-e59bead36ec3)

**Versions Used**
KubeSphere: v3.4.0
Kubernetes: 1.25.10

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by quinoxz** [comment]
yes i have this bug in v3.4 too

**Comment by yudong2015** [comment]
> **Describe the Bug** An error is thrown when creating a Devops project and Pipeline, the problem may be related to #5858. ![image](https://user-images.githubusercontent.com/30370418/255464856-1d0e08a7-65a7-40a3-849c-68e368f124d4.png) ![image](https://user-images.githubusercontent.com/30370418/255464902-db6b2be0-82b4-45a3-8655-e59bead36ec3.png)
> 
> **Versions Used** KubeSphere: v3.4.0 Kubernetes: 1.25.10
> 
> **Environment** How many nodes and their hardware configuration:
> 
> For example: CentOS 7.5 / 3 masters: 8cpu/8g; 3 nodes: 8cpu/16g (and other info are welcomed to help us debugging)
> 
> **How To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.

Yes, this is related to #5858 , that caused by the DevOps upgrade failed.

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/5d61375a-8b75-4ad1-8329-52896c7b0b49)


![Image](https://github.com/kubesphere/kubesphere/assets/18654693/3f71a8a0-fbe2-417b-a6ed-de1c8585a951)



![Image](https://github.com/kubesphere/kubesphere/assets/18654693/e55bc5a8-010e-4d73-848e-8bf7d8fa33db)
