### ISSUE TITLE
【upgrade】ks3.3.2->ks3.4.0, system components can‘t find right version for Receiver

### ISSUE THREAD

**Issue by sigboom** [kubesphere/kubesphere#5861]
**Describe the Bug**
use ks-installer update Cluster successfully，but ks-apiserver component restart always.

![image](https://github.com/kubesphere/kubesphere/assets/34954447/e03b1e26-7171-4b80-a34a-5fa16839e1e4)
**Versions Used**
KubeSphere: v3.4.0

**Environment**
1.24.6-aliyun.1

**Comment by littleBlackHouse** [comment]
base on log. your etcd is not ready. please check it.

**Comment by sigboom** [comment]
https://ask.kubesphere.io/forum/d/22655-sheng-ji-340hou-webwu-fa-deng-lu-ti-shi-request-to-httpks-apiserveroauthtoken-failed/6
