### ISSUE TITLE
v3.4.0容器组资源显示貌似有问题, 无痕、切换50%都有这个问题

### ISSUE THREAD

**Issue by AIMWLI** [kubesphere/kubesphere#5866]
<img width="1421" alt="Snipaste_2023-07-29_14-03-04" src="https://github.com/kubesphere/kubesphere/assets/31265254/542f7f86-2119-43b9-9f11-aa68089aa91c">

OS: M1  Chrome

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/19bc2f1f-4165-4f71-964d-313e8f54af0b)
