### ISSUE TITLE
Can't Install or upgrade kubesphere 3.4.0 with kk:v3.0.10

### ISSUE THREAD

**Issue by DoNotBugPlz** [kubesphere/kubesphere#5867]
## Something Wrong With the kubesphere 3.4.0

**What's your question**
Above the Question Titile,Can't install  --with kubesphere 3.4.0  -wtih kubernetes 1.24.x|1.25.x|1.26.x ( with the same problem)

**Environment: OS & Hardware Information**

* centos7
* kubesphere 3.4.0(try 3.3.2 upgrade to 3.4.0 but failed with kk v-3.0.10)
*  1.24.x |1.25.x|1.26.x

**Error logs or message (Attach logs or screenshot)**
```
15:13:56 CST success: [master]
Please wait for the installation to complete:     >>---
```
**It's waiting for this msg for a long time. So I use the command:**
`kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l 'app in (ks-install, ks-installer)' -o jsonpath='{.items[0].metadata.name}') -f
`

Here is logs:
```
TASK [common : KubeSphere | Creating custom manifests] *************************
changed: [localhost] => (item={'name': 'custom-values-opensearch-master', 'file': 'custom-values-opensearch-master.yaml'})
changed: [localhost] => (item={'name': 'custom-values-opensearch-data', 'file': 'custom-values-opensearch-data.yaml'})
failed: [localhost] (item={'name': 'custom-values-opensearch-curator', 'file': 'custom-values-opensearch-curator.yaml'}) => {"ansible_loop_var": "item", "changed": false, "item": {"file": "custom-values-opensearch-curator.yaml", "name": "custom-values-opensearch-curator"}, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'opensearchPrefix'"}
changed: [localhost] => (item={'name': 'custom-values-opensearch-dashboard', 'file': 'custom-values-opensearch-dashboard.yaml'})
```

So What Can I do Next? Many Thanks For Help

**Comment by halil-bugol** [comment]
What are you using as container runtime?

**Comment by DoNotBugPlz** [comment]
> What are you using as container runtime?

Containerd

**Comment by wenchajun** [comment]
Try adding this field.
https://github.com/kubesphere/ks-installer/blob/master/deploy/cluster-configuration.yaml#L81

**Comment by DoNotBugPlz** [comment]
> @wanjunlei @wenchajun It seems that ‘opensearchPrefix’ is missing from cc (clusterconfiguration), right?
Yes, that's the issue, and it has been resolved. Thank you!
