### ISSUE TITLE
Can's delete user.

### ISSUE THREAD

**Issue by zhangchiyue** [kubesphere/kubesphere#5870]
**Describe the Bug**
Can't delete  or create user.
[](url)
![k8sdelete](https://github.com/kubesphere/kubesphere/assets/39554716/e8ea10bd-5f7a-48c5-948c-fe70e1a6c76d)

**Versions Used**
KubeSphere: v3.3.2
Kubernetes: v1.23.10

**Environment**
 CentOS 7.5 / 1 masters:  4cpu/8g; 1nodes 8cpu/16g；1node:4cpu/8g;

**How To Reproduce**
1点击访问控制->用户->创建\删除都报异常无法删除，以前创建的用户也无法密码登录，只有admin可以登录

**Comment by zhou1203** [comment]
Hi, thanks for your bug report. Could you please provide more details about this bug, such as ks-apiserver logs, the  error message in http response, or anything else that might help us understand the issue better.
