### ISSUE TITLE
v3.4.0 create autoscaling failed

### ISSUE THREAD

**Issue by yakexi007** [kubesphere/kubesphere#5872]
kubesphere: v3.4.0
kubernetes: v1.26.0

![image](https://github.com/kubesphere/kubesphere/assets/7007290/9e553d52-0e97-4b41-8a2f-06085c7be310)

**Comment by wansir** [comment]
related to https://github.com/kubesphere/kubesphere/pull/5833

/assign @kubesphere/sig-console

**Comment by yeqiugt** [comment]
I noticed that the pull request https://github.com/kubesphere/console/pull/4191 has been merged. Why does the kubesphere-3.4.0 built just now  still have this bug?

**Comment by VioZhang** [comment]
same with https://github.com/kubesphere/kubesphere/issues/5884

**Comment by zjpjly** [comment]
this issue has been resolved 
![20231031093240_rec_](https://github.com/kubesphere/kubesphere/assets/18654693/4e22e0fe-2de2-4bb7-bf9d-f3663407c8e2)

**Comment by zjpjly** [comment]
kubesphere: v3.4.1
kubernetes: v1.22.12

![Image](https://github.com/kubesphere/kubesphere/assets/18654693/2dc123cb-722b-4fb0-b43a-eeb01b1d8cb1)

**Comment by donniean** [comment]
K8s version < v1.23, the api version is `autoscaling/v2beta2` .

K8s version >= 1.23, the api version is `autoscaling/v2` .
