### ISSUE TITLE
[BUG]: Error in allocating enterprise space

### ISSUE THREAD

**Issue by freemankevin** [kubesphere/kubesphere#5874]
An error is reported when the project is assigned to the enterprise space.

![359701919b7034991a32f58f4ed7220](https://github.com/kubesphere/kubesphere/assets/71524776/22dc7339-1376-4a7c-a681-2775cb1ec4e1)

From v3.0.0 to the current latest version v3.4.0, this has always existed, although the second addition is normal, but the first assignment of admin will report an error like this.

**Comment by zhou1203** [comment]
We are so glad for your bug reporting. This bug is scheduled to be fixed in version 3.4.1

**Comment by freemankevin** [comment]
Ok,Thanks.

**Comment by zhou1203** [comment]
Sorry about that, we recommend upgrading through each successive version. Skip version upgrading will trigger some unexpected errors

**Comment by freemankevin** [comment]
Get it，Thanks.
