### ISSUE TITLE
chart failed to be summited due to "404 page not found error"

### ISSUE THREAD

**Issue by zhangyang-bytedance** [kubesphere/kubesphere#5875]
**Describe the Bug**
![image](https://github.com/kubesphere/kubesphere/assets/95331997/e8c906a0-3591-4787-af0d-646551190ed2)

**Versions Used**
KubeSphere: 3.4.0
Kubernetes: 1.26.7

**How To Reproduce**
https://www.kubesphere.io/zh/docs/v3.3/application-store/app-lifecycle-management/

**Comment by doramingo** [comment]
是个bug，手动修复的话可以修改源码中的go.mod：github.com/emicklei/go-restful/v3 v3.11.0重新编译ks-apiserver

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/bfd2955a-fe6d-492a-be7f-735ec33f20b9)
