### ISSUE TITLE
Check clusterRole when adding a cluster

### ISSUE THREAD

**Issue by iawia002** [kubesphere/kubesphere#5877]
Preventing a host cluster from being added as a member of another cluster by mistake, ref: https://ask.kubesphere.io/forum/d/22464-kubespace-zhong-de-ns-jia-ru-workspace-sui-hou-jia-ru-zhi-hou-de-nsjiu-hui-bei-zi-dong-shan-chu

**Comment by zjpjly** [comment]
A host cluster  can not bind B host cluster

![Image](https://github.com/kubesphere/kubesphere/assets/18654693/0d1d6848-09c0-44a7-be4b-91b6b08b807e)
