### ISSUE TITLE
Gateway enable TCP/UPD traffic configuration prompt unknown field "tcp"

### ISSUE THREAD

**Issue by hongzhouzi** [kubesphere/kubesphere#5880]
**Describe the Bug**
Gateway enable TCP/UPD traffic configuration reporting the following error:
gateways. gateway.kubesphere.io "kubesphere-router-kubesphere-system" was not valid: * ‹nil>: Invalid value: "The edited file failed validation": ValidationError (Gateway.spec.controller): unknown field "tcp" in jo.kubesphere.gateway.spec.controller

**Versions Used**
KubeSphere: v3.4.0

**Comment by hongzhouzi** [comment]
This can be resolved in this release by executing the following command in the environment:
```sh
kubectl apply -f https://github.com/kubesphere/kubesphere/raw/v3.4.0/config/ks-core/crds/gateway.kubesphere.io_gateways.yaml
```

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/6f4fb8bb-f4dc-40ae-bee6-004e6acc31f4)
