### ISSUE TITLE
kubesphere 3.4.0 after enable  Logging , the page of Cluster Settings -> Log Receivers alert errors

### ISSUE THREAD

**Issue by ElfenSterben** [kubesphere/kubesphere#5882]
**Describe the Bug**
after enable  Logging , the page of Cluster Settings -> Log Receivers alert errors
![image](https://github.com/kubesphere/kubesphere/assets/19554131/d885b4e1-fb4f-486b-8a9f-7f8b39afc7dd)

**Versions Used**
KubeSphere: 3.4.0
Kubernetes: 1.27.4

**How To Reproduce**
1. enable Logging  https://www.kubesphere.io/docs/v3.3/pluggable-components/logging/
2. after ks-installer finished, go to Cluster Settings -> Log Receivers

**Comment by qianketian** [comment]
一样的错误

**Comment by nejinn** [comment]
就是个bug，太难了，还打算买企业版

**Comment by zhangnan30** [comment]
I also encountered this problem, it should be a bug

**Comment by nejinn** [comment]
Hi，this is Lerity      邮件已经收到      辛苦了

**Comment by harrymore** [comment]
I'm also having the same issue, it should be a bug

**Comment by harrymore** [comment]
And the document of https://www.kubesphere.io/docs/v3.3/pluggable-components/logging/ is out of date, opensearch is used when enabling logging component ,but chapter of "Verify the Installation of the Component" shows elasticsearch as before.

**Comment by wanjunlei** [comment]
same as https://github.com/kubesphere/console/issues/4176

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/4ef18860-ba80-4b52-b06b-aaec16d862e7)

**Comment by nejinn** [comment]
Hi，this is Lerity      邮件已经收到      辛苦了
