### ISSUE TITLE
【upgrade】ks 3.3.1=》3.4.0，enable logging failed.

### ISSUE THREAD

**Issue by luqiaoshi** [kubesphere/kubesphere#5888]
**Describe the Bug**
Pre: ks v3.3.1 + k8s v1.23.17
Step:
1.upgrade ks: ./kk upgrade --with-kubesphere v3.4.0 --with-kubernetes v1.23.17
2.wait for finishing, enable logging
Actual:
enable logging failed.
![image](https://github.com/kubesphere/kubesphere/assets/24789703/0c4a43d8-131d-4413-8552-6d50afa3d700)

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by hbbdgyb** [comment]
我也是服了，我也遇到了

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/08d244b3-38bd-4a76-bf4c-62de574012a1)


![Image](https://github.com/kubesphere/kubesphere/assets/18654693/afacc2b8-4ada-4aea-bd26-1e472e22833f)



![Image](https://github.com/kubesphere/kubesphere/assets/18654693/e0ec067d-39e5-4d12-9904-2f1ce5bd4e4f)
