### ISSUE TITLE
Request for front end project

### ISSUE THREAD

**Issue by hungtcs** [kubesphere/kubesphere#589]
Front-end project is required for using, thanks!

**Comment by cnicy** [comment]
前端据说要Q4才能发布，我们打算自己做一套，开源。
基于ReactJS+AntDesign+UmiJs

**Comment by rayzhou2017** [comment]
初步定在10月中旬。

**Comment by hungtcs** [comment]
@rayzhou2017 Thanks for your answer.

**Comment by spesoul** [comment]
前段部分现在开源准备的怎么样了？

**Comment by rayzhou2017** [comment]
现在大家都在忙2.1.0的发布，只有等这个发布了才能准备前端代码开源的事情，2.1.0预计这个月能release，很抱歉有些delay，请耐心等候一下。

**Comment by spesoul** [comment]
@rayzhou2017 Thanks for your comment

**Comment by rayzhou2017** [comment]
Already opensourced
