### ISSUE TITLE
No data in Tracing but Jaeger UI is display

### ISSUE THREAD

**Issue by spyhunter88** [kubesphere/kubesphere#5890]
## General remarks
After install Kubesphere 3.4.0 with K8s 1.25.3, install my own sample app (via Kubesphere Web UI), Traffic Monitoring is showed, but Tracing notifies error on the top-right corner (I don't remember but it display with **v1beta1** version that not support by K8S 1.25.3).
So I try to install Jeager Operator 2.46 from helm, the error now gone, but display `No Data`.
I also expose Jeager UI via NodePort.

Then I install OpenTelemetry Operator and Collector from this link `https://opentelemetry.io/docs/kubernetes/operator/`, with endpoint is link to jeager colletor.

I deploy a Java Quarkus application which send Otel data to `otel-collector` endpoint. Also Expose via Ingress controller (use nginx controller class).

**Versions Used**
**Kubesphere**: 3.4.0 with Istio, Monitoring and Logging enabled.
**Kubernetes**: 1.25.3
**Jaeger operator 2.46** (install from helm).
**`otel-operator`** and **`otel-collector`** are installed and send traces data to `jaeger-collector` via endpoint `jaeger-collector.istio-system.svc.cluster.local:14250`.
**Java Quarkus app** sends traces data to `otel-collector-collector.opentelemetry-operator-system.svc.cluster.local:1437` endpoint.

**Environment**
On-premise.

**How To Reproduce**
Keep refresh the Quarkus app via ingress.
The traffic monitoring is showed.
The tracing is empty even the service name is **`landing-page-service`**.
Open Jaeger UI (exposed via nodeport) then I can see 3 services in the list: `kubesphere-router-kubesphere-system.kubesphere-controls-system`, `jaeger.istio-system` and **`landing-page-service`** and all have trace data.

**Expected behavior**
Tracing menu in Kubesphere should display trace data.

Can someone explain the query logic behind ks-api then I can alter the otel-operator or jeager-operator to make the trace data is visible?

**Comment by hongzhouzi** [comment]
> Can someone explain the query logic behind ks-api then I can alter the otel-operator or jeager-operator to make the trace data is visible?

The jaeger-query API requested by the ks-api proxy can be seen here,
https://github.com/kubesphere/kubesphere/blob/v3.4.0/pkg/kapis/servicemesh/metrics/v1alpha2/handler.go#L152-L158

**Comment by spyhunter88** [comment]
Oh, I can see the difference between request in Jeager UI and ks-api proxy. The `serviceName` in ks-api proxy contain namespace, it should be `landing-page-service.project-dev` (I guess) but my otel-collector only get `landing-page-service`.

Seem like I only need to change my application config to generate service name to `landing-page-service.project-dev` instead of `landing-page-service`.

I will try and update later, thanks @hongzhouzi .
