### ISSUE TITLE
ERROR: pipeline edit shell 

### ISSUE THREAD

**Issue by gdstzmy** [kubesphere/kubesphere#5891]
**Describe the Bug**
In DevOps, when creating a pipeline, specifying shell scripts in the graphical interface of the pipeline editor does not actually exist. It must be edited in the Jenkinsfile to take effect.

**Versions Used**
KubeSphere:3.4.0
Kubernetes: k3s 2.12

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.9 / 1 masters:  4cpu/8g; 2 nodes: 4cpu/8g
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. In a DevOps project ,Go to 'Edit pipeline page'
2. Click on 'shell'
3. input command

**Expected behavior**

**Comment by GEK1** [comment]
Has the problem been solved? I had the same problem

**Comment by gdstzmy** [comment]
No，I will achieve my requirements by modifying the Jenkinsfile.

发件人: ***@***.***>
发送时间: 2023年10月11日 14:03
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [kubesphere/kubesphere] ERROR: pipeline edit shell (Issue #5891)


Has the problem been solved? I had the same problem

―

**Comment by VioZhang** [comment]
Same with https://github.com/kubesphere/kubesphere/issues/5902
