### ISSUE TITLE
3.4版本devops的流水线运行记录BUG

### ISSUE THREAD

**Issue by xyty-citibank** [kubesphere/kubesphere#5899]
**Describe the Bug**
devops流水线在运行几次后，在编辑设置中修改流水线的正则过滤配置后，运行记录的id重新从1开始，但是页面上的原有的运行记录还在，导致没有办法区分新运行的记录
For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:3.4.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by VioZhang** [comment]
Is that expected? @chilianyi

**Comment by yudong2015** [comment]
> **Describe the Bug** A clear and concise description of what the bug is. devops流水线在运行几次后，在编辑设置中修改流水线的正则过滤配置后，运行记录的id重新从1开始，但是页面上的原有的运行记录还在，导致没有办法区分新运行的记录 For UI issues please also add a screenshot that shows the issue.
> 
> **Versions Used** KubeSphere:3.4.0 Kubernetes: (If KubeSphere installer used, you can skip this)
> 
> **Environment** How many nodes and their hardware configuration:
> 
> For example: CentOS 7.5 / 3 masters: 8cpu/8g; 3 nodes: 8cpu/16g (and other info are welcomed to help us debugging)
> 
> **How To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.

@xyty-citibank 编辑正则过滤后，新的运行记录和原来的运行记录 对应的代码分支 是不同的吗 ？

**Comment by yudong2015** [comment]
> Is that expected? @chilianyi

Yes, that is expected that id start from 1 for new branch.

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/74a2d9af-e02f-4de3-b9c6-d21a00c4c195)
