### ISSUE TITLE
pipleline can't save shell command

### ISSUE THREAD

**Issue by weicy98** [kubesphere/kubesphere#5902]
environment: ubuntu20.04 all in one install 
I tried to add commond on  shell step, it still empty 
<img width="1440" alt="image" src="https://github.com/kubesphere/kubesphere/assets/118351330/b3ad1f5d-2d14-4732-aa1c-f92f343708aa">

**Comment by GEK1** [comment]
Has the problem been solved? I had the same problem

**Comment by yazhouio** [comment]
link https://github.com/kubesphere/issues/issues/2050

**Comment by daishuhuaimu** [comment]
I had the same problem，It can only be added via jenkinsfile

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/cbbb155e-b3ff-41f3-872e-20e3f0d2c7c5)
