### ISSUE TITLE
kubesphere 应用模板部署应用失败

### ISSUE THREAD

**Issue by Aurorxa** [kubesphere/kubesphere#5905]
# 版本
k8s 的版本是 v1.21.17 或 v1.23.17
kubesphere 的版本是 v3.3.2

# 安装方式
采用最小化安装

# 报错截图

![image](https://github.com/kubesphere/kubesphere/assets/25677587/edad2104-b0f5-491b-9c94-6c9a24a5e1e5)
![image](https://github.com/kubesphere/kubesphere/assets/25677587/acd3e6da-52db-471c-a254-00da1242bfeb)

**Comment by Aurorxa** [comment]
找到对应的问题了，ks-controller等组件中的 helm 版本过低导致的。
![image](https://github.com/kubesphere/kubesphere/assets/25677587/e25245b9-ad0e-466a-901a-61d669453260)
![image](https://github.com/kubesphere/kubesphere/assets/25677587/db11ed8b-1df7-4cee-b659-f926e7c486ab)

在 helm 的官方 issue 找到的解决方案：https://github.com/arttor/helmify/issues/11

![image](https://github.com/kubesphere/kubesphere/assets/25677587/98d97fc7-5016-4f96-9a4a-3af03eb64a27)

**Comment by Aurorxa** [comment]
希望，官方将内置的 helm 的版本升级一下。

**Comment by Aurorxa** [comment]
目前的临时解决方案是：手动替换容器中的 helm 。
![image](https://github.com/kubesphere/kubesphere/assets/25677587/d139c967-5bed-40e9-b41a-5abcb0271839)

**Comment by inksnw** [comment]
3.4版本已改用helm sdk的方式调用, 已不存在这个问题, 如果不能升级可临时手动替换容器中的 helm, 或者更新build/ks-controller-manager/Dockerfile 和 build/ks-apiserver/Dockerfile 中的ARG HELM_VERSION=v3.5.2 为新版, 手动编译

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/e72b24ce-c009-4e07-a830-777eafacb578)
