### ISSUE TITLE
Error the job is while at console it shows completed

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5906]
![09708529d28aac7adbb4ef416022100](https://github.com/kubesphere/kubesphere/assets/41519383/2700ffb0-8d3f-40b2-96b0-db0a62cf8a5f)
![b6e0e1fc4eed39352ea9c1dc70a920c](https://github.com/kubesphere/kubesphere/assets/41519383/2a857e8d-709c-4d51-9ee2-24df57d75ce8)

**Comment by doramingo** [comment]
The Kubesphere version is version 3.4.0.

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/9ca98c2a-1fdc-47d5-849a-70e0d9cf482e)
