### ISSUE TITLE
CentOS7.6安装离线版2.0失败

### ISSUE THREAD

**Issue by bowenliang123** [kubesphere/kubesphere#591]
使用的是2.0离线安装包，在root下执行install.sh安装失败
（https://kubesphere.io/download/offline/advanced-2.0.0）

<img width="1440" alt="屏幕快照 2019-07-19 上午10 29 45" src="https://user-images.githubusercontent.com/1935105/61505061-26e12a00-aa10-11e9-8d36-7c925066c4a9.png">

**Comment by lilinlinlin** [comment]
该机器之前安装了docker吗？配置是什么呢

**Comment by pixiake** [comment]
/etc/docker里是不是有daemon.json

**Comment by bowenliang123** [comment]
我是在vmware里面全新安装CentOS，没有安装过Docker

**Comment by bowenliang123** [comment]
/etc/docker路径为不存在

**Comment by pixiake** [comment]
systemctl status docker 看下

**Comment by bowenliang123** [comment]
systemctl status docker 结果如图 @pixiake 
<img width="1440" alt="屏幕快照 2019-07-19 上午11 17 59" src="https://user-images.githubusercontent.com/1935105/61507067-e3d68500-aa16-11e9-93e5-826de148d2cf.png">

**Comment by bowenliang123** [comment]
我想知道执行install.sh之后的这些错误提示，有影响吗？
发现/kubeinstaller/yum_repo/iso/repodata/repomd.xml不存在，/kubeinstaller/yum_repo/下是空的

Loading mirror speeds from cached hostfile
file:///kubeinstaller/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#37 - "Couldn't open file /kubeinstaller/yum_repo/iso/repodata/repomd.xml"
Trying other mirror.


<img width="1440" alt="屏幕快照 2019-07-19 上午11 17 59" src="https://user-images.githubusercontent.com/1935105/61507110-036dad80-aa17-11e9-8c07-0a236364609c.png">

**Comment by pixiake** [comment]
目前的离线包还没有对centos7.6做适配，所以找不到yum源，这个docker是怎么装上的呢？

**Comment by pixiake** [comment]
journalctl -f -u docker

**Comment by bowenliang123** [comment]
请问如果centos7.6不合适，我应该找centos版本多少？docker我没有手动安装，因为在文档上没有看到需要提前安装docker

journalctl -f -u docker
如图
<img width="1440" alt="屏幕快照 2019-07-19 上午11 26 59" src="https://user-images.githubusercontent.com/1935105/61507402-26e52800-aa18-11e9-9d4c-8f163a36941a.png">

**Comment by bowenliang123** [comment]
CentOS7.5是一定可以吗？虚拟机安装all-in-one有问题吗？

**Comment by pixiake** [comment]
centos7.5是可以的，如果机器可以联网的话，用在线安装包也可以支持centos7.6
配置要满足官网的配置需求哦

**Comment by bowenliang123** [comment]
噢这样啊。对了，centos的官网和镜像都已经不提供7.5的ISO下载了

**Comment by pixiake** [comment]
我看这个里边还可以下载  http://vault.centos.org/7.5.1804/isos/x86_64/   用Minimal的应该就可以

**Comment by pixiake** [comment]
我看这个里边还可以下载 http://vault.centos.org/7.5.1804/isos/x86_64/ 用Minimal的应该就可以

**Comment by bowenliang123** [comment]
好，等下我试试7.5
刚才我在用CentOS7.6来装2.0.2在线安装包，结果失败了，帮忙也看看

![image](https://user-images.githubusercontent.com/1935105/61508808-26e82680-aa1e-11e9-90c6-edc10d1df11f.png)

**Comment by pixiake** [comment]
kubectl  get pod -n kube-system  看下

**Comment by bowenliang123** [comment]
![image](https://user-images.githubusercontent.com/1935105/61508882-9100cb80-aa1e-11e9-8331-836334096d48.png)

**Comment by pixiake** [comment]
重新执行一次安装应该就可以了

**Comment by bowenliang123** [comment]
重试了两次，都是一样的报错，失败了

**Comment by bowenliang123** [comment]
![image](https://user-images.githubusercontent.com/1935105/61509611-ee4a4c00-aa21-11e9-9542-072c22cca219.png)

**Comment by pixiake** [comment]
这个报错应该是本地的网络配置导致helm不能正常使用   防火墙或者iptables

**Comment by bowenliang123** [comment]
谢谢建议，但还是遇到了新的问题。

关闭防火墙后，重新执行安装成功，并启动。

然后我在指南，部署应用的时候遇到错误。
https://docs.kubesphere.io/advanced-v2.0/zh-CN/quick-start/ingress-demo/

![image](https://user-images.githubusercontent.com/1935105/61512775-8c8fdf00-aa2d-11e9-9e5d-bcdc74902482.png)


查看服务组件的状态，部分正常，部分异常。

![image](https://user-images.githubusercontent.com/1935105/61512802-a3363600-aa2d-11e9-8611-fb7d83ea9770.png)


请问有什么好的建议吗，谢谢

**Comment by pixiake** [comment]
这个跟环境配置以及带宽有关，如果是单节点的话8c16g是可以正常启动的，机器满足这个配置要求的话，应该等等就正常了

**Comment by bowenliang123** [comment]
好的，谢谢！！已经

**Comment by liangyuanpeng** [comment]
@pixiake 

你好，帮忙看看我这个问题，谢谢！
```
TASK [prepare/nodes : KubeSphere| Installing JQ (YUM)] ****************************************************************************************
Friday 02 August 2019  18:27:22 +0800 (0:00:00.107)       0:00:04.625 *********
FAILED - RETRYING: KubeSphere| Installing JQ (YUM) (5 retries left).
FAILED - RETRYING: KubeSphere| Installing JQ (YUM) (4 retries left).
FAILED - RETRYING: KubeSphere| Installing JQ (YUM) (3 retries left).
FAILED - RETRYING: KubeSphere| Installing JQ (YUM) (2 retries left).
FAILED - RETRYING: KubeSphere| Installing JQ (YUM) (1 retries left).
fatal: [ks-allinone]: FAILED! => {"attempts": 5, "changed": false, "msg": "No package matching 'jq' found available, installed or updated", "rc": 126, "results": ["No package matching 'jq' found available, installed or updated"]}

PLAY RECAP ************************************************************************************************************************************
ks-allinone                : ok=4    changed=2    unreachable=0    failed=1
```

OS : Centos7.6
配置符合要求

**Comment by pixiake** [comment]
@liangyuanpeng   执行下yum  install  jq  看看

**Comment by liangyuanpeng** [comment]
@pixiake 

没有jq这个package，我下了jq的二进制包放在``/usr/bin``目录下，没有起作用，但是jq这个命令是可以的

```
[root@ks-allinone scripts]# jq
jq - commandline JSON processor [version 1.6]

Usage:  jq [options] <jq filter> [file...]
        jq [options] --args <jq filter> [strings...]
        jq [options] --jsonargs <jq filter> [JSON_TEXTS...]

jq is a tool for processing JSON inputs, applying the given filter to
its JSON text inputs and producing the filter's results as JSON on
standard output.

The simplest filter is ., which copies jq's input to its output
unmodified (except for formatting, but note that IEEE754 is used
for number representation internally, with all that that implies).

For more advanced filters see the jq(1) manpage ("man jq")
and/or https://stedolan.github.io/jq

Example:

        $ echo '{"foo": 0}' | jq .
        {
                "foo": 0
        }

For a listing of options, use jq --help.
```

```
FAILED - RETRYING: KubeSphere| Installing JQ (YUM) (4 retries left).
FAILED - RETRYING: KubeSphere| Installing JQ (YUM) (3 retries left).
FAILED - RETRYING: KubeSphere| Installing JQ (YUM) (2 retries left).
FAILED - RETRYING: KubeSphere| Installing JQ (YUM) (1 retries left).
fatal: [ks-allinone]: FAILED! => {"attempts": 5, "changed": false, "msg": "No package matching 'jq' found available, installed or updated", "rc": 126, "results": ["No package matching 'jq' found available, installed or updated"]}
```

**Comment by pixiake** [comment]
@liangyuanpeng 是用的自己的yum源吗？官方的yum源应该是有jq的

可以在kubesphere/roles/prepare/nodes/tasks/main.yaml中注释掉安装jq的相关tasks
