### ISSUE TITLE
Can devops support buildx multi-platform image building?

### ISSUE THREAD

**Issue by 0xdigiscore** [kubesphere/kubesphere#5915]
* kubesphere version: v3.3.2
* k8s version: aws eks v1.23

We are using KubeSphere in a Kubernetes cluster which consists of a mixture of x86 and arm64 nodes. Currently, when using the DevOps flow, we are facing an issue where we cannot utilize Docker's buildx feature to build multi-platform images (both for x86 and arm64 architectures).

This capability is quite crucial for us as it helps ensure our applications run seamlessly on all node types present in our cluster.

What we tried:
We attempted to incorporate buildx within our CI/CD process manually, but faced various challenges that made it unsuitable as a long-term solution.

Feature Request:
Would it be possible for KubeSphere to incorporate native support or provide guidelines on how to seamlessly integrate buildx for multi-platform image building within the DevOps flow?

Having such a feature or guideline would greatly benefit organizations like ours that operate on mixed-architecture clusters.

Thank you for considering this request. We appreciate the hard work you all put into making KubeSphere a valuable tool for the Kubernetes community.

**Comment by wwt164888** [comment]
大佬是实现了吗
