### ISSUE TITLE
Avoid deploy on control plane nodes

### ISSUE THREAD

**Issue by rfarajro** [kubesphere/kubesphere#5917]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**What's your question**
 How can deploy kubesphere on existing k8s cluster and avoid pods run on control plane nodes?

**Environment: OS & Hardware Information**
Kubernetes v1.23.7

**Error logs or message (Attach logs or screenshot)**

**Installer Version**
3.4

**Comment by weiliang-ms** [comment]
1. Set `taint`

```
$ kubectl taint node <your control plane node name> key=value:NoSchedule
```

2. Install `kubesphere` with `ks-installer`.

```
$ kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.4.0/kubesphere-installer.yaml
$ kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.4.0/cluster-configuration.yaml
```
