### ISSUE TITLE
node-exporter Abnormal operation

### ISSUE THREAD

**Issue by xzplays** [kubesphere/kubesphere#5918]
**Describe the Bug**
cpu memory Incorrect measurement data

![20230914163359](https://github.com/kubesphere/kubesphere/assets/19684023/30e22738-c62d-4aaf-b806-5d3c33e7eef2)
![20230914163441](https://github.com/kubesphere/kubesphere/assets/19684023/12bb80e9-fbac-40e2-861e-017ed05f1f3c)
![20230914163619](https://github.com/kubesphere/kubesphere/assets/19684023/455a296e-f31c-45c6-b43e-b8abda4e5ac5)
![20230914163645](https://github.com/kubesphere/kubesphere/assets/19684023/b69802c4-e9d2-4a5e-95e2-6aa3dd21badc)

**Versions Used**
KubeSphere:3.3.2-3.4.0
Kubernetes:1.21.0

**Environment**
CentOS 7.9 / 1 masters:  16cpu/12g; 2 nodes: 16cpu/12g

**How To Reproduce**
default install

**Expected behavior**

Pod has no errors and the collected data display is abnormal

**Comment by VioZhang** [comment]
Node 2 CPU shows 0. /cc @kubesphere/sig-console @kubesphere/sig-observability

**Comment by frezes** [comment]
If you compare  kubernetes dashboard with kubesphere console, you'll see that the diagrams in kubernetes dashboard are just a demonstration of the CPU/Memory requests/limits of the Pod in place; kubesphere not only contains the requests/limits display, but also contains the node's actual resource usage display.

/cc @xzplays

**Comment by frezes** [comment]
Another problem is that the cpu/ memory of some nodes does not have data. You can refer to  [forum](https://ask.kubesphere.io/forum/d/9212-node-exporterprometheusdown/10) to check
