### ISSUE TITLE
log-collection can  not available 

### ISSUE THREAD

**Issue by jdjn12345** [kubesphere/kubesphere#5926]
<!--
You don't need to remove this comment section, it's invisible on the issues page.

![图片](https://github.com/kubesphere/kubesphere/assets/99314567/85ea2b66-1aa6-4280-92d5-bdfd3358acae)

The log receiver function here is not available

After clicking, the front page will appear white

**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

![图片](https://github.com/kubesphere/kubesphere/assets/99314567/9fc9e4fe-c6de-4b9f-881c-5e9784b99d51)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.9 masters:  16cpu/128g; 3 nodes: 12cpu/96g

![图片](https://github.com/kubesphere/kubesphere/assets/99314567/d5a99bcd-1f79-428d-a876-2a17eb91a72f)

**Comment by jdjn12345** [comment]
![图片](https://github.com/kubesphere/kubesphere/assets/99314567/c85d11c3-023c-480e-9225-c955dc3a79a8)
 After clicking, the page will appear white 
![图片](https://github.com/kubesphere/kubesphere/assets/99314567/d8de07bf-19ff-4e07-adb4-f7ed62e8ae44)
master 16c 128g node 12c 96g
![图片](https://github.com/kubesphere/kubesphere/assets/99314567/a0162810-f4b0-4498-9947-0dde35502128)

**Comment by wanjunlei** [comment]
https://github.com/kubesphere/console/issues/4176

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/a6c73cc6-d499-4d95-ac0d-02f5b2612a18)


![Image](https://github.com/kubesphere/kubesphere/assets/18654693/f0731f55-7bfd-4a09-91c4-56410e15ec7d)
