### ISSUE TITLE
3.4.0 Enabling Devops report:namespaces "kubesphere-devops-worker" not found

### ISSUE THREAD

**Issue by chinapanpan** [kubesphere/kubesphere#5928]
**Describe the Bug**
when enabling the devpos in kubeshpere 3.4.0,  it failed and report error:namespaces "kubesphere-devops-worker" not found
For UI issues please also add a screenshot that shows the issue.
<img width="773" alt="image" src="https://github.com/kubesphere/kubesphere/assets/97090623/4e0a0140-ee33-4774-a85e-1d4c43e251bc">
![image](https://github.com/kubesphere/kubesphere/assets/97090623/a858b5f7-dc95-448b-9088-bccad391e4e5)

**Versions Used**
KubeSphere:3.4.0
Kubernetes: (If KubeSphere installer used, you can skip this)
aws EKS 1.26

**Environment**
How many nodes and their hardware configuration:
2 work node:  8C32GB Amazon linux2
For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. install aws eks 1.26
2. install the kubesphere 3.4.0 on EKS
3. Enable Devops through editing the CRD :ks-installer
4. found the error shown above

**Expected behavior**
devops can be enabled successfully

**Comment by yudong2015** [comment]
Yes, this is related to #5858 , and that caused by the DevOps upgrade failed.

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/fdc63557-6539-4b9e-b22a-73dbe68938ab)
