### ISSUE TITLE
kubephere console需要登录很多次才能登录上去

### ISSUE THREAD

**Issue by yisampi** [kubesphere/kubesphere#5934]
kubesphere：3.4.0
kubernetes：v1.23.10

kubesphere console pod报错信息如下

  <-- POST /login 2023/10/09T15:26:25.868
  --> POST /login 302 141ms 83b 2023/10/09T15:26:26.009
  <-- GET /clusters/default/overview 2023/10/09T15:26:26.051
Unauthorized Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: true,
      _transformState: [Object],
      [Symbol(kCapture)]: false
    },
    disturbed: true,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'http://ks-apiserver/api/v1/namespaces/kubesphere-system/configmaps/kubesphere-config',
    status: 401,
    statusText: 'Unauthorized',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
} false
{
  code: 401,
  kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message: 'Unauthorized: jwt: token used before issued, iat:2023-10-09 15:26:50 +0800 CST, now:2023-10-09 15:26:26.053187641 +0800 CST m=+449555.437871677',
  reason: 'Unauthorized',
  statusText: 'Unauthorized'
}
Unauthorized Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: true,
      _transformState: [Object],
      [Symbol(kCapture)]: false
    },
    disturbed: true,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'http://ks-apiserver/kapis/iam.kubesphere.io/v1alpha2/users/admin',
    status: 401,
    statusText: 'Unauthorized',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
} false
{
  code: 401,
  kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message: 'Unauthorized: jwt: token used before issued, iat:2023-10-09 15:26:50 +0800 CST, now:2023-10-09 15:26:26.067528479 +0800 CST m=+449555.452212539',
  reason: 'Unauthorized',
  statusText: 'Unauthorized'
}
  --> GET /clusters/default/overview 302 18ms 113b 2023/10/09T15:26:26.069
Unauthorized Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: true,
      _transformState: [Object],
      [Symbol(kCapture)]: false
    },
    disturbed: true,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'http://ks-apiserver/kapis/config.kubesphere.io/v1alpha2/configs/gpu/kinds',
    status: 401,
    statusText: 'Unauthorized',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
} false
  <-- GET /login?referer=/clusters/default/overview 2023/10/09T15:26:26.112
  --> GET /login?referer=/clusters/default/overview 200 6ms 17.79kb 2023/10/09T15:26:26.118
  <-- GET /login?referer=/clusters/default/overview 2023/10/09T15:26:26.189
  --> GET /login?referer=/clusters/default/overview 200 4ms 17.79kb 2023/10/09T15:26:26.193

**Comment by wansir** [comment]
@yisampi 

```
Unauthorized: jwt: token used before issued, iat:2023-10-09 15:26:50 +0800 CST, now:2023-10-09
```

节点时间不同步，配置一下 ntp 吧

**Comment by yisampi** [comment]
> @yisampi
> 
> ```
> Unauthorized: jwt: token used before issued, iat:2023-10-09 15:26:50 +0800 CST, now:2023-10-09
> ```
> 
> 节点时间不同步，配置一下 ntp 吧

谢谢
