### ISSUE TITLE
The project gateway has been created but the project gateway cannot be queried in the cluster gateway settings

### ISSUE THREAD

**Issue by hongzhouzi** [kubesphere/kubesphere#5942]
**Describe the Bug**
The project gateway has been created but the project gateway cannot be queried in the cluster gateway settings.
This is caused by the addition of `kubesphere.io/gateway-type` label in the cluster gateway settings.

<img width="1250" alt="image" src="https://github.com/kubesphere/kubesphere/assets/36416216/ed0c5d6f-961d-49aa-9a8a-13bee1291fbc">

**Versions Used**
KubeSphere: v3.4.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Comment by harrisonliu5** [comment]
It is the same as https://github.com/kubesphere/kubesphere/issues/5843

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/85a55d3a-5fd2-46d9-90eb-6fb6a6040e6f)
