### ISSUE TITLE
企业空间项目中应用负载应用选择创建模板应用选择应用模板仓库没反应

### ISSUE THREAD

**Issue by openg123** [kubesphere/kubesphere#5983]
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by wuyh** [comment]
请问 问题解决了吗？
