### ISSUE TITLE
S2I构建镜像时，怎么指定代码分支

### ISSUE THREAD

**Issue by zturning** [kubesphere/kubesphere#599]
只有一个代码地址的输入，例如我输入的是：https://github.com/zturning/spring-boot-demo.git
请求怎么指定代码分支？

**Comment by lilinlinlin** [comment]
参考文档，其中第四点   https://kubesphere.io/docs/advanced-v2.0/zh-CN/quick-start/devops-online/

**Comment by runzexia** [comment]
@soulseen

**Comment by soulseen** [comment]
目前还不支持，切换分支和commitId的功能会在下个版本2.1.0发布

**Comment by soulseen** [comment]
@zturning
