### ISSUE TITLE
关于节点调度

### ISSUE THREAD

**Issue by DustFinger001** [kubesphere/kubesphere#601]
kubesphere 在安装时可以将几个 node 节点进行污点操作，或者让kubesphere服务不在特定的节点运行的办法吗？
我们的环境有几个节点会在加入集群时搭载一些很占用资源的服务（大概1核2G/每个服务）。同时希望能精确的控制节点能搭载的服务数量，所以不希望节点被调度到其他服务（例如 kubesphere自带服务）

还有一个问题，安装好之后，我想要添加节点，在kubesphere环境下可以使用kubeadm 命令加入么？如可以，加入的这个节点会不会脱离 kubesphere 环境（监控、日志等）的管理？

**Comment by lilinlinlin** [comment]
1、第一个问题，kubesphere自带服务一般不会调度到别的node节点上，但比如监控和日志一些插件会在node上部署，这也是必要的。
2、第二个问题，有脚本添加节点，只需要添加计算节点IP即可很方便的，也有文档说明。

**Comment by DustFinger001** [comment]
@lilinlinlin 第一个问题我可以通过安装好之后再加这些特定节点搞定； 
第二个问题之所以需要使用 kubeadm 而不是 kubesphare 自带add 脚本是因为我们添加和删除节点的操作比较频繁，需要自动化逻辑，并且之前已经有基于 kubeadm 的实现，所以想 使用kubeadm 添加。

**Comment by lilinlinlin** [comment]
如果是那样的话，监控和日志采集相关插件没有在新加的node上部署了

**Comment by pixiake** [comment]
@DustFinger001 如果镜像里已经有docker和k8s一些组件的话可以直接用kubeadm添加节点，master上执行kubeadm token create --print-join-command生成添加命令，新节点上执行即可。

**Comment by DustFinger001** [comment]
@pixiake 我看kubesphere 的k8s 环境使用镜像是 qingyun的repo ，这个是否配置kubeadm 镜像源即可，添加的主机在加入kubesphere之前是否还需要做其他相关配置？

**Comment by pixiake** [comment]
是的  把swap关掉（swapoff -a）   可以对比下其它节点的kubelet配置

**Comment by DustFinger001** [comment]
我加入节点后 新节点的 calico-node 报错 
![image](https://user-images.githubusercontent.com/16345979/61843967-5ab8c580-aed0-11e9-8988-c87a9052b6c5.png)

**Comment by lilinlinlin** [comment]
@DustFinger001  cni需要单独安装，也可以从其他机器拷贝过来试下。

**Comment by DustFinger001** [comment]
@lilinlinlin 怎么单独安装？ 我把其他节点的 /opt/cni/bin/ 二进制文件都拷贝过来了，ipvsadm 也安装了，还是一样报 Unable to update cni config: No networks found in /etc/cni/net.d

**Comment by lilinlinlin** [comment]
https://lilinlinlin.github.io/2019/07/28/k8s1-15%E5%AE%89%E8%A3%85/#more
 可以看下这个文章，kubeadm join之前需要安装cni插件

**Comment by lilinlinlin** [comment]
@DustFinger001

**Comment by DustFinger001** [comment]
这个问题解决了，需要拷贝其他节点的证书文件conflist 文件修改为当前节点的信息，然后还需要在join后配置 kubeconf 路径。
现在有个疑问：是否其他机器上的证书文件都是由etcd生成并统一分发的（内容都是相同？）
ps：我看安装脚本里的逻辑，应该是在安装时生成，然后同步到各个节点。这个结论是否正确？

**Comment by lilinlinlin** [comment]
etcd存数据的，证书是别的方式生成的。配置文件和当前节点是有关系的。结论是对的。

**Comment by DustFinger001** [comment]
@lilinlinlin 关于节点加入集群，发现一个bug，加入的节点 dns 不正确，需要手动将 节点的配置文件 /var/lib/kubelet/config.yaml 的dns 手动改为正确的集群dns。
我安装的环境集群dns 为 10.233.0.3 但kubeadm join加入的节点dns 为 10.233.0.10

**Comment by lilinlinlin** [comment]
所有添加计算节点初始化时，需要统一各种配置，如：上面提到的kubelet的配置。

**Comment by zryfish** [comment]
close due to inactivity
