### ISSUE TITLE
How to configure the service on ui to specify a port range instead of a port

### ISSUE THREAD

**Issue by iwanlebron** [kubesphere/kubesphere#6016]
How to configure the service on ui to specify a port range instead of a port? I need to specify a port range of 30000-35000.
<img width="1144" alt="image" src="https://github.com/kubesphere/kubesphere/assets/105045937/3c37d784-ee7f-40dc-9aa2-bd0fac70ffcf">

**Comment by iwanlebron** [comment]
stream services require a port range for push and pull streams

**Comment by wansir** [comment]
It's not supported now, for more details https://github.com/kubernetes/kubernetes/issues/23864
