### ISSUE TITLE
After uninstalling the kubeedge component according to the documentation and reinstalling kubeedge, edge nodes appear on the web page. Through heml list -A, it is found that kubeedge is not installed.

### ISSUE THREAD

**Issue by lrs-960** [kubesphere/kubesphere#6033]
**Describe the Bug**

After uninstalling the kubeedge component according to the documentation and reinstalling kubeedge, edge nodes appear on the web page. Through heml list -A, it is found that kubeedge is not installed.

**Versions Used**
KubeSphere:3.4.1
Kubernetes: (v1.26.5)

**How To Reproduce**
1. Modify ClusterConfiguration ks-installer to close edgeruntime and kubeedge
2. Execute helm uninstall cloudcore -n kubeedge
3. Execute kubectl delete ns kubeedge
4. Restart edgeruntime and kubeedge in ClusterConfiguration

**Comment by yeqiugt** [comment]
Hi, I met the same error, how did you resolve it ? Thank very much.

**Comment by cl2017** [comment]
I also encountered this problem and have already solved it. Here is the solution:
1. Modify the `ClusterConfiguration` configMap, change the values of `kubeedge.enabled` and `edgeruntime.enabled` from true to false
2. Execute `helm uninstall cloudcore -n kubeedge`
3. Execute `kubectl delete ns kubeedge`
4. If the above still does not take effect, check the ClusterConfiguration `status.edgeruntime.status`. If the status is `enabled`, set it to `disabled`

After completing the above steps, kubeedge should be able to be reinstalled.
