### ISSUE TITLE
增加镜像搜索功能？

### ISSUE THREAD

**Issue by bowenliang123** [kubesphere/kubesphere#604]
部署中反复要输入完整的镜像名称，比如目前我用的是阿里云的镜像仓库，每次都要手动填写`仓库地址`+`镜像名称`+`镜像标签`，非常繁琐。

希望增加镜像搜索功能。

在选定仓库秘钥后，
1. 自动填写仓库地址，或者在秘钥的时候配置
2. 根据关键字搜索镜像
3. 列出镜像的标签，以供选择

目前的截图，输入相当繁琐：
![image](https://user-images.githubusercontent.com/1935105/62032440-389aac80-b21c-11e9-91d4-388d41862a10.png)

**Comment by zryfish** [comment]
这是一个很好的建议，我们这边看下怎么优化下

**Comment by bowenliang123** [comment]
在我设想中
1.先选仓库秘钥（否则不选就优先使用内置Harbor仓库），在仓库秘钥配置时候填入对应仓库地址。

2.然后用类似docker search命令的功能，来搜索指定仓库下的镜像
(https://docs.docker.com/engine/reference/commandline/search/)

3.进而使用仓库API列出镜像下的所有tag，以供选择 (https://stackoverflow.com/questions/28320134/how-to-list-all-tags-for-a-docker-image-on-a-remote-registry)

**Comment by soulseen** [comment]
@bowenliang123 第二步搜索指定仓库下的镜像是否需要优化
1. 当用户选择密钥后(不选默认dockerhub？)，可以在代码上做下处理，不需要填入registry地址。
2. 然后需要用户输入repo name(organization name)，dockerhub 是以用户名称作为repo名称，harbor可自定义。 local registry 可能镜像name就是repo名称，这部分会有多种情况，需要优化。
3. 然后搜索repo下的镜像。如果是local registry, 镜像name作为repo名称，则是搜索tag。
4. 进而搜索tag。

**Comment by soulseen** [comment]
在2.1中新增加了镜像搜索功能，

**Comment by soulseen** [comment]
可以体验下，欢迎提出建议。
/close
