### ISSUE TITLE
jenkins安装插件后，因当前jenkins版本低，导致插件由于缺少依赖无法加载，以至于流水线无法执行

### ISSUE THREAD

**Issue by wuqiang3424** [kubesphere/kubesphere#6052]
问题：jenkins安装插件后，因当前jenkins版本低，导致插件由于缺少依赖无法加载，以至于流水线无法执行
问题截图：
<img width="998" alt="image" src="https://github.com/kubesphere/kubesphere/assets/32158667/9e4ed78d-4a9f-4954-8dce-41f89f05f302">
说明：jenkins通过开启devops之后自动创建的
版本：Jenkins 2.319.3
问题说明：Dependency errors:

Jenkins build user vars plugin (1.9)
Update required: Branch API Plugin (2.6.2) to be updated to 2.1046.v0ca_37783ecc5 or higher
Jenkins (2.332.1) or higher required
Update required: Jenkins Mailer Plugin (414.vcc4c33714601) to be updated to 435.v79ef3972b_5c7 or higher
像这个报错意思是该插件需要jenkins版本为2.332.1，而当前是2.319.3导致插件无法正常使用，不仅如此，安装插件后之前的流水线功能都异常了

问：
1.是否可以升级jenkins版本，如果可以升级是手动升级还是在Kubesphere中有修改版本的地方呢
2.因为jenkins是由容器部署的，因此无法正常在jenkins web页面进行升级

**Comment by calvinyv** [comment]
to make this community more open to global users, pls use english to raise the issue, otherwise, pls raise ur question to local forum: https://ask.kubesphere.io/forum/, thx.
