### ISSUE TITLE
CPU and memory not collecting with own prometheus

### ISSUE THREAD

**Issue by sergey-ganchuk** [kubesphere/kubesphere#6053]
I'm using kubespere 3.4.1 with own prometheus.
Performed steps from article Bring Your Own Prometheus including creating resources but still can't see any statistics.
Like [Issue #5291](https://github.com/kubesphere/kubesphere/issues/5291) but I already created all prometheus resources.

**Versions Used**
KubeSphere: 3.4.1
Kubernetes: 1.28.2

**Environment**
Multicluster installation.
On host cluster I'm using embedded to kubesphere prometheus and I see statistics.
On member cluster I can only see number of pods and disk
![image](https://github.com/kubesphere/kubesphere/assets/132432020/b0ed024c-ab85-4920-b32e-67c0fc9833a8)

**How To Reproduce**
Open cluster overview page

**Expected behavior**
I should see statistics.

**Comment by maaiika** [comment]
The same issue is that Kubersphere has hard-coded the relevant Prometheus performance query statements. Should it be considered editable?
https://github.com/kubesphere/kubesphere/blob/18e089ff5feaad54891ff4cae3a726bf9810e997/pkg/simple/client/monitoring/prometheus/promql_meter.go#L28-L1102

**Comment by sergey-ganchuk** [comment]
Can we make own prometheus to expose those metrics? 
I'm not so familiar with it.

**Comment by maaiika** [comment]
> Can we make own prometheus to expose those metrics? I'm not so familiar with it.
You may need to install lower versions of node-exporter and kube-stete-metrics 。

**Comment by satriogosil** [comment]
Hi, i have the same issue here? so what's the solution?

**Comment by sergey-ganchuk** [comment]
> Hi, i have the same issue here? so what's the solution?

Actually, I just solved it.
My problem was that prometheus was depolyed via helm with following setting:

prometheus:
  enabled: true
  prometheusSpec:
    **ruleSelectorNilUsesHelmValues**: **true**
    
So prometheus doesn't load custom rules.
