### ISSUE TITLE
偶现service tcp端口无法访问，使用nodeport访问正常。需编辑服务，重新指定tcp协议、端口后恢复正常

### ISSUE THREAD

**Issue by xjh1994** [kubesphere/kubesphere#6060]
**Describe the Bug**
生产系统中突然pod访问不了mongodb了，检查了一下发现使用nodeport可以访问，用service+容器端口访问不通，期间没有改过任何东西。第二次出现了，之前一次是rocketmq访问不了。点了编辑服务，发现表单中协议是http，于是重新指定tcp协议、端口后恢复正常。
不知道是什么情况触发了这个问题。半年遇到两次。
![image](https://github.com/kubesphere/kubesphere/assets/3397116/f3b3e25c-910d-41e2-b2d4-5a60a7988582)

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: 3.3.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:
Ubuntu 18.04 / 1 master: 8cpu/32g; 2nodes: 8cpu/32g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by calvinyv** [comment]
For questions in Chinese, pls post it in Chinese [forum](https://ask.kubesphere.io/forum/), otherwise pls ask in English, thanks for understanding.
sorry, but I need to temporarily close this issue until its title and content are changed to English.
