### ISSUE TITLE
Slack and Support Links do not work

### ISSUE THREAD

**Issue by roadfox** [kubesphere/kubesphere#6066]
**Describe the Bug**
The Slack invite Links in Kubesphere Console UI and here in the Readme.md are outdated, only the one on kubesphere.io is working.

Also the link to support in the Readme.md [KubeSphere Online Support](https://kubesphere.cloud/en/ticket/) ends on a 404 Page

**Comment by faweizhao26** [comment]
Thanks. We will update the Readme.md. But the Slack invite Links in Kubesphere Console UI only be updated on the next release.

The reason of second problem is that we have stop this support. We will delete it in the Readme.md
