### ISSUE TITLE
 x509: certificate is valid for 10.233.0.1, 172.20.0.251, 

### ISSUE THREAD

**Issue by lisqorz** [kubesphere/kubesphere#6118]
step by step here
https://www.kubesphere.io/zh/docs/v3.4/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs/

**Describe the Bug**
<img width="967" alt="image" src="https://github.com/kubesphere/kubesphere/assets/42998845/940a21de-87df-40b8-a17d-a18814bab4b7">

Get "https://116.62.163.2:6443/api/v1/namespaces/kubekey-system": x509: certificate is valid for 10.233.0.1, 172.20.0.251, 127.0.0.1, not 116.62.163.2

**Versions Used**
KubeSphere:3.4.1
Kubernetes:  v1.22.12

**Environment**
How many nodes and their hardware configuration:
Alibaba Cloud Linux 2.1903 LTS 64位 等保2.0三级版 4cpu/8g 

**Steps to reproduce the behavior: **
1. ./kk create cluster -f config-sample.yaml

**Expected behavior**
16:46:10 CST [AutoRenewCertsModule] Generate k8s certs renew script
16:46:10 CST success: [node3]
16:46:10 CST [AutoRenewCertsModule] Generate k8s certs renew service
16:46:10 CST success: [node3]
16:46:10 CST [AutoRenewCertsModule] Generate k8s certs renew timer
16:46:10 CST success: [node3]
16:46:10 CST [AutoRenewCertsModule] Enable k8s certs renew service
16:46:10 CST success: [node3]
16:46:10 CST [SaveKubeConfigModule] Save kube config as a configmap
16:46:10 CST message: [LocalHost]
Get "https://116.62.163.2:6443/api/v1/namespaces/kubekey-system": x509: certificate is valid for 10.233.0.1, 172.20.0.251, 127.0.0.1, not 116.62.163.2
16:46:10 CST retry: [LocalHost]
16:46:15 CST message: [LocalHost]
Get "https://116.62.163.2:6443/api/v1/namespaces/kubekey-system": x509: certificate is valid for 10.233.0.1, 172.20.0.251, 127.0.0.1, not 116.62.163.2
16:46:15 CST retry: [LocalHost]
16:46:20 CST message: [LocalHost]
Get "https://116.62.163.2:6443/api/v1/namespaces/kubekey-system": x509: certificate is valid for 10.233.0.1, 172.20.0.251, 127.0.0.1, not 116.62.163.2
16:46:20 CST retry: [LocalHost]
16:46:25 CST message: [LocalHost]
Get "https://116.62.163.2:6443/api/v1/namespaces/kubekey-system": x509: certificate is valid for 10.233.0.1, 172.20.0.251, 127.0.0.1, not 116.62.163.2
16:46:25 CST retry: [LocalHost]
16:46:30 CST message: [LocalHost]
Get "https://116.62.163.2:6443/api/v1/namespaces/kubekey-system": x509: certificate is valid for 10.233.0.1, 172.20.0.251, 127.0.0.1, not 116.62.163.2
16:46:30 CST failed: [LocalHost]
error: Pipeline[CreateClusterPipeline] execute failed: Module[SaveKubeConfigModule] exec failed:
failed: [LocalHost] [SaveKubeConfig] exec failed after 5 retries: Get "https://116.62.163.2:6443/api/v1/namespaces/kubekey-system": x509: certificate is valid for 10.233.0.1, 172.20.0.251, 127.0.0.1, not 116.62.163.2

**Comment by lisqorz** [comment]
https://www.kubesphere.io/zh/docs/v3.4/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs/
按照这个教程安装的，执行完 ./kk create cluster -f config-sample.yaml 之后报这个错误

**Comment by ygqygq2** [comment]
你负载均衡那把 SLB IP写进去就行了，别删除它的那个域名。它内部就是使用这个域名绑定你的 SLB IP 的
