### ISSUE TITLE
monitoring dashboard import, when rkClient get object ,judege err

### ISSUE THREAD

**Issue by fengpengyun** [kubesphere/kubesphere#6145]
Describe the Bug
1、monitoring dashboard import, when rkClient get object ,judege err
`objKey := runtimeclient.ObjectKey{
			Namespace: namespace,
			Name:      dashboard.Name,
		}

		err = h.rtClient.Get(ctx, objKey, &dashboard)

		if err == nil {
			api.HandleBadRequest(resp, nil, errors.New("dashboards with the same name already exists."))
			return
		}`

Versions Used
KubeSphere: 3.4.1
Kubernetes: 1.26.0

Expected behavior：
This judgment is incorrect, it should be judged that it does not equal

**Comment by frezes** [comment]
```go
	err = h.rtClient.Get(ctx, objKey, &dashboard)

	if err == nil {
		api.HandleBadRequest(resp, nil, errors.New("dashboards with the same name already exists."))
		return
	}
```

If error is empty, an object with the same name already exists and is not expected to be overwritten.
