### ISSUE TITLE
devops工程的流水线编辑不能用鼠标滚轮缩放

### ISSUE THREAD

**Issue by wanghonglei5181** [kubesphere/kubesphere#615]

**Comment by minghaoye** [comment]
win10 
chrome 76.0.38.09.87 64bit
其它浏览器也没有复现，可以重装一下chrome试一下

**Comment by minghaoye** [comment]
抱歉，我们又重新测试了一些case，复现了这个问题。2.1我们会修复。
可以先用 firefox 体验
