### ISSUE TITLE
devops流水线编辑，不能提示具体错误

### ISSUE THREAD

**Issue by wanghonglei5181** [kubesphere/kubesphere#616]
在编辑流水线时，点击保存后仅有提示的有错误，但是没现实哪里有错误。

**Comment by zryfish** [comment]
能附上重现步骤，环境信息，和错误截图么

**Comment by runzexia** [comment]
这个问题已经发现前端同学在修复了
@minghaoye

**Comment by minghaoye** [comment]
已和wanghonglei5181 沟通了，需要在右侧 agent 中输入 label 参数，这个 2.1 我们优化一下
