### ISSUE TITLE
KubeSphere 2.0.2  Source-to-image 模式 一直转圈等待

### ISSUE THREAD

**Issue by aidocker** [kubesphere/kubesphere#618]
更换了仓库地址 https://gitee.com/aidocker/devops-java-sample.git  依然不行
没有错误日志输出，抱歉

**Comment by aidocker** [comment]
![s2i](https://user-images.githubusercontent.com/17754488/62273277-bb677580-b46f-11e9-8d56-e97dc09853dd.png)

**Comment by aidocker** [comment]
![fail](https://user-images.githubusercontent.com/17754488/62284795-f0cb8d80-b486-11e9-8a24-066490bb902e.png)
问题找到了，请关闭吧

**Comment by zryfish** [comment]
一般这种情况是创建deployment的时候指定了requests，k8s会预留资源，即使实际没有用到那么多。可以通过 kubectl top node 和 kubectl -n [namespace] top pod 来查看资源的使用情况，降低pod的requests值
