### ISSUE TITLE
KubesphereV4.1.1 -- version display error

### ISSUE THREAD

**Issue by whoslele** [kubesphere/kubesphere#6181]
installa successful , the cluster overview version shows v3.0.0, which should actually be v4.1.1

**Comment by wansir** [comment]
Could you provide more information, such as useful screenshots or the pod status? Please execute `helm -n kubesphere-system history ks-core` or `kubectl -n kubesphere-system get po` to check if KubeSphere  is deployed correctly. Version `v3.0.0` should not be appearing, as we currently do not support upgrading from 3.x to 4.x.

The following version information is expected:

![image](https://github.com/user-attachments/assets/99a59c4b-848e-49b9-ae75-b3d4f8d6c098)

**Comment by GitHubLoveKe** [comment]
I'm having the same issue
![图片](https://github.com/user-attachments/assets/42f313d5-57d3-48bf-8c77-e288771382be)
![图片](https://github.com/user-attachments/assets/b769f48f-16ea-4783-8f99-e0bd72d43337)
![图片](https://github.com/user-attachments/assets/db62438a-f655-4291-ae23-19d9e519fe80)

**Comment by whoslele** [comment]
![1726711726515](https://github.com/user-attachments/assets/b4c0a169-b3c9-4357-b42b-0aba7679db6e)

**Comment by wansir** [comment]
> ![1726711726515](https://private-user-images.githubusercontent.com/110213236/368815451-b4c0a169-b3c9-4357-b42b-0aba7679db6e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MTM4NjEsIm5iZiI6MTcyNjcxMzU2MSwicGF0aCI6Ii8xMTAyMTMyMzYvMzY4ODE1NDUxLWI0YzBhMTY5LWIzYzktNDM1Ny1iNDJiLTBhYmE3Njc5ZGI2ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQwMjM5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmY4OThkOWYwYzllNWI4N2U1NTQ2NjczNDc1OTc3YmE0MTE2N2EwYzI5MzgwODIyMzRmMWIyNDM4MDI5YTBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6D5j_x9J2ZDf-RDTw3xENRxMdEOQevph5GXUarEq4js)

We previously made adjustments to the Docker image build action on GitHub. Please try pulling the latest Docker image, the issues you're encountering can be resolved.

**Comment by GitHubLoveKe** [comment]
use kubespheredev? or build by self ?
I don't see an update in kubesphereio
![图片](https://github.com/user-attachments/assets/c9a20b7f-eebd-4f16-8000-3a79a8323f68)

**Comment by wansir** [comment]
> use kubespheredev? or build by self ? I don't see an update in kubesphereio ![图片](https://private-user-images.githubusercontent.com/17232388/368837775-c9a20b7f-eebd-4f16-8000-3a79a8323f68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTg0ODYsIm5iZiI6MTcyNjc5ODE4NiwicGF0aCI6Ii8xNzIzMjM4OC8zNjg4Mzc3NzUtYzlhMjBiN2YtZWViZC00ZjE2LTgwMDAtM2E3OWE4MzIzZjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDAyMDk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYjAzYTc3M2YzYzJkMDU1MmYzYWM5OTA1ZjQ2MTMwZmJmZWEzZGMzMzcxZjI1ODNjNWJjMjYzZDNiNTVkYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6XyeRKCa2KHIcHupzYl4UmDsCVV2b5Qvyhny93_6mV0)

We plan to use `swr.cn-southwest-2.myhuaweicloud.com/ks` instead of `registry.cn-beijing.aliyuncs.com/kubesphereio` to facilitate image pulling for users in China. You can specify this during the installation of KubeSphere with the following configuration:

```
--set global.imageRegistry=swr.cn-southwest-2.myhuaweicloud.com/ks
```

In kubespheredev, only pre release images will be uploaded.

**Comment by GitHubLoveKe** [comment]
> > 使用 KubeSphereDev？还是自行构建 ？我在 kubesphereio 中没有看到更新  ![图片](https://private-user-images.githubusercontent.com/17232388/368837775-c9a20b7f-eebd-4f16-8000-3a79a8323f68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3OTg0ODYsIm5iZiI6MTcyNjc5ODE4NiwicGF0aCI6Ii8xNzIzMjM4OC8zNjg4Mzc3NzUtYzlhMjBiN2YtZWViZC00ZjE2LTgwMDAtM2E3OWE4MzIzZjY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDAyMDk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzYjAzYTc3M2YzYzJkMDU1MmYzYWM5OTA1ZjQ2MTMwZmJmZWEzZGMzMzcxZjI1ODNjNWJjMjYzZDNiNTVkYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6XyeRKCa2KHIcHupzYl4UmDsCVV2b5Qvyhny93_6mV0)
> 
> 我们计划使用 `swr.cn-southwest-2.myhuaweicloud.com/ks` 而不是 `registry.cn-beijing.aliyuncs.com/kubesphereio` 方便中国用户拉取镜像。您可以在安装 KubeSphere 时使用以下配置指定此项：
> 
> ```
> --set global.imageRegistry=swr.cn-southwest-2.myhuaweicloud.com/ks
> ```
> 
> 在 kubespheredev 中，只会上传预发布镜像。

it works

**Comment by whoslele** [comment]
3q，
The issue has been resolved, it is suggest to update to the kubesphere.io docs；
