### ISSUE TITLE
自制应用入口之前版本是存在的，现在需要配置吗

### ISSUE THREAD

**Issue by Gebitily7** [kubesphere/kubesphere#6186]
![image](https://github.com/user-attachments/assets/43423d62-1097-4233-bc33-f95e89d705a6)

**Comment by zhou1203** [comment]
KubeSphere的版本号是什么？

**Comment by zhou1203** [comment]
首先需要在应用市场中安装`KubeSphere 服务网格`，安装成功后，在项目概览页的侧边栏会出现 `服务网格` 按钮，下面有自制应用。
![企业微信截图_72a4fc1a-d27d-40a2-b6d9-204f9773bc83](https://github.com/user-attachments/assets/3d730dcd-2be6-479d-bb75-169cfd6677ad)

**Comment by zhou1203** [comment]
应用商店的应用功能和服务网格的自制应用功能的界面有些错误需要调整

## 应用商店
![1726802657071](https://github.com/user-attachments/assets/b7fe70f8-32dd-4f0f-a216-38bdea1869c5)

## 服务网格
![1726802428490](https://github.com/user-attachments/assets/b74e6f26-53ce-4cb9-aa3d-81e4a93c2386)

/cc @donniean

**Comment by Gebitily7** [comment]
> KubeSphere的版本号是什么？

v4.1.1

**Comment by Gebitily7** [comment]
> 首先需要在应用市场中安装`KubeSphere 服务网格`，安装成功后，在项目概览页的侧边栏会出现 `服务网格` 按钮，下面有自制应用。 ![企业微信截图_72a4fc1a-d27d-40a2-b6d9-204f9773bc83](https://private-user-images.githubusercontent.com/34303854/369247341-3d730dcd-2be6-479d-bb75-169cfd6677ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MDc3MzEsIm5iZiI6MTcyNjgwNzQzMSwicGF0aCI6Ii8zNDMwMzg1NC8zNjkyNDczNDEtM2Q3MzBkY2QtMmJlNi00NzlkLWJiNzUtMTY5Y2ZkNjY3N2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDA0NDM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZGQ3NTE2OTY5MWIyYjM4YmRkNWVmOTRlMGQ1MDFiY2U0MTY1MmFjY2Y3MWZkMWZmY2Q0NTdhODcxNzUzMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-A7ozCRkvFb0mVjV2xBXKj_TcX_PXDoGdJTurATfo_g)

![image](https://github.com/user-attachments/assets/4f50688a-b52d-4852-b228-a46522f80742)
我的应用商店打开没有任何内容，是需要开启吗

**Comment by inksnw** [comment]
应用商店默认是不带应用的, 可以通过手动上传chart包并提交审核, 在应用商店管理审核通过后, 就会出现在列表中, 或者配置helm repo同步应用

**Comment by Gebitily7** [comment]
> 应用商店默认是不带应用的, 可以通过手动上传chart包并提交审核, 在应用商店管理审核通过后, 就会出现在列表中, 或者配置helm repo同步应用

@inksnw 不好意思，我不是很明白在哪里上传chart包。

**Comment by inksnw** [comment]
> > 应用商店默认是不带应用的, 可以通过手动上传chart包并提交审核, 在应用商店管理审核通过后, 就会出现在列表中, 或者配置helm repo同步应用
> 
> @inksnw 不好意思，我想安装`KubeSphere 服务网格`从哪里上传chart包。

稍等下, 整理个说明发在论坛

**Comment by zhou1203** [comment]
> > 应用商店默认是不带应用的, 可以通过手动上传chart包并提交审核, 在应用商店管理审核通过后, 就会出现在列表中, 或者配置helm repo同步应用
> 
> @inksnw 不好意思，我想安装`KubeSphere 服务网格`从哪里上传chart包。

在扩展中心中就能找到 KubeSphere 服务网格，默认已经上传了

**Comment by Gebitily7** [comment]
> KubeSphere

@zhou1203 是还需要等待吗，现在我这里搜索不到
![image](https://github.com/user-attachments/assets/b73c3a33-a400-4c2c-b570-5ab486724053)

**Comment by Gebitily7** [comment]
> > > 应用商店默认是不带应用的, 可以通过手动上传chart包并提交审核, 在应用商店管理审核通过后, 就会出现在列表中, 或者配置helm repo同步应用
> > 
> > 
> > @inksnw 不好意思，我想安装`KubeSphere 服务网格`从哪里上传chart包。
> 
> 稍等下, 整理个说明发在论坛

@inksnw 你好，论坛发好踢我下，谢谢

**Comment by inksnw** [comment]
https://ask.kubesphere.io/forum/d/23922-kubesphere-411-ying-yong-shang-dian-pei-zhi-fang-fa
This document is only for how to configure the app store
