### ISSUE TITLE
Monitoring & Alerting & DevOps Unable to load

### ISSUE THREAD

**Issue by GitHubLoveKe** [kubesphere/kubesphere#6193]
kubesphere v4.1.1.1
Kubernetes v1.28.13

![图片](https://github.com/user-attachments/assets/a1795742-1b3b-4a96-86d4-844f1fb00f8f)

Monitoring & Alerting & DevOps has been installed
![图片](https://github.com/user-attachments/assets/1d5416bb-47a4-414a-a87f-4802cf2dd2d3)

![图片](https://github.com/user-attachments/assets/3500e97c-15c2-48af-a0b6-17b6b120d6cd)

![图片](https://github.com/user-attachments/assets/3987c517-2098-4cac-b263-87398a171c4d)

**Comment by GitHubLoveKe** [comment]
here is pods , i used imageRegistry: swr.cn-southwest-2.myhuaweicloud.com/ks
![图片](https://github.com/user-attachments/assets/be89c2fa-bff2-441c-9d47-1789f1cbe815)

**Comment by lishuyanla** [comment]
+1 DevOps Unable to load

**Comment by GitHubLoveKe** [comment]
I  replaced it with kubespheredev/ks-console:master ，Is it will update to relese v4.1.1 ?

**Comment by GitHubLoveKe** [comment]
> I replaced it with kubespheredev/ks-console:master ，Is it will update to relese v4.1.1 ?
In v3.4.1 has similar question, need build it by self to replace containers ,Will there be a stable or upgraded helm?

**Comment by GitHubLoveKe** [comment]
> +1 DevOps Unable to load
I pulled dev container, or use source code to build
![图片](https://github.com/user-attachments/assets/9f15fa99-a287-4ac1-914e-de38911934dd)

**Comment by GitHubLoveKe** [comment]
I saw v4.1.2 
The issue has been resolved ，
 I will close the issue
