### ISSUE TITLE
安装devops后，企业空间-》devops项目进入后白屏

### ISSUE THREAD

**Issue by wwt164888** [kubesphere/kubesphere#6205]
![image](https://github.com/user-attachments/assets/d98206dc-5d30-4952-8c56-40ccc2dc8476)

devops项目进入后白屏，查看网络连接提示跨域错误

**Comment by GitHubLoveKe** [comment]
v4.1.2 has been fixed

**Comment by wwt164888** [comment]
如何升级到4.1.2

**Comment by GitHubLoveKe** [comment]
helm upgrade --install -n kubesphere-system --create-namespace ks-core ./ks-core --set global.tag=v4.1.2 --set global.imageRegistry=swr.cn-southwest-2.myhuaweicloud.com/ks --debug --wait

**Comment by wwt164888** [comment]
history.go:56: [debug] getting history for release ks-core
Error: path "./ks-core" not found
helm.go:84: [debug] path "./ks-core" not found
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        helm.sh/helm/v3/pkg/action/install.go:745
main.newUpgradeCmd.func2
        helm.sh/helm/v3/cmd/helm/upgrade.go:165
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.0/command.go:1039
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:267
runtime.goexit
        runtime/asm_amd64.s:1650

**Comment by GitHubLoveKe** [comment]
> history.go:56: [debug] getting history for release ks-core Error: path "./ks-core" not found helm.go:84: [debug] path "./ks-core" not found helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart helm.sh/helm/v3/pkg/action/install.go:745 main.newUpgradeCmd.func2 helm.sh/helm/v3/cmd/helm/upgrade.go:165 github.com/spf13/cobra.(*Command).execute github.com/spf13/cobra@v1.8.0/command.go:983 github.com/spf13/cobra.(*Command).ExecuteC github.com/spf13/cobra@v1.8.0/command.go:1115 github.com/spf13/cobra.(*Command).Execute github.com/spf13/cobra@v1.8.0/command.go:1039 main.main helm.sh/helm/v3/cmd/helm/helm.go:83 runtime.main runtime/proc.go:267 runtime.goexit runtime/asm_amd64.s:1650

I has downloaded it 
helm upgrade --install -n kubesphere-system --create-namespace ks-core https://charts.kubesphere.io/main/ks-core-1.1.1.tgz --set global.tag=v4.1.2 --set global.imageRegistry=swr.cn-southwest-2.myhuaweicloud.com/ks --debug --wait

**Comment by GitHubLoveKe** [comment]
> > history.go:56: [debug] getting history for release ks-core Error: path "./ks-core" not found helm.go:84: [debug] path "./ks-core" not found helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart helm.sh/helm/v3/pkg/action/install.go:745 main.newUpgradeCmd.func2 helm.sh/helm/v3/cmd/helm/upgrade.go:165 github.com/spf13/cobra.(*Command).execute github.com/spf13/cobra@v1.8.0/command.go:983 github.com/spf13/cobra.(*Command).ExecuteC github.com/spf13/cobra@v1.8.0/command.go:1115 github.com/spf13/cobra.(*Command).Execute github.com/spf13/cobra@v1.8.0/command.go:1039 main.main helm.sh/helm/v3/cmd/helm/helm.go:83 runtime.main runtime/proc.go:267 runtime.goexit runtime/asm_amd64.s:1650
> 
> I has downloaded it helm upgrade --install -n kubesphere-system --create-namespace ks-core https://charts.kubesphere.io/main/ks-core-1.1.1.tgz --set global.tag=v4.1.2 --set global.imageRegistry=swr.cn-southwest-2.myhuaweicloud.com/ks --debug --wait

When I installed it, kubesphere/ks-console:v4.1.2 hadn't synced to swr.cn-southwest-2.myhuaweicloud.com/ks
you need pull & tag

**Comment by wwt164888** [comment]
swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/ks-console:v4.1.2  这个在仓库里竟然没有镜像

**Comment by GitHubLoveKe** [comment]
if you can access dockerhub, not need to use --set global.imageRegistry=swr.cn-southwest-2.myhuaweicloud.com/ks

**Comment by GitHubLoveKe** [comment]
> swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/ks-console:v4.1.2 这个在仓库里竟然没有镜像

https://github.com/kubesphere/kubesphere/issues/6205#issuecomment-2378543550

**Comment by wwt164888** [comment]
okay

**Comment by pixiake** [comment]
> swr.cn-southwest-2.myhuaweicloud.com/ks/kubesphere/ks-console:v4.1.2 这个在仓库里竟然没有镜像

You can try to it again.

**Comment by wwt164888** [comment]
有了
