### ISSUE TITLE
centos7.5 2.0.2离线安装失败

### ISSUE THREAD

**Issue by lujs678** [kubesphere/kubesphere#622]
centos 7.5 minimal版本
安装最新的离线版，在安装docker时候报错了
![捕获](https://user-images.githubusercontent.com/30866140/62360670-f212be00-b54b-11e9-8303-ba0aaf5f430f.PNG)

**Comment by pixiake** [comment]
vim k8s/inventory/local/hosts.ini     可以在第一行最后加上  ip={当前机器的ip} 这个参数试下

**Comment by lujs678** [comment]
还是不行，最后报一样的错误
![image](https://user-images.githubusercontent.com/30866140/62432084-2959b880-b760-11e9-8301-ae4d8b0aa8ce.png)

**Comment by pixiake** [comment]
@lujs678 第一行这样配试下，ip换成自己的，如果有网的话建议联网安装
ks-allinone ansible_connection=local ip=192.168.0.2

[local-registry]
ks-allinone

[kube-master]
ks-allinone

[etcd]
ks-allinone

[kube-node]
ks-allinone

[k8s-cluster:children]
kube-node
kube-master

**Comment by lujs678** [comment]
已解决
