### ISSUE TITLE
helm中判断k8s版本，云厂商版本特殊无法正确匹配

### ISSUE THREAD

**Issue by ftsxd** [kubesphere/kubesphere#6228]
ks-core包中apiVersion: {{ if semverCompare ">=1.21.0-0" .Capabilities.KubeVersion.Version }}batch/v1{{ else }}batch/v1beta1{{end}}是这样匹配的，但是腾讯tke的k8s版本是v1.30.0-tke.1这种格式，导致cronJob无法安装

**Comment by wansir** [comment]
The issue you encountered has been fixed in [this PR](https://github.com/kubesphere/kubesphere/pull/6221). We plan to release a new Helm chart.

**Comment by ftsxd** [comment]
在多集群的时候，也是，而且找的也不是最新的chart版本
<img width="1389" alt="image" src="https://github.com/user-attachments/assets/ce960789-13d0-4513-9bd1-d68bc7a9f1d0">

**Comment by wansir** [comment]
> 在多集群的时候，也是，而且找的也不是最新的chart版本 <img alt="image" width="1389" src="https://private-user-images.githubusercontent.com/52474411/381407265-ce960789-13d0-4513-9bd1-d68bc7a9f1d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjc4MDksIm5iZiI6MTczMDI2NzUwOSwicGF0aCI6Ii81MjQ3NDQxMS8zODE0MDcyNjUtY2U5NjA3ODktMTNkMC00NTEzLTliZDEtZDY4YmM3YTlmMWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA1NTE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZDBmNDMxYWU4MDkxOTg3MDZmMzY4YTAxYmRiYTZiNmQ4ZjJlMTljM2YzYjg3N2IzMjRmN2YzZjZlYjE3MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JE15Ggg-kySIWbmvxuxeNjFj5c6orFTak92uaykC6wA">

https://github.com/kubesphere/kubesphere/pull/6237

Add the following configuration when adding a member cluster.

```
ksExtensionRepository:
  enabled: false
```

**Comment by ftsxd** [comment]
> > 在多集群的时候，而且找到的也不是最新的图表版本<img alt="图像" width="1389" src="https://private-user-images.githubusercontent.com/52474411/381407265-ce960789-13d0-4513-9bd1-d68bc7a9f1d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNjc4MDksIm5iZiI6MTczMDI2NzUwOSwicGF0aCI6Ii81MjQ3NDQxMS8zODE0MDcyNjUtY2U5NjA3ODktMTNkMC00NTEzLTliZDEtZDY4YmM3YTlmMWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDA1NTE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZDBmNDMxYWU4MDkxOTg3MDZmMzY4YTAxYmRiYTZiNmQ4ZjJlMTljM2YzYjg3N2IzMjRmN2YzZjZlYjE3MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JE15Ggg-kySIWbmvxuxeNjFj5c6orFTak92uaykC6wA">
> 
> #6237
> 
> 添加成员供应时添加以下配置。
> 
> ```
> ksExtensionRepository:
>   enabled: false
> ```

报错"failed to sync workspacerolebinding for cluster" err="create worspaceRoleBinding system-workspace-admin at cluster silkworm-test failed" logger="controllers.workspacerolebinding" cluster="silkworm-test"
![image](https://github.com/user-attachments/assets/cf4983e0-89d8-4c99-aba1-7d6a055d40c2)

**Comment by wangycc** [comment]
Hi @wansir how soon will the latest version be released? Currently v4.1.2 is still unfixed

**Comment by wansir** [comment]
@wangycc Hi, the issue will be fixed in the upcoming v4.1.3 release. Stay tuned for the update! 😊

**Comment by guoguoguilai** [comment]
> [#6237](https://github.com/kubesphere/kubesphere/pull/6237)
> 
> Include the following configuration when adding a member cluster.
> 
> ```
> ksExtensionRepository:
>   enabled: false
> ```

我在添加eks集群的时候遇到了这个问题。请问是添加到经过处理后的eks kubeconfig里吗

**Comment by ftsxd** [comment]
> > [#6237](https://github.com/kubesphere/kubesphere/pull/6237)
> > 添加成员集群时包括以下配置。
> > ```
> > ksExtensionRepository:
> >   enabled: false
> > ```
> 
> 我在添加eks负载的时候遇到了这个问题。请问添加到经过处理后的eks kubeconfig里吗？
> 
> ![Image](https://github.com/user-attachments/assets/4b953912-d467-4fe5-9901-2b913567f4ab)

yes

**Comment by fffguo** [comment]
E0317 20:29:23.411843       1 controller.go:329] "Reconciler error" err=<
	failed to reconcile cluster platform-uat-cce: failed to install KS Core in cluster platform-uat-cce: unable to build kubernetes objects from release manifest: resource mapping not found for name: "restart-extensions-museum" namespace: "kubesphere-system" from "": no matches for kind "CronJob" in version "batch/v1beta1"
	ensure CRDs are installed first
 > controller="cluster" controllerGroup="cluster.kubesphere.io" controllerKind="Cluster" Cluster="platform-uat-cce" namespace="" name="platform-uat-cce" reconcileID="55e9cdce-564f-4a4e-b5b0-25ca5674d18e"

我也遇到了类似的问题，连接的是华为云的CCE集群，应该也是版本识别有问题
[root@platform-uat-k8s-node-001 ~]# kubectl version 
Client Version: v1.30.6-r0-30.0.5
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.6-r0-30.0.34

并且我尝试再kubeconfig中添加了
ksExtensionRepository:
  enabled: false

并且还是报了以上的错误
