### ISSUE TITLE
kubesphere-all-offline-advanced-2.0.0 离线安装提示 Failed connect to 192.168.10.137:5080; Connection refused

### ISSUE THREAD

**Issue by Liuyanglong** [kubesphere/kubesphere#623]
如题。
mount成功，但是一直提示Failed connect to 192.168.10.137:5080; Connection refused，求解。

**Comment by lilinlinlin** [comment]
报错提示，安装源不能用。该环境是停机过吗？解决方法：重新执行下安装脚本。

**Comment by Liuyanglong** [comment]
@lilinlinlin  重新执行过多次，一直报这个错，可以手动配置安装源吗？我的环境是vmware的虚拟机。

**Comment by Liuyanglong** [comment]
@lilinlinlin 发现了这两个容器，但是failed，启动后提示端口被占用，我全部删掉并kill docker重启，仍然报端口被占用的错。
![image](https://user-images.githubusercontent.com/1468470/62513898-10303500-b850-11e9-966e-3e9088a71da5.png)
![image](https://user-images.githubusercontent.com/1468470/62513908-19b99d00-b850-11e9-96e9-eb351ff16435.png)

**Comment by lilinlinlin** [comment]
1、环境是vmware的虚拟机没关系的。
2、uninstall.sh运行这个脚本先卸载下，再安装。
3、这两个服务就是离线安装源转发的服务和镜像存放的服务。

**Comment by lilinlinlin** [comment]
vmware的虚拟机，如果打通了外网，可以使用在线安装，就不会有这两个服务。
@Liuyanglong

**Comment by Liuyanglong** [comment]
@lilinlinlin  已经解决，是docker-proxy 和 docker-runc两个命令没在PATH中原因导致，感谢~
