### ISSUE TITLE
Unable to create a new Ingress

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [kubesphere/kubesphere#6242]
**Describe the Bug**

Chinese: 无法点击新建 Ingress，可以编辑，无弹窗提示，控制台异常：“[wujie warn]: notify 事件订阅数量为空 undefined”，通过调试 JS 可知，未安装 KubeSphere 网关，安装 KubeSphere 网关 之后，即可点击 新建 Ingress

English: Unable to click to create new Ingress, can edit, no pop-up prompt, console exception: "[wujie warn]: notify event subscription quantity is empty undefined". Through debugging JS, it is known that KubeSphere gateway is not installed. After installing KubeSphere gateway, you can click to create new Ingress

For UI issues please also add a screenshot that shows the issue.

![20241028-14-45-59-DESKTOP-8E6LUNV-5980-chrome-Uc2KbjEQia](https://github.com/user-attachments/assets/aba02fd4-f31e-41b3-a6a3-1fb7c6117e88)

![20241028-14-23-47-DESKTOP-8E6LUNV-5973-chrome-2kSKxh5inH](https://github.com/user-attachments/assets/789ba407-46f4-49a0-ad50-d54d6375d954)

**Versions Used**
KubeSphere: v4.1.2
Kubernetes: v1.27.3

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by xuxiaowei-com-cn** [comment]
After installing KubeSphere gateway:

![20241028-14-48-34-DESKTOP-8E6LUNV-5982-chrome-kSW7PVYi9r](https://github.com/user-attachments/assets/dce13e14-74b4-45ae-a248-690afe5c80cb)

**Comment by donniean** [comment]
The issue has been fixed, please wait for the next version or use the release-4.1 branch.

<img width="1026" alt="企业微信截图_85f4cb21-1e23-427f-821d-a56cb3aa5db5" src="https://github.com/user-attachments/assets/76e80538-f562-4f35-b0ef-83a6573ebce8">
