### ISSUE TITLE
日志关键词搜索很不好用！

### ISSUE THREAD

**Issue by DustFinger001** [kubesphere/kubesphere#626]
现在日志关键词搜索很不方便，英文搜索只能单个词进行搜索，不能写短语或者句子；中文只能单个字搜索，不能搜索一个完整词，完整词会被分割成多个字搜索。这样的搜索结果对于日志量大的环境很不实用，希望能完善短语和词进行搜索的功能。

**Comment by benjaminhuo** [comment]
你好，现在英文支持句子的搜索，如下图所示，您说的不能搜索是在什么情况下产生的，可以给个示例吗？ 中文搜索需要支持中文分词的 es，这个我们后面会提供。现在也可以在设置里指向外部有中文分词的 es 来解决。

![Snip20190806_44](https://user-images.githubusercontent.com/18525465/62513409-964b7c00-b84e-11e9-8929-0e3c2dd32505.png)

![Snip20190806_45](https://user-images.githubusercontent.com/18525465/62513433-9ea3b700-b84e-11e9-8154-5c9d67dcc7c7.png)

**Comment by DustFinger001** [comment]
英文搜索的精确搜索能否精确到短语或句子匹配 比如说 “test result“ 短语作为一个关键字，搜索结果应该只包含 “test result“ 短语，而不是仅包含 “test” 或 “result”，又或两个单词分开的；
或者只包含“test result”应该最优先展示；否则有可能搜索出很多内容，而有用的仅仅只有几条， 还要在结果集中查询很久。

**Comment by benjaminhuo** [comment]
明白 你指的像用搜索引擎那样，在句子两边加引号，精确匹配整句的效果
我们会改进

**Comment by DustFinger001** [comment]
@benjaminhuo 期待下一版本的改进，会一直关注kubesphere。

**Comment by zryfish** [comment]
close due to inactivity
