### ISSUE TITLE
can not update application with helm

### ISSUE THREAD

**Issue by dgsfor** [kubesphere/kubesphere#6279]
In kubepshere, I built my own helm repository, deployed the helm application, when my application was updated, a new version was created, I went to update the application, and found that it did not take effect。

kubesphere version: 4.1

<img width="1591" alt="image" src="https://github.com/user-attachments/assets/bbc0ba63-7f38-46ec-b03c-a9093ff6ac79">
<img width="1676" alt="image" src="https://github.com/user-attachments/assets/bae10160-bf66-477b-b664-347b1585fd14">
<img width="1550" alt="image" src="https://github.com/user-attachments/assets/3b0391bf-f991-42b8-b06d-ce90fff7fb3e">

```shell
k get pods -n eve-base
NAME                                               READY   STATUS      RESTARTS   AGE
helm-executor-install-domestic-base-bwcntg-r8njr   0/1     Completed   0          98m
```

**Comment by inksnw** [comment]
https://github.com/kubesphere/kubesphere/pull/6214
It has been fixed and will be included in the next version
