### ISSUE TITLE
Permission issues with Helm chart installation.

### ISSUE THREAD

**Issue by donbing007** [kubesphere/kubesphere#6283]
This issue #6273  helped me resolve the problem where my regular account couldn't upgrade applications. 

However, there's still a new issue. Some of my Helm charts create resources like ClusterRoles or ClusterRoleBindings. If I don't assign the target account the highest privilege role, KubeSphere shows an error saying it can't create the resources. 
But at the same time, I don't want the target account to have cluster management permissions. How should I adjust the permissions in this case?

**Comment by inksnw** [comment]
You can refer to this to add some permissions and roles yourself
https://dev-guide.kubesphere.io/extension-dev-guide/zh/feature-customization/access-control/
