### ISSUE TITLE
没有 Devops 项目  创建按钮

### ISSUE THREAD

**Issue by duyiliu** [kubesphere/kubesphere#6284]
没有 Devops 项目  创建按钮， 权限都确认 最高权限，admin账户都试了不可以
![image](https://github.com/user-attachments/assets/4c19df0b-016f-45c8-a103-f7df1eb5cda4)

**Comment by wansir** [comment]
I have temporarily closed this issue as it seems to align with the problem described by @yudong2015. If the issue remains unresolved, please feel free to reopen it.

/close
