### ISSUE TITLE
redhat7.4 集群离线安装失败

### ISSUE THREAD

**Issue by lujs678** [kubesphere/kubesphere#629]
单机版安装解决了，到集群安装又出问题了
在ssh 登录处处报错了

fatal: [hippo04kf]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 5, "stderr": "Warning: Permanently added '99.13.XX.XX' (ECDSA) to the list of known hosts.\r\nPermission denied, please try again(publickey,gssapi-keyex,gssapi-with-mic).\r\n", "stderr_lines": ["Warning: Permanently added '99.13.XX.XX' (ECDSA) to the list of known hosts.", "Permission denied, please try again(publickey,gssapi-keyex,gssapi-with-mic)."], "stdout": "", "stdout_lines": []}

我已经安装常见问题，在host.ini里面加入non-root用户了，还是提示这个错误
而且我也尝试在安装节点ssh命令登录node节点，是可以成功的。

**Comment by lilinlinlin** [comment]
hosts.ini贴下

**Comment by lujs678** [comment]
[all]
hippo02kf ansible_connection=local  ip=99.XX.XXX.134 
hippo03kf ansible_host=99.XX.XXX.135  ip=99.XX.XXX.135 ansible_user=tester ansible_ssh_pass=@@@@@@
hippo04kf ansible_host=99.XX.XXX.136  ip=99.XX.XXX.136 ansible_user=tester ansible_ssh_pass=@@@@@@

[local-registry]
hippo02kf 

[kube-master]
hippo02kf 

[kube-node]
hippo03kf 
hippo04kf 

[etcd]
hippo02kf 

[k8s-cluster:children]
kube-node
kube-master

**Comment by lujs678** [comment]
> hosts.ini贴下

我这边的机器账号大概是这样：tester有root权限，我能拿到tester密码，root密码没有
ssh登陆我只能通过tester账号密码登录。

**Comment by lilinlinlin** [comment]
只贴了all的格式，ansible_ssh_pass改成ansible_become_pass，最后执行脚本时，需要转成root用户执行。
[all]
master ansible_connection=local  ip=192.168.0.5  ansible_user=tester  ansible_become_pass=@@@@@@ 
node1  ansible_host=192.168.0.6  ip=192.168.0.6  ansible_user=tester  ansible_become_pass=@@@@@@

**Comment by lujs678** [comment]
> 只贴了all的格式，ansible_ssh_pass改成ansible_become_pass，最后执行脚本时，需要转成root用户执行。
> [all]
> master ansible_connection=local ip=192.168.0.5 ansible_user=tester ansible_become_pass=@@@@@@
> node1 ansible_host=192.168.0.6 ip=192.168.0.6 ansible_user=tester ansible_become_pass=@@@@@@

可以了谢谢，没留意到这点区别。
现在又有新问题
node节点加入集群报token失效，但明显没有
Failed to connect to API Server \"99.XX.XXX.134:6443\": token id \"zfhjqa\" is invalid for this cluster or it has expired.

再之前报了个这么错误
{"changed": false, "msg": "error running kubectl (/usr/local/bin/kubectl apply --force --filename=/etc/kubernetes/k8s-cluster-critical-pc.yml) command (rc=1), out='', err='error: unable to recognize \"/etc/kubernetes/k8s-cluster-critical-pc.yml\": Get http://localhost:8080/api?timeout=32s: dial tcp 127.0.0.1:8080: connect: connection refused\n'"}
后来改了配置文件的
insecure-bind-address=0.0.0.0  端口改8080 就解决了

**Comment by lilinlinlin** [comment]
现在的k8s正常了没，添加node，是可以脚本还是手动添加的呢

**Comment by lujs678** [comment]
> 现在的k8s正常了没，添加node，是可以脚本还是手动添加的呢

这个是执行集群安装脚本时候报错的，手动kebeadm join也报一样的错，token重新生产也一样

**Comment by lilinlinlin** [comment]
1、执行安装是确定是用root用户去安装的吗？k8s是正常的吗？
2、可以卸载重新安装一遍。

**Comment by lujs678** [comment]
> 1、执行安装是确定是用root用户去安装的吗？k8s是正常的吗？
> 2、可以卸载重新安装一遍。

可以安装成功了，但是监控有个容器启动失败

![Uploading 微信图片_20190811204240.jpg…]()
![Uploading 微信图片_20190811204242.jpg…]()
![微信图片_20190811204244](https://user-images.githubusercontent.com/30866140/62834382-f04ca700-bc7d-11e9-8202-891da84d39bc.jpg)

**Comment by lilinlinlin** [comment]
安装成功之后，如果资源充足，后面的pod会正常启来。
