### ISSUE TITLE
centos7.6 all-in-one安装2.0.2失败

### ISSUE THREAD

**Issue by geli2016** [kubesphere/kubesphere#630]
在centos7.6下离线安装kubesphere-all-offline-advanced-2.0.2报yum源错误。
环境的硬件配置如下：（虚拟机）
1节点：8cpu/16g
复现步骤：
未修改conf/vars.yaml
直接运行./install.sh
选择1
See error

################################################
         KubeSphere Installer Menu
################################################
*   1) All-in-one
*   2) Multi-node
*   3) Quit
################################################
https://kubesphere.io/               2019-08-09
################################################
Please input an option: 1
1
umount: /kubeinstaller/yum_repo/iso: mountpoint not found
/etc/yum.repos.d ~/kubesphere-all-offline-advanced-2.0.2/scripts
/etc/yum.repos.d
mount: /dev/loop0 is write-protected, mounting read-only
mount: /dev/loop1 is write-protected, mounting read-only
Loaded plugins: fastestmirror
Cleaning repos: bash
Cleaning up list of fastest mirrors
Other repos take up 84 M of disk space (use --verbose for details)
Loaded plugins: fastestmirror
Determining fastest mirrors
file:///kubeinstaller/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#37 - "Couldn't open file /kubeinstaller/yum_repo/iso/repodata/repomd.xml"
Trying other mirror.

 One of the configured repositories failed (centos7),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=bash ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable bash
        or
            subscription-manager repos --disable=bash

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=bash.skip_if_unavailable=true

failure: repodata/repomd.xml from bash: [Errno 256] No more mirrors to try.
file:///kubeinstaller/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#37 - "Couldn't open file /kubeinstaller/yum_repo/iso/repodata/repomd.xml"
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
file:///kubeinstaller/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#37 - "Couldn't open file /kubeinstaller/yum_repo/iso/repodata/repomd.xml"
Trying other mirror.

 One of the configured repositories failed (centos7),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=bash ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable bash
        or
            subscription-manager repos --disable=bash

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=bash.skip_if_unavailable=true

failure: repodata/repomd.xml from bash: [Errno 256] No more mirrors to try.
file:///kubeinstaller/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#37 - "Couldn't open file /kubeinstaller/yum_repo/iso/repodata/repomd.xml"
Error: Install the base packages failed!
sudo: pip: command not found
Error: Install the base packages failed!
grep: /etc/lsb-release: No such file or directory
./all-in-one.sh: line 36: ansible-playbook: command not found
failed!

**Comment by geli2016** [comment]
/kubeinstaller/yum_repo/目录下是空的。

**Comment by lilinlinlin** [comment]
centos7.6系统还不支持离线下载部署。可以用centos7.4或7.5或在线部署。

**Comment by pixiake** [comment]
如果环境可以联网，建议使用在线安装，支持centos7.6

**Comment by geli2016** [comment]
> 如果环境可以联网，建议使用在线安装，支持centos7.6

在线centos7.6下安装依然遇到同样问题。


################################################
         KubeSphere Installer Menu
################################################
*   1) All-in-one
*   2) Multi-node
*   3) Quit
################################################
https://kubesphere.io/               2019-08-09
################################################
Please input an option: 1
1
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
file:///kubeinstaller/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#37 - "Couldn't open file /kubeinstaller/yum_repo/iso/repodata/repomd.xml"
Trying other mirror.


 One of the configured repositories failed (centos7),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=bash ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable bash
        or
            subscription-manager repos --disable=bash

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=bash.skip_if_unavailable=true

failure: repodata/repomd.xml from bash: [Errno 256] No more mirrors to try.
file:///kubeinstaller/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#37 - "Couldn't open file /kubeinstaller/yum_repo/iso/repodata/repomd.xml"
./os/centos7.sh: line 21: pip: command not found
./all-in-one.sh: line 34: ansible-playbook: command not found

**Comment by pixiake** [comment]
刚才执行离线安装修改的yum源，先还原一下 ，/etc/yum.repo.d  有备份

**Comment by geli2016** [comment]
> 刚才执行离线安装修改的yum源，先还原一下 ，/etc/yum.repo.d 有备份
是这个问题。解决了。

**Comment by geli2016** [comment]
> centos7.6系统还不支持离线下载部署。可以用centos7.4或7.5或在线部署。

在线部署对网络不低啊。。。还是想离线部署，centos哪个版本支持呢？

**Comment by lilinlinlin** [comment]
centos7.4或7.5可以离线部署

**Comment by haiker2011** [comment]
今天在centOS7.6上面实验离线版遇到了同样的问题

**Comment by lilinlinlin** [comment]
在线可以支持centos7.6 ；离线centos7.6版本安装脚本刚做好，不久应该会推出来。
如果你真需要的话，可以单独发给你。

**Comment by haiker2011** [comment]
@lilinlinlin 可以啊，我们正好可以帮你们测试一下

**Comment by lilinlinlin** [comment]
链接：https://pan.baidu.com/s/1HBlBaD69mx6z050sSgj0Kg 
提取码：eqe6 
把该iso放到离线环境的kubesphere-all-offline-advanced-2.0.2/Repos/下，重新跑

**Comment by haiker2011** [comment]
@lilinlinlin 谢谢！

**Comment by haiker2011** [comment]
@lilinlinlin 你好，添加上你给的ISO之前的问题解决了，但是在安装requirements.txt时候出现在了问题。

```
总计                                                                                                                                                 140 MB/s |  42 MB  00:00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  正在安装    : 2:container-selinux-2.107-1.el7_6.noarch                                                                                                                         1/4
  正在安装    : docker-ce-18.06.2.ce-3.el7.x86_64                                                                                                                                2/4
  正在安装    : python2-pip-8.1.2-9.el7.noarch                                                                                                                                   3/4
  正在安装    : sshpass-1.06-2.el7.x86_64                                                                                                                                        4/4
  验证中      : docker-ce-18.06.2.ce-3.el7.x86_64                                                                                                                                1/4
  验证中      : sshpass-1.06-2.el7.x86_64                                                                                                                                        2/4
  验证中      : 2:container-selinux-2.107-1.el7_6.noarch                                                                                                                         3/4
  验证中      : python2-pip-8.1.2-9.el7.noarch                                                                                                                                   4/4

已安装:
  docker-ce.x86_64 0:18.06.2.ce-3.el7                            python2-pip.noarch 0:8.1.2-9.el7                            sshpass.x86_64 0:1.06-2.el7

作为依赖被安装:
  container-selinux.noarch 2:2.107-1.el7_6

完毕！
Ignoring indexes: https://pypi.python.org/simple
Collecting ansible==2.7.6 (from -r /home/sunhaizhou/all-in-one/kubesphere-all-offline-advanced-2.0.2/scripts/os/requirements.txt (line 1))
  Could not find a version that satisfies the requirement ansible==2.7.6 (from -r /home/sunhaizhou/all-in-one/kubesphere-all-offline-advanced-2.0.2/scripts/os/requirements.txt (line 1)) (from versions: )
No matching distribution found for ansible==2.7.6 (from -r /home/sunhaizhou/all-in-one/kubesphere-all-offline-advanced-2.0.2/scripts/os/requirements.txt (line 1))
Error: Install the pip packages failed!
grep: /etc/lsb-release: 没有那个文件或目录
./all-in-one.sh:行36: ansible-playbook: 未找到命令
failed!
```

应该是ansible==2.7.6安装时找不到对应的版本。

**Comment by lilinlinlin** [comment]
@haiker2011  先把之前的iso umount掉，重新执行

**Comment by lilinlinlin** [comment]
ansible是pip安装的，不包括在requirement里

**Comment by pixiake** [comment]
可以手动umount一下/kubeinstaller/pip_repo/pip27/iso    或者重启机器    应该可以解决该问题
