### ISSUE TITLE
In version 4.1.2, where are the LDAP configuration and account data stored, and how can these data be backed up or stored by mounting NFS?

### ISSUE THREAD

**Issue by yakexi007** [kubesphere/kubesphere#6317]
**What's your question**

In version 4.1.2, where are the LDAP configuration and account data stored, and how can these data be backed up or stored by mounting NFS?

**Installer Version**

> v4.1.2

**Comment by wansir** [comment]
> **What's your question**
> 
> In version 4.1.2, where are the LDAP configuration and account data stored, and how can these data be backed up or stored by mounting NFS?
> 
> **Installer Version**
> 
> > v4.1.2

Since KubeSphere 3.x, LDAP is no longer used to store account data. Instead, we use CRDs to store account data in etcd. You can easily backup these CRs by setting up scheduled tasks.

```
kubectl get users.iam.kubesphere.io -o yaml > users.iam.kubesphere.io.yaml
```

**Comment by yakexi007** [comment]
Got it, thank you very much
