### ISSUE TITLE
页面上，需要增加一个能直接进入容器的入口，方便调试、排查问题

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#632]
![image](https://user-images.githubusercontent.com/43693241/62753245-53331800-ba9d-11e9-828d-9424598b8f5d.png)

**Comment by zryfish** [comment]
进入容器指的想查看容器的日志么，还是连接容器的终端

**Comment by shaowenchen** [comment]
连接容器的 console

**Comment by Leboudin** [comment]
https://kubesphere.io/docs/advanced-v2.0/zh-CN/quick-start/one-click-deploy/

**Comment by zryfish** [comment]
2.1.0已经fix
