### ISSUE TITLE
kubesphere能否独立使用呢

### ISSUE THREAD

**Issue by wanghaiqing2015** [kubesphere/kubesphere#633]
我想自己部署的k8s，可以采用kubesphere的dashboard吗

**Comment by lilinlinlin** [comment]
参考这部署过程。https://github.com/pixiake/ks-installer，后续会放到kubesphere下。

**Comment by wanghaiqing2015** [comment]
非常感谢，这个dashboard，我都感觉比帮忙安装k8s更好一点。毕竟安装很容易。

**Comment by FeynmanZhou** [comment]
@wanghaiqing2015  社区用户在已有k8s上安装的经验分享：

https://mp.weixin.qq.com/s/FcCBXs-f_VsNPp9qdMDfNQ

**Comment by ckgmg** [comment]
docker run方式运行，不成功
docker search kubesphere下载下来
run
---------------------------
Unable to find image 'kubesphere/kubesphere:lastest' locally
docker: Error response from daemon: manifest for kubesphere/kubesphere:lastest not found.
See 'docker run --help'.

**Comment by ckgmg** [comment]
kubernetes配置一台master,两台node上，kubesphere不安装在master上，安装在另一台独立的机器上，能否这样安装，

**Comment by lilinlinlin** [comment]
可以啊 ，但是要把证书拷贝到安装的机器上

**Comment by lilinlinlin** [comment]
镜像kubespheredev/ks-installer:advanced-2.0.2，你可以好好研究下kubesphere.yaml
