### ISSUE TITLE
Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'xxx' doesn't support architecture 'i386'

### ISSUE THREAD

**Issue by yangjianchun** [kubesphere/kubesphere#637]
系统ubuntu 19.04
deb https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu disco stable
apt update 会提示
Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'xxx' doesn't support architecture 'i386'

请问下是操作系统版本的问题吗？

**Comment by lilinlinlin** [comment]
是的，离线可以使用18.05以下的版本；机器可以连外网的话，19.04也可以。

**Comment by yangjianchun** [comment]
但是我服务器 16核24G  在线安装会提醒上诉那个  deb https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu disco stable  这个是脚本安装自动加到源里面 doesn't support architecture 'i386'

**Comment by lilinlinlin** [comment]
在线安装，将刚才执行离线安装修改的yum源，先还原一下 ，/etc/yum.repo.d 有备份

**Comment by lilinlinlin** [comment]
ubuntu系统回复这个文件/etc/apt/sources.list，上面的是centos系统的。

**Comment by yangjianchun** [comment]
TASK [prepare/nodes : GlusterFS | Installing glusterfs-client (APT)] ***************************************************************************************************************************************
Thursday 15 August 2019  16:13:50 +0800 (0:00:00.073)       0:00:40.757 ******* 
FAILED - RETRYING: GlusterFS | Installing glusterfs-client (APT) (5 retries left).
FAILED - RETRYING: GlusterFS | Installing glusterfs-client (APT) (4 retries left).
FAILED - RETRYING: GlusterFS | Installing glusterfs-client (APT) (3 retries left).
FAILED - RETRYING: GlusterFS | Installing glusterfs-client (APT) (2 retries left).
FAILED - RETRYING: GlusterFS | Installing glusterfs-client (APT) (1 retries left).
fatal: [ks-allinone]: FAILED! => {"attempts": 5, "changed": false, "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., W:Skipping acquire of configured file 'stable/binary-i386/Packages' as repository 'https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/ubuntu disco InRelease' doesn't support architecture 'i386', E:The repository 'http://ppa.launchpad.net/gluster/glusterfs-3.12/ubuntu disco Release' does not have a Release file."}

PLAY RECAP *************************************************************************************************************************************************************************************************
ks-allinone                : ok=8    changed=2    unreachable=0    failed=1   

Thursday 15 August 2019  16:14:58 +0800 (0:01:08.042)       0:01:48.799 ******* 

老是出现这个错误  ubuntu19.04 root用户执行     心好累！！！！！！！！1      现在可以生产环境可以用kubespher不

**Comment by yangjianchun** [comment]
是在线安装的

**Comment by pixiake** [comment]
错误提示doesn't support architecture 'i386'       在kubesphere/roles/prepare/nodes/tasks/main.yaml注释掉glusterfs-client相关任务

**Comment by lilinlinlin** [comment]
kubesphere生产环境可用了，操作系统要用64位的，如果不用glusterfs，可以把该安装glusterfs客户端那步注释。
