### ISSUE TITLE
centos7.4 2.0.2离线安装后，系统重启服务不恢复

### ISSUE THREAD

**Issue by Liuyanglong** [kubesphere/kubesphere#644]
如题，系统为centos 7.4部署2.0.2离线版成功，reboot后服务始终无法启动成功。
执行命令：
`kubectl get pods --all-namespaces`
可看出处于Running状态的只有30多个，且过了几个小时一直如此。
![image](https://user-images.githubusercontent.com/1468470/62928382-062baa80-bdeb-11e9-8d0c-dd80d044c7db.png)
![image](https://user-images.githubusercontent.com/1468470/62928404-0fb51280-bdeb-11e9-86f8-d63640713666.png)

**Comment by zryfish** [comment]
kube-system下的 coredns 没有起来，看下coredns的错误日志

**Comment by Liuyanglong** [comment]
重启了一次系统，现在的环境是这样的：

**Comment by Liuyanglong** [comment]
![image](https://user-images.githubusercontent.com/1468470/62936153-a4277100-bdfb-11e9-8f2d-f57d7026619d.png)
![image](https://user-images.githubusercontent.com/1468470/62936157-aab5e880-bdfb-11e9-85fd-a91f4f4a9a6d.png)
console依然上不去，之前部署的应用也访问不了。
@zryfish

**Comment by Liuyanglong** [comment]
![image](https://user-images.githubusercontent.com/1468470/62936263-ed77c080-bdfb-11e9-9124-2ee163ca09a5.png)
![image](https://user-images.githubusercontent.com/1468470/62936295-02545400-bdfc-11e9-847c-3cf3a7833556.png)

@zryfish

**Comment by Liuyanglong** [comment]
我执行命令：
kubectl get svc --all-namespaces|grep '10.233.0.1'
结果如下多出来一个default namespace，我记得kubesphere中是没有default组的。

![image](https://user-images.githubusercontent.com/1468470/62936488-7d1d6f00-bdfc-11e9-9c17-40a7984d90d1.png)

**Comment by zryfish** [comment]
coredns 无法连接 apiserver，可以执行 ipvsadm -Ln 看下 6443 端口是否对应主节点地址

**Comment by Liuyanglong** [comment]
![image](https://user-images.githubusercontent.com/1468470/63406923-dea59500-c41d-11e9-8c06-857388803685.png)
@zryfish
