### ISSUE TITLE
run ks-iam bear token exception

### ISSUE THREAD

**Issue by cnicy** [kubesphere/kubesphere#647]
make all成功编译源码后，在goland运行ks-iam模块的main方法时，报错：
```
E0814 23:55:11.679862    3201 reflector.go:134] pkg/mod/k8s.io/client-go@v0.0.0-20181213151034-8d9ed539ba31/tools/cache/reflector.go:95: Failed to list *v1.Role: Get https://10x x x:6443/apis/rbac.authorization.k8s.io/v1/roles?limit=500&resourceVersion=0: net/http: invalid header field value "Bearer xxxxx\n" for key Authorization
```
我是在mac上运行，在/var/run/secrets/kubernetes.io/serviceaccount目录下生成了token的ca.crt两个文件，这两个文件token和ca证书内容是从哪个workspace下的serviceaccount中来的？

**Comment by wansir** [comment]
你好，ks-iam 依赖的外部服务有kube-apiserver,redis,openldap，该错误信息是因为--kubeconfig 没有正确指定，无法同步k8s 中RBAC相关数据, 如果是在本地环境可以 使用该kubeconfig 验证一下能否通过 `kubectl get roles` 拿到数据

必传参数如下
```
--kubeconfig=
--redis-server=
--ldap-server=
--ldap-manager-dn=cn=
--ldap-manager-password=
--ldap-user-search-base=ou=
--ldap-group-search-base=ou=
--jwt-secret=
```

**Comment by cnicy** [comment]
```
$ kubectl get roles
NAME             AGE
admin            42m
operator         42m
prometheus-k8s   42m
viewer           42m
```
这是正常的，我在本地运行代码（ks-iam）的main方法，他提示找不到这两个文件：
/var/run/secrets/kubernetes.io/serviceaccount/token
/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
我看了下代码，这个是fluent-bit配置文件，token和ca.crt这两个文件内容从那里找得到。另外--kubeconfig这个文件内容有哪些呢？应该怎么配置。

**Comment by cnicy** [comment]
直接运行报这个错：I0816 14:47:20.022576    6156 k8sclient.go:52] open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
