### ISSUE TITLE
console报错internal server error，log报redis错误。

### ISSUE THREAD

**Issue by geli2016** [kubesphere/kubesphere#648]
console报错internal server error。看ks-console的pod log，有如下报错。

  <-- POST /logout 2019/08/15T07:57:27.111
  xxx POST /logout 500 7ms - 2019/08/15T07:57:27.118
ERR { ReplyError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
    at JavascriptRedisParser.returnError (/root/KubeSphereUI/node_modules/ioredis/lib/redis/parser.js:24:25)
    at JavascriptRedisParser.execute (/root/KubeSphereUI/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/root/KubeSphereUI/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17) name: 'ReplyError', message: 'MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.', command: { name: 'del', args: [ 'sid-kubesphere-testaccount1-RW9XLcBF7Y_tWoeRWdHZ7D2RUDHHm5s2' ] } }

**Comment by leoendless** [comment]
可以看下 kubectl -n kubesphere-system get deploy/redis -o yaml 的结果吗

**Comment by geli2016** [comment]
> 
> 
> 可以看下 kubectl -n kubesphere-system get deploy/redis -o yaml 的结果吗

[root@ks-allinone ~]# kubectl -n kubesphere-system get deploy/redis -o yaml 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"redis","tier":"database","version":"redis-4.0"},"name":"redis","namespace":"kubesphere-system"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"redis","tier":"database","version":"redis-4.0"}},"template":{"metadata":{"labels":{"app":"redis","tier":"database","version":"redis-4.0"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"node-role.kubernetes.io/master","operator":"In","values":[""]}]},"weight":100}]}},"containers":[{"image":"10.0.0.49:5000/library/redis:4.0","imagePullPolicy":"IfNotPresent","name":"redis","ports":[{"containerPort":6379,"protocol":"TCP"}],"resources":{"limits":{"cpu":"1000m","memory":"1000Mi"},"requests":{"cpu":"30m","memory":"100Mi"}},"volumeMounts":[{"mountPath":"/data","name":"redis-pvc","subPath":"redis-data"}]}],"tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/master"},{"key":"CriticalAddonsOnly","operator":"Exists"}],"volumes":[{"name":"redis-pvc","persistentVolumeClaim":{"claimName":"redis-pvc"}}]}}}}
  creationTimestamp: "2019-08-14T10:35:16Z"
  generation: 1
  labels:
    app: redis
    tier: database
    version: redis-4.0
  name: redis
  namespace: kubesphere-system
  resourceVersion: "145555"
  selfLink: /apis/extensions/v1beta1/namespaces/kubesphere-system/deployments/redis
  uid: 346a7a16-be7f-11e9-b5a4-fa163e14b4cc
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: redis
      tier: database
      version: redis-4.0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
        tier: database
        version: redis-4.0
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                - ""
            weight: 100
      containers:
      - image: 10.0.0.49:5000/library/redis:4.0
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1000Mi
          requests:
            cpu: 30m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: redis-pvc
          subPath: redis-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - name: redis-pvc
        persistentVolumeClaim:
          claimName: redis-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-08-14T10:35:16Z"
    lastUpdateTime: "2019-08-14T10:35:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

**Comment by zryfish** [comment]
看下redis pod的日志

**Comment by geli2016** [comment]
> 
> 
> 看下redis pod的日志
........
614:C 15 Aug 08:52:59.020 # Failed opening the RDB file dump.rdb (in server root dir /data) for saving: Permission denied
1:M 15 Aug 08:52:59.122 # Background saving error
1:M 15 Aug 08:53:05.056 * 1 changes in 3600 seconds. Saving...
1:M 15 Aug 08:53:05.057 * Background saving started by pid 615
615:C 15 Aug 08:53:05.057 # Failed opening the RDB file dump.rdb (in server root dir /data) for saving: Permission denied
1:M 15 Aug 08:53:05.158 # Background saving error

**Comment by zryfish** [comment]
挂盘的权限不够，导致redis无法做持久化，你的存储用的是什么

**Comment by geli2016** [comment]
> 
> 
> 挂盘的权限不够，导致redis无法做持久化，你的存储用的是什么

all-in-one安装。local volume

**Comment by geli2016** [comment]
redis pod 下，/data挂载的是redis-pvc。redis-pvc绑定的pv是vol-23.
这个文件的权限如下：
[root@ks-allinone ~]# ll /mnt/disks | grep vol-23
drwxr-xr-x.  2 root    root        6 Aug 14 10:34 vol-23

**Comment by DingQianWen** [comment]
```
./redis-cli   
127.0.0.1:6379> config set stop-writes-on-bgsave-error no   
127.0.0.1:6379> lpush myColour "red"
```

**Comment by DingQianWen** [comment]
```java
./redis-cli   
127.0.0.1:6379> config set stop-writes-on-bgsave-error no   
127.0.0.1:6379> lpush myColour "red"
```

**Comment by zryfish** [comment]
close due to inactivity
