### ISSUE TITLE
kubesphere v2.0.2 离线安装失败，提示Failed to create 'IPPool' resource: resource already exists: IPPool(default-pool)"

### ISSUE THREAD

**Issue by wuchencm** [kubesphere/kubesphere#651]
os: centos 7.6

fatal: [ks-allinone -> ks-allinone]: FAILED! => {"changed": true, "cmd": "echo \"\n{ \"kind\": \"IPPool\",\n\"apiVersion\": \"projectcalico.org/v3\",\n\"metadata\": {\n\"name\": \"default-pool\",\n},\n\"spec\": {\n\"cidr\": \"11.233.64.0/18\",\n\"ipipMode\": \"Always\",\n\"natOutgoing\": True }} \" | /usr/local/bin/calicoctl create -f -", "delta": "0:00:00.794658", "end": "2019-08-15 07:17:04.541788", "msg": "non-zero return code", "rc": 1, "start": "2019-08-15 07:17:03.747130", "stderr": "", "stderr_lines": [], "stdout": "Failed to create 'IPPool' resource: resource already exists: IPPool(default-pool)", "stdout_lines": ["Failed to create 'IPPool' resource: resource already exists: IPPool(default-pool)"]}

NO MORE HOSTS LEFT *************************************************************************************************************************************************************************************************************************

PLAY RECAP *********************************************************************************************************************************************************************************************************************************
ks-allinone                : ok=340  changed=36   unreachable=0    failed=1   
localhost                  : ok=1    changed=0    unreachable=0    failed=0

**Comment by lilinlinlin** [comment]
1、该机器之前是安装过k8s吗？
2、目前centos7.6离线部署还不支持，如果需要的话，
链接：https://pan.baidu.com/s/1HBlBaD69mx6z050sSgj0Kg
提取码：eqe6
把该iso放到离线环境的kubesphere-all-offline-advanced-2.0.2/Repos/下，重新跑

**Comment by veficos** [comment]
> 1、该机器之前是安装过k8s吗？
> 2、目前centos7.6离线部署还不支持，如果需要的话，
> 链接：https://pan.baidu.com/s/1HBlBaD69mx6z050sSgj0Kg
> 提取码：eqe6
> 把该iso放到离线环境的kubesphere-all-offline-advanced-2.0.2/Repos/下，重新跑

分享已过期，能再分享一份吗？
