### ISSUE TITLE
v2.0.2在线安装失败

### ISSUE THREAD

**Issue by wuchencm** [kubesphere/kubesphere#652]
错误提示：
fatal: [ks-allinone]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm upgrade --install ks-sonarqube /etc/kubesphere/sonarqube/sonarqube-0.13.5.tgz -f /etc/kubesphere/sonarqube/custom-values-sonarqube.yaml --namespace kubesphere-devops-system", "delta": "0:00:03.081434", "end": "2019-08-16 00:18:35.083017", "msg": "non-zero return code", "rc": 1, "start": "2019-08-16 00:18:32.001583", "stderr": "Error: UPGRADE FAILED: Get https://20.233.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%!D(MISSING)ks-sonarqube%!C(MISSING)OWNER%!D(MISSING)TILLER%!C(MISSING)STATUS%!D(MISSING)DEPLOYED: dial tcp 20.233.0.1:443: connect: no route to host", "stderr_lines": ["Error: UPGRADE FAILED: Get https://20.233.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%!D(MISSING)ks-sonarqube%!C(MISSING)OWNER%!D(MISSING)TILLER%!C(MISSING)STATUS%!D(MISSING)DEPLOYED: dial tcp 20.233.0.1:443: connect: no route to host"], "stdout": "", "stdout_lines": []}

操作系统：centos7.5_x64

**Comment by wuchencm** [comment]
ping 20.233.0.1 is ok
telnet 20.233.0.1 443 is ok

**Comment by pixiake** [comment]
检查下是不是机器防火墙还开着   建议关掉

**Comment by wuchencm** [comment]
确实是防火墙，systemctl stop firewalld后可以安装了，但是我始终没有在web ui里找到可以连接容器terminal的链接

**Comment by rayzhou2017** [comment]
system workspace docker terminal没有暴露出来，你需要自己创建pod，然后一直钻取下去到docker 级别就能看到，下一个版本会把terminal提升到pod 页面。

**Comment by wuchencm** [comment]
![image](https://user-images.githubusercontent.com/14210543/63160182-c0bbe700-c04f-11e9-88fa-02a243bbe67f.png)
一直卡在这里，最终会失败

**Comment by lilinlinlin** [comment]
free -m看下资源

**Comment by wuchencm** [comment]
[root@ks-allinone ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:           7805        4979         174          44        2650        1969
Swap:             0           0           0

**Comment by wuchencm** [comment]
![image](https://user-images.githubusercontent.com/14210543/63161112-e21dd280-c051-11e9-803c-b2e2504f9675.png)

**Comment by lilinlinlin** [comment]
echo 3 > /proc/sys/vm/drop_caches    指令释放下内存

**Comment by wuchencm** [comment]
> echo 3 > /proc/sys/vm/drop_caches 指令释放下内存

释放后依然会失败，我虚拟机 内存已经给了12G

**Comment by wuchencm** [comment]
![image](https://user-images.githubusercontent.com/14210543/63165239-6c1f6880-c05d-11e9-9006-9c6e6516c827.png)

**Comment by pixiake** [comment]
可以kubectl   describe看下这几个没起来的pod，应该是内存不足

**Comment by zryfish** [comment]
close due to inactivity
