### ISSUE TITLE
安装报错 ansible

### ISSUE THREAD

**Issue by alexshenyuefei** [kubesphere/kubesphere#653]
系统 CentOS Linux release 7.5.1804 (Core) 
离线安装   系统是新的
![image](https://user-images.githubusercontent.com/16495430/63146586-fea81380-c02d-11e9-8e7a-55d69e26766a.png)
报错

**Comment by alexshenyuefei** [comment]
![image](https://user-images.githubusercontent.com/16495430/63146644-3a42dd80-c02e-11e9-8bde-ba195f762aff.png)

**Comment by lilinlinlin** [comment]
@alexshenyuefei  可参考：https://github.com/kubesphere/ks-installer/issues/16

**Comment by zryfish** [comment]
close due to inactivity
