### ISSUE TITLE
有没有支持kustomize的计划

### ISSUE THREAD

**Issue by k0ngk0ng** [kubesphere/kubesphere#654]
k8s 1.14 有 kustomize 可以很好的控制 deployment，是否考虑在支持1.14后，在UI中加入对kustomize 的支持？

**Comment by rayzhou2017** [comment]
通常情况KubeSphere会支持最新k8s版本及两个旧版本，如果1.14支持kustomize，那意味着需要等1.16出来之后考虑这个需求。
