### ISSUE TITLE
安装卡死

### ISSUE THREAD

**Issue by lijinbang** [kubesphere/kubesphere#659]
安装以后就一直卡死在这个界面
![WX20190822-145548](https://user-images.githubusercontent.com/18083299/63492890-f7c94700-c4ec-11e9-8ced-6bf7cfcaaeae.png)

**Comment by zryfish** [comment]
这里不是卡死了，因为镜像比较大，如果网速不好的话，这里等待的时间会很长。可以打开新的终端，执行 iftop 看下

**Comment by lijinbang** [comment]
卡死在这里几乎流量为0 所以会说卡死，还有这个我昨天晚上十二点一直卡死在这里早上九点一看还是不卡了但是报错了。没有安装成功！

**Comment by zryfish** [comment]
报错信息能贴下么，安装的时候如果是云上环境，最好能临时把带宽调大些

**Comment by lijinbang** [comment]
稍等一下目前一直没有网速，本地网速是联通一百兆光纤，下载任何东西都正常！下载离线版速度11m每秒！
![WX20190822-165516](https://user-images.githubusercontent.com/18083299/63501241-e2a8e400-c4fd-11e9-837e-2eeb40bf2235.png)
这是当前网速。

**Comment by lijinbang** [comment]
我现在在等报错处理稍等一下。如果可以的话可以私聊。邮箱znsnzhang@outlook.com

**Comment by zryfish** [comment]
这个看的是clico的网卡， iftop -i [interface] 需要指定下电脑的主网卡

**Comment by lijinbang** [comment]
这个是指定的网卡信息，还是基本没有网速
![WX20190822-171844](https://user-images.githubusercontent.com/18083299/63502875-fdc92300-c500-11e9-8caf-5fd2064269af.png)

**Comment by zryfish** [comment]
close due to inactivity
