### ISSUE TITLE
代码编译make异常

### ISSUE THREAD

**Issue by Liuyanglong** [kubesphere/kubesphere#662]
我git clone kubesphere项目后，在路径下执行make，错误如下：
which: no controller-gen in (/home/gopath/bin:/home/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
GO111MODULE=on go install -mod=vendor k8s.io/code-generator/cmd/deepcopy-gen
go generate ./pkg/... ./cmd/...
go: sigs.k8s.io/testing_frameworks@v0.1.1: unrecognized import path "sigs.k8s.io/testing_frameworks" (https fetch: Get https://sigs.k8s.io/testing_frameworks?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: google.golang.org/genproto@v0.0.0-20190418145605-e7d98fc518a7: unrecognized import path "google.golang.org/genproto" (https fetch: Get https://google.golang.org/genproto?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/oauth2@v0.0.0-20190402181905-9f3314589c9a: unrecognized import path "golang.org/x/oauth2" (https fetch: Get https://golang.org/x/oauth2?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: sigs.k8s.io/controller-runtime@v0.1.10: unrecognized import path "sigs.k8s.io/controller-runtime" (https fetch: Get https://sigs.k8s.io/controller-runtime?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: k8s.io/klog@v0.3.1: unrecognized import path "k8s.io/klog" (https fetch: Get https://k8s.io/klog?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: google.golang.org/genproto@v0.0.0-20180817151627-c66870c02cf8: unrecognized import path "google.golang.org/genproto" (https fetch: Get https://google.golang.org/genproto?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/text@v0.3.0: unrecognized import path "golang.org/x/text" (https fetch: Get https://golang.org/x/text?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: k8s.io/code-generator@v0.0.0-20181117043124-c2090bec4d9b: unrecognized import path "k8s.io/code-generator" (https fetch: Get https://k8s.io/code-generator?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: google.golang.org/appengine@v1.5.0: unrecognized import path "google.golang.org/appengine" (https fetch: Get https://google.golang.org/appengine?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sys@v0.0.0-20190124100055-b90733256f2e: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sys@v0.0.0-20181116152217-5ac8a444bdc5: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sys@v0.0.0-20181107165924-66b7b1311ac8: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: sigs.k8s.io/controller-tools@v0.1.12: unrecognized import path "sigs.k8s.io/controller-tools" (https fetch: Get https://sigs.k8s.io/controller-tools?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: finding gopkg.in/yaml.v2 v2.0.0-20170812160011-eb3733d160e7
go: k8s.io/gengo@v0.0.0-20190327210449-e17681d19d3a: unrecognized import path "k8s.io/gengo" (https fetch: Get https://k8s.io/gengo?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: golang.org/x/crypto@v0.0.0-20190123085648-057139ce5d2b: unrecognized import path "golang.org/x/crypto" (https fetch: Get https://golang.org/x/crypto?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/net@v0.0.0-20180218175443-cbe0f9307d01: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/net@v0.0.0-20181220203305-927f97764cc3: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/net@v0.0.0-20190125091013-d26f9f9a57f3: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: k8s.io/apiserver@v0.0.0-20190507070644-e9c02aff496d: unrecognized import path "k8s.io/apiserver" (https fetch: Get https://k8s.io/apiserver?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: k8s.io/api@v0.0.0-20181213150558-05914d821849: unrecognized import path "k8s.io/api" (https fetch: Get https://k8s.io/api?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: finding github.com/mwitkow/go-conntrack v0.0.0-20161129095857-cc309e4a2223
go: k8s.io/kubernetes@v1.13.6: unrecognized import path "k8s.io/kubernetes" (https fetch: Get https://k8s.io/kubernetes?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: k8s.io/utils@v0.0.0-20190506122338-8fab8cb257d5: unrecognized import path "k8s.io/utils" (https fetch: Get https://k8s.io/utils?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: google.golang.org/grpc@v1.19.0: unrecognized import path "google.golang.org/grpc" (https fetch: Get https://google.golang.org/grpc?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/net@v0.0.0-20190613194153-d28f0bde5980: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sys@v0.0.0-20180909124046-d0be0721c37e: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/net@v0.0.0-20180906233101-161cd47e91fd: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding gopkg.in/resty.v1 v1.12.0
go: finding bitbucket.org/ww/goautoneg v0.0.0-20120707110453-75cd24fc2f2c
go: sigs.k8s.io/yaml@v1.1.0: unrecognized import path "sigs.k8s.io/yaml" (https fetch: Get https://sigs.k8s.io/yaml?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: golang.org/x/net@v0.0.0-20181114220301-adae6a3d119a: unrecognized import path "golang.org/x/net" (https fetch: Get https://golang.org/x/net?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sync@v0.0.0-20181221193216-37e7f081c4d4: unrecognized import path "golang.org/x/sync" (https fetch: Get https://golang.org/x/sync?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sync@v0.0.0-20181108010431-42b317875d0f: unrecognized import path "golang.org/x/sync" (https fetch: Get https://golang.org/x/sync?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: finding github.com/kr/logfmt v0.0.0-20140226030751-b84e30acd515
go: sigs.k8s.io/application@v0.0.0-20190404151855-67ae7f915d4e: unrecognized import path "sigs.k8s.io/application" (https fetch: Get https://sigs.k8s.io/application?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: golang.org/x/sync@v0.0.0-20180314180146-1d60e4601c6f: unrecognized import path "golang.org/x/sync" (https fetch: Get https://golang.org/x/sync?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: k8s.io/kube-openapi@v0.0.0-20181109181836-c59034cc13d5: unrecognized import path "k8s.io/kube-openapi" (https fetch: Get https://k8s.io/kube-openapi?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: k8s.io/apiextensions-apiserver@v0.0.0-20181213153335-0fe22c71c476: unrecognized import path "k8s.io/apiextensions-apiserver" (https fetch: Get https://k8s.io/apiextensions-apiserver?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
go: k8s.io/apimachinery@v0.0.0-20190221213512-86fb29eff628: unrecognized import path "k8s.io/apimachinery" (https fetch: Get https://k8s.io/apimachinery?go-get=1: dial tcp 35.201.71.162:443: i/o timeout)
个人理解，不是已经指定了mod和vender了吗？为什么还会有编译问题呢？

**Comment by runzexia** [comment]
在开发过程中，我们使用了k8s相关的一些代码生成工具，在安装工具时还是会扫描一下依赖是否合理。
这个可以配置一下`GOPROXY`来拉取依赖。
需要注意的是虽然项目的依赖管理使用了`go mod`，但是`k8s`的代码生成工具仍然依赖`GOPATH`的变量。
因此请把项目`$GOPATH/src/kubesphere.io/kubesphere`下，并保证shell中正确设置了`GOPATH`的值

**Comment by Liuyanglong** [comment]
增加设置：export GOPROXY=https://goproxy.cn
解决了。
