### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by lijinbang** [kubesphere/kubesphere#663]
centos7.5 安装失败然后截图如下
![QQ20190823-181826](https://user-images.githubusercontent.com/18083299/63585845-a2fffc00-c5d2-11e9-8970-b362a8451aee.png)
如果能够说明一下原因请回复一下！谢谢

**Comment by zryfish** [comment]
可以看下这个issue https://github.com/kubesphere/ks-installer/issues/33

**Comment by lilinlinlin** [comment]
cpu 、内存配置是什么呢

**Comment by lijinbang** [comment]
编辑了dns以后还是同样的报错。，而且重新安装了以后，配置文件重新恢复过来

**Comment by lijinbang** [comment]
目前安装到现在这种情况是因为什么呢？
![WX20190825-094939](https://user-images.githubusercontent.com/18083299/63644534-bbc8f880-c71d-11e9-9f47-ed25c0931c8d.png)

**Comment by lilinlinlin** [comment]
1、安装Jenkins时，需要等待sonarqube启动。
2、执行kubectl get pod -n kubesphere-devops-system看下面的ks-sonarqube-sonarqube是否running，也看下该pod的日志。kubectl describe pod -n kubesphere-devops-system  <pod name>

**Comment by zryfish** [comment]
close due to inactivity
