### ISSUE TITLE
删除&加入节点问题

### ISSUE THREAD

**Issue by DustFinger001** [kubesphere/kubesphere#665]
1.我自行安装的k8s环境，在使用kubectl 删除节点时，节点会被干净的删掉；但使用kubesphere 的k8s环境删除节点后，还需要calicoctl 再删除一次，是否可以做什么配置不调用calicoctl命令就干净的删除掉了。（我的k8s环境也是使用的calico插件）
2.节点加入时，如果其中一个节点ip曾经加入过，被删除后再加入，add-node 会提示错误，看 kubesphere 的安装代码，怀疑是加入过的节点ip被保存了，然后删除节点后同ip再次加入就会有冲突，这个地方有点不合理。
另外 #601 这个问题也麻烦帮看一下，kubeadm join 进来的节点使用的集群dns不正确，需要手工改。

**Comment by pixiake** [comment]
安装脚本也是用的kubeadm， kubectl  delete node之后   被删node节点的/etc/kubernetes下的相关文件不会被删除 ，如需重新加入集群需要手动删一下。
dns的配置为kubelet配置文件中的--cluster-dns    自行kubeadm  join不会修改kubelet的配置，所以需要手动修改下。

**Comment by DustFinger001** [comment]
@pixiake kubectl删除节点后，集群master节点执行calicoctl 还能看到已经被删的节点信息，需要再执行calicoctl 删除这个信息才行，我之前安装的纯k8s环境没有这个问题，这个问题应该是kubesphere使用的calico版本还有这个问题；并且修改集群现有节点ip以后k8s也不能正常识别（应该能正常识别才合理）。

**Comment by zryfish** [comment]
close due to inactivity
