### ISSUE TITLE
coredns经常无故CrashLoopBackOff

### ISSUE THREAD

**Issue by Liuyanglong** [kubesphere/kubesphere#669]
**Describe the bug(描述下问题)**
离线版2.0.2部署成功，成功运行了一段时间后coredns组件pod CrashLoopBackOff。重新install后恢复，但是又过一阵时间后再次CrashLoopBackOff。
![image](https://user-images.githubusercontent.com/1468470/63749899-fded6800-c8de-11e9-82f7-6cab77ba5f2b.png)

排查过程如下：

**1， 执行命令**
 `[root@ks-allinone kubernetes]# kubectl -n kube-system describe pod coredns-54f76f594-7kgk8`：
结果如下：
> Name:               coredns-54f76f594-7kgk8
> Namespace:          kube-system
> Priority:           2000000000
> PriorityClassName:  system-cluster-critical
> Node:               ks-allinone/192.168.10.139
> Start Time:         Tue, 27 Aug 2019 10:51:10 +0800
> Labels:             k8s-app=coredns
>                     pod-template-hash=54f76f594
> Annotations:        seccomp.security.alpha.kubernetes.io/pod: docker/default
> Status:             Running
> IP:                 10.233.87.136
> Controlled By:      ReplicaSet/coredns-54f76f594
> Containers:
>   coredns:
>     Container ID:  docker://40137e417bb874980431a13ca9bde4f43d14aba1faa01121cdbf93c357e26fa3
>     Image:         192.168.10.139:5000/google_containers/coredns:1.4.0
>     Image ID:      docker://sha256:a9e015907f63653e004cdd4141fd7ca388451839081024133861586aa43613a3
>     Ports:         53/UDP, 53/TCP, 9153/TCP
>     Host Ports:    0/UDP, 0/TCP, 0/TCP
>     Args:
>       -conf
>       /etc/coredns/Corefile
>     State:          Waiting
>       Reason:       CrashLoopBackOff
>     Last State:     Terminated
>       Reason:       Completed
>       Exit Code:    0
>       Started:      Tue, 27 Aug 2019 15:23:08 +0800
>       Finished:     Tue, 27 Aug 2019 15:24:48 +0800
>     Ready:          False
>     Restart Count:  46
>     Limits:
>       memory:  170Mi
>     Requests:
>       cpu:        100m
>       memory:     70Mi
>     Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
>     Environment:  <none>
>     Mounts:
>       /etc/coredns from config-volume (rw)
>       /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-rcnvf (ro)
> Conditions:
>   Type              Status
>   Initialized       True 
>   Ready             False 
>   ContainersReady   False 
>   PodScheduled      True 
> Volumes:
>   config-volume:
>     Type:      ConfigMap (a volume populated by a ConfigMap)
>     Name:      coredns
>     Optional:  false
>   coredns-token-rcnvf:
>     Type:        Secret (a volume populated by a Secret)
>     SecretName:  coredns-token-rcnvf
>     Optional:    false
> QoS Class:       Burstable
> Node-Selectors:  beta.kubernetes.io/os=linux
> Tolerations:     CriticalAddonsOnly
>                  node-role.kubernetes.io/master:NoSchedule
>                  node.kubernetes.io/not-ready:NoExecute for 300s
>                  node.kubernetes.io/unreachable:NoExecute for 300s
> Events:
>   Type     Reason     Age                     From                  Message
>   ----     ------     ----                    ----                  -------
>   Warning  Unhealthy  17m (x206 over 3h2m)    kubelet, ks-allinone  Liveness probe failed: HTTP probe failed with statuscode: 503
>   Warning  BackOff    8m21s (x481 over 175m)  kubelet, ks-allinone  Back-off restarting failed container
>   Normal   Pulled     3m31s (x45 over 3h3m)   kubelet, ks-allinone  Container image "192.168.10.139:5000/google_containers/coredns:1.4.0" already present on machine
> 

**2，执行命令：
`kubectl -n kube-system logs coredns-54f76f594-7kgk8`**
结果为：

> E0827 07:24:41.958601       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:260: Failed to list *v1.Namespace: Get https://10.233.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: connect: no route to host
> E0827 07:24:43.960595       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:260: Failed to list *v1.Namespace: Get https://10.233.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: connect: no route to host
> E0827 07:24:45.962617       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:260: Failed to list *v1.Namespace: Get https://10.233.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: connect: no route to host
> E0827 07:24:47.964586       1 reflector.go:134] github.com/coredns/coredns/plugin/kubernetes/controller.go:260: Failed to list *v1.Namespace: Get https://10.233.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.233.0.1:443: connect: no route to host
> [INFO] SIGTERM: Shutting down servers then terminating

**3，根据提示手动curl命令：
`curl -i -k 'https://10.233.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0'`**
结果为：
```
HTTP/1.1 403 Forbidden
Content-Type: application/json
X-Content-Type-Options: nosniff
Date: Tue, 27 Aug 2019 07:29:12 GMT
Content-Length: 320

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "namespaces is forbidden: User \"system:anonymous\" cannot list resource \"namespaces\" in API group \"\" at the cluster scope",
  "reason": "Forbidden",
  "details": {
    "kind": "namespaces"
  },
  "code": 403
}
```

**4，查看ipvs，执行命令：`ipvsadm -Ln`**
结果如下：
![image](https://user-images.githubusercontent.com/1468470/63750493-29bd1d80-c8e0-11e9-9c78-ff5dae99d71c.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 离线版 2.0.2

**Environment(环境的硬件配置)**
单节点版：8核，16G内存，200G磁盘

请帮忙看下，是哪儿出了问题， 这么解决？

**Comment by zryfish** [comment]
执行  docker ps | grep kube-apiserver 看下 uptime 检查下是否 kube-apiserver 被重启过。如果是的话，需要看下 kube-apiserver 的日记看下为啥会重启

**Comment by Liuyanglong** [comment]
@zryfish  没有重启过

**Comment by zryfish** [comment]
看下 kube-apiserver 日志，有错误信息么

**Comment by Liuyanglong** [comment]
@zryfish 看上去没有~很奇怪

**Comment by sheeplinjie** [comment]
我也有这样的问题，怎么解决
