### ISSUE TITLE
在使用s2i构建镜像时，无法使用maven私服nexus3

### ISSUE THREAD

**Issue by Divernia** [kubesphere/kubesphere#671]
使用s2i构建镜像拉取nexus3私服中的依赖一直显示Connection timed out
![image](https://user-images.githubusercontent.com/7236480/63823141-5a0ac780-c985-11e9-95d4-e9c63ccfed60.png)

**Comment by soulseen** [comment]
这像是网络问题，可以测试下进入容器中能正常访问nexus3地址吗

**Comment by runzexia** [comment]
如果拉取代码正常的话说明s2i容器是正常可以通外网的。

看日志的话像是到nexus网络不通，猜测可能是防火墙之类的配置问题。

**Comment by Divernia** [comment]
> 这像是网络问题，可以测试下进入容器中能正常访问nexus3地址吗

进入到容器中可以正常ping通并且可以下载私服中的依赖。

**Comment by Divernia** [comment]
> 如果拉取代码正常的话说明s2i容器是正常可以通外网的。
> 
> 看日志的话像是到nexus网络不通，猜测可能是防火墙之类的配置问题。

容器可以访问私服，私服已经开启匿名访问。
在一个干净的Centos7环境下装了maven是可以正常编译该项目的。

**Comment by runzexia** [comment]
s2i会启动docker run的容器执行制作镜像过程，可以试下docker run的容器是否可以正常访问nexus

**Comment by Divernia** [comment]
> s2i会启动docker run的容器执行制作镜像过程，可以试下docker run的容器是否可以正常访问nexus

容器中可以正常访问nexus，也可以正常下载依赖，所以比较纳闷。

**Comment by soulseen** [comment]
上面的测试和s2i 运行的pod在同一个节点吗，能否登上pod所在节点，执行`iptables -t nat -S`, 看下是否存在
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
这条规则

**Comment by soulseen** [comment]
> > 这像是网络问题，可以测试下进入容器中能正常访问nexus3地址吗
> 
> 进入到容器中可以正常ping通并且可以下载私服中的依赖。

s2i pod的容器中能正常访问的话，可能是执行构建的容器的网络问题，s2i的构建是调用宿主机的docker.socket去运行构建容器的
