### ISSUE TITLE
工具箱 kubectl 支持 completion

### ISSUE THREAD

**Issue by k0ngk0ng** [kubesphere/kubesphere#674]
是否能支持 kubectl 自动补全

**Comment by zryfish** [comment]
下一版本就会支持，目前可以手动加下配置

**Comment by k0ngk0ng** [comment]
请问手动配置如何加？服务器上的shell已经配置过自动补全的了

**Comment by zryfish** [comment]
可以参考 https://kubernetes.io/docs/tasks/tools/install-kubectl/#optional-kubectl-configurations ，进入到 pod 里执行这个命令

**Comment by zryfish** [comment]
Duplicate of #826
