### ISSUE TITLE
请问kubesphere 前端应用是在源码的哪个目录？用的什么前端框架和ui ？

### ISSUE THREAD

**Issue by wuchencm** [kubesphere/kubesphere#675]
请问kubesphere 前端应用是在源码的哪个目录？用的什么前端框架和ui ？

**Comment by rayzhou2017** [comment]
前端还没有开放出来，预计要等两个月的样子，会在kubesphere的一个单独的repo下。用的是react，mobx，koajs等

**Comment by mingzhuyang** [comment]
没有前端怎么用

**Comment by mingzhuyang** [comment]
我还找个半天，一个js文件都没有，😂

**Comment by rayzhou2017** [comment]
https://kubesphere.io/docs/ 有下载地址和安装说明

**Comment by mingzhuyang** [comment]
看到了，但是这种产品肯定都要拿过来改一下的😂

**Comment by rayzhou2017** [comment]
了解，肯定会开源的，稍等时间

**Comment by ngxlua** [comment]
还要2个月， 差不多得12月份了， 看前面的 issue 我乐观的以为 10月中下旬就可以...

**Comment by zz4536** [comment]
谢谢大神

**Comment by zryfish** [comment]
close due to inactivity
