### ISSUE TITLE
查看helm应用模板时报错

### ISSUE THREAD

**Issue by njxiaohan** [kubesphere/kubesphere#676]
<img width="1674" alt="WechatIMG278" src="https://user-images.githubusercontent.com/12640161/63849259-4c286700-c9c4-11e9-8e5d-4e583cb94a9d.png">

**Comment by njxiaohan** [comment]
错误信息：
[{"@type":"type.googleapis.com/openpitrix.ErrorDetail","error_name":"describe_resources_failed","cause":"dial tcp 10.233.52.199:3306: connect: connection refused"}]
已经查过了，所有命名空间下都没有clusterIP为10.233.52.199的资源。

**Comment by wansir** [comment]
可以到平台管理->服务组件页面，检查一下系统组件是否都正常

![image](https://user-images.githubusercontent.com/8263040/63920815-37a3a780-ca74-11e9-80ca-ca38303301c4.png)
