### ISSUE TITLE
sonarqube容器组一直重启

### ISSUE THREAD

**Issue by guoh1988** [kubesphere/kubesphere#677]
sonarqube容器组一直重启
**安装环境的硬件配置**
使用kubesphere-all-offline-advanced-2.0.2.tar.gz 安装 centos7.4 VMware虚拟机)
日志如下：
2019.08.29 02:43:00 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2019.08.29 02:43:00 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2019.08.29 02:43:00 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonarqube/temp/conf/es
2019.08.29 02:43:00 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2019.08.29 02:43:00 INFO  app[][o.e.p.PluginsService] no modules loaded
2019.08.29 02:43:00 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2019.08.29 02:43:07 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2019.08.29 02:43:07 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonarqube]: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -cp ./lib/common/*:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.2.5.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process4726797833832607326properties
2019.08.29 02:43:07 INFO  web[][o.s.p.ProcessEntryPoint] Starting web
2019.08.29 02:43:07 INFO  web[][o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
2019.08.29 02:43:08 INFO  web[][o.s.c.e.CoreExtensionsLoader] Loaded core extensions: 
2019.08.29 02:43:08 INFO  web[][o.e.p.PluginsService] no modules loaded
2019.08.29 02:43:08 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
2019.08.29 02:43:08 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
2019.08.29 02:43:08 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2019.08.29 02:43:09 INFO  web[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [127.0.0.1:9001]
2019.08.29 02:43:09 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 7.4.0.18908 / a4d0983e8057356b19996995343296311fbcc2ed
2019.08.29 02:43:09 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://ks-sonarqube-postgresql:5432/sonarDB
2019.08.29 02:43:10 INFO  web[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /opt/sonarqube
2019.08.29 02:43:10 INFO  web[][o.s.s.u.SystemPasscodeImpl] System authentication by passcode is disabled
2019.08.29 02:43:10 ERROR web[][o.s.s.p.Platform] Web server startup failed: Current version is too old. Please upgrade to Long Term Support version firstly.
2019.08.29 02:43:13 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2019.08.29 02:43:13 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2019.08.29 02:43:13 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
2019.08.29 02:43:13 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143

**Comment by runzexia** [comment]
可以尝试先卸载sonarqube
`helm delete --purge ks-sonarqube`
再删除掉sonarqube的pvc
`
kubectl delete -n kubesphere-devops-system pvc ks-sonarqube-postgresql
`
最后重新执行一下安装过程来尝试一下

**Comment by guoh1988** [comment]
可以了，UI部分什么时候可以单独部署

**Comment by runzexia** [comment]
2.1 解决了这个问题
/close
