### ISSUE TITLE
新安装的ks，日志查询报错

### ISSUE THREAD

**Issue by zhouleyan** [kubesphere/kubesphere#680]
![image](https://user-images.githubusercontent.com/7187495/63929088-6a08d100-ca83-11e9-9e5e-df684ca8b701.png)
刚装的kubesphere，没有任何操作。单节点nfs。

{
 "message": "readObjectStart: expect { or n, but found \u0000, error found in #0 byte of ...||..., bigger context ...||..."
}

**Comment by zhouleyan** [comment]
已解决，因为系统盘容量不够，将数据盘路径软连接至”/var/lib/docker“，导致需要修改日志收集挂载路径配置。

**Comment by huanggze** [comment]
如果主机环境修改过容器日志挂载路径，安装 ks-installer 时注意修改 containersLogMountedPath 参数。

如果已安装，可以通过手动更新 kubesphere-logging-system 下的 logging-fluentbit-operator ConfigMap，并重启 fluent-bit-operator 和 fluent-bit 解决。

![image](https://user-images.githubusercontent.com/22350668/63991851-e6e78980-cb1b-11e9-8d63-13e1145f0479.png)

**Comment by lijujntao120** [comment]
集群模式搭建，单节点nfs,同样是软连了docker的物理挂载点配置已修改，日志还是出不来！！方便指导一下吗??
![image](https://user-images.githubusercontent.com/35087233/64307275-2b65a000-cfc8-11e9-9131-3c8403793383.png)
![image](https://user-images.githubusercontent.com/35087233/64307296-3c161600-cfc8-11e9-8266-b77afa98e47d.png)

**Comment by lijujntao120** [comment]
![image](https://user-images.githubusercontent.com/35087233/64307312-489a6e80-cfc8-11e9-99dc-9cd8dd8c03e1.png)

**Comment by lijujntao120** [comment]
![image](https://user-images.githubusercontent.com/35087233/64307522-ebeb8380-cfc8-11e9-8af2-628b98ac3694.png)
