### ISSUE TITLE
无法配置用户邮箱

### ISSUE THREAD

**Issue by zhoulhb** [kubesphere/kubesphere#683]
安装模式：单机模式和集群模式

问题：
安装成功后更改admin用户邮箱
![image](https://user-images.githubusercontent.com/34292457/64001006-7cdddd00-cb39-11e9-92ad-701f10f4a0dc.png)

将默认邮箱地址改为zhoul@asto-inc.com，点击保存，系统报错：invalid email
![image](https://user-images.githubusercontent.com/34292457/64001142-c75f5980-cb39-11e9-882e-628feb670c03.png)

新建用户也无法配置邮箱

**Comment by wansir** [comment]
这里换成把邮箱地址换成小写就可以保存了

**Comment by zhoulhb** [comment]
按照你的方法已经解决了，谢谢！
