### ISSUE TITLE
能否让SonarQube支持C/C++的代码检查

### ISSUE THREAD

**Issue by klj890** [kubesphere/kubesphere#699]
需求如题。
有个开源的插件可以支持C/C++的代码检查。
[This repository contains a SonarQube plugin implementing C++ support.](https://github.com/SonarOpenCommunity/sonar-cxx)
能否在下个版本中支持？

**Comment by runzexia** [comment]
2.1 版本会添加支持

**Comment by runzexia** [comment]
solved by https://github.com/kubesphere/ks-installer/pull/68/files
/close
