### ISSUE TITLE
容器日志无法显示

### ISSUE THREAD

**Issue by lijujntao120** [kubesphere/kubesphere#703]
集群模式搭建，单节点nfs,同样是软连了docker的物理挂载点配置已修改，日志显示出不来！！

![image](https://user-images.githubusercontent.com/35087233/64315106-a8ead980-cfe3-11e9-925e-528357377de2.png)

![image](https://user-images.githubusercontent.com/35087233/64315114-aee0ba80-cfe3-11e9-86dc-c8ef0ab20cdc.png)

![image](https://user-images.githubusercontent.com/35087233/64315121-b30cd800-cfe3-11e9-9406-067e8c4a5ff1.png)

![image](https://user-images.githubusercontent.com/35087233/64315172-dafc3b80-cfe3-11e9-86c7-68bb3bdf5e98.png)

**Comment by lijujntao120** [comment]
怎么没人回复 一下！！

**Comment by huanggze** [comment]
#680 细化了操作步骤,再检查看看.  

如需要远程协助,可以加入kubesphere 技术微信群,与我们沟通.  群链接见官网底部微信图标 https://kubesphere.io/

**Comment by lijujntao120** [comment]
已经解决，之前比较迷惑的是把物理机和容器服务全重启也不生效
解决思路，要先将fluent bit删除然后重建才能使修改的文件生效，并重启fluent operator 
修改的文件见图片
![image](https://user-images.githubusercontent.com/35087233/64416704-48829780-d0ca-11e9-812b-8309d2ccc1f7.png)

![image](https://user-images.githubusercontent.com/35087233/64416760-6223df00-d0ca-11e9-89e3-4f44d77698a0.png)


界面上不能删除和重启，需要使用以下命令处理

# 修改  ConfigMap
kubectl edit -n kubesphere-logging-system configmaps logging-fluentbit-operator

# 删除 fluent-bit Daemonset
kubectl delete -n kubesphere-logging-system daemonsets fluent-bit

# 重启 fluent-bit-operator Deployment
kubectl scale -n kubesphere-logging-system deployment logging-fluentbit-operator --replicas=0
kubectl scale -n kubesphere-logging-system deployment logging-fluentbit-operator --replicas=1

# 检查 fluent-bit 是否起来
kubectl get po -n kubesphere-logging-system
