### ISSUE TITLE
Devops的项目数量显示Bug

### ISSUE THREAD

**Issue by geniussheep** [kubesphere/kubesphere#704]
本人使用 admin 用户在指定企业空间新建了两个devops的项目，如下图： 
![image](https://user-images.githubusercontent.com/7587017/64318766-6e863a00-cfed-11e9-88aa-2c7d547c6c3e.png)
进入到devops项目管理，如下图：
![image](https://user-images.githubusercontent.com/7587017/64318825-9bd2e800-cfed-11e9-94ed-1d9c23304269.png)
然后登陆个人账户（此账户未加入到该企业空间），如下图：
![image](https://user-images.githubusercontent.com/7587017/64319026-fff5ac00-cfed-11e9-8c5a-9ee1d36ddef4.png)
然后点击进入devops的管理页面，但是没有看到任何devops的项目 
![image](https://user-images.githubusercontent.com/7587017/64319085-20256b00-cfee-11e9-9d42-854175aea7b2.png)

但是同样的项目的管理，进入后能看到admin新建的项目，如下图
![image](https://user-images.githubusercontent.com/7587017/64319282-87dbb600-cfee-11e9-8a8b-65ae4890a1aa.png)

企业空间成员管理如下图：
![image](https://user-images.githubusercontent.com/7587017/64319332-aa6dcf00-cfee-11e9-853d-d33fd4c2c414.png)

**Comment by runzexia** [comment]
数量显示的问题会在2.1有临时fix，3.0完全fix

**Comment by shaowenchen** [comment]
out of date
/close
