### ISSUE TITLE
Centos7.6 All-in-one 安装requirements（YUM）报错！

### ISSUE THREAD

**Issue by PYIsOk** [kubesphere/kubesphere#706]
在Centos7.6下离线安装KubeSphere-all-offline-advanced-2.0.2,执行到 Install packages requirements（YUM）报错

环境的硬件配置如下：(虚拟机)
1节点：8cpu/16g 系统磁盘100G

错误如下：
![image](https://user-images.githubusercontent.com/37820823/64412212-80391180-d0c1-11e9-9c66-ad4ee52e76e8.png)

**Comment by Forest-L** [comment]
这个是缺乏ebtables包;
链接：https://pan.baidu.com/s/14Uh4RIrHHt7h8ZH0fgSdkQ 
提取码：1pn1 
复制这段内容后打开百度网盘手机App，操作更方便哦
临时解决方法：下载链接中的ebtables包，然后yum install -y ebtables-2.0.10-16.el7.x86_64.rpm

**Comment by PYIsOk** [comment]
![image](https://user-images.githubusercontent.com/37820823/64418076-e70ff800-d0cc-11e9-829b-e59db705536a.png)
请问 安装到这儿  是什么原因导致的呢？

**Comment by PYIsOk** [comment]
@Forest-L  您好
![image](https://user-images.githubusercontent.com/37820823/64418182-1d4d7780-d0cd-11e9-9945-0233bca07935.png)
这是什么原因导致的呢？

**Comment by PYIsOk** [comment]
@Forest-L 您好，这是什么原因导致的呢？
![image](https://user-images.githubusercontent.com/37820823/64418266-40782700-d0cd-11e9-996b-80c66e6fa68f.png)

**Comment by Forest-L** [comment]
原因应该是机器的dns配置问题，请检查下本机的/etc/resolv.conf中是否有不可用的dns

**Comment by PYIsOk** [comment]
@Forest-L 您好 我是离线安装 也需要查看不可用的DNS吗？

**Comment by Forest-L** [comment]
1、再执行一遍，
2、查看kubectl describe pod看下
3、还不行的话，可以提供远程方式，我们上去看下

**Comment by PYIsOk** [comment]
可以了，把不可用的DNS注释掉，安装成功了，十分感谢您！ @Forest-L
