### ISSUE TITLE
Centos 7 按照失败

### ISSUE THREAD

**Issue by zhuyuehao** [kubesphere/kubesphere#707]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
安装kubesphere-all-advanced-2.0.2报错

**安装环境的硬件配置**
物理机
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
![image](https://user-images.githubusercontent.com/25274630/64416626-1c671680-d0ca-11e9-964a-3501313517ab.png)

**Installer版本**
kubesphere-all-advanced-2.0.2

**Comment by Forest-L** [comment]
1、在线和离线安装，机器需要干净的；
2、在线安装需要能连网，且确定机器的安装源能用。
3、从截图看不出来用的是什么操作系统，如果是centos，用yum clean all;yum makecache试下。

**Comment by zryfish** [comment]
close due to inactivity
