### ISSUE TITLE
Multi-Node 模式，开放外网之后访问gitlab default backend - 404

### ISSUE THREAD

**Issue by dazsco** [kubesphere/kubesphere#709]
80端口代理访问界面显示
default backend - 404

443端口代理访问显示
400 Bad Request 
The plain HTTP request was sent to HTTPS port
nginx

已经重新安装过一次。

**Comment by dazsco** [comment]
jenkins
harbor
sonarqube
开放外网访问后均正常

**Comment by dazsco** [comment]
明白是咋回事了，做了nginx代理，但是gitlab登录密码按照文档上  admin / P@88w0rd 不正确啊

**Comment by dazsco** [comment]
gitlab的LDAP模式和管理员一样的密码，但是root的密码是多少呢。我改了管理员密码，jenkins登录不了。

**Comment by dazsco** [comment]
@runzexia 请问一下gitlab root用户的密码默认是多少呢。

**Comment by runzexia** [comment]
https://kubesphere.io/docs/advanced-v2.0/zh-CN/installation/gitlab-installation/#___gatsby 
账号密码与kubesphere登陆相同

**Comment by zryfish** [comment]
close due to inactivity
