### ISSUE TITLE
应用路由不稳定，经常无法连接

### ISSUE THREAD

**Issue by fjs4409** [kubesphere/kubesphere#713]
部署了12个项目，通过应用路由配置域名进行访问，如下图：
![image](https://user-images.githubusercontent.com/17290444/64510368-9559ae80-d314-11e9-907a-cb058f349e17.png)

出现的问题是，有时候访问很正常，速度很快， 隔一段时间就出现卡顿，甚至无法访问的情况，想请教一下这种状况如何解决？
![image](https://user-images.githubusercontent.com/17290444/64510411-b9b58b00-d314-11e9-9962-7c442cbc0e6c.png)

另外发现一个BUG， 服务超过一页， 在应用路由配置规则的时候， 会选择不到第二页的服务。
通过配置文件配的规则如下：
![image](https://user-images.githubusercontent.com/17290444/64510834-98a16a00-d315-11e9-83bb-d681bf4f7e4c.png)
实际编辑无法选择服务：
![image](https://user-images.githubusercontent.com/17290444/64510854-a3f49580-d315-11e9-8e42-9c50a3773cf1.png)

**Comment by fjs4409** [comment]
有大佬帮忙看看问题吗？ 应用路由访问经常不通

**Comment by zryfish** [comment]
你看下你的机器到网关的ip连接是不是稳定，这个报错是连接超时了
