### ISSUE TITLE
能不能在普通的物理机上安装

### ISSUE THREAD

**Issue by sj-dev** [kubesphere/kubesphere#715]
现在在普通的物理机上安装Centos7.6，离线安装也好，在线安装也好，都是有很多错误的，请问一下有没有经过离线或者在线安装在普通物理机上测试过的。

**Comment by Forest-L** [comment]
1、测试过的
2、资源目前至少要8核，16G
3、报什么错呢，带上截图
4、如果是离线安装的，请下载centos7.6的依赖包提前体验，下个版本会支持。
链接：https://pan.baidu.com/s/1BcdJL5CJMqgVdhmzSiNiag 
提取码：txt7

**Comment by sj-dev** [comment]
我重启下载了centos7.5，第一次离线安装失败，我把防火墙停了，安装成功了。谢谢啊，有问题再问。
