### ISSUE TITLE
FAILED - RETRYING: Update package management cache (YUM) (4 retries left).

### ISSUE THREAD

**Issue by zhuyuehao** [kubesphere/kubesphere#717]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
FAILED - RETRYING: Update package management cache (YUM) (4 retries left).
**安装环境的硬件配置**
centos 7
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
FAILED - RETRYING: Update package management cache (YUM) (4 retries left).
**Installer版本**
2.0.2

**Comment by Forest-L** [comment]
@zhuyuehao 
1、配置描述下
2、错误截全，好排查问题

**Comment by zryfish** [comment]
close due to inactivity
