### ISSUE TITLE
all-in-one 离线安装包 (2.0.2) 不支持centos7.6版本

### ISSUE THREAD

**Issue by liuts** [kubesphere/kubesphere#721]
**Describe the bug(描述下问题)**
all-in-one 离线安装包 (2.0.2) 不支持centos7.6版本
原因是：
/root/kubesphere-all-offline-advanced-2.0.2/Repos
目录下面没有centos-7.6-amd64.iso文件

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.0.2

**Environment(环境的硬件配置)**

1 masters:  8cpu/16g

**To Reproduce(复现步骤)**
$ curl -L https://kubesphere.io/download/offline/advanced-2.0.2 > advanced-2.0.2.tar.gz && tar -zxf advanced-2.0.2.tar.gz && cd kubesphere-all-offline-advanced-2.0.2/scripts

**Comment by Forest-L** [comment]
1、官方centos7.6系统安装下一个版本发布。
2、可以参考这个issue，里面单独有centos7.6的iso包，
https://github.com/kubesphere/ks-installer/issues/23

**Comment by liuts** [comment]
多谢
