### ISSUE TITLE
华为云全新安装的CentOS Linux release 7.5.1804 (Core) 安装失败

### ISSUE THREAD

**Issue by latermonk** [kubesphere/kubesphere#722]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**

安装失败

**安装环境的硬件配置**
华为云 CentOS Linux release 7.5.1804 (Core)

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
fatal: [ks-allinone]: FAILED! =>
`{"changed": true, "cmd": "/usr/local/bin/helm upgrade --install metrics-server /etc/kubesphere/metrics-server --namespace kube-system", "delta": "0:00:00.174379", "end": "2019-09-11 11:31:20.955787", "msg": "non-zero return code", "rc": 1, "start": "2019-09-11 11:31:20.781408", "stderr": "Error: could not find a ready tiller pod", "stderr_lines": ["Error: could not find a ready tiller pod"], "stdout": "", "stdout_lines": []}
`

**Installer版本**

curl -L https://kubesphere.io/download/stable/advanced-2.0.2 > advanced-2.0.2.tar.gz \
&& tar -zxf advanced-2.0.2.tar.gz && cd kubesphere-all-advanced-2.0.2/scripts

**Comment by Forest-L** [comment]
1、根据信息看，是helm的服务端tiller没有安装好，请再执行一遍看
