### ISSUE TITLE
【前端开源事宜】是否敲定时间了哇

### ISSUE THREAD

**Issue by ngxlua** [kubesphere/kubesphere#724]
测试了一下，kubesphere 在管理平台中非常具有竞争力，但没有开源前端导致我们公司很难进一步的调研、使用，

看到过往的 issue 表示是一定会开源的，只是还需要时间，不知道贵团队 10 月份能不能出一版呢，

非常感谢

**Comment by liuts** [comment]
期待前端开源

**Comment by rayzhou2017** [comment]
会开源的，现在在忙2.1.0发布
