### ISSUE TITLE
多节点离线安装，ks-sonarqube总是起不来

### ISSUE THREAD

**Issue by PYIsOk** [kubesphere/kubesphere#726]
**问题描述**
多节点离线安装，ks-sonarqube总是起不来，安装到 Sonarqube | Deploy Sonarqube 就会报错
**安装环境的硬件配置**
8c/16g 系统盘 100G 虚拟机

**错误信息或截图**
![8ZZ$I XU`LE3M7V5JH__C3V](https://user-images.githubusercontent.com/37820823/64685780-1c945700-d4ba-11e9-93ed-f30092bbc940.png)
**Installer版本**
2.02

**Comment by Forest-L** [comment]
1、检查下helm是否正常，helm --version包含服务端和客户端。
2、卸载再执行一遍。

**Comment by liuts** [comment]
1，防火网firewalld 要关闭
2，查看dns配置文件里面有没有ping不通的dns  ip。有的话删除。

**Comment by PYIsOk** [comment]
@Forest-L 最后把配置文件中sonarqube_enable设置为false安装成功，可是这个没有打开有什么影响吗？或者如何打开？要重新安装吗？

**Comment by Forest-L** [comment]
@PYIsOk  
1、sonarqube的功能可以搜索下，代码质量管理平台；
2、cicd这块有问题；
3、如果需要的话，是要重新安装

**Comment by zhangjun050754** [comment]
这边确实有问题 一直卡在这边 重装了好几次
