### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by DasWolke** [kubesphere/kubesphere#727]
It's not possible to install this software as the containers hosted on dockerhub.qingcloud.com all require authentication, so they can not be pulled.

**Comment by Forest-L** [comment]
1、在线安装确认网络是否是通的；
2、再执行一遍，看情况；
3、第二步还是报上面的错误则手动在机器上docker login dockerhub.qingcloud.com,用户名和密码都是guest试下。
![image](https://user-images.githubusercontent.com/50984129/64699222-e74a3200-d4d6-11e9-8771-9c883f1efa3b.png)

**Comment by DasWolke** [comment]
Worked, thank you. :)
