### ISSUE TITLE
Links to the Offline Version are extremely slow from Europe

### ISSUE THREAD

**Issue by satrobit** [kubesphere/kubesphere#734]
Links to the Offline Version are extremely slow from Europe. Are you able to provide a mirror to those files (https://kubesphere.io/download/offline/advanced-2.0.2 ) from outside of China?

**Comment by FeynmanZhou** [comment]
Hi @satrobit, do you have Kubernetes cluster? If so, we recommed you to [install KubeSphere in existing cluster](https://github.com/kubesphere/ks-installer).

**Comment by satrobit** [comment]
Thanks for the quick response.
I tried that way and even though I had some other problems It wasn't related to this issue. Anyway, this was way faster and smoother than installing the offline version.
So I consider this issue closed. Thank you again.

**Comment by FeynmanZhou** [comment]
> Thanks for the quick response.
> I tried that way and even though I had some other problems It wasn't related to this issue. Anyway, this was way faster and smoother than installing the offline version.
> So I consider this issue closed. Thank you again.

@satrobit Have you installed KubeSphere successfully? If any other problems you need help, join the [Slack Channel](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE) so we can help you to solve it in time.

**Comment by satrobit** [comment]
@FeynmanZhou I haven't yet. Thank you for your suggestion. I'll join the Slack Channel and ask my questions regarding the problem.
