### ISSUE TITLE
【新增功能建议】界面上提供部署界面，用户直接上传jar或者war包，平台自动以容器的形式部署好

### ISSUE THREAD

**Issue by fairychild1** [kubesphere/kubesphere#735]
时速云有提供类似功能
![image](https://user-images.githubusercontent.com/15730272/64748504-f5369c00-d544-11e9-8c6f-01cede1559a5.png)
![image](https://user-images.githubusercontent.com/15730272/64748509-f9fb5000-d544-11e9-9d0c-c6c92316aacf.png)

**Comment by zryfish** [comment]
2.1会提供
