### ISSUE TITLE
ansible版本问题导致安装失败

### ISSUE THREAD

**Issue by zky001** [kubesphere/kubesphere#741]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
1.安装文件按照步骤走下来，因为检查ansible版本不是2.7.0出错，但是我们的OS文件夹中的requirements.txt里写着ansible版本得是2.7.6，改成2.7.0后，又提示出错
![image](https://user-images.githubusercontent.com/9131265/64771684-f33efe00-d581-11e9-86ca-8d04ecbcc288.png)
.
**安装环境的硬件配置**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
![image](https://user-images.githubusercontent.com/9131265/64771888-4d3fc380-d582-11e9-8e80-a77b1e2a622f.png)

**Installer版本**

**Comment by zky001** [comment]
尝试了一下，uninstall报错如下
![image](https://user-images.githubusercontent.com/9131265/64930079-d0ea0080-d85f-11e9-9de3-2cd3d63808df.png)

**Comment by zky001** [comment]
@Forest-L uninstall时和install时遇到的问题类似

**Comment by Forest-L** [comment]
可以提供tv连上去看下吗

**Comment by Forest-L** [comment]
yum remove anisble @zky001

**Comment by zky001** [comment]
![image](https://user-images.githubusercontent.com/9131265/64933854-b9b80c80-d879-11e9-8c57-ccfa0a4955f6.png)
@Forest-L 还是之前那个问题   ansible版本不是2.7.0出错了

**Comment by Forest-L** [comment]
原因是192.168.0.13机器上安装了python3的版本，但是官方给的ansible版本里面不支持python3，建议可以在另外两台机器上安装或者安装完之后再安装python3版本。
@zky001 
```
(base) [root@node1 conf]# repoquery
  File "/usr/bin/repoquery", line 139
    print 'digraph packages {',
                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('digraph packages {', end=" ")?
```

**Comment by zky001** [comment]
@Forest-L 
按照兄弟你之前的思路，安装过程一直没问题  但是就是卡在下面这个错误这里
![image](https://user-images.githubusercontent.com/9131265/65008378-be44f980-d93b-11e9-978f-67e05a37ddfc.png)

**Comment by zky001** [comment]
configmaps "kubelet-config-1.12" is forbidden: User "system:bootstrap:xeah2a" cannot get resource "configmaps" in API group "" in the namespace "kube-system"", "stderr_lines": ["configmaps "kubelet-config-1.12" is forbidden: User "system:bootstrap:xeah2a" cannot get resource "configmaps" in API group "" in the namespace "kube-system"

**Comment by Forest-L** [comment]
1、报错来看，Kubelet bootstrap认证有问题，
2、之前看vars.yaml有的信息是需要配的；
3、uninstall看下，不行麻烦把机器信息发下至官网

**Comment by Forest-L** [comment]
@zky001
