### ISSUE TITLE
设置用户为“workspace-regular”时出错

### ISSUE THREAD

**Issue by jerryjedi** [kubesphere/kubesphere#743]
具有“workspace-admin"角色的用户要求用户到一个workspace，且准备授予“workspace-regular"角色时报错。
<img width="1041" alt="sp_2019-09-13_09-54-55" src="https://user-images.githubusercontent.com/7875026/64832539-eddac580-d60c-11e9-8a27-38f7693ce65a.png">

授予“workspace-admin"没有问题。

**Comment by wansir** [comment]
#650 fixed
