### ISSUE TITLE
如何查看异常容器组

### ISSUE THREAD

**Issue by jerryjedi** [kubesphere/kubesphere#746]
进入企业空间时，看到显示有3个异常容器组，请问如何查看是哪3个？

<img width="435" alt="sp_2019-09-14_21-52-15" src="https://user-images.githubusercontent.com/7875026/64909090-20361100-d73a-11e9-8119-4c1bbdb04833.png">

这是当前的，还是历史的？ 对现在系统的影响是如何的？如何检查和判断？

**Comment by huanggze** [comment]
目前这里显示有一点问题。恢复正常后，0 数值没有正确。2.1版本会有改进
