### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by jerryjedi** [kubesphere/kubesphere#748]
示例#13， 文档有错误：
<img width="902" alt="sp_2019-09-15_11-55-29" src="https://user-images.githubusercontent.com/7875026/64916395-e30c6600-d7af-11e9-8ddf-4b5cb1279a43.png">

<img width="547" alt="sp_2019-09-15_11-56-59" src="https://user-images.githubusercontent.com/7875026/64916400-fc151700-d7af-11e9-9ce8-df138a1187eb.png">

**Comment by FeynmanZhou** [comment]
Thanks for the feedback, this typo has been fixed by @zheng1
