### ISSUE TITLE
Unable to restart service docker

### ISSUE THREAD

**Issue by zhuyuehao** [kubesphere/kubesphere#750]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
RUNNING HANDLER [container-engine/docker : Docker | reload docker] ***************************************************************************************************************************************
Monday 16 September 2019  13:48:49 +0800 (0:00:00.141)       0:01:18.489 ****** 
fatal: [ks-allinone]: FAILED! => {"changed": false, "msg": "Unable to restart service docker: Job for docker.service failed because the control process exited with error code. See \"systemctl status docker.service\" and \"journalctl -xe\" for details.\n"}

**安装环境的硬件配置**
硬件：8C/64G
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core) 
Release:	7.6.1810
Codename:	Core
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
![image](https://user-images.githubusercontent.com/25274630/64936558-30a8d180-d889-11e9-806a-4c1f2b7452bf.png)

**Installer版本**
2.0.2

**Comment by Forest-L** [comment]
1、centos 7.6推荐在线安装；
2、centos7.4或者7.5在线和离线都可以；
3、环境上是否是干净的，且执行journalctl -u docker -f 日志信息截下。
@zhuyuehao

**Comment by zhuyuehao** [comment]
![image](https://user-images.githubusercontent.com/25274630/65004609-9a7bb680-d92f-11e9-95da-3b7e67adc56e.png)

**Comment by zhuyuehao** [comment]
环境之前装过其他软件，现在都卸载了，有什么方式可以排查是否卸载干净，或者哪些软件没有卸载干净会影响安装？

**Comment by zhuyuehao** [comment]
另外，在线/离线都尝试过，同样存在这个问题

**Comment by Forest-L** [comment]
能不能重启下机器，这里是docker问题，/etc/docker/daemon.json文件删掉。

**Comment by zhuyuehao** [comment]
意思是，删除这个文件，然后重启机器？

**Comment by Forest-L** [comment]
先删掉那个文件，然后再跑下，还是报这个问题的话，那就重启机器，最好不要轻易重启机器。

**Comment by zhuyuehao** [comment]
好，我试下

**Comment by zhuyuehao** [comment]
问题现在解决了；
解决方案：完全删除docker，包括/var/lib/docker，之前因为这里面有些images是项目上的没有删，现在备份后删除了，该问题得到解决
