### ISSUE TITLE
在线安装失败，无法继续

### ISSUE THREAD

**Issue by xstarts** [kubesphere/kubesphere#767]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)
在线安装失败后执行过离线安装，但是也失败，重新执行在线安装还是报错
**问题描述**
fatal: [master]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/usr/local/bin/kubectl -n openpitrix-system get pod | grep openpitrix-db-deployment | awk '{print $3}'", "delta": "0:00:00.209251", "end": "2019-09-19 07:11:04.553921", "rc": 0, "start": "2019-09-19 07:11:04.344670", "stderr": "", "stderr_lines": [], "stdout": "Pending", "stdout_lines": ["Pending"]}

**安装环境的硬件配置**
主节点：8C16G，Centos7.4
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**

**Installer版本**
2.0.2

**Comment by Forest-L** [comment]
1、describe openpitrix-db-deployment  pod的日志；
2、/etc/resolv.conf是否有不可用的IP；
3、离线安装失败之后，转为在线，最好重置下机器；
