### ISSUE TITLE
应用一键部署，搜不到应用

### ISSUE THREAD

**Issue by ckgmg** [kubesphere/kubesphere#777]
![image](https://user-images.githubusercontent.com/49260651/65400957-b54e9f00-ddf7-11e9-9345-ad3dda728b63.png)

**Comment by ckgmg** [comment]
![Uploading image.png…]()

**Comment by ckgmg** [comment]
![image](https://user-images.githubusercontent.com/49260651/65401097-7ec55400-ddf8-11e9-9d2a-405e9b8e4ddb.png)

**Comment by ckgmg** [comment]
功能不开放，灰度发布等，这基本跟dashboard没啥区别，还白白占用了一台8核16G的机器，得不偿失。
希望能继续开发好，全部开源，而不是只放部分功能出来！要想坐上龙头老大的位置，还有很长的路

**Comment by rayzhou2017** [comment]
后端不是已经都开源了吗？前端在下一个版本发布后就会开源，前端开源需要一点时间整理。上面那个错误看起来是openpitrix安装有问题。你现在使用kubesphere还有其它什么问题吗？

**Comment by ckgmg** [comment]
这个版本前端看不到我部署的应用，

**Comment by zryfish** [comment]
你的环境是安装有问题，你执行 kubectl get po --all-namespaces 看下是否所有的pod都已经起来了

**Comment by FeynmanZhou** [comment]
@ckgmg 所有功能是全部开源的，从你的截图来看，监控就不正常呀？
