### ISSUE TITLE
关联ldap，账号同步中pod意外停止

### ISSUE THREAD

**Issue by 53537** [kubesphere/kubesphere#780]
ks-account同步账号2000+之后，意外停止，报错如下

I0923 10:54:27.774444       1 main.go:270] user ERIC-WIN$ exist
I0923 10:54:27.774973       1 main.go:270] user Caifengjiao exist
F0923 10:54:27.921603       1 main.go:298] LDAP Result Code 34 "Invalid DN Syntax": invalid DN

**Comment by wansir** [comment]
目前AD 数据同步还在试验性开发中，根据错误信息（部分用户名不规范）稍作修复，已更新了`wansir/ad-sidecar:latest` 这个镜像版本

**Comment by 53537** [comment]
已更新最新镜像，中途出现如下错误
I0924 04:18:58.017534       1 main.go:270] user chenhongdan exist
F0924 04:18:58.164971       1 main.go:302] LDAP Result Code 21 "Invalid Attribute Syntax": mail: value #0 invalid per syntax
