### ISSUE TITLE
代码编译make all 异常

### ISSUE THREAD

**Issue by huahuadeep** [kubesphere/kubesphere#784]
[root@harbor kubesphere]# pwd
/opt/goworkspace/src/github.com/kubesphere/kubesphere
[root@harbor kubesphere]# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/opt/goworkspace"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/opt/goworkspace/src/github.com/kubesphere/kubesphere/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build500350208=/tmp/go-build -gno-record-gcc-switches"
[root@harbor kubesphere]# make all
which: no controller-gen in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/go/bin:/opt/goworkspace/bin:/root/bin:/usr/local/go/bin:/opt/goworkspace/bin)
go generate ./pkg/... ./cmd/...
gofmt -w ./pkg ./cmd ./tools ./api
go vet ./pkg/... ./cmd/...
export KUBEBUILDER_CONTROLPLANE_START_TIMEOUT=1m; go test ./pkg/... ./cmd/... -coverprofile cover.out
?   	kubesphere.io/kubesphere/pkg/api/devops/v1alpha2	[no test files]
?   	kubesphere.io/kubesphere/pkg/api/logging/v1alpha2	[no test files]
?   	kubesphere.io/kubesphere/pkg/api/monitoring/v1alpha2	[no test files]
?   	kubesphere.io/kubesphere/pkg/apigateway/caddy-plugin/authenticate	[no test files]
?   	kubesphere.io/kubesphere/pkg/apigateway/caddy-plugin/authentication	[no test files]
?   	kubesphere.io/kubesphere/pkg/apigateway/caddy-plugin/swagger	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/devops	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/devops/crdinstall	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/devops/install	[no test files]
2019/09/24 18:01:23 failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: permission denied
FAIL	kubesphere.io/kubesphere/pkg/apis/devops/v1alpha1	0.134s
?   	kubesphere.io/kubesphere/pkg/apis/devops/v1alpha2	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/iam	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/iam/install	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/iam/v1alpha2	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/logging	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/logging/install	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/logging/v1alpha2	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/monitoring	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/monitoring/install	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/monitoring/v1alpha2	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/network	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/network/crdinstall	[no test files]
2019/09/24 18:01:24 failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: permission denied
FAIL	kubesphere.io/kubesphere/pkg/apis/network/v1alpha1	0.063s
ok  	kubesphere.io/kubesphere/pkg/apis/network/v1alpha1/numorstring	0.031s	coverage: 0.0% of statements
?   	kubesphere.io/kubesphere/pkg/apis/operations	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/operations/install	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/operations/v1alpha2	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/resources	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/resources/install	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/resources/v1alpha2	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/servicemesh	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/servicemesh/crdinstall	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/servicemesh/metrics	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/servicemesh/metrics/install	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/servicemesh/metrics/v1alpha2	[no test files]
2019/09/24 18:01:26 failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: permission denied
FAIL	kubesphere.io/kubesphere/pkg/apis/servicemesh/v1alpha2	0.241s
?   	kubesphere.io/kubesphere/pkg/apis/tenant	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/tenant/crdinstall	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/tenant/install	[no test files]
2019/09/24 18:01:26 failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: permission denied
FAIL	kubesphere.io/kubesphere/pkg/apis/tenant/v1alpha1	0.081s
?   	kubesphere.io/kubesphere/pkg/apis/tenant/v1alpha2	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/terminal	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/terminal/install	[no test files]
?   	kubesphere.io/kubesphere/pkg/apis/terminal/v1alpha2	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/components	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/devops	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/git	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/iam	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/logging	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/monitoring	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/operations	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/quotas	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/registries	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/resources	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/revisions	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/routers	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/runtime	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/servicemesh/metrics	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/servicemesh/tracing	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/tenant	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/terminal	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/workloadstatuses	[no test files]
?   	kubesphere.io/kubesphere/pkg/apiserver/workspaces	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/clientset/versioned	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/clientset/versioned/fake	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/clientset/versioned/scheme	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/clientset/versioned/typed/devops/v1alpha1	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/clientset/versioned/typed/devops/v1alpha1/fake	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/clientset/versioned/typed/network/v1alpha1	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/clientset/versioned/typed/network/v1alpha1/fake	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/clientset/versioned/typed/servicemesh/v1alpha2	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/clientset/versioned/typed/servicemesh/v1alpha2/fake	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/clientset/versioned/typed/tenant/v1alpha1	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/clientset/versioned/typed/tenant/v1alpha1/fake	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/informers/externalversions	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/informers/externalversions/devops	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/informers/externalversions/devops/v1alpha1	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/informers/externalversions/internalinterfaces	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/informers/externalversions/network	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/informers/externalversions/network/v1alpha1	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/informers/externalversions/servicemesh	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/informers/externalversions/servicemesh/v1alpha2	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/informers/externalversions/tenant	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/informers/externalversions/tenant/v1alpha1	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/listers/devops/v1alpha1	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/listers/network/v1alpha1	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/listers/servicemesh/v1alpha2	[no test files]
?   	kubesphere.io/kubesphere/pkg/client/listers/tenant/v1alpha1	[no test files]
?   	kubesphere.io/kubesphere/pkg/constants	[no test files]
?   	kubesphere.io/kubesphere/pkg/controller	[no test files]
ok  	kubesphere.io/kubesphere/pkg/controller/application	0.168s	coverage: 0.0% of statements [no tests to run]
2019/09/24 18:01:28 failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: permission denied
FAIL	kubesphere.io/kubesphere/pkg/controller/clusterrolebinding	0.172s
ok  	kubesphere.io/kubesphere/pkg/controller/destinationrule	0.053s	coverage: 0.0% of statements [no tests to run]
ok  	kubesphere.io/kubesphere/pkg/controller/job	0.017s	coverage: 0.0% of statements [no tests to run]
2019/09/24 18:01:31 failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: permission denied
FAIL	kubesphere.io/kubesphere/pkg/controller/namespace	0.250s
?   	kubesphere.io/kubesphere/pkg/controller/network	[no test files]
?   	kubesphere.io/kubesphere/pkg/controller/network/controllerapi	[no test files]
ok  	kubesphere.io/kubesphere/pkg/controller/network/nsnetworkpolicy	0.217s	coverage: 63.9% of statements
?   	kubesphere.io/kubesphere/pkg/controller/network/provider	[no test files]
?   	kubesphere.io/kubesphere/pkg/controller/network/runoption	[no test files]
?   	kubesphere.io/kubesphere/pkg/controller/network/testing	[no test files]
?   	kubesphere.io/kubesphere/pkg/controller/network/utils	[no test files]
ok  	kubesphere.io/kubesphere/pkg/controller/network/wsnetworkpolicy	3.115s	coverage: 68.5% of statements
?   	kubesphere.io/kubesphere/pkg/controller/s2ibinary	[no test files]
?   	kubesphere.io/kubesphere/pkg/controller/s2irun	[no test files]
ok  	kubesphere.io/kubesphere/pkg/controller/storage/expansion	1.051s	coverage: 36.3% of statements
ok  	kubesphere.io/kubesphere/pkg/controller/virtualservice	0.036s	coverage: 0.0% of statements [no tests to run]
?   	kubesphere.io/kubesphere/pkg/controller/virtualservice/util	[no test files]
2019/09/24 18:01:36 failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: permission denied
FAIL	kubesphere.io/kubesphere/pkg/controller/workspace	0.166s
ok  	kubesphere.io/kubesphere/pkg/db	0.011s	coverage: 6.8% of statements
?   	kubesphere.io/kubesphere/pkg/gojenkins	[no test files]
?   	kubesphere.io/kubesphere/pkg/gojenkins/utils	[no test files]
?   	kubesphere.io/kubesphere/pkg/informers	[no test files]
?   	kubesphere.io/kubesphere/pkg/models	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/applications	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/components	[no test files]
ok  	kubesphere.io/kubesphere/pkg/models/devops	0.088s	coverage: 22.7% of statements
ok  	kubesphere.io/kubesphere/pkg/models/git	3.305s	coverage: 23.8% of statements
?   	kubesphere.io/kubesphere/pkg/models/iam	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/iam/policy	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/kubeconfig	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/kubectl	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/log	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/metrics	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/nodes	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/quotas	[no test files]
ok  	kubesphere.io/kubesphere/pkg/models/registries	6.320s	coverage: 48.3% of statements
?   	kubesphere.io/kubesphere/pkg/models/resources	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/revisions	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/routers	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/servicemesh	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/servicemesh/metrics	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/status	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/storage	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/tenant	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/terminal	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/workloads	[no test files]
?   	kubesphere.io/kubesphere/pkg/models/workspaces	[no test files]
?   	kubesphere.io/kubesphere/pkg/server	[no test files]
ok  	kubesphere.io/kubesphere/pkg/server/config	0.052s	coverage: 38.5% of statements
?   	kubesphere.io/kubesphere/pkg/server/errors	[no test files]
?   	kubesphere.io/kubesphere/pkg/server/filter	[no test files]
?   	kubesphere.io/kubesphere/pkg/server/options	[no test files]
?   	kubesphere.io/kubesphere/pkg/server/params	[no test files]
?   	kubesphere.io/kubesphere/pkg/simple/client	[no test files]
?   	kubesphere.io/kubesphere/pkg/simple/client/alerting	[no test files]
?   	kubesphere.io/kubesphere/pkg/simple/client/devops	[no test files]
?   	kubesphere.io/kubesphere/pkg/simple/client/elasticsearch	[no test files]
?   	kubesphere.io/kubesphere/pkg/simple/client/elasticsearch/versions/v5	[no test files]
?   	kubesphere.io/kubesphere/pkg/simple/client/elasticsearch/versions/v6	[no test files]
?   	kubesphere.io/kubesphere/pkg/simple/client/elasticsearch/versions/v7	[no test files]
?   	kubesphere.io/kubesphere/pkg/simple/client/fluentbit	[no test files]
?   	kubesphere.io/kubesphere/pkg/simple/client/k8s	[no test files]
?   	kubesphere.io/kubesphere/pkg/simple/client/kubesphere	[no test files]
?   	kubesphere.io/kubesphere/pkg/simple/client/ldap	[no test files]
ok  	kubesphere.io/kubesphere/pkg/simple/client/mysql	0.020s	coverage: 5.0% of statements
?   	kubesphere.io/kubesphere/pkg/simple/client/notification	[no test files]
?   	kubesphere.io/kubesphere/pkg/simple/client/openpitrix	[no test files]
?   	kubesphere.io/kubesphere/pkg/simple/client/prometheus	[no test files]
?   	kubesphere.io/kubesphere/pkg/simple/client/redis	[no test files]
?   	kubesphere.io/kubesphere/pkg/simple/client/s2is3	[no test files]
?   	kubesphere.io/kubesphere/pkg/simple/client/servicemesh	[no test files]
?   	kubesphere.io/kubesphere/pkg/simple/client/sonarqube	[no test files]
?   	kubesphere.io/kubesphere/pkg/test	[no test files]
?   	kubesphere.io/kubesphere/pkg/utils/hashutil	[no test files]
ok  	kubesphere.io/kubesphere/pkg/utils/idutils	0.435s	coverage: 45.7% of statements
?   	kubesphere.io/kubesphere/pkg/utils/iputil	[no test files]
?   	kubesphere.io/kubesphere/pkg/utils/jsonutil	[no test files]
?   	kubesphere.io/kubesphere/pkg/utils/jwtutil	[no test files]
?   	kubesphere.io/kubesphere/pkg/utils/k8sutil	[no test files]
?   	kubesphere.io/kubesphere/pkg/utils/net	[no test files]
?   	kubesphere.io/kubesphere/pkg/utils/readerutils	[no test files]
?   	kubesphere.io/kubesphere/pkg/utils/reflectutils	[no test files]
?   	kubesphere.io/kubesphere/pkg/utils/signals	[no test files]
?   	kubesphere.io/kubesphere/pkg/utils/sliceutil	[no test files]
?   	kubesphere.io/kubesphere/pkg/utils/stringutils	[no test files]
?   	kubesphere.io/kubesphere/pkg/utils/term	[no test files]
?   	kubesphere.io/kubesphere/pkg/version	[no test files]
?   	kubesphere.io/kubesphere/pkg/webhook	[no test files]
?   	kubesphere.io/kubesphere/cmd/controller-manager	[no test files]
?   	kubesphere.io/kubesphere/cmd/controller-manager/app	[no test files]
?   	kubesphere.io/kubesphere/cmd/controller-manager/app/options	[no test files]
?   	kubesphere.io/kubesphere/cmd/hypersphere	[no test files]
?   	kubesphere.io/kubesphere/cmd/ks-apigateway	[no test files]
?   	kubesphere.io/kubesphere/cmd/ks-apiserver	[no test files]
?   	kubesphere.io/kubesphere/cmd/ks-apiserver/app	[no test files]
?   	kubesphere.io/kubesphere/cmd/ks-apiserver/app/options	[no test files]
?   	kubesphere.io/kubesphere/cmd/ks-iam	[no test files]
?   	kubesphere.io/kubesphere/cmd/ks-iam/app	[no test files]
?   	kubesphere.io/kubesphere/cmd/ks-iam/app/options	[no test files]
?   	kubesphere.io/kubesphere/cmd/ks-network	[no test files]
FAIL
make: *** [test] Error 1
[root@harbor kubesphere]#

**Comment by zryfish** [comment]
kubesphere依赖kubebuilder来做测试，可以先执行下 hack/install_kubebuilder.sh 安装下kubebuilder
