### ISSUE TITLE
kubesphere安装gitlab之后无法访问

### ISSUE THREAD

**Issue by Micheal-yang-china** [kubesphere/kubesphere#795]
Kubesphere安装gitlab之后输入访问地址无法访问，页面显示default backend - 404

**Comment by rdzn-github** [comment]
不要以http://<node_ip>:30080访问，请以http://gitlab.devops.kubesphere.local:30080/访问，另外本地hosts需要配置<node_ip>   gitlab.devops.kubesphere.local

**Comment by Micheal-yang-china** [comment]
好的，可以了，多谢！
