### ISSUE TITLE
使用添加的chart仓库安装应用失败

### ISSUE THREAD

**Issue by jinjie2088** [kubesphere/kubesphere#803]
添加chart仓库后，可以获取到chart信息，但是安装失败，找不到安装的chart包。
![image](https://user-images.githubusercontent.com/4155721/65734689-bdb01e00-e106-11e9-80da-3f96f90aa6d5.png)

查看charts服务器的index-cache.yaml文件，文件中已经指定了urls：
![image](https://user-images.githubusercontent.com/4155721/65734757-0ff13f00-e107-11e9-98c0-bf521deedb50.png)
前面是带路径的，而去部署时没有把路径拼上去，导致找不到chart包

版本：2.0.2
charts库使用chartmuseum

**Comment by jinjie2088** [comment]
up

**Comment by rayzhou2017** [comment]
Please verify on KubeSphere 3.0.0
