### ISSUE TITLE
centos7离线安装问题

### ISSUE THREAD

**Issue by dylanyht** [kubesphere/kubesphere#804]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
提示找不到挂载点 无法进行安装
**安装环境的硬件配置**
centos7
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)
vmware虚拟机
**错误信息或截图**
umount: /kubeinstaller/yum_repo/iso: not mounted
/etc/yum.repos.d ~/kubesphere-all-offline-advanced-2.0.2/scripts
/etc/yum.repos.d
mount: /dev/loop0 is write-protected, mounting read-only
mount: /dev/loop1 is write-protected, mounting read-only
Loaded plugins: fastestmirror, langpacks
Cleaning repos: bash
Cleaning up list of fastest mirrors
Other repos take up 400 M of disk space (use --verbose for details)
Loaded plugins: fastestmirror, langpacks
Determining fastest mirrors
file:///kubeinstaller/yum_repo/iso/repodata/repomd.xml: [Errno 14] curl#37 - "Couldn't open file /kubeinstaller/yum_repo/iso/repodata/repomd.xml"
Trying other mirror.
**Installer版本**
2.0.2

**Comment by PYIsOk** [comment]
可以看下下面的issue，能帮助到你
