### ISSUE TITLE
CI/CD 流水线构建会导致harbor无法pull镜像，push正常

### ISSUE THREAD

**Issue by Micheal-yang-china** [kubesphere/kubesphere#807]
按照官方文档操作实例十二：CI/CD 流水线示例 (离线版)    
构建流水线的过程中镜像可以正常push到harbor但是在将服务发布到dev环境的过程中无法pull镜像

**Comment by runzexia** [comment]
无法pull镜像有错误信息嘛？

**Comment by Micheal-yang-china** [comment]
error response from daemon:Get http://harbor.devops.kubesphere.local:30280/v2/library/java/manifest/openjdk-8-jre-alpine:read tcp 20.xx.xx.120:32834 -> 20.xx.xx.32:30280: read: connection reset by peer

**Comment by soulseen** [comment]
测试下手动可以pull吗

**Comment by Micheal-yang-china** [comment]
平台不行，手动pull也不行

**Comment by runzexia** [comment]
请检查集群的网络状况，包括node 网络、kube-proxy、calico等
