### ISSUE TITLE
CI/CD 流水线构建，阶段七. Push with tag: 生成 tag 并 release 到 GitLab时无法成功

### ISSUE THREAD

**Issue by Micheal-yang-china** [kubesphere/kubesphere#808]
CI/CD 流水线构建，阶段七. Push with tag: 生成 tag 并 release 到 GitLab时无法成功
查看Jenkins构建日志，报错信息如下：
git push http://****:****@gitlab.devops.kubesphere.local:30080/****1/devops-java-sample.git --tags --ipv4 fata: unable to access 'http://****:****@gitlab.devops.kubesphere.local:30080/****1/devops-java-sample.git/': could not resolve host :****@gitlab.devops.kubesphere.local;Name or service not known

**Comment by runzexia** [comment]
.请确认已经安装gitlab

**Comment by Micheal-yang-china** [comment]
我是在k8s上安装的kubesphere，是每个节点都需要安装gitlab吗？

**Comment by soulseen** [comment]
检查下`kubesphere-devops-system` namespace下是否存在gitlab。

**Comment by Micheal-yang-china** [comment]
存在啊，拉取代码就是从内置的gitlab上拉取的，然后生成 tag 并 release 到 GitLab时无法成功

**Comment by soulseen** [comment]
修改下CoreDNS的配置。参考https://kubesphere.io/docs/advanced-v2.0/zh-CN/system-settings/edit-system-settings/#%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9-coredns-%E9%85%8D%E7%BD%AE
