### ISSUE TITLE
CI/CD 流水线构建 docker 命令找不到

### ISSUE THREAD

**Issue by aiguanglee** [kubesphere/kubesphere#810]
+ docker inspect -f . harbor.xxx.com/test/maven:3.6.1
/home/jenkins/workspace/ct-kRw6lGrXn3vo_xxx-xxx_master@tmp/durable-dbc14b4d/script.sh: 1: /home/jenkins/workspace/ct-kRw6lGrXn3vo_xxx-xxx_master@tmp/durable-dbc14b4d/script.sh: docker: not found

**Comment by runzexia** [comment]
请参考一下devops sample，需要嵌套一下container step
