### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by gshkb** [kubesphere/kubesphere#817]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**选择All-in-one模式,安装中途报错**

**硬件阿里云服务器 CentOS7.4  8核 16g 550G硬盘 5M带宽**

[备注]: <云主机> 

配置文件:
```
##config
## Please configure the API service, if your cluster based on QingCloud IaaS
## platform and want to use qingcloud-csi or qingcloud-cloud-controller-manager.
# Access key pair can be created in QingCloud console
qingcloud_access_key_id: ACCESS_KEY_ID
qingcloud_secret_access_key: ACCESS_KEY_SECRET
# Zone should be the same as Kubernetes cluster
qingcloud_zone: ZONE
# QingCloud IaaS platform service url.
qingcloud_host: api.qingcloud.com
qingcloud_port: 443
qingcloud_protocol: https
qingcloud_uri: /iaas
qingcloud_connection_retries: 3
qingcloud_connection_timeout: 30

## If you want to use QingCloud LoadBlancer Plugin, please reference the documentation for installation instructions.
## https://docs.kubesphere.io/advanced-v2.0/zh-CN/installation/qingcloud-lb
qingcloud_lb_enable: false
qingcloud_vxnet_id: SHOULD_BE_REPLACED

######################################################################
# Storage configuration
######################################################################
## https://docs.kubesphere.io/advanced-v2.0/zh-CN/installation/storage-configuration

# Local volume provisioner deployment(Only all-in-one)
local_volume_provisioner_enabled: true
local_volume_provisioner_storage_class: local
local_volume_is_default_class: true

# QingCloud CSI
qingcloud_csi_enabled: false
qingcloud_csi_is_default_class: false
#The type of volume in QingCloud IaaS platform.
# 0 represents high performance volume
# 3 respresents super high performance volume.
# 1 or 2 represents high capacity volume depending on cluste's zone
# 5 represents enterprise distributed SAN (NeonSAN) volume
# 100 represents basic volume
# 200 represents SSD enterprise volume.
qingcloud_type: 2
qingcloud_maxSize: 5000
qingcloud_minSize: 100
qingcloud_stepSize: 50
qingcloud_fsType: ext4
# 1 means single replica, 2 means multiple replicas. Default 2.
qingcloud_disk_replica: 2

# Ceph_rbd  deployment
ceph_rbd_enabled: false
ceph_rbd_is_default_class: false
ceph_rbd_storage_class: rbd

# e.g. ceph_rbd_monitors:
#   - 172.24.0.1:6789
#   - 172.24.0.2:6789
#   - 172.24.0.3:6789
ceph_rbd_monitors:
  - SHOULD_BE_REPLACED
ceph_rbd_admin_id: admin
# e.g. ceph_rbd_admin_secret: AQAnwihbXo+uDxAAD0HmWziVgTaAdai90IzZ6Q==
ceph_rbd_admin_secret: SHOULD_BE_REPLACED
ceph_rbd_pool: rbd
ceph_rbd_user_id: admin
# e.g. ceph_rbd_user_secret: AQAnwihbXo+uDxAAD0HmWziVgTaAdai90IzZ6Q==
ceph_rbd_user_secret: SHOULD_BE_REPLACED
ceph_rbd_fsType: ext4
ceph_rbd_imageFormat: 1
#ceph_rbd_imageFeatures: layering

# NFS-Client provisioner deployment
nfs_client_enable: false
nfs_client_is_default_class: false
# Hostname of the NFS server(ip or hostname)
nfs_server: SHOULD_BE_REPLACED
# Basepath of the mount point to be used
nfs_path: SHOULD_BE_REPLACED

# NeonSAN CSI
neonsan_csi_enabled: false
neonsan_csi_is_default_class: false
# csi-neonsan container option protocol: TCP or RDMA
neonsan_csi_protocol: TCP
# address of the NeonSAN server
neonsan_server_address: IP:PORT
# cluster_name of the NeonSAN server
neonsan_cluster_name: CLUSTER_NAME
# the name of the volume storage pool
neonsan_server_pool: kube
# NeonSAN image replica count
neonsan_server_replicas: 1
# set the increment of volumes size in GiB
neonsan_server_stepSize: 10
# the file system to use for the volume
neonsan_server_fsType: ext4
client_tcp_no_delay: 1
client_io_depth: 64
client_io_timeout: 30
conn_timeout: 8
open_volume_timeout: 180

# GlusterFS  provisioner deployment
glusterfs_provisioner_enabled: false
glusterfs_is_default_class: false
glusterfs_provisioner_storage_class: glusterfs
glusterfs_provisioner_restauthenabled: true
# e.g. glusterfs_provisioner_resturl: http://192.168.0.4:8080
glusterfs_provisioner_resturl: SHOULD_BE_REPLACED
# e.g. glusterfs_provisioner_clusterid: 6a6792ed25405eaa6302da99f2f5e24b
glusterfs_provisioner_clusterid: SHOULD_BE_REPLACED
glusterfs_provisioner_restuser: admin
glusterfs_provisioner_secretName: heketi-secret
glusterfs_provisioner_gidMin: 40000
glusterfs_provisioner_gidMax: 50000
glusterfs_provisioner_volumetype: replicate:2
# e.g. jwt_admin_key: 123456
jwt_admin_key: SHOULD_BE_REPLACED


######################################################################
# Cluster configuration
######################################################################
## Change this to use another Kubernetes version
ks_version: 2.0.2
kube_version: v1.13.5
etcd_version: v3.2.18
openpitrix_version: v0.3.5

ks_image_pull_policy: IfNotPresent
# Choose network plugin (calico or flannel)
kube_network_plugin: calico

# Kubernetes internal network for services, unused block of space.
kube_service_addresses: 10.233.0.0/18

# internal network. When used, it will assign IP
# addresses from this range to individual pods.
# This network must be unused in your network infrastructure!
kube_pods_subnet: 10.233.64.0/18

# Kube-proxy proxyMode configuration.
# Can be ipvs, iptables
kube_proxy_mode: ipvs

# Configure the amount of pods able to run on single node
# default is equal to application default
kubelet_max_pods: 110

# DNS configuration.
# Can be kubedns, coredns
dns_mode: coredns

# Access Port of KubeSphere
# 30000-32767 (30180/30280/30380 are not allowed)
console_port: 30880

disableMultiLogin: true

## HA(Highly Available) loadbalancer example config
## apiserver_loadbalancer_domain_name: "lb.kubesphere.local"
#loadbalancer_apiserver:
#  address: 192.168.0.10
#  port: 6443

#Docker periodic cleaning time (Can be reboot/yearly/annually/monthly/weekly/daily/hourly)
periodic_cleaning_time: weekly
## Add other registry
docker_registry_mirrors:
  - https://registry.docker-cn.com

#Etcd periodic backup time (Specify a period in minutes)
etcd_backup_period: 30
keep_backup_number: 5
etcd_backup_dir: "/var/backups/kube_etcd"

# Monitoring
prometheus_memory_size: 400Mi
prometheus_volume_size: 20Gi

# Logging
keep_log_days: 7

kibana_enable: false
elasticsearch_volume_size: 20Gi

# Notification (Including Jenkins Notify)
## Please replace following configuration with your own mail server information.
EMAIL_SMTP_HOST: mail.example.com
EMAIL_SMTP_PORT: 25
EMAIL_FROM_ADDR: admin@example.com
EMAIL_FROM_NAME: KubeSphere
EMAIL_FROM_PASS: password
EMAIL_USE_SSL: false

# Jenkins deployment
jenkins_memory_lim: 8Gi
jenkins_memory_req: 4Gi
Java_Opts: -Xms3g -Xmx6g -XX:MaxPermSize=512m -XX:MaxRAM=8g
JenkinsLocationUrl: jenkins.devops.kubesphere.local

# harbor deployment
harbor_enable: true
harbor_domain: harbor.devops.kubesphere.local

#GitLab deployment
gitlab_enable: true
gitlab_hosts_domain: devops.kubesphere.local

## sonarqube
sonarqube_enable: true
## If you already have a sonar server,  please fill in the following parameters.
## If not, a sonarqube will be installed by default.
#sonar_server_url: SHOULD_BE_REPLACED
#sonar_server_token: SHOULD_BE_REPLACED

## Container Engine Acceleration
## Use nvidia gpu acceleration in containers
# nvidia_accelerator_enabled: true
# nvidia_gpu_nodes:
#   - kube-gpu-001
```
**错误信息**

TASK [ks-logging : ks-logging | Checking elasticsearch-logging] ********************************************************************
Saturday 28 September 2019  16:26:36 +0800 (0:00:01.414)       0:04:52.893 **** 
fatal: [ks-allinone]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm list | grep \"elasticsearch-logging\" | grep \"elasticsearch-1.10.2\"", "delta": "0:00:00.445447", "end": "2019-09-28 16:26:37.287525", "msg": "non-zero return code", "rc": 1, "start": "2019-09-28 16:26:36.842078", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring

fatal: [ks-allinone]: FAILED! => {"attempts": 30, "changed": true, "cmd": "/usr/local/bin/kubectl get pod -n kubesphere-system -o wide | grep ks-account | awk '{print $3}'", "delta": "0:00:00.207351", "end": "2019-09-28 16:30:34.367019", "rc": 0, "start": "2019-09-28 16:30:34.159668", "stderr": "", "stderr_lines": [], "stdout": "Pending", "stdout_lines": ["Pending"]}

PLAY RECAP *************************************************************************************************************************
ks-allinone                : ok=296  changed=98   unreachable=0    failed=1   

Saturday 28 September 2019  16:30:34 +0800 (0:02:41.832)       0:08:50.608 **** 
=============================================================================== 
ks-devops/jenkins : KubeSphere | Waiting for ks-account ------------------------------------------------------------------- 161.83s
download : container_download | Download containers if pull is required or told to always pull (all nodes) ----------------- 19.90s
download : container_download | Download containers if pull is required or told to always pull (all nodes) ----------------- 18.54s
ks-devops/harbor : ks-devops | Getting harbor installation files ----------------------------------------------------------- 16.52s
ks-monitor : ks-monitor | Getting monitor installation files --------------------------------------------------------------- 14.59s
openpitrix : OpenPitrix | Getting OpenPitrix installation files ------------------------------------------------------------ 10.61s
ks-devops/ks-devops : OpenPitrix | Installing OpenPitrix(3) ----------------------------------------------------------------- 9.36s
storages/LocalVolume : local_volume | Creating manifests -------------------------------------------------------------------- 8.50s
download : Download items --------------------------------------------------------------------------------------------------- 8.29s
openpitrix : OpenPitrix | Installing OpenPitrix(2) -------------------------------------------------------------------------- 6.43s
metrics-server : Metrics-Server | Getting metrics-server installation files ------------------------------------------------- 4.43s
prepare/base : KubeSphere | Labeling system-workspace ----------------------------------------------------------------------- 4.11s
ks-devops/ks-devops : ks-devops | Getting ks-devops installation files ------------------------------------------------------ 3.82s
storages/LocalVolume : local_volume | Creating directories for local_volume ------------------------------------------------- 3.57s
ks-monitor : ks-monitor | Creating manifests -------------------------------------------------------------------------------- 3.48s
prepare/base : KubeSphere | Init KubeSphere --------------------------------------------------------------------------------- 3.25s
ks-logging : ks-logging | Creating manifests -------------------------------------------------------------------------------- 3.10s
ks-alerting : ks-alerting | Creating manifests ------------------------------------------------------------------------------ 3.01s
prepare/base : KubeSphere | Getting installation init files ----------------------------------------------------------------- 2.78s
ks-devops/s2i : S2I | Creating S2I secret(2) -------------------------------------------------------------------------------- 2.73s
failed!

**Installer版本**
kubesphere-all-advanced-2.0.2

**Comment by zryfish** [comment]
错误信息贴下啊

**Comment by gshkb** [comment]
TASK [ks-logging : ks-logging | Checking elasticsearch-logging] ********************************************************************
Saturday 28 September 2019  16:26:36 +0800 (0:00:01.414)       0:04:52.893 **** 
fatal: [ks-allinone]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm list | grep \"elasticsearch-logging\" | grep \"elasticsearch-1.10.2\"", "delta": "0:00:00.445447", "end": "2019-09-28 16:26:37.287525", "msg": "non-zero return code", "rc": 1, "start": "2019-09-28 16:26:36.842078", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring


TASK [ks-devops/jenkins : KubeSphere | Waiting for ks-account] *********************************************************************
Saturday 28 September 2019  16:27:52 +0800 (0:00:01.064)       0:06:08.776 **** 
FAILED - RETRYING: KubeSphere | Waiting for ks-account (30 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (29 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (28 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (27 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (26 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (25 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (24 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (23 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (22 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (21 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (20 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (19 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (18 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (17 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (16 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (15 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (14 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (13 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (12 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (11 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (10 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (9 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (8 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (7 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (6 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (5 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (4 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (3 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (2 retries left).
FAILED - RETRYING: KubeSphere | Waiting for ks-account (1 retries left).
fatal: [ks-allinone]: FAILED! => {"attempts": 30, "changed": true, "cmd": "/usr/local/bin/kubectl get pod -n kubesphere-system -o wide | grep ks-account | awk '{print $3}'", "delta": "0:00:00.207351", "end": "2019-09-28 16:30:34.367019", "rc": 0, "start": "2019-09-28 16:30:34.159668", "stderr": "", "stderr_lines": [], "stdout": "Pending", "stdout_lines": ["Pending"]}

PLAY RECAP *************************************************************************************************************************
ks-allinone                : ok=296  changed=98   unreachable=0    failed=1   

Saturday 28 September 2019  16:30:34 +0800 (0:02:41.832)       0:08:50.608 **** 
=============================================================================== 
ks-devops/jenkins : KubeSphere | Waiting for ks-account ------------------------------------------------------------------- 161.83s
download : container_download | Download containers if pull is required or told to always pull (all nodes) ----------------- 19.90s
download : container_download | Download containers if pull is required or told to always pull (all nodes) ----------------- 18.54s
ks-devops/harbor : ks-devops | Getting harbor installation files ----------------------------------------------------------- 16.52s
ks-monitor : ks-monitor | Getting monitor installation files --------------------------------------------------------------- 14.59s
openpitrix : OpenPitrix | Getting OpenPitrix installation files ------------------------------------------------------------ 10.61s
ks-devops/ks-devops : OpenPitrix | Installing OpenPitrix(3) ----------------------------------------------------------------- 9.36s
storages/LocalVolume : local_volume | Creating manifests -------------------------------------------------------------------- 8.50s
download : Download items --------------------------------------------------------------------------------------------------- 8.29s
openpitrix : OpenPitrix | Installing OpenPitrix(2) -------------------------------------------------------------------------- 6.43s
metrics-server : Metrics-Server | Getting metrics-server installation files ------------------------------------------------- 4.43s
prepare/base : KubeSphere | Labeling system-workspace ----------------------------------------------------------------------- 4.11s
ks-devops/ks-devops : ks-devops | Getting ks-devops installation files ------------------------------------------------------ 3.82s
storages/LocalVolume : local_volume | Creating directories for local_volume ------------------------------------------------- 3.57s
ks-monitor : ks-monitor | Creating manifests -------------------------------------------------------------------------------- 3.48s
prepare/base : KubeSphere | Init KubeSphere --------------------------------------------------------------------------------- 3.25s
ks-logging : ks-logging | Creating manifests -------------------------------------------------------------------------------- 3.10s
ks-alerting : ks-alerting | Creating manifests ------------------------------------------------------------------------------ 3.01s
prepare/base : KubeSphere | Getting installation init files ----------------------------------------------------------------- 2.78s
ks-devops/s2i : S2I | Creating S2I secret(2) -------------------------------------------------------------------------------- 2.73s
failed!

**Comment by rayzhou2017** [comment]
到 https://github.com/kubesphere/ks-installer/issues 找找答案
