### ISSUE TITLE
未安装devops，总览页面却显示devops工程数量

### ISSUE THREAD

**Issue by soulseen** [kubesphere/kubesphere#822]
**Describe the bug(描述下问题)**

ks-dev-2.1版本，未安装devops，总览页面却显示devops工程数量

![image](https://user-images.githubusercontent.com/16031013/65825062-d35b4a00-e2a4-11e9-9481-9a417b4b5f34.png)

**Versions used(KubeSphere/Kubernetes的版本)**

ks-dev-2.1-20190929

**Environment(环境的硬件配置)**

allinone: 8cpu/32g

**Comment by runzexia** [comment]
版本最好加带日期的版本号

**Comment by rayzhou2017** [comment]
注意这个地方也需要改

![Screen Shot 2019-09-29 at 1 32 59 PM](https://user-images.githubusercontent.com/28859385/65826805-a9625180-e2bd-11e9-8e9b-fddb01ad287a.png)

**Comment by rayzhou2017** [comment]
还有这个地方
![Screen Shot 2019-09-29 at 1 40 40 PM](https://user-images.githubusercontent.com/28859385/65826895-bb90bf80-e2be-11e9-9757-938daa167b29.png)

**Comment by huanggze** [comment]
![image](https://user-images.githubusercontent.com/22350668/65827839-129a9280-e2c7-11e9-9d12-3f405796e15e.png)

![image](https://user-images.githubusercontent.com/22350668/65827850-2b0aad00-e2c7-11e9-96f2-cec430318989.png)

![image](https://user-images.githubusercontent.com/22350668/65827862-4b3a6c00-e2c7-11e9-8d48-33cac077cf6d.png)

**Comment by soulseen** [comment]
上面的图中项目下的构建，可能是因为之前修改 configmap instller， 装devops失败后的残留的数据

**Comment by leoendless** [comment]
fixed in [kubespheredev/ks-console](https://hub.docker.com/r/kubespheredev/ks-console)
