### ISSUE TITLE
未安装告警模块界面显示通知邮件服务器设置

### ISSUE THREAD

**Issue by huojiao2006** [kubesphere/kubesphere#823]
**Describe the bug(描述下问题)**
未安装告警模块界面显示通知邮件服务器设置
  
**Versions used(KubeSphere/Kubernetes的版本)**
ks-dev-2.1

**Comment by leoendless** [comment]
fixed in [kubespheredev/ks-console](https://hub.docker.com/r/kubespheredev/ks-console)

**Comment by huojiao2006** [comment]
需要前端或者installer 看一下。

**Comment by leoendless** [comment]
verified
