### ISSUE TITLE
文档link错误

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#824]
* [x] 文档link到docs.kubesphere.io，需要link到kubesphere.io/docs，整体扫描一下link

![Screen Shot 2019-09-29 at 10 44 03 AM](https://user-images.githubusercontent.com/28859385/65825183-88423680-e2a6-11e9-8664-a41e3781d9b9.png)

**Comment by leoendless** [comment]
fixed in [kubespheredev/ks-console](https://hub.docker.com/r/kubespheredev/ks-console)

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20190930
