### ISSUE TITLE
项目中密钥引用数量错误

### ISSUE THREAD

**Issue by soulseen** [kubesphere/kubesphere#825]
**Describe the bug(描述下问题)**

在项目下创建密钥，新创建的密钥显示引用数为2。

![image](https://user-images.githubusercontent.com/16031013/65825214-fe469d80-e2a6-11e9-9a31-338923caba55.png)

**Versions used(KubeSphere/Kubernetes的版本)**

ks-dev-2.1-20190929

**Environment(环境的硬件配置)**

allinone: 8cpu/32g

**Comment by leoendless** [comment]
这里翻译错了，应该是配置项数量

**Comment by leoendless** [comment]
fixed in [kubespheredev/ks-console](https://hub.docker.com/r/kubespheredev/ks-console)
