### ISSUE TITLE
[19-09-28] 在pvc页面跳转到挂载pvc的pod页面会导致404

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#827]
![image](https://user-images.githubusercontent.com/31230341/65825462-c3923480-e2a9-11e9-820b-a6ac92091059.png)
在上面页面中点击跳转，下面页面url中出现未定义，点击面包屑会导致404
![image](https://user-images.githubusercontent.com/31230341/65825471-defd3f80-e2a9-11e9-8971-7066db969804.png)
/kind bug
/area console

**Comment by leoendless** [comment]
fixed in [kubespheredev/ks-console](https://hub.docker.com/r/kubespheredev/ks-console)
