### ISSUE TITLE
没有翻译成中文

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#828]
* [x] 内置角色没有翻译成中文

![Screen Shot 2019-09-29 at 11 19 46 AM](https://user-images.githubusercontent.com/28859385/65825576-0f91a900-e2ab-11e9-88a2-bf35927cb629.png)

* [x] 内置用户名也没有翻译
![Screen Shot 2019-09-29 at 11 23 56 AM](https://user-images.githubusercontent.com/28859385/65825610-a52d3880-e2ab-11e9-9a2c-1c1e9a23505a.png)

* [x] 这个地方PVC是不是最好翻译一下？
![Screen Shot 2019-09-29 at 1 35 38 PM](https://user-images.githubusercontent.com/28859385/65826841-1c6bc800-e2be-11e9-89f6-a36a2fb2b9cf.png)

* [x] 内置的workspace角色需要翻译
![Screen Shot 2019-09-29 at 1 51 15 PM](https://user-images.githubusercontent.com/28859385/65827000-41f9d100-e2c0-11e9-94c4-6b1a46a19a23.png)

**Comment by leoendless** [comment]
fixed in [kubespheredev/ks-console](https://hub.docker.com/r/kubespheredev/ks-console)

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20190930
