### ISSUE TITLE
主机容器组详情页多余信息

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#832]
* [x] 进入主机的容器组tab页，column里有主机name和ip，这个是多余的，因为你已经在查某个具体的主机，这些信息在左边已经有了。
![Screen Shot 2019-09-29 at 12 18 41 PM](https://user-images.githubusercontent.com/28859385/65826218-774bf200-e2b3-11e9-86bb-c3cc5d5e0dd9.png)

**Comment by rayzhou2017** [comment]
如果性能不受影响，换成pod关联的workload是不是更好一些？

**Comment by leoendless** [comment]
fixed in [kubespheredev/ks-console](https://hub.docker.com/r/kubespheredev/ks-console)

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20190930
