### ISSUE TITLE
csi list 

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#833]
* [ ] 没理解这个new是什么意思？也没有说明或者link，另外为什么没有qingstor csi？还有后续应该加上一些主流云厂商的csi
![Screen Shot 2019-09-29 at 12 27 22 PM](https://user-images.githubusercontent.com/28859385/65826282-ac0c7900-e2b4-11e9-965f-1bdb3ad7a670.png)

**Comment by justahole** [comment]
@rayzhou2017 new 是原有版本的升级，功能上是一样的。这里提供的旧版，可以理解为稳定版。说明很快就会加入。

**Comment by leoendless** [comment]
可以适当加个翻译说明下

**Comment by wnxn** [comment]
- 新建和升级的 KS，在 QingCloud CSI 存储类型 provisioner 字段不一致，这里 UI 设计需要修改。https://app.zeplin.io/project/5cbe7fbc2f55d8b73f56811b/screen/5d660ad439bbe3139a91cbe3
- QingStor CSI 之前的版本因为 NeonSAN CLI 客户端协议不匹配，需要发新版本，计划 10 月发布一版。
https://tower.im/teams/637817/documents/9288/
- 阿里云和腾讯云已经调研完毕，待与 installer 集成。
https://tower.im/teams/637817/documents/8872/
https://tower.im/teams/637817/documents/8978/

**Comment by rayzhou2017** [comment]
那是不是应该用版本号表示比较合理？

**Comment by wnxn** [comment]
KS 升到 2.1 后 QingCloud CSI 版本都是 v1.1.0 了，就是 provisioner 字段要兼容 老版 
csi-qingcloud 和新版 
disk.csi.qingcloud.com 插件字段，已经和 @Carlosfengv @minghaoye 沟通过了。创建存储类型修改建议在：https://git.internal.yunify.com/KubeSphere/kubesphere-console/issues/1275 
创建存储类型参数文案我也修改一下，会更新到 zeplin 上。

**Comment by wnxn** [comment]
创建存储类型参数文案修改建议：https://git.internal.yunify.com/KubeSphere/kubesphere-console/issues/1275 @Carlosfengv @justahole

**Comment by wnxn** [comment]
由于 Kubernetes 里 PV 记录的存储类型的 provisioner 字段不可更改。
QingCloud CSI v1.1.0 默认 provisioner 字段为 disk.csi.qingcloud.com，以后推荐使用 disk.csi.qingcloud.com
QingCloud CSI v0.2.x 默认 provisioner 字段为 csi-qingcloud
对于 新建的 KS 2.1 集群 provisioner 字段为 disk.csi.qingcloud.com
对于 升级的 KS 2.1 集群需要兼容之前创建的 PV，所以 provisioner 字段为 csi-qingcloud
目前 KS 2.1 UI 关于 qingcloud-csi 存储类型需要兼容2个 provisioner，经过与 @Carlosfengv 讨论，创建存储类型第2页中创建 qingcloud-csi 存储类型的 provisioner 设置为 disk.csi.qingcloud.com ，如果是升级到 KS 2.1 的集群可以通过自定义方式创建指定 provisioner 的存储类型。

**Comment by lihongyu65085** [comment]
any plan  to  support  minio？
