### ISSUE TITLE
unknown workspace

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#834]
* [ ] 这一页多了一个没有名字的workspace，感觉是bug，总览页没有个这个问题
![Screen Shot 2019-09-29 at 1 38 05 PM](https://user-images.githubusercontent.com/28859385/65826877-7e2c3200-e2be-11e9-9b6b-b37525f2c86a.png)

**Comment by justahole** [comment]
这个问题已经在修复中了。

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20190930
