### ISSUE TITLE
system project项目成员

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#837]
* [ ] 项目成员怎么是0个？ admin不是其成员吗？
![Screen Shot 2019-09-29 at 3 46 54 PM](https://user-images.githubusercontent.com/28859385/65828731-6cec2100-e2d0-11e9-832b-d8828a79f1b7.png)

**Comment by leoendless** [comment]
@wansir 看下吧，应该是接口没有返回

**Comment by wansir** [comment]
目前的解决方式是将admin从 system project 里移除（system project不再设置管理员）， admin 本来就属于集群管理员，没有必要再绑定项目下的角色

**Comment by rayzhou2017** [comment]
OK
