### ISSUE TITLE
resource limit 显示NaN

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#838]
* [x] 如下图所示
![Screen Shot 2019-09-29 at 3 53 24 PM](https://user-images.githubusercontent.com/28859385/65828798-5d210c80-e2d1-11e9-9d6b-63d997664c12.png)

**Comment by leoendless** [comment]
fixed in [kubespheredev/ks-console](https://hub.docker.com/r/kubespheredev/ks-console)

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20190930
