### ISSUE TITLE
工作负载

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#839]
* [x] 下面负载的显示我感觉比较奇怪，pod列表里包含了job的，但job和cronjob是单独的menu，是不是应该把job和cronjob都列到工作负载里，和deployment它们并列？
![Screen Shot 2019-09-29 at 3 57 37 PM](https://user-images.githubusercontent.com/28859385/65828852-07992f80-e2d2-11e9-9f57-aa839322465f.png)

**Comment by Carlosfengv** [comment]
已将容器组作为单独菜单进行显示，同时优化了容器组状态，增加了 Conditions 信息
