### ISSUE TITLE
[9.29] 2.1 安装完 devops 报错 

### ISSUE THREAD

**Issue by minghaoye** [kubesphere/kubesphere#840]
### 环境
Ubuntu Server 18.04.1 LTS 64bit
all in one

#### Request URL: http://139.198.17.39:30880/kapis/tenant.kubesphere.io/v1alpha2/workspaces/console-ae/devops?paging=limit%3D10%2Cpage%3D1

Status Code: 500 Internal Server Error

#### response 
Code: 500
Message: "Error 1049: Unknown database 'devops'"

**Comment by shaowenchen** [comment]
没有安装成功，看下 pod，应该有 error。

登陆 pod 

```bash
$ kubectl exec -it -n kubesphere-system  kubesphere-installer-58b6d85b55-x9hwn bash
```

编辑文件

```bash
 vi /kubesphere/installer/roles/ks-devops/s2i/tasks/main.yaml
```

删掉 

- - name: S2I | Creating S2I crds
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/s2i/s2i-crd.yaml"

再次编辑 cm ，等待生效。

**Comment by runzexia** [comment]
fix by https://github.com/kubesphere/ks-installer/pull/168

**Comment by runzexia** [comment]
Fixed
