### ISSUE TITLE
关于roadmap的AI platform

### ISSUE THREAD

**Issue by OdinLin** [kubesphere/kubesphere#842]
想问下， readme上面 2019的roadmap上面有ai platform的关键词，请问下这块是否有具体的排期或者能描述下这块大致的功能展望吗。 PS: "Futrue Realeases" 拼写错了  应该是 "Future Realeases"  ：）

**Comment by benjaminhuo** [comment]
AI Platform 大概得明年上半年了
功能展望主要是训练，推理，存储及数据管理吧

**Comment by OdinLin** [comment]
哇  棒极了！ 那会是以应用的存在还是直接集成进平台呢

**Comment by benjaminhuo** [comment]
作为独立的组件选装

**Comment by OdinLin** [comment]
期待~
