### ISSUE TITLE
关于日志抓取不到

### ISSUE THREAD

**Issue by anstns** [kubesphere/kubesphere#845]
场景：我们是用二进制来搭建的kubernetes，修改了docker挂载，开启了聚合，现在fluent-bit抓取不到日志，我们外部es数据，用helm安装fluentd 可以正常抓取数据，但是页面依然不展示日志，求大佬解决一下，比较急
![image](https://user-images.githubusercontent.com/36152763/65835449-d2fc9680-e318-11e9-9633-7a9068e96891.png)
![image](https://user-images.githubusercontent.com/36152763/65835458-f32c5580-e318-11e9-9905-c0a39eecce88.png)
![image](https://user-images.githubusercontent.com/36152763/65835465-093a1600-e319-11e9-9ae4-d243abb3171f.png)

**Comment by anstns** [comment]
![image](https://user-images.githubusercontent.com/36152763/65837375-22e35980-e329-11e9-9ec8-8b372e4d37e3.png)
![image](https://user-images.githubusercontent.com/36152763/65837386-5b833300-e329-11e9-92a2-be757fb72f70.png)
![image](https://user-images.githubusercontent.com/36152763/65837392-75247a80-e329-11e9-9365-c2e4aaaca394.png)

**Comment by huanggze** [comment]
不好意思，放假回复迟了。fluent-bit 没有报错，应该是正常运行了。请问修改 cm 里的 containersMountedPath 是安装后修改的还是安装时？如果已安装后修改的，需要重启 fluent-bit operator 具体看 #680 

外部的 es 有没有数据呢？`curl <es_ip>:9200/_cat/indices` 看一下，kubesphere 的日志 index 都是 `ks-logstash-log-<日期>` 的方式命名。有没有产生数据？

**Comment by anstns** [comment]
已经好用了谢谢

**Comment by huanggze** [comment]
好的。请问是什么原因呢？方便其他人参考

**Comment by anstns** [comment]
正常配置就可以使用
