### ISSUE TITLE
disable devops plugin but still show devops

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#847]
* [ ] as shown below
<img width="285" alt="Screen Shot 2019-09-30 at 10 43 31 AM" src="https://user-images.githubusercontent.com/28859385/65846103-4c26d880-e36f-11e9-8524-fd23a480d684.png">

**Comment by leoendless** [comment]
Please check the value of ``globals.ksConfig.devops`` in the browser console.

**Comment by rayzhou2017** [comment]
Here is the console http://139.198.14.155:30880/workspaces/ray-ws/overview/usage

**Comment by leoendless** [comment]
No devops found in ray-ws workspace

**Comment by rayzhou2017** [comment]
use ray account to check, not admin

**Comment by leoendless** [comment]
same issue as https://github.com/kubesphere/kubesphere/issues/850
