### ISSUE TITLE
【2.1】Jenkins 没有对 Sonarqube 插件初始化参数，导致流水线找不到配置

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#848]
需要增加配置的位置：

添加  SonarQube servers 相关信息即可。

![image](https://user-images.githubusercontent.com/43693241/65856940-670c4380-e395-11e9-9a8b-b1b28b014fd5.png)

导致的报错：

ERROR: SonarQube installation defined in this job (SonarQube) does not match any configured installation. Number of installations that can be configured: 0.

**Comment by runzexia** [comment]
@pixiake

**Comment by runzexia** [comment]
fixed
