### ISSUE TITLE
普通用户登录显示应用商店

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#850]
* [x] 系统没有装应用商店，但登录依然显示
<img width="959" alt="Screen Shot 2019-09-30 at 3 27 53 PM" src="https://user-images.githubusercontent.com/28859385/65857721-fcf49e00-e396-11e9-9b35-242b8495c72b.png">

**Comment by leoendless** [comment]
@zryfish /kapis/v1alpha1/configz 这个接口普通用户调用报错 403 ，而且这里的具体信息最好能够隐藏吧
