### ISSUE TITLE
【2.1】创建示例应用时，提示不准确，找不到【高级设置】选项

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#853]
创建示例 bookinfo 示例应用时，提示【在高级设置中设置外网访问方式】

![image](https://user-images.githubusercontent.com/43693241/65858738-4940dd80-e399-11e9-99cf-9f52f6b36cc6.png)

实际上没有【高级设置】的选项，应该是在【应用路由】中设置网关。

**Comment by leoendless** [comment]
需要修复下权限

**Comment by daiqingliang** [comment]
![新建的项目，没有外网访问菜单](https://user-images.githubusercontent.com/25365956/66541959-b7d52680-eb63-11e9-8fd7-de36f88d3b84.jpg)

文档提示有问题，或者更新文档或者修改前端
