### ISSUE TITLE
【2.1】发送测试邮件时，提示404 page not found

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#855]
1、安装notifaction组件；

2、进入平台设置-邮件服务器，正确填写相关参数，点发送测试邮件；
提示404 page not found

<img width="939" alt="1569837745(1)" src="https://user-images.githubusercontent.com/7677050/65869179-8367aa80-e3ac-11e9-81d7-27d527ccf737.png">

**Comment by LDWinsky** [comment]
已经解决了这个问题。

**Comment by justahole** [comment]
API已经接入，现在没有这个问题了。

**Comment by mayuhope** [comment]
此问题经验证已修复
