### ISSUE TITLE
【2.1】Istio 灰度发布功能，选择镜像流量时，添加容器镜像报错 500

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/kubesphere#857]
![image](https://user-images.githubusercontent.com/43693241/65870222-48ff0d00-e3ae-11e9-91c9-c013dddaf66f.png)

这个错误，在创建工作负载时，也会复现。应该是镜像 search API 的问题。

**Comment by leoendless** [comment]
Fixed
