### ISSUE TITLE
【2.1】禁用devops后，在企业空间列表仍然显示了devops 工程数量

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#860]
1、修改 ks-installer 的 configmap 禁用devops组件；

2、登录后进入一个企业空间，点击左上方的空间列表，查看企业空间，发现企业空间列表仍然显示了devops工程数量；
<img width="547" alt="777" src="https://user-images.githubusercontent.com/7677050/65892041-36013280-e3d8-11e9-80cd-233dca64a08c.PNG">

**Comment by runzexia** [comment]
@leoendless

**Comment by leoendless** [comment]
Fixed

**Comment by mayuhope** [comment]
此问题并没有修复，仍然存在：

![image](https://user-images.githubusercontent.com/7677050/67265172-abe05180-f4df-11e9-8eaf-3e2c27f14199.png)

/assign  @leoendless

**Comment by leoendless** [comment]
Fixed

**Comment by mayuhope** [comment]
已验证
