### ISSUE TITLE
【2.1】项目内告警策略，尚未触发告警时，最近告警时间为 Invalid date

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#863]
1、进入一个项目，监控告警-告警策略中添加一条告警策略；

2、在该告警策略尚未触发告警时，最近告警时间显示为Invalid date；
<img width="612" alt="444" src="https://user-images.githubusercontent.com/7677050/65928146-4bee1200-e42f-11e9-9f75-d9d5fe6de9db.PNG">

**Comment by leoendless** [comment]
Fixed

**Comment by mayuhope** [comment]
经验证已修复
