### ISSUE TITLE
【2.1】单独开启安装 DevOps 后，创建 DevOps 工程报 Service Unavailable

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#866]
单独开启安装 DevOps 后，创建 DevOps 工程时报 Service Unavailable，DevOps 组件都是正常的

![image](https://user-images.githubusercontent.com/40452856/66097792-5bf22700-e5d2-11e9-9130-8e0f9a38c6a0.png)
![image](https://user-images.githubusercontent.com/40452856/66097802-66142580-e5d2-11e9-8f39-130588040cbd.png)

**Comment by soulseen** [comment]
这个是devops的组件没有装完全，jenkins，s2i等都没有装。

**Comment by daiqingliang** [comment]
![jenkins组件都起来了，但是创建DevOps项目失败](https://user-images.githubusercontent.com/25365956/66541464-f23dc400-eb61-11e9-98bd-510c963d19ed.jpg)

**Comment by runzexia** [comment]
@daiqingliang 你的版本是2.1吗

**Comment by runzexia** [comment]
@daiqingliang 现在这个仓库默认应该是2.0.2，可以看下jenkins日志有什么报错吗。
2.1.0版本还没有正式发布，在测试中

**Comment by daiqingliang** [comment]
@runzexia 
![云之家图片20191010140848](https://user-images.githubusercontent.com/25365956/66543411-e35a1000-eb67-11e9-864d-4d558a5f1216.jpg)
![云之家图片20191010140956](https://user-images.githubusercontent.com/25365956/66543425-e8b75a80-eb67-11e9-93ee-148d8dd1ecf8.jpg)

的确有报错，仓库是2.0.2，那我的版本为啥会是2.1.0呢？
这个问题怎么解决？

**Comment by runzexia** [comment]
@daiqingliang 可以提供下远程访问方式吗，可以的话请发到邮箱 kubesphere@yunify.com

**Comment by daiqingliang** [comment]
@runzexia 我这是在内网搭的。。。不支持外网访问

**Comment by runzexia** [comment]
安装的时候是使用的installer哪个分支的yaml文件呢
提供向日葵/tv12也是可以的
@daiqingliang

**Comment by daiqingliang** [comment]
@runzexia 
我是在已有的k8s 1.14上安装KubeSphere，用的是官方的安装文档：https://kubesphere.io/docs/v2.0/zh-CN/installation/install-on-k8s/
yaml是从 git clone https://github.com/kubesphere/ks-installer.git 获取
ks-installer/deploy/kubesphere-installer.yaml 
pod 如下：
![111](https://user-images.githubusercontent.com/25365956/66557826-1f4f9e00-eb85-11e9-9900-9f4b7dcb58b2.jpg)
![222](https://user-images.githubusercontent.com/25365956/66557864-30001400-eb85-11e9-83ad-fda8c45b4187.jpg)

登录kubesphere dashboard后：
![dashboard](https://user-images.githubusercontent.com/25365956/66557930-4b6b1f00-eb85-11e9-95fe-d99d4a6c81f6.jpg)
版本信息：
![1570700277253](https://user-images.githubusercontent.com/25365956/66557955-56be4a80-eb85-11e9-83ed-d287637f2086.jpg)

**Comment by daiqingliang** [comment]
@runzexia 向日葵和teamview都木得，因为是内网环境

**Comment by runzexia** [comment]
@daiqingliang 现在镜像有一些问题，修复好我告知您

**Comment by daiqingliang** [comment]
@runzexia 好的，非常感谢

**Comment by runzexia** [comment]
@daiqingliang 需要卸载掉重新安装下，现在已经修复了

**Comment by daiqingliang** [comment]
@runzexia 是单独安装Jenkin镜像jenkins:2.138.4，还是需要重新安装kubeSphere?

**Comment by runzexia** [comment]
重新安装下kubesphere

**Comment by daiqingliang** [comment]
@runzexia 
卸载使用：https://github.com/kubesphere/ks-installer/blob/master/scripts/kubesphere-delete.sh 这个就可以？
然后重新安装的时候，我应该用 https://github.com/kubesphere/ks-installer/ 里的哪个分支呢？
advanced-2.0.2 还是master?

**Comment by runzexia** [comment]
@daiqingliang 可以使用master分支上的脚本进行卸载
安装的时候仍然使用advanced-2.0.2分支

**Comment by daiqingliang** [comment]
@runzexia 
卸载完了，有些pod需要手动删除。
安装之前我有个疑问，能告诉我修复的镜像是哪几个吗？
我这边因为网络的问题，很多镜像是手动下载然后修改tag的

**Comment by pixiake** [comment]
kubespheredev/ks-installer:advanced-2.0.2

**Comment by daiqingliang** [comment]
@runzexia @pixiake 
创建devops工程成功了，多谢两位！

**Comment by runzexia** [comment]
@FeynmanZhou 已修复

**Comment by wartih** [comment]
我现在在ubuntu 16.04.6 虚拟机上使用你们的脚本allinone模式安装2.0.2 还是出现了这个问题
![image](https://user-images.githubusercontent.com/22047859/71391990-6b1cca00-2641-11ea-88d7-575371d235b0.png)
在最开始有报错：
![image](https://user-images.githubusercontent.com/22047859/71392015-7ec83080-2641-11ea-96d5-cc2c498cbafe.png)

后来似乎没事儿了？
![image](https://user-images.githubusercontent.com/22047859/71392028-8be51f80-2641-11ea-897c-77f62a4d546c.png)

**Comment by wartih** [comment]
@FeynmanZhou @runzexia @pixiake

**Comment by wartih** [comment]
![image](https://user-images.githubusercontent.com/22047859/71392146-0a41c180-2642-11ea-9ee6-e7a58052e37b.png)
