### ISSUE TITLE
install-gitlab-harbor.yml 语法问题

### ISSUE THREAD

**Issue by haozi23333** [kubesphere/kubesphere#867]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
已结安装完成kubesphere, 需要补上Harbor-Gitlab
执行gitlab-harbor.sh,  提示 install-gitlab-harbor.yml 语法问题, 均按照官方文档执行
`wget https://raw.githubusercontent.com/kubesphere/tutorial/master/tutorial%203%20-%20install-gitlab-harbor/install-gitlab-harbor.yml`

```yaml
---

- hosts: k8s-cluster
  roles:
    - kubesphere-defaults
    - prepare/nodes

- hosts: kube-master[0]
  roles:
    - kubesphere-defaults
    - { role: ks-devops/harbor, when: "harbor_enable == true" }
    - { role: ks-devops/gitlab, when: "gitlab_enable == true" }[
```
```sh

[root@haozi scripts]# chmod +x gitlab-harbor.sh && ./gitlab-harbor.sh


################################################
         gitlab-harbor Installer Menu                                                                                                                     ################################################
*   1) Harbor
*   2) Gitlab
*   3) Harbor-Gitlab
################################################
https://kubesphere.io/               2019-10-05
################################################
Please input an option: 2
2
 [WARNING]: Unable to parse /root/ks-installer/k8s/inventory/local/hosts.ini as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available                                                                                 
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'                              
ERROR! the role 'kubesphere-defaults' was not found in /root/ks-installer/scripts/../kubesphere/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/root/ks-installer/scripts/../kubesphere

The error appears to be in '/root/ks-installer/kubesphere/install-gitlab-harbor.yml': line 5, column 7, but may                                           be elsewhere in the file depending on the exact syntax problem.                                                                                           
The offending line appears to be:                                                                                                                         
  roles:                                                                                                                                                      - kubesphere-defaults                                                                                                                                       ^ here                                                                                                                                              
failed!

```

**安装环境的硬件配置**

3节点 2Core8G KVM虚拟机, Centos 7.6
k8s:
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

kubesphere: 
KubeSphere Version: 2.0.2
Kubernetes Version: v1.15.3 
OpenPitrix: v0.3.5

ansible 2.8.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

**Comment by yunkunrao** [comment]
This issue is for kubeSphere version 2.0.2 and installation method was changed for latest ks 2.1 with plug-in installations enabled, doc link: https://kubesphere.com.cn/docs/v2.1/zh-CN/installation/harbor-installation/. 
And for your case, you can installer habor/gitlab with helm. Related link is as follows:
[habor](https://github.com/goharbor/harbor-helm)
[gitlab](https://docs.gitlab.com/charts/)
