### ISSUE TITLE
【2.1】应用路由端口无法指定 80

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#868]
参考 [示例二](https://kubesphere.io/docs/advanced-v2.0/zh-CN/quick-start/ingress-demo/) 指定 80 端口无法创建应用路由
![image](https://user-images.githubusercontent.com/40452856/66257778-bc9a8300-e7cf-11e9-99e1-052c0f6eee91.png)

**Comment by leoendless** [comment]
Fixed
