### ISSUE TITLE
k8sv1.16.0 安装kubesphere2.0.2报错-Error: validation failed: unable to recognize \"\": no matches for kind \"Deployment\" in version \"extensions/v1beta1\""

### ISSUE THREAD

**Issue by 2804337402** [kubesphere/kubesphere#870]
TASK [ks-devops/sonarqube : Sonarqube | Deploy Sonarqube] **********************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm upgrade --install ks-sonarqube  /etc/kubesphere/sonarqube/sonarqube-0.13.5.tgz -f /etc/kubesphere/sonarqube/custom-values-sonarqube.yaml  --namespace kubesphere-devops-system\n", "delta": "0:00:00.384153", "end": "2019-10-06 19:07:40.355654", "msg": "non-zero return code", "rc": 1, "start": "2019-10-06 19:07:39.971501", "stderr": "Error: validation failed: unable to recognize \"\": no matches for kind \"Deployment\" in version \"extensions/v1beta1\"", "stderr_lines": ["Error: validation failed: unable to recognize \"\": no matches for kind \"Deployment\" in version \"extensions/v1beta1\""], "stdout": "Release \"ks-sonarqube\" does not exist. Installing it now.", "stdout_lines": ["Release \"ks-sonarqube\" does not exist. Installing it now."]}

![微信图片_20191007031513](https://user-images.githubusercontent.com/25359798/66274385-b3cdae00-e8b0-11e9-90df-a2246f8cdb3b.png)

**Comment by runzexia** [comment]
暂时不支持k8s 1.16，目前可用版本为1.13.x、1.14.x、1.15.x

**Comment by cjd9023** [comment]
请问有考虑支持1.16.x吗

**Comment by zryfish** [comment]
k8s 1.16 去掉了 externsions/v1beta1 api group，会导致helm安装有问题，建议先用1.16之前的版本，kubesphere 3.0 会支持1.16
