### ISSUE TITLE
all-in-one模式，安装kubesphere完成后，单独安装 Harbor，没有端口访问

### ISSUE THREAD

**Issue by zwqzhangweiqiang** [kubesphere/kubesphere#871]
kubesphere采用all-in-one安装模式，安装版本为2.02，安装完成后，单独安装harbor，安装完成后，查看端口，没有，也不能访问，安装步骤如下：
1.wget https://raw.githubusercontent.com/kubesphere/tutorial/master/tutorial%203%20-%20install-gitlab-harbor/install-gitlab-harbor.yml
2. wget https://raw.githubusercontent.com/kubesphere/tutorial/master/tutorial%203%20-%20install-gitlab-harbor/gitlab-harbor.sh
3.chmod +x gitlab-harbor.sh && ./gitlab-harbor.sh
脚本执行完后如图：
![图片](https://user-images.githubusercontent.com/14371089/66368034-5ed18b00-e9c9-11e9-9886-2e3a4f77c7cd.png)

**Comment by pixiake** [comment]
@Forest-L

**Comment by Forest-L** [comment]
```
- { role: ks-devops/harbor, when: "harbor_enable == true" }
- { role: ks-devops/gitlab, when: "gitlab_enable == true" }
改成如下，再执行脚本
- { role: ks-devops/harbor, when: harbor_enable|default(true) }
- { role: ks-devops/gitlab, when: gitlab_enable|default(true) }
```

**Comment by zwqzhangweiqiang** [comment]
解决
