### ISSUE TITLE
【2.1】An error occurred while editing user roles

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#874]
1、Enter platform management-Account management；

2、Select a user and click edit，then  modify user roles，an error occurred：
<img width="955" alt="1570523826(1)" src="https://user-images.githubusercontent.com/7677050/66380778-a583ad00-e9ea-11e9-8611-74e3017e6c45.png">

**Comment by wansir** [comment]
预期的错误，数据写入 超出了最大尝试次数

**Comment by mayuhope** [comment]
经经验已修复
