### ISSUE TITLE
【2.1】安装完devops组建后，界面上未显示构建

### ISSUE THREAD

**Issue by soulseen** [kubesphere/kubesphere#877]
**Describe the bug(描述下问题)**

1.修改insatll configmap，安装完devops。  

2.进入项目，左侧没有显示“构建”

![image](https://user-images.githubusercontent.com/16031013/66385965-ff3ca500-e9f3-11e9-96c3-4db6829a40ed.png)
![image](https://user-images.githubusercontent.com/16031013/66385983-06fc4980-e9f4-11e9-83a3-3ef691263a88.png)

**Comment by leoendless** [comment]
项目里的imagebuilder 权限漏了

**Comment by runzexia** [comment]
/reopen

@leoendless @wansir 最近的安装包还是不能看到构建

**Comment by soulseen** [comment]
/close
20191012的安装包修复了
