### ISSUE TITLE
[设计] 项目配额编辑重构

### ISSUE THREAD

**Issue by Carlosfengv** [kubesphere/kubesphere#879]
- [x] 优化项目设置，基础设置中的配额修改

[查看设计稿](zpl://screen?sid=5d8adc5eb6c1b60256e5f2b7&pid=5cbe7fbc2f55d8b73f56811b)

zpl://screen?sid=5d8adc5eb6c1b60256e5f2b7&pid=5cbe7fbc2f55d8b73f56811b

**Comment by leoendless** [comment]
Done
