### ISSUE TITLE
remove unnecessary logs

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#880]
ks-apigateway and ks-console produces redundant logs. consider to remove them

![image](https://user-images.githubusercontent.com/22350668/66449990-8425ce00-ea89-11e9-8bd2-9f28f3f2f39f.png)

**Comment by leoendless** [comment]
这应该是正常的把， 数据就是这么流动的

**Comment by huanggze** [comment]
yes but unnecessary. No need to feed them into es storage
