### ISSUE TITLE
protocol drop down list is not wide enough

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/kubesphere#885]
**General remarks**

**Describe the bug(描述下问题)**
协议下拉列表部分文字隐藏

For UI issues please also add a screenshot that shows the issue.
![Jietu20191009-173606](https://user-images.githubusercontent.com/28883416/66470321-f0212a00-eabb-11e9-895b-eb85b6cc0cd6.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0 dev 20191009

**Environment(环境的硬件配置)**
MacOS +  Safari

**To Reproduce(复现步骤)**
1. 创建简单服务
2. 选择工作负载
3. 下拉选择协议，页面适配有问题，部分文字被隐藏

**Comment by leoendless** [comment]
Fixed

**Comment by calvinyv** [comment]
verified
