### ISSUE TITLE
Devops projects are visible to enterprise space members when devops is disabled

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#886]
1、Modify ks-installer configmap to disable devops component;

2、Enter the enterprise space-members management，click on a member；

3、You can see the devops project page，click it ，an error has occurred：
Internal  server  error；

![image](https://user-images.githubusercontent.com/7677050/66471710-658dfa00-eabe-11e9-963e-709f71f6e050.png)

**Comment by rayzhou2017** [comment]
This one might have been fixed.

**Comment by mayuhope** [comment]
已验证
