### ISSUE TITLE
【2.1】It's invalid to deploy an App from imported App repository

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#887]
I've deploy an app named "emq x" from imported app repo "https://repos.emqx.io/charts", but I can't see any workloads, it seems the api is invalid.

**Comment by FeynmanZhou** [comment]
@wansir  One more issue I got from this repo "https://repos.emqx.io/charts", I've deploy the emq App from this repo but I didn't see any workloads under this app. It's normal when using command "helm install emq chart" instead.

![image](https://user-images.githubusercontent.com/40452856/66663223-e09d0f00-ec7c-11e9-9be2-c51bd73a53cc.png)

**Comment by zheng1** [comment]
![截屏2019-10-2318 26 51](https://user-images.githubusercontent.com/4156721/67384776-62b5fd80-f5c4-11e9-94c7-8e7e65386edd.png)

原因是emqx是在values.yaml里面指定namespace, 这个不是一个标准的做法.

我们还需要想个更好的办法来处理这类问题

**Comment by FeynmanZhou** [comment]
@zheng1 噢 原来是这个原因，这个手动改一下 namespace 作为 workaround 也可以接受，不算是 OP 的 bug，如果有更优雅的办法，比如自动获取当前的 ns 然后传给 app 的 values 那就更好了。
