### ISSUE TITLE
【2.1】Failed to upload app

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/kubesphere#890]
Just uploaded a Nginx app but it returns following errors.
![image](https://user-images.githubusercontent.com/40452856/66545961-68482800-eb6e-11e9-93bc-364e6faeaf29.png)

![image](https://user-images.githubusercontent.com/40452856/66546038-9d547a80-eb6e-11e9-8557-d6cf01b5fc3a.png)

**Comment by rayzhou2017** [comment]
verified
