### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by agile-com** [kubesphere/kubesphere#891]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
fatal: [ks-allinone]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm upgrade --install ks-sonarqube /etc/kubesphere/sonarqube/sonarqube-0.13.5.tgz -f /etc/kubesphere/sonarqube/custom-values-sonarqube.yaml --namespace kubesphere-devops-system", "delta": "0:00:02.147002", "end": "2019-10-10 14:38:01.919506", "msg": "non-zero return code", "rc": 1, "start": "2019-10-10 14:37:59.772504", "stderr": "Error: UPGRADE FAILED: Get https://10.233.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%!D(MISSING)ks-sonarqube%!C(MISSING)OWNER%!D(MISSING)TILLER%!C(MISSING)STATUS%!D(MISSING)DEPLOYED: dial tcp 10.233.0.1:443: connect: no route to host", "stderr_lines": ["Error: UPGRADE FAILED: Get https://10.233.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=NAME%!D(MISSING)ks-sonarqube%!C(MISSING)OWNER%!D(MISSING)TILLER%!C(MISSING)STATUS%!D(MISSING)DEPLOYED: dial tcp 10.233.0.1:443: connect: no route to host"], "stdout": "", "stdout_lines": []}
**安装环境的硬件配置**

[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)
阿里云主机
**错误信息或截图**

**Installer版本**
KubeSphere 高级版 (Advanced Edition 2.0.2)

**Comment by rayzhou2017** [comment]
https://github.com/kubesphere/ks-installer/issues/23 到这儿找找答案
