### ISSUE TITLE
dockerhub.qingcloud.com不可用

### ISSUE THREAD

**Issue by MarsHanZhen** [kubesphere/kubesphere#892]
**问题描述**
playbook中的账号密码docker login失败
**安装环境的硬件配置**
ubuntu18.04 all-in-one安装;  本地笔记本安装

**错误信息或截图**
fatal: [ks-allinone]: FAILED! => {"attempts": 5, "changed": true, "cmd": "docker login -u guest -p guest dockerhub.qingcloud.com", "delta": "0:00:00.246694", "end": "2019-10-10 16:12:39.520770", "msg": "non-zero return code", "rc": 1, "start": "2019-10-10 16:12:39.274076", "stderr": "WARNING! Using --password via the CLI is insecure. Use --password-stdin.\nError response from daemon: Get https://dockerhub.qingcloud.com/v2/: Get https://dockerauth.qingcloud.com:6000/auth?account=guest&client_id=docker&offline_token=true&service=dockerhub.qingcloud.com: Forbidden", "stderr_lines": ["WARNING! Using --password via the CLI is insecure. Use --password-stdin.", "Error response from daemon: Get https://dockerhub.qingcloud.com/v2/: Get https://dockerauth.qingcloud.com:6000/auth?account=guest&client_id=docker&offline_token=true&service=dockerhub.qingcloud.com: Forbidden"], "stdout": "", "stdout_lines": []}

**Installer版本**
kubesphere-all-advanced-2.0.2

**Comment by rayzhou2017** [comment]
查一下防火墙，你在机器上手动登录看看

**Comment by MarsHanZhen** [comment]
2天前我也手动登录了,当时登录不上,刚才试了下,能登陆了

**Comment by 357220278** [comment]
redhat7.4 同样的问题安装了6次都是卡在这里
