### ISSUE TITLE
kubesphere中的有状态副本集（statefulset）的IP固定是如何做到的？

### ISSUE THREAD

**Issue by Liuyanglong** [kubesphere/kubesphere#895]
kubesphere中的有状态副本集（statefulset）的IP固定是如何做到的？即使删除了statefulset的pod，新启动的pod的ip依然不变，很好奇，求解惑。

**Comment by rayzhou2017** [comment]
应该不是固定的，可能是碰巧。你可以taint一下节点，然后kill上面的pod，让它调度到其它节点试试

**Comment by Liuyanglong** [comment]
> 应该不是固定的，可能是碰巧。你可以taint一下节点，然后kill上面的pod，让它调度到其它节点试试

在同一节点上kill pod，重启后的ip是固定的，这是如何做到的？

**Comment by rayzhou2017** [comment]
这个应该是CNI的特性

**Comment by magicsong** [comment]
@Liuyanglong statefulset的podname是固定的，calico中的同一个name的pod ip也是有缓存的。
