### ISSUE TITLE
all in one pvc capacity 

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#900]
**General remarks**

![image](https://user-images.githubusercontent.com/31230341/66623549-c0d6fe00-ec1e-11e9-99e1-a088c2bea32a.png)

The capacity display is incorrect, it seems to be the host capacity?
/cc @huanggze @wnxn 
/milestone2.1.0
/area monitoring storage

**Comment by wnxn** [comment]
In Ks 2.1, we use Openebs to support local volume. 
Openebs creates a directory on each nodes. Each PVC is a sub-directory of the directory Openebs created.
In my opinion, this situation seems reasonable. 

```
kubectl get sc openebs-local -oyaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: "/var/openebs/local"
    openebs.io/cas-type: local
  creationTimestamp: "2019-08-20T07:42:14Z"
  name: openebs-local
  resourceVersion: "1885175"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/openebs-local
  uid: 06fcc37d-c31e-11e9-a026-52549938a379
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```

**Comment by runzexia** [comment]
![image](https://user-images.githubusercontent.com/31230341/66630285-7ceff300-ec36-11e9-978a-4140635fdea0.png)
Tn the detail page, the capacity of pvc is displayed as 20Gi 
@wnxn

**Comment by wnxn** [comment]
The capacity is fake in some storage system.
