### ISSUE TITLE
workbench component monitoring list

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#901]
* [x] 没有安装的组件是不是不应该显示，不然用户会觉得很奇怪
![Screen Shot 2019-10-11 at 3 19 05 PM](https://user-images.githubusercontent.com/28859385/66632436-0b667380-ec3b-11e9-9fc6-338f288926f5.png)

**Comment by leoendless** [comment]
Updated

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191012
