### ISSUE TITLE
初装系统有未分配ns

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#904]
* [x] 如下图所示

![Screen Shot 2019-10-11 at 3 50 55 PM](https://user-images.githubusercontent.com/28859385/66634389-8fbaf580-ec3f-11e9-8b77-5b98f5568222.png)

**Comment by pixiake** [comment]
fixed

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191013
