### ISSUE TITLE
工作台k8s pod监控数量有误

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#905]
* [x] 见下图，应该是4个
![Screen Shot 2019-10-11 at 4 01 57 PM](https://user-images.githubusercontent.com/28859385/66634851-867e5880-ec40-11e9-8a2c-1ce66f11a30f.png)
![Screen Shot 2019-10-11 at 4 02 06 PM](https://user-images.githubusercontent.com/28859385/66634859-8b430c80-ec40-11e9-934c-ee45345cff36.png)

**Comment by rayzhou2017** [comment]
2.1.0-dev-20191012 看起来是把dashboard改成服务数量，跟服务组件数字对齐，但现在是monitoring数字不对，见下图，dashboard的数字还是pod的数量。

<img width="776" alt="Screen Shot 2019-10-12 at 9 42 41 PM" src="https://user-images.githubusercontent.com/28859385/66702404-fa505c00-ed39-11e9-89b8-cc9613d3c8fd.png">
<img width="807" alt="Screen Shot 2019-10-12 at 9 42 34 PM" src="https://user-images.githubusercontent.com/28859385/66702411-050af100-ed3a-11e9-97fd-ae117eae5bd7.png">

**Comment by rayzhou2017** [comment]
还有这个地方的监控数字，他们不是调用的一个api吗？
<img width="1179" alt="Screen Shot 2019-10-12 at 9 51 47 PM" src="https://user-images.githubusercontent.com/28859385/66702465-7cd91b80-ed3a-11e9-9a80-5beb6d592210.png">

**Comment by justahole** [comment]
传的参数不同，这边漏了。

**Comment by rayzhou2017** [comment]
monitoring还没有改过来. /cc @justahole 

![Screen Shot 2019-10-15 at 11 43 42 AM](https://user-images.githubusercontent.com/28859385/66798628-399cc980-ef41-11e9-9094-4509b4b95643.png)
![Screen Shot 2019-10-15 at 11 43 58 AM](https://user-images.githubusercontent.com/28859385/66798635-3e617d80-ef41-11e9-9ad4-8f17dfbba9a4.png)
![Screen Shot 2019-10-15 at 11 44 39 AM](https://user-images.githubusercontent.com/28859385/66798651-48837c00-ef41-11e9-8dc2-54a9e9f567b2.png)

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191017
