### ISSUE TITLE
The deployment description information cannot be displayed

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#908]
1、创建一个工作负载-部署，填写描述信息；

2、创建完成后查看列表中部署，发现描述信息没有显示
![image](https://user-images.githubusercontent.com/7677050/66638899-66eb2e00-ec48-11e9-9cc6-9335c7f84c07.png)

**Comment by leoendless** [comment]
Fixed

**Comment by mayuhope** [comment]
经验证已修复
