### ISSUE TITLE
邮服务器配置完成保存后，切换页面后测试邮箱接受地址无法保存

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#911]
1、进入邮件服务器页面，配置SMTP 服务器地址、SMTP 用户、SMTP密码、发件人、测试邮箱收件地址，发送测试邮件成功，点保存，保存成功；

2、切换页面到日志收集再切换回来，发现刚才填写的测试邮箱接受地址无法显示；
![image](https://user-images.githubusercontent.com/7677050/66640272-3fe22b80-ec4b-11e9-87ac-1bbdcaa4d182.png)

**Comment by justahole** [comment]
@mayuhope 这个数据并没有存入数据库中，只是作为检验当前发送的邮件是否能收到的功能而已

**Comment by mayuhope** [comment]
> @mayuhope 这个数据并没有存入数据库中，只是作为检验当前发送的邮件是否能收到的功能而已
感觉存起来比较好呀，不然用户不知道自己填了什么

**Comment by huojiao2006** [comment]
测试邮箱只是用于测试的，临时的，并不用于系统设置，因此没有保存，也没必要保存。

**Comment by mayuhope** [comment]
好的，那先维持现状
