### ISSUE TITLE
普通用户看不到工具箱

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#912]
* [ ] 如下图
![Screen Shot 2019-10-11 at 5 29 52 PM](https://user-images.githubusercontent.com/28859385/66641144-be8b9880-ec4c-11e9-9a0c-50544c45cb91.png)

**Comment by rayzhou2017** [comment]
现在能看到日志查询，kubeconfig不应该显示吗？

**Comment by leoendless** [comment]
@wansir 看下吧

**Comment by wansir** [comment]
@leoendless  #797 普通用户的kubeconfig也可以开放下载

**Comment by wansir** [comment]
所有用户都可以提供日志查询的入口, `tenent.kubesphere.io`下的API已经针对用户做了权限校验

**Comment by leoendless** [comment]
Fixed

**Comment by rayzhou2017** [comment]
verified
