### ISSUE TITLE
用户角色描述信息无法显示

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#913]
用户角色描述在此处无法显示：

![image](https://user-images.githubusercontent.com/7677050/66641485-7620aa80-ec4d-11e9-8f0a-cea92d238e33.png)

**Comment by leoendless** [comment]
Fixed

**Comment by mayuhope** [comment]
![image](https://user-images.githubusercontent.com/7677050/67063729-63046200-f19a-11e9-9568-ada65d781692.png)
现在是这样，觉得ok
