### ISSUE TITLE
无法上传文件，提示404 page not found!

### ISSUE THREAD

**Issue by daiqingliang** [kubesphere/kubesphere#915]
创建服务的时候，无法上传文件（jar/java等等文件都无法上传），提示404 page not found!
我版本是2.0.1，已有k8s(1.14)，使用https://github.com/kubesphere/ks-installer/ --advanced-2.0.2 分支搭建的kubesphere。
使用kubectl get pod --all-namespaces 查看所有pod均正常

![error1](https://user-images.githubusercontent.com/25365956/66642050-7f5e4700-ec4e-11e9-857a-93f17918ff91.jpg)

**Comment by daiqingliang** [comment]
希望关注一下，这个功能还是很有用。

**Comment by minghaoye** [comment]
@pixiake 这个是2.10的功能

**Comment by daiqingliang** [comment]
@minghaoye 2.1.0版本现在有上线的时间线安排吗？

**Comment by rayzhou2017** [comment]
@daiqingliang https://kubesphere.io/forum/d/19-2-1-ga

**Comment by minghaoye** [comment]
前后端版本不一致，感觉是前端的镜像拉错了，
ks-console 换回2.02的吧，（dockerhub.qingcloud.com/kubesphere/ks-console:advanced-2.0.2）
