### ISSUE TITLE
在企业空间添加仓库后，通过应用仓库部署应用失败

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#916]
1、进入企业空间，企业空间管理-应用仓库，创建仓库，填写URL地址，添加仓库成功；

2、进入项目，应用负载-应用-应用模板，点击部署新应用，选择应用仓库，选择一款应用例如fluentd，按步骤点击部署，没有任何提示错误，但是实际结果部署失败，没有显示任何应用；
前端请求如下：

![image](https://user-images.githubusercontent.com/7677050/66644721-3d380400-ec54-11e9-8c84-2fd873bcf13e.png)

**Comment by wansir** [comment]
前端已修复

**Comment by mayuhope** [comment]
已修复
