### ISSUE TITLE
allinone ks-console默认有2个

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#922]
* [ ] 如图所示，allinone应该是一个，多节点才是两个
<img width="1126" alt="Screen Shot 2019-10-12 at 9 32 26 AM" src="https://user-images.githubusercontent.com/28859385/66692674-43b99080-ecd3-11e9-81b8-6d068437746d.png">

**Comment by pixiake** [comment]
fixed

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191013
