### ISSUE TITLE
应用已经上传成功，但是仍可以选择文件上传

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#923]
1、进入企业空间-应用模板，点击创建apps，在创建应用模板页面点击【开始上传】

2、点击上传helm配置文件，在弹出的对话框中选择本地已有的nginx的配置文件，提示上传成功，但是下方还有“选择文件”的功能可以点击，点击后再次出现了上传文件的对话框：

![image](https://user-images.githubusercontent.com/7677050/66693250-97c77380-ecd9-11e9-8dbe-314ba9e228ae.png)

![image](https://user-images.githubusercontent.com/7677050/66693277-c6454e80-ecd9-11e9-8915-0c121413f43a.png)

**Comment by whDongRui** [comment]
根据刚才讨论的已经修改了。上传完配置包显示默认的，但用户还是可以选择上传应用图标。

修复代码请[参见](https://git.internal.yunify.com/KubeSphere/kubesphere-console/commit/53b2e66cce9d898efdc101574cf931673fceca72)

修改后上传成功后确认后的效果如下截图所示
![image](https://user-images.githubusercontent.com/38676269/66693804-9ef18000-ecdf-11e9-9441-54be9966ef17.png)

**Comment by mayuhope** [comment]
已修复，现在只可以上传图标
