### ISSUE TITLE
正在删除中的项目不允许进入详情

### ISSUE THREAD

**Issue by Carlosfengv** [kubesphere/kubesphere#925]
RT；
- [x]  1.  项目中左上角的切换项目功能 可以进入到正在删除的项目中去。 预期 删除中的条目为disable状态，不可点击； 设计稿 zpl://screen?sid=5da1403bed4237241ee3f408&pid=5cbe7fbc2f55d8b73f56811b

- [x]  2.  列表页中的项目，应区分出正在删除的项目，且name 为disable 状态以示不可点；
设计稿 zpl://screen?pid=5cbe7fbc2f55d8b73f56811b&sid=5d2d3385a1f25163f00fa04a

**Comment by leoendless** [comment]
Fixed
