### ISSUE TITLE
对部署编辑配置模板，关闭收集日志落盘，无法确认提交

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#929]
1、新建一个部署，在部署中开启日志落盘，日志落盘收集成功；

2、编辑部署-编辑配置模板，点击存储卷，关闭收集落盘日志，发现下方的【确认】按钮是灰色的，无法点击：

![image](https://user-images.githubusercontent.com/7677050/66694589-84bba000-ece7-11e9-827f-57f3979d0d26.png)

**Comment by leoendless** [comment]
fixed

**Comment by mayuhope** [comment]
已验证
