### ISSUE TITLE
在ks-installer的configmap设置logsidecarInjector为False时，前端项目高级设置仍可设置开启落盘日志收集

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#930]
1、后台执行kubectl edit cm -n kubesphere-system ks-installer，默认情况下logsidecarInjector:
        enabled: False

![image](https://user-images.githubusercontent.com/7677050/66694691-e3cde480-ece8-11e9-8d6f-dd262a6cd08a.png)

2、进入前端，新建一个项目，查看项目高级设置，发现落盘日志收集仍在显示，且可设置为开启：

![image](https://user-images.githubusercontent.com/7677050/66694702-1b3c9100-ece9-11e9-9720-5561844d5535.png)

**Comment by leoendless** [comment]
@zryfish 接口需要返回这层信息了
