### ISSUE TITLE
添加告警策略失败，提示错误

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#932]
1、进入平台管理-监控中心-告警策略；

2、新建一条告警策略，按步骤正确填写相关内容，到了告警规则这一步时点击下一步时，报错,后端返回了400错误：

![image](https://user-images.githubusercontent.com/7677050/66695496-f9e1a200-ecf4-11e9-8823-519f4aa6d563.png)

**Comment by justahole** [comment]
fixed

**Comment by mayuhope** [comment]
经验证已修复
