### ISSUE TITLE
the pod status in the console is displayed incorrectly.

### ISSUE THREAD

**Issue by runzexia** [kubesphere/kubesphere#934]
* [x] The status of the pod created by the job is completed, but it is displayed as running in the console.
![image](https://user-images.githubusercontent.com/31230341/66696021-9ce8ea80-ecfa-11e9-91ed-208d5d30c15c.png)
/area console
/kind bug
/assign @leoendless 
/milestone 2.1.0

**Comment by leoendless** [comment]
Fixed
