### ISSUE TITLE
 Nameserver limits were exceeded 导致csi起不来

### ISSUE THREAD

**Issue by bmingithub** [kubesphere/kubesphere#935]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**

**安装环境的硬件配置**
ap2a虚机安装，os是centos7
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**
qingcloud-csi 出现这个event，导致qingcloud-csi起不来  
Warning  DNSConfigForming  97s (x821 over 176m)    kubelet, node1  Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 100.64.11.3 114.114.114.114 119.29.29.29

/etc/resolv.conf是这样的（貌似新建的虚机都是这样）
[root@master kubesphere-all-2.1.0-dev]# cat /etc/resolv.conf
```
# Generated by NetworkManager
#search ap2a.qingcloud.com
nameserver 100.64.11.3
nameserver 114.114.114.114
nameserver 119.29.29.29
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
nameserver 1.2.4.8
```

**Installer版本**
kubesphere-all-2.1.0-dev-20191012.tar

**Comment by pixiake** [comment]
/etc/resolv.conf应该不能超过3个吧

**Comment by pixiake** [comment]
@Wiley Wang

**Comment by wnxn** [comment]
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
把多的 nameserver 删了就可以了，这是 Pod 启动的问题，和 CSI 没关系的。

**Comment by calvinyv** [comment]
solution provided
