### ISSUE TITLE
在项目中部署应用后，相应容器组无法关联到该应用

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#939]
1、创建应用chartmu-hewodb；

2、查看生成的工作负载和容器组，发现容器组没有显示对应的应用：
![image](https://user-images.githubusercontent.com/7677050/66696841-120bee00-ed02-11e9-9f44-3f79d162d8a2.png)
![image](https://user-images.githubusercontent.com/7677050/66696873-5d260100-ed02-11e9-8798-ce94f71bb973.png)

**Comment by leoendless** [comment]
@zryfish 看下吧 ， pod 里没有 metadata.labels.chart 信息

**Comment by leoendless** [comment]
目前由helm chart 生成的pod 没有相关信息，无法展示
