### ISSUE TITLE
无法创建应用分类

### ISSUE THREAD

**Issue by huanggze** [kubesphere/kubesphere#940]
![image](https://user-images.githubusercontent.com/22350668/66697248-79c43800-ed06-11e9-8425-8d5dae9c555c.png)

**Comment by huanggze** [comment]
/area/app-managment
/kind/bug
/milestone 2.1.0
/assign @leoendless

**Comment by huanggze** [comment]
现在又可以了

**Comment by leoendless** [comment]
应该是op服务还没正常启动吧
