### ISSUE TITLE
编辑项目配额时，在已有部署的情况下，建议在资源配额中显示部署这一行以便配置

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#941]
1、在项目中创建一个部署；

2、进入项目基本信息，项目管理-编辑配额，发现资源配额中默认只有容器组配置项，无部署配置项，建议默认增加一行部署配置项；
![image](https://user-images.githubusercontent.com/7677050/66697288-c0b22d80-ed06-11e9-878f-6fd3cc9992fd.png)

此问题属于improve，优先级不高

**Comment by Carlosfengv** [comment]
这种表单右侧都有一个添加项，这里是添加配额项。
我们默认屏蔽掉了一些不常用的配额项，当然如果想对资源进行配额控制的话，可以添加项，选择所需资源输入配额数量即可。
