### ISSUE TITLE
单节点环境安装gitlab 服务启动正常，但是无法访问，请问一下是什么原因

### ISSUE THREAD

**Issue by gongjx11** [kubesphere/kubesphere#945]
![image](https://user-images.githubusercontent.com/21954004/66698943-26a5b180-ed15-11e9-848b-4ef94714ac8c.png)
服务端口以经起来：
![image](https://user-images.githubusercontent.com/21954004/66698963-5654b980-ed15-11e9-9011-5ed50e020b60.png)

访问报错
![image](https://user-images.githubusercontent.com/21954004/66698950-3c1adb80-ed15-11e9-84cc-428f884855e8.png)

**Comment by rdzn-github** [comment]
在本机hosts配置域名访问试一下

**Comment by oliver-csu** [comment]
举例说明：如果在yaml中配置的域名是baidu-int.com，那么gitlab的域名是gitlab.baidu-int.com，所以如果配置的是gitlab.baidu-int.com，那么域名应该是gitlab.gitlab.baidu-int.com
