### ISSUE TITLE
后台存在pending的pod时，该项目下涉及容器组的页面均无法显示

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#948]
1、在项目pp2下创建了一个部署，镜像为alpine，挂载的存储卷访问模式为ReadWriteMany；

2、创建部署完成后，容器组页面一直转圈无法显示：
![image](https://user-images.githubusercontent.com/7677050/66699275-ded45980-ed17-11e9-817a-bc61447dda9a.png)

3、查看后台的2个pod状态如下：
![image](https://user-images.githubusercontent.com/7677050/66699286-104d2500-ed18-11e9-9367-e6951bf51fa3.png)

**Comment by leoendless** [comment]
Fixed

**Comment by mayuhope** [comment]
已验证
