### ISSUE TITLE
守护进程集的容器组副本数量配置无效

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#950]
**Describe the bug(描述下问题)**
创建守护进程集时， 配置容器组副本数量无效，副本数量与节点数相同
For UI issues please also add a screenshot that shows the issue.

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0

**Expected behavior(预期行为)**
创建守护进程集，默认容器组副本数量为节点数，且不允许用户修改

**Comment by leoendless** [comment]
fixed
