### ISSUE TITLE
部署挂载了ReadWriteMany访问模式的存储卷后，挂载失败了，存储卷状态也不对

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#951]
1、进入项目-存储卷，创建一个ReadWriteMany多节点读写的存储卷，名称为volome8888(别名存储卷8888)，容量为351G；

2、创建一个部署，镜像为alpine，挂载步骤1中的存储卷，创建部署成功，但是存在2个pod，一个正常，一个不正常：
![image](https://user-images.githubusercontent.com/7677050/66699725-b9494f00-ed1b-11e9-8dbd-f9979961da1e.png)

3、查看步骤1中的存储卷，结果显示创建中，但是已挂载：
![image](https://user-images.githubusercontent.com/7677050/66699577-ae41ef00-ed1a-11e9-9a8d-94a94d6cb5b2.png)

4、存储卷对应的部署状态也不对，为VolumeBindingFailed：
![image](https://user-images.githubusercontent.com/7677050/66699648-4d66e680-ed1b-11e9-8ffe-a378533eb2e3.png)

**Comment by wnxn** [comment]
@mayuhope 
复现情况，deploy 的 Pod 我这都没起来，PVC 没创建出来
![屏幕快照 2019-10-14 下午5 27 40](https://user-images.githubusercontent.com/13119696/66741531-52a56c00-eea8-11e9-9d05-293795320b6c.png)

![屏幕快照 2019-10-14 下午5 29 08](https://user-images.githubusercontent.com/13119696/66741500-44efe680-eea8-11e9-8c14-dac766d9b7bd.png)

存储卷事件里显示是因为 Access Mode 不支持 ReadWriteOnce。
这里用的是 local volume 的存储类型，只能支持 ReadWriteOnce，installer 需要将 local volume storageclass 的 annotation 设置为只支持 ReadWriteOnce 的。RWO 的 local pvc 可以挂载同一个 deploy 的 2 个 pod

**Comment by pixiake** [comment]
@wnxn https://github.com/kubesphere/ks-installer/blob/79100d6b4ba4ffbfe9c5e6b91487ef337490ea5e/src/kubesphere/roles/plugins/LocalVolume/templates/openebs-lite-sc.yaml.j2#L8
