### ISSUE TITLE
项目配额管理

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#955]
* [x] cpu,mem 限制的bar拉不动
* [x] 设置pod等限制没有生效（view页面显示还是无限制，还没有测试实际效果）
* [x] pod等所在下拉框里选择项和配额view页面不一致（比如没有statefulset等）
<img width="1035" alt="Screen Shot 2019-10-12 at 10 31 55 PM" src="https://user-images.githubusercontent.com/28859385/66703012-68981d00-ed40-11e9-850b-4c6c5ca76f1a.png">

**Comment by rayzhou2017** [comment]
第二个问题确实存在，在chrome下，错误如下
<img width="1227" alt="Screen Shot 2019-10-13 at 10 00 36 AM" src="https://user-images.githubusercontent.com/28859385/66709909-5c43ac80-eda0-11e9-8f5e-0d39e08630a5.png">

**Comment by leoendless** [comment]
Fixed

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191015
