### ISSUE TITLE
打不开ns

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#956]
* [ ] 从top5进入system-workspace，然后选择kubesphere-system，点击，找不到资源
<img width="1187" alt="Screen Shot 2019-10-13 at 12 34 37 PM" src="https://user-images.githubusercontent.com/28859385/66711004-f19d6b80-edb5-11e9-8667-57f7d2e53f87.png">

**Comment by leoendless** [comment]
fixed

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191015
