### ISSUE TITLE
kubesphere安装后无法登录-Internal Server Error

### ISSUE THREAD

**Issue by 2804337402** [kubesphere/kubesphere#957]
![kubesphere登录后Internal Server Error](https://user-images.githubusercontent.com/25359798/66711330-5fe52c80-edbc-11e9-812c-fdd27016070e.png)
![kubesphere后台服务都已启动并正常工作](https://user-images.githubusercontent.com/25359798/66711331-68d5fe00-edbc-11e9-898a-983114976bde.png)
![kubesphere-ks-account-日志没有发现问题](https://user-images.githubusercontent.com/25359798/66711334-73909300-edbc-11e9-81f5-e06e880b5d56.png)
![kubesphere-apigateway-查看日志发现问题](https://user-images.githubusercontent.com/25359798/66711338-85723600-edbc-11e9-84dd-e9f7004c9c29.png)
![kubesphere_redis_log](https://user-images.githubusercontent.com/25359798/66711343-928f2500-edbc-11e9-9679-6d8715eb0901.png)
![kubesphere_openldap_log](https://user-images.githubusercontent.com/25359798/66711344-98850600-edbc-11e9-9d56-450632e0eda9.png)
![kubesphere_ks_docs_no_log](https://user-images.githubusercontent.com/25359798/66711345-9e7ae700-edbc-11e9-978b-373673f0fea4.png)
![kubesphere_ks_controller_manager](https://user-images.githubusercontent.com/25359798/66711347-a63a8b80-edbc-11e9-968d-71d12cbbc912.png)
![kubesphere_ks_console_log](https://user-images.githubusercontent.com/25359798/66711348-acc90300-edbc-11e9-9b2f-274e5cf5f7b8.png)
![kubesphere_installer_log](https://user-images.githubusercontent.com/25359798/66711353-b5213e00-edbc-11e9-8567-9503218480be.png)
![kubesphere_console_查看日志发现问题](https://user-images.githubusercontent.com/25359798/66711354-b81c2e80-edbc-11e9-98cf-7dcf1a9ca56b.png)
![centos_top_info](https://user-images.githubusercontent.com/25359798/66711355-bb171f00-edbc-11e9-8cd9-95d83447350b.png)
![centos_kernal_info](https://user-images.githubusercontent.com/25359798/66711357-bfdbd300-edbc-11e9-8592-0ae6507ac262.png)
![centos_free_info](https://user-images.githubusercontent.com/25359798/66711358-c407f080-edbc-11e9-93b0-e6e77f46ca71.png)

**Comment by zryfish** [comment]
没有 ks-apiserver 这个 pod，应该是安装失败了，可以尝试卸载ks重新装下。
重装之前建议看下kubernetes的组件是否都正常

**Comment by 2804337402** [comment]
多谢
