### ISSUE TITLE
创建devops 工程出错

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#958]
* [ ] 初装系统，enable devops，创建工程出错
<img width="1173" alt="Screen Shot 2019-10-13 at 1 43 16 PM" src="https://user-images.githubusercontent.com/28859385/66711481-7771e480-edbf-11e9-8c10-5f4ae875d53f.png">

**Comment by soulseen** [comment]
执行`kubectl -n kubesphere-devops-system get po`
看下pod状态

**Comment by rayzhou2017** [comment]
是正常的，这个bug应该能复现，环境http://139.198.14.155:30881/workspaces/ray-ws/devops
[root@ks-allinone ~]# kubectl -n kubesphere-devops-system get po
NAME                                        READY   STATUS      RESTARTS   AGE
ks-devops-db-ctrl-job-f4f42                 0/1     Completed   0          3h43m
ks-devops-db-init-job-dth6r                 0/1     Completed   0          3h43m
ks-jenkins-c6d7b7cfd-5b79s                  1/1     Running     0          3h42m
ks-sonarqube-postgresql-5c4db956d7-8tsnr    1/1     Running     0          3h43m
ks-sonarqube-sonarqube-58f8fbc89-945lb      1/1     Running     0          3h43m
s2ioperator-0                               1/1     Running     1          3h43m
uc-jenkins-update-center-7cf67f54dc-7ngfs   1/1     Running     0          3h44m

**Comment by runzexia** [comment]
在修复了，这个bug是jenkins启动过程中，update center被重启了。
导致 jenkins 插件下载安装失败。
修复使 jenkins 安装插件失败时直接退出，以进行重试

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191015
