### ISSUE TITLE
pod replica 降低的时候状态提示错误

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#959]
* [x] 如图所示，我在降低replica数量的时候显示是初始化，应该是删除中
![Screen Shot 2019-10-14 at 10 06 10 AM](https://user-images.githubusercontent.com/28859385/66726163-51ede500-ee6a-11e9-94c6-482e051f77be.png)

**Comment by leoendless** [comment]
Fixed

**Comment by rayzhou2017** [comment]
还没有fix，没有显示删除中

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191016
