### ISSUE TITLE
项目overview添加密钥和configmap

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#960]
* [ ] 既然quota有这些资源，overview page也应该展现出来
![Screen Shot 2019-10-14 at 10 41 49 AM](https://user-images.githubusercontent.com/28859385/66727040-5668cc80-ee6f-11e9-9953-6f6075d59d1c.png)

**Comment by rayzhou2017** [comment]
还有application总数

**Comment by leoendless** [comment]
@huanggze 提供下指标吧

**Comment by huanggze** [comment]
configmap 我加一下，application 计数会放在 3.0

Application CRD 监控需要改 ks下面的 controller-manager 代码。目前 ks 自身监控数据不规范 https://github.com/kubesphere/kubesphere/blob/master/pkg/apiserver/monitoring/monitoring.go#L32

后面会统一调整 ks 自己的监控指标部分
