### ISSUE TITLE
job args引号问题

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#962]
* [ ] 我run了一个job，输入参数，但感觉不对，docker输入的是echo,"hello world"，yaml里是' "hello world" '，多了一个单引号，导致日志是"hello world"，而不是 hello world，不应该有双引号吧？
![Screen Shot 2019-10-14 at 10 59 24 AM](https://user-images.githubusercontent.com/28859385/66727485-24a53500-ee72-11e9-90e8-d23e959e2b58.png)
![Screen Shot 2019-10-14 at 10 59 40 AM](https://user-images.githubusercontent.com/28859385/66727491-2b33ac80-ee72-11e9-84a3-c87dc2ff7d5f.png)
![Screen Shot 2019-10-14 at 11 01 07 AM](https://user-images.githubusercontent.com/28859385/66727493-2e2e9d00-ee72-11e9-8dc4-c041f903561b.png)

**Comment by leoendless** [comment]
Fixed

**Comment by rayzhou2017** [comment]
没有fix呀，还是老样子

**Comment by rayzhou2017** [comment]
感觉还是不对，yaml直接去掉双引号了
![Screen Shot 2019-10-15 at 3 45 50 PM](https://user-images.githubusercontent.com/28859385/66810993-dde33800-ef62-11e9-8513-758eb81efffe.png)

**Comment by rayzhou2017** [comment]
正确的行为应该是我在UI的args里填写echo,"hello world"，在yaml里应该是 
```
- echo
- "hello world"
```

**Comment by rayzhou2017** [comment]
这个地方的解析应该是按照分号解析，每个段落是一行，每行前面加一个-，至于每行用户输入什么照搬就可以了。

**Comment by leoendless** [comment]
这个是一个yaml转换库的问题，需要更改输入方式吗，

> 这个地方的解析应该是按照分号解析，每个段落是一行，每行前面加一个-，至于每行用户输入什么照搬就可以了。

这样需要添加的判断反而更多了

**Comment by rayzhou2017** [comment]
我不清楚yaml转换库具体是什么问题，我听起来应该没那么复杂，代码应该是类似这样
 words = string.split(",")
for word in words
      print "-" + word
      print newline

**Comment by rayzhou2017** [comment]
我这儿运行不了
![Screen Shot 2019-10-17 at 4 09 39 PM](https://user-images.githubusercontent.com/28859385/66990304-88409400-f0f8-11e9-8f8b-6b176ef906d0.png)
![Screen Shot 2019-10-17 at 4 09 45 PM](https://user-images.githubusercontent.com/28859385/66990325-8ecf0b80-f0f8-11e9-8b56-7e8caecec267.png)

/cc @mayuhope 帮忙复现一下

**Comment by rayzhou2017** [comment]
这个很容易复现，busybox镜像，填写args （echo,"hello world"), yaml里hello world的双引号没有了，这个执行会有问题。
![Screen Shot 2019-10-25 at 10 45 16 AM](https://user-images.githubusercontent.com/28859385/67539400-99029280-f714-11e9-99bd-eab11695c688.png)
![Screen Shot 2019-10-25 at 10 45 42 AM](https://user-images.githubusercontent.com/28859385/67539434-b8012480-f714-11e9-85d2-4556a851abff.png)

**Comment by rayzhou2017** [comment]
这个双引号就没有存下来，我输入双引号，点击对勾之后再重新编辑，双引号也不见了。

**Comment by rayzhou2017** [comment]
真是奇怪了，我job就不能正常运行 @calvinyv 你帮忙复现一下

**Comment by calvinyv** [comment]
我昨天在1028的build上面测过我们文档里面的pi打印，是不用输入引号的，只需要输入：
-Mbignum=bpi,-wle,print bpi(2000)

yaml 就会被转化为：
```        - name: perl-4n2trl  
          image: perl  
          command:  
            - perl    
          args:   
            - '-Mbignum=bpi'  
            - '-wle'  
            - print bpi(2000)  
```

**Comment by rayzhou2017** [comment]
按照上面的例子，用busybox，args，不是command测试一下，

**Comment by calvinyv** [comment]
@rayzhou2017 args 填 
```echo,"hello world"
```
没问题的
![Jietu20191030-151537](https://user-images.githubusercontent.com/28883416/67836746-5aac0f80-fb28-11e9-9bae-8484b56bfcc4.png)
![Jietu20191030-151605](https://user-images.githubusercontent.com/28883416/67836752-60095a00-fb28-11e9-95df-59093d3c4396.png)
