### ISSUE TITLE
项目概览，物理资源界面显示问题

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#964]
**Describe the bug(描述下问题)**
项目概览，物理资源界面，统计图横轴的第一个第二个时间中间无分隔。
当统计图的横轴时间秒数为0时，未显示秒数。
统计图中未显示天

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/53003665/66727842-3daee580-ee74-11e9-9b5d-a89a45b7886c.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere:2.1.0

**Expected behavior(预期行为)**
建议时间显示格式一致，增加天显示

**Comment by leoendless** [comment]
fixed

**Comment by wanjunlei** [comment]
![image](https://user-images.githubusercontent.com/53003665/66886788-3241f280-f00b-11e9-96ed-c00dc5f3ca27.png)
还是有问题
