### ISSUE TITLE
创建服务文案

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#968]
* [ ] 简单服务需要重新想一下文案
![Screen Shot 2019-10-14 at 1 32 29 PM](https://user-images.githubusercontent.com/28859385/66732529-ebc78900-ee8e-11e9-8749-b63c38726a8c.png)

**Comment by Carlosfengv** [comment]
对服务类型 进行了调整，新增自定义创建；
设计稿 zpl://screen?pid=5cbe7fbc2f55d8b73f56811b&sid=5d43f5115e3f3d88d204c548

**Comment by leoendless** [comment]
fixed

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191015
