### ISSUE TITLE
内存限额文案

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#969]
* [ ] 这个地方的内存单位好像没有限制，而且显示也不友好
![Screen Shot 2019-10-14 at 2 35 47 PM](https://user-images.githubusercontent.com/28859385/66732809-e74fa000-ee8f-11e9-8c96-fbb201b77f3d.png)

**Comment by leoendless** [comment]
Fixed

**Comment by rayzhou2017** [comment]
还没fix，依然显示巨大无比的一个数字，而且拽上面两个横条右边的bar（limit值）不是很灵敏，需要拖一个相对比较大跨度才移动。
![Screen Shot 2019-10-15 at 11 19 48 AM](https://user-images.githubusercontent.com/28859385/66797552-af9f3180-ef3d-11e9-9228-d52f93f9cc69.png)

**Comment by leoendless** [comment]
给看下你的环境

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191015
