### ISSUE TITLE
cronjob quota出错

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#970]
* [ ] 是不是cronjob quota的定义有问题？我一个cronjob都运行不了
![Screen Shot 2019-10-14 at 2 40 04 PM](https://user-images.githubusercontent.com/28859385/66732993-99876780-ee90-11e9-962c-06945cdaa6aa.png)
![Screen Shot 2019-10-14 at 2 40 11 PM](https://user-images.githubusercontent.com/28859385/66732998-9ee4b200-ee90-11e9-84e4-d6e2aa8708e6.png)
![Screen Shot 2019-10-14 at 2 40 26 PM](https://user-images.githubusercontent.com/28859385/66733003-a3a96600-ee90-11e9-8e5c-bcaec3215f41.png)

**Comment by zryfish** [comment]
cronjob会生成job，占用job配额，这个环境是不是之前创建过一个job，导致cronjob没法创建job了？

**Comment by rayzhou2017** [comment]
是的，那我感觉quota把job和cronjob分开设置不合理，既然他们是共用quota的话

**Comment by leoendless** [comment]
建议不设置 job 的配额把

**Comment by rayzhou2017** [comment]
我觉得合在一起好一些

**Comment by leoendless** [comment]
怎么合呢， 定时job 占用job, 并不是共用，cronjob还可能会占用多个job

**Comment by wansir** [comment]
job，deployment ，statefulset  等工作负载的配额会产生冲突，如果pod 配额满了， 那么工作负载实际上就无法调度了， job 和cronjob 也是同理。  k8s 中这些资源配额都是单独设置的， 如果这里和k8s 不一致的话， 会有解释成本， 所以也不建议合在一起进行设置

**Comment by zryfish** [comment]
job, pod 是从更细粒度限制配额，还是需要分开的

**Comment by rayzhou2017** [comment]
pod其实用户好理解，但job和cronjob用户看不懂的

**Comment by rayzhou2017** [comment]
verified
