### ISSUE TITLE
创建任务，选择容器镜像界面，当镜像名称包含大写字母时，默认的任务名称不合法

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#971]
**Describe the bug(描述下问题)**
创建任务，选择容器镜像界面，当镜像名称包含大写字母时，默认的任务名称是不合法的，若不展开高级设置，点击保存按钮时，是不会有错误提示的。创建其他应用负载时，有类似错误。

![image](https://user-images.githubusercontent.com/53003665/66733418-149d4d80-ee92-11e9-8604-cd1304e984c8.png)

![image](https://user-images.githubusercontent.com/53003665/66733445-2bdc3b00-ee92-11e9-9a9c-28197817f555.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere:2.1.0

**Expected behavior(预期行为)**
1.当默认的任务名称不合法时，应进行自动转换，例如大写字母转为小写字母
2.保存镜像时，若高级设置中的设置有错误，应自动展开高级设置，使用户可以看到错误提示

**Comment by minghaoye** [comment]
fixed
