### ISSUE TITLE
 删除job计数没更新

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#972]
* [x] 删除job后上面的tab页数字还是旧的，重新打开也不行
![Screen Shot 2019-10-14 at 4 12 23 PM](https://user-images.githubusercontent.com/28859385/66737050-7b743400-ee9d-11e9-9210-7d15814cd700.png)

**Comment by leoendless** [comment]
这个环境有其它 job 吗， 这里的数字是 quota 里的 used

**Comment by rayzhou2017** [comment]
是的，有job，但这个太迷惑人了，跟job/cronjob quota使用量一样的问题。

**Comment by leoendless** [comment]
感觉是 job 过滤的问题，这的计数调整成不用 quota 的吧

**Comment by leoendless** [comment]
fixed

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191017
