### ISSUE TITLE
提交应用模版审核文档url错误

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#973]
* [x] 开发者测试指南url错误
![Screen Shot 2019-10-14 at 4 16 15 PM](https://user-images.githubusercontent.com/28859385/66737243-02291100-ee9e-11e9-8704-ceb8ae702e96.png)

**Comment by whDongRui** [comment]
@FeynmanZhou ,这里“开发者测试指南”的url需要你提供一下，之前好像跟你提过一次的。

**Comment by FeynmanZhou** [comment]
已提交给 @whDongRui ，更新到 console 后请 verify 一下这个 issue

**Comment by whDongRui** [comment]
这个昨天按给的文档路径已经修复了。

**Comment by rayzhou2017** [comment]
verified
