### ISSUE TITLE
PVC状态为Bond时候，显示为更新中

### ISSUE THREAD

**Issue by bmingithub** [kubesphere/kubesphere#974]
**Describe the bug(描述下问题)**
真个在运行的PCV前端状态显示为更新中，
For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/35321102/66737382-64821180-ee9e-11e9-93f4-ac63009bf827.png)

**Expected behavior(预期行为)**
应该显示为Bound的中文翻译

**Comment by justahole** [comment]
fixed

**Comment by bmingithub** [comment]
10月24的版本，问题还是存在。 
![image](https://user-images.githubusercontent.com/35321102/67538226-2e9c2300-f711-11e9-8cd1-25c4c3ca8dba.png)
过滤选项中，状态是没有“更新中”，而且选项是不是也不齐

**Comment by justahole** [comment]
过滤选项没有这么细的粒度。

**Comment by justahole** [comment]
这是原本为了区分是否正在扩容，现在用别的方式提示了，新的代码已提交，等待刷新。

**Comment by mayuhope** [comment]
目前有等待中，准备就绪，丢失这3种状态，存储卷扩容时的状态是准备就绪。
![image](https://user-images.githubusercontent.com/7677050/68474002-5b971c80-025f-11ea-82d9-1c03533759b2.png)

**Comment by for-mat** [comment]
> 目前2.1版本有等待中，准备就绪，丢失这3种状态，存储卷扩容时的状态是准备就绪。
> ![image](https://user-images.githubusercontent.com/7677050/68474002-5b971c80-025f-11ea-82d9-1c03533759b2.png)

这种情况如何处理呢，我改了配置扩容，但是实际上容量没有变化，重启pod也没有变化
