### ISSUE TITLE
应用状态不对

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#975]
* [x] 我这个应用已经提交审核且审核通过，这个地方应该是待发布或待上架吧？
![Screen Shot 2019-10-14 at 4 21 39 PM](https://user-images.githubusercontent.com/28859385/66737511-c478b800-ee9e-11e9-96fc-8e8c5b4b1c2c.png)

**Comment by whDongRui** [comment]
应用目前只有4种状态，只有draft(待提交)，active(已上架)，suspended(已下架)，deleted(已删除)，
没有待发布或待上架的状态。

这个要支持的话得后端多设计一种应用的状态。

**Comment by wansir** [comment]
> @pengcong @zheng1 应用目前只有4种状态吧，分别为draft(待提交)，active(已上架)，suspended(已下架)，deleted(已删除)，
> 没有待发布或待上架的状态。
> 
> 这个要支持的话得后端多设计一种应用的状态。

这里应用状态是passed， 状态应该翻译为 审核通过或者是待发布

**Comment by whDongRui** [comment]
这个万宏明刚跟我说app已经有passed这种状态，我一会改一下前端的显示。

**Comment by whDongRui** [comment]
这个前端代码已经更新了，我刚才测试发现接口返回的还是没有“ passed”这种状态的应用

**Comment by whDongRui** [comment]
这个针对app已经把draft都翻译成了“开发中”
![image](https://user-images.githubusercontent.com/38676269/67175376-6dbc3280-f3f8-11e9-959b-41631d29f893.png)

**Comment by rayzhou2017** [comment]
verified
