### ISSUE TITLE
应用商店问题

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#976]
* [x] 未分类没有我刚发布的应用
![Screen Shot 2019-10-14 at 4 29 19 PM](https://user-images.githubusercontent.com/28859385/66737990-ff2f2000-ee9f-11e9-9880-8dc404cac165.png)
* [x] 提供商是system是不是不对？联系方式我好像也没地方填写，版本ID是不是最好显示出来？
![Screen Shot 2019-10-14 at 4 29 29 PM](https://user-images.githubusercontent.com/28859385/66738045-22f26600-eea0-11e9-85b4-ede8bc502e1e.png)
* [ ] 部署的时候状态没有用websocket刷新
![Screen Shot 2019-10-14 at 4 30 26 PM](https://user-images.githubusercontent.com/28859385/66738191-795fa480-eea0-11e9-9f3c-8c316b7b5f5e.png)

**Comment by whDongRui** [comment]
@zheng1 @pengcong06 第一个问题，未分类的id是“ctg-uncategorized”，但这个app返回信息category_set为空数据[]。这个需要后端在创建时给应用默认一个“未分类”的分类，前端在显示时才能过滤。

第二个问题，”提供商“，“联系方式”这两个应该应该是按OP的设计来的，感觉“提供商”可以改成“企业空间”，“联系方式”可以去掉。版本ID显示的话在哪里显示，在版本那个table列表中显示？

第三个问题，应用部署后列表没有websocket，这个跟后端沟通的结果是可能这个版本支持不了。

**Comment by Carlosfengv** [comment]
服务商 => 服务商(企业空间);
联系方式暂时去掉，以后可以完善企业空间的信息（包括ISV认证）;
显示版本ID貌似没什么用吧？

**Comment by wansir** [comment]
1. fixed https://github.com/openpitrix/openpitrix/pull/954
2. fixed #991 
3. 暂时无法支持

**Comment by rayzhou2017** [comment]
verified on 2.1.0-dev-20191018
