### ISSUE TITLE
关于devops问题请教下

### ISSUE THREAD

**Issue by Zephery** [kubesphere/kubesphere#979]
请问下：
1.kubeSphere2.1.0是否会采用jenkins x？

2.dashboard是用的vue么？devops能否从kubeSphere单独拆分出来

3.devops是否会参考阿里云云效那样做？

**Comment by runzexia** [comment]
1. 2.1.0不会采用 jenkins x
2. 暂时还不支持独立devops，2.1支持组件选装，可以安装自己需要的组件
3. kubesphere devops和云效都是devops产品，在某些功能上会有重合。目前kubesphere以容器devops为主，后期功能会逐渐丰富，如果有好的建议可以在github上提issue反馈。

**Comment by Zephery** [comment]
谢谢回答，云效的图形化，还有操作上会更好，更能理解，后期功能希望能参考云效来做吧。
