### ISSUE TITLE
定时任务执行纪录问题

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#980]
**Describe the bug(描述下问题)**
1.运行中的任务有结束时间
2.所有任务的结束时间是一样的，新的任务会刷新旧的任务的结束时间

![image](https://user-images.githubusercontent.com/53003665/66742146-9a78c300-eea9-11e9-83cb-583859c7dfe6.png)

![image](https://user-images.githubusercontent.com/53003665/66742389-17a43800-eeaa-11e9-8a17-2034bd4e951b.png)

/area console
/kind bug
/milestone 2.1.0

**Comment by minghaoye** [comment]
<img width="944" alt="Screen Shot 2019-10-15 at 4 37 08 PM" src="https://user-images.githubusercontent.com/22934997/66815051-32d67c80-ef6a-11e9-82ce-cdc9ea59bdae.png">
没有复现，可以给个环境地址么

**Comment by wanjunlei** [comment]
http://139.198.191.57:30880
admin
P@88w0rd

**Comment by wanjunlei** [comment]
http://139.198.191.57:30880

**Comment by wanjunlei** [comment]
@minghaoye http://139.198.191.57:30880
![image](https://user-images.githubusercontent.com/53003665/66904014-00925100-f036-11e9-9744-6d0e3e593e23.png)

**Comment by minghaoye** [comment]
fixed
