### ISSUE TITLE
创建定时任务时，activeDeadlineSeconds参数设置无效

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#981]
Describe the bug(描述下问题)
创建定时任务时，activeDeadlineSeconds参数设置无效

Versions used(KubeSphere/Kubernetes的版本)
KubeSphere:2.1.0

/area console
/area depoly
/kind bug
/milestone 2.1.0

**Comment by leoendless** [comment]
Fixed

**Comment by wanjunlei** [comment]
已修复
