### ISSUE TITLE
kubesphere 中devops工程流水线

### ISSUE THREAD

**Issue by redhatxl** [kubesphere/kubesphere#982]
kubesphere 中devops工程流水线中如何在发送的邮件内容中获取到{BUILD_NUMBER}  ${JOB_NAME}信息呢，想在通知邮件中体现这些信息。

**Comment by runzexia** [comment]
/area devops
/kind question
/close
参考下面的文章 https://www.cloudbees.com/blog/mail-step-jenkins-workflow

**Comment by redhatxl** [comment]
好的，谢谢
