### ISSUE TITLE
启用op后，应用商店报错

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#985]
1、修改ks-installer的cm，将op从False改为True；

2、待apiserver重启完毕后，登录界面；

3、应用商店报错：
![image](https://user-images.githubusercontent.com/7677050/66744359-d1050c80-eeae-11e9-862b-c830c962fd8e.png)

**Comment by whDongRui** [comment]
/assign @wansir 
截图中的两个提示应该是查询分类和应用信息时，这两个接口返回的错误信息，得后端帮忙看一下是什么原因导致的。

**Comment by zheng1** [comment]
看上去是安装有问题，需要检查一下db-ctrl相关的job
