### ISSUE TITLE
Kubernetes V1.16已经不再支持 apiversion “extensions/v1beta”

### ISSUE THREAD

**Issue by ChangMuChen** [kubesphere/kubesphere#989]
Kubernetes V1.16已经不再支持 apiversion “extensions/v1beta”,导致在安装的时候helm报错，是否考虑使用“apps/v1”
报错信息如下：
```
 [WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'
PLAY [localhost] ***************************************************************
TASK [download : include_tasks] ************************************************
skipping: [localhost]
TASK [download : Download items] ***********************************************
skipping: [localhost]
TASK [download : Sync container] ***********************************************
skipping: [localhost]
TASK [kubesphere-defaults : Configure defaults] ********************************
ok: [localhost] => {
    "msg": "Check roles/kubespray-defaults/defaults/main.yml"
}
TASK [ks-devops/sonarqube : ks-devops | Creating ks-jenkins webhook(external)] ***
skipping: [localhost]
TASK [ks-devops/sonarqube : ks-devops | Getting sonarqube installation files] ***
changed: [localhost]
TASK [ks-devops/sonarqube : Sonarqube | Creating manifests] ********************
changed: [localhost] => (item={u'name': u'custom-values-sonarqube', u'file': u'custom-values-sonarqube.yaml'})
TASK [ks-devops/sonarqube : Sonarqube | Deploy Sonarqube] **********************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm upgrade --install ks-sonarqube  /etc/kubesphere/sonarqube/sonarqube-0.13.5.tgz -f /etc/kubesphere/sonarqube/custom-values-sonarqube.yaml  --namespace kubesphere-devops-system\n", "delta": "0:00:01.815235", "end": "2019-10-15 00:37:32.637143", "msg": "non-zero return code", "rc": 1, "start": "2019-10-15 00:37:30.821908", "stderr": "Error: validation failed: unable to recognize \"\": no matches for kind \"Deployment\" in version \"extensions/v1beta1\"", "stderr_lines": ["Error: validation failed: unable to recognize \"\": no matches for kind \"Deployment\" in version \"extensions/v1beta1\""], "stdout": "Release \"ks-sonarqube\" does not exist. Installing it now.", "stdout_lines": ["Release \"ks-sonarqube\" does not exist. Installing it now."]}
PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0   
```

**Comment by rayzhou2017** [comment]
这个需要等helm的支持吧

**Comment by zryfish** [comment]
KubeSphere 目前不支持 k8s v1.16 ，这个不仅需要 helm 更新，还需要对应的 charts 更新，需要等一段时间

**Comment by ChangMuChen** [comment]
> KubeSphere 目前不支持 k8s v1.16 ，这个不仅需要 helm 更新，还需要对应的 charts 更新，需要等一段时间

你说的对，我正在期待有其他的方案

**Comment by zryfish** [comment]
@ChangMuChen https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals 你可以按照这个建议，重新启用下这几组API，然后再安装KubeSphere

**Comment by Akdie** [comment]
kubernetes v1.15.3同样的问题

[root@k8s-kubespray-master-0 deploy]# kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l job-name=kubesphere-installer -o jsonpath='{.items[0].metadata.name}') -f
 [WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'

PLAY [localhost] ***************************************************************

TASK [download : include_tasks] ************************************************
skipping: [localhost]

TASK [download : Download items] ***********************************************
skipping: [localhost]

TASK [download : Sync container] ***********************************************
skipping: [localhost]

TASK [kubesphere-defaults : Configure defaults] ********************************
ok: [localhost] => {
    "msg": "Check roles/kubespray-defaults/defaults/main.yml"
}

TASK [ks-devops/sonarqube : ks-devops | Creating ks-jenkins webhook(external)] ***
skipping: [localhost]

TASK [ks-devops/sonarqube : ks-devops | Getting sonarqube installation files] ***
changed: [localhost]

TASK [ks-devops/sonarqube : Sonarqube | Creating manifests] ********************
changed: [localhost] => (item={u'name': u'custom-values-sonarqube', u'file': u'custom-values-sonarqube.yaml'})

TASK [ks-devops/sonarqube : Sonarqube | Deploy Sonarqube] **********************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/helm upgrade --install ks-sonarqube  /etc/kubesphere/sonarqube/sonarqube-0.13.5.tgz -f /etc/kubesphere/sonarqube/custom-values-sonarqube.yaml  --namespace kubesphere-devops-system\n", "delta": "0:00:00.754018", "end": "2019-10-25 17:51:18.092323", "msg": "non-zero return code", "rc": 1, "start": "2019-10-25 17:51:17.338305", "stderr": "Error: UPGRADE FAILED: configmaps is forbidden: User \"system:serviceaccount:kube-system:default\" cannot list resource \"configmaps\" in API group \"\" in the namespace \"kube-system\"", "stderr_lines": ["Error: UPGRADE FAILED: configmaps is forbidden: User \"system:serviceaccount:kube-system:default\" cannot list resource \"configmaps\" in API group \"\" in the namespace \"kube-system\""], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=1    skipped=4    rescued=0    ignored=0

[root@k8s-kubespray-master-0 deploy]# kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
