### ISSUE TITLE
删除devops工程凭证时，确认语中的名称不正确

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#995]
1、新建一个devops工程，新建一个凭证kubeconfig；

2、删除该凭证，结果确认提示语中名称是undefined(见下图)，导致的结果是必须输入undefined才能删除：

![image](https://user-images.githubusercontent.com/7677050/66805394-7d9ac900-ef57-11e9-8fec-1ce9b965ea00.png)

**Comment by minghaoye** [comment]
fixed

**Comment by mayuhope** [comment]
经验证已修复
