### ISSUE TITLE
安装时停止在某一过程中，无报错无信息

### ISSUE THREAD

**Issue by 2young2simple** [kubesphere/kubesphere#997]
**问题描述**
使用以下命令安装 KubeSphere Advanced Edition 2.0.2 ，使用 All-in-one 模式
```
$ curl -L https://kubesphere.io/download/stable/advanced-2.0.2 > advanced-2.0.2.tar.gz && tar -zxf advanced-2.0.2.tar.gz && cd kubesphere-all-advanced-2.0.2/scripts
$ ./install.sh
```
使用安装时每次停留在这行 
```
TASK [download : container_download | Download containers if pull is required or told to alwags pull (all nodes)] ***
```
安装了3次均停在这个位置不进行下去， 等待了1个小时以上...不知道是哪有问题，有哪里可以看到一些具体原因吗？ 或者详细的下载信息

**安装环境的硬件配置**

VMware虚拟机/Centos 7.4/全新环境
2Cpu   8G内存  20G存储 

**错误信息或截图**

![image](https://user-images.githubusercontent.com/7031722/66805950-dd45a400-ef58-11e9-94fc-b07589209500.png)

**Installer版本**

 KubeSphere Advanced Edition 2.0.2

**Comment by zryfish** [comment]
这一步是下载安装所需镜像的步骤，根据网络状况的不同，这一步所花的时间不同，建议安装前将网络带宽临时调大
