### ISSUE TITLE
workspace-regular用户创建的项目名称为undefined

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#998]
**Describe the bug(描述下问题)**
用户角色为cluster-regular，项目角色为workspace-regular，创建项目时，项目名称显示为undefined

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/53003665/66806540-63aeb580-ef5a-11e9-8684-a9cd59565062.png)

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere:2.1.0

/area console
/kind bug
/milestone 2.1.0

**Comment by leoendless** [comment]
fixed
