### ISSUE TITLE
流水线活动页面空白

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#999]
![image](https://user-images.githubusercontent.com/7677050/66806913-3dd5e080-ef5b-11e9-91e3-e68089ab43d1.png)

点击上图的活动，结果页面空白：
![image](https://user-images.githubusercontent.com/7677050/66806931-4201fe00-ef5b-11e9-8f69-52afefa7b9c5.png)

**Comment by minghaoye** [comment]
fixed

**Comment by mayuhope** [comment]
已验证
